- pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
- pdns/dnsdistdist/dnsdist-lua-ffi.cc
This PR could use unit and regression tests.
I have:
> dnsdist: Add Lua FFI helpers for protocol and MAC address access, proxy protocol payload generation

- .github/actions/spell-check/expect.txt
- pdns/dnsdistdist/docs/reference/config.rst
> dnsdist: docs for newThread&friends

- docs/appendices/EOL.rst
- pdns/dnsdistdist/docs/eol.rst
> auth/dnsdist: update EOL docs

- .github/actions/spell-check/expect.txt
- docs/lua-records/functions.rst
- pdns/lua-record.cc
- regression-tests.auth-py/test_LuaRecords.py
> auth LUA: add ifurlextup function

- pdns/recursordist/docs/metrics.rst
- pdns/recursordist/docs/performance.rst
This is a start, have to think if more needs to be added.
Fixes the rec part of #11238
I have:
> rec: Elaborate on TCP and OOO

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.target.centos-7
- builder-support/dockerfiles/Dockerfile.target.centos-8
- builder-support/dockerfiles/Dockerfile.target.el-7
- builder-support/dockerfiles/Dockerfile.target.el-7-amd64
- builder-support/dockerfiles/Dockerfile.target.el-8
- builder-support/dockerfiles/Dockerfile.target.el-8-amd64
- builder-support/dockerfiles/Dockerfile.target.el-8-arm64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-amd64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-arm64
> rec-4.6.x: builder: migrate EL8 builds to oraclelinux, rename centos8 to el8 where possible

- pdns/tcpiohandler.cc
- regression-tests.dnsdist/test_OutgoingDOH.py
- regression-tests.dnsdist/test_OutgoingTLS.py
> dnsdist: Set Server Name Indication on outgoing TLS connections (DoT, DoH)

- docs/requirements.txt
- pdns/dnsdistdist/docs/requirements.txt
- pdns/recursordist/docs/requirements.txt
> dnsdist-1.5.x: Pin docutils to < 0.18 for now

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.target.centos-7
- builder-support/dockerfiles/Dockerfile.target.centos-8
- builder-support/dockerfiles/Dockerfile.target.el-7
- builder-support/dockerfiles/Dockerfile.target.el-7-amd64
- builder-support/dockerfiles/Dockerfile.target.el-8
- builder-support/dockerfiles/Dockerfile.target.el-8-amd64
- builder-support/dockerfiles/Dockerfile.target.el-8-arm64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-amd64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-arm64
> dnsdist-1.6.x: builder: migrate EL8 builds to oraclelinux, rename centos8 to el8 where possible

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.target.centos-7
- builder-support/dockerfiles/Dockerfile.target.centos-8
- builder-support/dockerfiles/Dockerfile.target.el-7
- builder-support/dockerfiles/Dockerfile.target.el-7-amd64
- builder-support/dockerfiles/Dockerfile.target.el-8
- builder-support/dockerfiles/Dockerfile.target.el-8-amd64
- builder-support/dockerfiles/Dockerfile.target.el-8-arm64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-amd64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-arm64
> auth-4.6.x: builder: migrate EL8 builds to oraclelinux, rename centos8 to el8 where possible

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.target.centos-7
- builder-support/dockerfiles/Dockerfile.target.centos-8
- builder-support/dockerfiles/Dockerfile.target.el-7
- builder-support/dockerfiles/Dockerfile.target.el-7-amd64
- builder-support/dockerfiles/Dockerfile.target.el-8
- builder-support/dockerfiles/Dockerfile.target.el-8-amd64
- builder-support/dockerfiles/Dockerfile.target.el-8-arm64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-amd64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-arm64
> auth-4.5.x: builder: migrate EL8 builds to oraclelinux, rename centos8 to el8 where possible

- builder-support/dockerfiles/Dockerfile.target.el-7
- builder-support/dockerfiles/Dockerfile.target.el-8
- builder-support/dockerfiles/Dockerfile.target.el-8-amd64
- builder-support/dockerfiles/Dockerfile.target.el-8-arm64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-amd64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-arm64
> auth-4.4.x: builder: migrate EL8 builds to oraclelinux, rename centos8 to el8 where possible

- builder-support/dockerfiles/Dockerfile.target.el-7
- builder-support/dockerfiles/Dockerfile.target.el-8
- builder-support/dockerfiles/Dockerfile.target.el-8-amd64
- builder-support/dockerfiles/Dockerfile.target.el-8-arm64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-amd64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-arm64
> rec-4.4.x: builder: migrate EL8 builds to oraclelinux, rename centos8 to el8 where possible

- builder-support/dockerfiles/Dockerfile.target.el-7
- builder-support/dockerfiles/Dockerfile.target.el-8
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
> dnsdist-1.5.x:  builder: migrate EL8 builds to oraclelinux, rename centos8 to el8 where possible

- docs/lua-records/functions.rst
> auth docs: clarify that filterForward is new in 4.5.0 and fix example

- Dockerfile-dnsdist
> dnsdist Docker image: install ca-certificates

- Dockerfile-dnsdist
> dnsdist 1.7.x Docker image: install ca-certificates

- build-scripts/docker/repo-test/generate-repo-files.py
- build-scripts/docker/repo-test/templates/Dockerfile-el.jinja2
> repo-test: add el 8 target, using oracle linux

- pdns/dnsname.hh
- pdns/dnswriter.hh
- pdns/misc.hh
Just a small cleanup :)
I have:
> Remove unused 'deque' include, and the declaration of segmentDNSName

- pdns/dns.cc
- pdns/dns.hh
- pdns/pdns_recursor.cc
- pdns/test-dnsname_cc.cc
it instead of letting a worker do that
I have:
> rec: Detect a malformed question early so we can drop it asap

- modules/lmdbbackend/lmdbbackend.hh
> auth lmdb: default values for KeyDataDB members, thanks ubsan

- modules/geoipbackend/geoipbackend.cc
- pdns/dnscrypt.cc
- pdns/dnspcap.hh
- pdns/dnsrecords.cc
- pdns/dnsscope.cc
- pdns/dynlistener.cc
- pdns/filterpo.cc
- pdns/iputils.cc
- pdns/minicurl.cc
- pdns/misc.cc
- pdns/namespaces.hh
- pdns/rcpgenerator.cc
- pdns/responsestats.cc
- pdns/sillyrecords.cc
- pdns/ws-api.cc
Only include it where used
I have:
> Remove include boost/format.hpp from namespaces.hh 

- pdns/lwres.cc
- pdns/resolve-context.hh
- pdns/syncres.cc
- pdns/syncres.hh
In the forwarding case, it is not available until we have a better config language)
I have:
> rec: Add SNI to DoT if available

- pdns/recursordist/rec-main.cc
This is much more clean and easier and enables a lot more freedom
to have different periods or threads for different tasks, though
that freedom is not used yet.
I have:
> rec: Replace manual maintainance of periodic tasks by an OO approach.

- builder-support/specs/dnsdist.spec
- builder-support/specs/pdns-recursor.spec
- builder-support/specs/pdns.spec
> el7 builds: switch to boost 1.69

- pdns/recursordist/ednsextendederror.cc
> rec: Add missing 'limits' include in ednsextendederror.cc

- docs/backends/lmdb.rst
- ext/lmdb-safe/lmdb-typed.cc
- ext/lmdb-safe/lmdb-typed.hh
- modules/lmdbbackend/lmdbbackend.cc
- modules/lmdbbackend/lmdbbackend.hh
- regression-tests.nobackend/lmdb-id-generation/command
- regression-tests.nobackend/lmdb-id-generation/description
- regression-tests.nobackend/lmdb-id-generation/expected_result
> auth lmdb: add random ID generation feature

- pdns/svc-records.cc
> Add a missing white-space in SvcParam::keyFromString()

- build-scripts/docker/repo-test/generate-repo-files.py
> Add auth-47 to repo test script.

- docs/changelog/4.7.rst
- docs/changelog/index.rst
- docs/secpoll.zone
> auth-4.7.0-alpha1: changelog & secpoll

- pdns/pdns_recursor.cc
- regression-tests.recursor-dnssec/test_Lua.py
When following a CNAME as indicated by `dq.followupFunction = "followCNAMERecords"` the result might need to be post processed for native dns64 purposes.
Should fix #11320.
There are many ways to influence query results. The interaction between these methods is complex and should be revisited one day. At the moment it feels like to much code is duplicated but we still are missing cases.
I have:
> Rec: followCNAME and native dns64

- docs/backends/lmdb.rst
- ext/lmdb-safe/lmdb-safe.cc
- ext/lmdb-safe/lmdb-safe.hh
- modules/lmdbbackend/lmdbbackend.cc
- pdns/dnsdistdist/dnsdist-kvs.hh
- pdns/dnsdistdist/test-dnsdistkvs_cc.cc
> auth lmdb: make map size configurable

- pdns/tcpiohandler.cc
> dnsdist: Remove the leak warning with GnuTLS >= 3.7.3

- pdns/dnsdist-web.cc
- pdns/dnsdist.cc
- pdns/dnsdist.hh
- pdns/dnsdistdist/docs/statistics.rst
- pdns/dnsdistdist/test-dnsdisttcp_cc.cc
> dnsdist: Fix the latency-count metric

- pdns/pdns_recursor.cc
- pdns/recursor_cache.cc
- pdns/recursordist/rec-taskqueue.cc
- pdns/recursordist/rec-tcp.cc
- pdns/syncres.hh
> rec: QType ADDR is supposed to be used internally only.

- README.md
> Update README.md for c++17 support

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.7.rst
- pdns/recursordist/docs/changelog/index.rst
- pdns/recursordist/docs/lua-config/additionals.rst
- pdns/recursordist/docs/upgrade.rst
> rec: Prep for rec-4.7.0-alpha1

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.target.ubuntu-jammy
> rec: Backport 11199 to rec 4.6.x: add ubuntu jammy build target

- pdns/lwres.cc
> rec: Backport 11257 to rec 4.6.x: Initialize isNew before calling a exception throwing function

- pdns/pdns_recursor.cc
- pdns/recursordist/docs/settings.rst
- pdns/recursordist/docs/upgrade.rst
- pdns/recursordist/test-syncres_cc.cc
- pdns/reczones.cc
- pdns/syncres.cc
- pdns/syncres.hh
Backport of #11283
Once this is is, we have to adapt the docs in the main branch (settings and upgarde guide) to refer to the right version.
I have:
> rec: Backport 11283 to rec 4.6.x: Allow disabling of processing the root hints

- pdns/syncres.cc
> rec: string::find(char) returns a size_type, not a boolean; coverity CID 1475294

- pdns/pdns_recursor.cc
> rec: Backport of 11300 to rec-4.6.x: Use the Lua context stored in SyncRes when calling hooks

- pdns/pdns_recursor.cc
> Backport of 11300 to rec-4.5.x: Use the Lua context stored in SyncRes when calling hooks

- .circleci/config.yml
- regression-tests.recursor-dnssec/recursortests.py
- regression-tests.recursor/config.sh
> rec: Backport 11044 to rec 4.5.x: Fix v6 test setup and start using a more modern auth on circleci

- .circleci/config.yml
- regression-tests.recursor-dnssec/recursortests.py
- regression-tests.recursor/config.sh
> rec: Backport 11044 to rec 4.4.x: Fix v6 test setup and start using a more modern auth on circleci

- builder-support/debian/authoritative/debian-buster/tests-source/launch-pdns
> auth deb test: upstream more lenient startup wait

- pdns/dnsdist.cc
> dnsdist: Properly release UDP states when using random IDs

- pdns/dnsdist.cc
> dnsdist: The check interval applies to health-check, not timeouts

- pdns/dnsdist.cc
- pdns/dnsdistdist/docs/manpages/dnsdist.1.rst
- pdns/dnsdistdist/test-dnsdistlbpolicies_cc.cc
- pdns/dolog.hh
- pdns/logger.cc
- pdns/test-dnscrypt_cc.cc
> dnsdist: add --log-timestamps flag

- modules/gpgsqlbackend/gpgsqlbackend.cc
> Fix query description to say "first" when searching for first ordername.

- pdns/common_startup.cc
- pdns/distributor.hh
- pdns/tcpreceiver.cc
- pdns/test-distributor_hh.cc
and add a more detailed latency metrics
I have:
> auth: fix proxy protocol query statistics

- build-scripts/docker/repo-test/generate-repo-files.py
> Add rec-47 to repo test script.

- docs/http-api/swagger/authoritative-api-swagger.yaml
- pdns/ws-auth.cc
- regression-tests.api/test_Zones.py
> auth API: fetch individual rrsets

- docs/domainmetadata.rst
I think the intended word here is "record" :)
I have:
> Fix small typo in docs/domainmetadata.rst, s/recording/record/

- pdns/dnsdist-lua.cc
> dnsdist: more useful default ports for DoT/DoH backends

- pdns/recursordist/rec-main.cc
> rec: Wrong task was used to clean outgoing TCP

- .github/actions/spell-check/expect.txt
- docs/guides/algoroll.rst
- docs/guides/index.rst
> auth docs: add algorithm rolling guide

- build-scripts/changelog-from-pr.py
- build-scripts/git-to-changelog-merges
Add my username to changelog scripts
I have:
> Add `fredmorcos` to changelog scripts

- .clang-tidy.bugs
- .clang-tidy.full
- contrib/pdnsutil.bash_completion.d
- docs/manpages/pdnsutil.1.rst
- pdns/dnssecinfra.cc
- pdns/dnssecinfra.hh
- pdns/dynloader.cc
- pdns/misc.cc
- pdns/misc.hh
- pdns/opensslsigners.cc
- pdns/pdnsutil.cc
- pdns/pkcs11signers.hh
- pdns/test-signers.cc
Add support for importing and exporting ECDSA keys from/to PEM
I have:
> Import and export of ECDSA keys from/to PEM

- docs/guides/algoroll.rst
- docs/guides/kskroll.rst
> auth docs: fix typo in RFC number

- pdns/syncres.cc
> rec: Backport 11376 to rec 4.6.x: Be more careful using refresh mode only for the record asked

- pdns/opensslsigners.cc
Enable named curves on ECDSA key generation and import from ISC
I have:
> Enable named curves on ECDSA key generation and import from ISC

- pdns/doh.hh
> dnsdist: fix build on MacOS and OpenBSD: include <unordered_map>

- pdns/recursordist/docs/http-api/endpoint-servers-config.rst
- pdns/recursordist/docs/lua-config/proxymapping.rst
- pdns/recursordist/docs/settings.rst
- pdns/recursordist/docs/upgrade.rst
Plus  assorted typos. Fixes #11439
I have:
> rec: Note that api-config-dir and include-dir should be the same for updates via REST to work

- pdns/syncres.cc
- pdns/syncres.hh
This is part of a grand scheme to reduce the size and provide better encapsulation for `SyncRes`. I started a branch doing everything, but that got out of hand, so now I'm doing it t step by step.
Changing more tables to be shared instead of thread local is part of the plan.
I have:
> rec: Move implemenation of failed and non-resolving table to .cc file

- builder-support/dockerfiles/Dockerfile.target.el-7
- builder-support/dockerfiles/Dockerfile.target.el-8
- builder-support/dockerfiles/Dockerfile.target.el-8-amd64
- builder-support/dockerfiles/Dockerfile.target.el-8-arm64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-amd64
- builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-arm64
- pdns/ixfr.cc
- regression-tests.auth-py/requirements.txt
- regression-tests.auth-py/runtests
- regression-tests.auth-py/test_XFRIncomplete.py
- regression-tests.ixfrdist/requirements.txt
- regression-tests.recursor-dnssec/test_RPZIncomplete.py
> Rec 4.4.x: Fix a case where an incomplete read caused by network error might result in a truncated zone

- .github/actions/spell-check/expect.txt
> spelling: add missed words

- pdns/pdns_recursor.cc
> rec: Only log "Unable to send NOD lookup" if log-comnon-errors is set

- docs/changelog/4.4.rst
- docs/changelog/4.5.rst
- docs/changelog/4.6.rst
- pdns/recursordist/docs/changelog/4.4.rst
- pdns/recursordist/docs/changelog/4.5.rst
- pdns/recursordist/docs/changelog/4.6.rst
> Fill in PR#s for Security Advisory 2022-01

- pdns/.gitignore
- pdns/lwres.cc
- pdns/pdns_recursor.cc
- pdns/recpacketcache.cc
- pdns/recursordist/rec-main.cc
- pdns/recursordist/test-syncres_cc1.cc
- pdns/rpzloader.cc
- pdns/sillyrecords.cc
No real bug uncovered, but some dead code eliminated, an `assert` added and a declaration made `const`. All sensible things to do. Two cases that are false positives (AFAIKS) remain.
I have:
> Rec: scanbuild fixes

- contrib/_pdnsutil.zsh_completion
Zsh completion script for pdnsutil, incl. completion of subcommands, zones and tsig keys (bare with me, my first completion script ever)
I have:
> auth: zsh completion script for pdnsutil

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.target.ubuntu-jammy
> auth-4.6.x: add Ubuntu jammy target

- .github/actions/spell-check/expect.txt
- docs/lua-records/functions.rst
- pdns/lua-record.cc
- regression-tests.auth-py/test_LuaRecords.py
> auth 4.6.x LUA: add ifurlextup function

- pdns/common_startup.cc
- pdns/distributor.hh
- pdns/tcpreceiver.cc
- pdns/test-distributor_hh.cc
> auth-4.6.x: fix proxy protocol query statistics and add more detailed latency metrics

- pdns/syncres.cc
> rec: Backport 11376 to rec 4.5.x: Be more careful using refresh mode only for the record asked

- ext/lmdb-safe/lmdb-safe.cc
- ext/luawrapper/include/LuaContext.hpp
> Fix a couple of static analysis warnings

- pdns/recursordist/rec-main.cc
There still is a race, but this is better than calling `sd_notify` before the handler is created.
I have:
> rec: In the handler, call sd_notify just befere entering the main loop in RecursorThread

- pdns/recursordist/docs/lua-scripting/ffi.rst
- pdns/recursordist/docs/lua-scripting/hooks.rst
Plus fix a formatting issue in policyEventFilter docs.
I have:
> rec: postresolve_ffi docs

- pdns/syncres.cc
This changes to timestamp printing to only print relevant fields: year and day of week are not useful in this context. Also make the  sortable if needed using e.g. `... - | sort -k3`
Compare:
```
; edns from thread follows
;
192.5.6.30      1       Wed Mar 23 13:34:38 2022
192.31.80.30    1       Wed Mar 23 13:34:38 2022
192.42.93.30    1       Wed Mar 23 13:34:39 2022
192.52.178.30   1       Wed Mar 23 13:34:39 2022
```
to
```
; edns from thread follows
;
192.5.6.30      1       03-23T13:33:36
192.55.83.30    1       03-23T13:33:36
192.42.93.30    1       03-23T13:33:36
192.41.162.30   1       03-23T13:33:37
```
I have:
> rec: Use nice format for timestamp printing

- pdns/dnsrecords.cc
- pdns/lwres.cc
- pdns/misc.cc
- pdns/recpacketcache.cc
- pdns/recpacketcache.hh
- pdns/recursor_cache.hh
- pdns/recursordist/rec-main.cc
- pdns/rpzloader.cc
- pdns/syncres.hh
> Bunch of Coverity fixes 

- ext/luawrapper/include/LuaContext.hpp
Catch any exception that might be thrown when (copy) constructing an object.
As the push method is declared `noexcept` we cannot have that.
If this is acceptable we should upstream it I suppose.
I have:
> Coverity: 1419402 Uncaught exception in LuaWrapper

- docs/dnsupdate.rst
> auth docs: fix typo in dnsupdate doc, thanks Carsten Strotmann

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.5.rst
- pdns/recursordist/docs/changelog/4.6.rst
- pdns/recursordist/docs/upgrade.rst
Prep for rec 4.5.9 and 4.6.2 release.
I have:
> Prep for 4.5.9 and 4.6.2 releases

- pdns/iputils.hh
- pdns/misc.cc
With these three we no longer have outstanding coverity issues.
Check the commit message of the 2nd commit for some background info.
Once this is in, I plan to
- see if adding a model would reduce the amount of false positives. In particular, coverity has some issues understanding passing pointer values through pipes and sees those as leaks.
- review closed reports to see if we might have dismissed reports wrongly
I have:
> Rec: three more coverity cases: 1487743, 1419403 and 1419401

- pdns/packetcache.hh
> Another case of unaligned access of header data found by ubsan on OpenBSD

- pdns/iputils.hh
Coverity 1487850 Uncaught exception
Coverity 1487851 Uncaught exception
I have:
> followup on #11509: copyTree() also throws a std::logic_exception on internal inconsistencies

- pdns/pdns_recursor.cc
- pdns/rec-lua-conf.cc
- pdns/rec-lua-conf.hh
- pdns/recursordist/docs/lua-config/proxymapping.rst
- pdns/recursordist/docs/lua-scripting/dnsname.rst
- pdns/recursordist/rec-tcp.cc
- regression-tests.recursor-dnssec/test_Protobuf.py
Followup on #11396 
It turns out there needs to be another condition on which to let the mapping depend: the name queried.
As a bonus, fix some small issues in the `DNS Suffix Match Group` docs.
ping @neilcook 
I have:
- [X ] compiled this code
> Rec: proxy by table per domain queried

- docs/changelog/4.6.rst
- docs/secpoll.zone
> auth-4.6.2: changelog + secpoll

- pdns/dnsdistdist/docs/advanced/ebpf.rst
> Mention addCapabilitiesToRetain in eBPF docs.

- regression-tests.recursor-dnssec/test_Protobuf.py
> rec: Zap a leftover debug lines in test code

- .circleci/config.yml
> rec: enable a few more optional parts for coverity build

- pdns/syncres.cc
> Fix Coverity 1487923 Out-of-bounds read (wrong use of sizeof)

- pdns/syncres.cc
> rec: Backport 11536 to rec 4.7.x: Fix Coverity 1487923 Out-of-bounds read (wrong use of sizeof) 

- .github/actions/spell-check/expect.txt
- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.7.rst
- pdns/recursordist/docs/settings.rst
- pdns/recursordist/docs/upgrade.rst
> rec: Prep for rec-4.7.0-beta1

- tasks.py
Adds libdecaf (auth) tests to Github Actions.
I have:
> Add libdecaf (auth) tests to Github Actions

- pdns/dnsdist-cache.cc
- pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
And make sure that we cannot create such an object.
Fixes #11383.
I have:
> dnsdist: Raise the number of entries in a packet cache to at least 1

- regression-tests.recursor-dnssec/test_Protobuf.py
(cherry picked from commit ae901eb52569bc9eca6c4e871a3fc808c7e19002)
Backport of #11529 
I have:
> rec: Backport of #11529: Zap a leftover debug line in test code

- pdns/syncres.cc
> rec: Backport 11541 to rec 4.7.x: fix DoT port for probed authoritative servers

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.target.ubuntu-jammy
- pdns/bpf-filter.cc
- pdns/dnsdist-cache.cc
- pdns/dnsdist-lua-bindings.cc
- pdns/dnsdist-lua.cc
- pdns/dnsdist-tcp.cc
- pdns/dnsdist-web.cc
- pdns/dnsdist.cc
- pdns/dnsdist.hh
- pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
- pdns/dnsdistdist/dnsdist-tcp-downstream.hh
- pdns/dnsdistdist/docs/reference/config.rst
- pdns/dnsdistdist/docs/statistics.rst
- pdns/dnsdistdist/doh.cc
- pdns/dnsdistdist/test-dnsdisttcp_cc.cc
- pdns/dnsname.hh
- pdns/dnssecinfra.hh
- pdns/iputils.hh
- pdns/misc.hh
- pdns/tcpiohandler.cc
- regression-tests.dnsdist/test_OutgoingDOH.py
- regression-tests.dnsdist/test_OutgoingTLS.py
This PR backports commits from the following pull requests to rel/dnsdist-1.7.x: #11176 #11197 #11199 #11251 #11253 #11255 #11323 #11324 #11545 #11546 #11547 #11565
I have:
> dnsdist-1.7.x: Backports for 1.7.1

- .github/workflows/codeql-analysis.yml
This might fix the occasional build issues with the CodeQL GH Action.
I have:
> rec: Reduce make -j parameter from 8 to 4 for CodeQL action, as dnsdist does.

- pdns/dnsdist.cc
Backport of #11375 to rel/dnsdist-1.7.x
I have:
> dnsdist-1.7.x: The check interval applies to health-check, not timeouts

- pdns/dnsdist.cc
The existing message keeps confusing users, so it had to go :)
I have:
> dnsdist: Better log message when no downstream server are available

- docs/secpoll.zone
- pdns/dnsdistdist/docs/changelog.rst
> dnsdist: ChangeLog and secpoll update for dnsdist 1.7.1

- pdns/pdns_recursor.cc
> rec: Backport of 11496 to rec-4.6.x: Prevent segfault with empty allow-from-file and allow-from options

- pdns/dnsdist-lua.cc
- pdns/dnsdist-web.cc
- pdns/dnsdistdist/dnsdist-web.hh
- pdns/dnsdistdist/docs/reference/config.rst
- regression-tests.dnsdist/test_API.py
> dnsdist: Add an option for unauthenticated access to the API

- regression-tests.recursor-dnssec/test_Protobuf.py
It can happen the root updating houskeeping code has not run yet when processing the first quey.
In that case, we do not have root DNSKEY records in cache.  When validating the
answer, rec will then go out and fetch those, so no real issue, apart form
the fact that it interferes with our expected outgoing protobuf messages.
Same make sure the root DNSKEY records are cached before doing the actual test query.
I also looked into avoid the race in the startup code, but that is not easy to do.
I have:
> rec: Avoid a race in test code between processing the first query and the priming code

- pdns/anadns.hh
- pdns/dnsreplay.cc
- pdns/ixplore.cc
- pdns/signingpipe.cc
- pdns/zonemd.cc
> auth: Set of Coverity fixes

- pdns/opensslsigners.cc
- pdns/test-signers.cc
> RSA PEM import/export

- pdns/dnsdist-console.cc
Reported by Coverity as CID 378254.
I have:
> dnsdist: Remove dead code in the console

- regression-tests.auth-py/test_XFRIncomplete.py
After adding debug lines I think I have fixed the race. I'll leave the debug lines in for the moment, maybe there's more than one race.
I have:
> Auth: fix race in incomplete xfr test

- pdns/dnsdistdist/docs/upgrade_guide.rst
> dnsdist: Fix formatting issues in the upgrade guide

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.7.rst
- pdns/recursordist/docs/upgrade.rst
> Prep for rec-4.7.0-rc1

- pdns/recursordist/docs/lua-scripting/dnsrecord.rst
- pdns/recursordist/docs/lua-scripting/dq.rst
> rec: Document a few missing DNSQuestion attributes

- pdns/dnsdist-lua-inspection.cc
- pdns/dnsdist-rings.cc
>  dnsdist: remove implicit type conversion

- pdns/recursordist/docs/lua-config/rpz.rst
- pdns/recursordist/docs/lua-scripting/dq.rst
- pdns/recursordist/docs/manpages/pdns_recursor.1.rst
- pdns/recursordist/docs/manpages/rec_control.1.rst
Also
- don't include local refs, they end up wrong in the man page. Replace them by URLs.
- add links to general docs on both maual pages.
I have:
- [X compiled this code
> Clarify naming of RPZ zones loaded by rpzFile.

- builder-support/debian/authoritative/debian-buster/rules
- builder-support/specs/pdns.spec
tested on el7 and debian buster.
I have:
> auth packaging: add DoT support to sdig

- pdns/arguments.cc
Plus a tweak in the associated structured logging.
I have:
> rec: Deprecation warning for XPF settings.

- docs/upgrading.rst
It was a little unclear that it doesn't apply to something like 4.2.0-beta2.
I have:
> auth: Clarify 4.3.0 upgrade note

- docs/secpoll.zone
- pdns/recursordist/docs/appendices/EOL.rst
- pdns/recursordist/docs/changelog/4.7.rst
> Rec: prep 4.7.0

- pdns/arguments.hh
- pdns/pdns_recursor.cc
- pdns/rec-lua-conf.cc
- pdns/recursordist/logr.hh
- pdns/recursordist/rec-main.cc
- pdns/recursordist/rec-main.hh
- pdns/recursordist/rec-tcp.cc
- pdns/recursordist/rec-zonetocache.cc
- pdns/reczones.cc
- pdns/rpzloader.cc
- pdns/secpoll-recursor.cc
- pdns/secpoll-recursor.hh
- pdns/syncres.cc
- pdns/syncres.hh
- pdns/validate-recursor.cc
- pdns/validate-recursor.hh
Logging for houskeeping function plus introducing a name for the often used `const std::shared_ptr<Logr::Logger>&` type.
I have:
> rec: Structured logging for housekeeping

- pdns/dnsdist.cc
Backport of #11437 to rel/dnsdist-1.7.x.
When health-checking is disabled, or when a check delay longer than one second is used, there is no need to allocate a new multiplexer object every second.
(cherry picked from commit 017337515725264173e4d1f254bc0a19e4da6f4a)
I have:
> dnsdist-1.7.x: Only allocate the health-check mplexer when needed

- pdns/dnsdist.cc
Backport of #11577 to rel/dnsdist-1.7.x
I have:
> dnsdist-1.7: Scan the UDP buckets only when we have outstanding queries

- regression-tests.dnsdist/runtests
- regression-tests.recursor-dnssec/runtests
> protobuf: use python implementation during tests

- docs/secpoll.zone
> rec: Update secpoll status for 4.4.8, missed on 4.7.0 release

- regression-tests.dnsdist/runtests
- regression-tests.recursor-dnssec/runtests
Backport of #11658 to rel/dnsdist-1.7.x
I have:
> dnsdist-1.7.x: protobuf: use python implementation during tests

- pdns/dnsdist-web.cc
- regression-tests.dnsdist/test_API.py
> dnsdist: Add the protocol (Do53, DoT, DoH, ...) of backends in the API

- pdns/recursordist/rec-main.cc
Follow up to #11671. Two more typos. I thought I had skimmed it well enough last time. :/ Second time is the charm?
I have:
> rec: Fix typos in stats log messages

- pdns/dnsdist.cc
> dnsdist: fix building without libedit in dnsdist.cc as well

- pdns/auth-querycache.cc
- pdns/auth-querycache.hh
> auth: remove an unused variable from the querycache

- pdns/dnsdistdist/docs/reference/dq.rst
There might be a better way to describe this... verbiage taken from newPacketCache
I have:
> dnsdist: Update dq.rst

- pdns/pdns_recursor.cc
- pdns/recursordist/rec-main.cc
- pdns/syncres.cc
- pdns/syncres.hh
Plus a bit more detailed info on exceptions for housekeeping, which should aid when diagnosing trouble.
I have:
> rec:  Structured logging for dns64 and simlar functions using directResolve()

- pdns/dnsdistdist/Makefile.am
- pdns/dnsdistdist/logging.hh
- pdns/fstrm_logger.cc
- pdns/pdns_recursor.cc
- pdns/rec-lua-conf.cc
- pdns/rec-lua-conf.hh
- pdns/recursordist/rec-main.cc
- pdns/recursordist/rec-main.hh
- pdns/recursordist/rec-tcp.cc
- pdns/remote_logger.cc
- pdns/rpzloader.cc
Structured logging for RPZ, dnstap and protobuf subsystems, plus a few that were missed before.
I have:
> rec: structured logging for various subsystyems

- pdns/recursordist/rec-main.cc
i.e. when running under systemd. I check `getenv("NOTIFY_SOCKET");`, which I *think* is a good way to decide that.
While there, add thread id to SL messages for bot the text and systemd backend.
I have:
> rec: Use systemd-journal for structured logging if it is available

- pdns/dnsdistdist/docs/guides/downstreams.rst
> dnsdist: Fix a typo in the Downstream guide

- .github/actions/spell-check/expect.txt
- pdns/dnsdistdist/docs/advanced/ebpf.rst
> dnsdist: Document eBPF requirements, external program support

- pdns/packethandler.cc
Expansion will result in missing signatures and broken nsec(x) records.
Request to be accepted -->
I have:
> auth: no ALIAS and LUA record expansion in presigned zones

- docs/manpages/pdnsutil.1.rst
> auth: add b2b-migrate to pdnsutil man page

- .github/workflows/codeql-analysis.yml
Release branches should still be good for a while after that. So no immedaite need to update those.
I have:
> Move to v2 for CodeQL action, v1 will be deprecated dec 2022

- pdns/recursordist/docs/settings.rst
- pdns/ws-recursor.cc
> Backport 11609 to rec 4.5.x: Fix API issue when asking config values for allow-from

- pdns/dnsdist-web.cc
- pdns/dnsdistdist/dnsdist-prometheus.hh
- pdns/dnsdistdist/dnsdist-web.hh
> dnsdist: Fix a few performance-related warnings reported by cppcheck

- regression-tests.dnsdist/runtests
- regression-tests.recursor-dnssec/runtests
> rec-4.7.x: protobuf: use python implementation during tests

- regression-tests.dnsdist/runtests
- regression-tests.recursor-dnssec/runtests
> rec-4.6.x: protobuf: use python implementation during tests

- regression-tests.dnsdist/runtests
- regression-tests.recursor-dnssec/runtests
> rec-4.5.x: protobuf: use python implementation during tests

- docs/requirements.txt
- pdns/dnsdistdist/docs/requirements.txt
- pdns/recursordist/docs/requirements.txt
- regression-tests.dnsdist/runtests
- regression-tests.recursor-dnssec/runtests
> dnsdist-1.6.x: backport of python dep/runtime fixes for protobuf and jinja2

- docs/requirements.txt
- pdns/dnsdistdist/docs/requirements.txt
- pdns/recursordist/docs/requirements.txt
somehow managed to add this for 1.6 earlier, but not 1.5.
I have:
> dnsdist-1.5.x docs: Pin jinja2 to < 3.1.0

- pdns/dnsdist-lua.cc
> dnsdist: Do not try to auto-upgrade DoT and DoH backends

- pdns/webserver.cc
- pdns/webserver.hh
- pdns/ws-recursor.cc
> rec: Structured logging for webserver

- pdns/dnsdistdist/docs/statistics.rst
This adds a few missing stats to the documentation.
I have:
> dnsdist docs: add some missing statistics

- builder-support/debian/authoritative/debian-buster/rules
- builder-support/debian/dnsdist/debian-buster/rules
- builder-support/debian/recursor/debian-buster/rules
> dnsdist-1.7: dh_builddeb: force gzip compression, thanks Zash!

- build-scripts/docker/repo-test/generate-repo-files.py
> Add Ubuntu Jammy to repo test script.

- builder-support/debian/authoritative/debian-buster/rules
- builder-support/debian/dnsdist/debian-buster/rules
- builder-support/debian/recursor/debian-buster/rules
> rec-4.6.x: dh_builddeb: force gzip compression, thanks Zash!

- builder-support/debian/authoritative/debian-buster/rules
- builder-support/debian/dnsdist/debian-buster/rules
- builder-support/debian/recursor/debian-buster/rules
> rec-4.7: dh_builddeb: force gzip compression, thanks Zash!

- pdns/recursordist/rec-zonetocache.cc
- pdns/recursordist/test-rec-zonetocache.cc
> Rec: allow generic format of records in zone file

- builder-support/debian/authoritative/debian-buster/rules
- builder-support/debian/dnsdist/debian-buster/rules
- builder-support/debian/recursor/debian-buster/rules
> auth-4.6: dh_builddeb: force gzip compression, thanks Zash!

- .github/workflows/codeql-analysis.yml
(cherry picked from commit a0c99342e7aa22e16a75d9e7daa4de69d087bc38)
Backport of #11641 
I have:
> rec: Backport 11641 to rec-4.7.x: Move to v2 for CodeQL action, v1 will be deprecated dec 2022

- pdns/recursordist/rec-zonetocache.cc
- pdns/recursordist/test-rec-zonetocache.cc
> rec: Backport 11726 to rec 4.7.x: Convert generic format while parsing zone files for ZoneToCache

- pdns/recursordist/test-rec-zonetocache.cc
> rec: Avoid log spam in tests for for zonemd generic 

- .github/workflows/codeql-analysis.yml
> auth-4.4.x: Move to v2 for CodeQL action, v1 will be deprecated dec 2022

- .github/workflows/codeql-analysis.yml
> auth-4.6.x: Move to v2 for CodeQL action, v1 will be deprecated dec 2022

- modules/lmdbbackend/lmdbbackend.cc
deleteDomain() in lmdb was incomplete
I have:
> auth: fix deleteDomain() in lmdb backend

- .github/actions/spell-check/expect.txt
- .github/actions/spell-check/patterns.txt
- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.7.rst
> rec: Prep for rec-4.7.1

- builder-support/debian/authoritative/debian-buster/tests-source/launch-pdns
> auth-4.6.x deb test: upstream more lenient startup wait

- docs/changelog/4.6.rst
- docs/secpoll.zone
> auth-4.6.3: changelog and secpoll

- pdns/syncres.cc
Simplify handling of edns table. Prompted by Coverity 1490173
I have:
> rec: edns table simplification followup

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.target.ubuntu-kinetic
- builder-support/dockerfiles/Dockerfile.target.ubuntu-kinetic-amd64
- builder-support/dockerfiles/Dockerfile.target.ubuntu-kinetic-arm64
> add ubuntu kinetic target and run it daily in CI

- builder-support/dockerfiles/Dockerfile.rpmbuild
> el9: remove epel-testing, new re2 is in epel9 stable now 

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.target.debian-bookworm
- builder-support/dockerfiles/Dockerfile.target.debian-bookworm-amd64
- builder-support/dockerfiles/Dockerfile.target.debian-bookworm-arm64
> add debian bookworm target and run it daily in CI

- pdns/filterpo.cc
- pdns/filterpo.hh
- pdns/logging.hh
- pdns/lwres.cc
- pdns/lwres.hh
- pdns/pdns_recursor.cc
- pdns/recursordist/rec-main.cc
- pdns/recursordist/rec-main.hh
- pdns/recursordist/rec-tcp.cc
- pdns/syncres.hh
After this, "only" query tracing and validation remains to be converted to SL.
I have:
> rec:  stuctured logging for incoming and outgoing subsystems

- pdns/mastercommunicator.cc
> auth: make sure a notified zone is in the zonecache

- docs/lua-records/index.rst
- pdns/lua-auth4.hh
- pdns/lua-record.cc
- pdns/packethandler.cc
- pdns/packethandler.hh
- regression-tests.auth-py/authtests.py
- regression-tests.auth-py/test_LuaRecords.py
- regression-tests.auth-py/test_ProxyProtocol.py
> auth LUA: make shared mode work for TCP queries

- modules/gsqlite3backend/3.4.0_to_4.0.0_schema.sqlite3.sql
- modules/gsqlite3backend/4.0.0_to_4.2.0_schema.sqlite3.sql
- modules/gsqlite3backend/4.2.0_to_4.3.0_schema.sqlite3.sql
- modules/gsqlite3backend/4.3.0_to_4.3.1_schema.sqlite3.sql
- modules/gsqlite3backend/4.3.1_to_4.7.0_schema.sqlite3.sql
- modules/gsqlite3backend/dnssec-3.x_to_3.4.0_schema.sqlite3.sql
- modules/gsqlite3backend/gsqlite3backend.cc
> auth: sql/catalog nits

- pdns/dnsdistdist/docs/upgrade_guide.rst
> dnsdist docs: fix addRule typo

- modules/gsqlite3backend/3.4.0_to_4.0.0_schema.sqlite3.sql
- modules/gsqlite3backend/4.0.0_to_4.2.0_schema.sqlite3.sql
- modules/gsqlite3backend/4.2.0_to_4.3.0_schema.sqlite3.sql
- modules/gsqlite3backend/4.3.0_to_4.3.1_schema.sqlite3.sql
- modules/gsqlite3backend/4.3.1_to_4.7.0_schema.sqlite3.sql
- modules/gsqlite3backend/dnssec-3.x_to_3.4.0_schema.sqlite3.sql
- modules/gsqlite3backend/gsqlite3backend.cc
> auth-4.7.x: backport #11822

- pdns/webserver.cc
Initialize the `s_dlog` field of that new response. I would prefer to do that in the
exception's ct, but we do not have the uniqueid there.
Avoids a crash with `webserver-loglevel=detailed`.
I have:
> rec: structured logging for webserver followup: An HttpException creates a new response body.

- pdns/recursordist/Makefile.am
> res: Set rec_control_LDFLAGS, needed for MacOS or any platforms where libcrypto is not in default lib path.

- pdns/auth-main.cc
> auth: use getInnerRemote() for the remotes ring

- pdns/pdns_recursor.cc
- pdns/recursordist/rec-protozero.cc
- pdns/recursordist/rec-protozero.hh
- pdns/remote_logger.cc
Security Advisory 2022-02
I have:
> Rec: check protobuf size

- pdns/pdns_recursor.cc
- pdns/recursordist/rec-protozero.cc
- pdns/recursordist/rec-protozero.hh
- pdns/remote_logger.cc
> Backport of protobuf PSA 2022-02 (CVE-2022-37428) to rec-4.5.x

- pdns/pdns_recursor.cc
- pdns/recursordist/rec-protozero.cc
- pdns/recursordist/rec-protozero.hh
- pdns/remote_logger.cc
> Backport of protobuf PSA 2022-02 (CVE-2022-37428) to rec-4.6.x

- pdns/pdns_recursor.cc
- pdns/recursordist/rec-protozero.cc
- pdns/recursordist/rec-protozero.hh
- pdns/remote_logger.cc
> Backport of protobuf PSA 2022-02 (CVE-2022-37428) to rec-4.7.x

- pdns/pdns_recursor.cc
- regression-tests.recursor-dnssec/test_Lua.py
> rec: Backport 11773 to rec 4.6.x: Resize answer length to actual received length in udpQueryResponse 

- pdns/pdns_recursor.cc
- regression-tests.recursor-dnssec/test_Lua.py
> rec: Backport 11773 to rec-4.7.x: Resize answer length to actual received length in udpQueryResponse 

- pdns/reczones.cc
(cherry picked from commit 799114529470923a5e633dadc47b59c4e2a7e220)
Backport of #11843 
I have:
> rec: backport 11843 to rec-4.7.x: Clear the caches *after* loading authzones.

- pdns/recursordist/docs/changelog/4.5.rst
- pdns/recursordist/docs/changelog/4.6.rst
- pdns/recursordist/docs/changelog/4.7.rst
- pdns/recursordist/docs/security-advisories/powerdns-advisory-2022-02.rst
> PSA 2022-02 tweaks and add PR#'s

- pdns/rec_control.cc
> rec_control: test for "--version" before requiring an argument.

- pdns/webserver.cc
dnsdist does not, either. Avoids leaking VERSION to not authorized users.
Implements #4979.
I have:
> auth/rec web: stop sending Server: header

- pdns/lua-base4.cc
- pdns/lua-base4.hh
- pdns/recursordist/rec-main.cc
Handle errors when loading Lua scripts.
I have:
> Handle Lua script loading errors

- pdns/auth-main.cc
> auth-4.7.x: use getInnerRemote() for the remotes ring

- modules/gmysqlbackend/4.3.0_to_4.7.0_schema.mysql.sql
- modules/gmysqlbackend/schema.mysql.sql
- modules/godbcbackend/schema.mssql.sql
- modules/gpgsqlbackend/4.3.0_to_4.7.0_schema.pgsql.sql
- modules/gpgsqlbackend/schema.pgsql.sql
- modules/gsqlite3backend/4.3.1_to_4.7.0_schema.sqlite3.sql
- modules/gsqlite3backend/schema.sqlite3.sql
> auth catalog zones: simplify migration schemas by appending columns

- pdns/auth-main.cc
Successor of #10830
fixes #11332
closes #10830
closes #10829
I have:
> auth: initialize zone cache after dropping privileges

- modules/gmysqlbackend/4.3.0_to_4.7.0_schema.mysql.sql
- modules/gmysqlbackend/schema.mysql.sql
- modules/godbcbackend/schema.mssql.sql
- modules/gpgsqlbackend/4.3.0_to_4.7.0_schema.pgsql.sql
- modules/gpgsqlbackend/schema.pgsql.sql
- modules/gsqlite3backend/4.3.1_to_4.7.0_schema.sqlite3.sql
- modules/gsqlite3backend/schema.sqlite3.sql
> auth-4.7.x catalog zones: simplify migration schemas by appending columns

- docs/modes-of-operation.rst
- docs/settings.rst
- pdns/auth-main.cc
- pdns/slavecommunicator.cc
> auth-4.7.x:  New setting compare-signatures-on-zone-freshness-check to disable DO flag for SOA checks #11508

- pdns/recursordist/docs/settings.rst
- pdns/recursordist/rec-main.cc
- pdns/syncres.cc
- pdns/syncres.hh
> rec: For zones having many NS records take a sample

- pdns/syncres.cc
- pdns/syncres.hh
> rec: backport 11848 to rec-4.7.x: Also check qperq limit if throttling happened, as it increases counters.

- pdns/tkey.cc
> auth-4.7.x: Fix CID 1497843: Execution cannot reach this statement

- pdns/common_startup.cc
> auth-4.6.x: use getInnerRemote() for the remotes ring

- pdns/ws-auth.cc
- regression-tests.api/test_Zones.py
> auth-4.7.x: api, nsec3param improvements

- pdns/auth-main.cc
- pdns/auth-main.hh
> auth-4.7.x: fix gcc warning

- pdns/lua-record.cc
> auth LUA records: we only need one IsUpOracle checker thread

- pdns/lua-record.cc
> auth-4.7.x: LUA records: we only need one IsUpOracle checker thread

- pdns/arguments.cc
- pdns/arguments.hh
- pdns/recursordist/Makefile.am
- pdns/recursordist/docs/manpages/pdns_recursor.1.rst
- pdns/recursordist/rec-main.cc
Add `--config[=check|=diff|=default]` to the recursor
I have:
> Recursor: Add `--config[=check|=diff|=default]`

- pdns/recursordist/docs/appendices/internals.rst
> rec docs: fix spelling error (lifetimeof is not a word)

- pdns/lua-record.cc
inspired by #6188
We can rid of this when we make it to C++20.
I have:
> auth LUA: fix "braces around scalar initializer" warning

- pdns/auth-main.cc
- pdns/auth-main.hh
- pdns/lua-record.cc
backport of #11932 and #11933
I have:
> auth-4.7.x: backport two compiler warning fixes

- pdns/pdns_recursor.cc
- pdns/recursordist/docs/settings.rst
- pdns/syncres.cc
- pdns/syncres.hh
(cherry picked from commit a49b0b40a0c1c1af9531b99e9266a8c2aa89cd68)
Backport of #11904 
I have:
> Backport 11904 to rec-4.5.x: For zones having many NS records, we are not interested in all so take a sample.

- pdns/pdns_recursor.cc
- pdns/recursordist/docs/settings.rst
- pdns/syncres.cc
- pdns/syncres.hh
(cherry picked from commit a49b0b40a0c1c1af9531b99e9266a8c2aa89cd68)
Backport of #11904 
I have:
> rec: Backport 11904 to rec-4.6.x: For zones having many NS records, we are not interested in all so take a sample.

- pdns/recursordist/docs/settings.rst
- pdns/recursordist/rec-main.cc
- pdns/syncres.cc
- pdns/syncres.hh
(cherry picked from commit a49b0b40a0c1c1af9531b99e9266a8c2aa89cd68)
Backport of #11904 
I have:
> rec: Backport 11904 to rec-4.7.x: For zones having many NS records, we are not interested in all so take a sample.

- .github/workflows/codeql-analysis.yml
(cherry picked from commit a0c99342e7aa22e16a75d9e7daa4de69d087bc38)
Backport of #11641 
I have:
> rec: Backport of 11641 to rec-4.5.x: Move to v2 for CodeQL action, v1 will be deprecated dec 2022

- .github/actions/spell-check/expect.txt
- docs/backends/generic-mysql.rst
- docs/backends/generic-postgresql.rst
- docs/backends/generic-sqlite3.rst
- docs/changelog/4.7.rst
- docs/secpoll.zone
- docs/upgrading.rst
> auth-4.7.0-beta2: secpoll and docs

- build-scripts/docker/repo-test/generate-repo-files.py
> Add auth-47 for Ubuntu Jammy and EL9 to test script.

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.rpmbuild
- builder-support/dockerfiles/Dockerfile.target.centos-9-stream
- builder-support/dockerfiles/Dockerfile.target.el-9
- builder-support/dockerfiles/Dockerfile.target.el-9-amd64
- builder-support/dockerfiles/Dockerfile.target.el-9-arm64
- builder-support/specs/pdns.spec
> rec-4.7: add EL9+9stream targets

- docs/appendices/EOL.rst
The current EOL dates for Auth still assume 4.7 would be released "~ June 2022". That date has come and gone.
Might keep this PR open till 4.7 is released.
I have:
> Update auth EOL dates a bit :)

- pdns/recursordist/test-syncres_cc6.cc
> rec: Add unit test to check that we go Bogus if a DS query responds with a CNAME on a would-be Secure zone

- Dockerfile-auth
- Dockerfile-dnsdist
- Dockerfile-recursor
> docker: upgrade to bullseye

- Dockerfile-auth
- Dockerfile-dnsdist
- Dockerfile-recursor
> rec 4.5.x docker: upgrade to bullseye

- Dockerfile-auth
- Dockerfile-dnsdist
- Dockerfile-recursor
> auth 4.6.x docker: upgrade to bullseye

- Dockerfile-auth
- Dockerfile-dnsdist
- Dockerfile-recursor
> rec 4.7.x docker: upgrade to bullseye

- Dockerfile-auth
- Dockerfile-dnsdist
- Dockerfile-recursor
> rec 4.6.x docker: upgrade to bullseye

- Dockerfile-auth
- Dockerfile-dnsdist
- Dockerfile-recursor
> dnsdist 1.7.x docker: upgrade to bullseye

- Dockerfile-auth
- Dockerfile-dnsdist
- Dockerfile-recursor
> auth-4.7.x docker: upgrade to bullseye

- Dockerfile-auth
- Dockerfile-dnsdist
- Dockerfile-recursor
> auth 4.5.x docker: upgrade to bullseye

- Dockerfile-auth
- Dockerfile-dnsdist
- Dockerfile-recursor
> dnsdist 1.6.x docker: upgrade to bullseye

- m4/boost.m4
Also upstreamed: https://github.com/tsuna/boost.m4/pull/129
I have:
> clang14 has reached MacOS

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.5.rst
- pdns/recursordist/docs/changelog/4.6.rst
- pdns/recursordist/docs/changelog/4.7.rst
- pdns/recursordist/docs/settings.rst
- pdns/recursordist/docs/upgrade.rst
> rec: Prep rec 4.7.3 4.6.4 4.5.11

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.rpmbuild
- builder-support/dockerfiles/Dockerfile.target.centos-9-stream
- builder-support/dockerfiles/Dockerfile.target.el-9
- builder-support/dockerfiles/Dockerfile.target.el-9-amd64
- builder-support/dockerfiles/Dockerfile.target.el-9-arm64
- builder-support/specs/pdns.spec
> dnsdist-1.7: add el9/9stream targets

- pdns/recursordist/docs/lua-scripting/hooks.rst
> rec: Typo in hooks.rst

- pdns/dnssecinfra.cc
- pdns/dnswriter.cc
- pdns/protozero.hh
- pdns/rcpgenerator.cc
- pdns/rec_channel_rec.cc
- pdns/recursor_cache.cc
- pdns/recursordist/rec-zonetocache.cc
- pdns/ws-recursor.cc
Moslty rec, but some touch dnsdist and auth as well.
All innocent, the DNS protocol stores (relative) time in a 32-bit unsigned int, there's not a lot we can do about that.
I have:
> Coverity Fixes 20220921

- pdns/dnssecinfra.cc
- pdns/dnswriter.cc
- pdns/protozero.hh
- pdns/rcpgenerator.cc
- pdns/recursor_cache.cc
Typo in annotations and one missed
I have:
> Folowup to #11986: coverity fixes

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.8.rst
- pdns/recursordist/docs/changelog/index.rst
- pdns/recursordist/docs/upgrade.rst
> Prep for rec-4.8.0-alpha1

- pdns/recursordist/docs/appendices/EOL.rst
- pdns/recursordist/docs/changelog/4.8.rst
- pdns/recursordist/docs/upgrade.rst
> Only say EOL if a version is actually EOL, plus some fixes to cross references.

- pdns/recursordist/docs/settings.rst
> Say since when XPF has been deprecated in rec

- pdns/pdns_recursor.cc
- pdns/recursordist/rec-main.cc
- pdns/recursordist/rec-taskqueue.cc
A typo, some level changes and a few missed conversions.
I have:
> rec: A few tweaks to structured logging calls

- pdns/recursordist/rec-main.cc
> Warn if snmp-agent is set but SNMP is not available.

- pdns/dnsdistdist/docs/rules-actions.rst
> dnsdist: Update rules-actions.rst

- builder-support/specs/pdns-recursor.spec
> Enable include-dir by default in RPM builds, to be in line with DEB builds

- pdns/dnsdistdist/docs/install.rst
- pdns/libssl.cc
> dnsdist: Add a build option (define) to prevent loading OpenSSL's errors

- pdns/dnsdist-lua.cc
- pdns/dnsdistdist/dnsdist-discovery.cc
> dnsdist: Add missing thread names

- pdns/dnsdist-web.cc
> dnsdist: Slightly reduce the number of allocations in API calls

- m4/boost.m4
> auth-4.7: clang14 has reached MacOS

- pdns/lua-recursor4.cc
- pdns/lua-recursor4.hh
- pdns/pdns_recursor.cc
- pdns/recursordist/docs/lua-scripting/dq.rst
- pdns/recursordist/test-syncres_cc.cc
- pdns/syncres.cc
- regression-tests.recursor-dnssec/test_Lua.py
Handy for cases where the Lua code needs to know the time the query was received.
I have:
> rec: add querytime attribute to dq

- .circleci/config.yml
> auth-4.5.x: circleci auth-py: set pdns_control path

- pdns/axfr-retriever.cc
> auth-4.7: axfr-retriever: abort on chunk with TC set

- pdns/axfr-retriever.cc
> auth-4.6: axfr-retriever: abort on chunk with TC set

- pdns/lua-record.cc
> auth-4.6 LUA records: we only need one IsUpOracle checker thread

- modules/gpgsqlbackend/spgsql.cc
> auth-4.6: Log "NULL" for nullptr-bound properties instead of dereferencing

- pdns/dns.cc
- pdns/dns.hh
- pdns/rec-snmp.cc
- pdns/rec_channel_rec.cc
- pdns/recursordist/RECURSOR-MIB.txt
- pdns/recursordist/docs/metrics.rst
- pdns/syncres.cc
- pdns/syncres.hh
- pdns/ws-recursor.cc
> Rec: provide rcode received from auths metrics

- pdns/dnsparser.cc
Most of the time this method is called on packets that do not include any problematic records, so quickly iterating over the records before allocating and copying things around saves a fair amount of CPU time.
I have:
> dnsdist: Rewrite packets to remove records only if actually needed

- pdns/dnsdist-protocols.cc
- pdns/dnsdist-protocols.hh
By making it easier to inline. 
I have:
> dnsdist: Speed up the dnsdist::Protocol() constructor

- pdns/dnsdist-lua.cc
- pdns/dnsdistdist/dnsdist-lua-ffi.cc
- pdns/dnsdistdist/dnsdist-lua-ffi.hh
- pdns/dnsdistdist/docs/reference/config.rst
- pdns/dnsdistdist/docs/reference/dq.rst
- pdns/dnsdistdist/docs/rules-actions.rst
- pdns/dnsdistdist/doh.cc
- pdns/doh.hh
- regression-tests.dnsdist/test_DOH.py
> dnsdist: Speed up DoH handling by preventing allocations and copies

- pdns/dnsdistdist/dnsdist-discovery.cc
- regression-tests.dnsdist/test_BackendDiscovery.py
Also remove two unreachable code paths lowering our code coverage.
I have:
> dnsdist: More backend discovery regression tests

- pdns/dnspacket.cc
- pdns/dnspacket.hh
- pdns/tcpreceiver.cc
> auth 4.7 AXFR server: abort on chunk with TC set

- pdns/portsmplexer.cc
Thanks to Jonathan Perkin for the patch!
Closes #12044.
I have:
> Fix compilation of the event ports multiplexer

- pdns/recursordist/rec-main.cc
> rec: Fix --config (should be equal to --config=default),  followup to #11907

- pdns/rec_channel_rec.cc
> rec: fix build with --disable-dnstap, followup to #11903

- regression-tests.recursor-dnssec/recursortests.py
- regression-tests.recursor-dnssec/test_LockedCache.py
> rec: Regression test for locked cache

- .github/actions/spell-check/expect.txt
- docs/changelog/4.7.rst
- docs/secpoll.zone
> auth-4.7.0-rc1: secpoll&changelog

- docs/backends/lmdb.rst
> auth: lmdbbackend: add schema version 4 in the backend documentation

- regression-tests.recursor-dnssec/test_LockedCache.py
> Rec: fix locked regr test

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.8.rst
- pdns/recursordist/docs/conf.py
- pdns/recursordist/docs/manpages/pdns_recursor.1.rst
- pdns/recursordist/docs/upgrade.rst
> rec: Prep for rec-4.8.0-beta1

- pdns/proxy-protocol.cc
- pdns/test-proxy_protocol_cc.cc
> Proxy Protocol: Only allocate once when generating the payload

- pdns/dnsdistdist/test-dnsdistsvc_cc.cc
> dnsdist: More SVC unit tests

- pdns/dnsdist-lua.cc
- pdns/dnsdist-lua.hh
- pdns/dnsdist-protocols.cc
- pdns/dnsdist-protocols.hh
- pdns/dnsdistdist/Makefile.am
- pdns/dnsdistdist/dnsdist-lua-bindings-rings.cc
- pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
- pdns/dnsdistdist/dnsdist-lua-ffi.cc
- pdns/dnsdistdist/docs/reference/config.rst
> dnsdist: Add Lua binding for inspecting the in-memory ring buffers

- pdns/portsmplexer.cc
> auth-4.7: Fix compilation of the event ports multiplexer

- pdns/dnsdistdist/docs/reference/config.rst
And not in 1.7.0 as the documentation was stating.
I have:
> dnsdist: 'newThread()' and co were actually introduced in 1.8

- .github/actions/spell-check/expect.txt
- pdns/recursordist/docs/changelog/4.8.rst
- pdns/recursordist/docs/getting-started.rst
- pdns/recursordist/docs/lua-config/protobuf.rst
- pdns/recursordist/docs/upgrade.rst
> Fix spell-checking issues

- docs/backends/lmdb.rst
> auth: add note about lmdb-random-ids and catalog zones producers

- pdns/tcpreceiver.cc
Catalog-zones added a getDomainInfo() call which is missing in tinydns and pipe backend. As a result of this axfr was broken for these backends. After this pull getDomainInfo() is only a requirement for catalog-zone capable backends.
I have:
> auth: fix axfr for tinydns and pipe backend

- docs/changelog/4.7.rst
- docs/secpoll.zone
> auth-4.7-0: docs and secpoll

- builder-support/specs/pdns.spec
- modules/gmysqlbackend/Makefile.am
- modules/godbcbackend/Makefile.am
- modules/gpgsqlbackend/Makefile.am
- modules/gsqlite3backend/Makefile.am
> auth-4.7: include auth 4.7 schema upgrade files in tarballs and packages

- builder-support/specs/pdns.spec
- docs/upgrading.rst
- modules/gmysqlbackend/Makefile.am
- modules/godbcbackend/Makefile.am
- modules/gpgsqlbackend/Makefile.am
- modules/gsqlite3backend/Makefile.am
> auth: include auth 4.7 schema upgrade files in tarballs and packages

- pdns/lua-record.cc
> auth-4.5: auth LUA records: we only need one IsUpOracle checker thread

- docs/appendices/EOL.rst
- docs/secpoll.zone
> auth: update EOL matrix with 4.7.0 release

- .github/dependabot.yml
- .github/workflows/build-and-test-all.yml
- .github/workflows/builder-dispatch.yml
- .github/workflows/builder.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/formatting.yml
- .github/workflows/fuzz.yml
- .github/workflows/secpoll.yml
- .github/workflows/spelling2.yml
This sets up dependabot to:
* automatically open PRs if we use an old version of any GitHub Action
* tell us (in the Security tab) if we use old versions of any Python packages
This PR also includes a set of dependabot-generated commits that we'd otherwise get as a bunch of individual PRs as soon as we merge this yaml file into master.
I have:
> Setup dependabot

- .github/workflows/misc-dailies.yml
- builder-support/dockerfiles/Dockerfile.rpmbuild
- builder-support/dockerfiles/Dockerfile.target.centos-7
and add a daily GH job to notice future bump opportunities
I have:
> el7 builds: bump devtoolset version

- .github/workflows/misc-dailies.yml
- build-scripts/check-debian-autoremovals.py
> daily job: check debian autoremovals

- pdns/syncres.cc
> rec: More clear trace message for cache-only lookups.

- .github/actions/spell-check/allow.txt
- modules/gmysqlbackend/smysql.cc
- modules/pipebackend/coprocess.cc
- modules/pipebackend/pipebackend.cc
- modules/remotebackend/pipeconnector.cc
- pdns/arguments.cc
- pdns/auth-main.cc
- pdns/backends/gsql/gsqlbackend.cc
- pdns/bindparser.yy
- pdns/dynhandler.cc
- pdns/misc.cc
- pdns/misc.hh
- pdns/qtype.cc
- pdns/resolver.cc
- pdns/rfc2136handler.cc
- pdns/syncres.hh
`std::to_string()` has been there since C++11, so use it.
I have:
> Replace itoa() with std::to_string()

- regression-tests.recursor-dnssec/test_LockedCache.py
> rec: Fix assertAlmostEqual call to compare absolute difference

- pdns/backends/gsql/gsqlbackend.cc
- regression-tests.auth-py/test_IXFR.py
With 566162d43d5317edb834bdbf2ead9bd76a2eef13 the action was reversed but the condition not.
Th changes to the ixfr test only removes debug prints.
I have:
> Auth: xfr refresh check

- .github/workflows/builder-dispatch.yml
see previous conversation in #12139
> github builds: upload to downloads.powerdns.com

- docs/changelog/4.7.rst
- docs/secpoll.zone
> auth-4.7.1: secpoll and docs

- pdns/backends/gsql/gsqlbackend.cc
- regression-tests.auth-py/test_IXFR.py
> auth-4.7.x: fix xfr refresh check

- docs/changelog/4.7.rst
- docs/secpoll.zone
> auth-4.7.2: secpoll & docs

- pdns/misc.cc
- pdns/test-misc_hh.cc
Backport of #12066 
Appeases CodeQL
I have:
> rec: backport 12066 to rec 4.8.x: Detect invalid bytes in makeBytesFromHex() 

- pdns/recursor_cache.cc
- pdns/recursordist/test-recursorcache_cc.cc
> rec: Backport 12140 to rec 4.8.x: be more lenient replacing auth by non-auth records in cache

- pdns/qtype.hh
This fixes #12089
The theory says there should be no unwanted side effects, but I'd like that to be validated independently.
I have:
> rec: Implement output operator for QTypes.

- docs/secpoll.zone
- pdns/dnsdistdist/docs/changelog.rst
> dnsdist-1.7.3: docs and secpoll

- build-scripts/docker/repo-test/generate-repo-files.py
- build-scripts/docker/repo-test/templates/Dockerfile-el.jinja2
Also fixes an issue we had with the template for EL-9.
I have:
> Add dnsdist-17 for Ubuntu Jammy and EL-9 to repo test script

- pdns/rec-snmp.cc
- pdns/recursordist/docs/metrics.rst
Originally I played with a subtable, that idea was abandoned, but somehow those OIDs ended up in the table. 
This also add a doc commit to address the problem discussed in #12126
I have:
> Rec: fix snmp rcodes OIDs

- pdns/qtype.hh
> rec: Backport 12122 to rec 4.8.x: Implement output operator for QTypes

- pdns/rec-snmp.cc
- pdns/recursordist/docs/metrics.rst
> rec: Backport 12155 to rec 4.8.x: Fix snmp OID numbers for rcode stats

- pdns/misc.cc
- pdns/test-misc_hh.cc
> rec: Backport 12066 to rec 4.6.x: Detect invalid bytes in makeBytesFromHex() 

- pdns/misc.cc
- pdns/test-misc_hh.cc
> rec: Backport 12066 to rec 4.7.x: Detect invalid bytes in makeBytesFromHex() 

- .github/actions/spell-check/expect.txt
- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.8.rst
> rec: Prep for rec-4.8.0-beta2

- pdns/dynhandler.cc
> auth-4.7.x: fix pdns_control list-zones

- pdns/ixfr.cc
- pdns/ixfr.hh
- pdns/ixplore.cc
- pdns/rpzloader.cc
- pdns/rpzloader.hh
- pdns/slavecommunicator.cc
> rec: Backport 12125 to rec 4.7.x: Timout handling for ixfrs as a client

- pdns/ixfr.cc
- pdns/ixfr.hh
- pdns/ixplore.cc
- pdns/rpzloader.cc
- pdns/rpzloader.hh
- pdns/slavecommunicator.cc
> rec: Backport 12125 to rec 4.6.x: Timout handling for ixfrs as a client

- pdns/ixfr.cc
- pdns/ixfr.hh
- pdns/ixplore.cc
- pdns/rpzloader.cc
- pdns/rpzloader.hh
- pdns/slavecommunicator.cc
> rec: Backport 12125 to rec 4.5.x: Timout handling for ixfrs as a client

- pdns/syncres.cc
Noted the other day by @rgacogne 
I have:
> rec: Correct skip record condition in processRecords

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.8.rst
> Prep for rec-4.8.0-rc1

- pdns/dnsdistdist/docs/reference/tuning.rst
> dnsdist: Fix typo in the doc for setUDPSocketBufferSizes

- pdns/dnsdist.hh
- pdns/dnsdistdist/dnsdist-backend.cc
- pdns/dnsdistdist/test-dnsdistbackend_cc.cc
> dnsdist: Fix duplicated first delay in lazy mode, add more log messages

- pdns/mtasker.hh
- pdns/recursordist/test-mtasker.cc
> rec: Disable test_MtaskerException on Apple Silicon if asan is enabled. 

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.5.rst
- pdns/recursordist/docs/changelog/4.6.rst
- pdns/recursordist/docs/changelog/4.7.rst
> Prep for rec-4.5.12 rec-4.6.5 rec-4.7.4

- docs/requirements.txt
> auth docs build, bump sphinxcontrib-openapi to a version compatible with Python 3.10

- pdns/zonemd.hh
> rec-4.7.x: Stop using deprecated std::binary_function

- Docker-README.md
Updates the `Docker-README.md` file with a note about needing to initialize git submodules before being able to do a Docker build.  I've also corrected a few minor typos in the `Compose example` section.
Part of #12179.
I have:
> Update Docker README to mention dependency on git submodule

- pdns/recursordist/docs/lua-config/rpz.rst
> rec: Mention timeout also aplies to IXFRs

- .github/actions/spell-check/expect.txt
- pdns/recursordist/docs/changelog/4.5.rst
- pdns/recursordist/docs/changelog/4.6.rst
- pdns/recursordist/docs/changelog/4.7.rst
> Fix a typo in the recursor's ChangeLog, allow 'builddeb'

- pdns/pdnsutil.cc
A pet peeve from me...
Fixes #11341
I have:
> auth: Basic abstraction for handling colored terminal output, respecting isatty(), --no-colors and NO_COLOR

- docs/appendices/types.rst
> auth: Update supported recordtypes: remove A6 MAILA MAILB SIG and WKS, add ZONEMD

- pdns/dnsdistdist/docs/statistics.rst
> dnsdist: Fix a typo in the counters documentation

- pdns/ws-auth.cc
> auth API: slightly clearer message when a backend cannot create domains

- modules/remotebackend/remotebackend.cc
- modules/remotebackend/remotebackend.hh
- pdns/backends/gsql/gsqlbackend.cc
- pdns/backends/gsql/gsqlbackend.hh
- pdns/dnsbackend.hh
> auth: move alsoNotifies up into DNSBackend

- modules/lmdbbackend/lmdbbackend.cc
- modules/lmdbbackend/lmdbbackend.hh
> auth 4.6 lmdb: implement alsoNotifies

- modules/lmdbbackend/lmdbbackend.cc
- modules/lmdbbackend/lmdbbackend.hh
> auth 4.7 lmdb: implement alsoNotifies

- regression-tests.auth-py/test_XFRIncomplete.py
> auth 4.5: fix race in incomplete xfr test

- pdns/axfr-retriever.cc
> auth-4.5: axfr-retriever: abort on chunk with TC set

- .github/workflows/codeql-analysis.yml
> auth-4.5.x: Move to v2 for CodeQL action, v1 will be deprecated dec 2022

- modules/gpgsqlbackend/gpgsqlbackend.cc
> auth 4.7: fix invalid catalog zone sql query for gpgsqlbackend

- pdns/ws-auth.cc
- regression-tests.api/test_Zones.py
- regression-tests.api/test_helper.py
> auth-4.7 API: fix newly created zone not rectified

- pdns/dnsdist-tcp.cc
- pdns/dnsdist.cc
- pdns/dnsdist.hh
- [Only allocate a ConnectionInfo object when actually needed](https://github.com/PowerDNS/pdns/commit/d4a188180a3b8e690bd215f04a5bdca6abcf53e5)
- [dnsdist: Prevent a copy when inserting a tag](https://github.com/PowerDNS/pdns/commit/7c878adc15091d0b0ed36d85f6ed4baa4c2f0edd)
- [dnsdist: Keep the local copy of the downstream servers around](https://github.com/PowerDNS/pdns/commit/9a0f37a7f99b22f133f3f1c333964dd793eec337)
I have:
> dnsdist: Small improvements

- .github/actions/spell-check/expect.txt
- pdns/recursordist/docs/settings.rst
> Fix a typo and allow 'byteslimit'

- pdns/pdns_recursor.cc
- pdns/qtype.hh
- pdns/recursordist/rec-tcp.cc
- pdns/syncres.cc
- pdns/syncres.hh
> rec: Backport 12289 to rec 4.8.x: refactor unsuppored qtype code and make sure we ServFail on all unsupported qtypes

- regression-tests.auth-py/test_LuaRecords.py
> auth 4.6: take into account default urlcheck timeout is 2 seconds for Lua records tests

- pdns/ws-auth.cc
> auth 4.7 API: slightly clearer message when a backend cannot create domains

- modules/lmdbbackend/lmdbbackend.cc
- regression-tests/backends/lmdb-master
> auth lmdb: make outgoing notifications work

- modules/lmdbbackend/lmdbbackend.cc
- regression-tests/backends/lmdb-master
> auth-4.7 lmdb: make outgoing notifications work

- pdns/dnsdistdist/docs/rules-actions.rst
From a discussion on IRC.
I searched for this but could not find it. I believe this documents what dnsdist does if no action handled the packet.
Plus a few :program:`dnsdist`.
I have:
> dnsdist: Document what happens to a packet not handled by any action

- pdns/dnsparser.hh
> auth 4.6: pdnsutil edit-zone, detect capitalization changes in LUA, TXT and SPF records

- pdns/dnsdistdist/docs/guides/downstreams.rst
As reported by Kai Stian Olstad (thanks!).
Closes #12271.
I have:
> dnsdist: Fix a typo in the Healthcheck configuration guide

- pdns/dnsdistdist/docs/reference/config.rst
> dnsdist: List default of top argument of topX functions

- docs/dnsupdate.rst
- pdns/recursordist/docs/lua-scripting/hooks.rst
> spell-check: Make the spell-checker happy

- pdns/pdns_recursor.cc
- pdns/recursordist/rec-tcp.cc
Reported by HellSpawn.
I have:
> rec: Fix compilation on FreeBSD

- pdns/dnsdist.cc
Spotted compiler warning on FreeBSD 
I have:
> dnsdist: Use rlim_t for limit

- modules/lmdbbackend/lmdbbackend.cc
- regression-tests.api/test_TSIG.py
- regression-tests.api/test_helper.py
Fix TSIG removal in lmdb backend
fixes #12223
I have:
> auth: lmdb, fix TSIG key removal

- pdns/iputils.cc
Not raising because it's already high is not an error.
I have:
> Setting socket buf size: not decreasing is not an error

- pdns/libssl.cc
Note that the `openssl pkcs12` command uses `AES-256-CBC with PBKDF2` since OpenSSL 3.x, meaning PKCS12 files generated from now on do not have this issue, but existing ones do. 
I have:
> dnsdist: Fix loading PKCS12-encrypted (RC2 CBC) certs with OpenSSL 3.x

- pdns/recursordist/pdns_recursor.cc
- pdns/recursordist/rec-tcounters.cc
- pdns/recursordist/rec-tcounters.hh
- pdns/recursordist/rec_channel_rec.cc
- pdns/recursordist/syncres.cc
- pdns/recursordist/syncres.hh
- pdns/recursordist/test-syncres_cc.cc
- pdns/recursordist/validate-recursor.cc
> rec: move dnssec and policy counters to TCounter object

- pdns/recursordist/pdns_recursor.cc
Based on a diff from @rgacogne 
I have:
> rec: Warn on high (90%) mthread stack usage

- modules/ldapbackend/ldapbackend.cc
- modules/ldapbackend/powerldap.hh
- modules/pipebackend/coprocess.cc
- pdns/auth-catalogzone.hh
- pdns/auth-main.cc
- pdns/credentials.cc
- pdns/dns.hh
- pdns/dnsdistdist/doh.cc
- pdns/dnsparser.cc
- pdns/dnsrecords.cc
- pdns/dynhandler.cc
- pdns/dynlistener.cc
- pdns/dynlistener.hh
- pdns/dynmessenger.hh
- pdns/ixfrutils.cc
- pdns/mastercommunicator.cc
- pdns/pdnsutil.cc
- pdns/resolver.cc
- pdns/sillyrecords.cc
- pdns/slavecommunicator.cc
- pdns/sstuff.hh
- pdns/tcpreceiver.cc
- pdns/ueberbackend.cc
- pdns/utility.hh
- pdns/zoneparser-tng.cc
One more pass of clang-tidy across the sources, someday bit by bit clangd will not burn my CPU while running. :rofl: 
I have:
> Clang-tidy: one more time

- docs/common/tarball-pgp-keys.rst
Remove Bert and Pieter, add Remi and Otto
Same order as mentioned key file.
I have:
> Update the pgp keys listed in docs

- pdns/dnsdist-ecs.cc
- pdns/dnsdist-ecs.hh
- pdns/dnsdist-idstate.hh
- pdns/dnsdist.hh
- pdns/dnsdistdist/dnsdist-rules.hh
- pdns/ednsoptions.hh
- pdns/test-dnsdist_cc.cc
> dnsdist: Move DNSQuestion's EDNS options to a unique pointer

- pdns/misc.cc
- pdns/recursordist/pdns_recursor.cc
Also some assorted clang-tidy fixes.
I have:
> Be more careful saving errno in makeClientSocket() and closesocket()

- pdns/dnsdist.hh
- pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
- pdns/dnsdistdist/dnsdist-lua-ffi.cc
> dnsdist: Add a Lua FFI interface for metrics

- pdns/dnsdist-console.cc
- pdns/dnsdist-idstate.hh
- pdns/dnsdist-lua-bindings-dnsquestion.cc
- pdns/dnsdist-lua-bindings.cc
- pdns/dnsdistdist/docs/reference/config.rst
- pdns/dnsdistdist/docs/reference/dq.rst
- regression-tests.dnsdist/test_Advanced.py
> dnsdist: Add bindings for the current and query times in DQ/DR

- build-scripts/gh-actions-setup-inv
- tasks.py
See https://github.com/actions/runner-images/issues/6894
I have:
> CI: Work-around the "503  Service Unavailable" erros on azure.archive.ubuntu.com

- .github/actions/spell-check/expect.txt
> spell-checker: Allow EACA (from the PGP public keys in the docs)

- .github/workflows/build-and-test-all.yml
- build-scripts/gh-actions-setup-inv
Let's try this for a bit. If it helps, we'll update the other workflows too.
I have:
> build-and-test-all: add functionality to quickly switch ubuntu mirrors

- pdns/recursordist/negcache.cc
Originally suggested by @rgacogne, but not included in the merge of #12374 somehow.
I have:
> rec: negcache dump code: close fd on fdopen fail

- pdns/recursordist/README.md
> rec: README tweaks, .md does not know :program:`...`

- pdns/credentials.cc
> credentials: Explicitly clear credentials once they have been moved

- docs/manpages/dnsreplay.1.rst
> dnsreplay: Fix formatting in the man page

- pdns/recursordist/rec-main.cc
- pdns/syncres.cc
- pdns/syncres.hh
PowerDNS Security Advisory 2023-01
I have:
> rec: Backport to 4.8.x: Do *not* use QName Minimization for DS retrievals in QM fallback mode.

- pdns/iputils.cc
(cherry picked from commit fe65dec04f3fadaca8f5319cf02f4b302463afe9)
Backport of #12333 
I have:
> rec: Backport 12333 to rec-4.8.x: For setting socket buf size not decreasing is not an error

- pdns/pdns_recursor.cc
- pdns/recursordist/rec-tcp.cc
(cherry picked from commit 398bb0f1e7122d6de0e6c5ec3383ba49a446d580)
Backport of #12317 
I have:
> rec: Backport 12317 to rec-4.8.x: Fix compilation on FreeBSD. reported by HellSpawn

- pdns/lwres.cc
- pdns/lwres.hh
- pdns/pdns_recursor.cc
> rec: Backport 12407 to 4.8.x: do not chain ecs enabled queries

- pdns/cachecleaner.hh
- pdns/rec_channel_rec.cc
- pdns/recursor_cache.cc
- pdns/recursor_cache.hh
- pdns/recursordist/negcache.cc
- pdns/recursordist/negcache.hh
- pdns/recursordist/rec-main.cc
- pdns/recursordist/test-negcache_cc.cc
- pdns/recursordist/test-recursorcache_cc.cc
Backport of #12374
To be conservative, we might consider a minimal version of this for backporting. That would be the cachecleaner.h and test parts.
I have:
> rec: Backport 12374 to rec-4.8.x: make cache cleaning more fair when under pressure

- pdns/recursordist/docs/security-advisories/powerdns-advisory-2023-01.rst
Also, attribution line was lost.
I have:
> rec: Add a bit more explanation to advisory

- pdns/mtasker.cc
- pdns/mtasker.hh
- pdns/recursordist/docs/performance.rst
- pdns/recursordist/docs/settings.rst
- pdns/recursordist/lazy_allocator.hh
- pdns/recursordist/mtasker_context.hh
- pdns/recursordist/rec-main.cc
- pdns/recursordist/test-mtasker.cc
Place a `PROT_NONE` guard page at top and bottom of stack. Original work by @rgacogne with some tweaks by me.
I have:
> Rec: stack protector for mthread stacks

- pdns/cdb.cc
- pdns/dnsdistdist/test-dnsdistrings_cc.cc
> dnsdist: Fix a couple warnings reported by clang++

- pdns/recursordist/rec-main.cc
- pdns/recursordist/syncres.cc
- pdns/recursordist/syncres.hh
https://docs.powerdns.com/recursor/security-advisories/powerdns-advisory-2023-01.html
I have:
> rec:  Do *not* use QName Minimization for DS retrievals in QM fallback mode.

- tasks.py
> Enable the highest supported level of `FORTIFY_SOURCE` in our CI tests

- pdns/lock.hh
> lock.hh: include <stdexcept>

- pdns/dnsdist-cache.cc
- pdns/dnsdistdist/docs/advanced/axfr.rst
- pdns/dnsdistdist/docs/upgrade_guide.rst
- pdns/test-dnsdistpacketcache_cc.cc
- regression-tests.dnsdist/test_Caching.py
> dnsdist: Document interactions between XFR, NOTIFY and the cache

- pdns/opensslsigners.cc
Easy stuff, first commit is formatting (automated) and second commit is lint fixes (mostly automated). I suggest to review commit by commit.
I have:
> Openssl 3.0: RSA prep work

- docs/requirements.txt
- pdns/dnsdistdist/docs/requirements.txt
- pdns/recursordist/docs/requirements.txt
partial backport of #11167
I have:
> dnsdist-1.7: stop depending on lieter's copies of sphinx modules

- pdns/misc.cc
- pdns/misc.hh
clang-tidy assisted. Much more to be done, but this is it for now
I have:
> Assorted cleanup of misc.cc and misc.hh

- pdns/lock.hh
> dnsdist-1.7: lock.hh: include <stdexcept>

- pdns/recursordist/test_libcrypto
> rec: fix test_libcrypto's scan for dup libcrypto by using a proper pattern

- pdns/lock.hh
> rec-4.8: lock.hh: include <stdexcept>

- regression-tests/tkey.py
> auth tests tkey.py: explicitly use python3

- pdns/secpoll-recursor.cc
> rec: Backport 12467 to rec: 4.8.x: do not use "message" as key, it has a special meaning to systemd-journal

- pdns/dnsdist-lua.cc
- pdns/dnsdist-web.cc
- pdns/dnsdistdist/dnsdist-web.hh
- pdns/dnsdistdist/docs/reference/config.rst
- regression-tests.dnsdist/test_API.py
> dnsdist: Add an option for unauthenticated access to the dashboard

- pdns/recursordist/syncres.cc
- pdns/test-dnsdistpacketcache_cc.cc
> Fix two minor warnings

- tasks.py
> dnsdist: Enable Link-Time Optimizations in our CI

- pdns/dnsdist-web.cc
- pdns/dnsdistdist/docs/guides/webserver.rst
- pdns/dnsdistdist/docs/install.rst
- regression-tests.dnsdist/test_Caching.py
- tasks.py
> dnsdist: Add an API endpoint to remove entries from caches

- pdns/minicurl.cc
> MiniCurl: Fix building on versions older than 7.43.0

- pdns/dnsdist.cc
- regression-tests.dnsdist/test_Metrics.py
> dnsdist: Properly update rcode-related metrics on RCodeAction hits

- pdns/dnsdist-lua.cc
- pdns/dnsdist-tcp.cc
- pdns/dnsdist.hh
- pdns/dnsdistdist/Makefile.am
- pdns/dnsdistdist/dnsdist-concurrent-connections.hh
- pdns/dnsdistdist/docs/upgrade_guide.rst
- pdns/dnsdistdist/doh.cc
- regression-tests.dnsdist/test_DOH.py
> dnsdist: Apply the max number of concurrent conns per client to DoH

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.8.rst
- pdns/recursordist/docs/upgrade.rst
> rec: Prep for rec-4.8.2

- .github/actions/spell-check/expect.txt
- pdns/recursordist/docs/upgrade.rst
> Fix spelling issues

- pdns/recursordist/rec-lua-conf.cc
- pdns/recursordist/rec-main.cc
- pdns/recursordist/reczones.cc
Adjust logging levels for a couple of messages that don't appear to be particularly fatal-error and fix a typo in another.
I have:
> Logging tweaks

- pdns/dnsdistdist/Makefile.am
- pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
<strike>This PR is based on #12417 and will have to be rebased.</strike>
I have:
> dnsdist: Add unit tests for the Lua FFI interface

- builder-support/specs/dnsdist.spec
As far as I can tell, #12481 forgot to remove this one line.
I have:
> dnsdist rpm builds: stop trying to ship dnsdist.conf.sample

- pdns/opensslsigners.cc
- pdns/test-signers.cc
Support OpenSSL 3.0 in the RSA signer.
I have:
> OpenSSL3.0: RSA signer

- .github/workflows/documentation.yml
- tasks.py
- Add short commit hash to html doc artifacts that are uploaded to GH.
- Always build and GH artifact upload documentation PDFs since installing their deps doesn't take that much time anymore.
- Add the product (auth/rec/dnsdist) name to the html doc artifacts.
I have:
> Misc additions and changes to CI documentation generation

- .github/workflows/documentation.yml
> Fix GH CI docs upload

- .github/workflows/codeql-analysis.yml
> codeql workflow: set ubuntu mirror

- pdns/opensslsigners.cc
- pdns/test-signers.cc
Support OpenSSL 3.0 in the ECDSA signer.
I have:
> OpenSSL 3.0: ECDSA signer

- pdns/dnsdist-console.cc
- pdns/libssl.cc
Small cleanups in `libssl.cc` and `dnsdist-console.cc`.
I have:
> Small cleanups in `libssl.cc` and `dnsdist-console.cc`

- README.md
Changed copyright date from "2021" to "2023" to match the official docs at https://doc.powerdns.com/authoritative/
I have:
- [N/A] included documentation (including possible behaviour changes)
- [N/A] documented the code
- [N/A] added or modified regression test(s)
- [N/A] added or modified unit test(s)
> Update copyright to 2023

- pdns/ixfrdist-stats.cc
- regression-tests.ixfrdist/test_Stats.py
Draft status because this lives on top of #12489 which is not merged yet.
I have:
> ixfrdist /metrics: add CPU and memory stats, note unit for uptime

- pdns/opensslsigners.cc
Cleanup (formatting, lints) of the EdDSA signer. Mostly automated changes.
I have:
> EdDSA signer cleanup

- pdns/opensslsigners.cc
Support OpenSSL 3.0 in the EdDSA signer. Since the EdDSA signer was already using the EVP API there aren't any implementation changes. What is changed are a few cleanups and refactoring, plus using `pdns::OpenSSL::error` for exceptions where it makes sense.
I have:
> OpenSSL 3.0: EdDSA signer

- .not-formatted
- pdns/opensslsigners.cc
Final formatting of `opensslsigners.cc` (automated) and remove it from `.not-formatted`.
I have:
> Final formatting of `opensslsigners.cc`

- pdns/ixfrdist-stats.cc
- pdns/ixfrdist-stats.hh
- pdns/ixfrdist.cc
- regression-tests.ixfrdist/test_Stats.py
- tasks.py
backport of #12489 #12494 #12510
I have:
> auth-4.7.x: ixfrdist fixes and improvements

- pdns/recursordist/docs/settings.rst
Fix typo in Recursor settings.rst. Credit to check-spelling bot.
I have:
> rec: Fix doc typo

- pdns/dnsdist-web.cc
As suggested by @dch (thanks!).
I have:
> dnsdist: Better wording for the 'no cache' case

- pdns/dnsdistdist/dnsdist-backend.cc
- regression-tests.dnsdist/test_Advanced.py
> dnsdist: Properly record the incoming flags on a timeout

- pdns/dnsdist-lua.cc
Long IPv6 addresses and huge weight and order values were not properly handled.
Fixes https://github.com/PowerDNS/pdns/issues/12370.
I have:
> dnsdist: Fix the formatting of 'showServers'

- .github/actions/spell-check/expect.txt
- pdns/dnsdist-lua.cc
- pdns/dnsdistdist/docs/advanced/tuning.rst
- pdns/dnsdistdist/docs/reference/config.rst
- pdns/libssl.cc
- pdns/libssl.hh
- pdns/tcpiohandler.cc
- pdns/tcpiohandler.hh
> dnsdist: Enable experimental kTLS support with OpenSSL on Linux

- pdns/dnsdist-web.cc
- pdns/dnsdistdist/docs/guides/webserver.rst
- regression-tests.dnsdist/test_Prometheus.py
Also make sure that we test the caching metrics in our regression tests.
Fixes #11799.
I have:
> dnsdist: Add prometheus type and help for 'cache_cleanup_count'

- pdns/dnsdistdist/docs/reference/config.rst
Closes https://github.com/PowerDNS/pdns/issues/10855
I have:
> dnsdist: Make it clearer that exactPathMatching was introduced in 1.6

- .github/workflows/misc-dailies.yml
Fixing version of ODBC packages in misc-dailies workflow.
I have:
> Apply odbc packages workaround to misc-dailies workflow

- regression-tests.dnsdist/test_Metrics.py
> dnsdist: Add regression tests for responses, cache metrics

- build-scripts/gh-actions-setup-inv
Avoid GRUB-related errors due to runner image configuration by reinstalling it.
I have:
> Workaround for grub error raised after apt-get dist-upgrade

- SECURITY.md
> Security policy: Our bug bounty program moved from HackerOne to YesWeHack

- pdns/minicurl.cc
- pdns/minicurl.hh
inspired by #12292, but as a much smaller change. Hopefully helps for #12426
I have:
> auth 4.7 minicurl: stop leaking hostlist memory

- .circleci/config.yml
- .github/workflows/build-and-test-all.yml
- tasks.py
Added LDAP and geoip-mmdb tests to GitHub Actions. Removed from CircleCI. Simplified collector job in build-and-test-all.yml.
I have:
> GH Actions: added ldap and geoip-mmdb tests. Removed from CircleCI.

- build-scripts/gh-actions-setup-inv
- tasks.py
Preparing apt operations to allow downgrades. Required for using ubuntu mirrors when installing/upgrading ODBC packages.
I have:
> Avoid Microsoft repo for ODBC packages. Step 1 of 3: allow apt downgrades

- .github/actions/spell-check/expect.txt
- docs/secpoll.zone
- pdns/dnsdistdist/docs/changelog.rst
> dnsdist: ChangeLog and secpoll update for 1.8.0-rc1

- pdns/pkcs11signers.cc
Some cleanup and support openssl 3 in `pkcs11signers.cc`.
I have:
> OpenSSL 3.0: PKCS11 signers

- build-scripts/docker/repo-test/generate-repo-files.py
> Add dnsdist-18 to repo test script.

- .github/workflows/codeql-analysis.yml
Preparing apt operations to allow downgrades. Required for using ubuntu mirrors when installing/upgrading ODBC packages.
I have:
> Avoid Microsoft repo for ODBC packages. Step 1b: codeql - allow apt downgrades

- modules/gpgsqlbackend/Makefile.am
- modules/remotebackend/Makefile.am
> auth: Add flags to find libssl includes to two modules needing them

- .github/workflows/build-and-test-all.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/misc-dailies.yml
- tasks.py
Cleanup manual installation of ODBC packages.
I have:
> Avoid Microsoft repo for ODBC packages. Step 3 of 3: cleanup manual installation of ODBC packages

- pdns/dnsdist.cc
- regression-tests.dnsdist/test_Advanced.py
The original destination was not properly updated: `hopLocal` contains the destination address of the packet we received, and matches `origDest` unless the proxy protocol is used, in which case `origDest` will be updated by the 'real' destination address as seen by the client and the first hop.
Reported by @phonedph1 (many thanks!).
Fixes https://github.com/PowerDNS/pdns/issues/12581.
I have:
> dnsdist: Fix the harvesting of destination addresses

- pdns/rec-lua-conf.cc
- pdns/recursordist/rec-main.cc
- pdns/reczones.cc
> rec: Backport 12495 to rex-4.8.x: Change a few logging urgency levels

- pdns/recursordist/test-syncres_cc7.cc
- pdns/syncres.cc
> rec: Backport 12598 to rec-4.8.x: Update validation state after a missing negative indication

- pdns/recursordist/negcache.cc
- pdns/recursordist/negcache.hh
- pdns/recursordist/test-negcache_cc.cc
- pdns/recursordist/test-syncres_cc10.cc
- pdns/syncres.cc
Combined backport of #12595, #12610  and #12611
I have:
> rec: Backport 12595, 12610 and 12611 to rec-4.8.x: fix serve-stale logic

- pdns/recursordist/test-syncres_cc10.cc
(cherry picked from commit 60a0965f82283249e8f054afe474adc33a57b8bc)
Backport of #12614 
I have:
> Rec: backport 12614 to rec-4.8.x: test that an ImmediateServFailException isn't hidden by the serve-stale logic

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.8.rst
> rec: Prep for rec-4.8.3

- .github/workflows/build-and-test-all.yml
- .github/workflows/builder.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/formatting.yml
- .github/workflows/fuzz.yml
- .github/workflows/secpoll.yml
- .github/workflows/spelling.yml
- Move to v2 for CodeQL action, v1 will be deprecated dec 2022 #11641 
- Switch from set-output to GITHUB_OUTPUT #12284 
- Restrict permissions for GITHUB_TOKEN in our workflows #12254
- Run scheduled workflows only if a var is set #12522 
- dnsdist: Disable the send wrappers in our CI #12316 
I have:
> dnsdist-1.7.x: Backport CI fixes

- .github/actions/spell-check/expect.txt
> Allow xdp and TSAN in our spell-checker

- docs/manpages/pdnsutil.1.rst
- remove stray `:`
- harmonize `...`
I have:
> docs: pdnsutil

- .github/workflows/build-and-test-all.yml
- .github/workflows/builder-dispatch.yml
- .github/workflows/builder.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/formatting.yml
- .github/workflows/fuzz.yml
- build-scripts/gh-actions-setup-inv
- tasks.py
Backporting updates in GH Actions for simplified collector jobs and fixing warnings for deprecated actions.
I have:
> Backport GH Actions updates from master to rec-4.8.x

- contrib/_pdnsutil.zsh_completion
- contrib/pdnsutil.bash_completion.d
- docs/manpages/pdnsutil.1.rst
- pdns/pdnsutil.cc
Add the ability to list members of a catalog zone
Closes #12356
I have:
> auth: pdnsutil, implement list-member-zones

- docs/secpoll.zone
- pdns/dnsdistdist/docs/changelog.rst
Note that #12615 has not been merged yet<strike>, and that we might have to rebase this PR once #12620 has been merged.</strike>
I have:
> dnsdist: ChangeLog and secpoll update for 1.8.0-rc2

- .github/actions/spell-check/expect.txt
> spelling: re-add "TSAN" to expect.txt

- docs/running.rst
- pdns/recursordist/docs/manpages/pdns_recursor.1.rst
Describe the usually expected configuration (systemd as pid1) first, then refer to init scripts.
I have:
> Steer Linux users towards the supported service manager

- .github/workflows/build-and-test-all.yml
- .github/workflows/builder-dispatch.yml
- .github/workflows/builder.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/documentation.yml
- .github/workflows/formatting.yml
- .github/workflows/misc-dailies.yml
- .github/workflows/secpoll.yml
GitHub commits to honoring semver for its actions repositories, so let's limit the number of PRs dependabot needs to make
I have:
> GitHub actions follow major

- .github/workflows/build-and-test-all.yml
- .github/workflows/builder.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/fuzz.yml
- .github/workflows/secpoll.yml
- .github/workflows/spelling.yml
- .github/workflows/spelling2.yml
- build-scripts/gh-actions-setup-inv
- docs/requirements.txt
- pdns/dnsdistdist/docs/requirements.txt
- pdns/recursordist/docs/requirements.txt
- tasks.py
Backporting updates in GH Actions for simplified collector jobs and fixing warnings for deprecated actions.
I have:
> Backport GH Actions updates from master to rec-4.6.x

- docs/secpoll.zone
- pdns/dnsdistdist/docs/changelog.rst
- pdns/dnsdistdist/docs/upgrade_guide.rst
> dnsdist: Prepare ChangeLog and secpoll for 1.8.0-rc3

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.target.ubuntu-lunar
- builder-support/dockerfiles/Dockerfile.target.ubuntu-lunar-amd64
- builder-support/dockerfiles/Dockerfile.target.ubuntu-lunar-arm64
> add ubuntu:lunar builder target and test it daily

- .github/workflows/build-and-test-all.yml
- .github/workflows/builder-dispatch.yml
- .github/workflows/builder.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/formatting.yml
- .github/workflows/fuzz.yml
- build-scripts/gh-actions-setup-inv
- tasks.py
Backporting updates in GH Actions for simplified collector jobs and fixing warnings for deprecated actions.
I have:
> Backport GH Actions updates from master to rec-4.7.x

- .github/workflows/builder.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/fuzz.yml
- .github/workflows/secpoll.yml
- .github/workflows/spelling.yml
Backporting minor fixes on permissions and deprecated actions.
I have:
> Backport GH Actions updates from master to auth-4.5.x

- build-scripts/docker/repo-test/generate-repo-files.py
> Add auth-48 to repo test script.

- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.target.amazon-2023
- builder-support/specs/dnsdist.spec
- builder-support/specs/pdns-recursor.spec
- builder-support/specs/pdns.spec
> builder: add amazon-2023 target

- pdns/recursordist/negcache.cc
- pdns/recursordist/negcache.hh
- pdns/recursordist/test-negcache_cc.cc
> rec: fix a race in the negcache unit tests

- pdns/pdns_recursor.cc
- pdns/syncres.cc
Low severity
(CVE-2023-26437)
Backport of #12699
I have:
> rec: Backport 12699 to rec-4.8.x: Deterred spoofing attempts can lead to authoritative servers being marked unavailable

- pdns/pdns_recursor.cc
- pdns/syncres.cc
Low severity  (CVE-2023-26437)
Backport of #12699 
I have:
> rec: Backport 12699 to rec-4.7.x: Deterred spoofing attempts can lead to authoritative servers being marked unavailable 

- pdns/pdns_recursor.cc
- pdns/syncres.cc
Low severity (CVE-2023-26437)
Backport of #12699 
I have:
> rec: Backport 12699 to rec-4.6.x: Deterred spoofing attempts can lead to authoritative servers being marked unavailable 

- .github/actions/spell-check/expect.txt
- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.6.rst
- pdns/recursordist/docs/changelog/4.7.rst
- pdns/recursordist/docs/changelog/4.8.rst
- pdns/recursordist/docs/security-advisories/powerdns-advisory-2023-02.rst
> Prep for PowerDNS Security Advisory 2023-02

- .github/actions/spell-check/expect.txt
> spellcheck: Fix entry for memlock

- docs/secpoll.zone
- pdns/dnsdistdist/docs/changelog.rst
- pdns/dnsdistdist/docs/eol.rst
> dnsdist: Prepare ChangeLog and secpoll update for 1.8.0

- .github/actions/spell-check/expect.txt
- SECURITY.md
- docs/common/security-policy.rst
> change hackerone references to point to yeswehack

- pdns/recursordist/ednsextendederror.hh
- pdns/recursordist/syncres.cc
- regression-tests.recursor-dnssec/test_AggressiveNSECCache.py
- regression-tests.recursor-dnssec/test_RootNXTrust.py
> rec: Start using newly assigned "Synthesized" EDE

- build-scripts/test-recursor-bulk
This is relevant for the buildbot tests
I have:
> rec: Do not generate large not really useful test file containing names in powerdnssec.org in bulk test

- .github/actions/spell-check/allow.txt
- pdns/dnsdistdist/docs/changelog.rst
- pdns/dnsdistdist/docs/reference/config.rst
- pdns/pkcs11signers.cc
- regression-tests.dnsdist/test_DOH.py
`PKCS` instead of `PCKS`.  Everything is comments, docs, or in one instance a class name that is not actually important.
I have:
> Fix spelling of PKCS

- pdns/dnsdistdist/docs/reference/ebpf.rst
> dnsdist: fix formatting and `external` description

- .github/actions/spell-check/expect.txt
- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.9.rst
- pdns/recursordist/docs/changelog/index.rst
- pdns/recursordist/docs/performance.rst
- pdns/recursordist/docs/settings.rst
- pdns/recursordist/docs/upgrade.rst
> rec: Prep for rec-4.9.0-alpha1

- modules/lmdbbackend/lmdbbackend.cc
- regression-tests.api/test_TSIG.py
- regression-tests.api/test_helper.py
- regression-tests.nobackend/lmdb-metadata-leak/command
- regression-tests.nobackend/lmdb-metadata-leak/description
- regression-tests.nobackend/lmdb-metadata-leak/expected_result
- tasks.py
Backport lmdb delete fixes and tests from 3a52d52f0
I have:
> auth-4.7.x backport lmdb delete fixes and tests

- contrib/_pdnsutil.zsh_completion
- contrib/pdnsutil.bash_completion.d
- docs/manpages/pdnsutil.1.rst
- pdns/pdnsutil.cc
> auth-4.7.x: pdnsutil, implement list-member-zones

- pdns/dnsrecords.cc
- pdns/dnsrecords.hh
> auth-4.7.x: Prevent a race during the processing of SVC auto-hints

- docs/secpoll.zone
- pdns/dnsdistdist/docs/changelog.rst
Only a draft since:
- <strike>https://github.com/PowerDNS/pdns/pull/12622 needs to be reviewed and merged first</strike>
- <strike>the release date has not been decided</strike>
- <strike>we will need to update the serial of the secpoll zone, and it will likely conflict with other merges in the meantime</strike>
Draft status removed:
- Release date updated
- Serial updated
- Rebased against `master`
I have:
> dnsdist: Add ChangeLog and secpoll update for dnsdist 1.7.4

- build-scripts/docker/repo-test/generate-repo-files.py
This adds a minor feature to the repo test script where it reports the versions of the packages that were tested.
Ubuntu Bionic has been removed for auth-48 and dnsdist-18.
The script's version has finally been updated (as it should on every change).
```
$ ./generate-repo-files.py --test rec-48
=== testing rec-48 ===
Building Docker image using Dockerfile.rec-48.centos-7...
Running Docker container tagged rec-48.centos-7...
Building Docker image using Dockerfile.rec-48.debian-bullseye...
Running Docker container tagged rec-48.debian-bullseye...
Building Docker image using Dockerfile.rec-48.debian-buster...
Running Docker container tagged rec-48.debian-buster...
Building Docker image using Dockerfile.rec-48.el-8...
Running Docker container tagged rec-48.el-8...
Building Docker image using …
```
> Report Version when Testing Repositories

- docs/changelog/4.7.rst
- docs/secpoll.zone
> auth 4.7.4: secpoll and docs

- regression-tests.api/runtests.py
Since ab6031a1a1cbf914df56d908ab5eb259b101df17 stdout and stderr of the backgrounded pdns_server are captured in a pipe. This pipe has a default-limit of 64K on Linux. Exceeding this 64K limit causes tests to freeze with no further output or timeout at a more or less random point in the tests.
Found in GitHub Actions while working on #12086.
I have:
> api tests: avoid default pipe size limit

- regression-tests.dnsdist/requirements.txt
- regression-tests.recursor-dnssec/requirements.txt
- regression-tests/tests/.gitignore
- tasks.py
- Refactor some pyinvoke tasks
- Add missing cmake dependency for libdecaf
- Force clang-12 on libdecaf cmake build
- Use major versions for GH actions
I have:
> Ci fixes and cleanups

- pdns/recursordist/ws-recursor.cc
> rec: warning: variable 'total' set but not used

- docs/changelog/4.8.rst
- docs/secpoll.zone
> auth-4.8.0-beta1: secpoll&docs

- docs/changelog/4.8.rst
- docs/secpoll.zone
> bump secpoll serial, adjust release date

- .clang-tidy.full
> clang-tidy: Increase the code complexity threshold to 50 for now

- pdns/dnsdistdist/dnsdist-healthchecks.cc
> dnsdist: Print the received, invalid health-check response ID

- SECURITY.md
- docs/common/security-policy.rst
- docs/common/tarball-pgp-keys.rst
> docs: update GPG keyblock link

- .clang-tidy.full
- pdns/recursordist/rec-main.cc
> rec: delint rec-main.cc wrt high complexity

- regression-tests.recursor-dnssec/test_SimpleDoT.py
> rec: Fix DoT test to no use www.powerdns.com, as it changed

- .github/workflows/secpoll.yml
> secpoll check: use preferred ubuntu mirror

- pdns/recursordist/rec-main.cc
> rec: fix clang-tidy botch wrt spelling of "log-fail"

- docs/settings.rst
I think this more clearly describes the option
Specify what `config-dir` is
I have:
> Be more specific in describing config-dir

- .github/workflows/misc-dailies.yml
Set clang version 12 as environment variable for test `misc-dailies.yml` running on Ubuntu focal.
I have:
> GH actions - misc-dailies.yaml: set clang version for Ubuntu-20 

- .clang-tidy.full
- pdns/recursordist/rec-main.cc
- pdns/recursordist/rec-main.hh
- pdns/recursordist/syncres.hh
> rec: Full delint rec-main.cc

- .clang-tidy.full
- pdns/recursordist/rec-main.hh
- pdns/recursordist/rec-tcp.cc
- pdns/recursordist/syncres.hh
> Delint rec-tcp.cc

- pdns/validate.cc
> rec: fix typo in trace message

- pdns/recursordist/docs/appendices/FAQ.rst
- pdns/recursordist/docs/settings.rst
- pdns/recursordist/reczones.cc
- pdns/recursordist/syncres.cc
- pdns/recursordist/test-syncres_cc.cc
Fixes #12848
I have:
@SrX please take a look, thanks!
> rec: Introduce a way to completely disable root-refresh

- docs/settings.rst
- pdns/auth-main.cc
- pdns/pdnsutil.cc
- pdns/signingpipe.cc
- pdns/signingpipe.hh
- pdns/tcpreceiver.cc
> auth-4.8: add setting workaround-11804-max-chunk-records #12780

- pdns/pdnsutil.cc
> auth-4.8.x: pdnsutil: if user pushes unknown key in response to "problem with zone" prompt, do not throw away their changes

- docs/backends/lmdb.rst
- modules/lmdbbackend/lmdbbackend.cc
and enforce shards=1 in LS mode
backport of #12866
I have:
> auth-4.8.x: lmdb: delete duplicate domain entries in deleteDomain

- pdns/packethandler.cc
- regression-tests/tests/ent-asterisk/command
- regression-tests/tests/ent-asterisk/expected_result
- regression-tests/tests/ent-asterisk/expected_result.dnssec
- regression-tests/tests/ent-asterisk/expected_result.narrow
- regression-tests/tests/ent-asterisk/expected_result.nsec3
> auth-4.8.x: do not answer with broken TYPE0 data when expanding an ENT wildcard

- docs/changelog/4.8.rst
- docs/secpoll.zone
> auth-4.8.0: docs and secpoll

- .github/actions/spell-check/expect.txt
- docs/upgrading.rst
> auth upgrading: fix 4.6/4.7 header; update LMDB text

- docs/secpoll.zone
- pdns/recursordist/docs/appendices/FAQ.rst
- pdns/recursordist/docs/changelog/4.9.rst
- pdns/recursordist/docs/upgrade.rst
> rec: Prep for rec-4.9.0-beta1

- pdns/recursordist/rec-taskqueue.cc
- pdns/recursordist/rec-taskqueue.hh
- pdns/recursordist/taskqueue.cc
- pdns/recursordist/taskqueue.hh
- pdns/recursordist/ws-recursor.cc
- pdns/recursordist/ws-recursor.hh
- pdns/secpoll.cc
- pdns/zonemd.cc
- pdns/zonemd.hh
A set of random files made clean. During this process .clang-tidy.full was also amended a bit.
I have:
> Another set of delinting

- pdns/recursordist/pdns_recursor.cc
- pdns/recursordist/syncres.cc
- pdns/recursordist/syncres.hh
This is enough for now, mostly a metric only interesting to devs
I have:
> rec: keep track of max depth reached and report it if !quiet

- pdns/recursordist/docs/lua-config/rpz.rst
- pdns/recursordist/filterpo.hh
- pdns/recursordist/pdns_recursor.cc
- pdns/recursordist/rec-lua-conf.cc
- pdns/recursordist/rpzloader.cc
- pdns/recursordist/syncres.cc
- regression-tests.recursor-dnssec/test_RPZ.py
> rec: add SOA to RPZ modified answers if configured to do so

- pdns/recursordist/RECURSOR-MIB.txt
- pdns/recursordist/docs/metrics.rst
- pdns/recursordist/pdns_recursor.cc
- pdns/recursordist/rec-snmp.cc
- pdns/recursordist/rec-tcounters.hh
- pdns/recursordist/rec_channel_rec.cc
- pdns/recursordist/ws-recursor.cc
- regression-tests.recursor-dnssec/test_SNMP.py
> rec: expose NOD/UDR metrics

- .github/workflows/builder-dispatch.yml
> builder-dispatch: add debian-bookworm target to defaults

- .github/scripts/clang-tidy.py
backport of one commit from #12792
I have:
> auth-4.8: Don't fail when there are no warnings produced by clang-tidy

- pdns/Makefile.am
- pdns/speedtest.cc
> Fix build of speedtest and make sure it gets built automatically to avoid bitrot

- dockerdata/startup.py
Edited a single line which contais the webserver config template for dnsdist.
I have:
> edited webserver config template for dnsdist docker container.

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.9.rst
- pdns/recursordist/docs/metrics.rst
- pdns/recursordist/docs/upgrade.rst
> rec: Prep for rec-4.9.0-rc1

- pdns/dnsdistdist/dnsdist-healthchecks.cc
Backport of #12811 to rel/dnsdist-1.8.x
I have:
> dnsdist-1.8.x: Add the query ID to health-check log messages, fix nits

- pdns/recursordist/docs/lua-config/ztc.rst
> rec: fix documentation of zoneToCache localAddress attribute

- regression-tests.dnsdist/test_LuaFFI.py
> dnsdist: Add a regression test for the Lua FFI raw tag interface

- pdns/dnssecinfra.cc
Previous version could return true if the first iteration succeeded, but the second one threw. Spotted by pt01 on IRC.
I have:
> rec: Followup to #12893: Rewrite and fix verifyOne() loop

- pdns/recursordist/lwres.cc
Call should not fail and it's a best effort anyway in this case
I have:
> rec: Silence Coverity 1462719 Unchecked return value from library.

- pdns/dnsdistdist/Makefile.am
> dnsdist: add dnsdist-lua-inspection-ffi.h to dist tarballs

- pdns/channel.hh
> channel: Add an annotation so Coverity does not think we leak

- pdns/channel.hh
- pdns/dnsdistdist/dnsdist-async.cc
- pdns/dnsdistdist/dnsdist-async.hh
> dnsdist: Implement the AsynchronousHolder with the new channel feature

- pdns/recursordist/rec-main.cc
> rec: Backport 12928 to rec-4.9.x: fix daemonize()

- pdns/dnssecinfra.cc
> rec: Backport 12933 to rec 4.9.x: rewrite and fix verifyOne() loop

- pdns/dnsdist.cc
> dnsdist: fix typo

- pdns/dnsdist-dynblocks.hh
- pdns/dnsdist-lbpolicies.hh
- pdns/dnsdist-lua-actions.cc
- pdns/dnsdist-lua-bindings-dnsquestion.cc
- pdns/dnsdist-lua-bindings.cc
- pdns/dnsdist-lua-inspection.cc
- pdns/dnsdist-lua-rules.cc
- pdns/dnsdist-lua.cc
- pdns/dnsdist-web.cc
- pdns/dnsdistdist/dnsdist-discovery.cc
- pdns/dnsdistdist/dnsdist-lua-bindings-network.cc
- pdns/dnsdistdist/dnsdist-lua-network.cc
- pdns/dnsdistdist/dnsdist-rules.hh
- pdns/dnsdistdist/dnsdist-tcp.hh
- pdns/dnsparser.cc
- pdns/libssl.cc
- pdns/libssl.hh
- pdns/mplexer.hh
- pdns/tcpiohandler.cc
I don't expect these changes to actually make a difference in practice, because pretty much all of them impact configuration processing, where performance is not that critical. Still they should not hurt and a few of them (mplexer, OpenSSLTLSConnection, MOADNSParser) might actually improve some edge cases.
I have:
> dnsdist: Apply performance suggestions from Coverity

- pdns/recursordist/docs/performance.rst
> rec: give advice on a typical dnsdist-recursor setup with the new defauls

- pdns/recursordist/logging.cc
- pdns/recursordist/rec-main.hh
- pdns/recursordist/rec_channel_rec.cc
- pdns/recursordist/reczones-helpers.cc
- pdns/recursordist/reczones.cc
- pdns/recursordist/syncres.cc
- pdns/recursordist/syncres.hh
> rec: fix a set of move optimizations, as suggested by coverity

- .github/workflows/build-packages.yml
- .github/workflows/build-tags.yml
- .github/workflows/builder-dispatch.yml
- builder-support/dockerfiles/Dockerfile.debbuild
- builder-support/dockerfiles/Dockerfile.rpmbuild
This PR is a first step into better SLSA-compliance. It makes a few changes to our builder-dispatch workflow:
- generate sha256 hashes for all the artifacts generated (source tarballs and package tarballs) by the build process
- generate intoto provenance attestation for these artifacts using the generic provenance generator (https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/generic) 
At the moment the provenance attestation is only accessible as an action artifact, and is not uploaded along the other artifacts, which is something we might want to do.
The attestation states that the artifacts were generated on a GitHub action runner, and with which exact workflow and parameters.
The attestation can be visualized via `$ cat multiple.intoto.jsonl | jq -r …
> Builder-dispatch: Generate provenance for built artifacts

- pdns/dns.hh
- pdns/recursordist/lwres.hh
- pdns/recursordist/pdns_recursor.cc
- pdns/recursordist/rec-main.cc
- pdns/recursordist/rec-main.hh
- pdns/recursordist/rec-tcp.cc
- pdns/recursordist/syncres.hh
> rec: Delint pdns recursor.cc

- pdns/recursordist/syncres.cc
> rec: Backport 12963 to rec 4.9.x: fix qname length getting out-of-sync with qname-minimization iteration count

- docs/secpoll.zone
- pdns/recursordist/docs/appendices/EOL.rst
- pdns/recursordist/docs/changelog/4.9.rst
- pdns/recursordist/docs/performance.rst
- pdns/recursordist/docs/upgrade.rst
> Prep for rec-4.9.0

- pdns/dnsdistdist/docs/reference/config.rst
> Document the StatNodeStats.hits attribute.

- pdns/dnsdistdist/docs/reference/config.rst
> Document the trailing '.' in StatNode.fullname

- docs/http-api/zone.rst
This pull request fixes two small bugs in the HTTP API documentation.
I have:
> Documentation fix in HTTP API - zone.rst

- Docker-README.md
A minor patch to https://github.com/PowerDNS/pdns/pull/11961
I have:
> Update base Debian version in Docker docs

- modules/lmdbbackend/lmdbbackend.cc
> auth lmdb: add backend commands for checking & refreshing indexes

- m4/pdns_check_libcrypto.m4
> auth-4.8.x: Work around Red Hat 8 pooping the bed in OpenSSL's headers

- ext/yahttp/yahttp/reqresp.cpp
> auth-4.8: YaHTTP: Prevent integer overflow on very large chunks

- modules/lmdbbackend/lmdbbackend.cc
> auth 4.8 lmdb: add backend commands for checking & refreshing indexes

- ext/arc4random/Makefile.am
- ext/arc4random/arc4random.hh
Also a tiny bit of cleanup
Followup to #12931 
A few `redundant declaration` warnings remain, will try to fix them separately.
I have:
> Fix build: put arc4random.hh into _SOURCES

- docs/changelog/4.8.rst
- docs/secpoll.zone
> auth 4.8.1: docs & secpoll

- configure.ac
- ext/arc4random/Makefile.am
- ext/arc4random/arc4random.hh
- ext/arc4random/explicit_bzero.c
- ext/arc4random/includes.h
- m4/pdns_check_secure_memset.m4
- pdns/dnsdistdist/configure.ac
- pdns/dnsdistdist/ext/arc4random/explicit_bzero.c
- pdns/recursordist/configure.ac
- pdns/recursordist/ext/arc4random/explicit_bzero.c
- pdns/recursordist/m4/pdns_check_secure_memset.m4
The latter is needed on e.g. el-7
Followup to #12999 
This also fixes the redundant declaration warnings
I have:
> Fix build part2: include chacha_private.h and explicit_bzero.c

- pdns/dnsdist-carbon.cc
- pdns/dnsdist-web.cc
- pdns/dnsdist.hh
- pdns/dnsdistdist/dnsdist-backend.cc
- pdns/dnsdistdist/dnsdist-healthchecks.cc
- pdns/dnsdistdist/docs/guides/webserver.rst
- regression-tests.dnsdist/test_API.py
- regression-tests.dnsdist/test_HealthChecks.py
Closes https://github.com/PowerDNS/pdns/issues/12846.
I have:
> dnsdist: Add metrics for health-check failures

- pdns/recursordist/docs/changelog/4.9.rst
Make it a lil' clearer there is an upgrade guide
> Update recursor changelog

- pdns/dnsdistdist/docs/changelog.rst
> dnsdist changelog: fix indentation of this line

- pdns/dnsdistdist/docs/changelog.rst
Make it a lil' clearer that there is an upgrade guide
> Update dnsdist changelog

- pdns/version.cc
It's too hard to keep up-to-date and serves no real purpose.
Fixes #13004
I have:
> Do not include year(s) in copyright messages.

- README.md
- docs/conf.py
- pdns/dnsdistdist/docs/conf.py
- pdns/recursordist/README.md
- pdns/recursordist/docs/conf.py
- pdns/ws-auth.cc
> Further removal op copyright years

- docs/dnsupdate.rst
one-letter typo
I have:
- [s] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
> Typo in dnsupdate.rst

- ext/lmdb-safe/lmdb-typed.hh
- modules/bindbackend/bindbackend2.hh
- modules/geoipbackend/geoipbackend.cc
- modules/lmdbbackend/lmdbbackend.cc
- modules/lua2backend/lua2api2.hh
- modules/remotebackend/remotebackend.hh
- pdns/auth-main.cc
- pdns/dnsbackend.hh
- pdns/dnsreplay.cc
- pdns/dnssecinfra.cc
- pdns/dnssecinfra.hh
- pdns/dnswasher.cc
- pdns/dynlistener.cc
- pdns/pdnsutil.cc
- pdns/pkcs11signers.cc
- pdns/webserver.cc
- pdns/ws-api.cc
- pdns/ws-auth.cc
- pdns/zoneparser-tng.hh
> auth: Fix a bunch of warnings reported by Coverity

- pdns/recursordist/pdns_recursor.cc
Alternative solution to #13011
I have:
> rec: set TTL in getFakePTRRecords

- .github/workflows/build-packages.yml
- .github/workflows/builder.yml
- .github/workflows/documentation.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
I have:
> Switch from deprecated ::set-output

- regression-tests/runtests
Provide an annotation so that a run like https://github.com/jsoref/pdns/actions/runs/5654989194 is easier to understand
I have:
> Highlight why regression tests failed with github annotation

- docs/performance.rst
Documentation improvements to pdns authoritative.
I have:
> Queue limit and performance documentation

- .github/workflows/build-packages.yml
The name of the source tarball file has to be normalized first (authoritative -> pdns, recursor -> pdns-recursor) as well.
I have:
> build-packages: Fix provenance generation for the source tarball

- pdns/dnsbackend.cc
> auth: report which backend failed to instantiate

- pdns/pdns_recursor.cc
- pdns/recursordist/rec-main.cc
- pdns/recursordist/rec-main.hh
- pdns/recursordist/rec-tcp.cc
- regression-tests.recursor-dnssec/requirements.txt
- regression-tests.recursor-dnssec/test_Protobuf.py
- regression-tests.recursor-dnssec/test_SimpleDoT.py
> rec: Backport 13021 to rec-4.7.x: fix setting of policy tags

- pdns/pdns_recursor.cc
- pdns/recursordist/rec-main.cc
- pdns/recursordist/rec-main.hh
- pdns/recursordist/rec-tcp.cc
- regression-tests.recursor-dnssec/requirements.txt
- regression-tests.recursor-dnssec/test_Protobuf.py
- regression-tests.recursor-dnssec/test_SimpleDoT.py
> rec: Backport 13021 to rec-4.8.x: fix setting of policy tags

- pdns/recursordist/pdns_recursor.cc
- pdns/recursordist/rec-main.cc
- pdns/recursordist/rec-main.hh
- pdns/recursordist/rec-tcp.cc
- regression-tests.recursor-dnssec/test_Protobuf.py
> rec: Backport 13021 to rec-4.9.x: fix setting of policy tags

- pdns/calidns.cc
Fixes https://github.com/PowerDNS/pdns/issues/13015.
I have:
> calidns: Fix setting an ECS source of 0

- docs/domainmetadata.rst
> auth docs: remove domainmetadata/DNSSEC warning, has not been true for years

- pdns/recursordist/docs/upgrade.rst
> rec: Expand the note on max-recursion-depth in the upgrade notes

- pdns/distributor.hh
> auth: Refactor the MultiThreadDistributor using pdns::channel

- ext/lmdb-safe/lmdb-typed.hh
> auth 4.8 lmdb: when broadcasting indexes, -do- rewrite them even if they are unchanged

- docs/settings.rst
- pdns/recursordist/docs/settings.rst
Document default for `webserver-loglevel`
I have:
> Document default for `webserver-loglevel`

- regression-tests.ixfrdist/requirements.txt
- regression-tests.ixfrdist/runtests
nose is deprecated and does not work with py3.11
I have:
> ixfrdist: switch testing to pytest

- pdns/dnsdistdist/dnsdist-discovery.cc
note that the remaining check against `got` is theoretically useless, but leaving it in feels better
I have:
> coverity CID 398388: useless <0 check on unsigned value

- pdns/dnsdist-lua-bindings.cc
- pdns/dnsdistdist/docs/reference/dq.rst
- regression-tests.dnsdist/test_Lua.py
> dnsdist: Add a DNSHeader:getTC() Lua binding

- pdns/Makefile.am
- pdns/calidns.cc
- pdns/dnsbulktest.cc
- pdns/dnsgram.cc
- pdns/ixfrdist.cc
> tools: Address more Coverity warnings

- pdns/recursordist/rec-lua-conf.cc
- pdns/remote_logger.cc
62b191d seems to have introduced a few typos. Some have already been fixed while others still remain - hope to have caught most now.
I have:
#ottoneedsmoresleep
> Fix a few typos in log messages

- pdns/convert-yaml-to-json.py
Cleanup `convert-yaml-to-json.py`
I have:
> Cleanup `convert-yaml-to-json.py`

- pdns/recursordist/pdns_recursor.cc
- pdns/recursordist/syncres.cc
- pdns/recursordist/syncres.hh
- pdns/recursordist/test-syncres_cc10.cc
> rec: Do not assume the records are in a particular order when determining if an answer is NODATA

- pdns/channel.hh
- pdns/delaypipe.cc
- pdns/distributor.hh
- pdns/dnsdist-tcp.cc
- pdns/dnsdistdist/dnsdist-nghttp2.cc
- pdns/dnsdistdist/doh.cc
- pdns/snmp-agent.cc
- pdns/test-channel.cc
Hopefully this will prevent the kind of error fixed in #13147.
I have:
> channel: Make the blocking parameters of the object queue explicit

- pdns/ixfr.cc
- regression-tests.recursor-dnssec/test_RPZ.py
> rec: Backport 13105 to rec 4.7.x: (I)XFR: handle partial read of len prefix

- pdns/ixfr.cc
- regression-tests.recursor-dnssec/test_RPZ.py
> rec: Backport 13105 to rec 4.8.x: (I)XFR: handle partial read of len prefix

- pdns/ixfr.cc
- regression-tests.recursor-dnssec/test_RPZ.py
> rec: Backport 13105 to rec 4.9.x: (I)XFR: handle partial read of len prefix

- pdns/recursordist/rec-lua-conf.cc
- pdns/remote_logger.cc
(cherry picked from commit 84d2423481cff98765c482964d11ef828a2774d2)
Backport of #13151 
I have:
> rec: Backport 13151 to rec-4.9.x: Fix a few typos.

- pdns/recursordist/aggressive_nsec.cc
- pdns/recursordist/test-aggressive_nsec_cc.cc
> rec: Backport 13106 to rec 4.9.x: replace data in the aggressive cache if new data becomes available

- CODING_GUIDELINES.md
- CONTRIBUTING.md
We have had an internal version of this document for a while now, but there is no reason not to make it available to external contributors as well.
I have:
> Add a coding guidelines document to the public repository

- ext/json11/json11.cpp
- pdns/Makefile.am
- pdns/recursordist/ws-recursor.cc
- pdns/test-webserver_cc.cc
- pdns/webserver.cc
- pdns/webserver.hh
- regression-tests.api/test_Servers.py
- regression-tests.api/test_Zones.py
> Backport 13071 to rec 4.9.x: Fix code producing json

- pdns/dnsdist.cc
Backport of https://github.com/PowerDNS/pdns/pull/12941 to rel/dnsdist-1.8.x
I have:
> dnsdist-1.8.x: fix typo libeditr -> libedit

- dockerdata/startup.py
Backport of https://github.com/PowerDNS/pdns/pull/12916 to rel/dnsdist-1.8.x
I have:
> dnsdist-1.8.x: Fix webserver config template for our docker container

- pdns/dnsdistdist/dnsdist-dynblocks.cc
Backport of #12911 to rel/dnsdist-1.8.x
Regular, userspace blocks increment the "dyn blocked" counter for every dropped query. The eBPF blocks are executed in kernelspace and thus do not increment that counter at all, which makes it challenging for reporting to do its job. On the other hand we want our eBPF code to be as efficient as possible since it is used when performance really matters.
This commit updates the counter when a eBPF dynamic block is removed, which is a compromise between the performance impact and a slight reporting delay.
(cherry picked from commit e59686d645ff5d1652f2fdef109fff5d98d70ea2)
I have:
> dnsdist-1.8.x: Increment the "dyn blocked" counter for eBPF blocks as well

- pdns/dnsdist.cc
- pdns/dnsdist.hh
- pdns/dnsdistdist/dnsdist-backend.cc
- pdns/dnsdistdist/dnsdist-tsan.supp
Backport of #12726 to rel/dnsdist-1.8.x
I have:
> dnsdist-1.8.x: Properly handle reconnection failure for backend UDP sockets

- pdns/dnsdist.cc
- regression-tests.dnsdist/test_Metrics.py
Backport of https://github.com/PowerDNS/pdns/pull/12783 to rel/dnsdist-1.8.x
I have:
> dnsdist-1.8.x: Fix cache hit and miss metrics with DoH queries

- pdns/dnsdistdist/dnsdist-discovery.cc
- pdns/sstuff.hh
- regression-tests.dnsdist/dnsdisttests.py
- regression-tests.dnsdist/test_BackendDiscovery.py
Backport of #13113 to rel/dnsdist-1.8.x
I have:
> dnsdist-1.8.x: Properly handle short reads on backend upgrade discovery

- pdns/backends/gsql/gsqlbackend.cc
- pdns/dnsparser.cc
- pdns/dnsparser.hh
- pdns/qtype.cc
- pdns/qtype.hh
- pdns/rfc2136handler.cc
Backport of https://github.com/PowerDNS/pdns/pull/12776 to rel/dnsdist-1.8.x
I have:
> dnsdist-1.8.x: Make DNSQType.TSIG available in dnsdist

- pdns/dnsdist-carbon.cc
- pdns/dnsdist-lua-inspection.cc
- pdns/dnsdist-lua.cc
- pdns/dnsdist-web.cc
- pdns/dnsdist.hh
- pdns/dnsdistdist/Makefile.am
- pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
- pdns/dnsdistdist/dnsdist-lua-ffi.cc
- pdns/dnsdistdist/dnsdist-metrics.cc
- pdns/dnsdistdist/dnsdist-metrics.hh
- pdns/dnsdistdist/docs/reference/custommetrics.rst
- pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
- regression-tests.dnsdist/test_Advanced.py
Backport of https://github.com/PowerDNS/pdns/pull/12921 to rel/dnsdist-1.8.x.
I have:
> dnsdist-1.8.x: Allow declaring custom metrics at runtime

- .github/workflows/build-packages.yml
Check if `pkghashes` and `srchashes` entries were created for all targets in `build-packages.yml`.
I have:
> GH actions. build-packages.yml: check if hash entries were created for all targets

- docs/secpoll.zone
- pdns/recursordist/docs/changelog/4.7.rst
- pdns/recursordist/docs/changelog/4.8.rst
- pdns/recursordist/docs/changelog/4.9.rst
> rec: Prep for upcoming rec 4.7.6, 4.8.5 and 4.9.1 releases

- pdns/tcpiohandler.cc
We used to get a index from OpenSSL when the first incoming or outgoing TLS connection was created. That index is later used to store application-related data along the TLS connection, to be able to access it in callbacks called from inside the OpenSSL library.
Unfortunately the atomic flag construction used was racy: if a second connection is created while the first one is still getting the index, it could be reading the initial value (-1) instead of the actual index, which might prevent the callback from working properly because they cannot retrieve the necessary data. The good news is that this should not have a serious impact: a TLS session might not be properly resumed while it should have been, leading to a full TLS session negotiation. This commit fixes the race by using a full …
> TCPIOHandler: Fix a race when creating the first TLS connections

- pdns/recursordist/mtasker_ucontext.cc
(cherry picked from commit bbf76a06de324da40302d51850c7c475e465cb3a)
Backport of #13174 
I have:
> rec: backport 13174 to rec-4.9.x: Include cstdint in mtasker_ucontext.cc, noted by @zeha

- pdns/tcpiohandler.cc
We used to get a index from OpenSSL when the first incoming or outgoing TLS connection was created. That index is later used to store application-related data along the TLS connection, to be able to access it in callbacks called from inside the OpenSSL library.
Unfortunately the atomic flag construction used was racy: if a second connection is created while the first one is still getting the index, it could be reading the initial value (-1) instead of the actual index, which might prevent the callback from working properly because they cannot retrieve the necessary data. The good news is that this should not have a serious impact: a TLS session might not be properly resumed while it should have been, leading to a full TLS session negotiation. This commit fixes the race by using a full …
> dnsdist-1.8.x: TCPIOHandler: Fix a race when creating the first TLS connections

- modules/bindbackend/Makefile.am
- pdns/Makefile.am
- pdns/bindlexer.l
Bindlexer use C++ bison header
I have:
> Bindlexer use C++ bison header

- .github/workflows/build-packages.yml
- .github/workflows/builder-dispatch.yml
- builder-support/dockerfiles/Dockerfile.rpmbuild
- [Fix the generation of packages JSON list for provenance](https://github.com/PowerDNS/pdns/commit/99c370a2c30ae7152791d852fb7b37280ac35b22): the conditions were broken because our templating system supports a very limited syntax
- [build-packages: Fix 'check if hashes were created for all requested targets](https://github.com/PowerDNS/pdns/commit/00feba47c530579440085ba16248adcf4c2cc71f): If the 'inputs.os' list ends with a newline the check fails because the `for` loop syntax is wrong.
I have:
> Fix provenance generation for our packages

- pdns/recursordist/lwres.cc
- pdns/recursordist/lwres.hh
- pdns/recursordist/pdns_recursor.cc
- pdns/recursordist/rec-protozero.cc
- pdns/recursordist/syncres.cc
- pdns/recursordist/syncres.hh
Additionally, handle a few clang-tidy warnings
I have:
> rec: fix a few unused argument warnings (depening on features enabled)

- regression-tests.auth-py/runtests
- tasks.py
* switch from `docker-compose` to `docker compose`
* make apt more verbose
I have:
> auth-4.8: unbreak docker compose

- pdns/dnspacket.cc
> auth-4.8.x: Fix incorrect optsize

- ext/json11/json11.cpp
- pdns/Makefile.am
- pdns/recursordist/ws-recursor.cc
- pdns/test-webserver_cc.cc
- pdns/webserver.cc
- pdns/webserver.hh
- regression-tests.api/test_Servers.py
- regression-tests.api/test_Zones.py
> auth-4.8.x: fix code producing json

- .clang-tidy.full
- pdns/ixfr.cc
- regression-tests.recursor-dnssec/test_RPZ.py
> auth-4.8.x: (I)XFR: handle partial read of len prefix

- .github/ISSUE_TEMPLATE/bug_report.md
@Habbie is suffering from people not reading the open source items in the current issue template. This adds some check boxes...
I have:
> Add speed bumps to bug filing

- docs/changelog/4.8.rst
- docs/secpoll.zone
> auth-4.8.2: secpoll&docs

- .github/workflows/build-packages.yml
- .github/workflows/build-tags.yml
- .github/workflows/builder.yml
- builder-support/dockerfiles/Dockerfile.debbuild
- builder-support/dockerfiles/Dockerfile.rpmbuild
So we can get automatically built packages with provenance attestations for dnsdist 1.8.x releases.
I have:
> dnsdist-1.8.x: Backport the workflow to build packages from tags

- .github/actions/spell-check/expect.txt
- docs/secpoll.zone
- pdns/dnsdistdist/docs/changelog.rst
> dnsdist: Add ChangeLog and secpoll update for 1.8.1

- .github/workflows/build-packages.yml
> build-packages: Upload provenance attestations to the correct dir

- regression-tests/recursor-test
- regression-tests/runtests
Follow-up to #13068
I got the syntax wrong (sorry).
I have:
> Fix GitHub Action log title reporting

- pdns/recursordist/pdns-recursor.service.in
> rec: remove Before=nss-lookup.target line from unit file

- .github/workflows/build-and-test-all.yml
- tasks.py
Adding `make distdir` as an additional step during the build of all components in `build-and-test-all.yml`
I have:
> GH actions. build-and-test-all.yml: add make distdir as an additional step for build jobs

- .github/workflows/build-and-test-all.yml
> rec: With #13101 the cwd of the build changed, adapt call to ci-rust-install

- pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc
- pdns/recursordist/Makefile.am
I'll try to fix this after the 5.0.0-alpha1 release.
I have:
> Rec's unit tests (in combination with asan+ubsan) are not ready yet for randomization

- pdns/recursordist/settings/table.py
> rec: Fix wrongly converted default for "quiet"

- Dockerfile-recursor
- pdns/recursordist/settings/Makefile.am
- pdns/recursordist/settings/rust/Makefile.am
> rec: fix docker build; it does `make install` without first building the default target

- .github/actions/spell-check/expect.txt
- docs/secpoll.zone
- pdns/recursordist/docs/changelog/5.0.rst
- pdns/recursordist/docs/changelog/index.rst
- pdns/recursordist/docs/upgrade.rst
- pdns/recursordist/docs/yamlsettings.rst
> Prep for rec-5.0.0-alpha1

- pdns/recursordist/settings/cxxsupport.cc
> rec: Fix Coverityy 1519054: Using invalid iterator

- pdns/dnsdistdist/test-dnsdistnghttp2-in_cc.cc
- pdns/dnsdistdist/test-dnsdistnghttp2_cc.cc
- pdns/dnsdistdist/test-dnsdistnghttp2_common.hh
- pdns/dnsdistdist/test-dnsdisttcp_cc.cc
> dnsdist: Ensure our unit tests can be run in random order

- docs/settings.rst
- pdns/auth-main.cc
- pdns/ws-auth.cc
- regression-tests.api/runtests.py
- regression-tests.api/test_Zones.py
> auth-4.8: add default-catalog-zone setting

- docs/secpoll.zone
- pdns/dnsdistdist/docs/changelog.rst
- pdns/dnsdistdist/docs/upgrade_guide.rst
> dnsdist: Add ChangeLog and update secpoll for 1.9.0-alpha1

- pdns/dnsdistdist/docs/changelog.rst
- pdns/dnsdistdist/docs/statistics.rst
> dnsdist: Fix too short underline for latency-doh-avg1000000 title

- pdns/recursordist/docs/appendices/yamlconversion.rst
> rec: Clarify file name and placement rules for converted old-style files

- pdns/recursordist/docs/settings.rst
- pdns/recursordist/docs/yamlsettings.rst
- pdns/recursordist/rec-main.cc
- pdns/recursordist/settings/table.py
Fixes #13264
Also document what happens if quiet is set.
I have:
> rec: allow loglevel to be set to levels < 3

- pdns/recursordist/Makefile.am
The mthread fixes from #13251 should allow that now
I have:
> rec: Switch randomization of unit tests back on
