PowerDNS/pdns

pdns/dnsdist-tcp.cc, pdns/dnsdistdist/dnsdist-tcp-downstream.cc, pdns/dnsdistdist/dnsdist-tcp.hh, pdns/dnsdistdist/doh.cc, regression-tests.dnsdist/dnsdistdohtests.py, regression-tests.dnsdist/test_DOH.py, regression-tests.dnsdist/test_ProxyProtocol.py
Backport of #11604 to rel/dnsdist-1.7.x
dnsdist forwards incoming DoH queries to its backend over UDP, and
retry over TCP if the response is truncated (TC=1).
When the proxy protocol is used between dnsdist and its backend, the
second query, over TCP, needs to take into account that the proxy
protocol payload has already been handled. This was not properly done
in that exact case because the proxy protocol payload length was not
propagated to the code handling the TCP communication, leading to
the query ID being edited at the wrong offset in the packet and thus
to an invalid proxy protocol payload.
I have:
=> dnsdist-1.7.x: Fix invalid proxy protocol payload on a DoH TC to TCP retry

.github/actions/spell-check/expect.txt, pdns/dnsdist-carbon.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-web.cc, pdns/dnsdist.hh, pdns/dnsdistdist/dnsdist-prometheus.hh, pdns/dnsdistdist/dnsdist-web.hh, pdns/dnsdistdist/docs/reference/custommetrics.rst, pdns/dnsdistdist/docs/reference/index.rst, regression-tests.dnsdist/test_API.py, regression-tests.dnsdist/test_Advanced.py
This PR adds a few functions to declare and manipulate user-defined metrics. Currently supports `gauge` and `counter` types with set, increment and decrement operations.
I have:
=> dnsdist: add support for user defined metrics

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc, pdns/dnsdist.cc, pdns/dnsdistdist/docs/reference/config.rst, pdns/dolog.hh, pdns/test-dnscrypt_cc.cc
This pull request:
- sends 'verbose' message at syslog's 'debug' level instead of 'info'
- adds a new configuration option, `setVerboseLogDestination(dest)` which, when used at configuration time, redirects these messages to a file instead of sending to the standard output and/or syslog.
This is useful to be able to log these messages separately when investigating an issue, without flooding the system logs.
I have:
=> dnsdist: Optionally send 'verbose' messages to a file, and log them at 'DEBUG' level otherwise

pdns/dnsdistdist/doh.cc, regression-tests.dnsdist/test_ProxyProtocol.py
Backport of #11621 to rel/dnsdist-1.7.x
<strike>This PR is based on https://github.com/PowerDNS/pdns/pull/11665 and therefore will need to be rebased after that one has been merged.</strike>
I have:
=> dnsdist-1.7.x: Fix a crash on a invalid protocol in DoH forwarded-for header

contrib/xdp-filter.ebpf.src, contrib/xdp.py, ext/libbpf/libbpf.h, pdns/bpf-filter.cc, pdns/bpf-filter.hh, pdns/dnsdist-console.cc, pdns/dnsdist-lua-bindings.cc, pdns/dnsdistdist/docs/reference/ebpf.rst, pdns/iputils.hh
=> use BPF_MAP_TYPE_LPM_TRIE for range matching

Makefile.am, ext/lmdb-safe/lmdb-safe.hh, ext/lmdb-safe/lmdb-typed.hh, pdns/dnsname.hh, pdns/dnsparser.hh, pdns/dnsrecords.cc, pdns/dnsrecords.hh, pdns/iputils.hh, pdns/packetcache.hh, pdns/recursordist/.gitignore, pdns/recursordist/Makefile.am, pdns/recursordist/reczones-helpers.cc, pdns/recursordist/reczones-helpers.hh, pdns/recursordist/test-reczones-helpers.cc, pdns/reczones-helpers.cc, pdns/reczones-helpers.hh, pdns/reczones.cc, pdns/syncres.cc, pdns/syncres.hh, pdns/test-iputils_hh.cc
This adds the missing parts to load IPv6 entries from a provided `etc-hosts` file:
* Adds support for reversing IPv4 and IPv6 addresses to `ComboAddress`. Also adds tests for that.
* Replaces the usage of strings for IP addresses with `ComboAddress`.
* Moves a few things around for testability (in a separate commit).
* Also breaks down some parts into smaller functions (also in a separate commit).
* Fixes a pre-existing issue where `PTR` entries were being added for aliases (i.e. "non canonical hostname(s)").
* Adds tests for the pre-existing IPv4-only functionality in `test-reczones-helpers.cc`.
* Also adds tests for loading IPv6 entries as well.
* Adds the ability to print domain maps and their corresponding record entries to a `std::stringstream`.
* The usual misc cleanups & clang-tidy …
=> Recursor: Load IPv6 entries from `etc-hosts` file

pdns/pdnsutil.cc
This bug fix resolves the input prompt appearing before the options are flushed, in specific shells.
Also fixes: Input prompts appearing on a new line.
I have:
=> Pdnustil flush prompt

pdns/recursordist/docs/settings.rst, pdns/ws-recursor.cc, regression-tests.api/test_RecursorConfig.py
=> Backport 11609 to rec 4.6.x: Fix API issue when asking config values for allow-from or allow-notiy-from 

pdns/rec_channel_rec.cc, pdns/recursordist/rec-main.cc, pdns/syncres.cc, pdns/syncres.hh
This case is bit more tricky compared to the other maps as we context switch and another request/thread might update the status.
The original code refers back to  `mode` to compute the new state, but I think that should be  `EDNSLevel`, to handle the case of mandatory EDNS correctly: in that case we send with EDNS even if mode is `No`.
Also, the original code is a little complex:  it saves the old mode and it uses a pointer to the current mode, It uses those to only change the record if needed. I decide to move that logic to the actual modifier method.
Lastly, the loop is executed at most 3 times according to the original code. I think that should be 2, as we only case we continue is when we set the mode to `NOEDNS`. I did tests on master with 1M names and `assert(tries < 2)` and never …
=> Rec: shared ednsmap

pdns/dnsdist.cc, pdns/iputils.cc, pdns/iputils.hh
=> dnsdist: refactor sendfromto

pdns/recursordist/rec-main.cc, pdns/recursordist/test-syncres_cc1.cc, pdns/syncres.cc, pdns/syncres.hh
Only store exceptional status: `Ignorant` or `No`. Including cleanup of timestamp handling.
An `OK` entry now does not expire, as it is not stored. An `Ignorant` or `Bad` status will expire after two hours. After that the IP will be probed again. To avoid unnessesary churn, timestamps will only be set on initial status update or change. After two hours the status will be reset to OK by removing the entry, and potentially a new state will be created after that.
If an `Ignorant` entry turns out to be `OK` it will be erased.
I have:
=> Rec: make edns table a sparse table

pdns/recursordist/docs/settings.rst, pdns/recursordist/rec-main.cc
As @mnordhoff noted, the new systemd-journal backend isn't nice for human consumption. So switch back to the row of `k=v` pairs output by default and introduce a setting to use the systemd-journal backend. This setting also allows for other backends to be used (in the future).
Also: respect loglevel. The traditional output was filtered, but for structured logging, that was not done. While there, shortcut the traditional way as well, to avoid unnecessary churn.
Should fix #11705 and #11706
I have:
=> Rec: systemd-journal structured logging followup

pdns/dnsdist-lua-bindings.cc, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/docs/reference/dnsname.rst, pdns/dnsname.hh, pdns/test-dnsname_cc.cc
This PR adds a new method, `SuffixMatchTree::getBestMatch()` making it possible to know against which name from a `SuffixMatchTree` we matched.
It also adds lua bindings for that method in dnsdist, as well as bindings for a few more `DNSName` methods.
I have:
=> Implement `SuffixMatchTree::getBestMatch()` to get the name that matched

pdns/dnsdist-tcp.cc, pdns/dnsdist-web.cc, pdns/dnsdist.cc, pdns/dnsdistdist/dnsdist-nghttp2.cc, pdns/dnsdistdist/dnsdist-tcp-downstream.cc, regression-tests.dnsdist/test_API.py
Also properly report the latency as TCP when forwaring a query received over UDP to TCP-only, DoT and DoH backends.
And export the TCP latency in the prometheus and API metrics.
I have:
=> dnsdist: Compute backend latency earlier, to avoid internal latency 

pdns/dnsdistdist/dnsdist-backend.cc, pdns/dnsdistdist/dnsdist-discovery.cc, pdns/dnsdistdist/dnsdist-healthchecks.cc, pdns/dnsdistdist/dnsdist-tcp-downstream.cc
In some cases we want to bind to a specific interface when contacting a backend without specifying an exact source address, leaving the kernel select one for us.
I have:
=> dnsdist: Bind to the requested src interface without a src address

pdns/dnsdist-lua-inspection.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/doh.cc, regression-tests.dnsdist/test_DynBlocks.py
This tries to make sure we call `handleResponseSent()` when returning directly a self generated answer (like when serving from the packet cache).
`grepq()` display is now:
```
-2.3    127.0.0.1:60976                                 DoUDP                     11991 www.example.com.          A               RD    Question
-2.2    127.0.0.1:60976                                 DoUDP        9.9.9.9:53   11991 www.example.com.          A     102.7     RD    No Error. 1 answers
-1.7    127.0.0.1:52311                                 DoUDP                     25359 www.example.com.          A               RD    Question
-1.7    127.0.0.1:52311                                 -            Cache        25359 www.example.com.          A     0.0       RD    No Error. 1 answers
```
I was a bit …
=> dnsdist: fill ringbuffers with responses served from the cache

pdns/dnsdist-lua.cc
This should make sure that our signal handler wins over any signal handlers installed by threads.
I have:
=> dnsdist newThread(): mask SIGTERM

pdns/dnsdistdist/dnsdist-tcp-downstream.hh
When we are in the process of sending a query to the backend, that query is no longer accounted in the "queued" queries nor it is in the "queued" responses, but we need to take it into account.
Otherwise we might be sending two concurrent queries to a backend that does not support out-of-order processing (increasing our latency), or even worse to one that does not support pipelining.
I have:
=> dnsdist: Fix the number of concurrent queries on a backend TCP conn

pdns/dnslabeltext.rl, pdns/dnsname.cc
The test in `dnslabeltext.rl` should be exactly equivalent, but not cause a compiler warning on platforms where `char` is unsigned.
The test in `dnsname.cc` gets more strict, it will now detect illegal label lengths on all platforms, not just > 127 only on platforms where `char` is signed, as it does before this PR.
I have:
=> Fix warnings found by compiler on MacOS, where char is unsigned

pdns/syncres.cc
This makes the view of the record cache consistent with what syncres thinks. This will become important in the near future.
This `> 5` has been there since
https://github.com/PowerDNS/pdns/commit/7bf2638379826e89d655194bf5834bd7deda450a
I *suppose* it was to prevent accessing data from the cache while it could be cleaned by another thread.
But these days we copy data from the cache, so no need for that this "safeguard". Apart from that I wonder what would happen if we encounter glue records with ttl < 5 (not that those would make any practical sense).
I have:
=> rec: remove > 5 check on ttl of glue from the cache.

build-scripts/docker/repo-test/generate-repo-files.py
Remove EOL releases from repo test script.
Also merge code blocks spread out over identical conditional statements.
Tested by running:
- `generate-repo-files.py --test auth-47`
- `generate-repo-files.py --test rec-47`
- `generate-repo-files.py --test dnsdist-17`
Diff is confusing, check actual code. It's not much.
I have:
=> Clean up repo test script.

modules/lmdbbackend/lmdbbackend.cc, pdns/backends/gsql/gsqlbackend.cc
These Bind and remote backends return true when at least a TSIG key is returned, as expected by the API and pdnsutil code, but the GSQL backend returned false if at least a key was returned and true otherwise. The LMDB backend always returned false.
This caused `pdnsutil b2b-migrate` not to migrate TSIG keys from a GSQL or LMDB backend, amongst other things.
I have:
=> auth: Fix getTSIGKeys() return value in GSQL and LMDB backends

regression-tests.nobackend/tinydns-data-check/expected_result, regression-tests/tests/1dyndns-update-add-delete-txt/command, regression-tests/tests/1dyndns-update-add-delete-txt/expected_result
This should unbreak CI.
I have:
=> auth 2136: in recently added TXT tests, hide SOA details

pdns/recursordist/rec-main.cc
Previously, this was only done if log-common-errors was true, due
to argument reversal.  In general task *would* be executed, as they
are also run after each query processed by SyncRes (so not after
packet cache hits).
Thanks to @jelu!
(cherry picked from commit c42b6632e00eaa93911ce88a0b4aa8c598441e2a)
Backport of #11692 
I have:
=> rec: Backport 11692 to rec-4.7.x: Run tasks from houskeeping thread in a proper way.

pdns/lwres.cc, pdns/recursordist/rec-tcp.cc
No earth-shattering speed differences in my limited testing, but the nature of DNS message exchange is such that they should benefit from TCP_NODELAY.
In response to #11734 
I have:
=> rec: Set TCP_NODELAY on in and outgoing TCP

pdns/dnsdistdist/configure.ac, pdns/dnsdistdist/dnsdist-random.cc
It turns out to use much less CPU than RANDOM_bytes() from libcrypto.
I have:
=> dnsdist: Use getrandom() if available

pdns/dnsdistdist/dnsdist-tcp-downstream.cc
Setting `TCP_NODELAY` disables Nagle's algorithm, which is unfortunately not always playing nice with TCP delayed ACKs. This is especially true when the backend supports out-of-order processing, allowing dnsdist to send several queries at once without waiting for an answer. In that case dnsdist often has to wait several milliseconds (20ms is common) before
the remote end decides to send the delayed ACK which allows us to send the next query.
Note that this could lead to more TCP segments being sent by dnsdist instead of being aggregated, but in practice we already take care of sending a DNS query as a single `send()` syscall whenever possible.
I have:
=> dnsdist: Set TCP_NODELAY on the TCP connection to backends

pdns/dnsdist-ecs.cc, pdns/dnsdist-ecs.hh, pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua-bindings-dnsquestion.cc, pdns/dnsdistdist/docs/rules-actions.rst, pdns/test-dnsdist_cc.cc, regression-tests.dnsdist/test_RulesActions.py
This allow generating a full NODATA/NXDOMAIN cachable negative response, rather than an RPZ-style reponse with only an informational SOA record in the additional section.
I have:
=> Add option to NegativeAndSOAAction to place SOA in the authority section

modules/bindbackend/bindbackend2.cc
Removes a superfluous `if` and folds both branches which had identical behavior.
Concerning the checklist: As the code makes no changes to the behavior, there is no documentation and no additional tests, everything works exactly as before.
See also #11549.
=> auth: Simplify code in `Bind2Backend::lookup()`

pdns/lwres.cc, pdns/recursordist/test-mtasker.cc, pdns/syncres.cc
All considered harmless by code inspection, but the compiler on jammy does not realise that.
I have:
=> rec: Uninited vars, seen by compiling on jammy

modules/lmdbbackend/lmdbbackend.cc
backport the relevant parts of #11764
I have:
=> auth-4.6.x: fix deleteDomain() in lmdb backend

build-scripts/docker/repo-test/generate-repo-files.py
=> Add auth-46 and rec-47 for Ubunty Jammy to repo test script.

.github/workflows/builder.yml, builder-support/dockerfiles/Dockerfile.rpmbuild, builder-support/dockerfiles/Dockerfile.target.centos-9-stream, builder-support/dockerfiles/Dockerfile.target.el-9, builder-support/dockerfiles/Dockerfile.target.el-9-amd64, builder-support/dockerfiles/Dockerfile.target.el-9-arm64, builder-support/specs/pdns.spec
This branch successfully builds EL9 packages, but there is some work left:
Fixes #11753
=> EL9 builds

docs/settings.rst
This patch documents sending NOTIFY on non-standard ports for `also-notify`.
I have:
=> Update `also-notify` docs for non-standard ports

pdns/syncres.cc
Fixes #11736 in the most basic way. There are some plans to unify
the various NS state tables into a single elaborate data structure,
that would be the moment to store a moving average or similar.
Also modify the output a bit: show times in ms instead of us and
without all the decimals.
Example output:
```
; nsspeed dump follows
; nsname        timestamp       [ip/decaying-ms/last-ms...]
a6-192.akamaiedge.net   2022-07-12T13:59:29.585 23.211.133.192/4.440/8.837
usw6.akam.net   2022-07-12T13:59:25.472 23.61.199.64/423.307/1000.000
ns6-194.akamaiedge.net  2022-07-12T13:59:29.585 95.100.168.194/5.835/14.186
ns5-194.akamaiedge.net  2022-07-12T13:59:29.585 184.85.248.194/11.788/28.661
a11-192.akamaiedge.net  2022-07-12T13:59:29.585 84.53.139.192/6.843/10.938      2600:1480:1::c0/14.585/18.466 …
```
=> rec: Save the last nsspeed recorded plus output it in rec_control dump-nsspeeds

modules/bindbackend/bindbackend2.hh, modules/bindbackend/binddnssec.cc, modules/lmdbbackend/lmdbbackend.cc, modules/lmdbbackend/lmdbbackend.hh, modules/remotebackend/remotebackend.cc, modules/remotebackend/remotebackend.hh, modules/remotebackend/test-remotebackend.cc, pdns/backends/gsql/gsqlbackend.cc, pdns/backends/gsql/gsqlbackend.hh, pdns/dnsbackend.hh, pdns/dnspacket.cc, pdns/mastercommunicator.cc, pdns/slavecommunicator.cc, pdns/tcpreceiver.cc, pdns/ueberbackend.cc, pdns/ueberbackend.hh, pdns/ws-auth.cc
Stop after the first backend with TSIG support (like we do with metadata and cryptokeys)
I have:
=> auth: getTSIGKey(s) cleanup

pdns/dnsbulktest.cc
ubsan spotted the unitialised value
I have:
=> dnsbulktest: initialise struct member; use correct type when setting it

pdns/lua-base4.hh, pdns/recursordist/rec-main.cc
Fixes #11818 #10079
Regard "not able to read Lua script" on startup as fatal. Try to avoid this bug in the future by marking `loadFile` `[[nodiscard]]`
I have:
=> rec: Handle file related errors initially loading Lua script.

pdns/dnsdistdist/docs/reference/config.rst
Tiny change in wording to alleviate some confusion #11810 that I had when configuring dnsdist packet cache with DNS cookies.
Before merging please confirm that if `cookieHashing=false`, and `skipOptions` is set to a list of values not including DNS cookies explicitly, cookies still will not be hashed.
Does not change any code.
I have:
=> dnsdist: docs clarification on cookie hashing

pdns/dnsdist.cc
Ref. #4155
Also reconnect on ENETUNREACH.
On Ubuntu 22.04/dnsdist 1.6.1 I get `ENETUNREACH` errno for backend servers only accessible through VPN.
I hid these backends in a `PoolAvalilableRule`, and this works, but when VPN is up again, all DNS packets to the backends are dropped.
After adding the check for `ENETUNREACH` dnsdist is able to resume using these backends.
I've added a `strerror()` wrap around the errno for good measure, as I found the numeric errno less than helpful.
I have:
=> Also reconnect on ENETUNREACH.

pdns/reczones.cc
Fix a race between (re)loading an authzone and wiping the caches.
I have:
=> Clear the caches *after* loading authzones.

regression-tests.dnsdist/test_CDB.py
dnsdist will only automatically reload the CDB file if the mtime changed, but the mtime might not change if the update to the file happens at the exact same second than the first write.
I have:
=> dnsdist: Fix a possible race in the CDB reload regression tests

pdns/dnsdistdist/dnsdist-discovery.cc, pdns/dnsdistdist/dnsdist-discovery.hh
We were updating the timer of a copy, instead of the object representing the backend we are trying to upgrade.
I have:
=> dnsdist: Use the correct delay when a backend cannot be upgraded to Do{T,H}

pdns/dnsdist.cc
The latency was counted twice, and the frontend-nxdomain, frontend-noerror and frontend-servfail was increased twice as well.
I have:
=> dnsdist: Fix latency and counters update for UDP cache hits

pdns/dnsdist.cc
We no longer need it after that initial health-check round so it is only wasting (a very small amount of) memory and one file descriptor at that point.
I have:
=> dnsdist: Do not keep the mplexer created for the initial health-check around

pdns/dnsdist-carbon.cc, pdns/dnsdist-lua-inspection.cc, pdns/dnsdist-web.cc
This commit ensures that we don't crash if we forget to update a part of code if we ever add a new type of metrics, as happened in 9f4fa5ae01efa878d2aa27e4398740d7ed6ef01f.
I would prefer to refactor all the places in one single function, but the output formats differ too much.
I have:
=> dnsdist: Better handling of the different types of metrics

pdns/dnsdistdist/doh.cc
The current code is calling `h2o_socket_getpeername()` and `h2o_socket_getsockname() `once per DoH _query_, and while the former is cheap because h2o caches the result for us, the latter is actually expensive, so this code caches both values so that we only retrieve
them once per DoH connection.
I have:
=> dnsdist: Only call getsockname() once per incoming DoH connection

pdns/pdns_recursor.cc, pdns/rec-lua-conf.cc, pdns/rec-lua-conf.hh, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh
- Avoid reloading Lua config if it hasn't changed
- Asynchronously destroys dnstap connections from the old config in case of reload
Fixes #11795
I have:
=> Fix recursor not responsive after Lua config reload

pdns/dnsdist-lbpolicies.hh, pdns/dnsdist.hh, pdns/dnsdistdist/dnsdist-backend.cc, pdns/dnsdistdist/dnsdist-lbpolicies.cc
We only need to take the lock to get the shared pointer, as the actual content is guaranteed not to change, so we do not need to hold the lock while we iterate over the servers list to check whether they are up, or what their current outstanding count is.
I have:
=> dnsdist: Slightly reduce contention around a pool's servers

pdns/pdns_recursor.cc, pdns/recursordist/docs/dns64.rst, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_DNS64.py
RFC 6147 section 5.1 says: all RCodes except NXDomain should be candidate for dns64.
The current code only considers dns64 if RCode == NoError
We also restructure things a bit to get rid of most of the repeated lines handling `policyResult`.
To be added: tests
I have:
=> Rec: consider dns64 processing in more cases than Rcode == NoError

pdns/rec-snmp.cc, pdns/rec_channel_rec.cc, pdns/recursordist/RECURSOR-MIB.txt, pdns/recursordist/docs/metrics.rst, pdns/recursordist/rec-main.cc, pdns/syncres.hh, pdns/ws-recursor.cc
Fixes #6981
If we think it will provide useful numbers, we could split the metrics in a general maintenance and Lua maintenance.
I have:
=> rec: Keep time and count metrics when maintenance is called.

pdns/pdns_recursor.cc, pdns/rec-lua-conf.cc, pdns/rec-lua-conf.hh, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh
Backport #11850 (Fix recursor not responsive after Lua config reload) to rec 4.7.x
I have:
=> Backport #11850 (Fix recursor not responsive after Lua config reload) to rec 4.7.x

pdns/dnsdist-lua-actions.cc, pdns/fstrm_logger.cc, pdns/fstrm_logger.hh, pdns/lwres.cc, pdns/lwres.hh, pdns/recursordist/rec-main.cc, pdns/remote_logger.cc, pdns/remote_logger.hh
Let `queueData()` return a status and log that via a program supplied helper.
This way, the program specific (`recursor`, `dnsdist`) logging isn't polluting the common code.
I'm not 100% happy with this helper, but I lack inspiration to come up with something better atm.
There are a few other cases that need to be dealt with some day.
`dnsdist` log levels should be reviewed (I copied the existing), they might be too verbose.
One observable change in `dnsdist`:
```
"FrameStreamLogger: queue full, dropping."
```
now turned into
```
"dnstap: queue full, dropping."
```
If that is considered a problem, the name of the subsystem should not come the class via a virtual method, but from the caller of the helper.
I have:
=> Reorganize protobuf queueData() with respect to logging

pdns/syncres.cc, pdns/syncres.hh
This condition would be caught when going out previously, so is
an optimisation, not a behaviour difference.
I have:
=> rec: Also check qperq limit if throttling happened, as it increases counters.

builder-support/dockerfiles/Dockerfile.debbuild-prepare
This was triggered by Ubuntu Kinetic pulling in a version of 
systemd-resolved that breaks inside Docker. systemd-resolved is an indirect
(via Recommends somewhere) dependency of devscripts, which we need.
However, if we were relying on Recommends, that was a bug, so I'm applying
the flag to all distributions.
I have:
=> builder: add --no-install-recommends to apt-get install

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-rings.cc, pdns/dnsdist-rings.hh, pdns/dnsdist.cc, pdns/dnsdistdist/dnsdist-backend.cc, pdns/dnsdistdist/docs/reference/config.rst
In some setups where `grepq`, `top*` and the dynamic blocks are not used, inserting queries and/or responses into the ring buffers is not worth it, as it involves (small) CPU and memory costs.
I have:
=> dnsdist: Make recording queries/responses in the ringbuffers optional

pdns/lwres.cc
Followup to #11881
`remoteLoggerQueueData` should not be inside `#ifdef HAVE_FSTRM`
I have:
=> Fix build if dnstap is not enabled

pdns/dnsdist-console.cc, pdns/dnsdist-lua-actions.cc, pdns/dnsdistdist/docs/rules-actions.rst
In my prod env, I need to Tee queries from specific ip address, since there are multiple ip addresses on a single interface and the receiver has source address based ACLs and Views.
So I proposed an optional parameter in TeeAction to set the socket bind address.
Usage:
`addAction(AllRule(), TeeAction("192.0.2.54", false, "192.0.2.53"))`
In which case, "192.0.2.54" is the ComboAddress of receiver, "192.0.2.53" is the ComboAddress of sender.
I have:
=> dnsdist: Add local ComboAddress parameter for SBind() at TeeAction()

pdns/libssl.cc
Since https://github.com/openssl/openssl/commit/661595ca0933fe631faeadd14a189acd5d4185e0
we can no longer rely on the ciphers and digests required for TLS to be loaded by `OPENSSL_init_ssl()`, so let's give up and load everything.
I hope you have a lot of RAM.
Hopefully fixes #11853 (I don't have the exact same certificate to be 100% sure).
I have:
=> libssl: Properly load ciphers and digests with OpenSSL 3.0

pdns/lwres.cc, pdns/lwres.hh, pdns/recursordist/docs/settings.rst, pdns/recursordist/rec-main.cc
See https://www.rfc-editor.org/rfc/rfc8467 and https://www.rfc-editor.org/rfc/rfc7830
A few questions remaining:
1. Do we want to make this configurable? Currently this PR pads outgoing messages if and only if we're doing DoT. It could be we expect our outgoing traffic to be encapsulated in an encrypted channel. In that case padding could also be an option for un-encrypted outgoing traffic, but I find that a bit far fetched and not something you would do typically. 
3. (Related to 1.) Does it make sense to not want padding for DoT?
4. This PR uses a padding size of 128, as we are (kind of) client. Is that OK?
I have:
=> rec: Implement padding of (DoT) messages to auth

docs/modes-of-operation.rst, docs/settings.rst, pdns/auth-main.cc, pdns/slavecommunicator.cc
This is a workaround for #10447 until SOA Checks over TCP are supported.
Turning this off will disable the DO flag for SOA queries during zone freshness checks of secondary zones
to workaround truncated SOA responses. It will also disable signature comparison which are used to detect
signature changes even when the serial was not increased. Hence, disable this setting only if the Primary
name server always increases the serial on signature changes.
Default: yes (= old behavior)
I have:
=> New setting compare-signatures-on-zone-freshness-check to disable DO flag for SOA checks

pdns/auth-main.cc, pdns/auth-main.hh
```
auth-main.cc:133:6: warning: redundant redeclaration of ‘void mainthread()’ in same scope [-Wredundant-decls]
133 | void mainthread();
|      ^~~~~~~~~~
In file included from auth-main.cc:55:
auth-main.hh:51:13: note: previous declaration of ‘void mainthread()’
51 | extern void mainthread();
|             ^~~~~~~~~~
```
I have:
=> auth: fix gcc warning

pdns/ws-auth.cc, regression-tests.api/test_Zones.py
Successor of #11917
Closes: #11917
Fixes: #11824
API:
- Ignore NSEC3* metadata in the db for insecure zones (like the rest of the authoritative server)
- Remove existing NSEC3* metadata when dnssec is enabled (without a nsec3parm value) or disabled. This will avoid surprises caused by old NSEC3* metadata.
- Always treat an empty nsec3param as a removal request (secure and insecure zones). This will make it possible to remove old and ignored NSEC3* metadata.
I have:
=> auth: api, nsec3param improvements

pdns/syncres.cc, pdns/syncres.hh
This condition would be caught when going out previously, so is
an optimisation, not a behaviour difference.
(cherry picked from commit c75d28f2b786b986ec10675e3c853a52eec11e37)
Backport of #11848 
I have:
=> rec: Backport 11848 to rec-4.6.x: Also check qperq limit if throttling happened, as it increases counters.

pdns/syncres.cc, pdns/syncres.hh
This condition would be caught when going out previously, so is
an optimisation, not a behaviour difference.
(cherry picked from commit c75d28f2b786b986ec10675e3c853a52eec11e37)
Backport of #11848 
I have:
=> rec: Backport 11848 to rec-4.5.x: Also check qperq limit if throttling happened, as it increases counters.

pdns/recursordist/test-syncres_cc5.cc, pdns/syncres.cc, pdns/syncres.hh
_As with any validation related PR, this should be reviewed with extra care!_
This issue happens if a record set is signed even though the zone
itself is Insecure. Syncres then tries to retrieve DNSKEYs and a
timeout on that would lead to an ImmediateServFailException.
So do not throw an exception.  Further validation with the potentially
empty set of DNSKEYs should do the right thing. Including tests for
both Secure and Insecure zones.
I have:
=> rec: Failure to retrieve DNSKEYs of an Insecure zone should not be fatal.

pdns/tkey.cc
Followup to #11143.
Not a bug per se, but the unreachable code should be guarded by proper #ifdef
I have:
=> auth: Fix CID 1497843: Execution cannot reach this statement

pdns/recursordist/test-syncres_cc5.cc, pdns/syncres.cc, pdns/syncres.hh
This issue happens if a record set is signed even though the zone itself is Insecure. Syncres then tries to retrieve DNSKEYs and a timeout on that would lead to an ImmediateServFailException.
Only throw exception later in validateRecordsWithSigs, after checking zone cuts, when we are sure the zone is Secure.
(cherry picked from commit 6dc8b0b2c6fb2e628356f8dc5c5de4dfd919ec5d)
Backport of #11890 
I have:
=> rec: Backport of 11890 to rec-4.5.x: Failure to retrieve DNSKEYs of an Insecure zone should not be fatal.

pdns/recursordist/test-syncres_cc5.cc, pdns/syncres.cc, pdns/syncres.hh
This issue happens if a record set is signed even though the zone itself is Insecure. Syncres then tries to retrieve DNSKEYs and a timeout on that would lead to an ImmediateServFailException.
Only throw exception later in validateRecordsWithSigs, after checking zone cuts, when we are sure the zone is Secure.
(cherry picked from commit 6dc8b0b2c6fb2e628356f8dc5c5de4dfd919ec5d)
Backport of #11890
I have:
=> rec: Backport of 11890 to rec-4.6.x: Failure to retrieve DNSKEYs of an Insecure zone should not be fatal.

pdns/recursordist/test-syncres_cc5.cc, pdns/syncres.cc, pdns/syncres.hh
This issue happens if a record set is signed even though the zone itself is Insecure. Syncres then tries to retrieve DNSKEYs and a timeout on that would lead to an ImmediateServFailException.
Only throw exception later in validateRecordsWithSigs, after checking zone cuts, when we are sure the zone is Secure.
(cherry picked from commit 6dc8b0b2c6fb2e628356f8dc5c5de4dfd919ec5d)
Backport of #11890 
I have:
=> rec: Backport 11890 to rec-4.7.x: Failure to retrieve DNSKEYs of an Insecure zone should not be fatal.

docs/catalog.rst
Replace catalog zone by `catalog.example` only because I found reading `catalog.invalid` looked strange. Other than that fix a typo and reformat the zone proper.
I have:
=> Nits on documentation for catalog zones

pdns/recursordist/docs/lua-scripting/hooks.rst
Clarifies documentation: not only `ipfilter` and `preresolve` should return `true` when they influence/modify the normal query flow.
I have:
=> Clarify return codes for the LUA hooks in the Recursor

pdns/axfr-retriever.cc
This avoids zones missing whole chunks of data on the secondary side, as described in #11804
I have:
=> axfr-retriever: abort on chunk with TC set

modules/bindbackend/bindbackend2.cc, modules/bindbackend/binddnssec.cc, pdns/dbdnsseckeeper.cc, pdns/dnsseckeeper.hh, pdns/packethandler.cc, pdns/pdnsutil.cc, pdns/tcpreceiver.cc
Small cpp modernization found with `clang-tidy`:
- Initialize out parameter to `false` at call site of `getNSEC3PARAM`
- Use `nullptr` instead of `0`
- Avoid bool auto conv check for `p != nullptr` instead
I didn't digged the `std::optional` way, ~due to the absence of `optional` in pdns sources and~ mostly because i am inexperienced with. ~No hard feeling about it.~ It's used in pdns source see for example: <https://github.com/PowerDNS/pdns/blob/9e912e583ac8954fa26c4f1b93782515741caeda/pdns/dnstap.hh> (redacted to add an example).
Why redacted? Made a typo while searching. :facepalm:.
https://en.cppreference.com/w/cpp/utility/optional
I have:
=> [clang-tidy] Use nullptr in getNSEC3PARAM + init bool at callsite

pdns/recursor_cache.cc, pdns/recursor_cache.hh, pdns/recursordist/docs/settings.rst, pdns/recursordist/rec-main.cc, pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc10.cc, pdns/reczones.cc, pdns/syncres.cc, pdns/syncres.hh
While we already are very careful to check if a received answer is really the answer to a question we asked an authoritative server this provides an extra layer of protection against spoofing. 
To quote from the docs:
This adds an extra layer of protection---as it limits the window of time cache updates are accepted---at the cost of a less efficient record cache.
The default value of 0 means no extra locking of entries in the record cache occurs. When non-zero, record sets received (e.g. in the Additional Section) will not replace existing record sets in the record cache until the given percentage of the original TTL has expired. So 80 means that an entry with an original TTL of 3600 will only be replaced if its older than  0.8 * 3600 = 2880 seconds. A value of 100 means only expired …
=> Rec: lock record cache entries

regression-tests/README.md
Fix a broken link `jdnssec-link` in `regression-tests/README.md`.
=> fix #11997 jdnssec was broken link to repository directly.

pdns/dnsname.cc, pdns/dnsname.hh
Fixes #12014
Since we do not know the callers of this, we need to be extra careful not to print random strings. Especially call errors like `DNSName(p, -1)` should not be disastrous.
Note: the `throw std::runtime_error("Found . in wrong position in DNSName "+string(p));` case becomes a `range_error`. If that is not acceptable I should add a `throwSafeRuntimeError` function.
I have:
=> Include (with precautions) offending data in messages about too long a label

pdns/communicator.hh, pdns/mastercommunicator.cc, pdns/misc.cc, pdns/misc.hh, pdns/pdns_recursor.cc, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-tcp.cc, pdns/test-misc_hh.cc
Improve error message when invalid values for `local-address` are provided in recursor config file. The recursor used to depend on `parseService` subroutines to parse addresses. This subroutine didn't do much except "scan until colon or EOF is reached".
This PR replaces the use of `parseService` with `ComboAddress` which offers better parsing and error reporting for address values.
This PR also cleans up and modernizes `getHostname`.
I have:
=> Improve error message when invalid values for `local-address` are provided in recursor config file

pdns/recursordist/rec-tcp.cc
On e.g. MacOS I saw: 
```
rec-tcp.cc:1038:8: warning: variable 'first' set but not used [-Wunused-but-set-variable]
auto first = true;
```
I have:
=> rec: Properly guard  TCP_DEFER_ACCEPT

pdns/recursordist/docs/settings.rst, pdns/recursordist/docs/upgrade.rst
Switchin loggging backend must be done on the command line (at least for now).
I have:
=> rec: Make clear structured-logging-backend must be set on the command line

pdns/dnsdist-dynblocks.hh, pdns/dnsdist-lua-inspection.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-web.cc, pdns/dnsdist.cc, pdns/dnsdistdist/dnsdist-dynblocks.cc, pdns/dnsdistdist/dnsdist-lua-inspection-ffi.cc, pdns/dnsdistdist/docs/install.rst, pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc, tasks.py
Each of these features involves an extra thread, which we might want to avoid on some architectures.
I have:
=> dnsdist: Add build-time options to disable the dynamic blocks and UDP response delay

pdns/dnsdist-lua.cc, pdns/dnsdist.cc
When exiting on user request, dnsdist calls `_Exit()` to avoid any issue caused by the order in which the destructors of our long-lived objects are called (it would be nice to fix this properly, but it would require a fairly large refactoring).
Since the static destructors are not called in that case, the most recent coverage data is not always properly dumped to disk. Explicitly calling __gcov_dump` before exiting ensures that no data is lost.
I have:
=> dnsdist: Better code coverage stats when enabled

pdns/recursordist/docs/appendices/compiling.rst, pdns/recursordist/docs/getting-started.rst, pdns/recursordist/docs/settings.rst
I'm also making the mention of PowerDNS Recursor more consistent: no ``the`` and either :program:`PowerDNS Recursor` or :program:`Recursor`. Use short form if the long form was used already in a section or it would become tedious to have the long form for another reason.
Fixes #11828, though the recursor.conf man page is not going to happen anytime soon, as we lack the infrastructure for that and maintaining both a .rst file and a man page would be a pain.
With released versions, pdns_recursor --config=default helps a bit. In master pdns_recursor --config=[default|check|diff] was added.
I have:
=> rec: Update docs for getting started and compiling.

pdns/iputils.hh, pdns/pdns_recursor.cc, pdns/rec-lua-conf.hh, pdns/rec_channel_rec.cc, pdns/recursordist/docs/manpages/rec_control.1.rst, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh, pdns/recursordist/rec-tcp.cc, pdns/ws-recursor.cc
This implements two counters per ProxyMapping subnet. First counter (netmaskMatches) counts the number of hits based on netmask. The second counter counts the hits of domain (if relevant for the mapping).
I did not want to introduce another atomic count, as one day we will be moving to an mcounter like approach.
Actually this PR contains two approaches avoiding atomic counters:
- The first part (commit 1-3)). Creates a per-thread map of netmask->counts.
This has the drawback that for each ProxyMapping match, we also need to do a lookup in the counts map to find the counters to increment.
- The second approach (last commit) changes the ProxyMapping config to be per-thread (in master it is a shared pointer per thread, all these pointers point to a common config object). That way we can keep …
=> Rec: proxymapping stats

pdns/recursor_cache.cc, pdns/recursordist/docs/settings.rst, pdns/recursordist/test-syncres_cc10.cc
Followup to #11958
Current code gives the right answer (the authoritative records) to the client but does not replace the unauthoritative record set  in the cache by the authoritative one. That's a bit too strict interpretation of the locking feature.
I have:
=> rec: If new data is auth and existing data is not, replace even if cache locking is active

pdns/recursordist/aggressive_nsec.cc
Fixes a less than optimal cache maintenance cache issue. 
I have:
=> rec: when an expired nsec3 entry is seen move it to the front of the expiry queue

pdns/dnsdist-cache.cc, pdns/dnsdist-cache.hh, pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc, pdns/dnsdistdist/dnsdist-lua-ffi-interface.h, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsparser.cc, pdns/dnsparser.hh, pdns/test-dnsdistpacketcache_cc.cc
This PR adds Lua (FFI and non-FFI) bindings to:
- check if a given domain is present in the cache, and if so get the corresponding IP addresses of A and AAAA records present in the answer section of entries for that domain ;
- check if there are answers in the cache containing an A (or AAAA for IPv6) record corresponding to a given address, and if so get the list of the requested domains that led to these answers.
This can be used for threat intelligence.
I have:
=> dnsdist: Add Lua bindings to look up domain and IP addresses from the cache

regression-tests.dnsdist/dnsdisttests.py, regression-tests.dnsdist/test_CDB.py, regression-tests.dnsdist/test_Protobuf.py, regression-tests.dnsdist/test_TCPFastOpen.py, regression-tests.dnsdist/test_TLS.py
We now have enough regression tests that nosetests runs out of file descriptors without this change. We should have been more careful about not leaving so much state around between tests anyway.
I have:
=> dnsdist: Stop background threads and close file descriptors in regression tests

pdns/dnscrypt.cc, pdns/dnscrypt.hh, pdns/dnsdist-cache.cc, pdns/dnsdist-lua-inspection.cc, pdns/dnsdist-protobuf.cc, pdns/dnsdist-web.cc, pdns/dnsdist.cc, pdns/dnsdistdist/dnsdist-dynblocks.cc, pdns/dnsdistdist/dnsdist-lua-bindings-dnscrypt.cc, pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc, pdns/dnsdistdist/dnsdist-rules.hh, pdns/ednscookies.cc
Two sets of coverity reports. Should make dnsdist clean again.
Two last two in `dnscryp.cc` look strange as we're modifying through a `const &`. But that happens via the lock guard `operator->` which returns a `T*`, not a `const T*`. 
I have:
=> Dnsdist: coverity 20220928

pdns/dnsdist-lua-actions.cc, pdns/dnsdist-rings.hh, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsdistdist/dnsdist-mac-address.cc, pdns/dnsdistdist/dnsdist-mac-address.hh
When the MAC address feature is enabled, dnsdist usually keeps seeing the same devices, so it makes sense to keep a tiny (10 entries), short-lived (60s) cache of MAC addresses to speed things up.
We might want to make the size configurable at a later point if this proves useful.
I have:
=> dnsdist: Implement a small MAC address cache

pdns/dnspacket.cc, pdns/dnspacket.hh, pdns/tcpreceiver.cc
This makes the server break the whole transfer if it was about to send a truncated chunk. Part of mitigation for #11804 without yet solving it completely.
I have:
=> auth AXFR server: abort on chunk with TC set

.github/workflows/builder-dispatch.yml
This makes it easier to generate packages from any branch or tag for one or more distribution targets at a time. It also adds a flag for building releases.
To try this, go to Actions on a repo that has a copy of the yaml file on any branch. Then pick the target ("Trigger specific package build") on the left, open the "Run workflow" dropdown, pick your branch with the yaml file in "Use workflow from"; then check the rest of the fields and hit "Run workflow".
Once merged, this will simplify - it will no longer be necessary to first open the "Run workflow from" dropdown.
Note that this does not magically know what distributions are available for a given product or tag/branch.
I have:
=> expand builder-dispatch workflow for release building

pdns/dnstap.cc, pdns/pdns_recursor.cc, pdns/rec-lua-conf.cc, pdns/rec-lua-conf.hh, pdns/rec_channel_rec.cc, pdns/recursordist/docs/indexTOC.rst, pdns/recursordist/docs/lua-config/protobuf.rst, pdns/recursordist/docs/nod_udr.rst, pdns/recursordist/docs/security.rst, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh, pdns/recursordist/rec-tcp.cc, pdns/remote_logger.hh, regression-tests.recursor-dnssec/test_RecDnstap.py
This adds support to send NOD and UDR notifications using dnstap.
``Message.type`` will be set to ``CLIENT_QUERY`` for NOD and ``RESOLVER_RESPONSE`` for UDR. The concerned domain name will be attached in the ``Message.query_zone`` field and finally,  UDR notifiations will get the reply attached to the ``Message.response_message`` field.
I have:
=> rec: add support for NOD/UDR notifications using dnstap

pdns/ednscookies.cc
The truncation is due to DNS specific protocol properties.
Fixes Coverity CID 380097.
I have:
=> ednscookies: Fix another store_truncates_time_t coverity report

pdns/dnsdist-lua-bindings.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/dnsdist-tcp.hh, pdns/dnsdistdist/docs/install.rst, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/doh.cc
On some environments that have very limited resources and deal with a fairly low amount of QPS, it does not make sense to have several UDP, TCP, DoT and DoH handler threads to deal with the various network interfaces, so this PR adds a build option where there is a single UDP thread to deal with all incoming queries, a TCP/DoT worker thread can deal with several/all listening IP addresses (merging the `accept()` thread into the worker) and a single DoH worker thread can deal with several/all listening IP addresses as well.
Reducing the number of threads that way yields a lower memory footprint and lower the cost of context switches.
Note that this change is not enabled by default, as it would not make sense for most environments.
I have:
=> dnsdist: Add a 'single acceptor thread' build option, reducing the number of threads

pdns/dnsdist-cache.cc, pdns/dnsdist-cache.hh, pdns/dnsdist.cc, pdns/test-dnsdistpacketcache_cc.cc
For DoH queries we do two cache lookups:
- a first one for responses received over UDP, that can be truncated,   which we do not want here as the client likely would not what to do with that
- then on a miss, a second one for responses received over TCP
We do not want the first lookup to override the initial query in case of a hit for a TC=1 response, so we used to do a copy of the
query (allocation + copy).
This code move the TC=1 check to the cache itself so we do not have to do that copy, speeding things up.
I have:
=> dnsdist: Faster cache-lookups for DNS over HTTPS queries

.github/actions/spell-check/expect.txt, pdns/dnsdist-lua.cc, pdns/dnsdist-lua.hh, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/dnsdist-dnsparser.cc, pdns/dnsdistdist/dnsdist-dnsparser.hh, pdns/dnsdistdist/dnsdist-lua-bindings-dnsparser.cc, pdns/dnsdistdist/dnsdist-lua-ffi-interface.h, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsdistdist/docs/reference/dnsparser.rst, pdns/dnsdistdist/docs/reference/index.rst, pdns/dnsdistdist/test-dnsdist-dnsparser.cc, regression-tests.dnsdist/test_DNSParser.py
This PR provides regular and FFI bindings allowing to look at the DNS records contained in a DNS payload. There is no parsing of the rdata (content) of the DNS records, though, and at this point this is not something we want to add.
I have:
=> dnsdist: Add Lua helpers to look into the content of DNS payloads

pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
append to the output buffer in expungeByName (instead of overwriting)
I have:
- [ X] compiled this code
- [ X] tested this code
- [X ]  checked that this code was merged to master
This fix addresses #12075
=> retain output when expunging from multiple caches

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc, pdns/dnsdistdist/docs/reference/config.rst
PR adds a function to return the list of pool names, so it is possible to iterate over all defined pools.
Use case is to remove a FQDN from all caches via expungeByName. This patch adds the missing list of pool names for getPool(name):getCache():expungeByName("...")
Implements feature request #12073 
I have:
- [ X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ X] compiled this code
- [ X] tested this code
- [ X] included documentation (including possible behaviour changes)
- [X ]  checked that this code was merged to master
=> add getPoolNames() function, returning a list of pool names

pdns/dnsdist-lua.cc, pdns/dnsdistdist/docs/reference/config.rst
Currently, `dnsdist` exits when encountering an error in the DoT/DoH configuration (such as files for keys are not found or readable).
This PR is a proposal to skip the DoT/DoH frontend configuration and to continue launching anyway.
I have:
=> dnsdist: skip DoT/DoH frontend when a tls configuration error occurs

docs/upgrading.rst
The Auth 4.7 upgrade note said every backend used `...schema.pgsql.sql`.
`X.sql` matches an older note.
I have:
=> docs: Clarify schema change filename

pdns/rpzloader.cc
=> rec: Log invalid RPZ content when obtained via IXFR

pdns/slavecommunicator.cc
This pull will make it easier to move to catalog zones by not performing a zone reset when unique was empty.
It also fixes a bug. After a zone requiring an options update, options for every next zone was updated as well. This is harmless but it will result in a huge amount of unnecessary database queries.
I have:
=> auth: catalog zones, avoid bulk zone reset while migrating to a catalog and fix a bug

pdns/slavecommunicator.cc
=> auth-4.7.x: catalog zones, avoid bulk zone reset while migrating to a catalog and fix a bug

docs/settings.rst
As it actually makes things slightly worse in that case, because the response cannot be cached because of the scoped records, invalidating the whole response. This is especially a problem with the Geo IP backend but might be an issue with Lua and remote backends as well.
I have:
=> auth: Document that `consistent-backends` should not be used with scoped records

regression-tests.auth-py/test_LuaRecords.py
This test assumes the health check timeout is 1 second, while it is 2 seconds by default.
Adapt tests to take that into account, which resolves the occasional failure as tested locally.
I have:
=> auth: take into account default urlcheck timeout is 2 seconds for Lua records tests 

pdns/pdns_recursor.cc, pdns/rec-lua-conf.cc, pdns/rec-lua-conf.hh, pdns/rec_channel_rec.cc, pdns/recursordist/docs/manpages/rec_control.1.rst, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh, pdns/recursordist/rec-tcp.cc
We already did it for dnstap. This also does the protobuf loggers.
I'm not doing the async part now, as TSAN reports there would be a race. We do a synchronous cleanup of the old config when we see the config changed only.
The case occurring the most: no changes is now handled quickly and that is the main thing.
I'm also adding/removing a few places where the config checking is done:
- do it where we need to know if a certain logger is enabled in both the UDP and TCP input path
- do it in startDoResolve, so any thread handling a non-PC hit gets the new config.
- do it periodically since not al threads actually handle incoming packets or call startDoResolve that often.
I spotted the latter case by changing config and the looking at `rec_control get-remotelogger-stats` and seeing the olde …
=> rec: Compare old and new config for protobuf logger config objects on Lua config reload

pdns/syncres.cc
We would not make progres anyway, and end up repeatedly asking the full name from the roots as the "Trying less specific NS" code path is hit.
Noted by and fix from  @phonedph1
Fixes #12090
As this is an optimzation for broken domains, this is not an immediate candidate for backporting, though it should be considered for that after more testing.
I have:
=> rec: If we encounter a loop in QM, continue with the next iteration.

pdns/common_startup.cc, pdns/misc.cc, pdns/receiver.cc, pdns/test-misc_hh.cc
Backport of #11908 and #12066
I have:
=> auth-4.6.x: initialize zone cache after dropping privileges; Detect invalid bytes in makeBytesFromHex() 

pdns/recursor_cache.cc, pdns/recursordist/test-recursorcache_cc.cc
So be a bit more lenient with replacing auth records by unauth, as unauth (typically infra records) might come in while we are resolving.
Should fix #12078. 
But the issue of doing multiple cache lookups that assume records do no expire in-between during the resolving process is a fundamental issue. In the future we might create a separate infra cache which should take this fundamental  issue into account.
I have:
=> rec: QM can get confused by expiring infra records

regression-tests.recursor-dnssec/test_LockedCache.py
(cherry picked from commit 67dd4251f758a695dab05e206a32199ccee6c214)
(cherry picked from commit 23064464fe298ac748470942de6e04a429be9a31)
Backport of #12054 and #12133
I have:
=> rec: backport 12054 to rec-4.8.x: Fix assertAlmostEqual call to compare absolute difference

pdns/rpzloader.cc
(cherry picked from commit 55a99233728fc01e3946a97fb8dbb073a3003622)
Backport of #12081 
I have:
=> rec: backport 12081 to rec-4.8.x: Log invalid RPZ content when obtained via IXFR

pdns/pdns_recursor.cc, pdns/rec-lua-conf.cc, pdns/rec-lua-conf.hh, pdns/rec_channel_rec.cc, pdns/recursordist/docs/manpages/rec_control.1.rst, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh, pdns/recursordist/rec-tcp.cc
I'm not doing the async part now, as tsan reports there would be a race. The case occuring the most: no changes is now handled correctly and quickly and that is the main thing.
(cherry picked from commit babe943035818b7a97e59cfd70921ba06bbf31cf)
Backport of #12063 
I have:
=> rec: backport 12063 to 4.8.x: Also do the compare for protobuf logger config objects.

pdns/ixfr.cc, pdns/ixfr.hh, pdns/ixplore.cc, pdns/rpzloader.cc, pdns/rpzloader.hh, pdns/slavecommunicator.cc
One complicating factor is that this is shared code, but auth and rec do not agree on the definiton of the timeout value: auth states it is a maximum idle time, while rec state it is the total xfr time. While both apporaches make sense and in the end we would like to enforce both, we now go for a more simple solution that respects auth or rec behaviour based on a flag.
I have:
=> Timout handling for ixfrs as a client.

pdns/ixfr.cc, pdns/ixfr.hh, pdns/ixplore.cc, pdns/rpzloader.cc, pdns/rpzloader.hh, pdns/slavecommunicator.cc
=> rec: Backport 12125 to rec 4.8.x: handle ixfr connect and transfer timeouts

pdns/recursor_cache.cc, pdns/recursordist/rec-taskqueue.cc
Should fix #11337
(cherry picked from commit 7a278799ee23e582c3b722cea578699db1791bc2)
Partial backport of #11338
I have:
=> rec: Backport 11338 to rec-4.5.x: QType ADDR is supposed to be used internally only.

pdns/rpzloader.cc
(cherry picked from commit 55a99233728fc01e3946a97fb8dbb073a3003622)
Backport of #12081 
I have:
=> rec: Backport to rec-4.5.x: Log invalid RPZ content when obtained via IXFR

pdns/recursordist/aggressive_nsec.cc
(cherry picked from commit 05a4985708988eb10f9291a40406b205e7d5d5b2)
Backport of #12038 
I have:
=> rec: Backport 12038 to rec-4.6.x: when an expired nsec3 entry is seen, move it to the front of the expiry queue

pdns/rpzloader.cc
(cherry picked from commit 55a99233728fc01e3946a97fb8dbb073a3003622)
Backport of #12081 
I have:
=> rec: Backport 12081 to rec-4.6.x: Log invalid RPZ content when obtained via IXFR

pdns/recursordist/aggressive_nsec.cc
(cherry picked from commit 05a4985708988eb10f9291a40406b205e7d5d5b2)
Backport of #12038 
I have:
=> rec: Backport 12038 to rec-4.7.x: when an expired nsec3 entry is seen, move it to the front of the expiry queue

pdns/rpzloader.cc
(cherry picked from commit 55a99233728fc01e3946a97fb8dbb073a3003622)
Backport of #12081 
I have:
=> rec: Backport 12081 to re-4.7.x: Log invalid RPZ content when obtained via IXFR

pdns/dynhandler.cc
pdns_control list-zone without specifying a type resulted in a crash
fixes #12156
I have:
=> auth: fix pdns_control list-zones

pdns/dnsdist-lua-bindings.cc
`boost::optional::value_or()` has been introduced in 1.56 and we only require 1.53, so stop using it.
Hopefully fixes the `master` part of #12142.
I have:
=> dnsdist: Fix building with boost < 1.56

pdns/dnsdist-lua-bindings.cc
partial backport of #12177, plus another fix
this makes dnsdist-1.7.x build on Amazon Linux 2 again.
I have:
=> dnsdist-1.7.x: fix building with boost < 1.56

pdns/recursordist/rec-main.cc, pdns/recursordist/test-syncres_cc7.cc, pdns/reczones.cc, pdns/syncres.cc, pdns/syncres.hh, regression-tests.recursor-dnssec/test_AggressiveNSECCache.py
This avoid `a.root-servers.net` going `Bogus`, which can happen if the `.net NS` are not cached and we miss the cut.
Fixes #12160 and avoids the need to prime the `.net NS` records explicitly.
Draft for now.
I have:
=> rec: Get DS records with QM switched on.

pdns/dnsdistdist/dnsdist-backend.cc
We are making sure that our computation will not overflow the maximum value of a `time_t`, and we know that this maximum value is positive, so we can use a `size_t` to do the comparison.
I have:
=> dnsdist: Fix 'comparison of integer expressions of different signedness' warning

pdns/webserver.cc
(cherry picked from commit 68dbf30cebc92d29853314b1160257a9dbc5f4f1)
Backport of #12194 
I have:
=> rec: Backport 12194 to rec-4.8.x: Fix typo in structured logging key

pdns/syncres.cc
Noted the other day by @rgacogne
(cherry picked from commit d1321ff57909f8fb9d0bd7a20e3c4eb85a6b76e1)
Backport of #12198 
I have:
=> rec: Backport 12198 to rec-4.8.x: Correct skip record condition in processRecords.

pdns/syncres.cc
With @rgacogne and @phonedph1
Fixes #12189
(cherry picked from commit af746aaf59a2e977bafabd5814635f59b01e5835)
Backport of #12199 
I have:
=> rec: Backport 12199 to rec-4.8.x: Also consider recursive forward in the "forwarded DS should not end up in negCache code"

builder-support/specs/pdns.spec
Signed-off-by: Georg Pfuetzenreuter <mail@georg-pfuetzenreuter.net>
Allows the EL package to be installed on openSUSE / SLE without errors. Currently the following is printed:
```
Loading repository data...                                                                                                               
Reading installed packages...                                                                                                            
Resolving package dependencies...                                                                                                                                                                                                                                                 
Problem: nothing provides 'systemd-units' needed by the to be …
```
=> Clear systemd-units dependency 

pdns/syncres.cc
When I introduced serve state in #11776, I reintroduced the mistake previously fixed in #11376. Fixes #12078
(cherry picked from commit 28a3eea55d15d33a65b2108c1598c15d00e0173c)
Backport of  #12219
I have:
=> recL Backport to rec-4.8.x: Infra queries should not use refresh mode

regression-tests.dnsdist/dnsdisttests.py, regression-tests.dnsdist/test_Caching.py, regression-tests.dnsdist/test_Carbon.py, regression-tests.dnsdist/test_HealthChecks.py, regression-tests.dnsdist/test_Responses.py, regression-tests.dnsdist/test_SNMP.py, regression-tests.dnsdist/test_TLS.py
1. On dnsdist startup, we poll the listening address and assume dnsdist is ready if a TCP connection can be established.
2. On teardown we have a better and tighter loop to poll process exit status.
Both 1 and 2 were taken from the recursor regression test framework.
A typical test run now is 16min instead of 26min.
I have:
=> dnsdist: regress speedup

pdns/syncres.cc
With @rgacogne and @phonedph1
Fixes #12189
(cherry picked from commit af746aaf59a2e977bafabd5814635f59b01e5835)
Backport of #12199 
I have:
=> rec: Backport 12199 to rec-4.7.x: Also consider recursive forward in the "forwarded DS should not end up in negCache code."

pdns/syncres.cc
Noted the other day by @rgacogne
(cherry picked from commit d1321ff57909f8fb9d0bd7a20e3c4eb85a6b76e1)
Backport of #12198
I have:
=> rec: Backport 12198 to rec-4.7.x: Correct skip record condition in processRecords.

pdns/portsmplexer.cc
Thanks to Jonathan Perkin for the patch!
(cherry picked from commit 7ea87a63ab48e938bdb8b73ebfde1ac6bc71704f)
Backport of #12046 
I have:
=> rec: Backport 12046 to rec-4.7.x: Fix compilation of the event ports multiplexer

pdns/syncres.cc
Noted the other day by @rgacogne
(cherry picked from commit d1321ff57909f8fb9d0bd7a20e3c4eb85a6b76e1)
Backport of #12198
I have:
=> rec: Backport 12198 to rec-4.6.x: Correct skip record condition in processRecords.

pdns/syncres.cc
With @rgacogne and @phonedph1
Fixes #12189
(cherry picked from commit af746aaf59a2e977bafabd5814635f59b01e5835)
Backport of #12199
I have:
=> rec: Backport 12199 to rec-4.5.x: Also consider recursive forward in the "forwarded DS should not end up in negCache code."

pdns/syncres.cc
Noted the other day by @rgacogne
(cherry picked from commit d1321ff57909f8fb9d0bd7a20e3c4eb85a6b76e1)
Backport of #12198 
I have:
=> rec: Backport 12198 to rec-4.5.x: Correct skip record condition in processRecords.

pdns/auth-catalogzone.hh, pdns/dns.cc, pdns/dns.hh
Small rewrite to use a C++ array + constExpr in `dns.cc`.
I have:
=> [clang-tidy:array] in dns.cc/hh std::array instead of c array.

docs/http-api/server.rst, docs/http-api/tsigkey.rst, docs/http-api/zone.rst
added examples to Servers and Zones endpoints, fixed order in TSIGKeys endpoint
Added missing examples for Servers and Zones endpoints, fixed order in TSIGKeys endpoint
I have:
=> updates to API documentation of Auth

modules/bindbackend/bindbackend2.cc
Yet an other clang-tidy yield
- avoid bool implicit conversion
- init boolean
- nullptr
- use string::empty
- using instead of typedef (may need review, not confortable enough of the change in semantics)
- use `auto` where suggested (may need careful review) see auto-comment.
- use `const auto` where suggested
- use `cerrno` instead of `errno.h`
I have:
=> Clang tidy/bindbackend

modules/geoipbackend/geoipbackend.cc
An other clang-tidy PR.
- NULL -> nullptr
- Use std::array
- Use better overload for a `find` before a `string/char*` now a `char`.
I have:
=> Clang tidy/geoipbackend

pdns/pdnsutil.cc
An other clang-tidy in `pdns_utils` for `nullptr` + initialize.
Moved the comments upper to avoid depassing 80char limit.
No problem if a rollup is justified of #11966 #11910 #11957, did separated one to avoid a big commit/pr.
I have:
=> [clang-tidy] Use nullptr explicitly and initialize directly.

pdns/dynlistener.cc
Changes in `pdns/dynlistener.cc` to comply with clang-tidy.
If theses patches are welcome, I may do some on personal time.
To the reviewer: take caution as said before i am not a pro-cpp dev prefers a really conservative review! :)
Fix founds with:
- [readability-implicit-bool-conversion]
- pdns/dynlistener.cc:256
- pdns/dynlistener.cc:272:8
- [readability-container-data-pointer]
- pdns/dynlistener.cc:240:19
- pdns/dynlistener.cc:245:25
- pdns/dynlistener.cc:256:17
- dns/dynlistener.cc:263:17
- [bugprone-narrowing-conversions,cppcoreguidelines-narrowing-conversions]
- pdns/dynlistener.cc:240:29
- pdns/dynlistener.cc:256:27
Avoided to fix `if` related to avoid making too much git noise.
I have:
=> [clang-tidy]: DynListener::getLine.

pdns/pdnsutil.cc
Again a clang-tidy patch, this time use `empty()` for checking emptiness of strings/collections and a not-int variables moved declaration to assignation site.
It's change driven by clang-tidy advise but since it involves sensible code a careful review is needed. I ran clang-tidy on this code because I read it at work.
I have:
=> [clang-tidy] pdns_utils use empty where possible + move decl to assignation site.

pdns/dnssecinfra.cc
This changes the crypto algorithm benchmark used by `pdnsutil test-algorithm` and `pdnsutil test-algorithms` to use RSA keys of 2048 bits instead of 1024 bits.
I have:
=> Use RSA-2048 instead of RSA-1024 for crypto benchmark

m4/ax_check_sign.m4, m4/ax_cxx_compile_stdcxx.m4
While I would not recommend running with `-Werror` always, I find it convenient to catch silly mistakes during development. The patches in this PR make `-Werror` work on my system. After discussion, perhaps we can upstream some things to the autoconf-archive.
I have:
=> make builds pass with -Werror on _my_ system

pdns/dnsname.cc, pdns/dnsname.hh
Also check length before de-referencing.
- Why using `strchr` if we have a length?
- Accepting `char * p` that doesn't contains `\0`
- In case of calling from `DNSName` `string` constructor yes `string::length` exclude `\0`
- In case of calling directly it's callee responsibility to provide a valid `length` but it's not less safe than just doing `strchr` IMHO
Not slower in our dev environment.
At work we use https://github.com/PowerDNS/pdns/pull/5160 from @baloo, I work on upstreaming + rebasing this contribution to master (will open an issue to discuss design about it soon).
In a lot of languages `string`s don't terminate with a `\0` like in Rust, so I got some over-read of one with `valgrind` on `strchr` when I wanted to get rid of `string` temporaries just for zeroes. …
=> DNSName constructor use memchr instead of strchr and cleanup with string_view

contrib/xdp-filter.ebpf.src, contrib/xdp-logging-middleware.ebpf.src, contrib/xdp-logging.py
According to this issue https://github.com/PowerDNS/pdns/issues/11009, this pull request add the possibility to load user-defined XDP function when performing TC or DROP action. This allow the user to log the queries even if they do not reach libpcap.
I added a custom XDP filter and a Python script to load it and output information about dropped/tc packets
I have:
=> dnsdist: Added XDP middleware for dropped/redirected queries logging

modules/gpgsqlbackend/gpgsqlbackend.cc
I tried to setup a catalog zone but it didn't work. I use PostgreSQL as a backend. The following error was logged repeatedly. PostgreSQL doesn't convert integers (0 in this case) to a boolean. I replaced 0 with false to get a valid SQL statement. I tested the SQL statement itself via psql and it worked, but I did not compile PowerDNS.
```
Oct 23 14:19:17 ns1.example.com pdns_server[924]: AXFR-out zone 'catalog.example.com', client '2001:abcd:99:ef::2a0:1', transfer initiated
Oct 23 14:19:17 ns1.example.com pdns_server[924]: TCP server is without backend connections in doAXFR, launching
Oct 23 14:19:17 ns1.example.com pdns_server[924]: TCP nameserver had error, cycling backend: virtual bool GSQLBackend::getCatalogMembers(const DNSName&, std::vector<CatalogInfo>&, CatalogInfo::CatalogType) …
```
=> auth: fix invalid catalog zone sql query for gpgsqlbackend

pdns/ws-auth.cc, regression-tests.api/test_Zones.py, regression-tests.api/test_helper.py
default-api-rectify defaults to "yes" nowadays, therefore one should expect newly created zones to be rectified, even if they are not DNSSEC-enabled.
Fixing this also slightly simplifies the create zone code, as it can now rely on updateDomainSettingsFromDocument applying SOA-EDIT-API transformations.
Found while working on #12086. 
I have:
=> API: Auth: fix newly created zone not rectified

.github/workflows/build-and-test-all.yml, .github/workflows/builder-dispatch.yml, .github/workflows/builder.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/formatting.yml, .github/workflows/fuzz.yml, .github/workflows/misc-dailies.yml, .github/workflows/secpoll.yml, .github/workflows/spelling.yml
Added using https://github.com/step-security/secure-workflows For more information see:
- https://github.com/ossf/scorecard/blob/d8fefc9b246db3600c777e9d60d441d7c386ce1d/docs/checks.md#token-permissions
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
- 
I have:
=> Restrict permissions for GITHUB_TOKEN in our workflows

docs/lua-records/functions.rst, pdns/lua-record.cc, pdns/minicurl.cc, pdns/minicurl.hh
This PR adds a `byteslimit` option to lua `ifurlup()` function that allows limiting the size read while querying the given URL.
Note that we may actually read a bit more than `byteslimit` depending on the underlying curl buffering.
Fix #12240 
I have:
=> auth: add byteslimit support to lua ifurlup() function

pdns/recursordist/docs/settings.rst
Add an example for negating dont-query
Add example in doc for how to negate a netmask group - implements alternative solution for #12217 
I have:
- [NA] compiled this code
- [NA] tested this code
- [NA] documented the code
- [NA] added or modified regression test(s)
- [NA] added or modified unit test(s)
=> rec: Document negation of netmasks in settings.rst

pdns/dnsdistdist/dnsdist-backend.cc
```
dnsdist-backend.cc:601:61: warning: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
if (backOffCoeffTmp != HUGE_VAL && backOffCoeffTmp <= std::numeric_limits<time_t>::max()) {
~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I have:
=> dnsdist: Fix a warning about long to double conversion

pdns/dnsdistdist/dnsdist.service.in, pdns/ixfrdist.service.in, pdns/pdns.service.in, pdns/recursordist/pdns-recursor.service.in
Adds 'After=time-sync.target' to the service unit files; this will not have any immediate effect, unless the system administrator has also enabled a unit which has a 'Before' dependency on that target; there are none of those units enabled in a default configuration in common distributions. systemd itself adds such an 'After' dependency to all timer units with OnCalendar settings, and to some other units.
However, in a system which makes use of systemd-timesyncd, the admin can enable systemd-time-wait-sync.service, which has such a dependency. The result would be that none of the PowerDNS services on the system would be started until after systemd-timesyncd is certain that the system's clock is synchronized with the configured external source.
A similar configuration can be achieved on …
=> systemd: Add "After" dependency on time-sync.target

m4/systemd.m4, pdns/Makefile.am, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/dnsdist.service.in, pdns/ixfrdist.service.in, pdns/pdns.service.in, pdns/recursordist/Makefile.am, pdns/recursordist/pdns-recursor.service.in
Another sandboxing option, [ProtectProc](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectProc=) hides all /proc/<pid> that are not owned by the service user and hides some kernel things from /proc as well.
Also adds `MemoryDenyWriteExecute`
I have:
=> service files: Add more sandboxing options

modules/lmdbbackend/lmdbbackend.cc, modules/lmdbbackend/lmdbbackend.hh
This reverts #12267. Working also-notify is not very useful when automatic notifies also don't work - which will be fixed in 4.7.
I have:
=> auth-4.6.x: Revert "auth lmdb: implement alsoNotifies"

pdns/ws-auth.cc, regression-tests.api/test_Zones.py
treat consumer zones as secondary type in the api
Related #12212
I have:
=> auth: api, do not create SOA and NS records for consumer zones

pdns/pdns_recursor.cc, pdns/qtype.hh, pdns/recursordist/rec-tcp.cc, pdns/syncres.cc, pdns/syncres.hh
This fixes #12251
Also I'd like to know why we ServFail on NSEC3 but not on NSEC: we should either fix that or add a comment explaining this.
I have:
=> rec: refactor unsuppored qtype code and make sure we ServFail on all unsupported qtypes

regression-tests.dnsdist/test_SNMP.py
Since https://github.com/PowerDNS/pdns/pull/12214 I'm seeing regular failures of the SNMP regression tests on our CI:
```
2022-11-29T11:39:46.6902570Z === configs/dnsdist_TestSNMP.log ===
2022-11-29T11:39:46.6921953Z Added downstream server 127.0.0.1:5350
2022-11-29T11:39:46.6922191Z unknown snmp version 193
2022-11-29T11:39:46.6922516Z NET-SNMP version 5.8 AgentX subagent connected
2022-11-29T11:39:46.6922670Z Listening on 127.0.0.1:5340
2022-11-29T11:39:46.6923124Z dnsdist 0.0.0-git1 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
2022-11-29T11:39:46.6923289Z ACL allowing queries from: 127.0.0.1/32
2022-11-29T11:39:46.6923648Z Console ACL allowing connections from: 127.0.0.0/8, ::1/128 …
```
=> dnsdist: Add logs to investigate the SNMP regression tests failure

pdns/ws-auth.cc, regression-tests.api/test_Zones.py
=> auth-4.7 api: do not create SOA and NS records for consumer zones

pdns/dnsdist-tcp.cc, pdns/dnsdistdist/dnsdist-tcp-upstream.hh, pdns/dnsdistdist/dnsdist-tcp.hh
We need this construct to deal with cross-protocol queries, like queries received over TCP or DoT, but forwarded over DoH, because the thread dealing with the client and the one dealing with the backend will not be the same in that case, and we do not want to have different threads touching the same TCP connections. So we pass the query and response to the correct thread via pipes. Until now we were allocating an additional object, `TCPCrossProtocolQuerySender`, to deal with that case, but I noticed that the existing `IncomingTCPConnectionState` object already does everything we need, except that it needs to know that the response is a cross-protocol one in order to pass it via the pipe instead of treating it in a different way. This can be done by looking if the current thread ID differs …
=> dnsdist: Get rid of TCPCrossProtocolQuerySender

.github/actions/spell-check/expect.txt, pdns/bpf-filter.cc, pdns/dnsdistdist/docs/advanced/ebpf.rst
Raise RLIMIT_MEMLOCK automatically when eBPF is requested.
#10566 
This PR adds changes to eBPF filter constructor which when invoked automatically raises the RLIMIT_MEMLOCK from 64k to 1024k.
The hard limit for the user needs to be set in `/etc/security/limits.conf`.
I have:
=> dnsdist: Raise RLIMIT_MEMLOCK automatically when eBPF is requested

pdns/minicurl.cc, pdns/minicurl.hh
```
minicurl.cc:134:30: error: 'CURLOPT_XFERINFOFUNCTION' was not declared in this scope; did you mean 'CURLOPT_WRITEFUNCTION'?
```
Fix missing `CURLOPT_XFERINFOFUNCTION` for libcurl versions before 7.32.0
I have:
=> minicurl: fix missing CURLOPT_XFERINFOFUNCTION on old curl versions

.github/workflows/build-and-test-all.yml
The way the send wrappers are implemented, reading the data _after_ it has been sent, cause them to report a data race that does not exist with existing implementations:
- we call `send()` from thread 1 to send a query to a backend, never touching the data or associated metadata again from that thread
- we get a response from the backend in a different thread, thread 2, which will then access the metadata and sometimes (truncated UDP answers following a DoH query) even modify the data itself
- ASAN and TSAN complain because the wrapper might still be reading the data after the UDP datagram has been sent, which is effectively a race, but it does not really make any sense for an actual implementation of `send()` to do that.
We work around that by disabling the `send()` wrappers in our CI, …
=> dnsdist: Disable the send wrappers in our CI

pdns/histogram.hh, pdns/lwres.cc, pdns/pdns_recursor.cc, pdns/rec-carbon.cc, pdns/rec-snmp.cc, pdns/rec_channel_rec.cc, pdns/recursordist/Makefile.am, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh, pdns/recursordist/rec-tcounters.cc, pdns/recursordist/rec-tcounters.hh, pdns/recursordist/rec-tcp.cc, pdns/recursordist/tcounters.hh, pdns/recursordist/test-rec-tcounters_cc.cc, pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc, pdns/syncres.hh, pdns/tcounters.hh, pdns/ws-recursor.cc, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_AggressiveNSECCache.py, regression-tests.recursor-dnssec/test_RootNXTrust.py, regression-tests.recursor-dnssec/test_SimpleDoT.py, regression-tests.recursor-dnssec/test_SimpleForwardOverDoT.py
This is a mostly lockless (and not using atomics) way to keep track of counters and other metrics.
Atomic value are more expensive than you would think (especially if your platform has no native atomic support for your data type), and using locking all the time for often updated counters is very expensive as well.
The idea for `TCounters` is based on
https://github.com/ahupowerdns/mcounter
But addresses the issues raised in
https://github.com/ahupowerdns/mcounter/issues/3
Templates are used, the application has to provide a specific class to hold the values and enums to index these values.  The application specific class also has to provide a `merge()` method to merge two instances of the application specific data.  For counters that is simple: just add them. Averages (or histograms) …
=> Introducing TCounters

regression-tests.dnsdist/dnsdisttests.py
This might help with the recent dnsdist regression issues by making sure the responder is active. UDP responder could still lag...
I have:
=> dnsdist: Wait for TCP responder to become active before starting dnsdist

regression-tests.dnsdist/dnsdisttests.py
We use `SO_REUSEPORT` in these tests so if the old responder is still around when the next test starts, it is quite likely that it might get one of the new queries. This is usually fine because responders with a different behaviour listen on different ports, but if a query is queued to an old responder socket right during the time that responder is checking whether it should stop and the actual exit, the query will be lost.
I have:
=> dnsdist: Stop the responders more quickly during the tests

pdns/dnsdistdist/dnsdist-tcp-downstream.hh
The remaining milliseconds after handling the full seconds was not properly converted to microseconds.
I have:
=> dnsdist: Fix the health-check timeout computation for DoH backend

pdns/recursordist/Makefile.am, pdns/recursordist/docs/upgrade.rst, pdns/recursordist/pdns_recursor.cc, pdns/recursordist/rec-responsestats.cc, pdns/recursordist/rec-responsestats.hh, pdns/recursordist/rec-tcounters.cc, pdns/recursordist/rec-tcounters.hh, pdns/recursordist/rec_channel_rec.cc, pdns/recursordist/responsestats.cc, pdns/recursordist/responsestats.hh, pdns/tcounters.hh, pdns/ws-api.cc, regression-tests.api/runtests.py
This allows for the packet cache hit path to record response stats without performance impact.
The qtype and rcode counters are capped, as I ran into trouble with the thread stack sizes on macOS and OpenBSD. See the source comment for explanation.
Closes #11534
I have:
=> rec: make response stats a tcounter object

regression-tests.auth-py/test_AnyBind.py, regression-tests.recursor-dnssec/test_AnyBind.py
v6 is more work, as the test client code assumes v4
Tested by neutering IsAnyAddress handling of auth and rec and verifying the tests fail.
Fixes #3965 (at least th v4 part).
I have:
=> Test ANY bind UDP handling for the v4 case

pdns/recursordist/test-rec-tcounters_cc.cc, pdns/recursordist/test-recpacketcache_cc.cc, pdns/recursordist/testrunner.cc
Some system habe a low resoltion nanosleep(), which sleeps for at least a few ms. Compensate for that by running fewer loops with longer sleeps.
Also use dns_random and make sure it is initlized properly for all tests.
I have:
=> rec: tcounter test tweaks

.github/workflows/build-and-test-all.yml, .github/workflows/builder-dispatch.yml
`::set-output` is deprecated in favor of `$GITHUB_OUTPUT`
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
I have:
=> Switch from set-output to GITHUB_OUTPUT

ext/json11/json11.cpp, pdns/webserver.cc, regression-tests.api/test_Servers.py
Mostly auth, as it has code to retrieve log lines via REST API. But other products could be affected as well.
The existing json11 code assumes the strings are already valid UTF8.
Fixes #9349
Also url encode `path` in log lines, as it trips pytest:
```
Running tests...
$ 'pytest' '--junitxml=pytest.xml' '-v'
==STDOUT===
==STDERRR===
File "/home/otto/pdns/regression-tests.api/runtests.py", line 304, in <module>
print(serverproc.stderr.read())
File "/usr/lib/python3.9/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xeb in position 4304: invalid continuation byte
```
There might be more places where this is needed.
I have:
=> auth: Properly encode json strings containing binary data

pdns/ixfrdist.cc, regression-tests.ixfrdist/test_IXFR.py
Ixfrdist used to generate invalid IXFR responses if it has multiple zone versions between the requested serial and the latest serial. See https://github.com/PowerDNS/pdns/issues/6880#issuecomment-420980817
This essentially moves the adding of the enclosing "latest serial" SOAs out of the loop which adds the changes of all the zone versions.
I have:
=> Fix multiple-version IXFR request handling in ixfrdist

pdns/dnsdistdist/dnsdist-tcp-downstream.cc, pdns/dnsdistdist/dnsdist-tcp.hh
From rfc1995 section 2 "Brief Description of the Protocol":
"If an IXFR query with the same or newer version number than that of the server is received, it is replied to with a single SOA record of the server's current version, just as in AXFR."
Until now we considered such a message to be an unfinished response to the pending {A,I}XFR, waiting for more DNS messages to come up and keeping the connection open for as long as the remote host was willing to accept that. This causes an issue for servers keeping the connection open for a very long time, like ixfrdist.
Fixes #12099 
I have:
=> dnsdist: Properly handle single-SOA XFR responses

docs/manpages/dnsreplay.1.rst, pdns/dnsreplay.cc
Needs more polishing, but I needed that option to investigate an issue and I don't want to have to write that code again the next time I need it :)
I have:
=> dnsreplay: Add an option to spoof the initial source IP

pdns/recursordist/recursor_cache.cc, pdns/recursordist/recursor_cache.hh
Existing code was correct but used the wrong name for the method: isEntryUsable() actually tested for isUnusable, but the caller compensated for it. Reverse logic to make it more clear.
I have:
=> rec: Use correct logic for isEntryUsable()

pdns/minicurl.cc, pdns/minicurl.hh
Having naked pointers around make my skin crawl.. Unfortunately this is harder that it should be because cURL used to alias `CURL` to `void` (why!?) and now cannot get rid of that because it would break too many projects, so we have to set `CURL_STRICTER` when it is available (7.50+) and fallback to naked pointers otherwise.
I have:
=> auth, rec: Wrap the CURL raw pointers in smart pointers

pdns/recursordist/pdns_recursor.cc
The exception reason is present in "regular" logging but not in structured logging.
I have:
=> rec: Add the 'parse packet from auth' error message to structured logging

pdns/recursordist/pdns_recursor.cc, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh, pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh, regression-tests.recursor-dnssec/test_AggressiveNSECCache.py, regression-tests.recursor-dnssec/test_RootNXTrust.py
Examples:
```
; EDE: 0 (Other): (Result synthesized from aggressive NSEC cache (RFC8198))
; EDE: 0 (Other): (Result synthesized by root-nx-trust)
; EDE: 22 (No Reachable Authority): (delegation timeout4.com)
```
As there is no specific EDE for synthesized, use noError with a text.
We have to be careful here: a single client query can lead to multiple beginResolve calls. Some of these are done after the main result has been looked up, for example to validate the result. These subsequent calls can generate EDE's but we do not want to copy the EDE to the main result in those cases. A typical example would be an absent DS for an Insecure domain. Nothing wrong with these but we do not want the potential absent DS EDE (which could be synthesized) to be returned with the main query,
I have:
=> rec: Generate EDE in more cases, specifically on unreachable auths or sythesized results.

pdns/recursordist/negcache.cc, pdns/recursordist/negcache.hh
When searching in negcache, when the stale function is triggered and the type of the cache is type0, the asynchronous expired task request resolution type is A record, and the actual client request is AAAA type request, so the request type of the asynchronous expired task should be changed Change to the type requested by the user
I have:
=> Refresh of negcache stale entry might use wrong qtype

pdns/dnsdistdist/dnsdist-tcp.hh
By incrementing it _before_ writing to the pipe, and decrementing it in case of an error, we prevent a very possible underflow from occurring if the reader manages to decrement before we can return from write and increment it.
Fixes #12357 
I have:
=> dnsdist: Prevent an underflow of the TCP d_queued counter

pdns/recursordist/nod.cc, pdns/recursordist/rec-main.cc, pdns/recursordist/rpzloader.cc, pdns/remote_logger.cc, pdns/snmp-agent.cc, pdns/webserver.cc
Use thread names without capitals, as they look a bit ugly otherwise.
Threads started by libfstrm are not named, as they are created internally by the lib.
Partly supsersedes #11138
I have:
=> rec: Name recursor threads consistently with a "rec/" prefix.

pdns/dnsdist.cc
Most exceptions are handled by `handleOnePacket()`, but we might be out of memory (`std::bad_alloc`) in which case we DO NOT want to log (as it would trigger another memory allocation attempt that might throw as well) but wait a bit (one millisecond) and then try to recover.
I have:
=> dnsdist: Handle out-of-memory exceptions in the UDP receiver thread

pdns/dnsdist-console.cc, pdns/dnsdist-lua-actions.cc, pdns/dnsdistdist/docs/rules-actions.rst, regression-tests.dnsdist/test_Responses.py
Reduce the TTL of records in a response to a percentage of the original TTL. For example, passing 50 means that the original TTL will be cut in half.
One use-case for this action is when dnsdist is in front of a recursor with the "refresh almost expired" feature enabled: dnsdist will then cache the packet for shorter duration than the recursor, allowing the recursor to re-fetch before the record has expired.
Related to https://github.com/PowerDNS/pdns/issues/10600.
I have:
=> dnsdist: Add SetReducedTTLResponseAction

pdns/dnsdist-idstate.hh, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/dnsdist-backend.cc, pdns/dnsdistdist/doh.cc, pdns/test-dnsdist_cc.cc
This pull request replaces the existing mechanism to ensure that UDP states can be safely accessed by several threads with a simpler, more robust one. This is possible now that we introduced the `InternalQueryState`, splitting the data from `IDState`.
<strike>Note that this pull request builds on https://github.com/PowerDNS/pdns/pull/12354 and will have to be rebased.</strike>
I have:
=> dnsdist: Stronger guarantees against data race in the UDP path 

pdns/ipcipher.cc, pdns/ipcipher.hh
Support OpenSSL 3.0 for ipcipher CA6 encryption/decryption. Nothing special here, use OpenSSL 3.0's `EVP_CIPHER_*` instead of the deprecated `AES_*` API but continue to support the deprecated OpenSSL 1.1.1 API.
I have:
=> Support OpenSSL 3.0 for ipcipher CA6 encryption/decryption

pdns/dnsdist-idstate.hh, pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua.hh, pdns/dnsdist.cc, pdns/dnsdistdist/dnsdist-lua-ffi-interface.h, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsdistdist/docs/rules-actions.rst
This pull request introduces the ability to cap the TTL of records after they have been inserted into the packet cache, so that we can keep them in cache for as long as possible but still return a lower TTL to the client.
<strike>Note that this pull request builds on https://github.com/PowerDNS/pdns/pull/12383 and will have to be rebased.</strike>
I have:
=> dnsdist: Add the ability to cap the TTL of records after insertion into the cache

pdns/dnsdist.cc, pdns/dnsdistdist/doh.cc
When we are in "single acceptor thread" mode, merge the 'main' and 'client' DoH threads into a single one. We use separate threads to reduce the separate the handling of the HTTP/2 traffic from the DNS handling, to reduce latency, but that does not really make sense on small devices with a single, limited CPU core. On these we prefer using as few threads as possible to reduce the context switches and the memory usage.
<strike>Note that this pull request builds on https://github.com/PowerDNS/pdns/pull/12383 and will have to be rebased.</strike>
I have:
=> dnsdist: Merge the 'main' and 'client' DoH threads in single acceptor mode

.github/actions/spell-check/expect.txt, pdns/dnsdist-cache.cc, pdns/dnsdist-cache.hh, pdns/dnsdist-web.cc, pdns/dnsdist.cc, pdns/dnsdistdist/docs/guides/webserver.rst, pdns/dnsdistdist/docs/upgrade_guide.rst
- Properly record cache-hits as responses: For a very long time we have not been adding cache-hits to the responses counter, which is wrong. Let's fix it now. Closes https://github.com/PowerDNS/pdns/issues/12045.
- Only record one hit or miss per query in the cache metrics: The scope-zero feature and the DoH paths can actually do more than one lookup per query, and until now this led to an increase of the per-cache metric for every lookup, while the global `cache-hits` and `cache-misses` metrics were only updated once per query. This has led to several questions and misunderstandings, so we now only update the per-cache metrics once per query as well. Closes https://github.com/PowerDNS/pdns/issues/12398.
- Update the prometheus sample in the documentation: It was very old and not …
=> dnsdist: Proper accounting of response and cache hits

pdns/dnsdistdist/doh.cc, pdns/libssl.cc, pdns/libssl.hh, pdns/tcpiohandler.cc
OpenSSL 3.0: TLS MAC handling. Use `EVP_MAC_CTX` instead of `HMAC_CTX` on OpenSSL 3.0 but continue to support `HMAC_CTX` for OpenSSL < 3.0.
I have:
=> OpenSSL 3.0: TLS MAC handling

pdns/recursordist/lwres.cc, pdns/recursordist/lwres.hh, pdns/recursordist/pdns_recursor.cc
Avoid processing a chain with queries having different ECS data by lwres:asyncresolve() as it assumes the mask received corresponds to the mask sent out, so do not chain ecs queries.
I have:
=> rec: do not chain ecs enabled queries

pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh, pdns/recursordist/test-syncres_cc3.cc
Note: I'm marking this as "Draft" since I _might_ have overlooked a case where the forward to a forwarder in the RD=0 case is actually needed or useful. I cannot think of one and the unit tests and regression tests agree, but I do need independent confirmation on this. That said:
Since forever, there has been special case code for forwarded queries in the RD=0 case.  This special case code does a hardcoded RD=0 query to the specified forwarder.  This code has two consequences:
1. Even if the forwarder is marked recursive it gets a RD=0 query
2. The cache is not consulted at all
The corresponding unit tests actually test this behaviour, but after historic digging with help from @rgacogne it turns out the the unit test do not reflect the desired functionality, but the current state of …
=> rec: Change the way RD=0 forwarded queries are handled.

pdns/libssl.cc
=> dnsdist: Gracefully handle a failure to create a TLS server context

.github/workflows/build-and-test-all.yml, .github/workflows/builder-dispatch.yml, .github/workflows/builder.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/formatting.yml, .github/workflows/fuzz.yml
Added using https://github.com/step-security/secure-workflows For more information see:
- https://github.com/ossf/scorecard/blob/d8fefc9b246db3600c777e9d60d441d7c386ce1d/docs/checks.md#token-permissions
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
(cherry picked from commit aff4e1eafa5bbc4e9ef6acee9d73b2154e0ab9b9)
Backport of #12254 
I have:
=> rec: Backport 12254 to rec-4.8.x: Restrict permissions for GITHUB_TOKEN in our workflows

ext/json11/json11.cpp, pdns/webserver.cc, regression-tests.api/test_Servers.py
Backport of #12260 
The existing code assumes the strings are alreayd valid UTF8 and contain potential out-of-bound accesses.
Also urlEncode path in log lines, as it trips pytest.xml:
Running tests...
$ 'pytest' '--junitxml=pytest.xml' '-v'
==STDOUT===
==STDERRR===
File "/home/otto/pdns/regression-tests.api/runtests.py", line 304, in <module>
print(serverproc.stderr.read())
File "/usr/lib/python3.9/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xeb in position 4304: invalid continuation byte
There might be more places where this is needed.
(cherry picked from commit 1478a2c8713535e4cbd1943e2526e3527d58a19b)
I have:
=> rec: Backport 12260 to rec-4.8.x: Properly encode json string containing binary data

pdns/dnsdistdist/doh.cc, pdns/dolog.hh, pdns/libssl.cc, pdns/libssl.hh, pdns/tcpiohandler.cc, regression-tests.dnsdist/test_OCSP.py
Contrary to certificates and keys, OCSP files are never required to provide a working DoT or DoH service, so it's better to start even if would not load all, or any, OCSP files.
Closes #12341.
I have:
=> dnsdist: Skip invalid OCSP files after issuing a warning

pdns/dbdnsseckeeper.cc, pdns/decafsigners.cc, pdns/dnssecinfra.cc, pdns/dnssecinfra.hh, pdns/dnssecsigner.cc, pdns/opensslsigners.cc, pdns/pdnsutil.cc, pdns/pkcs11signers.cc, pdns/pkcs11signers.hh, pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc10.cc, pdns/recursordist/test-syncres_cc4.cc, pdns/sodiumsigners.cc, pdns/test-signers.cc, pdns/ws-auth.cc
For `ECDSA`, and likely for `RSA`, computing the public key is not a cheap operation. So instead of computing it twice to get the lookup key for our signatures cache, reuse the computed public key and only compute its digest.
In addition, since ed* algorithms were already using the whole key instead of a digest, place the cut off at public keys larger than 64 bytes, meaning that only `RSA` ones (128+ bytes) will be hashed.
This provides an additional speedup for `ECDSA` keys (32 or 48 bytes) since they no longer need to be hashed, and simplifies the signers code as the hashing can be moved to signature key cache now that it only depends on they key size.
For reference the size of a `SHA-1` digest is 20 bytes.
In my tests this reduces by 30% the cost of calling `addRRSigs()` for `ECDSA` …
=> auth: Speed up ECDSA and RSA signatures

tasks.py
This PR enables initialization of automatic variables to a pattern in our CI, in order to better catch uninitialized variables.
Enabling this option has two theoretical drawbacks:
- runtime is slightly slower
- it does hide the use of uninitialized variables from memory sanitizers like clang's Memory Sanitizer and Valgrind.
The first point should not matter much for our CI since we are already running ASAN, TSAN and/or UBSAN anyway, and the second does not apply either since we do not enable these sanitizers either (Valgrind is too slow, and memory sanitizer is hard to get right because some cases require instrumenting shared libraries as well). Note that this does not prevent from compiler from reporting the use of uninitialized variables via `-Wuninitialized` or `wmaybe-uninitialized` …
=> CI: Initialize automatic variables to a pattern in our CI 

.not-formatted, pdns/dnsdist-carbon.cc, pdns/dnsdist-lua.cc, pdns/dnsdist.cc, pdns/dnsdistdist/dnsdist-carbon.hh
This PR implements a refactoring of the Carbon handling in dnsdist. Each remote endpoint is now handled by its own thread, as to prevent a slow/unreachable server from impacting others.
It also implements an exponential back-off when a server cannot be reached properly, as to not overload a suffering endpoint.
Hopefully closes #10517 and #11216.
I have:
=> dnsdist: Better handling of multiple carbon servers

pdns/recursordist/negcache.cc, pdns/recursordist/negcache.hh
=> rec: Backport 12352 to rec 4.8.x: Refresh of negcache stale entry might use wrong qtype 

pdns/pdns_recursor.cc
=> rec: Backport 12368 to rec-4.8.x: Add the 'parse packet from auth' error message to structured logging

pdns/recursordist/negcache.cc, pdns/recursordist/negcache.hh, pdns/recursordist/test-syncres_cc10.cc, pdns/syncres.cc
=> rec: Backport 12395 to rec-4.8.x: When the stale function is triggered, wrong data can be returned from negcache and record cache

pdns/recursordist/secpoll-recursor.cc
Fixes #12466
A more fundamental approach would be to make sure to not use keys that have special meaning to systemd-journal in the structured logging backend code.
I have:
=> rec: do not use "message" as key, it has a special meaning to systemd-journal

pdns/minicurl.cc
=> MiniCurl: Stop using the deprecated CURLOPT_PROTOCOLS on curl 7.85+

pdns/dnsdist-lua-actions.cc, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsparser.cc, pdns/dnsparser.hh, pdns/test-dnsparser_cc.cc
By using `std::unordered_set` instead of `std::set`.
I have:
=> dnsdist: Rewrite/clear records from DNS packets slightly faster

pdns/dnsparser.cc
Technically that does not matter because the size is limited to `2^16-1` bytes, and if the size is incorrect we will throw during the copy, but it's nicer to detect the incorrect size before allocating, as suggested by Coverity (CID 383044).
I have:
=> Check the record size before allocating in PacketReader::copyRecord()

modules/lmdbbackend/lmdbbackend.cc, pdns/dnsparser.cc, pdns/dnsparser.hh
This two commits improve the performance of the LMDB backend a bit (I remember seeing up to 10% reduction in CPU usage in an unrealistic benchmark):
- avoid the allocation of a string in `LMDBBackend::get()`
- reduce allocations and copies in `DNSRecordContent::deserialize()`: the move from a vector to a PacketBuffer prevents the memory from being zeroed while we are going to overwrite it right away. The change from MOADNSParser to PacketReader avoids the need to copy the header and the whole packet (allocation + copy), parse the qname again, as well as the allocation of a vector of records while we know we have only one of these.
I have:
=> auth: Small performance improvement for the LMDB backend

pdns/dnsdist-cache.cc, pdns/dnsdist-ecs.cc, pdns/dnsdist-lua-bindings-dnsquestion.cc, pdns/dnsdistdist/dnsdist-discovery.cc, pdns/dnsdistdist/dnsdist-dnsparser.cc, pdns/dnsdistdist/dnsdist-dnsparser.hh, pdns/dnsdistdist/dnsdist-lua-ffi-interface.h, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsdistdist/docs/reference/dq.rst, pdns/dnsdistdist/doh.cc, pdns/dnsdistdist/test-dnsdist-dnsparser.cc, pdns/dnsparser.cc, pdns/dnsparser.hh, pdns/namespaces.hh, pdns/packetcache.hh, pdns/protozero.cc, pdns/recursordist/ednsextendederror.cc, regression-tests.dnsdist/test_Advanced.py
In some setups, we might need to get the result for a different qname and change the response to set the owner names of the records matching the changed qname back to the initial qname. Note that this is brittle and should only be used in very specific cases.
<strike>This PR is based on top of https://github.com/PowerDNS/pdns/pull/12388 and will have to be rebased.</strike>
I have:
=> dnsdist: Add the ability to change the qname and owner names in DNS packets

pdns/dnsparser.cc
I removed the pdns_string_view alias in #12417 as it was no longer used, but merging #11511 actually reintroduced it, breaking the build.
I have:
=> Fix a collision between #12417 and #11511

pdns/dnsdist-lua.cc
I did not manage to avoid repeating the function name, unfortunately, without writing something terribly ugly (mixing function-like macros with lambdas), so for now this will have to do.
Closes https://github.com/PowerDNS/pdns/issues/11894.
I have:
=> dnsdist: Refactor 'cannot be used at runtime' handling

pdns/ixfrdist-stats.cc, pdns/ixfrdist-stats.hh, pdns/ixfrdist.cc, regression-tests.ixfrdist/test_Stats.py, tasks.py
Without the quoting, the output isn't even valid. Once it's valid (quoted), promtool warns that counters should be suffixed with `_total`, so I changed that too.
While this looks like breaking changes marked with `backport-to-auth-4.7.x?`, before this PR, the metrics endpoint did not work at all, so I've decided to take the opportunity to sneak some improvements in. I'll likely do another PR to add some more stats like CPU/RAM/FD usage.
I have:
=> ixfrdist /metrics: formatting, cleanup, one new metric

tasks.py
Example failure: https://github.com/PowerDNS/pdns/actions/runs/4076304690/jobs/7023858077
I have:
=> Fix GH CI docs upload

.github/workflows/build-and-test-all.yml, regression-tests/recursor-test
It seems that putting a sleep between the `dnsbulktest` runs in `regression-tests/recursor-test` circumvents the UDP packet loss issues we have been seeing without the sleep.
Still have to find out how and why.
I have:
=> rec: less bulk test variations and enable TSAN for bulk tests

pdns/ixfrdist-stats.hh, regression-tests.ixfrdist/test_Stats.py
Before C++20 std::atomic variables are not guaranteed to be initialized, even though it looks like compilers are actually doing the initialization even in C++17.
Reported by Coverity as CID 1504405.
I have:
=> ixfrdist: Make sure that our metrics are properly initialized

pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua-rules.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-lua.hh, pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc, pdns/dnsdistdist/dnsdist-lua-bindings-protobuf.cc, regression-tests.dnsdist/test_Caching.py, regression-tests.dnsdist/test_Routing.py
Change behavior of many commands to actually check the passed in vars / parameters that they are consumed fully. If they are not, we assume that they were not supported, and indicate first failing var / parameter.
I have:
=> dnsdist: Warn on unsupported parameters

pdns/opensslsigners.cc
Fix some incorrect usages of OpenSSL 1.1/3.0 functions outside of build=guarded blocks.
I have:
=> OpenSSL 3.0: Stay compatible with OpenSSL 1.0 to Fix CentOS7 builds

pdns/logger.cc, pdns/logger.hh, pdns/recursordist/aggressive_nsec.cc, pdns/recursordist/docs/manpages/rec_control.1.rst, pdns/recursordist/docs/running.rst, pdns/recursordist/docs/upgrade.rst, pdns/recursordist/pdns_recursor.cc, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh, pdns/recursordist/rec_channel_rec.cc, pdns/recursordist/rec_control.cc, pdns/recursordist/secpoll-recursor.cc, pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh, pdns/validate.cc
The (open) fd is passed to the recursor. The recursor will then dump its trace info to that fd. It will also add microsecond timestamps.
An example:
```
us === START OF TRACE 2023-01-31T09:07:58.425 ===
94 QM www.powerdns.com: doResolve
98 www.powerdns.com: Wants DNSSEC processing, auth data required by query for A
112 QM www.powerdns.com: Step0 Not cached
115 QM www.powerdns.com: Checking if we have NS in cache for 'www.powerdns.com'
117 QM www.powerdns.com: No valid/useful NS in cache for 'www.powerdns.com'
119 QM www.powerdns.com: Checking if we have NS in cache for 'powerdns.com'
124 QM www.powerdns.com: NS (with ip, or non-glue) in cache for 'powerdns.com' -> 'pdns-public-ns1.powerdns.com', within bailiwick: 1, in cache, ttl=86387
130 QM www.powerdns.com: NS (with ip, or non-glue) in …
```
=>  rec: rec_control trace-regex: trace to a file or stdout instead of the general log

pdns/recursordist/aggressive_nsec.cc, pdns/recursordist/aggressive_nsec.hh, pdns/recursordist/docs/settings.rst, pdns/recursordist/rec-main.cc, pdns/recursordist/test-aggressive_nsec_cc.cc, pdns/recursordist/test-syncres_cc.cc
This PR explores the following idea:
The aggressive cache is not very effective for large NSEC3 domains: each NSEC3 record only covers a relatively small amount of random names.
We only want to put NSEC3 records in the aggressive cache if there is a decent chance a hash will hit it. Hashes are random wrt the corresponding names.
So look at the bitwise common prefix of the owner and next, and do not store the record if the common prefix is long.
We also might want to introduce a switch to completely forget the aggressive cache for the NSEC3 case.
Missing: tests, settings code.
BTW: this also fixes/circumvents a bug in `isMinimallyCoveringNSEC3` as the master one confuses the representations of owner and next.
The common prefix loop can abort if it exceeds the threshold. I'll write that if …
=> Only store NSEC3 records in aggressive cache if we expect them to be effective.

pdns/dbdnsseckeeper.cc, pdns/dnssecinfra.cc, pdns/dnssecinfra.hh, pdns/dnsseckeeper.hh, pdns/opensslsigners.cc, pdns/pdnsutil.cc, pdns/test-signers.cc
Small cleanup. Avoid the use of raw pointers in checkKey(s) routines.
I have:
=> Avoid the use of raw pointers in checkKey(s) routines

pdns/dnsdist.cc
This is very useful when investigating an issue that prevent dnsdist from starting, for example.
Closes #10932.
I have:
=> dnsdist: List version number early

regression-tests.dnsdist/.gitignore, regression-tests.dnsdist/Makefile, regression-tests.dnsdist/runtests
This makes my life easier during testing, and feels cleaner.
I have:
=> dnsdist: Move the certs handling to a Makefile in the regression tests

pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua-inspection.cc, pdns/dnsdist-lua-rules.cc, pdns/dnsdistdist/dnsdist-lua-bindings-kvs.cc
Fixes https://github.com/PowerDNS/pdns/issues/12184.
There is one remaining usage that is handled in https://github.com/PowerDNS/pdns/pull/12537 to prevent a conflict.
I have:
=> dnsdist: Stop using the deprecated `boost::optional::get_value_or`

.github/workflows/build-and-test-all.yml, .github/workflows/builder.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/misc-dailies.yml
Defines vars for specific scheduled workflow files. This allows a repository to enable a specific workflow's schedule w/o enabling all of them.
Closes #12519
Fixes #12498
Note: I've only added guards to things that don't have `needs`. Ideally all of the `needs` things depend on things that are guarded.
I have:
=> Run scheduled workflows only if a var is set

.github/workflows/build-and-test-all.yml, .github/workflows/codeql-analysis.yml, tasks.py
Added removal and installation of ODBC packages to version 2.3.6. Bug found in latest available in Microsoft repo (<https://github.com/microsoft/linux-package-repositories/issues/36>)
I have:
=> gh actions: added manual removal/installation of odbc packages

regression-tests.dnsdist/test_Advanced.py
It looks like it takes longer than expected for the timeout to be recorded when running on GitHub Actions.
I have:
=> dnsdist: Give the 'flags on timeout' test more headroom

pdns/dnsdist-console.cc, pdns/dnsdist-lua-rules.cc, pdns/dnsdistdist/dnsdist-rules.hh, pdns/dnsdistdist/docs/rules-actions.rst, pdns/dnsdistdist/test-dnsdistrules_cc.cc
This PR:
- add a check to prevent several threads from cleaning up the IP database at the same time (the threads are serialized by a lock, but they would still do the work twice for no good reason) ;
- make lookups roughly 50% faster by using a hashed index instead of an ordered one ;
- divide the IP database in separate shards, using the new hash index, to reduce lock contention: this increases the performance of the rule up to 6 times in my tests (20 threads, 10 shards)
Hopefully closes https://github.com/PowerDNS/pdns/issues/10124.
I have:
=> dnsdist: Improve the scalability of MaxQPSIPRule()

pdns/dnsdist-cache.cc, pdns/dnsdist-dynblocks.hh, pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua-bindings-dnsquestion.cc, pdns/dnsdist-lua-bindings.cc, pdns/dnsdist-lua-rules.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-lua.hh, pdns/dnsdist.cc, pdns/dnsdistdist/dnsdist-async.cc, pdns/dnsdistdist/dnsdist-backend.cc, pdns/dnsdistdist/dnsdist-lua-bindings-dnscrypt.cc, pdns/dnsdistdist/dnsdist-rules.hh, pdns/dnswriter.cc
Most of these are 'performance' warnings in parts of code where performance does not really matter (or the compiler should already do the right thing without our help), but there is no harm in being more consistent. It also makes it easier to spot more meaningful warnings in the future. The remaining changes are false-positives where `cppcheck` does not detect that null-pointer dereferences cannot actually happen, so I edited the code to make it clearer (removing redundant checks in some cases, actually adding some in other cases).
I have:
=> dnsdist: Fix warnings from cppcheck

.not-formatted, pdns/decafsigners.cc, pdns/dnssecinfra.cc, pdns/dnssecinfra.hh, pdns/opensslsigners.cc, pdns/pdnsutil.cc, pdns/sodiumsigners.cc, pdns/test-signers.cc
- Fixes some confusing argument ordering and method naming.
- Instead of PEM-related functions only being able to handle files, introduce helpers to handle (import/export from) strings as well.
- Use the new helpers to simplify the tests a little.
- Some documentation formatting.
I have:
=> Signers cleanup

pdns/recursordist/docs/settings.rst
If I understood `serve-stale-extensions` correctly it's working on 30s intervals. Thus an hour should be 120 and not 200, at least if your hours also have 3600 seconds. :wink:
I have:
=> rec doc: serve-stale-extensions works on 30s so an hour should be 120x

contrib/ProtobufLogger.py, pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-protobuf.cc, pdns/dnsdist-protobuf.hh, pdns/dnsdistdist/docs/rules-actions.rst, regression-tests.dnsdist/test_Protobuf.py
Closes https://github.com/PowerDNS/pdns/issues/9335.
I have:
=> dnsdist: Add support for metadata in protobuf messages

pdns/dnsdistdist/doh.cc
During the recent addition of the concurrent connection checks for incoming DoH connections, I introduced a bug by using the connection object just after it has been released.
This was fortunately spotted by ASAN pretty quickly.
I have:
=> dnsdist: Fix a use-after-free in the incoming DoH path

builder-support/debian/dnsdist/debian-buster/rules, builder-support/specs/dnsdist.spec
dnsdist is already built and tested with LTO enabled in our CI, and I have successfully built packages against these changes using our "Trigger specific package build" workflow.
We already know that building with LTO reduces the size of the `dnsdist` binary, and we expect performance gains as well, but I have not yet measured those.
The GCC version in EL8 requires explicitly setting the `AR` and `RANLIB` to use, so I'm setting them for all RPM-based builds since it should not hurt.
This closes the dnsdist part of https://github.com/PowerDNS/pdns/issues/11032
I have:
=> dnsdist: Enable Link-Time Optimization for our packages

docs/catalog.rst
I think the address `127.0.0.1` makes little sense when creating a secondary zone, and I hope this is a tad less confusing.
I have:
=> replace address of primary

pdns/dnsdist-protocols.hh
This fixes building dnsdist with gcc13:
```
In file included from dnsdist-protocols.cc:26:
dnsdist-protocols.hh:32:8: error: use of enum 'typeenum' without previous declaration
32 |   enum typeenum : uint8_t
|        ^~~~~~~~
dnsdist-protocols.hh:32:19: error: 'uint8_t' was not declared in this scope
32 |   enum typeenum : uint8_t
|                   ^~~~~~~
dnsdist-protocols.hh:25:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
24 | #include <vector>
+++ |+#include <cstdint>
25 | #include <string>
```
I have:
=> dnsdist-protocols.hh: include <cstdint>

docs/domainmetadata.rst
A word too many in ALSO-NOTIFY
I have:
=> Small typo in ALSO-NOTIFY

docs/dnssec/pkcs11.rst, docs/migration.rst, docs/tsig.rst, pdns/recursordist/docs/changelog/pre-4.0.rst, pdns/recursordist/docs/settings.rst
both `feature is experimental` and `an experimental feature` were used in the repository (although, some hits are from doxygen's config, which shouldn't be counted)... this picks the one that seems to be used most by pdns docs...
I have:
=> docs: harmonize `an experimental feature`

pdns/dnsdist-protobuf.cc, regression-tests.dnsdist/dnsdisttests.py, regression-tests.dnsdist/test_Metrics.py, regression-tests.dnsdist/test_Protobuf.py
The `MetaValue` is required to exist, which means that we need to have at least one value.
The DoH-related values should be empty non-DoH protocols, but the protocol buffer messages should still be sent, with the expected content.
Fixes https://github.com/PowerDNS/pdns/issues/12560
I have:
=> dnsdist: Ensure we have at least one protobuf MetaValue

pdns/dnsdistdist/docs/reference/svc.rst, regression-tests.dnsdist/test_SVCB.py
As per the IANA registry, 7 is the id assigned for the dohpath SVCB parameter: https://www.iana.org/assignments/dns-svcb/dns-svcb.xhtml
The dnsdist docs and some SVCB regression tests use `key42` for the `dohpath` SVCB parameter, but the assigned id is 7, hence `key7`.
I have:
=> Use key7 for dohpath in SVCB examples in dnsdist

set-ubuntu-mirror/action.yml
Modifying the action set-ubuntu-mirror to add prioritization of the ubuntu mirror over the Microsoft repo for ODBC packages.
Checklist
I have:
=> Avoid Microsoft repo for ODBC packages. Step 2 of 3: prioritize ubuntu mirror

pdns/dnsdist-protobuf.cc
When DoH is disabled, protobuf is trying to access unavailable struct fields. Don't include these in the protobuf messages since they are not available.
I have:
=> dnsdist-protobuf: fix compilation with DoH disabled

ext/yahttp/yahttp/reqresp.hpp, ext/yahttp/yahttp/router.cpp, ext/yahttp/yahttp/router.hpp
The previous version relied on having `HAVE_CXX11` defined, which is not true when you are compiling with C++17, for example, even though the C++11 features are available (`HAVE_CXX17` is defined but that does not help).
I'll open a pull request in the YaHTTP repo as well.
I have:
=> YaHTTP: Better detection of whether C++11 features are available

pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/doh.cc, pdns/dnsdistdist/test-dnsdisttcp_cc.cc, regression-tests.dnsdist/test_Metrics.py
The fix is very similar to the one in https://github.com/PowerDNS/pdns/pull/12590 but I prefer not to rely on the latency metric, and explicitly tells whether the response is coming from a backend instead.
I added regression tests to make sure we don't break that again in the future.
Reported by @phonedph1 (many thanks!).
I have:
=> dnsdist: Only increment the 'servfail-responses' metric on backend responses

m4/pdns_d_fortify_source.m4, m4/pdns_enable_lto.m4
`gl_COMPILER_OPTION_IF` already does the needful, so we do not need to tinker with the flags.
This might help with the issue reported in https://github.com/PowerDNS/pdns/issues/11032 but I'm unfortunately unable to reproduce it, so I'm not sure.
I have:
=> m4: Clean up the fortify and LTO m4 by not directly editing flags

pdns/recursordist/negcache.cc, pdns/recursordist/negcache.hh, pdns/recursordist/syncres.cc, pdns/recursordist/test-negcache_cc.cc
This is a reason serve-stale is causing an intermittent high CPU load: the wipe function actually called was deleting a (potentially large) subtree of the negcache on all shards. Root cause was an unaccounted for conversion between short and bool.
I have:
=> rec: Call the right wipe function for negcache in the serve-stale case

pdns/recursordist/syncres.cc, pdns/recursordist/test-syncres_cc7.cc
Reported by @mnordhoff  as `Recursor: False AD bit in empty insecure response from buggy F5`:
```
`vietnamplus.vn.` is an insecure zone.
`en.vietnamplus.vn.` is an extremely janky zone that responds poorly to everything except A queries; its NSes are `f51.vnanet.vn.` and `gtm03.vnanet.vn.`, so we can guess why. ;-)
`dig [en.vietnamplus.vn](http://en.vietnamplus.vn/) aaaa` gives an empty response with the AD bit on. (I assume this affects almost every query type; I'm using AAAA as an example.)
I'm running Recursor 4.9.0~alpha0+master.930.g791621029-1pdns.focal (latest at the time of writing) on Ubuntu 20.04 amd64.
On Quad9 (Miami PoP) PowerDNS, I've seen (empty) responses with and without the AD bit. The latter may have been cache hits; I dunno.
(Quad9 Unbound returns empty, insecure …
```
=> rec: Update validation state after a missing negative indication

pdns/recursor_cache.cc, pdns/recursor_cache.hh
Adding this to 4.x.8 to make it easier to compare record cache vs negcache code (PR for negcache upcoming)
No functional change.
Backport of #12347
I have:
=> rec: Backport 12347 to rec-4.x.8: Use correct logic for isEntryUsable()

pdns/recursordist/syncres.cc, pdns/recursordist/test-syncres_cc10.cc
There are several issues here: we do not want to retry on an exception ever as an exception indicates a final failure. e.g. a resolution timeout for the whole query. Recursing in that state will generate an exception storm. Individual timeouts of contacting a nameserver do not generate an exception.  Also, we do not want to recurse if the cache lookup for stale records did not produce anything in the second iteration, we know it's probably going to be fatal and it requires (portentially) a lot of work to find out.
This solves CPU pegging seen.
Check diff ignoring white-space, otherwise it's hard to read.
I have:
=> rec: Fix serve-stale loop logic

pdns/recursordist/negcache.cc, pdns/recursordist/negcache.hh
Use same `isEntryUsable()` logic as record cache.
I have:
=> rec: Fix serve-stale logic in negcache by following the record cache case more closely

pdns/recursordist/test-syncres_cc10.cc
=> rec: test that an ImmediateServFailException isn't hidden by the serve-stale logic

m4/boost.m4, pdns/dnsdist-protocols.cc, pdns/dnsdist-protocols.hh
- dnsdist-protocols.hh: include <cstdint> #12569 
- clang14 has reached MacOS #11971 
I have:
=> dnsdist-1.7.x: Backport build fixes

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc
Backport of #12074 to rel/dnsdist-1.7.x: add getPoolNames() function, returning a list of pool names 
I have:
=> dnsdist-1.7.x: add getPoolNames() function

pdns/dnsdist-idstate.hh, pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua-bindings-dnsquestion.cc, pdns/dnsdist-protobuf.cc, pdns/dnsdistdist/dnsdist-lua-ffi-interface.h, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsdistdist/docs/reference/dq.rst, pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
I forgot to add these before, and they are already used by the recursor.
I have:
=> dnsdist: Add Lua bindings for PB requestorID, deviceName and deviceID

modules/godbcbackend/sodbc.cc
Fixing issue #12324, Generic ODBC backend. Setting ColumnSize argument (field length of SQL_VARCHAR type parameter) in SQLBindParameter function call. It's needed to properly bind PowerDNS variables (like domain.name) to SQL statements
I have:
=> auth: fix ColumnSize argument in SQLBindParameter #12324

pdns/dnsdistdist/doh.cc
This will likely fix https://github.com/PowerDNS/pdns/issues/12645, even though it's not clear to me how we end up with an unset qname.
Note that master already use `toLogString()` since that code has been refactored in the meantime.
I have:
=> dnsdist: Use toLogString for the qname to prevent an error if it's empty

pdns/dnsdistdist/html/index.html, pdns/dnsdistdist/html/local.js
Since 1.8.0 we have separate latencies based on the incoming transport, but the internal web interface was only reporting the UDP one. After this commit the interface will display the latency for UDP, TCP, DoT and DoH queries.
Reported by Stephane Bortzmeyer (thanks!).
I have:
=> dnsdist: Report per-incoming transport latencies in the web interface

pdns/dnsdist.cc, regression-tests.dnsdist/test_Advanced.py
It is a slightly different issue than https://github.com/PowerDNS/pdns/issues/12581 because we cannot harvest the original destination address on a loopback interface, so the code path is a bit different.
Fixes https://github.com/PowerDNS/pdns/issues/12640
I have:
=> dnsdist: Use the correct source address when harvesting failed

pdns/dnsdist-lua-inspection.cc, pdns/dnsdistdist/dnsdist-dynblocks.cc, pdns/dnsdistdist/dnsdist-lua-inspection-ffi.cc, pdns/dnsdistdist/dnsdist-lua-inspection-ffi.hh, pdns/dnsscope.cc, pdns/statnode.cc, pdns/statnode.hh
This PR adds the number of cache hits to `StatNode` objects.
I have:
=> dnsdist: Count hits in the StatNode

pdns/dnsdist-carbon.cc, pdns/dnsdist-lua-bindings.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-snmp.cc, pdns/dnsdist.hh, pdns/dnsdistdist/dnsdist-lbpolicies.cc, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsdistdist/html/local.js, regression-tests.dnsdist/test_BackendDiscovery.py
Since 1.8.0 we separately record the latency for queries forwarded over UDP and TCP, to get a better picture of what is going on. It means we have to be careful to pick the relevant one when looking at the latency.
This is a follow-up on https://github.com/PowerDNS/pdns/pull/12638.
I have:
=> dnsdist: Report the TCP latency for TCP-only Do53, DoT and DoH backends

pdns/dnsrecords.cc, pdns/dnsrecords.hh
When `svc-autohints` is enabled, the content of SVCB and HTTPS records is modified in `PacketHandler::doAdditionalProcessing()` to expand the IPv4 and IPv6 with their actual values.
This causes an issue because the content of these records might be shared between threads, via the record cache, and one thread could be trying to read from the internal `std::set` while a second thread is altering it, leading to a data race and possibly to memory corruption and a crash.
This is correctly detected by TSAN:
```
WARNING: ThreadSanitizer: data race (pid=102795)
Write of size 8 at 0x7b3400010350 by thread T33:
#0 operator delete(void*) <null> (pdns_server+0x211b7c) (BuildId: 384adc19a67695435bd5e89d0a77f562561f4593)
#1 std::__new_allocator<std::_Rb_tree_node<SvcParam>>::deallocate(std::_Rb_tree_nod …
```
=> auth: Prevent a race during the processing of SVC auto-hints

ext/lmdb-safe/lmdb-safe.hh
this should fix the build on older systems like Ubuntu Bionic and el8
I have:
=> lmdb-safe: remove unused header, plus assert macro presence

pdns/dnsdistdist/dnsdist-secpoll.hh
avoids build failure noticed on Alpine
I have:
=> dnsdist secpoll: explicitly include necessary ctime header for time_t

pdns/dnsdist-cache.cc, pdns/dnsparser.cc, pdns/dnsparser.hh, pdns/recursordist/pdns_recursor.cc, pdns/test-dnsparser_cc.cc, regression-tests.recursor-dnssec/test_PacketCache.py
I added an argument to `ageDNSPacket()` to circumvent having to do it in two places in rec.
I am also wondering if the break in `ageDNSPakcet()` is right:
I suspect we want to continue with other records even if we see an OPT (which does not *have* to be the last as far as I know)
I have:
- [X ] compiled this code
=> rec and dnsdist: fix a dnsheader unaligned case

pdns/dnsdist-lua-rules.cc, pdns/dnsdist-lua.hh
The parameters were properly parsed but not marked as consumed, leading to warnings such as:
```
addAction: Unknown key 'name' given - ignored
```
I have:
=> dnsdist: Fix 'Unknown key' issue for actions and rules parameters

pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh
Now that we have getQMFallbackMode(), we can go back to always increase depth and never decrease it and adapt the upper bound check if needed.
I have:
=> rec: re-establish "recursion depth is always increasing" invariant

regression-tests.dnsdist/dnsdisttests.py, regression-tests.dnsdist/test_API.py, regression-tests.dnsdist/test_Advanced.py, regression-tests.dnsdist/test_DNSCrypt.py, regression-tests.dnsdist/test_DOH.py, regression-tests.dnsdist/test_Metrics.py, regression-tests.dnsdist/test_TLS.py
Some of the tests need the API port to be available in addition to the regular Do53 ones. In addition some of the tests are not using the default listening address or port, so we need to wait for the correct one to come up.
I have:
=> dnsdist: Wait until dnsdist is listening on the requested port in the tests

pdns/recursordist/aggressive_nsec.cc, pdns/recursordist/syncres.cc, pdns/validate.cc, pdns/validate.hh
This is a small cleanup, passing simple references (`const T&`) instead of shared pointers ( `std::shared_ptr<const T>&`) to the functions from `validate.hh/validate.cc` whenever possible.
I have:
=> validate: Stop passing shared pointers all the way down

pdns/recursordist/syncres.cc, regression-tests.recursor-dnssec/test_AggressiveNSECCache.py
Fixes #12691
There is a slight complication here: If QM found an error, a retry without QM is done, and that clears the EDE but might not find an EDE itself (since it does not walk all labels).  So remember the original EDE and put it back in place if the last effort attempt failed but did not set an EDE.
I have:
=> rec: reset EDE in context when starting to resolve

regression-tests.dnsdist/dnsdisttests.py
This prevents a long list of
```
kill... <Popen: returncode: None args: ['../pdns/dnsdistdist/dnsdist', '--supervised...>
```
lines when running with TSAN-enabled.
In my tests it did not seem to really slow the build: roughly 3% slower but that might even be in the error margin for these tests.
I have:
=> dnsdist: Wait a bit longer for the process to exit before killing it

pdns/recursordist/pdns_recursor.cc, pdns/recursordist/syncres.cc
PowerDNS Security Advisory 2023-02: Deterred spoofing attempts can lead to authoritative servers being marked unavailable (CVE-2023-26437)
Low severity
I have:
=> rec: Deterred spoofing attempts can lead to authoritative servers being marked unavailable

pdns/pdnsutil.cc
Fixes a typo in pdnsutil clear-zone help output
from
```bash
$ pdnsutil clear-zone foo bar
Syntax: pdnsutil edit-zone ZONE
```
to
```bash
$ pdnsutil clear-zone foo bar
Syntax: pdnsutil clear-zone ZONE
```
I have:
=> Fixes a typo in pdnsutil clear-zone help output

pdns/recursordist/docs/performance.rst
The performance section of the PowerDNS Recursor documentation has example firewall rules for skipping conntrack for 53/udp, but it may be tempting for the reader to assume that the firewall rules shown there would be all the rules they need.
This adds a reminder (right in the context of the example rules) that they still need their regular firewall rules for 53/tcp.
I have:
=> Add reminders for 53/tcp rules in the NOTRACK example rules in pdns-rec docs

pdns/recursordist/docs/settings.rst, pdns/recursordist/pdns_recursor.cc, pdns/recursordist/rec-main.cc, pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh, regression-tests.recursor-dnssec/test_PacketCache.py
Distinguish between negative answers (NxDomain and NoData), failure to resolve (e.g. ServFail and completely empty answers) and ordinary answers when capping the packet cache TTL. A new setting (packetcache-negative-ttl) is created for that.
NoData is: empty answer section but SOA record present in authority section.
I have:
=> rec: More fine grained capping of packet cache TTL

pdns/dns.cc, pdns/dns.hh
I hope it does not introduce subtle signed/unsigned issues as the original enum had type `int`.
I have:
=> Cleanup rcode enums: base one is 8 bit unsigned, extended one 16 bit unsigned

pdns/recursordist/RECURSOR-MIB.txt, pdns/recursordist/docs/settings.rst, pdns/recursordist/pdns_recursor.cc, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh, pdns/recursordist/rec-snmp.cc, pdns/recursordist/rec-tcounters.hh, pdns/recursordist/rec_channel_rec.cc, pdns/recursordist/recpacketcache.cc, pdns/recursordist/recpacketcache.hh, pdns/recursordist/recursor_cache.cc, pdns/recursordist/syncres.hh, pdns/recursordist/ws-recursor.cc, regression-tests.recursor-dnssec/test_PacketCache.py, regression-tests/recursor-test
Initial draft version, not very much tested, but appears to work as designed. Note that this only changes the PC itself. In the future, this will open up possibilities to reorganise incoming packet handling.
TODO
I have:
=> Rec: sharded and shared packet cache

regression-tests/recursor-test
Switch (the now non-default) `reuseport=no`. No distributor thread, so thundering herds might come up.
We might have to change the bulk test to use multiple src ports (if `SO_REUSEPORT` kernel handling takes that into account).
We also have to think how the new `reuseport=yes` default affects other setups with few clients. At the least very clear docs on how to diagnose imbalance in assigning work to workers are needed. Or revert the default changes...
I have:
=> rec: bulk tests (with their one client driving the test) do not work well with reuseport=yes and many workers

regression-tests/recursor-test
Large imbalance seen without.
We might have to re-evaluate the changed default for `pdns-distributes-queries` and `resueport`.
BTW: I see even greater imbalance in runs before the shared packet cache was committed:
https://builder.powerdns.com/#/builders/119/builds/1714
```
Mar 30 20:16:00 msg="PowerDNS Recursor itself will distribute queries over threads" subsystem="config" level="0" prio="Notice" tid="0" ts="1680200160.814"
...
Mar 30 20:31:16 msg="Queries handled by thread" subsystem="stats" level="0" prio="Info" tid="0" ts="1680201076.890" count="0" thread="0"
Mar 30 20:31:16 msg="Queries handled by thread" subsystem="stats" level="0" prio="Info" tid="0" ts="1680201076.890" count="0" thread="1"
Mar 30 20:31:16 msg="Queries handled by thread" subsystem="stats" level="0" prio="Info" …
```
=> rec: Also set pdns-distributes-queries for bulk tests.

builder-support/debian/recursor/debian-buster/rules
reprepro for builder.powerdns.com cannot handle xz compression yet, but newer Debian and Ubuntu dh_builddeb turn it on by default.
Was accidentally removed in #10072.
Build failure can be seen in https://builder.powerdns.com/#/builders/109/builds/2717
I have:
=> recursor: restore explicit gzip compression for Ubuntu

ext/json11/json11.cpp, pdns/webserver.cc, regression-tests.api/test_Servers.py
=> auth-4.7.x: Properly encode json string containing binary data

pdns/auth-main.cc, pdns/communicator.cc, pdns/mastercommunicator.cc
Kicking the communicator loop for notifies is counter productive since the delay caused by the extra slaveRefresh() and masterUpdateCheck() calls is fare bigger than the time we gain on average. Since #7790 doNotifications() is already called about once every second.
The increased freshness check frequentie is also resulting in a significant load increase. Especially in larger setups when catalog zones are in use.
I have:
=> auth: calm down the communicator loop

docs/backends/lmdb.rst
Fixes warning
```
docs/backends/lmdb.rst:115: WARNING: Explicit markup ends without a blank line; unexpected unindent.
```
I have:
=> docs: lmdb - Add blank line after explicit markup

ext/lmdb-safe/lmdb-typed.hh
Cleanup this warning:
```
In file included from ../../ext/lmdb-safe/lmdb-typed.cc:1: ../../ext/lmdb-safe/lmdb-typed.hh:656:11: warning: variable 'scanned' set but not used [-Wunused-but-set-variable]
int scanned = 0;
^
```
I have:
=> lmdb-safe: remove leftover debug variable

pdns/tcpreceiver.cc
Clean up this warning:
```
tcpreceiver.cc:1005:7: warning: variable 'records' set but not used [-Wunused-but-set-variable]
int records=0;
```
I have:
=> auth: remove unused var in tcpreceiver.cc

pdns/recursordist/docs/lua-config/additionals.rst
The current documentation doesn't mention indirect additional fetching, which this PR corrects. For example NAPTR
returning an SRV record, which then returns an A record requires two lines of configuration to get all the additionals
in a single lookup.
I have:
=> Make Additionals documentation more accurate

pdns/dnsdistdist/docs/reference/config.rst
Remove the default value because the default is all matches.
I have:
=> dnsdist: Update config.rst

pdns/dnsdist-lua.cc
`disableZeroScope` was  accidentally changed into `disableZeroScoping` in commit 597a91a3cec373ebd4172d167a0f9c7500781027
I have:
=> Undo an accidentally change (disableZeroScope -> disableZeroScoping)

docs/manpages/ixfrdist.yml.5.rst, pdns/ixfrdist.cc, pdns/ixfrdist.example.yml
This option allows to cap the refresh interval to a lower value than the one retreived from the SOA.
Fix #6996 
I have:
=> ixfrdist: add a per domain max-soa-refresh option

docs/backends/lmdb.rst, ext/lmdb-safe/lmdb-safe.cc, ext/lmdb-safe/lmdb-safe.hh, ext/lmdb-safe/lmdb-typed.hh, modules/lmdbbackend/lmdbbackend.cc, modules/lmdbbackend/lmdbbackend.hh
When two LightningStream writers add the same zone, they most likely will get different zone IDs, and LightningStream will then synchronise both copies to all receivers. With this PR, auth handles that situation consistently across a cluster.
I have:
=> auth LMDB: handle duplicate domain existence consistently

pdns/dnsdistdist/docs/reference/config.rst
The webserver() function is documented to have lost some arguments with 1.7.0 but this was implemented only with 1.8.0.
I have:
=> Some webserver parameters were removed with 1.8.0

regression-tests.dnsdist/test_API.py
This issue seems to be more prominent when using a TSAN enabled dnsdist.
I do wonder what GH does to get such slowness out of their runners. On a local system, I was only able to reproduce using a slow machine, generate extra load on it and reduce the timeout to 0.5.
I have:
=> dnsdist: github runners can be *very* slow wrt I/O, use a more generous timeout in tests

pdns/recursordist/lwres.cc, pdns/recursordist/lwres.hh, pdns/recursordist/pdns_recursor.cc
Reported by gcc build:
```
wres.cc: In function 'asyncresolve':
lwres.cc:631:26: warning: 'len' may be used uninitialized in this function [-Wmaybe-uninitialized]
631 |       logIncomingResponse(outgoingLoggers, context ? context->d_initialRequestId : boost::none, uuid, ip, domain, type, qid, doTCP, dnsOverTLS, srcmask, len, lwr->d_rcode, lwr->d_records, queryTime, exportTypes);
|                          ^
lwres.cc:390:10: note: 'len' was declared here
390 |   size_t len;
|          ^
```
While there, replace some mandatory pointers by refs
I have:
=> rec: Fix uninited var causing wrong `bytes` field reported in protobuf log in rare cases

.github/workflows/build-and-test-all.yml
This way the tests are still run even if clang-tidy reported a warning, instead of stopping everything.
I have:
=> ci: Add a separate check for clang-tidy failure

pdns/libssl.cc
`EVP_MAC_CTX_set_params` doesn't consume the allocated memory, so it's up to us to free it. This means that we are leaking a small bit of memory every time we process an incoming or outgoing TLS connections involving a TLS ticket.
Reported by Valgrind.
This was introduced in #12412 which was not backported, so only dnsdist 1.8.0 is impacted, and only when compiled with OpenSSL 3.x.
I have:
=> libssl: Fix a memory leak when processing TLS tickets w/ OpenSSL 3.x

.github/scripts/clang-tidy.py, .github/workflows/build-and-test-all.yml
Fixes:
- https://github.com/PowerDNS/pdns/actions/runs/4914871488/jobs/8776690618?pr=12790#step:17:1
- https://github.com/PowerDNS/pdns/actions/runs/4913592644/jobs/8774214076?pr=12790#step:2:1
I have:
=> Fix the `clang-tidy` jobs failing

pdns/dnsdistdist/dnsdist-tsan.supp
There is an actual race when one thread, likely the console, changes the health-check mode of a given backend just when the health-check thread is determining whether it should send a health-check probe. We are fine with getting a wrong value in the health-check thread, as long as we eventually get the new one, so let's not worry about it and add a TSAN suppression.
We already have a suppression for the methods setting the mode, but it looks like they are inlined so TSAN cannot find them.
The TSAN report was:
```
WARNING: ThreadSanitizer: data race (pid=5301)
Read of size 1 at 0x7b78000002ae by thread T11:
#0 DownstreamState::healthCheckRequired(std::optional<long>) /__w/pdns/pdns/pdns/dnsdistdist/dnsdist-backend.cc:555:16 (dnsdist+0x18f003)
#1 healthChecksThread() …
```
=> dnsdist: Suppress a race warning when setting a backend health-check mode

builder-support/dockerfiles/Dockerfile.debbuild-prepare
Debian requires an 'orig' tarball to be part of the source artifact set (along with the .dsc and .debian.tar.xz files), so the debbuild-prepare Dockerfile will now make a copy of the sdist-provided tarball with the proper name.
I have:
=> builder-support: Prepare to make Debian-style source artifacts

pdns/dnsdist-lua-actions.cc, regression-tests.dnsdist/test_Spoofing.py
While spoofing a record, copy the qclass from the request (eliminating the hardcoded QClass::IN).
This fixes [https://github.com/PowerDNS/pdns/issues/12801]
I have:
- [x ] compiled this code
- [ x] tested this code
- [x ] added or modified regression test(s)
- [ x]  checked that this code was merged to master
=> SpoofAction: copy the QClass from the request, fixes #12801 + regression test

.clang-tidy.full
While I agree that we should try to avoid non-const global vars as much as possible, this rule kills the boost testing framework so we cannot keep it.
I have:
=> clang-tidy: Disable cppcoreguidelines-avoid-non-const-global-variables

docs/settings.rst, pdns/auth-main.cc, pdns/pdnsutil.cc, pdns/signingpipe.cc, pdns/signingpipe.hh, pdns/tcpreceiver.cc
Workaround for https://github.com/PowerDNS/pdns/issues/11804. Defaults to previously hard-coded value of 100.
I will add docs.
I have:
=> auth: add setting workaround-11804-max-chunk-records

pdns/recursordist/pdns_recursor.cc
Ideally we would log the received scope info as well, but we do not have access ot that information in the spot where the log object is created.
I have:
=> rec: Log if the answer was marked variable by SyncRes and if it was stored into  the packet cache (if !quiet)

.clang-tidy.full
The current level of 50 is too low for a function like 'handleQueuedHealthChecks' which is quite simple.
I don't want to raise this too high, but we need to be realistic and find a level that is bearable with our current code-base, so that we can first focus on functions that are really too complex, and then consider lowering the bar.
I have:
=> clang-tidy: Increase the cognitive complexity threshold to 75

.clang-tidy.full, pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh, pdns/recursordist/test-syncres_cc1.cc
They are not the same thing.
If this is deemed OK, we might consider making the bound settable.
Needs extra careful review, as I am moving the depth checking logic.
I have:
=> rec: Distinguish between recursion depth and cname length

.github/workflows/fuzz.yml, Dockerfile-cifuzz
Setting a different apt-mirror for fuzz test to avoid errors with the default Ubuntu APT repository.
I have:
=> Changing apt mirror for cifuzz base-builder image

pdns/dnsdistdist/dnsdist-backend.cc, pdns/dnsdistdist/dnsdist-healthchecks.cc
`SO_REUSEADDR` is useful on TCP server sockets to allow binding quickly after restarting the process without waiting `TIME_WAIT` seconds, or to allow some port reuse on BSD. It also allows reusing a port more quickly for TCP client sockets.
For UDP sockets, however, Linux allows two sockets to be bound to the same address and port, and will distribute all packets to the most recent socket, which is very unexpected, to say the least.
Reported by @paddg (many, many thanks!).
I have:
=> dnsdist: Stop setting SO_REUSEADDR on outgoing UDP client sockets

.clang-tidy.full, pdns/recursordist/validate-recursor.cc, pdns/validate.cc, pdns/validate.hh
=> Delint validate.cc and related files

.clang-tidy.full, pdns/recursordist/recursor_cache.cc, pdns/recursordist/recursor_cache.hh, pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh, pdns/recursordist/test-syncres_cc2.cc
The computed `d_orig_ttl` can be wrong if `d_now.tv_sec` is more recent than the `d_now.tv_sec` the TTD was computed from. This can happen if we went out to get e.g. keys and that took time. `d_orig_ttl` even potentially wraps around in that case if the TTL value was smaller than that delay. Work around that and make sure `d_orig_ttl` is within the legal range.
An alternative approach would be to store `d_orig_ttl` the moment we change the `d_ttl` to be a TTD. I looked into that but we have no convenient place to store it. There are also a few places the TTD is replaced yet again with another value, so things started to get quite complicated. But maybe I missed an approach to have the real original TTL stored somewhere. I'll keep looking into that, as that is a better approach in the end. …
=> rec: Sanitize d_orig_ttl stored in record cache

pdns/recursordist/docs/settings.rst, pdns/recursordist/rec-main.cc
Before #12779, the fixed limit on CNAME chain length (16) effectively worked as recursion depth limit.
I have:
=> rec: bound maximum recursion depth to 16.

pdns/pdnsutil.cc
Before this patch, we clear the delta if the user does not select "apply", including when the user hits an unknown key. With this patch, we only clear on the specific choices that want that behaviour.
I have:
=> pdnsutil: if user pushes unknown key in response to "problem with zone" prompt, do not throw away their changes

build-scripts/docker/repo-test/generate-repo-files.py
Add Debian Bookworm for `auth-master` & `auth-48` to repo test script.
I have:
=> Add Bookworm to repo test script.

.github/workflows/build-and-test-all.yml, tasks.py
Fix for https://github.com/PowerDNS/pdns/issues/12844. Adds configuration to enable IPv6 for actions running on docker containers: `options: --sysctl net.ipv6.conf.all.disable_ipv6=0`.
I have:
=> Enable ipv6 for actions running on docker containers

.github/workflows/build-and-test-all.yml
For reasons entirely unclear to me, this check suddenly is broken on Debian 11. I see the same failure on my local system.
Moving it back outside the container makes it work. This is not great as now we rely on Azure/Ubuntu mirrors again, but right now this makes our CI green again. Needs more investigation at some point.
I have:
=> swagger-syntax-check: run outside of Docker

pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh, pdns/recursordist/test-syncres_cc1.cc
This can happen if the CNAME record itself was found, but its target not
Reported by @phonedph1  on IRC.
I have:
Needs test
=> rec: Prevent duplicate C/DNAMEs being included when doing serve-stale

pdns/dnsdistdist/test-dnsdistasync.cc
We are adding an expired event so the worker thread of the AsynchronousHolder can pick it up immediately, even before we come back from the call to push(), which leads to a racy test. This was observed on GitHub Actions when running with TSAN:
```
FAIL: testrunner
================
Running 170 test cases...
test-dnsdistasync.cc(156): error: in "test_dnsdistasync/test_AddingExpiredEvent": check !holder->empty() has failed
*** 1 failure is detected in the test module "unit"
FAIL testrunner (exit status: 201)
```
I have:
=> dnsdist: Remove a racy test in the AsynchronousHolder unit tests

pdns/dnssecinfra.cc, pdns/dnssecinfra.hh, pdns/recursordist/docs/manpages/rec_control.1.rst, pdns/recursordist/docs/settings.rst, pdns/recursordist/rec-main.cc, pdns/recursordist/rec_channel.hh, pdns/recursordist/rec_channel_rec.cc
introduce a way to disable DNSSEC algos. Default is to determine automatically (for algos 5 and 7 only) . You can also set it manually by setting `"dnssec-disabled-algorithms` to a list of algorithm numbers.
Fixes #12890
On a Rocky Linux 9.2 system with default config:
`Jun 07 09:20:07 msg="Disabled DNSSEC algorithms" subsystem="config" level="0" prio="Notice" tid="0" ts="1686129607.324" algorithms="5 7"`
and [icann.org](http://icann.org/) is Insecure
And after setting the crypto policy to --set DEFAULT:SHA1 it does not print the log line and starts validating [icann.org](http://icann.org/)
You can get the status wit a new `rec_control command: list-dnssec-algos`. Example output:
`RSASHA1(disabled) RSASHA1-NSEC3-SHA1(disabled) RSASHA256 RSASHA512 ECDSAP256SHA256 ECDSAP384SHA384 ED25519 …
=> rec: add feature to switch off unsupported DNSSEC algos

pdns/misc.hh, pdns/recursordist/rec-main.cc
Fixes  #12468
Includes a cleanup of `CIStringComparePOSIX` and making its operator() `const` so ii can be used for a case-insensitive set.
I have:
=> rec: systemd-journal backend: escape keys that are special

pdns/recursordist/rec-main.cc
Follow up to the delinting of this code in #12836. Originally the type used was `int`.
I have:
=> rec: uid_t and gid_t can be unsigned, so doing > on an -1 value is tricky

pdns/dnsdist.cc
We used to wait one full second between every run, which only makes sense if the runs are not taking a long time. But as soon as we have at least one check timing out, the run is taking roughly the time of the longest timeout configured, so after this commit we:
- do not wait at all if the last run took more than a full second
- wait one second minus the elapsed time of the last run otherwise
I have:
=> dnsdist: Account for the health-check run time between two runs

ext/yahttp/yahttp/reqresp.cpp
If the chunk_size is very close to the maximum value of an integer, we trigger an integer overflow when checking if we have a trailing newline after the payload.
Reported by OSS-Fuzz as:
* https://oss-fuzz.com/testcase-detail/6439610474692608
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56804
Upstream request at https://github.com/cmouse/yahttp/pull/28
I have:
=> YaHTTP: Prevent integer overflow on very large chunks

pdns/dnsdistdist/dnsdist-healthchecks.cc
We forgot to resize the response buffer to what we actually got, so the initial buffer size (512) was mistakenly used later on. Technically this should not be an issue as the buffer is large enough, but that prevents us from reporting that the response was broken if it not large enough for a DNS header, for example.
I have:
=> dnsdist: Properly set the size of the UDP health-check response

pdns/dnsdist.cc, regression-tests.dnsdist/test_Metrics.py
Since we do two lookups for DoH queries forwarded over UDP (first TCP then UDP), we need to be careful to only record a cache miss in our last attempt.
Fixes #12762.
I have:
=> dnsdist: Fix cache hit and miss metrics with DoH queries

pdns/dnsdistdist/dnsdist-healthchecks.cc
Backport of #12800 to rel/dnsdist-1.8.x.
(cherry picked from commit bf22f0fdc1b9fe5f5d4e1d96333751542c432fe6)
I have:
=> dnsdist-1.8.x: Print the received, invalid health-check response ID

pdns/dnsdist.cc
Backport of #12802 to rel/dnsdist-1.8.x.
We used to wait one full second between every run, which only makes sense if the runs are not taking a long time. But as soon as we have at least one check timing out, the run is taking roughly the time of the longest timeout configured, so after this commit we:
- do not wait at all if the last run took more than a full second
- wait one second minus the elapsed time of the last run otherwise
(cherry picked from commit 5b48dd1425dabbba7ab6758fe3ccf2b1410faef7)
I have:
=> dnsdist-1.8.x: Account for the health-check run time between two runs

pdns/dnsdistdist/dnsdist-healthchecks.cc
Backport of #12804 on rel/dnsdist-1.8.x.
We forgot to resize the response buffer to what we actually got, so the initial buffer size (512) was mistakenly used later on. Technically this should not be an issue as the buffer is large enough, but that prevents us from reporting that the response was broken if it not large enough for a DNS header, for example.
(cherry picked from commit 6a04912e36e32104434d2b1b0625a0de0e0c002d)
I have:
=> dnsdist-1.8.x: Properly set the size of the UDP health-check response

pdns/dnsdistdist/dnsdist-backend.cc, pdns/dnsdistdist/dnsdist-healthchecks.cc
Backport of #12819 to rel/dnsdist-1.8.x
`SO_REUSEADDR` is useful on TCP server sockets to allow binding quickly after restarting the process without waiting `TIME_WAIT` seconds, or to allow some port reuse on BSD. It also allows reusing a port more quickly for TCP client sockets.
For UDP sockets, however, Linux allows two sockets to be bound to the same address and port, and will distribute all packets to the most recent socket, which is very unexpected, to say the least.
(cherry picked from commit b33f09f1989e938c503142a38c556df94254443a)
I have:
=> dnsdist-1.8.x: Stop setting SO_REUSEADDR on outgoing UDP client sockets

.not-formatted, pdns/dns_random.cc, pdns/dns_random.hh, pdns/lua-base4.cc, pdns/opensslsigners.cc, pdns/pdnsutil.cc, pdns/recursordist/rec-main.cc, pdns/test-dns_random_hh.cc, pdns/tsigutils.cc
Currently `dns_random(uint32_t upper_bound)` has a drawbacks: the exclusive upper bound is mandatory. So the simple case: get full 32-bit randomness is not covered and the code to avoid modulo-bias is always executed. This is wasteful.
So add ``dns_random_uint32()`.
Start with using it in `pdns::dns_random_engine` and ` dns_random_uint16()`.
Also: reformat, cleanup, delint and refactor and *enable* tests.
I have:
=> dns random: add method to get full 32-bits of randomness

docs/appendices/types.rst
Docs link to a wrong rfc for ZONEMD record. 
I have:
=> Fix wrong rfc number in docs for ZONEMD record

pdns/recursordist/rec-main.cc
Originally the code did not distinguish between parent return and error:
```
static void daemonize(Logr::log_t log)
{
if (fork())
exit(0); // bye bye
setsid();
...
```
I have:
=> rec: fix daemonize(), followup to #12836

m4/pdns_check_libcrypto.m4
And move to BN_new() instead, which has been present since at least 0.9.6 and is still in 3.1.
I have:
=> Stop using the now deprecated ERR_load_CRYPTO_strings() to detect OpenSSL

.github/scripts/git-filter.py, .github/workflows/build-and-test-all.yml
The problem was that clang-tidy-diff needs to truncate paths for clang-tidy to find the files relative to the current directory and where the compilation database is, so files under directories like `ext` and `modules` didn't end up being found because they were expected to be under `pdns`. What this change does is hacky, but it's all I can think of for now (short of a rework and/or changing the project structure).
I have:
=> Fix issue with clang-tidy and module source files

pdns/recursordist/syncres.cc
Fixes an issue where the trace looks whack because the log line doesn't include the qname.  Also affects 4.9
I have:
=> rec: include qname when logging skip of step 4 of qname minimization

builder-support/dockerfiles/Dockerfile.rpmbuild
=> workaround: recognise centos-7 target name too in provenance generation

builder-support/dockerfiles/Dockerfile.authoritative, builder-support/dockerfiles/Dockerfile.dnsdist, builder-support/dockerfiles/Dockerfile.recursor, builder-support/dockerfiles/Dockerfile.target.sdist
we were using 3.10, which is very old. The autoconf(-archive) in that recognises Python 3.1x as 3.1, which is how somebody noticed.
This also means we bump flex, ragel, and bison. Everything appears to work.
I have:
=> bump sdist builders to alpine 3.18

.github/workflows/misc-dailies.yml
#10776 means doc building requires Python 3.9 now, so bump coverity runs to an Ubuntu that has that.
I bumped the rec and dnsdist builds too, just as future proofing.
I have:
=> coverity: bump to ubuntu 22.04

pdns/recursordist/syncres.cc
Approach two: fall back to non-QM mode if loop detected Fixes #12956
I have:
=> rec: fix qname length getting out-of-sync with qname-minimization iteration count (approach 2)

.github/workflows/build-packages.yml, .github/workflows/build-tags.yml
This PR:
- fixes the package building workflow: we need to normalize the name of the product being built: `authoritative` yields packages named `pdns`, `recursor` `pdns-recursor`
- fixes the names used when invoking the workflow after a tag has been pushed: the product names were not correct for `auth` and `rec`.
I have:
=> build-packages: Fix the package buikding workflow

pdns/dnsdistdist/docs/advanced/passing-source-address.rst, pdns/dnsdistdist/docs/guides/dns-over-https.rst, pdns/dnsdistdist/docs/guides/dns-over-tls.rst
This has caused a serious problem to at least one user, probably more, by resulting in configuration samples that do not work when copy/pasted to a file, which is really a shame.
I have:
=> dnsdist: Fix the rendering of some Lua configuration examples

.github/workflows/builder-dispatch.yml
So that we can use it from forks:
> For reusable workflows outside your enterprise or organization, the permissions setting for id-token should be explicitly set to write at the caller workflow level or in the specific job that calls the reusable workflow.
I have:
=> builder-dispatch: Explicitly grant permissions to the build package workflow

pdns/backends/gsql/gsqlbackend.cc, pdns/dnsparser.cc, pdns/dnsparser.hh, pdns/qtype.cc, pdns/qtype.hh, pdns/rfc2136handler.cc
Make DNSQType.TSIG available fot matching in dnsdist.
The TSIG line was commented in 914353c, I suspect this change was committed by mistake, but it prevents a user of dnsdist from matching incoming queries with QTypeRule(DNSQType.TSIG)
I have:
=> Make DNSQType.TSIG available in dnsdist

modules/lmdbbackend/lmdbbackend.cc
This reduces the window for a race with Lightning Stream. The full fix would be to make `deleteDomain` a single RW transaction.
I have:
=> auth lmdb: in Lightning Stream mode, during deleteDomain, use RW transaction to get ID list

m4/pdns_check_libcrypto.m4
=> auth-4.8.x: Stop using the now deprecated ERR_load_CRYPTO_strings() to detect OpenSSL

modules/lmdbbackend/lmdbbackend.cc
=> auth 4.8.x lmdb: in Lightning Stream mode, during deleteDomain, use RW transaction to get ID list

pdns/dnsdistdist/dnsdist-metrics.cc
We use a temporary `std::string` for a very short tile after it is no longer required to exist when adding a new custom metric. Reported by Coverity as CID 394511.
This was recently introduced on master and does not need to be backported.
I have:
=> dnsdist: Fix "Pointer to local outside storage" reported by Coverity

pdns/dnsdistdist/doh.cc, regression-tests.dnsdist/test_DOH.py
When both the processing of X-Forwarded-For DNS-over-https headers (`trustForwardedForHeader=true`) and a maximum number of concurrent TCP connections per client (`setMaxTCPConnectionsPerClient()`) are enabled, dnsdist could crash because of an uncaught exception:
```
dnsdist[X]: terminate called after throwing an instance of 'std::runtime_error'
dnsdist[X]:   what():  DOH thread failed to launch: map::at
```
This was caused by the TCP connection being first accounted for with the initial source IP (from the upstream HTTP proxy) but later released using the IP extracted from the X-Forwarded-For header, leading to an unexpected failure to locate the corresponding entry in the map.
We might not actually want to enforce the maximum number of concurrent TCP connections per client when …
=> dnsdist: Fix a crash when X-Forwarded-For overrides the initial source IP

pdns/dnsdistdist/doh.cc, regression-tests.dnsdist/test_DOH.py
Backport of https://github.com/PowerDNS/pdns/pull/12976 to rel/dnsdist-1.8.x.
When both the processing of X-Forwarded-For DNS-over-https headers (`trustForwardedForHeader=true`) and a maximum number of concurrent TCP connections per client (`setMaxTCPConnectionsPerClient()`) are enabled, dnsdist could crash because of an uncaught exception:
```
dnsdist[X]: terminate called after throwing an instance of 'std::runtime_error'
dnsdist[X]:   what():  DOH thread failed to launch: map::at
```
This was caused by the TCP connection being first accounted for with the initial source IP (from the upstream HTTP proxy) but later released using the IP extracted from the X-Forwarded-For header, leading to an unexpected failure to locate the corresponding entry in the map.
We might not actually want to …
=> dnsdist-1.8.x: Fix a crash when X-Forwarded-For overrides the initial source IP

regression-tests.recursor-dnssec/printlogs.py, regression-tests.recursor-dnssec/requirements.txt, regression-tests.recursor-dnssec/runtests, regression-tests.recursor-dnssec/test_EDNS.py, regression-tests.recursor-dnssec/test_Lua.py, regression-tests.recursor-dnssec/test_Notify.py, regression-tests.recursor-dnssec/test_RecDnstap.py
One mysterious failure on Debian bookworm spotted: test_EDNS.py does not seem to set the right edns version on the outgoing query. To be investigated.
I have:
=> rec: Upgrade regression tests to use pytest instead of nose

modules/bindbackend/bindbackend2.cc, pdns/auth-zonecache.hh, pdns/dbdnsseckeeper.cc, pdns/ixplore.cc, pdns/saxfr.cc, pdns/serialtweaker.cc, pdns/tkey.cc, pdns/ws-auth.cc
Most are not *really* bad, as we convert time_t or unsigned int, which is good for quite some time. One case of converting time_t to *signed* int spotted.
I have:
=> auth: Fix coverity time_t related warnings

m4/pdns_check_libcrypto.m4
Backport of #12935 
And move to BN_new() instead, which has been present since at least 0.9.6 and is still in 3.1.
(cherry picked from commit 9fcef4932c9323b085984f8a087045fef70103f5)
I have:
=> rec: backport of 12935 to rec-4.9.x: Stop using the now deprecated ERR_load_CRYPTO_strings() to detect OpenSSL

m4/pdns_check_libcrypto.m4
Backport of #12961 
The openssl/kdf.h header on EL8 is invalid because someone backported a work-in-progress feature to an older OpenSSL branch and did not bother to backport the fixes that were added later.
Red Hat declined to fix their mess and helpfully suggested we do the work instead in https://bugzilla.redhat.com/show_bug.cgi?id=2215856
(cherry picked from commit 3dabf2d4a1a478fb00a232259e8043f075eb4d03)
I have:
=> rec: Backport 12961 to rec-4.9.x: Work around Red Hat 8 pooping the bed in OpenSSL's headers

pdns/recursordist/Makefile.am
=> rec: libarc4random should be linked even if libsodium is not used

pdns/pdns.service.in
Dear Team,
On Ubuntu there is no `mysqld.service`. Only `mysql.service` exists.
With a mysql backend in use but without waiting for `mysql.service` to start, the pdns service can fail+restart a couple of times on boot with an error like:
`systemd[1]: Failed to start PowerDNS Authoritative Server.` -> until mysql will start and accept the connections of pdns.
It's not a big deal, pdns.service will start anyways.
I'm getting the error twice in a Ubuntu 20.04 VM when booting up.
I also checked 16.04, 18.04, 22.04 and none of them has `mysqld.service` when I install mysql from repo.
Personally I also prefer the `*d.service` names and other services like OpenSSH can handle both on Ubuntu with a regular service unit file here: `/lib/systemd/system/ssh.service`
plus with a symlink which points …
=> wait for mysql.service

pdns/dns.hh
See https://github.com/PowerDNS/pdns/pull/13012 for the reason why we prefer a plain `uint16_t` to an `unsigned` bit field of the same size.
~Opening as a draft for now, mostly to see if our CI passes.~
I have:
=> dnsheader: Switch from bitfield to uint16_t whenever possible

pdns/recursordist/docs/settings.rst
Try to reduce confusion about what the edns-subnet-allow-list setting does and doesn't affect.
We had a discussion on IRC about this setting. I had misunderstood the purpose of it pretty badly. So, I've tried to clarify the meaning.
I have:
=> Update settings.rst -- clarify edns-subnet-allow-list

pdns/dnsproxy.hh
`recurseFor` does not actually exist, remove it.
I have:
=> auth: DNSProxy: remove declaration without implementation

pdns/misc.hh
This prevents compiling dnsdist when libcrypto is not available, which should be possible.
I have:
=> misc: `pdns::getMessageFromErrno()` does not depend on libcrypto

pdns/recursordist/pdns_recursor.cc, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh, pdns/recursordist/rec-tcp.cc, regression-tests.recursor-dnssec/test_Protobuf.py
As `gettag` can add protobuf policy tags, we do not want to cache the protobuf policy tags stored (and therefore fixed) in the packet cache.
Also, set `SocketFamily` always (was missing on a cache hit).
This is a Draft PR, as the current state of this PR changes behaviour if policy tags are set in an interception function (e.g. `postResolve`) later in the resolving process. In that case the policy tags should en up in the packet cache. I have to think a bit how to arrange that, and what to do if `gettag` also add tags for a case that *does* have policy tags stored already in the packet cache.
Reported by @wojas
Follow-up: we now keep track of the tags set by `gettag(_ffi)` separately. This allows for them to not end up in the PC.
Do pass the tags set by `gettag(_ffi)` to other other Lua …
=> Rec: fix setting of policy tags

.not-formatted, pdns/dnsdistdist/dnsdist-healthchecks.cc, pdns/dnsdistdist/dnsdist-healthchecks.hh
If we were woken up by the multiplexer but have actually nothing to read, or the call to `recv()` is interrupted, we do not want to stop listening for the health-check response event. It is also not useful to log about it, even at "verbose health-check" level.
Note that we would have logged previously, so this kind of event would not have gone unnoticed anyway.
I have:
=> dnsdist: Better handling of spurious wake-ups, interrupted calls

pdns/test-channel.cc
Not only does this ensure that we can actually retrieve the submitted object, it prevents memory analysis tools from reporting a leak.
I have:
=> channel unit tests: Actually retrieve the object after an overflow

builder-support/debian/authoritative/debian-buster/control
[pdns-tools package descriptions for Debian / Ubuntu](https://github.com/PowerDNS/pdns/blob/29d9168874867c712da624bc4173b62f07cb79bf/builder-support/debian/authoritative/debian-buster/control#L55) don't list all tools contained within pdns-tools which is a bit confusing when looking for a specific tool (such as calidns or sdig).
Closes #13016.
I have:
=> Add missing tools to pdns-tools package description (control)

pdns/tcpreceiver.cc
Put remote into log messages emitted when a TCP Connection Thread dies.
I have:
=> auth: add remote to logs when tcp thread dies

regression-tests/recursor-test
When the bulktest failed, there was no obvious indication as to why it failed...
I have:
=> Clarify why bulktest is failing

pdns/recursordist/docs/manpages/rec_control.1.rst
Use backticks in [rec_control(1)](https://doc.powerdns.com/recursor/manpages/rec_control.1.html)
> wipe-cache DOMAIN [DOMAIN] […]
Wipe entries for DOMAIN (exact name match) from the cache. This is useful if, for example, an important server has a new IP address, but the TTL has not yet expired. Multiple domain names can be passed. DOMAIN can be suffixed with a ‘$’. to delete the whole tree from the cache. i.e. ‘powerdns.com$’ will remove all cached entries under and including the powerdns.com name.
I have:
=> Use backticks in rec_control(1)

builder-support/specs/dnsdist.spec
The file was already readable by the group, but our RPM specs did not set the group to 'dnsdist'.
Fixes #13027.
I have:
=> dnsdist: Set the group of our configuration file to dnsdist on RH and co

pdns/calidns.cc
calidns could have crashed with a null pointer derefence if the main thread exits before the receiver thread has finished, because the vector of sockets no longer existed.
I have:
=> calidns: Prevent a crash on an empty domains file

m4/pdns_check_libcrypto.m4
The openssl/kdf.h header on EL8 is invalid because someone backported a work-in-progress feature to an older OpenSSL branch and did not bother to backport the fixes that were added later.
Red Hat declined to fix their mess and helpfully suggested we do the work instead in https://bugzilla.redhat.com/show_bug.cgi?id=2215856
(cherry picked from commit 3dabf2d4a1a478fb00a232259e8043f075eb4d03)
Backport of #12961 
I have:
=> rec: Backport 12961 to rec-4.7.x: Work around Red Hat 8 pooping the bed in OpenSSL's headers

m4/pdns_check_libcrypto.m4
The openssl/kdf.h header on EL8 is invalid because someone backported a work-in-progress feature to an older OpenSSL branch and did not bother to backport the fixes that were added later.
Red Hat declined to fix their mess and helpfully suggested we do the work instead in https://bugzilla.redhat.com/show_bug.cgi?id=2215856
(cherry picked from commit 3dabf2d4a1a478fb00a232259e8043f075eb4d03)
Backport of #12961 
I have:
=>  rec: Backport 12961 to rec-4.8x: Work around Red Hat 8 pooping the bed in OpenSSL's headers

ext/yahttp/yahttp/reqresp.cpp
If the chunk_size is very close to the maximum value of an integer, we trigger an integer overflow when checking if we have a trailing newline after the payload.
Reported by OSS-Fuzz as:
https://oss-fuzz.com/testcase-detail/6439610474692608 https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56804
(cherry picked from commit b602982fc5b4fb9139dec591541e0c070ceb47f5)
Backport of #12892 
I have:
=> rec: Backport 12892 to rec-4.7.x: YaHTTP: Prevent integer overflow on very large chunks

ext/yahttp/yahttp/reqresp.cpp
If the chunk_size is very close to the maximum value of an integer, we trigger an integer overflow when checking if we have a trailing newline after the payload.
Reported by OSS-Fuzz as:
https://oss-fuzz.com/testcase-detail/6439610474692608 https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56804
(cherry picked from commit b602982fc5b4fb9139dec591541e0c070ceb47f5)
Backport of #12892 
I have:
=> rec: Backport of 12892 to rec-4.8.x: YaHTTP: Prevent integer overflow on very large chunks

builder-support/specs/dnsdist.spec
I _hope_ the `%attr` directive does the right thing, based on http://ftp.rpm.org/max-rpm/s1-rpm-anywhere-specifying-file-attributes.html
I'm using this directive instead of calling `chgrp` in `%post` because I'm told using `chgrp` would make `verify` complain about the ownership later.
This replaces https://github.com/PowerDNS/pdns/pull/13037 which was not working properly.
I have:
=> dnsdist: Fix the group of the dnsdist.conf file when installed via RPM

builder-support/specs/dnsdist.spec
This is useless as long as `@service_user@` and `@service_group@` are set to 'dnsdist' (which is always true in our build system), and would not have worked otherwise because dnsdist would have rejected it with:
```
--gid/-g set on command-line, but dnsdist was started as a systemd service.
Use the 'Group' setting in the systemd unit file to set the group to run as
```
I have:
=> dnsdist: Stop passing -u dnsdist -g dnsdist on systemd's ExecStart

pdns/recursordist/lua-recursor4.cc, pdns/recursordist/pdns_recursor.cc
I expected the compiler to already prevent the copy in the `distributeAsyncFunction` case, but looking at the actual allocations using `heaptrack` shows that this was not true, so we can actually prevent one allocation and copy in the `pdns-distributes-queries` case with this fix.
I have:
=> rec: Fixes a few performance issues reported by Coverity

ext/lmdb-safe/lmdb-typed.hh
before this patch, there was a chance of desync:
assume two LS+auth nodes are in sync
1. node A deletes zone example.com (this deletes the domain object, an index reference to it, and a few other things)
2. node B sends out notify for example.com which is a primary zone, and updates the domain object (last_notified)
3. LS syncs. For the domain object, the notified one is newer than the deleted one, so auth1 gets the domain object back. The index entry, however, had an older timestamp, and remains deleted
With this patch, the index entry gets a fresh timestamp too, so conflict resolution stops breaking the index.
I have:
=> auth lmdb: when broadcasting indexes, -do- rewrite them even if they are unchanged

pdns/recursordist/docs/settings.rst
Since 4.9.0, the packet cache is sharded and shared by all threads.
I have:
=> Update max-packetcache-entries setting doc

modules/bindbackend/binddnssec.cc
Fix some annoying warnings in the bind backend.
I have:
=> Auth: Fix warnings in bind backend

pdns/tcpreceiver.cc
Logs will typically have:
```
AXFR-out zone '<ZONE>', client '<ipv6>', transfer initiated
AXFR-out zone '<ZONE>', client '[<ipv6>]:<PORT>', allowed: client IP is in allow-axfr-ips
AXFR-out zone '<ZONE>', client '<ipv6>', AXFR finished
```
it's frustrating that the three lines aren't consistent -- it makes it hard to scan / match up
I have:
=> auth: harmonize *xfr log messages

pdns/ixfr.cc, regression-tests.recursor-dnssec/test_RPZ.py
While reading (I)XFR responses from remotes, if the two octet header for a chunk is read partially, we end the transfer immediately. This is wrong.
* this PR adds a test for that
* the commit that adds the test also has a bad fix (it's bad because it turns EOF into an Exception, which, for example, hides the problem mentioned in #13104 even deeper)
* the commit after it has a better fix but it's not pretty. It should at least recalculate `elapsed` once more I think. (added another commit that does that. Besides that, not sure we can get clang-tidy entirely happy.)
Besides that, this PR:
* adds the value of `primarySOACount` to all three exceptions
* fixes a typo
I have:
=> (I)XFR: handle partial read of len prefix

pdns/dnsdistdist/dnsdist-discovery.cc, pdns/sstuff.hh, regression-tests.dnsdist/dnsdisttests.py, regression-tests.dnsdist/test_BackendDiscovery.py
Checking for all callers of `Socket::readWithTimeout()` (see https://github.com/PowerDNS/pdns/pull/13105) yielded a second bug, in dnsdist this time.
I have:
=> dnsdist: Properly handle short reads on backend upgrade discovery

contrib/assert-equal-DNSMessage/eqdnsmessage.py, pdns/ixfrdist.cc, regression-tests.ixfrdist/test_IXFR.py
fixes #11378
this PR also fixes eqdnsmessage because it looks like dnspython shuffled some types around
I have:
=> ixfrdist: set AA=1 on SOA responses

pdns/dnspacket.cc
Hi,
I noticed these entries in my logs after rotating some DNSSEC keys:
pdns_server[514339]: Weird, trying to send a message that needs truncation, 513 > 512. Question was for domain.tld|DNSKEY
After some digging it turns out that the DNS cookie 'code' and 'length' fields are not included in optsize. This causes pdns to send out packets that should have been truncated.
dig options to reproduce: +bufsize=512 +cookie
I have:
=> optsize off by -4 when including DNS cookie

pdns/dnsdist-tcp.cc, pdns/dnsdistdist/dnsdist-lua-ffi.cc
This PR clears two cosmetic warnings at compilation.
I have:
=> dnsdist: cosmetic compilation warning fixes 

pdns/dnsdist.cc
Responses sent directly from dnsdist, without reaching out to a backend (self-generated and cache hits answers, mostly) where not properly accounted for in frontend metrics, ring buffer entries and latency computation when `recvmmsg`/`sendmmsg` support was enabled via `setUDPMultipleMessagesVectorSize()`.
Fixes https://github.com/PowerDNS/pdns/issues/13148.
I have:
=> dnsdist: Properly record self-answered UDP responses with recvmmsg

pdns/dnsdist.cc
Responses sent directly from dnsdist, without reaching out to a backend (self-generated and cache hits answers, mostly) where not properly accounted for in frontend metrics, ring buffer entries and latency computation when `recvmmsg`/`sendmmsg` support was enabled via `setUDPMultipleMessagesVectorSize()`.
Backport of #13149 to rel/dnsdist-1.8.x.
I have:
=> dnsdist-1.8.x: Properly record self-answered UDP responses with recvmmsg

pdns/dnsdistdist/doh.cc
When not in single acceptor mode, the DOH thread processing incoming queries after they have been parsed is using 100% as the incoming channel is not blocking. This PR makes the receiving part to block.
I have:
=> dnsdist: DOH - make query channel receiving part blocking

pdns/iputils.cc
I dislike the use of `#ifdef FOO` vs. `#if FOO` to check for symbols in general because at first glance it could seem ambiguous (i.e. Given `#define FOO 0`, `#ifdef FOO` is true).
Since we use this style everywhere, it prompted me to change the meson scripts to generate `#define FOO` instead of `#define FOO 1` and `#undef FOO` instead of `#define FOO 0`.
Except that `iputils.cc` was using `#if HAVE_GETIFADDRS` which breaks with the new `#define HAVE_GETIFADDRS`.
I have:
=> Consistency: Use #ifdef instead of #if in `iputils.cc`

pdns/recursordist/aggressive_nsec.cc, pdns/recursordist/test-aggressive_nsec_cc.cc
Currently, new data does not get recorded into the aggressive cache if there's an existing entry that matches. Together with the fact that in (in some cases) pruning is unfair (it scans the zones always in the same order and stops clearing when it has reached the goal) and/or not very active (when the recursor is lightly loaded) this has the consequence that old expired records can remain in the cache that prevent new data to be recorded and used.
On a lightly loaded rec I see this with `rec_control dump-cache -`:
```
; Zone .
. -36987 IN NSEC aaa. NS SOA RRSIG NSEC DNSKEY
```
Note that the root zone is last in the list, so entries in it are most likely to be skipped when pruning without pressure.
The unfairness should be fixed as well, using recent changes in ``cachecleaner.hh`` as a …
=> rec: replace data in the aggressive cache if new data becomes available

ext/json11/json11.cpp, pdns/Makefile.am, pdns/recursordist/ws-recursor.cc, pdns/test-webserver_cc.cc, pdns/webserver.cc, pdns/webserver.hh, regression-tests.api/test_Servers.py, regression-tests.api/test_Zones.py
Should fix #13050, followup to #12260.
This reverts #12260 and adds a function to test if a URL passed in is valid.
There remains one potential issue: through the API, it is possible to produce data that is not properly UTF8, e.g. by retrieving log lines which themselves can contains arbitrary data (I'm assuming this to be on the safe side as I have no evidence otherwise). Currently we pass that data through, so it ends up in the json output. At the moment we do not have any function to validate if the source data we pass through via json is valid UTF8, and so it's hard to filter invalid data out. There's code to be found on the internet to validate if data is valid UTF8 (e.g. http://bjoern.hoehrmann.de/utf-8/decoder/dfa/), we could use that, but there still remains to decide what to do …
=> Fix code producing json

pdns/dnsdist-lua.cc
Backport of #12738 to rel/dnsdist-1.8.x
'disableZeroScope' was  accidentally changed to 'disableZeroScoping' in commit 597a91a3cec373ebd4172d167a0f9c7500781027
(cherry picked from commit d85c923f52d1e2140f3ecf5467b513c7b54a856e)
I have:
=> dnsdist-1.8.x: Undo an accidentally change of disableZeroScope to disableZeroScoping

m4/pdns_check_libcrypto.m4
Backport of #12961 to rel/dnsdist-1.8.x
The openssl/kdf.h header on EL8 is invalid because someone backported a work-in-progress feature to an older OpenSSL branch and did not bother to backport the fixes that were added later.
Red Hat declined to fix their mess and helpfully suggested we do the work instead in https://bugzilla.redhat.com/show_bug.cgi?id=2215856
(cherry picked from commit 3dabf2d4a1a478fb00a232259e8043f075eb4d03)
I have:
=> dnsdist-1.8.x: Work around Red Hat 8 pooping the bed in OpenSSL's headers

m4/pdns_check_libcrypto.m4
And move to BN_new() instead, which has been present since at least 0.9.6 and is still in 3.1.
Backport of https://github.com/PowerDNS/pdns/pull/12935 to rel/dnsdist-1.8.x
I have:
=> dnsdist-1.8.x: Stop using the now deprecated ERR_load_CRYPTO_strings() to detect OpenSSL

pdns/dnsdistdist/test-dnsdistasync.cc
Backport of https://github.com/PowerDNS/pdns/pull/12905 to rel/dnsdist-1.8.x
We are adding an expired event so the worker thread of the AsynchronousHolder can pick it up immediately, even before we come back from the call to push(), which leads to a racy test. This was observed on GitHub Actions when running with TSAN:
```
FAIL: testrunner
================
Running 170 test cases...
test-dnsdistasync.cc(156): error: in "test_dnsdistasync/test_AddingExpiredEvent": check !holder->empty() has failed
*** 1 failure is detected in the test module "unit"
FAIL testrunner (exit status: 201)
```
(cherry picked from commit 35bbac75efbd4fb8a9523ab3974bea5507484f65)
I have:
=> dnsdist-1.8.x: Remove a racy test in the AsynchronousHolder unit tests

ext/yahttp/yahttp/reqresp.cpp
Backport of https://github.com/PowerDNS/pdns/pull/12892 to rel/dnsdist-1.8.x
If the chunk_size is very close to the maximum value of an integer, we trigger an integer overflow when checking if we have a trailing newline after the payload.
Reported by OSS-Fuzz as:
https://oss-fuzz.com/testcase-detail/6439610474692608 https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56804
(cherry picked from commit b602982fc5b4fb9139dec591541e0c070ceb47f5)
I have:
=> dnsdist-1.8.x: YaHTTP: Prevent integer overflow on very large chunks

pdns/libssl.cc
Backport of #12794 to rel/dnsdist-1.8.x
(cherry picked from commit 0a18d0349145ae0c49b6dfef0be58bde925c4806)
I have:
=> dnsdist-1.8.x: Fix a memory leak when processing TLS tickets w/ OpenSSL 3.x

pdns/dnsdist-lua-actions.cc, regression-tests.dnsdist/test_Spoofing.py
Backport of https://github.com/PowerDNS/pdns/pull/12806 to rel/dnsdist-1.8.x
(cherry picked from commit 6bb404b627442d64b829edcffcc9f5fbc4987eb4)
I have:
=> dnsdist-1.8x: SpoofAction: copy the QClass from the request

builder-support/specs/dnsdist.spec
Backport of #13084 to rel/dnsdist-1.8.x
I have:
=> dnsdist-1.8.x: Fix the group of the dnsdist.conf file when installed via RPM

m4/pdns_with_net_snmp.m4, tasks.py
We have had a fair amount of issues with `net-snmp` adding unexpected and unwanted values to both `CXXFLAGS` and `LDFLAGS`, and it was just reported to also define `HAVE_LIBSSL` in its public header, which messes up our own feature detection. Therefore it is likely better for everyone to prevent net-snmp from being enabled without the user intending it. For our own packages we explicitly enable net-snmp when supported, and this commit also enables it in our CI for dnsdist (it was already done for the recursor) so it should not have any impact.
I have:
=> Change the default for building with net-snmp from `auto` to `no`

pdns/recursordist/pdns_recursor.cc, pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh, pdns/recursordist/test-syncres_cc10.cc
(cherry picked from commit fa5f61e94e1bd354d42923a844c59b3be232c29f)
Backport of #13102 
I have:
=> rec: Backport #13102 to rec-4.9.x: Do not assume the records are in a particular order when deterining if an answer is NODATA

ext/arc4random/arc4random.c, ext/arc4random/includes.h
Avoiding a redundant and/or missing declaration (depending HAVE_* defines)
I have:
=> Declare ssh_compat_getentropy in the right spot.

pdns/dnsdist-cache.hh, regression-tests.dnsdist/test_Metrics.py
In theory calling `std::atomic<T>::load()` is exactly the same than calling `std::atomic<T>::operator T` but I have seen TSAN choke on the former while not on the latter, so let's try it.
Also fix the description of one of our regression tests.
I have:
=> dnsdist: Try to fix a data race warning reported by TSAN

regression-tests.recursor-dnssec/test_Protobuf.py
=> rec: fix call of empty() in Protobuf regression test, nice speedup

pdns/version.cc
This prints the list of auth modules that were loaded next to the printout of modules that were compiled in.
I have:
=> Auth: Print the list of loaded modules next to the config.h preset

pdns/channel.hh
g++ reports:
```
In file included from channel.cc:23:
channel.hh:38:17: warning: redundant redeclaration of ‘void __tsan_acquire(void*)’ in same scope [-Wredundant-decls]
38 | extern "C" void __tsan_acquire(void* addr);
|                 ^~~~~~~~~~~~~~
In file included from /usr/include/c++/13.2.1/bits/shared_ptr_atomic.h:37,
from /usr/include/c++/13.2.1/memory:81,
from channel.hh:23:
/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include/sanitizer/tsan_interface.h:24:6: note: previous declaration of ‘void __tsan_acquire(void*)’
24 | void __tsan_acquire(void *addr);
|      ^~~~~~~~~~~~~~
channel.hh:39:17: warning: redundant redeclaration of ‘void __tsan_release(void*)’ in same scope [-Wredundant-decls]
39 | extern "C" void __tsan_release(void* addr);
|                 ^~~~~~~~~~~~~~ …
```
=> channel: Fix redundant redeclaration warning

ext/arc4random/arc4random.hh
If `arc4random.hh` is included before `config.h`, the `HAVE_*` defines are not yet available and thus we include the definition of the following functions even though they might be available in the standard headers:
- `arc4random`
- `arc4random_buf`
- `arc4random_uniform`
- `explicit_bzero`
Yielding warnings:
```
In file included from dns_random.hh:27,
from tsigutils.cc:25:
../ext/arc4random/arc4random.hh:9:12: warning: redundant redeclaration of ‘uint32_t arc4random()’ in same scope [-Wredundant-decls]
9 |   uint32_t arc4random(void);
|            ^~~~~~~~~~
In file included from /usr/include/c++/13.2.1/cstdlib:79,
from /usr/include/c++/13.2.1/ext/string_conversions.h:43,
from /usr/include/c++/13.2.1/bits/basic_string.h:4097,
from /usr/include/c++/13.2.1/string:54,
from dnsname.hh:26, …
```
=> arc4random: Fix 'redundant redeclaration’ warnings

pdns/json.cc, pdns/json.hh, pdns/pdnsutil.cc, pdns/ws-auth.cc, regression-tests.api/test_Zones.py
Implementation of #8717.
For emptying out secondary zones, sending an empty rrset array should work. 
Also:
- forbid negative TTL in RRsets
- forbid changing RRsets in Consumer zones (deleting them all is still okay)
- reduce code directly in updateDomainSettingsFromDocument, to make clang-tidy happy
I have:
=> API: Auth: replace zone contents et al

docs/changelog/4.8.rst, regression-tests.auth-py/runtests, tasks.py
=> switch from `docker-compose` to `docker compose` and stop installing docker-compose because that uninstalls runc

pdns/dnsdistdist/Makefile.am
On systems that do not provide arc4random we actually need to link the internal library in.
I have:
=> dnsdist: dnsdist's fuzzing target needs to link against arc4random

regression-tests.dnsdist/test_Metrics.py
We have seen in https://github.com/PowerDNS/pdns/issues/13148 that we can easily break frontend metrics when `recvmmsg`/`sendmmsg` support is enabled via `setUDPMultipleMessagesVectorSize()`, so let's test the metrics in that case explicitly so we do not break them again in the future.
Closes https://github.com/PowerDNS/pdns/issues/13180
I have:
=> dnsdist: Also test metrics with recvmmsg support enabled

pdns/dnsdistdist/docs/guides/webserver.rst
Additional parameters to webserver() are now depreciated. Update documentation to refer to setWebserverConfig()
Minor documentation correction
I have:
=> Update documentation to point to proper function

pdns/dnsdistdist/docs/statistics.rst
This fixes a typo in the documentation of 
https://dnsdist.org/statistics.html#latency-doh-avg100000
there is no prometheus metric for latency-doh-avg100k,
but latency-doh-avg1M exists.
I have:
=> docu typo fix: latency-doh-avg 100k -> 1M

pdns/dnsdistdist/test-dnsdistnghttp2-in_cc.cc
These tests were failing on EL with LTO enabled, and passing everywhere else. It turns out that we did not properly reset the `s_processQuery` hack that we used in these tests to simulate the policy decision (rules and actions), and thus inherited what the last test set it to instead of the default (dropping queries), which was very unexpected.
This is a draft for now, as I only tested it on a development VM. I'll trigger the "Test package building for specific distributions" workflow in a few minutes to make sure that it indeed fixes it.
I have:
=> dnsdist: Fix unit tests for incoming DoH w/ nghttp2

pdns/recursordist/aggressive_nsec.cc, pdns/recursordist/rec_channel_rec.cc, pdns/recursordist/test-aggressive_nsec_cc.cc
There are several issues with the current pruning approach. See #13109.
A consequence of the issues mentioned there is that the aggressive cache size can remain "too big" after a pruning run, causing the next pruning run also to scan many items and still do nothing. 
The hypothesis is that we're seeing bad consequences if the ineffective pruning since #13106, as a typical aggressive cache now contains way less expired items than before, causing it to hit the "bad case" more often. We have to confirm this, however. If we get confirmation, this must be backported to the 4.9.x branch.
Should fix #13109.
I have:
=> rec: make aggressive cache pruning more effective and more fair

pdns/Makefile.am, pdns/dnsdistdist/Makefile.am, pdns/recursordist/Makefile.am, pdns/recursordist/test-aggressive_nsec_cc.cc
Also be a bit more lenient in a recently introduced test that checks timing of some aggressive cache manipulations.
The random seed is written to the test log file, so it is possible to reproduce the order of a particular failed run.
I have:
=> Introduce randomness in test order to catch hidden dependencies between unit-tests

pdns/mtasker.cc, pdns/recursordist/test-mtasker.cc, pdns/recursordist/test-rec-zonetocache.cc
This allows the test to be reintroduced on macOS plus the mtasker tests now start to work with ASA and randomization on: after the exception test is run other mtasker test would fail before.
I *do* wonder if the `d_runQueue.pop();` call should be done in the "exception is thrown" case. But as it is skipped in the current state of affairs, I am not pulling it iside the `catch` block for now`.
Also silence logging in the zoneToCache tests, previously an earlier test wold take care of that.
I have:
=> rec: When an exception is thrown from an mthread register stack switch (in the ASAN case)

builder-support/dockerfiles/Dockerfile.rpmbuild
this should unbreak the centos-9-stream and amazonlinux-2023 builds
I have:
=> builder (rpm): use allowerasing to allow replacement of curl-minimal with curl

docs/settings.rst, pdns/auth-main.cc, pdns/ws-auth.cc, regression-tests.api/runtests.py, regression-tests.api/test_Zones.py
=> auth: add default-catalog-zone setting

pdns/tkey.cc
Error message for missing GSS-TSIG feature (not compiled in) needs some improvement (or maybe some more not's) ...
I have:
#ottoneedsmoresleep
=> Auth: Improve error message for missing GSS-TSIG feature

modules/gmysqlbackend/smysql.cc
Setting this option, even to 0, causes spurious warnings to the console
with recent libmysqlclient versions. The upstream bug
( https://bugs.mysql.com/bug.php?id=112089, also https://bugs.launchpad.net/ubuntu/+source/mysql-8.0/+bug/2031548 )
has now been open for a month, so we're implementing a workaround.
0 was the default since at least MySQL 5.7, perhaps longer.
closes #13242
I have:
=> smysql: stop explicity setting MYSQL_OPT_RECONNECT to 0

builder-support/debian/dnsdist/debian-buster/rules, builder-support/specs/dnsdist.spec, pdns/dnsdistdist/docs/upgrade_guide.rst
As we promised we would..
Also document that h2o is no longer built by default in the upgrade guide.
I have:
=> dnsdist: Enable back h2o support in our packages

pdns/recursordist/docs/performance.rst, pdns/recursordist/docs/settings.rst, pdns/recursordist/docs/yamlsettings.rst, pdns/recursordist/pdns_recursor.cc, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-main.hh, pdns/recursordist/rec-tcp.cc, pdns/recursordist/rec_channel_rec.cc, pdns/recursordist/settings/table.py
The new TCP worker thread(s) are listeners and workers for incoming TCP only. As all the caches are shared these days there is no reason to handle them in regular distributor threads or workers.
To simplify matters a bit, always run at least one TCP Listener/worker thread. This has the consequence that regular worker(s) do no longer do TCP (if pdns-distributes-queries is false) and neither do the distributor thread(s) (if pdns-distributes-qeuries is true).
Basic test done on macOS, with all the settings combinations (which are plenty!). Needs:
and docs. Hence draft status.
Fixes #8394
I have:
=> rec: move tcp-in processing to dedicated thread(s)

pdns/recursordist/settings/Makefile.am
See comment for motivation. While working on the settings project, I had this line, but I thouhgt it was no longer needed so I removed it. It turns out it *is* needed. Found out when adding the recursor.tcp_threads field.
To reproduce the issue this PR fixes: rename a field in `table.py` and run make in `recursordist`. You'll see that `settings/rust/src/lib.rs.h` will not contain the name change.
I have:
=> rec: Add make -C rust clean when generate.py is run

pdns/dnsdist-lua-bindings-dnsquestion.cc, pdns/dnsdistdist/docs/reference/dq.rst
First shot to add a "selectedBackend" LUA binding to get the `ComboAddress` of the selected backend from `DNSResponse::d_downstream`. This pull request will fix #13201.
Successful testing with the following config
```lua
function alterDnstapResponse(dr, tap)
tap:setExtra(dr.selectedBackend:toString() )
end
rl = newFrameStreamTcpLogger("10.0.0.100:6000")
addResponseAction(AllRule(), DnstapLogResponseAction("dnsdist1", rl, alterDnstapResponse))
```
I have:
=> dnsdist: add lua binding to downstream address

pdns/recursordist/docs/settings.rst, pdns/recursordist/docs/yamlsettings.rst, pdns/recursordist/settings/generate.py, pdns/recursordist/settings/rust/Makefile.am, pdns/recursordist/settings/table.py
Partly from @RvdE, I've added the Rust side of things. It was not immediately obvious that part is needed, but there are cases where I think it is needed: running with a `config-dir` set to the default value on the command line should not produce a diff in YAML mode.
Fixes #13259
I have:
=> rec: Fix sysconfdir handling in new settings code

pdns/cachecleaner.hh, pdns/recursordist/negcache.cc, pdns/recursordist/negcache.hh, pdns/recursordist/rec-taskqueue.cc, pdns/recursordist/rec-taskqueue.hh, pdns/recursordist/recpacketcache.cc, pdns/recursordist/recpacketcache.hh, pdns/recursordist/recursor_cache.cc, pdns/recursordist/recursor_cache.hh, pdns/recursordist/test-recpacketcache_cc.cc, pdns/recursordist/test-syncres_cc.cc
Fixes #13266.
ALso, only submit tasks that produce rcode 0 result. While it is not _wrong_ to submit tasks for queries that previously produced rcode != 0, these cache entries or governed by different (smaller) TTLs, so we are likely to submit more tasks than makes sense.
When these rcode != 0 entries with small TTLs are expired, on repeated client queries we'll trigger regular query processing (using the record cache), which itself wil trigger tasks if relevant.
Also include some general delinting of common cache code.
I have:
=> rec: packetcache submit task fixes

pdns/recursordist/test-recpacketcache_cc.cc
Not all tests leave an empty queue.
Test that use syncres get an auto clear, but this test does not use syncres.
I have:
=> rec: Clear taskQueue at start of test run

pdns/recursordist/aggressive_nsec.cc, pdns/recursordist/test-aggressive_nsec_cc.cc
Backport of #13209 without the specific cache dump part
I have:
=> rec: Backport 13209 to rec 4.9.x: Implement a more fair way to prune the aggressive cache

pdns/recursordist/rec-taskqueue.cc, pdns/recursordist/rec-taskqueue.hh, pdns/recursordist/recpacketcache.cc, pdns/recursordist/recpacketcache.hh
(cherry picked from commit 11c65aeda2aef3aabeeff9aa1491bc84954ed905)
Backport of #13278 
I have:
=> rec: Backport 13278 to rec-4.9.x: Prevent lookups for unsupported qtypes or rcode != 0 to submit refresh tasks

README.md
Debian 9 / Ubuntu Bionic are no longer supported,
but conveniently the build instructions are not really release specific.
Removing the version references from the README
I have:
=> Remove versioning from Debian/Ubuntu

pdns/recursordist/settings/Makefile.am
So dists do not have to run python to generate them. Previously python was a hidden dependency.
I have:
=> rec: Put files generated by generate.py into tarball

modules/gmysqlbackend/smysql.cc
=> auth-4.7.x: smysql: stop explicity setting MYSQL_OPT_RECONNECT to 0

pdns/recursordist/rec-main.cc, pdns/recursordist/settings/table.py, pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh
This mechanism selects servers marked down to be used anyway with a given chance. Inspired by the OARC talk
https://indico.dns-oarc.net/event/47/contributions/1018/ by  Fenglu Zhang (Tsinghua University) .
If picked a chance of 1/25, but I do not have data yet to determine the "right" value.
I have:
=> rec: implement probabilistic unthrottle

pdns/recursordist/rec-main.cc, pdns/recursordist/rec-taskqueue.cc, pdns/recursordist/rec-taskqueue.hh, pdns/recursordist/syncres.cc, pdns/recursordist/test-rec-taskqueue.cc, pdns/recursordist/test-syncres_cc5.cc
An optimization reducing the number of queries sent to auths, enabled by the assumption that qname minimization does not add anything for infra-queries, i.e. queries issued by the recursor itself to resolve NS names to addresses.
Also compute the `max-qperq` bound dynamically (based on the qname minimization mode for the current query).
I'm working on this PR, I noticed that are current number of auth queries per client query for various extreme cases is much lower than the numbers reported in #8646. Likely the better zone cut algo helps a lot, and maybe some other improvements we did over the years. So that's good and might even enable us to have stricter default values for `max-qperq`.
I have:
=> Rec: do not use qname minimization for infra-queries

regression-tests.auth-py/runtests, tasks.py
partial backport of #13194
I have:
=> auth-4.7.x: switch from `docker-compose` to `docker compose` and stop installing docker-compose because that uninstalls runc

modules/gmysqlbackend/smysql.cc
=> auth-4.8.x: smysql: stop explicity setting MYSQL_OPT_RECONNECT to 0

pdns/dnsdistdist/docs/reference/tuning.rst
Document default TCP values just like UDP timeout.
I have:
=> dnsdist: Update tuning.rst

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist-web.cc, pdns/dnsdist.cc, pdns/dnsdistdist/dnsdist-kvs.cc, pdns/dnsdistdist/dnsdist-lua-bindings-dnscrypt.cc, pdns/dnsdistdist/dnsdist-nghttp2-in.cc, pdns/dnsdistdist/dnsdist-nghttp2.cc, pdns/dnsdistdist/dnsdist-secpoll.cc, pdns/dnsdistdist/doh.cc, pdns/tcpiohandler.cc
This PR re-evaluates the log level of all messages in the DNSdist code base. The rules are simple:
- 'Error' should only be used when a critical service will not function properly
- 'Warning' should be used when a non-essential feature may not be working as expected
- 'Info' is for everything that should not go unnoticed but also cannot be triggered by an outside attacker, otherwise we might be flooding our logs
- 'Verbose' can be used for everything else.
There are a few exceptions, something we log at the 'info' level for events that might be happening a lot, but only when told to do so, like for example with verbose health-check reporting.
I have:
=> dnsdist: Set proper levels when logging messages

docs/upgrading.rst, pdns/arguments.cc
In 4.5, a bunch of things were renamed: https://doc.powerdns.com/authoritative/upgrading.html#renamed-options, but while there's code to tell people about renames, these renames were not included. This PR adds them.
I have:
=> Report auth settings deprecated in 4.5

docs/manpages/dnsscope.1.rst, pdns/dnsscope.cc
Until now `dnsscope` was only looking at packets from and to ports 53 and 5300 which is a bit restrictive.
I have:
=> dnsscope: Add a `--port` option to select a custom port

pdns/dnsdist-lua.cc, pdns/dnsdist-web.cc, pdns/dnsdistdist/dnsdist-dynblocks.cc, pdns/dnsdistdist/docs/advanced/ebpf.rst, pdns/dnsdistdist/docs/guides/dynblocks.rst, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/docs/reference/ebpf.rst, pdns/dnsdistdist/html/local.js
- Display whether blocks are eBPF-based in `showDynBlocks()`
- Log whether newly inserted dynamic blocks are eBPF-based
- Document that `add*DynBlocks()` methods are legacy ones
- Display whether blocks ar eeBPF-based in the internal web interface and API as well, plus export the metrics for the default BPF filter (`setDefaultBPFFilter`) automatically.
See https://github.com/PowerDNS/pdns/issues/13307 for more context.
I have:
=> dnsdist: Fix several cosmetic issues in eBPF dynamic blocks, update documentation

pdns/dnsdistdist/test-dnsdistasync.cc
We used to set the `errorRaised` variable from the `AsynchronousHolder` thread then check its value from the main thread, which is correctly reported as TSAN as a data race. We do know that we have waited enough, and that otherwise it's fine to fail, but TSAN cannot know that. Switching to a `std::atomic<bool>` fixes it.
I have:
=> dnsdist: Fix a race in the Async unit tests

contrib/assert-equal-DNSMessage/eqdnsmessage.py, pdns/ixfrdist.cc, regression-tests.ixfrdist/test_IXFR.py
=> auth-4.8: ixfrdist: set AA=1 on SOA responses

pdns/dnsdistdist/dnsdist-nghttp2-in.cc, pdns/dnsdistdist/dnsdist-nghttp2-in.hh
This PR changes the way timeouts are handled for incoming DoH connections with nghttp2 to follow the existing behaviour (h2o) more closely: the TCP read timeout is used when the connection is first created, until the handshake has been completed, the proxy protocol payload received if expected, and the first query received, then the idle timeout is used
It also fixes an issue with our accounting of open streams, which were not properly erased on normal termination.
I have:
=> dnsdist: Fix timeouts on incoming DoH connections with nghttp2

modules/remotebackend/httpconnector.cc, modules/remotebackend/pipeconnector.cc, modules/remotebackend/remotebackend.cc, modules/remotebackend/remotebackend.hh, modules/remotebackend/test-remotebackend-http.cc, modules/remotebackend/test-remotebackend-json.cc, modules/remotebackend/test-remotebackend-keys.hh, modules/remotebackend/test-remotebackend-pipe.cc, modules/remotebackend/test-remotebackend-post.cc, modules/remotebackend/test-remotebackend-unix.cc, modules/remotebackend/test-remotebackend-zeromq.cc, modules/remotebackend/test-remotebackend.cc, modules/remotebackend/unixconnector.cc, modules/remotebackend/zmqconnector.cc
Some cleanups to the auth remote backend. They are entirely automated by `clang-tidy`.
I have:
=> Some cleanups to the auth remote backend

pdns/iputils.hh, pdns/test-iputils_hh.cc
Until now we only normalized too large masks when constructed from a `ComboAddress` object and a separate mask, but not from a string.
I have:
=> Netmask: Normalize subnet masks coming from a string

modules/gmysqlbackend/smysql.cc
=> auth-4.6: smysql: stop explicity setting MYSQL_OPT_RECONNECT to 0

.github/scripts/clang-tidy-diff.py, .github/scripts/clang-tidy.py, .github/scripts/git-filter.py, .github/scripts/helpers.py, .github/scripts/normalize_paths_in_compilation_database.py, .github/workflows/build-and-test-all.yml
We now build in `dist` directories instead of building directly in the repository hierarchy, which makes matching files from the `git diff` against the compilation database harder, and then reporting the findings to the correct file in the repository even so.
This PR fixes that by rewriting the paths inside the compilation database to match the paths in the git repository, so that clang-tidy is run against these, from the root of the repository. It then ensures that the correct paths are used in the annotations generated from the clang-tidy output.
I had to import and modify a version of the `clang-tidy-diff.py` utility into our repository because `clang-tidy` only supports filenames in `-line-filter`, not paths, and the upstream `clang-tidy-diff.py` utility doesn't handle that.
I have:
=> build-and-test-all: Fix clang tidy checks

pdns/recursordist/rec-main.cc, pdns/recursordist/settings/table.py, pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh, pdns/recursordist/test-syncres_cc.cc
Also fix a counting ommission
I have:
=> rec: Make QName Minimization parameters from RFC 9156 settable

pdns/cachecleaner.hh, pdns/recursordist/negcache.cc, pdns/recursordist/negcache.hh, pdns/recursordist/rec-main.cc, pdns/recursordist/recpacketcache.cc, pdns/recursordist/recpacketcache.hh, pdns/recursordist/recursor_cache.cc, pdns/recursordist/recursor_cache.hh, pdns/recursordist/test-negcache_cc.cc, pdns/recursordist/test-recpacketcache_cc.cc, pdns/recursordist/test-recursorcache_cc.cc
For SyncRes tests we have a general mechanism setting the globals
before the test are run, but the non-syncres tests do not have that, while
they still use some globals.  In this particular case, the test would
fail if the last SyncRes test run before was setting
SyncRes::s_locked_ttlperc.
While there, pass the time to the prune functions. This avoids
potential timing issues for some tests.
I have:
- [X added or modified unit test(s)
=> rec:  Fix a spuriously failing recursorcache_cc test: reset globals (indirectly) used

pdns/dnsdistdist/docs/reference/dq.rst
If the re-try is also a servfail, dnsdist will restart it endlessly. Give some tips to not do that.
I have:
=> dnsdist: Fix the documentation of `dq:restart` to prevent an endless loop

pdns/recursordist/syncres.cc, pdns/recursordist/test-syncres_cc10.cc
PR #12395 already did that for the NXDOMAIN case.
I have:
=> rec: If serving stale, wipe CNAME records from cache when we get a NODATA negative response for them

tasks.py
It was removed during the DoQ work and I forgot to enable it back.
I have:
=> tasks: Enable back building dnsdist with LTO in our CI

pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdistdist/dnsdist-nghttp2-in.cc, pdns/dnsdistdist/dnsdist-tcp-upstream.hh, pdns/dnsdistdist/doh.cc, regression-tests.dnsdist/test_DOH.py
Mostly false positives, but also a real issue with `QueryProcessingResult::Empty` which was processed twice for incoming DoH queries with nghttp2.
I have:
=> dnsdist: Fix a few warnings from Coverity

pdns/ixfrdist-stats.cc, pdns/ixfrdist-stats.hh, pdns/ixfrdist.cc, regression-tests.ixfrdist/test_IXFR.py, regression-tests.ixfrdist/test_Stats.py
=> ixfrdist: add NOTIFY receive support

pdns/recursordist/lazy_allocator.hh
On NetBSD, memory used as stack should be R/W, and marked MAP_STACK, as on OpenBSD.
After a fresh build of the git HEAD of pdns on NetBSD/amd64-current, both updated to 2023-10-21 state,
the pdns_recursor would not run: the worker threads it created immediately died, throwing std::bad_alloc.
Otto Moerbeek suggested that the adjustments to the "lazy allocator" done for OpenBSD might be relevant.
A ktrace of the crashing recursor showed mprotect returning an error (with errno 13, EACCES) to each of
the threads just before they crashed, so I made the accompanying changes, which turned out to resolve
the situation.
I have:
=> Handle stack memory on NetBSD as on OpenBSD

pdns/dnsdist-idstate.hh, pdns/dnsdistdist/m4/dnsdist_enable_doq.m4, pdns/libssl.cc
DISABLE_OCSP_STAPLING has to be defined as well, since boring does not seem to have it.
Including a copy-paste and an include fix.
I have:
=> dnsdist: Allow building of dnsdist against boringssl on OpenBSD

pdns/recursordist/mtasker_fcontext.cc
OpenBSD has IBT (aka control flow enforcement) on amd64, for processor models that support it. But it turns out that the existing endbr64 instructions in the boost assembly for context switching are not enough: there needs to be endbr64 instructions right after the jump_fcontext() call, as indirect branches end up there.
I have:
=> rec: Add endbr64 instructions in the right spots for OpenBSD/amd64

pdns/recursordist/negcache.cc, pdns/recursordist/negcache.hh
Superseded #13383 by calling the general get() function that has all the special cases covered.
I have:
=> rec: handle serve stale logic in getRootNXTrust()

pdns/cachecleaner.hh, pdns/iputils.hh, pdns/recursordist/negcache.cc, pdns/recursordist/negcache.hh, pdns/recursordist/pdns_recursor.cc, pdns/recursordist/rec-main.cc, pdns/recursordist/rec_channel_rec.cc, pdns/recursordist/recpacketcache.cc, pdns/recursordist/recpacketcache.hh, pdns/recursordist/recursor_cache.cc, pdns/recursordist/recursor_cache.hh
Implements the record cache part of #12612. Includes a clang-tidy cleanup in two parts. Probably easiest to review per individual commit. One clang-tidy case (using clangd 15.0.0) remains in `recursor_cache.hh`:
```
[bugprone-standalone-empty]: Ignoring the result of 'empty()'
[[nodiscard]] bool isEmpty() const
{
return d_nmt.empty();
}
```
I believe clang-tidy is confused here. 
I have:
=> rec: tidy cache and only copy values if non-expired entry was found

.github/actions/spell-check/expect.txt, pdns/recursordist/docs/appendices/structuredlogging.rst
This describes the current state of affairs.
In the future, we should strive to unify the structured logging formats of the various products. We can either adapt the default backend if we want to (and accept it might be disruptive to existing scanning of structured logs), or we can define a new backend that conforms to the yet to be set standard.
I have:
=> rec: Describe the keys and values produced by structured logging in more detail

.github/workflows/build-packages.yml
The new version fixes the "The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/" warning.
I have:
=> build-packages: Update the version of the generic SLSA generator

pdns/recursordist/recursor_cache.cc, pdns/recursordist/syncres.cc
Fixing a use_after_move and a copy_instead_of_move
I have:
=> rec: fix coverity 1523746 and 1523745

.not-formatted, modules/bindbackend/bindbackend2.cc, modules/bindbackend/bindbackend2.hh, modules/remotebackend/remotebackend.cc, modules/remotebackend/remotebackend.hh, modules/remotebackend/test-remotebackend-http.cc, modules/remotebackend/test-remotebackend-json.cc, modules/remotebackend/test-remotebackend-pipe.cc, modules/remotebackend/test-remotebackend-post.cc, modules/remotebackend/test-remotebackend-unix.cc, modules/remotebackend/test-remotebackend-zeromq.cc, modules/remotebackend/test-remotebackend.cc, pdns/backends/gsql/gsqlbackend.cc, pdns/backends/gsql/gsqlbackend.hh, pdns/dnsbackend.cc, pdns/dnsbackend.hh, pdns/pdnsutil.cc, pdns/test-ueberbackend_cc.cc, pdns/ueberbackend.cc, pdns/ueberbackend.hh, pdns/ws-auth.cc
While I was fixing an issue with meson on MacOS related to the loading of backend shared modules when they are dynamically loaded, I formatted and cleaned up `ueberbackend.cc` a bit.
I have:
=> Cleanup `ueberbackend.cc` a bit

pdns/dnsdist-dynblocks.hh, pdns/dnsdist-lua-inspection.cc, pdns/dnsdistdist/docs/reference/config.rst, pdns/iputils.hh
This adds the ability to remove an existing range from the list of existing included/excluded ranges.
I have:
=> dnsdist: Add a DynBlockRulesGroup:removeRange() binding

pdns/recursordist/negcache.cc, pdns/recursordist/negcache.hh
Superseded #13383 by calling the general get() function that has all the special cases covered.
(cherry picked from commit e2bfa1460d5b9e4e470c2f8829ef6c10bc583c73)
Backport of #13409 
I have:
=> rec: backport 13409 to rec-4.9.x: handle serve stale logic in getRootNXTrust()

m4/ax_compare_version.m4, pdns/recursordist/configure.ac, pdns/recursordist/m4/ax_compare_version.m4, pdns/recursordist/m4/pdns_check_cargo.m4
I was a bit surprised autotools cannot check versions out of the box, so I added the AX_COMPARE_VERSION macro. 
I have:
=> rec: Teach configure to check for cargo version and require >= 1.64

pdns/dolog.hh
Coverity reports:
```
Performance inefficiencies (COPY_INSTEAD_OF_MOVE): "args" is
passed-by-value as parameter to "dolog" when it could be moved instead.
```
This PR implements perfect forwarding for the variadic template parameters of DNSdist's logging methods to address it, even though the performance of these functions should not matter much.
I have:
=> dnsdist: Fix Coverity CID 1523748: Performance inefficiencies in dolog.hh

pdns/dnsdistdist/m4/pdns_with_quiche.m4
Based on the release notes the API we use did not change after that.
Fixes https://github.com/PowerDNS/pdns/issues/13433
I have:
=> dnsdist: Require Quiche >= 0.15.0

pdns/recursordist/settings/cxxsupport.cc
This is due to an unititalizded value, since the CXX code does not generate constructors for structs.
`fix settings/cxxsupport.cc:525:40: runtime error: load of value 80, which is not a valid value for type 'bool'`
Mostly harmless
I have:
=> rec: fix ubsan error: using a value of 80 for bool

pdns/recursordist/settings/table.py, regression-tests.recursor-dnssec/test_AggressiveNSECCache.py, regression-tests.recursor-dnssec/test_basicNSEC3.py
Following the general consensus between open source vendors.
I have:
=> rec: change default of nsec3-max-iterations to 50

pdns/dnsdist-console.cc, pdns/dnsdist-idstate.hh, pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua-bindings-dnsquestion.cc, pdns/dnsdist.cc, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/dnsdist-edns.cc, pdns/dnsdistdist/dnsdist-edns.hh, pdns/dnsdistdist/dnsdist-lua-ffi-interface.h, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsdistdist/docs/reference/dq.rst, pdns/dnsdistdist/docs/rules-actions.rst, regression-tests.dnsdist/test_EDE.py
This PR adds support for adding EDNS Extended DNS Error statuses from DNSDist, via the following mechanisms:
- `SetExtendedDNSErrorAction`
- `SetExtendedDNSErrorResponseAction`
- `DNSQuestion:setExtendedDNSError(infoCode [, extraText])`
- `DNSResponse:setExtendedDNSError(infoCode [, extraText])`
- `dnsdist_ffi_dnsquestion_set_extended_dns_error(...)`
Closes https://github.com/PowerDNS/pdns/issues/12572
I have:
=> dnsdist: Add support for setting Extended DNS Error statuses

docs/migration.rst
Without :doc: the sentence is rendered as
See its manpage <manpages/zone2sql.1> for more information.
in the html output as can currently be seen on
https://doc.powerdns.com/authoritative/migration.html#migration-zone2sql . Adding :doc: makes this a proper link.
I have:
- [-] included documentation (including possible behaviour changes)
- [-] documented the code
- [-] added or modified regression test(s)
- [-] added or modified unit test(s)
=> docs/migration: Fix reference to zone2sql(1) manpage

pdns/recursordist/root-addresses.hh
Is going to be effective 20231127. Both existing and new addresses
work already at the moment of writing (20231027).
https://www.lacnic.net/6869/2/lacnic/lacnic-assigns-number-resources-to-the-usc_isi-dns-root-server
Fixes https://github.com/PowerDNS/pdns/issues/12897
I have:
=> rec: Update new b-root-server.net addresses in built-in hints.

builder-support/helpers/install_rust.sh, pdns/recursordist/settings/rust/Cargo.lock, tasks.py
This is a partial fix to #13470, by making sure the install script handles aarch64. It does *not* handle the case for using an existing rust install yet.
I have:
=> rec: install helper: Update rust to 1.73, take into account aarch64, update rust deps

pdns/recursordist/pdns_recursor.cc
Problem spotted by @zjs604381586 in #13483, though proposed fix was not correct.
I have:
=> rec: take into account throttled queries when determining if we had a cachehit

pdns/recursordist/docs/lua-config/rpz.rst, pdns/recursordist/filterpo.cc, pdns/recursordist/filterpo.hh, pdns/recursordist/rec-lua-conf.cc, pdns/recursordist/test-rpzloader_cc.cc
First the fix: the 2nd dup check in both `addNameTrigger` and `addNetmaskTrigger` was lacking a `!` I believe (unless I am misunderstanding things, so double check please!). While there, also fix the exception strings that were mixing up the new and existing policies.
Add a regress checks for that case, and also for the newly introduced `ignoreDuplicates` flag. Plus an example file from the draft for good measure.
Fixes #12842
I have:
=> rec: introduce a setting to allow RPZ duplicates, including a dup handling fix

pdns/recursordist/docs/metrics.rst, pdns/recursordist/lwres.cc, pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh, pdns/recursordist/ws-recursor.cc
Fixes #13463
There are also two behaviour changes: previously v6 queries over TCP or DoT were not counted in `ipv6-outqueries`, and queries were counted even when a Lua `preoutquery` hook would have prevented them.
I have:
=> rec: document outgoing querycounts better, including a small fix

pdns/dnsdist-carbon.cc, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/dnsdist-backend.cc, pdns/dnsdistdist/dnsdist-backoff.hh, pdns/dnsdistdist/test-dnsdistbackoff.cc
The existing code could overflow in some cases, leading to a potentially endless busy-loop.
Backport of #13520 to rel/dnsdist-1.8.x.
I have:
=> dnsdist-1.8.x: Refactor the exponential back-off timer code

pdns/recursordist/settings/docs-new-preamble-in.rst, pdns/recursordist/settings/docs-old-preamble-in.rst
This is the plan: in 5.0.0 use of YAML is completely optional. In 5.1.0 we are more insistent, e.g. by installing a default recursor.yml file for new installs. This release should also encourage admins to convert by loud log messages. In 5.2.0 old-style compatibility has to be enabled manually.
I have:
=> rec: describe the YAML transition plan in three phases

docs/catalog.rst, docs/manpages/pdnsutil.1.rst, pdns/pdnsutil.cc
As discussed in #12903 there's no documented way of removing a zone from a catalog zone. Adding a `unset-catalog` subcommand seems straightforward.
I have:
=> Add note to pdnsutil manpage on how to remove zone from catalog zone

regression-tests/runtests
Abort if `./regresstion-tests/runtests` is called directly.
I tend to do this because I misremember that I should use `start-test-stop help` instead.
I have:
=> auth tests: abort if runtests is used incorrectly

docs/settings.rst, pdns/auth-main.cc, pdns/logger.cc, pdns/logger.hh
When enabled, log messages are formatted like structured logs, including their log level/priority: 
`msg="Unable to launch, no backends configured for querying" prio="Error"`
fixes #12988 
I have:
=> auth: add loglevel-show setting

pdns/dnsdist.cc, regression-tests.dnsdist/test_Advanced.py
Until now we would not have detected if the response was larger than our buffer (4096 bytes or larger in some cases), which could have led to parsing errors or even forwarding a corrupted response.
<strike>I'll found this issue while working on https://github.com/PowerDNS/pdns/issues/11563 and a regression test for this issue will be included in a subsequent PR.</strike>I actually added one to this PR as well.
I have:
=> dnsdist: Detect and dismiss truncated UDP responses from a backend

pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua-rules.cc, pdns/dnsdist-lua.hh, pdns/dnsdistconf.lua, pdns/dnsdistdist/docs/rules-actions.rst, regression-tests.dnsdist/test-include-dir/01-test.conf, regression-tests.dnsdist/test_Basics.py, regression-tests.dnsdist/test_CacheHitResponses.py, regression-tests.dnsdist/test_CacheInsertedResponses.py, regression-tests.dnsdist/test_Caching.py, regression-tests.dnsdist/test_CheckConfig.py, regression-tests.dnsdist/test_Deprecated.py, regression-tests.dnsdist/test_EdnsClientSubnet.py, regression-tests.dnsdist/test_Routing.py, regression-tests.dnsdist/test_RulesActions.py, regression-tests.dnsdist/test_SVCB.py, regression-tests.dnsdist/test_SelfAnsweredResponses.py, regression-tests.dnsdist/test_Spoofing.py
- `NetmaskGroupRule` now accepts a string or list of strings, instead of requiring the use of `newNMG`
- `SuffixMatchNodeRule` also accepts a string or list of strings, instead of requiring the use of `newSuffixMatchNode`
- Passing a string or list of strings to `addAction` is now deprecated
- `makeRule` is now deprecated
Fixes https://github.com/PowerDNS/pdns/issues/10158
I have:
=> dnsdist: Improve `NetmaskGroupRule`/`SuffixMatchNodeRule`, deprecate `makeRule`

pdns/dnsdist-lua.cc, pdns/dnsdist-protocols.cc, pdns/dnsdist-protocols.hh, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/docs/reference/config.rst, pdns/proxy-protocol.hh, regression-tests.dnsdist/test_ProxyProtocol.py
When the new `proxyProtocolAdvertiseTLS` to `newServer` is set, and the query has been received from the client over an encrypted channel, the SSL proxy protocol TLV is set in the proxy protocol payload sent to the backend.
Closes https://github.com/PowerDNS/pdns/issues/11301
I have:
=> dnsdist: Add an option to set the SSL proxy protocol TLV

pdns/dnsdist-cache.cc, pdns/dnsdist-cache.hh, pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc, pdns/dnsdistdist/dnsdist-tcp-downstream.hh, pdns/dnsdistdist/dnsdist-tcp-upstream.hh, pdns/dnsdistdist/docs/reference/config.rst, pdns/test-dnsdistpacketcache_cc.cc, regression-tests.dnsdist/test_Caching.py
It used to be set to 4096 bytes, which is also a hard limit for UDP responses anyway, because of the internal buffer size, but the limit can now be raised for responses received over TCP (including DoT and DoH).
Since the existing value was used to determine the initial size of TCP buffers, these are also updated:
- the default buffer size for incoming TCP connections is now 2 bytes: no need to waste a lot of memory for incoming connections until we got at least one query
- the default buffer size for outgoing connection is now 512 bytes: it should be enough for a fair percentage of responses
This PR is based on top of https://github.com/PowerDNS/pdns/pull/13536 and will need to be rebased, so the first commit can be ignored for now.
Closes https://github.com/PowerDNS/pdns/issues/11563.
I …
=> dnsdist: Make the max size of entries in the packet cache configurable

.github/workflows/build-and-test-all.yml, .github/workflows/builder.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/formatting.yml, .github/workflows/fuzz.yml, .github/workflows/secpoll.yml, .github/workflows/spelling2.yml, build-scripts/gh-actions-setup-inv
Make `build-and-test-all` and `builder` workflows reusable from other branches.
Backport changes for deprecated actions.
This PR is a pre-requisite for scheduling the workflows `build-and-test-all` and `builder` from the `master` branch.
The following branches will be triggered from `master`:
- `auth/4.8.x`. Already merged: [https://github.com/PowerDNS/pdns/pull/13534](https://github.com/PowerDNS/pdns/pull/13534)
- `auth/4.7.x`
- `auth/4.6.x`
- `rec/5.0.x`
- `rec/4.9.x`
- `rec/4.8.x`
- `dnsdist/1.8.x`
- `dnsdist/1.7.x`
Example of a run for the `builder` workflow, per release/branch: [link](https://github.com/romeroalx/pdns/actions/runs/7113662407)
Same example for the `build-and-test-all` workflow: [link](https://github.com/romeroalx/pdns/actions/runs/7113662409)
I have:
=> GH Actions - rel/dnsdist-1.7.x: make `build-and-test-all` and `builder` workflows reusable from other branches

pdns/recursordist/lua-recursor4.cc
This fixes the recently recurring errors happening in our CI in these tests:
```
FAILED test_Lua.py::LuaHooksRecursorTest::testPreResolve - TypeError: msg is not a dns.message.Message but a <class 'NoneType'>
FAILED test_Lua.py::LuaHooksRecursorTest::testVanillaNXD - ConnectionRefusedError: [Errno 111] Connection refused
FAILED test_Lua.py::LuaHooksRecursorDistributesTest::testPreResolve - TypeError: msg is not a dns.message.Message but a <class 'NoneType'>
FAILED test_Lua.py::LuaHooksRecursorDistributesTest::testVanillaNXD - ConnectionRefusedError: [Errno 111] Connection refused
```
The recursor was crashing because it was calling a Lua callback which no longer existed at this point.
Introduced in 50bd111e3c78e2cc8c2aa916a1f9fc22699f1f60
I have:
=> rec: Fix a dangling reference in Lua's UDP Query Response callback

pdns/dnsdistdist/dnsdist-lua-network.cc, pdns/dnsdistdist/dnsdist-lua-network.hh
The main thread needs to be able to access the data even if the NetworkListener object has been destroyed first, which usually only happens when DNSdist is exiting, but could also happen earlier if the Lua handle is garbage collected (see #13583).
I have:
=> dnsdist: Fix a small race in the NetworkListener

pdns/dnsdist-lua.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/dnsdist-nghttp2-in.cc, pdns/dnsdistdist/dnsdist-tcp-upstream.hh, pdns/dnsdistdist/dnsdist-tcp.hh, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/test-dnsdistnghttp2-in_cc.cc, pdns/dnsdistdist/test-dnsdistnghttp2_cc.cc, pdns/dnsdistdist/test-dnsdisttcp_cc.cc, regression-tests.dnsdist/test_ProxyProtocol.py
The per-bind option defaults to `true` as to not break existing configuration, but setting `allowProxyProtocol=false` on a `add*Local()` directive disables proxy-protocol handling for this specific bind.
Closes https://github.com/PowerDNS/pdns/issues/12922
I have:
=> dnsdist: Allow enabling incoming PROXY protocol on a per-bind basis

pdns/recursordist/docs/performance.rst
We should suggest people only stop tracking on client DNS queries, instead of more blanket rules.
The other rules allow source port 53 traffic in without any filtering.
Even on larger recursor instances out queries are generally small enough to be handled by stateful tracking defaults.
I have:
=> rec: Update performance.rst

pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua-bindings-dnsquestion.cc, pdns/dnsdist-lua.hh, pdns/dnsdist.cc, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsdistdist/docs/reference/dq.rst, pdns/dnsdistdist/docs/rules-actions.rst, regression-tests.dnsdist/test_Spoofing.py
This PR adds the ability to spoof a raw response for ``ANY`` queries, as it would not make sense to use ``ANY`` for the type of the response record.
Closes https://github.com/PowerDNS/pdns/issues/13559
I have:
=> dnsdist: Spoof a raw response for ANY queries

pdns/dnsdist-lua-rules.cc, pdns/dnsdistdist/docs/rules-actions.rst, regression-tests.dnsdist/test_Basics.py, regression-tests.dnsdist/test_RulesActions.py
An easier to type alias to `SuffixMatchNodeRule`, as suggested by Håkan Lindqvist.
Closes https://github.com/PowerDNS/pdns/issues/13563
I have:
=> dnsdist: Add `QNameSuffixRule`

regression-tests.dnsdist/test_LuaFFI.py
=> dnsdist: Add regression tests for DNS header set/get via Lua FFI

pdns/dnsdistdist/dnsdist-nghttp2-in.cc, pdns/tcpiohandler.cc, regression-tests.dnsdist/test_DOH.py
Explaining that DNSdist with nghttp2 only supports DNS over HTTP2, as a best effort.
I have:
=> dnsdist: Send a HTTP 400 response to HTTP/1.1 clients

pdns/dnsdist-console.cc, pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua-rules.cc, pdns/dnsdist-lua-vars.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/dnsdist-lua-ffi.hh, pdns/dnsdistdist/dnsdist-rules.hh, pdns/dnsdistdist/docs/reference/constants.rst, pdns/dnsdistdist/docs/rules-actions.rst, pdns/dnsdistdist/test-dnsdistrules_cc.cc, regression-tests.dnsdist/test_Size.py
`PayloadSizeRule` can be used to match queries and responses based on their sizes, and `TCResponseAction` to truncate an already existing answer. Together they can be used to enforce a stricter truncation limit than what the backend is doing.
I have:
=> dnsdist: Add `PayloadSizeRule` and `TCResponseAction`

.github/workflows/build-and-test-all.yml, .github/workflows/builder.yml
Make `build-and-test-all` and `builder` workflows reusable from other branches.
Backport changes for deprecated actions.
This PR is a pre-requisite for scheduling the workflows `build-and-test-all` and `builder` from the `master` branch.
The following branches will be triggered from `master`:
- `auth/4.8.x`. Already merged: [https://github.com/PowerDNS/pdns/pull/13534](https://github.com/PowerDNS/pdns/pull/13534)
- `auth/4.7.x`
- `auth/4.6.x`
- `rec/5.0.x`
- `rec/4.9.x`
- `rec/4.8.x`
- `dnsdist/1.8.x`
- `dnsdist/1.7.x`
Example of a run for the `builder` workflow, per release/branch: [link](https://github.com/romeroalx/pdns/actions/runs/7113662407)
Same example for the `build-and-test-all` workflow: [link](https://github.com/romeroalx/pdns/actions/runs/7113662409)
I have:
=> GH Actions - rel/auth-4.6.x: make `build-and-test-all` and `builder` workflows reusable from other branches

.github/workflows/build-and-test-all.yml, .github/workflows/builder.yml
Make `build-and-test-all` and `builder` workflows reusable from other branches.
This PR is a pre-requisite for scheduling the workflows `build-and-test-all` and `builder` from the `master` branch.
The following branches will be triggered from `master`:
- `auth/4.8.x`. Already merged: [https://github.com/PowerDNS/pdns/pull/13534](https://github.com/PowerDNS/pdns/pull/13534)
- `auth/4.7.x`
- `auth/4.6.x`
- `rec/5.0.x`
- `rec/4.9.x`
- `rec/4.8.x`
- `dnsdist/1.8.x`
- `dnsdist/1.7.x`
Example of a run for the `builder` workflow, per release/branch: [link](https://github.com/romeroalx/pdns/actions/runs/7113662407)
Same example for the `build-and-test-all` workflow: [link](https://github.com/romeroalx/pdns/actions/runs/7113662409)
I have:
=> GH Actions - rel/rec-5.0.x: make `build-and-test-all` and `builder` workflows reusable from other branches

pdns/dnsdistdist/configure.ac
=> dnsdist: display if DNS over HTTP/3 is enabled or not in the configure report

pdns/tcpreceiver.cc
Fixes a small type qualifier warning:
```
[199/464] Compiling C++ object pdns/libpdns-tcpreceiver.cc.a.p/tcpreceiver.cc.o
../pdns/tcpreceiver.cc: In function ‘int readnWithTimeout(int, void*, unsigned int, unsigned int, bool, unsigned int)’:
../pdns/tcpreceiver.cc:135:22: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
135 |       if (elapsed >= static_cast<decltype(elapsed)>(remainingTotal)) {
|                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I have:
=> Fix type qualifier warning

pdns/dnsdist.cc, regression-tests.dnsdist/test_Advanced.py
Backport of #13536 to rel/dnsdist-1.8.x
I have:
=> dnsdist-1.8.x: Detect and dismiss truncated UDP responses from a backend

pdns/dnsdist-lua-rules.cc, regression-tests.dnsdist/test_RulesActions.py
Backport of #13488 to rel/dnsdist-1.8.x.
I have:
=> dnsdist-1.8.x: Fix the removal of the last rule by name or UUID

regression-tests.dnsdist/test_RulesActions.py
Backport of #13314 to rel/dnsdist-1.8.x.
See https://github.com/PowerDNS/pdns/pull/12912 for the longer explanation.
I have:
=> dnsdist-1.8.x: Skip our BADVERS regression test on broken Python versions

ext/json11/json11.cpp, pdns/webserver.cc, regression-tests.api/test_Servers.py
Backport of #13071 to rel/dnsdist-1.8.x
I have:
=> dnsdist-1.8.x: Fix code producing json

pdns/dnsdist-lua-bindings.cc, pdns/dnsdistdist/docs/reference/dq.rst, regression-tests.dnsdist/test_Lua.py
Backport of #13135 to rel/dnsdist-1.8.x
I have:
=> dnsdist-1.8.x: Add a `DNSHeader:getTC()` Lua binding

regression-tests.dnsdist/test_Metrics.py
Backport of #13182 to rel/dnsdist-1.8.x
We have seen in https://github.com/PowerDNS/pdns/issues/13148 that we can easily break frontend metrics when `recvmmsg`/`sendmmsg` support is enabled via `setUDPMultipleMessagesVectorSize()`, so let's test the metrics in that case explicitly so we do not break them again in the future.
I have:
=> dnsdist-1.8.x: Also test metrics with recvmmsg support enabled

pdns/dnsdistdist/test-dnsdistasync.cc
Backport of #13304 to rel/dnsdist-1.8.x.
We used to set the `errorRaised` variable from the `AsynchronousHolder` thread then check its value from the main thread, which is correctly reported as TSAN as a data race. We do know that we have waited enough, and that otherwise it's fine to fail, but TSAN cannot know that. Switching to a `std::atomic<bool>` fixes it.
I have:
=> dnsdist-1.8.x: Fix a race in the Async unit tests

pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Fix `DynBlockRulesGroup:removeRange`'s version in the docs

Docker-README.md, Dockerfile-auth
This PR adds `supervisor` to the Auth container image. Tini is still in place as default init process, but supervisor can be used for scenarios where more advanced process management has benefits.
Scenarios where this might be beneficial include:
- Running multiple processes (ie: auth + ixfrdist) within a single container
- Kubernetes: Automating restarts of a process (ie: ixfrdist) within a container when a mounted configmap containing the process' configuration is observed to have been changed (without restarting the container itself) 
I have:
=> Add supervisor to Auth container image

docs/http-api/swagger/authoritative-api-swagger.yaml, ext/yahttp/yahttp/router.cpp, ext/yahttp/yahttp/router.hpp, pdns/recursordist/ws-recursor.cc, pdns/webserver.cc, pdns/webserver.hh, pdns/ws-api.cc, pdns/ws-auth.cc, regression-tests.api/test_Basics.py, regression-tests.api/test_Zones.py
This change moves the HTTP verb checking into YaHTTP router. 
I have:
=> auth: Move method checking to Router

pdns/recursordist/settings/table.py
This is true since the move to `arc4random()`.
Remove them from YAML settings and mention the fact in old-style
I have:
=> rec: rng and entropy-source are not longer processed

pdns/recursordist/settings/table.py, pdns/recursordist/syncres.cc
The better zone-cut algorithm allows this. In my test of various cases (all top 1 million names and various reverse resolving cases mentioned in #8646 (with cold cache) I never saw a qperq higher than 37 (qname minimization enabled and DNSSEC validation as well).
I have:
=> rec: lower default max-qperq limit.

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: ChangeLog and secpoll update for 1.8.3

pdns/dnsdist-lua.cc, pdns/dnsdistdist/docs/guides/dns-over-http3.rst, pdns/dnsdistdist/docs/reference/config.rst
Fixes https://github.com/PowerDNS/pdns/issues/13639
I have:
=> dnsdist: Set the DNS over HTTP/3 default port to 443

.github/actions/spell-check/expect.txt, pdns/recursordist/Makefile.am, pdns/recursordist/rec-main.cc, pdns/recursordist/settings/generate.py, pdns/recursordist/settings/rust/Makefile.am, pdns/recursordist/settings/table.py
Backport of #13588 and #13612 
I have:
=> tec: Backport 13588 to rec 5.0.x: fix handling of RUNTIME_DIRETCORY and NOD dirs

pdns/dnsdistdist/doh3.cc, pdns/dnsdistdist/doq.cc
If the stream has no capacity left, Quiche will refuse to queue more data and return `QUICHE_ERR_DONE`. We then have to wait until the stream becomes writable again to retry sending our response.
Hopefully closes #13631. I managed to hit the reported issue and this PR fixes it for me, but I'm not 100% sure I am sending the same kind of traffic, so it might not fix all issues.
I have:
=> dnsdist: Handle congested DoQ streams

pdns/ws-auth.cc
This was lost / incorrectly replaced in #13153.
I have:
=> ws-auth: restore zone cache cleanup in apiServerZoneDetailDELETE

pdns/ws-auth.cc
So far we never flushed the DNSSEC caches, except when DELETEing a domain. However clearly some operations can affect the DNSSEC settings, and then the caches should go.
Also do this for the flush API, to be consistent, and for users writing to the DNSSEC settings/data externally.
I have:
=> auth api: flush all caches when flushing

.github/workflows/codeql-analysis.yml
Force CI failure if there are binaries present in a Pull Request.
The original request comes from this [pull request](https://github.com/PowerDNS/pdns/pull/13221)
This is an example of a failure in the CodeQL workflow when a binary file is added to a PR: [here](https://github.com/romeroalx/pdns/actions/runs/7182275016/job/19558412138)
I have:
=> GH Actions: force CI failure if there are binaries present in a Pull Request

docs/Makefile.am, pdns/Makefile.am
This allows building at least the auth in a mostly default configuration like
this:
```
mkdir build && cd build && \
autoreconf --install --force --verbose .. && \
../configure ...
```
This is useful because not all IDEs \*cough\* editors like in-tree builds, for performance or other reasons.
I have:
=> auth: allow building in separate build directory

pdns/dnsdist-lua-bindings.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-tcp.cc
One real issue that impact the TCP connection termination metrics, and some insignificant "performance" warnings in places where we do not care about performance.
The TCP metric issue was introduced in 448d66d4bb6fc1a6abff2329bd01cb65cf45005a so we will need to backport the fix to 1.8.x and perhaps 1.7.x.
I have:
=> dnsdist: Fix Coverity warnings

pdns/pdnsutil.cc
```
In file included from /usr/include/c++/13.2.1/x86_64-pc-linux-gnu/bits/c++allocator.h:33,
from /usr/include/c++/13.2.1/bits/allocator.h:46,
from /usr/include/c++/13.2.1/memory:65,
from /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:35,
from /usr/include/boost/smart_ptr/detail/shared_count.hpp:27,
from /usr/include/boost/smart_ptr/shared_ptr.hpp:18,
from /usr/include/boost/smart_ptr/allocate_shared_array.hpp:15,
from /usr/include/boost/smart_ptr/make_shared_array.hpp:13,
from ../pdns/pdnsutil.cc:2:
In member function ‘void std::__new_allocator<_Tp>::deallocate(_Tp*, size_type) [with _Tp = DNSResourceRecord]’,
inlined from ‘static void std::allocator_traits<std::allocator<_Tp1> >::deallocate(allocator_type&, pointer, size_type) [with _Tp = DNSResourceRecord]’ at …
```
=> Fix warning about pointer with non-zero offset being freed

pdns/dnsbulktest.cc, pdns/dnstcpbench.cc, pdns/histog.hh
```
[283/464] Compiling C++ object pdns/libdnstcpbench.a.p/dnstcpbench.cc.o
../pdns/dnstcpbench.cc:27:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
27 | #pragma GCC diagnostic ignored "-Wdeprecated-copy-with-user-provided-copy"
|                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[291/464] Compiling C++ object pdns/libdnsscope.a.p/dnsscope.cc.o
In file included from ../pdns/dnsscope.cc:27:
../pdns/histog.hh:4:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
4 | #pragma GCC diagnostic ignored "-Wdeprecated-copy-with-user-provided-copy"
|                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[305/464] Compiling C++ object pdns/libdnsbulktest.a.p/dnsbulktest.cc.o …
```
=> Fix "unknown option" warnings on GCC and older Clang

.not-formatted, pdns/auth-main.cc, pdns/statbag.hh, pdns/ws-api.cc, pdns/ws-api.hh, pdns/ws-auth.cc, pdns/ws-auth.hh
This removes the `extern StatBag` object from `ws-auth` and instead passes it around as a function/method argument. We should do this, in general, as part of a wider cleanup.
This also cleans up and formats some files automatically using `clang-format`.
Better reviewed on a per-commit basis.
I have:
=> Remove the `extern`ed `StatBag` from `ws-auth`

pdns/ws-auth.cc
When using a comma after the last element, `clang-format` is forced to put the closing brace on a separate line. This also improves the readability of future diffs.
I have:
=> Fix vector list formatting in `ws-auth.cc`

.github/workflows/build-and-test-all-releases-dispatch.yml, .github/workflows/build-and-test-all.yml, .github/workflows/builder-releases-dispatch.yml, .github/workflows/builder.yml
Schedule `build-and-test-all` (weekly) and `builder` (daily) workflows from `master` by adding two new workflow files. Follows the same periodicity as the schedules in `master`. Tested [here](https://github.com/romeroalx/pdns/actions/runs/7208879149) and [here](https://github.com/romeroalx/pdns/actions/runs/7208879157) 
The following branches will be triggered:
- `auth/4.8.x`
- `auth/4.7.x`
- `auth/4.6.x`
- `rec/5.0.x`
- `rec/4.9.x`
- `rec/4.8.x`
- `dnsdist/1.8.x`
- `dnsdist/1.7.x`
Workflows `build-and-test-all` and `builder` made reusable. 
I have:
=> GH Actions: Schedule `build-and-test-all` and `builder` workflows from `master` for different releases

pdns/dnsdistdist/doh3.cc, pdns/dnsdistdist/doq-common.cc, pdns/dnsdistdist/doq-common.hh, pdns/dnsdistdist/doq.cc, pdns/dnsreplay.cc, pdns/sstuff.hh
By reading as many UDP datagrams as possible from the socket when it becomes readable, processing as many DoQ events as possible in one go, and preventing a few allocations and copies.
I do get very nice results with this pull request and increasing the rmem and wmem buffers (which quic-go appears to do by default):
And even better on a longer-run, as the cost of establishing the QUIC connections is amortized (60 seconds run vs 20 seconds for the previous one above):
Might help with https://github.com/PowerDNS/pdns/issues/13631 even though I believe https://github.com/PowerDNS/pdns/pull/13664 might very well be as big a win.
I have:
=> dnsdist: Optimize the DoQ packet handling path

pdns/dnsdistdist/doh3.cc, pdns/dnsdistdist/doq.cc, regression-tests.dnsdist/quictests.py, regression-tests.dnsdist/test_DOH3.py, regression-tests.dnsdist/test_DOQ.py
This makes sure we enforce ACL in the DOQ and DOH3 paths.
I have:
=> dnsdist: doq,doh3 make sure we enforce any ACL

Dockerfile-dnsdist
This PR update the Dockerfile for dnsdist to enable DoQ and DoH3 as described in https://github.com/PowerDNS/pdns/issues/13669
I have:
=> Enable doq and doh3 in dockerfile-dnsdist

pdns/dnsdist.cc, pdns/iputils.cc, pdns/iputils.hh
QUIC packets should never be fragmented, so we need `DF=1`.
I have:
=> dnsdist: Enable PMTU discovery and disable fragmentation on QUIC binds

pdns/dnsdist.cc
When code coverage is enabled, we try to call `exit()` instead of our usual use of `_exit()` to get more accurate coverage. It does however trigger a race condition between the destruction of Lua objects and the Lua context(s) they belong to, so we try to explicitly clean up the objects before calling `exit()`.
I have:
=> dnsdist: Clean up the Lua objects before exiting

.github/workflows/build-and-test-all.yml, .github/workflows/build-packages.yml, .github/workflows/builder.yml, .github/workflows/documentation.yml, .github/workflows/fuzz.yml
Supersedes #13636 and #13637.
I have:
=> ci: Update upload-artifact and download-artifact to version 4

pdns/recursordist/mtasker.hh, pdns/recursordist/rec-main.cc, pdns/recursordist/test-mtasker.cc
The bug is located in a part of the code that we never actually use since we always pass the current time to the function, so I decided to reduce the complexity by making this parameter mandatory.
Reported by Coverity as CID 1533199.
I have:
=> rec: Fix a potential null deref in `MTasker::schedule()`

.github/workflows/build-packages.yml
The current version of the SLSA framework uses upload-artifact v3 which is not compatible with download-artifact v4 (don't ask me).
I have:
=> build-packages: Fix the handling of provenance artifacts

builder-support/dockerfiles/Dockerfile.target.debian-trixie
The package `fakeroot` is not present by default with the `Debian Trixie` docker image.
This package is used by the script `builder/helpers/build-debs.sh` during the `build` job of the `builder` workflow.
Fix tested here: [https://github.com/romeroalx/pdns/actions/runs/7473538907](https://github.com/romeroalx/pdns/actions/runs/7473538907)
I have:
=> GH Acttions: fix builder workflow for Debian Trixie

builder-support/dockerfiles/Dockerfile.target.debian-trixie
The package `fakeroot` is not present by default with the `Debian Trixie` docker image.
This package is used by the script `builder/helpers/build-debs.sh` during the `build` job of the `builder` workflow.
An example of a [failed run](https://github.com/PowerDNS/pdns/actions/runs/7469424676/job/20326514735#step:3:4233)
Already merged in [Master](https://github.com/PowerDNS/pdns/pull/13692). 
I have:
=> Backport 13692 to rec 5.0.x: GH Actions - Fix builder workflow for Debian Trixie

pdns/dnsdistdist/doh3.cc, pdns/dnsdistdist/doq.cc
This adds `Content-Type: application/dns-message` header in HTTP/3 responses which seems to make chromium happier...
This also unify `vinfolog()` content in the QUIC and HTTP/3 response paths so that we display the response size and always use `DoH3` just like in the query log (and not `http/3`).
Fixes #13690 on my setup.
I have:
=> dnsdist: DoH3 add content-type header information in responses

pdns/recursordist/Makefile.am, pdns/recursordist/mkpubsuffixcc, pdns/recursordist/settings/Makefile.am, pdns/recursordist/settings/rust/Makefile.am
Allow building recursor with autoconf in a separate build dir.
The codegen for the rust parts is not 100% clean: it writes two files into the srcdir. But it does build.
I have:
=> rec: allow out-of-tree builds

.github/actions/spell-check/allow.txt, docs/lua-records/functions.rst, pdns/lua-record.cc
Add and document a `localwho()` function for LUA records
This allows you to change your answer based on which address or port a query came in from.
Can be used like this:
```
berthub.eu	300	IN	LUA	A ";if(localwho:getPort() == 5300) then return '217.100.190.174'; else return '86.82.68.237'; end"
```
This, combined with some forwarding/iptables, means that queries that came in on 217.100.190.174 also get 217.100.190.174 as an answer. And same for 86.82.68.237. In this way you can do some simple DNS-based dual homing.
This code has been running in production for a few years already.
I have:
=> Add and document a `localwho()` function for LUA records

.not-formatted, pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua.hh, pdns/dnsdist-protobuf.cc, pdns/dnsdist-protobuf.hh, pdns/dnsdist.hh, pdns/dnsmessage.proto, pdns/dnsname.cc, pdns/dnsname.hh, pdns/dnstap.cc, pdns/dnstap.hh, pdns/protozero.hh, pdns/recursordist/lwres.cc, pdns/recursordist/pdns_recursor.cc, regression-tests.dnsdist/dnsdisttests.py, regression-tests.dnsdist/test_Protobuf.py
This PR properly sets protocol when logging via dnstap or protobuf when using DNS over QUIC and DNS over HTTP/3.
For protobuf, we add a `httpVersion` field so we can distinguish between DoH and DoHTTP/3 (https://github.com/PowerDNS/dnsmessage/pull/8).
We should eventually do something similar for dnstap if there is a possibility to do so (https://github.com/dnstap/dnstap.pb/issues/20).
Fix https://github.com/PowerDNS/pdns/issues/13672 and https://github.com/PowerDNS/pdns/issues/13673
Todo:
I have:
=> dnsdist: properly set protocol when logging

.not-formatted, docs/settings.rst, pdns/auth-main.cc, pdns/auth-primarycommunicator.cc, pdns/communicator.cc, pdns/communicator.hh
Adds a configurable `delay-notifications` parameter to delay notifications.
Fix #12785 
I have:
=> auth: add a configurable delay for notifications

docs/upgrading.rst, modules/gmysqlbackend/gmysqlbackend.cc, modules/godbcbackend/godbcbackend.cc, modules/gpgsqlbackend/gpgsqlbackend.cc, modules/gsqlite3backend/gsqlite3backend.cc, pdns/backends/gsql/gsqlbackend.cc, regression-tests.api/test_Zones.py, regression-tests/backends/godbc_sqlite3-master
This makes `catalog` non-empty in `.../zones` in the API (where it already works for `.../zones/example.com.`)
~~very much draft, needs a test~~ has a test
I have:
=> auth: set catalog in gsql getAllDomains

.github/actions/spell-check/allow.txt, .not-formatted, pdns/dnsdist-console.cc, pdns/dnsdist-console.hh, pdns/dnsdist-lua.cc, pdns/dnsdist.cc, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/dnsdist-crypto.cc, pdns/dnsdistdist/dnsdist-crypto.hh, pdns/dnsdistdist/docs/guides/console.rst, pdns/dnsdistdist/docs/manpages/dnsdist.1.rst, pdns/dnsdistdist/doh3.cc, pdns/dnsdistdist/doq-common.cc, pdns/dnsdistdist/doq-common.hh, pdns/dnsdistdist/doq.cc
We used to fall back to plain-text for console communications when libsodium was not available, which was not great. Now that we are also using the authenticated encryption module to secure our QUIC tokens, let's fall back to OpenSSL's Chacha20 Poly 1305 implementation instead.
Note that, unfortunately, both implementations are not compatible so the console communication format will be different depending on whether libsodium is available. I believe this is still better than plain-text :)
I'm renaming `sodcrypto.cc` and `sodcrypto.hh` in the process and GitHub is unfortunately not handling that very well, so it might be easier to review the diff in a different tool, sorry about that.
I have:
=> dnsdist: Fall back to libcrypto for authenticated encryption

modules/tinydnsbackend/Makefile.am
Fix a small issue where libssl include path would not be included while building tinydnsbackend.
```
In file included from tinydnsbackend.cc:25:
In file included from ./tinydnsbackend.hh:23:
In file included from ../../pdns/dnsbackend.hh:46:
../../pdns/sha.hh:25:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
^~~~~~~~~~~~~~~
1 error generated.
```
I have:
=> auth: fix tinydnsbackend compilation issue

pdns/dnsproxy.cc
Some parts of `dnsproxy.cc` had compilation errors but were not used on CI because they were inside calls to logging macros.
I have:
=> Fix compilation errors in `dnsproxy.cc` due to unused macro

pdns/dnsname.cc, pdns/dnsname.hh
This PR ~format `dnsname.{hh,cc}` files and~ corrects the type of `len` and `offset` arguments from `int` to `size_t`.
I have:
=> DNSName: correct len and offset types

tasks.py
Compilation errors were not caught inside of calls to logging macros on master. This enables verbose logging in our CI to catch such errors.
I have:
=> CI: Enable verbose logging to catch errors within logging macros

regression-tests.recursor/YAMLConversion/command
This test has race condition and after #13728, an output line can occur multilpe times in the output. So filter those.
I have:
=> rec: fix YAML conversion test

pdns/recursordist/aggressive_nsec.hh, pdns/recursordist/docs/manpages/rec_control.1.rst, pdns/recursordist/rec_channel_rec.cc
To avoid race conditions creating and destroying the cache, we do not allow setting the cache size if it is not enabled from startup. Also, setting the cache size to 0 with this command does not disable the cache, it just makes it mostly ineffective (entries can still appear in it and get used until the purge task is run). 
Fixes #13265.
I have:
=> rec: introduce command to set aggressive NSEC cache size

pdns/iputils.hh, pdns/recursordist/filterpo.cc, pdns/recursordist/filterpo.hh
The change to lookup in `NetmaskTree` looks more invasive than it is. `node_type`'s key part is already `const`. The `value` is not `const`, we can change it without bad effects.
I have:
=> rec: Tidy filterpo.?? (reaching into iputils.hh as well)

regression-tests.auth-py/test_GSSTSIG.py
Wrong records were tested for non-presence, as noted by @Assumeru
I have:
=> auth: fix gss regression test

pdns/dnsname.cc, pdns/dnsname.hh
The gist of this change is to stop allocating and copying per label when parsing DNSNames from the wire format, as long as we do not encounter a compression pointer, so that we only allocate and copy once for as many labels as possible.
This has a noticeable impact in some of our speedtest results:
| Test | Before | After |
| --- | --- | --- |
| 'parse 'empty-query'' | 7282032.6 runs/s, 0.14 us/run | 13519722.8 runs/s, 0.07 us/run |
| 'parse 'empty-query' bare' | 7512588.4 runs/s, 0.13 us/run | 14421770.5 runs/s, 0.07 us/run |
| 'parse 'typical-referral' bare | 917539.2 runs/s, 1.09 us/run | 1151581.7 runs/s, 0.87 us/run |
| 'parse 'typical-referral'' | 626927.3 runs/s, 1.60 us/run | 711754.3 runs/s, 1.40 us/run |
The improvement is quite clear when the number of labels increases:
| …
=> dnsname: Optimize parsing of uncompressed labels

.github/workflows/codeql-analysis.yml
The fuzzing/corpus directory contains payloads that are used to speed-up the process of finding interesting code paths, and some of these are binary files.
I have:
=> ci: Exclude the fuzzing/corpus dir from the 'no binary files' check

builder-support/dockerfiles/Dockerfile.target.ubuntu-noble
The latest Ubuntu Noble docker image includes a package `usrmerge` version that lacks the sha256sum in its metadata, which provokes a failure in our provenance script.
As a workaround, this package is removed until it is fixed for the distro.
This fix has been tested in the following [run](https://github.com/romeroalx/pdns/actions/runs/7749148036)
I have:
=> GH Actions: fix builds for ubuntu noble. Remove pkg usrmerge

docs/upgrading.rst, pdns/ws-auth.cc
This should make outdated API clients notice failure earlier and/or more clearly.
I have:
=> auth API: reject priority element in record, closes #12657

pdns/dnsdistdist/doh3.cc, pdns/dnsdistdist/doq-common.hh, pdns/dnsdistdist/doq.cc
After a QUIC connection has been negotiated, we mostly get short QUIC headers that do not contain the QUIC version. This is fine as long as we still know about the connection, which might not be the case if it has been idle for longer that our timer and thus we forgot about its connection ID. What happens then is that we will mistakenly think that the remote peer is trying to establish a new QUIC connection with a version set to 0, which we don't support, and therefore start the version negotiation process. What we should instead do is notice that the packet is not a 'Initial' one and discard it, as we cannot open a new connection from a short header anyway. Note that the peer knows about our idle timer so in theory it should not try to reuse such a connection, but it does happen from …
=> dnsdist: Better handling of short, non-initial QUIC headers

.github/actions/spell-check/expect.txt, docs/lua-records/functions.rst, pdns/lua-record.cc, regression-tests.auth-py/test_LuaRecords.py
This adds a Lua function to return a record based on a weighted hash of the DNS record name.  One use case here is to consistently return the same IP address for a particular cache server based on what subdomain is requesting the data.
This is pretty much a copy and paste of pickwhashed
I have:
=> Add Lua function to pick records via name hash

ext/luawrapper/include/LuaContext.hpp, pdns/dnsdist-lua-bindings.cc, pdns/dnsdist-lua.cc, regression-tests.dnsdist/test_Routing.py
luajit aligns only to 8 bytes by default, and some objects require 16 byte alignment.
Fixes #13766
Note that one `static_assert` in LuaContext.hpp is commented.  This trips on c++lib 17, but does not seem to be harmful right now as the code works.
The fundamental solution remains to have luajit agree with C++ on minimal alignment of its allocators.
I have:
=> dnsdist: do not allocate 16-byte aligned objects through lua(jit)

pdns/dnsdistdist/doh3.cc, pdns/dnsdistdist/doq.cc
Reported by Coverity as 414759 and 414760:
> Performance inefficiencies  (COPY_INSTEAD_OF_MOVE)
I have:
=> dnsdist: Fix performance inefficiencies reported by Coverity

pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Clarify that setSuffixMatchRule blocks per suffix, not labels

pdns/recursordist/aggressive_nsec.cc, pdns/recursordist/aggressive_nsec.hh, pdns/recursordist/pdns_recursor.cc, pdns/recursordist/rec-main.cc, pdns/recursordist/rec-zonetocache.cc, pdns/recursordist/settings/table.py, pdns/recursordist/syncres.cc, pdns/recursordist/syncres.hh, pdns/recursordist/test-aggressive_nsec_cc.cc, pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc4.cc, pdns/recursordist/test-syncres_cc5.cc, pdns/recursordist/test-syncres_cc8.cc, pdns/validate.cc, pdns/validate.hh, regression-tests.recursor-dnssec/test_AggressiveNSECCache.py
=> rec: Backport Keytrap to rec-5.0.x

pdns/Makefile.am
Add missing libdl to `ixfrdist` linking.
I have:
=> ixfrdist: fix centos build

regression-tests.recursor-dnssec/test_ExtendedErrors.py
(cherry picked from commit 1c47d58191e285aa2f85c24bbddba55f95cd58a2)
Backport of #13787 
I have:
=> rec: Backport 13787 to rec-5.0.x: skip a few test that depend on sidnlab's public test setup that no longer works

regression-tests.recursor-dnssec/test_ExtendedErrors.py
Backport of #13787 
(cherry picked from commit 1c47d58191e285aa2f85c24bbddba55f95cd58a2)
I have:
=> rec: Backport 13787 to rec-4.x.8: skip a few test that depend on sidnlab's public test setup that no longer works

regression-tests.recursor-dnssec/test_ExtendedErrors.py, regression-tests.recursor-dnssec/test_ServerNames.py
Backport of #13813 
See https://dnspython.readthedocs.io/en/stable/whatsnew.html 2.6.0 2nd bullet
(cherry picked from commit e1ea89984da1c10850dd0cb4e7d4d7ee501e078d)
I have:
=> rec: Backport 13813 to rec 4.9.x: dnspython's API changed wrt NSID, apply (version dependent) fix in regression test

regression-tests.recursor-dnssec/test_ExtendedErrors.py, regression-tests.recursor-dnssec/test_ServerNames.py
Backport of #13813
See https://dnspython.readthedocs.io/en/stable/whatsnew.html 2.6.0 2nd bullet
(cherry picked from commit e1ea89984da1c10850dd0cb4e7d4d7ee501e078d)
I have:
=> rec: Backport 13813 to rec.5.0.x: dnspython's API changed wrt NSID, apply (version dependent) fix in regression test

pdns/recursordist/rec-zonetocache.cc, pdns/zonemd.cc, pdns/zonemd.hh, regression-tests.recursor-dnssec/test_ZTC.py
=> rec: Backport 13788 to rec 5.0.x: fix the zoneToCache regression introduced by SA 2024-01

pdns/recursordist/filterpo.cc, pdns/recursordist/filterpo.hh, pdns/recursordist/lua-recursor4.cc, pdns/recursordist/pdns_recursor.cc, pdns/recursordist/rec-lua-conf.cc, pdns/recursordist/rec-main.cc, pdns/recursordist/rpzloader.cc, pdns/recursordist/test-filterpo_cc.cc
This PR contains two ways to reduce RPZ memory usage:
1. Use `unique_ptr`s for optional data in a `Policy` object. This reduces the memory used per RPZs by roughly 40% in typical cases.
2. Avoid keeping a reference to the Lua config object in the thread startup code. This avoid keeping the RPZs loaded at startup around after a `rec_control reload-lua-config`.  Tested with `rpzFile` and `rec_control reload-lua-config`, but I suspect `rpzPrimary` has the same issue.
Fixes #13827 and fixes #12870 (duplicate)
Some memory usage data, first a clean startup wit a couple of RPZ loaded via `rpzPrimary()`:
```
1043 otto      10    0 2344M 2327M idle      fsleep    1:15  0.00% pdns_recursor <- master
68681 otto      10    0 1404M 1386M idle      fsleep    1:30  0.00% pdns_recursor <- PR code
```
On …
=> rec: reduce RPZ memory usage

docs/performance.rst, docs/settings.rst
It wasn't clear to be what overload-queue-length did until I looked at the code.  This is a documentation only update
=> Update overload-queue-length and overload-drops documentation

pdns/recursordist/syncres.cc, pdns/recursordist/test-syncres_cc3.cc
When the recursor is forwarding to a resolver, we accept the names composing the CNAME chain starting at the queried name. This means we also need to gather the denial of existence proof for CNAMEs that were expanded from a wildcard, otherwise the response sent to the client cannot be DNSSEC-validated.
Fixes https://github.com/PowerDNS/pdns/issues/13817 and supersedes https://github.com/PowerDNS/pdns/pull/13818
I have:
=> rec: Fix gathering of denial of existence proof for wildcard-expanded names

pdns/recursordist/test-syncres_cc3.cc, pdns/syncres.cc
Manual backport of #13847 as syncres.c's location changed
I have:
=> rec: Backport 13847 to rec-4.8.x: Fix gathering of denial of existence proof for wildcard-expanded names

.clang-tidy.full
This was discussed earlier. There are good reason to have const and/or refs as fields. For refs you do need to take care the reference objects does not get deleted, of course.
I have:
=> common: less strict clang-tidy: allow const and/or ref fields in classes

pdns/recursordist/rec-zonetocache.cc
In the record cache, a wildcard has no meaning, it will only match a literal '*'. No need for backport AFAIKS, as it does not prevent queries matching a wildcard in the auth to be processed by rec (either the query is sent to the auth if no match was found in the record cache, or it is matched by the record cache against a previously received record from the auth).
I have:
=> rec: Don't enter wildcard qnames into the cache in the ZoneToCache function

docs/backends/remote.rst
Update remote backend documentation to reflect the fact that getAllDomains is mandatory unless you change the Zone Cache default
I have:
=> Update remote.rst to reflect that getAllDomains might be mandatory

pdns/nameserver.cc
Should fix #13857 in many cases, though you can still argue this is a OpenBSD bug (or at least an undesirable difference between other systems and OpenBSD).
See also #9633
I have:
=> auth: on OpenBSD, try harder to send on a non-blocking socket

.github/workflows/build-and-test-all.yml
Github runners with the latest `ubuntu-22.04` image version are using a 32-bit entropy value, which is not compatible with the LLVM installed by default on these runners. This affects the `build-and-test-all.yml` workflow (even tough tests are run on containers on top of the GH runners).
This change should be reverted once the issue is solved. This issue can be tracked [here](https://github.com/actions/runner-images/issues/9491)
I have:
=> gh actions: Fix CI - `issue 9491` on repository `actions/runner-images`

builder-support/dockerfiles/Dockerfile.target.debian-trixie
Update submodule pdns-builder for removing fakeroot usage.
CI runs currently failing when building `rel/rec-5.0.x` on `ubuntu-noble`: [https://github.com/PowerDNS/pdns/actions/runs/8226664556/job/22493416295](https://github.com/PowerDNS/pdns/actions/runs/8226664556/job/22493416295)
I have:
=> rec: Backport 13720 to rec-5.0.x: update submodule pdns-builder for removing fakeroot usage

pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/dnsdist-lua-actions.cc, pdns/dnsdistdist/dnsdist-lua-rules.cc, pdns/dnsdistdist/dnsdist-rule-chains.cc, pdns/dnsdistdist/dnsdist-rule-chains.hh, pdns/dnsdistdist/dnsdist-tcp-upstream.hh, pdns/dnsdistdist/dnsdist-web.cc, pdns/dnsdistdist/dnsdist-xsk.cc, pdns/dnsdistdist/dnsdist.cc, pdns/dnsdistdist/dnsdist.hh, pdns/dnsdistdist/doh.cc, pdns/dnsdistdist/doh3.cc, pdns/dnsdistdist/doq.cc, pdns/dnsdistdist/test-dnsdist_cc.cc, pdns/dnsdistdist/test-dnsdisttcp_cc.cc
This PR creates a list of response rule chains so we can deal with them using a loop instead of having to take care of them one by one. It makes the code easier to read and reduces the likelihood of introducing a bug when implementing a new chain.
I have:
=> dnsdist: Simplify the handling of rule chains

pdns/auth-secondarycommunicator.cc
=> auth 4.9: do not disable ns records at apex in consumer zones

pdns/nameserver.cc
=> auth 4.9: on OpenBSD, try harder to send on a non-blocking socket

pdns/dnsdistdist/dnsdist-console.cc, regression-tests.dnsdist/dnsdisttests.py, regression-tests.dnsdist/test_Console.py
If we don't set the family of the client IP address, `ComboAddress::getSocklen()` will return the size of an IPv4 struct and thus the first IPv6 client address will get truncated. Subsequent connections will be fine because the family will have been set to IPv6.
Completely untested, needs to be tested and could use a regression test!
Hopefully fixes https://github.com/PowerDNS/pdns/issues/13903
I have:
=> dnsdist: Fix first IPv6 console connection being rejected

pdns/dnsdistdist/dnsdist-idstate.hh
This saves 524 kB per downstream server in the default configuration (8 bytes times 65536 slots).
I have:
=> dnsdist: Shrink InternalQueryState's size by reordering its fields

pdns/recursordist/pdns_recursor.cc, regression-tests.recursor-dnssec/test_TraceFail.py, regression-tests.recursor-dnssec/test_ZTC.py
This was introduced with the trace rewrite. Add a regression test to detect future failure.
While there, modify the ZTC test to not start auths, they are not needed.
I have:
=> rec: fix trace=fail regression

.github/workflows/build-packages.yml, .github/workflows/builder-dispatch.yml
As it is coming out next month, we should start building from it with the next releases of rec 5, auth 4.9.x and dnsdist 1.9.x
@rgacogne am I seeing correctly that this does not need backports?
I have:
=> add ubuntu noble to default build targets

.github/workflows/build-and-test-all.yml, .github/workflows/codeql-analysis.yml, tasks.py
When working on stuff related to optional features it is easy to miss e.g. an `#ifdef`, so also build with basically all optional stuff disabled. Approach stolen from the dnsdist case.
I have:
=> rec ci: also build a rec with all optional stuff disabled

pdns/dnsdistdist/dnsdist.cc
Refer to #13945 for details
I have:
On macOS:
```
prio="Debug" msg="Got query for www.apple.com|A from 127.0.0.1:57298, relayed to [2620:fe::fe]:53"
prio="Debug" msg="Got answer from [2620:fe::fe]:53, relayed to 127.0.0.1:57298 (UDP), took 17783 us"
Disable v6 here
prio="Debug" msg="Got query for www.apple.com|A from 127.0.0.1:51308, relayed to [2620:fe::fe]:53"
prio="Debug" msg="Error sending request to backend [2620:fe::fe]:53: No route to host"
prio="Info" msg="Error connecting to new server with address [2620:fe::fe]:53: connecting socket to [2620:fe::fe]:53: No route to host"
prio="Debug" msg="Backend [2620:fe::fe]:53 reached the lazy health-check threshold (50% out of 20%, looking at sample of 2 items with 1 failures), moving to Potential Failure state"
prio="Debug" msg="Backend …
```
=> dnsdist: also handle EHOSTUNREACH as a case for reconnecting the socket

pdns/dnsdist-console.cc, regression-tests.dnsdist/dnsdisttests.py, regression-tests.dnsdist/test_Console.py
Backport of #13906 to 1.9.x
I have:
=> dnsdist-1.9.x: Backport of #13906 - Fix first IPv6 console connection being rejected

pdns/dnsdist-idstate.hh
Backport of #13920 to 1.9.x
I have:
=> dnsdist-1.9.x: Backport of #13920 - Shrink InternalQueryState's size by reordering its fields

.github/workflows/misc-dailies.yml
Add option feature (full) to ci-rec-configure in the misc-dailies workflow. Required since [this change](https://github.com/PowerDNS/pdns/commit/dc46a0283a5f36dcd4747cfd868087e0800ada75)
Example of a failed run: [https://github.com/PowerDNS/pdns/actions/runs/8353894551/job/22866345611](https://github.com/PowerDNS/pdns/actions/runs/8353894551/job/22866345611)
I have:
=> gh actions - misc-dailies workflow: add feature option to ci-rec-configure task

modules/gmysqlbackend/gmysqlbackend.cc, modules/godbcbackend/godbcbackend.cc, modules/gpgsqlbackend/gpgsqlbackend.cc, modules/gsqlite3backend/gsqlite3backend.cc, pdns/backends/gsql/gsqlbackend.hh
Using a unique pointer from the beginning makes the ownership of the pointer more clear, and prevents leaking the database connection and associated memory if an exception is raised right away.
I have:
=> auth: Wrap SSql pointers in a unique pointer earlier

docs/upgrading.rst, pdns/ixfrdist.cc
This avoids getting IPv6-mapped v4 sources, which confused the NOTIFY and acl handlers.
I have:
=> ixfrdist: use IPV6_V6ONLY on listening sockets, closes #13878

pdns/ssqlite3.cc
Clean up SSQLite3::~SSQLite3
* The loop will run once or twice
* There used to be some cleanup that was done in the failure case but it has been gone for a while
* Clarify logic
* Report error message from sqlite3
I have:
=> Clean up `SSQLite3::~SSQLite3`

pdns/pdnsutil.cc, pdns/ws-auth.cc
https://datatracker.ietf.org/doc/html/rfc8624#section-3.3
```
| Number | Mnemonics       | DNSSEC Delegation | DNSSEC Validation |
+--------+-----------------+-------------------+-------------------+
| 0      | NULL (CDS only) | MUST NOT [*]      | MUST NOT [*]      |
| 1      | SHA-1           | MUST NOT          | MUST              |
| 2      | SHA-256         | MUST              | MUST              |
| 3      | GOST R 34.11-94 | MUST NOT          | MAY               |
| 4      | SHA-384         | MAY               | RECOMMENDED       |
```
closes #13950
I have:
=> auth: deprecate output of SHA1, GOST hashes

docs/lua-records/index.rst
Improve rst for lua-records
I have:
=> Improve rst for lua-records

pdns/recursordist/rec-main.cc
This allows `dont-throttle-netmasks` to have negations.  The introduction of YAML settings made the docs say that it supports negations already, so this just makes that actually work.
I have:
=> rec-main: let NetmaskGroup parse dont-throttle-netmasks

.github/workflows/build-tags.yml
build-tags uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master As of f107ec62467b8779db9bbdb175721ef232ed52e5, that workflow requires:
```yml
permissions:
actions: read   # To read the workflow path.
id-token: write # To sign the provenance.
contents: write # To be able to upload assets as release artifacts
```
Per https://docs.github.com/en/actions/using-workflows/reusing-workflows in order for this to work, the calling job (in build-tags) needs to have the maximum required permissions in order for the calling workflow to be run.
I have:
=> Allow build-tags to run on forks

.github/workflows/formatting.yml
The workflow performs two very unrelated tasks:
* Verify source code formatting
* Check Makefile.am sort order
I have:
=> Clarify workflow name

pdns/threadname.cc
Meson uses `#define HAVE_FEATURE` (without 1), so it matters there
I have:
=> Always check HAVE_XYZ flags with #ifdef

pdns/dnsdistdist/dnsdist-backend.cc
The check was reverted, meaning that we did not properly remove an address:port from the XSK map when reconnecting a backend, and actually tried to remove an entry from a non-existing map when XSK is compiled in but not enabled, triggering a:
```
Error getting the XSK destination addresses map path '/sys/fs/bpf/dnsdist/xsk-destinations-v4'
```
message.
I have:
=> dnsdist: Fix XSK-enabled check when reconnecting a backend

pdns/dnsdistdist/dnsdist-backend.cc
Backport of #13914 to 1.9.x: 
The check was reverted, meaning that we did not properly remove an address:port from the XSK map when reconnecting a backend, and actually tried to remove an entry from a non-existing map when XSK is compiled in but not enabled, triggering a:
```
Error getting the XSK destination addresses map path '/sys/fs/bpf/dnsdist/xsk-destinations-v4'
```
message.
I have:
=> dnsdist-1.9.x: Backport of 13914 - Fix XSK-enabled check when reconnecting a backend

docs/settings.rst, pdns/auth-main.cc, pdns/recursordist/docs/running.rst, pdns/recursordist/settings/table.py
~~PRing now so I don't forget, but this is not done:~~ done:
=> auth, rec: update option text and docs to clarify logging is to stderr, not stdout

docs/dnsupdate.rst, docs/settings.rst, pdns/auth-main.cc, pdns/gss_context.hh, pdns/rfc2136handler.cc, regression-tests.auth-py/test_GSSTSIG.py
Closes #12234 by adding the proposed `dnsupdate-require-tsig` setting.
Not ideal perhaps, but backwards compatible, which is nice. Adding to `test_GSSTSIG.py` is a bit iffy considering it's not GSS related but it is convenient.
I have:
=> auth: Add setting to make TSIG required for DNS updates
