PowerDNS/pdns

pdns/recursordist/pdns-recursor.service.in

rec: Backport 13210 to rec-4.9.x: remove Before=nss-lookup.target line from unit file

---

.github/workflows/build-packages.yml
.github/workflows/build-tags.yml
.github/workflows/builder.yml
builder-support/dockerfiles/Dockerfile.debbuild
builder-support/dockerfiles/Dockerfile.rpmbuild

This is basically a copy of the backport to dnsdist-1.8.x PR #13184
I have:

rec: Backport 13223 to rec-4.9.x: auto-build on tags and generate provenance

---

pdns/recursordist/lua-recursor4.cc
pdns/recursordist/pdns_recursor.cc

rec: Backport 13092 to rec 4.9.x: prevent two cases of copy of data that can be moved

---

.github/workflows/builder.yml
builder-support/dockerfiles/Dockerfile.target.ubuntu-mantic
builder-support/dockerfiles/Dockerfile.target.ubuntu-mantic-amd64
builder-support/dockerfiles/Dockerfile.target.ubuntu-mantic-arm64

builder: add ubuntu-mantic target

---

.github/workflows/builder.yml
builder-support/debian/authoritative/debian-buster/tests-source/smoke-bind
builder-support/debian/authoritative/debian-buster/tests-source/smoke-lmdb
builder-support/debian/authoritative/debian-buster/tests/control
builder-support/debian/authoritative/debian-buster/tests/smoke-bind
builder-support/debian/authoritative/debian-buster/tests/smoke-mysql
builder-support/debian/authoritative/debian-buster/tests/smoke-mysql-sp
builder-support/debian/authoritative/debian-buster/tests/smoke-pgsql
builder-support/dockerfiles/Dockerfile.target.debian-trixie
builder-support/dockerfiles/Dockerfile.target.debian-trixie-amd64
builder-support/dockerfiles/Dockerfile.target.debian-trixie-arm64

add debian-trixie build target

---

.github/actions/spell-check/allow.txt
pdns/dnsdist-carbon.cc
pdns/dnsdist-web.cc
pdns/dnsdistdist/docs/guides/webserver.rst

dnsdist: client timeouts not client imeouts 
I have:

dnsdist: client timeouts not client imeouts 

---

.github/actions/spell-check/expect.txt
pdns/dnsdistdist/docs/reference/kvs.rst

dnsdist kvs docs: fix typo

---

regression-tests.dnsdist/test_RulesActions.py

See https://github.com/PowerDNS/pdns/pull/12912 for the longer explanation.
I have:

dnsdist: Skip our BADVERS regression test on broken Python versions

---

docs/requirements.in
docs/requirements.txt

auth docs: update sphinxcontrib-api hash, add a comment

---

docs/changelog/4.8.rst
docs/secpoll.zone

auth-4.8.3: changelog and secpoll

---

build-scripts/gh-actions-setup-inv

auth-4.7: fix github actions grub issue

---

build-scripts/gh-actions-setup-inv

auth-4.6: fix github actions grub issue

---

pdns/dnsdist-web.cc
pdns/dnsdistdist/html/local.js

As suggested by Sébastien Riccio in https://github.com/PowerDNS/pdns/issues/7332#issuecomment-1750027255
I have:

dnsdist: Display the rule name, if any, in the web interface

---

pdns/dnspacket.cc

auth-4.7: Fix incorrect optsize

---

m4/pdns_check_libcrypto.m4

auth-4.7: Work around Red Hat 8 pooping the bed in OpenSSL's headers

---

pdns/recursordist/rec-zonetocache.cc
pdns/recursordist/rec-zonetocache.hh
pdns/unix_utility.cc

Some were missing priority. While there, delint zone to cache code as well and fix one log message: Validated denial of absence  -> Validated denial of existence
I have:

rec: fix log messages related to zone to cache function

---

pdns/recursordist/lua-recursor4.cc
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/pubsuffixloader.cc
pdns/recursordist/rec-lua-conf.cc
pdns/recursordist/rec-taskqueue.cc
pdns/recursordist/rec-tcp.cc
pdns/recursordist/syncres.cc
pdns/unix_utility.cc

Found while working on a list
I have:

rec: more log (level) fixes

---

pdns/recursordist/docs/changelog/4.9.rst

rec: Mention removal of sysvinit script in 4.9.x changelog.

---

pdns/recursordist/syncres.cc

Do not chase CNAMEs while resolving NS names to addresses, including a fix where useless child NS records prevent (potential useful) parent NS records to be inserted into the cache.
I have:

rec: conform to rfc2181 10.3

---

Dockerfile-dnsdist

dnsdist Docker: enable h2o again, using our fork

---

docs/requirements.txt
pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

dnsdist-1.6.x docs: move dependencies from pieterlexis to PowerDNS

---

Dockerfile-dnsdist

dnsdist 1.8 Docker: enable h2o again, using our fork

---

Dockerfile-dnsdist

dnsdist 1.6 Docker: enable h2o again, using our fork

---

pdns/recursordist/rec-zonetocache.cc

rec: Fix Coverity 1522436 Dereference null return value

---

ext/lmdb-safe/lmdb-typed.hh
modules/geoipbackend/geoipbackend.cc
modules/geoipbackend/geoipbackend.hh
modules/lmdbbackend/lmdbbackend.cc

Cleanup some compilation warnings in geoip and lmdb.
I have:

Minor cleanups to geoip and lmdb

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/doh.cc

dnsdist: Better clang-tidy suppressions

---

pdns/dnsdistdist/docs/guides/dns-over-https.rst

fix: added missing closed bracket on line 28
I have:
- [ x] documented the code

fix: added missing closed bracket

---

m4/boost.m4

Will upstream as well
I wish the boost script would not need this...
I have:

Update boost.m4, clang 17 is out

---

docs/performance.rst

Document send-latency and receive-latency
I have:

Document send and receive latency metrics

---

pdns/dns.hh
pdns/dnscrypt.cc
pdns/dnsdist-cache.cc
pdns/dnsdist-ecs.cc
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist-xpf.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-discovery.cc
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist-secpoll.cc
pdns/dnsdistdist/dnsdist-tcp.hh
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/doq.cc
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
pdns/dnsdistdist/test-dnsdistnghttp2_cc.cc
pdns/dnsparser.cc
pdns/dnstap.cc
pdns/protozero.cc
pdns/test-dnsdistpacketcache_cc.cc

Follow up on the possible `dnsheader` alignment issue mentioned by @omoerbeek in #13280.
I have:

dnsdist: Prevent dnsheader alignment issues

---

builder-support/specs/dnsdist.spec

builder-support: Enable missing dnsdist features on Amazon 2023, unbreak dnsdist package on EL8/9

---

.github/actions/spell-check/expect.txt
docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst
pdns/dnsdistdist/docs/conf.py

dnsdist: Add ChangeLog and secpoll update for DNSdist 1.9.0-alpha3

---

pdns/recursordist/lazy_allocator.hh

(cherry picked from commit d6ff1755940d77ca502bf21a8f2d4d690252d0d2)
Backport of #13408 
I have:

rec: Backport 13408 to rec-4.9.x: Handle stack memory on NetBSD as on OpenBSD

---

pdns/dnsdistdist/docs/install.rst

fix: added missing underscore on line 63 -> * `TinyCDB <https://www.corpit.ru/mjt/tinycdb.html>`_ (optional, CDB support)
I have:
- [ x] documented the code

fix: added missing underscore

---

pdns/recursordist/settings/table.py

rec: correct webserver-loglevel docs.

---

.github/workflows/misc-dailies.yml

<strike>DO NOT MERGE THIS, the second commit should go first!</strike>
I cannot easily test this because it requires valid coverity tokens, and these are not accessible to a fork or a pull request. Given that the workflow is already broken anyway, we might want to merge this and see how it goes.
I have:

misc-dailies: Install quiche for Coverity's DNSdist analysis

---

docs/catalog.rst

Improves PR #13000.
Documentation only change.
I have:

auth doc: catalog: replace the word "draft"

---

docs/dnssec/index.rst

The previous text was not going to be finished, so replace it with friendly text
I have:

acknowledge everyone

---

docs/changelog/pre-4.0.rst
docs/dnssec/advice.rst
docs/dnssec/intro.rst

* various rst bits
* various stale link fixes (I know no one cares, but it's hard to read things, and i'm trying to make heads or tales out of stuff and failing miserably)
* step one in fixing refs to `powerdnssec.org`
I have:

Minor doc tweaks

---

pdns/recursordist/mtasker_fcontext.cc

Followup to #13430. Obvioulsy I did not compile on !amd64
I have:

rec: Followup to #13430: also define CET_ENDBR on !amd64

---

pdns/dnsdist-lua-inspection.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/configure.ac
pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-healthchecks.cc
pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist-nghttp2-in.hh
pdns/dnsdistdist/dnsdist-nghttp2.cc
pdns/dnsdistdist/test-dnsdistnghttp2-in_cc.cc
pdns/dnsdistdist/test-dnsdistnghttp2_cc.cc

dnsdist: Fix the case where nghttp2 is available but DoH is disabled

---

pdns/recursordist/syncres.cc
pdns/recursordist/test-syncres_cc10.cc

rec: Backport 13353 to rec 4.9.x:  If serving stale, wipe CNAME records from cache when we get a NODATA negative response for them

---

pdns/dnsdistdist/doh.cc
pdns/ixfrdist-stats.hh
pdns/recursordist/settings/cxxsupport.cc

Fix a few coverity warnings

---

.clang-tidy.full
pdns/dnsdistdist/test-dnsdist-dnsparser.cc
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/reczones.cc
pdns/recursordist/secpoll-recursor.cc

Assorted delinting, mark do while loops as ok

---

pdns/recursordist/test-aggressive_nsec_cc.cc

…ming differences
Backport of #13237
I have:

rec: backport 13237 to rec-4.9.x: Be even more lenient in allowing timing differences 

---

regression-tests.auth-py/requirements.txt
regression-tests.auth-py/runtests

auth-py tests: switch to pytest

---

pdns/iputils.hh
pdns/logging.hh

As documented. The way this is done is by defined a specific log function if SL is used. Could potentially be used for other cases.
I have:

rec: for structured logging always log addresses including port

---

modules/geoipbackend/geoipbackend.cc
pdns/dnsbulktest.cc
pdns/dnstcpbench.cc
pdns/ixfrdist.cc
pdns/test-dns_random_hh.cc

Folowup to #13442: clang acceptt `#pragma GCC  diagnostic`, so use that to cover both gcc as clang.
I have:

Followup to 13442: avoid some warnings

---

pdns/recursordist/settings/docs-new-preamble-in.rst

rec: duplicates in YAML vectors have setting specific effects

---

builder-support/dockerfiles/Dockerfile.recursor

rec: Install cargo for the sdist step as well now that configure expects it

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/4.9.rst

rec: Prep for rec-4.9.2

---

pdns/recursordist/settings/table.py

I have:
- [X read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document

rec: move a few settings from recursor to outgoing section

---

pdns/dnsdistdist/docs/reference/config.rst

dnsdist: Document getStatisticsCounters()

---

pdns/recursordist/rpzloader.cc

There were two thing non-optimal:
- The old zone contents is being kept in memory during a sleep for the next iteration and then thrown away. Fix: throw away before the sleep.
- The Lua config is kept alive. This causes refs to old config data to stay around until all threads have cleared that config. Fix that by making the config loop-local and load it after the sleep call.
Above claims confirmed by adding some debug code showing the ref counts
for a config with many RPZs.
I have:

rec: be more memory efficient handling RPZ updates

---

.github/actions/spell-check/expect.txt
docs/secpoll.zone
pdns/recursordist/docs/changelog/5.0.rst
pdns/recursordist/docs/upgrade.rst

Prep for rec-5.0.0-beta1
I have:

Prep for rec-5.0.0-beta1

---

pdns/recursordist/rec-tcpout.cc

rec: correctly apply outgoing.tcp_max_queries bound

---

pdns/auth-main.cc

auth: exit(0) on --version, like dnsdist and recursor do

---

pdns/dnsdist-web.cc
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/docs/guides/webserver.rst
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
regression-tests.dnsdist/test_API.py

dnsdist: Add a 'rings' endpoint to the REST API

---

pdns/dnsdist-lua-rules.cc
regression-tests.dnsdist/test_RulesActions.py

Reported by Holger Hoffstätte on the mailing-list.
I have:

dnsdist: Fix the removal of the last rule by name or UUID

---

pdns/recursordist/docs/http-api/index.rst
pdns/recursordist/docs/http-api/zone.rst

rec: provide two examples of zone manipulation in API docs

---

pdns/arguments.cc
pdns/dnsbackend.cc
pdns/dnsdist-lua.cc
pdns/ixfrdist.cc
pdns/ixfrutils.cc
pdns/misc.cc
pdns/misc.hh

Add `pdns::visit_directory()`, wrapping opendir/readdir/closedir

---

pdns/dnsdistdist/DNSDIST-MIB.txt
pdns/dnsdistdist/docs/statistics.rst

See https://github.com/PowerDNS/pdns/issues/13206
I have:

dnsdist: Clearly document that the current latency bucket is UDP only

---

pdns/recursordist/settings/docs-new-preamble-in.rst
pdns/recursordist/settings/generate.py
pdns/recursordist/settings/table.py

rec: fix a few yaml examples that still used old syntax

---

pdns/dnsdist-lua-bindings.cc
pdns/rcpgenerator.cc

Fix a few warnings from clang-tidy that were not fixed in #13513

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/configure.ac

Reported by Oto Šťáva on the mailing-list, thanks!
I have:

dnsdist: Fix building with DoQ but without DoH or DoT

---

pdns/recursordist/pdns_recursor.cc
pdns/recursordist/syncres.cc
pdns/recursordist/syncres.hh
pdns/recursordist/ws-recursor.cc
pdns/tcounters.hh

This is a pretty big beast. A few complaints remain. I marked a few functions with the "high-complexity" annotation. Not because I think we should not refactor them, but because I think that should be done in a separate PR. I did handle the more simple cases, though, as they were not very intrusive.
A changed conditions using the clang-tidy suggested substitutions, but given the recent experience with those, beware and double check (I did that as well, but it's easy to oversee something).
It also includes a few cases outside syncres.?? that were either needed (type changes) or just happened to catch my attention.
I have:

rec: tidy syncres

---

.not-formatted
pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/dolog.cc
pdns/dnsdistdist/test-dnsdistlbpolicies_cc.cc
pdns/dolog.hh
pdns/recursordist/lwres.cc
pdns/sdig.cc
pdns/test-dnscrypt_cc.cc

<strike>Still a draft until we decide on an unified "format" for auth and rec as well.</strike>
Matches the format described in https://github.com/PowerDNS/pdns/pull/13062#issuecomment-1791031178
Closes #12987.
I have:

dnsdist: Add a structured log-like logging option

---

pdns/libssl.cc

I forgot to push that one change.
I have:

Cleanup a `libssl.cc` #ifdef

---

docs/lua-records/index.rst

Also mention qtype is not a thing in Lua records.
Fixes #8443
I have:

auth: Give an example Lua record accessing qname

---

.not-formatted
pdns/backends/gsql/ssql.hh
pdns/ssqlite3.cc
pdns/ssqlite3.hh

I was looking into a build issue with meson and came across those files which are easily cleaned up.
I have:

Cleanup `ssql` and `ssqlite3`

---

tasks.py

Enable back variant `bind-dnssec-pkcs11` for auth-backend tests (`build-and-test-all` workflow)
I have:

GH Actions: enable back variant bind-dnssec-pkcs11 for auth-backend tests

---

.github/workflows/build-and-test-all.yml

We are not interested in the coverage of forks, and it is confusing since relative coverage for forks does not really make sense.
I have:

build-and-test-all: Restrict Coveralls code coverage to the main repo

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-lua.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-resolver.cc
pdns/dnsdistdist/dnsdist-resolver.hh
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/test_BackendDiscovery.py

Closes https://github.com/PowerDNS/pdns/issues/9875
I have:

dnsdist: Add `getAddressInfo()` for asynchronous DNS resolution

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/proxyprotocolutils.py
regression-tests.dnsdist/test_ProxyProtocol.py
regression-tests.dnsdist/test_TeeAction.py

Closes https://github.com/PowerDNS/pdns/issues/13038
I have:

dnsdist: Add Proxy Protocol v2 support to `TeeAction`

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdistdist/docs/reference/netmaskgroup.rst
pdns/iputils.hh
pdns/recursordist/ws-recursor.cc
regression-tests.dnsdist/test_RulesActions.py

<strike>This needs a few tests.</strike>
Closes https://github.com/PowerDNS/pdns/issues/13203
I have:

dnsdist: Add `NetmaskGroup:addNMG()` to merge Netmask groups

---

pdns/dnsdistdist/docs/statistics.rst

Fixes https://github.com/PowerDNS/pdns/issues/13526
I have:

dnsdist: Document that the `responses` metric changed in 1.8

---

docs/secpoll.zone
pdns/recursordist/docs/appendices/EOL.rst
pdns/recursordist/docs/changelog/5.0.rst
pdns/recursordist/docs/changelog/index.rst
pdns/recursordist/docs/upgrade.rst

rec: prep 5.0.0 rc1

---

.github/workflows/build-and-test-all.yml
tasks.py

auth CI: clarify that the mssql password is not a secret

---

.github/actions/spell-check/expect.txt
pdns/recursordist/Makefile.am
pdns/recursordist/rec-main.cc
pdns/recursordist/settings/generate.py
pdns/recursordist/settings/rust/Makefile.am
pdns/recursordist/settings/table.py

A few cases were lost with the new settings code.
<strike>I did not verify the RUNTIME_DIRECTORY change with systemd yet.</strike>
I have:

Rec: correct defaults of various dirs

---

pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc

dnsdist: Add Lua FFI bindings: hashing arbitrary data and knowing if the query was received over IPv6

---

pdns/dns.hh
pdns/dnsparser.cc

Small cleanup of `DNSResourceRecord`
I have:

Small cleanup of `DNSResourceRecord`

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst
pdns/dnsdistdist/docs/conf.py
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/docs/upgrade_guide.rst

dnsdist: ChangeLog and secpoll update for 1.9.0-alpha4

---

pdns/recursordist/Makefile.am

rec: Always set the two new vars in the Makefile, followup to 13588

---

pdns/dnsdist-lua.cc
pdns/dnsdist-web.cc
pdns/dnsdistdist/dnsdist-dynblocks.cc
pdns/dnsdistdist/docs/advanced/ebpf.rst
pdns/dnsdistdist/docs/guides/dynblocks.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/ebpf.rst
pdns/dnsdistdist/html/local.js

Backport of #13310 to rel/dnsdist-1.8.x
I have:

dnsdist-1.8.x: Fix several cosmetic issues in eBPF dynamic blocks, update documentation

---

pdns/ixfrdist.cc

auth-4.8: ixfrdist: Fix the validation of 'max-soa-refresh'

---

pdns/recursordist/rec-main.cc
pdns/recursordist/settings/table.py

rec: Disabling structured logging is deprecated

---

pdns/recursordist/rec-main.cc
pdns/recursordist/settings/table.py

(cherry picked from commit 6362c4df2bac887ba5e3d4e630186f8709b6e3f3)
Backport of #13567
I have:

rec: Backport 13567 to rec-5.0.x: Disabling structured logging is deprecated

---

Docker-README.md
Dockerfile-auth

auth-4.8: Add supervisor to Auth container image

---

pdns/dnsdist-console.cc
pdns/dnsdistdist/docs/guides/dns-over-http3.rst
pdns/dnsdistdist/docs/guides/dns-over-https.rst
pdns/dnsdistdist/docs/reference/config.rst

Fixes https://github.com/PowerDNS/pdns/issues/13640
I have:

dnsdist: Document `showDOH3Frontends`, how to advertise HTTP/3 support over HTTP/2

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/5.0.rst
pdns/recursordist/docs/upgrade.rst

Rec: prep 5.0.0 rc2

---

docs/changelog/4.8.rst
docs/secpoll.zone

auth-4.8.4: secpoll&docs

---

docs/settings.rst

Clarify `allow-notify-from` documentation (based on discussion on irc). 
I have:

clarify `allow-notify-from` docs

---

pdns/ws-auth.cc

This replaces the use of macros and the spurious use of `NOLINT` in `ws-auth.cc`.
- The last 3 commits are the relevant ones
- Only merge this after #13613 
I have:

Fix macros and `NOLINT`s in `ws-auth.cc`

---

tasks.py

Based on the OpenSSF compiler options hardening guide for C and C++: https://best.openssf.org/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++
I have:

CI: Enable more compiler hardening options during our CI run

---

pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

rec: Backport 13675 to rec 5.0.x: Fix documentation building error for dnsdist and recursor

---

docs/secpoll.zone
pdns/recursordist/docs/appendices/EOL.rst
pdns/recursordist/docs/changelog/5.0.rst

rec: Prepare for rec-5.0.1 final release

---

pdns/iputils.cc

iputils: avoid unused warnings on !linux

---

pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

Backport 13675 to rec 4.9.x: Fix documentation building error for dnsdist and recursor

---

pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

Backport 13675 to rec 4.8.x: Fix documentation building error for dnsdist and recursor

---

.github/scripts/clang-tidy.py
.github/scripts/git-filter.py

Nothing special, some delinting and formatting.
I have:

Small cleanups of the Github clang-tidy helper scripts

---

.not-formatted
pdns/Makefile.am
pdns/dnspacket.cc
pdns/dnspacket.hh
pdns/dnsproxy.cc
pdns/dnsproxy.hh
pdns/ednssubnet.cc
pdns/ednssubnet.hh
pdns/iputils.hh
pdns/stubresolver.cc
pdns/stubresolver.hh
regression-tests.auth-py/clientsubnetoption.py
regression-tests.auth-py/test_ALIAS.py

auth: forward EDNS Client Subnet option during ALIAS processing

---

docs/changelog/4.9.rst
docs/changelog/index.rst
docs/secpoll.zone

docs&secpoll for auth-4.9.0-alpha1

---

pdns/dnsdist-snmp.cc
pdns/recursordist/rec-snmp.cc
pdns/snmp-agent.cc
pdns/snmp-agent.hh

Touches a small part of dnsdist as well
I have:

rec: Cleanup of code doing SNMP OID handling

---

ext/yahttp/yahttp/router.hpp
pdns/recursordist/rec-main.cc
pdns/recursordist/syncres.cc

All performance inefficiencies, all Low impact.
I have:

Fix a few coverity reports

---

.github/workflows/codeql-analysis.yml
builder-support/dockerfiles/Dockerfile.target.debian-trixie

pdns-builder: update to newest, removes fakeroot usage

---

pdns/axfr-retriever.cc
pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/syncres.cc

rec should be coverity clean after this
I have:

rec: coverity 20240116

---

docs/upgrading.rst

auth docs: add note about EL9 and SHA1

---

pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

best reviewed per commit
I have:

auth LUA createForward: allow non-hex word prefix

---

pdns/dnsdist-lua-actions.cc
pdns/dnstap.cc

dnsdist, rec: Fix missed optimizations reported by Coverity

---

pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

Backport 13675 to dnsdist 1.7.x: Fix documentation building error for dnsdist and recursor

---

pdns/backends/gsql/gsqlbackend.cc

getAllDomains catalog: avoid useless copy

---

pdns/recursordist/rec_control.cc
regression-tests.recursor/YAMLConversion/expected_result

It's not an error message. So I'd go for STDOUT in this case.
I have:

STDOUT instead of STDERR. Probably a typo.

---

pdns/logger.hh
pdns/recursordist/syncres.cc

rec: use ref wrapper instead of raw pointer in variant

---

.not-formatted
pdns/digests.hh
pdns/dnssecsigner.cc
pdns/pkcs11signers.cc
pdns/sha.hh
pdns/test-digests_hh.cc
pdns/test-sha_hh.cc

Cleanup `sha.hh` and `digests.hh`
I have:

Cleanup `sha.hh` and `digests.hh`

---

.not-formatted
pdns/dnsbackend.cc
pdns/dnsbackend.hh

Cleanup & format `dnsbackend.cc/.hh`
I have:

Cleanup & format `dnsbackend.cc/.hh`

---

pdns/recursordist/docs/lua-config/rpz.rst
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-lua-conf.cc
pdns/recursordist/rec-lua-conf.hh
pdns/recursordist/rpzloader.cc
pdns/recursordist/rpzloader.hh
pdns/recursordist/settings/table.py
regression-tests.recursor-dnssec/test_RPZ.py

This refactors the RPZ load via IXFR thread code and allows processing of notifies, causing the RPZ code to immediately initiate an IXFR.
Fixes #12777 (for the RPZ part)
I have:

rec: RPZ from primary refactor and allow notifies for RPZs

---

builder-support/helpers/install_quiche.sh
tasks.py

This fixes CVE-2023-6193, in addition to smaller fixes.
I have:

dnsdist: Update Quiche to 0.20.0

---

pdns/dnsdistdist/docs/rules-actions.rst

Try to link to existing documentation to make it easier to work out how to work with DNSNameSets (without grepping through the git repo). I'm not sure if this works, but feel free to point me in a better direction.
I have:

Link to existing documentation for DNSNameSet.

---

pdns/recursordist/rec-lua-conf.cc
pdns/recursordist/rpzloader.cc

Coverity issues 1533681..1533686, all low impact perf related
I have:

rec: fix Coverity issues in new RPZ code

---

builder-support/helpers/install_rust.sh
pdns/recursordist/settings/rust/Cargo.lock

rec: update to cargo 1.75 and updated Cargo dependencies

---

.github/actions/spell-check/expect.txt
docs/lua-records/functions.rst
pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

auth LUA: add dblookup function

---

.github/workflows/build-and-test-all.yml
regression-tests.dnsdist/dnsdistDynBlockTests.py
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_DynBlocksEBPF.py
tasks.py

Fixes https://github.com/PowerDNS/pdns/issues/11581
I have tested this locally but I'm pretty sure I forgot something that will fail on our CI, let's see :)
I have:

dnsdist: Add regression tests for eBPF blocks (static / dynamic)

---

pdns/bpf-filter.cc

CID 414570 and CID 414569 (Uninitialized variables) are false positives as far as I can tell, the variables are properly set by the call to `bpf_get_next_key`, but let's zero-initialize them anyway, while delinting the code.
I have:

dnsdist: Fix a warning reported by Coverity

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-lua-hooks.cc
pdns/dnsdistdist/dnsdist-lua-hooks.hh
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/test_DNSCrypt.py

Having a hook that can accept multiple callbacks makes it a lot easier to manage the execution of several, independant tasks that needs to be called regularly.
I have:

dnsdist: Add a Lua maintenance hook

---

pdns/dnsdistdist/docs/advanced/xsk.rst

Reported by Chris Hofstaedtler (thanks!).
Also document the limitations of our implementation.
I have:

dnsdist: Fix typos in the AF_XDP documentation 

---

pdns/dnsdistdist/doh3.cc
pdns/dnsdistdist/doq.cc

dnsdist: Fix a missing explicit atomic load of the Quiche configuration

---

pdns/recursordist/settings/docs-new-preamble-in.rst

Fix #13777 documentation typo
I have:

fix(doc): incorrect setting `query_local_address`

---

pdns/pdns_recursor.cc
pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/aggressive_nsec.hh
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-zonetocache.cc
pdns/recursordist/test-aggressive_nsec_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc5.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/validate.cc
pdns/validate.hh
regression-tests.recursor-dnssec/test_AggressiveNSECCache.py

rec: Backport Keytrap to rec-4.8.x

---

pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/aggressive_nsec.hh
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-zonetocache.cc
pdns/recursordist/settings/table.py
pdns/recursordist/syncres.cc
pdns/recursordist/syncres.hh
pdns/recursordist/test-aggressive_nsec_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc5.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/validate.cc
pdns/validate.hh
regression-tests.recursor-dnssec/test_AggressiveNSECCache.py

rec: CVE-2023-50387 and CVE-2023-50868

---

regression-tests.recursor-dnssec/test_ExtendedErrors.py

rec: skip a few tests that depend on sidnlab's public test setup that no longer works

---

pdns/recursordist/rec-zonetocache.cc
pdns/zonemd.cc
pdns/zonemd.hh
regression-tests.recursor-dnssec/test_ZTC.py

rec: fix the zoneToCache regression introduced by SA 2024-01

---

docs/manpages/ixfrdist.yml.5.rst
pdns/Makefile.am
pdns/communicator.hh
pdns/ixfrdist.cc
pdns/ixfrdist.example.yml
regression-tests.ixfrdist/ixfrdisttests.py
regression-tests.ixfrdist/test_IXFR.py
regression-tests.ixfrdist/test_Stats.py

ixfrdist: add support for outgoing notify

---

pdns/ixfrdist.cc

Better check socket return values and warn about trying to notify a v6 remote while there is no v6 support.
Fix coverity CID 1534483
I have:

ixfrist: fix coverity report 1534483

---

docs/backends/lmdb.rst
docs/upgrading.rst
modules/lmdbbackend/lmdbbackend.cc

lmdb: remove mapasync mode, it was always a lie

---

pdns/ixfrdist.cc

ixfrdist: fix Coverity 1534661 and 1534662

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst

dnsdist: ChangeLog and secpoll update for 1.9.0 final!

---

pdns/dnsdistdist/docs/eol.rst

This PR aligns DNSdist support/EOL statements with the Authoritative and Recursor ones.
I have:

dnsdist: Update the EOL statements

---

.github/actions/spell-check/expect.txt
docs/changelog/4.9.rst
docs/secpoll.zone

auth 4.9.0-beta2: docs&secpoll

---

pdns/recursordist/docs/security-advisories/powerdns-advisory-2024-01.rst

rec: add thanks to Petr Spacek to SA 2024-01

---

regression-tests.recursor-dnssec/test_ServerNames.py

rec: dnspython's API changed wrt NSID, apply (version dependent) fix in regression test

---

pdns/recursordist/test-aggressive_nsec_cc.cc
pdns/recursordist/test-syncres_cc4.cc
regression-tests.recursor-dnssec/test_ExtendedErrors.py
regression-tests.recursor-dnssec/test_ServerNames.py

rec-4.8.x: fix unit and regression tests, mostly due to python changes

---

pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/test-aggressive_nsec_cc.cc

rec: Backport 13543 to rec 4.9.x: a single NSEC3 record covering everything is a special case 

---

pdns/recursordist/rec-zonetocache.cc
pdns/zonemd.cc
pdns/zonemd.hh
regression-tests.recursor-dnssec/test_ZTC.py

rec: Backport 13788 to rec-4.9.x: fix the zoneToCache regression introduced by SA 2024-01 

---

pdns/recursordist/syncres.cc
pdns/recursordist/test-syncres_cc3.cc

rec: Backport 13847 to rec 4.9.x: Fix gathering of denial of existence proof for wildcard-expanded names 

---

pdns/recursordist/syncres.cc
pdns/recursordist/test-syncres_cc3.cc

rec: Backport 13847 to rec-5.0.x: Fix gathering of denial of existence proof for wildcard-expanded names

---

.github/workflows/builder.yml
builder-support/dockerfiles/Dockerfile.target.ubuntu-noble
builder-support/dockerfiles/Dockerfile.target.ubuntu-noble-amd64
builder-support/dockerfiles/Dockerfile.target.ubuntu-noble-arm64

rec: Backport 13580 to rec 5.0.x: add ubuntu-noble build target and test it daily

---

pdns/recursordist/rec-main.cc

Partial backport of #13830 
I have:

rec: Backport 13830 to rec 5.0.x: reduce RPZ memory usage

---

pdns/recursordist/pdns_recursor.cc
pdns/recursordist/syncres.hh
pdns/validate.cc
pdns/validate.hh

(cherry picked from commit 9d4a01ffa2b724907e07db423da048f68f15eca2)
Backport of #13824 
I have:

rec: Backport 13824 to rec-5.0.x: log if a dnssec related limit was hit (if log_bogus is set)

---

pdns/recursordist/rec-zonetocache.cc
pdns/zonemd.cc
pdns/zonemd.hh
regression-tests.recursor-dnssec/test_ZTC.py

rec: Backport 13788 to rec 4.8.x: fix the zoneToCache regression introduced by SA 2024-01 

---

pdns/dnsdistdist/docs/upgrade_guide.rst

Reported by Martin Frausing (many thanks!).
I have:

dnsdist: Fix HTTP/1 -> HTTP/2 mistake in the upgrade notes

---

pdns/recursordist/rpzloader.cc
pdns/recursordist/rpzloader.hh

rec: tidy rpzloader.cc and .hh

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/4.8.rst
pdns/recursordist/docs/changelog/4.9.rst
pdns/recursordist/docs/changelog/5.0.rst
pdns/recursordist/docs/upgrade.rst

rec: prep for 5.0.3, 4.9.4 and 4.8.7

---

pdns/fstrm_logger.cc
pdns/fstrm_logger.hh

Support v6 in FrameStreamLogger, including tidy

---

builder-support/debian/authoritative/debian-buster/pdns-backend-bind.postinst

auth debian: adjust option name in shipped postinst

---

docs/lua-records/functions.rst
pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

as suggested in https://github.com/PowerDNS/pdns/issues/12358#issuecomment-1974255190
I have:

auth LUA dblookup: switch qtype argument to int

---

docs/lua-records/functions.rst
pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

auth LUA: support returning empty set in filterForward

---

pdns/validate.cc
pdns/validate.hh

validate: Remove unused `harvestCSPFromRecs()`

---

builder-support/helpers/install_quiche.sh
tasks.py

dnsdist: update to quiche 0.20.1

---

.github/workflows/build-and-test-all.yml

(cherry picked from commit e0bf314e472d0c1d4bc1ff82d97cabf87be1e929)
Backport of #13907 
I have:

dnsdist: backport 13907 to 1.9.x: gh actions: wo issue 9491 - actions/runner-images

---

.github/workflows/build-and-test-all.yml

backport of #13907. Revert when the upstream issue is resolved.
I have:

auth 4.9: gh actions: wo issue 9491 - actions/runner-images

---

builder-support/helpers/install_quiche.sh
tasks.py

dnsdist: Backport 13909 to dnsdist 1.9.x: update to quiche 0.20.1

---

pdns/recursordist/lua-recursor4.cc
pdns/recursordist/lua-recursor4.hh
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-tcp.cc

First commit is "mechanical" stuff, 2nd and 3rd more interesting. Especially the elimination of the `goto` should be carefully reviewed. Last commit is reformat only.
I have:

rec: tidy recursor-lua4.cc and recursor-lua4.hh

---

docs/lua-records/functions.rst
pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

auth 4.9 LUA: support returning empty set in filterForward #13879

---

pdns/auth-catalogzone.cc

auth 4.9: catalog, include groups in hash calculation

---

Docker-README.md
dockerdata/startup.py

auth 4.9 Docker: Only print config if debug flag is set

---

modules/remotebackend/test-remotebackend.cc
modules/remotebackend/testrunner.sh
modules/remotebackend/unittest.rb
modules/remotebackend/unittest_pipe.rb
modules/remotebackend/unittest_zeromq.rb
modules/remotebackend/unixconnector.cc

auth 4.9: revive remotebackend tests and fix failures

---

docs/lua-records/functions.rst
pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

auth 4.9 LUA dblookup: switch qtype argument to int

---

.dockerignore

.dockerignore: adjust for https://github.com/docker/buildx/issues/850

---

.dockerignore

auth-4.9 .dockerignore: adjust for https://github.com/docker/buildx/issues/850

---

pdns/recursordist/syncres.cc

All other calls to doThrottle are protected properly except this one. Little refactoring while there.
I have:

rec: don't throttle lame servers if they are marked as dontThrottle

---

docs/manpages/sdig.1.rst
pdns/sdig.cc

sdig: remove xpf handling

---

builder-support/debian/authoritative/debian-buster/pdns-backend-bind.postinst

auth 4.9 debian: adjust option name in shipped postinst

---

m4/boost.m4

Sad we have to maintain this.
I have:

Add a bunch of new compiler versions to the compiler list used by boost.m4

---

pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/test-dnsdistbackend_cc.cc

Needs more testing!
Fixes https://github.com/PowerDNS/pdns/issues/13837
I have:

dnsdist: Properly handle a failure of the first lazy health-check

---

Docker-README.md
dockerdata/startup.py

dnsdist-1.9.x: Backport of #13849 - Docker: Only print config if debug flag is set

---

pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/test-dnsdistbackend_cc.cc

Backport of #13834 to 1.9.x
I have:

dnsdist-1.9.x: Backport of 13834 - dnsdist: Properly handle a failure of the first lazy health-check

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

* Link to GitHub Discussions Q&A category
* Treat descriptions as sentences
I have:

Improve issue template options

---

modules/gmysqlbackend/gmysqlbackend.cc
modules/gmysqlbackend/smysql.cc
modules/gmysqlbackend/smysql.hh

after #13060 I noticed a compiler warning, so I have now shaved the entire yak
.. unless I have now invoked the wrath of clang-tidy
I have:

auth smysql: remove unused var

---

.github/actions/spell-check/expect.txt
pdns/recursordist/docs/appendices/structuredlogging.rst
pdns/recursordist/rec-main.cc
pdns/recursordist/settings/table.py

rec: add structured logging backend that uses JSON representation

---

.github/workflows/build-and-test-all-releases-dispatch.yml
.github/workflows/builder-releases-dispatch.yml

add auth-4.9.x and dnsdist-1.9.x to daily build test

---

pdns/dnsdistdist/docs/guides/dynblocks.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/upgrade_guide.rst

And the effects it has on Dynamic Blocks.
I have:

dnsdist: Document that cache hits go into the ring buffer since 1.8.0

---

docs/dnsupdate.rst

Fix Dynamic DNS docs to include the fact that GSS-TSIG is now supported.
I have:

Update Dynamic DNS Update Docs with GSS-TSIG

---

pdns/recursordist/docs/lua-scripting/netmask.rst

rec: fix netmask docs wrt deprecatd isIpX() functions

---

pdns/logging.hh
pdns/recursordist/docs/upgrade.rst
pdns/recursordist/logging.cc
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec_control.cc
pdns/recursordist/rpzloader.cc
pdns/recursordist/settings/table.py
regression-tests.recursor/YAMLConversion/expected_result

rec: remove the possiblility to disable structured logging

---

pdns/recursordist/rec-system-resolve.cc

rec: fixup res-system-resolve.cc on FreeBSD: resolve.h needs netinet/in.h

---

builder-support/dockerfiles/Dockerfile.rpmsbom
builder-support/dockerfiles/Dockerfile.rpmtest
builder-support/dockerfiles/Dockerfile.target.amazon-2
builder-support/dockerfiles/Dockerfile.target.amazon-2023
builder-support/dockerfiles/Dockerfile.target.centos-7
builder-support/dockerfiles/Dockerfile.target.centos-8
builder-support/dockerfiles/Dockerfile.target.centos-9-stream
builder-support/dockerfiles/Dockerfile.target.el-9
builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
builder-support/helpers/generate-sbom-dnf.py

This PR adds a few steps to the RPM Docker files:
- `Dockerfile.rpmtest` installs the generate packages on the base image
- `Dockerfile.rpmsbom` generates a SBOM in [CycloneDX](https://cyclonedx.org/) format for the installed packages
I'm skipping EL-7 packages because EL-7 will be EOL soon, and `python2-dnf` was adding a lot of complexity.
I'm attaching some generated SBOMs as an example:
[dnsdist-1.9.0-alpha0.2486.generatesbom.gfef1b1c63-el-9.cyclonedx.json](https://github.com/PowerDNS/pdns/files/14757168/dnsdist-1.9.0-alpha0.2486.generatesbom.gfef1b1c63-el-9.cyclonedx.json)
[pdns-tools-4.8.0-beta1.2338.generatesbom.gfef1b1c63-el-9.cyclonedx.json](https://github.com/PowerDNS/pdns/files/14757169/pdns-tools-4.8.0-beta1.2338.generatesbom.gfef1b1c63-el-9.cyclonedx.json) …

Generate Software Bill Of Materials (SBOMs) for our RPM packages

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/test-dnsdistnghttp2-in_cc.cc

When an incoming DoH connection using the `nghttp2` provider is waiting for a response from a backend that results in a I/O error or timeout, and the incoming connection also fails due to a I/O error or timeout, dnsdist could in some cases try to dereference a null pointer, leading to a crash.
I have:

dnsdist: Fix a null-deref in incoming DoH w/ nghttp2

---

Docker-README.md
dockerdata/startup.py

rec: Backport 13849 to rec 5.0.x: Only print Docker config if debug flag is set 

---

pdns/recursordist/pdns_recursor.cc
regression-tests.recursor-dnssec/test_TraceFail.py
regression-tests.recursor-dnssec/test_ZTC.py

rec: Backport 13926 to rec 5.0.x: fix trace=fail regression and add regression test for it

---

Docker-README.md
dockerdata/startup.py

rec: Backport 13849 to rec 4.9.x: Only print Docker config if debug flag is set 

---

pdns/recursordist/pdns_recursor.cc
regression-tests.recursor-dnssec/test_TraceFail.py
regression-tests.recursor-dnssec/test_ZTC.py

rec: Backport 13926 to rec 4.9.x: fix trace=fail regression and add regression test for it

---

pdns/recursordist/docs/appendices/compiling.rst

rec: mention rust compiler in compiling docs

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/test-dnsdistnghttp2-in_cc.cc

Backport of #14003 to rel/dnsdist-1.9.x.
When an incoming DoH connection using the `nghttp2` provider is waiting for a response from a backend that results in a I/O error or timeout, and the incoming connection also fails due to a I/O error or timeout, dnsdist could in some cases try to dereference a null pointer, leading to a crash.
I have:

dnsdist-1.9.x: Backport 14003 - Fix a null-deref in incoming DoH w/ nghttp2

---

docs/appendices/backend-writers-guide.rst
modules/bindbackend/bindbackend2.cc
modules/geoipbackend/geoipbackend.cc
modules/gmysqlbackend/gmysqlbackend.cc
modules/godbcbackend/godbcbackend.cc
modules/gpgsqlbackend/gpgsqlbackend.cc
modules/gsqlite3backend/gsqlite3backend.cc
modules/ldapbackend/ldapbackend.cc
modules/lmdbbackend/lmdbbackend.cc
modules/lua2backend/lua2backend.cc
modules/pipebackend/pipebackend.cc
modules/remotebackend/remotebackend.cc
modules/tinydnsbackend/tinydnsbackend.cc
pdns/dnsbackend.cc
pdns/dnsbackend.hh
pdns/test-ueberbackend_cc.cc

This does not fix any issue but clarifies the ownership and lifetime of the backend factories, while ensuring they are properly destroyed when the program exits.
I have:

auth: Wrap backend factories in smart pointers

---

pdns/recursordist/settings/table.py

Noted when reading #14022 
I have:

rec docs: we do not have a query cache

---

pdns/dnsdistdist/docs/guides/console.rst

dnsdist: Document how to generate a console key without dnsdist

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst

dnsdist: Update ChangeLog and secpoll for DNSdist 1.9.2

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst

dnsdist: Update secpoll and ChangeLog for 1.9.3

---

builder-support/specs/dnsdist.spec
builder-support/specs/pdns-recursor.spec

https://github.com/PowerDNS/pdns/pull/13772 but for dnsdist and the recursor.
I have:

dnsdist/rec: Change home directory to /var/lib/<product> on EL-based OSs

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/4.8.rst
pdns/recursordist/docs/changelog/4.9.rst
pdns/recursordist/docs/changelog/5.0.rst
pdns/recursordist/docs/security-advisories/powerdns-advisory-2024-02.rst

security advisory 2024-02+changelogs+secpoll

---

pdns/recursordist/syncres.cc
pdns/recursordist/test-syncres_cc1.cc

for security advisory 2024-02
I have:

rec: a name can be present already when building the cname chain

---

pdns/recursordist/docs/security-advisories/powerdns-advisory-2024-02.rst

security advisory 2024-02: fix formatting

---

pdns/recursordist/docs/lua-config/proxymapping.rst
pdns/recursordist/docs/lua-scripting/dq.rst
pdns/recursordist/lua-recursor4-ffi.hh
pdns/recursordist/lua-recursor4.cc
pdns/recursordist/lua-recursor4.hh
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-tcp.cc
regression-tests.recursor-dnssec/test_ProxyProtocol.py

rec: add interface (not subject to proxy protocol substitutions) addresses in Lua DNSQuestion and corresponding FFI

---

builder-support/dockerfiles/Dockerfile.rpmsbom
builder-support/dockerfiles/Dockerfile.rpmtest
builder-support/dockerfiles/Dockerfile.target.amazon-2
builder-support/dockerfiles/Dockerfile.target.amazon-2023
builder-support/dockerfiles/Dockerfile.target.centos-7
builder-support/dockerfiles/Dockerfile.target.centos-8
builder-support/dockerfiles/Dockerfile.target.centos-9-stream
builder-support/dockerfiles/Dockerfile.target.el-9
builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
builder-support/helpers/generate-sbom-dnf.py

Backport of #13983 to rel/dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 13983 - Generate Software Bill Of Materials (SBOMs) for our RPM packages

---

pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/doh3.cc
pdns/dnsdistdist/doq-common.cc
pdns/dnsdistdist/doq-common.hh
pdns/dnsdistdist/doq.cc
pdns/iputils.cc
pdns/iputils.hh
regression-tests.dnsdist/quictests.py
regression-tests.dnsdist/test_DOH3.py
regression-tests.dnsdist/test_DOQ.py

And expose the correct destination IP to Lua.
I have:

dnsdist: Use the correct source IP for outgoing QUIC datagrams

---

builder-support/dockerfiles/Dockerfile.target.debian-trixie
pdns/recursordist/syncres.cc
pdns/recursordist/test-syncres_cc1.cc

merge rec-5.0.4 back onto rel/rec-5.0.x

---

.github/workflows/build-and-test-all-releases-dispatch.yml
.github/workflows/build-and-test-all.yml

backport of #14061, minus dnsdist/rec bits, plus change the tag in build-and-test-all
I have:

auth-4.9.x: GH actions - build-and-test-all: parameterize workflow to run different docker runner versions

---

.github/workflows/build-and-test-all.yml

backport of #14044 for the removal of snap dependencies
I have:

auth: Backport 14044 to auth-4.9.x: gh actions - replace yq snap in collect job build-and-test-all

---

docs/dnssec/intro.rst

Fixes typo mentioned in #14135, which is in the DNSSEC intro documentation.
I have:

Updated typo in DNSSEC intro documentation (ECSDA instead of ECDSA)

---

pdns/recursordist/settings/docs-new-preamble-in.rst
pdns/recursordist/settings/table.py

rec: fix two doc examples missing a colon

---

.not-formatted
pdns/iputils.cc
pdns/iputils.hh

Especially the "extra tricky" commit needs extra review attention.
Not terribly happy about the NOLINT markers, but no way to work around that without a major overhaul, and even then  not all of them can be avoided, as we are calling into APIs that use old-school C idiom.
I have:

Tidy iputils.hh and iputils.cc

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist-tcp-upstream.hh
pdns/dnsdistdist/dnsdist-tcp.cc

dnsdist: Log the correct amount of bytes sent for DoH w/ nghttp2

---

.github/workflows/build-and-test-all.yml

(cherry picked from commit 3a5fb2cb7e890e1ebb0e0e75f6349640fc76f878)
Backport of #14044
I have:

rec: backport 14044 to rec-5.0.x: gh actions - replace yq snap in collect job build-and-test-all

---

.github/workflows/build-and-test-all.yml

(cherry picked from commit 3a5fb2cb7e890e1ebb0e0e75f6349640fc76f878)
Backport of #14044
I have:

rec: Backport 14044 to rec-4.9.x: gh actions - replace yq snap in collect job build-and-test-all

---

.github/workflows/build-and-test-all.yml

(cherry picked from commit 3a5fb2cb7e890e1ebb0e0e75f6349640fc76f878)
Backport of #14044
I have:

rec: Backport 14044 to rec-4.8.x: gh actions - replace yq snap in collect job build-and-test-all

---

pdns/iputils.cc

rec: followup to 14097: missed OpenBSD specfic case

---

builder-support/helpers/quiche.json

dnsdist: Update Quiche to 0.21.0

---

pdns/recursordist/docs/security-advisories/powerdns-advisory-2024-02.rst

I had to reread that line at least once, this makes it easier to grok.
I have:

[trivial] improve readability of the list of affected versions in advisory-2024-02

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist-nghttp2-in.hh
pdns/dnsdistdist/dnsdist-tcp-upstream.hh
pdns/dnsdistdist/dnsdist-tcp.cc

They were always replaced by the correct HTTP/2 ones anyway, but it's a lot cleaner that way.
I have:

dnsdist: Fix TCP I/O timeout and callback being used for HTTP/2

---

docs/modes-of-operation.rst

auth docs: update primary/secondary terminology

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst
pdns/dnsdistdist/docs/security-advisories/powerdns-advisory-for-dnsdist-2024-03.rst

dnsdist: Update the secpoll zone and the ChangeLog for 1.9.4

---

docs/dnsupdate.rst
docs/settings.rst

auth docs, clarify that dnsupdate-require-tsig is new in 5.0

---

pdns/recursordist/settings/table.py

rec: mention subnets are not allowed (yet) in query-local-address/outgoing.source_address

---

.github/workflows/build-and-test-all.yml

backport of #14044 for the removal of snap dependencies
I have:

dnsdist: Backport 14044 to dnsdist-1.9.x: gh actions - replace yq snap in collect job build-and-test-all

---

pdns/dnsdistdist/docs/security-advisories/powerdns-advisory-for-dnsdist-2024-03.rst

Add a newline so that the list of workarounds actually becomes a list.
I have:

Fix formatting of PowerDNS SA 2024-03

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/4.8.rst
pdns/recursordist/docs/changelog/4.9.rst
pdns/recursordist/docs/changelog/5.0.rst
pdns/recursordist/docs/upgrade.rst

rec: prep for 20240514 releases

---

pdns/auth-primarycommunicator.cc
pdns/backends/gsql/gsqlbackend.cc

Partial backport of #14057
I have:

Auth-4.9.x: Partial backport of #14057

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/5.1.rst
pdns/recursordist/docs/changelog/index.rst
pdns/recursordist/docs/upgrade.rst

rec: prep rec-5.1.0-alpha1

---

contrib/ProtobufLogger.py
pdns/recursordist/docs/lua-config/protobuf.rst
pdns/recursordist/rec-protozero.cc

In particular, this adds HTTPS, SVCB and NAPTR.
I have:

rec: extra export types for protobuf messages

---

.github/workflows/build-and-test-all.yml

Fix a typo (autotools) in `build-and-test-all.yml` as reported by @omoerbeek (thanks!)
I have:

GH Actions: Fix a typo in build-and-test-all.yml

---

pdns/ueberbackend.cc

Clang-tidy lint cleanups for `UeberBackend`
I have:

`UeberBackend` cleanups

---

pdns/dnsdistdist/test-dnsdist_cc.cc

dnsdist: Fix a warning when compiling the unit tests without XSK

---

pdns/dnsbackend.cc
pdns/ueberbackend.cc

Helpful when looking into loading backend module files.
I have:

Auth: Add debug logging to `UeberBackend` and `BackendMakerClass`

---

.github/workflows/build-and-test-all.yml

auth 4.9: always pull runner image from powerdns for forks

---

builder-support/dockerfiles/Dockerfile.rpmsbom
builder-support/dockerfiles/Dockerfile.rpmtest
builder-support/dockerfiles/Dockerfile.target.amazon-2
builder-support/dockerfiles/Dockerfile.target.amazon-2023
builder-support/dockerfiles/Dockerfile.target.centos-7
builder-support/dockerfiles/Dockerfile.target.centos-8
builder-support/dockerfiles/Dockerfile.target.centos-9-stream
builder-support/dockerfiles/Dockerfile.target.el-9
builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
builder-support/helpers/generate-sbom-dnf.py

backport of #13983 + #13998
I have:

auth 4.9: Generate Software Bill Of Materials (SBOMs) for our RPM packages

---

docs/appendices/backend-writers-guide.rst
modules/bindbackend/bindbackend2.cc
modules/geoipbackend/geoipbackend.cc
modules/gmysqlbackend/gmysqlbackend.cc
modules/godbcbackend/godbcbackend.cc
modules/gpgsqlbackend/gpgsqlbackend.cc
modules/gsqlite3backend/gsqlite3backend.cc
modules/ldapbackend/ldapbackend.cc
modules/lmdbbackend/lmdbbackend.cc
modules/lua2backend/lua2backend.cc
modules/pipebackend/pipebackend.cc
modules/remotebackend/remotebackend.cc
modules/tinydnsbackend/tinydnsbackend.cc
pdns/dnsbackend.cc
pdns/dnsbackend.hh
pdns/test-ueberbackend_cc.cc

auth 4.9: Wrap backend factories in smart pointers

---

pdns/pkcs11signers.cc

auth-4.9: Properly finalize PKCS11 modules before releasing them

---

pdns/dnsdist-web.cc

Backport of #14167 to dnsdist-1.9.x.
The `registerWebHandler()` Lua method can be used to tie a custom Lua function to an HTTP endpoint. This function was clearly not intended to be used at runtime but this was never enforced, so let's prevent a race condition by wrapping the internal web handlers map in a lock.
I have:

dnsdist-1.9.x: Backport of 14167 - Prevent a race when calling `registerWebHandler` at runtime

---

pdns/dnsproxy.cc

auth 4.9 dnsproxy: fix build on s390x

---

docs/manpages/sdig.1.rst

sdig.1: format example commands better

---

.github/workflows/build-and-test-all.yml

I successfully tested this locally, let's see how it goes on CI.
I have:

auth: Enable LeakSanitizer while running the unit tests in CI

---

Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor

Test run: [https://github.com/romeroalx/pdns/actions/runs/9172321677](https://github.com/romeroalx/pdns/actions/runs/9172321677)
I have:

dnsdist-1.7.x: Partial backport of #14171 for fixing the build of arm64 images

---

pdns/test-distributor_hh.cc

auth: Fix a memory leak report in the distributor unit tests

---

pdns/devpollmplexer.cc
pdns/epollmplexer.cc
pdns/kqueuemplexer.cc
pdns/mplexer.hh
pdns/pollmplexer.cc
pdns/portsmplexer.cc
pdns/recursordist/Makefile.am
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/ratelimitedlog.hh
pdns/recursordist/rec-main.cc

rec: Backport 14185 to rec 5.0.x: report error and adjust when linux map limit is too low 

---

modules/remotebackend/test-remotebackend-http.cc
modules/remotebackend/test-remotebackend-json.cc
modules/remotebackend/test-remotebackend-pipe.cc
modules/remotebackend/test-remotebackend-post.cc
modules/remotebackend/test-remotebackend-unix.cc
modules/remotebackend/test-remotebackend-zeromq.cc

auth-4.9: Use smart pointers in the remote backend unit tests

---

pdns/test-distributor_hh.cc

auth-4.9: Fix a memory leak report in the distributor unit tests

---

.github/workflows/build-and-test-all.yml

backport of #14200. Might need #14228 and #14231
I have:

auth-4.9: Enable LeakSanitizer while running the unit tests in CI

---

pdns/recursordist/docs/lua-scripting/dq.rst
pdns/recursordist/docs/lua-scripting/hooks.rst

rec: improve docs on gettag() and gettag_ffi()

---

pdns/ixfrdist.cc

Introduced in 48d1f24b87dfd95696c0db8311c81dc622717102
I have:

ixfrdist: Fix broken 'uid' and 'gid' parsing for non-numerical values

---

pdns/ixfrdist.cc

auth 4.9 ixfrdist: Fix brokn 'uid' and 'gid' parsing for non-numerical values

---

m4/systemd.m4

auth 4.9 autoconf: allow prerelease systemd versions

---

docs/changelog/4.9.rst
docs/secpoll.zone
docs/upgrading.rst

auth-4.9.1: changelog&secpoll

---

builder-support/helpers/rust.json
pdns/recursordist/settings/rust/Cargo.lock
pdns/recursordist/settings/rust/Cargo.toml

rec: update to rust/cargo 1.78 and update dependencies

---

contrib/ProtobufLogger.py
pdns/dnsmessage.proto
pdns/protozero.hh
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
regression-tests.recursor-dnssec/test_Protobuf.py

Implements #13020
If/when this is merged, do not forget to update https://github.com/PowerDNS/dnsmessage/blob/master/dnsmessage.proto
I have:

rec: add a few more fields to the protobuf messages

---

pdns/recursordist/syncres.cc
pdns/recursordist/test-syncres_cc1.cc

Original PR did the adjust in the wrong block. Discovered by Coverity 1546549
Diff to pre-#14221 code to see the result.
I have:

rec: followup to #14221: fix timeout adjust case

---

pdns/iputils.hh

As requested by Otto in https://github.com/PowerDNS/pdns/pull/14259, I reviewed the code tagged as a Wrapper object use after free defect by Coverity (CIDs `425793` in DNSdist, `1544902` and `1544903` in the recursor) and I agree it is a false positive. This code is hard to read, so I tried to improve its readability in this pull request.
I have:

NetmaskTree: Improve the readability of `NetmaskTree::TreeNode::split()`

---

tasks.py

Fixes #11180
Enables back the tests under `regression-test.rootzone` ignored for the `auth-backend` tests during the migration from CircleCi to GitHub actions. Based on the original tests defined [here](https://github.com/PowerDNS/pdns/blob/rel/auth-4.5.x/.circleci/config.yml)
Skipped `unbound-host` validation for `regression-test.rootzone/direct-ns` as there is no DS record on the parent zone for the nameservers of net
I have:

GH Actions: enable again rootzone regression-tests for auth

---

pdns/dnsdistdist/docs/reference/actions.rst
pdns/dnsdistdist/docs/reference/selectors.rst

dnsdist: Point the documentation to the correct FFI interface header

---

.not-formatted
pdns/protozero.cc
pdns/protozero.hh

Added `NOLINT(cppcoreguidelines-non-private-member-variables-in-classes)` since I think it make sense to have protected fields here.
`.hh` changes look bigger than they really are, check first commit while ignoring whitespace.
I have:

protozero reformat and tidy

---

.github/workflows/build-packages.yml

Provide a more descriptive title for builds and leave out redundant "build"

---

pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc

dnsdist: Add a Lua FFI function to set proxy protocol values

---

.github/workflows/build-docker-images-dispatch.yml
.github/workflows/build-docker-images-tags.yml
.github/workflows/build-docker-images.yml
.github/workflows/docker.yml

Only commit [2ae7713](https://github.com/PowerDNS/pdns/commit/2ae77131ffc4058a7293a3eec29295716e164594) is really needed but all commits in the Pull Request were cherry-picked for context.
I have:

dnsdist-1.8.x: backport of #14171 for fixing the build of images on new tags

---

.github/workflows/build-docker-images-dispatch.yml
.github/workflows/build-docker-images-tags.yml
.github/workflows/build-docker-images.yml
.github/workflows/docker.yml

Only commit [0344e8f](https://github.com/PowerDNS/pdns/commit/0344e8fbfcbf7165f8f8eac6037a32b3c8ce3d4d) is really needed but all commits in the Pull Request were cherry-picked for context.
I have:

dnsdist-1.9.x: backport of #14171 for fixing the build of images on new tags

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/5.1.rst
pdns/recursordist/docs/upgrade.rst

rec: prep for rec-5.1.0-beta1

---

pdns/dnsdistdist/docs/advanced/passing-source-address.rst

dnsdist: Hopefully make the "passing the source address" documentation better

---

.github/workflows/build-docker-images-dispatch.yml
.github/workflows/build-docker-images-tags.yml
.github/workflows/build-docker-images.yml
.github/workflows/docker.yml

Only commit [d2bb165](https://github.com/PowerDNS/pdns/pull/14291/commits/d2bb16585b982feebda633f74829ce763c343c72) is really needed but all commits in the Pull Request were cherry-picked for context.
I have:

auth-4.7.x: backport of #14171 for fixing the build of images on new tags

---

.github/workflows/build-docker-images-dispatch.yml
.github/workflows/build-docker-images-tags.yml
.github/workflows/build-docker-images.yml
.github/workflows/docker.yml

Only commit [f958b2b](https://github.com/PowerDNS/pdns/pull/14290/commits/f958b2b274d3b817e6c88b3099e603da94370ef0) is really needed but all commits in the Pull Request were cherry-picked for context.
I have:

auth-4.8.x: backport of #14171 for fixing the build of images on new tags

---

pdns/recursordist/docs/performance.rst

rec: document vm.max_map_count can be too low

---

.github/workflows/build-docker-images-dispatch.yml
.github/workflows/build-docker-images-tags.yml
.github/workflows/build-docker-images.yml
.github/workflows/docker.yml

Only commit [abccae1](https://github.com/PowerDNS/pdns/commit/abccae12d4443131dd9ef3f7302541cdb9039e77) is really needed but all commits in the Pull Request were cherry-picked for context. 
I have:

rec-5.0.x: backport of #14171 for fixing the build of images on new tags

---

.github/workflows/build-docker-images-dispatch.yml
.github/workflows/build-docker-images-tags.yml
.github/workflows/build-docker-images.yml
.github/workflows/docker.yml

Only commit [541b90c](https://github.com/PowerDNS/pdns/pull/14287/commits/541b90c8dd3d55851167ad1a8b3f053d009e2881) is really needed but all commits in the Pull Request were cherry-picked for context. 
I have:

rec-4.9.x: backport of #14171 for fixing the build of images on new tags

---

build-scripts/docker/repo-test/generate-repo-files.py

It's been a while since we updated this script and changes have been accumulating on my different machines.
This PR includes:
- addition of auth-49, rec-50 and dnsdist-19
- addition of Ubuntu Noble distro
- removal of Ubuntu Bionic
- fix for different regex strings in newer Python 3.x versions
I have:

Update repo test script.

---

pdns/dnsdistdist/dnsdist-dnsparser.cc
pdns/dnsdistdist/dnsdist-dnsparser.hh
pdns/dnsdistdist/dnsdist-lua-actions.cc
pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-lua.hh
pdns/dnsdistdist/dnsdist-svc.cc
pdns/dnsdistdist/dnsdist-svc.hh
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
regression-tests.dnsdist/test_SVCB.py

dnsdist: Add Lua FFI bindings to generate SVC responses

---

docs/lua-records/index.rst

auth docs: remove stray backquote

---

regression-tests.dnsdist/runtests

Homebrew prefix may vary depending on the setup and previous `curl-openssl` package has now been renamed `curl`.
I have:

dnsdist: update test runner for mac

---

pdns/dnsdistdist/dnsdist-lua-inspection.cc

This PR switches from `sscanf()` to `pdns::checked_stoi()` to parse "100ms"-like parameters to `grepq()`. `sscanf()` is hard to use right and often triggers warnings from static analysis tools, so let's switch to our better-suited `pdns::checked_stoi()` instead.
I have:

dnsdist: Use `pdns::checked_stoi` instead of `sscanf` for `grepq`'s ms

---

pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-tcp.cc
regression-tests.recursor-dnssec/test_ProxyProtocol.py

rec: Backport 14340 to rec 5.0.x: count substituted remote in case of proxy protocol

---

pdns/recursordist/rec-main.hh
pdns/recursordist/rec-tcp.cc
regression-tests.recursor-dnssec/test_Protobuf.py

Followup to #13021
Also adds regression tests so that all combos of UDP/TCP and non-ffi/ffi are tested..
I have:

rec: fix TCP case for policy tags set by gettag(_ffi)

---

pdns/recursordist/rec-main.hh
pdns/recursordist/rec-tcp.cc
regression-tests.recursor-dnssec/test_Protobuf.py

rec: Backport 14346 to rec-5.0.x: fix TCP case for cached policy tags 

---

pdns/recursordist/rec-main.hh
pdns/recursordist/rec-tcp.cc
regression-tests.recursor-dnssec/test_Protobuf.py

Cherry picked from
6a3943374904b39769d8c6fcb3923b6456814d19 and 9bddb82fd4166c83b055f037f775f33471403704
Backport of #14351
I have:

rec: Backport 14346 to rec-4.9.x: fix TCP case for cached policy tags

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst

dnsdist: Prepare ChangeLog and secpoll for 1.9.5

---

pdns/recursordist/docs/performance.rst
pdns/recursordist/settings/table.py

rec: describe (roughly) memory usage

---

pdns/recursordist/pdns_recursor.cc
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_DNS64.py

rec: don't send double SOA record in the case of a dns64 CNAME that does not resolve

---

builder-support/debian/recursor/debian-buster/pdns-recursor.maintscript
builder-support/debian/recursor/debian-buster/recursor.lua
builder-support/debian/recursor/debian-buster/rules
pdns/recursordist/rec_channel_rec.cc

Followup to #14265. Debian tweaks suggested by @zeha, but skipping the pub suffix list part.
I have:

Rec followup to #14265: use correct file suffix for reloading and debian tweaks

---

.github/actions/spell-check/expect.txt
docs/secpoll.zone
pdns/recursordist/docs/changelog/5.1.rst
pdns/recursordist/docs/upgrade.rst
pdns/recursordist/settings/table.py

Prep for rec-5.1.0-rc1

---

builder-support/debian/recursor/debian-buster/pdns-recursor.maintscript
builder-support/debian/recursor/debian-buster/recursor.lua
builder-support/debian/recursor/debian-buster/rules

@zeha can you take look? Thanks!
I have:

rec: keep Lua config for now as existing configs might use it

---

modules/godbcbackend/OBJECTLIBS

needed for e.g. macOS with non-dylib odbc
I have:

auth: allow -lodbc in a non-standard location

---

pdns/axfr-retriever.cc

Including a fix to timeout potentially underflowing. Coverity complains about n (now called bytesRead) overflowing, but that's a false positive, as numread is bounded.
I have:

Tidy AXFRRetriever::timeoutReadn

---

pdns/recursordist/settings/cxxsupport.cc

rec: Fix coverity 1544951 copy_instead_of_move

---

.not-formatted
pdns/cachecleaner.hh
pdns/lock.hh
pdns/sholder.hh

Tidy lock.hh, cachecleaner.hh and sholder.hh

---

pdns/iputils.hh

Hopefully Coverity will take the hint.
I have:

AddressAndPortRange: Make it clearer only low-order bits matter to us

---

pdns/dnsdistdist/dnsdist-web.cc
regression-tests.dnsdist/test_Prometheus.py

Otherwise `promtool` and other prometheus consumers are quite unhappy.
I have:

dnsdist: Dedup Prometheus help and type lines for custom metrics with labels

---

builder-support/dockerfiles/Dockerfile.target.el-7
builder-support/dockerfiles/Dockerfile.target.oraclelinux-7

tested locally for auth
rec test build https://github.com/Habbie/pdns/actions/runs/9758362716
dnsdist test build https://github.com/Habbie/pdns/actions/runs/9758367870
I have:

switch el7 builds to Oracle Linux 7

---

.not-formatted
modules/remotebackend/httpconnector.cc
pdns/ixfrutils.cc
pdns/shuffle.cc
pdns/sstuff.hh
pdns/test-distributor_hh.cc
pdns/webserver.cc

Note the `readWithTimeout` return type change to make things more consistent.
Plus a few small nits that caught my eye.
I have:

Tidy sstuf.hh and shuffle.??

---

builder-support/dockerfiles/Dockerfile.target.el-7
builder-support/dockerfiles/Dockerfile.target.oraclelinux-7

backport of #14400
test build at https://github.com/Habbie/pdns/actions/runs/9759220881
I have:

rec-5.1: switch el7 builds to Oracle Linux 7

---

.github/workflows/builder.yml

daily package build: use el-7 target instead of centos-7

---

docs/secpoll.zone
pdns/recursordist/docs/appendices/EOL.rst
pdns/recursordist/docs/changelog/4.9.rst
pdns/recursordist/docs/changelog/5.0.rst

rec: Prep for rec-4.9.7 and 5.0.7 releases

---

modules/geoipbackend/geoipbackend.cc
modules/lua2backend/lua2api2.hh
pdns/dnspacket.cc
pdns/misc.cc
pdns/misc.hh
pdns/opensslsigners.cc
pdns/pdnsutil.cc

Various minor cleanups here and there.
I have:

Various cleanups

---

builder-support/dockerfiles/Dockerfile.target.el-7
builder-support/dockerfiles/Dockerfile.target.oraclelinux-7

(cherry picked from commit 73a1b98f92c671c590540ac19d74d70499f89066)
Backport of #14400 
I have:

rec: Backport 14400 to rec 4.9.x: switch el7 builds to Oracle Linux 7 

---

builder-support/dockerfiles/Dockerfile.target.el-7
builder-support/dockerfiles/Dockerfile.target.oraclelinux-7

(cherry picked from commit 73a1b98f92c671c590540ac19d74d70499f89066)
Backport of #134400
I have:

rec: Backport 14400 to rec 5.0.x: switch el7 builds to Oracle Linux 7

---

.github/workflows/builder.yml

missed this spot in #14406
I have:

exclude el7 from arm64 in daily package builds

---

builder-support/dockerfiles/Dockerfile.target.el-7
builder-support/dockerfiles/Dockerfile.target.oraclelinux-7

backport of #14400
test build at https://github.com/Habbie/pdns/actions/runs/9759237902
I have:

auth-4.9: switch el7 builds to Oracle Linux 7

---

pdns/recursordist/settings/cxxsupport.cc

Fix a minor "processsing" typo.
Noticed more S don't make it any faster. :stuck_out_tongue_winking_eye:
I have:

Recursor: Fix processsing typo.

---

pdns/recursordist/settings/cxxsupport.cc

(cherry picked from commit c91c84f640e32a7d24925a78cf3609e731d098e9)
I have:

rec: Backport 14425 to rec 5.1.x: fix typo in log message

---

contrib/xdp.py
pdns/dnsdistdist/docs/advanced/xsk.rst
pdns/dnsdistdist/docs/reference/constants.rst

dnsdist: Better documentation and debug informations for `XSK`/`AF_XDP`

---

builder-support/dockerfiles/Dockerfile.target.el-7
builder-support/dockerfiles/Dockerfile.target.oraclelinux-7

auth-4.8: switch el7 builds to Oracle Linux 7

---

pdns/dnsdist-web.cc
regression-tests.dnsdist/test_Prometheus.py

Backport of #14395 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport of 14395 - Dedup Prometheus help and type lines for custom metrics with labels

---

builder-support/dockerfiles/Dockerfile.target.el-7
builder-support/dockerfiles/Dockerfile.target.oraclelinux-7

Backport of #14400 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 14400 - Switch el7 builds to Oracle Linux 7

---

.github/actions/spell-check/expect.txt
pdns/recursordist/docs/running.rst

rec: document log lines produced by logging.quiet set to false

---

docs/secpoll.zone
pdns/recursordist/docs/appendices/EOL.rst
pdns/recursordist/docs/changelog/5.1.rst

rec: prep for rec-5.1.0

---

.github/workflows/builder-releases-dispatch.yml

rec: move to rec-5.1.x for builder-releases-dispatch.yml as well

---

.github/workflows/builder.yml

rec 4.9.x: daily build for el-7 instead of centos-7

---

.github/workflows/builder.yml

rec 5.0.x: daily build for el-7 instead of centos-7

---

.github/workflows/builder.yml

rec 5.1.x: daily build for el-7 instead of centos-7

---

.github/workflows/builder.yml

auth: Backport 14445 to auth 4.8.x: use el-7 for daily build

---

.github/workflows/builder.yml

auth: Backport 14445 to auth 4.9.x: use el-7 for daily build

---

.github/workflows/builder.yml

dnsdist: Backport 14445 to dnsdist 1.9.x: use el-7 for daily build

---

.github/workflows/build-and-test-all-releases-dispatch.yml
.github/workflows/builder-releases-dispatch.yml

ci: Stop building rel/dnsdist-1.7.x, as 1.7.x is EOL

---

pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-xsk.cc
pdns/xsk.cc
pdns/xsk.hh

Backport of #14429 to rel/dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 14429 - Fix a race in the XSK/AF_XDP backend handling code

---

.github/workflows/builder.yml

dnsdist: Backport 14445 to dnsdist 1.8.x: use el-7 for daily build

---

builder-support/dockerfiles/Dockerfile.target.el-7
builder-support/dockerfiles/Dockerfile.target.oraclelinux-7

(cherry picked from commit 73a1b98f92c671c590540ac19d74d70499f89066) (cherry picked from commit 87e2e08b41de7453f144721ed232219052205651)
Attempt to fix the error reported in https://github.com/PowerDNS/pdns/actions/runs/9908269710/job/27373689135
Please validate if `devtoolset-11-gcc-c++` is the right one for dnsdist 1.8
I have:

dnsdist 1.8.x: switch el7 builds to Oracle Linux 7

---

Dockerfile-recursor
dockerdata/recursor.conf

rec: provide docker image with yml config file

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst

dnsdist: Prepare ChangeLog and secpoll for 1.9.6

---

.github/workflows/build-packages.yml

build-packages: More lenient permissions on the packages directory

---

pdns/recursordist/filterpo.cc
pdns/recursordist/rpzloader.cc
regression-tests.recursor-dnssec/test_RPZ.py

Dump file part reported on IRC by @spirillen 
I have:

rec: dump right SOA into dumpFile and report non-relative SOA for includeSOA=true

---

regression-tests.dnsdist/requirements.txt
regression-tests.recursor-dnssec/requirements.txt

rec: Backport 14486 to rec 4.9.x: pin pysnmp to version 5 for regression tests

---

regression-tests.dnsdist/requirements.txt
regression-tests.recursor-dnssec/requirements.txt

rec: Backport 14486 to rec 5.1.x: pin pysnmp to version 5 for regression tests

---

pdns/recursordist/.gitignore

rec: Ignore pubsuffix.cc now that it's no longer (a symlink) in git

---

pdns/recursordist/settings/docs-new-preamble-in.rst

rec: expand YAML docs with more examples and consistent formatting

---

pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-console.cc
pdns/dnsdistdist/dnsdist-dynblocks.hh
pdns/dnsdistdist/dnsdist-healthchecks.cc
pdns/dnsdistdist/dnsdist-lbpolicies.cc
pdns/dnsdistdist/dnsdist-lbpolicies.hh
pdns/dnsdistdist/dnsdist-lua-ffi.hh
pdns/dnsdistdist/dnsdist-lua.hh
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsdistdist/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist-web.cc
pdns/dnsdistdist/dnsdist.hh
pdns/dnsdistdist/test-dnsdistrules_cc.cc

dnsdist: Only include the expensive LuaContext header when required

---

pdns/recursordist/settings/table.py

rec: fix include dir docs to not say YAML settings include .conf files

---

Dockerfile-recursor
dockerdata/recursor.conf

rec: Backport 14459 to rec 5.1.x: move default Docker config to YAML 

---

ext/yahttp/yahttp/router.cpp

rec: Backport 14404 to rec 5.1.x: Yahttp router: avoid unsigned underflow in match()

---

ext/yahttp/yahttp/router.cpp

rec: Backport 14404 to rec 5.0.x: Yahttp router: avoid unsigned underflow in route()

---

pdns/recursordist/filterpo.cc
pdns/recursordist/rpzloader.cc
regression-tests.recursor-dnssec/test_RPZ.py

(cherry picked from commit 397da738caad01df0da04387083c73a0e941608b)
Backport of #14471
I have:

rec: Backport 14471 to rec-5.1.x: dump right SOA into dumpFile and report non-relative SOA for includeSOA=true

---

pdns/recursordist/filterpo.cc
pdns/recursordist/rpzloader.cc
regression-tests.recursor-dnssec/test_RPZ.py

(cherry picked from commit 397da738caad01df0da04387083c73a0e941608b)
Backport of #14471
I have:

rec: Backport of 14471 to rec-5.0.x: dump right SOA into dumpFile and report non-relative SOA for includeSOA=true

---

pdns/recursordist/filterpo.cc
pdns/recursordist/rpzloader.cc
regression-tests.recursor-dnssec/test_RPZ.py

(cherry picked from commit 397da738caad01df0da04387083c73a0e941608b)
Backport of #14471 
I have:

rec: Backport of 14471 to rec-4.9.x: dump right SOA into dumpFile and report non-relative SOA for includeSOA=true

---

pdns/recursordist/RECURSOR-MIB.txt

(cherry picked from commit 551641127c26799ff8ef80f56887a6ccd0d2b74f)
Backport of #14514 
I have:

rec: Backport 14514 to rec 5.1.x: fix maintenanceCalls vs maintenanceCount

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/4.9.rst
pdns/recursordist/docs/changelog/5.0.rst
pdns/recursordist/docs/changelog/5.1.rst

rec: Prep for rec-4.9.8, rec-5.0.8 and rec-5.1.1

---

.not-formatted
pdns/auth-main.cc
pdns/recursordist/rec-main.cc
pdns/version.cc
pdns/version.hh

Refactor is needed to implement #14455.
I have:

rec/auth: Refactor version reporting code and write version to stdout

---

pdns/axfr-retriever.cc
pdns/dnsbulktest.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/test-dnsdist-dnsparser.cc
pdns/dnsdistdist/test-dnsdist_cc.cc
pdns/dnspacket.cc
pdns/dnsparser.cc
pdns/dnsparser.hh
pdns/dnsproxy.cc
pdns/dnsrecords.cc
pdns/dnsreplay.cc
pdns/ixfr.cc
pdns/ixfrdist.cc
pdns/ixfrutils.cc
pdns/nsec3dig.cc
pdns/recursordist/lwres.cc
pdns/recursordist/rec-system-resolve.cc
pdns/resolver.cc
pdns/rfc2136handler.cc
pdns/saxfr.cc
pdns/sdig.cc
pdns/speedtest.cc
pdns/stubresolver.cc
pdns/tcpreceiver.cc
pdns/test-dnsrecords_cc.cc
pdns/test-tsig.cc
pdns/tsigverifier.cc

Main change is in `dnsparser.hh`, rest is collateral.
I have:

common: remove position from MOADNSParser::answers_t, it it used nowhere

---

pdns/recursordist/docs/generate-man-pages.py
pdns/recursordist/meson.build

rec: add generation of man pages to meson.build

---

pdns/recursordist/docs/lua-config/protobuf.rst

Fix a typo in protobuf.rst

---

docs/settings.rst
modules/lua2backend/lua2api2.hh
pdns/auth-main.cc
pdns/auth-secondarycommunicator.cc
pdns/lua-auth4.cc
pdns/lua-auth4.hh
pdns/lua-base4.cc
pdns/lua-base4.hh
pdns/lua-record.cc
pdns/packethandler.cc
pdns/recursordist/lua-recursor4.cc
pdns/recursordist/lua-recursor4.hh
pdns/recursordist/rec-lua-conf.cc
pdns/recursordist/settings/table.py

Adds ability to load lua scripts globally. Fixes #11676
I have:

Lua global include

---

docs/backends/generic-mysql.rst

Added MariaDB to doc "Generic MySQL backend", as discussed in [github.com/PowerDNS/pdns/discussions/14538](https://github.com/PowerDNS/pdns/discussions/14538). 
I have:

Include MariaDB in doc "Generic MySQL backend"

---

ext/json11/json11.cpp

fixes #14549, which came with a patch
tested on debian 12, not with gcc-15
I have:

json11: add include for cstdint

---

regression-tests.recursor-dnssec/test_ExtendedErrors.py

rec: re-enable a few tests now that sidnlabs re-instated the zones used

---

.github/workflows/build-packages.yml

We are OK with making private repository names discoverable via the public Rekor API server.
I have:

Post provenance data to the public transparency log for private repos

---

pdns/dnsdistdist/docs/reference/config.rst

dnsdist: Update the documentation of `showServers` with new metrics

---

CONTRIBUTING.md
SECURITY.md

Also rename dnsdist to DNSdist in the security policy.
I have:

CONTRIBUTING: Fix outdated security policy link

---

.github/workflows/misc-dailies.yml
tasks.py

I have tested that this change does not break the working workflows, and I have tested some parts of the Coverity one but not the whole thing. I'll do a follow-up PR to make it easier to test the Coverity workflow, although the required secrets make that hard.
I have:

Fix the Coverity workflow after the Quiche installation refactoring

---

pdns/recursordist/rec-main.cc

Previously, zero stats would be skipped, making sure correct policy names are used. Fixes #14522
Note that removed policies will still be reflected in the counts.
I have:

rec: always include all stats for RPZs in Prometheus data (previously zero stats would be skipped)

---

docs/settings.rst

This is effectively a follow-up to #14561
I have:

docs: Improve wording docs about oversized chunks

---

pdns/ssqlite3.cc

ssqlite3: use "begin immediate" to avoid later fights over upgrading to write

---

docs/settings.rst

auth docs: mark settings removed in 4.9.0

---

docs/lua-records/index.rst

Avoids misrender and warning from sphinx.
I have:

auth docs: reword LUA return paragraph

---

pdns/ssqlite3.cc

(cherry picked from commit 63851a822fb5651cd7720c7f7f597309aeaa82a7)
I have:

auth-4.9: ssqlite3: use "begin immediate" to avoid later fights over upgrading to write

---

pdns/recursordist/settings/table.py

rec docs: fix *.lua, * has special meaning

---

.gitignore

Gitignore the ccls cache
I have:

Gitignore the ccls cache

---

docs/performance.rst
docs/settings.rst

auth docs: fix one error and expand a bit on queues and threads

---

.github/actions/spell-check/patterns.txt
pdns/dnsdistdist/docs/reference/config.rst

dnsdist: Add an example of how to use `hashPassword()`

---

pdns/dnspacket.cc

Add doc reference to oversized chunk message

---

pdns/dnsdistdist/dnsdist-cache.cc
pdns/dnsdistdist/dnsdist-ecs.cc
pdns/dnsdistdist/dnsdist-ecs.hh
pdns/dnsdistdist/dnsdist-lua-actions.cc
pdns/dnsdistdist/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsdistdist/dnsdist-svc.cc
pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/test-dnsdist_cc.cc
regression-tests.dnsdist/test_LuaFFI.py

Closes https://github.com/PowerDNS/pdns/issues/14567.
I have:

dnsdist: Add Lua FFI accessors for EDNS version and extended rcode

---

builder-support/helpers/install_quiche.sh
builder-support/helpers/quiche.json
tasks.py

Backport of #14529 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 14529 - Update Quiche to 0.22.0 (in our packages)

---

pdns/communicator.cc
pdns/lua-record.cc
pdns/signingpipe.cc

auth: more and better thread names

---

.not-formatted
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/test-sholder_hh.cc
pdns/recursordist/Makefile.am
pdns/recursordist/test-sholder_hh.cc
pdns/test-sholder_hh.cc

This file has been around for a while, but never enabled.
I have:

Enable the (tiny) shared holder unit test

---

regression-tests.recursor-dnssec/test_SimpleForwardOverDoT.py

Not a fundamental solution, but it might make the occasional connectivity issues GH workflows see less annoying.
I have:

rec: use multiple forwarding targets for DoT forwarding test

---

.github/workflows/build-and-test-all.yml

auth 4.7 mssql CI: switch to 2022-CU12 image

---

meson.build

Refactor meson building of fuzz tools
I have:

Refactor meson building of fuzz tools

---

.clang-tidy.bugs
.clang-tidy.full

This option is missing from new versions of clang-tidy and is not used anymore.
I have:

Fix clang-tidy

---

pdns/webserver.cc

auth 4.9 webserver.cc: try to pass exception text with 500 errors

---

.github/workflows/coverity-dispatch.yml
.github/workflows/misc-dailies.yml

We have one Coverity token per product, and not a global token.
I have:

coverity: Use the correct secret token

---

ext/json11/json11.cpp

auth-4.9 json11: add include for cstdint

---

ext/yahttp/yahttp/router.cpp

auth-4.9  Yahttp router: appease coverity wrt unsigned underflow in match()

---

regression-tests/README.md

auth: "document" PDNS_BUILD_PATH for regression-tests/

---

pdns/dnsdistdist/dnsdist-lua.cc

Fixes #14699 for me, although feels too easy.
I have:

dnsdist: start the backend if rest of config is processed

---

.github/actions/spell-check/expect.txt
build-scripts/git-to-changelog-merges
docs/changelog/4.9.rst
docs/secpoll.zone

auth-4.9.2: docs+secpoll

---

pdns/recursordist/rec-main.cc
pdns/recursordist/recursor_cache.cc
pdns/recursordist/recursor_cache.hh
pdns/recursordist/settings/table.py
pdns/recursordist/test-recursorcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc8.cc

rec: CVE-2024-25590: limit maximum size of rr sets in record cache

---

pdns/recursordist/rec-main.cc
pdns/recursordist/recursor_cache.cc
pdns/recursordist/recursor_cache.hh
pdns/recursordist/settings/table.py
pdns/recursordist/test-recursorcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc8.cc

rec: backport of CVE-2024-25590 to rec-5.1.x: limit maximum size of rr sets in record cache

---

pdns/recursordist/rec-main.cc
pdns/recursordist/recursor_cache.cc
pdns/recursordist/recursor_cache.hh
pdns/recursordist/settings/table.py
pdns/recursordist/test-recursorcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/uuid-utils.cc

rec: backport of CVE-2024-25590 to rec-5.0.x: limit maximum size of rr sets in record cache

---

pdns/recursordist/rec-main.cc
pdns/recursordist/recursor_cache.cc
pdns/recursordist/recursor_cache.hh
pdns/recursordist/test-recursorcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/uuid-utils.cc

rec: backport of CVE-2024-25590 to rec-4.9.x: limit maximum size of rr sets in record cache

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst

dnsdist: Update ChangeLog and secpoll for 1.9.7

---

builder-support/dockerfiles/Dockerfile.debbuild-prepare
builder-support/dockerfiles/Dockerfile.recursor
builder-support/dockerfiles/Dockerfile.rpmbuild
builder-support/helpers/install_rust.sh

rec: rust download dedup

---

docs/catalog.rst

Documents steps needed to update catalog-consuming secondary servers when address and/or port of primary server changes.
I have:

auth doc: Document 2-step process for consumer zone updates.

---

build-scripts/test-recursor

bump SNMP ignore from buster to bookworm after buildbot VM upgrade

---

ext/lmdb-safe/lmdb-safe.hh
ext/lmdb-safe/lmdb-typed.cc
ext/lmdb-safe/lmdb-typed.hh
modules/lmdbbackend/lmdbbackend.cc

Some cleanups for lmdb-safe
I have:

Some cleanups for lmdb-safe

---

ext/lmdb-safe/lmdb-safe.cc
ext/lmdb-safe/lmdb-safe.hh
ext/lmdb-safe/lmdb-typed.hh

Gets rid of a lot of templating cruft and relies more on dispatch and specializing.
I have:

Rework MDBIn/OutVal

---

builder-support/dockerfiles/Dockerfile.rpmbuild
builder-support/dockerfiles/Dockerfile.target.oraclelinux-8

needs build tests (auth did pass locally)
I have:

el-8: use gcc-toolset-13

---

ext/lmdb-safe/lmdb-safe.hh
ext/lmdb-safe/lmdb-typed.hh
meson.build

Small cleanups

---

pdns/recursordist/RECURSOR-MIB.txt
pdns/recursordist/docs/metrics.rst
pdns/recursordist/lwres.hh
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-snmp.cc
pdns/recursordist/rec-tcounters.hh
pdns/recursordist/rec_channel_rec.cc
pdns/recursordist/syncres.cc
pdns/recursordist/ws-recursor.cc
regression-tests.recursor-dnssec/test_SNMP.py

(cherry picked from commit b22ec811be8c094605df49e015be02e9a85d978e)
Backport of #14554 
I have:

rec: Backport 14554 to rec-5.1.x: distinguish OS imposed limits from app imposed limits, specifically on chains

---

pdns/recursordist/reczones-helpers.cc
pdns/recursordist/reczones-helpers.hh
pdns/recursordist/reczones.cc
pdns/recursordist/settings/table.py
regression-tests.recursor-dnssec/test_DNS64.py

rec: Backport 14693 to rec 5.1.x: implement rfc6303 special zones (mostly v6 reverse mappings) 

---

ext/lmdb-safe/lmdb-typed.hh

Not everything is automated here, so worth taking a quick look especially around the macro -> template function changes.
I have:

Cleanup lints & macros in lmdb-typed.hh

---

pdns/dnsdistdist/dnsdist-cache.cc

dnsdist: Fix Coverity warning 445614: " Argument cannot be negative"

---

pdns/lua-base4.cc
pdns/recursordist/Makefile.am
pdns/recursordist/docs/lua-scripting/functions.rst
pdns/recursordist/docs/lua-scripting/logging.rst
pdns/recursordist/lua-recursor4.cc
pdns/recursordist/lua-recursor4.hh
pdns/recursordist/rec-main.cc
pdns/recursordist/recursor_cache.cc
pdns/recursordist/recursor_cache.hh
pdns/recursordist/settings/table.py
pdns/recursordist/test-recursorcache_cc.cc

Crate additonal Lua functions to:
- Dump (some) MRU records from the record cache
- Load above dump again into the record cache
- Run some Lua on startup
- Run some Lua on graceful shutdown (`rec_control quite-nicely`)
- Create a thread running a Lua script
- Do structured logging from Lua
Provides parts of the puzzle of #8032
I have:

rec: provide a few more Lua functions, most importantly record cache dump and load

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/5.1.rst
pdns/recursordist/docs/upgrade.rst

rec: prep for rec-5.1.3

---

pdns/recursordist/settings/table.py
pdns/recursordist/test-settings.cc
pdns/root-dnssec.hh
regression-tests.recursor-dnssec/test_TrustAnchors.py

fetched from https://www.iana.org/dnssec/files after their 2024-07-24 update.
If you take just the first commit, you get a nice crash.  I did not squash because you might want to see if that crash could also happen to users.
I have:

recursor: add 38696 root anchor

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/5.2.rst
pdns/recursordist/docs/changelog/index.rst
pdns/recursordist/docs/upgrade.rst
pdns/recursordist/settings/docs-new-preamble-in.rst

rec: Prep for rec-5.2.0-alpha1

---

.github/workflows/codeql-analysis.yml

example output ([original, will expire](https://github.com/PowerDNS/pdns/actions/runs/11726291450/job/32664569495)):
```
modules/tinydnsbackend/data.cdb:                                application/octet-stream; charset=binary
Error: Process completed with exit code 1.
```
I have:

CI: have binary check emit offenders

---

pdns/tkey.cc

auth: don't log absense of GSS-TSIG functionality at such a high level, use DEBUG

---

docs/settings.rst

auth settings: document that lua-global-include-dir is in 5.0.0

---

.github/workflows/build-and-test-all.yml
.github/workflows/build-packages.yml
.github/workflows/builder-dispatch.yml
.github/workflows/builder.yml
.github/workflows/fuzz.yml

rec-4.9.x: move from up/download-artifact@3 to @4

---

pdns/recursordist/Makefile.am
pdns/recursordist/rec-lua-conf.cc
pdns/recursordist/rec-system-resolve.cc
pdns/recursordist/rec-system-resolve.hh
pdns/recursordist/rec-xfr.cc
pdns/recursordist/rec-xfr.hh
pdns/recursordist/reczones.cc
pdns/recursordist/rpzloader.cc
pdns/recursordist/settings/cxxsupport.cc
pdns/recursordist/settings/docs-new-preamble-in.rst
pdns/recursordist/settings/rust/src/bridge.rs
regression-tests.recursor-dnssec/test_FWCatz.py

If the system resolver is enabled
I have:

rec: allow addresses to retrieve catalog zones and RPZs to be names

---

pdns/recursordist/rec-main.cc
pdns/recursordist/rec-xfr.cc
pdns/recursordist/rec-xfr.hh

rec: bunch of coverity reports, all low severity

---

docs/appendices/EOL.rst

auth EOL: adjust for long delay after 4.9

---

pdns/recursordist/docs/manpages/rec_control.1.rst
pdns/recursordist/rec_channel_rec.cc

Plus some minor style edits
I have:

rec: rec_control docs update to reflect current state of dump-cache

---

.github/workflows/builder.yml
builder-support/debian/authoritative/debian-buster/rules
builder-support/debian/recursor/debian-buster/rules
builder-support/dockerfiles/Dockerfile.target.ubuntu-oracular

includes a workaround for libcrypto brokenness, which fixes #14084
I have:

builder: add ubuntu-oracular target

---

pdns/recursordist/docs/manpages/rec_control.1.rst
pdns/recursordist/rec_channel_rec.cc
pdns/recursordist/settings/docs-new-preamble-in.rst
pdns/recursordist/settings/generate.py
pdns/recursordist/settings/table.py

Fixes #14870
Also add ``rec_control reload-yaml`` as an alias for ``reload-lua-config``.
I have:

rec: add rec_control reload-yaml, document which and how settings can be modified runtime 

---

pdns/recursordist/settings/generate.py
pdns/recursordist/settings/rust-bridge-in.rs

rec: Fix a couple typos in the Rust generator and bridge

---

pdns/dnsdistdist/dnsdist-metrics.cc
pdns/dnsdistdist/docs/reference/custommetrics.rst

dnsdist custom metrics: better error messages, small doc improvements

---

pdns/dnsdist-doh-common.hh
pdns/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-doh-common.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/libssl.cc
pdns/libssl.hh
pdns/tcpiohandler.cc
pdns/tcpiohandler.hh
regression-tests.dnsdist/test_TLS.py

Backport of #14764 to rel/dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport of #14764 - add the ability to load a given TLS tickets key

---

.github/actions/spell-check/expect.txt
docs/secpoll.zone
pdns/recursordist/docs/changelog/5.2.rst
pdns/recursordist/docs/upgrade.rst

rec: Prep for rec-5.2.0-beta1

---

regression-tests.recursor-dnssec/test_RecDnstap.py

The issue is that if the test ends *too* quick LeakSanatizer did not init all thread local data structures yet, and it reports this and exits with a non-zero exit code:
```
Tracer caught signal 11: addr=0x7fc0f2bc0000 pc=0x55bc6eccaeda sp=0x7fc0f29e1d40
==10208==LeakSanitizer has encountered a fatal error.
==10208==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==10208==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```
I have:

rec: cleanup dnstap regression test a bit and try to avoid LeakSanitizer internal issue

---

pdns/recursordist/settings/generate.py
pdns/recursordist/settings/rust/Cargo.lock
pdns/recursordist/settings/rust/Cargo.toml
pdns/recursordist/settings/rust/src/bridge.rs

rec: follow clippy's code improvements advice, move static lib version to 5.2.0

---

pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rpzloader.cc

rec: coverity fixes, all minor optimizations

---

build-scripts/docker/repo-test/generate-repo-files.py

generate-repo-files: pick up git versions from output too

---

Dockerfile-recursor

Fixes #14915
Before:
Features: libcrypto-ecdsa libcrypto-ed25519 libcrypto-ed448 libcrypto-eddsa lua nod protobuf dnstap-framestream sodium curl scrypt
After:
Features: libcrypto-ecdsa libcrypto-ed25519 libcrypto-ed448 libcrypto-eddsa lua nod protobuf dnstap-framestream snmp sodium curl DoT scrypt
Dependencies are already there.
I have:

rec: sync Dockerfile build options with packages

---

.github/workflows/documentation.yml

Also uploads the PDF artifacts to the various websites

also add the PDFs to the websites

---

.github/workflows/documentation.yml

Use ./docs/_build for all the to be uploaded artifacts

adjusted paths

---

pdns/recursordist/docs/lua-scripting/dnsname.rst
pdns/recursordist/docs/manpages/rec_control.1.rst
pdns/recursordist/docs/running.rst

rec: minor doc fixes

---

pdns/recursordist/settings/table.py

rec: backport 14957 to rec-5.2.x: Avoid local source port 4791

---

pdns/dnsdistdist/dnsdist-metrics.cc
pdns/dnsdistdist/docs/reference/custommetrics.rst

Backport of #14888 to rel/dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport of 14888 - Custom metrics: better error messages, small doc improvements

---

pdns/auth-zonecache.cc

clang-tidy complains here about pointless std::move of a trivially copyable type.
I have:

use some structured binding

---

pdns/recursordist/decafsigners.cc

rec: zap dangling symlink, leftover of #14926

---

pdns/dnsdistdist/docs/reference/actions.rst

dnsdist: Fix some small issues in the documentation for actions

---

.github/workflows/build-and-test-all.yml
pdns/recursordist/meson.build
tasks.py

Including a fix to pickup the right compiler and flags flags (affects existing auth build as well).
I also added some code to get the right SAN names in the meson case.
I have:

rec: start building rec also using meson in ci

---

pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-tcp.cc

rec: explictly log port of listening addresses

---

pdns/dnsdistdist/Makefile.am

dnsdist:: add -lssl to testrunner link, needed on OpenBSD at least

---

pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/doh3.hh

dnsdist: fix doh3-less compile

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc

dnsdist: Fix missing variant header that prevents building on EL8

---

pdns/credentials.cc
pdns/credentials.hh

Tidy credentials.??

---

.github/workflows/coverity.yml

This is needed to build DNSdist now that the settings, actions and selectors are generated from YAML files.
I have:

dnsdist: Install python-yaml in the Coverity workflow

---

pdns/recursordist/settings/table.py

rec: fix forward zones example in YAML

---

pdns/tcpreceiver.cc

Auth-4.8 check return value of getCatalogMembers()

---

contrib/xdp-filter.ebpf.src
contrib/xdp.py

This PR adds the following parameters to `xdp.py`:
- Maximum size of eBPF maps
- Number of network queues in XSK mode
It also delint the code in a second commit.
I have:

dnsdist: Make hard-coded values configurable in xdp.py

---

docs/changelog/4.7.rst
docs/changelog/4.8.rst
docs/changelog/4.9.rst
docs/secpoll.zone

Administrivia for upcoming releases
I have:

auth-{4.7.5,4.8.5,4.9.4}: changelog entries + secpoll update

---

contrib/xdp.py

dnsdist: Add support for multiple network interfaces in the XDP helper

---

docs/common/tarball-pgp-keys.rst

docs: correct text of link for key block

---

.github/workflows/documentation.yml

rec: fix docs generating, settings/ is now rec-rust-lib/

---

pdns/recursordist/rec-rust-lib/rust/build.rs

Locally tested with autotools dist dir, meson in-tree build dir and meson out-of tree build dir as well.
Also tested with CI package build. So I think everything is covered.
I have:

rec: fix cxx include dir

---

pdns/arguments.cc
pdns/dnsname.hh
pdns/lua-base4.cc
pdns/recursordist/rec-web-stubs.hh
pdns/recursordist/syncres.cc
pdns/zonemd.cc

New set of Coverity issues. Most Low severity, one Medium (that's a separate commit).
I have:

rec: coverity 20250212

---

.github/scripts/publish.js
.github/workflows/documentation.yml

revert from rclone back to custom sync script

---

pdns/recursordist/Makefile.am
pdns/recursordist/meson-dist-script.sh
pdns/recursordist/meson.build
pdns/recursordist/rec-main.cc

We take a look now if the src dir as the `.1` file. If so, we don't generated them. This work nicely for dist dirs, which contain re-built man pages, like some other pre-generated files.
I have:

rec: add meson install target and fix meson dist issues after new way of generating man pages was merged

---

builder-support/helpers/install_rust.sh
builder-support/helpers/rust.json

don't merge this until a successful build has been done!
I have:

Update Rust to 1.84.1 for our packages

---

docs/tsig.rst

Mark up tsig tables/algorithms/lengths
I have:

Mark up tsig tables/algorithms/lengths

---

docs/lua-records/index.rst

Mark up www and ip addresses
I have:

Mark up www and ip addresses

---

builder-support/helpers/install_rust.sh
builder-support/helpers/rust.json

Backport of #15164 to dnsdist-1.9.x.
(cherry picked from commit 4c6fc13c2a95bd4cf801409d12e54f2a23fa16f1)
I have:

dnsdist-1.9.x: Update Rust to 1.84.1 for our packages

---

docs/lua-records/functions.rst

link to ifurlup-options
I have:

docs: lua link to ifurlup-options

---

docs/lua-records/functions.rst

- This tries to document the behavior of #9529
I have:

docs: lua warn about first run checks

---

.github/workflows/misc-dailies.yml
build-scripts/test-recursor-bulk
tasks.py

After suggestion by @mnordhoff in IRC
I have:

rec: update umbrella top million URLs

---

pdns/recursordist/rec-rust-lib/table.py

Example given in the YAM docs is wrong.
I have:

rec: fix auth_zones yaml example

---

regression-tests.recursor-dnssec/test_FWCatz.py

rec: workaround a potential (but rare) race in the FWCatz test

---

pdns/credentials.hh

(cherry picked from commit 23dd0603511f7b34f43e8d6c121aa4277d2cb317)
Backport of #15063 
I have:

rec: Backport 15063 to rec-5.2.x: Include cstdint to get uint64_t

---

pdns/root-dnssec.hh
regression-tests.recursor-dnssec/test_TrustAnchors.py

rec: Backport 14525 to rec-5.0.x: add new root trust anchor

---

pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

auth 4.9.x: Backport "Damage control in Lua createForward() and createForward6()."

---

pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

auth 4.7.x: Backport "Damage control in Lua createForward() and createForward6()."

---

.github/workflows/build-and-test-all.yml
.github/workflows/build-docker-images-dispatch.yml
.github/workflows/build-docker-images-tags.yml
.github/workflows/build-docker-images.yml
.github/workflows/build-packages.yml
.github/workflows/builder.yml

Helps with error when cross-compiling docker images: <https://github.com/PowerDNS/pdns/actions/runs/13623217280/job/38076107466>
This PR updates the version for building packages, images, and test-builds to `ubuntu-24.04`
Test `builder.yml`: <https://github.com/romeroalx/pdns/actions/runs/13639217036>
Test `build-packages.yml`: <https://github.com/romeroalx/pdns/actions/runs/13639272782>
Test `build-docker-images.yml`: <https://github.com/romeroalx/pdns/actions/runs/13639272769>
Replaces  #15219
I have:

GH Actions: upgrade version of Ubuntu runners to 24.04

---

pdns/recursordist/docs/lua-config/rpz.rst

rec docs: elaborate on RPZ refresh parameter

---

pdns/logging.hh
pdns/recursordist/logging.cc
pdns/recursordist/logr.hh

Tidy of structured logging related files

---

pdns/dnsdistdist/dnsdist-lua-bindings-kvs.cc
pdns/dnsdistdist/dnsdist-rules-factory.hh
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-rust-lib/cxxsupport.cc

Fix a few gcc warnings on trixie

---

docs/upgrading.rst

Mention a couple behaviour changes which might matter to users when upgrading, before we forget about them.
I have:

[auth] [doc] minor documentation updates

---

meson/sanitizers/meson.build
pdns/recursordist/mtasker_context.cc

rec: comment on an issue encountered running asan on trixie and define HAVE_LEAK_SANITIZER_INTERFACE

---

build-scripts/docker/repo-test/generate-repo-files.py

repo-test: also show compiled-in features

---

pdns/pdnsutil.cc

There are two `pdnsutil` commands which, when run, print "did you mean 'different command name'?" and exit.
Now that we have good data structures to be able to dispatch `pdnsutil` command, it becomes almost trivial to add command aliases.
So instead of telling you to rework your finger muscle memory, `pdnsutil` will now be a nice lad and run the command you intended to run.
I have:

[pdnsutil] Command aliases

---

pdns/recursordist/rec-rust-lib/rust/src/web.rs

rec: more consistency in logging statements generated in web server code

---

Dockerfile-dnsdist

This PR is built on top of https://github.com/PowerDNS/pdns/pull/15284, do not merge this one first.
I have:

dnsdist: Build the `dnsdist` of our Docker image with `meson`

---

meson/code-coverage/meson.build

Properly define `COVERAGE` when code coverage is enabled via `meson`

---

pdns/dnsdistdist/docs/quickstart.rst

dnsdist: Fix a typo in the quickstart guide

---

pdns/dnsdistdist/meson/lua/meson.build
pdns/recursordist/meson.build

And cleanup `add_project_arguments` for rec while there.
I have:

rec, dnsdist: Fix symbol export on macos

---

.github/actions/spell-check/expect.txt
docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst
pdns/dnsdistdist/docs/upgrade_guide.rst

dnsdist: Update secpoll and ChangeLog for 2.0.0-alpha1

---

docs/secpoll.zone

security polling: Fix the code for DNSdist 2.0.0 alpha1

---

builder-support/debian/dnsdist/debian-bookworm/control

trixie has a new package systemd-dev that's needed for Meson to detect systemd.
I have:

dnsdist: fix package build on trixie

---

builder-support/helpers/rust.json

Upgrade Rust to 1.85.0

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc

dnsdist: Fix YAML configuration failure to build without CDB/LMDB

---

regression-tests/tests/pdnsutil-zone-handling/command

otherwise output gets the wrong order on my system
I have:

enforce LC_ALL=C for recently added sort calls

---

modules/gmysqlbackend/smysql.cc

auth-4.8.x: mysql: use MYSQL_TYPE_LONGLONG on 64bit platforms

---

regression-tests.recursor-dnssec/test_SimpleDoT.py

Previously we assumed we didn't need TCP at all.
I have:

rec: in test_SimpleDot.py make sure we have the root DNSKEY in cache, it might require TCP

---

pdns/auth-primarycommunicator.cc

We're talking about an active role here, so primary or producer.
I have:

auth: fix log string in case there are notifies needed

---

pdns/dnsdistdist/docs/advanced/luaaction.rst

See https://github.com/PowerDNS/pdns/discussions/15350
I have:

dnsdist: Document how Lua functions can be called from YAML

---

dockerdata/startup.py

rec: fix generation of recursor config if PDNS_RECURSOR_API_KEY is set

---

builder-support/debian/dnsdist/debian-bookworm/control
builder-support/specs/dnsdist.spec

This time actually tested!
I have:

dnsdist: followup to #15326 (fix build on trixie), package name typo crept in

---

pdns/dnsdistdist/docs/reference/actions.rst

Update docs for `SpoofAction()` in dnsdist 
I have:

Update actions.rst: `SpoofAction()`

---

tasks.py

Otherwise we might be trying to install a version that is no longer present in the repository, yielding a 404 error.
It might also be possible to update the base image.
I have:

tasks: Run apt-get update before installing auth test deps

---

pdns/dnsdistdist/meson.build

dnsdist with meson: Do not try to get the version/path of Python if not found

---

.github/workflows/build-and-test-all.yml

not strictly tested, but I did test against postgres 14 locally
I have:

CI: bump postgres version

---

.github/actions/spell-check/expect.txt
docs/secpoll.zone
pdns/recursordist/docs/changelog/5.2.rst
pdns/recursordist/docs/security-advisories/powerdns-advisory-2025-01.rst

rec: prep for rec-5.2.1

---

regression-tests.recursor-dnssec/test_SimpleDoT.py

rec: Backport 15352 to rec 5.2.x: in test_SimpleDot.py make sure we have the root DNSKEY in cache, it might require TCP

---

regression-tests.recursor-dnssec/test_SimpleDoT.py

rc: Backport 15352 to rec 5.0.x: in test_SimpleDot.py make sure we have the root DNSKEY in cache, it might require TCP

---

regression-tests.recursor-dnssec/test_SimpleDoT.py

rec: Backport 15352 to rec 5.1.x: in test_SimpleDot.py make sure we have the root DNSKEY in cache, it might require TCP

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/5.0.rst
pdns/recursordist/docs/changelog/5.1.rst
pdns/recursordist/docs/changelog/5.2.rst

rec: Prep for rec 20250409 releases

---

pdns/dnsdistdist/dnsdist-cache.cc
pdns/dnsdistdist/dnsdist-cache.hh
pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
pdns/dnsdistdist/fuzz_dnsdistcache.cc
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
pdns/dnsdistdist/test-dnsdistpacketcache_cc.cc

We have way too many options to keep adding them to the constructor.
I have:

dnsdist: Refactor the packet cache settings

---

pdns/dnsdistdist/docs/reference/config.rst

dnsdist: Mention the lazy health-check option more often in the docs

---

pdns/libssl.cc
pdns/libssl.hh

dnsdist: a few more cases of potentially unused args

---

docs/running.rst

auth docs: stop mentioning SysV init script, it has been gone for a while

---

docs/backends/bind.rst
docs/backends/generic-mysql.rst
docs/backends/generic-odbc.rst
docs/backends/generic-postgresql.rst
docs/backends/generic-sqlite3.rst
docs/backends/geoip.rst
docs/backends/ldap.rst
docs/backends/lmdb.rst
docs/backends/lua2.rst
docs/backends/pipe.rst
docs/backends/random.rst
docs/backends/remote.rst
docs/backends/tinydns.rst
docs/http-api/search.rst

Not all backends support searching for records and/or comments. Document this so that people aren't too disappointed when their searches do not return anything.
I have:

[auth] Mention which backends support search operations

---

pdns/dnsdistdist/test-dnsdistrings_cc.cc

Calling `BOOST_CHECK_*` is quite expensive, so this commit limits the number of these calls done in a tight loop.
I have:

dnsdist: Small optimization in the Rings unit tests

---

pdns/dnsdistdist/dnsdist-settings-definitions.yml

Remove `.` after `default` since that seems to be the style for this file...
I have:

Remove period

---

.github/workflows/build-packages.yml
.github/workflows/builder.yml
.github/workflows/codeql-analysis.yml

rec-5.0.x: switch to unbuntu-24 for workflows

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc

Backport of #15481 to rel/dnsdist-1.9.x.
The remote end might very well have already closed the HTTP stream corresponding to the timeout or response we are processing. While this means we need to discard the event we were processing, it is not an unexpected event and we should thus not raise an exception since the caller cannot do anything about it.
I have:

dnsdist-1.9.x: Backport 15481 - Gracefully handle timeout/response for a closed HTTP stream

---

.github/actions/spell-check/expect.txt
docs/secpoll.zone
docs/security-advisories/powerdns-advisory-2025-02.rst
pdns/dnsdistdist/docs/changelog.rst
pdns/dnsdistdist/docs/security-advisories/powerdns-advisory-for-dnsdist-2025-02.rst

dnsdist: Update ChangeLog and secpoll for DNSdist 1.9.9

---

pdns/dnsdistdist/docs/security-advisories/powerdns-advisory-for-dnsdist-2025-02.rst

dnsdist: Fix syntax of advisory 2025-02

---

.github/workflows/build-packages.yml
.github/workflows/builder.yml
.github/workflows/formatting.yml
.github/workflows/fuzz.yml

auth 4.9.x: move to ubuntu 24 for package building

---

modules/bindbackend/bindbackend2.cc
modules/geoipbackend/geoipbackend.cc
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
modules/lua2backend/lua2api2.hh
modules/remotebackend/remotebackend.cc
pdns/auth-primarycommunicator.cc
pdns/auth-secondarycommunicator.cc
pdns/communicator.hh
pdns/dbdnsseckeeper.cc
pdns/dnssecsigner.cc
pdns/tcpreceiver.cc
pdns/ws-api.cc
pdns/ws-api.hh

This PR is attempting to get more changes out of the views work.
The first commit addresses improvements pointed by Coverity after the merge of the `zonezilla` branch.
The next three commits are not-relevant-to-views commits which can be objectioned/vetoed/bikesheded/ignored right now and will reduce the size of the views PR (soon to hit a git repository near you).
I have:

More low-hanging fruits from the views work

---

builder-support/helpers/quiche.json

dnsdist-1.9.x: Upgrade Quiche to 0.23.4

---

builder-support/helpers/rust.json

Backport #15329 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Upgrade Rust to 1.85.0

---

builder-support/helpers/install_quiche.sh

Backport of #15440 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 15440 - If SONAME is present in the generated quiche lib set it to the correct value

---

pdns/dnsdistdist/docs/reference/dq.rst

See https://github.com/PowerDNS/pdns/pull/15508
I have:

dnsdist: Document that DNSQuestion::getIncomingInterface was backported

---

.github/workflows/build-and-test-all.yml

It seems to be broken for now:
```
🚀 Posting coverage data to https://coveralls.io/api/v1/jobs
HTTP error:
---
Error: Payment Required (402)
Message: {"message":"Repo was paused. Check your subscription.","error":true}
---
```
and I don't really care about coverage on stable branches anyway.
I have:

dnsdist-1.9.x: Disable code coverage

---

pdns/dnsdist-lua-bindings.cc

Backport of #15514 to dnsdist-1.9.x.
The object holding the callback function, which is translated into a `LuaContext::LuaFunctionCaller`, needs to be destroyed while holding the Lua mutex because it will unregister itself from the Lua context, causing a corruption if a different thread is accessing the Lua context at the same time.
I have:

dnsdist-1.9.x: Backport 15514 - Fix memory corruption when using `getAddressInfo`

---

ext/protozero/CHANGELOG.md
ext/protozero/LICENSE.md
ext/protozero/include/protozero/basic_pbf_builder.hpp
ext/protozero/include/protozero/basic_pbf_writer.hpp
ext/protozero/include/protozero/buffer_string.hpp
ext/protozero/include/protozero/data_view.hpp
ext/protozero/include/protozero/pbf_message.hpp
ext/protozero/include/protozero/pbf_reader.hpp
ext/protozero/include/protozero/types.hpp
ext/protozero/include/protozero/varint.hpp
ext/protozero/include/protozero/version.hpp

Nothing dramatic, but still nice to have.
https://github.com/mapbox/protozero/releases/tag/v1.8.0
I have:

Upgrade to protozero 1.8.0

---

pdns/dnsdistdist/docs/reference/yaml-settings.rst

The version present in our repository was not in sync with recently made changes.
I have:

dnsdist: Fix outdated YAML settings documentation

---

pdns/dnsdistdist/docs/reference/rules-management.rst

Spotted by @phonedph1 in https://github.com/PowerDNS/pdns/issues/15456, thanks!
I have:

dnsdist: Fix references to 1.10 in the documentation: it's 2.0.0

---

docs/changelog/4.9.rst
docs/secpoll.zone

For the upcoming 4.9.5 release.
I have:

auth-4.9.5 changelog & secpoll update

---

.github/workflows/build-packages.yml
.github/workflows/builder.yml

Extends #15483 
Tests [builder.yml](https://github.com/romeroalx/pdns/actions/runs/14875221811) and [build-packages.yml](https://github.com/romeroalx/pdns/actions/runs/14875221845)
I have:

dnsdist-1.9.x: Switch builder and build-packages workflows to 24.04

---

regression-tests.dnsdist/test_ProxyProtocol.py

dnsdist: Fix a flaky Proxy Protocol regression test

---

pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdist.cc
pdns/dnsdistdist/dnsdist-proxy-protocol.cc
pdns/dnsdistdist/dnsdist-proxy-protocol.hh
regression-tests.dnsdist/proxyprotocolutils.py
regression-tests.dnsdist/test_RestartQuery.py

Backport of #15534 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 15534 - Only set the proxy protocol payload size when actually added

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst
pdns/dnsdistdist/docs/security-advisories/powerdns-advisory-for-dnsdist-2025-03.rst

dnsdist: Add ChangeLog and update security polling zone for 1.9.10

---

pdns/dnsdistdist/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/dnsdist-metrics.cc
pdns/dnsdistdist/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist.hh

dnsdist: Fix one potential issue and several false positives reported by Coverity 

---

builder-support/helpers/quiche.json

dnsdist: Upgrade Quiche to 0.24.2 in our packages

---

builder-support/helpers/rust.json

Use Rust 1.87.0 when building our packages

---

.github/actions/spell-check/expect.txt
docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst
pdns/dnsdistdist/docs/conf.py

dnsdist: Add ChangeLog and update security polling zone for 2.0.0-alpha2

---

pdns/pdnsutil.cc
pdns/ws-auth.cc

Trust inet_pton to validate IPv6 addresses and nothing more

---

pdns/dnsdistdist/dnsdist-rust-lib/rust/Cargo.lock

dnsdist: Update our Rust dependencies

---

builder-support/specs/pdns-recursor.spec

I have seen reports that luajit on arm64 works.
I have:

rec: build el-9 package with luajit on arm64

---

.github/workflows/build-packages-daily-master.yml
builder-support/specs/pdns-recursor.spec
pdns/recursordist/meson.build
pdns/recursordist/meson_options.txt

Assorted things: allow longer timeout for unit tests, some options tweaking to avoid a gazillion warnings, mostly coming from boost not respecting a few deprecations.
Also build daily packages for trixie.
I have:

rec: meson packages followup

---

pdns/dnsdistdist/docs/reference/index.rst
pdns/dnsdistdist/docs/reference/selectors.rst

dnsdist docs: Place "Rule Selectors" in more appropriate place in TOC

---

pdns/dnsdistdist/dnsdist-settings-definitions.yml
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/yaml-settings.rst

dnsdist settings docs: fix derailed sentence

---

regression-tests/tests/1dyndns-update-add-invalid-record/command

dyndns test: report script failure

---

modules/bindbackend/bindbackend2.cc
pdns/dnsbackend.hh
pdns/dnsseckeeper.hh
pdns/packethandler.cc
pdns/pdnsutil.cc

Minor janitorial cleanups.
I have:

Some spring paranoia

---

pdns/ws-auth.cc

auth views http: report network typos to user

---

builder-support/dockerfiles/Dockerfile.target.amazon-2023
builder-support/dockerfiles/Dockerfile.target.centos-10-stream
builder-support/dockerfiles/Dockerfile.target.centos-9-stream
builder-support/dockerfiles/Dockerfile.target.docs
builder-support/specs/pdns-recursor.spec

rec: amazon2023 build fix + nits

---

pdns/ueberbackend.cc
pdns/ueberbackend.hh

auth: stop maintaining vector of ueberbackend instances

---

pdns/recursordist/rec-zonetocache.cc
pdns/recursordist/syncres.cc
pdns/recursordist/syncres.hh

rec: when using ZTC, do not store non-auth data if the name is subject to recursive forwarding

---

pdns/misc.hh
pdns/recursordist/test-syncres_cc4.cc
pdns/validate.cc

needs tests. EDE reporting in checkSignatureInceptionAndExpiry also needs adjusting.
I have:

rec validate: use rfc1982 math for RRSIG timestamps

---

pdns/dnsdistdist/meson/libcrypto/meson.build

dnsdist meson: followup to #15685 to avoid compiler warnings

---

pdns/dnsdistdist/dnsdist-actions-factory.cc
pdns/dnsdistdist/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-lua-ffi.hh
pdns/dnsdistdist/dnsdist.hh
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/meson.build
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
regression-tests.dnsdist/test_Protobuf.py

Closes https://github.com/PowerDNS/pdns/issues/14901
I have:

dnsdist: Add Lua APIs to set Meta tags in protobuf messages

---

docs/lua-records/functions.rst

occurred to me while reading https://github.com/PowerDNS/pdns/discussions/15644
I have:

auth docs: note that pickselfweighted() is new in auth 5

---

.github/workflows/documentation.yml
tasks.py

We need to generate the parts of the documentation sources that are no longer present in the repository before building it.
I have:

dnsdist: Fix the documentation workflow

---

docs/http-api/swagger/authoritative-api-swagger.yaml
pdns/ws-auth.cc
regression-tests.api/test_Views.py

auth views REST: don't wrap list around single network

---

modules/lmdbbackend/lmdbbackend.cc

This is commit 9ca3a5c9f17126d8a2850bf41a457f31f08f4df1 only, from #15696. 
I have:

auth-4.9.x: backport lmdb lightning stream race fix

---

docs/http-api/views.rst

remove mistaken doc section - you cannot delete views

---

builder-support/debian/recursor/debian-buster/rules
builder-support/debian/recursor/debian-trixie/rules

rec: Fix sysconfdir in debian packages built by meson

---

ext/lmdb-safe/lmdb-safe.hh
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh

This is a port of #15677.
I have:

auth-4.9.x: backport lmdb mapsize fix

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc

dnsdist: Error on unsupported backend protocols from YAML

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-configuration-yaml.hh
pdns/dnsdistdist/dnsdist-console-completion.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-settings-documentation-generator.py
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/test_Console.py

Should fix https://github.com/PowerDNS/pdns/issues/15743
I have:

dnsdist: Add a Lua binding to get objects declared in YAML

---

pdns/ednscookies.cc
pdns/tsigutils.cc

auth: Use arc4random(void *, size) in TSIG generation

---

pdns/dnsdistdist/dnsdist-lua-bindings.cc

Backport #15707 to rel/dnsdist-2.0.x
We currently return an empty `std::shared_ptr` when the backend is not set (self-answered response, for example), and unfortunately LuaWrapper is not smart enough to make that equivalent to `nil`, so testing whether the backend is valid from Lua is not possible. While I would prefer to fix that, this fix prevents us from crashing when calling the bindings associated to a backend with an empty shared pointer.
I have:

dnsdist-2.0.x: Backport 15707 - Prevent Lua bindings for backend from crashing on empty backend

---

.github/workflows/build-tags.yml

backport of #13970, which now apparently is also needed for building from non-forks
I have:

auth-4.9.x: explicit permissions in build-tags

---

.github/workflows/build-tags.yml

backport of #13970, which now apparently is also needed for building from non-forks
I have:

dnsdist-1.9.x: explicit permissions in build-tags

---

docs/changelog/4.9.rst
docs/secpoll.zone

auth-4.9.7 secpoll & changelog

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst

dnsdist: Prepare ChangeLog and security polling zone for 2.0.0-rc1

---

builder-support/dockerfiles/Dockerfile.target.el-10
builder-support/helpers/install_meson.sh
builder-support/helpers/install_quiche.sh
builder-support/helpers/install_rust.sh

dnsdist-2.0.x: Backport 15639 - Add el-10 target

---

pdns/dnsdistdist/dnsdist-protocols.cc
pdns/dnsdistdist/dnsdist-protocols.hh
pdns/dnsdistdist/dnsdist-rules-factory.hh
pdns/dnsdistdist/dnsdist-selectors-definitions.yml
pdns/dnsdistdist/dnsdist-settings-documentation-generator.py
pdns/dnsdistdist/docs/reference/selectors.rst
regression-tests.dnsdist/test_IncomingProtocol.py

Closes https://github.com/PowerDNS/pdns/issues/14060
I have:

dnsdist: Add a selector to match the incoming protocol 

---

docs/domainmetadata.rst
docs/guides/alias.rst
docs/settings.rst

This addresses a few shortcomings in the documentation.
I have:

Fewer mistakes in the auth documenation

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc

Backport of #15815 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 15815 - Properly process the YAML source parameter for backends

---

regression-tests.dnsdist/test_Console.py

dnsdist: Test accessing the rings via the console

---

pdns/zoneparser-tng.cc

strip semicolon from import files
fixes https://github.com/PowerDNS/pdns/issues/14382
I have:

fixes zone2sql include with a comment (replacement PR)

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-configuration.hh
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-settings-definitions.yml
pdns/dnsdistdist/dnsdist-web.cc
pdns/dnsdistdist/dnsdist-web.hh
pdns/dnsdistdist/dnsdist.cc
regression-tests.dnsdist/test_API.py
regression-tests.dnsdist/test_OutgoingDOH.py
regression-tests.dnsdist/test_OutgoingTLS.py
regression-tests.dnsdist/test_TLSSessionResumption.py
regression-tests.dnsdist/test_Yaml.py

Backport of #15823 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 15823 - Bring back listening on multiple web server addresses

---

pdns/dnsdistdist/Makefile.am

Stolen from Habbie, many thanks!
I have:

dnsdist: Fix out-of-tree builds with autotools

---

pdns/dnsdistdist/dnsdist-mac-address.cc
pdns/dnsdistdist/dnsdist-mac-address.hh

dnsdist: Improve the scalability of the MAC address cache

---

pdns/dnsparser.cc
pdns/dnsparser.hh

dnsdist: Small speedup for `getEDNSUDPPayloadSizeAndZ()`

---

regression-tests.dnsdist/test_Console.py

dnsdist: Test the built-in console client in our regression tests

---

pdns/dnsdistdist/Makefile.am

Backport of #15861 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 15861 - Fix out-of-tree builds with autotools

---

pdns/dnsparser.cc
pdns/dnsparser.hh

Backport of #15869 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 15869 - Small speedup for getEDNSUDPPayloadSizeAndZ()

---

.github/actions/spell-check/candidate.patterns
.github/actions/spell-check/expect.txt
.github/actions/spell-check/patterns.txt
docs/secpoll.zone
pdns/recursordist/docs/changelog/5.0.rst
pdns/recursordist/docs/changelog/5.1.rst
pdns/recursordist/docs/changelog/5.2.rst
pdns/recursordist/docs/security-advisories/powerdns-advisory-2025-04.rst
pdns/recursordist/rec-rust-lib/table.py

rec: Prep for rec 20250721 releases

---

pdns/dnsdistdist/dnsdist-actions-factory.cc
pdns/protozero-trace.cc
pdns/protozero-trace.hh
pdns/sdig.cc

Should be the last PR before beta1
I have:

rec: add version to edns record for OpenTelemetry data

---

pdns/protozero-trace.hh

rec: add a reserved/alignment byte in EDNS record

---

docs/secpoll.zone
pdns/recursordist/docs/appendices/compiling.rst
pdns/recursordist/docs/changelog/5.3.rst
pdns/recursordist/docs/upgrade.rst

rec: prep for rec-5.3.0-beta1

---

.github/actions/spell-check/expect.txt
docs/changelog/5.0.rst
docs/secpoll.zone

It's beta release time!
I have:

auth 5.0.0ß1 changelog + secpoll

---

builder-support/helpers/quiche.json

dnsdist-2.0.x: Upgrade Cloudflare's Quiche to 0.24.4

---

builder-support/helpers/quiche.json

dnsdist-1.9.x: Upgrade Cloudflare's Quiche to 0.24.4

---

regression-tests.dnsdist/test_Yaml.py

dnsdist: Test netmask exclusions via YAML

---

pdns/dnsdistdist/dnsdist-rings.hh

Backport of #15916 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: backport 15916 - Update rings' atomic counter without holding the lock

---

pdns/recursordist/docs/lua-scripting/functions.rst
pdns/recursordist/lua-recursor4.cc

(cherry picked from commit 2cf70298c17ace48a112023f68cab2e385240a1a)
Backport of #15435 
I have:

Bacport 15435 to rec-5.2.x: add a Lua function to get the config dir and name

---

pdns/recursordist/syncres.cc
pdns/recursordist/test-syncres_cc1.cc

Backport 15893 to rec-5.2.x: if a RPZ hit has a custom CNAME record, we should try harder to follow it

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/5.1.rst
pdns/recursordist/docs/changelog/5.2.rst
pdns/recursordist/docs/lua-scripting/functions.rst

rec: Prep for 5.1.7 and 5.2.5

---

docs/settings.rst
pdns/auth-main.cc
regression-tests.auth-py/test_Cookies.py

First part of #15941 (the easy one).
I have:

auth: random edns cookies

---

m4/boost.m4

Fix Boost system lib req: it is no longer a lib for boost >= 1.89

---

pdns/dnsdistdist/dnsdist.cc

dnsdist --version: report yaml support

---

.github/workflows/build-and-test-all-releases-dispatch.yml
.github/workflows/builder-releases-dispatch.yml
build-scripts/docker/repo-test/generate-repo-files.py

auth: update CI for 5.x

---

pdns/recursordist/rec-rust-lib/generate.py

rec: Path.unlink(True) requires python 3.8, rewrite so it works on older versions

---

pdns/dnsdistdist/dnsdist.cc

Backport of #15959 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 15959: dnsdist --version: report yaml support

---

builder-support/helpers/h2o.json

Backport #16034 to rel/dnsdist-1.9.x
I have:

dnsdist-1.9.x: Upgrade h2o to 2.2.6-pdns3

---

pdns/dnsdistdist/meson-dist-script.sh

dnsdist: Add missing generated files to the dist tarball

---

pdns/dnsdistdist/dnsdist-doh-common.hh
pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist-nghttp2-in.hh
pdns/dnsdistdist/doh.cc

Backport of #16007 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 16007 - Add mitigations for the HTTP/2 MadeYouReset attack

---

docs/secpoll.zone
pdns/recursordist/docs/appendices/EOL.rst
pdns/recursordist/docs/changelog/5.3.rst
pdns/recursordist/docs/upgrade.rst

rec: prep for rec-5.3.0

---

docs/appendices/EOL.rst
docs/upgrading.rst
pdns/dnsdistdist/docs/eol.rst
pdns/recursordist/docs/appendices/EOL.rst

couple of things noted during/after the auth-5.0.0 release
I have:

auth: random doc nits

---

pdns/dnsdistdist/dnsdist-async.cc
pdns/dnsdistdist/dnsdist-carbon.cc
pdns/dnsdistdist/dnsdist-configuration.cc
pdns/dnsdistdist/dnsdist-configuration.hh
pdns/dnsdistdist/dnsdist-console.cc
pdns/dnsdistdist/dnsdist-discovery.cc
pdns/dnsdistdist/dnsdist-lua-bindings.cc
pdns/dnsdistdist/dnsdist-lua-network.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-nghttp2.cc
pdns/dnsdistdist/dnsdist-resolver.cc
pdns/dnsdistdist/dnsdist-self-answers.cc
pdns/dnsdistdist/dnsdist-snmp.cc
pdns/dnsdistdist/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist-web.cc
pdns/dnsdistdist/dnsdist-xsk.cc
pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/doh3.cc
pdns/dnsdistdist/doq.cc
pdns/sholder.hh

Backport of #15874 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 15874 - Only check the freshness of the configuration when needed

---

pdns/auth-secondarycommunicator.cc

Trivial fix for #11134: instead of printing the raw `time_t`, use a human-readable form.
I have:

Display SOA check timestamps in human-readable form

---

pdns/recursordist/mkpubsuffixcc
pdns/recursordist/pubsuffix.hh
pdns/recursordist/pubsuffixloader.cc

rec pubsuffix: tidy and use C++ strings

---

pdns/dnsdistdist/meson-dist-script.sh
pdns/recursordist/meson-dist-script.sh

Partial revert of #15717
(cherry picked from commit 7d6bde8216f8871137053dcfa54d23752244237b)
I have:

Backport 16058 to rec 5.3.x: rec/dnsdist: add (back) the line that sets the version in configure.ac

---

.github/workflows/build-exotic-distributions-packages-dispatch.yml
.github/workflows/builder.yml

Add a dispatch workflow to test package building for exotic distributions

---

pdns/dnsdistdist/dnsdist.cc
regression-tests.dnsdist/test_ConfigurationUpdates.py

dnsdist: Test that the configuration is correctly reloaded in various cases

---

regression-tests.api/test_Zones.py

Once again, merging separate PRs which had green lights caused a build failure afterwards.
I have:

auth: unbreak tests

---

.github/actions/spell-check/expect.txt
pdns/recursordist/docs/http-api/index.rst
pdns/recursordist/ws-recursor.cc

rec: warn on passwordless webserver startup and extends docs

---

pdns/pdnsutil.cc

Split `EDITOR` into space separated chunks, so that it may contain options passed to the editor. This used to work when `pdnsutil` was using `system()` and got broken in the switch to `execvp()`.
I have:

pdnsutil: allow spaces in EDITOR

---

.github/PULL_REQUEST_TEMPLATE.md
.github/actions/spell-check/expect.txt
.github/workflows/dco.yml
AI_POLICY.md
CONTRIBUTING.md
DCO

This is only a draft for now, while we discuss how we want to do it.
I have:

Require Developer Certificate of Origin in pull requests

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst
pdns/dnsdistdist/docs/security-advisories/powerdns-advisory-for-dnsdist-2025-05.rst

dnsdist: Update security polling and changelog for 1.9.11, 2.0.1

---

AI_POLICY.md

Remove superfluous `the`
I have:

Remove superfluous `the`

---

.github/workflows/documentation.yml
.gitignore

We are currently not using it, so no need to waste CPU cycles on it.
I have:

documentation: Stop pushing to netlify

---

modules/pipebackend/pipebackend.cc

Noticed by dwfreed on irc.
I have:

auth: missing space in error message

---

pdns/recursordist/lwres.cc
pdns/recursordist/rec_channel_rec.cc

rec: fix a few issues reported by coverity, all minor
