pdns/dnsdist.cc

Manual backport of #13946 to rel/dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport #13946 - Also handle EHOSTUNREACH as a case for reconnecting the socket

---

builder-support/dockerfiles/Dockerfile.recursor
builder-support/dockerfiles/Dockerfile.rpmbuild

I broke them in https://github.com/PowerDNS/pdns/pull/13972 by not realizing that `jq` and the new `JSON` files were now needed during the `sdist` phase for the recursor, and also managed to use a wrong path :man_facepalming: 
I have:

Fix recursor packages builds

---

pdns/recursordist/configure.ac

This should avoid build failure on GNU Libc systems from before `res_query` moved into libc proper.
Tested on el7, testing all others in https://github.com/Habbie/pdns/actions/runs/8434779315
I have:

rec: also look for __res_query symbol

---

pdns/recursordist/test-syncres_cc8.cc
pdns/validate.cc

We need to count the number of NSEC3s that are present in the response, not the number of times we have to consider possible NSEC3s when looking for the NSEC3 closest encloser, label by label.
I have:

rec: Correctly count NSEC3s considered when chasing the closest encloser

---

pdns/misc.hh
pdns/recursordist/nod.cc
pdns/recursordist/nod.hh
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/settings/table.py
pdns/recursordist/stable-bloom.hh

This modified the threading model of the NOD/UDR subsystem. We now use a single DB, which has the big advantage that there's way less memory and disk storage used. Also, multiple threads will not report the same name, as they base their decision on the same data.
This PR also cleans up the code and introduces a setting to set the interval for the writing snapshots to disk (0 means switch the disk based snapshot mechanism off).
As a bonus the code to select the newest snap actually does what's promised. Existing code picked the oldest snap, unless I'm very confused, so please do a review for that commit with good attention to detail.
Ideally it should be confirmed that lock contention is not  an issue here. I do not expect given the number we have seen for the record cache (packet cache …

rec: use shared NOD (and/or UDR) DB, to avoid multiple copies in memory and on disk

---

builder-support/dockerfiles/Dockerfile.rpmsbom

Fix grep syntax in Dockerfile.rpmsbom. Currently shows the following error when building authoritative on `rhel>7`:
```
#48 [dist 6/6] RUN cd /pdns/builder-support/helpers/ &&     if ! $(grep -q 'release 7' /etc/redhat-release); then       for pkg in $(dnf list installed 'pdns*' | grep -E ^'pdns' | grep -vF '-debuginfo-' | cut -d. -f1); do         python3 generate-sbom-dnf.py /dist/${pkg}-4.8.0-alpha0.4469.testgeneratesbom.g177712258-el-8.cyclonedx.json ${pkg};       done;     fi
#48 0.208 grep: invalid argument 'ebuginfo-' for '--directories'
#48 0.208 Valid arguments are:
#48 0.208   - 'read'
#48 0.208   - 'recurse'
#48 0.208   - 'skip'
#48 0.208 Usage: grep [OPTION]... PATTERN [FILE]...
#48 0.208 Try 'grep --help' for more information.
#48 DONE 0.5s
```
Fix tested here: …

Dockerfile.rpmsbom:  fix grep syntax for authoritative on rhel>7

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/docs/guides/webserver.rst
pdns/dnsdistdist/doh.cc
regression-tests.dnsdist/test_DOH.py

This PR:
- increases the HTTP/1.1 query counter when a DoH connection is initiated with a `http/1.1` ALPN and the `nghttp2` provider is used, so we can detect these. We will not actually process the DoH payload (if any) anyway ;
- fix the HTTP connections counter when the `nghttp2` provider is used, as it was not updated ;
- add a regression test for these two values.
I have:

dnsdist: Fix DNS over HTTP connections/queries counters with `nghttp2` 

---

pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/test-dnsdisttcp_cc.cc

After a timeout we cannot reuse the TCP connection to the backend anyway, so let's release it immediately.
I have:

dnsdist: Release failed TCP backend connections more quickly

---

pdns/dnsdistdist/dnsdist-tcp-downstream.cc

We used to keep a shared pointer to the incoming TCP connection around in `TCPConnectionToBackend::d_currentQuery.d_sender` even after all queries sent to the backend failed, which prevented the incoming TCP connection from being closed as soon as it should have.
I have:

dnsdist: Release incoming TCP connection right away on backend failure

---

.not-formatted
pdns/dnsdistdist/dnsdist-lbpolicies.cc
pdns/dnsdistdist/docs/guides/serverselection.rst
pdns/dnsdistdist/test-dnsdistlbpolicies_cc.cc
regression-tests.dnsdist/test_Routing.py

It was not possible to indicate that all servers were unavailable from Lua FFI load-balancing policies. After this PR returning a value equal or greater than the number of servers will be interpreted as such.
Fixes https://github.com/PowerDNS/pdns/issues/13977
I have:

dnsdist: Support "no server available" result from Lua FFI LB policies

---

pdns/recursordist/settings/table.py

In particular, incoming.proxy_protocol_from and incomig.edns_padding_from
(cherry picked from commit 1d24ae8124caef413ecfc4b4279334967933a927)
Backport of #13947 
I have:

rec: Backport 13947 to rec-5.0.x: fix types of two YAML settings that should be sequences of subnets

---

pdns/recursordist/rec-main.cc

This allows dont-throttle-netmasks to have negations.
(cherry picked from commit 109aebd08611cbb148cd520c7466968873e986f7)
Backport #13966 
I have:

rec: Backport 13966 to rec-5.0.x: let NetmaskGroup parse dont-throttle-netmasks

---

pdns/recursordist/test-syncres_cc8.cc
pdns/validate.cc

We need to count the number of NSEC3s that are present in the response, not the number of times we have to consider possible NSEC3s when looking for the NSEC3 closest encloser, label by label.
(cherry picked from commit c4f4d09654bde9d389e83f0bc8eadc6b665e9de9)
Backport of #13984 
I have:

rec: Backport 13984 to rec-5.0.x: Correctly count NSEC3s considered when chasing the closest encloser

---

pdns/recursordist/test-syncres_cc8.cc
pdns/validate.cc

We need to count the number of NSEC3s that are present in the response, not the number of times we have to consider possible NSEC3s when looking for the NSEC3 closest encloser, label by label.
(cherry picked from commit c4f4d09654bde9d389e83f0bc8eadc6b665e9de9)
Backport of #13984 
I have:

rec: Backport 13984 to rec-4.9.x: Correctly count NSEC3s considered when chasing the closest encloser

---

pdns/recursordist/test-syncres_cc8.cc
pdns/validate.cc

We need to count the number of NSEC3s that are present in the response, not the number of times we have to consider possible NSEC3s when looking for the NSEC3 closest encloser, label by label.
(cherry picked from commit c4f4d09654bde9d389e83f0bc8eadc6b665e9de9)
Backport of #13984 
I have:

rec: Backport 13984 to rec-4.8.x: Correctly count NSEC3s considered when chasing the closest encloser

---

pdns/misc.hh

It turns out that some of the BPF helper functions return a negative `errno` value in case of failure, and since we wrap the return value into a `FDWrapper` right away this led to a warning from Valgrind about trying to close an invalid file descriptor.
I have:

FDWrapper: Do not try to close negative file descriptors

---

pdns/recursordist/docs/upgrade.rst
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/rec-tcp.cc
pdns/recursordist/settings/table.py
regression-tests.recursor-dnssec/test_ProxyProtocol.py

Fixes #13948
I had to move the code that retrieves the local address up to be able to check the exception for both UDP and TCP. This part of the change should be reviewed extra carefully to not have bad side-effects.
Potentially an extra syscall is done before dropping a connection/packet. 
You can use this as follows:
```yaml
incoming:
listen:
- 0.0.0.0:5301
- 0.0.0.0:5302
- '[::]:5301'
proxy_protocol_from: [127.0.0.1]
proxy_protocol_exceptions: [127.0.0.1:5302]
```
Has the effect that queries _to_ `127.0.0.1:5302` will not require proxy protocol, while queries _to_ `127.0.0.1:5301` will. Note that `proxy_protocol_from` talks about remote addresses/subnets, while `proxy_protocol_exceptions` talks about local addresses. I hope I made that clear in the docs.
I have:

Rec: add setting to exclude specific listen socket addresses from requiring proxy protocol

---

pdns/misc.hh

Backport #14006 to rel/dnsdist-1.9-x.
I have:

dnsdist-1.9-x: Backport 14006 - FDWrapper: Do not try to close negative file descriptors

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/docs/guides/webserver.rst
pdns/dnsdistdist/doh.cc
regression-tests.dnsdist/test_DOH.py

Backport of #13999 to rel/dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 13999 - Fix DNS over HTTP connections/queries counters with `nghttp2`

---

.not-formatted
pdns/dnsdistdist/dnsdist-lbpolicies.cc
pdns/dnsdistdist/docs/guides/serverselection.rst
pdns/dnsdistdist/test-dnsdistlbpolicies_cc.cc
regression-tests.dnsdist/test_Routing.py

Backport of #14001 to rel/dnsdist-1.9.x.
I have:

dnsdist-1.9.x: Backport 14001 - Support "no server available" result from Lua FFI LB policies

---

pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/test-dnsdisttcp_cc.cc

Backport #14004 to rel/dnsdist-1.9.x.
After a timeout we cannot reuse the TCP connection to the backend anyway, so let's release it immediately.
I have:

dnsdist-1.9.x: Backport 14004 - Release failed TCP backend connections more quickly

---

pdns/pkcs11signers.cc

This gets rid of two leaks reported by LeakSanitizer when running our unit tests:
```
Direct leak of 48 byte(s) in 1 object(s) allocated from:
#0 0x5fe6c6e7d099 in malloc (/pdns/pdns/testrunner+0x220099) (BuildId: 08d4c369b5f2f19f183aa5d6ab931a6653b70ab9)
#1 0x7e6cdc6a0964  (/usr/lib/libp11-kit.so.0+0x36964) (BuildId: 307da6c0b5c7d87a1b0fd0a63e0bda93c9375e8a)
Indirect leak of 72 byte(s) in 1 object(s) allocated from:
#0 0x5fe6c6e7d401 in calloc (/pdns/pdns/testrunner+0x220401) (BuildId: 08d4c369b5f2f19f183aa5d6ab931a6653b70ab9)
#1 0x7e6cdc6a09b6  (/usr/lib/libp11-kit.so.0+0x369b6) (BuildId: 307da6c0b5c7d87a1b0fd0a63e0bda93c9375e8a)
```
I have:

auth: Properly finalize PKCS11 modules before releasing them

---

m4/pdns_d_fortify_source.m4
m4/pdns_enable_lto.m4
m4/pdns_with_postgresql.m4

- configure: remove broken bashism
In a configure check that was carefully written for pre-unix-wars versions of the bourne shell, some code which was only valid using GNU bash was included.
The `==` operator is a bash-specific alias for `=`. It behaves exactly the same, except more confusing. It contains no added functionality, other than making an otherwise /bin/sh compatible script only work when /bin/sh is a symlink to /bin/bash.
- configure: remove useless multi-step check for cdb
cdb doesn't provide a pkg-config file. Debian patches one in, but theirs is broken and provides no functionality which isn't already covered by checking if -lcdb works.
The compile test is already needed in the general case, provides more accurate results even on Debian, and avoids running commands that …

configure.ac fixup: do not require bash

---

pdns/dnspacket.cc
pdns/dnspacket.hh
pdns/tcpreceiver.cc

Currently, TCP responses are not shuffled.
It seems the heuristics way back in 2005 was "when it's TCP, it's probably a zone transfer", which might have made sense back then, but not in 2024.
Fixes #13003 in the way it was suggested in the github discussion.
I have:

Do shuffle TCP responses except *XFRs

---

meson/libdecaf/meson.build
meson/pgsql/meson.build

This fixes `libdecaf` detection on Github runners. The library is installed in `/usr/local` and, when given custom directories to search in, meson doesn't add the `/lib` or `/include` postfix so we need to add those ourselves.
When given `/usr/local`, strace shows that meson searches for the library files in the given directories verbatim:
```
newfstatat(AT_FDCWD, "/usr/local/libdecaf.so", 0x7ffd8d377be0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/decaf.so", 0x7ffd8d377be0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/libdecaf.a", 0x7ffd8d377be0, 0) = -1 ENOENT (No such file or directory)
```
There's a tiny cleanup for the postgres backend.
*Do not merge until we've tested it again on the runner*.
I have:

Meson fix for `libdecaf` detection

---

modules/remotebackend/test-remotebackend-http.cc
modules/remotebackend/test-remotebackend-json.cc
modules/remotebackend/test-remotebackend-pipe.cc
modules/remotebackend/test-remotebackend-post.cc
modules/remotebackend/test-remotebackend-unix.cc
modules/remotebackend/test-remotebackend-zeromq.cc

This PR gets rid of LeakSanitizer warnings like this one:
```
Direct leak of 1 byte(s) in 1 object(s) allocated from:
#0 0x652dca6a1e12 in operator new(unsigned long) (/pdns/modules/remotebackend/remotebackend_http.test+0x1b8e12) (BuildId: f9ff2ecf3bf5e1000f1bb0cd8950e4cb9244f2e3)
#1 0x652dca6a622a in RemotebackendSetup::RemotebackendSetup() /pdns/modules/remotebackend/test-remotebackend-http.cc:78:7
#2 0x652dca6a5e1b in boost::unit_test::ut_detail::global_configuration_impl<RemotebackendSetup>::test_start(unsigned long, unsigned long) /usr/include/boost/test/tree/global_fixture.hpp:91:40
SUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s).
FAIL remotebackend_http.test (exit status: 1)
```
I have:

auth: Use smart pointers in the remote backend unit tests

---

ext/lmdb-safe/meson.build
meson.build

`lmdb-safe` needs gettime.
I have:

Meson fix: `lmdb-safe` needs gettime

---

pdns/stat_t.hh

Concentrate all the `reinterpret_cast`s in two places. Also includes a few minor type fixes in the second commit.
I have:

stat_t tidy

---

.github/workflows/build-and-test-all.yml

We need to fix some one-time allocations in the authoritative server that are reported as leaked memory before we can enable it for the authoritative server as well. See:
- https://github.com/PowerDNS/pdns/pull/14028
- https://github.com/PowerDNS/pdns/pull/14029
<strike>There is also a leak in the remotebackend unit tests that I will investigate after https://github.com/PowerDNS/pdns/pull/13960 has been merged. Fixed by https://github.com/PowerDNS/pdns/pull/14033</strike>
I have:

ci: Enable LeakSanitizer during dnsdist and recursor unit tests

---

pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/test-dnsdisttcp_cc.cc

This reverts commit 7b5f590ee72fecf54c0c40b24e98ba03a406af53.
(cherry picked from commit b3d13db2b0ddf5c5bea4c080330ac1e72475c918)
I have:

dnsdist-1.9.x: Revert "dnsdist: Release failed TCP backend connections more quickly"

---

.github/workflows/build-and-test-all.yml

CI tests got stuck because of an issue with Ubuntu's Snap repository: [see](https://github.com/PowerDNS/pdns/actions/runs/8552185020/job/23433771884)
This repository is only used for downloading the tools `yq` and `jq` during the job `collect` in `build-and-test-all`.
In order to simplify dependencies from external repos, this PR switches to a different tool - `jc` downloaded from `apt` with `jq` -  for converting `yaml` format to `json` and then using `jq` from the additional string manipulations
I have:

GH Actions: Remove yq snap dependency in collect job, workflow `build-and-test-all`

---

pdns/pdnsutil.cc

Avoids `[Error] SVCB record svcb.example.com has a target sub.svcb.example.com that has neither address nor SVCB records.` when there is a valid LUA A or LUA AAAA at the target name.
I have:

pdnsutil check-zone: accept LUA A/AAAA as SVCB address targets

---

.github/workflows/build-and-test-all.yml

This reverts commit e0bf314e472d0c1d4bc1ff82d97cabf87be1e929.
The workaround done in #13907 is no longer needed. 
Currently, this workaround is being applied to all runners independent from the runner image version. To actually apply the fix to only a specific version, the following changes should be applied in a new PR: [commit](https://github.com/romeroalx/pdns/commit/a06785722c7a7b002f6ebe4de3eb0c848d9b8e93). However, it seems is no longer needed as the current images already have in place the fix done by GitHub (check [here](https://github.com/actions/runner-images?tab=readme-ov-file#available-images))
I have:

Revert "gh actions: wo issue 9491 - actions/runner-images"

---

auth/systemd/ixfrdist.service.in
auth/systemd/pdns-auth.service.in
meson.build
meson/libsystemd/meson.build
meson/systemd/meson.build
meson_options.txt

This adds support for generating the `pdns-auth` and `ixfrdist` systemd service files.
- Creates new input service files under `auth/systemd/{pdns-auth,ixfrdist}.service.in` and generates `build/pdns-auth.service`, `build/pdns-auth@.service`, `build/ixfrdist.service` and `build/ixfrdist@.service`.
- Replaces all the weird checking for systemd features (that the Makefile does using sed and perl) using a more sane configuration dictionary.
- Adds the missing `-D systemd` configure feature to enable/disable/auto libsystemd detection for systemd notification.
I have:

Meson: `pdns-auth` and `ixfrdist` systemd service files

---

pdns/dnsdistdist/dolog.cc

Regression introduced with the logging refactoring of dnsdist.
See rel/dnsdist-1.8.x: https://github.com/PowerDNS/pdns/blob/4d5bb67a2a75f9d88894e7dfc42bbbebfda297b0/pdns/dnsdist.cc#L103
In master and 1.9.x the newly intrdoduced `LoggingConfiguration::s_syslog` is inited to `false`.
This does not matter using the default systemd unit file as it disables syslog:
```
ExecStart=@bindir@/dnsdist --supervised --disable-syslog
```
but it does matter for non-systemd cases.
I have:

dnsdist: syslog should be enabled by default

---

pdns/dnsdistdist/dnsdist-downstream-connection.hh
pdns/dnsdistdist/dnsdist-nghttp2.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.hh
pdns/dnsdistdist/dnsdist-tcp.cc
pdns/dnsdistdist/test-dnsdist-connections-cache.cc

When we are looking for an existing TCP connection to a backend to reuse, we routinely (every 60s by default) clean up existing connections from the cache.
7b5f590ee72fecf54c0c40b24e98ba03a406af53 removes a connection from the cache more aggressively when it has failed, but I did not notice that the same function might be called from the cache cleaning algorithm. It caused the cache cleanup function to call this function which in turns tried to remove the connection from the same cache, invalidating the iterator of the cache algorithm, and causing a crash when the function returned.
Better fix than https://github.com/PowerDNS/pdns/pull/14039 for master, and likely for 1.9.x after more testing.
I have:

dnsdist: Fix a crash in the Downstream TCP handler

---

meson/libdecaf/meson.build

Fixes the build in case libdecaf is not available at all for me (tested on macOS and OpenBSD)
I have:

meson: don't assume libdecaf is present when declaring dependency

---

pdns/validate.cc

I don't think we should count RRSIGs with unsupported algos towards the RRSIG limit, just like expired RRSIGs are skipped.
I found two places where the RRSIG's limit is increased if we're encountering unsupported algo's.
In `validateWithKeySet` the `checkSignatureWithKey` call currently returns `false` because `DNSCryptoKeyEngine::makeFromPublicKeyString` fails for unsupported algorithms. We must check earlier, as otherwise the counter is already increased. It does not look lik `ede` set is passed to the caller here. 
In `validateDNSKeysAgainstDS` we have a similar case. The `ede` does not seem to get used if an unsupported algo is encountered.
I have:

rec: do not count RRSIGs using unsupported algorithms towards RRSIGs limit

---

pdns/dnsdistdist/dnsdist-doh-common.cc

This was introduced in 1.9.0, with the use of the `nghttp2` library for incoming DNS over HTTP(S).
Fixes https://github.com/PowerDNS/pdns/issues/14046
I have:

dnsdist: Fix DNS over plain HTTP broken by `reloadAllCertificates()`

---

pdns/dnsdistdist/dnsdist-doh-common.cc

Backport of #14070 to rel/dnsdist-1.9.x
This was introduced in 1.9.0, with the use of the `nghttp2` library for incoming DNS over HTTP(S).
I have:

dnsdist-1.9.x: Backport 14070 - Fix DNS over plain HTTP broken by `reloadAllCertificates()`

---

pdns/xsk.cc

It turns out we need to include the linux specific headers AFTER the regular ones, because it then detects that some types have already been defined (`sockaddr_in6` for example) and does not attempt to re-define them, which otherwise breaks the C++ One Definition Rule.
I thought I fixed all of these in 1.9.2 but compiling with `g++` instead of `clang++` brought a remaining one that this PR fixes.
I have:

dnsdist: Fix "C++ One Definition Rule" warnings in XSK

---

pdns/xsk.cc

Backport of #14037 to rel/dnsdist-1.9.x.
It turns out we need to include the linux specific headers AFTER the regular ones, because it then detects that some types have already been defined (`sockaddr_in6` for example) and does not attempt to re-define them, which otherwise breaks the C++ One Definition Rule
(cherry picked from commit 679360ad842c60e38f4009cecac6e1422c747889)
I have:

dnsdist-1.9.x: Backport 14037 - Fix "C++ One Definition Rule" warnings in XSK

---

docs/appendices/backend-writers-guide.rst

For `getBeforeAndAfterNamesAbsolute()`, in case of proof of non existence for a type (and not the name), the requested name should be returned, **not** the name before it.
This is a small addition to the Backend writers’ guide
I have:

Add clarification on backend writer guide

---

pdns/recursordist/docs/lua-scripting/dq.rst

Remove `current` from the dq.extendedError* docs. Keeping `current` suggests it's a read-only field
I have:

rec: Remove `current` from the extended error code binding descriptions

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist-nghttp2-in.hh

This fixes an issue in the code dealing with incoming DNS over HTTPS queries with the nghttp2 provider. In some rare cases, if the incoming query is forwarded to the backend over TCP and the response comes back immediately (the `read()` call done just after the `write()` call sending the query must succeed and yield a complete response), the processing of the response might end up calling `IncomingHTTP2Connection::readHTTPData()` down the line, via the `nghttp2` callbacks, while we were already inside this function. This does not actually work because `nghttp2_session_mem_recv` is not reentrant, so the internal state of the `nghttp2_session` object might become inconsistent and trigger an assertion, for example:
```
nghttp2_session.c:6854: nghttp2_session_mem_recv2: Assertion …
```

dnsdist: Fix a crash in incoming DoH with nghttp2

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist-nghttp2-in.hh

Backport of #14104 to rel/dnsdist-1.9.x
This fixes an issue in the code dealing with incoming DNS over HTTPS queries with the nghttp2 provider. In some rare cases, if the incoming query is forwarded to the backend over TCP and the response comes back immediately (the `read()` call done just after the `write()` call sending the query must succeed and yield a complete response), the processing of the response might end up calling `IncomingHTTP2Connection::readHTTPData()` down the line, via the `nghttp2` callbacks, while we were already inside this function. This does not actually work because `nghttp2_session_mem_recv` is not reentrant, so the internal state of the `nghttp2_session` object might become inconsistent and trigger an assertion, for example:
```
nghttp2_session.c:6854: …
```

dnsdist-1.9.x: Backport 14104 - Fix a crash in incoming DoH with nghttp2

---

pdns/recursordist/syncres.cc
pdns/recursordist/test-syncres_cc1.cc

A name can be present already when building the cname chain.
I have:

rec: merge rec-4.9.5 back onto rel/rec-4.9.x

---

pdns/recursordist/test-syncres_cc1.cc
pdns/syncres.cc

A name can be present already when building the cname chain.
I have:

rec: merge rec-4.8.8 back onto rel/rec-4.8.x

---

pdns/validate.cc

(cherry picked from commit 834660b5c62fe7a8bcf93b0182f26fbfa5464ecc)
Backport of #14049 
I have:

rec: Backport 14049 to rec-5.0.x: do not count RRSIGs using unsupported algorithms toward RRSIGs limit

---

pdns/validate.cc

(cherry picked from commit 834660b5c62fe7a8bcf93b0182f26fbfa5464ecc)
Backport of #14049 
I have:

rec: Backport 14049 to rec-4.9.x: do not count RRSIGs using unsupported algorithms toward RRSIGs limit

---

pdns/validate.cc

(cherry picked from commit 834660b5c62fe7a8bcf93b0182f26fbfa5464ecc)
Backport of #14049 
I have:

rec: Backport 14049 to rec-4.8.x: do not count RRSIGs using unsupported algorithms toward RRSIGs limit

---

.github/workflows/build-and-test-all-releases-dispatch.yml
.github/workflows/build-and-test-all.yml

Parameterize workflow  `build-and-test-all` for running different container images as runners.
This enables solving the request introduced in #13530 for testing also using `libssl1.1`.
Before backporting to branches `rel/auth-4.9.x` and `rel/dnsdist-1.9.x`, it is required to approve and merge the PR [https://github.com/PowerDNS/base-pdns-ci-image/pull/12](https://github.com/PowerDNS/base-pdns-ci-image/pull/12) in `PowerDNS/base-pdns-ci-image`
I have:

GH actions - build-and-test-all: parameterize workflow to run different docker runner versions

---

.github/workflows/build-and-test-all.yml
tasks.py

Initial work as part of the tasks included in #13987 for building `auth` using Meson inside the `build-and-test-all` workflow.
Output binaries from the meson build are not installed but only generated (current `ci-make-install step`).
I have:

GH Actions - Meson: Build auth using meson in `build-and-test-all`.

---

.github/workflows/build-and-test-all.yml

Use `ubuntu-22.04` as runner-os instead of `ubuntu-20.04` for the `build-and-test-all` workflow. 
Required by #14090 
I have:

rec-5.0.x: gh actions - use ubuntu-22.04 runners in build-and-test-all

---

.github/workflows/build-and-test-all.yml

Backports #14132 to `rel/rec-4.9.x`: Use `ubuntu-22.04` as runner-os for the `build-and-test-all` workflow.
Required by #14092 
I have:

rec: Backport 14132 to rec-4.9.x: gh actions - build-and-test-all: use ubuntu-22.04 runners

---

.github/workflows/build-and-test-all.yml

Backports #14132 to `rel/rec-4.8.x`: Use `ubuntu-22.04` as runner-os for the `build-and-test-all` workflow.
**UPDATE:**
Partially back-ported: only for `collect` job. Some dependencies in the `build-and-test-all` workflow are not available on `ubuntu-22.04` and will require too many changes.
Required by #14094 
I have:

rec: Backport 14132 to rec-4.8.x: gh actions - build-and-test-all: use ubuntu-22.04 runners

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc

We usually buffer a bit to avoid sending a lot of small data chunks on the wire (or to the kernel anyway), but for `HTTP/2 PING` frames that are not followed by anything else calling for a response, this causes an issue as these frames are designed to measure the latency between a client and a server, and are used by HTTP/2 proxies to ensure that a connection can be reused.
I have:

dnsdist: Reply to HTTP/2 PING frames immediately

---

.github/workflows/build-and-test-all.yml

This PR makes the path from where the runner container image is pulled fixed to `powerdns`.
In #14061, it was introduced the path to be read from the context variable `github.repository`, but this broke the CI for forks of this repo, as reported in the same PR.
I have:

GH Actions: fix the repository where the runner images are pulled from

---

.github/workflows/build-and-test-all.yml

Backport of #14044 for the removal of snap dependencies.
In addition, the job `collect` from `build-and-test-all` will now run on `ubuntu-22.04`, where the package `jc` is available. 
I have:

dnsdist: Backport 14044 to dnsdist-1.7.x: gh actions - replace yq snap in collect job build-and-test-all

---

.github/workflows/build-and-test-all.yml

Backport of #14044 for the removal of snap dependencies.
In addition, the job `collect` from `build-and-test-all` will now run on `ubuntu-22.04`, where the package `jc` is available. 
I have:

dnsdist: Backport 14044 to dnsdist-1.8.x: gh actions - replace yq snap in collect job build-and-test-all

---

docs/settings.rst
pdns/auth-main.cc
pdns/auth-main.hh
pdns/dnsrecords.cc
regression-tests.auth-py/test_LuaRecords.py

backport of #14021, but with the default flipped to 'yes', which matches behaviour of previous versions
I have:

auth-4.9 LUA: (optionally) drop whitespace on join

---

pdns/dnsdistdist/dnsdist-idstate.cc
pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist.cc
regression-tests.dnsdist/quictests.py
regression-tests.dnsdist/test_DOH.py
regression-tests.dnsdist/test_DOH3.py
regression-tests.dnsdist/test_DOQ.py

We did not properly handle incoming XFR requests received over DoH When a TCP-only or DoT backend was configured, and the nghttp2 provider used.
This commits fixes the assertion failure and makes sure that XFR requests are denied with `NOTIMP` when received over DNS over HTTPS, including DNS over HTTP/3. It also denies them when received over DNS over QUIC as this is not properly handled at the moment, although it does not cause a crash.
I have:

dnsdist: Fix handling of XFR requests over DoH

---

pdns/dnsdistdist/dnsdist-web.cc

The `registerWebHandler()` Lua method can be used to tie a custom Lua function to an HTTP endpoint. This function was clearly not intended to be used at runtime but this was never enforced, so let's prevent a race condition by wrapping the internal web handlers map in a lock.
I have:

dnsdist: Prevent a race when calling `registerWebHandler` at runtime

---

.clang-tidy.bugs
.clang-tidy.full

Self explanatory, the reason is that most of the time (e.g. logging) we want the flushing that comes with using `endl` as opposed to using `'\n'`.
I have:

Disable clang-tidy's `performance-avoid-endl` check

---

meson.build
modules/bindbackend/meson.build
modules/geoipbackend/meson.build
modules/gmysqlbackend/meson.build
modules/godbcbackend/meson.build
modules/gpgsqlbackend/meson.build
modules/gsqlite3backend/meson.build
modules/ldapbackend/meson.build
modules/lmdbbackend/meson.build
modules/lua2backend/meson.build
modules/meson.build
modules/pipebackend/meson.build
modules/remotebackend/meson.build
modules/tinydnsbackend/meson.build

This simplifies the handling of modules, and puts the backend file artifacts in a directory similar to how autotools did it, this helps simplify adapting the regression tests harness to support our Meson builds.
All the files that are `modules/*backend/meson.build` were changed the same way: The library creation was removed from there and the source and extra files variable were renamed to `module_sources` and `module_extras`.
Then the handling of modules was moved from the top-level `meson.build` into `modules/meson.build` and made a bit more generic to handle the creation of library artifacts for each backend there.
I have:

Meson: Move modules handling to `modules/` dir

---

.github/workflows/build-and-test-all.yml
pdns/dnsdistdist/dnsdist.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec_channel_rec.cc
pdns/recursordist/recursor-tsan.supp
regression-tests.recursor-dnssec/recursortests.py

Mostly inspired by/copied from #14143. Same considerations wrt tsan apply. I tried calling `rec_control quit-nicely`, but that causes a race: the `rec_control` command finishes before rec has actually quit, so the kill code would be activated anyway, especially with tsan enabled quitting takes some time.
I' marking this a draft: 
- I see the occasional segfault in the dnstap nod tests. To be investigated.
- I need to double check that actual leaks in CI are detected (I did a local test already)
I have:

rec: enable lsan in regression tests

---

.github/workflows/build-and-test-all.yml

Backport of #14044 for the removal of snap dependencies.
In addition, the job `collect` from `build-and-test-all` will now run on `ubuntu-22.04`, where the package `jc` is available. 
I have:

auth: Backport 14044 to auth-4.7.x: gh actions - replace yq snap in collect job build-and-test-all

---

.github/workflows/build-and-test-all.yml

Backport of #14044 for the removal of snap dependencies.
In addition, the job `collect` from `build-and-test-all` will now run on `ubuntu-22.04`, where the package `jc` is available. 
I have:

auth: Backport 14044 to auth-4.8.x: gh actions - replace yq snap in collect job build-and-test-all

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc

Backport of #14128 to dnsdist-1.9.x
We usually buffer a bit to avoid sending a lot of small data chunks on the wire (or to the kernel anyway), but for `HTTP/2 PING` frames that are not followed by anything else calling for a response, this causes an issue as these frames are designed to measure the latency between a client and a server, and are used by HTTP/2 proxies to ensure that a connection can be reused.
I have:

dnsdist-1.9.x: Backport of 14128 - Reply to HTTP/2 PING frames immediately

---

pdns/pdnsutil.cc

auth 4.9: pdnsutil check-zone: accept LUA A/AAAA as SVCB address targets

---

m4/pdns_check_time_t.m4

auth 4.9: m4: Add option for 64-bit time_t on 32-bit systems with glibc-2.34

---

pdns/bindparser.yy
pdns/named.conf.parsertest

Some tokens were not properly freed: ACL names and entries, unused word or quoted string terms. This is limited to the parsing of the bind file format, zones themselves are fine, so there is no security impact.
Found by LeakSanitizer over our existing unit tests.
I have:

auth: Fix memory leaks in the bind file format parser

---

pdns/bindparser.yy
pdns/named.conf.parsertest

auth-4.9: Fix memory leaks in the bind file format parser

---

Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor

Test run: [https://github.com/romeroalx/pdns/actions/runs/9172324832](https://github.com/romeroalx/pdns/actions/runs/9172324832)
I have:

dnsdist-1.8.x: Partial backport of #14171 for fixing the build of arm64 images

---

Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor

Test run: [https://github.com/romeroalx/pdns/actions/runs/9172326975](https://github.com/romeroalx/pdns/actions/runs/9172326975)
I have:

dnsdist-1.9.x: Partial backport of #14171 for fixing the build of arm64 images

---

Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor

Test run: [https://github.com/romeroalx/pdns/actions/runs/9172260927](https://github.com/romeroalx/pdns/actions/runs/9172260927)
I have:

rec-5.0.x: Partial backport of #14171 for fixing the build of arm64 images

---

Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor

Test run: [https://github.com/romeroalx/pdns/actions/runs/9172272280](https://github.com/romeroalx/pdns/actions/runs/9172272280)
I have:

rec-4.9.x: Partial backport of #14171 for fixing the build of arm64 images

---

Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor

Test run: [https://github.com/romeroalx/pdns/actions/runs/9172276837](https://github.com/romeroalx/pdns/actions/runs/9172276837)
I have:

rec-4.8.x: Partial backport of #14171 for fixing the build of arm64 images

---

pdns/dnsdistdist/dnsdist-ecs.cc
pdns/ednsoptions.cc
pdns/ipcipher.cc

PowerDNS Security Advisory 2024-03 has made it clear that some of them that have been designed to break during testing might break in production, as we compile with `NDEBUG` unset.
I have:

dnsdist: Get rid of `assert()`

---

pdns/devpollmplexer.cc
pdns/epollmplexer.cc
pdns/kqueuemplexer.cc
pdns/mplexer.hh
pdns/pollmplexer.cc
pdns/portsmplexer.cc
pdns/recursordist/Makefile.am
pdns/recursordist/docs/upgrade.rst
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/ratelimitedlog.hh
pdns/recursordist/rec-main.cc

- Warn when `vm.max_map_count` is dangerously low and adjust `max-mthreads` accordingly
- Fix a few cases where lack of logging could hide bad errors.
- Don't let recursorthead die on exceptions for the pdns-distributes-queries=no case
- Use rate limited logging for the logging in these cases
Not that the rate limited logging is not very smart, it throws all logging calls in one basket.
You might want to see part of the diff with whitespace ignored, it boils down to indenting changes due to an introduce try/catch block.
Fixes the logging part of #14180 
I have:

rec: log vm.max_map_count possibly being too low and log a few exceptions (with rate limiting)

---

pdns/dnsdist.cc
pdns/dnsdistdist/doh3.cc
pdns/dnsdistdist/doq-common.cc
pdns/dnsdistdist/doq-common.hh
pdns/dnsdistdist/doq.cc
pdns/iputils.cc
pdns/iputils.hh
regression-tests.dnsdist/quictests.py
regression-tests.dnsdist/test_DOH3.py
regression-tests.dnsdist/test_DOQ.py

Backport of #14078 to rel/dnsdist-1.9.x
And expose the correct destination IP to Lua.
I have:

dnsdist-1.9.x: Backport of #14078 - Use the correct source IP for outgoing QUIC datagrams

---

pdns/dnsdistdist/docs/reference/config.rst

Detail return values  for `Server:isUp()` method and `Server.upStatus` attribute to clarify behavior related to the server being administratively set UP or DOWN.
Closes #14217
I have:

dnsdist: Clarify server status documentation

---

ext/yahttp/yahttp/utility.hpp

The default values, 8192 bytes for the maximum request line size and 100 fields, are taken from the default settings of Apache HTTPd:
- https://httpd.apache.org/docs/2.2/mod/core.html#limitrequestline
- https://httpd.apache.org/docs/2.2/mod/core.html#limitrequestfields
Reported by OSS-Fuzz as a timeout in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67993
(cherry picked from commit 249c86a63865e4a980511839887890c3940fc6e6)
Backport of #14197 
I have:

rec: Backport 14197 to rec 5.0.x: YaHTTP: Enforce max # of request fields and max request line size 

---

ext/yahttp/yahttp/utility.hpp

auth-4.9 YaHTTP: Enforce max # of request fields and max request line size

---

Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor

Test run: [https://github.com/romeroalx/pdns/actions/runs/9172307456](https://github.com/romeroalx/pdns/actions/runs/9172307456)
I have:

auth-4.7.x: Partial backport of #14171 for fixing the build of arm64 images

---

Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor

Test run: [https://github.com/romeroalx/pdns/actions/runs/9172305113](https://github.com/romeroalx/pdns/actions/runs/9172305113)
I have:

auth-4.8.x: Partial backport of #14171 for fixing the build of arm64 images

---

regression-tests.recursor-dnssec/test_Protobuf.py

We want to make sure `requestorId`, `deviceId` and `deviceName` reflect what is set in `gettag(_ffi)`. Test that explicitly by appending the remote port to the values used (and make sure the port is different for the two test requests).
Port is convenient, as it is available in both `gettag` and `gettag_ffi`.
I have:

rec: add a few more cases for the Protobuf tests wrt deviceID and friends

---

pdns/recursordist/RECURSOR-MIB.txt
pdns/recursordist/docs/metrics.rst
pdns/recursordist/lwres.cc
pdns/recursordist/lwres.hh
pdns/recursordist/mtasker.hh
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/rec-snmp.cc
pdns/recursordist/rec-tcounters.hh
pdns/recursordist/rec-tcp.cc
pdns/recursordist/rec_channel_rec.cc
pdns/recursordist/settings/table.py
pdns/recursordist/syncres.cc
pdns/recursordist/syncres.hh
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/ws-recursor.cc
regression-tests.recursor-dnssec/test_SNMP.py

- When the number of concurrent requests is high, reduce the timeout we are willing to wait for the auth's reply.  
- Improvements in the handling of long or old chains. 
- Add the possibility to reduce max chain length (default off). Includes metrics see see better what is going on.
I have:

rec: handle auths slow to respond when load is high better

---

pdns/recursordist/docs/http-api/zone.rst
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/ws-recursor.cc
regression-tests.api/test_Zones.py

Closes #14116
Allows setting `notify_allowed` when adding forwarded zones through the Recursor API.  This works with the new YAML settings and the old-style settings.  If `notify_allowed` is not sent or is set to false, the behavior is unchanged.  If `notify_allowed` is set to true the Recursor will allow NOTIFY to clear cache for the given zone.
I have:

Allow setting notify_allowed in Recursor API for forwarded zones

---

m4/systemd.m4

Support systemd prerelease versions, like example 256~rc3. Also preemptively support versions like 252.2.
Without this, configure prints:
```
./configure: line 21310: test: 256~rc3: integer expression expected
...
```
And I assume it turns off the newer features.
I have:

autoconf: allow prerelease systemd versions

---

pdns/recursordist/settings/generate.py
pdns/recursordist/settings/rust/src/bridge.rs

Case in generated code:
```
warning: assigning the result of `ToOwned::to_owned()` may be inefficient
--> src/lib.rs:2242:17
|
2242 | ...   self.unique_response_history_dir = rhs.unique_response_history_dir.to_owned...
|       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_into()`: `rhs.unique_response_history_dir.clone_into(&mut self.unique_response_history_dir)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
```
I have:

rec: make clippy happy

---

pdns/recursordist/rec-main.cc
pdns/recursordist/rec_channel_rec.cc
pdns/recursordist/settings/cxxsupport.cc

@rgacogne when reviewing could you also check the coverity reports on iputils? I *think* they are false positives, but this is tricky stuff. rec has two of them, dnsdist one.
I have:

rec: fix cases of copy instead of move, as reported by coverity

---

pdns/pdnsutil.cc

Merge #14011 added checking for LUA records to checkZone(), but LUA records depend on --enable-lua-records and the change causes a build error without.
I have:

pdnsutil check-zone: make LUA records optional

---

pdns/recursordist/docs/appendices/FAQ.rst
pdns/recursordist/settings/table.py

As discussed in https://github.com/PowerDNS/pdns/issues/14263 the behavior of the recursor is as expected but as older versions of dig +trace use RD=0 queries and fail when no data is returned i thought it best to document this.
I have:

rec: allow_no_rd - document cache contents on root on startup pertaining to dig +trace

---

meson/auto-var-init/meson.build

Auth/meson: Don't fail if compiler doesn't support `trivial-auto-var-init`.
This will issue a warning instead and print out a summary line that the compiler doesn't support it.
This should fix the issue here: https://github.com/PowerDNS/pdns/actions/runs/9309740577/job/25625817149
I have:

Auth/meson: Don't fail if compiler doesn't support `trivial-auto-var-init`

---

modules/remotebackend/httpconnector.cc

Add missing field name of "auth" and ampersand between records.
Use `pdnsutil` to add following RR set to an auth server with remote backend and HTTP connector:
```
foo.example.com. 100 IN TXT "foo"
foo.example.com. 100 IN TXT "bar"
```
The backend HTTP server will receive `replaceRRSet` request body like:
`1&rrset[0][content]=%22foo%22&rrset[0][qclass]=1&rrset[0][qname]=foo%2eexample%2ecom%2e&rrset[0][qtype]=TXT&rrset[0][ttl]=1001&rrset[1][content]=%22bar%22&rrset[1][qclass]=1&rrset[1][qname]=foo%2eexample%2ecom%2e&rrset[1][qtype]=TXT&rrset[1][ttl]=100`.
The field name of "auth" (`rrset[0][auth]`, `rrset[1][auth]`) and the ampersand between the two RRs (`1001`) are missing.
I have:

remotebackend: Fix http request of replaceRRSet

---

pdns/dnsdistdist/dnsdist-dynblocks.cc

Introduced in 099e95eee273937d666255dc7ebe510d717b4a07 (#14182), spotted by Coverity. Needs to be backported if we decide to backport #14182.
I have:

dnsdist: Fix a user-after-move in the dynamic rules SMT code

---

pdns/dnsdistdist/dnscrypt.hh

These are always properly initialized later in the code but Coverity is not convinced, and it's good practice to initialize them anyway.
I have:

dnsdist: Initialize DNSCrypt structures

---

.github/workflows/build-docker-images-dispatch.yml
.github/workflows/build-docker-images-tags.yml
.github/workflows/build-docker-images.yml
.github/workflows/docker.yml

Only commit [c5727aa](https://github.com/PowerDNS/pdns/pull/14289/commits/c5727aa8f8b0a3fa360c03fb1f2728624de50070) is really needed but all commits in the Pull Request were cherry-picked for context.
I have:

auth-4.9.x: backport of #14171 for fixing the build of images on new tags

---

docs/http-api/index.rst
docs/settings.rst
pdns/auth-main.cc
pdns/webserver.cc
pdns/webserver.hh
pdns/ws-auth.cc

In the REST API, make the timeout for reading requests and writing responses configurable.
I have:

auth web: make request/response timeout configurable

---

docs/http-api/index.rst
docs/settings.rst
pdns/auth-main.cc
pdns/webserver.cc
pdns/webserver.hh
pdns/ws-auth.cc

In the REST API, make the timeout for reading requests and writing responses configurable.
Backport of #14218
I have:

auth web: Backport 14218 to auth-4.8.x: make request/response timeout configurable

---

pdns/dnsdistdist/dnsdist-tcp.cc

There is a dangling '%' at the end of the format string, which is only a formatting issue because of the way our logger works but is still ugly.
I have:

dnsdist: Fix 'Error creating TCP worker' error message

---

pdns/dnsdistdist/dnsdist.service.in

We used to be able to use only `CAP_BPF` since kernel 5.8, but the eBPF verifier has been made more strict a few versions later and we now require `CAP_SYS_ADMIN` again.
I have:

dnsdist: Edit the systemd unit file, `CAP_BPF` is no longer enough

---

.github/workflows/misc-dailies.yml

Set python-version 3.11 for complying with pip pinning in `misc-dailies.yml`.
Fixes an error in the CI for pip packages not being pinned: [https://github.com/PowerDNS/pdns/actions/runs/9395185097/job/25874138446](https://github.com/PowerDNS/pdns/actions/runs/9395185097/job/25874138446)
I have:

GH Actions - misc-dailies: set python-version 3.11 for complying with pip pinning

---

pdns/recursordist/rec-main.cc
pdns/recursordist/settings/table.py
pdns/recursordist/syncres.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc1.cc

While working on this, I saw a inconsistency in the result, depending on the CNAME being in cache or not.
See the comment in `test-syncres_cc1.cc`. 
I have:

rec: make max CNAME chain length handled settable, previously fixed at 10

---

contrib/ProtobufLogger.py
pdns/recursordist/lwres.cc
pdns/recursordist/rec-protozero.cc
pdns/recursordist/rec-protozero.hh

As noted by @johnhtodd 
UDR field is optional, and is not determined yet at the point where the outgoingProtobuf message is created.
I have:

rec: do not add UDR field to outgoingProtobuf answer messages

---

.github/workflows/build-and-test-all.yml
meson.build
regression-tests/backends/bind-master
regression-tests/backends/geoip-master
regression-tests/backends/gmysql-master
regression-tests/backends/godbc_mssql-master
regression-tests/backends/godbc_sqlite3-master
regression-tests/backends/gpgsql-master
regression-tests/backends/gsql-common
regression-tests/backends/gsqlite3-master
regression-tests/backends/ldap-master
regression-tests/backends/lmdb-master
regression-tests/backends/lua2-master
regression-tests/backends/remote-master
regression-tests/backends/tinydns-master
regression-tests/runtests
regression-tests/start-test-stop
tasks.py

Adds meson support into the auth backend regression tests harness.
The CI parts are still missing and I'll add them in a later PR, they're quite the headache for now. 
I have:

Support meson in regression tests harness

---

pdns/dnsdistdist/docs/advanced/ebpf.rst
pdns/dnsdistdist/docs/reference/config.rst

We used to be able to use only `CAP_BPF` since kernel 5.8, but the eBPF verifier has been made more strict a few versions later and we now require `CAP_SYS_ADMIN` again.
I have:

dnsdist: Document that eBPF socket filtering requires `CAP_SYS_ADMIN`

---

pdns/dnsdistdist/dolog.cc

Regression introduced with the logging refactoring of dnsdist.
In rel/dnsdist-1.8.x: https://github.com/PowerDNS/pdns/blob/4d5bb67a2a75f9d88894e7dfc42bbbebfda297b0/pdns/dnsdist.cc#L103
In master and 1.9.x the newly introduced `LoggingConfiguration::s_syslog` is initialized to `false`.
This does not matter using the default systemd unit file as it disables syslog:
```
ExecStart=@bindir@/dnsdist --supervised --disable-syslog
```
but it does matter for non-systemd cases.
(cherry picked from commit 22931f35e56ff2c0b5e2147c157a5a765d60b8a2)
I have:

dnsdist-1.9.x: Backport of #14050: Syslog should be enabled by default

---

pdns/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist-tcp-upstream.hh

Backport of #14131 to dnsdist-1.9.x.
I have:

dnsdist-1.9.x: Backport of 14131: Log the correct amount of bytes sent for DoH w/ nghttp2

---

ext/yahttp/yahttp/utility.hpp

Backport of #14197 to dnsdist-1.9.x
The default values, 8192 bytes for the maximum request line size and 100 fields, are taken from the default settings of Apache HTTPd:
- https://httpd.apache.org/docs/2.2/mod/core.html#limitrequestline
- https://httpd.apache.org/docs/2.2/mod/core.html#limitrequestfields
Reported by OSS-Fuzz as a timeout in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67993
I have:

dnsdist-1.9.x: Backport of 14197: YaHTTP: Enforce max # of request fields and max request line size

---

m4/systemd.m4

Backport of #14247 to dnsdist-1.9.x.
I have:

dnsdist-1.9.x: Backport of 14247: autoconf: allow prerelease systemd versions

---

pdns/dnsdistdist/dnsdist.service.in

Backport of #14281 to dnsdist-1.9.x
We used to be able to use only `CAP_BPF` since kernel 5.8, but the eBPF verifier has been made more strict a few versions later and we now require `CAP_SYS_ADMIN` again.
I have:

dnsdist-1.9.x: Backport of 14281: Edit the systemd unit file, `CAP_BPF` is no longer enough

---

pdns/dnsdist-tcp.cc

Backport of #14270 to dnsdist-1.9.x.
There is a dangling '%' at the end of the format string, which is only a formatting issue because of the way our logger works but is still ugly.
I have:

dnsdist-1.9.x: Backport of 14270: Fix 'Error creating TCP worker' error message

---

pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc

Backport of #14255 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport of 14255: Add a Lua FFI function to set proxy protocol values

---

pdns/test-dnsdist_cc.cc

Backport of #14162  to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport of 14162: Fix a warning when compiling the unit tests without XSK

---

pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-tcp.cc
regression-tests.recursor-dnssec/test_ProxyProtocol.py

All other remote counts use the address substituted by the ProxyProtocol, so `remote` should as well.
In an ideal world we should also test  the other `remote` counts produced by https://docs.powerdns.com/recursor/http-api/endpoint-jsonstat.html#get--jsonstat
I have:

rec: fix client remotes count when using proxy protocol

---

pdns/dnsdistdist/dnsdist-snmp.cc
pdns/recursordist/rec-snmp.cc
pdns/snmp-agent.cc
pdns/snmp-agent.hh

The net-snmp headers are unfortunately defining things that we do not want, like `INET6` and `HAVE_LIBSSL`, so it's better for us not to include them from our headers.
Hopefully closes https://github.com/PowerDNS/pdns/issues/11204
I have:

snmp-agent: Move net-snmp headers out of our headers

---

pdns/dnsdistdist/dnsdist-lua-web.cc
pdns/dnsdistdist/dnsdist-web.cc

Custom web handlers written in Lua modify the global Lua context, but until now they did not take the lock protecting it so a data race condition was possible.
Reported by TSAN while running our unit tests.
I have:

dnsdist: Fix a race condition with custom Lua web handlers

---

pdns/dnsdist-web.cc
pdns/dnsdistdist/dnsdist-lua-web.cc

Backport of #14341 to dnsdist-1.9.x
Custom web handlers written in Lua modify the global Lua context, but until now they did not take the lock protecting it so a data race condition was possible.
Reported by TSAN while running our unit tests.
I have:

dnsdist-1.9.x: Backport of 14341: Fix a race condition with custom Lua web handlers

---

m4/systemd.m4

For example 256~rc3. Also preemptively support versions like 252.2.
(cherry picked from commit 81e3f38b1909956e228077e4677c34f469ea9835)
Backport of #14247 
I have:

rec: Backport 14247 to rec 5.0.x: autoconf: allow prerelease systemd versions

---

builder-support/specs/dnsdist.spec

The initial commit (7b070182728b4537489fcf33e6c382a93becb4a9) was added in https://github.com/PowerDNS/pdns/pull/14241 and needs to be backported to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport "skip libxdp-devel for rhel8-aarch64"

---

.github/workflows/build-and-test-all-releases-dispatch.yml
.github/workflows/builder-releases-dispatch.yml

Branch`rel/auth-4.6` is no longer maintained. This PR removes this branch from the scheduled workflows `build-and-test-all-releases-dispatch.yml` and `builder-releases-dispatch.yml`
I have:

GH Actions: remove rel/auth-4.6.x from daily/weekly builds

---

pdns/dns.cc
pdns/views.hh

Includes minor cleanup and additions to make UnsignedCharView usable for this use case. Supersedes #14356
Fixes
```
/usr/include/c++/v1/__fwd/string_view.h:22:41: warning: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 19, so please migrate off of it. [-Wdeprecated-declarations]
```
I have:

dns.cc: use pdns::views::UnsignedCharView

---

contrib/ProtobufLogger.py
pdns/recursordist/lwres.cc

As there is no good existing field, I opted to add it as a meta field.  
An example of a pb mesage as decoded by `contrib/ProtobufLogger.py`
Tagging @johnhtodd  as he mentioned absence of ns name in the outgoing protobuf messages.
```
[2024-06-12 11:27:56.977200] Query (O) of size 52: N/A(N/A) -> 84.53.175.157:53 (UDP) id: 46200 uuid: b'409a2bd67737411cbe32130bdd314832', initial uuid: b'e1b4901623d04a6482db42fecf2472c9'  requestorid: N/A deviceid: N/A devicename: N/A serverid: b'mbp.local' nod: N/A workerId: N/A pcCacheHit: N/A outgoingQueries: N/A
- (meta) nsName -> n1b.akamaiedge.net
- Question: 1, 1, e67691.b.akamaiedge.net.
[2024-06-12 11:27:56.990436] Response (I) of size 84: N/A(N/A) -> 84.53.175.157:53 (UDP) id: 46200 uuid: b'409a2bd67737411cbe32130bdd314832', initial uuid: …
```

rec: add nsName into outgoing protobuf request/response messages

---

pdns/test-distributor_hh.cc

This unit test is checking that we correctly throw when too many queries are waiting in the distribution pipe, by making the mock backend slow on purpose. Once the distributor has been restarted as expected, we need to wait until the mock backend has processed all queued queries, otherwise Leak Sanitizer will rightfully report a memory leak.
I have:
=

auth: Better fix for the leak reported by LSAN in test-distributor_hh.cc

---

builder-support/debian/recursor/debian-buster/rules
builder-support/specs/pdns-recursor.spec
pdns/recursordist/Makefile.am
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/rec_control.cc
pdns/recursordist/reczones.cc
pdns/recursordist/settings/docs-new-preamble-in.rst

This should allow us to work around the packaging issues discussed in #13935. The idea is that modify the parsing so that .conf files also *may* contain YAML.
The search for a config file then becomes:
1. Try reading `recuror.yml` if it exists. If valid, done. If it is invalid punt.
2. Try reading `recursor.conf` as YAML. If it is valid, done.
3. If it is invalid, try to read as old-style.
This means that the status of `recursor.conf` as a config file in the packaging meta data does not need to change.
This allows us to install a default YAML config into `recursor.conf` for new installs. Of course we leave `recursor.conf` alone for existing installs.
This is a draft. I will add docs and packaging changes after this is deemed the way to proceed.
@zeha could you check if this approach is …

rec: allow recursor.conf file to contain YAML to ease transition to YAML config

---

pdns/recursordist/pdns_recursor.cc
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_DNS64.py

rec: Backport 14373 to rec 5.0.x:  Remove potential double SOA records if the target of a dns64 name is NODATA

---

pdns/misc.cc
pdns/misc.hh

It might even be the case that this (marking `unixDie` as `[[noreturn]]`) makes Coverity realize pos does not overflow.
I have:

Cleanup read2n and mark unixDie as [[noreturn]]

---

meson.build
modules/lmdbbackend/meson.build

Fix the LMDB backend not finding symbols in `pdns-auth` and `pdns-auth-util`. This ended up being much simpler than the original route I had taken of doing lots of refactoring. I went down the wrong path because I was under the impression that some of those missing symbols were missing in the module itself and not in the executable that is loading the module (e.g. `pdns-auth` or `pdns-auth-util`).
I have:

Fix the LMDB backend not finding symbols in `pdns-auth` and `pdns-auth-util`

---

meson.build

Avoids on FreebSD and macOS:
```
In file included from ../pdns/uuid-utils.cc:23:
../pdns/uuid-utils.hh:24:10: fatal error: 'boost/uuid/uuid.hpp' file not found
```
I have:

auth: followup to 14370: add boost depedendency

---

builder-support/debian/recursor/debian-buster/pdns-recursor.maintscript
builder-support/debian/recursor/debian-buster/recursor.lua
builder-support/debian/recursor/debian-buster/rules

(cherry picked from commit 6b2d9507dab4d64623bbca6fcd3bbd57ddebff8e)
Backport of #14384 
I have:

rec: Backport 14384 to rec-5.1.x: keep Lua config as existing configs might use it 

---

pdns/dnsdistdist/doq.cc
pdns/dnsdistdist/m4/pdns_with_quiche.m4

Quiche broke its existing API in 0.22.0: https://github.com/cloudflare/quiche/pull/1726 
This pull request adds m4 code to detect whether the Quiche version we are building against is `>= 0.22.0`, and if it is defines `HAVE_QUICHE_STREAM_ERROR_CODES` which is later used by the code using Quiche to know which version of the API to use.
I have:

dnsdist: Handle Quiche >= 0.22.0

---

pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-lua-bindings.cc
pdns/dnsdistdist/dnsdist-web.cc
pdns/dnsdistdist/dnsdist.hh

While there should not be much risk in a data race involving a boolean apart from getting an outdated value, it's still undefined behaviour and it rightfully makes TSAN unhappy.
This commit makes the status atomic: hopefully using relaxed memory ordering when reading the status will make it as cheap as a regular non-atomic read on most platforms.
I have:

dnsdist: Fix a race when accessing a backend health status

---

.github/workflows/build-packages.yml

The gist is to upload the SLSA attestations (.json files) to the correct folder on the remote server ($product/$version/) instead of copying them in the home folder like we do today.
I have unfortunately not tested the change with the actual workflow so please review it carefully!
I have:

build-packages: Upload SLSA attestations to the right directory

---

.not-formatted
pdns/recursordist/syncres.cc
pdns/recursordist/syncres.hh
pdns/recursordist/test-syncres_cc2.cc

This adds the (last) reason an entry was added/updated in the throttle table:
```
$ ./rec_control dump-throttlemap -
...
217.160.80.19	nytrng.com	A	3	2024-07-02T12:35:58	RCodeRefused
205.251.196.19	e-volution.ai	A	5	2024-07-02T12:35:21	Timeout
15.203.224.34	c0044539.itcs.hp.com	A	100	2024-07-02T12:35:57	PermanentError
...
```
I have:

rec: show throttle reason

---

pdns/libssl.hh

`../pdns/libssl.cc:637:28: error: no member named 'content' in 'OpenSSLTLSTicketKey'`
Followup to #14327 
I have:

Fix compile error on OPENSSL_VERSION_MAJOR < 3

---

.github/workflows/build-packages.yml

It turns out that ` steps.download-src-provenance.outputs.download-path` and `steps.download-provenance.outputs.download-path` are identical, triggering an error from `mv` because the files have been moved after being expanded.
I have:

build-package: Fix copy of the provenance attestations

---

pdns/libssl.cc

If you specify ` --enable-tls-providers` it's possible to build without openssl engine support. However, currently `openssl/engine.h` is still included. This PR changes that
I have:

Don't include openssl/engine.h if it's not going to be used

---

pdns/dnsdistdist/dnsdist-lua-bindings.cc
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-lua.hh

They were not available to the per-thread FFI rule, action and load-balancing policy environments.
I have:

dnsdist: Make the logging functions available to all Lua environments

---

pdns/dns.cc
pdns/views.hh

Backport of #14359 to rel/dnsdist-1.9.x.
Includes minor cleanup and additions to make UnsignedCharView usable for this use case. Supersedes #14356
Fixes
/usr/include/c++/v1/__fwd/string_view.h:22:41: warning: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 19, so please migrate off of it. [-Wdeprecated-declarations]
(cherry picked from commit 949ea9456dbe76e78aeff5f6f37f218549d1b493)
I have:

dnsdist-1.9.x: Backport of 14359 - dns.cc: use pdns::views::UnsignedCharView

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-lua.hh
pdns/dnsdistdist/dnsdist-lua-ffi.cc

Backport of #14398 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 14398 - Make the logging functions available to all Lua environments

---

pdns/dnsdistdist/doq.cc
pdns/dnsdistdist/m4/pdns_with_quiche.m4

Backport of #14392 to dnsdist-1.9.x
Quiche broke its existing API in 0.22.0: https://github.com/cloudflare/quiche/pull/1726 This pull request adds m4 code to detect whether the Quiche version we are building against is >= 0.22.0, and if it is defines `HAVE_QUICHE_STREAM_ERROR_CODES` which is later used by the code using Quiche to know which version of the API to use.
I have:

dnsdist-1.9.x: Backport of 14392 - Handle Quiche >= 0.22.0

---

.github/workflows/build-packages-daily-master.yml

test run on my fork in https://github.com/Habbie/pdns/actions/runs/9841614945 (the ubicloud failures are expected - my fork does not have access)
after this has merged and run once (successfully) we should expect uploaded packages. Next step then is to get them into the master repos so buildbot can stop doing that.
I have:

gh actions: daily master build of packages

---

pdns/libssl.cc

Backport of #14431 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 14431 - Don't include openssl/engine.h if it's not going to be used

---

pdns/dns.cc
pdns/dns.hh
pdns/dnsparser.hh
pdns/recursordist/syncres.cc
pdns/recursordist/syncres.hh
pdns/recursordist/test-syncres_cc9.cc

This refactors `sanitizeRecords()` and fixes a case where it was dependent on the order of records in the AUTH section.
Includes two `toString` functions that I am missing all the time.
This PR is reviewed best by individual commit. 1st and 2nd commits are comments and cleanup. 3rd fixes a bug, 4th refactors things and gets rid of the order dependency.
I have:

rec: refactor sanitizeRecords and fix order dependency

---

pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-xsk.cc
pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/dnsdist.hh
pdns/xsk.cc
pdns/xsk.hh

For performance reasons we used to keep a local list of available frames in our `XskWorker` object, like we are doing in the `XskSocket` one, to avoid having to go to the shared list which is protected by a lock. Unfortunately, while it works well for the `XskSocket` because it is accessed by a single `XskRouter` thread, the `XskWorker` object can be accessed by multiple threads at once: `XskResponderThread`, `responderThread`, `XskClientThread` and `XskRouter`. Most of the time these threads do not acquire nor release frames to the local list, but `responderThread` does acquire one when a response frame is punted to the regular networking stack, and all of them release frames when an unexpected condition occurs, for example when a queue is full. This leads to memory corruption and to a …

dnsdist: Fix a race in the XSK/AF_XDP backend handling code

---

build-scripts/docker/repo-test/README.md
build-scripts/docker/repo-test/generate-repo-files.py
build-scripts/docker/repo-test/templates/pdns-list.jinja2

This PR adds tests for the ARM64 repos to the "repo test script".
These have already been tested for a few releases.
I have:

Add ARM64 tests to repo script

---

docs/generate-man-pages.py
meson.build

This gets man-pages to get built using meson. There was an issue that `pip install` expected a hash for `setuptools` from the requirements file (which included hashes for everything and caused to pip to run with `--require-hashes`). I am not entirely sure why we used `setuptools-git`, so switching that to the non-git version fixed it.
I have:

Auth/Meson: Fix man-page generation

---

meson.build

- Fixes some warnings produced by meson about configuration variables expected by the `.in` files not being available in the configuration dict.
- Adds the `prefix` to `bindir` and `sbindir`, previously it produced e.g. `bin/pdns_server` and `sbin/pdns_server` and now it produces `/usr/local/bin/...`
I have:

Auth/Meson: Fix `.service` files generation

---

regression-tests.dnsdist/requirements.txt
regression-tests.recursor-dnssec/requirements.txt

There also seems to be a race in both a rec and ad dnsdist test that quite often pops up.
Specifically in rec `test_RecDnstap.DNSTapLogNODTest` and in dnsdist `TestAsyncFFI.testTruncation` (calling a destructor from a signal handler does not look safe:
```
==4264==ERROR: AddressSanitizer: SEGV on unknown address 0x7ff514006688 (pc 0x7ff517bea27b bp 0x000000000000 sp 0x7ffdd6e39180 T0)
==4264==The signal is caused by a WRITE memory access.
#0 0x7ff517bea27b  (/lib/x86_64-linux-gnu/libluajit-5.1.so.2+0x1527b)
#1 0x7ff517be9d25  (/lib/x86_64-linux-gnu/libluajit-5.1.so.2+0x14d25)
#2 0x7ff517bf05e7  (/lib/x86_64-linux-gnu/libluajit-5.1.so.2+0x1b5e7)
#3 0x55ab38c7300b in LuaContext::~LuaContext() /__w/pdns/pdns/pdns/dnsdistdist/dnsdist-0.0.0-git1/./ext/luawrapper/include/LuaContext.hpp:174:9
#4 …
```

Pin pysnmp version for rec and dnsdist regression tests

---

regression-tests.dnsdist/requirements.txt
regression-tests.recursor-dnssec/requirements.txt

dnsdist: Backport 14486 to dnsdist 1.9.x: pin pysnmp to version 5 for regression tests

---

regression-tests.dnsdist/requirements.txt
regression-tests.recursor-dnssec/requirements.txt

dnsdist: Backport 14486 to dnsdist 1.8.x: pin pysnmp to version 5 for regression tests

---

pdns/dnsdistdist/dnsdist-carbon.cc
pdns/dnsdistdist/dnsdist-console.cc
pdns/dnsdistdist/dnsdist-lua-rules.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-web.cc
pdns/dnsdistdist/dnsdist.cc

I'm not very happy with what Coverity is doing with this rule: while it does find some actual potential performance improvements, more often than not what it suggests would actually lead to a use-after-free issue.
I have:

dnsdist: Fix/silence Coverity "auto causes copy" warnings

---

pdns/dnsdistdist/dnsdist-carbon.cc
pdns/dnsdistdist/dnsdist-lua-inspection.cc
pdns/dnsdistdist/dnsdist-metrics.cc
pdns/dnsdistdist/dnsdist-metrics.hh
pdns/dnsdistdist/dnsdist-snmp.cc
pdns/dnsdistdist/dnsdist-web.cc
pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/dnsdist.hh
pdns/stat_t.hh

dnsdist: Use atomic variables for the per-protocol latencies

---

pdns/recursordist/syncres.cc

Plus: as we only use a limited set of NS names for resolving, processing all additional records does not help.
I have:

rec: limit the number of async tasks pushed to resolve NS names

---

pdns/recursordist/syncres.cc

Plus: as we only use a limited set of NS names for resolving, processing all additional records does not help.
(cherry picked from commit cd2de2ee7ad55f295a00dfce5488ee3863d974d6)
Backport of #14499 
I have:

rec: Backport 14499 to rec-5.1.x: limit the number of async tasks pushed to resolve NS names

---

pdns/recursordist/RECURSOR-MIB.txt

fixed maintenanceCalls vs maintenanceCount
It's anyones guess if it should be called Calls or Count in the end, it should be the same name in the end.
snmp would complain about the missing definition of the object maintenanceCalls as the definition later in the file is called maintenanceCount like this:
"Undefined OBJECT (maintenanceCalls): At line 1446 in /usr/share/mibs//RECURSOR-MIB"
I have:

Update RECURSOR-MIB to fix wrong naming for maintenanceCount object

---

contrib/_pdnsutil.zsh_completion
contrib/pdnsutil.bash_completion.d
docs/manpages/pdnsutil.1.rst
pdns/dnspacket.cc
pdns/dnspacket.hh
pdns/pdnsutil.cc

This can be used to lookup records from a backend using some filtering like type and client subnet.
I have:

`pdnsutil`: Add `backend-lookup` subcommand

---

pdns/dbdnsseckeeper.cc
pdns/dnssecinfra.hh
pdns/dnsseckeeper.hh
pdns/dnssecsigner.cc
pdns/packethandler.cc

Addresses the feature request I made on Issue #14371 .
 
When processing DNSSEC enabled query for some presigned zones, the lookup for the `RRSIG` records does not include the DNS packet. This caused some problem on our end, since our remote backend implementation relies on the real-remote header (the client's address) to provide users with the correct response values.
I have:

auth: provide dns packet when doing lookup for presigned signatures

---

pdns/recursordist/meson.build
pdns/recursordist/settings/meson.build

Rearrange dependencies so that we don't get multiple object files for `cxx-generated.o`, but just a single one that gets linked into `librec_common`.
I have:

rec: avoid duplicate object files in meson build

---

pdns/dnsdistdist/docs/reference/dnstap.rst
pdns/recursordist/docs/lua-config/protobuf.rst

I could not figure out which library to look at for the configuration values. @rgacogne helpfully pointed me in the right direction in #14510
Ideally we could link to more specific documentation, but as mentioned in #14510, it's not really easily linkable.
I have:

docs: Add link to the fstrm FrameStream library

---

pdns/recursordist/docs/metrics.rst

The [metrics documentation](https://doc.powerdns.com/recursor/metrics.html#dnssec-result-bogus-signature-no-yet-valid) mentions metric `dnssec-result-bogus-signature-no-yet-valid`, but [the actual metric name returned by `rec_control get-all`](https://github.com/PowerDNS/pdns/blob/7c9dce982470615ea1a3902433ff5af5cd83f70b/pdns/recursordist/rec_channel_rec.cc#L1497) is `dnssec-result-bogus-signature-not-yet-valid` (`not` rather than `no`).  This PR fixes that inconsistency.
I have:

Fix misspelled `dnssec-result-bogus-signature-no-yet-valid` metric name in documentation

---

.github/actions/spell-check/expect.txt
docs/backends/ldap.rst
docs/changelog/4.1.rst
docs/changelog/4.2.rst
docs/changelog/pre-4.0.rst
docs/lua-records/index.rst
docs/modes-of-operation.rst
docs/settings.rst
pdns/dnsdistdist/docs/advanced/passing-source-address.rst
pdns/dnsdistdist/docs/advanced/tuning.rst
pdns/dnsdistdist/docs/changelog.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/recursordist/docs/changelog/4.3.rst
pdns/recursordist/docs/changelog/5.0.rst
pdns/recursordist/docs/running.rst
pdns/recursordist/settings/docs-new-preamble-in.rst
pdns/recursordist/settings/docs-old-preamble-in.rst

Identified and fixed typos / spelling issues identified by the [typos](https://github.com/crate-ci/typos) tool. I tried to leave all the British-english spellings in place, as that seems to be the convention here.
It might be a good idea to add the typos tool to CI, at least for documentation. It did have a lot of false positives that would need to be added to an exemption list. If you're interested in this, let me know and I can send a PR.
I have:

Fix documentation typos

---

pdns/uuid-utils.cc

Boost 1.86.0 changes seem to no longer indirectly include header which causes build to fail with:
```
uuid-utils.cc:38:58: error: 'random' is not a class, namespace, or enumeration
thread_local boost::uuids::basic_random_generator<boost::random::mt19937> t_uuidGenerator;
^
```
boost/random/mersenne_twister.hpp has been available since Boost 1.21.2
Seen when updating Boost in Homebrew https://github.com/Homebrew/homebrew-core/pull/181332
I have:

Fix build with boost 1.86.0

---

pdns/libssl.cc

Engine support is not used by the recursor or the authoritative server's tools (`sdig`) so there is no need to enable it for them, especially since it has now been deprecated for a while and trigger compilation warnings.
I have:

libssl: Enable OpenSSL engine support for DNSdist only

---

pdns/recursordist/RECURSOR-MIB.txt
pdns/recursordist/docs/metrics.rst
pdns/recursordist/lwres.hh
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-snmp.cc
pdns/recursordist/rec-tcounters.hh
pdns/recursordist/rec_channel_rec.cc
pdns/recursordist/syncres.cc
pdns/recursordist/ws-recursor.cc
regression-tests.recursor-dnssec/test_SNMP.py

The newly introduced limits on chain size and age would return OSLimitError, while they are applications specific, do not indicate OS resource shortage and do not set errno. This PR introduces a specific `LWResult::Result` code.
Fixes #14551 
I have:

rec: distinguish OS imposed limits from app imposed limits, specifically on chains

---

pdns/dnsdistdist/dnsdist-ecs.cc
pdns/dnsdistdist/test-dnsdist_cc.cc
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_DOH.py
regression-tests.dnsdist/test_EDE.py
regression-tests.dnsdist/test_EDNSSelfGenerated.py

We used to wrongly reverse the byte-ordering of the existing EDNS flags when editing the OPT header, for example when setting an extended DNS error status.
Fixes https://github.com/PowerDNS/pdns/issues/14548.
I have:

dnsdist: Fix EDNS flags confusion when editing the OPT header

---

builder-support/helpers/install_quiche.sh
builder-support/helpers/quiche.json
tasks.py

Since 0.22.0 Quiche sets a proper `SONAME`, see cloudflare/quiche#1769
but it does not matter in our case since we install the Quiche library in such a way (libdnsdist-quiche.so)
that we are the only user, and it will always be updated with DNSdist. Keeping it makes our life significantly harder
since several packaging tools look a the `SONAME`, so this PR reverts this change.
I have:

dnsdist: Update Quiche to 0.22.0 (in our packages)

---

modules/geoipbackend/geoipbackend.cc
modules/geoipbackend/geoipinterface.cc
pdns/pdnsutil.cc

clang-tidy fixes

---

pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist.cc

If the server has not been added to the default pool, and is removed before the configuration has been fully parsed, the default pool might not exist yet.
Also create the default pool earlier, before parsing the configuration, so that we don't trip over its absence in a different place.
I have:

dnsdist: Handle a non-existent default pool when removing a server

---

.github/workflows/build-and-test-all-releases-dispatch.yml
.github/workflows/build-and-test-all.yml
.github/workflows/builder-releases-dispatch.yml

Avoid CI failures related to Coveralls when upload fails due to any errors.
Simplification of calls for workflows `build-and-test-all-releases-dispatch.yml` and `builder-releases-dispatch.yml` to improve readability.
I have:

GH Actions -  Coveralls: avoid CI failure when upload fails

---

pdns/uuid-utils.cc

Boost 1.86.0 changes seem to no longer indirectly include header which causes build to fail with:
```
uuid-utils.cc:38:58:
error: 'random' is not a class, namespace, or enumeration
```
boost/random/mersenne_twister.hpp has been available since Boost 1.21.2
(cherry picked from commit eed56000b1d68ac083b8e8bea4ff0ea30a1579c4)
Backport of #14562 
I have:

rec: Backport to rec-5.1.x: Fix build with boost 1.86.0

---

ext/yahttp/yahttp/reqresp.hpp

`g++` 14.2.1's `-Wnon-virtual-dtor` complains:
```
‘class YaHTTP::HTTPBase’ has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
```
I have:

YaHTTP: Fix a non-virtual destructor warning in the `HTTPBase` class

---

pdns/recursordist/settings/generate.py

With this the error message from #14525 becomes:
```
thread '<unnamed>' panicked at src/lib.rs:2394:347:
default value defined for `dnssec_trustanchors' should be valid YAML: Error(".[0]: invalid type: sequence, expected field identifier", line: 1, column: 103)
```
I have:

rec: better error message in case of syntax errors in defaults defined in table.py

---

regression-tests.recursor-dnssec/printlogs.py
regression-tests.recursor-dnssec/runtests
regression-tests.recursor-dnssec/test_Additionals.py
regression-tests.recursor-dnssec/test_ECS.py
regression-tests.recursor-dnssec/test_EDNSPadding.py
regression-tests.recursor-dnssec/test_Flags.py
regression-tests.recursor-dnssec/test_Lua.py
regression-tests.recursor-dnssec/test_Protobuf.py
regression-tests.recursor-dnssec/test_RDFlag.py
regression-tests.recursor-dnssec/test_RPZ.py
regression-tests.recursor-dnssec/test_RPZIncomplete.py
regression-tests.recursor-dnssec/test_ReadTrustAnchorsFromFile.py
regression-tests.recursor-dnssec/test_RecDnstap.py
regression-tests.recursor-dnssec/test_RootNXTrust.py
regression-tests.recursor-dnssec/test_TTL.py
regression-tests.recursor-dnssec/test_TrustAnchors.py

This fixes (at least locally) a race occasionally seen in the regression tests:
A test might finish "too early". In that case not all workers are fully setup yet, and leak sanitizer crashes due to a stack out of bounds.
One case fixed by introducing a sleep (for a test to see if the dnstap queue is empty), and one actually querying an existing out-of-band domain, which was enough for me to get all threads properly setup. Previously it would check a domain and get connnection refused, as this test does not setup auths at all. The assumption is that that causes a "too fast exit" of rec.
Log before fix:
```
test_RecDnstap.py:274: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cls = <class 'test_RecDnstap.DNSTapLogNODTest'>
@classmethod
def …
```

rec: fix regression test nod races and printlogs.py

---

docs/settings.rst

Fixes this warning from sphinx:
```
docs/settings.rst:1407: WARNING: undefined label: _stat-overload-drops (if the link has no caption the label must precede a section header)
```
I have:

auth docs: fix invalid reference

---

docs/settings.rst
pdns/auth-main.cc
pdns/dnsproxy.cc
pdns/dnsproxy.hh

Address #13039 by making the local port range configurable.
I have:

auth dnsproxy: make local port range configurable

---

docs/requirements.in
docs/requirements.txt

One of the external dependencies for building docs, the `pip` package `sphinxcontrib-fulltoc` has a not-pinned setup-requirement dependency with the package `pbr`. This makes us update our list of pinned pulled packages each time a new version comes up.
The package version is being explicitly set to `6.1.0` in this PR because otherwise, the tool that generates the list (`pip-compile --generate-hashes requirements.in`) will not include a dependency that is already satisfied. 
**NOTE**: the execution of the tool requires Python 3.11, which is the version used in the CI. Any other Python version would end up with a different list and errors when running the workflows
I have:

docs - pip pinning: set pbr version to 6.1.0

---

docs/settings.rst

We are reusing the source UDP port for a very long time. Cannot have people interfere or try to attack us with this design.
I have:

auth dnsproxy: document network ought to be trusted

---

regression-tests.auth-py/authtests.py
regression-tests.auth-py/runtests
regression-tests.auth-py/test_GSSTSIG.py

Support `$PDNS_BUILD_PATH` like in `regression-tests`. Avoid passing the autoconf-only `module-dir` and instead assume modules are in `$PDNS_BUILD_PATH/modules`.
Avoid `authbind` on macOS, where it is not necessary and absent.
I have:

regression-tests.auth-py: allow running with meson, and on macOS

---

regression-tests.auth-py/test_ALIAS.py

`expected_aaaa` is unused in these tests, use it.
I have:

regression-tests.auth-py: actually test ALIAS AAAA cases

---

pdns/packethandler.cc
pdns/ueberbackend.cc
pdns/ueberbackend.hh

Encapsulate this pattern into a new function:
```
while (B.get(rr)) ;      // don't leave DB handle in bad state
```
I've tentatively called the function `lookupEnd`.
This is a tiny improvement and probably opens a can of clang-tidy worms. I'll preemptively say that a solution which would instead remove the need to explicitly call this would be better, but that can still come.
I have:

auth: encapsulate lookup()-cleanup

---

pdns/dnsdistdist/dnsdist-lua-inspection.cc

We internally use a timestamp obtained via `CLOCK_MONOTONIC` which is quite useless to an external observer, so convert it to a normal unix timestamp in the Lua accessor.
Closes https://github.com/PowerDNS/pdns/issues/14552
I have:

dnsdist: Return a valid unix timestamp for Dynamic Block's `until`

---

pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/docs/advanced/tuning.rst
pdns/dnsdistdist/docs/reference/tuning.rst

dnsdist: Add warnings about large values passed to `setMaxTCPClientThreads`

---

pdns/recursordist/settings/table.py

Improve documentation of interaction of `dont_query` and `forward_zones`.
I have:
- [N/A] compiled this code
- [N/A] tested this code
- [N/A] documented the code
- [N/A] added or modified regression test(s)
- [N/A] added or modified unit test(s)

Mention effect of dont_query on forward_zones

---

pdns/dnsdistdist/test-dnsdistasync.cc

It looks like OpenBSD has different thread scheduler behaviour, and it can take a while for the error condition to be set.
Note that executing the loop more times does not work, as the `holder->empty()` condition is wat terminates the loop from what I have observed. But it still takes a while for the error condition to get set. Increasing the individual `usleeps` is what made this work reliable on OpenBSD/arm64.
I have:

dnsdist: adapt unit test to avoid race on OpenBSD

---

regression-tests/backends/common
regression-tests/backends/lmdb-master
regression-tests/start-test-stop

Convenient to set $RUNWRAPPER_PDNSUTIL to "gdb -q --args" or something.
Bare pdns has $RUNWRAPPER for that
I have:

Add a way to run pdnsutil using a debugger as part of the LMDB regression tests

---

.clang-tidy.bugs
.clang-tidy.full

Remove leftover config from old clang-tidy versions. This is unused in newer versions.
I have:

Remove leftover config from old clang-tidy versions

---

pdns/recursordist/syncres.cc
pdns/recursordist/syncres.hh
pdns/recursordist/test-syncres_cc3.cc

Instead of calling erase() on the vector we're processing, keep a bitmap.
If the bitmap indicates we need to erase records, do that by moving the *wanted* records into a new vector.
This avoids calling erase() multiple times, which can become costly on large vectors if done multiple times: each time all the elements after the one erased are moved. 
Also: be more strict in with the answers we allow in the answer section.
I have:

rec: rework sanitize code

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist-tcp.cc
regression-tests.dnsdist/test_ProxyProtocol.py

After reading the proxy protocol payload from the I/O buffer we were clearing the buffer but failed to properly reset the position, leading to an exception when trying to read the DNS payload after processing the TLS handshake:
```
Got an exception while handling (reading) TCP query from 127.0.0.1:59426: Calling tryRead() with a too small buffer (2) for a read of 18446744073709551566 bytes starting at 52
```
The huge value comes from the fact that the position (52 here) is larger than the size of the buffer (2 at this point to read the size of the incoming DNS payload), leading to an unsigned underflow. The code is properly detecting that the value makes no sense in this context, but the connection is then dropped because we cannot recover.
It turns out we had a end-to-end test for the …

dnsdist: Fix handling of proxy protocol payload outside of TLS for DoT

---

pdns/recursordist/docs/upgrade.rst

rec: document potential upgrade issue

---

pdns/dnsdistdist/testrunner.cc
pdns/recursordist/testrunner.cc
pdns/testrunner.cc

Always randomize unit test runs (as CI is alreayd doing). I've seen one time to many a dependency on order. Typical case is forgetting to init a var. 
Plus a little tidy of rec's testrunner. 
I have:

Randomize unit tests always

---

pdns/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist-nghttp2-in.cc
regression-tests.dnsdist/test_ProxyProtocol.py

Backport of #14636 to dnsdist-1.9.x.
After reading the proxy protocol payload from the I/O buffer we were clearing the buffer but failed to properly reset the position, leading to an exception when trying to read the DNS payload after processing the TLS handshake:
```
Got an exception while handling (reading) TCP query from 127.0.0.1:59426: Calling tryRead() with a too small buffer (2) for a read of 18446744073709551566 bytes starting at 52
```
The huge value comes from the fact that the position (52 here) is larger than the size of the buffer (2 at this point to read the size of the incoming DNS payload), leading to an unsigned underflow. The code is properly detecting that the value makes no sense in this context, but the connection is then dropped because we cannot recover.
It turns …

dnsdist-1.9.x: Backport #14636 - Fix handling of proxy protocol payload outside of TLS for DoT

---

pdns/dnsdist-lua-inspection.cc

Backport of #14570 to dnsdist-1.9.x.
We internally use a timestamp obtained via `CLOCK_MONOTONIC` which is quite useless to an external observer, so convert it to a normal unix timestamp in the Lua accessor.
I have:

dnsdist-1.9.x: Backport 14570 - Return a valid unix timestamp for Dynamic Block's `until`

---

pdns/dnsdist-ecs.cc
pdns/test-dnsdist_cc.cc
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_DOH.py
regression-tests.dnsdist/test_EDE.py
regression-tests.dnsdist/test_EDNSSelfGenerated.py

Backport of #14569 to dnsdist-1.9.x
We used to wrongly reverse the byte-ordering of the existing EDNS flags when editing the OPT header, for example when setting an extended DNS error status.
(cherry picked from commit 010521a0197091642bbc654b2b371b462fa73033)
I have:

dnsdist-1.9.x: Backport 14569 - Fix EDNS flags confusion when editing the OPT header

---

pdns/dnsdist.cc
pdns/dnsdistdist/docs/advanced/tuning.rst
pdns/dnsdistdist/docs/reference/tuning.rst

Backport of #14534 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 14534 - Add warnings about large values passed to `setMaxTCPClientThreads`

---

pdns/dnsdist-lua.cc
pdns/dnsdist.cc

Backport of #14575 to dnsdist-1.9.x.
If the server has not been added to the default pool, and is removed before the configuration has been fully parsed, the default pool might not exist yet.
Also create the default pool earlier, before parsing the configuration, so that we don't trip over its absence in a different place.
I have:

dnsdist-1.9.x: Backport 14575 - Handle a non-existent default pool when removing a server

---

pdns/fstrm_logger.cc
pdns/fstrm_logger.hh

Introduce a "too large" counter for the framestream remote logger

---

pdns/recursordist/pdns_recursor.cc
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_Chain.py

rec: make chain test more robust and fix max chain size accounting

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

While `rrset_name` (plus optionally `rrset_type`) turns `list` into `lookup` for records, we don't have `lookup` for comments, so we need to filter those comments out explicitly after listing them all from the database.
This also shows that in case of a zone with lots of comments, the 'rrset filter' (which actually -is- efficient for records) does a lot of extra work for comments.
~~Needs a test.~~ has a test now
Fixes #14539
I have:

auth API: when querying with rrset_name, respect it for comments too

---

.github/workflows/build-and-test-all.yml

The weekly-scheduled workflow `build-and-test-all-releases-dispatch.yml` has been failing for quite some time because the version of the `ldap` library that is installed for Debian 11 does not have the file `ldap.pc`, and therefore `meson` is not able to find the library (see [run](https://github.com/PowerDNS/pdns/actions/runs/10839375107/job/30079638703)). This has been solved in newer versions like the one that can be installed in Debian 12.
This PR changes the definition of the matrix for the job `build-auth` in `build-and-test-all.yaml` to skip the case for building auth with meson on Debian 11. 
NOTE: Adding the `exclude` cause was insufficient because it is evaluated before the clause `include` in a matrix definition. Also, these clauses (`include`/`exclude`) do not support matching …

GH actions: skip job build-auth with meson for Debian 11

---

pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-nghttp2.cc
pdns/dnsdistdist/dnsdist-nghttp2.hh
pdns/libssl.cc
pdns/libssl.hh
pdns/tcpiohandler.cc
pdns/tcpiohandler.hh

Instead of storing the frontend context for server-side connection and the `SSL_CTX*` for client-side. 
The first commit in this PR fixes a race condition where reloading the certificate and key via `reloadAllCertificates()`, for example, could cause the `ALPN`-related data to be destroyed while it was still used by an existing TLS connection. The time window to trigger the issue is quite narrow because `ALPN` data is only accessed during the initial handshake, but we have got one report of it happening in the wild, and TSAN confirms the race. This is not a security issue since it cannot be triggered without administrative access to dnsdist.
The remaining commits are making this code more clean and robust, and should probably not be backported. 
I would recommend reviewing this PR commit …

dnsdist: Always store the `OpenSSLTLSIOCtx` in the connection

---

pdns/recursordist/meson.build

Previously, only the pollmplexer was linked in. Pick up the right one, depending on platform. Do not put any of them in the common lib, because the static initializer does not get called in that case.
I have:

rec: meson build: link in right multiplexer

---

pdns/uuid-utils.cc

Backport of #14562 to dnsdist-1.8.x
Boost 1.86.0 changes seem to no longer indirectly include header which causes build to fail with:
```
uuid-utils.cc:38:58:
error: 'random' is not a class, namespace, or enumeration
```
boost/random/mersenne_twister.hpp has been available since Boost 1.21.2
I have:

dnsdist-1.8.x: Backport 14562 - Fix build with boost 1.86.0

---

pdns/tcpiohandler.cc

Backport of #14671 to dnsdist-1.8.x
I have:

dnsdist-1.8.x: Backport 14671 - Always store the `OpenSSLTLSIOCtx` in the connection

---

pdns/dnsdistdist/dnsdist-lua-actions.cc

cannot unsee the extra space, it has haunted me for days now
I have:

dnsdist: very nitty Update dnsdist-lua-actions.cc

---

.github/workflows/build-and-test-all.yml

https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240915.1 broke mssql.
https://github.com/microsoft/mssql-docker/issues/868 fits the kernel upgrade.
this commit switches from 2017-GA to 2022-CU12, which unbreaks the build
I have:

auth mssql CI: switch to 2022-CU12 image

---

builder-support/helpers/rust.json

The `boring-sys` crate used by `Quiche` uses a version of the `bindgen` crate that requires `Rust >= 1.77.0`.
We already upgraded the Rust version in the default branch in https://github.com/PowerDNS/pdns/pull/14252
I have:

dnsdist-1.9.x: Update the Rust version we use in our packages to 1.78

---

docs/secpoll.zone
pdns/dnsdistdist/docs/changelog.rst

dnsdist: Update ChangeLog and secpoll for 1.8.4

---

.github/workflows/build-and-test-all.yml

auth 4.9 mssql CI: switch to 2022-CU12 image

---

builder-support/helpers/generate-sbom-dnf.py

this turns `4.8.0` into `4.8.0-0.beta1.authnodynnoso.3731.g201e03656.1pdns.el8`, which is what `rpm -qa` also prints (except we leave out `pdns-` in front and `.x86_64` at the tail)
I have:

dnf sbom: use same logic for our version number too

---

.github/workflows/coverity-dispatch.yml
.github/workflows/coverity.yml
.github/workflows/misc-dailies.yml

I need to find a way to test this, but review and comments welcome in the meantime :)
I have:

Move coverity to a reusable workflow, add a dispatcher workflow

---

builder-support/helpers/generate-sbom-dnf.py

fixes the breakage introduced in #14691
I have:

dnf sbom: handle arch absence

---

pdns/tcpiohandler.cc

Backport of #14671 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 14671 - Always store the `OpenSSLTLSIOCtx` in the connection

---

regression-tests.recursor-dnssec/test_NamedForward.py

This tries to work around the occasional GH networking issues
I have:

rec: use multiple targets for the named forward test

---

builder-support/post-build

This is caused by pdns-recursor matching pdns*, which is intended to select auth files only.
Not terribly happy with the code duplication, but we would end up in quoting hell otherwise.
I have:

Do not include a stray pdns dir in the recursor artifacts

---

.clang-format
.clang-tidy.bugs
.clang-tidy.full

Cleanup clang-tidy and -format config files to fix lint issues
I have:

Cleanup clang config files

---

pdns/webserver.cc

fixes #14637 -if- the client sends `Accept: application/json`
I have:

webserver.cc: try to pass exception text with 500 errors

---

.not-formatted
ext/lmdb-safe/lmdb-typed.cc
ext/lmdb-safe/lmdb-typed.hh
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh

Some cleanup to lmdb source files, the 128-bit IDs branch is getting more complicated so I want to merge commits that can be made independent:
- Formatting and lint cleanups
- Rewrite serToString and serFromString (and rename them to serializeToBuffer and deserializeFromBuffer). The rewrites fix issues with casts and memory copies.
- Rename the LMDBIDVec
- Clean up source code comments
I have:

Cleanups to lmdb source files

---

pdns/dbdnsseckeeper.cc
pdns/dnssecinfra.hh
pdns/dnsseckeeper.hh
pdns/dnssecsigner.cc
pdns/packethandler.cc

auth-4.9: provide dns packet when doing lookup for presigned signatures

---

pdns/dnspacket.cc
pdns/dnspacket.hh
pdns/packethandler.cc
pdns/packethandler.hh
pdns/tcpreceiver.cc

Avoid DNSPacket pulling UeberBackend.
This is a refactoring commit from #14594 which I think stands on its own.
I have:

auth: move checkForCorrectTSIG into packethandler

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

auth 4.9 API: when querying with rrset_name, respect it for comments too

---

pdns/uuid-utils.cc

auth-4.9: Fix build with boost 1.86.0

---

pdns/pdnsutil.cc

auth-4.9 pdnsutil check-zone: make LUA records optional

---

pdns/dnsdistdist/dnsdist-lua-actions.cc
regression-tests.dnsdist/test_Spoofing.py

My reasoning is that it makes sense to add EDNS to responses generated from DNSdist provided that:
- the initial query had EDNS
- `setAddEDNSToSelfGeneratedResponses` has not been set to `false`
- we are only provided part of the response (record data here) and not a full response packet
The current behaviour looks like a bug to me, even though the code was explicitly disabling EDNS. Unfortunately the commit adding that code (fd138b6658dbb36d1ceb5f022e5e1db5d2b4d1f8) doesn't explain why, and the pull request in which it was located (#8171) doesn't either. So I'd currently be inclined to backporting this commit to 1.9.x.
I have:

dnsdist: Add EDNS to responses generated from raw record data

---

pdns/dnsdist-lua-actions.cc
regression-tests.dnsdist/test_Spoofing.py

Backport of #14728 to rel/dnsdist-1.9.x
My reasoning is that it makes sense to add EDNS to responses generated from DNSdist provided that:
- the initial query had EDNS
- `setAddEDNSToSelfGeneratedResponses` has not been set to `false`
- we are only provided part of the response and not a full response packet
I have:

dnsdist-1.9.x: Backport 14728 - Add EDNS to responses generated from raw record data

---

pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-lua-ffi.hh
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
regression-tests.dnsdist/test_ProxyProtocol.py

<strike>Needs:
- manual testing
- unit tests
- regression tests
</strike>
Fixes https://github.com/PowerDNS/pdns/issues/14656
I have:

dnsdist: Add a FFI accessor to incoming proxy protocol values

---

pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-lua-ffi.hh
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
regression-tests.dnsdist/test_ProxyProtocol.py

Backport of #14664 to rel/dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 14664 - Add a FFI accessor to incoming proxy protocol values

---

pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/docs/advanced/ebpf.rst
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_DynBlocksEBPF.py
regression-tests.dnsdist/test_EBPF.py

The current eBPF code tries to parse the beginning of the DNS payload to extract the qname for all UDP datagrams, which is not course not working correctly for QUIC packets. I don't immediately see a way to identify QUIC packets from our eBPF code, so for now this commit disables the eBPF filtering feature on QUIC sockets.
Fixes https://github.com/PowerDNS/pdns/issues/14736
I have:

dnsdist: Disable eBPF filtering on QUIC (DoQ, DoH3) sockets

---

pdns/dnsdist.cc
pdns/dnsdistdist/docs/advanced/ebpf.rst
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_DynBlocksEBPF.py
regression-tests.dnsdist/test_EBPF.py

Backport of #14739 to rel/dnsdist-1.9.x
The current eBPF code tries to parse the beginning of the DNS payload to extract the qname for all UDP datagrams, which is not course not working correctly for QUIC packets. I don't immediately see a way to identify QUIC packets from our eBPF code, so for now this commit disables the eBPF filtering feature on QUIC sockets.
I have:

dnsdist-1.9.x: Backport 14739 : Disable eBPF filtering on QUIC (DoQ, DoH3) sockets

---

pdns/recursordist/filterpo.hh
pdns/recursordist/rec-main.cc
pdns/recursordist/syncres.cc

- Log policyname on policyHit when updating root
- Do not register invalid file-based RPZs
- Do not return null SOA (this should no longer happen with the 2nd bullet, but better safe than sorry)
2nd commit: do not apply NS based policies to (recursive) forwarders. This commit is debatable, hence draft status.
I have:

rec: rpz tweaks

---

pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/rec-tcp.cc

But do not ratelimit them. Note that `MOADNSExceptions` is derived from `std::runtime_errror` and not from `std::exception`.
Also introduce the same logic related to `gettag()` in `rec-tcp.cc` compared to `pdns_recursor.cc`. 
Churn is a bit high as `s_rateLimitedLogger` changed into `g_rateLimitedLogger`, to make it available in `rec-tcp.cc`.
Fixes #14582
I have:

rec: Only log MOADNSExceptions if logging.log_common_errors is true.

---

pdns/recursordist/settings/Makefile.am

But don't report an error during configure:
When building from a src tarball you don't need python (the tarball includes the generated files), but that changes if settings/table.py was modified or when building from a github checkout.
I have:

rec: Give a more clear error message if the build fails because python was not found

---

pdns/recursordist/reczones-helpers.cc
pdns/recursordist/reczones-helpers.hh
pdns/recursordist/reczones.cc
pdns/recursordist/settings/table.py
regression-tests.recursor-dnssec/test_DNS64.py

Guarded by a `recursor.serve_rfc6303` setting, default `true`.
Requested by @neilcook 
I have:

rec: implement rfc6303 special zones (mostly v6 reverse mappings)

---

pdns/recursordist/settings/cxxsupport.cc
pdns/recursordist/settings/docs-new-preamble-in.rst
pdns/recursordist/settings/table.py
regression-tests.recursor-dnssec/test_Notify.py

Until now AuthZones did not have the field at all, and for ForwardZones it was only processed if reading from a forward_zones_file.
A slight drawback is the thing mentioned in the comment: the zones will be shown in `allow_notify_for` if you
run `pdns_recursor --config`, while they aren't actually there in any config file.
I have:

rec: notify_allowed should be processed for forward_zones and forward_zones_recurse

---

docs/catalog.rst

In the example about assigning members to a producer zone, the example.com zone should have its kind (type) set to primary, as native zones are not included in the catalog.
`pdnsutil set-catalog` does not change the type to primary, so we also have to run `pdnsutil set-kind`.
I have:

auth docs: set catalog member to primary

---

builder-support/helpers/rust.json

Workaround for mentioned issue
I have:

Move back to rust 1.80.1, see https://github.com/PowerDNS/pdns/issues/14757

---

pdns/recursordist/recursor_cache.cc
pdns/recursordist/test-reczones-helpers.cc
pdns/recursordist/test-syncres_cc.cc

In particluar if a specific test was run that would set the maximum RRSET very low, the reczones_helpers/test_UserHints test would fail.
I have:

rec: make sure the record cache has sane paramers for each unit test

---

pdns/auth-secondarycommunicator.cc

Trivially replace initialisation of `soatimes` in `ixfrSuck`.
I have:

ixfrSuck: init soatimes without separate memset

---

.clang-tidy.full

This is a quick fix, maybe there are better ways.
I have:

Followup to #14705: clang-tidy does not pick up last option listed

---

pdns/sdig.cc

as mentioned in comments to #14649
I have:

auth sdig: some improvements for stdin mode

---

pdns/dnsdistdist/dnsdist-doh-common.cc
pdns/dnsdistdist/dnsdist-doh-common.hh
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/libssl.cc
pdns/libssl.hh
pdns/tcpiohandler.cc
pdns/tcpiohandler.hh
regression-tests.dnsdist/test_TLS.py

This adds the ability to load a given TLS tickets key on DOH and TLS frontends.
I have:

dnsdist: add the ability to load a given TLS tickets key

---

build-scripts/test-recursor
meson.build
regression-tests.nobackend/rectify-axfr/command
regression-tests/backends/lmdb-slave
regression-tests/runtests
regression-tests/start-test-stop
tasks.py

Add lmdb regression tests to meson
I have:

Add lmdb regression tests to meson

---

.github/workflows/documentation.yml
pdns/recursordist/docs/changelog/4.1.rst
pdns/recursordist/docs/performance.rst
tasks.py

rec: generate metrics docs when publishing

---

regression-tests.auth-py/authtests.py

PR removed duplicate `tearDownClass` method. one located at line [244](https://github.com/PowerDNS/pdns/blob/51c26d140a95d07ca25ed787cc9b2f470d9b7570/regression-tests.auth-py/authtests.py#L244) while the other one located at line [253](https://github.com/PowerDNS/pdns/blob/51c26d140a95d07ca25ed787cc9b2f470d9b7570/regression-tests.auth-py/authtests.py#L253).
I have:

regression-tests.auth-py: remove duplicate method

---

pdns/packethandler.cc

This change allow an empty string to be returned to CHAOS version.bind request. version-string by default is set to "full" through pdns/auth-main.cc declareArguments(), however does not allow an empty string to be returned as PowerDNS Recursor does.
I have:

pdns: allow empty string in version-string

---

pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-cache.cc
pdns/dnsdistdist/dnsdist-cache.hh
pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
pdns/dnsdistdist/docs/reference/config.rst

Idea from #14649
Include more readily accessible info from the packet cache.
Potentially need to change documentation to remove 'summary of the cache', or make the full packet stuff an optional argument. 
I have:

dnsdist: dump more packet cache

---

.clang-tidy.full

As I suspected the last fix to the clang-tidy config file broke it. This fixes it.
I have:

Fix clang-tidy (again)

---

ext/lmdb-safe/lmdb-safe.hh

It was only included for non-dnsdist contexts, but `std::runtime_error` is used in all contexts and gcc version 14.2.1 20240910 (at least) is not happy about it:
```
In file included from ext/lmdb-safe/lmdb-safe.cc:2:
ext/lmdb-safe/lmdb-safe.hh: In member function ‘int MDBROTransactionImpl::get(MDB_dbi, const MDBInVal&, MDBOutVal&)’:
ext/lmdb-safe/lmdb-safe.hh:379:18: error: ‘runtime_error’ is not a member of ‘std’
379 |       throw std::runtime_error("Attempt to use a closed RO transaction for get");
|
```
I have:

dnsdist: Add missing `stdexcept` include in `lmdb-safe.hh`

---

pdns/recursordist/lwres.cc
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/syncres.hh
regression-tests.recursor-dnssec/test_Chain.py

rec: Backport 14628 to rec 5.1.x: rec: avoid duplicated waiter ids for chained requests 

---

build-scripts/test-recursor

(cherry picked from commit 32ac2627fad9d398756c6ec05ae423eec22eff7e)
I have:

rec: Backport 14766 to rec 5.1.x: bump SNMP ignore from buster to bookworm after buildbot VM upgrade 

---

pdns/dnsdistdist/docs/advanced/axfr.rst
pdns/dnsdistdist/docs/advanced/ebpf.rst
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/docs/reference/rules-management.rst

update docs to use non-deprecated examples

dnsdist: stop using makeRule, update Qname to QName so links should work

---

pdns/recursordist/mtasker.hh
pdns/recursordist/test-rec-tcounters_cc.cc
pdns/recursordist/test-syncres_cc.cc

The testrunner run becomes very slow, a non-zero inception skew is needed.
I have:

rec: make valgrind build and testrunner run work again

---

pdns/recursordist/docs/upgrade.rst
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-tcounters.hh
pdns/recursordist/syncres.cc

Also
- cleans up two TCounters that where unused and/or redundant.
- group the log lines more naturally
- print doubles with two decimal places
I have:

rec: periodic stats cleanup and rename outqueries-per-query to outqueries-per-query-perc

---

pdns/dnsdistdist/dnsdist-lua-hooks.cc

The key received on the lua side might be truncated if it contains the null char. By changing the type of the prototype, the lua wrapper uses the `key.size()` method to evaluate the actual size.
I have:

dnsdist setTicketsKeyAddedHook(): adjust type of the key to fix potential truncate

---

.github/actions/spell-check/expect.txt
pdns/dnsdistdist/docs/guides/dns-over-https.rst

This small documentation change updates dnsdist with an example nginx configuration, for running DoH with the grpc_pass directive. Closes #14815 
I have:

Add dnsdist documentation example for using DoH behind nginx

---

pdns/recursordist/mtasker.hh
pdns/recursordist/mtasker_context.hh
pdns/recursordist/test-mtasker.cc

If we do not do that, only the next call of `sendEvent` will release
the shared pointer to the `TCPConnectionHandler` in `PacketID` as it overwrites `d_eventkey`. Same for `d_waitval`. This
might delay cleaning TCP objects up on not-so-busy threads.
Fixes https://github.com/PowerDNS/pdns/issues/13422, thought it can still take a while on idle recursors,
as the housekeeping function is not called often in those cases.
Added a simple mechanism to make sure `d_eventkey` is not used when it is not set yet or after being moved.
I have:

rec: drop ref in mtasker when it is no longer needed

---

pdns/recursordist/syncres.cc
pdns/recursordist/test-syncres_cc1.cc

Specifically when the max CNAME chain length is exceeded (with QName Minimization enabled), but there are likely other cases.
Fixes #14310 
I have:

rec: fix a difference between record-cache hit and miss in some ServFail results 

---

pdns/recursordist/rec_channel_rec.cc

Fixes #13066 while there.
I have:

rec: rec_control top* cleanup

---

regression-tests.recursor-dnssec/test_SimpleDoT.py

Other tests using external servers already use 5s
Should fix #14829 in many cases.
I have:

rec: use a more generous timeout for a test using external servers

---

pdns/recursordist/rec-xfr.hh

The coverity report is about zoneIdx, but it is always initialized in rec-main.cc before being used. Still having no initialized fields is better in general.
I have:

rec: fix coverity 1564914 (afaiks harmless)

---

regression-tests/start-test-stop

Revert "Cleanup"
This reverts commit 48c18926520f873af6f32a2003225e704637c69d (part of #14621).
I have:

unbreak local running of auth regression tests

---

pdns/dnsdistdist/dnsdist-lua.cc

dnsdist: Fix two broken Lua directives

---

pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/rec-tcp.cc
pdns/recursordist/settings/table.py

Make a clear distinction between the various types of use of file descriptors. Some are static, some depend on the number of mthreads active, some on the number of posix threads.
As we already are reserving  max mthreads (2048) times workers (2 UDP + 1 TCP)) by default, I think we can bump max_tcp_clients  to 1024 without special precautions, apart from taking into account max_tcp_clients when computing the maximum number of FDs used. The current number already is > 6k. An extra 1k isn't that big of a deal. This number is then used to potentially reduce max mthreads.
I checked the numbers against the actual number seen on a running recursor, adding FDs for pipes and other assorted stuff which weren't included previously.
Fixes the last part of #14533.
I have:

rec: better fd count estimates and move default incoming.max_tcp_client to 1024 

---

.clang-tidy.bugs
.clang-tidy.full

Root cause was the slightly different parsing or the Checks: line, newer version handle the single quotes differently. Also remove two entries that are not present on older clang-tidy implementations.
I have:

Finally fix the clang-tidy issues.

---

.github/workflows/build-docker-images.yml
.github/workflows/build-packages.yml
.github/workflows/builder.yml

Use the variable `ARM64_USE_UBICLOUD='1'` to enable using arm64 runners on Ubicloud when building images or packages. This avoids errors when running these workflows on forks.
**NOTE**: Please add the variable `ARM64_USE_UBICLOUD='1'` into the repository configuration before merging.
Test build packages with arm64 runners not available (variable unset):
- Builder: [https://github.com/romeroalx/pdns/actions/runs/11404844261](https://github.com/romeroalx/pdns/actions/runs/11404844261)
- Build packages: [https://github.com/romeroalx/pdns/actions/runs/11404844315](https://github.com/romeroalx/pdns/actions/runs/11404844315)
Test build packages with arm64 runners available (`ARM64_USE_UBICLOUD='1'):
- Builder: [https://github.com/romeroalx/pdns/actions/runs/11407238715](https://github.com/romero …

GH actions: use arm64 Ubicloud runners only if a variable is defined at repository level

---

docs/settings.rst
pdns/auth-main.cc
pdns/packethandler.cc
pdns/packethandler.hh
regression-tests.auth-py/authtests.py
regression-tests.auth-py/test_ResolveAcrossZones.py

Addresses #10017. Introduces new setting `resolve-across-zones`. Default is the unchanged behaviour.
Turning off the new setting causes CNAME targets to not be followed across (local) zones. Also, queries that could be answered by following a local delegation are similarly not resolved.
I have:

auth: allow turning off across-zone resolving

---

pdns/dnsdistdist/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/docs/reference/dq.rst

FFI seems to have this already.
Not sure if there is a reason not to include it in the normal Lua bindings?
Use case: want to easily check how much time has been spent so far, to decide if query should be replayed or not. 
```Lua
function result(dq)
warnlog("query elapsed time is " .. dq:getElapsedUs() .. " us")
return DNSResponseAction.None
end
addAction(AllRule(), LuaAction(result))
addResponseAction(AllRule(),LuaResponseAction(result))
addLocal("127.0.0.1:5454")
newServer({address="8.8.8.8"})
```
```
query elapsed time is 69.56 us
query elapsed time is 34759.856 us
```
I have:

dnsdist: add elapsed time to dq object

---

pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/aggressive_nsec.hh
pdns/recursordist/syncres.cc
pdns/recursordist/test-aggressive_nsec_cc.cc

And report this in cache dump and traces
Fixes #14855
Example trace line:
```
Nov 20 10:26:07 [2] ww8.drijf.net: Looking for a NSEC before ww8.drijf.net: found a possible NSEC at ns3.drijf.net inserted by ww9.drijf.net/A ww8.drijf.net: is covered by (ns3.drijf.net to www.drijf.net) and it proves that the name does not exist
```
I have:

rec: Remember which query led to aggresive cache insert/update

---

configure.ac
modules/bindbackend/Makefile.am
modules/geoipbackend/Makefile.am
modules/gmysqlbackend/Makefile.am
modules/godbcbackend/Makefile.am
modules/gpgsqlbackend/Makefile.am
modules/gsqlite3backend/Makefile.am
modules/ldapbackend/Makefile.am
modules/lmdbbackend/Makefile.am
modules/lua2backend/Makefile.am
modules/pipebackend/Makefile.am
modules/remotebackend/Makefile.am
modules/tinydnsbackend/Makefile.am

auth: don't build .so for non-dyn modules

---

pdns/ixfr.cc
pdns/recursordist/filterpo.hh
pdns/recursordist/rpzloader.cc
regression-tests.recursor-dnssec/test_RPZ.py

There is a double bookkeeping going on for RPZs. An RPZ has an internal serial number, but also stores a SOA, which has its own serial. #14471 attempted to dump the real SOA into the dumpFile, but it was only partially correct. Consequence is that after a restart or `rec_control reload-lua-config` rec would present an older than previous serial (read from the dumpFile) to the auth server, which in most cases would respond with a full zone. After that the serial would be right, only the dumpFile would contain the wrong serial.
This adds consistency checking, a regression test and as an extra also gives a better error message if our serial is *higher* than the auths one. Previously we would report an exception that the auth has closed the connection.
Fixes #14857
I have:

rec: fix serial number inconsistency for RPZ dumpfiles

---

builder-support/dockerfiles/Dockerfile.debbuild-prepare
builder-support/dockerfiles/Dockerfile.recursor
builder-support/dockerfiles/Dockerfile.rpmbuild

tested with el-9 and debian-bookworm
I have:

rec build: stop using /sdist/ to cache rust

---

pdns/pdnsutil.cc

After a change to a zone pdnsutil offers to increase the serial. Similar to `pdnsutil increase-serial` inform the user about the actual value of the new serial if the increase was agreed to.
To check for the change to be flushed out to the secondaries it is useful to know that serial. So emitting it without me having to ask for it is a nice service.
I have:

pdnsutil edit-zone: Emit the updated SOA serial

---

modules/remotebackend/test-remotebackend-pipe.cc
modules/remotebackend/test-remotebackend-unix.cc
modules/remotebackend/test-remotebackend-zeromq.cc
pdns/auth-main.cc
pdns/dnsparser.cc
pdns/dnsparser.hh
pdns/dnsrecords.cc
pdns/dnsrecords.hh
pdns/dnsscope.cc
pdns/nsecrecords.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/reczones.cc
pdns/sillyrecords.cc
pdns/test-dnsname_cc.cc
pdns/test-dnsrecords_cc.cc
pdns/test-signers.cc
pdns/test-zoneparser_tng_cc.cc

Actually seen in recursor, but auth could also have it in theory.
The issue is that you cannot call type register functions while the rest of the threads are doing their work. The actual fix is in `reczones.cc`, but also guard against this happening in other places (for both rec and auth), and while there remove the unused `unregist` function.
I have:

fix register type race

---

.github/workflows/build-and-test-all.yml
.github/workflows/build-packages.yml
.github/workflows/builder.yml
.github/workflows/codeql-analysis.yml
.github/workflows/formatting.yml
.github/workflows/fuzz.yml

Backport #13679: Update upload/download artifact actions to v4.
As cited in the deprecation notice ([https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)), these actions cannot be used from the end of January 2025:
> "Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of `actions/upload-artifact` or `actions/download-artifact`"
As part of this PR, #13539 and #13725 are also backported for updating to v4 `actions/checkout` and `action/cache`.
I have:

dnsdist 1.8.x: Backport 13679 - Update upload-artifact and download-artifact to version 4

---

pdns/recursordist/rec-main.cc

The stop hook was not called in the threads=1 case. This looks better from a symmetry point of view as well.
I have:

re: followup to 14796: also call stop hook in 1 thread case

---

.github/workflows/build-and-test-all.yml
.github/workflows/builder-dispatch.yml
.github/workflows/builder.yml
.github/workflows/codeql-analysis.yml
.github/workflows/formatting.yml
.github/workflows/fuzz.yml

Backport #13679: Update upload/download artifact actions to v4.
As cited in the deprecation notice ([https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)), these actions cannot be used from the end of January 2025:
> "Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of `actions/upload-artifact` or `actions/download-artifact`"
As part of this PR, #13539 and #13725 are also backported for updating to v4 `actions/checkout` and `action/cache`.
I have:

auth-4.7.x: Backport 13679 - Update upload-artifact and download-artifact to version 4

---

.github/workflows/build-and-test-all.yml
.github/workflows/builder-dispatch.yml
.github/workflows/builder.yml
.github/workflows/codeql-analysis.yml
.github/workflows/formatting.yml
.github/workflows/fuzz.yml
.github/workflows/misc-dailies.yml
.github/workflows/secpoll.yml

Backport #13679: Update upload/download artifact actions to v4.
As cited in the deprecation notice ([https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)), these actions cannot be used from the end of January 2025:
> "Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of `actions/upload-artifact` or `actions/download-artifact`"
As part of this PR, #13539 and #13725 are also backported for updating to v4 `actions/checkout` and `action/cache`.
I have:

auth-4.8.x: Backport 13679 - Update upload-artifact and download-artifact to version 4

---

.github/workflows/documentation.yml

Installs the 'inv' tool, before trying to invoke it :o) Cargo-Culted from the other task, so I'm not entirely sure if we need all of it here

Install inv before using it

---

.github/workflows/documentation.yml
tasks.py

untar the html docs before syncing them to web1. Remove tar.bz2 of documentation sites

Fix for upload to web1

---

.github/workflows/documentation.yml
tasks.py

put pdfs in latex subdirectory before uploading to web1

put pdfs in latex subdirectory before uploading to web1

---

pdns/dnsdistdist/docs/reference/config.rst

The example callback function signature is incorrect.
I have:

dnsdist: Fix addMaintenanceCallback example

---

.github/workflows/build-packages.yml

When I'm running this workflow by hand I'm mostly interested in results of specific builds. But the part of the name that varies is at the end, and chopped of in te tree view. so it requires extra clicking to see which build failed. This moves the target platform part to the from of the displayed name.
I have:

GH workflow for building packages: change name so target isn't chopped off

---

.github/workflows/build-packages-daily-master.yml

After this commit, the `build-packages-daily-master` workflow will only be executed on repositories that have a `SCHEDULED_PACKAGES_DAILY` variable set to a non-negative value.
I added the variable to the PowerDNS/pdns repository already.
I have:

CI: Run the daily package building workflow only if requested

---

pdns/rcpgenerator.cc
pdns/test-dnsrecords_cc.cc

Until about 2011, hexadecimal input as ascii strings were required to have an even number of characters, in order to make a correct number of bytes. Then changes were made to allow whitespace in these strings, or a dangling single hex char was accepted as the high-order part of a complete byte, i.e. "ABCDE" would be parsed as "ABCDE0".
This PR brings back the exception which used to be raised for an odd number of meaningful characters, but does not change the rest of the logic (i.e. you can still write "AB_CD_EF" if you want).
I have:

[bugfix] Reject hexadecimal blobs with odd number of characters

---

pdns/dnsdistdist/dnsdist-lbpolicies.cc
pdns/dnsdistdist/dnsdist-lua.cc
regression-tests.dnsdist/test_Routing.py

The first issue was introduced during the configuration refactoring, and caused `whashed` and `wrandom` to use the wrong internal setting for bounded-loads.
The second issue is the same than the one fixed in #14929: "Zero is the initial value, but until now it was only possible to pass a value greater than or equal to 1.0 to `setWeightedBalancingFactor()` so it was not possible to reset it to the default value". The actual check was also wrong since the refactoring.
I have:

dnsdist: Fix issues with the balancing factors

---

pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/doh.cc
pdns/libssl.cc
pdns/libssl.hh
pdns/tcpiohandler.cc
pdns/tcpiohandler.hh
regression-tests.dnsdist/test_OutgoingDOH.py
regression-tests.dnsdist/test_OutgoingTLS.py

This adds keyLogFile setting to DoT and DoH backends.
I have:
The regression tests just try if the logfiles exist and are non-empty, they don't really check what is in them.

dnsdist: allow setting keyLogFile to DoT/DoH backends

---

pdns/dnsdistdist/docs/reference/dq.rst

As suggested by Otto in https://github.com/PowerDNS/pdns/pull/14887
I have:

dnsdist: Document that `DNSQuestion::getElapsedUs` will be added in 1.9.8

---

pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/rec-tcp.cc

Instead of addresses * threads * protocol lines
The recursor startup is too chatty, it's easy to miss important warnings or errors. The socket creation code is the biggest offender (it logs per thread and per listening address for both UDP and TCP), so reduce the amount of lines to just two.
Also stop doing old-style logging for code that is changed and unlikely to be backported, it has been declared unsupported.
The log lines now look like:
```
Dec 09 09:30:01 msg="Listening for queries" subsystem="config" level="0" prio="Info" tid="0" ts="1733733001.553" addresses="0.0.0.0:5301 [::]:5301" proto="UDP" reuseport="1" socketInstances="4"
Dec 09 09:30:01 msg="Listening for queries" subsystem="config" level="0" prio="Info" tid="0" ts="1733733001.553" addresses="0.0.0.0:5301 [::]:5301" …
```

rec: log only one line per protocol for listening sockets,

---

.github/actions/spell-check/expect.txt
docs/conf.py
pdns/dnsdistdist/docs/conf.py
pdns/recursordist/docs/conf.py

Also uses the proper style for the name of the beast, except for dnsdist which uses a different theme that does not have logo-text.html
I have:

web docs: Render search box on top.

---

pdns/recursordist/settings/table.py

The local UDP port of the recursor needs to avoid port **4791** of the **RDMA network card Roce v2 protocol** to prevent random access to this port, causing read timeouts
When the recursor sends a DNS request and the local port is specified as 4791, if there is RDMA hardware on the machine, when the response with dst as port 4791 reaches the network card driver, it will be directly processed by the hardware as Roce v2 protocol, and the recursor will not get a response to this request.
I have:

recursor udp-source-port-avoid default setting add 4791 port

---

.github/actions/spell-check/expect.txt
build-scripts/changelog-from-pr.py
docs/secpoll.zone
pdns/recursordist/docs/changelog/5.2.rst
pdns/recursordist/docs/upgrade.rst

rec: prep for rec-5.2.0-rc1

---

pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/docs/reference/dq.rst

Backport of #14850 to rel/dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport of #14850 - add elapsed time to dq object

---

modules/lmdbbackend/lmdbbackend.cc
pdns/dnsparser.cc
pdns/dnsparser.hh
regression-tests.auth-py/test_SVCB.py

This is an attempt to fix #12653. When using LMDB as backend, DNS records are serialized using `GenericDNSPacketWriter<>::xfrSvcParamKeyVals`, which writes no value in the "auto" case. Thus, when reading back with `PacketReader::xfrSvcParamKeyVals`, we should handle an empty value as the absent serialization of "auto".
Note that this does not change the way data is serialized, so there should be no interoperability problem caused by this.
I have:

Fix ipv*hint=auto on lmdb backend

---

pdns/dnsdistdist/dnsdist-idstate.hh
pdns/dnsdistdist/dnsdist.cc
regression-tests.dnsdist/test_Caching.py

The zero-scope feature involves a first cache lookup before the ECS information has been added to the query, then on a miss a second, regular lookup is done. When we get a response from the backend that contains an ECS scope set to 0, we can insert it into the cache in a way that allows using it for all clients, but we must be careful to use the key that was computed during the first lookup, and not the second one.
Incoming DoH queries make that even more interesting because while they are received over TCP, they are initially forwarded to the backend over UDP but can be retried over TCP if a TC=1 answer is received. In that case we must be very careful not to insert the answer into the cache using the wrong protocol, as we don't want to serve a TC=1 answer to a client contacting us over …

dnsdist: Fix ECS zero-scope with incoming DoH queries

---

regression-tests.recursor-dnssec/pytest.ini
regression-tests.recursor-dnssec/runtests
regression-tests.recursor-dnssec/test_Chain.py
regression-tests.recursor-dnssec/test_ExtendedErrors.py
regression-tests.recursor-dnssec/test_SimpleDoT.py
regression-tests.recursor-dnssec/test_SimpleForwardOverDoT.py
regression-tests.recursor-dnssec/test_WellKnown.py

Add `pytest` markers to
- tests that need external connectivity
- a test that has been shown to be unreliable on GH but fine elsewhere (`test_Chain.py`).
- get rid of the special status of `test_WellKnown.py`
This opens up a structured way to disable some tests on GH (if the intermittent failures become too annoying), while they are still being run locally and by buildbot.
I have:

rec: regression test markers

---

pdns/dnsdistdist/dnsdist-carbon.cc
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-lua-ffi.hh
pdns/dnsdistdist/dnsdist-lua-inspection.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-metrics.cc
pdns/dnsdistdist/dnsdist-metrics.hh
pdns/dnsdistdist/dnsdist-web.cc
pdns/dnsdistdist/docs/reference/custommetrics.rst
regression-tests.dnsdist/test_API.py
regression-tests.dnsdist/test_Prometheus.py

This adds support for prometheus labels on custom metrics. Changes the metrics maps to hold a map of labels to metric values for each metric. Metrics without labels have an empty string label combination value.
Adds an optional options table as the last parameter of `incMetric`, `decMetric`, `setMetric` and `getMetric`, which can be used to set labels by using the `label` key or to set the previously used parameter (either `step` or `value`).
Closes: #13359
I have:

dnsdist: add support for labels on custom metrics

---

docs/changelog/4.9.rst
docs/secpoll.zone

auth-4.9.3: docs&secpoll

---

pdns/recursordist/docs/lua-config/protobuf.rst
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-tcp.cc
regression-tests.recursor-dnssec/test_Protobuf.py

Fixes logic behind `taggedOnly=true` for `protobufServer()` regarding cache-returned responses,
removes the option from documentation of `outgoingProtobufServer()` as a filtering in this path was never implemented (it is accepted as a generic protobuf option only).
Closes #15007
I have:

recursor: fixed behaviour of protobufServer(.. {taggedOnly=true})

---

pdns/recursordist/decafsigners.cc

(cherry picked from commit 472b550479aa41bb08ff76b356f454ff8e4b7c9f)
Backport of #14991 
I have:

rec: Backport 14991 to rec 5.2.x: zap dangling symlink

---

pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/aggressive_nsec.hh
pdns/recursordist/rec-zonetocache.cc
pdns/recursordist/recursor_cache.cc
pdns/recursordist/recursor_cache.hh
pdns/recursordist/reczones-helpers.cc
pdns/recursordist/syncres.cc
pdns/recursordist/syncres.hh
pdns/recursordist/test-recursorcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc2.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc8.cc

Currently, we stored and return vectors, change this to store and return a shared pointer to const vectors. This allows us to return a single shared pointer on get(), avoiding to copy all vector elements. 
This approach does not work for the answer records, as modified (e.g. TTL) `DNSRecord`s are returned.
Speedup of get() of about 10% in a totally artificial test case of a single insert and many gets(). Should also save a bit on memory. We store `nullptr` for empty vectors and make sure `get()` rerurns a ready-made empty vector in that case.
This not only needs review on the detail level, but also on the general approach!
I have:
- [X compiled this code

rec: store authority recs and signatures as shared pointers to const data

---

CODING_GUIDELINES.md

noted by @BozhanL in #14993
I have:

coding guidelines: remove bool advice that conflicts with clang-tidy

---

pdns/lua-auth4.hh
pdns/lua-record.cc
pdns/packethandler.cc
regression-tests.auth-py/test_LuaRecords.py

`createForward` and `createForward6` will use the `zone_record` as base. Closes #7522
I have:

auth: createForward and createForward6 will use the zone_record as base

---

regression-tests.dnsdist/configCA.conf

The CA certificates that we are generating as par of our regression tests were lacking the X.509 `Key Usage` extension, causing TLS validation with Python 3.13 to fail with:
> certificate verify failed: CA cert does not include key usage extension
It appears that Python 3.13 enables `VERIFY_X509_STRICT` by default, which makes OpenSSL stricter, and thus it chokes on our invalid CA.
I have:

dnsdist: Fix regression tests with Python 3.13

---

pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-doh-common.cc
pdns/dnsdistdist/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/doh3.cc
pdns/dnsdistdist/doh3.hh
pdns/dnsdistdist/test-dnsdisttcp_cc.cc
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/doh3client.py
regression-tests.dnsdist/test_DOH3.py

The DoH ones have been there for a long time, but the DoH3 ones were missing. Note that we still don't have the ability to set a HTTP response for DoH3 queries (including response maps) and SNI is still missing (Quiche does not make that last one easy).
I have:

dnsdist: Add DoH3 headers, query string, path and scheme bindings

---

regression-tests.dnsdist/test_Responses.py

dnsdist: Add a regression test rewriting the response code via Lua

---

modules/geoipbackend/geoipbackend.cc
modules/geoipbackend/geoipinterface-dat.cc
modules/geoipbackend/geoipinterface-mmdb.cc
modules/geoipbackend/geoipinterface.hh
pdns/dnsdistdist/dnsdist-dynblocks.cc
pdns/dnsdistdist/dnsdist-lua-inspection.cc
pdns/sdig.cc
pdns/statnode.cc
pdns/statnode.hh
pdns/ws-auth.cc

I have:
- [x ] compiled this code

boost > std optional

---

m4/boost.m4
modules/lua2backend/lua2api2.hh
pdns/arguments.cc
pdns/dnsbulktest.cc
pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
pdns/dnsrecords.cc
pdns/svc-records.hh

Just a cleanup to prepare for C++20
I have:

clang-tidy: simplify some algorithms

---

pdns/recursordist/docs/lua-config/protobuf.rst
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-tcp.cc
regression-tests.recursor-dnssec/test_Protobuf.py

rec: Backport 15010 to rec 5.2.x: fix protobufServer(.. {taggedOnly=true}) logic for cache-returned responses 

---

.github/workflows/build-and-test-all.yml
regression-tests/recursor-test
tasks.py

On ubicloud we do not run in a container any more, as it lacks v6 connectivity. We are running a debian executable on ubuntu, this is not causing any real issues (so far) except for some boost dependencies version mismatches. Luckily the boost packages required are available on ubuntu 24.04. 
Current state of affairs:
- We run mini (100 names) tsan and ubsan+asan tests on GH (v4 only)
- We run two medium sized (50k names) ubsan + asan tests on ubicloud (v4 only and v6 enabled)
Big (or medium) tsan tests do not work as they get killed due to excessive memory requirements (many TB virtual plus many GB resident).
Plan is to add a bigger version of the bulk test in daily. That one should use a auto-built recursor package.
I have:

rec: add bigger (and v6 enabled) bulk test on ubicloud

---

.github/actions/spell-check/expect.txt
docs/lua-records/functions.rst
pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

added a new Lua function that returns pickwhashed or pickrandom(if there is no available candidate) but the weight is fetched from candidates via URL. Modified some functions to be able to provide weight as a state.
I have:

auth: added self weighted lua function

---

modules/lmdbbackend/lmdbbackend.cc

As reported in #14779, pre-v5 database schema would (incorrectly) allow for multiple TSIG keys to be created with the same name and algorithm. Once the database gets converted to v5 schema, those redundant keys can no longer be used, yet would appear in pdnsutil list-tsig-key output.
I have:

[lmdb] Ignore unreachable TSIG keys in getTSIGKeys

---

docs/lua-records/functions.rst
pdns/lua-record.cc
regression-tests.auth-py/authtests.py
regression-tests.auth-py/test_LuaRecords.py

This PR introduces two new options to the `if*up` Lua functions:
- `interval`, if provided, overrides the global `lua-health-checks-interval` value for this particular test.
- `minimumFailures`, if provided, is the number of unsuccessful checks in a row required to mark the address as down. The default is 1, which matches the current behaviour of marking an address as down at the first unsuccessful check.
I have:

Lua up checks: finer control

---

pdns/pdnsutil.cc

Old issues #1304 and #2855 describe situations where `pdnsutil add-zone-key` failed yet did not report failure.
I believe the current state of the code will correctly report failure, but it does not hurt to be more careful in `pdnsutil`. The changes in this PR achieve two things:
- `pdnsutil add-zone-key` will exit with non-zero status if attempting to get the key ID from the backend failed (for we can not be sure a key had been added in this case).
- if the backend is able to return a key ID, an extra request to fetch the key with this ID will be performed, to confirm the key has correctly be created; if this fetch fails, it will report the error and exit with a non-zero status code.
The first two commits are purely janitorial cleanup; the important change is found in the third commit. …

pdnsutil add-zone-key: more checks

---

pdns/recursordist/rpzloader.cc

rec: delete temp file on failure to dump RPZ file

---

pdns/dnsdistdist/dnsdist-lua-actions.cc
pdns/dnsdistdist/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/doh3.cc
pdns/dnsdistdist/doh3.hh
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/doh3client.py
regression-tests.dnsdist/test_DOH3.py

dnsdist: Add the ability to set custom HTTP responses over DoH3

---

.not-formatted
pdns/dnsdistdist/dnsdist-secpoll.cc

Also fix the formatting and clang-tidy warnings in the process.
I have:

dnsdist: Improve error messages on security polling failures

---

pdns/dnsdistdist/dnsdist-lua-inspection-ffi.h

The `dnsdist_ffi_stat_node_get_children_*` methods return the sum of the queries or responses received for the children of a node AND the node itself. It's quite unexpected but breaking the existing behaviour now would be painful.
I have:

dnsdist: Document `dnsdist_ffi_stat_node_get_children_*` return children+node stats

---

pdns/pdnsutil.cc

This PR is one first step in the path to make `pdnsutil` code readable and maintainable.
Key changes are:
- every toplevel `pdnsutil` command is now handled by its own routine, rather than inline in `main`.
- command declaration is now a `map` data structure, which allows the nested `if ... else if ... else if ...` spaghetti in `main` to be replaced by a `find` and function pointer call.
Did you know that `pdnsutil` had two different logic blocks handling the `hash-password` command, 600 lines of code apart, with the second one being completely dead code as it would have no chance to run?
I have:

Hair trimming in pdnsutil #1

---

pdns/auth-main.cc
pdns/dynlistener.cc
pdns/dynlistener.hh

Fixes: #1694 
This changes `DynListener` to register the "quit" function separately from other functions, and then pretend this function name has been typed when the file descriptor gets closed.
I have:

Exit gracefully on ^D on control-console

---

pdns/dnsname.hh
pdns/dnsparser.hh
pdns/dnsrecords.hh
pdns/recursordist/metrics_table.py
pdns/recursordist/recursor_cache.cc
pdns/recursordist/recursor_cache.hh
pdns/test-dnsrecords_cc.cc

This implements a better computation of the metric `cache-bytes`. The existing one neglected the size of the individual records.
This one might overestimate in some cases (string storage in string object itself) and underestimate because malloc bucket sizes, but at least it takes into account variable sized records.
I have:

rec: Compute size *estimate* for record cache allocated size

---

pdns/calidns.cc
pdns/dnsdistdist/dnsdist-cache.cc
pdns/dnsdistdist/dnsdist-ecs.cc
pdns/dnsdistdist/test-dnsdist_cc.cc
pdns/dnsdistdist/test-dnsdistedns.cc
pdns/dnsdistdist/test-dnsdistpacketcache_cc.cc
pdns/dnspacket.cc
pdns/dnsproxy.cc
pdns/dnsreplay.cc
pdns/ednssubnet.cc
pdns/ednssubnet.hh
pdns/recursordist/lua-recursor4.cc
pdns/recursordist/lwres.cc
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-tcp.cc
pdns/recursordist/syncres.cc
pdns/recursordist/syncres.hh
pdns/recursordist/test-ednsoptions_cc.cc
pdns/recursordist/test-syncres_cc1.cc
pdns/recursordist/test-syncres_cc2.cc
pdns/sdig.cc
pdns/stubresolver.cc
pdns/test-packetcache_cc.cc
pdns/test-packetcache_hh.cc

Fixes #13704 
Uses beter (rfc7871 derived) names for things and introduced encapsulation to hide the internal representation of `EDNSSubnetOpts`.
Most of this are mechanical changes, the real stuff is in `ednssubnet.??`.
I have:

EDNSSubnetOpts refactoring

---

pdns/arguments.cc
pdns/dnsparser.cc
pdns/dnsrecords.cc
pdns/rcpgenerator.cc
pdns/recursordist/lua-recursor4.cc
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/pubsuffixloader.cc
pdns/recursordist/rec-lua-conf.cc
pdns/recursordist/rec-zonetocache.cc
pdns/recursordist/rec_channel_rec.cc
pdns/recursordist/reczones.cc
pdns/recursordist/settings/generate.py
pdns/recursordist/syncres.cc
pdns/recursordist/validate-recursor.cc

Couple of cases where a variable can be moved, spotted by the new version of Coverity. All Severity "Low". You'd expect a compiler to move an object in a few cases without help, but lets follow Coverity.
I have:

rec: New Coverity Variable copied when it could be moved cases

---

pdns/recursordist/rec-zonetocache.cc
pdns/recursordist/syncres.cc

1587809 Variable copied when it could be moved
1587817 Variable copied when it could be moved
1587819 Variable copied when it could be moved
I have:

rec: Coverity issues missed in last round, all severity "Low"

---

.github/workflows/coverity.yml

Since https://github.com/PowerDNS/pdns/pull/14969 we need LLD to be able to link against the DNSdist static Rust library and LTO enabled, as oldish linkers choke on that. This PR makes sure LLD is installed in the Coverity workflow.
I have tested that this PR properly installs LLD in the environment, I can't test the whole workflow because it requires secrets that are only available on the main PowerDNS repository.
I have:

dnsdist: Fix missing LLD dependency in the Coverity workflow

---

pdns/recursordist/rec-main.cc
pdns/recursordist/settings/docs-new-preamble-in.rst

And fix a doc issue as well (`notify` vs `notify_allowed` vs `allow_notify`).
I have:

rec: better phrased --enable-old-settings warning

---

pdns/pdnsutil.cc

This boring PR boringly addresses coverity complaints about `pdnsutil`, as well as some easy-to-do clang-tidy ones.
I have:

Boring pdnsutil cleanups

---

pdns/recursordist/settings/docs-new-preamble-in.rst
pdns/recursordist/settings/table.py

…ua config.
Fixes #15052
I have:

rec: document that forwarding catalog zones cannot be combined with Lua config.

---

.github/workflows/build-docker-images.yml
Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor

This PR allows not setting credentials when setting `push: false`. Useful for testing images.
Removes warning: `LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 39)`
Test: <https://github.com/romeroalx/pdns/actions/runs/12885369941>
I have:

GH Actions - build-docker-images.yaml: allow testing image building without credentials

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-lua-actions.cc
pdns/dnsdistdist/dnsdist-lua.cc

dnsdist: Fix possible low impact performance issues reported by Coverity

---

docs/lua-records/functions.rst
pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

`createReverse6` will insert or push '0' to the converted address, so that `dig` will not treated it as an illegal IDN.
Closes #7524
I have:

auth: prevent createReverse6 from generating illegal IDN record 

---

pdns/dnsdistdist/doh3.cc
pdns/dnsdistdist/doh3.hh
pdns/dnsdistdist/doq-common.cc
pdns/dnsdistdist/doq-common.hh
pdns/dnsdistdist/doq.cc
pdns/dnsdistdist/doq.hh
pdns/dnsdistdist/m4/pdns_with_quiche.m4
regression-tests.dnsdist/doh3client.py
regression-tests.dnsdist/doqclient.py
regression-tests.dnsdist/test_SNI.py

This PR adds Server Name Indication support for incoming QUIC (DoQ, DoH3) connections. It requires an accessor in the Quiche library that has not been merged yet, see https://github.com/cloudflare/quiche/pull/1895
Closes #14048.
I have:

dnsdist: Gather Server Name Indication on QUIC (DoQ, DoH3) connections

---

modules/bindbackend/binddnssec.cc
pdns/backends/gsql/gsqlbackend.cc
regression-tests.auth-py/test_GSSTSIG.py

When an sql insertion fails, not as a severe problem (such as a database connection timeout) but simply because no insertion took place, this should be reported as an error, but was not.
A consequence of this fix is that the `test_GSSTSIG.py` test now fail because `pdnsutil import-key-zone` now reports failure, as the sqlite database is empty at this state in the test run. The second commit addresses this by issueing `pdnsutil create-zone` first. (this operation targets the `example.org` zone which is not used/relevant in this test anyway)
I have:

Correctly report SQL insertion errors

---

.github/actions/spell-check/expect.txt
docs/lua-records/functions.rst
pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

Document geoiplookup function (introduced in #6171). Closes #8597 
Expose `enum GeoIPQueryAttribute` from geoipinterface.hh to Lua.
I have:

Document geoiplookup and expose GeoIPQueryAttribute to Lua

---

meson/libresolv/meson.build
pdns/recursordist/meson.build

1. Local arc4random was not declared as dependency
2. libresolv was not found (no pkgconfig file) but is still needed
I have:

rec: fix two issues building rec using meson on debian11

---

.gitattributes

Meson utilizes `git archive` as the first step in producing a release tarball. Certain files don't need to be distributed in release tarballs at all -- namely, files used by git itself, or by github when processing a git repository for e.g. CI purposes. They have no use case outside of a git repo -- not even as documentation.
Exclude these files from the tarball. This affects both `meson dist` and the github autogenerated tarballs on the Tags page. More work is needed to have `meson dist` reach parity with automake's `make distcheck`, but this is a start.

Force various files to be skipped when generating git archives

---

meson/ldap/meson.build

auth: try to find ldap libs in case pkconfig is missing (happens on debian11)

---

ext/lmdb-safe/lmdb-safe.cc
ext/lmdb-safe/lmdb-safe.hh
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
pdns/dnsbackend.hh
pdns/pdnsutil.cc
pdns/ueberbackend.cc
pdns/ueberbackend.hh
regression-tests.nobackend/lmdb-id-generation/expected_result
regression-tests.nobackend/lmdb-metadata-leak/expected_result
regression-tests.nobackend/lmdb-schema-upgrade/expected_result

As mentioned in issue #11060, if the use of `pdnsutil` causes local files to be created, one must be aware of this in order to make sure that the `pdns_server` process, which is likely to run with different credentials, can make use of these files.
A first version of this work would only display the message if `pdns.conf` contained `setuid` or `setgid` settings, but since not all setups use this (depending on the init system or other shenanigans), it is probably better to always warn.
I have:

Let pdnsutil warn when creating local files

---

build-scripts/docker/repo-test/templates/Dockerfile-debian.jinja2
builder-support/debian/authoritative/debian-buster/control
builder-support/debian/recursor/debian-buster/tests/control
tasks.py

bind9-dnsutils exists starting in Debian bullseye, and dnsutils stopped existing in trixie.
I have:

Replace dnsutils with bind9-dnsutils

---

pdns/dnsbackend.hh
pdns/tcpreceiver.cc

Parse errors in getCatalogMembers() did result in a valid but empty catalog zone.
I have:

auth, check return value of getCatalogMembers()

---

modules/tinydnsbackend/tinydnsbackend.cc
modules/tinydnsbackend/tinydnsbackend.hh

This PR extends the `TinyBackend` capabilities to:
- implement the `getDomainInfo` in order to query a single domain.
- make sure all backend functions which may end up discovering domains update the internal state, in order to make sure that we can compute unique domain ids which are not `-1`.
Fixes #14563
I have:

Grow tinybackend capabilities a bit

---

pdns/tcpreceiver.cc

auth-4.7, check return value of getCatalogMembers()

---

pdns/tcpreceiver.cc

auth-4.9 check return value of getCatalogMembers()

---

.github/actions/spell-check/expect.txt
.github/actions/spell-check/patterns.txt
pdns/dnsdistdist/docs/reference/selectors.rst
regression-tests.dnsdist/test_RE2.py

Closes https://github.com/PowerDNS/pdns/issues/15099
I have:

dnsdist: Document that RE2 does full matching, add regression tests

---

builder-support/debian/dnsdist/debian-bookworm/control
builder-support/debian/dnsdist/debian-bookworm/rules
builder-support/debian/dnsdist/debian-buster/control
builder-support/debian/dnsdist/debian-buster/rules
builder-support/dockerfiles/Dockerfile.dnsdist
builder-support/specs/dnsdist.spec
pdns/dnsdistdist/test-dnsdistrules_cc.cc

This PR switches the compiler from G++ to clang++ to keep building with LTO, which is not possible with g++ now that we link against a Rust-based static library built with LLVM.
Note that it breaks on EL-7 (no python yaml package) and Debian Buster (linking issue related to std::filesystem I haven't investigated yet). We might get away with not supporting DNSdist 2.0+ on these.
I have:

dnsdist: Enable the new YAML configuration in our packages

---

pdns/dnsdistdist/.gitignore
pdns/dnsdistdist/dnsdist-rust-lib/Makefile.am
pdns/dnsdistdist/dnsdist-rust-lib/dnsdist-settings-generator.py
pdns/dnsdistdist/dnsdist-rust-lib/meson.build
pdns/dnsdistdist/meson.build

Our Python script to generate actions, selectors and settings from the YAML definitions of these items was making too many assumptions about the current working directory, which is just wrong outside of  the autotools world.
This PR also add our unit tests to `meson test`, and add the XSK fuzzing target to `.gitignore`.
I have:

dnsdist: Better handling of out-of-tree builds

---

pdns/dnsdistdist/doh3.cc
pdns/dnsdistdist/m4/pdns_with_quiche.m4
pdns/dnsdistdist/meson/quiche/meson.build

Quiche 0.23.0 has renamed `quiche_h3_event_headers_has_body` to `quiche_h3_event_headers_has_more_frames`, so we need to handle that.
I have:

dnsdist: Handle Quiche >= 0.23.0 since the API changed

---

pdns/recursordist/meson.build
pdns/recursordist/pdns-recursor.service.meson.in

Stolen from auth mostly.
Fixes #15116
I have:
Diff between autotools and meson:
```
--- pdns-recursor.service	2025-02-04 15:14:44.839361699 +0100
+++ build/pdns-recursor.service	2025-02-04 16:29:17.886166778 +0100
@@ -1,12 +1,13 @@
[Unit]
Description=PowerDNS Recursor
-Documentation=man:pdns_recursor(1) man:rec_control(1)
+Documentation=man:pdns_recursor(1)
+Documentation=man:rec_control(1)
Documentation=https://doc.powerdns.com
Wants=network-online.target
After=network-online.target time-sync.target
[Service]
-ExecStart=/usr/local/sbin/pdns_recursor --daemon=no --write-pid=no --disable-syslog --log-timestamp=no
+ExecStart=/usr/local/sbin/pdns_recursor   --daemon=no --write-pid=no --disable-syslog --log-timestamp=no
User=pdns
Group=pdns
Type=notify
@@ -45,7 +46,7 @@
RemoveIPC=true …
```

rec: create service unit files when building using meson

---

pdns/dnsdistdist/meson.build

dnsdist: Fix meson build failure when DoH3 support is disabled

---

pdns/dnsdistdist/meson/re2/meson.build

Apparently some version(s) of `re2` pass `-std=c++11` in the result of `pkg-config --cflags`, which helpfully downgrades us from C++17 to C++11. Let's just ignore what it says.
I have:

dnsdist: Ignore `re2`'s broken compilation flags

---

pdns/recursordist/settings/docs-new-preamble-in.rst
pdns/recursordist/settings/rust/src/bridge.rs
pdns/recursordist/settings/table.py

Plus an extra consistency check in the case of `forward_zones` (`forward_zones_recurse` cannot be done easily as the code actually does not look at the flag value, but is driven by the name of the field being processed, the incoming YAML has the flag set to `false` by default.
I have:

rec: better explain how the recurse field works in various contexts

---

pdns/dnsdistdist/meson/quiche/meson.build

Before this commit we only tried older versions of Quiche if the `quiche` feature was not explicitely enabled, and failed otherwise.
I have:

dnsdist: Gracefully fall back to older versions of Quiche

---

pdns/dnsdistdist/dnsdist-xsk.cc
pdns/dnsdistdist/xsk.cc
pdns/dnsdistdist/xsk.hh

In https://github.com/boostorg/lockfree/pull/90 `boost::lockfree::spsc_queue` introduced moved semantics, which is great, but added restrictions to the callback functor that did not exist before, breaking the API. This PR fixes that by updating our callbacks to expect an object instead of a reference.
I have:

dnsdist: Fix compatibility with `boost::lockfree` >= 1.87.0

---

docs/manpages/pdnsutil.1.rst
docs/settings.rst
docs/upgrading.rst
pdns/pdnsutil.cc

As suggested in #3878, in the absence of algorithm names and key sizes on the commandline, `pdnsutil add-zone-key` could make use of the defaults in `pdns.conf`, is any, rather than hardwired values.
This trivial PR implements this and updates the documentation accordingly.
I have:

[pdnsutil] Let add-zone-key use defaults from pdns.conf

---

pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-lua-bindings-protobuf.cc
pdns/dnsdistdist/dnsdist-rust-lib/rust/src/lib.rs
pdns/dnsdistdist/dnsdist-settings-definitions.yml
pdns/dnsdistdist/docs/reference/dnstap.rst
pdns/dnsdistdist/docs/reference/protobuf.rst
pdns/dnsdistdist/docs/reference/yaml-settings.rst
pdns/dnsdistdist/meson.build
pdns/dnsdistdist/remote_logger_pool.cc
pdns/dnsdistdist/remote_logger_pool.hh
pdns/remote_logger_pool.cc
pdns/remote_logger_pool.hh
regression-tests.dnsdist/test_Dnstap.py

This adds a new kind of `RemoteLoggerInterface`: `RemoteLoggerPool`. It can take multiple other `RemoteLoggerInterface`s and pass data to them in round-robin order by default.
This also adds additional option to `newRemoteLogger`, `newFrameStreamTcpLogger` and `newFrameStreamUnixLogger`: `connectionCount`, which can be used to generate a pool with multiple connections.
Closes: #14861
I have:

dnsdist: add pooling support for `RemoteLoggerInterface`

---

pdns/recursordist/lwres.hh
pdns/recursordist/rec-tcounters.hh
pdns/recursordist/syncres.cc

Safe right now as `LWResult::d_rcode` gets assigned from the 4 bit `rcode` in the header.  But that might change one day. I'd rather make `LWResult::d_rcode` an `uint8_t`, but that causes a conflict with the OOB resolving code that does not make a difference between `res` and `d_rcode`.
Also fix a typo in a constant name and reorder fields in `LWResult` largest to smallest.
I have:

rec: check bounds of rcode stats counter index (safe right now)

---

docs/manpages/sdig.1.rst
pdns/Makefile.am
pdns/ednscookies.cc
pdns/ednscookies.hh
pdns/misc.cc
pdns/misc.hh
pdns/recursordist/Makefile.am
pdns/recursordist/meson.build
pdns/recursordist/test-ednscookie_cc.cc
pdns/sdig.cc
pdns/test-ednscookie_cc.cc

Pretty basic, user is required to set the correct cookie on a BADCOOKIE answer, which is shown in the first request/reply below. The second request/reply shows what happens if you set a correct cookie.
```
$ ./sdig 192.168.178.3 53 sub.sub.example.com a cookie -
Reply to question for qname='sub.sub.example.com.', qtype=A
Rcode: 23 (Bad/missing Server Cookie), RD: 0, QR: 1, TC: 0, AA: 1, opcode: 0
2	.	16777216	IN	OPT	AAoAGGrZ7yCJECiwAQAAAGerQcoDWpPycNQHaQ==
EDNS Cookie response: 6ad9ef20891028b00100000067ab41ca035a93f270d40769
$ ./sdig 192.168.178.3 53 sub.sub.example.com a cookie 6ad9ef20891028b00100000067ab41ca035a93f270d40769
Reply to question for qname='sub.sub.example.com.', qtype=A
Rcode: 0 (No Error), RD: 0, QR: 1, TC: 0, AA: 1, opcode: 0
0	sub.sub.example.com.	60	IN	A	1.2.3.4
2	.	0 …
```

sdig: implement cookie support

---

pdns/pdnsutil.cc

This applies the same "fetch key after add" verification logic, added to `pdnsutil` `add-zone-key` command recently, to the `import-zone-key` and `import-zone-key-pem` commands.
I have:

pdnsutil: check for key presence after import

---

docs/settings.rst

This innocent-looking PR attempts to clean a few minor things:
- address documentation build warnings 
- ~~address code build warnings when building the authoritative server by moving `static` code within the `#ifdef ... #endif` blocks which is its only user.~~ <-- fixed in the meantime by other changes
There is no guarantee you won't fall asleep out of boredom while looking at it.
I have:

Boring minor cleanups

---

modules/lmdbbackend/lmdbbackend.cc

This simple PR intends to improve the LMDB backend performance in the following situations:
- upon low-memory conditions, by disabling operating system read ahead on the database file, which could cause some read operations to put database contents in the buffer cache at the expense of memory available to the processes.
- when processing large RRSET updates, by allocating a temporary data structure once to its desired size, rather than having it grow multiple times to reach its final size.
I have:

Low-hanging LMDB fruits

---

docs/generate-man-pages.py
meson.build
pdns/dnsdistdist/dnsdist.service.meson.in
pdns/dnsdistdist/docs/generate-man-pages.py
pdns/dnsdistdist/meson.build
pdns/dnsdistdist/meson_options.txt
pdns/recursordist/meson.build

dnsdist: Install binary, man page and systemd unit files with meson

---

pdns/dnsdistdist/dnsdist-lua.cc

The console address and port were not properly set in client mode, so `dnsdist` tried to connect to the default console address and port.
I have:

dnsdist: Fix console ("client mode") on non-default address or port

---

pdns/dnsdistdist/meson.build

Since we now use the `follow_symlinks` option of `install_data()`. We could probably make it work with older versions but a quick look at what distributions provide suggests that 1.2.1 or 1.3.0 is practically the same amount of pain.
I have:

dnsdist: Bump the required version of `meson` to 1.3

---

pdns/recursordist/meson.build

recursor/meson: fix typo in comment

---

pdns/dnsrecords.cc
pdns/pdnsutil.cc
pdns/zoneparser-tng.cc
regression-tests.nobackend/lmdb-schema-upgrade/expected_result

There are a couples of issues where people have noticed odd behaviour with ALIAS records. My understanding of them is that they should be represented similarly to CNAME records, except for name compression.
This PR implements this and makes sure that they are stored with a non-root trailing dot[1], and said dot is removed for display and when serving the record contents.
[1] Except on LMDB, which always stores records without non-root trailing dots; I suppose this is intentional in order to save space in the database.
I have:

Make the record representation of ALIAS match CNAME

---

docs/modes-of-operation.rst

Try to improve freshness-check description
I have:

Try to improve freshness-check description

---

pdns/dnsdistdist/dnsdist-actions-factory.cc
pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-rules.cc

This time I'm using `[[maybe_unused]]` because the parameters will be used in some configurations. So ``[[maybe_unused]]`` is not actually useless!
I have:

dnsdist: Fix several unused parameter warnings without DoH support

---

builder-support/gen-version
pdns/dnsdistdist/builder-support/gen-version
pdns/dnsdistdist/meson-dist-script.sh
pdns/dnsdistdist/meson.build
pdns/dnsdistdist/version.sh
pdns/recursordist/builder-support/gen-version

This PR mimics what was done for the recursor, allowing DNSdist tarballs to be generated via `meson`. The resulting tarball builds fine, and looking at the differences with the same tarball generated via `autotools` did not show any issue (there are some differences, mostly generated files that are present in the `meson`-generated tarball and not in the `autotools` one. If anything this is a missing optimization in the `autotools` version). `htmlfiles.h` is included in the `autotools` version and not in the `meson` one, but that does not seem to be an issue.
It also includes the `man-pages` optimization added to the recursor in https://github.com/PowerDNS/pdns/pull/15161.
I have:

dnsdist: Generate tarballs via `meson dist`

---

pdns/recursordist/rec-main.cc
pdns/recursordist/ws-recursor.cc

A couple cases of complaints that should be eliminated by reducing the scope of a lock plus one "you can use a ref".
I have:

rec: coverity 20250217

---

regression-tests.dnsdist/test_Dnstap.py

Since we now use more than one TCP connection, it is entirely possible for the response message to arrive before the query one, and our tests should just deal with that.
I have:

dnsdist: Handle response dnstap messages arriving before the query ones

---

modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh

Recent tinkering made me discover the hard way that, in some corner (error) cases, I could get a double `free` in the `LMDBBackend` destructor.
Further investigation showed that we can end up with two active LMDB transactions; these need to be aborted in the reverse order of their creation, and, well, this wasn't always the case.
This PR fixes this problem.
I have:

Improve LMDBBackend reliability

---

pdns/auth-main.cc
pdns/lua-record.cc
pdns/packethandler.cc

While trying to help a user trying to make use of Lua records, I couldn't help but notice the related log messages would use different spellings for "Lua".
This PR attempts to homogeneize this, to make searching in the logs easier.
I have:

Consistent spelling of "Lua record" in logs

---

pdns/dnsdistdist/dnsdist-xsk.cc
pdns/xsk.cc
pdns/xsk.hh

Backport of #15137 to dnsdist-1.9.x: In https://github.com/boostorg/lockfree/pull/90 `boost::lockfree::spsc_queue` introduced moved semantics, which is great, but added restrictions to the callback functor that did not exist before, breaking the API. This PR fixes that by updating our callbacks to expect an object instead of a reference.
(cherry picked from commit 05543aed8ccff2270a65d3f9b75e6e9d894b8b45)
I have:

dnsdist-1.9.x: Backport of 15137 Fix compatibility with boost::lockfree >= 1.87.0

---

pdns/dnsdistdist/doh3.cc
pdns/dnsdistdist/m4/pdns_with_quiche.m4

Backport of #15118 to dnsdist-1.9.x: Quiche 0.23.0 has renamed `quiche_h3_event_headers_has_body` to `quiche_h3_event_headers_has_more_frames`, so we need to handle that.
I have:

dnsdist-1.9.x: Handle Quiche >= 0.23.0 since the API changed

---

docs/appendices/backend-writers-guide.rst
docs/backends/generic-sql.rst
docs/backends/geoip.rst
docs/changelog/4.0.rst
docs/changelog/4.1.rst
docs/changelog/4.7.rst
docs/dnssec/migration.rst
docs/guides/basic-database.rst
docs/running.rst
docs/upgrading.rst

docs: link to doc:pdnsutil

---

docs/dnssec/migration.rst

Small tweaks to DNSSEC migration
I have:

docs: DNSSEC migration

---

pdns/misc.cc
pdns/webserver.cc

Add two missing includes

---

pdns/recursordist/rec-rust-lib/table.py
pdns/recursordist/reczones.cc

The YAML code already disallows an empty forwarders list. The added case mainly covers the case when an old-style forward file is parsed as if it's YAML. This now generated an error:
Feb 21 09:57:39 msg="Fatal error" error="empty list of forwarders for domain '- zone: example.com\"on line 1 of tmp/f.conf" subsystem="config" level="0" prio="Critical" tid="0" ts="1740128259.137" exception="PDNSException"
This hopefully makes admins realize rec is trying to parse YAML content, but is expecting old-style as the file does not end in in .yml.
I have:

rec: document file extension of zone forward file and do not accept empty list of forwards

---

docs/appendices/types.rst
docs/backends/bind.rst
docs/backends/generic-sql.rst
docs/backends/ldap.rst
docs/backends/lua2.rst
docs/backends/remote.rst
docs/backends/tinydns.rst
docs/dnssec/operational.rst
docs/dnsupdate.rst
docs/domainmetadata.rst
docs/guides/alias.rst
docs/http-api/zone.rst
docs/manpages/zone2sql.1.rst
docs/migration.rst
docs/running.rst
docs/settings.rst
docs/tsig.rst

docs: Update to primary/secondary

---

docs/manpages/pdnsutil.1.rst
pdns/pdnsutil.cc

This is another take at #12350 ("Group pdnsutil usage by topic"). The dictionary of `pdnsutil` commands is extended with a "command group" and the short help text, for every command. This allows these help texts to be output in groups, with alphabetical ordering within each group, automagically.
Doing this also exposes a few commands which lack help texts, these can either remain hidden or get gifted a nice help text (to be discussed in this PR).
The grouping of commands is ~~stolen~~ borrowed from #12350 and open for discussion as well. The changes in this PR allow for group assignment to be changed very easily, as well as new groups created, if deemed useful.
I have:

More helpful pdnsutil help output

---

.github/workflows/documentation.yml

This got removed in #14767 by accident.
I tested that this works without any variables or secrets by pushing to master on a fork, without this patch.
I have:

docs: reinstate artifact generation for PRs

---

pdns/recursordist/settings/table.py
pdns/recursordist/test-settings.cc
pdns/root-dnssec.hh
regression-tests.recursor-dnssec/test_TrustAnchors.py

fetched from https://www.iana.org/dnssec/files after their 2024-07-24 update
(cherry picked from commit 0bbbdd60ab054e7bbfc2b0d0604d1f7e15f0a229)
Backport of #14525 
I have:

rec: Backport 14525 to rec-5.1.x: add 38696 root anchor

---

pdns/recursordist/lua-recursor4.cc
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh

Main change in `RecThreadInfo`, rest is consequential.
I have:

rec: store thread id in info object, makes a few methods less error prone

---

pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

This adds a missing validation step in `createForward`, where a code path would be too confident assuming the data it works on is a valid hex representation of an ipv4 address.
This is a one-liner in spirit, the changes are a bit larger in order to appease `clang-tidy`.
I have:

Damage control in Lua createForward()

---

ext/lmdb-safe/lmdb-safe.hh
modules/lmdbbackend/lmdbbackend.cc

Posted for first review. Bit draft still.
After updating `lookup()` and `get()` for the prefix method, I also had to update `list()` (as that also just prepares us for `get()`).
I don't think any other functions in lmdbbackend.cc need updating to work correctly; I do think a few more could benefit.
I copied the StringView define from lmdbbackend.cc but I'm not sure it's doing the right thing (in either place perhaps). It's also possible that we can fully rely on having the right Boost version these days.
I have:

lmdb-safe: add prefix() cursor; use it in list/lookup/get

---

modules/lmdbbackend/lmdbbackend.cc

I noticed recently that a multi-backend configuration with LMDB as the last backend would not display all domains in `pdnsutil list-all-zones` (and possibly other operations).
This is caused by the LMDB backend replacing the data instead of appending to it.
I have:

Fix list-all-zones in multi-backend configuration involving LMDB

---

.github/actions/spell-check/expect.txt
.github/workflows/spelling3.yml
pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

auth 4.8.x: Backport "Damage control in Lua createForward() and createForward6()."

---

.github/actions/spell-check/excludes.txt
.github/actions/spell-check/expect.txt
docs/conf.py
docs/depfile.py
docs/generate-docs.py
docs/generate-man-pages.py
meson.build
pdns/dnsdistdist/docs/conf.py
pdns/dnsdistdist/docs/depfile.py
pdns/dnsdistdist/docs/generate-docs.py
pdns/dnsdistdist/meson.build
pdns/recursordist/docs/conf.py
pdns/recursordist/docs/depfile.py
pdns/recursordist/docs/generate-docs.py
pdns/recursordist/meson.build

Same script used for rec, auth and dnsdist docs. All meson.build file gain a few new targets: `html_docs`, `html-docs.tar.bz2` and `product-name.pdf` and a do all called `all-docs`.
To test run `meson compile -C builddir *target*`.
Note that generating a pdf needs latex. The meson script does not check for that atm.
TODO:
I have:

Use meson to generate docs (html + pdf)

---

ext/lmdb-safe/lmdb-safe.cc
regression-tests.auth-py/test_LuaRecordsLMDB.py

It has been noticed that using `include` statements in Lua records served by LMDB would cause a `SERVFAIL` result, with a `Duplicate RW transaction` exception report in the server logs.
~~This is caused by almost all LMDB transactions in the server being considered as RW transactions, even when they aren't; LMDB does not allow for more than one writer to operate at the same time, by design.~~
~~This PR reworks the way the RO/RW status of the transaction is decided, and correctly uses RO transactions. Note that the existing lmdb access code here seems to be written assuming an LMDB RW transaction is not allowed to coexist with any other transaction, even RO ones. If I am wrong on this, I have a much simpler fix (one-liner) to propose instead.~~
Edit: these changes introduced a …

Avoid LMDB exception during recursive lookup

---

pdns/pdnsutil.cc

As reported in #15130, `pdnsutil increase-serial` should fail on secondary zones.
The approach in this PR is quite conservative, if the backend is not able to report whether the zone is primary or secondary, we'll try to increase anyway - have to trust the user at some point.
Similarly, there is no check added to `pdnsutil edit-zone`. We assume you know more or less what you are doing.
I have:

[pdnsutil] Do not allow increase-serial on secondary zones

---

pdns/pdnsutil.cc
regression-tests/backends/bind-master
regression-tests/backends/geoip-master
regression-tests/backends/gmysql-slave
regression-tests/backends/godbc_mssql-slave
regression-tests/backends/gpgsql-slave
regression-tests/backends/gsqlite3-slave
regression-tests/backends/ldap-master
regression-tests/backends/lmdb-master
regression-tests/backends/lmdb-slave
regression-tests/backends/lua2-master
regression-tests/backends/remote-master
regression-tests/tests/pdnsutil-zone-handling/command
regression-tests/tests/pdnsutil-zone-handling/description
regression-tests/tests/pdnsutil-zone-handling/expected_result

The discussion of #4727 suggests that adding some smarts to `add-record` for it not to insert duplicate content would be welcome.
This PR does exactly this, and also tries to make the "Thou shalt not mix CNAME with other records" logic easier to follow.
I have:

[pdnsutil] dedup in add-record

---

pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

Today is a new moon, so it's perfect time to work on Lua support in PowerDNS.
This purely janitorial PR splits the monster function `setupLuaRecords` into pieces, so that every single Lua helper function (such as `createReverse`, `ifurlup`...) can be found in its own function.
This will help working in this area in the future.
Probably better reviewed in a per-commit basis, with whitespace changes ignored in the first commit.
I have:

[auth] [janitor] Mop up some Lua records code

---

.github/actions/spell-check/expect.txt
docs/lua-records/functions.rst
pdns/lua-record.cc
pdns/minicurl.cc
pdns/minicurl.hh
regression-tests.auth-py/test_LuaRecords.py

This supersedes #10431. Sorry for the mess.
I have:

auth lua records: new option to set the http status code to match in ifurlup function

---

docs/lua-records/functions.rst
pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

This option, is set to "true", will force the `if*up` Lua functions to return SERVFAIL, rather than applying the backupSelector, if none of the health checks for the targets to check have completed yet.
And you get a few tab->spaces fixes, at no extra charge!
I have:

Add a "failOnIncompleteCheck" option to if*up Lua functions

---

docs/lua-records/reference/comboaddress.rst
pdns/dnsdistdist/dnsdist-lua-bindings.cc
pdns/dnsdistdist/docs/reference/comboaddress.rst
pdns/lua-base4.cc

Add newCAFromRaw docs, getRaw func+doc
It's mostly dumb copy-paste
Fixes #15246
I have:
- I don't see any existing dnsdist regression/unit tests using these functions and I think adding them is beyond the scope

lua comboaddress: raw docs, cleanups, dnsdist add getRaw

---

pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/rec-tcp.cc

And while there make it file-local.
This is an attempt to fix the ASAN crash in https://github.com/PowerDNS/pdns/pull/15257#issuecomment-2706009670
but I'm not sure how this scenario (`t_tcpClientCounts` not-initialized or a `nullptr`) can happen, as RecursorThreads are only cleanup up after they have been fully initialized and the multiplexer (the relevant parent in the dt cal stack) is only created for RecursorThreads after `t_tcpClientCounts` is inited.
But as this method of letting the runtime do the init is much cleaner, I decided to create the PR anyway. 
I did not succeed in reproducing the ASAN issue locally.
I have:

rec: make sure t_tcpClientCounts is always initialized

---

pdns/recursordist/syncres.cc
pdns/recursordist/syncres.hh
pdns/recursordist/test-syncres_cc1.cc

Ale make sure to removed the skipped answer records. It's a bit sad we have to do this, but some auths have no issue sending us illegal answers, and in this case it was very probable intended to follow the CNAME.
I have:

rec: if we see a CNAME and an answer record, follow CNAME

---

regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_Chain.py

UDP is more or less kaput on GitHub, even for the local interface. If this works on GH as expected/hoped for, we have more strict consistency checks.
I have:

rec: make the chain test more reliable by using TCP

---

Dockerfile-dnsdist

And remove `h2o` support which is now deprecated.
I have:

dnsdist: Fix the location of the dnsdist-quiche library in our Docker image

---

pdns/dnsdistdist/meson/lua/meson.build

This is a lot better than the existing `rdynamic` option because the symbols of our internal, static Rust library are somehow showing up in the final binary otherwise.
I have:

dnsdist: Export only FFI symbols, regardless of visibility

---

pdns/dnsdistdist/dnsdist-actions-factory.cc
pdns/dnstap.cc
pdns/dnstap.hh
pdns/dnstap.proto
regression-tests.dnsdist/test_Dnstap.py

dnsdist: add support for dnstap new http_protocol field

---

pdns/dnsdistdist/dnsdist-idstate.hh
pdns/dnsdistdist/dnsdist-protobuf.cc
pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/docs/reference/rules-management.rst
regression-tests.dnsdist/test_Protobuf.py

Properly set `packetCacheHit` and `outgoingQueries` fields in logged protobuf messages. The number of `outgoingQueries` is set to `0` when the answer is either self generated or a cachehit. Otherwise set to `1`.
I have:

dnsdist: protobuf, support packetCacheHit and outgoingQueries fields

---

pdns/recursordist/syncres.cc
pdns/recursordist/test-syncres_cc1.cc

rec: Backport 15254 to 5.1.x: If we see both a CNAME and answer records, follow CNAME and discard the answer records

---

pdns/dnsdistdist/dnsdist-actions-factory.cc

dnsdist: Fix "missing declaration" warning for `ProtocolToDNSTap`

---

pdns/dnsdistdist/meson/xsk/meson.build

The detection of whether `bpf_xdp_query` is available was not done.
I have:

dnsdist: Fix XSK mode detection when built with `meson`

---

.github/workflows/build-and-test-all.yml
tasks.py

To get rid of the `WARNING: Symbolizer buffer too small` warning, which is caused by big backtraces, and fixed in clang >= 15 by using a dynamic symbolizer buffer size.
I only upgrade it for dnsdist because of a compatibility issue between `libfaketime` and the ASAN implementation in recent versions of `clang`:
https://github.com/wolfcw/libfaketime/issues/365
It seems to be fixed in the `libfaketime` repository. There has not been any release since the fix, but I guess we could compile from a more recent commit.
I have:

dnsdist: Upgrade clang to 19 in our CI

---

pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-console.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-rust-lib/rust/src/lib.rs
pdns/dnsdistdist/dnsdist-settings-definitions.yml
pdns/dnsdistdist/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/yaml-settings.rst

Currently TCP backend has per server config option while UDP backend can only use the global timeout setting. This change will add timeout config per UDP backend server.
Add per backend server timeout config for UDP case
I have:

Add timeout config per UDP backend server

---

.github/workflows/build-packages-daily-master.yml
.github/workflows/build-packages.yml

~The dockerfile for building `ubuntu-focal` is still needed. The target is still used by `build-packages.yml`. It was removed in #15277~
Specify the list of target os for the building daily packages for master. 
Skip with a [warning](https://github.com/romeroalx/pdns/actions/runs/13837226839/job/38715241163#step:4:7) the OS for which there is no target dockerfile
Error: <https://github.com/PowerDNS/pdns/actions/runs/13827425631>
Test: <https://github.com/romeroalx/pdns/actions/runs/13837226839>
I have:

Specify the list of target-os for the daily build of packages

---

.github/workflows/build-and-test-all.yml

CI appears to be flaky because of random networking problems. It seems more useful to let the other jobs run and potentially pass than to just kill them when something flaky flakes.
I have:

ci: use fail-fast: false for more jobs

---

.github/workflows/documentation.yml

Fixes the documentation workflows upload. Uses sudo to install rclone, omits the --no-wait flag on the invalidations, since that doesn't exist (...). Lastly, adds the possibility to set DOCS_WORKFLOW_BRANCH_OVERRIDE in which case the workflow doesn't check for the branch it's running on, so it can be tested on other branches. Useful in forks.
I have:

Fixes the documentation workflows upload

---

docs/settings.rst

Clarify documentation according to what @Habbie believes to be true.
I have:
- [N/A] compiled this code
- [N/A] tested this code
- [N/A] documented the code
- [N/A] added or modified regression test(s)
- [N/A] added or modified unit test(s)

docs: clarify secondary behaviour when xfr-cycle-interval elapses

---

pdns/recursordist/rec-tcp.cc

If a TCP connection is alive when we are exiting, we might dereference a `null` pointer when the TCP connection destructor is called after the thread-local `t_tcpClientCounts` object has been destroyed.
Spotted by UBSAN in the regression tests:
```
Mar 20 12:43:46 msg="Received rec_control command via control socket" subsystem="control" level="0" prio="Info" tid="0" ts="1742474626.168" command="quit-nicely"
Mar 20 12:43:46 msg="Exiting on user request" subsystem="runtime" level="0" prio="Notice" tid="0" ts="1742474626.168" nicely="1"
rec-tcp.cc:111:26: runtime error: member call on null pointer of type 'std::map<ComboAddress, unsigned int, ComboAddress::addressOnlyLessThan>'
#0 0x557fb203936a in TCPConnection::~TCPConnection() /__w/pdns/pdns/pdns/recursordist/pdns-recursor-0.0.0-git1/rec-t …
```

rec: Prevent a crash when exiting nicely

---

builder-support/debian/dnsdist/debian-bookworm/rules
builder-support/debian/dnsdist/debian-bullseye/rules
builder-support/specs/dnsdist.spec
pdns/dnsdistdist/meson.build

Successful package build run at: https://github.com/rgacogne/pdns/actions/runs/13988473202
I have:

dnsdist: Better handling of the `dlsym` missing symbol in our Rust lib

---

ext/lmdb-safe/lmdb-typed.hh

We (@Habbie and I) have been puzzled by seeing `in index get, found more than one item` exceptions thrown by the LMDB backend. The message was misleading - what happened was that there was exactly one item, but it was marked as deleted, so retrieving it correctly failed, and this possible outcome was not guarded against.
This PR attempts to provide more accurate exception messages, and to correctly handle this situation by returning no result (absence of data).
I have:

[auth] lmdb: be more robust against marked-as-deleted items

---

modules/gmysqlbackend/smysql.cc

Found on s390x
DB contents:
```
MariaDB [pdns]> select * from records;
+----+-----------+-------------------------+------+----------------------------------------------------------+--------+------+----------+-----------+------+
| id | domain_id | name                    | type | content                                                  | ttl    | prio | disabled | ordername | auth |
+----+-----------+-------------------------+------+----------------------------------------------------------+--------+------+----------+-----------+------+
|  1 |         1 | mysql.example.org       | SOA  | ns1.example.org dns.example.org 1 10800 3600 604800 3600 | 172800 |    0 |        0 | NULL      |    1 |
|  2 |         1 | mysql.example.org       | NS   | ns1.example.org …
```

mysql: use MYSQL_TYPE_LONGLONG on 64bit platforms

---

docs/changelog/pre-4.0.rst
docs/security-advisories/powerdns-advisory-2012-01.rst
docs/security-advisories/powerdns-advisory-2015-01.rst
docs/security-advisories/powerdns-advisory-2015-02.rst
docs/security-advisories/powerdns-advisory-2015-03.rst
pdns/recursordist/docs/changelog/pre-4.0.rst
pdns/recursordist/docs/security-advisories/powerdns-advisory-2014-01.rst

https://doc.powerdns.com/authoritative/security-advisories/powerdns-advisory-2015-01.html renders:
```
Workaround: Run your Recursor under a supervisor. Exposure can be limited by configuring the `allow-from <../recursor/settings.md#allow-from>`__ setting so only trusted users can query your nameserver. There is no workaround for the Authoritative server.
```
The goal was for `allow-from` to be a link to recursor/settings
Also, the files are now (and have been for a while!) `.rst`, not `.md`....
I have:

Docs: Fix allow-from markup/link

---

pdns/Makefile.am

I found the hard way that changes I was brewing would build with autoconf but not with meson, because autoconf no longer cause `tsig-tests` to be built, which made me miss changes required in `tsig-tests.cc`.
This PR causes this test program to be built again if `--enable-tools` is used (similarly to `speedtest`).
I have:

[autocconf] [auth] Build tsig-tests if --enable-tools

---

ext/lmdb-safe/lmdb-typed.hh

auth-4.9.x: Handle marked-as-deleted elements in ReadonlyOperations::get<>

---

modules/geoipbackend/geoipbackend.cc

Once upon a time, a PowerDNS user forgot to put a space after a semicolon in a YAML configuration file, and `pdns_server` complained with something as unpleasant as:
```
Caught an exception instantiating a backend (geoip): Cannot read config file illegal map value
```
The changes in this PR try to give a bit more information to help figure out what went wrong:
```
Caught an exception instantiating a backend (geoip): Configuration error in /users/miod/config/geoip/zones.yml, line 5, column 10: illegal map value
```
Note that the error location, in this particular error case, points to the next keyword in the file. But even if it is not 100% accurate, this helps narrowing where the problem must be, which can be helpful for large files.
I have:

[geoip] Try and be more helpful in YAML error exceptions

---

docs/settings.rst
pdns/pdnsutil.cc

~~This addresses #8785 by applying the `default-soa-edit` recipe to the freshly created zone serial number, unless `default-soa-content` contains a non-zero serial number.~~
This now only suggests invoking `increase-serial` if relevant.
I have:

[pdnsutil] Suggest increase-serial after create-zone

---

configure.ac
meson/various-functions/meson.build
pdns/recursordist/configure.ac
pdns/ws-api.cc

There is a `strcasestr` implementation in case the function is not provided by libc, which was apparently needed by json-related code and added to run on older Solaris versions, in the auth 3.x days.
However, years later, nothing in the current code uses this function anymore, so there is no need to 1) check for its availability and 2) provide an implementation if it is missing.
I have:

bye bye strcasestr

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc

This commit changes the way DNSdist handles a non-existent Lua function name being referenced from the YAML configuration: instead of silently ignoring the problem, it loudly complains before exiting.
See https://github.com/PowerDNS/pdns/discussions/15350
I have:

dnsdist: Better handling of non-existent Lua function name in YAML

---

pdns/dnsdistdist/dnsdist-rust-lib/rust/build_dnsdist_rust_library
pdns/recursordist/rec-rust-lib/rust/build_recrust

This happens in OpenBSD package build. Please test in your build environment. Here al went fine with different in-tree and out-of-tree build dirs.
I have:

When CARGO_TARGET_DIR is set the generated C++ files end up in a different location

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-lua.cc

It does not make sense, and in some cases might lead to a crash because the Xsk socket is actually an empty shared pointer in client mode.
I have:

dnsdist: Do not register Xsk sockets on configuration check or client mode

---

regression-tests.dnsdist/test_Async.py

The existing code was catching all exceptions based on `OSError` raised by a call to `os.unlink()` , and re-throwing if the file actually existed, in an attempt to only ignore the case where the file did not exist and still fail if the process did not have enough rights to remove it, for example.
Unfortunately this construct introduced a TOCTOU issue, where the initial exception might have been raised because the file did not exist at the time of the call, resulting in a `FileNotFoundError` exception being raised, but had been created before the existence check, resulting in a puzzling message:
```
ready: 8/8 workersException in thread Asynchronous Responder:
Traceback (most recent call last):
File "/usr/lib/python3.13/threading.py", line 992, in run
self._target(*self._args, …
```

dnsdist: Fix a TOCTOU in the Async regression tests

---

regression-tests.dnsdist/runtests
regression-tests.dnsdist/test_SNI.py

We now build with Quiche >= 0.23.2 so we can enable them.
Closes https://github.com/PowerDNS/pdns/issues/15079
I have:

dnsdist: Enable the DoQ and DoH3 parts of the SNI tests in our CI

---

docs/appendices/backend-writers-guide.rst
modules/bindbackend/bindbackend2.hh
modules/bindbackend/binddnssec.cc
modules/geoipbackend/geoipbackend.hh
modules/ldapbackend/ldapbackend.hh
modules/lmdbbackend/lmdbbackend.hh
modules/lua2backend/lua2api2.hh
modules/pipebackend/pipebackend.hh
modules/remotebackend/remotebackend.cc
modules/remotebackend/remotebackend.hh
modules/tinydnsbackend/tinydnsbackend.hh
pdns/backends/gsql/gsqlbackend.cc
pdns/backends/gsql/gsqlbackend.hh
pdns/dnsbackend.hh
pdns/pdnsutil.cc
pdns/test-ueberbackend_cc.cc
pdns/ueberbackend.cc
pdns/ueberbackend.hh

This PR allows backends to report whether they support various capabilities - in spirit, this extends the `doesDNSSEC()` method.
This is then used in `pdnsutil` to avoid attempting to perform operations which will fail due to lack of support in the backend, and allows it to provide less cryptic error messages.
Addresses #15006.
The update to the backend's writer's guide is intentionally incomplete, as the omitted two capabilities do not have their relevant backend bits documented yet (it's on a todolist somewhere).
Edit: added another capability and let ÜberBackend report the aggregated capabilities of all configured backends, in order to be able to provide a better error message when a zone creation operation fails because none of the configured backend supports that operation; this …

[auth] Backend capabilities

---

pdns/.gitignore

When I made sure `tsig-tests` were built when using autoconf, I had to change the dash to an underscore due to ~autoconf being a major pain in the you-know-what~ technical reasons, but forgot to update the `.gitignore` file accordingly.
I have:

.gitignore glitch

---

pdns/ws-auth.cc

While looking at another issue, I couldn't help but notice a few minor cracks in the webservice code, with regard to zone metadata queries:
- the `API-RECTIFY` metadata is supposed to be queryable but not changeable, but due to it being missing from the known metadata names, it was not queryable.
- the `SOA-EDIT-API` metadata is supposed to be queryable and not changeable, but was also missing.
This PR updates the list of known metadata names, sorts it, and eventually reworks the data structure used to prevent a double search (once for a known name, once to know its readonly status).
I have:

[auth] minor web service cleanup

---

pdns/dnsdistdist/dnsdist-carbon.cc
pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-doh-common.cc
pdns/dnsdistdist/dnsdist-doh-common.hh
pdns/dnsdistdist/dnsdist-lua-inspection.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-settings-definitions.yml
pdns/dnsdistdist/dnsdist-tcp-upstream.hh
pdns/dnsdistdist/dnsdist-web.cc
pdns/dnsdistdist/dnsdist.hh
pdns/dnsdistdist/docs/advanced/tls-sessions-management.rst
pdns/dnsdistdist/docs/reference/yaml-settings.rst
pdns/dnsdistdist/doh.cc
pdns/tcpiohandler.cc
pdns/tcpiohandler.hh
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_TLSSessionResumption.py

Using the same Session Ticket Encryption Key on identical frontends allow TLS sessions to be resumed in a much more efficient way, reducing the latency and CPU usage. While it was already possible to do so by manually managing the STEK, the default behaviour was to create and use a different STEK for each frontend, because our Lua configuration makes it almost impossible to ensure that two frontends are identical.
This is not an issue with the new YAML configuration format, so let's share the STEK automatically in this case.
Closes https://github.com/PowerDNS/pdns/issues/13336
I have:

dnsdist: Share tickets key between identical frontends created via YAML

---

pdns/dnsdistdist/meson/libssl-providers/meson.build
pdns/dnsdistdist/meson/quiche/meson.build
pdns/libssl.cc

@romeroalx spotted two issues when trying to run our regression tests with meson:
- we forgot to check for the availability of `quiche_conn_server_name` when we migrated from `autotools` to `meson`
- the OpenSSL version check done when providers are enabled did not use the correct syntax
Many thanks!
I have:

dnsdist: Fix two issues when building with `meson`

---

.github/actions/spell-check/expect.txt
pdns/dnsdistdist/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
regression-tests.dnsdist/test_IncomingInterface.py

This is useful in Virtual Routing and Forwarding (VRF) environments where the destination IP address might not be enough to identify the VRF.
I have:

dnsdist: Add Lua bindings for the incoming network interface

---

pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/dnsdist.hh
regression-tests.dnsdist/test_Caching.py

Fixes https://github.com/PowerDNS/pdns/issues/15337. We can do better with regard to using responses received over TCP for UDP queries, and perhaps the other way around, but this is the minimal fix to backport.
I have:

dnsdist: Fix cache lookup for unavailable TCP-only backends

---

regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/runtests

This makes picking the right modulerdir explicit instead of hard-coded. With meson the location varies, and also I would like to use packaged modules even when I happen to have backend .so's in the default place.
There's also an extra arg  (called extra) needed by the upcoming cookie code.
I have:

rec regr tests: allow to set moduledir using an env var

---

docs/manpages/pdnsutil.1.rst
pdns/pdnsutil.cc
regression-tests.nobackend/lmdb-id-generation/command
regression-tests.nobackend/lmdb-id-generation/expected_result

Some (well, one) `pdnsutil` commands have a "quiet" option. This adds a global "quiet" option which can be used to reduce the output from `pdnsutil`.
Use this option to silence the "new files may have been created, check permission and ownership" warning added recently, for the sake of some regression tests, where these messages come in the way of getting a clean output.
I have:

Add a quiet option to pdnsutil

---

pdns/packethandler.cc
pdns/packethandler.hh

This moderately evil PR reworks the logic within `doQuestion` to get rid of the `goto` statements within this large chunk of code. This is done in reasonably simple steps, and is probably better reviewed on a per-commit basis.
The steps are:
- after the common checks, make each question opcode handled by its own routine (Query/Notify/Update and NotImplemented for all the other opcodes).
- split the Query logic in two parts: an inner part which performs the logic before the `sendit` label, and an outer part which takes over from `sendit` onwards. The return value of the inner part tells the outer part whether the `sendit` logic must be applied (add additional records, etc) or if the response packet should be sent in its current state.
- split the inner part of the Query logic again in two …

[auth] Rework PacketHandler::doQuestion()

---

ext/lmdb-safe/lmdb-safe.hh
modules/lmdbbackend/lmdbbackend.cc

backport of #15176
draft. It works, but we have not yet decided to merge this into 4.9
I have:

auth-4.9: lmdb-safe: add prefix() cursor; use it in list/lookup/get

---

docs/backends/remote.rst
docs/http-api/swagger/authoritative-api-swagger.yaml
modules/gmysqlbackend/gmysqlbackend.cc
modules/godbcbackend/godbcbackend.cc
modules/gpgsqlbackend/gpgsqlbackend.cc
modules/gsqlite3backend/gsqlite3backend.cc
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
modules/remotebackend/remotebackend.cc
modules/remotebackend/remotebackend.hh
pdns/backends/gsql/gsqlbackend.cc
pdns/backends/gsql/gsqlbackend.hh
pdns/dnsbackend.cc
pdns/dnsbackend.hh
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

This is an attempt at fixing #11473. The first commit adds the necessary plumbing to be able to gather disabled records. The second commit allows the API to use this feature. 
I have:

API: allow fetching disabled RRsets

---

pdns/dnsbackend.hh
pdns/packethandler.cc

As was reported on the pdns-users lists some time ago, if you set up a multiple backend configuration where your DNS records are served by a non-DNSSEC capable backend and your DNS keys are served by e.g. a database backend, some requests will cause the server to commit suicide with no useful information in the logs.
This PR attemps to improve this situation a bit:
- the first commit replaces the `abort` call by the throwing of an exception, which will cause it to end up in the logs, and a proper ServFail response.
- the second commit attempts to recognize that situation, in which case it will log a low-priority message and keep processing the request - but there won't be any NSEC data in the response.
I am not sure the second commit is worth having - but I also am quite sure that …

Better behaviour with non-working DNSSEC configurations

---

pdns/dnspacket.cc

As found the hard way in #14513, incoming DNS packets which fail to parse correctly are silently ignored (regardless of the transport protocol being used).
This PR will log these errors at the `Debug` level, similarly to the other "ill-formed packet" errors (e.g. packet too short to be a DNS query).
I have:

[auth] Log DNS packet parse errors

---

docs/dnsupdate.rst

Structure-wise, the paragraph on the interaction between ``allow-dnsupdate-from``, ``ALLOW-DNSUPDATE-FROM`` and ``TSIG-ALLOW-DNSUPDATE`` wound up in the section of the document on Lua update policies.
That seems unintentional, and it's additionally confusing because the description of the Lua update policy setting explicitly mentions that it causes all other enforcement mechanisms to be disabled. This change attempts to correct that.
I have:

Rearrange confusingly ordered docs on DNS update checks

---

pdns/dnspacket.cc
pdns/dnspacket.hh

While working on other things I couldn't help but notice `DNSPacket::setRemote` is never invoked with two arguments, so there is no need to keep it and its default value. The few pieces of code which care about setting that `d_inner_remote` field do it directly.
I have:

Boring trivial dead code removal

---

tasks.py

We are experiencing a lot of build failures on GH actions when building with `meson` and `ASAN+UBSAN`, likely running out of memory. We could try to be smarter and only reduce the concurrency when building with `ASAN+UBSAN`, but for now let's see if it makes the failures go away.
I have:

dnsdist: Limit the number of concurrent build jobs to 4 on CI

---

.github/actions/spell-check/allow.txt
pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-rust-lib/rust/src/lib.rs
pdns/dnsdistdist/dnsdist-settings-definitions.yml
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/yaml-settings.rst
pdns/misc.cc
pdns/misc.hh

Some users would want to setup DSCP marking for DNS packets according to its network engineering needs. This PR is to provide such a configurable capability.
I have:

dnsdist: Support DSCP marking towards downstream server

---

pdns/dnsdistdist/dnsdist-cache.cc
pdns/dnsdistdist/dnsdist-idstate.hh
pdns/dnsdistdist/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
regression-tests.dnsdist/test_CacheHitResponses.py

When cache hit actions to be executed, it will be useful to know if this cache hit is a normal cache hit or stale cache hit, and different actions can be done based on that. This is to add an indicator available to cache hit response rule actions.
I have:

dnsdist: Add indicator for cache hit rules to know if hit a stale entry

---

regression-tests.dnsdist/test_TCPLimits.py

It is completely possible that the entire query will be sent before the dnsdist process notices that the number of IOs is larger than the limit, closes the connection, and the test process is notified of the socket being closed (for example because of buffering). So we need to detect that the connection is closed during our attempt to read the response, rather than while we are sending the query. This commit does that, and also introduces a slight delay after sending each byte of the query, increasing the likelihood of the dnsdist process actually reading bytes one by one.
I have:

dnsdist: Properly handle buffering in the "max read IOs" test

---

docs/backends/generic-mysql.rst

As discussed on pdns-users@ recently, the use of foreign key constraints with the mysql database prevents it from being usable with group replication, and the error messages are not really helpful, so put a warning in the documentation to save our future selves some time.
I have:

Document mysql foreign keys being incompatible with group replication

---

pdns/dnsdistdist/dnsdist-backend.cc
regression-tests.dnsdist/test_PoolManagement.py

Introduced in https://github.com/PowerDNS/pdns/pull/15418 so we will need to backport this one to 1.9.x.
I have:

dnsdist: Fix an iterator out-of-bound read when removing a TCP-only server

---

pdns/dnsdistdist/dnsdist-tcp.cc
regression-tests.dnsdist/test_TCPLimits.py

The "maximum duration" test used to trigger the maximum number of TCP read IOs, preventing the next test from being run. This PR first makes it possible to define an "unlimited" value for the maximum number of TCP read IOs then use it for this test.
I have:

dnsdist: Fix spurious failure of the TCP limits regression tests

---

pdns/recursordist/docs/lua-scripting/functions.rst
pdns/recursordist/lua-recursor4.cc

Add a Lua function to get the config directory and config name.
Handy for defining a more complex Lua configuration.
I have:

rec: add a Lua function to get the config dir and name

---

pdns/dnsdistdist/dnsdist-doh-common.hh

This commit fixes a double-free triggered by an exception being raised while we are processing a timeout for an incoming DoH query. The exception bypasses the call releasing the smart pointer, and thus the destructor is called when we reach the end of the function since we own the smart pointer, but unfortunately it has already been destroyed by the function that raised the exception. The fix is to release the pointer first, then call the function, so even if an exception is raised we no longer own the pointer, and it's clear that the function has taken ownership of it.
Fixes #15475.
I have:

dnsdist: Fix a crash when processing timeouts for incoming DoH queries

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc

The remote end might very well have already closed the HTTP stream corresponding to the timeout or response we are processing. While this means we need to discard the event we were processing, it is not an unexpected event and we should thus not raise an exception since the caller cannot do anything about it.
Most of the time raising an exception is harmless, but https://github.com/PowerDNS/pdns/pull/15480 illustrated very well that it might have unwanted side-effects, in addition to being wrong.
I have:

dnsdist: Gracefully handle timeout/response for a closed HTTP stream

---

builder-support/helpers/install_quiche.sh

This is needed as we rename the file. We try to not include the SONAME, but some systems include it anyway.
Fixes #15427
I have:

If SONAME is present in the generated quiche lib set it to the correct value

---

pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-carbon.cc
pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-discovery.cc
pdns/dnsdistdist/dnsdist-lua-bindings.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-web.cc
pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/upgrade_guide.rst
pdns/dnsdistdist/test-dnsdistbackend_cc.cc
regression-tests.dnsdist/test_HealthChecks.py

Calling `setAuto()` on a backend used to set the health-check mode to `active`, even if it had been set to `lazy` before, which was quite confusing.
This commit introduces a new method, `setAutoActive()` which can be used to change the health-check mode to `active`, and alters the behaviour of `setAuto()` to restore the previous health-check mode instead. This is a breaking change but since the default health-check mode is `active` I don't expect to break any existing configurations. It also introduces a new method, `getHealthCheckMode()`, to inspect the current mode.
Fixes https://github.com/PowerDNS/pdns/issues/13836
I have:

dnsdist: Be consistent with regard to health-check modes transition

---

pdns/dnsdistdist/dnsdist-frontend.cc
pdns/dnsdistdist/dnsdist-frontend.hh
pdns/dnsdistdist/dnsdist-lua-bindings-dnscrypt.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/dnscrypt.rst
regression-tests.dnsdist/test_DNSCrypt.py

We internally keep two different frontends (UDP and TCP) for DNSCrypt configuration binds, but the frontends should not be exposed to the user.
`getDNSCryptBind` should return distinct DNSCrypt contexts, one per DNSCrypt configuration bind. This was broken between 1.9.x and 2.0 during the refactoring of how frontends are internally kept.
I have:

dnsdist: Fix a confusion about contexts/frontends in `getDNSCryptBind`

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/docs/advanced/tls-certificates-management.rst
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/doq-common.cc
pdns/libssl.cc
pdns/libssl.hh
pdns/tcpiohandler.cc
regression-tests.dnsdist/.gitignore
regression-tests.dnsdist/Makefile
regression-tests.dnsdist/configServer2.conf
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_SNI.py

We already supported this with GnuTLS, but OpenSSL does not make it easy: we need to keep a different `SSL_CTX` object for each certificate/key and change the `SSL_CTX` associated with an incoming connection to the correct one based on the Server Name Indication from the servername callback (actually OpenSSL devs advise to use the ClientHello callback instead when using a recent enough version of OpenSSL, but the SNI hostname is not available is not available at this point so we would have to parse it ourselves, which is a terrible idea, and the drawbacks are not clear. `nginx` has been getting away with it, so hopefully we will as well).
One additional issue is that we still need to load certificates for the same name but different key types (RSA vs ECDSA, for example) in the same …

dnsdist: Add support for switching certificates based on SNI w/ OpenSSL

---

docs/requirements.txt

Updated list of packages in `docs/requirements.txt` by running `pip-compile --generate-hashes -U requirements.in` (Python 3.11)
Fixes errors in CI: <https://github.com/PowerDNS/pdns/actions/runs/14723465051>
Tests:
- [validate pip pinning](https://github.com/romeroalx/pdns/actions/runs/14727804491)
- [documentation](https://github.com/romeroalx/pdns/actions/runs/14727955885)
I have:

Docs: update Python3 dependencies to fix CI failure

---

pdns/dnsdistdist/doh3.cc
pdns/dnsdistdist/doq-common.cc
pdns/dnsdistdist/doq-common.hh
pdns/dnsdistdist/doq.cc
pdns/iputils.hh

Backport #15438 to rel/dnsdist-1.9.x
FreeBSD refuses the use of `IP_SENDSRCADDR` on a socket that is bound to a specific address, returning `EINVAL` in that case.
I have:

dnsdist-1.9.x: Backport 15438 - Only pass source addresses on sockets bound to ANY

---

pdns/dnsdistdist/dnsdist-backend.cc

Backport of #15046 to dnsdist-1.9.x.
Let the user know if we are using a specific interface or source address to contact the backend, as it is quite helpful to pinpoint the issue.
I have:

dnsdist-1.9.x: Backport 15046 - Better error when we cannot connect a backend socket

---

pdns/credentials.hh

Backport of #15063 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 15063 - Include cstdint to get uint64_t

---

pdns/dnsdist-web.cc
pdns/recursordist/docs/http-api/prometheus.rst
pdns/recursordist/ws-recursor.cc
pdns/ws-auth.cc

Backport of #15072 to dnsdist-1.9.x
Prometheus v3 will, by default, be more strict about the content-types returned from scrape endpoints. With the current value (just `text/plain`), it would fail to scrape.
In this commit the value is changed from `text/plain` to `text/plain; version=0.0.4`.
See also [1] and [2]
[1] https://prometheus.io/docs/instrumenting/exposition_formats/ [2] https://prometheus.io/docs/prometheus/3.0/migration/
I have:

dnsdist-1.9.x: Backport 15072 - Adjust Content-Type header for Prometheus endpoint to include version

---

pdns/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist-tcp-upstream.hh
regression-tests.dnsdist/test_ProxyProtocol.py

Backport of #15257 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 15257 - Limit # of proxy protocol-enabled outgoing TCP connections

---

.github/actions/spell-check/expect.txt
pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
regression-tests.dnsdist/test_IncomingInterface.py

Backport #15420 to dnsdist-1.9.x
The documentation will have to be updated in the master branch to indicate that the feature was backported to 1.9.10.
I have:

dnsdist-1.9.x: Backport 15420 - Add Lua bindings for the incoming network interface

---

pdns/dnsdist-lua.cc

It does not make sense, and in some cases might lead to a crash because the Xsk socket is actually an empty shared pointer in client mode.
Backport #15362 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 15362 - Do not register Xsk sockets on configuration check or client mode

---

pdns/dnsdistdist/dnsdist-lua-bindings.cc

The object holding the callback function, which is translated into a `LuaContext::LuaFunctionCaller`, needs to be destroyed while holding the Lua mutex because it will unregister itself from the Lua context, causing a corruption if a different thread is accessing the Lua context at the same time.
Hopefully closes https://github.com/PowerDNS/pdns/issues/15495
It's not clear to me yet if/why 1.9.x doesn't have the same issue so I'm putting the "backport to dnsdist-1.9.x" label until I can investigate.
I have:

dnsdist: Fix memory corruption when using `getAddressInfo`

---

pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-lua-bindings.cc
pdns/dnsdistdist/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/test_HealthChecks.py

When users configure multiple downstream servers, the servers could be in different states. Some of them is up and some of them maybe down. The user would like to use different healtch check parameters when server is in different state. For example, the user would like to use a shorter interval for servers that are in down state, so it can be changed back into up state faster once it recovered. This PR is to provide a API so that user can tune some of the health check parameters at runtime.
Not all related health check parameters are included yet in this API, more can be added later if usage arise.
I have:

dnsdist: Provide runtime update API for some health check params

---

pdns/noinitvector.hh

GCC 15.1 complains about a missing `cstdint` include when building `DNSdist`:
```
In file included from ../doh3.hh:29,
from ../doh3.cc:23:
../noinitvector.hh:67:35: error: ‘uint8_t’ was not declared in this scope
67 | using PacketBuffer = NoInitVector<uint8_t>;
|                                   ^~~~~~~
../noinitvector.hh:7:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
6 | #include <vector>
+++ |+#include <cstdint>
7 |
../noinitvector.hh:67:42: error: template argument 1 is invalid
67 | using PacketBuffer = NoInitVector<uint8_t>;
|                                          ^
In file included from ../dnsdist-idstate.hh:27,
from ../doh3.hh:48:
../dnscrypt.hh:247:20: error: ‘PacketBuffer’ has not been declared
247 |   void …
```

Fix building with GCC 15.1: missing `cstdint` include

---

pdns/dnsdistdist/meson/libedit/meson.build

Based on a patch by Robert Edmonds (thanks!).
Closes #15516 
I have:

dnsdist: Don't build with `libedit` if disabled via `meson`

---

pdns/dnssecinfra.cc
pdns/test-tsig.cc

Some TSIG clients may send mixed case key names. RFC 8945 4.3.3 requires that the digest is calculated over the lowercase version of that.
~~Needs a test.~~ now has a test
I have:

TSIG payload: use canonical (lowercase) name format

---

pdns/dnsdistdist/dnsdist-actions-definitions.yml
pdns/dnsdistdist/docs/reference/actions.rst
pdns/dnsdistdist/docs/reference/yaml-actions.rst
pdns/dnsdistdist/docs/upgrade_guide.rst

As noted in #14791, it is probably not working as expected and there is no practical use for it anyway.
Closes #14791 
I have:

dnsdist: Deprecate the `options` parameter of `HTTPStatusAction`

---

docs/manpages/pdns_server.1.rst

fix small typo in manpage
I have:

typo in pdns_server manpage

---

regression-tests.dnsdist/test_BackendDiscovery.py

This test has been randomly failing on GH actions lately, and it looks like it is because we sometimes do not get the IPv6 addresses when resolving `dns.quad9.net` via the system resolver.
I have:

dnsdist: Gracefully handle missing v6 in backend discovery test

---

pdns/dnsdistdist/dnsdist-concurrent-connections.cc

The bug was introduced in 99d1e8f044d43b9a75ffc70fed22ea674a9b7859. Thanks to Robert Edmonds for finding, reporting and proposing a patch fixing the issue!
Fixes https://github.com/PowerDNS/pdns/issues/15552
I have:

dnsdist: Fix a crash in the TCP concurrent connections map

---

builder-support/specs/dnsdist.spec
pdns/dnsdistdist/meson_options.txt

It used to be that way with `autotools` and I don't see any good reason to disable it by default.
Also explicitly enable eBPF support in our EL-based packages.
Successful packages test run: https://github.com/rgacogne/pdns/actions/runs/15040674021
I have:

dnsdist: Switch `eBPF` support to `auto` when building with `meson`

---

regression-tests.dnsdist/test_BackendDiscovery.py

Backport of #15541 to dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 15541 - Gracefully handle missing v6 in backend discovery test

---

pdns/noinitvector.hh

Backport of #15520 to dnsdist-1.9.x:
GCC 15.1 complains about a missing `cstdint` include when building `DNSdist`:
```
In file included from ../doh3.hh:29,
from ../doh3.cc:23:
../noinitvector.hh:67:35: error: ‘uint8_t’ was not declared in this scope
67 | using PacketBuffer = NoInitVector<uint8_t>;
|                                   ^~~~~~~
../noinitvector.hh:7:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
6 | #include <vector>
+++ |+#include <cstdint>
7 |
../noinitvector.hh:67:42: error: template argument 1 is invalid
67 | using PacketBuffer = NoInitVector<uint8_t>;
|                                          ^
In file included from ../dnsdist-idstate.hh:27,
from ../doh3.hh:48:
../dnscrypt.hh:247:20: error: ‘PacketBuffer’ has …
```

dnsdist-1.9.x: Backport 15520 - Fix building with GCC 15.1: missing `cstdint` include

---

regression-tests.dnsdist/test_BackendDiscovery.py

Apparently IPv6 is very flaky on GH actions these days, and I see this test failing again and again because DNSdist cannot reliably reach the servers over IPv6. IPv4 is fine from GH actions, v4 and v6 are fine locally, so let's not fail in that case.
I have:

dnsdist: Fix backend discovery regression test on GH action (again)

---

dockerdata/dnsdist-resolver.lua

The Lua code in `dnsdist-resolver.lua` periodically check whether the IP addresses associated with configured backend names have changed, and if they have it does potentially remove backends whose IP addresses are no longer present, and adds backends for new IP addresses. Each backend configured in DNSdist uses a fair amount of memory because of the states we pre-allocate for UDP queries, and unfortunately it looks like Lua holds to removed backends for quite a while by default, causing the removed backends to actually co-exist in memory with the new ones for a long time, leading to a higher than necessary memory consumption. This is particularly problematic when you realize that the memory allocator usually hold onto memory even when the program releases it. So in environments where IP …

dnsdist: Reduce memory usage with fast-changing dynamic backends

---

.github/workflows/build-and-test-all.yml

GH actions provides us with a 16 GB runner on public repositories, but only 7 GB on private ones. Unfortunately our current workflow assumes that we can get away with 4 concurrent jobs when building DNSdist, which is true when we have 16 GB available but not with 7 GB.
So this commit switches to Ubicloud runners (standard 4, 4 vCPU, 16 GB) for repositories defining the `REPOSITORY_USE_UBICLOUD` variable to 1. These runners are also significantly faster than the GH actions ones.
I have:

build-and-test-all: Build DNSdist on Ubicloud runners when needed

---

pdns/dnsdistdist/dnsdist-rust-lib/Makefile.am
pdns/dnsdistdist/dnsdist-rust-lib/dnsdist-settings-generator.py
pdns/dnsdistdist/dnsdist-rust-lib/meson.build

Before this commit calling `meson compile` a second time right after building triggered a re-generation of the `dnsdist-configuration-yaml-items-generated.cc` file because `meson` wants it to be present in the build directory, but we also want to generate it in the source directory so that it can be included in the repository.
The current solution is a bit dirty, but our options are limited because some files are only generated when YAML support is available, because they require Rust, and we need them to be in the dist tarball. Otto suggested that we could generate them only when building the dist tarball, I'll look into it in a bit, but since 2.0.0-alpha2 is on its way I think it makes sense to commit this solution first.
I have:

dnsdist: Fix our `meson` build not reaching a stable state

---

pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-metrics.cc
pdns/dnsdistdist/dnsdist-metrics.hh

This commit improves the scalability of custom metrics by:
- being optimistic about the existence of a given metric (including labels): since most of the time a given metric, even with labels, will be increased more than once, we can take read-only lock and only fallback to taking a write lock if we actually have to add a new entry. This is especially useful when using custom metrics with per-thread Lua, since there is no global lock involved in this case.
- optimizing the "no label" case, since the Lua FFI interface does not use anyway: skip the creation (and destruction) of an empty labels map whenever possible, return an empty string early when combining empty labels.
It already yields a noticeable improvement when a single thread is used, but really shines when several threads are …

dnsdist: Improve scalability of custom metrics

---

pdns/dnsdistdist/dnsdist-rust-lib/dnsdist-settings-generator.py
pdns/dnsdistdist/dnsdist-settings-definitions.yml
pdns/dnsdistdist/docs/quickstart.rst

I am seeing: ```FileExistsError: [Errno 17] File exists: '/Users/otto/pdns/pdns/dnsdistdist/dnsdist-rust-lib/dnsdist-configuration-yaml-items-generated.cc' -> './dnsdist-rust-lib//dnsdist-configuration-yaml-items-generated.cc'```
after a change in `dnsdist-settings-definitions.yml`.
Plus three typos in docs.
I also noticed stable state is not reach until a second run of meson compile after changing `dnsdist-settings-definitions.yml`. Did not investigate that one.
```
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /opt/homebrew/bin/ninja -C /Users/otto/pdns/pdns/dnsdistdist/build -v
ninja: Entering directory `/Users/otto/pdns/pdns/dnsdistdist/build'
[1/8] /bin/sh -c 'test ! -e ../config.h'
[2/8] /opt/homebrew/bin/python3 …
```

dnsdist: don't try creating symlink if it already exists

---

pdns/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist-tcp-upstream.hh
pdns/dnsdistdist/test-dnsdisttcp_cc.cc

Backport #15571 to rel/dnsdist-1.9.x:
It happens when we keep finding queries waiting for us on the incoming TCP socket from the client, and responses waiting for us on the TCP socket to the backend after forwarding a new query. This is quite unlikely but not impossible to happen, as reported by Renaud Allard (many thanks for taking the time to investigate the issue!).
I have:

dnsdist-1.9.x: Backport 15571 - Fix a crash when TCP queries and responses keep coming

---

pdns/dnsdistdist/dnsdist-tcp-upstream.hh
pdns/dnsdistdist/dnsdist-tcp.cc
pdns/dnsdistdist/test-dnsdisttcp_cc.cc

It happens when we keep finding queries waiting for us on the incoming TCP socket from the client, and responses waiting for us on the TCP socket to the backend after forwarding a new query. This is quite unlikely but not impossible to happen, as reported by Renaud Allard (many thanks for taking the time to investigate the issue!).
I have:

dnsdist: Fix a crash when TCP queries and responses keep coming

---

builder-support/dockerfiles/Dockerfile.rpmbuild

Otherwise `pip` is not found when installing `meson`.
I have:

dnsdist: Fix building on EL-8 (we now need Python 3.12 instead of 3.11)

---

pdns/dnsdistdist/dnsdist-lua-rules.cc
pdns/dnsdistdist/dnsdist-lua-selectors-generated.cc
pdns/dnsdistdist/dnsdist-rules-factory.hh
pdns/dnsdistdist/dnsdist-rules-generator.py
pdns/dnsdistdist/dnsdist-rust-bridge-selectors-generated.cc
pdns/dnsdistdist/dnsdist-rust-lib/rust/src/lib.rs
pdns/dnsdistdist/dnsdist-selectors-definitions.yml
pdns/dnsdistdist/dnsdist-selectors-factory-generated.cc
pdns/dnsdistdist/dnsdist-selectors-factory-generated.hh
regression-tests.dnsdist/test_Tags.py

Before 2.0.0 passing an empty value to `TagRule` meant that only the presence of the tag with an empty value would be accepted. That behaviour changed when we introduced the YAML configuration format, refactoring the selectors in the process, to instead mean that an empty string meant that all values would be accepted, only the tag presence being checked. This is an unfortunate side-effect of a limitation of the `cxx` Rust <-> C++ interoperability layer that we are using (lack of support for `Option<T>` <-> `std::optional<T>`, namely). This PR fixes restores the existing behaviour by adding an additional boolean to the YAML configuration, and ensuring that passing an empty value to the Lua configuration is not treated as not passing any value.
I have:

dnsdist: Fix the behaviour of `TagRule` with an empty string as value

---

builder-support/helpers/install_quiche.sh

BSD sed does not like -i without arg
I have:

install quiche helper: do not use -i without arg and add missing / on Darwin

---

modules/geoipbackend/geoipbackend.cc

g++ 15.1.1 reports:
```
geoipbackend.cc: In constructor 'GeoIPBackend::GeoIPBackend(const std::string&)':
geoipbackend.cc:88:62: warning: ignoring attributes on template argument 'int (*)(DIR*)' [-Wignored-attributes]
88 |     auto dirHandle = std::unique_ptr<DIR, decltype(&closedir)>(opendir(getArg("dnssec-keydir").c_str()), closedir);
```
I have:

auth: Fix `ignoring attributes on template argument` warning in the GeoIP backend

---

pdns/dnsdistdist/dnsdist-rust-lib/rust/Makefile.am
pdns/dnsdistdist/dnsdist-rust-lib/rust/build_dnsdist_rust_library

The documentation states that only `cargo update` and `cargo install` should update the dependencies present in the `Cargo.lock` file, but it still seems safer to explictly ask `cargo build` to not update them.
I have:

dnsdist: Explicitly use the versions present in `Cargo.lock` when building

---

.github/workflows/build-and-test-all.yml

Backport of #14565 to `dnsdist-1.9.x`.
Avoid CI failures related to Coveralls when upload fails due to any errors.
I have:

dnsdist-1.9.x: backport 14565 - gh actions - coveralls: avoid CI failure by setting fail-on-error: false

---

.github/workflows/build-and-test-all.yml

Backport of #14565 to `rec-5.0.x`.
Avoid CI failures related to Coveralls when upload fails due to any errors.
I have:

rec-5.0.x: backport 14565 - gh actions - coveralls: avoid CI failure by setting fail-on-error: false

---

pdns/pdnsutil.cc
pdns/utility.hh

`pdnsutil edit-zone` will invoke an external editor, using `system(3)`. This replaces the logic with an `execvp(2)`-based one.
I have:

Do not use system(3) in pdnsutil

---

pdns/pdnsutil.cc

A part of @Habbie's evil plans is to make `pdnsutil` have a dashless syntax, writing `pdnsutil object action arguments`, where "object" is a noun and "action" is a verb.
This change attempts to recognize "object-action" and "object action" and rewrites them as "action-object" which is the current naming scheme for `pdnsutil` commands.
(this is just testing the waters here, and also confirming that I got @Habbie's intentions right)
I have:

Try harder matching command names in pdnsutil

---

pdns/pdnsutil.cc
pdns/zoneparser-tng.cc
pdns/zoneparser-tng.hh

This trivial mechanical PR lets `pdnsutil load-zone` default to the `default-ttl` setting as the TTL value for entries lacking a TTL, if `$TTL` is not set in the file being loaded.
This addresses #8494.
I have:

[tools] Honour default-ttl in pdnsutil load-zone

---

pdns/dnsdistdist/dnsdist-actions-factory.cc
pdns/dnsdistdist/dnsdist-console.cc
pdns/dnsdistdist/dnsdist-ecs.cc
pdns/dnsdistdist/dnsdist-ecs.hh
pdns/dnsdistdist/dnsdist-lua-response-actions-generated.cc
pdns/dnsdistdist/dnsdist-response-actions-definitions.yml
pdns/dnsdistdist/dnsdist-response-actions-factory-generated.cc
pdns/dnsdistdist/dnsdist-response-actions-factory-generated.hh
pdns/dnsdistdist/dnsdist-rust-bridge-actions-generated.cc
pdns/dnsdistdist/dnsdist-rust-bridge-actions-generated.hh
pdns/dnsdistdist/dnsdist-rust-lib/rust/src/lib.rs
pdns/dnsdistdist/docs/reference/actions.rst
regression-tests.dnsdist/test_Responses.py

This Pull Request adds the new SetEDNSOptionResponseAction to dnsdist, allowing arbitrary EDNS options and data to be added to DNS responses. It also includes documentation and a regression test for this new action.
I have:

dnsdist: add SetEDNSOptionResponseAction

---

builder-support/debian/recursor/debian-buster/rules
builder-support/debian/recursor/debian-trixie/rules
builder-support/specs/pdns-recursor.spec

So dev builds use auto, and package builds use the infra supplied flag. This should avoid the redefinition warning in all cases.
I have:

rec: Disable fortify on package builds, it is supplied db package build infra

---

.github/workflows/builder.yml
builder-support/dockerfiles/Dockerfile.target.centos-10-stream
builder-support/specs/dnsdist.spec

Update: now that all deps are available, this PR has become nice and small and simple. `--version` output from the three products is identical to the EL9 build. Rémi noticed eBPF missing in dnsdist, but that's true for EL9 too and he'll fix that separately.
I will test this on aarch64 before removing the Draft status.
~~~
this is hacked up instead of done nicely.
Once EPEL10 becomes available, we can re-enable sodium, re2, etc. and do this nicely, and then start building it periodically to prepare us for RHEL10 (next year I think)
only tested for dnsdist
~~~
I have:

builder: add centos-10-stream target

---

.github/actions/spell-check/allow.txt
.github/scripts/normalize_paths_in_coverage.py
.github/workflows/build-and-test-all.yml
meson/code-coverage/meson.build
meson_options.txt
pdns/dnsdistdist/meson_options.txt
pdns/recursordist/meson_options.txt
regression-tests.nobackend/README
regression-tests.nobackend/soa-edit/command
tasks.py

Use meson builds for regression tests.
It is important to note that instead of installing a product, the output binaries are used in later stages for running the tests. Also, the binaries for auth have different names: i.e. `pdns-auth` instead of `pdns_server` or `pdns-auth-util` instead of `pdnsutil`.
This PR also:
- Enables the `yaml` build option for dnsdist full.
- Uses `datefudge` instead of `faketime`. The original returned the following error:  `libfaketime: Unexpected recursive calls to clock_gettime() without proper initialization. Trying alternative.` which makes the test to hang. There is a known bug for the library related to statically linked programs (see [bugs](https://manpages.ubuntu.com/manpages/trusty/man1/faketime.1.html)) although the reason could be a different one
I …

GH Actions - build-and-test-all: use meson builds for regression tests

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua-actions.cc
pdns/dnsdistdist/docs/reference/actions.rst
regression-tests.dnsdist/test_Responses.py

This Pull Request adds the new SetEDNSOptionResponseAction to dnsdist, allowing arbitrary EDNS options and data to be added to DNS responses. It also includes documentation and a regression test for this new action.
It is a back port of #15610 for 1.9.x
I have:

dnsdist-1.9.x: backport 15610 - add SetEDNSOptionResponseAction

---

pdns/dnsdistdist/dnsdist-cache.cc
pdns/dnsdistdist/dnsdist-cache.hh
pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
pdns/dnsdistdist/dnsdist-rust-lib/dnsdist-settings-generator.py
pdns/dnsdistdist/dnsdist-settings-definitions.yml
pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/yaml-settings.rst
pdns/packetcache.hh
regression-tests.dnsdist/test_Caching.py

Use case arise that two clients with different udp payload size, a customized client uses 4096 while glibc resolver uses 1232. User would like to share cache result for the same query name, type and class in this case. The downstream servers does not use ECS and would not return different answers upon other EDNS options so this is to add an option to support such use case.
I have:

dnsdist: add option to support cache sharing between different payload sizes

---

pdns/dnsdistdist/dnsdist-svc.cc
pdns/dnsparser.hh
pdns/dnsrecords.cc
pdns/dnswriter.cc
pdns/dnswriter.hh
pdns/rcpgenerator.cc
pdns/rcpgenerator.hh

While looking at other things, I couldn't help but notice that the last argument of the `xfrName` (de)serialization functions is never used in the current state of the code.
This simple PR removes it and should not cause any difference in behaviour.
I have:

Remove never used argument

---

pdns/pdnsutil.cc

One recurring mistake I do while typing at the keyboard is to hit the "," key instead of the "." key - they are next to each other, after all. With a small enough font size I do not always notice, and it looks like I was not alone, as fellow developers let me merge a PR with commas instead of dots at the end of sentences.
This PR fixes it, and it is probably shorter than this "short" description.
I have:

End sentences with dots, not commas.

---

docs/manpages/pdnsutil.1.rst

Clarify where default TTL on `add-record` comes from
I have:

pdnsutil: clarify provenance of default TTL

---

modules/bindbackend/bindbackend2.cc
modules/ldapbackend/native.cc
modules/lua2backend/lua2api2.hh
modules/tinydnsbackend/tinydnsbackend.cc
modules/tinydnsbackend/tinydnsbackend.hh

This makes sure than, for backends which may not be able to provide a sensical value for the "domain id" field of `DomainInfo`, we use `UnknownDomainID`.
The 2nd commit will also make the TinyDNS backend return the domain id it was initially queried for, in its `DNSResourceRecord` results, for consistency (note that that value may be `UnknownDomainID`).
I have:

More domain ID love

---

pdns/dnssecsigner.cc

As observed in #12899, using a large DNSSEC signature cache has the drawback of cache maintainance being sometimes costly, since it is performed while holding an exclusive lock on the cache.
While a proper fix to that issue is to improve the maintainance logic, a cheap fruit consists of performing the actual entries cleanup (which will invoke a lot of destructors and memory management functions) outside of the lock, after exchanging the cache contents with shiny new empty contents.
(Also I do not dare removing the "blunt but effective" comment yet)
I have:

Low-hanging signature cache hanging fruit

---

pdns/auth-main.cc

The loglevel was accidentally bumped to Info in an earlier PR (but after 4.9)
I have:

auth: restore correct logging level for startup version message

---

pdns/dnsdistdist/dnsdist-self-answers.cc
pdns/dnsdistdist/dnsdist.cc
pdns/dnsdistdist/dnsdist.hh
regression-tests.dnsdist/test_Spoofing.py

While it makes sense to add/remove EDNS when the answer was generated from the query itself, we should not be doing that when it has been generated from a whole DNS packet, as it probably contains exactly what the user intended it to.
I have:

dnsdist: Do not replace EDNS in answers self-generated from a packet

---

docs/upgrading.rst
pdns/sillyrecords.cc
pdns/test-dnsrecords_cc.cc

Fixes the cases mentioned in #10558, though there are still cases where there's no well defined canonical form, and the REST code just enforces it's own idea of what's THE canonical form.
Beware: this changes behaviour. Code submitting data to the REST interface might be surprised that previously accepted strings are no longer accepted (and vice versa).
I have:

Compute LOC text representation without using floating point for latitude and longitude

---

pdns/dnsparser.cc
pdns/dnsparser.hh
pdns/rcpgenerator.cc
pdns/recursordist/syncres.cc

Should fix both issues reported in #15660
I chose to get rid of the extra copy of txtEscape and expose it. Better have one version than two, even if it might be broken?
I have:

rec: fix negativetrustanchor.server CH TXT query processing (disabled by default)

---

regression-tests/start-test-stop

In #2979, the complete list of keys was displayed at the end of tests, but this can be considered a leftover debug bit. However it makes the "N out N tests (100%) tests passed" line less visible when running tests. So let's remove it before this change turns 10 and starts throwing teenager tantrums.
I have:

Stop listing the trusted keys at the end of tests

---

docs/appendices/backend-writers-guide.rst
docs/lua-records/functions.rst

This documents that symbolic constants for GeoIPQueryAttribute are not available to Lua records in versions predating 5.0.0.
I have:

Lua GeoIPQueryAttribute documentation update

---

pdns/dnsdistdist/dnsdist-idstate.hh
pdns/dnsdistdist/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
regression-tests.dnsdist/test_RestartQuery.py

Sometimes it is useful to keep tracking the total number of query restarts. This is to add a restartCount field to the query which gets incremented everytime it is restarted. The enhancement also provides an interface for lua action to retrieve this count for any further needed checks.
I have:

dnsdist: add a count to track the number of query restarts

---

meson/libcrypto/meson.build
meson/libssl/meson.build

This fixes a case where we also had double -lcrypto on the command line: one from dep_libssl, and one from dep_libcrypto.
Also avoid a bunch of warning: as compile commands don't take -L:
c++: warning: argument unused during compilation: '-L/usr/local/eboringssl/lib' [-Wunused-command-line -argument]
I have:
- [X read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document

meson: Pick -lcrypto up from the spot defined by dep_libcrypto

---

pdns/dnsdistdist/dnsdist-settings-documentation-generator.py
pdns/dnsdistdist/docs/reference/yaml-settings.rst

Browsing through the dnsdist docs, I noticed that there an empty code block in the new YAML config page for dnsdist.
I have:

doc(dnsdist): remove superfluous code block in YAML config

---

ext/lmdb-safe/lmdb-safe.hh

Using bswap64 causes infinite reursion if your system has a #define bswap64 __builtin_bswap64
I have:

auth: rename bswap64 to pdns_bswap64.

---

pdns/recursordist/test-rec-zonetocache.cc

Since 753ad2390bfbc90f6bc1b68f980ef4bcdc2cfddc ZoneToCache checks whether a given zone has a recursive forward rule, so we need the Domain map to be properly initialized in all tests, as they can be executed in random order.
Fixes:
```
ThreadSanitizer:DEADLYSIGNAL
==35969==ERROR: ThreadSanitizer: SEGV on unknown address 0x000000000018 (pc 0x5568e9f8bb04 bp 0x4c00000000000 sp 0x7ffcc13b77f0 T35969)
==35969==The signal is caused by a READ memory access.
==35969==Hint: address points to the zero page.
#0 std::_Hashtable<DNSName, std::pair<DNSName const, SyncRes::AuthDomain>, std::allocator<std::pair<DNSName const, SyncRes::AuthDomain> >, std::__detail::_Select1st, std::equal_to<DNSName>, std::hash<DNSName>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, …
```

rec: Prevent a crash in the ZoneToCache unit tests

---

.github/actions/spell-check/expect.txt
pdns/dnsdistdist/docs/install.rst
pdns/dnsdistdist/docs/upgrade_guide.rst

Hopefully fixes https://github.com/PowerDNS/pdns/issues/15710 :)
I have:

dnsdist: Python with YAML is no longer optional to build dnsdist

---

ext/lmdb-safe/lmdb-safe.hh
ext/lmdb-safe/lmdb-typed.hh
modules/lmdbbackend/lmdbbackend.cc

The focus of this PR is to simplify the logic of LMDB deletions when running in `flag-deleted` mode. In this mode, deletions are not performed, specific deletion markers are put as the data instead.
Therefore:
- it is not necessary to delete existing data before writing the marker, the marker will replace the existing data (if any) anyway.
- similarly, it is not necessary to check for data existence before writing the marker.
I have:

better rm in LMDB #2

---

ext/lmdb-safe/lmdb-safe.cc
ext/lmdb-safe/lmdb-safe.hh
ext/lmdb-safe/lmdb-typed.hh
modules/lmdbbackend/lmdbbackend.cc

This PR makes sure that exceptions raised because of LMDB errors carry the LMDB error information, rather than have us use our crystal balls to figure out that.
The support contract prices for crystal balls are becoming closer and closer to unaffordable nowadays, so we have to take action to reduce the wear on ours.
I have:

Better LMDB error information

---

pdns/recursordist/meson.build

As mentioned on irc, when `pubsuffix.cc` does not exist, it needs to be built from `effective_tld_names.dat`, which must be downloaded if it does not exist either.
When building with autoconf, these two steps are well-split. But when building with meson, the absence of the first file causes the complete "download, then generate" action, even if the file to download is already there.
This PR ought to fix this.
I have:

rec: avoid curl during build if unnecessary

---

configure.ac
m4/pdns_with_lua.m4
pdns/dnsdistdist/configure.ac
pdns/recursordist/configure.ac

Lua is mandatory for all three projects (auth, recursor, dnsdist), so the `autoconf` logic can be simplified a bit.
Better reviewed with whitespace changes ignored due to indent decrease in `pdns_with_lua.m4`.
I have:

Lua for all

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

As mentioned in #11733, operations on zone keys on primary zone should cause a zone serial number increase if the zone has been configured to do so (`SOA-EDIT-API` metadata).
While working on this, I noticed that the feature adding the previous and new serial numbers in HTTP response headers had been broken, and was returning the new value in both headers, because the "old" header was set up from an already updated value. Oops. (I have added a test for this)
I have:

Increase zone serial number after zone key operations

---

pdns/dnsdistdist/dnsdist-lua-bindings.cc
pdns/dnsdistdist/docs/reference/config.rst

This exposes the total number of queries a downstream server has handled similarly to how the :getDrops() method are available within Lua
When doing custom logic within Lua it's sometimes useful to be able to know how many queries a given server has handled, so this simply exposes that metric within the Server class directly.
I have:

Add :getQueries() method to Server class

---

ext/lmdb-safe/lmdb-safe.cc

I believe there is a small race in the `getMDBEnv`: if the database file does not exist when we first try to get the file metadata, we acquire the lock then create a new `MDBEnv` and store it in the map. But what happens if a different thread created the database between our first check and the call to `MDBEnv`? I believe we would create a new environment and override the existing entry in the map, bypassing the check.
This commit introduces a second check right after acquiring the lock to prevent that.
I have:

lmdb-safe: Fix a small race in `getMDBEnv`

---

dockerdata/dnsdist-resolver.lua

The `dnsdist-resolver` script regularly checks the IPs corresponding to a backend `hostname`, and updates our backend accordingly:
- if an IP we previously received vanishes, it removes the backend corresponding to that IP
- if a new IP shows up, it adds a new backend
The existing code tries to avoid some work by keeping track of the number of IPs associated to a given server, skipping the comparisons of recently received IPs to existing ones if the number did not change. This unfortunately does not work well if we get the same number of IPs but with different IPs in the set.
This caused some backends to never get removed and stay along as ghosts, as well as some new IPs to never be picked up.
This came up while investigating https://github.com/PowerDNS/pdns/issues/15446 but I'm not sure …

dnsdist-resolver: Fix a bug when we get new IPs for a server

---

pdns/recursordist/rec-rust-lib/docs-new-preamble-in.rst

zonetocaches was under recursor section instead of recordcache
I have:

rec: Correct zonetocaches settings example

---

.github/actions/spell-check/expect.txt
pdns/dnsdistdist/docs/install.rst

While the installation docs covers building dnsdist with autotools and GNU make, there is none for meson and ninja. Describe how to do the latter.
I have:

dnsdist: Mention compiling with meson

---

pdns/dnsdistdist/dnsdist-lua-bindings-dnscrypt.cc
pdns/dnsdistdist/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/dnsdist-lua.cc
regression-tests.dnsdist/test_Lua.py

Until now we were returning an empty shared pointer, but unfortunately LuaWrapper is currently not smart enough to turn that into a `nil` value.
This is a better fix than https://github.com/PowerDNS/pdns/pull/15707 for https://github.com/PowerDNS/pdns/issues/15699 although I would still like https://github.com/PowerDNS/pdns/pull/15707 to get merged for defense in depth.
I have:

dnsdist: Return `nil` for non-existing Lua objects

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-settings-definitions.yml

Backport of #15729 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 15729 - Enforce that additional addresses are DoT/DoH only

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-lua.cc
regression-tests.dnsdist/test_HealthChecks.py

We can only validate if a proper subject name or subject address is passed, and we do not want to silently disable validation, so let's refuse to start.
I have:

dnsdist: Error if backend certificate validation is enabled without a subject name

---

pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-rust-lib/table.py
pdns/recursordist/rec-tcp.cc

The failure *is* reported if the `incoming.listen` setting is !default.
I have:

rec: start to listen on ::1 by default, but don't consider it an error if that fails

---

modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh

Monday's code factorization in lmdb has been a tad too optimistic, and coverity rightly pointed out that I introduced a risk of `nullptr` dereference.
This trivial PR fixes this. See commit message for details.
I have:

fix coverity-reported stupid lmdb bug

---

Dockerfile-auth

auth-4.9.x: backport crash on --version caused by doubly loaded modules

---

pdns/dnsdistdist/dnsdist-kvs.cc
pdns/dnsdistdist/dnsdist-kvs.hh

Backport of 15738 to rel/dnsdist-2.0.x
As noted by Peter: "LMBD requires that database is opened exactly once per process. Opening multiple times breaks file locks silently, which leads to corrupting the database."
While I don't expect users to actually do that, we already have a nice helper function to prevent this mistake in the lmdb-safe code base, so let's use it.
I have:

dnsdist-2.0.x: Backport 15738 - Prevent users from opening the same LMDB twice

---

docs/appendices/backend-writers-guide.rst
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
pdns/backends/gsql/gsqlbackend.cc
pdns/backends/gsql/gsqlbackend.hh
pdns/dbdnsseckeeper.cc
pdns/dnsbackend.hh
pdns/pdnsutil.cc
pdns/rfc2136handler.cc

This (hopefully) completes the recent NSEC3 record handling work in LMDB, to guarantee that we never leave dangling records when performing deletions or updates:
- when updating an NSEC3 record, remove the previous back record (since it would become dangling).
- when removing an NSEC3 record, always remove the other record from the pair.
Note the second item from the list above manifests itself in multiple ways in `replaceRRSet`:
- When removing all records regardless of their type (using `QType::ANY`), we need to check for an NSEC3 record and, if found, remove the matching record of the chain.
- When removing a particular record type, and not adding any record after that, we need to check whether we end up with a single NSEC3 record to that name, in which case it should be removed (with …

lmdb NSEC3 record handling hygiene

---

modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh

One of the commits in #15767 turned to be too aggressively deleting data when it should not have. This PR reverts the incorrect logic.
I have:

lmdb NSEC3 record handling hygiene bugfix

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-configuration-yaml.hh
pdns/dnsdistdist/dnsdist-console-completion.cc
pdns/dnsdistdist/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-settings-documentation-generator.py
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/test_Console.py

Backport of #15747 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 15747 - Add a Lua binding to get objects declared in YAML

---

.github/workflows/build-packages-daily-master.yml
.github/workflows/build-packages.yml
.github/workflows/builder-dispatch.yml
.github/workflows/builder.yml
BUILDING-PACKAGES.md
builder-support/dockerfiles/Dockerfile.target.el-10
builder-support/helpers/install_meson.sh
builder-support/helpers/install_quiche.sh
builder-support/helpers/install_rust.sh

plus fix invoking `build.sh` without `-m`
draft PR until the centos-10-stream merge shows green in daily CI.
I have:

builder: add el-10 target, based on rockylinux:10 for now

---

modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
pdns/dbdnsseckeeper.cc
pdns/pdnsutil.cc
pdns/rfc2136handler.cc

I am still digging into that LMDB+NSEC3 rabbit hole. Every DNS Resource Record serialized in the database has a flag supposed to tell us whether there are NSEC3 records for it. Except the value of the flag were not always correct.
This PR makes sure that this flag is set when such records exist or are about to be added. And cleared when they are removed but that particular record is not deleted afterwards. This also makes sure that NSEC3 in narrow mode will create spurious NSEC3 records.
Probably better reviewed on a commit-by-commit basis. The 3rd one ~will amaze you~ is a bit tricky, but correct (write down a truth table of the `if()` condition and body, for the two `qtype == ANY` and `qtype != ANY` conditions, and you'll see the new version yields the same results as before).
I guess …

lmdb NSEC3 record handling hygiene: return of the wrath of the seventh son of the phantom of the beast

---

pdns/dnsdistdist/configure.ac

Depending on the system we might actually need to link with `libdl` when our Rust library is used, and the mechanism to do that was not properly set up when building with `autotools` (we were adding `LIBDL` to the the libraries we need but the variable was not properly filled). Unfortunately the systems we are exercising in our CI do not need to explicitly link with `libdl` so we did not notice.
Reported by @paddg in https://github.com/PowerDNS/pdns/discussions/15804#discussioncomment-13707873
I have:

dnsdist: Properly link with `libdl` when building with `autotools`

---

regression-tests.nobackend/edns1/test-edns.py
regression-tests.nobackend/negcache-tests-dotted-cname/pipe.py
regression-tests.nobackend/soa-edit/command

This makes the datefudge call work on systems with common non-C locales.
After opening this PR, I found two more tests that did not run on my system. The second commit fixes those by explicitly calling `python3`.
I have:

datefudge: more portable date parsing; py3 fixes

---

docs/backends/lmdb.rst
docs/upgrading.rst
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
regression-tests.api/test_Zones.py

As proposed in #14079, this adds (quite crudely) search support to the LMDB backend.
Note that only records may be searched, as the LMDB does not currently support comments.
I have:

Add record search capability to the LMDB backend

---

meson.build
pdns/Makefile.am
pdns/dns.cc
pdns/dns.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-actions-definitions.yml
pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-rules-generator.py
pdns/dnsdistdist/dnsdist-rust-lib/dnsdist-settings-generator.py
pdns/dnsdistdist/dnsdist-selectors-definitions.yml
pdns/dnsdistdist/dnsdist-settings-definitions.yml
pdns/dnsdistdist/dnsdist-settings-documentation-generator.py
pdns/dnsdistdist/docs/upgrade_guide.rst
pdns/dnsdistdist/meson.build
pdns/dnsdistdist/test-dns_cc.cc
pdns/test-dns_cc.cc
regression-tests.dnsdist/test_DOH.py
regression-tests.dnsdist/test_DOH3.py
regression-tests.dnsdist/test_DOQ.py
regression-tests.dnsdist/test_DynBlocksServFail.py
regression-tests.dnsdist/test_Yaml.py

Backport of #15819 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 15819 - Handle named rcodes in the YAML configuration

---

.github/actions/spell-check/expect.txt
docs/dnssec/operational.rst
docs/domainmetadata.rst
docs/settings.rst
pdns/dbdnsseckeeper.cc
pdns/dnsseckeeper.hh
pdns/packethandler.cc
pdns/packethandler.hh
pdns/pdnsutil.cc
pdns/ws-auth.cc
regression-tests.auth-py/test_AuthSignal.py

Implements [RFC9615](https://datatracker.ietf.org/doc/rfc9615/). We'd like to replace our LUA-based implementation at desec.io with this for about 50k zones.
Implementation:
- Introduce `SIGNALING-ZONE` metadata. Zones with this setting will synthesize bootstrapping records.
- Signaling zone needs to use narrow-mode online signing (because neighboring owner names are not known at signing time).
- Usage:
```sh
export nshost=ns1.example.net
pdnsutil create-zone _signal.$nshost $nshost  # create NS record too
pdnsutil secure-zone _signal.$nshost
pdnsutil set-nsec3 _signal.$nshost "1 0 0 -" narrow
pdnsutil rectify-zone _signal.$nshost
pdnsutil set-meta _signal.$nshost SIGNALING-ZONE 1
```
Questions / tasks:
I have:

Auth feature: RFC9615 (authenticated DNSSEC bootstrapping)

---

docs/manpages/zone2sql.1.rst
pdns/zone2sql.cc

adds functionality to zone2sql import script to have a delete statement. useful for testing / retesting zone imports
I have:

delete existing matching zones during (re)import

---

pdns/dnsdistdist/dnsdist-configuration-yaml.cc
pdns/dnsdistdist/dnsdist-rust-bridge.hh
pdns/dnsdistdist/dnsdist-rust-lib/rust-middle-in.rs
pdns/dnsdistdist/dnsdist-rust-lib/rust-post-in.rs
pdns/dnsdistdist/dnsdist-settings-definitions.yml
regression-tests.dnsdist/test_Yaml.py

Until now it was possible to reference NMG objects in the YAML configuration but not to create one, which is a bit silly.
I have:

dnsdist: Allow registering NMG objects from YAML

---

.github/workflows/build-tags.yml

build-tags uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master As of f107ec62467b8779db9bbdb175721ef232ed52e5, that workflow requires:
permissions:
actions: read   # To read the workflow path.
id-token: write # To sign the provenance.
contents: write # To be able to upload assets as release artifacts
Per https://docs.github.com/en/actions/using-workflows/reusing-workflows in order for this to work, the calling job (in build-tags) needs to have the maximum required permissions in order for the calling workflow to be run.
(cherry picked from commit 8c4888c19d4997d7e443c6ad4953e716ee5429b0)
I have:

rec-5.0.x: Allow build-tags to run on forks

---

pdns/dnsdistdist/dnsdist.cc

We don't actually need a `DNSResponse` object in this case, and even though passing a `DNSResponse` object seems more intuitive constructing then immediately destructing it is not exactly free.
I have:

dnsdist: Avoid constructing a DNSResponse object when not really needed

---

docs/http-api/swagger/authoritative-api-swagger.yaml
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
pdns/dns.hh
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

This adds, similarly to comments, a "last modified" timestamp to the rrsets returned by the HTTP API, when this information is known. Currently only implemented in LMDB. I've been told some people have an interest in this.
I have:

Provide record timestamps in the API

---

pdns/dnsdistdist/dnsdist-idstate.hh
pdns/dnsdistdist/dnsdist-self-answers.cc
pdns/dnsdistdist/dnsdist.cc

We already parse the EDNS Z value once for incoming UDP queries, so no need to do it again later in the process.
I have:

dnsdist: Only parse EDNS Z once

---

pdns/dnsdistdist/dnsdist-idstate.hh
pdns/dnsdistdist/dnsdist-self-answers.cc
pdns/dnsdistdist/dnsdist.cc

Backport of #15872 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 15872 - Only parse EDNS Z once

---

pdns/dnsdistdist/dnsdist-configuration.hh

Backport #15871 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 15871 - Use an unordered map for pools

---

ext/luawrapper/include/LuaContext.hpp
pdns/test-luawrapper.cc

My motivation is that now that `std::optional` is available I prefer using it instead of `boost::optional`, and it is silly to have to convert between the two around the C++/Lua interface.
Ideally I would not mind removing support for `boost::optional` in LuaWrapper altogether, but this would require a significant amount of work.
I have:

LuaWrapper: Add support for `std::optional`

---

pdns/recursordist/docs/lua-config/protobuf.rst
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-tcp.cc
regression-tests.recursor-dnssec/test_Protobuf.py

Backport 15010 to rec-5.1.x: fix protobufServer(.. {taggedOnly=true}) logic for cache-returned responses

---

dockerdata/startup.py

Fixes #15367
(cherry picked from commit 11c99697469722bce3cc675a128f79790e934a7c)
Backport of #15368
I have:

Backport 15368 to rec-5.2.x: fix generation of recursor config if PDNS_RECURSOR_API_KEY is set

---

pdns/rcpgenerator.cc
pdns/test-rcpgenerator_cc.cc
pdns/test-svc_records_cc.cc

To avoid other issues, increase strictness of value checks for *known* keys, regardless if they are in generic or canonical format.
Also add a test for key00NNN (= leading zeroes).
https://github.com/PowerDNS/pdns/issues/15479
I have:

SVCB: allow parsing keys in generic format without value

---

modules/lmdbbackend/lmdbbackend.cc

This routine (only used for to enumerate the contents of a view) chops an lmdb key into a vector of labels, then builds a DNSName with all the labels in reverse order, and reverses it. But we know enough to be able to build it with the labels in right order and save that reverse call... (not sure this is good enough to allow us to get rid of the comment regarding this routine's efficiency, though)
I have:

Make keyUnconv a bit less inefficient

---

regression-tests.dnsdist/test_TimeoutResponse.py

This test fails from time to time in our CI. After investigation, it turns out that sometimes the response comes just a few milliseconds after the 3 seconds timeout has expired:
```
Got answer from 127.0.0.1:14191, relayed to 127.0.0.1:36139 (UDP), took 3.00105e+06 us
```
So let's use a slightly larger timeout of 4 seconds. It will not add any delay if the response is received faster than that and will hopefully reduce the number of spurious failures.
I have:

dnsdist: Increase the time granted for the "timeout then restart" test

---

pdns/dnsdistdist/dnsdist-lua.cc

This adds some missing #if statements to support building without OpenSSL.
When compiling dnsdist 2.0.0 without OpenSSL support it fails in several places.
This patch adds #if defined(HAVE_LIBSSL) where needed.
I have:

Add missing #if statements to dnsdist-lua.cc

---

docs/http-api/swagger/authoritative-api-swagger.yaml
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
pdns/dns.hh
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

This is backport of the "records timestamps in the API" PR. The only change compared to what is is master is that I did not change the API swagger version in this PR.
I have:

Backport 15867 to auth 4.9.x

---

docs/backends/geoip.rst

The geoip backend documentation mentions:
> Additionally, the GeoIP backend can be used to provide service over
> several clusters, any of which can be taken out of use easily, for
> example for maintenance purposes.
But no details on how that is achieved. Without knowing Lua records exist, it's hard to find how to do it.
Add a reference to the Lua records documentation to make it easier to see the connection.
I have:

docs: clarify geoip service health checks uses lua records

---

ext/lmdb-safe/lmdb-safe.cc
ext/lmdb-safe/lmdb-safe.hh

LMDB requires:
- a transaction and its cursors must only be used by a single thread
- a thread may only have a single transaction at a time
- but, if `MDB_NOTLS` is in use, this does not apply to read-only transactions.
The first and second points are the reasons why we are keeping track of transactions, but because of the third point we cannot be strict with regard to read-only transactions, unless we keep track of whether the `MDB_NOTLS` flag is in use.
I recently noticed that I made a mistake in c340aa91bf37d8105d2b2390eecbadfca88c1d27, and `MDBEnv::getROTX()` now returns the number of read-write transactions instead of the number of read-only transactions. I also noticed that `MDBEnv::getROTX()` is not actually used, and we only enforce that a thread that already has a read-write …

lmdb-safe: Remove the read-only transactions counter

---

pdns/dnsdistdist/dnsdist-concurrent-connections.cc

In some setups the cleaning was too aggressive, wasting CPU cycles.
I have:

dnsdist: Clean up incoming TCP connections counters once per minute

---

pdns/dnsdistdist/dnsdist.cc
pdns/dnsname.cc
pdns/dnsname.hh
pdns/test-dnsname_cc.cc

This commit introduces a new method to compare a `DNSName` against a view of raw, wire-format bytes, skipping the
allocation and copy that is usually required to get a second `DNSName` object to compare against. This significantly reduces the amount of time matching a DNS response received from a backend against the content we expect to find.
I have:

dnsdist: Speed up response content matching

---

pdns/dynhandler.cc
regression-tests.nobackend/supermaster-signed/expected_result
regression-tests.nobackend/supermaster-unsigned/expected_result

This is an updated version of #12154, adding zone names in error messages, see that PR description for use case and details.
I have:

More zone names in error messages

---

pdns/recursordist/rec-rust-lib/rust/src/bridge.hh

Not doing so results in creating shared pointer to an incomplete class, which does not work for all compilers/c++ libs.
I have:

rec: include logr.hh in bridge.hh

---

pdns/recursordist/rec-rust-lib/rust/src/bridge.hh

Not doing so results in creating a shared pointer to an incomplete class, which does not work for all compilers/c++ lib combinations.
(cherry picked from commit d8cc01c39531a3ec6ca1ad8ec17b09a97b0f833a)
Backport of #16021 
I have:

Backport 16021 to rec-5.3.x: include logr.hh in bridge.hh

---

modules/bindbackend/bindbackend2.cc
pdns/dnswriter.cc

We require Boost >= 1.54 to build. Therefore, we can drop constructs written to accomodate older versions.
I have:

Remove boost < 1.54 leftovers

---

builder-support/helpers/h2o.json

The new version of `h2o` adds mitigation against the MadeYouReset / CVE-2025-8671 attack.
I have:

dnsdist: Upgrade h2o to 2.2.6-pdns3

---

pdns/dnsdistdist/dnsdist-crypto.cc

Fixes g++ 8: ../dnsdist-crypto.cc:291:16: warning: operation on 'count' may be undefined [-Wsequence-point]
I have:

dnsdist: don't increment in a potential macro argument

---

pdns/dnsdistdist/dnsdist-crypto.cc

Backport of #16042 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 16042 - Don't increment in a potential macro argument

---

pdns/dnsdistdist/dnsdist-crypto.cc

Backport of #16042 to rel/dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 16042 - Don't increment in a potential macro argument

---

pdns/dnsdistdist/meson/compiler-setup/meson.build

Backport of #16043 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 16043 - Allow building wth gcc8, which needs -lstdc++fs as link argument

---

pdns/packethandler.hh
pdns/rfc2136handler.cc
regression-tests.auth-py/test_GSSTSIG.py

As mentioned in #14953, if the Lua policy script refuses a DNS update request, we will skip the records which have caused the rejection. But if all the records in the update get rejected by the Lua policy, it makes much more sense (IMHO) to return `Refused`. Partial updates will still return `OK` (unless they hit another error condition).
I have:

Correctly handle dnsupdate reject by Lua policy

---

pdns/dnsdistdist/docs/guides/webserver.rst
pdns/dnsdistdist/docs/reference/config.rst

This MR tries to clarify different auths in the built-in webserver in the docs.
I have no idea how do the auth interfere with custom endpoints made in dnsdist config with `registerWebHandler` :( I don't currently use it anywhere.
Fixes #15769
I have:

dnsdist: Clarify different webserver auths

---

regression-tests.nobackend/gsqlite3-corrupted-record/command

Apparently a last-minute change in #15966 which broke the added test was not caught by the CI and this was successfully merged, only to break further PR once rebased. Sorry about that.
I have:

auth: unbreak test.

---

modules/bindbackend/bindbackend2.cc
modules/bindbackend/bindbackend2.hh
pdns/zoneparser-tng.cc
pdns/zoneparser-tng.hh

As mentioned in #469, if you use a bind zone file which includes other file, and use a nonzero value of `bind-check-interval` in order to reload the zone when it changes, the check only concerns the first zone files, and changes to any included files are not noticed.
This PR fixes this by:
- making a list of all the included files.
- ~~checking it twice, PowerDNS is coming to town.~~
- checking the modified time of all these files when the check gets triggered.
I have:

auth: smarter bind zone file freshness check

---

pdns/rcpgenerator.cc
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

This PR is intended to fix #11052 by preventing ill-formed record data to be fed from the REST API, by performing stricter validation of the records.
As usual, you get a first cleanup commit while thinking about the problem (which makes `ws-auth.cc` 100% clang-tidy compliant!), and one two-liner commit which addresses it.
I have:

API: stricter record content validation

---

pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist-nghttp2.cc
pdns/dnsdistdist/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist-tcp.hh
pdns/dnsdistdist/test-dnsdistnghttp2_cc.cc

Backport of #16015 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport 16015 - Don't call `nghttp2_session_send` from a callback

---

pdns/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist-nghttp2-in.cc
pdns/dnsdistdist/dnsdist-nghttp2.cc
pdns/dnsdistdist/dnsdist-tcp.hh
pdns/dnsdistdist/test-dnsdistnghttp2_cc.cc

Backport of #16015 to rel/dnsdist-1.9.x
I have:

dnsdist-1.9.x: Backport 16015 - Don't call `nghttp2_session_send` from a callback

---

pdns/ixfrutils.hh
regression-tests.ixfrdist/test_CaseSensitiveTXT.py

TXT record values are case sensitive, but the compilation of an IXFR difference in ixfrdist doesn't produce a difference when the change is only a case modification.
This commit removes the toLower() call when comparing record content to properly handle case-sensitive changes.
I have:

fix case sensitivity handling for IXFR requests in ixfrdist

---

meson.build
tasks.py

While building the auth and running the regression/unit tests for all the backends. I discovered that `meson` does not check if `socat` is installed.
This is fixed in this commit:
- **fix(auth): Ensure socat is installed when enabling tests**
I then discovered that `PDNS_BUILD_PATH` is not correctly set when running `meson test`. It would be empty, and hence `start-test-stop` would look for the wrong binaries in the wrong place.
This is fixed with this commit:
- **fix(auth): set PDNS_BUILD_PATH when running tests**
Note that not *all* tests run with `meson test` actually succeed from me. But those failures are not related to these changes.
I have:

auth: small meson improvements for testing

---

pdns/dnsdistdist/dnsdist-nghttp2.cc

Backport of #16082 to rel/dnsdist-2.0.x
I have:

dnsdist-2.0.x: Backport #16082 - Fix the IO reentry guard in outgoing DoH

---

docs/upgrading.rst
pdns/dnslabeltext.rl
pdns/misc.hh
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

This is an attempt at fixing #15990. Instead of taking the JSON record content strings as is, they will now be processed a bit to increase the odds of them matching their proper representation and pass validation.
As a side effect, this unbreaks a test labeled as a regression, which is probably something good?
I have:

REST API: normalize record contents received

---

pdns/rcpgenerator.cc
pdns/test-dnsrecords_cc.cc

Two small changes to textual data in record contents:
- reading a multiple values record (`HINFO`, `NAPTR`) from text form (bind-style or fed to the API) did not allow values to be unquoted, even if they did not contain spaces. This is now accepted (and fixes two known-to-be-broken unit tests).
- writing a multiple values record, when one of the values is an empty string, well, did output an empty string, leading to confusing error messages. These empty values will now get output as `""` to make them "visible". This is intended to help #5208 where the error message complaining about the bad record did not make enough sense.
I have:

auth: record contents handling changes

---

pdns/dnsdistdist/dnsdist.cc
regression-tests.dnsdist/test_ConfigurationUpdates.py

Backport of #16065 to rel/dnsdist-2.0.x
This is mostly new regression tests but also includes a small change that prevents an unwanted delay when the configuration has been updated while `recv` was waiting for a packet.
I have:

dnsdist-2.0.x: Backport 16065 - Test that the configuration is correctly reloaded in various cases

---

modules/godbcbackend/sodbc.cc

@omoerbeek pointed me to a spurious auth test failure in the CI, which I have not been able to reproduce. However, building with sanitizers and running the tests again showed that in the ODBC module, `delete` was invoked on the wrong type and thus with a size not matching the size used by the matching `new`. This is caused by the `SQL_INTEGER` parameters being allocated either as `UDWORD` or `ULONG` which do not have the same size (at least on 64-bit platforms).
This PR tries to fix this by remembering the size used for allocation in this case, and invoking `delete` with either a `UDWORD *` or a `ULONG *` cast, whichever matches the size.
I have:

auth: memory corruption in ODBC

---

pdns/recursordist/lwres.cc

Otherwise binding a local TCP port will fail, as the stored port is likely still in use do to connections lingering.
Observed when forcing DoT to specific nameservers that support cookies.  In many cases the effect was: see the bind failing and go to the next nameserver, that's likely why it was noticed before.
While there, add a little bit of more detail in trace info.
I have:

rec: only store IP (and no port) as local address in cookie store

---

pdns/recursordist/docs/lua-scripting/comboaddress.rst

Fixes #16128
Plus some general improvements.
One day we should make the Lua classes docs for all three products (more) consistent.
I have:

rec docs: ComboAddress has no == operator, don't suggest it has

---

m4/boost.m4

Same PR as #16009, but targeting the correct branch this time.
I have:

auth-5.0: backport "Fix Boost system lib dependency: it is no longer available since 1.89"

---

docs/backends/lmdb.rst
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh

Backport of #16141. Raw diff is slightly different due to lmdb performance changes (#15864) not having been backported.
I have:

auth 5.0: backport "lmdb: optional memory-only notification timestamps"

---

docs/views.rst
pdns/check-zone.cc
pdns/check-zone.hh
pdns/pdnsutil.cc
pdns/ws-auth.cc
regression-tests/tests/views-management/expected_result

Although view names never end up on the wire, they need to be usable with the REST API, so we need to reject a few characters (such as `/`).
This PR adds view name validation to `pdnsutil` and the REST API, and updates the documentation to mention the allowed characters for view names.
I have:

auth views: perform character set validation of view names

---

contrib/ProtobufLogger.py
pdns/dnsmessage.proto
pdns/protozero-trace.hh
pdns/protozero.hh
pdns/recursordist/pdns_recursor.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/rec-tcp.cc
regression-tests.recursor-dnssec/test_Protobuf.py

Fields are added if available. At the moment, the availability of a `TraceID` is coupled to OT Trace data being generated. 
We might want to record a `openTelemetryTraceID` into the protobuf without  generating or including the OT Trace into the PB. That is for a later PR.
Tagging @neilcook. Once approved, the `dnsmessage.proto` changes should be copied to https://github.com/PowerDNS/dnsmessage
I have:

rec: add a few fields in protobuf logs: ede, edeText and OpenTelemetryTraceID

---

.github/workflows/build-docker-images-tags.yml
.github/workflows/docker.yml

Backport 16169 to rec 5.1.x: build-docker-images-tags: Grant enough permissions to sign images

---

modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh

I went into the LMDB backend once again to tinker around some idea I had. The idea turned out not to be a good one, but while tinkering I came with that cleanup which IMO makes the code a bit less ugly.
I have:

auth: some more lmdb polish

---

builder-support/dockerfiles/Dockerfile.dnsdist
pdns/dnsdistdist/meson-dist-script.sh

Since we are now dynamically setting the version of our internal Rust library when generating the release tarball, `cargo` needs to update the `Cargo.lock` file to reflect the new version, which is not possible if we are passing `--locked`:
```
error: the lock file /pdns/dnsdist-2.1.0-alpha0.870.master.gc64b979bc/dnsdist-rust-lib/rust/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```
This commit fixes that also updating the `Cargo.lock` file when generating the release tarball so that `cargo` no longer needs to update the `Cargo.lock`.
Fixes #16177 
I have:

dnsdist: Fix release builds by updating the locked Rust lib version

---

pdns/dnsrecords.cc
pdns/dnsrecords.hh
pdns/qtype.cc
pdns/qtype.hh
pdns/test-dnsrecords_cc.cc

This PR adds support for the HHIT and BRID records defined in [draft-ietf-drip-registries-33](https://www.ietf.org/archive/id/draft-ietf-drip-registries-33.html).
These are (from our perspective) simple Base64 encoded blobs. The blobs themselves encode CBOR data that we can ignore.
I have:

feat: Add DRIP records (HHIT and BRID)

---

pdns/dnsdistdist/dnsdist-actions-factory.cc
pdns/dnsdistdist/dnsdist-idstate.cc
pdns/dnsdistdist/dnsdist-idstate.hh
pdns/dnsdistdist/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-lua-ffi.hh
pdns/dnsdistdist/dnsdist.hh
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/test-dnsdist-lua-ffi.cc
regression-tests.dnsdist/test_Protobuf.py

This commit fixes setting Protocol Buffer meta keys on DNS response via Lua FFI: the existing code was assuming it was possible to use the question methods on a response object which is not true and would likely have ended in a crash at some point.
It also propagates meta keys set on a DNS question to the corresponding DNS response.Before this commit the values were not passed along to the response which was quite unexpected, especially for self-answered responses.
I have:

dnsdist: Fix setting meta keys on response, pass them from question to response

---

docs/backends/lmdb.rst
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh

This is similar to #16154, but this time concerning the domain freshness check timestamp.
This behaviour is controlled by the `lmdb-write-notification-update` setting (which name becomes thus a bit misleading, suggestions welcome, rename it or add a separate setting?)
I think that this more or less fixes (or at least, works around) #13024.
I have:

lmdb: optional memory-only freshness check timestamp
