docs/markdown/authoritative/backend-remote.md
=> Add note about priority field

pdns/README-dnsdist.md, pdns/dnsdist-carbon.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist-web.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/html/local.js
For each downstream server, export queries, drops and latency.
=> Export dnsdist Downstream servers stats via carbon.

pdns/dnsrecords.hh
=> Fix inconsistent override usage in dnsrecords.hh

pdns/Makefile.am, pdns/iputils.cc, pdns/iputils.hh, pdns/test-nmtree.cc
Provides NetmaskTree<T> implementation, which is a IP prefix tree intended for best prefix matching for IPv4 and IPv6 addresses.
=> Tree implementation for NetmaskGroup

.travis.yml, docs/markdown/authoritative/backend-geoip.md, modules/geoipbackend/geoipbackend.cc
Adds support for
- per subnet formats
- additional format specifiers
Fixes
- Uses most specific scope
=> Geoipbackend features

modules/pipebackend/pipebackend.cc, modules/pipebackend/pipebackend.hh, pdns/pdnssec.cc
Closes #2921 (thanks @paddg)!
@zeha ?
=> pipe: Correctly initialize the abi-version var

modules/godbcbackend/sodbc.cc, regression-tests/start-test-stop
- Fix SELECT NULL safety
- Do not truncate variable length data
Fixes partially #2926
=> gODBC touches

build-scripts/build-auth-debian
These variables are defined so we use them everywhere
=> use the vars

docs/manpages/dnsdist.1.md, pdns/README-dnsdist.md, pdns/dnsdist.cc, pdns/dnsdistdist/.gitignore
* Add a `--version` command
* Add dnsdist to the gitignore
=> small dnsdist enhancements

.travis.yml, docs/markdown/authoritative/backend-geoip.md, modules/geoipbackend/geoipbackend.cc, modules/geoipbackend/regression-tests/.gitignore, modules/geoipbackend/regression-tests/region-a-resolution/command, modules/geoipbackend/regression-tests/region-cname-resolution/command, modules/geoipbackend/regression-tests/text-interpolation/command, modules/geoipbackend/regression-tests/text-interpolation/description, regression-tests/backends/geoip-master, regression-tests/start-test-stop
Add ability to interpolate the content field with geoip attributes.
=> Geoip interpolation and sundry of fixes.

pdns/ws-auth.cc
And rename the involved var so its clearer what is going on.
=> API: fix crash introduced in abb873ee

.travis.yml, regression-tests/backends/geoip-master, regression-tests/backends/remote-master
=> redo .travis.yml

pdns/dnsdist-tcp.cc
In dnsdist, we try to reuse TCP connection to Downstream servers
as much as possible. However, when sending the size of a new
query, we didn't properly handle a connection being closed by the
downstream server.
Turns out, writing tests actually help finding bugs, who
would have thought?
=> Gracefully handle a reused downstream TCP connection dying on us

pdns/qtype.hh
=> Move internal QTypes to the private range

pdns/misc.hh
=> Drop compat code for gcc3.x/RHEL5

pdns/dnsdistdist/html/index.html
=> Improve dnsdist html a tiny bit more

.travis.yml, pdns/ws-recursor.cc
And fix a memory/rapidjson issue.
If the data is correct is yet to be seen.
=> API: Reenable Recursor tests

docs/markdown/httpapi/api_spec.md, pdns/json.cc, pdns/json.hh, pdns/ws-api.cc, pdns/ws-api.hh, pdns/ws-auth.cc, pdns/ws-recursor.cc, regression-tests.api/test_Cache.py, regression-tests.api/test_Servers.py
Note that this changes the URL, and only allows for exact flushing now.
Fixes #3003.
=> API: make cache flushing a public, documented operation

pdns/devpollmplexer.cc
=> devpoll compile fix

modules/bindbackend/bindbackend2.cc, pdns/dnsrecords.cc, pdns/pdnssec.cc, pdns/resolver.cc
#3020 
~~Todo: port to master~~
=> traling dot in DNAME content

m4/boost.m4
=> update boost.m4 to latest version

pdns/dynhandler.cc
=> Exit with 0 when receiving QUIT

pdns/mbedtlssigners.cc
=> Fix overzealous replacement of pdnssec

docs/markdown/changelog.md.raw, pdns/common_startup.cc, pdns/pdns.conf-dist
=> auth: listen on v6 by default

pdns/misc.cc
=> Fix missing cast, LLONG_MIN->LONG_MIN in strToUID() and strToGID()

pdns/zone2sql.cc
=> Remove --dnssec from zone2sql

modules/luabackend/lua_functions.cc, modules/luabackend/luabackend.hh, modules/luabackend/minimal.cc
edns subnet support for luabackend
=> luabackend: edns-subnet support

pdns/zone2sql.cc
Introduced in #3019.
Closes #3067
=> Fix logic error in zone2sql

build-scripts/debian-recursor/pdns-recursor.init, docs/markdown/recursor/settings.md, pdns/pdns_recursor.cc
=> Run pdns_recursor on the foreground by default

pdns/dnsbackend.cc, pdns/dnsbackend.hh, pdns/ueberbackend.cc, regression-tests/tests/bind-add-zone/expected_result.bind
Closes #2793 by porting the changes made in #2770 to master.
=> negcache improvements

build-aux/gen-version, build-scripts/build-auth-rpm, build-scripts/build-dnsdist-rpm, build-scripts/build-recursor-rpm
=> Build release packages properly

pdns/dnsdist-console.cc
=> Update dnsdist completion rules, fixes completion dying on us

m4/ax_check_openssl.m4, pdns/Makefile.am, pdns/opensslsigners.hh, pdns/version.cc
include / closes #3131 
fixes #3133
=> improve openssl m4 file and some cleanup

docs/markdown/authoritative/installation.md
The current output is pretty out-of-date, it is back from 2002!
This patch updates the output to the version of 3.3.
=> update the output of 'pdns monitor'

pdns/pdnsutil.cc
=> Fix pdnsutil check-all-zones crash

pdns/misc.cc
=> Add timezone to generated bind slave zone files

docs/secpoll.zone
Also, update the NS records in the zone to use the new infra
Closes #3114
=> Update secpoll for alpha1

pdns/mbedtlssigners.cc
As noted by @mind04 in #3161, nothing guarantees the signer will
be used for a single task with a single key. This way we make
sure that there is nothing left behind.
In addition, we now consistently use getName() in error messages.
=> mbed ECDSA: Completely reset the key on from* calls

m4/pdns_enable_reproducible.m4
=> Determine system name at configure time

modules/luabackend/lua_functions.cc, pdns/logger.hh, pdns/lua-pdns.cc, pdns/mastercommunicator.cc, pdns/tcpreceiver.cc, pdns/ueberbackend.cc
=> Remove Logger::NTLog

modules/bindbackend/bindbackend2.cc, pdns/resolver.cc
=> fix trailing dots in slave zones

pdns/dnsdist-web.cc, pdns/dnsdistdist/html/local.js
=> Expose server latency in dnsdist API/UI

pdns/pdnsutil.cc
=> pdnsutil: don't check disabled records

pdns/pdnssec.cc
Closes #3184 
Backport of #3205 to 3.4
=> pdnssec: don't check disabled records

pdns/pdnsutil.cc
With a SOA, the zone is considered created by all parts.
Fixes #3168 
Serial = 1, other parts taken from default-* settings.
=> pdnsutil create-zone: Create SOA, too

m4/ax_lib_socket_nsl.m4
=> Add socket/nsl check to local m4

pdns/filterpo.cc, pdns/lua-recursor4.cc, pdns/rpzloader.cc, pdns/validate.cc
Fix small things in recursor code.
=> Recursor fixes

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc, pdns/dnsrulactions.hh
Add AllowAction() to dnsdist as the README says it should be available
=> dnsdist: README hints to AllowAction() yet doesnt exist, add it

pdns/dnsdistdist/html/index.html, pdns/dnsdistdist/html/lines.css
* closing tag for head
* move css to head
* fix duplicate id chart_container (change to class)
* remove some trailing whitespace
=> fix html a bit

build-scripts/dist-dnsdist, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/configure.ac, pdns/dnsdistdist/m4/pdns_check_pandoc.m4, pdns/dnsdistdist/populate
Build manpage when they are not there and ensure they are distributed in
the tarball.
=> dnsdist: Build manpages from make

pdns/Makefile.am
=> remove unneeded source from auth tarball testrunner

pdns/dnsdist-ecs.cc
Using the buffer value at position `pos` as an uint16_t requires 2 byte alignment,
which is not guaranteed here.
=> dnsdist: Fix misaligned load/store in ECS, reported by UBSAN

docs/markdown/authoritative/backend-generic-sql.md, modules/bindbackend/bindbackend2.cc, pdns/backends/gsql/gsqlbackend.cc, pdns/dnsbackend.cc, pdns/tcpreceiver.cc
Also, exit instead of crashing when a backend throws a PDNSException during initialization.
=> Make auth crash less on transient DB failures

regression-tests.nobackend/zone2sql-json-comments/command, regression-tests.nobackend/zone2sql-json-comments/description, regression-tests.nobackend/zone2sql-json-comments/example.net.zone, regression-tests.nobackend/zone2sql-json-comments/expected_result
=> Add test for zone2sql --json-comments

pdns/dnsdist-lua2.cc
Hopefully this should fix #3277.
=> dnsdist: Lock the response ring in exceedRespGen()

modules/remotebackend/Makefile.am, modules/remotebackend/TODO, modules/remotebackend/httpconnector.cc, modules/remotebackend/pipeconnector.cc, modules/remotebackend/regression-tests/backend.rb, modules/remotebackend/remotebackend.cc, modules/remotebackend/remotebackend.hh, modules/remotebackend/test-remotebackend-http.cc, modules/remotebackend/test-remotebackend-json.cc, modules/remotebackend/test-remotebackend-pipe.cc, modules/remotebackend/test-remotebackend-post.cc, modules/remotebackend/test-remotebackend-unix.cc, modules/remotebackend/test-remotebackend-zeromq.cc, modules/remotebackend/test-remotebackend.cc, modules/remotebackend/unixconnector.cc, modules/remotebackend/zmqconnector.cc, pdns/json.cc, pdns/json.hh
Removes rapidjson from remotebackend. Also fixes few small bugs found during conversion.
=> Convert remotebackend to JSON11 and fix some small bugs

modules/bindbackend/bindbackend2.cc
Replace the out-of-zone check by using DNSName isPartOf().
Without this commit, importing the Yeti root zone via AXFR fails
with:
"Unable to feed record during incoming AXFR of '.':
out-of-zone data 'aaa..' during AXFR of zone '..'
because stripDomainSuffix("aaa.", ".") returns false.
=> Fix bindbackend's feedRecord to handle being slave for the root

pdns/dnsdist-tcp.cc
The outstanding count was incremented for every query processed
in a single TCP session but was only decremented once per session.
It could also have been decremented before being incremented
if setupTCPDownstream() failed.
It might close #3288.
=> dnsdist: Better handling of outstanding TCP queries

pdns/dnsdistdist/Makefile.am
This allows to regenerate the js files
=> add incfiles and src_js/ to dnsdist dist tarball

README.md, docs/markdown/authoritative/recursion.md
@pieterlexis Hi. I'm more a tennis guy.
=> Improve README.md for recursor compilation

pdns/zoneparser-tng.cc
=> ZoneParser: Throw PDNSException on too many SOA data elements

pdns/dnsdist-lua.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsrulactions.hh
=> Distclass: expose qclass to dnsdist

pdns/Makefile.am, pdns/dnsparser.hh, pdns/test-dnsparser_hh.cc
=> Allow lowercase typeXXXX record types

pdns/dnsdist-lua.cc
=> dnsdist: Log webserver binding errors even in client mode

pdns/pdnsutil.cc
=> pdnsutil: provide helpful output with command help

pdns/pdnsutil.cc
=> pdnsutil: warn if we can't read the config file

modules/ldapbackend/ldapbackend.cc, modules/ldapbackend/powerldap.cc
=> unbreak the LDAP backend

pdns/pdnsutil.cc
=> pdnsutil: respect default-soa-* settings

pdns/lua-recursor4.cc
=> recursor: apply rcode set in UDPQueryResponse callback

pdns/README-dnsdist.md, pdns/dnsdist-lua.cc, regression-tests.dnsdist/.gitignore, regression-tests.dnsdist/dnscrypt.py, regression-tests.dnsdist/dnsdisttests.py, regression-tests.dnsdist/test_Advanced.py, regression-tests.dnsdist/test_Basics.py, regression-tests.dnsdist/test_DNSCrypt.py, regression-tests.dnsdist/test_EdnsClientSubnet.py
QPSPoolAction() and DNSSECRule() are mentioned in the README but
the Lua bindings were missing.
Add missing tests for some actions and rules.
Clean existing tests a bit in the process.
=> dnsdist: Add missing QPSPoolAction & DNSSECRule. Add missing tests.

docs/markdown/httpapi/README.md, docs/markdown/httpapi/api_spec.md, pdns/backends/gsql/gsqlbackend.cc, pdns/comment.hh, pdns/ws-auth.cc, regression-tests.api/runtests.py, regression-tests.api/test_Zones.py, regression-tests.api/test_helper.py
Will break any existing 4.0-alpha api-v1 users.
=> API: Fix zone/records design mistake

pdns/pdns_recursor.cc
needs testing, perhaps tests, docs
=> add lowercase-outgoing feature to Recursor

pdns/base64.cc
=> Handle return codes from OpenSSL BIO_*

pdns/dnsdist-tcp.cc, pdns/dnsdist.cc
Make sure we hold the Lua mutex before getting the packet cache
shared_ptr, so that we don't have a thread reading it at the
exact same time it is altered by another.
We could have used atomic_load/atomic_store but libstdc++ uses
a pool of mutex for that anyway.
This might fix #3396.
=> dnsdist: Prevent the cache ptr from being altered under our feet

pdns/Makefile.am, pdns/selectmplexer.cc
=> remove unnecessary include from selectmplexer.cc

pdns/dnsdist-web.cc
This is a very rough implementation to unify dnsdist with auth and
rec as far as pdnscontrol is concerned, by adding:
- /api/v1/servers/localhost/config
- /api/v1/servers/localhost/statistics
We'll need to refactor this at some point, maybe by merging with
ws-api.
=> dnsdist: Add statistics and config to API to make pdnscontrol happy

pdns/README-dnsdist.md, pdns/dnsdist-lua2.cc
Fix some minor issues in the README.
=> dnsdist: Don't crash when calling cache functions with nil on the console

pdns/pdnsutil.cc
=> pdnsutil: support chroot

docs/markdown/httpapi/api_spec.md, pdns/ws-api.cc, pdns/ws-api.hh, pdns/ws-auth.cc, pdns/ws-recursor.cc, regression-tests.api/test_Discovery.py
=> Add /api discovery endpoint

contrib/systemd-pdns.service
e9046db moved all our manpages to section 1.
=> pdns: man pages are in section 1 now

build-scripts/build-auth-rpm, build-scripts/build-dnsdist-rpm, build-scripts/build-recursor-rpm
=> Fix CentOS 6 builds

pdns/zoneparser-tng.cc, regression-tests.nobackend/tinydns-data-check/expected_result, regression-tests/zones/example.com
=> strip all types of whitespace from around content while parsing zones, fixes #3568

README.md
=> Use another copyright keypoint

modules/luabackend/dnssec.cc, modules/luabackend/lua_functions.cc, modules/luabackend/luabackend.hh, modules/luabackend/master.cc, modules/luabackend/private.cc, modules/luabackend/slave.cc, modules/luabackend/supermaster.cc, modules/luabackend/test2/.gitignore, modules/luabackend/test2/pdns, modules/luabackend/test2/pdns-luabackend.lua, modules/luabackend/test2/pdns.conf, modules/luabackend/test2/pdns_control, modules/luabackend/test2/runtest, modules/luabackend/test2/runtest.pl
Fixes for the Lua-backend, based on the luabackendfixes branch done by ahu.
Added some checking of return values.
Use pushinteger/tointeger where appropriate so things work a little better with Lua 5.3
Added a simple test script to test the backend.
=> Luabackendfixes take2

m4/pdns_check_os.m4
=> Add -latomic to LDFLAGS on mips(el)

pdns/pdnsutil.cc
=> pdnsutil: add NS record without trailing dot with create-zone

regression-tests/start-test-stop
Don't rely on the output of pdnsutil for this
Closes #3591
=> Add a ZSK to secure-delegated test zone properly

pdns/syncres.cc, pdns/syncres.hh
And also improve some trace messages.
=> Recursor: Fix the forwarding to multiple servers

docs/markdown/authoritative/dnsupdate.md, docs/markdown/authoritative/settings.md
=> Fix dnsupdate docs.

modules/geoipbackend/geoipbackend.cc
=> geoip: Fix typo in messages

pdns/backends/gsql/gsqlbackend.cc, pdns/backends/gsql/ssql.hh
=> Lowercase names when inserting in the database

regression-tests.recursor/config.sh, regression-tests.recursor/rec_control-manpage/command, regression-tests.recursor/rec_control-manpage/description, regression-tests/runtests, regression-tests/start-test-stop
=> Add test for rec_control manpage

pdns/pdnsutil.cc
=> pdnsutil: Don't try to rectify non-DNSSEC zones

pdns/zoneparser-tng.cc
=> tabs are whitespace too!

docs/markdown/recursor/settings.md, pdns/pdns_recursor.cc, regression-tests.recursor/config.sh, regression-tests.recursor/lowercase-outgoing/command, regression-tests.recursor/lowercase-outgoing/description, regression-tests.recursor/lowercase-outgoing/expected_result, regression-tests.recursor/start.sh, regression-tests.recursor/stop.sh
=> Add `lowercase-outgoing` to Recursor 4.0

modules/gpgsqlbackend/spgsql.cc
Closes #3480 
Could use a review
=> pdnsutil: Fix segfault in the gpgsql backend

pdns/dnsrulactions.hh
Otherwise we might crash when one thread inserts into the internal
map while another one is accessing it.
Reported by @rygl.
=> dnsdist: Add a lock to MaxQPSIPRule

docs/markdown/authoritative/backend-pipe.md, docs/markdown/authoritative/backend-remote.md
=> Document v6 scoped syntax

pdns/pdnsutil.cc
Use EXIT_ constants instead of bools or ints when function return
value is passed to exit() function.
=> fix exit statuses to constants and return 0 when success

pdns/dnsdistdist/Makefile.am
=> dnsdist: Make check should run testrunner

pdns/pdns_recursor.cc
Closes #3709
Also add a comment in the code regarding another DNSSEC ticket
=> Always validate on 'validate' and 'log-fail'

pdns/dnssecinfra.cc, pdns/dnssecinfra.hh, pdns/validate.cc
=> process nsec3 insecure delegation

build-scripts/travis.sh, regression-tests.recursor-dnssec/.gitignore, regression-tests.recursor-dnssec/basicDNSSEC.py, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/runtests, regression-tests.recursor-dnssec/test_Expired.py, regression-tests.recursor-dnssec/test_NotYetValid.py, regression-tests.recursor-dnssec/test_basicNSEC.py, regression-tests.recursor-dnssec/test_basicNSEC3.py
Basic NSEC and NSEC3 tests and timing-related tests.
=> More DNSSEC tests

pdns/zoneparser-tng.cc, regression-tests.nobackend/tinydns-data-check/expected_result, regression-tests/zones/example.com
=> backport parser fixes

docs/markdown/authoritative/howtos.md
Line 284: unset-pushish-cds --> unset-publish-cds
=> Fixed a typo

pdns/packethandler.cc
It was unused anyway, closes #213.
=> Remove the ancient validDNSName function

pdns/lua-recursor4.cc
=> rec: Add missing Lua rcodes bindings

modules/bindbackend/bindbackend2.cc
=> bind: Improve skipped zone error messages

pdns/pdnsutil.cc
=> pdnsutil load-zone: ignore double SOA

build-scripts/build-auth-debian, build-scripts/build-dnsdist-debian, build-scripts/build-recursor-debian, build-scripts/debian-recursor/pdns-recursor.install
Having it there will lead to pain
=> Remove dnsdist service file on trusty

docs/markdown/changelog.raw.md
with Unreleased as the date for now
=> Auth and Recursor 4.0.0-alpha3 changelogs

pdns/dnsbackend.cc, pdns/dnsbackend.hh, pdns/ueberbackend.cc
=> fix SOA caching with multiple backends (3.4.9)

modules/bindbackend/binddnssec.cc, pdns/dbdnsseckeeper.cc, pdns/pdnsutil.cc
=> set NSEC3PARAM algorithm to 1

pdns/common_startup.cc, pdns/logger.cc, pdns/logger.hh, pdns/pdns.conf-dist, pdns/pdns_recursor.cc, pdns/receiver.cc
=> Add disable syslog setting for 3.4

build-scripts/build-auth-rpm, build-scripts/debian-authoritative/rules
By the time this is read, it is too late anyway.
=> build scripts: Stop patching config-dir in pdns.conf

pdns/recursordist/pdns-recursor.service.in
=> rec: Increase max FDs for systemd machines

pdns/dnssecinfra.cc, pdns/logger.cc, pdns/pdns_recursor.cc, pdns/rec_control.cc, pdns/recursordist/Makefile.am, pdns/recursordist/configure.ac, pdns/recursordist/statbag.cc, pdns/recursordist/statbag.hh
* Add summary to the recursor's configure output
* Remove the statbag from the recursor
* Fix #3855 as well
=> Some Recursor fixes

regression-tests.api/runtests, regression-tests.dnsdist/runtests, regression-tests.recursor-dnssec/runtests
Note: I only tested this for dnsdist.
=> allow overriding python binary in tests

build-scripts/build-auth-debian, build-scripts/build-auth-rpm, build-scripts/debian-authoritative/pdns-server.install, docs/markdown/authoritative/running.md, pdns/.gitignore, pdns/Makefile.am
Idea and some changes taken from @ekohl, thanks!
Closes: #2563
=> Generate and install virtual hosting unit file

contrib/ProtobufLogger.py
=> Add ProtobufLogger.py, a script to display protobuf messages

pdns/recursordist/pdns-recursor.service.in
=> recursor: set more sensible default fd limit

docs/markdown/recursor/dnssec.md, docs/mkdocs.yml
Note, already contains docs on the non-merged #3910 code.
=> Add Recursor DNSSEC docs

build-scripts/build-recursor-debian, build-scripts/build-recursor-rpm, build-scripts/debian-recursor/pdns-recursor.install, pdns/recursordist/.gitignore, pdns/recursordist/Makefile.am
=> recursor: Add multi-instance unit-file

pdns/lwres.cc
to comply with [RFC 6840 § 5.9](https://tools.ietf.org/html/rfc6840#section-5.9)
=> Recursor: set +CD on queries forwarded to a recursor

docs/markdown/httpapi/README.md
=> fix link for #3950

build-scripts/debian-authoritative/control.in, build-scripts/debian-authoritative/rules, build-scripts/debian-recursor/rules
=> Sync debian build scripts a bit

pdns/recursordist/README.md
=> README: Fix package and pkg-config names for libluaX.Y on Debian/Ubuntu

pdns/reczones.cc
=> recursor: Require = in forward-zones

docs/markdown/changelog.raw.md, docs/secpoll.zone
Need to merge #3957 and #3961 first.
=> Add Recursor RC1 changelog

m4/boost.m4
the parts where we differ are filed upstream as:
https://github.com/tsuna/boost.m4/pull/83
https://github.com/tsuna/boost.m4/pull/85
=> sync boost.m4 with upstream

docs/markdown/recursor/dnssec.md
=> Add a remark on dig's use of the AD flag

pdns/dnspcap2protobuf.cc
The protobuf 'question' object is always used but wasn't released correctly when `QR` wasn't set. Use protobuf's `mutable_()` getters instead of allocating separate objects on the stack to prevent this kind of errors.
=> Fix an invalid use of stack memory in dnspcap2protobuf

pdns/dnsdist.cc
=> dnsdist: Add version and feature information to version output

pdns/dnsgram.cc, pdns/dnspcap.cc, pdns/dnspcap.hh, pdns/dnspcap2protobuf.cc
Mostly missing/bad error handling for edge cases.
=> auth: Minor fixes to dnspcap{,2protobuf}, reported by coverity

docs/markdown/authoritative/backend-pipe.md
=> Reformat pipebackend documentation for clarity

modules/gmysqlbackend/gmysqlbackend.cc, modules/godbcbackend/godbcbackend.cc, modules/goraclebackend/goraclebackend.cc, modules/gpgsqlbackend/gpgsqlbackend.cc, modules/gsqlite3backend/gsqlite3backend.cc, pdns/backends/gsql/gsqlbackend.cc, pdns/backends/gsql/gsqlbackend.hh
=> remove gsql::isOurDomain for now

pdns/recursordist/html/js/d3.js, pdns/recursordist/html/js/jquery-1.8.3.js, pdns/recursordist/html/js/moment.js, pdns/recursordist/html/js/rickshaw.js, pdns/recursordist/html/js/underscore.js
* d3 v3.3.6
* jquery v1.8.3
* moment v2.9.0
* rickshaw v1.4.6
* underscore v1.8.3
Fixes last missing files in Recursor tarball for #3118.
=> Import Javascript sources for libs shipped with Recursor

modules/gsqlite3backend/gsqlite3backend.cc, modules/gsqlite3backend/gsqlite3backend.hh, modules/ldapbackend/ldapbackend.hh, modules/luabackend/dnssec.cc, modules/luabackend/lua_functions.cc, modules/luabackend/luabackend.cc, modules/luabackend/master.cc, modules/luabackend/minimal.cc, modules/luabackend/private.cc, modules/luabackend/reload.cc, modules/luabackend/slave.cc, modules/luabackend/supermaster.cc, modules/opendbxbackend/odbxbackend.hh, pdns/sodcrypto.cc, pdns/ssqlite3.cc, pdns/ssqlite3.hh, pdns/zone2ldap.cc
=> Hopefully appease the License Gods (again)

pdns/dnsdistdist/incfiles, pdns/recursordist/incfiles
For improved reproducibility.
Fixes #4092
=> Sort included html files

pdns/basic.rpz
=> Recursor: basic.rpz fix

docs/markdown/recursor/settings.md
=> rec: Add protocol buffers documentation

build-scripts/travis.sh, pdns/Makefile.am
also fix auth `make check` failing because of missing file in tarball
=> Add protobuf to travis

build-scripts/build-dnsdist-rpm
Fixes #4130 
The raspi builds will be fixed once we have the time to look at the pi's
=> Build RPMs with protobuf

docs/markdown/authoritative/settings.md, docs/markdown/authoritative/upgrading.md, docs/markdown/recursor/settings.md
Fixes one of the marks in #4151
=> Update docs for 4.0.0

build-scripts/build-auth-rpm
=> Create tinydns backend packages for CentOS 7

pdns/rec_channel_rec.cc
=> rec 3.7.x: Add some sanity checking to rec_control wipe-cache

pdns/lua-recursor4.cc
=> Fail on startup when lua-dns-script doesn't exist

pdns/dbdnsseckeeper.cc
=> ignore tailing dot in signer name

pdns/lua-recursor4.cc
=> Add more Netmask methods for recursor Lua

pdns/pdnsutil.cc
If no changes are made then exit instead of asking what to do.
=> pdnsutil: Remove checking of ctime and always diff the changes.

pdns/secpoll-recursor.cc
=> Validate DNSSEC for secpoll.powerdns.com

pdns/packethandler.cc
This allows for example the use of dnsdist in front of supermaster
slaves.
dnsdist must be configured to send ECS to the backend with:
* `useClientSubnet=true` on the corresponding `newServer()`
* `setECSSourcePrefixV4(32)` and/or `setECSSourcePrefixV6(128)` so
the exact source is sent to the slave
* `setECSOverride(true)` so that any existing ECS information is
overridden
In addition, pdns must be configured to accept notification from
dnsdist with `trusted-notification-proxy` and to process ECS with
`edns-subnet-processing=yes`.
Closes #4039.
=> auth: Trust EDNS Client Subnet from a trusted notification proxy

docs/markdown/authoritative/performance.md
=> Correct wrong statistics counter name in docs

pdns/dnsrecords.cc
=> report DHCID type

pdns/README-dnsdist.md, pdns/dnsdist-console.cc, pdns/dnsdist-lua2.cc, pdns/dnsdist.hh
=> dnsdist: Add `help()` and `showVersion()`

docs/markdown/authoritative/backend-bind.md
Fix incorrect anchor to Hybrid BIND-mode operation.
=> Fix broken link

docs/markdown/recursor/scripting.md
Fixes some inconsistencies / typos
=> Small documentation fix

contrib/pdnsutil.bash_completion.d
Feel free to add this simple helper to PowerDNS distribution.
=> contrib: simple bash completion for pdnsutil

pdns/dnsrecords.cc, pdns/pdnsutil.cc
=> strip trailing dot in PTR content

pdns/README-dnsdist.md, pdns/dnsdistdist/website/markdown/download.md
* in the README
* on the website's download page
=> dnsdist: Document protobuf and re2 as optional deps

docs/markdown/httpapi/README.md
=> Fix broken HTTP API example for AAAA

pdns/dnspacket.cc
Successor of #4298
Fixes: #4259
Closes: #4298
=> fix TSIG for single thread distributor

pdns/Makefile.am, pdns/rec-lua-conf.cc, pdns/recursordist/Makefile.am, pdns/recursordist/root-dnssec.hh, pdns/root-dnssec.hh, pdns/toysdig.cc
=> Move the root DNSSEC data to a header file

docs/markdown/recursor/scripting.md, pdns/lua-recursor4.cc
=> rec: Fix doc for ComboAddress/Netmask Lua bindings, add missing ones

pdns/misc.cc, pdns/test-iputils_hh.cc
Add tests for this.
Fixes: #4382
=> ComboAddress: don't allow invalid ports

docs/markdown/recursor/settings.md, pdns/pdns_recursor.cc, pdns/rec-lua-conf.cc, pdns/rec-lua-conf.hh, pdns/rec-protobuf.cc, pdns/rec-protobuf.hh
=> rec: Add an option to only send protobuf messages with a policy or tag set

pdns/lua-recursor4.cc
=> rec: Fix accessing an empty policyCustom, policyName from Lua

pdns/rec-lua-conf.cc, pdns/reczones.cc, pdns/rpzloader.hh
=> rec: Fix RPZ default policy not being applied over IXFR

docs/markdown/authoritative/dnsupdate.md, pdns/Makefile.am, pdns/common_startup.cc, pdns/lua-auth4.cc, pdns/lua-auth4.hh, pdns/packethandler.cc, pdns/packethandler.hh, pdns/rfc2136handler.cc
Adds ability to authorize DNS updates with a Lua script.
=> Update policy lua

pdns/pdns_recursor.cc
@42wim discovered that the query-local-address was not used for the
initial RPZ AXFR. However, it was used in subsequent IXFRs. It appears
that we executed the lua-config-file before checking the
query-local-address(6).
(cherry picked from commit b7ef582884c603ea45e602c3e42f254cf869d2d7)
=> Backport #4381: Parse query-local-address before lua-config-file

Makefile.am, configure.ac
=> Backport #4405: allow --without-modules

contrib/pdnsutil.bash_completion.d, pdns/pdnsutil.cc
Added change-slave-zone-master command for changing the master server(s) for a slave zone.
=> pdnsutil: Added change-slave-zone-master command

pdns/pdnsutil.cc
(cherry picked from commit af3a3769097ed43b8a1ebc623a6697f668f9f4c5)
=> pdnsutil: create-slave-zone accept multiple masters

docs/markdown/recursor/running.md
found this undocumented feature in the code.
=> Add doc about the $ feature of wipe-domain

pdns/recursordist/README.md
=> Give tarball link

modules/geoipbackend/geoipbackend.cc
(cherry picked from commit d0f81f040c6ef6dfc6d84471c084a1a86ce18e4e)
=> Backport #4442: geoipbackend: Fix minor naming issue

pdns/validate.cc, regression-tests.recursor-dnssec/test_NoDS.py
=> Rec: don't go bogus on zero configured DSs

docs/secpoll.zone
=> Send secpoll users of 3.X to the 3.X docs

build-scripts/build-auth-debian
libzmq-dev has been renamed to libzmq3-dev
=> Fix build dependencies for Ubuntu Yakkety

pdns/packethandler.cc
=> remove the suggestion of variable hiding being a problem

pdns/ws-auth.cc, regression-tests.api/test_Zones.py
=> API: url in zone info should be absolute

modules/gpgsqlbackend/spgsql.cc
(cherry-picked from master 903bb4924bc5130c0e81f0c5759d0177f53e82fd)
=> Backport #4459: plugs memory leak in postgresql backend

pdns/pdns_recursor.cc, pdns/rec-lua-conf.cc, pdns/rec_channel_rec.cc, pdns/validate-recursor.cc, pdns/validate-recursor.hh
=> Warn the user when DNSSEC related things are attempted when DNSSEC is disabled

docs/markdown/recursor/settings.md, pdns/pdns_recursor.cc, regression-tests.recursor/RPZ-Lua/expected_result, regression-tests.recursor/RPZ/expected_result
=> On RPZ customPolicy, follow the resulting CNAME

pdns/syncres.cc, regression-tests.recursor/cache-recursorcache-forward/command, regression-tests.recursor/cache-recursorcache-forward/description, regression-tests.recursor/cache-recursorcache-forward/expected_result, regression-tests.recursor/config.sh
=> Cache records for zones that were delegated to from a forwarded zone

pdns/validate.cc, regression-tests.recursor-dnssec/test_NoDS.py
=> Backport #4431: don't go bogus on zero configured DSs

build-scripts/build-auth-rpm
Make MyDNS backend rpm. Related https://github.com/PowerDNS/pdns/issues/4607
@Habbie
=> Make MyDNS backend rpm

pdns/dnsmessage.proto
(cherry picked from commit 0caa1aa850208caf18924b49e5be5ca7cdbf0515)
=> Backport #4554: Add requestorId and some comments to the protobuf definition file

docs/markdown/authoritative/dnssec.md
Fusl was confused about 'algorithm' because we use the word both for crypto algos and DS digest types.
I have:
=> a nit for Fusl

pdns/syncres.cc, pdns/syncres.hh, pdns/validate-recursor.cc, pdns/validate.cc, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_Interop.py
=> Handle CNAMEs at the apex of secure zones to other secure zones

m4/pdns_check_libcrypto_ecdsa.m4, pdns/opensslsigners.cc
=> Fix building with ECDSA support disabled in libcrypto

pdns/pdns_recursor.cc, pdns/reczones.cc, pdns/syncres.cc, pdns/syncres.hh
=> Backport #4672: On (re-)priming, fetch the root NS records

docs/markdown/authoritative/modes-of-operation.md
Clarification and Pointer to the Master/Slave Setup
Head some troubles getting all the pointers in the documentation for a working master/slave setup. I think there should be a place where all requirements are at least listed. Maybe another location or form of presentation is better, but this page and presentation is something that would have helped me.
=> Clarification and Pointer to the Master/Slave setup

build-scripts/test-recursor-bulk, build-scripts/travis.sh, m4/boost.m4
Let's be good citizens. Reported by e3amn2l.
=> Switch from HTTP to HTTPS whenever possible

build-scripts/build-recursor-rpm, pdns/dnsname.hh
=> Backport #4674: Enable protobuf in CentOS 6 packages

build-scripts/travis.sh, modules/godbcbackend/sodbc.cc, regression-tests/backends/godbc_sqlite3-master
=> backport odbc unbreaking

pdns/ws-auth.cc
According to IRC, this should fix #4621
I have:
=> According to IRC, this should fix #4621

pdns/dnsdist.cc
Since we now have response rules, it makes sense to gracefully handle exceptions in the UDP responder thread as well.
I have:
=> dnsdist: Handle exceptions in the UDP responder thread

build-scripts/travis.sh
see https://github.com/travis-ci/travis-ci/issues/6961 for the auth issue. Recursor had a binding problem.
I have:
=> conform to updated travis image

build-scripts/travis.sh
=> stop auto-started pdns with 0.0.0.0 bind, to allow individual binds

docs/manpages/pdnsutil.1.md
Documentation in the man-pages for the rectify- and secure-all-zones features. This was already included in the output of pdnsutil.
I have:
=> Add rectify- and secure-all-zones documentation

pdns/pdnsutil.cc
=> avoid undefined behaviour in clang vs. gcc

pdns/dnsdist-tcp.cc
Otherwise we might end up refusing every new TCP connection until we are restarted.
I have:
=> dnsdist: Decrement the queued TCP conn count if writing to the pipe fails

pdns/README-dnsdist.md
=> add missing letter, plus format

pdns/dnsdist-lua2.cc
=> dnsdist: Ignore newBPFFilter() and newDynBPFFilter() in client mode

pdns/pdnsutil.cc
Fix a warning reported by coverity (minor resource leak).
I have:
=> auth: Fix coverity warning in `pdnsutil show-zone`

pdns/syncres.cc, pdns/syncres.hh, pdns/validate-recursor.cc, pdns/validate.cc, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_Interop.py
Fix for #4466 for 4.0.X
I have:
=> Backport #4629:  Handle CNAMEs at the apex of secure zones to other secure zones

pdns/dnsdistdist/website/markdown/changelog.md
Remember to update the date if needed!
=> dnsdist: Update ChangeLog for 1.1.0-beta2

pdns/dnsdistdist/contrib/dnsdist.init.centos6
Because shell programming is terrible
I have:
=> Fix dnsdist initscript config check

pdns/calidns.cc
(cherry picked from commit b4f5799bf3ed50dc0146a2bbfb2c61551de0136b)
I have:
=> Backport #4686: calidns: Don't crash if we don't have enough 'unknown' queries remaining

docs/markdown/httpapi/api_spec.md
=> Add link to options of SOA-EDIT-API

docs/markdown/authoritative/backend-remote.md, modules/bindbackend/bindbackend2.hh, modules/bindbackend/binddnssec.cc, modules/geoipbackend/geoipbackend.cc, modules/geoipbackend/geoipbackend.hh, modules/luabackend/dnssec.cc, modules/luabackend/luabackend.hh, modules/luabackend/test2/pdns-luabackend.lua, modules/oraclebackend/oraclebackend.cc, modules/oraclebackend/oraclebackend.hh, modules/remotebackend/remotebackend.cc, modules/remotebackend/remotebackend.hh, modules/remotebackend/test-remotebackend.cc, pdns/backends/gsql/gsqlbackend.cc, pdns/backends/gsql/gsqlbackend.hh, pdns/dbdnsseckeeper.cc, pdns/dnsbackend.hh, pdns/pdnsutil.cc, pdns/ueberbackend.cc, pdns/ueberbackend.hh
It was unused anyway. Closes #4493
=> Remove 'kind' param in DNSBackend::getDomainKeys

contrib/ProtobufLogger.py, docs/markdown/recursor/settings.md, pdns/dnsdist-protobuf.cc, pdns/dnsmessage.proto, pdns/dnspcap2protobuf.cc, pdns/lwres.cc, pdns/lwres.hh, pdns/pdns_recursor.cc, pdns/protobuf.cc, pdns/protobuf.hh, pdns/rec-lua-conf.cc, pdns/rec-lua-conf.hh, pdns/recursordist/Makefile.am, pdns/recursordist/resolve-context.hh, pdns/resolve-context.hh, pdns/secpoll-recursor.cc, pdns/syncres.cc, pdns/syncres.hh, pdns/validate-recursor.cc, pdns/validate-recursor.hh
Also add ProtobufLogger.py, a script to display protobuf payloads
=> rec: Log outgoing queries / incoming responses via protobuf

docs/markdown/authoritative/migration.md
=> Remove b2b migrate from 3.x Docs

docs/markdown/authoritative/running.md
To have questions like #4713 documented.
I have:
=> Document disable-syslog intereaction with systemd

pdns/syncres.cc, regression-tests.recursor/auth-zones/command, regression-tests.recursor/auth-zones/expected_result
As:
1. we **are** authoritative for the zone named at the apex
2. We would servfail because we could get an upward referral
Closes #4771
I have:
=> Only delegate if NS's are below apex in auth-zones

configure.ac, m4/ax_check_link_flag.m4, m4/pdns_check_os.m4, pdns/dnsdistdist/m4/ax_check_link_flag.m4, pdns/recursordist/m4/ax_check_link_flag.m4
closes #4825
Also move the OS detection to the top
Needs testing on these platforms.
I have:
=> Check if we can link against libatomic if needed

docs/Makefile.am
=> Graceful fallback if pandoc is unavailable

docs/manpages/pdnsutil.1.md, docs/markdown/authoritative/migration.md, docs/markdown/authoritative/tsig.md, docs/markdown/httpapi/api_spec.md
Fixes  #4626
Fixes  #4637
I have:
=> Various documentation improvements

pdns/slavecommunicator.cc
(cherry picked from commit d3c9e1df6ce74dee576f81f383f4aa5decea8c62)
=> backport: handle SOAs with serial 0 correctly in incoming AXFR

pdns/recursordist/Makefile.am
=> Recursor: ship mkpubsuffixcc

pdns/dnsdistdist/.gitignore, pdns/dnsdistdist/Makefile.am
=> Fix dnsdist out-of-tree builds

pdns/recursordist/Makefile.am
Closes #4842
(cherry picked from commit 265ff1c3cb1083e1f5b4ed0ddafd200c2f27acf4)
I have:
=> Backport #4874: Recursor: ship mkpubsuffixcc

docs/markdown/recursor/settings.md, docs/markdown/recursor/upgrading.md, pdns/pdns_recursor.cc, pdns/syncres.cc, pdns/syncres.hh
Default to 40, was unlimited.
I have:
=> rec: Add `max-recursion-depth` to limit the number of internal recursion

pdns/webserver.cc
This could lead to a Denial Of Service, before we even got a chance
to check that the remote client is allowed by the ACL.
Reported by mongo (thanks!).
(cherry picked from commit a84b0d994dfc39d4379050ff9249891ed3e82f56)
I have:
=> Backport #4887: auth: Don't exit if the webserver can't accept a connection

pdns/dnsparser.cc
(cherry picked from commit b2af454119290be074fc873052d80631c5e16dce)
I have:
=> Backport #4889: auth: Correctly check unknown record content size

pdns/webserver.cc
This could lead to a Denial Of Service, before we even got a chance to check that the remote client is allowed by the ACL.
Reported by mongo (thanks!).
I have:
=> auth: Don't exit if the webserver can't accept a connection

pdns/dnsparser.cc
The existing check is subject to an integer overflow.
I have:
=> auth: Correctly check unknown record content size

pdns/Makefile.am, pdns/dnspacket.cc, pdns/dnsparser.cc, pdns/dnsparser.hh, pdns/dnssecinfra.cc, pdns/dnssecinfra.hh, pdns/ixfr.cc, pdns/misc.hh, pdns/recursordist/Makefile.am, pdns/recursordist/tsigverifier.cc, pdns/recursordist/tsigverifier.hh, pdns/resolver.cc, pdns/resolver.hh, pdns/saxfr.cc, pdns/tcpreceiver.cc, pdns/tsigverifier.cc, pdns/tsigverifier.hh
(cherry picked from commit 16c7f7823221d5d75282a77b2e9043b3f60e1ad2)
I have:
=> Backport #4893: Check TSIG signature on IXFR

pdns/dnspacket.cc, pdns/dnsparser.cc, pdns/dnsparser.hh, pdns/dnssecinfra.cc, pdns/dnssecinfra.hh, pdns/resolver.cc, pdns/tcpreceiver.cc
=> Backport #4893: auth: Fix TSIG computation

pdns/Makefile.am, pdns/dnspacket.cc, pdns/dnsparser.cc, pdns/dnsparser.hh, pdns/dnssecinfra.cc, pdns/dnssecinfra.hh, pdns/ixfr.cc, pdns/misc.hh, pdns/recursordist/Makefile.am, pdns/recursordist/tsigverifier.cc, pdns/recursordist/tsigverifier.hh, pdns/resolver.cc, pdns/resolver.hh, pdns/saxfr.cc, pdns/tcpreceiver.cc, pdns/tsigverifier.cc, pdns/tsigverifier.hh
=> Check TSIG signature on IXFR

docs/markdown/changelog.md.raw, docs/markdown/security/powerdns-advisory-2016-02.md, docs/markdown/security/powerdns-advisory-2016-03.md, docs/markdown/security/powerdns-advisory-2016-04.md, docs/markdown/security/powerdns-advisory-2016-05.md, docs/mkdocs.yml
=> Auth 3.4.11 and recursor 3.7.4 changelogs

pdns/README-dnsdist.md, pdns/dnsdist-lua2.cc, pdns/dnsdist.cc, pdns/dnsdist.hh
=> dnsdist: Add an option to 'mute' UDP responses per bind

build-scripts/build-auth-rpm
Closes #4669
Closes #4902
I have:
=> Backport #4903: Build the bind backend for CentOS 6 differently

docs/markdown/changelog.raw.md, docs/secpoll.zone
=> Add Authoritative Server 4.0.3 changelog

pdns/dnsdist.cc
improve dnsdist lua version reporting
I have:
=> report more specific lua version; report luajit

docs/markdown/authoritative/backend-ldap.md, docs/markdown/changelog.raw.md, docs/markdown/end-of-life.md, docs/process-md.sh
This PR fixes several documentation issues.
I have:
=> Documentation improvements

ext/yahttp/yahttp/yahttp-config.h
We set our include directories nowadays.
Closes #4866 (again)
I have:
=> Remove a relative import in yahttp-config.h

ext/json11/json11.cpp, ext/json11/json11.hpp
Backports `json11` fixes from upstream.
Hopefully fixes #4913.
I have:
=> Backport json11 fixes from upstream

contrib/ProtobufLogger.py, docs/markdown/recursor/settings.md, pdns/dnsdist-protobuf.cc, pdns/dnsmessage.proto, pdns/dnspcap2protobuf.cc, pdns/lwres.cc, pdns/lwres.hh, pdns/pdns_recursor.cc, pdns/protobuf.cc, pdns/protobuf.hh, pdns/rec-lua-conf.cc, pdns/rec-lua-conf.hh, pdns/recursordist/Makefile.am, pdns/recursordist/resolve-context.hh, pdns/resolve-context.hh, pdns/secpoll-recursor.cc, pdns/syncres.cc, pdns/syncres.hh, pdns/validate-recursor.cc, pdns/validate-recursor.hh
Log outgoing queries / incoming responses via protobuf.
I have:
=> Backport #3869: rec: Log outgoing queries / incoming responses via protobuf

.github/PULL_REQUEST_TEMPLATE.md
people reported being confused by this checkbox. This language improvement hopefully fixes that.
I have:
=> clarify checkbox comment

pdns/root-dnssec.hh
This add the DS for the 2017 root DNSSEC key
I have:
=> Add the 2017 root key

pdns/README-dnsdist.md
Minor dnsdist doc improvements.
I have:
=> fix some typos; improve argument references

build-scripts/travis.sh
Thus avoiding issues when/if the repository is cloned with a different name.
I have:
=> Use `${TRAVIS_BUILD_DIR}` instead of assuming the repo is in `pdns`

pdns/root-dnssec.hh
(cherry picked from commit d5037c4d34ffbc89ca5d4f79554dd87aa49fdbc8)
I have:
=> Backport #4972: Add the 2017 root key

ext/yahttp/yahttp/yahttp-config.h
We set our include directories nowadays.
Closes #4866 (again)
(cherry picked from commit 4c3c83f3bc1eecd82d09e1e527108fae98ce1fda)
I have:
=> Backport #4879: Remove a relative import in yahttp-config.h (auth)

ext/json11/json11.cpp, ext/json11/json11.hpp
(cherry picked from commit 3c20dd3b30bd0c15c5f7a1e82fba3bb5254b28df)
I have:
=> Backport #4940: Backport json11 fixes from upstream

ext/yahttp/yahttp/yahttp-config.h
We set our include directories nowadays.
Closes #4866 (again)
(cherry picked from commit 4c3c83f3bc1eecd82d09e1e527108fae98ce1fda)
I have:
=> Backport #4879: Remove a relative import in yahttp-config.h (rec)

docs/markdown/authoritative/settings.md, pdns/common_startup.cc, pdns/pdns_recursor.cc
(cherry picked from commit e12f84078798343e9749864cdeee44e68c4a81e6 and 90217d3960e3ee439405989b78fdf7e810d562f2)
I have:
=> Backport #4868: Document that carbon-server requires IP address, no hostname accepted. (auth)

docs/markdown/authoritative/settings.md, pdns/common_startup.cc, pdns/pdns_recursor.cc
(cherry picked from commit e12f84078798343e9749864cdeee44e68c4a81e6 and 90217d3960e3ee439405989b78fdf7e810d562f2)
I have:
=> Backport #4868: Document that carbon-server requires IP address, no hostname accepted. (rec)

ext/luawrapper/include/LuaContext.hpp
=> Backport #4775: LuaWrapper: Use the correct index when storing a function

pdns/recpacketcache.cc
Closes #5007
(cherry picked from commit f226db2f2c12a2c0c16b3125a0438d9aca0d017c)
I have:
=> Backport #4500: Silence a GCC 6.2 compiler warning

pdns/root-addresses.hh
http://www.internic.net/domain/db.cache
last update:    October 20, 2016
I have:
=> Backport #4603: g.root-servers.net added IPv6

build-scripts/build-auth-rpm
=> Backport #4463: build Bind backend for CentOS 6

pdns/reczones.cc
Closes #4999 
Closes #5008 
I have:
=> Backport #4794: RPZ: some logging fixes

regression-tests.recursor/RPZ-Lua/command, regression-tests.recursor/RPZ-Lua/expected_result
(cherry picked from commit 41eac9c12f28cc7a07a45ae0abe86ba390802e06)
I have:
=> Backport #4767: hide ttl in RPZ tests to avoid random failures

pdns/dnsbackend.hh, pdns/dnsname.hh, pdns/lua-recursor4.cc, pdns/lwres.hh, pdns/nsecrecords.cc, pdns/pdns_recursor.cc, pdns/rec-lua-conf.cc, pdns/rec_channel_rec.cc, pdns/remote_logger.cc, pdns/remote_logger.hh, pdns/resolver.hh, pdns/rpzloader.cc, pdns/syncres.cc, pdns/validate.cc, pdns/webserver.cc, pdns/ws-api.cc
This doesn't fix any real issue, just a minor clean up to try preventing future ones:
* remove some leftovers
* fix shadowed variables (reported by -Wshadow)
* make sure labelsToAdd is not empty in getZoneCuts()
* explicitly use const iterators in validateWithKeySet and getKeysFor
I have:
=> backport #4917: rec: Clean up, fix compiler warnings

pdns/pdnsutil.cc
Fix a warning reported by coverity (minor resource leak).
(cherry picked from commit 0944e3fc8333686767678eadb80fb0236fdc5fba)
I have:
=> backport #4746: auth: Fix coverity warning in `pdnsutil show-zone`

pdns/pdns_recursor.cc, pdns/qtype.cc, pdns/rcpgenerator.cc, pdns/rec_control.cc, pdns/receiver.cc, pdns/recursordist/README.md, pdns/reczones.cc, pdns/resolver.cc, pdns/slavecommunicator.cc, pdns/sodcrypto.cc, pdns/statbag.cc, pdns/syncres.cc, pdns/test-dnscrypt_cc.cc, pdns/test-dnsdist_cc.cc, pdns/ueberbackend.cc, pdns/unix_semaphore.cc, pdns/unix_utility.cc, pdns/version.cc, pdns/webserver.cc, pdns/ws-api.cc, pdns/ws-auth.cc, pdns/ws-recursor.cc, pdns/zone2json.cc, pdns/zone2sql.cc, pdns/zoneparser-tng.cc
Updates the copyright date in several files to 2017 and adds the 'default' copyright header to files that were missed in #4163.
I have:
=> Update copyright for several files

modules/godbcbackend/sodbc.cc
godbc query logging was not working correctly. Now it does.
I have:
=> fix godbc query logging

modules/geoipbackend/geoipbackend.cc, modules/gpgsqlbackend/spgsql.cc, modules/ldapbackend/ldapbackend.cc, modules/luabackend/minimal.cc, modules/remotebackend/unixconnector.cc, pdns/communicator.hh, pdns/dbdnsseckeeper.cc, pdns/dnsdist-cache.cc, pdns/dnsdist-tcp.cc, pdns/dnspacket.cc, pdns/packetcache.cc, pdns/rfc2136handler.cc
Our internal Coverity reported minor issues / inefficiencies:
* Exceptions not handled in destructors
* members not properly initialized or copied, fine with the current code but let's prevent future issues
* Signed / unsigned conversion, one useless allocation
I have:
=> Minor fixes based on Coverity's report

m4/boost.m4
This prevents the "Unable to figure out toolset name" warning
I have:
=> Add GCC 6.3 to boost.m4

docs/markdown/authoritative/dnsupdate.md
=> Update version number for Lua updatePolicy

modules/godbcbackend/sodbc.cc
backport #5051 to 4.0.x
I have:
=> backport #5051: fix godbc query logging (cherry-pick of d2bc6b2)

pdns/Makefile.am, pdns/dnsdistdist/Makefile.am, pdns/recursordist/Makefile.am
=> Indicate that dnslabeltext.cc is generated

regression-tests.dnsdist/requirements.txt
=> dnsdist: pysnmp4.3.4 fix compatibility problems with pyasn1

docs/markdown/authoritative/performance.md
=> auth: Document that the cache respect the answer's TTL

docs/markdown/authoritative/howtos.md
=> Docs: modernize the 'database' howto somewhat

docs/markdown/authoritative/backend-pipe.md
This makes the * in these wildcards visible, and drops the weird italics.
I have:
=> escape markdown formatting chars

docs/markdown/recursor/settings.md
rec: enhance documentation by adding/correcting 'Available since'-tags for the diversity of available options
=> rec: enhance documentation

pdns/ws-auth.cc
Pretty up auth webserver output. Closes #1844.
I have:
=> Close #1844: we report 1200 qps as 1.2e3 qps in auth webserver.

pdns/arguments.cc, pdns/iputils.hh, pdns/nproxy.cc, pdns/pdns_recursor.cc, pdns/qtype.cc
=> Fix minor issues reported by `cppcheck`

pdns/pdnsutil.cc
=> for create-slave-zone, actually add all slaves, and not only first n times

pdns/README-dnsdist.md
I've been confused a few times by the TCP bool on these functions. Clarify it.
I have:
=> clarify that UDP is always there

docs/markdown/appendix/backend-writers-guide.md
=> doc: Document empty non-terminal in backends

docs/markdown/authoritative/backend-bind.md
=> Docs: version since native is supported in BIND

pdns/signingpipe.cc
If an exception is thrown during the signing, the worker thread needs to delete the current chunk, otherwise the corresponding memory is lost.
I have:
=> auth: Don't leak on signing errors during outgoing AXFR

pdns/arguments.cc, pdns/iputils.hh, pdns/nproxy.cc, pdns/pdns_recursor.cc, pdns/qtype.cc
(cherry picked from commit d7c676a5d42d5d7e5078a8662d355c9a782bdb51)
I have:
=> Backport #5101: Fix minor issues reported by `cppcheck`

modules/geoipbackend/geoipbackend.cc, modules/gpgsqlbackend/spgsql.cc, modules/ldapbackend/ldapbackend.cc, modules/luabackend/minimal.cc, modules/remotebackend/unixconnector.cc, pdns/communicator.hh, pdns/dbdnsseckeeper.cc, pdns/dnsdist-cache.cc, pdns/dnsdist-tcp.cc, pdns/dnspacket.cc, pdns/packetcache.cc, pdns/rfc2136handler.cc
Our internal Coverity reported minor issues / inefficiencies:
* Exceptions not handled in destructors
* members not properly initialized or copied, fine with the current code but let's prevent future issues
* Signed / unsigned conversion, one useless allocation
I have:
=> Backport 5049: Minor fixes based on Coverity's report

pdns/arguments.cc, pdns/iputils.hh, pdns/nproxy.cc, pdns/pdns_recursor.cc, pdns/qtype.cc
(cherry picked from commit d7c676a5d42d5d7e5078a8662d355c9a782bdb51)
I have:
=> Backport #5101: rec-4.0.x: Fix minor issues reported by `cppcheck`

build-scripts/travis.sh, regression-tests/backends/bind-master, regression-tests/backends/gsql-common, regression-tests/tests/ent-asterisk/description, regression-tests/tests/ent-asterisk/expected_result.dnssec
unbreak testing on machines with fresh unbound
I have:
=> Backport 4839

docs/markdown/authoritative/howtos.md, docs/markdown/authoritative/settings.md, pdns/common_startup.cc, pdns/packethandler.cc, pdns/packethandler.hh, regression-tests/backends/gsql-common
=> ALIAS: disable expansion by default

docs/markdown/authoritative/backend-generic-postgresql.md
=> Fix wrong launch/module name in PostgreSQL 4.x auth docs

pdns/test-recpacketcache_cc.cc
Add unit tests checking that the packet cache stores and returns different answers for different tags, for the same query.
I have:
=> rec: Add unit tests for the packet cache tags handling

pdns/README-dnsdist.md
We did not document well what validFrom and validTo were supposed to be.
I have:
=> small documentation fix for dnsdist DNSCrypt

build-scripts/debian-dnsdist/control.in
=> Fix typo in control file for dnsdist

m4/boost.m4
add gcc/g++ 5.4 detection to boost.m4, need to upstream this to tsuna, and backport it to the 4.x branches.
I have:
=> detect gcc/g++ 5.4

regression-tests.dnsdist/test_DynBlocks.py
Hopefully it will help understand what's going on with the frequent failures on Travis.
I have:
=> dnsdist: Add some debug to the DynBlocks regression tests

regression-tests.dnsdist/.gitignore
ignore `dnsmessage_pb2.py` as it is a generated file.
I have:
=> ignore file created by runtests

pdns/ascii.hh, pdns/misc.hh, pdns/rcpgenerator.cc, pdns/zoneparser-tng.cc
dns_isspace() and dns_toupper() are all functions operating upon ASCII
characters. So lets move them into ascii.hh and keep them together with
dns_tolower()
=> move two other functions into ascii.hh

docs/markdown/authoritative/backend-geoip.md, modules/geoipbackend/geoipbackend.cc, modules/geoipbackend/geoipbackend.hh
geoipbackend: Add support for %cc modifier, fixes #4122
I have:
=> geoipbackend: Add support for %cc modifier

modules/geoipbackend/geoipbackend.cc, modules/geoipbackend/geoipbackend.hh
Fixes #4704 by applying weights consistently on all lookups.
I have:
=> geoipbackend: Move static record lookup to separate method

pdns/README-dnsdist.md
=> dnsdist: Clarify that addPoolRule() applies to source addresses

build-scripts/test-auth
Should fix the auth test in buildbot: https://builder.powerdns.com/#/builders/45/builds/1245
I have:
=> Tell the tests where to find zone2json

pdns/syncres.cc
(cherry picked from commit 129bb0c322b6a20860c14f0b1bcfcad2bd586389)
I have:
=> Backport #5283: rec: Skip DNSSEC validation for cache hits from authoritative zones

m4/boost.m4
=> detect gcc/g++ 5.4, 7.0 and 7.1 in boost.m4

regression-tests/tests/nsecx-upcase/command, regression-tests/tests/nsecx-upcase/description, regression-tests/tests/nsecx-upcase/expected_result, regression-tests/tests/nsecx-upcase/expected_result.narrow, regression-tests/tests/nsecx-upcase/expected_result.nsec3
=> auth: add test to make sure NSEC(3) generation is case insensitive

pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc
The `OOB` was not correctly set for cache hits for data coming from authoritative zones. Since we disable `DNSSEC` validation for `OOB` data, this led to `DNSSEC` validation failures in some cases.
I have:
=> rec: Skip DNSSEC validation for cache hits from authoritative zones

docs/markdown/authoritative/dnsupdate.md, docs/markdown/authoritative/domainmetadata.md, pdns/rfc2136handler.cc, regression-tests.nobackend/counters/command, regression-tests.nobackend/counters/expected_result
Backport of pull #5264
I have:
=> Notify dnsupdate backport

modules/remotebackend/unixconnector.cc
Inspired by the comments in #5306, although I doubt it'll help.
I have:
=> auth: Don't copy data around when sending and receiving in the Unix Connector

ext/yahttp/yahttp/cookie.hpp, ext/yahttp/yahttp/exception.hpp, ext/yahttp/yahttp/reqresp.cpp, ext/yahttp/yahttp/reqresp.hpp, ext/yahttp/yahttp/router.cpp, ext/yahttp/yahttp/url.hpp, ext/yahttp/yahttp/utility.hpp, ext/yahttp/yahttp/yahttp.hpp
Backport changes from upstream up to c5b83288a4c2f8ec07cb8cb7bd150f2210db67b6
"Add missing `YaHTTP::isdigit()`, fix locale-enabled versions"
I have:
=> rec-4.0.x: YaHTTP: Sync with upstream changes

ext/yahttp/yahttp/cookie.hpp, ext/yahttp/yahttp/exception.hpp, ext/yahttp/yahttp/reqresp.cpp, ext/yahttp/yahttp/reqresp.hpp, ext/yahttp/yahttp/router.cpp, ext/yahttp/yahttp/url.hpp, ext/yahttp/yahttp/utility.hpp, ext/yahttp/yahttp/yahttp.hpp
Backport changes from upstream up to c5b83288a4c2f8ec07cb8cb7bd150f2210db67b6
"Add missing `YaHTTP::isdigit()`, fix locale-enabled versions"
I have:
=> auth-4.0.x: YaHTTP: Sync with upstream changes

docs/markdown/changelog.raw.md, docs/secpoll.zone
The changelog for 4.0.5.
I have:
=> Recursor 4.0.5-RC1 changelog

pdns/dnsdist-lua.cc, pdns/dnsdist-lua2.cc
Print a friendly error message if you pass a `DNSResponseAction` to `addRule()`, or a `DNSAction` to `addResponseRule()` instead of a cryptic error.
I have:
=> dnsdist: Print useful messages when query and response actions are mixed

pdns/recursordist/test-ednsoptions_cc.cc
In order to prevent an issue like #5320 from coming back.
I have:
=> rec: Add unit tests for EDNS Client Subnet truncation

pdns/mtasker.cc, pdns/mtasker.hh, pdns/pdns_recursor.cc, pdns/rec_channel_rec.cc
=> rec: Mark MT methods as const whenever possible

docs/markdown/recursor/settings.md, modules/remotebackend/Makefile.am, pdns/Makefile.am, pdns/ednssubnet.cc, pdns/ednssubnet.hh, pdns/iputils.cc, pdns/iputils.hh, pdns/lua-recursor4.cc, pdns/pdns_recursor.cc, pdns/recursordist/Makefile.am, pdns/recursordist/ecs.cc, pdns/syncres.cc, pdns/syncres.hh
=> rec-4.0.x: Backport #4924 and #4988

docs/markdown/changelog.raw.md
Also, order the items somewhat and add additional information
I have:
=> Add the Recursor 4.0.5 rc 2 changelog

build-scripts/travis.sh, pdns/speedtest.cc
=> auth: build all tools in travis and fix speedtest build

pdns/dnsname.hh, pdns/lua-auth4.cc, pdns/pdnsutil.cc, pdns/slavecommunicator.cc, pdns/tcpreceiver.cc, regression-tests/backends/gmysql-master, regression-tests/tests/nsec-upcase/command, regression-tests/tests/nsec-upcase/description, regression-tests/tests/nsec-upcase/expected_result, regression-tests/tests/nsec-upcase/expected_result.narrow, regression-tests/tests/nsec-upcase/expected_result.nsec3
Make sure NSEC ordernames are always lower case.
Fixes #5370 and a few other case related NSEC bugs.
I have:
=> NSEC fixes

modules/luabackend/luabackend.hh, modules/luabackend/minimal.cc, modules/opendbxbackend/odbxbackend.cc, modules/opendbxbackend/odbxbackend.hh, modules/opendbxbackend/odbxprivate.cc, pdns/dbdnsseckeeper.cc, pdns/dnsname.hh, pdns/dnsseckeeper.hh, pdns/lua-auth.cc, pdns/packethandler.cc, pdns/pdnsutil.cc, pdns/slavecommunicator.cc, pdns/tcpreceiver.cc, pdns/ueberbackend.cc, pdns/ueberbackend.hh, regression-tests/backends/gmysql-master, regression-tests/tests/nsec-upcase/command, regression-tests/tests/nsec-upcase/description, regression-tests/tests/nsec-upcase/expected_result, regression-tests/tests/nsec-upcase/expected_result.narrow, regression-tests/tests/nsec-upcase/expected_result.nsec3
Beckport of:
#5373, #5377 and #5384 (opendbx and lua backend fix)
I have:
=> Backports to rel/auth-4.0.x

m4/boost.m4
Small last update before the 4.0.5 release
I have:
=> Sync boost.m4 from master

docs/markdown/changelog.raw.md, docs/secpoll.zone
=> Update docs and secpoll for auth 4.0.4 rc1

docs/markdown/changelog.raw.md, docs/secpoll.zone
=> Update docs and secpoll for Recursor 4.0.5

pdns/dnssecinfra.hh, pdns/sodiumsigners.cc
=> Backport of #5422 do not hash the message in the ed25519 signer

m4/pdns_check_os.m4
=> unbreak quoting; fixes #5401

pdns/README-dnsdist.md
This addresses #5433, which featured a user attempting to create 30k rules.
Documentation update
I have:
=> Document that rules are not for creating by the thousands

configure.ac, m4/pdns_check_libdecaf.m4, pdns/Makefile.am, pdns/dbdnsseckeeper.cc, pdns/decafsigners.cc, pdns/dnssecinfra.cc, pdns/dnsseckeeper.hh, pdns/pdnsutil.cc, pdns/recursordist/Makefile.am, pdns/recursordist/configure.ac, pdns/recursordist/decafsigners.cc, pdns/recursordist/m4/pdns_check_libdecaf.m4, pdns/test-signers.cc, pdns/version.cc
PowerDNS libdecaf signers
```
Testing algorithm 15: 'Decaf ED25519' ->'Decaf ED25519' -> 'Decaf ED25519' Signature & verify ok, signature 68usec, verify 93usec
Testing algorithm 16: 'Decaf ED448' ->'Decaf ED448' -> 'Decaf ED448' Signature & verify ok, signature 163usec, verify 252usec
```
I have:
=> hello decaf signers (ED25519 and ED448)

build-scripts/build-auth-rpm
=> add 3.4.0_to_4.1.0_schema.mysql.sql to backend-mysql rpm

build-scripts/travis.sh, modules/remotebackend/Gemfile.lock
=> install fakeroot and bump json gem version, for new travis image

configure.ac, m4/pdns_check_libdecaf.m4, pdns/Makefile.am, pdns/dbdnsseckeeper.cc, pdns/decafsigners.cc, pdns/dnssecinfra.cc, pdns/dnsseckeeper.hh, pdns/pdnsutil.cc, pdns/test-signers.cc, pdns/version.cc
Backport of #5427 + #5437 
I have:
=> Backport decaf signer

m4/pdns_check_libdecaf.m4, pdns/Makefile.am, pdns/dbdnsseckeeper.cc, pdns/decafsigners.cc, pdns/dnssecinfra.cc, pdns/dnsseckeeper.hh, pdns/pdnsutil.cc, pdns/recursordist/Makefile.am, pdns/recursordist/configure.ac, pdns/recursordist/decafsigners.cc, pdns/recursordist/m4/pdns_check_libdecaf.m4, pdns/test-signers.cc, pdns/version.cc
Backport of #5427 + #5437
I have:
=> Rec 4.0.x: backport decaf signer

pdns/pdns_recursor.cc
`rfc6891`' states in section 6.2.3 that 
> [a requestor's payload] lower than 512 MUST be treated as equal to 512
Fixes #5407.
I have:
=> rec: Treat requestor's payload size lower than 512 as equal to 512

docs/markdown/changelog.raw.md, docs/secpoll.zone
=> Authoritative Server 4.0.4 changelog and secpoll

docs/markdown/authoritative/backend-lua.md
=> remove broken link; clarify status

docs/markdown/recursor/scripting.md
=> Doc: Fix a typo in the recursor's scripting documentation

docs/markdown/common/logging.md
`Carbon` is documented but I forgot to add mention of `SNMP` to that page.
I have:
=> Mention the recursor's SNMP support in logging.md

build-scripts/travis.sh
(cherry picked from commit dad54543abf80aedefbe47f1d538542763794173)
I have:
=> Backport 5455: Travis: Use auth 4.0 for recursor tests

pdns/root-addresses.hh
http://www.internic.net/domain/db.cache
last update:    June 01, 2017
the addr change is effective since 2017-06-01
I have:
=> rec: changed IPv6 addr of b.root-servers.net

pdns/recursor_cache.cc, pdns/recursor_cache.hh
The existing name doesn't make it clear it only indexes netmask-specific entries.
I have:
=> rec: Rename the ECS cache index and add a comment on how it works

pdns/rec_channel_rec.cc, pdns/syncres.cc, pdns/syncres.hh
Keep metrics: ecs-queries, ecs-responses.
I have:
=> Ecs stats: some fun metrics

regression-tests.recursor-dnssec/clientsubnetoption.py, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_ECS.py
=> rec: Add ECS regression tests

pdns/root-addresses.hh
=> Backport #4497 and #5470: Add E and B root IPv6 addresses

pdns/cachecleaner.hh, pdns/recursor_cache.cc
(cherry picked from commit 197d755)
I have:
- [] compiled and tested this code
=> rec: Backport #5416: Move expired cache entries to the front so they are expunged

regression-tests.recursor-dnssec/test_ECS.py
In order to prevent future issues like the one fixed by #5403.
I have:
=> rec: Add ECS scope handling by the cache to our regression tests

ext/json11/json11.cpp, ext/json11/json11.hpp
(cherry picked from commit 3c20dd3b30bd0c15c5f7a1e82fba3bb5254b28df)
Fixes #5458.
I have:
=> auth-4.0.x: Backport #4940: Backport json11 fixes from upstream

docs/markdown/changelog.raw.md, docs/markdown/recursor/upgrading.md, docs/secpoll.zone
=> changelog+secpoll for recursor 4.0.6

docs/MIBS/DNSDIST-MIB.txt, pdns/dnsdist-snmp.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistconf.lua, regression-tests.dnsdist/test_API.py, regression-tests.dnsdist/test_Basics.py, regression-tests.dnsdist/test_CheckConfig.py, regression-tests.dnsdist/test_SNMP.py
Closes #5513 
Note: not in the changelog yet.
I have:
=> dnsdist: Remove BlockFilter

pdns/README-dnsdist.md
=> dnsdist: Clarify that NetmaskGroupRule can match the destination

pdns/dnsdistdist/Makefile.am
=> dnsdist docs: Ensure pip and setup tools are updated when building docs.

pdns/syncres.cc
Fix DNSSEC validation for `irc.oftc.net`, where the AA=1 answer contains the `CNAME` plus the referral for the `CNAME` target, which is of course not covered by any `RRSIG`:
```
$ dig NS irc.oftc.net @89.16.189.59 +dnssec
; <<>> DiG 9.11.1-P3 <<>> NS irc.oftc.net @89.16.189.59 +dnssec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32123
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 6, ADDITIONAL: 17
;; WARNING: recursion requested but not available
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;irc.oftc.net.                  IN      NS
;; ANSWER SECTION:
irc.oftc.net.           14400   IN      CNAME   irc.geo.oftc.net.
irc.oftc.net.           14400   IN      RRSIG   CNAME 8 3 14400 20170808153120 …
```
=> rec: On an AA=1 CNAME answer, only the CNAME is necessarily authoritative

pdns/secpoll-auth.cc, pdns/secpoll-recursor.cc
=> Fix typo in two log messages

pdns/recursordist/Makefile.am, pdns/recursordist/RECURSOR-MIB.txt, pdns/recursordist/docs/changelog/4.1.rst, pdns/recursordist/docs/lua-config/protobuf.rst, pdns/recursordist/docs/lua-scripting/hooks.rst, pdns/recursordist/docs/lua-scripting/statistics.rst, pdns/recursordist/powerdns-example-script.lua
* Add MIB to docs
* Update some functions based on the changelog
* Update the changelog for 4.1.0
I have:
=> Recursor documentation additions

ext/yahttp/yahttp/reqresp.hpp, ext/yahttp/yahttp/router.hpp
Fix a warning reported by Coverity.
I have:
=> Update YaHTTP to 93e75d1412d7dafab54f68b7efb9a4e30fd8b9fe

pdns/dnsdist-console.cc
=> dnsdist: Add completion for `setStaleCacheEntriesTTL()`

pdns/dnsdist-lua.cc
=> dnsdist: Skip timeouts on the response latency graph

pdns/dnsdistconf.lua
Remove default passwords and console keys from the sample configuration file, to lower the risk of someone copy/pasting it into production.
I have:
=> dnsdist: Make it clear that the sample passwords should be changed

pdns/dnsdistdist/docs/advanced/ecs.rst, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/docs/statistics.rst
=> dnsdist: Fix small typos

pdns/dnsdistdist/docs/guides/carbon.rst, pdns/dnsdistdist/docs/guides/index.rst, pdns/dnsdistdist/docs/reference/carbon.rst, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/docs/reference/index.rst, pdns/dnsdistdist/docs/statistics.rst
That part had gone MIA during the move to the new documentation format!
I have:
=> dnsdist: Document sending statistics to carbon in the new docs

pdns/dnsdistdist/docs/guides/cache.rst
=> add dontAge to packetcache guide

pdns/recursordist/docs/changelog/4.1.rst, pdns/recursordist/docs/lua-config/protobuf.rst
=> Two recursor doc fixes

pdns/dnsdistdist/docs/guides/serverselection.rst, pdns/dnsdistdist/docs/reference/config.rst
Hopefully fixes the confusion reported in #2946. 
I have:
=> dnsdist: Clarify how the different load-balancing policies work

pdns/recursordist/README.md
=> cd to the right directory before compiling

pdns/test-packetcache_cc.cc
=> increase TTL in packet cache test to avoid failure on slow testing runs

build-scripts/build-auth-rpm, m4/pdns_check_virtualenv.m4
This fixes 2 issues with building RPMs and detecting auth manpages properly.
I have:
=> Fix errors with our build scripts

docs/Makefile.am, docs/domainmetadata.rst
=> auth documentation nits

modules/mydnsbackend/mydnsbackend.cc
=> mydnsbackend: Initialize d_query_stmt

m4/pdns_check_os.m4
Thanks @tjikkun!
Closes #5456
I have:
=> Fix libatomic detection on ppc64

build-scripts/build-auth-debian, build-scripts/build-dnsdist-debian, build-scripts/build-recursor-debian
Adds a missing command from the changes in #5593.
I have:
=> Buildscripts: move deb files to correct dir

m4/ax_arg_default_enable_disable.m4, m4/systemd.m4
=> Add help text on autodetecting systemd support

pdns/recursor_cache.cc
=> rec: Add missing cinttypes include for PRId64

pdns/ueberbackend.cc, regression-tests/tests/ds-at-parent/command, regression-tests/tests/ds-at-parent/description, regression-tests/tests/ds-at-parent/expected_result
=> lookups one level (or more) below apex did confuse getAuth() for qytpe DS

docs/guides/recursion.rst
=> Fix dnsdist install link in auth docs

pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Document the Truncate option to `setDynBlocksAction()`

build-scripts/travis.sh
Thus avoiding issues when/if the repository is cloned with a different
name.
(cherry picked from commit 1e0253cad96199647f92ef4fa8230f614637e80c)
I have:
=> Backport #4986: Use `${TRAVIS_BUILD_DIR}` instead of assuming the repo is in `pdns`

pdns/dnsdist-ecs.cc
This can lead to a DoS on 32 bits if a backend server sends a crafted response and we happen to be working with a buffer allocated to a very high virtual address.
Reported by Guido Vranken (many thanks!).
I have:
=> dnsdist: Fix potential pointer wrap-around on 32 bits

pdns/dnsdist-web.cc, regression-tests.dnsdist/test_API.py
All paths were accessible to a user authenticated with Basic Authentication, instead of being only accessible with an API key.
I have:
=> dnsdist: Make the API available with an API key only

build-scripts/travis.sh
=> rec: Display the content of the testrunner logs in case of failure

pdns/pdns_recursor.cc, pdns/recursordist/docs/settings.rst, pdns/reczones.cc, pdns/rpzloader.hh
To be able to log changes made to a `RPZ` zone more easily.
I have:
=> rec: Add `log-rpz-changes` to log RPZ additions and removals

docs/appendices/EOL.rst, docs/backends/generic-sql.rst, docs/dnsupdate.rst, docs/domainmetadata.rst, docs/http-api/endpoint-zones.rst, docs/http-api/zone-properties.rst, docs/index.rst, docs/upgrading.rst, pdns/dnsdistdist/docs/index.rst, pdns/recursordist/docs/appendices/EOL.rst, pdns/recursordist/docs/index.rst
All kinds of small fixes.
Related issues:
- #5329 
- #2165 
- #3895 
- #4129 
- #4151
I have:
=> Assorted documentation fixes

build-scripts/test-auth, build-scripts/travis.sh, modules/luabackend/test2/.gitignore, modules/luabackend/test2/pdns, modules/luabackend/test2/pdns-luabackend.lua, modules/luabackend/test2/pdns.conf
=> Fix and hook up luabackend tests

docs/changelog/4.1.rst, docs/secpoll.zone
This is an update for the ChangeLog for the Authoritative Server for the upcoming 4.1.0 release.
=> auth: Update the ChangeLog for 4.1.0.

pdns/recursordist/README.md, pdns/version.cc, pdns/ws-auth.cc
This is a backport of commit ff8f70b800e8b81a6d97c2d2568483d03228df2a to the rel/rec-4.0.x branch.
I have:
=> Update copyright year in publicly visible output and files

pdns/recursordist/README.md, pdns/version.cc, pdns/ws-auth.cc
This is a backport of commit ff8f70b800e8b81a6d97c2d2568483d03228df2a to the rel/auth-4.0.x branch.
I have:
=> Feature/update copyright year auth 4.0.x

pdns/recursordist/test-syncres_cc.cc, pdns/validate.cc
=> rec: Handle NSEC wrap-around

docs/common/api/statisticitem.rst, docs/common/api/zone.rst, docs/conf.py, docs/http-api/index.rst, docs/http-api/zone.rst, docs/modes-of-operation.rst, docs/performance.rst, docs/upgrading.rst, pdns/dnsdistdist/docs/reference/config.rst, pdns/recursordist/docs/changelog/4.0.rst, pdns/recursordist/docs/conf.py, pdns/recursordist/docs/http-api/index.rst, pdns/recursordist/docs/http-api/zone-properties.rst, pdns/recursordist/docs/http-api/zone.rst, pdns/recursordist/docs/lua-scripting/hooks.rst, pdns/recursordist/docs/settings.rst
=> Fix some doc nits

pdns/dnsrecords.cc
=> be more specific about trailing dot handling, fixes #5673

pdns/recursordist/docs/lua-scripting/hooks.rst
=> gettag doc nits

m4/boost.m4
=> boost.m4: detect gcc 7.2

docs/guides/recursion.rst
=> doc nit: s/seperate/separate/

pdns/secpoll-auth.cc
=> remove "" around secpoll result. Fixes #5692

pdns/dnsdistdist/docs/reference/netmaskgroup.rst
=> dnsdist: Fix NetmaskGroup NGM -> NMG typo in the doc

pdns/zoneparser-tng.cc, regression-tests/zones/unit.test
This adds the requested unit test to PR #5667.
**Question for reviewers**: in the unit test only check for QType and content or keeps all checks?
Closes #5667.
Closes https://github.com/PowerDNS/pdns/issues/4703.
I have:
- both before and after the fix (so before the new unit test fails and after it passes)
=> Unit test for AFSDB fix (PR #5667)

pdns/dnsdistdist/docs/rules-actions.rst
=> dnsdist: Fix typo in the documentation QnameRule -> QNameRule

docs/upgrading.rst
Adds a short note on the new LDAP record types and that the user possibly has to update LDAP schema.
Closes #5690.
I have:
=> Add note on updating LDAP schema.

pdns/syncres.cc, pdns/validate.cc
This is a follow-up on 5716.
Closes #5747.
I have:
=> rec: Check that the owner name is part of the signer in getDenial

pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc
The target zone being insecure doesn't mean that the denial of the DS is too, if the parent zone is Secure.
I have:
=> rec: For DS queries, only the cuts down to the parent matter

.travis.yml
=> Remove failing mongodb source from travis

docs/upgrading.rst, m4/pdns_check_libsodium.m4, pdns/recursordist/docs/upgrade.rst
Found by @mind04.
Also add upgrade docs.
I have:
=> Fix libsodium autodetect without libsodium

pdns/dnsdist.cc
=> fix azerty typo

docs/secpoll.zone
=> add rec-4.1.0-alpha1 to secpoll

pdns/rec-carbon.cc, pdns/ws-recursor.cc
The carbon & webserver API mthreads get improved logging with this PR.
I have:
=> improve logging of errors in carbon & web services thread

.travis.yml
=> Encrypt the IRC channel name so notifications are not sent for forks

pdns/recursordist/docs/manpages/rec_control.rst
=> rec_control manpage: fix spelling error found by lintian

build-scripts/test-recursor-bulk, build-scripts/travis.sh, regression-tests/recursor-test
=> Backport #5755: Improve dnsbulktest experience in travis for more robustness

.travis.yml
(cherry picked from commit f4614876f16ac3223786b26b18a4386045102f09)
I have:
=> Backport #5802: Encrypt the IRC channel name so notifications are not sent for forks

docs/appendices/compiling.rst, docs/appendices/crypto-export.rst, docs/appendices/types.rst, docs/backends/bind.rst, docs/backends/generic-postgresql.rst, docs/backends/index.rst, docs/common/tarball-pgp-keys.rst, docs/dnssec/modes-of-operation.rst, docs/dnssec/operational.rst, docs/dnsupdate.rst, docs/http-api/endpoint-zones.rst, pdns/dnsdistdist/docs/install.rst, pdns/recursordist/docs/appendices/compiling.rst, pdns/recursordist/docs/appendices/crypto-export.rst, pdns/recursordist/docs/metrics.rst, pdns/recursordist/docs/settings.rst
Fixes the following issues:
* #5724 
* #5728 
* #5688 
* #5714 
* #5635 
* #5790 
I have:
=> Fix a bunch of documentation nits

pdns/common_startup.cc
Either of these config settings may be empty
Closes #5809
I have:
=> Auth: Don't warn on empty default-{k,z}sk-algorithm

.travis.yml
It looks like we don't need any of them and they fail often enough that this is an inconvenience.
Supersedes #5831 (if travis passes :) ).
I have:
=> Remove all custom repositories

pdns/root-addresses.hh
The IP of b.root-servers.net has changed.
I have:
=> b.root renumbering, effective 2017-10-24

docs/settings.rst
=> docs: clarify settings for allow-dnsupdate-from

docs/dnsupdate.rst
=> dnsupdate default for allow-dnsupdate-from

docs/dnsupdate.rst
Example use of `pdnsutil generate-tsig-key`
I have:
closes https://github.com/PowerDNS/pdns/issues/5850
=> Show use of pdnsutil generate-tsig-key

docs/settings.rst
=> fix markup for warning

pdns/dnsdistdist/docs/guides/console.rst
=> dnsdist: fix console connection guide

pdns/dnsdist-console.cc
Be nice and accept plain `help` too. Fixes #4845.
I have:
=> dnsdist: accept help for help()

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.1.rst, pdns/recursordist/docs/metrics.rst
Update the ChangeLog and secpoll for Recursor 4.1.0 RC2.
=> Update the ChangeLog and secpoll for Recursor 4.1.0 RC2.

modules/remotebackend/.bundle/config
This should fix the auth tests from failing at the "checking dirtyness of the git repo" step.
(cherry picked from commit 664135769af13364a4de0ed9e3efc6cd281a52b2)
I have:
=> Make travis happy

pdns/dbdnsseckeeper.cc
One step toward fixing #3267 in 4.2.0
I have:
=> auth: Warn about algo 5 -> 7 upgrade in log

pdns/tcpreceiver.cc
Successor of #5767 
Remove some complexity from the the outbound AXFR nsec3 code.
Closes #5767 
I have:
=> auth: stop doing individual RRSIG queries during outbound AXFR

docs/changelog/4.1.rst, docs/secpoll.zone
Update ChangeLog and secpoll for Auth 4.1.0 RC2.
=> Update ChangeLog and secpoll for auth-4.1.0-rc2.

pdns/dnsdistdist/.gitignore, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/docs/advanced/index.rst, pdns/dnsdistdist/docs/advanced/multiple-instance.rst
Add multi-instance systemd unit file for dnsdist and some documentation about the usage.
I have:
=> Add multi-instance unit file

pdns/pdnsutil.cc
Also, fix indenting for the `generate-tsig-key` block.
Closes #5849 
I have:
=> pdnsutil: Fix messages created by generate-tsig-key

regression-tests.dnsdist/dnsdisttests.py, regression-tests.dnsdist/test_AXFR.py, regression-tests.dnsdist/test_EdnsClientSubnet.py, regression-tests.dnsdist/test_Protobuf.py, regression-tests.dnsdist/test_Routing.py, regression-tests.dnsdist/test_TeeAction.py, regression-tests.dnsdist/test_Trailing.py
=> dnsdist: Add regression tests for TeeAction

pdns/pdns_recursor.cc
=> rec: Add EDNS to truncated, servfail answers

modules/remotebackend/.bundle/config
(cherry picked from commit 664135769af13364a4de0ed9e3efc6cd281a52b2)
I have:
=> Make travis happy on rel/auth-4.0.x

pdns/dbdnsseckeeper.cc, pdns/dnsseckeeper.hh, pdns/pdnsutil.cc, pdns/ws-auth.cc
=> auth: Add back missing output details to rectifyZone

pdns/recursordist/Caddyfile, pdns/recursordist/html/index.html, pdns/recursordist/html/js/handlebars-v4.0.11.js, pdns/recursordist/html/lines.css, pdns/recursordist/html/local.js, pdns/recursordist/html/styling.css
Cleanup the recursor web UI:
- Switch to Handlebars templating
- Slightly cleaner look
- Slightly cleaner and more mobile friendly HTML
I have:
=> rec: cleanup web UI

pdns/recursordist/test-syncres_cc.cc
Add some unit tests for the validation of cached CNAMEs as a follow-up to #5904, since we retrieve these separately from the regular cached entries.
I have:
=> rec: Add unit tests for DNSSEC validation of cached CNAME answers

pdns/syncres.cc
Even from forward-recurse servers.
Fixes #5934.
I have:
=> rec: Only accept types not matching the query if we asked for ANY

docs/http-api/index.rst
Mention API key in Webserver documentation
I have:
closes #5940
=> mention API key required for access

pdns/pdnsutil.cc
=> auth: Don't complain that glues are occluded by a delegation

docs/manpages/pdnsutil.1.rst
It was missing from the manpage.
I have:
=> document missing pdnsutil list-tsig-key command

docs/changelog/4.1.rst, docs/secpoll.zone
This PR should only be merged after #5936 has been merged to `master`!
=> Update ChangeLog and secpoll for auth-4.1.0-rc3.

README.md, m4/pdns_check_os.m4, pdns/recursordist/README.md
This PR improves the build experience of auth, rec and dnsdist for macOS users.
I have:
=> macOS build fixes

build-scripts/changelog-from-pr.py, build-scripts/cherry-pick-pr.py
These scripts use the GitHub API to retrieve their information and do something useful.
I have:
=> Add two scripts: one to backport PRs and one to generate changelogs

docs/changelog/4.0.rst, docs/secpoll.zone, pdns/recursordist/docs/changelog/4.0.rst
=> Add Authoritative Server 4.0.5 and Recursor 4.0.7 changelogs + secpoll

m4/pdns_check_os.m4
reference: https://github.com/arvidn/libtorrent/issues/2364#issuecomment-336175406
(cherry picked from commit e201675a3aa63712f8d08c27f2cedc10873b8f4c)
I have:
=> Backport #5955: recent Apple Xcode headers need this

pdns/dnsdistdist/html/local.js, pdns/opensslsigners.cc, pdns/recursordist/html/local.js, pdns/validate-recursor.cc, pdns/ws-recursor.cc
=> rec-4.0.x: Backports for 4.0.7

docs/manpages/pdnsutil.1.rst
Adds description of add-record command with options to the man-page.
I have:
- [N/A] compiled and tested this code
- [N/A] included documentation (including possible behaviour changes)
- [N/A] added or modified regression test(s)
- [N/A] added or modified unit test(s)
=> Adds description of add-record

pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc
We used to store additional records in `AA=1` answers as auth. In addition to being wrong, it also broke DNSSEC validation if the record was stored as `Indeterminate` because while we take care of not validating additional records when processing an answer, we have no way of knowing in which
section a record was originally located when we retrieve it from the cache.
When an answer becomes too big to fit in the requester `UDP` payload, `rfc4035` allows the sender to keep records in the additional section while omitting the corresponding `RRSIGs`, without setting the `TC` bit.
I have:
=> rec: Store additional records as non-auth, even on AA=1 answers

pdns/ws-auth.cc
=> auth: Deny cache flush, zone retrieve and notify if the API is RO

pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc
=> rec: When validating DNSKeys, the zone should be part of the signer

pdns/common_startup.cc, pdns/pdns_recursor.cc, pdns/recursordist/docs/manpages/pdns_recursor.rst
=> it's id.server, not server.id

pdns/ws-recursor.cc
=> rec: Sanitize values received from the API before writing them to the conf

build-aux/gen-version
pick up the `BUILDER_VERSION` environment variable if it is present
I have:
=> add preliminary pdns-builder support

pdns/pdns_recursor.cc, pdns/secpoll-recursor.cc
- (cherry picked from commit 47e9b74f9ee097b9bdc029c21c9edfb2f7532102)
- (cherry picked from commit 581d4ea357effe5b7d61da8cd46cec6ed9cb132e)
=> Backport #5930: secpoll order agnostic

docs/appendices/EOL.rst
This makes it official that support for the Authoritative Server 3.x is dead and gone. Wording suggestions are accepted.
I have:
=> [WIP] Update auth EOL statement on Auth

docs/changelog/4.1.rst
This has already been deployed
I have:
=> Fix 4.1.0 changelog blog url

build-scripts/travis.sh
=> Travis: Display the content of the logs when the auth unit tests fail

pdns/syncres.cc
=> rec: Use getRR<T>() instead of directly using a dynamic cast

pdns/dnsdistdist/docs/advanced/ebpf.rst, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/docs/reference/ebpf.rst
=> dnsdist: Add missing documentation about ClientState, eBPF dynamic filters

pdns/mplexer.hh
=> Add the missing <sys/time.h> include to mplexer.hh for struct timeval

README.md, pdns/README-dnsdist.md
=> Update/add macOS compilation notes

pdns/recursordist/docs/appendices/EOL.rst, pdns/recursordist/docs/dnssec.rst
Small update to the Recursor's EOL statements. Needs some @ahupowerdns love
I have:
=> Recursor: update EOL statements

docs/http-api/swagger/authoritative-api-swagger.yaml
- Defines most object types
- Documents GET requests for /servers and /zones
Issue #5854 
I have:
=> Add Draft of swagger spec for Authoritative Server HTTP API

README.md, regression-tests/README.md
Some small notes in documentation after setting up a new dev environment on debian-jessie
I have:
=> Small changes to docs that can help contributors

regression-tests/README.md
=> Docs: Fix minor typos in the regression tests README

pdns/syncres.cc
We don't use records of another class than `IN`, but we used to store some of them in the cache which is useless. Just skip them.
I have:
=> rec: Don't process records for another class than IN

build-scripts/build-recursor-rpm
=> Fix PIDDIR detection on CentOS 6

pdns/dnsdist-lua.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/docs/guides/downstreams.rst, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Add a class option to health checks

pdns/dnsdistdist/docs/advanced/multiple-instance.rst, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/docs/reference/ebpf.rst, pdns/dnsdistdist/docs/rules-actions.rst
What it says on the tin :)
I have:
=> dnsdist docs: Fix opcode links and sphinx warnings

docs/appendices/compiling.rst, docs/backends/index.rst
minor documentation fixes 
I have:
=> Os doc fixes

pdns/pdnsutil.cc
=> auth: Init openssl and libsodium before chrooting in pdnsutil

pdns/lua-auth4.cc
=> auth: Add methods missing from AuthLua4 when Lua support is disabled

pdns/recursordist/README.md
Because we don't ship effective_tld_names.dat in git.
I have:
=> rec: note curl dep when building from git

regression-tests.api/runtests.py
Cleans up `runtests.py` a bit. Extracted and improved from #2603.
Now shows which commands and tests are executed, and the common server arguments are prepared in a single place.
I have:
=> regression-tests.api: clean up runtests.py wrapper

README.md, docs/conf.py, pdns/dnsdistdist/docs/conf.py, pdns/recursordist/README.md, pdns/recursordist/docs/conf.py, pdns/version.cc, pdns/ws-auth.cc
Also update several years to match the data in pdns/version.cc
I have:
=> Update copyright years to 2018

.travis.yml, regression-tests.recursor/config.sh
* unbreak recursor tests after #5390
* don't test auth and dnsdist on this branch
I have:
=> rec 4.1.x: travis fixes/improvements

build-scripts/travis.sh, regression-tests.recursor/config.sh
=> rec 4.0.x: unbreak travis

modules/luabackend/luabackend.hh, modules/luabackend/minimal.cc, modules/mydnsbackend/mydnsbackend.cc, modules/mydnsbackend/mydnsbackend.hh, modules/opendbxbackend/odbxbackend.cc, modules/opendbxbackend/odbxbackend.hh, pdns/dns.hh, pdns/dnsbackend.cc, pdns/dnsbackend.hh, pdns/dnsrecords.cc, pdns/dnsseckeeper.hh, pdns/packethandler.cc, pdns/pdnsutil.cc, pdns/rfc2136handler.cc, pdns/serialtweaker.cc, pdns/tcpreceiver.cc, pdns/ueberbackend.cc, pdns/ueberbackend.hh, pdns/ws-auth.cc, regression-tests.api/test_Zones.py
This also fixes #4515 and #2377.
=> Remove serializeSOAData, refactor calculate/edit/increaseSOA

pdns/ednsoptions.hh
Update list in enum, correct DAU code.
From https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-11
I have:
=> Update EDNS Option code list

docs/manpages/pdnsutil.1.rst
=> pdnsutil.1: document 'bench-db'

modules/mydnsbackend/mydnsbackend.cc, pdns/backends/gsql/gsqlbackend.cc, pdns/backends/gsql/ssql.hh, pdns/bpf-filter.cc, pdns/dbdnsseckeeper.cc, pdns/dnsparser.cc, pdns/dnssecinfra.cc, pdns/ixfr.cc, pdns/recursordist/test-syncres_cc.cc, pdns/reczones.cc, pdns/resolver.cc, pdns/rpzloader.cc, pdns/slavecommunicator.cc, pdns/syncres.cc, pdns/test-dnsname_cc.cc, pdns/tsig-tests.cc, pdns/tsigverifier.cc, pdns/validate.cc, pdns/ws-recursor.cc, pdns/zoneparser-tng.cc
Avoid "Attempt to print an unset dnsname" throws in log and throw messages.
I have:
=> Use toLogString() for logging and throwing

pdns/dnsparser.hh, pdns/dnsrecords.hh, pdns/dnswriter.hh, pdns/rcpgenerator.cc, pdns/rcpgenerator.hh
- Fix error reporting for parser
- Remove surrounding whitespace. closes #2611.
I have:
=> pdns: Improve record parsing

pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc
Anything else than the initial CNAME can't be considered authoritative.
Fixes #6135.
I have:
=> rec: Don't validate signature for "glue" CNAME

modules/ldapbackend/ldapbackend.cc
=> LDAP: fix getDomainInfo() to set this as di.backend

modules/remotebackend/Gemfile.lock, modules/remotebackend/regression-tests/Gemfile.lock
GitHub reported a vulnerable dependency. While we only use this for testing, I want the warning to go away.
I have:
=> upgrade to webrick 1.4.2 (CVE-2009-4492)

pdns/resolver.cc, pdns/resolver.hh, pdns/slavecommunicator.cc
While looking at the slave code, I stumbled across some cruft...
I have:
=> Auth: slave cleanups

pdns/dnsdist-tcp.cc
With this commit, the check against spoofing is only performed against the first message, and not against subsequent ones.
Thanks to Janne (das_j) for help debugging this issue.
I have:
=> fix dnsdist problems with large AXFR: it checked first record of 2nd envelope against the original qname

pdns/recursordist/test-syncres_cc.cc, pdns/reczones.cc
=> Backport 6209 - Make `primeHints` threadsafe

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.1.rst, pdns/recursordist/docs/security-advisories/powerdns-advisory-2018-01.rst
Also add security advisory 2018-01.
=> Update changelog and secpoll for rec-4.1.1.

pdns/recursordist/test-syncres_cc.cc, pdns/validate.cc
Fixes the DNSSEC validation issue found in Knot Resolver, where a NSEC{3} ancestor delegation is wrongly use to prove the non-existence of a RR below the delegation.
We already had the correct check for the exact owner name, but not for RRs below the delegation.
I have:
=> rec: Correctly handle ancestor delegation NSEC{,3} for children

pdns/dnsdistdist/docs/reference/config.rst
=> Typo in maxCheckFailures description

pdns/dnsdistdist/docs/guides/serverpools.rst
=> capitalization DropAction in guide

pdns/dnsdistdist/docs/rules-actions.rst
=> capitalization AndRule in example

pdns/dnsdistdist/tcpiohandler.cc
=> dnsdist: Print GnuTLS error messages when parsing the configuration

pdns/recursordist/docs/lua-config/rpz.rst
* fixes typo rzpMaster -> rpzMaster
* lowercase "settings" for consistency with other heading
I have:
=> fix typo rzpMaster, lowercase settings

pdns/test-dnsname_cc.cc
this after our 'a.root-servers.net' scare (which turned out to be unrelated)
I have:
=> add a test for single character labels in dnsname and how they compare 

modules/tinydnsbackend/tinydnsbackend.cc, pdns/nsecrecords.cc, pdns/rcpgenerator.cc, pdns/rcpgenerator.hh
Fix few fixmes. Not sure if there are any issue IDs
I have:
=> Some Fixmes

modules/gmysqlbackend/smysql.cc
We will reuse the same array most of the time, but it turns out that calling `mysql_stmt_next_result()` followed by `mysql_stmt_store_result()` invalidates the existing binding (the first one sets `stmt->bind_result_done` to `false`, causing the second to reset the existing binding).
Fixes #6115.
I have:
=> auth: Always bind the results array after executing a MySQL statement

docs/http-api/swagger/authoritative-api-swagger.yaml, pdns/ws-api.cc, regression-tests.api/runtests, regression-tests.api/runtests.py, regression-tests.api/test_Servers.py
With the intention to fix #2602
=> Expose ResponseStats via REST API

build-scripts/build-dnsdist-rpm
=> EL6: fix dnsdist builds

pdns/dnsrecords.cc
=> backport: forbid label compression in ALIAS wire format

modules/gmysqlbackend/smysql.cc, modules/ldapbackend/ldapbackend.cc, pdns/dnsparser.cc, pdns/mplexer.hh, pdns/nproxy.cc, pdns/pdnsutil.cc, pdns/slavecommunicator.cc
=> backports for auth 4.1.1

pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Update the ChangeLog for the 1.2.1 release

docs/secpoll.zone
=> Add Auth 4.1.1 secpoll

.travis.yml
No need to run the auth or rec tests on that branch.
I have:
=> dnsdist: Only run dnsdist's tests on rel/dnsdist-1.2.x

docs/manpages/ixfrdist.1.rst, pdns/ixfrdist.cc
=> ixfrdist: Implement priv-dropping

pdns/.gitignore
We generate all our service-files
I have:
=> Ignore *.service in pdns/

build-scripts/changelog-from-pr.py
=> changelog-from-pr.py: Fix output indenting

build-scripts/debian-authoritative/pdns-tools.install
=> ship ixfrdist.service in tools deb

pdns/dbdnsseckeeper.cc
Greetings from fodem.....
fixes #6224
I have:
=> Auth: fix rectify (ordername) for non dnssec zones

pdns/dnsdist-tcp.cc
dnsdist had problems with large AXFR as it checked first record of second envelope against the original qname.
With this commit, the check against spoofing is only performed against the first message, and not against subsequent ones.
Thanks to Janne for help debugging this issue.
(cherry picked from commit 5af7506d106b85773d0b157e025fe5ac31d983b6)
I have:
=> backport #6180: fix dnsdist problems with large AXFR: it checked first record of 2nd envelope against the original qname

pdns/dnsdist.cc
Closes #6305 for master
I have:
=> dnsdist: Exit with code 1 on invalid parameter

pdns/rfc2136handler.cc, regression-tests/tests/1dyndns-cname-and-other-data/command, regression-tests/tests/1dyndns-cname-and-other-data/description, regression-tests/tests/1dyndns-cname-and-other-data/expected_result, regression-tests/tests/1dyndns-cname-and-other-data/skip.nodyndns
=> Backport #6276 (auth 4.0.x): Prevent CNAME + other data with DNSUpdate

pdns/rfc2136handler.cc, regression-tests/tests/1dyndns-cname-and-other-data/command, regression-tests/tests/1dyndns-cname-and-other-data/description, regression-tests/tests/1dyndns-cname-and-other-data/expected_result, regression-tests/tests/1dyndns-cname-and-other-data/skip.nodyndns
=> Backport #6276 (auth 4.1.x): Prevent CNAME + other data with DNSUpdate

pdns/recursor_cache.cc, pdns/recursordist/test-recursorcache_cc.cc
Reported by Andreas Jakum (thanks!).
Fixes #6319.
I have:
=> rec: Fix ECS-specific NS AAAA not being returned from the cache

pdns/misc.cc
Turns out, the compiler was right...
I have:
=> Fix unused variable compiler warning

docs/secpoll.zone
Fixes debian bug #892718
I have:
=> add latest deb9 auth to secpoll

regression-tests/README.md
Otherwise `tests/ent-asterisk` still fails.
I have:
=> note that libunbound also needs to come from backports

build-scripts/travis.sh
The nominum FTP site is unreliable/slow.
I have:
=> use mirror for dnsperf

pdns/dnsrecords.hh
=> Remove extra semicolons to remove some -pedantic warnings.

pdns/dnsdist-snmp.cc, pdns/misc.cc
=> dnsdist: Fix 'unreachable code' warnings reported by SonarCloud

build-scripts/travis.sh
To prevent issues with travis' connectivity
I have:
=> tests: lower dnsbulktest threshold in travis

pdns/stubresolver.cc
Reload /etc/resolv.conf when file has been modified
Issue #6263
I have:
=> Auth: Reload /etc/resolv.conf when modified. Fix #6263

README.md, bootstrap, build-scripts/dist-recursor, build-scripts/jenkins/auth-git, build-scripts/travis.sh, docs/appendices/compiling.rst, pdns/README-dnsdist.md, pdns/dnsdistdist/README, pdns/recursordist/README.md, pdns/recursordist/bootstrap, pdns/recursordist/docs/appendices/compiling.rst
Inspired by @tih - who pretty please should comment on this. Will need minor builder changes.
I have:
=> [WIP] get rid of useless bootstrap scripts; related cleanups

pdns/dnsdist-console.cc
=> Add '?' for providing help() output on dnsdist -c

pdns/filterpo.hh, pdns/recursordist/docs/http-api/endpoint-rpz-stats.rst, pdns/recursordist/docs/http-api/index.rst, pdns/reczones.cc, pdns/rpzloader.cc, pdns/rpzloader.hh, pdns/ws-recursor.cc
Closes #6225.
Discussion:
- Is the keyed JSON good? Or should we use a list of hashes?
- is the endpoint URL good? I'd like to reserve the `/rpz` endpoint for RPZ manipulation
I have:
=> Recursor: Add RPZ statistics endpoint

build-scripts/travis.sh
(cherry picked from commit 280c2f89caaa1726fd02e6315e26f7b683ed6781)
I have:
=> rec-4.1.x: Backport tests: lower dnsbulktest threshold in travis

pdns/dnsdist-dynbpf.cc, pdns/dnsdist-dynbpf.hh, pdns/dnsdist-lua.cc, pdns/dnsdistdist/docs/reference/ebpf.rst
=>  dnsdist: Log when we add an eBPF dynamic block, like regular ones

pdns/dnsdist-carbon.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-snmp.cc, pdns/dnsdist-web.cc, pdns/dnsdist.cc
Almost all of those copies should be quite fast and not noticeable, but let's not make a habit of doing a full copy.
I have:
=> dnsdist: Reduce the amount of times we copy our shared objects

pdns/sodcrypto.cc
=> dnsdist: Fix concat of the console msg length to the error message

pdns/lua-recursor4-ffi.hh, pdns/lua-recursor4.cc, pdns/lua-recursor4.hh, pdns/pdns_recursor.cc, pdns/recursordist/Makefile.am, pdns/recursordist/lua-recursor4-ffi.hh, pdns/recursordist/test-syncres_cc.cc
=> Backport 6344 to rec 4.1.x: Add a new Lua FFI hook, gettag-ffi

pdns/filterpo.hh, pdns/ixfr.cc, pdns/recursor_cache.cc, pdns/recursordist/docs/http-api/endpoint-rpz-stats.rst, pdns/recursordist/docs/http-api/index.rst, pdns/recursordist/test-negcache_cc.cc, pdns/recursordist/test-recursorcache_cc.cc, pdns/reczones.cc, pdns/rpzloader.cc, pdns/rpzloader.hh, pdns/slavecommunicator.cc, pdns/ws-recursor.cc
This PR contains the following backports:
- #6055
- #6172
- #6300
- #6320
- #6379
I have:
=> Recursor 4.1.2 backports

pdns/dnsdist.cc, pdns/dnsdistdist/docs/manpages/dnsdist.1.rst
We keep finding bugs with this option because we don't use it on a regular basis and most users run dnsdist under some kind of supervision anyway.
Closes #6329.
I have:
=> dnsdist: Remove the --daemon option

regression-tests.recursor/comments-in-forward-zones-file/command, regression-tests.recursor/comments-in-forward-zones-file/expected_result
This should make rel/rec-4.1.x pass on buildbot.
I have:
=> backport jq/sorting fixes from #6304 to rec 4.1

pdns/dnsdistdist/dnsdist-dnscrypt.hh
=> dnsdist: Remove empty dnsdist-dnscrypt.hh file

pdns/common_startup.cc, pdns/dnsproxy.cc, pdns/dnsproxy.hh
=> Backport: add TCP support for ALIAS

regression-tests.dnsdist/dnsdisttests.py
=> dnsdist: Manually raise an exception on EOF while reading the nonce

modules/luabackend/test2/pdns
This makes build-auth-debian-jessie pass on buildbot.
I have:
=> fix path assumptions in lua(2) tests

pdns/dnsdistdist/docs/guides/downstreams.rst, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Fix two small nits on the documentation

pdns/dnsdistdist/test-dnsdistrings_cc.cc
=> dnsdist: Initialize the done variable in the rings' unit tests

pdns/signingpipe.cc, pdns/tcpreceiver.cc
=> auth: avoid an isane amount of new backend connections during an AXFR

docs/common/tarball-pgp-keys.rst, pdns/dnsdistdist/docs/install.rst
This avoids redirects, making `curl` easier to use.
I have:
=> fix url to gpg keyblocks

.github/ISSUE_TEMPLATE.md
We are getting more and more tickets that demand things as if we are your overpaid vendor. With this PR, I hope we can remind submitters that we are human beings.
I have:
=> Remind submitters we are human beings too

pdns/dnsdistdist/docs/rules-actions.rst
=> docs: Fix missing ref in the dnsdist docs

modules/ldapbackend/Makefile.am, modules/ldapbackend/OBJECTFILES, modules/ldapbackend/exceptions.hh, modules/ldapbackend/ldapauthenticator.cc, modules/ldapbackend/ldapauthenticator_p.hh, modules/ldapbackend/ldapbackend.cc, modules/ldapbackend/ldapbackend.hh, modules/ldapbackend/ldaputils.cc, modules/ldapbackend/master.cc, modules/ldapbackend/native.cc, modules/ldapbackend/pdns-domaininfo.schema, modules/ldapbackend/powerldap.cc, modules/ldapbackend/powerldap.hh, pdns/zone2ldap.cc, regression-tests/backends/ldap-master
Cold on the heels of PR #5260 I finally managed to split it. Here is the first batch of updates to the LDAP backend, that do not add anything DNSSEC related but consist of internal refactors and minor cosmetic changes.
Two new features are here though, ALIAS and DNAME support, as I felt that they belonged more in this PR than in the DNSSEC one.
I have:
=> Ldap misc updates

modules/gpgsqlbackend/gpgsqlbackend.cc, pdns/backends/gsql/gsqlbackend.hh
=> auth: Allocate new statements after reconnecting to PostgreSQL

m4/pdns_with_lua.m4
=> Lua detection: make `--with-lua` autodetect

pdns/communicator.cc, pdns/packethandler.cc, pdns/slavecommunicator.cc
=> Backport: recheck serial when AXFR is done

regression-tests.dnsdist/test_Routing.py
Given that the weight of the first server is very close to the maximum and we only send 100 queries, it quite possible that the second one gets no query at all in `testHighValueWRandom`.
Switch to the lesser / greater assertions so we get the exact values in case of failure.
I have:
=> dnsdist: Be more permissive in wrandom tests, log values on failure

docs/guides/alias.rst, docs/upgrading.rst
This just fixes a documentation typo I stumbled upon
I have:
=> fix doc typo: expension->expansion

configure.ac
=> autoconf: fix quoting; fix lua2 backend liblua check

pdns/rec-lua-conf.cc, pdns/rec-lua-conf.hh, pdns/rpzloader.cc, pdns/rpzloader.hh
=> rec: Stop the obsolete RPZ threads after a Lua configuration reload

docs/manpages/calidns.1.rst, pdns/calidns.cc
=> calidns: Add a maximum-qps option to stay at a given stable load

build-scripts/build-auth-rpm, docs/lua-records.rst, m4/pdns_with_lua_records.m4, regression-tests.auth-py/test_LuaRecords.py
Fix some typos in documentation of LUA records.
I have:
=> docs: clarify ifportup and fix some typos

pdns/pdns_recursor.cc
=>  rec: Remove some unnecessary allocations and copies in the UDP path

pdns/misc.cc
=> report unparseable data in stoul invalid_argument exception

pdns/pdnsutil.cc
=> make check-zone error on rows that have content but shouldn't

build-scripts/build-auth-rpm, build-scripts/debian-authoritative/pdns-server.install, docs/Makefile.am, modules/luabackend/test2/pdns, modules/luabackend/test2/pdns_control, modules/luabackend/test2/runtest.pl
Selective backport of #6304 to make all buildbot builds work.
I have:
=> Auth 4.1.x: unbreak build

pdns/botansigners.cc
(cherry picked from commit 7d9895fe11d5371f5d775d9f13a8b52f494021b1)
Backport of #6478 
I have:
=> Fix a warning on botan >= 2.5.0

build-scripts/debian-authoritative/pdns-backend-mysql.postinst, build-scripts/debian-authoritative/pdns-backend-mysql.postrm, build-scripts/debian-authoritative/pdns-server.config, build-scripts/debian-authoritative/pdns-server.postinst, build-scripts/debian-authoritative/pdns-server.templates
=> Backport: Debian Authoritative packaging fixes for 4.1

pdns/ednsoptions.hh
(cherry picked from commit d442f33f7b36c5039dd0ae8968e70fb7f18f757a)
Backport of #6155 
I have:
=> backport: Update EDNS Option code list

lgtm.yml
Setup auth, recursor and dnsdist for lgtm.com.
Unclear what to do about Lua - which is required for dnsdist and previously we thought making this non-optional for recursor, too.
I have:
=> Add custom config for lgtm.com

pdns/backends/gsql/gsqlbackend.cc, pdns/dnspacket.cc, pdns/dnspcap.cc, pdns/ixfr.hh, pdns/opensslsigners.hh, pdns/ws-auth.cc
- Catch exceptions by reference (the actual object is discarded in these anyway)
- Add include guards
I have:
=> Cleanup small issues found by lgtm.com

pdns/pdnsutil.cc
=> pdnsutil: Use new domain in b2bmigrate

pdns/dnspacket.cc
Backport of #6312 + #6545 
I have:
=> auth: lower 'packet too short' loglevel 

pdns/ws-auth.cc, regression-tests.api/test_Zones.py
=> Backport 6571

docs/changelog/4.1.rst, docs/secpoll.zone
docs + secpoll update for auth 4.1.2
I have:
=>  docs + secpoll update for auth 4.1.2

docs/security-advisories/powerdns-advisory-2018-02.rst
=> Add PowerDNS Advisory 2018-02 for CVE-2018-1046 in dnsreplay

modules/remotebackend/remotebackend.hh, pdns/communicator.hh, pdns/dbdnsseckeeper.cc, pdns/dnsdist-tcp.cc, pdns/dnsrecords.cc, pdns/ednssubnet.cc, pdns/iputils.cc, pdns/iputils.hh, pdns/misc.cc, pdns/nameserver.cc, pdns/pdns_recursor.cc, pdns/syncres.hh, pdns/test-iputils_hh.cc
- polymorphic exceptions caught by value
- ComboAddress objects manipulated via `memset()`
I have:
=> Fix warnings reported by GCC 8.1.0

docs/Makefile.am
This fixes the build failures seen at https://builder.powerdns.com/#/builders/8/builds/2285
Successful test build at https://builder.powerdns.com/#/builders/8/builds/2287
I have:
=> add dnspcap2calidns manpage to build

pdns/dnsdistdist/docs/reference/dnstap.rst
=> dnstap.rst: Fix some editing errors

build-scripts/travis.sh, regression-tests.nobackend/rectify-axfr/expected_result, regression-tests/tests/verify-dnssec-zone/command, regression-tests/tests/verify-dnssec-zone/expected_result, regression-tests/tests/verify-dnssec-zone/expected_result.nsec3-optout
With thanks to @jelu for updating the validns ppa with ecdsa support!
I have:
=> revive validns testing, closes #3097

pdns/pdnsutil.cc, pdns/receiver.cc, pdns/ueberbackend.cc, pdns/ueberbackend.hh
Also load load modules defined in `pdns.conf` and that may be used by the `launch` directive.
I have:
=> pdnsutil: also load modules through the load-modules directive

pdns/misc.cc, pdns/pdns_recursor.cc, pdns/rec-lua-conf.cc, pdns/rec-snmp.cc, pdns/rec_channel_rec.cc, pdns/recursordist/RECURSOR-MIB.txt, pdns/recursordist/docs/http-api/endpoint-cache.rst, pdns/recursordist/docs/metrics.rst, pdns/resolver.cc, pdns/resolver.hh, pdns/rpzloader.cc, pdns/rpzloader.hh, pdns/syncres.cc, pdns/syncres.hh, pdns/ws-recursor.cc, regression-tests.api/runtests, regression-tests.api/runtests.py, regression-tests.api/test_Cache.py, regression-tests.api/test_helper.py
=> rec: backport #6562, #6566, #6567 and #6588 to 4.1.x

modules/bindbackend/bindbackend2.cc, pdns/tcpreceiver.cc
=> Fix some minor issues for presigned (large) bind zones

pdns/calidns.cc
=> calidns: Don't issue socket buffer or SCHED_FIFO warnings in quiet mode

pdns/unix_utility.cc
A nit. Smaller than any other nit you ever saw.
I have:
=> the absolute tinyest of nits

pdns/ixfrutils.cc
=> ixfrdist: store TTL in stored zones

pdns/pdns_recursor.cc
Backport of #6640.
(cherry picked from commit 1763442754e6a30dd0fc0c6a37316c2b30b9a3b8)
I have:
=> rec-4.1.x: Fix 'adding an integer to a string does not append to it' error

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.1.rst
=> ChangeLog and secpoll update for rec 4.1.3

docs/modes-of-operation.rst, pdns/dnsproxy.cc, pdns/lua-auth4.cc, pdns/pdnsutil.cc, pdns/ws-auth.cc, regression-tests.api/test_Zones.py, regression-tests/tests/alias-address/command, regression-tests/tests/alias-address/expected_result
Backports of:
- #6370 
- #6559 
- #6614 
I have:
=> Auth 4.1.3 backports

docs/changelog/4.1.rst, docs/secpoll.zone
=> Auth 4.1.3 changelog and secpoll

docs/settings.rst
Fix a typo in auth settings doc
I have:
- [*] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
=> Fix typo in settings doc

pdns/ws-auth.cc, regression-tests.api/test_cryptokeys.py
=> API: Send correct response codes for the CryptoKey endpoints

pdns/recursordist/docs/appendices/compiling.rst
I have:
- [*] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
=> Fix issue in recursor compilation doc

docs/http-api/swagger/authoritative-api-swagger.yaml
Fix incorrect doc, found by @dkoster.
I have:
=> API docs: zone delete returns 204

pdns/stubresolver.cc
Improves locking in stub resolver to avoid race conditions.
I have:
=> stubresolver: Improve locking

modules/geoipbackend/geoipbackend.hh, pdns/dnssecsigner.cc, pdns/ixfrdist.cc, pdns/lwres.cc, pdns/lwres.hh, pdns/rec-lua-conf.cc, pdns/recursordist/test-syncres_cc.cc
=> Fix minor warnings reported by the compiler or cppcheck

pdns/syncres.cc
Adds type output in one place.
I have:
=> slightly improve DNSSEC trace logging

regression-tests.dnsdist/test_DynBlocks.py
It would have prevented the issue fixed in #6706.
I have:
=> dnsdist: Test the content of dynamic blocks using the API

pdns/dnsdistdist/html/local.js
=> dnsdist: Limit QPS and latency to two decimals in the web view

pdns/test-packetcache_cc.cc
Hopefully this will lower the risks of failure on slow hosts, like our pi builder.
Closes #6578.
I have:
=> auth: Increase the packet cache TTL in our unit tests

regression-tests.recursor-dnssec/test_RPZ.py
=> rec: Add some regression tests for RPZ over AXFR and IXFR

regression-tests.recursor-dnssec/requirements.txt, regression-tests.recursor-dnssec/test_RPZ.py
Add the "Full AXFR and REST API" parts from #6722 that went missing after a rebase on the wrong version of the branch (shame on me).
I have:
=> rec: Add full AXFR in the middle of IXFR, API checks in RPZ tests

pdns/dnspacket.cc
=> fix up compilation on rhel6 for dedup speedup in auth

pdns/recursordist/docs/dnssec.rst
Resize table in source to avoid breakage in the HTML output.
n/a
=> docs/dnssec: improve HTML rendering of table

build-scripts/test-recursor, pdns/lua-recursor4.cc, pdns/lua-recursor4.hh, pdns/pdns_recursor.cc, pdns/recursordist/docs/lua-scripting/hooks.rst, pdns/recursordist/docs/settings.rst
This adds a lua `maintenance()` callback that will be called periodically.
Fix #5991 
I have:
=> rec: Add lua maintenance callback

pdns/recursordist/docs/settings.rst
Document that pdns-distributes-queries is on by default
I have:
=> pdns-distributes-queries is on by default

pdns/recursordist/docs/running.rst
=> Fix a typo in the recursor docs

build-scripts/travis.sh, pdns/pdns_recursor.cc, regression-tests.recursor-dnssec/requirements.txt, regression-tests.recursor-dnssec/snmpd.conf, regression-tests.recursor-dnssec/test_SNMP.py
This fixes a SNMP regression introduced in 4.1.3.
I have:
=>  rec: Allow the SNMP thread to retrieve statistics

pdns/recursordist/test-syncres_cc.cc, pdns/test-recpacketcache_cc.cc
Same logic than the one in #6595 but to be able to build the unit tests. 
I have:
=> rec: Reorder more headers to be able to build with Boost 1.67+

pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Add ChangeLog for dnsdist 1.3.1

pdns/dnsdist-cache.cc
=> dnsdist: Add missing include for PRId64, fix build on CentOS 6 / SLES 12

pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Add ChangeLog for dnsdist 1.3.2

docs/appendices/crypto-export.rst
also change powerdns Downloadlink from http to https
I have:
=> [DOC] fix botan lib link

pdns/dnsdistdist/docs/reference/config.rst
Thanks to @pr0vieh for reporting this mistake!
I have:
=> dnsdist: Fix the type of maxNegativeTTL (int, not bool) in the doc

pdns/calidns.cc
Instead of a naive fixed sleep between batch sends, check the actual time
passed to determine how long to sleep. This allows calidns to actually
reach qps targets at higher rates.
I have:
=> calidns: accurate qps targets

pdns/mtasker.cc, pdns/mtasker_fcontext.cc
=> rec: Allocate one more stack byte to make _GLIBCXX_ASSERTIONS happy

docs/backends/geoip.rst, docs/settings.rst, pdns/recursordist/docs/settings.rst
cc @cmouse for the geoip doc changes.
I have:
=> Fix some doc nits and re-do parts of the Geo IP docs

docs/backends/geoip.rst
Document that MMDB support was added in v4.2.
I have:
=> geoipbackend: Document that MMDB support has been added in v4.2

pdns/ws-auth.cc, regression-tests.api/test_Zones.py
=> auth-4.1.x: Backport #6816: Make sure that we use strict weak records ordering in the API

regression-tests.recursor-dnssec/runtests
After #6698, requirements.txt requires a new pip to be parsed correctly.
(Also, I installed `protoc` on the builders just now, to make this branch build).
I have:
=> recursor testing: upgrade pip

pdns/pdns_recursor.cc, pdns/rec-lua-conf.cc
=> rec: Fix compilation without protobuf support

docs/settings.rst, pdns/dnsdistdist/docs/rules-actions.rst
Two small things I noticed when setting up dnsdist in front of some auths.
I have:
=> Documentation fixes

pdns/dnsdistdist/docs/guides/dns-over-tls.rst
=> dnsdist: Fix DoT docs to clarify we only listen on TCP, not UDP

pdns/ixfrdist.cc, pdns/ixfrutils.cc, pdns/ixfrutils.hh
See #6880 for the discussion
I have:
=> Several ixfrdist fixes

regression-tests.dnsdist/test_Advanced.py
Add a test verifying destination address retrieval when listening with an any-address bind.
I have:
=> dnsdist: Test retrieving address from any-address binds
