pdns/README-dnsdist.md
pdns/dnsdist-lua2.cc

`NetmaskGroup:addMasks(table)` was incorrectly documented as `NetmaskGroup:addMask(table)`.
I have:

dnsdist: Fix a typo in the documentation of NetmaskGroup:addMasks()

---

pdns/dnsdist-lua.cc
pdns/dnsdist.cc

We were basically betting on the compiler not doing copy elision, and thus moving the temporary value which effectively prevented him from doing so. Let's just assume that the compiler will do its job.
I have:

dnsdist: Get rid of std::move() calls preventing copy elision

---

docs/markdown/authoritative/domainmetadata.md
docs/markdown/authoritative/settings.md
pdns/common_startup.cc
pdns/slavecommunicator.cc

Add an option to set a global lua-axfr-script value
I have:

auth: add option to set a global lua-axfr-script value

---

docs/manpages/calidns.1.md
pdns/Makefile.am
pdns/calidns.cc

This will allow using e.g. a stable amount of QPS (`--increment 1`) and test recursors.
I have:

calidns: add --increment and --want-recursion flags

---

pdns/dbdnsseckeeper.cc
pdns/dnsseckeeper.hh
pdns/packethandler.cc
pdns/slavecommunicator.cc
pdns/tcpreceiver.cc
pdns/ueberbackend.cc
pdns/ueberbackend.hh

- Improve the axfr dnssec freshness check. It is no longer necessary to increase a serial after a zone was signed/unsigned. 
Note: an insecure master zone only get refreshed on a slave after all existing signatures have expired, to keep the existing resilience against losing private keys on the master... 
- Ignore NSEC3PARAM metadata in an unsigned zones
I have:

Dnssec axfr

---

docs/markdown/authoritative/settings.md
pdns/common_startup.cc
pdns/communicator.cc
pdns/communicator.hh
pdns/packethandler.cc
pdns/packethandler.hh

This patch will allow you to redirect inbound notifications to a proxy server.  It's intended use is in anycast environments where it might be necessary for a proxy server to preform the AXFR.
The configuration option "forward-notify" has been added to the pdns.conf parser. The option accepts multiple IPv4 and IPv6 address values.
Obsoletes #4964 
I have:

Feature request: PowerDNS Forward-Notify Patch

---

pdns/pdns_recursor.cc

EDNS Client Subnet would only work if a Lua script was loaded in git master
I have:

also set d_requestor without Lua: the ECS logic needs it

---

pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/syncres.cc

with this, EDNS Client Subnet becomes compatible with the packet cache while using the existing variable answer facility.
Before this PR, the packetcache applied to ECS-variable answers, which meant the packetcache had to be disabled for ECS service.
We now mark ECS answers as variable, using the existing meant-for-lua setVariable answers.
I have:

with this, EDNS Client Subnet becomes compatible with the packet cache

---

pdns/pdns_recursor.cc

`snmp-master-socket` is a regular parameter but was declared as an on/off switch.
I have:

rec: snmp-master-socket is a parameter, not a switch

---

pdns/pdns_recursor.cc

It turns out that an empty switch is enabled by default.
I have:

rec: Disable use-incoming-edns-subnet by default

---

pdns/iputils.hh

when making a netmask from a comboaddress, we neglected to zero the port. This could lead to a proliferation of netmasks when compared naively (the port could be random!)
Hardcode the port of a netmask to 0. It really should not HAVE a port, but this does speed up "conversion".
I have:

when making a netmask from a comboaddress, we neglected to zero the port

---

docs/markdown/authoritative/howtos.md

howtos.md is a prime search result for "PowerDNS ALIAS records", and it's also linked from the [record types](https://doc.powerdns.com/md/types/#alias) pages, but its example to enable ALIAS expansion is not compatible with current release 4.0.3. This PR adds an example for 4.0.x.
I have:

howtos: add ALIAS recursor note for 4.0.x compatibility

---

pdns/pdns_recursor.cc

(cherry picked from commit a16c4536496ab0d3cf959bcb45e7a6cf41d02e3e)
I have:

Backport #5402: rec: Disable use-incoming-edns-subnet by default

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

This PR changes the authoritative API to forbid sending a CNAME RRset after a non-CNAME RRset is already in place at a given point in a zone and vice-versa.
Fixes #5305.
I have:

API: Auth: forbid mixing CNAME and other RRsets

---

pdns/dynlistener.cc

The change fixes listenOnTCP to allow pdns to bind control sockets to IPv6.
I have:

allow control socket to listen on IPv6

---

pdns/lwres.cc
pdns/recursor_cache.hh
pdns/syncres.cc

We use the same reference for passing the `ECS` source value to send in the query and to return the `ECS` scope value received from the server. That's fine but in the case were we send a query without `EDNS`, because we have detected the server chokes on it, we forgot to reset the value, causing the caller to believe the server actually returned an `ECS` scope value if it passed any `ECS` source value.
This PR also enhances the logging of `ImmediateServFailException` raised in `SyncRes::getRootNS()`.
I have:

rec: Don't take the initial ECS source for a scope one if EDNS is off

---

regression-tests.nobackend/rectify-axfr/command
regression-tests.nobackend/rectify-axfr/expected_result

- add root zone to rectify-axfr test
- remove comment suggesting travis ldns-verify-zone is buggy
I have:

add root zone to rectify-axfr test

---

docs/markdown/authoritative/domainmetadata.md

This PR takes the changes from #4510 regarding the use of pdnsutil with regards to domain metadata. The TSIG from that PR were already added in b1ee4ad6af4889e737a59243fe14a4e7913d42ad.
Closes #4510
I have:

Docs: add pdnsutil examples to domain metadata

---

pdns/dnssecinfra.hh
pdns/sodiumsigners.cc

Do not hash the message in the ed25519 signer.
Implementation verified against the example in https://www.rfc-editor.org/errata_search.php?rfc=8080
```
This is a Native zone
Metadata items: None
Zone has NSEC semantics
keys:
ID = 1 (CSK), flags = 257, tag = 3613, algo = 15, bits = 256      Active ( ED25519 )
CSK DNSKEY = example.com. IN DNSKEY 257 3 15 l02Woi0iS8Aa25FQkUd9RMzZHJpBoRQwAQEX1SxZJA4= ; ( ED25519 )
DS = example.com. IN DS 3613 15 1 b2c63605467c4a40942b47a953e9c0d38f81083a ; ( SHA1 digest )
DS = example.com. IN DS 3613 15 2 3aa5ab37efce57f737fc1627013fee07bdf241bd10f3b1964ab55c78e79a304b ; ( SHA256 digest )
DS = example.com. IN DS 3613 15 4 89389da437fca8372e67359dfc0dd4428fa2615df6e31bc5501677dd068514fea5c4efaf82188530a8a1645d9d3ef884 ; ( SHA-384 digest )
```
I have:

 do not hash the message in the ed25519 signer

---

docs/markdown/authoritative/howtos.md

Previous 4.0.x example for ALIAS opened up an unrestricted recursive server due to `allow-recursion` default. Make the example secure.
I have:

howtos: avoid unrestricted recursive resolution in 4.0.x ALIAS example

---

pdns/test-iputils_hh.cc

Additional tests:
* getBits()
* isIpv4()
* isIPv6()
* getNetwork()
* getMaskedNetwork()
* check that Netmasks constructed from ComboAddresses with different ports match
I have:

Add more tests to the Netmask unit tests

---

m4/pdns_enable_sanitizers.m4
pdns/mtasker_context.hh

`clang` >= 4.0.0 and `gcc` > 7.1, at least, use the new ASAN fiber switch interface taking three pointers instead of just one.
I have:

rec: Add support for the new ASAN fiber switch API

---

docs/markdown/authoritative/backend-geoip.md

In the geoip backend configuration, the "services" section returns either resource records or CNAMEs depending on what is configured in the "records" section.
Add some documentation explaining this.
I have:

[documentation] [geoipbackend] Add notes about "services" and CNAME handling

---

pdns/dnsrulactions.hh
regression-tests.dnsdist/test_RecordsCount.py

We can bail out if the section has less records than the minimum we require, but not if it has more since they obviously might be of different types.
Fixes #5365.
I have:

dnsdist: Fix RecordsTypeCountRule's handling of the # of records in a section

---

pdns/README-dnsdist.md
pdns/dnsdist-lua.cc
pdns/dnsdist-lua2.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsrulactions.hh
regression-tests.dnsdist/test_Advanced.py
regression-tests.dnsdist/test_DynBlocks.py

This allows forcing a client to retry over TCP instead of dropping or refusing the query.
I have:

dnsdist: Make a `truncate` action available to DynBlock and Lua

---

docs/markdown/recursor/settings.md

In testing, it appears to me that setting a zone in `forward-zones` to query for an address limited by `dont-query` is not stopped by it.
I have:

rec: Document behaviour of dont-query with forward-zones.

---

docs/markdown/recursor/dnssec.md

The documented rec_control command show-ntas does not appear to be correct.
I have:

rec_control documentation fix: `show-ntas` -> `get-ntas`

---

pdns/dnsdist-lua.cc

Changes getTopQueries and getGenResponses to return lowercase versions for all names. Closes #5287 
I have:

dnsdist: Change dnsdist stats functions to always return lowercase names

---

modules/bindbackend/binddnssec.cc
modules/tinydnsbackend/tinydnsbackend.cc
pdns/dnsparser.cc
pdns/dnsparser.hh
pdns/lua-auth4.cc
pdns/lua-pdns.cc
pdns/lua-recursor4.cc
pdns/packethandler.cc
pdns/pdnsutil.cc
pdns/rec-lua-conf.cc
pdns/recursordist/test-negcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/reczones.cc
pdns/speedtest.cc
pdns/syncres.cc
pdns/test-dnsrecords_cc.cc
pdns/ws-auth.cc

Make `DNSRecordContent::mastermake()` return a shared pointer instead of a naked one, since we almost always wrapped it into one afterward, and had no good reason not to anyway.
I have:

Make DNSRecordContent::mastermake() return a shared pointer

---

m4/pdns_check_os.m4

cherry-pick of the fix for #5401 from rel/rec-4.0.x. Tested with the dash shell on macOS.
I have:

unbreak quoting; fixes #5401

---

pdns/README-dnsdist.md
pdns/dnsdist-console.cc
pdns/dnsdist-lua2.cc
pdns/dnsrulactions.hh

This effectively allows (for example) pool selection from Lua, but then cached.
Sample code:
```
newServer({address="192.168.1.20", pool=""})
newServer({address="8.8.8.8", pool="elgoog"})
tisrElGoog=TimedIPSetRule()
tisrRest=TimedIPSetRule()
addAction(tisrElGoog:slice(), PoolAction("elgoog"))
addAction(tisrRest:slice(), PoolAction(""))
elgoogPeople=newNMG()
elgoogPeople:addMask("192.168.1.0/28")
function pickPool(dq)
if(elgoogPeople:match(dq.remoteaddr)) -- in real life, this would be external
then
print("Lua caught query for a googlePerson")
tisrElGoog:add(dq.remoteaddr, 10)
return DNSAction.Pool, "elgoog"
else
print("Lua caught query for restPerson")
tisrRest:add(dq.remoteaddr, 60)
return DNSAction.None, ""
end
end
addLuaAction(AllRule(), pickPool)
```
A new DNSRule that can be …

Implement a runtime changeable rule that matches IP address for a certain time

---

build-scripts/travis.sh
modules/remotebackend/Gemfile.lock

I think the last commit should make this pass. PRing already since I might not be able to finish it today.
If somebody else needs to pick this up, please:
* remove the `group: edge` line
* regroup the commits such that the jdnssec removal (which is spread over several commits) is easily reverted later
* remove the `set -x`
Furthermore:
* presumably replacing jdnssec with https://www.monshouwer.eu/download/3rd_party/jdnssec-tools-0.13.ecdsafix.tar.gz would allow it to work again
I have:

make master branch work on the new travis image

---

pdns/decafsigners.cc

don't use the libdecaf ed25519 signer when libsoduim is enabled
I have:

don't use the libdecaf ed25519 signer when libsoduim is enabled

---

modules/tinydnsbackend/tinydnsbackend.cc
modules/tinydnsbackend/tinydnsbackend.hh

backport: auth: Don't leak a CDB object in case of bogus data

---

pdns/pdns_recursor.cc

`rfc6891` states in section 6.2.3 that:
> [a requestor's payload] lower than 512 MUST be treated as equal to 512
(cherry picked from commit 320157487ec1cd0a9c4bcfd5309d9d651c26eb72)
I have:

Backport #5446: rec: Treat requestor's payload size lower than 512 as equal to 512

---

pdns/dnsdist-tcp.cc

Otherwise the compiler rightly warns about the variable being set but not used when `MSG_FASTOPEN` is not available:
> warning: variable 'freshConn' set but not used 
I have:

dnsdist: Only declare/set `freshConn` if `MSG_FASTOPEN` is defined

---

build-scripts/travis.sh

Before, we used to download an ancient version. This was needed back then for the 'spring cleaning' (to have a recent version of the authoritative server). Now add the 4.0 repo to the travis builder and use those binaries to test the recursor.
I have:

Travis: Use auth 4.0 for recursor tests

---

docs/markdown/recursor/settings.md
pdns/dnssecinfra.cc
pdns/dnssecinfra.hh
pdns/dnsseckeeper.hh
pdns/dnssecsigner.cc
pdns/epollmplexer.cc
pdns/packethandler.cc
pdns/pdns_recursor.cc
pdns/pdnsutil.cc
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/Makefile.am
pdns/recursordist/negcache.hh
pdns/recursordist/test-recursorcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/reczones.cc
pdns/secpoll-recursor.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/toysdig.cc
pdns/validate-recursor.cc
pdns/validate.cc
pdns/validate.hh
pdns/ws-auth.cc
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_Interop.py

The goal of this PR is to do `DNSSEC` validation "on-the-fly" during the resolving process, instead of afterwards. This has several advantages, the main ones being that:
- ability to validate every answer if that makes sense, not just the final result ;
- ability to cache the validation status along with the answer, preventing from having to validate the same answer again and again.
I have:

rec: Implement "on-the-fly" DNSSEC processing

---

pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc

If `tcpFastOpen` is set on a backend, we used to skip the `connect()` call regardless of `MSG_FASTOPEN` availability. We then tried to call `sendmsg()` (without `MSG_FASTOPEN`) on an unconnected TCP socket, which failed.
Fixes #5452.
I have:

dnsdist: Fix TCP with Fast Open requested but unsupported

---

docs/markdown/authoritative/howtos.md

I'm not sure if this is a bug in the docs, a bug in pdns, or an old bug
that was fixed. I will open an issue to reference this.
Query for SOA record as-is in documentation results in 500 errors when trying to view or edit the zone, like this:
```
Jun  6 13:52:05 debian pdns_server[1108]: Jun 06 13:52:05 HTTP ISE for "/api/v1/servers/localhost/zones/example.com": STL Exception: Parsing record content (try 'pdnsutil check-zone'): missing field at the end of record content 'localhost admin@example.com 1'
```
I have:

Fix query in howtos.md doc

---

pdns/cachecleaner.hh
pdns/dbdnsseckeeper.cc
pdns/dnsseckeeper.hh
pdns/recpacketcache.cc
pdns/recpacketcache.hh
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh
pdns/recursordist/test-recursorcache_cc.cc
pdns/syncres.cc

The existing cache implementation has been not designed for a very large number of ECS-specific entries for a given (qname,qtype) entry. This is fine for most cases, but we can do better if we have several thousands of entries for the same (qname, qtype) and are looking for the longest-prefix match.
This PR adds a NetmaskTree based ECS index to the cache, keeping track of the netmask-specific entries to be able to get the best match quickly. The index is disabled by default and is only enabled once the cache holds netmask-specific entries, so there should not be any penalty for deployment not enabling ECS.
Remaining known issues:
- ANY queries do not use the index ;
- removal the cache is a bit slower since we need to update the ECS index, but it should be good enough ;
- …

rec: Add an ECS index to the cache

---

pdns/syncres.cc
pdns/syncres.hh

Otherwise we insert into the cache based on the incoming ECS but later do the lookup based on the query's source IP.
I have:

rec: Use the incoming ECS for cache lookup if `use-incoming-edns-subnet` is set

---

pdns/Makefile.am
pdns/ixfr.cc
pdns/ixfr.hh
pdns/recursordist/Makefile.am
pdns/recursordist/test-common.hh
pdns/recursordist/test-ixfr_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/test-common.hh
pdns/test-ixfr_cc.cc

Under certain conditions, we could have skipped the additions part of the last `IXFR` sequence, because we stopped processing records after seeing a `SOA` record with the new serial. However, as stated
in `rfc1995`'s "Response format" section:
> "the first RR of the added RRs is the newer SOA RR"
I have:

rec: Fix IXFR skipping the additions part of the last sequence

---

pdns/Makefile.am
pdns/dnsrecords.hh
pdns/ixfr.cc
pdns/ixfr.hh
pdns/recursordist/Makefile.am
pdns/recursordist/test-common.hh
pdns/recursordist/test-ixfr_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/test-common.hh
pdns/test-ixfr_cc.cc

Under certain conditions, we could have skipped the additions part of the last `IXFR` sequence, because we stopped processing records after seeing a `SOA` record with the new serial. However, as stated
in `rfc1995`'s "Response format" section:
> "the first RR of the added RRs is the newer SOA RR"
(cherry picked from commit d67ae3b)
I have:

rec: Backport #5476: Fix IXFR skipping the additions part of the last sequence

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh

Properly handle a Secure to Insecure cut on the same auth servers. We correctly detected the zone cut by retrieving the `DS` after getting the `NS` answer, but we incorrectly marked the `NS` answer as Bogus because we expected it to be signed.
The existing `SyncRes` unit test was completely wrong, simulating a secure `DS` denial.
I have:

rec: Handle Secure to Insecure cut on the same auth servers

---

pdns/syncres.cc

If `use-incoming-ecs` is set and an actual ECS value was received.
I have:

rec: Use ECS when updating the validation state if needed

---

pdns/ws-recursor.cc

serveConnection in auth caught a lot more exceptions than the recursor code, which then would just hang on an uncaught exception.
Also cleans up a duplicated data.clear().
Fixes #5398.
I have:

API: Clean up auth/recursor code mismatches

---

pdns/iputils.hh
pdns/lwres.cc
pdns/pdns_recursor.cc
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/syncres.cc
pdns/syncres.hh
pdns/test-iputils_hh.cc

Backports:
* #5372 
* #5397 
* #5399 
* #5403
* #5408 
* #5414
We should ponder #5406 for rec-4.0.x. It doesn't make much sense on master now that we have an ECS index in our cache, but it might still be relevant for rec-4.0.x to make sure that the cache always picks up the _best_ ECS match. 
I have:

rec40: Backport ECS fixes

---

modules/gmysqlbackend/gmysqlbackend.cc
modules/gmysqlbackend/gmysqlbackend.hh
modules/gmysqlbackend/smysql.cc
modules/gmysqlbackend/smysql.hh
modules/gpgsqlbackend/gpgsqlbackend.cc
modules/gpgsqlbackend/gpgsqlbackend.hh
modules/gpgsqlbackend/spgsql.cc
modules/gpgsqlbackend/spgsql.hh
pdns/backends/gsql/gsqlbackend.cc
pdns/backends/gsql/gsqlbackend.hh
pdns/backends/gsql/ssql.hh

Test if the connection has been closed before trying to use it, and reconnect if it has.
Barely tested, comments welcome!
I have:

auth: Reconnect to the server if the My/Pg connection has been closed

---

pdns/iputils.cc

Fix a bug in the handling of short writes over `TCP`. It could have led to sending data from the beginning of the buffer twice instead of from the proper place in the buffer, sending corrupted responses.
Since it requires filling out the `TCP` window, and thus large answers toward the same `TCP` client to occur, `AXFR` answers are the most likely to be affected.
Introduced in https://github.com/PowerDNS/pdns/pull/4985, so only master is affected.
Fixes #5494.
I have:

dnsdist: Fix TCP short writes handling

---

pdns/pdns_recursor.cc

We try to read as many messages as possible after being woken up, but only the first read can count as a no-packet error.
Fixes #5474.
I have:

rec: Only increase `no-packet-error` on the first read

---

pdns/pdns_recursor.cc

#5103 made the recursor open a separate listening socket for each worker thread when `reuseport` is enabled and `pdns-distributes-queries`, but also made each worker thread listen on _every_ one of those sockets by mistake..
I have:

rec: Fix all work threads listening on all 'per thread' sockets

---

build-scripts/debian-recursor/control.in
build-scripts/debian-recursor/rules
pdns/recursordist/.gitignore
pdns/recursordist/Makefile.am
pdns/recursordist/test_libcrypto

As net snmp is linked to OpenSSL 1.0 and we link against 1.1, users get 'interesting' crashes.
**note**: needs to be tested in our builder.
This disables building our packages with netsnmp.
It also adds tests that catch this during `make check`
I have:

Don't build with SNMP on Debian Stretch

---

ext/luawrapper/include/LuaContext.hpp

They might hold shared pointers, and moving them cause the source to become empty.
Sync with upstream's f9c686e2fa3ad5cf5593265dda491239e32e2955.
I have:

LuaWrapper: Don't move the content of vectors, maps and unordered_maps

---

pdns/dnsdist-lua.cc
pdns/dnsdist.hh
pdns/dnsrulactions.hh

* Add a `DNSRule::toString()` to make debugging from Lua or the console easier
* Add virtual destructors to `DNSRule`, `DNSAction` and `DNSResponseAction` so the destructors of derived classes are run even when deleted via the base type
I have:

dnsdist: Add `DNSRule::toString()`, fix dtors for rules and actions

---

pdns/README-dnsdist.md
pdns/dnsdist.cc
pdns/dnsdist.hh
regression-tests.dnsdist/test_Spoofing.py

We could already return several addresses via the `SpoofAction()` rule, but it was not possible from `Lua`.
I have:

dnsdist: Add support for returning several IPs to spoof from Lua

---

pdns/dnsdist-lua2.cc
pdns/statnode.cc
pdns/statnode.hh

* Add labels count to the `StatNode` object
* We used to set the full name for every `submit()`, just set it once
I have:

dnsdist: Add labels count to StatNode, only set the name once

---

pdns/dnsdist-lua2.cc
regression-tests.dnsdist/test_DNSCrypt.py

I completely forgot that they were stored in network byte order.
Thanks to @bjoe2k4 for reporting the issue!
Fixes #5507.
I have:

dnsdist: Fix the DNSCrypt timestamps returned by the Lua bindings

---

docs/markdown/appendix/backend-writers-guide.md
modules/bindbackend/bindbackend2.hh
modules/luabackend/luabackend.hh
modules/luabackend/master.cc
modules/luabackend/minimal.cc
modules/mydnsbackend/mydnsbackend.cc
modules/mydnsbackend/mydnsbackend.hh
modules/opendbxbackend/odbxbackend.cc
modules/opendbxbackend/odbxbackend.hh
pdns/dnsbackend.cc
pdns/dnsbackend.hh
pdns/packethandler.cc
pdns/ueberbackend.cc
pdns/ueberbackend.hh

Remove DNSPacket pointer from getSOA. This was never okay to use (at least with caching enabled).
Split from #4545 per @Habbie's wish.
I have:

Auth: drop broken support for packet-specific SOA replies from backends

---

modules/goraclebackend/goraclebackend.cc

Adds query for last key insert id to goracle backend, it was forgotten in 63de53119e80fa93c6374f0db0c4cd5b2712f37c
I have:

goraclebackend: Add missing query for last key insert id

---

modules/gpgsqlbackend/3.4.0_to_4.1.0_schema.pgsql.sql
modules/gpgsqlbackend/schema.pgsql.sql

mysql uses BIGINT for records id.
postgres is also uses BIGINT (BIGSERIAL) too.
I have:

Postgres bigint

---

pdns/recursor_cache.cc
pdns/recursordist/negcache.cc
pdns/recursordist/test-negcache_cc.cc

This change will dump RRSIGs for the recursor cache, negative cache.
It also adds the validation state to the dump.
I have:

Add more information to recursor cache dumps

---

pdns/recursordist/test-syncres_cc.cc
pdns/validate.cc

`rfc4035` states that:
* >The validator's notion of the current time MUST be less than or equal to the time listed in the RRSIG RR's Expiration field.
* >The validator's notion of the current time MUST be greater than or equal to the time listed in the RRSIG RR's Inception field.
Reported by Petr Špaček of cz.nic (thanks!).
I have:

rec: Fix validation at the exact RRSIG inception or expiration time

---

pdns/dnsbackend.cc
pdns/dnsbackend.hh
pdns/packethandler.cc
pdns/ueberbackend.cc
pdns/ueberbackend.hh
pdns/ws-auth.cc

The original motivation for #4545: avoid creating fake DNSPacket objects just for calling getAuth() from API code.
I have:

Remove DNSPacket from getAuth() signature

---

modules/ldapbackend/Makefile.am

Schema files for ldapbackend are not shipped in the tarball, making distribution for distributions impossible.
Related to #4443 
I have:

Ship ldapbackend schema files in tarball

---

docs/markdown/recursor/settings.md
docs/markdown/recursor/upgrading.md
pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/docs/upgrade.rst

It looks like we always overrode the `loglevel` value to 6, so change and document the default to 6, but don't override it otherwise.
I have:

rec: Don't always override `loglevel` to 6

---

pdns/iputils.hh
pdns/recursordist/test-recursorcache_cc.cc
pdns/test-iputils_hh.cc

Having the most specific ones first, then the less specific ones then the empty one makes it easier to match the most specific first, in that case in the cache.
Please don't merge before we ponder the impact of this change a bit more!
I have:

rec: Make more specific Netmasks < to less specific ones

---

pdns/recursordist/negcache.cc
pdns/recursordist/test-recursorcache_cc.cc

* Add a missing header for `PRId64` in the negative cache, required on EL5/EL6
* Fix the recursor cache unit tests, caused by #5406 not being up-to-date with master
I have:

rec: Fix the recursor build

---

pdns/arguments.cc
pdns/secpoll-auth.cc
pdns/secpoll-recursor.cc

It makes Coverity happier.
I have:

Clartify how we check the return value of std::string::find()

---

pdns/resolver.cc
pdns/webserver.cc
pdns/webserver.hh
pdns/ws-recursor.cc
pdns/ws-recursor.hh

There was no issue AFAICT, but it makes it less likely to mess up in the future and leak memory, or trigger a use-after-free.
I have:

Wrap the webserver's and Resolver::tryGetSOASerial objects into smart pointers

---

pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/test-recursorcache_cc.cc
pdns/test-nmtree.cc

We lacked tests removing things for the NMT, as well as tests for the removal and expiration of entries in the ECS cache index.
I have:

rec: Add more unit tests for the NetmaskTree and ECS cache index

---

pdns/recursor_cache.cc
pdns/recursordist/test-recursorcache_cc.cc

The current code gets the most specific entry, and checks whether it's still valid. If it's not, it removes it from the index and loops to fetch the next best match. However, if the entry is valid but doesn't hold authoritative data and the caller requested it, it tries to loop to get a new match. Since the entry is still present in the index, it will just get the same entry over and over, triggering an infinite loop.
I have:

rec: Prevent an infinite loop if we need auth and the best match is not

---

pdns/dnsdistdist/docs/rules-actions.rst

fixes #5573
The addAnyTCRule() sets the truncated flag only for type ANY queries not *all queries* as previously noted in the documentation.
I have:

Corrected addAnyTCRule() documentation

---

docs/backends/generic-sql.rst

The existing documentation mixed powerdns.com w/ example.com which made reading it confusing. This switches the page to consistently use example.com
I have:

Switch dns master/slave example to consistently use example.com

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

We skipped the validation of:
- ECS-specific negative answers
- completely empty NODATA answers (no SOA, no NSEC, nothing)
I have:

rec: Be more careful about the validation of negative answers

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

Otherwise we might get into an infinite loop until we reach a limit like `max-qperq`, or possibly smash our stack.
I have:

rec: Don't fetch the DNSKEY of a zone to validate the DS of the same zone

---

pdns/recursordist/test-syncres_cc.cc

The unit tests now need to call `setDNSSECValidation()` to request validation, instead of setting `g_dnssecmode` directly.
I have:

rec: Fix the tests added in #5569 and #5570, DNSSEC modes changed in #5557

---

pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh

When DNSCrypt is enabled, we encrypt the answer in place, but we need to keep a copy of the DNS header of the original answer to be able to populate the responses ring buffer.
Fixes #5566.
I have:

dnsdist: Copy the DNS header before encrypting it in place

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua2.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst

To be able to disable the logging of connections and disconnections to the console.
Closes #5565.
I have:

dnsdist: Add setConsoleConnectionsLogging()

---

build-scripts/README.md
build-scripts/build-auth-debian
build-scripts/build-auth-rpm
build-scripts/build-dnsdist-debian
build-scripts/build-dnsdist-rpm
build-scripts/build-recursor-debian
build-scripts/build-recursor-rpm
build-scripts/debian-authoritative/control.in
build-scripts/functions.sh

Closes #5585 and ensures that the build scripts now _only_ use a tarball to build the packages.
Needs backport to 4.0.x
I have:

Fix two issues with the build scripts

---

pdns/recursor_cache.cc

This closes #5510 for the 4.0.x train.
On a `rec_control dump-cache`, we now dump RRSIGs and show the 'auth' status of the records.
I have:

Backport #5511: Dump RRSIGs on `dump-cache`

---

docs/http-api/index.rst
docs/settings.rst
pdns/common_startup.cc
pdns/pdns_recursor.cc
pdns/recursordist/docs/http-api/index.rst
pdns/recursordist/docs/settings.rst

The default value of `webserver-allow-from` (0.0.0.0, ::/0) means that the webserver is accessible from everywhere as soon as it's enabled. We don't want to change that in a minor release, but let's switch to a more sensible default (127.0.0.1, ::1) for 4.1.
I have:

Switch the default webserver's ACL to "127.0.0.1, ::1"

---

pdns/dnsdistdist/docs/changelog.rst
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/docs/reference/protobuf.rst

Document the new features introduced in #5396.
I have:

dnsdist: Document the tag features

---

pdns/dnsdist-carbon.cc
pdns/iputils.hh

Use `2001:db8::1:53_tcp` instead of `[2001:db8::1]:53_tcp`, as square brackets have special meaning for some Carbon storage engines and backends. I went with the `:port` instead of `_port` as suggested in the initial report to be consistent with the current IPv4 encoding. Since the port is always present it shouldn't be ambiguous, but I'm of course open to switch to another encoding. 
Fixes #5538.
I have:

dnsdist: Don't use square brackets for IPv6 in Carbon metrics

---

pdns/test-nameserver_cc.cc

skip v6-dependent test when PDNS_TEST_NO_IPV6 is set in environment

---

pdns/ws-auth.cc

The "Crypto Keys" API introduced in 4.1 does not honor the `api-readonly` setting.
I have:

auth: Check if the API is read-only on crypto keys methods

---

modules/luabackend/minimal.cc

Hello,
Current implementation of the getSOA() function in the Lua Backend does not set the qname member of the SOAData structure. This brakes DNS query processing and causes PowerDNS to return a 'REFUSED' response. Proposed patch sets qname to the name that is passed to getSOA().

Fix getSOA() in luabackend

---

docs/backends/geoip.rst
modules/geoipbackend/geoipbackend.cc
modules/geoipbackend/regression-tests/apex-record/command
modules/geoipbackend/regression-tests/apex-record/description
modules/geoipbackend/regression-tests/apex-record/expected_result
modules/geoipbackend/regression-tests/static-any-resolution/expected_result
regression-tests/backends/geoip-master

Add ability to have service record for apex record and any other static record. Fixes #3747.
I have:

geoipbackend: Service for apex record

---

pdns/ueberbackend.cc
regression-tests/tests/ds-at-parent/command
regression-tests/tests/ds-at-parent/description
regression-tests/tests/ds-at-parent/expected_result

lookups one level (or more) below apex did confuse getAuth() for qytpe DS
I have:

lookups one level (or more) below apex did confuse getAuth() for qytpe DS

---

pdns/pdns_recursor.cc
pdns/sortlist.cc
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_Sortlist.py

In #5357 @killerwhile discovered we were missorting CNAME records when using sortlist.
With this commit, we should get it right by moving to stable_sort and being more careful about type equivalence.
Fix sortlist in the presence of CNAME
I have:

Fix sortlist in the presence of CNAME

---

build-scripts/travis.sh

Thus avoiding issues when/if the repository is cloned with a different
name.
(cherry picked from commit 1e0253cad96199647f92ef4fa8230f614637e80c)
I have:

Backport #4986: Use `${TRAVIS_BUILD_DIR}` instead of assuming the repo is in `pdns`

---

pdns/packethandler.cc
regression-tests/tests/direct-rrsig/expected_result

In rfc1035 is not very clear about this
4.1.1
```
OPCODE          A four bit field that specifies kind of query in this
message. ...
```
and 
```
4               Not Implemented - The name server does
not support the requested kind of query.
```
But there is room for discussion.
rfc2136 on the other hand, is very clear about the use of NOTIMP
2.2
```
NOTIMP      4       The name server does not support
the specified Opcode.
```
This pull is replacing NOTIMP with REFUSED for non opcode related use.
I have:

NOTIMP is only appropriate for an unsupported opcode

---

pdns/pdnsutil.cc

pdnsutil edit-zone runs checkZone, but not from the database, but straight from the zonefile just edited, which can't yet be rectified.
This commit removes the auth=1 check in case of data that is supplied straight to checkZone not from the database
I have:

fix that pdnsutil edit-zone complains about auth=1 problems on all data

---

pdns/syncres.cc

Fix some typos in DNSSEC debug logging, add some more data
I have:

fix typo in logging of dnssec validation, add some fields

---

pdns/dnsseckeeper.hh
pdns/serialtweaker.cc
pdns/tcpreceiver.cc

auth: first and last SOA in an AXFR must be identical

---

pdns/ws-auth.cc
regression-tests.api/runtests.py
regression-tests.api/test_Zones.py

API: prevent duplicate records in single RRset

---

pdns/recursordist/docs/conf.py

Maybe that's rather a Github bug because pull(s) and commit(s) works this way. But at least it is now as in /pdns/docs/conf.py
I have:

Otherwise the issues are dead links.

---

pdns/zoneparser-tng.cc

This wraps all calls to `toCanonic` in try/catch and rethrows it as a
PDNSException with more information.
Closes #5520.
I have:

Catch DNSName exception in the Zoneparser

---

regression-tests/backends/bind-master
regression-tests/backends/geoip-master
regression-tests/backends/gsql-common
regression-tests/backends/ldap-master
regression-tests/backends/mydns-master
regression-tests/backends/opendbx-master
regression-tests/backends/oracle-master
regression-tests/backends/remote-master
regression-tests/backends/tinydns-master
regression-tests/start-test-stop

Added an address variable to regression-tests set to 127.0.0.1
Issue #2835 
I have:

listen on 127.0.0.1 during regression tests

---

contrib/ProtobufLogger.py
pdns/dnsmessage.proto
pdns/filterpo.cc
pdns/filterpo.hh
pdns/pdns_recursor.cc
pdns/rec-protobuf.cc
pdns/rec-protobuf.hh

Add a new field to our protocol buffer format to be able to know which type of policy matched. This is especially useful when using one or more `RPZ` zone containing different types of rules.
I have:

rec: Log the policy type (QName, Client IP, NS IP...) over protobuf

---

pdns/rec_channel_rec.cc

Unlikely as it seems, I just got hit by a race where three threads were trying to register the stats at the same time, causing my starting recursor to stay stuck while consuming a lot of CPU.
I have:

rec: Guard `registerAllStats()` with an atomic flag instead of a bool

---

pdns/iputils.hh
pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/test_ECS.py
regression-tests.recursor-dnssec/test_Interop.py

The current behavior is to send a query without ECS information and to cache it as a non ECS-specific entry. Unfortunately doing so meant that we wouldn't send any further ECS-specific queries for
this `(qname,qtype)` since we could fallback to the non ECS-specific cached answer.
This commit adds a new parameter, `ecs-scope-zero-addr`, allowing to specify the address sent to ECS-whitelisted authoritative servers in that case. If unset, the default is to take the first usable (non-any) address in `query-local-address` then in `query-local-address6`, and finally to use `127.0.0.1` as a last resort.
I have:

rec: Fix cache handling of ECS queries with a source length of 0

---

pdns/pdns_recursor.cc
pdns/sortlist.cc
pdns/sortlist.hh

remove unused SortList compare operator for ComboAddress

---

build-scripts/travis.sh
m4/pdns_with_net_snmp.m4
pdns/devpollmplexer.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/devpollmplexer.cc
pdns/dnsdistdist/epollmplexer.cc
pdns/dnsdistdist/kqueuemplexer.cc
pdns/dnsdistdist/mplexer.hh
pdns/dnsdistdist/portsmplexer.cc
pdns/dnsdistdist/selectmplexer.cc
pdns/epollmplexer.cc
pdns/kqueuemplexer.cc
pdns/mplexer.hh
pdns/pollmplexer.cc
pdns/portsmplexer.cc
pdns/selectmplexer.cc
pdns/snmp-agent.cc
pdns/snmp-agent.hh

If the connection to the master is lost, the SNMP subagent API inserts an alarm to try to reconnect after a certain delay.
Should fix #5327.
I have:

SNMP: Handle SNMP alarms so we can reconnect to the master

---

pdns/dnsdist.cc
regression-tests.dnsdist/test_DynBlocks.py

Winfried noted that our new dynamic truncation rule worked fine on UDP, but on TCP/IP a truncate would be converted into a drop, which was not the intended effect.
This commit makes dynamic truncate a NOOP on TCP.
I have:

Make dnsdist dynamic truncate do right thing on TCP/IP

---

contrib/ProtobufLogger.py
pdns/dnsmessage.proto
pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/protobuf.cc
pdns/protobuf.hh
pdns/recursordist/docs/lua-scripting/dq.rst
pdns/recursordist/docs/lua-scripting/hooks.rst

This PR provides support for a deviceId field, set by Lua, and included in protobuf messages. I essentially just shadowed what was already done for requestorID.
DeviceId would typically be parsed from an EDNS option such as 65001 or the new edns0-clientid draft, and would usually be a mac address but could also be an IP 4/6 address.
I have:

Support for identifying devices by id such as mac address

---

pdns/misc.cc

This fixes compilation on FreeBSD, which requires an extra include file and defines a slightly different type.
Here's the log wich shows the compilation errors: https://pkg.cainites.net/data/freebsd_11-1x64-system/2017-08-30_10h50m42s/logs/errors/powerdns-recursor-4.1.0a1.log
I have:

[PATCH]: Recursor 4.1.0 alpha 1 fails to build on FreeBSD

---

regression-tests/runtests

Travis now [1] defaults to _JAVA_OPTIONS="-Xmx2048m -Xms512m". We wouldn't
care much, except that every Java command now outputs the following line
to stderr, breaking our jdnssec diffs:
"Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m"
[1]: https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/
I have:

auth: Unset _JAVA_OPTIONS before using jdnssec

---

pdns/syncres.cc

We forgot to add NSEC/NSEC3 records on a `root-nx-trust` cache hit.
Fixes #5649.
I have:

rec: Add NSEC records on nx-trust cache hits

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/validate.cc

The DNSSEC validation check for section 4.1 of rfc6840 was wrong, leading to a Bogus validation state when getting a denial from the root zone.
Also fixes a bug in a DNSSEC validation corner case with forwarded zones, uncovered by this fix (we should go Bogus if we get an `NXDomain` answer from the parent when trying to get a `DS` record for a name we were told exists, by the authoritative server we forwarded to).
Fixes #5648.
Supersedes #5651.
I have:

rec: Fix erroneous check for section 4.1 of rfc6840

---

build-scripts/build-auth-rpm
build-scripts/debian-authoritative/control.in
build-scripts/debian-authoritative/rules
configure.ac
docs/changelog/4.1.rst
docs/dnssec/pkcs11.rst
pdns/version.cc

All distros we build for (except CentOS 6) have a new enough p11kit. Packages built with this support are [here](https://downloads.powerdns.com/autobuilt_browser/#/auth/0.0.authenablepkcs11.1832ge15ac7d).
Closes #3110
I have:

Enable PKCS#11 in authoritative packages

---

pdns/dnspacket.cc

`rfc6891` states in section 6.2.3 that:
> [a requestor's payload] lower than 512 MUST be treated as equal to 512
I have:

auth: Treat requestor's payload size lower than 512 as equal to 512

---

pdns/pdnsutil.cc

We would read out of bounds if SRV or MX content did not have enough parts.
I have:

verify parts.size(). Fixes #5688

---

pdns/dnsdist-tcp.cc
pdns/dnsrulactions.hh

dnsdist: Fix several signed/unsigned comparison warnings on ARM

---

docs/http-api/endpoint-zones.rst
pdns/ws-auth.cc

For zone PATCH requests, this adds new `X-PDNS-Old-Serial` and `X-PDNS-New-Serial` response
headers with the zone serials before and after the changes.
Ideally this would be returned in a response JSON object, but this API
currently return 204 No Content and I did not want to break any clients
that might rely on this.
I have:

auth api: return new serial in header after PATCH

---

docs/Makefile.am

Without this, not having virtualenv leads to a confusing error, as seen in #5701 
I have:

actually abort when virtualenv is missing. Fixes #5701

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/dnsrulactions.cc
pdns/dnsdistdist/docs/rules-actions.rst
pdns/dnsrulactions.hh

This adds a ProbaRule, ProbaRule(1.0) means 'match always', 0.1 '10%'. Useful for TeeAction.
Sometimes you don't want an action to happen 100% of the time. With ProbaRule you can for example 'Tee' 1% of your traffic to hot spares which then always have a hot cache:
addAction(ProbaRule(0.1), TeeAction("127.0.0.1:5301"))
I have:

add ProbaRule to dnsdist: match with given probability

---

modules/bindbackend/bindbackend2.cc

Make bindbackend `startTransaction` to return false when it has failed.
I have:

bindbackend: Fix transaction to return false on failure

---

docs/http-api/endpoint-cryptokeys.rst
docs/settings.rst
docs/upgrading.rst
pdns/common_startup.cc
pdns/common_startup.hh
pdns/pdnsutil.cc
pdns/ws-auth.cc

Before, the `default-{k,z}sk-algorithms` options would accept multiple options. While the `default-{k,z}sk-size` would only accept a single value.
The first commit makes the algorithms options singular.
Furthermore, size is only needed for non-fixed length algo's (and we don't have defaults). the second displays a warning on start up if the size is 0 when it should be a number.
The last commit makes the cryptokey endpoint in the API use the defaults if `algo` and/or `size` are not passed in the request.
I have:

Auth DNSSEC: Make default options singular and use defaults in Cryptokey API-endpoint

---

pdns/pdnsutil.cc

Remove printing of DS records from `pdnsutil export-zone-dnskey …`.  This was not only inconsistent behaviour[1] but also done incorrectly[2].
Fixes https://github.com/PowerDNS/pdns/issues/5719.
[1] as noted by @jpmens
[2] as noted by @Habbie
I have:

Remove printing of DS records from export-zone-dnskey.

---

pdns/dbdnsseckeeper.cc

This PR makes the auth also publish CDS/CDNSKEY records for inactive keys, as this is needed to roll without double sigs.
Closes #5721
I have:

Auth: Publish inactive KSK/CSK as CDNSKEY/CDS

---

pdns/syncres.cc

The existing code handles NSEC, NSEC3 and RRSIG records separately and doesn't consider that the initial query could have been for a NSEC record. Let's first check whether the record matches the initial request, and only if it doesn't try the NSEC/NSEC3/RRSIG specific code.
Fixes #5705.
I have:

rec: Handle direct NSEC queries

---

modules/bindbackend/bindbackend2.cc
modules/bindbackend/bindbackend2.hh

While this should not happen, using a smart pointer prevents double-free, user-after-free or invalid pointer dereference if we mess up our transaction logic.
I have:

auth: Use a unique pointer for bind backend's `d_of`

---

pdns/lua-recursor4.cc
pdns/pdns_recursor.cc

Those values are not documented in a recursor context, and does not work as one could expect since `pdns.PASS` results in an immediate `ServFail` and `pdns.TRUNCATE` in a strange status code being sent (showing up as `RESERVED13` in `dig`).
I have:

rec: Remove pdns.PASS and pdns.TRUNCATE

---

pdns/botan110signers.cc

This is included in https://github.com/PowerDNS/pdns/pull/5498, so don't merge this PR unless we decide not to include #5498 in 4.1.
In the same manner we should backport this fix to 4.0 if we don't backport #5498 there, and I don't think we should backport it.
I have:

auth: Fix a crash when getting a public GOST key if the private one is not set

---

pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/docs/manpages/rec_control.rst
pdns/recursordist/docs/metrics.rst
pdns/syncres.hh

With this commit, the number of (packet)cache entries can be changed at runtime, although the effect may not be immediate in case of shrinking the cache.
I have:

implement dynamic cache sizeing for recursor

---

pdns/dnssecinfra.cc
pdns/dnssecinfra.hh
pdns/packethandler.cc
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/validate.cc
pdns/validate.hh

Since there is so many broken DNS servers handing NS queries incorrectly, move to DS queries for figuring out zone cuts since we only care as long as the zone is Secure (including with a TA).
Please review this carefully before merging.
Fixes #5681.
I have:

rec: Detect zone cuts by asking for DS instead of NS

---

pdns/dnsbulktest.cc

This is a priority merge since it holds up our testing. Once merged, it will eventually end up on our repos, which means our testing will only then benefit, since they apt-get the testing tools from our repo!
The Umbrella 1M list does not need www doubling in dnsbulktest and in fact is useless if you do.
Make doubling optional.
I have:

add --www feature to dnsbulktest to make it (not) add www. to everything too

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

As pointed out in https://github.com/PowerDNS/pdns/issues/5735, the recursor has an interesting issue when handling a direct query for the `RRSIG` type. It would send a query to the corresponding authoritative server and assume that a `NOTIMPL` answer, as sent for example by PowerDNS 4.0.x, is an indication that this server does not support `EDNS`.
Since it does not make a lot of sense to directly ask for `RRSIG` or `NSEC3` records anyway, let's just refuse those queries as we already do for `AXFR` and `IXFR`.
One thing to ponder is that the current code sends a `ServFail` answer for `AXFR` and `IXFR`, and that feels wrong. Perhaps `REFUSED` would be more suited?
Fixes #5735.
I have:

rec: Do not allow direct queries for RRSIG or NSEC3

---

pdns/dnsbulktest.cc

With this commit, dnsbulktest writes out more statistics when invoked with -e. This enables more granular limits for determining build success in travis.
I have:

Add more metrics to dnsbulktest -e output

---

modules/remotebackend/Makefile.am

Fix remotebackend out of tree issue in #5743
I have:

remotebackend: Fix libjson11.la location to top_builddir

---

build-scripts/test-recursor-bulk
build-scripts/travis.sh
regression-tests/recursor-test

This commit changes our dnsbulktest source from Alexa to Cisco Umbrella, but this turned out not to be as important as we thought.
In addition, it turns out we had been installing pdns-tools incorrectly because of wrong apt-settings. We now install pdns-tools from the master repo at repo.powerdns.com
This commit also tunes pdns_recursor to use less simultaneous outbound connections during testing, which appears to make Travis NAT happier, leading to less errors.
Finally, we use new features of dnsbulktest to extract more statistics for how well we are doing. Success is now dependent on errors and timeouts, and less on NXDOMAIN.
I have:

Improve dnsbulktest experience in travis for more robustness

---

pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh
pdns/recursordist/test-negcache_cc.cc
pdns/syncres.cc

When looking for a `DS`, ignore a cached `NXDOMAIN` answer whose `SOA` matches the exact domain we are looking the `DS` for.
Fixes #5749.
I have:

rec: When looking for a DS, skip NXD if the auth matches the qname

---

pdns/pdns_recursor.cc

With this PR, pdns_recursor non-quiet logging shows DNSSEC status and adds time spent waiting for network, plus total time spent before answer was sent. This quantifies the internal overhead.
This PR is required for SLA compliance measures we need in 4.1
I have:

Improve --quiet=false output for recursor to include DNSSEC and more timing details

---

pdns/pdns_recursor.cc
regression-tests.recursor-dnssec/basicDNSSEC.py

The client might need them for validation purpose, for example, so it needs to know the answer has been truncated.
I have:

rec: Set TC=1 if we had to omit part of the AUTHORITY section

---

pdns/slavecommunicator.cc

Since the QC/PC split up, we only removed entries for the AXFR'd domain from the packet cache, not the query cache.
We also did not remove entries in case of IXFR. We might want to backport that second part to 4.0.
I have:

auth: Correctly purge entries from the caches after a transfer

---

pdns/Makefile.am
pdns/dnssecinfra.cc
pdns/dnssecinfra.hh
pdns/recursordist/Makefile.am
pdns/recursordist/test-signers.cc
pdns/test-signers.cc

Add test vectors from `rfc5933`, `rfc8080` and `Knot DNS` tests for `RSA`, `ECDSA`, `ed25519` and `GOST`.
I did not refactor the existing tests for `ed448` because I failed to get `libdecaf` to compile properly on my host so far.
I have:

Add DNSSEC test vectors for RSA, ECDSA, ed25519 and GOST

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/validate.cc
pdns/validate.hh

rec: Don't negcache entries for longer than their RRSIG validity

---

m4/pdns_check_libsodium.m4

This was 'no' before. As we (want to) use libsodium for dnsdist's
console *and* for ed25519 for the auth and the recursor, we might as wel
use it when we detect it.
This would a good change to have in auth 4.1, rec 4.1 and dndist 1.3,
currently on master.
NOTE: will need an entry in the upgrade guides
I have:

autoconf: set --enable-libsodium to 'auto'

---

pdns/sstuff.hh
pdns/webserver.cc
pdns/ws-recursor.cc

Gracefully handle `Socket::accept()` returning a null pointer on `EAGAIN`.
I have:

If accept() returns EAGAIN, Socket::accept() returns a null pointer

---

docs/secpoll.zone
docs/upgrading.rst
pdns/recursordist/docs/changelog/4.1.rst

Update the ChangeLog for Recursor 4.1.0 RC1.

Update the ChangeLog and secpoll for Recursor 4.1.0 RC1.

---

pdns/dnspacket.hh
pdns/receiver.cc
pdns/syncres.hh
pdns/test-dns_random_hh.cc
pdns/zone2json.cc
pdns/zone2ldap.cc
pdns/zone2sql.cc

…5158
Removing preprocessor directives for GCC version lower then 4.7 issue #5158 
I have:

Remove preprocessor directives for older GCC versions

---

modules/tinydnsbackend/tinydnsbackend.cc

When throwing because of bogus content in the tinydns database, report the offending name+type so the admin can find the offending record.
I have:

tinydns: report broken content that causes errors

---

pdns/mtasker.cc
pdns/mtasker_fcontext.cc
pdns/recursordist/Makefile.am
pdns/recursordist/test-mtasker.cc

In MTasker, MThreads can throw exceptions, which then get caught by the 'kernel' thread. This mechanism was faulty in our 'old boost' support, leading to crashes in std::rethrow_exception. 
This PR fixes the 'old boost' support, plus adds a testcase for throwing & catching such exceptions. In addition, this simple testcase found a bug in MTasker with timeoutless waiters. This has also been solved.
I have:

Fix throwing exceptions from MThreads, plus add unit tests

---

modules/tinydnsbackend/tinydnsbackend.cc

It doesn't look like an issue since there is a `continue` at the end of the alternative, but this is a lot cleaner that way.
Reported by Coverity.
I have:

auth: Fix missing else braces in TinyDNSBackend::get()

---

modules/gmysqlbackend/smysql.cc

Related to #5675, but does not fix it.
I have:

auth: Display the needed size when a MySQL result was truncated

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/validate.cc
pdns/validate.hh

Otherwise we might consider that a NSEC record covers a name when it does not.
I have:

rec: Check that the NSEC covers an ENT when looking for NODATA

---

pdns/root-addresses.hh

new b.root ipv4 address
closes  #5663
I have:

b.root renumbering, effective 2017-10-24

---

pdns/pdns_recursor.cc
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh

Before, we would only lowercase the original qname before handing it to SyncRes. Now the syncresolveWrapper lowercases if it has to before handing the qname to asyncresolve.
I have:

rec: Lowercase all outgoing qnames when lowercase-outgoing is set

---

pdns/pdns_recursor.cc
pdns/syncres.cc
pdns/syncres.hh

This is a backport of #5740
I have:

Backport #5740: Lowercase all outgoing qnames when lowercase-outgoing is set

---

docs/backends/generic-mysql.rst

Addresses doc issue #5668 for default database name.
I have:
Note: the doc currently has the default port as 3306, but the default port is actually set to 0. I might recommend changing the default to reflect the document (3306).

Update docs to reflect actual default database name.

---

docs/dnssec/modes-of-operation.rst
docs/manpages/pdnsutil.1.rst
modules/bindbackend/bindbackend2.cc
pdns/bindparser.yy
pdns/bindparserclasses.hh
pdns/pdnsutil.cc

This PR fixes a bunch of minor issues discovered by @jpmens (thanks!). The following issues are fixed:
* #5787 `pdnsutil set-meta` will now exit with an error code if the domain does not exists
* #5784 Two missing commands for pdnsutil (`create-slave-zone` and `change-slave-zone-master`) have been documented
* #5786 The BIND backend will properly tell the user that they missed setting the 'file' stanza in the 'zone' block of the bind-config file
* #5785 Clarified that the databse used for the hybrid bind mode is not the same one as the `bind-dnssec-db`
I have:

Fix some of the issues found by @jpmens

---

pdns/pdnsutil.cc
pdns/signingpipe.cc
pdns/signingpipe.hh
pdns/tcpreceiver.cc

The current code detects that the corresponding pipe has been closed, but has no way to know if we were still expecting something from this worker or if this is a "normal" exit. This leads to `d_outstanding` not being decreased if we expected an answer from the dying worker, meaning we will wait forever for the result.
This patch keeps track of the number of answers we are expecting from each worker, treating a worker exiting while we still expect some answer from its end as an error.
It also move to the use of `std::thread` to get rid of the temporary allocated struct used to pass parameters to the new thread.
I have:

 auth: Handle a signing pipe worker dying with work still pending

---

pdns/tcpreceiver.cc

more s/string/DNSName in doAXFR(), and fix a NSEC chain bug for characters >127 or < 32
I have:

auth: more DNSName in doAXFR()

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_Advanced.py

In 1.2.0 we deprecated the `addQPSLimit()` function, suggesting the use of `QPSAction()` as a replacement, but the Lua binding for `QPSAction()` was missing. In addition the documentation was referring to `QPSLimitAction()` instead of `QPSAction()`.
I have:

dnsdist: Add missing QPSAction

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst

If the parameter is present, its value is used to set the initial state of the `DownstreamServer` until a health check is performed, instead of using the previous known state.
It's useful if one wants to restore the automatic status detection but knows that the server is either currently down but was previously up (queries sent until the health check is performed will be lost); or currently up but was previously down, so it process queries immediately.
I have:

dnsdist: Add an optional `status` parameter to `setAuto()`

---

modules/bindbackend/binddnssec.cc
pdns/bindparserclasses.hh
pdns/ws-auth.cc

* Fix `Bind2Backend::addDomainKey()` return value without `SQLite3`
* Handle `addKey()` returning false in `apiZoneCryptokeysPOST`
* Make sure `hadFileDirective` is initialized in `BindDomainInfo`
I have:

auth: Fix Coverity warnings in apiZoneCryptokeysPOST and BindDomainInfo

---

modules/ldapbackend/ldapbackend.cc
modules/ldapbackend/ldaputils.hh
modules/ldapbackend/powerldap.cc
modules/ldapbackend/powerldap.hh

Make sure the timeout from the settings is used in the PowerLDAP class
With a little luck this fixes #5742 
Could use some testing. @sooslaca?
I have:

auth: ldapbackend, use the timeout setting in the PowerLDAP class

---

pdns/syncres.cc

We don't need to store NSEC3 records in the positive cache because:
* we don't allow direct NSEC3 queries
* denial of existence proofs in wildcard expanded positive responses are stored in `authorityRecs` for the initial qname
* denial of existence proofs for negative responses are stored in the negative cache
I have:

rec: Don't directly store NSEC3 records in the positive cache

---

pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/docs/metrics.rst
pdns/syncres.cc
pdns/syncres.hh

With this commit, PowerDNS provides metrics on the difference between the time spent waiting for authoritative servers, and the amount of time elapsed between arrival of query
and sending out the response. This metric should be seen as experimental until operational experience proves its relevance.
I have:

Implement experimental metric tracking time spent within PowerDNS per query

---

pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh
pdns/syncres.cc
pdns/syncres.hh

We don't need to validate the answers to the "infrastructure" queries, for example to retrieve `NS` records and authoritative servers addresses.
We do however need to validate entries retrieved from our negative cache if the initial query did not ask for validation but the current one does.
I have:

rec: Disable validation for infra queries, validate entries from the negcache

---

docs/settings.rst
pdns/common_startup.cc
pdns/logger.cc
pdns/logger.hh
pdns/pdns.service.in
pdns/pdns_recursor.cc
pdns/receiver.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/pdns-recursor.service.in

This option can be used to disable printing timestamps to stdout, this is useful when using systemd-journald or another supervisor that timestamps stdout by itself. As the logs will not have 2 timestamps.
I have:

4.1 polish: Add log-timestamp option

---

docs/dnsupdate.rst

Clarify association between use of TSIG key and ALLOW-DNSUPDATE-FROM. Previous description sounded like AND
I have:

Attempt to clarify use of TSIG key and ALLOW-DNSUPDATE-FROM

---

docs/common/api/configsetting.rst
docs/http-api/index.rst

- Add `api=yes` required to enable API
- Change ports in examples from 8082 to 8081 to reflect default port in
configs for Authoritative DNS
I have:

Add missing config option in HTTP API docs

---

pdns/dnsdist.cc

The log message as printed when no downstream server could be selected confused g_servFailOnNoPolicy true/false. Which confused me why I did not get any response using the default settings.
I have:

dnsdist: Fix log message in no-downstream-server case

---

pdns/dnsdist-lua2.cc
pdns/dnsrulactions.hh

No need to create a TCP connection to the protobuf server every time we are started in client mode.
I have:

dnsdist: Don't create a Remote Logger in client mode

---

build-scripts/build-recursor-rpm
build-scripts/debian-recursor/pdns-recursor.init

This fixes this issue for sys v init. For systemd, it is advices that the admin creates these directories (or doesn't touch the setting).
Closes #5439
I have:

Rec: create socket-dir from init-script

---

pdns/dnsname.cc
pdns/dnsname.hh
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/test-dnsname_cc.cc
pdns/validate.cc
pdns/validate.hh

Fix DNSSEC validation for:
* denial of wildcards in negative answer
* denial of existence proofs in wildcard expanded positive responses
Fixes #5861.
I have:

rec: Fix validation of denial proofs

---

pdns/dnsdistdist/dnsrulactions.cc

Since 0beaa5c825059986d3ce108a4bd2578a08d6d1d0 we checked the space available against the current length, instead of the real capacity, resulting in the query being dropped because it looked like there was not enough room to add the ECS value.
Fixes #5859.
I have:

dnsdist: Fix TeeAction() with EDNS Client Subnet

---

pdns/rec-lua-conf.cc

g_rootdnsname which might not yet have been initialized when our global scope DNSSEC trust anchor initializing code runs. This broke DNSSEC validation with `-flto`.
I also audited the code for other global scope uses of g_rootdnsname and did not find any, but I did not look too hard. 
This minimal fix is super safe for 4.1. A broader fix might be setting a `__attribute__((init_priority(0))` on `g_rootdnsname`. 
I have:

With this commit, the root-anchor provisioning machinery no longer uses g_rootdnsname

---

docs/dnssec/operational.rst
docs/manpages/pdnsutil.1.rst

Brief documentation for `pdnsutil set-nsec3` with no salt (e.g. `"1 0 0 -"`).
They're the only two parts of the documentation I found that discuss `set-nsec3` in detail.
The diff to `pdnsutil.1.rst` is a bit messy because line wrapping, even though I just added a few words.
I have:

Document pdnsutil set-nsec3 with no salt ("1 0 0 -")

---

docs/backends/generic-mysql.rst
docs/backends/generic-postgresql.rst
modules/gmysqlbackend/gmysqlbackend.cc
modules/gpgsqlbackend/gpgsqlbackend.cc

Sync defaults in code and docs for gmysqlbackend and gpgsqlbackend. Fixes #5668 (just the remaining bits).
I have:

Sync gmysql/gpgsql default settings and docs

---

modules/bindbackend/bindbackend2.cc
modules/geoipbackend/geoipbackend.cc
modules/gpgsqlbackend/spgsql.cc
modules/pipebackend/coprocess.cc
modules/remotebackend/pipeconnector.cc
modules/remotebackend/unixconnector.cc
pdns/auth-querycache.hh
pdns/calidns.cc
pdns/dbdnsseckeeper.cc
pdns/dnsdist.cc
pdns/dnsreplay.cc
pdns/iputils.cc
pdns/lua-auth4.cc
pdns/nproxy.cc
pdns/nsec3dig.cc
pdns/packethandler.cc
pdns/pdns_recursor.cc
pdns/pdnsutil.cc
pdns/pkcs11signers.cc
pdns/recursordist/test-recursorcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/saxfr.cc
pdns/statnode.cc
pdns/syncres.cc
pdns/tcpreceiver.cc
pdns/test-dnsname_cc.cc
pdns/zoneparser-tng.cc

Let's try not to shadow variable by declaring a new variable with the same name in the scope of the previous one. Fix a bug in the way `isTCPSocketUsable()` handles `EINTR` errors.
Reported by GCC's `-Wshadow`.
I have:

Fix shadowed variables

---

pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst

This adds the configuration option `ipBindAddrNoPort` for downstream servers to optionally disable `IP_BIND_ADDRESS_NO_PORT` if `dnsdist` was built with support for it. It defaults to `true` to maintain current behavior by default.
This addresses the problem when `dnsdist` was built on a kernel newer than 4.2, but is running (in my case, in a container) on a system with an older kernel version which does not support `IP_BIND_ADDRESS_NO_PORT`, causing TCP connections to immediately fail.
I have:

Add configuration option to disable IP_BIND_ADDRESS_NO_PORT.

---

docs/secpoll.zone

We (I) forgot to bump the SOA record when adding the info for rec-4.1.0-rc2.
Fixes #5887.

Bump SOA record for rec-4.1.0-rc2.

---

pdns/rec_channel_rec.cc
pdns/syncres.cc
pdns/syncres.hh

We used to not sort the different addresses we had for a given NS by speed, only taking care of placing the first one in front. However we also didn't remove existing entries for a given NS, meaning that if a given IP stopped being advertised it would stay in our NS speeds map and keep being used to determine the fastest NS, even if we would only send queries to the new IPs after the selection. Since we didn't send any query to the old IP anymore, its latency would only keep decaying meaning the computed latency of the corresponding NS would only keep decreasing, completely uncorrelated from its real latency.
This commit removes old entries from the NS speeds map if they are no longer present when we refresh the addresses of a given NS. In addition, it orders all NS IPs by decaying …

rec: Sort NS addresses by speed, remove old ones

---

modules/bindbackend/bindbackend2.cc
modules/bindbackend/bindbackend2.hh
pdns/pdnsutil.cc

While attempting to do a migration from the BIND backend to gsqlite3, several issues arose:
* No masters were set in the target db (#5807)
* Only the last master in the list of masters would be added to the target database
* The BIND backend was not fully aware of native zones
The last issue stemmed from an incomplete implementation in #5115.
This PR aims to fix all these issues.
Note: the b2b-migrate patch for setting the masters correctly and the patch to add the masters to the DomainInfo might need to be backported to 4.0.x.
I have:

BIND backend: Several improvements for b2b-migrate

---

pdns/syncres.cc

We only purged existing entries if we had more than one new entry, because the purging code was too tied to the code sorting the new entries.
I have:

rec: Purge nsSpeeds entries even if we get less than 2 new entries

---

pdns/ws-auth.cc

With the current 301 redirect it is only possible to reset or resize once. Every next duplicate action is replaced by the destination cached in the browser.
I have:

auth: use 302 redirects in the webserver for ringbuffer reset or resize

---

pdns/distributor.hh

'retry once' is no permanent error condition. This is just PowerDNS telling you 'hey something is wrong with my connection to the db server, let me fix this for you'.
I have:

auth: retry once is not an error condition.

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh

RFC 4509 section 3: "Validator implementations SHOULD ignore DS RR
containing SHA-1 digests if DS RRs with SHA-256 digests are present in the
DS RRset."
As SHA348 is specified as well, the spirit of the this line is "use the
best algorithm".
This also means that if a delegation has DS records for multiple keys
(and algos) and only a subset have stronger digests, we will discard the
DS records for the weaker digests.
I have:

Prevent possible downgrade attacks in the recursor

---

pdns/syncres.cc

Print more details of trust anchors. In addition, the --trace output that mentions if data from authoritative servers gets accepted now also prints the TTL and clarifies the 'place' number previously printed.
I have:

--trace logging with more details about trust anchors, plus ttl of auth data

---

pdns/recursordist/test-syncres_cc.cc
pdns/validate.cc

Otherwise there is a very real risk that a `NSEC` will cover a more specific wildcard and we end up with what looks like a `NXDOMAIN` proof but is a `NODATA` one.
Fixes #5882.
I have:

rec: Split NODATA/NXDOMAIN NSEC wildcard denial proof of existence

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

When an entry retrieved from the cache or the negative cache has not been previously validated because the initial query did not ask for validation, we only validate answers if the current zone
state was Secure. This is fine, but we also need to update the state of the current query if the current zone is Insecure or Bogus, even though we don't need to validate the records.
I have:

rec: Fix incomplete validation of cached entries

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/validate.cc

We could have gone Bogus on a positive answer synthetized from a wildcard if the corresponding `NSEC3` had more iterations that we were willing to accept, while the correct result is Insecure.
I have:

rec: Fix going Insecure on NSEC3 hashes with too many iterations

---

pdns/iputils.hh
pdns/test-nmtree.cc

- `NetmaskTree::erase()` now removes "hanging" branches of the tree, if the `cleanup` constructor parameter was set to true
- `NetmaskGroup` now has `deleteMask()` methods that use `NetmaskTree:erase()`
- `NetmaskGroup` gained `lookup()` methods in the process
Grabbed from the weakforced tree:
- https://github.com/PowerDNS/weakforced/commit/d5c916a2d00ec3bec3a09055de5709976e184c95
- https://github.com/PowerDNS/weakforced/commit/1170d8da692c0033e0a80c22447d0c00fb0cb7b2
I have:

Better support for deleting entries in NetmaskTree and NetmaskGroup

---

pdns/secpoll-recursor.cc

Even if the security polling fails because of a `Servfail` or DNSSEC validation, there is no reason to retry right away during the next `houseKeeping()` iteration. On recursor with an important workload, we could end up doing a security polling every second.
I have:

rec: Don't retry security polling too often when it fails

---

pdns/communicator.cc
pdns/distributor.hh
pdns/dnsproxy.cc
pdns/tcpreceiver.cc
pdns/webserver.cc
pdns/ws-auth.cc

This stops us dying while we die. A call to exit() will trigger destructors, which may paradoxically stop the process from exiting, taking down only one thread, but harming the rest of the process.
I have:

use _exit() when we really really want to exit, for example after a fatal error

---

docs/common/api/zone.rst
docs/http-api/zone.rst

Naming stuff is hard. Docs only change.

API docs: reduce RRSets/Records confusion 

---

pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/recursordist/contrib/dns64.lua
pdns/recursordist/docs/lua-scripting/dq.rst

This PR exposes the DNSSEC validation state to Lua hooks that run after the normal resolution process (`nodata`, `nxdomain`, `postresolve`).
This should fix #5888, although the ability to update the validation state from these hooks is postponed to after 4.1.0.
I have:

rec: Add the DNSSEC validation state to the DNSQuestion Lua object

---

pdns/pdns_recursor.cc
pdns/secpoll-recursor.cc

in the recursor secpoll code, we ASSumed the TXT record would be the first record first record we received. Sometimes it was the RRSIG, leading to a silent error, and no secpoll check. Fixed the assumption, added an error.
I have:

in the recursor secpoll code, we ASSumed the TXT record would be the first record

---

docs/manpages/pdnsutil.1.rst
pdns/pdnsutil.cc

This adds a `add-meta` command to `pdnsutil` that can be used to append to existing metadata without clobbering it.
Closes #5853
I have:

pdnsutil: Add add-meta function

---

pdns/pdnsutil.cc

Fixes #3059 
This is the output when eclipsing happens:
```
../../pdns/pdns/pdnsutil --config-dir=. check-zone example.com
Oct 30 17:47:31 Reading random entropy from '/dev/urandom'
Oct 30 17:47:31 gsqlite3: connection to '/home/lieter/src/PowerDNS/pdns-conf/3/pdns.db' successful
Oct 30 17:47:31 gsqlite3: connection to '/home/lieter/src/PowerDNS/pdns-conf/3/pdns.db' successful
[Warning] 'eclipsed.example.com|A' in zone 'example.com' is eclipsed by the zone-cut at 'eclipsed.example.com'
[Warning] 'dsfsdfs.fffff.eclipsed.example.com|A' in zone 'example.com' is eclipsed by the zone-cut at 'eclipsed.example.com'
Checked 5 records of 'example.com', 0 errors, 2 warnings.
```
I have:

pdnsutil: Warn if records in a zone are eclipsed

---

pdns/pdns_recursor.cc

But hey, don't do that.
I have:

rec: Don't crash when asked to run with zero threads

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh

We just have to take care not to try to contact that NS to learn its own IP addresses, because that does not make sense. Before this, we could skip a perfectly valid NS for which we had retrieved the A and/or AAAA entries, for example via a glue.
Also get rid of a flawed calculation based on whether IPv6 was enabled whereas we were only dealing with NS at this point.
Should fix #2758.
I have:

rec: Allow the use of a 'self-resolving' NS if cached A/AAAA exists

---

pdns/pdnsutil.cc
pdns/signingpipe.cc
pdns/signingpipe.hh
pdns/tcpreceiver.cc

The current code detects that the corresponding pipe has been closed, but has no way to know if we were still expecting something from this worker or if this is a "normal" exit. This leads to d_outstanding not being decreased if we expected an answer from the dying worker, meaning we will wait forever for the result.
This patch keeps track of the number of answers we are expecting from each worker, treating a worker exiting while we still expect some answer from its end as an error.
This is a backport of #5777.
(cherry picked from commit e3200e070e7cc4e243676776c41eb806c4edb7a5)
Fixes #5322.
I have:

auth 4.0.x: Handle a signing pipe worker dying with work still pending

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

Before, We would happily accept this POST
I have:

API: Throw exception in metadata endpoint w/ wrong zone

---

pdns/mastercommunicator.cc
pdns/slavecommunicator.cc
pdns/tcpreceiver.cc

This would lead to crashes if the TSIG key was referenced in TSIG-ALLOW-FROM but the key was not in the tsigkeys table.
Closes #5931
I do need to add some regression tests, but need to have a good look at how.
Note: some unchecked calls to `B64Decode` remain in the code, these will be fixed in another PR.
I have:

Check return value for all getTSIGKey calls

---

pdns/dbdnsseckeeper.cc
pdns/dnsseckeeper.hh
pdns/pdnsutil.cc
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

This PR makes sure we can disable DNSSEC via the API, this is equivalent to doing `pdnsutil disable-dnssec`.
Closes #5909
Closes #5910 
I have:

API: Allow disabling DNSSEC

---

docs/changelog/4.1.rst

It was accidentally labeled as `auth` but was only for `rec`.

Remove #5938 from auth-4.1.0-rc3 ChangeLog.

---

pdns/pdns_recursor.cc
pdns/reczones.cc

Add the config-name argument to the definition of configname.
There was a bug where the config-name parameter was not used to change the path of the config file. This meant that some commands via rec_control (e.g. reload-acls) would fail when run against a recursor which had config-name defined. The correct behaviour was present in some, but not all, definitions of configname. 
This PR adds the existing correct behaviour to 2 more places. 
I have:

Edit configname definition to include the 'config-name' argument

---

pdns/recursordist/docs/manpages/pdns_recursor.rst

Point to pdns_recursor and not pdns_server.
I have:

Fix reference to the wrong product

---

pdns/syncres.cc

The iterator is invalidated after being erased, so we have to handle that case explicitly. 
I have:

rec: Fix the use of a deleted iterator in SyncRes::getDSRecords()

---

pdns/dbdnsseckeeper.cc
pdns/ws-auth.cc

Before, we would spawn a new UeberBackend in the DNSSECKeeper, but there
was already a transaction going on, so the rectify would never finish,
as rectifyZone would not return.
I have:

Fix hang when PATCHing zone during rectify

---

pdns/recursordist/negcache.cc
pdns/recursordist/test-negcache_cc.cc

* add the validation status of regular entries to the negative cache dump
* fix the dumped type of DNSSEC records
I have:

rec: Dump the validation status of negcache entries, fix DNSSEC type

---

pdns/resolver.cc

this improves the #5974 situation a bit
instead of `Attempt to print an unset dnsname` we now print `SOA query to 'x.x.x.x:53' produced response without domain name (RCode: Form Error)`
I have:

report remote IP when SOA query comes back with empty question section

---

docs/http-api/cryptokeyitem.rst
docs/http-api/endpoint-cryptokeys.rst
pdns/dnsseckeeper.hh
pdns/ws-auth.cc
regression-tests.api/test_Zones.py
regression-tests.api/test_cryptokeys.py

Add algorithm and bits to the Cryptokey objects and let the POST command accept this CryptoKey object.
I have:

API: Make the /cryptokeys endpoint consistently use CryptoKey objects

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

Fix a bug that prevented `Secure` negative cache entries to be marked as such when they were first inserted, marking them as `Indeterminate` instead. This would require us to validate them a second time for no valid reason.
I have:

rec: Cache Secure validation state when inserting negcache entries

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/validate.cc

There is two reasons you can get a proper `DS` denial:
* Secure to insecure cut, and if we are getting a referral with a `DS` denial, we know that we have to check that the `NS` bit is set as described in section 8.9 of `rfc5155`
* No zone cut inside a secure zone, and then of course the `NS` is not set
When we retrieve the `DS` denial from the negative cache with a validation status of Indeterminate, most likely because validation was not enabled during the query that landed it in the cache, we don't have enough data to know which case we are looking at, so let's just skip the `NS` check.
I have:

rec: Fix DNSSEC validation of DS denial from the negative cache

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/rules-actions.rst
pdns/dnsrulactions.hh

Add burst option to MaxQPSIPRule
I have:

dnsdist: Add burst option to MaxQPSIPRule

---

regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_Interop.py
regression-tests.recursor-dnssec/test_Sortlist.py

We parsed the DNS header flags section as if it were the EDNS flags section. Due to the placement of the QR and DO bit in these sections respectively, this caused all testcases to always see a DO bit.
I have:

fix reading of ednsflags in recursor testing

---

docs/dnssec/operational.rst
pdns/serialtweaker.cc

As alluded to in the docs and warnings in the logs, remove INCEPTION and INCEPTION-WEEK as possible values for SOA-EDIT for 4.1.
I have:

Remove deprecated SOA-EDIT values

---

pdns/opensslsigners.cc

Also fix some missing `free` calls in when dealing with `RSA` keys, but those are only reachable on out of memory so they don't really matter.
I have:

rec:  Don't leak when the loading a public ECDSA key fails

---

pdns/pdns_recursor.cc

When secpool exceeded `max-total-msec`, previously only "Exception while performing security poll" got logged.
Example after change: Exception while performing security poll: Too much time waiting for security-status.secpoll.powerdns.com|DS, timeouts: 5, throttles: 0, queries: 14, 8259msec
I have:

recursor secpoll: improve message on timeout

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh

DNSSEC validation should be disabled for data from local `auth` zones. It was done when the data was retrieved from the local zone, but we tried incorrectly to validate on a cache hit if the initial query did not require validation but a subsequent one did, leading to `Bogus` results. We now check beforehand if the data comes from a local `auth` zone, then do the `CNAME` and regular cache checks.
I have:

rec: Skip validation (including cached entries) for auth zones

---

pdns/packethandler.cc

If our server name contained a dash or a dot, 'dig chaos txt server.id @yourserver' would break in auth.
This applies a minimal fix for the 4.1.early timeframe. I'll leave it up to everyone if this is 4.1.0 material or not. If anyone asks, my vote is 'yes'.
This PR should eventually be succeeded by the result of #6010.
I have:

quote server-id to hosts with - or . in their name get reported again

---

pdns/test-nameserver_cc.cc

(cherry picked from commit 2ff8d3d1913f80d72e4584a957aa89cead69dd81)

Backport #5590: skip v6-dependent test when PDNS_TEST_NO_IPV6 is set in environment.

---

pdns/dnsrecords.cc

fixes #6028
We accidentally enabled compression for ALIAS record content, which is strictly forbidden.
I have:

forbid label compression in ALIAS wire format

---

regression-tests.recursor/RPZ/command

Since we ask for several records that are CNAME to default.example.net. the TTL might have been decreased by the time we get to the last ones. That's fine, the TTL we are interested in are for other records, so we can just ignore the TTL for this exact record.
I have:

rec: Normalize the TTLs for default.example.net. in the RPZ tests

---

pdns/dnsdist-lua.cc

We keep the servers ordered inside their pools because it's easier for the policies that way, so we sort them whenever a new one is added. However we were doing the sorting _before_ the order of the
new server had been set, resulting in the last added server to be sorted based on an order of 0, regardless of its actual order.
Reported by Frank Even (thanks!).
I have:

dnsdist: Sort the servers based on their 'order' after it has been set

---

pdns/dnsdist-tcp.cc
regression-tests.dnsdist/test_TCPKeepAlive.py

We used to close the TCP connection right away on cases where that did not make sense:
- on a cache hit
- on a self-generated answer
- on a servfail answer caused by the lack of usable downstream servers
We still close the TCP connections on drops, dynamic blocks, lack of usable downstream servers without `setServFailWhenNoServer()` set, invalid queries, network errors..
I have:

dnsdist: Keep the TCP connection open on cache hit, generated answers

---

pdns/recursordist/test-negcache_cc.cc

On 32-bit OS with a signed 32-bit `time_t`, we have a known issue with dates later than 2038 in `RecordTextWriter::xfrTime()`. For now we will just use an earlier date than 2038 in these tests since the date has no relevance there.
Fixes #6050.
I have:

rec: Work around a RRSIG year-2038 issue in the negcache unit tests

---

pdns/dnsdist-web.cc
pdns/dnsdistdist/docs/guides/webserver.rst
regression-tests.dnsdist/test_API.py

Pools are not very interesting by themselves, but since caches are associated with them this provides access to the various cache statistics!
I have:

dnsdist: Add Pools, cacheHitResponseRules to the API

---

pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/test-iputils_hh.cc
pdns/misc.cc
pdns/test-iputils_hh.cc

dnsdist's newServer source parameter is documented to take values
of those forms (plus some more):
- v4 address ("192.0.2.1")
- v6 address ("2001:DB8::1")
For consistency, bracketed addresses ("[2001:DB8::1]") should work too, and all of them
should have a test.
Example that would previously "fail":
```
newServer({name="pdns", address="[::1]:5300", source="[::1]"}):setUp()
```
Gives:
```
Dismissing source [::1] because '[::1]' is not a valid interface name
Added downstream server [::1]:5300
```
I have:

Handle bracketed IPv6 addresses without ports

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst

This allows the user to, for example, print certain things during daemon startup but not while connecting a client.
I have:

dnsdist: add inClientStartup() function

---

pdns/syncres.cc

While processing records sent by an authoritative server, some of them could have been added to the cache even though they have a different class than `IN`. We should simply skip these records.
I have:

rec: Don't add non-IN records to the cache

---

pdns/recursordist/test-syncres_cc.cc

This might not fix our apparently random failures, but it will at least remove on possible cause.
I have:

rec: Use the SyncRes time in our unit tests when checking cache validity

---

pdns/nproxy.cc

This used to compile in 4.0.5, in 4.1.0 I get this (on OpenBSD -current amd64):
```
nproxy.cc:303:8: error: use of undeclared identifier 'chroot'
if(chroot(g_vm["chroot"].as<string>().c_str()) < 0 || chdir("/") < 0)
^
nproxy.cc:303:59: error: use of undeclared identifier 'chdir'
if(chroot(g_vm["chroot"].as<string>().c_str()) < 0 || chdir("/") < 0)
^
nproxy.cc:309:8: error: use of undeclared identifier 'setgid'
if(setgid(g_vm["setgid"].as<int>()) < 0)
^
nproxy.cc:312:8: error: use of undeclared identifier 'setgroups'
if(setgroups(0, NULL) < 0)
^
nproxy.cc:317:8: error: use of undeclared identifier 'setuid'
if(setuid(g_vm["setuid"].as<int>()) < 0)
^
nproxy.cc:326:3: error: use of undeclared identifier 'close'
close(null_fd);
^
nproxy.cc:354:6: error: use of undeclared identifier 'fork' …
```

Include unistd.h for chroot(2) et al.

---

pdns/dnsdist.cc

On macOS, none of the freebind/bindany/... options are available, so the var "one" as used for setsockopt is unused. This quiets clang.
I have:

Quiet unused variable warning on macOS

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py
regression-tests.api/test_cryptokeys.py

This commit ensures that any request for a path inside a non-existing
zone returns an HTTP 404 code.
Closes #6074
I have:

API: return 404 for non-existing zones

---

docs/http-api/swagger/authoritative-api-swagger.yaml

Makes it clear that when a zone is PATCHed, pdns operates on each of the RRsets present in the `rrsets` JSON array. In other words, if that array is empty, nothing happens (in particular, nothing is deleted).
I have:

docs: API: clarify what happens if rrsets is empty

---

pdns/dnsdist.cc

If an exception is raised in the responder thread after the outstanding queries counter has been decremented, but before we could mark the state as processed, the same state would be processed again and the counter decremented a second time, either because of a duplicate answer or more likely by the timeout handler.
This commit simply increase back the outstanding counter when such an exception occurs. It might fixes #5652.
I have:

dnsdist: Fix the oustanding counter when an exception is raised

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/validate.cc
pdns/validate.hh

When the positive answer is expanded from a wildcard with `NSEC3`, the closest encloser is not always parent of the `qname`, depending on the number of labels in the initial wildcard.
I have:

rec: Fix the computation of the closest encloser for positive answers

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

We incorrectly merged answers for the same qname and qtype coming from a single packet but from different sections when storing them in the cache. It resulted in duplicates for the IP addresses of some NS, for example.
I have:

rec: Don't cache merged answers from different sections in a single packet

---

docs/modes-of-operation.rst

As briefly discussed on IRC, here is my suggested improvement to the 'modes-of-operation' docs.
I had been wondering if I needed to deploy multi-master mysql replication or something like galera.

Docs: Add note about only needing ro db access

---

pdns/dnsparser.cc

Using a signed 16 bit int as a pointer into a block that can be up to 64kbyte long is a recipe for failure.
I have:

auth: fix out of bounds exception in CAA processing, fixes #6089

---

pdns/lua-auth4.cc

auth: Fix uninitialized index in Lua's DNSPacket::getRRS() binding

---

modules/ldapbackend/ldapbackend.cc

list() did not initialise m_qtype, but get() looks at it. This got introduced in #4922.
Lokely fixes #6097 and #6060.
I cannot actually test this.
I have:

ldapbackend: fix listing zones incl. AXFR

---

pdns/lwres.cc
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_ECS.py
regression-tests.recursor-dnssec/test_Interop.py
regression-tests.recursor-dnssec/test_LargeAnswer.py

The size we used to pass to `arecvfrom()` along with our buffer was off by one byte, resulting in the last byte of our buffer to be uninitialized for answers exactly matching our outgoing buffer size. Since we passed the correct size to `MOADNSParser`, we were reading one bye of uninitialized memory for such answers.
This caused issue with some authoritative servers sending an answer of our exact buffer size, causing a parsing error. We would then retry without `EDNS`, causing `DNSSEC` validation failures for some domains on such authoritative servers.
I have:

 rec: Pass the correct buffer size to arecvfrom()

---

pdns/dbdnsseckeeper.cc
pdns/dnssecinfra.cc
pdns/opensslsigners.cc
pdns/pdnsutil.cc
pdns/ws-auth.cc
regression-tests.api/test_cryptokeys.py

Previously, creating keys with tiny sizes would fail because OpenSSL would not allow it. Newer versions apparently accept sizes lower than the RFCs allow.
Might need to go into the upgrade notes?
I have:

Forbid creating algo 5/8/10 keys with out-of-spec sizes

---

pdns/Makefile.am

Injects moduleobjects to dependency tracking. This fixes issue where pdns_server did not recompile after backend object(s) were changed.
I have:

pdns: Fix dependency tracking for backends

---

pdns/pdnsutil.cc

Fixes #3760.
Simply adds the colours to the console output. Red for deletes. Green for additions.

Add colour to diff output of pdnsutil

---

.travis.yml

Building/testing recursor and dnsdist on this branch is useless.
I have:

auth 4.1.x: limit travis builds to auth only

---

pdns/dns.hh
pdns/dnsdist-console.cc
pdns/dnsdist.cc
pdns/iputils.cc
pdns/iputils.hh
pdns/kqueuemplexer.cc
pdns/misc.cc

These are the minimal changes to make the authoritative server, the
recursor, and dnsdist compile and run properly on NetBSD.
The changes fall into three groups:
1) A number of existing "#if defined" lines already in place for other
BSD variants needed to be expanded with "|| defined(__NetBSD__)" to
get the same effect here.
2) The pthread CPU affinity code in pdns/misc.cc needed changes,
because the underlying cpuset_t is opaque in NetBSD, and one must
use function calls operating on a pointer to a CPU set returned by
cpuset_create(), instead of declaring a local struct and operating
on that.
3) The socket control message interface uses the CMSG_DATA() macro to
fetch optional information for packets, but expects that to assume
a "const struct cmsghdr" declaration.  NetBSD has a …

Changes to compile and run on NetBSD

---

pdns/dnspacket.cc
pdns/dnspacket.hh
pdns/sdig.cc

Remove references to EDNS PING. Option code 5 has been assigned to something else in the meantime.
I have:

Remove obsolete EDNS PING code

---

pdns/dnsdist-cache.cc
pdns/dnsdist-cache.hh
pdns/dnsdist-console.cc
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/rules-actions.rst
pdns/test-dnsdistpacketcache_cc.cc
regression-tests.dnsdist/test_Advanced.py
regression-tests.dnsdist/test_Caching.py

Adds a request Action to set the packetcache TTL used for temporary failures, (= ServFail + Refused).
RFC. Will add docs, test etc when not everyone is shouting at me for this.
Usage example:
```
addAction("deduktiva.com.", TempFailureCacheTTLAction(1))
addAction("244.77.in-addr.arpa.", TempFailureCacheTTLAction(86400))
```
I have:

Add TempFailureCacheTTLAction

---

pdns/dnsname.cc
pdns/test-dnsname_cc.cc

Closes #6018 (commit is now part of this pull request)
https://tools.ietf.org/html/rfc4343#section-2.1
I have:

escaping unusual DNS label octets in DNSName is off by one

---

pdns/dns.cc
pdns/dns.hh
pdns/dnsdist-console.cc
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdist-lua-vars.cc
pdns/dnsdistdist/docs/reference/constants.rst
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_EdnsClientSubnet.py
regression-tests.dnsdist/test_Responses.py

Add ERCodeRule to match on EDNS Extended RCodes.
Separate rule to avoid performance cost for non-EDNS packets. Unclear if this is a good idea for correctness.
I have:

Add ERCodeRule

---

pdns/recursordist/negcache.cc
pdns/recursordist/test-syncres_cc.cc

It turns out that, at least on Linux, doing
```
struct timeval now;
gettimeofday(&now, nullptr);
now.tv_sec - time(nullptr);
```
might be 1, without the time actually going backward. So let's just be consistent in our calls and we should get far less false positives during our tests.
I have:

rec: Don't mix time() and gettimeofday() in our unit tests

---

pdns/dnsdist-lua.cc

`dnsdist -c` would try to honour `snmpAgent(..)`.
I have:

dnsdist: do not connect the snmpAgent from a dnsdist client. Fixes #6163

---

build-scripts/build-auth-rpm
docs/upgrading.rst
modules/gmysqlbackend/4.1.0_to_4.1.1_schema.mysql.sql
modules/gmysqlbackend/Makefile.am
modules/gmysqlbackend/schema.mysql.sql

gmysql-backend: set unsigned attribute on notified_serial column

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/test-syncres_cc.cc
pdns/sdig.cc
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/runtests
regression-tests.recursor-dnssec/test_ECS.py

Adds an option named `ecs-add-for` to the Recursor. Clients matching this NetmaskGroup will get their real IP address in the ECS option in outgoing packets. This should be especially useful for setups running PowerDNS Recursor behind a DNS loadbalancer like dnsdist.
The existing `edns-subnet-whitelist` stays in effect, and not matching clients will get the scope zero fallback. Also, if the client already supplied an ECS option, it will be passed on according to the existing rules. Previously, all clients would get this behaviour, except if they already sent an ECS option.
This commit also restructures the ECS code in SyncRes to be easier to understand.
I have:

Recursor: add ecs-add-for option

---

pdns/syncres.cc

If the `preoutquery` hook was defined but didn't handle the query, the resulting variable was left uninitialized.
I have:

rec: Initialize the result var before calling the preoutquery hook

---

pdns/dnsdist-console.cc

This should fix #6175 
In the ticket I've claimed that documentation and TAB autocompletion have the typo, but I was mistaken, the documentation is already correct.
I have:

fix showTLSContexts tab completion

---

pdns/dnsdistdist/m4/dnsdist_check_gnutls.m4
pdns/dnsdistdist/m4/dnsdist_check_libssl.m4
pdns/dnsdistdist/m4/dnsdist_enable_tls.m4
pdns/dnsdistdist/m4/pdns_check_libcrypto.m4

* Only fail if DNS over TLS is enabled and we don't have either `GnuTLS` or `OpenSSL` libssl
* Switch `GnuTLS` to `auto`, we will detect it but should only link it if DNS over TLS is enabled
I have:

dnsdist: Fix building without libssl

---

pdns/dnsdist.cc
pdns/pdns_recursor.cc

a227f47d3323ca9a532b076f7e1b209dd2962346 broke building on macOS, as it defines TCP_FASTOPEN but not SOL_TCP.
Other code bits already used IPPROTO_TCP with SOL_TCP, f.e. tcpreceiver.cc.
I have:

Fix macOS build: Use IPPROTO_TCP instead of SOL_TCP

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/validate.cc
pdns/validate.hh

(cherry picked from commit e4894ce)
(cherry picked from commit dfbe5d7)
Backport from stable (see #6092).
Closes #6196.

 rec: Fix the computation of the closest encloser for positive answers #6092 

---

pdns/lwres.cc
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_ECS.py
regression-tests.recursor-dnssec/test_Interop.py
regression-tests.recursor-dnssec/test_LargeAnswer.py

(cherry picked from commit 4185f08)
(cherry picked from commit fb611f0)
(cherry picked from commit fb611f0)
Backport from stable (see #6095).
Fixes #6195.

rec: Pass the correct buffer size to arecvfrom()

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

(cherry picked from commit 933299e)
(cherry picked from commit f100caa)
Backport from stable (see #6137).
Fixes #6194.

rec: Don't validate signature for "glue" CNAME

---

pdns/recursordist/test-syncres_cc.cc
pdns/reczones.cc

wim on IRC discovered that there is a chance on startup that the root-server IPs will be incorrect.
I have:

Minimal fix to make primeHints threadsafe

---

pdns/recursordist/test-syncres_cc.cc
pdns/validate.cc

The commits for this PR were cherrypicked from @rgacogne's fixes for the PDNS master branch.
Fixes the DNSSEC validation issue found in Knot Resolver, where a NSEC{3} ancestor delegation is wrongly use to prove the non-existence of a RR below the delegation.
We already had the correct check for the exact owner name, but not for RRs below the delegation.
I have:

rec: Correctly handle ancestor delegation NSEC{,3} for children

---

pdns/dnsdistdist/tcpiohandler.hh

`clang` emits a warning when `std::atomic_flag`'s `ATOMIC_FLAG_INIT` is used as a member initializer. Unfortunately the default constructor leaves in a undefined state, so we need to clear it in the constructor.
Fixes #6184.
I have:

dnsdist: Fix a warning about braces around scalar initializer

---

pdns/pdns_recursor.cc

Copied this over from receiver.cc, as @ahupowerdns pointed out that Auth handles this.
I have:

recursor: abort when unused arguments remain

---

pdns/pdnsutil.cc

pdnsutil only says it can't load your config it it can't, doesn't tell you why. With this PR it does.
I have:

improve error message of pdnsutil if it can't find configuration

---

pdns/dnsproxy.cc
pdns/dnsproxy.hh
pdns/pdns_recursor.cc
pdns/resolver.cc
pdns/resolver.hh
pdns/slavecommunicator.cc

Since several implementations suffer from a race allowing an attacker to insert `UDP` packets between the `bind()` and `connect()` calls from a different source that the expected one (see [1]), this PR adds additional checks: 
* Check the source address with `recvfrom()` in the recursor's `handleGenUDPQueryResponse()` to prevent `bind()`/`connect()` race
* Store the remote address in the auth's `DNSProxy` and use `recvfrom()`, so we can prevent a race condition if a packet arrives between `bind()` and `connect()`
* Check the remote peer address in the auth's `Resolver` when we receive a response since the socket is not connected
[1]: http://seclists.org/oss-sec/2017/q4/224
I have:

Check more thoroughly the source of UDP answers

---

pdns/remote_logger.cc
pdns/remote_logger.hh

Instead of waiting to have a message to send and failing to send it, causing some messages to be lost in some cases because we would detect the failure too late in the process.
I have:

Keep trying if the first connection to the remote logger failed

---

modules/remotebackend/remotebackend.cc
modules/remotebackend/remotebackend.hh
modules/remotebackend/test-remotebackend.cc
pdns/backends/gsql/gsqlbackend.cc
pdns/backends/gsql/gsqlbackend.hh
pdns/dnsbackend.cc
pdns/dnsbackend.hh

time_t can be bigger, which could lead to overflow/underflow issues.
Closes #1010
I have:

Change from time_t to uint32_t for serial in calculateSOASerial

---

pdns/syncres.cc
pdns/syncres.hh

Fix for #5187 by slightly abusing our current tracking mechanism by stuffing our ComboAddress in as a DNSName and reusing much of shuffleInSpeedOrder.
This also prints a + in the trace log if the query is RD and - otherwise. Very much like previous versions did.
Pull request originally #5207
This produces log entries and usage such as:
```
./pdns_recursor --trace='.*' --forward-zones-recurse=".=7.7.7.7;7.6.6.6:55;[::1]:6000;8.8.8.8" --forward-zones="google.com=7.7.7.7;8.8.8.8" --local-port=5353 --socket-dir=/tmp --dnssec=off
Jan 10 16:37:06 [2] test3: Cache consultations done, have 1 NS to contact
Jan 10 16:37:06 [2] test3: Domain has hardcoded nameservers
Jan 10 16:37:06 [2] test3.: Nameservers: +8.8.8.8:53(12.85ms), +7.6.6.6:55(913.56ms), +[::1]:6000(913.57ms),
Jan 10 16:37:06 [2] …
```

Keep track of forward-zones NS speeds

---

pdns/mtasker.hh

Throwing an exception uses libgcc's stack unwinder. On mips64el
the unwinder will overflow the default stack size of 8K. In turn
the return ucontext gets overwritten, resulting in a jump into
garbage.
This is Debian bug #887034. Patch is applied in Debian pdns-recursor 4.1.0-3. Build logs will be at https://buildd.debian.org/status/package.php?p=pdns%2drecursor
I have:

Increase MTasker stacksize to avoid crash in exception unwinding

---

pdns/pdns_recursor.cc
pdns/xpf.cc

This fixes CID 1385372 and CID 1385373.
I have:

Fix two Coverity issues

---

docs/manpages/dnsreplay.1.rst
pdns/dnsreplay.cc

Allowing to replay queries received/sent from/to another port than 53.
I have:

Add an --initial-port option to dnsreplay

---

pdns/rfc2136handler.cc

Improve two DNSUPDATE log messages.
Before:
```
UPDATE (11434) from 10.2.1.6 for dynamic.home.zeha.at: Failed PreRequisites check, returning 6
UPDATE (10230) from 10.2.1.6 for dynamic.home.zeha.at: Failed PreRequisites check, returning NXRRSet
```
Hopefully, after:
```
UPDATE (x) from 10.2.1.6 for dynamic.home.zeha.at: Failed PreRequisites check, returning YXDomain
UPDATE (x) from 10.2.1.6 for dynamic.home.zeha.at: Failed PreRequisites check (RRs differ), returning NXRRSet
```
I have:
Haven't actually run it!

Improve DNSUPDATE prereq check log messages

---

modules/bindbackend/bindbackend2.cc

`queueReloadAndStore` already caught `PDNSException` and `std::exception`, but `loadConfig` (called at init time) only caught `PDNSException` and `std::system_error`, neglecting `std::runtime_error`.
This just duplicates the `PDNSException` handling to `std::exception`.
Before:
```
% ../pdns/pdnsutil --config-dir=. check-zone powerdnssec.org
Jan 05 22:20:16 Caught an exception instantiating a backend, cleaning up
Jan 05 22:20:16 UeberBackend destructor called, removing ourselves from instances, and deleting our backends
Error: name too long to append
```
After:
```
% ../pdns/pdnsutil --config-dir=. check-zone powerdnssec.org
error at 2018-01-05 22:17:15 +0100 parsing 'powerdnssec.org' from file '../regression-tests/zones//powerdnssec.org': name too long to append
Jan 05 22:17:15 …
```

bindbackend: handle std::exception during startup zone-parsing

---

pdns/ixfr.cc
pdns/slavecommunicator.cc

Makes IXFR client actively close connection to IXFR server when IXFR is considered to be done. Right now the client would keep reading data from socket even server has sent out all the IXFR responses, until server close the TCP connection. The whole transaction can last for 30s or longer, depends on IXFR server.
Fix bug.
Say a.test.com has two A records.
```
a.test.com.  IN  A  10.0.0.1
a.test.com.  IN  A  10.0.0.2
```
IXFR client receives an add change that a.test.com has another A record 10.0.0.3. The update will remove all A records of a.test.com and only keep the newly added one. The final result will be:
```
a.test.com.  IN  A  10.0.0.3
```
I have:

IXFR: correct behavior of dealing with DNS Name with multiple records; speed up IXFR transaction

---

docs/modes-of-operation.rst

https://doc.powerdns.com/md/authoritative/modes-of-operation/ claims  that ```Notifications are only sent for domains with type MASTER in your backend.``` but this can (fortunately) be controlled by the `slave-renotify` settings which was not mentioned.
I have:

mention slave-renotify in notification warnings

---

docs/settings.rst
pdns/dnsdistdist/docs/advanced/timedipsetrule.rst
pdns/dnsdistdist/docs/reference/comboaddress.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/dnscrypt.rst
pdns/dnsdistdist/docs/reference/dnsname.rst
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/docs/reference/ebpf.rst
pdns/dnsdistdist/docs/reference/netmaskgroup.rst
pdns/dnsdistdist/docs/reference/protobuf.rst
pdns/recursordist/docs/changelog/4.1.rst
pdns/recursordist/docs/lua-scripting/comboaddress.rst
pdns/recursordist/docs/lua-scripting/dnsname.rst
pdns/recursordist/docs/lua-scripting/dnsrecord.rst
pdns/recursordist/docs/lua-scripting/dq.rst
pdns/recursordist/docs/lua-scripting/functions.rst
pdns/recursordist/docs/lua-scripting/netmask.rst
pdns/recursordist/docs/lua-scripting/statistics.rst
pdns/recursordist/docs/running.rst

This PR fixes some issues with the documentation regarding Lua objects. The layout is improved by this.
*before*
*after*
Several other small rendering issues and missing refs are fixed as well
I have:

docs: Ensure Lua objects and their attributes are layed-out

---

build-scripts/build-auth-debian
build-scripts/build-auth-rpm
build-scripts/debian-authoritative/pdns-tools.install
build-scripts/debian-authoritative/pdns-tools.manpages
docs/Makefile.am
docs/conf.py
docs/manpages/ixfrdist.1.rst
pdns/.gitignore
pdns/Makefile.am
pdns/dnsparser.cc
pdns/ixfrdist.cc
pdns/ixfrdist.service.in
pdns/ixfrutils.cc
pdns/ixfrutils.hh
pdns/ixplore.cc
pdns/misc.cc
pdns/misc.hh
pdns/sstuff.hh

This tool will AXFR any number of zones from a DNS server, store them on-disk and allow clients to request SOA, IXFR and AXFR. It will generate the IXFR on the fly.
PR opened for thorough review and brainstorming on improvements and features.
I have:

New tool: ixfrdist

---

pdns/dnsdist.cc

t_uuidGenerator is now used in makeRuleID, but was only present under HAVE_PROTOBUF.
Found by @Habbie.
I have:

dnsdist: fix build without protobuf

---

regression-tests.dnsdist/test_Dnstap.py

Apparently the dnstap listener does not always shut down correctly. Using a different port than the protobuf tests avoids an annoying failure.
I have:

dnsdist: avoid port reuse in tests

---

pdns/ixfrdist.cc

I haven't done a real test but looking at the code, it seems that we do not check if our serial is up to date when running in non-verbose mode.
I have:

ixfrdist: Check the serial even if verbose is off

---

regression-tests.dnsdist/dnsdisttests.py

Fixes `ValueError: unsupported format character ',' (0x2c) at index 26` when running the tests against a dnsdist without libsodium compiled in.
I have:

dnsdist: fix error formatting

---

pdns/ixfrdist.cc

It was found that ixfrdist would crash with a segfault under certain circumstances. It seems that we would accidentally write a nullptr into `g_soas` on an update exception. This PR ensures we only write a SOA to g_soas when an update is fully done.
Also, protect every read access to `g_soas` with the mutex.
I have:

ixfrdist: Prevent a nullptr exception and guard reads/writes

---

docs/changelog/4.1.rst

PRs part of this release are:
* 6261, 6260 - backports PRs, originals are
6261:
* 6077
* 6048
* 6172
* 6134
* 6129
* 6122
* 6103
* 6041
6260:
* 6029
Update changelog for auth-4.1.1 release
I have:

Update 4.1 changelog for auth-4.1.1 release

---

docs/http-api/swagger/authoritative-api-swagger.yaml

swagger-codegen was throwing errors about invalid syntax and unexpected types. allOf requires to specify a mixed type array, which is syntactically expressed by "-"
See:
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/
https://swagger.io/docs/specification/data-models/data-types/#array

Making swagger code-gen happy.

---

pdns/tcpreceiver.cc

When a client has no permission to AXFR a zone from a server, the following diagnostics are logged:
```
AXFR of domain 'example' denied: client IP 10.0.0.1 has no permission
AXFR of domain 'example' failed: 10.0.0.1 cannot request AXFR
```
I feel the word _cannot_ is incorrect and should be _may not_ to indicate permission.
I have:

Change wording to indicate may not XFR instead of cannot

---

pdns/ixfrdist.cc
pdns/resolver.cc
pdns/resolver.hh

When transferring huge zones, we might not make in the hardcoded 10 seconds. This PR makes `AXFRRetriever::getChunk()` and `timeoutReadn()` get an optional timeout parameter and hooks it up to ixfrdist.
We'll nee dto hook this up to the recursor and the auth in the future as well.
I have:

ixfrdist: Allow setting the inbound AXFR timeout

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdist.hh

Removes the class QTag wrapper around std::unordered_map, which did not provide any value as far as I could see.
I have:

dnsdist: Clean up QTag code

---

pdns/dnsdist-lua-vars.cc
pdns/dnsdist-lua.hh
pdns/dnsdist-snmp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/DNSDIST-MIB.txt
pdns/dnsdistdist/docs/rules-actions.rst
pdns/dnsdistdist/docs/statistics.rst
regression-tests.dnsdist/test_API.py

Previously, an error from inside Lua code in an LuaAction or LuaResponseAction would cause the query to not be answered at all, with no diagnostics.
- Creates a new statistic item: rule-servfail
- Logs Lua errors with warnlog
- Failed Lua code causes an immediate ServFail now
Example log:
```
> LuaAction failed inside lua, returning ServFail: [string "chunk"]:21: attempt to call a nil value (global 'rl')
```
I have:

dnsdist: Report Lua(Response)Action failures

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua.hh

Move implementation code out of header file. Allows the dolog.hh include to go away again, and hopefully less recompiles in the future.
I have:

dnsdist: Move Lua(Response)Action operator() out of header file

---

regression-tests.dnsdist/requirements.txt

Use protobuf 3.x library when running dnsdist regression tests on macOS.
(`protobuf` from brew is 3.5.1.)
Makes this error go away for me:
```
======================================================================
ERROR: Failure: TypeError (__init__() got an unexpected keyword argument 'syntax')
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/ch/Source/Deduktiva/pdns/regression-tests.dnsdist/.venv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
addr.filename, addr.module)
File "/Users/ch/Source/Deduktiva/pdns/regression-tests.dnsdist/.venv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
return self.importFromDir(dir_path, fqname)
File …
```

dnsdist: In tests use protobuf3 on macOS

---

pdns/pdnsutil.cc

Make `replace-rrset` tell the user to use the `replace-rrset` command, rather than `replace-record`.
Replaces the `replace-record` command to `replace-rrset` in the syntax help for the `replace-rrset` command.
I have:

Fix syntax error for replace-rrset

---

pdns/reczones.cc

Before, if the `refresh` was not set in the lua-config file's
`rpzMaster` statement, we would keep trying to get delta's the whole
time. This commit ensures we update the zone's refresh config to the
value from the AXFR'd zone (if not set in the config).
This issue has been present since #6237
I have:

rec: Ensure we don't hammer the RPZ master server

---

pdns/ixfrdist.cc
pdns/ixfrutils.hh

This prevents us going to the disk for every incoming query.
I have:

ixfrdist: Keep latest AXFR and `--keep` IXFR's in memory

---

pdns/mastercommunicator.cc
pdns/misc.cc
pdns/misc.hh
pdns/resolver.cc
pdns/rfc2136handler.cc
pdns/slavecommunicator.cc

If either is unset, don't send out notifications or AXFR requests using
that address family.
This PR probably needs some docs and some tests. But already opened for a code-review
I have:

auth: make outgoing-query-address{,6} behaviour equivalent

---

pdns/ixfrdist.cc

spotted by @rgacogne
We would read the size of the buffer on a possibly blocking call.
I have:

ixfrdist: Read only the amount of bytes we need

---

pdns/rec-lua-conf.cc
pdns/recursordist/docs/lua-config/rpz.rst
pdns/reczones.cc
pdns/resolver.cc
pdns/resolver.hh
pdns/rpzloader.cc
pdns/rpzloader.hh

Backports #6290 and the resolver.{cc,hh} part of #6268.
I have:

Backport: rec: Implement settable AXFR timeout for RPZ

---

pdns/dnsdistdist/docs/rules-actions.rst

Contrary to `MaxQPSIPRule()`, `MaxQPSRule()` matches the traffic below the QPS limit, not above.
We should deprecated one of those two and replace it with a new selector whose behavior is consistent with the other one.
I have:

dnsdist: Fix the documentation for MaxQPSRule()

---

pdns/resolver.cc
pdns/resolver.hh

We used to apply the default timeout of 10s to retrieve the chunk's length even if we were passed a different one.
I have:

ixfrdist: Also respect the AXFR timeout for the chunk's length

---

pdns/resolver.cc
pdns/resolver.hh

We used to apply the default timeout of 10s to retrieve the chunk's length even if we were passed a different one.
(cherry picked from commit b726c12720f31a6cdd94a06ccb3a427a96f19669)
I have:

Backport 6302: ixfrdist: Also respect the AXFR timeout for the chunk's length

---

pdns/recursordist/Makefile.am

Remove leftover -I from recursor Makefile.
I have:

Remove leftover -I ext/rapidjson

---

pdns/recursor_cache.cc

This would lead to us not refreshing ECS-varying answers in the cache, and therefore an even more depressed cache rate.
Thanks to @liordot who found the issue & provided a fix in #6241. This code has been tested by @paddg where it slightly reduced CPU load.
The fix seems trivial, but a second look is required.
I have:

Fix ECS-based cache entry refresh code

---

build-scripts/debian-recursor/pdns-recursor.dirs
build-scripts/debian-recursor/rules

Modifies the debian build scripts so that the recursor.conf by default features include-dir=/etc/powerdns/recursor.d (and that said directory is created during install)
I added this because it's a QOL feature that as far as I can tell does not interfere with unmodified existing installs.
Documentation seems superfluous since this PR shortdesc is already longer than the entirety of the patch.
I have:

Add a default include-dir for recursor as per auth

---

pdns/pdnsutil.cc

With this PR, pdnsutil will error about leftover MBOXFW records (as requested in #6064), and any other unknown records stored in the database.
I have:

make check-zone error on rows that have content but shouldn't

---

pdns/dnssecinfra.cc
pdns/pdnsutil.cc
pdns/pkcs11signers.cc
pdns/pkcs11signers.hh

Some devices have slots that do not start from 0, so we ask for the slot IDs from the device and iterate those instead of just guessing the slot ID.
I have:

pkcs11signers: Fix yubikey NEO to work

---

pdns/rfc2136handler.cc
regression-tests/tests/1dyndns-cname-and-other-data/command
regression-tests/tests/1dyndns-cname-and-other-data/description
regression-tests/tests/1dyndns-cname-and-other-data/expected_result
regression-tests/tests/1dyndns-cname-and-other-data/skip.nodyndns

When sending a DNS UPDATE with a CNAME and other data addition for the same name, we will send a FORMERR back to the client.
When an addition of a CNAME is attempted and there is other data at that name (that is not removed in the same update), send a REFUSED to the client.
When data is added and there is a CNAME at that name (that is not removed in the same update), send a REFUSED to the client.
Closes #6270 
I have:

dnsupdate: Reject updates if they would lead to CNAME+Other data

---

pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/docs/metrics.rst
pdns/syncres.cc
pdns/syncres.hh

We only considered a query a cache miss if we had to do at least one outgoing query, but having to look up into one of the internally hosted zone (auth-zones) should count as a cache miss too.
I have:

rec: Count a lookup into an internal auth zone as a cache miss

---

pdns/recursor_cache.cc
pdns/recursordist/test-recursorcache_cc.cc

We don't need to update the ECS index when replacing an existing entry, except if the entry has expired, because then we might have removed it from the ECS index.
I have:

rec: Only update the ECS cache index when needed

---

build-scripts/build-auth-debian
build-scripts/build-auth-rpm
build-scripts/debian-authoritative/pdns-server.install
docs/Makefile.am
modules/luabackend/lua_functions.cc
modules/luabackend/test2/pdns-luabackend.lua
modules/luabackend/test2/pdns_control
modules/luabackend/test2/runtest.pl
regression-tests.recursor/comments-in-forward-zones-file/command
regression-tests.recursor/comments-in-forward-zones-file/expected_result
regression-tests/runtests
regression-tests/start-test-stop

This PR collects fixes for various failures currently happening on our builders.
I have:

unbreak various things

---

pdns/dnsdist-lua-bindings.cc
pdns/fstrm_logger.cc
pdns/fstrm_logger.hh
pdns/recursordist/docs/lua-config/protobuf.rst
pdns/remote_logger.cc
regression-tests.dnsdist/dnsdisttests.py

Fixes a nullptr deref under --check-config, found by Quad9.
To make this work, RemoteLogger with asyncConnect now waits for the first message before  connecting. FrameStreamLogger created in client mode will not create its IO Thread, making logging impossible.
All tests will now run --check-config on their generated configuration files before running, so errors like this one should be caught by the tests.
I have:

dnsdist: create RemoteLoggers in client mode, but avoid connecting

---

pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/statistics.rst

Clean up some statistics accounting which was handled inconsistently before:
- Before, UDP selfAnswered was increased even if no response was sent, while this isn't done for TCP or UDP/TCP cacheHits. Now it is only increased if a response goes out.
- ~~Global latency stats were not updated for TCP at all~~ - to avoid changing current behaviour, this is dropped
- Treat selfAnswered, cacheHits, and noPolicy the same (=latency 0) for global latency stats, both UDP and TCP
Additional stats issues that this PR does not fix:
- UDP and TCP update aclDrops, nonCompliantQueries, queries at different times
- nonCompliantQueries is increased either before or after queries is increased
I have:

dnsdist: unify global stats accounting

---

pdns/webserver.hh
pdns/ws-auth.cc
regression-tests.api/runtests
regression-tests.api/runtests.py
regression-tests.api/test_Basics.py
regression-tests.api/test_Servers.py
regression-tests.api/test_Zones.py
regression-tests.api/test_cryptokeys.py
regression-tests.api/test_helper.py

Fixes #4482.
Also fixes tests for py3k.
I have:

Auth API: return status 409 if domain already exists (+test cleanup

---

pdns/Makefile.am
pdns/calidns.cc

This adds the possibility to simulate much more clients using `calidns` if the receiver is capable of handling the `EDNS Client Subnet` option.
The current code only supports `IPv4`, sorry about that.  
I have:

calidns: Add the --ecs parameter to add random ECS values to queries

---

pdns/dnsdistconf.lua

Update deprecated syntax used in dist configuration file
See https://dnsdist.org/rules-actions.html?highlight=qpspoolrule#addQPSPoolRule
fix #6347 
I have:

dnsdist: Update deprecated syntax used in dist configuration file

---

pdns/zoneparser-tng.cc

Before this commit, you could crash pdnsutil edit-zone this way:
1) run pdnsutil edit-zone example.org
2) add a line saying: IN TXT ("
3) exit editor
I suspect other consumers of the zone file parser could also crash this way.
After this commit, we don't crash but we fail to report the line number.
There is room for more improvement here.
I have:

rather than crash, sheepishly report no file/linenum

---

pdns/dnsdist-lua-inspection.cc
pdns/dnsdist-lua.cc
pdns/statnode.cc
pdns/statnode.hh

- We kept track of the remote addresses for each `StatNode` entry, copying them around several times, while we never used them in `dnsdist` (`dnsscope` does)
- The `exceed*` functions (or more precisely the `filterScore()` one) sorted their return based on the score. We didn't used that (undocumented) property, and it led to unneeded copy of entire maps
- Use a `reserve()`'d `unordered_map` instead of a `map` for `exceed*` operations
I have:

dnsdist: Speed up the processing of large ring buffers

---

pdns/dnsdist-lua.cc

Most of our dynamic block examples pass the value returned by one of the `exceed*()` functions to `addDynBlocks()`, which is how it was designed. However `addDynBlocks()` will copy and update the state holder even if that value is empty. If the state is large, for example because we blocked a larger set of addresses, this does hurt.
I have:

dnsdist: Only update the DynBlock state holders when needed

---

pdns/dnsdist-lua-inspection.cc

Typo introduced in #6350, not a big issue since both rings should have roughly  the same size after a while.
I have:

dnsdist: Reserve according to the _query_ ring size in exceedQueryGen

---

pdns/dnsdist-carbon.cc
pdns/dnsdist.hh
regression-tests.dnsdist/test_Carbon.py

This PR adds a metric (`servers-up`) to be pushed to carbon for servers in a pool which are in a state of `UP`. There already existed a metric for `servers` but that did not offer insight into the health of a `ServerPool`, rather was just a count for the total list of downstreams irrespective of their `State`. There did not appear to be an open issue/request for this.
I have:
Proposed Metric:
```
dnsdist.carbonname1.main.pools._default_.servers-up 2 1520457187
```
Regression Test Output:
```
$ DNSDISTBIN=../pdns/dnsdistdist/dnsdist ./runtests test_Carbon.py
Generating a 2048 bit RSA private key
.......................................................................+++
...............................................+++
writing new private key to 'ca.key'
-----
Generating a 2048 bit RSA …
```

Add Metric "server-up" Count to Carbon Reporting

---

build-scripts/debian-authoritative/pdns-backend-lua2.examples

The example file in debian packages was wrong.
I have:

build-scripts: Use correct example file for lua2

---

pdns/dnsdist-lua2.cc
pdns/statnode.cc
pdns/statnode.hh

Backport of #6350 to dnsdist-1.2.x.
I have:

dnsdist: Backport speed improvements for large ring buffers (6350)

---

docs/modes-of-operation.rst
pdns/lua-auth4.cc

Also fix a typo in the example of the auth documentation about axfr filters.
Fix #6228 
I have:

auth: fix handling of user-defined axfr filters return values

---

pdns/pdnsutil.cc

Add quiet modifier to pdnsutil rectify-all-zones command to only output on error.
Also properly exit with a non-zero code when an error is encountered.
Fix #6245 
I have:

auth: add quiet modifier to pdnsutil rectify-all-zones command

---

m4/pdns_check_libsodium.m4
pdns/dnscrypt.cc
pdns/dnscrypt.hh
pdns/dnsdist-dnscrypt.cc
pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua-vars.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/dnscrypt.rst
pdns/test-dnscrypt_cc.cc
regression-tests.dnsdist/dnscrypt.py
regression-tests.dnsdist/test_DNSCrypt.py

This PR adds support for `DNSCrypt`'s `xchacha20` algorithm, as well as multiple actives `DNSCrypt` certificates. It also removes the `getOldCertificate()` and `getCurrentCertificate()` methods on `DNSCrypt` bind objects, because I couldn't find a meaningful way to emulate them with `n` active certificates. Sorry for breaking compatibility!
I have:

dnsdist: Implement xchacha20 support for DNSCrypt

---

pdns/devpollmplexer.cc
pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst
pdns/epollmplexer.cc
pdns/kqueuemplexer.cc
pdns/mplexer.hh
pdns/pollmplexer.cc

This is very useful if the backend is distributing queries based only on (source IP, source port, destination IP, destination port), which is for example the case of PowerDNS Recursor with several
threads, `reuseport` set and `pdns-distribute-queries` not set.
I have:

dnsdist: Add an option to use several source ports toward a backend

---

pdns/lua-recursor4-ffi.hh
pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/recursordist/Makefile.am
pdns/recursordist/lua-recursor4-ffi.hh
pdns/recursordist/test-syncres_cc.cc

Add a new `gettag_ffi()` hook, which is an FFI-friendly version of the existing `gettag()`.
I have:

rec: Add a new Lua FFI hook, gettag_ffi

---

pdns/dnsdist-lua.cc

The build was failing because the `DNSCryptExchangeVersion` type was not defined.
I have:

dnsdist: Fix building when DNSCrypt support is not enabled

---

build-scripts/travis.sh
modules/pipebackend/coprocess.cc
modules/remotebackend/pipeconnector.cc
pdns/common_startup.cc
pdns/dnsdist-tcp.cc
pdns/dnstcpbench.cc
pdns/ixfr.cc
pdns/misc.cc
pdns/nameserver.cc
pdns/nameserver.hh
pdns/opensslsigners.cc
pdns/pdns_recursor.cc
pdns/pkcs11signers.cc
pdns/rfc2136handler.cc
pdns/sodcrypto.cc

Variable-length arrays are not supported by the C++ standard, and make it very easy to forget how big the array is, which is an issue with small stacks.
In most cases we were already copying the content of the `VLA` to a string or a vector right away anyhow, so we might actually see a gain.
This PR also adds `-Werror=vla` on Travis so we don't use `VLA` by mistake in the future.
I have:

Remove VLAs

---

pdns/dnsdist-carbon.cc
pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdist.hh

We used to hold the `Lua` lock while applying the load-balancing policy to select a backend, which is only needed by `Lua` policies, not core ones. We do need a lock to make sure that the vector of servers is not altered under our feet, but a per-pool read-write lock is enough and reduces contention a lot, especially when the `maintenance` thread is doing some heavy-lifting.
I have:

dnsdist: Use a separate lock for accessing the pool's servers

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst

Add min-udp-source-port, max-udp-source-port and avoid-udp-source-port variables to tune the range of ports we use
This should address #6321 
I have:

recursor: Add options to tune udp source ports

---

pdns/dnsdist-lua2.cc

The `exceed*()` functions return a different kind of map since 2e32ba8d17631d3c32f6a29922fba0dfd724ba3a and I forgot to update `addBPFFilterDynBlocks()` 
accordingly.
I have:

dnsdist: Unbreak addBPFFilterDynBlocks()

---

pdns/dnsdist-lua-inspection.cc

Debian Jessie's compiler reports that `cutoff` might be used uninitialized in `statNodeRespRing()`. This is a false positive, but let's just initialize it no matter what so the compiler stops whining.
I have:

dnsdist: Work around a false positive in statNodeRespRing()

---

pdns/dnsdist-web.cc

We keep having issues with large values, and I see no good reason to keep using `int` instead of `double` in that code.
Hopefully closes #6211.
I have:

dnsdist: Use double instead of int in the API

---

pdns/misc.cc

This very slightly improves the #4450 situation. Ideally we'd log name/type but we don't have that information in the right place.
I have:

report unparseable data in stoul invalid_argument exception

---

pdns/pdns_recursor.cc
pdns/recursordist/configure.ac

See discussion https://github.com/PowerDNS/pdns/issues/6398#issuecomment-376434065
Fix #6398 
I have:

rec: fallback to std::set when boost::container::flat_set is not available

---

pdns/pdns_recursor.cc
pdns/recursordist/configure.ac
pdns/recursordist/docs/settings.rst

Only notice if boost flat_set are not available instead of throwing an error.
The API was clear though.
Fix #6398
I have:

rec: really fallback to std::set when boost::container::flat_set is not available

---

docs/backends/lua2.rst
modules/lua2backend/lua2api2.hh
modules/lua2backend/regression-tests/lua2-dnssec.lua

This should make the lua2backend tests pass more reliably. It also fixes the documentation title.
I have:

Lua2 fixes

---

pdns/dnspacket.cc

It might be a pretty common error if there is a bad recursor or client,
leading to potential a logging overdose.
cc: @cmouse 
I have:

auth: lower 'packet too short' loglevel

---

pdns/common_startup.cc
pdns/dnspacket.cc
pdns/dnspacket.hh

DNSPacket exposes the aptly named getMaxReplyLen() function which we mistakenly thought meant this was the supplied EDNS buffer size. In some places we want to know the actual raw EDNS buffer size. This PR adds that, and hooks it up to our logging.
I have:

add actual EDNS buffer size logging, not just our interpretation

---

pdns/dnsdist-lua.cc

Calling newServer with something like "foo:53" would previously end up like this (at least in assert-enabled builds):
```
Error creating new server with address :53: Unable to convert presentation address ':53'
Assertion failed: (obj), function operator(), file ./ext/luawrapper/include/LuaContext.hpp, line 1149.
./run-dist: line 3: 18014 Abort trap: 6           ../../pdns/pdns/dnsdistdist/dnsdist --config dnsdist.lua
```
After this change:
```
Error creating new server with address :53: Unable to convert presentation address ':53'
Listening on 127.0.0.1:5400
...
```
IIRC running newServer from a remote console this would also crash the daemon process.
I have to say that starting up with the invalid newServer is bad, but judging by the code this was the intended behaviour.
I've pushed the …

dnsdist: avoid LuaWrapper assert on errors in newServer()

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/test_Caching.py

Add an option so that we add `ECS` information to the query before looking up the cache, even if no backend has been selected. This is useful when all backends in a pool use `ECS`, causing the cached entries to be hashed with `ECS` information.
Fixes #6098.
I have:

dnsdist: Optionally add ECS for cache lookup when all backends are down

---

pdns/dnsdist-console.cc
pdns/dnsdist-dynblocks.hh
pdns/dnsdist-lua-inspection.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-dynblocks.hh
pdns/dnsdistdist/docs/guides/dynblocks.rst
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/test_DynBlocks.py

The new `DynBlockRulesGroup` object is designed to make the processing of multiple rate-limiting rules faster by walking the query and response buffers only once for each invocation, instead of once per existing `exceed*()` invocation.
For example, instead of having something like:
```
function maintenance()
addDynBlocks(exceedQRate(30, 10), "Exceeded query rate", 60)
addDynBlocks(exceedNXDOMAINs(20, 10), "Exceeded NXD rate", 60)
addDynBlocks(exceedServFails(20, 10), "Exceeded ServFail rate", 60)
addDynBlocks(exceedQTypeRate(dnsdist.ANY, 5, 10), "Exceeded ANY rate", 60)
addDynBlocks(exceedRespByterate(1000000, 10), "Exceeded resp BW rate", 60)
end
```
The new syntax would be:
```
local dbr = dynBlockRulesGroup()
dbr:setQueryRate(30, 10, "Exceeded query rate", 60) …
```

dnsdist: Add DynBlockRulesGroup

---

pdns/common_startup.cc
pdns/dnsproxy.cc
pdns/dnsproxy.hh

The dnsproxy does not support TCP. For questions that come in over TCP that rely on ALIAS expansion, this PR short circuits the request via the stub resolver, instead of the proxy.
I have:

add TCP support for ALIAS

---

ext/luawrapper/include/LuaContext.hpp
pdns/dnscrypt.cc
pdns/dnscrypt.hh
pdns/dnsdist-dynbpf.hh
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-lua.hh
pdns/dnsdist-snmp.cc
pdns/dnsdist-snmp.hh
pdns/dnsdist.hh
pdns/dnsdistdist/tcpiohandler.cc
pdns/dnsname.hh
pdns/dnsparser.cc
pdns/iputils.hh
pdns/lock.hh
pdns/misc.hh
pdns/pollmplexer.cc
pdns/statnode.cc

Mostly non-noticeable performance hints:
- pass shared pointers by reference whenever possible
- use pre-increment instead of post-increment for non-primitive types
- use initialization list instead of assigning values in the constructor's body
`LuaWrapper` moving the function variable before using it again might be a real issue though, and the locks' move constructor might have become one at some point.
I have:

dnsdist: Fix warnings reported by clang's analyzer and cppcheck

---

regression-tests.nobackend/tinydns-data-check/expected_result

For unexplained reasons, #6377 was green on Travis even though the hash in this test was wrong. Master then went red. This PR should fix that.
I have:

update data.cdb hash after merge of #6377

---

pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/guides/downstreams.rst
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_HealthChecks.py
regression-tests.dnsdist/test_TCPLimits.py

This PR allows the use of a `Lua` function to dynamically set the `QName`, `QType`, `QClass` and `dnsheader` of health check queries.
Closes #6161.
I have:

dnsdist: Add `checkFunction` to implement a dynamic health check

---

pdns/dnscrypt.hh

`time_t` is signed there.
I have:

dnsdist: Fix a sign comparison warning on armv7l

---

build-scripts/travis.sh

(cherry picked from commit 0e62797ed1cc33cbc44cbbc58d69da400cec85b1)
The nominum FTP site is unreliable/slow.
I have:

backport #6360: use mirror for dnsperf

---

pdns/recursordist/test-syncres_cc.cc

Backport of #6086
rec: Use the SyncRes time in our unit tests when checking cache validity 
This might not fix our apparently random failures, but it will at least
remove on possible cause.
Debian pdns-recursor 4.1.1-1 shipped with this patch.
I have:

Backport of #6086

---

pdns/mtasker.hh

Backport of #6179
Throwing an exception uses libgcc's stack unwinder. On mips64el
the unwinder will overflow the default stack size of 8K. In turn
the return ucontext gets overwritten, resulting in a jump into
garbage.
This is Debian bug #887034. Patch is applied in Debian pdns-recursor 4.1.0-3. Build logs will be at https://buildd.debian.org/status/package.php?p=pdns%2drecursor
Debian pdns-recursor 4.1.1-1 shipped with this patch.
I have:

Backport of #6179

---

build-scripts/build-dnsdist-rpm
pdns/dnsdistdist/contrib/dnsdist.upstart.conf

We forgot about this in #6394
I have:

Move the EL6 dnsdist package to upstart

---

docs/http-api/swagger/authoritative-api-swagger.yaml

This adds a missing parameter to swagger documentation -- as defined, you couldn't create a zone with a client. It also fixes a typo in the `Comment` definition.
Finally, I added some comments about an issue I have actually using this to generate a client. The main swagger code generator fails on the current definition for querying statistics, and I need to comment those lines out in my client project, but perhaps other people are having other experiences.
I'm a happy pdns user for years and am happily implementing a new client tool to use the REST API instead of inserting right into the database. Thanks for all your work on this!
I have:

Add parameters to swagger API definition for creating zone

---

pdns/dnsdist-lua.cc

OpenBSD requires `sys/socket.h` to come before `net/if.h`.
I have:

dnsdist: reorder headers to fix OpenBSD build

---

pdns/dnsdist.cc
pdns/dnsdistdist/docs/manpages/dnsdist.1.rst

Tiny improvements to the available dnsdist program options, and the --help and --version output.
Intended to be on top of #6433, might need a rebase then.
I have:

dnsdist cli option improvements

---

configure.ac
m4/pdns_enable_backend_unit_tests.m4
m4/pdns_enable_unit_tests.m4

Split `PDNS_ENABLE_UNIT_TESTS` so recursor, dnsdist dont have meaningless `--enable-backend-unit-tests`.
I have:

Split PDNS_ENABLE_UNIT_TESTS

---

pdns/dnsrecords.hh

Warning from clang: Apple LLVM version 9.1.0 (clang-902.0.39.1)
I have:

Fix reorder warning: field 'd_rname' will be initialized after field 'd_st'

---

pdns/Makefile.am
pdns/dnsdistdist/Makefile.am
pdns/recursordist/Makefile.am

Without this, building a Debian package twice in a row fails because there are new files.
I have:

make clean: rm generated .service and .conf-dist files

---

pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdistdist/docs/guides/serverselection.rst
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/test_Routing.py

This restricts weight values on downstreams and caps the calculated sum of all weights to avoid the following issues:
* Sum of all downstream weights combined exceeding the max value of `int`, causing queries to be dropped with `no-policy`
* Negative values on some downstreams causing a sum of all downstream weights to be 0 or less, causing queries to be dropped with `no-policy`
* Negative value weight preventing any queries from going to a downstream
* Run regression tests as described in `regression-tests.dnsdist/README`, particularly `test_Routing.py`
* Manually try adding downstreams with weights that are negative or greater than `2147483647` and observe the logged error and that they are not added, similar behavior to master when adding a bad address
* Add multiple downstreams (with …

Restrict value range for weight parameter, avoid sum overflows dropping queries

---

m4/pdns_with_lua.m4

Ensure `--with-lua=luajit` actually works and ensure we detect minimum
versions for LuaJit and plain Lua correctly.
I have:

Lua detection: make more robust

---

pdns/reczones.cc

If `etc-hosts-file` is set, but it cannot be opened, we claim we cannot open `/etc/hosts`.
I have:

rec: print the actual name of the failing file

---

pdns/syncres.cc

aj reported that we increase "dnssec-validations" counter even when running with process-no-validate.  This can be caused by us receiving queries for special names ('localhost', 'version.bind') which we explicitly mark as Insecure. This led our statistics to conclude a validation attempt had taken place.
This commit puts the update check behind 'shouldValidate()'.
I have:

 we increase "dnssec-validations" counter even when running with process-no-validate

---

pdns/lwres.cc
pdns/lwres.hh
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh

Hopefully fixes #6462, I haven't tested this exact case. Thanks to @phonedph1 for the report and the suggested fix!
I have:

rec: Don't account chained queries more than once

---

build-scripts/travis.sh
pdns/recpacketcache.cc
pdns/recpacketcache.hh
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/test-recursorcache_cc.cc
regression-tests.recursor/config.sh

This PR:
- fixes the "ghost" regression tests and enable them back ;
- add a corresponding unit test ;
- clean up the corresponding code in the recursor's cache, since the check was duplicated ;
- clean up the constructors of the recursor's packet and query caches.
I have:

rec: Enable the ghost tests again, add a corresponding unit test

---

pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/remote_logger.cc
pdns/remote_logger.hh
pdns/syncres.cc
pdns/syncres.hh

Use a dedicated protobuf queue for each worker thread, instead of sharing a single one for all worker threads, leading to some contention under heavy load.
Also properly stops the existing protobuf exporter threads on a `Lua` configuration reload.
I have:

rec: Use a separate protobuf exporter thread per worker thread

---

pdns/misc.cc
pdns/resolver.cc
pdns/resolver.hh
pdns/rpzloader.cc

The initial `AXFR` query to a `RPZ` server was using a hard-coded ten seconds timeout regardless of the `axfrTimeout` setting.
We also messed up error reporting in `waitForRWData()` when `poll` returns `-1`.
I have:

rec: Respect the AXFR timeout while connecting to the RPZ server

---

pdns/dns_random.cc

* `getrandom()` is declared in `sys/random.h`, not `linux/random.h`, contrary to what some man pages say
* `L` has been replaced by `g_log`
* `getrandom()` returns the number of bytes when everything goes well
I have:

Fix compilation and use of getrandom() when available

---

pdns/communicator.cc
pdns/packethandler.cc
pdns/slavecommunicator.cc

When a slave receives a NOTIFY, it (if the serial check says it should) re-transfers the zone. If additional NOTIFYs come in during the transfer, those are acknowledged, even if they mean that the zone we are transferring is not the latest version. With this patch, we will recheck the serial when the transfer is done and, if necessary, do another transfer to make sure are truly up to date with the master.
I have:

recheck serial when AXFR is done

---

pdns/Makefile.am

We correctly add `RT_LIBS` to most programs using `clock_gettime()`, directly or not, but we forgot `dnspcap2protobuf`. Should fix #6482.
I have:

auth: Link dnspcap2protobuf against librt when needed

---

pdns/pdnsutil.cc

Add return 0 for correct exit of set-kind and set-account

---

pdns/dns_random.cc
pdns/dns_random.hh
pdns/recursordist/Makefile.am
pdns/recursordist/test-syncres_cc.cc
pdns/test-dns_random_hh.cc

- Don't force the use of the `urandom` backend in the unit tests
- Raise a `runtime_error` instead of a `PDNSException` since it was the existing behavior and it makes more sense anyway
- Test all available backends by allowing to force the re-initialization
I have:

Fix the dns_random unit tests, test all available backends

---

pdns/dnsdistdist/docs/index.rst

lualang.org appears dead, lua.org appears alive

lualang.org -> lua.org

---

docs/manpages/ixfrdist.1.rst
pdns/Makefile.am
pdns/ixfrdist.cc
pdns/ixfrutils.cc
pdns/ixplore.cc
pdns/logger.cc
pdns/logger.hh

This makes `ixfrdist` no longer block when sending out an AXFR.
To improve the logging in `ixfrdist`, it now uses `Logger`. This PR also patches the `Logger` class to optionally prepend a severity prefix to emitted log lines.
Closes #6468 
I have:

ixfrdist: use worker threads to handle TCP connections

---

regression-tests/backends/mydns-master

The MyDNS database doesn't support more data then 128 chars, this simply filters out the data import. The very-long-txt test was already excluded using fail.mydns file.

Remove very-long-txt from "to sql" for mydns test

---

pdns/recursordist/configure.ac

We need that to get the FFI symbols exported.
I have:

rec: Add -rdynamic to C{,XX}FLAGS when we build with LuaJIT

---

modules/ldapbackend/ldapbackend.hh
modules/ldapbackend/powerldap.cc

As @cmouse pointed out, the LDAP backend generates a fair amount of compiler warning with certain options (that I didn't think to enable, my bad).
This PR removes them.
I have:

Remove compiler warnings pointed by Aki

---

pdns/dnsbackend.hh

The const keyword fell to wrong side of the function, so move it where it belongs to.
Broken in a2dfc9ea78614a9eef514a612117e507d70d4664
I have:

dnsbackend: Make isMaster a const

---

pdns/recursordist/configure.ac

We need that to get the FFI symbols exported.
I have:

rec-4.1.x: Add -rdynamic to C{,XX}FLAGS when we build with LuaJIT

---

pdns/rec-lua-conf.cc
pdns/recursordist/docs/lua-config/rpz.rst
pdns/rpzloader.cc
pdns/rpzloader.hh

* Add `seedFile` to load `RPZ` zones from a file, then update via `IXFR`
* Add `dumpFile` so the latest version of the zone is dumped to a file after a successful `IXFR`
Need documentation, and ideally regression tests.
I have:

rec: Add the possibility to preload RPZ from file, dump updates to a file

---

build-scripts/travis.sh
m4/pdns_with_lua.m4

This brings Travis closer in line with what we actually ship. Lowering the LuaJIT requirement from 2.0.3 to 2.0.2 has been tested in Travis and on buildbot with no observable ill effects.
I have:

switch travis to luajit; lower luajit required version to 2.0.2

---

pdns/dnsdistdist/test-dnsdistrings_cc.cc

Thanks @zeha!
Fixes #6430.
I have:

 dnsdist tests: avoid failure on not-so-optimal distribution

---

modules/godbcbackend/sodbc.hh
pdns/ssqlite3.hh

`SSQLite3` and `SODBC` are missing override declarations
I have:

Add missing overrides

---

pdns/packethandler.cc

Before this patch, the meta lookup would interfere with the already-started `B.lookup`. This caused failures with odbc/MSSQL.
I have:

avoid interleaved access to B (via d_dk)

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/guides/dns-over-tls.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/tcpiohandler.cc
pdns/dnsdistdist/tcpiohandler.hh

To be able to present an ECDSA certificate to clients supporting it and a RSA one to those who don't.
Closes #6450.
I have:

dnsdist: Add support for more than one TLS certificate

---

docs/manpages/calidns.1.rst
pdns/calidns.cc

If the `--ecs-from-file` option is used, `calidns` read an IP address or netmask from a third space-separated field in the query file, and adds it to the query as an `EDNS Client Subnet` option.
This PR also makes `calidns` ignore lines starting with a `#` in the query file, to be able to put comments in it.
I have:

 calidns: Add an option to read ECS values from the query file, skip comments

---

pdns/common_startup.cc

configuration variables without a help string do not show up in --help and
pdns_control current-config
I have:

document undocumented config vars

---

.github/PULL_REQUEST_TEMPLATE.md

A PR submitter may have checked that code compiles, but may not have had time to (sufficiently) test. This has happened to me a few times this week already. With this change, those two situations can be indicated separately.
I have:

split compile/test in pull request template

---

docs/settings.rst
modules/bindbackend/bindbackend2.cc

In #6308, a bug is reported with a config containing this line:
```
launch=gsqlite3:api,bind:main,bind:dnsadmin,bind:eec,bind:jobstuff,bind:nzrb
```
However, that is invalid setup, as the bindbackend shares data between instances without respecting the suffix.
This PR makes such setups fail early so surprises are avoided.
I have:

bindbackend: refuse launch suffixes

---

pdns/rec_control.cc

By invoking the full file parser instead of doing two runs looking for specific keys, the include-dir logic is allowed to run.
I have:

make rec_control respect include-dir; closes #6536

---

pdns/dnspacket.cc

auth: lower 'packet too short' loglevel in another place

---

pdns/protobuf.cc
pdns/protobuf.hh

This avoids errors like 
```
/usr/local/include/boost/function_types/components.hpp:139:35: error: expected a qualified name after 'typename'
template<typename T, typename L>
^
./dns.hh:228:11: note: expanded from macro 'L'
#define L theL()
```
This is an alternative to #6516. It does not preclude later merging of #6516.
I have:

move includes around to avoid boost L conflict

---

docs/backends/geoip.rst

Remove the incorrect deprecation warning, and replace it with changed warning.
I have:

docs: geoip-database-files has not been dropped in v4.2.0

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

The soa serial was not increased after dnssec related updates via the api
I have:

auth-api: increase serial after dnssec related updates

---

modules/bindbackend/bindbackend2.cc

This fix is in a different form already present on master (part of #6021)
I have:

auth-bindbackend: only compare ips in isMaster()

---

pdns/dnstap.proto

Add syntax statement to `dnstap.proto` as suggested by the compilation warning.  This is the same default syntax statement  the the protobuf compiler falls back to.
This is just to get rid of  the jarring warning message to comes by when compiling.
I have:

Add syntax to dns.proto to silence compilation warning.

---

pdns/dnsreplay.cc

dnsreplay: Bail out on a too small outgoing buffer

---

pdns/recursor_cache.hh
pdns/recursordist/test-recursorcache_cc.cc

The recursor's ECS index used the `DNSName`'s case insensitive reverse lexicographical ordering (default) instead of the canonical ordering one.
While quite faster, it isn't exactly right and can lead to some names not being correctly wiped from the cache.
This issue is addressed by #6505 on master.  
I have:

 rec: Use canonical ordering in the ECS index

---

pdns/lua-recursor4-ffi.hh
pdns/lua-recursor4.cc

(cherry picked from commit aedec560c6494e838d92e9a8106d5ff87367eb83)
I have:

Backport 6574 to 4.1.x: rec: Add _raw versions for qname / ComboAddresses to the FFI API

---

docs/Makefile.am

Fixes the docs subdir to not use parallel build even if `-j` is used.  Also adds `clean` target support.
I have:

Disable parallel build for docs

---

build-scripts/build-auth-rpm
build-scripts/debian-authoritative/pdns-tools.install
build-scripts/debian-authoritative/pdns-tools.manpages
docs/conf.py
docs/manpages/dnspcap2calidns.1.rst
pdns/.gitignore
pdns/Makefile.am
pdns/common_startup.cc
pdns/dnspcap2calidns.cc

This tool generates a list of queries (qname, qtype, source) in the `calidns` format from a `PCAP`.
This PR lacks documentation.
I have:

Add dnspcap2calidns, to convert PCAP to the calidns format

---

pdns/recursordist/docs/http-api/endpoint-cache.rst
pdns/ws-recursor.cc
regression-tests.api/runtests.py
regression-tests.api/test_Cache.py
regression-tests.api/test_helper.py

This adds support for the `subtree` parameter to the cache flush API endpoint.
```
/api/v1/servers/localhost/cache/flush?domain=example.com.&subtree=true
```
Fix #6550 
I have:

rec api: add subtree option to the cache flush endpoint

---

docs/settings.rst

Modified the previous value of webserver-allow-from to correctly reflect the change introduced [here](https://github.com/PowerDNS/pdns/commit/be3e14771236c0476713d7d55aa2d60622a799e2).
I have:

reflect accurate old value of webserver-allow-from

---

pdns/dnsdistdist/docs/guides/downstreams.rst
pdns/dnsdistdist/docs/guides/webserver.rst
pdns/dnsdistdist/docs/reference/config.rst

Fix #6483 by documenting the dnsdist `setVerboseHealthChecks()` lua function.
I have:

docs: document setVerboseHealthChecks()

---

docs/manpages/calidns.1.rst
pdns/calidns.cc

- Add an option to stop once we drop below a minimum rate, as well as a `quiet` option so I can start `calidns` from a script and it just outputs the maximum QPS reached before we dropped below 99.9%, for example
- Accept lines with an ECS value even if we don't use it, so we can use a file with ECS information more easily
- Only write a 'plot' file when asked to, because I keep finding those files on my filesystem :)
I have:

calidns: Add quiet, minimum-success-rate options to use from a script

---

pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh
pdns/recursordist/test-negcache_cc.cc
pdns/recursordist/test-recursorcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh

Most of the lookups in the query (positive) and negative caches are done on the exact name only, and doing so using a hash is much more faster than using canonical ordering.
In both cases we still need canonical ordering to be able to wipe a domain and its subtree from the cache efficiently, but regular retrieval (cachecache, get()) doesn't.
Pros:
- Faster retrieval: ~8x faster
Cons:
- Increased memory usage: ~10% overhead worst case (entries with only one small record)
- Slower insertion: 1.08x slower
I have:

rec: Add hashed indexes to the caches, for faster retrieval

---

pdns/recursordist/docs/lua-scripting/hooks.rst

Fix an example Lua script from the documentation.
I have:

our recursor lua policy override example did not work

---

pdns/lwres.cc
regression-tests.recursor-dnssec/test_ECS.py

Don't accept an `ECS` scope more specific than the source we sent, if the authoritative server has gone mad.
- Before:
```
secure.booking.com. 53 IN CNAME secure.c.booking.com. ; (Insecure) auth=1 127.0.0.1/128
```
- After:
```
secure.booking.com. 29 IN CNAME secure.c.booking.com. ; (Insecure) auth=1 127.0.0.1/32
```
I have:

rec: Make sure that the ECS scope from the auth is < to the source 

---

pdns/rec-lua-conf.cc
pdns/rpzloader.cc
pdns/rpzloader.hh

This PR fixes two issues in our RPZ loading code introduced in #6237:
- the RPZ thread was modifying the zone shared with all of the other threads during the first AXFR, triggering a race condition that could have lead to crashes ;
- the RPZ thread was started during the parsing of the Lua configuration, and was immediately modifying its RPZ zone. The first AXFR was altering the shared zone and the following IXFRs were updating the configuration with a new copy of the zone, as they should. However if one IXFR finished before the Lua parsing was finished, for example because we were loading a huge RPZ file from the disk, the new zone would have been overridden by an empty one at the end of the parsing. We now delay the creation of the RPZ threads, and therefore the AXFR and IXFR, until the …

rec: Delay the loading of RPZ zones until the parsing is done, fix race

---

pdns/pdns_recursor.cc
pdns/rec-snmp.cc
pdns/rec_channel_rec.cc
pdns/recursordist/RECURSOR-MIB.txt
pdns/recursordist/docs/metrics.rst
pdns/syncres.hh

This allows us to drop queries when a pipe goes full, thus still distributing queries to other threads instead of blocking. It also adds a new metric to keep track of queries dropped because the pipe was full.
I have:

rec: Use a separate, non-blocking pipe to distribute queries

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

OPT and TSIG rrsets are already ignored in incoming AXFR. This restricts creation of such records through the authoritative API and fix #6441 
I have:

auth-api: restrict creation of OPT and TSIG rrsets

---

pdns/pdns_recursor.cc
pdns/syncres.hh

This makes sure that no worker or distributor thread will get blocked while waiting for a response from another thread, for example while gathering stats or executing a command coming from the control
channel.
This PR needs a serious review, don't merge blindly!
It might also need some documentation update.
I have:

rec: Move carbon/webserver/control/stats handling to a separate thread

---

README.md
docs/conf.py
pdns/dnsdistdist/docs/conf.py
pdns/recursordist/README.md
pdns/recursordist/docs/conf.py
pdns/version.cc
pdns/ws-auth.cc

Also update several years to match the data in pdns/version.cc
4.1.2 is still "copyright 2017". Backport #6130 to auth-4.1.x.
I don't know what I'm doing, but it shouldn't be possible for something like this to go wrong...
(Backport for rec is #6611.)
I have:

Backport 6130 to auth-4.1.x: Update copyright years to 2018

---

README.md
docs/conf.py
pdns/dnsdistdist/docs/conf.py
pdns/recursordist/README.md
pdns/recursordist/docs/conf.py
pdns/version.cc
pdns/ws-auth.cc

Also update several years to match the data in pdns/version.cc
4.1.2 is still "copyright 2017". Backport #6130 to rec-4.1.x.
I don't know what I'm doing, but it shouldn't be possible for something like this to go wrong...
(Backport for auth is #6610.)
I have:

Backport 6130 to rec-4.1.x: Update copyright years to 2018

---

pdns/lua-recursor4.cc
pdns/lwres.cc
pdns/pdns_recursor.cc
pdns/protobuf.cc
pdns/protobuf.hh
pdns/rec-carbon.cc
pdns/rec-lua-conf.cc
pdns/rec_channel_rec.cc
pdns/recpacketcache.hh
pdns/recursor_cache.cc
pdns/rpzloader.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/validate-recursor.cc
pdns/ws-recursor.cc

See  #6542, #6516, #6358.
This is an alternative to #6517 which could still be merged eventually.
I have:

reorder includes to avoid Boost L conflict

---

pdns/recursordist/configure.ac

This moves `-rdynamic` from compiler to linker flags for the recursor. Ref #6511 
I DID NOT test if the FFI symbols are correctly exported with this patch.
I have:

-rdynamic is for the linker

---

build-scripts/build-dnsdist-rpm

We used the non-existing `%elif` rpm macro ¯\\_(ツ)_/¯.
(cherry picked from commit 3e27601f900aa91c4f17ae4d24b48564fab157e4)
I have:

backport #6641: dnsdist: fix RPM scriptlets

---

build-scripts/build-dnsdist-rpm

We used the non-existing `%elif` rpm macro ¯\\_(ツ)_/¯. Which broke upgrades and removals on EL6. Unfortunately, this is broken in already released packages, so the only solution we can offer is:
> Please use `yum --setopt=tsflags=noscripts remove dnsdist` and reinstall
Once we have released a new version with this fix.
I have:

dnsdist: fix RPM scriptlets

---

pdns/dnsproxy.cc
regression-tests/tests/alias-address/command
regression-tests/tests/alias-address/expected_result

Ensure ALIAS answers over TCP have correct name

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

The default API output exports zone in AXFR format without IN in the records. This just adds IN to the output string.
I have:

API export function output change to add IN to the output

---

modules/gmysqlbackend/smysql.cc

`tx_isolation` has been deprecated since 5.7.20 and removed in 8.0.3, see https://bugs.mysql.com/bug.php?id=88227
This uses syntax documented all the way back to MySQL 5.0 (and also supported by 8.0).
Fixes #6632.
I have:

gmysql: Use future-proof statement for transaction isolation

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

When creating new records with the API, TYPE0 records are now removed. Also takes care of the CNAME check.
Fixes #6645.
I have:

API: Remove ENTs when "replacing" new records

---

pdns/pdns_recursor.cc

`unixDie()` will output the value of `errno` but it might have been overridden since the call to `write()`, so let's keep printing the value of `error`.
I have:

rec: Fix 'adding an integer to a string does not append to it' error

---

pdns/dnsname.hh

Entries that are not `endNode`s are basically place-holder and don't have a valid value, so we shouldn't attempt to copy the value when we duplicate a node, or the whole tree.
Among other possible issues it triggers the Undefined Behavior Sanitizer:
```
dnsname.hh:236:126: runtime error: load of value 165, which is not a valid value for type 'bool'
``` 
I have:

Don't copy unitialized values of SuffixMatchTree

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

We frequently get users who pass two identical RRsets, each holding one record, with different content. The user might then be confused to only see the second one ending up in the zone. Erroring out early should avoid confusion.
Comments welcome. ~~Still needs a test.~~
Suggested by @hlindqvist 
I have:

reject duplicate RRsets in patchZone

---

pdns/pdns_recursor.cc

Before:
```
$ dig +ednsflags=0x88 ...
..
; EDNS: version: 0, flags: do; MBZ: 0x0088, udp: 4096
```
After:
```
$ dig +ednsflags=0x88 ...
..
; EDNS: version: 0, flags: do; udp: 4096
```
I have:

zero the must-be-zero bits

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst

This new setting limits the number of `UDP` queries we attempt to handle after being woken up by the multiplexer and before returning back to process other events.
Before this, we could end up trying to process queries after queries and almost never return from `handleNewUDPQuestion()` to process new events, meaning we could eventually end up never scheduling new `mthreads` or handle responses from authoritative servers for a long time, only sending responses for packetcache hits and creating new `mthreads`.
This would also make `rec_control` seem unresponsive and return with:
```
Fatal: Timeout waiting for answer from control channel
```
I have:

rec: Add a new max-udp-queries-per-round setting

---

pdns/dnsdist-lua-bindings.cc

This tries to improve Lua error reporting, see #6535. Exceptions thrown in a Lua subroutine can be printed:
```
x = newNMG()
res, err = pcall(function() x:addMask('banana') end)
if not res then
print("An error has been thrown: ", err)
end
```
I have:

dnsdist: allow known exception types to be converted to string

---

build-scripts/travis.sh

Because we keep missing the warning.
Recursor clang will fail until usage of `unixDie` is fixed.
I have:

Add -Werror=string-plus-int to Travis clang testing

---

modules/geoipbackend/geoipinterface-dat.cc

The return value must be greater than 0, all other indicate lookup failure.
Fixes #6676 (when using non-geoip database, or database mismatch)
I have:

geoipbackend: Check GeoIP_id_by_addr_gl and GeoIP_id_by_addr_v6_gl return value

---

Brewfile

This should reduce the time required to hunt down common dependencies on macOS, to get a build with most features enabled.
The various DBs are excluded though.
I have:

Allow running "brew bundle" to fetch deps on macOS

---

README.md
docs/conf.py
pdns/dnsdistdist/docs/conf.py
pdns/recursordist/README.md
pdns/recursordist/docs/conf.py
pdns/version.cc
pdns/ws-auth.cc

Also update several years to match the data in pdns/version.cc
Backport #6130 to dnsdist-1.2.x.
I don't know if future 1.2.x releases are planned, but if so...
(Auth and rec were #6610 and #6611 respectively.)
I have:

Backport 6130 to dnsdist-1.2.x: Update copyright years to 2018

---

.travis.yml
build-scripts/travis.sh
pdns/recursordist/test-negcache_cc.cc

- Enable ASAN in dnsdist and recursor builds ;
- Enable UBSAN in dnsdist's build (it fails for the rec, probably because it needs too much memory) ;
- Get rid of the special version of `clang` (`3.6`) for the recursor, Travis upgraded to `5.0.0` in the meantime ;
- Fix a memory leak in the negative cache unit tests, detected by Leak Sanitizer.
Unfortunately we are already running out of time for the authoritative builds, so no change there.
I have:

Enable Address (dnsdist, rec) and Undefined Behavior (dnsdist) Sanitizers in Travis

---

pdns/qtype.hh

Fixes #6685
It's not clear to me why these lines were missing.
I have:

Initialize some missed qtypes

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdist.hh
pdns/fstrm_logger.hh
pdns/remote_logger.hh

For better introspection all creatable objects should have toString() methods. Actually many objects already have toString() implemented in C++, but then it's not hooked up to Lua.
This adds a few (easy) objects to Lua, obviously more would be better.
I have:

dnsdist: Expose toString of various objects to Lua

---

pdns/recursordist/docs/settings.rst

Compiling resursor shows this warning:
```
updating environment: 75 added, 0 changed, 0 removed                           
reading sources... [100%] upgrade                                                                                                                                                       
pdns/recursordist/docs/settings.rst:890: WARNING: Explicit markup ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... rec_control.1 { } pdns_recursor.1 { reading sources... [100%] upgrade                                                                                                        }                                              
build succeeded, 1 warnings.
The manual …
```

docs: Add extra LF to settings.rst to squash sphinx warning

---

README.md

The docs say:
```
When building from git, the following packages are also required: autoconf, automake,
$ autoreconf -vi
$ ./configure --with-modules="" --without-lua
$ make
```
However, that second one yields:
```
$ ./configure --with-modules="" --without-lua
...
checking for protoc... no
checking whether we will enable LUA records... yes
configure: error: LUA records need LUA. You can disable this feature with the --disable-lua-records switch or configure a proper LUA installation.
```
When adding the --disable-lua-records, the configure completes.

docs: Fix ./configure example, add --disable-lua-records

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/rules-actions.rst

The `MaxQPSIPRule` rule needs to keep a state for seen source addresses. While this state is small we don't want to keep it for too long so this PR adds a cleaning mechanism that will remove entries that haven't been seen for a while. It also reduces the size of the state struct.
I have:

dnsdist: Remove 'expired' states from MaxQPSIPRule

---

pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh

The first issue was that we closed the socket toward the backend if the first connection attempt failed, but tried to reconnect without reopening it, as reported by Aleš Rygl on the mailing-list [1].
The second issue is that we would close and reconnect the backend socket on some error codes even if the error was occurring on the health check socket, which is a separate one.
This PR also makes sure we don't try to reconnect from the healthcheck and responder threads at the same time, and that we don't accidentally start the same responder thread twice.
[1]: https://mailman.powerdns.com/pipermail/dnsdist/2018-May/000425.html
I have:

 dnsdist: Fix reconnection handling

---

ext/luawrapper/include/LuaContext.hpp

This allows uncaught `std::exception` to be better reported with reason information.
See #6541 
I have:

luawrapper: report caught std::exception as lua_error

---

pdns/pdnsutil.cc

The occlusion check was ignoring NS, DNAME and DS records.
The auth check was incomplete (only for records with auth == 0)
Add DS at delegation check
Fixes #6622
I have:

pdnsutil: occlusion and auth check improvements

---

pdns/lwres.cc
pdns/lwres.hh
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

This PR:
* differentiates 'could not parse response' from 'got a valid FORMERR response'
* limits 'no EDNS' fallback to responders that send valid FORMERR responses
This is a minimal patch. We could collapse `EDNSStatus::UNKNOWN` and `EDNSStatus::EDNSIGNORANT` but keeping both might be useful for debugging some day. 
Note that (with or without this PR) we treat a FORMERR EDNS0 response as a signal that the auth does not speak EDNS0. Formally, this is wrong. Practically, this is fine.
I have:

implement the EDNS camel diet (draft-spacek-edns-camel-diet)

---

pdns/dnsdist.cc
pdns/dnsdist.hh

While investigating #6664, I noticed that we pass the `remote` member to functions that could alter it, like `Socket::recvFrom()`. At the moment I don't see how it could have led to having a different port in the end, since we use a connected socket, but it's still not very clean.
As there is no reason to alter `remote` and some other members after the object construction, this PR marks them as `const` so we are prevented from passing them to a function that might alter their content.
I have:

 dnsdist: Mark the remote member of DownstreamState as const

---

pdns/dynhandler.cc

The non-controversial bit of #4457.
I have:

pdns_control notify: handle slave w/o renotify properly

---

pdns/dns.hh

Adding brace initializers makes it non-trivial, which does not seem
like a very good idea for a packed structure.
gcc 8.1.0 complains with:
```
warning: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘struct EDNS0Record’ from an array of ‘uint32_t’ {aka ‘unsigned int’} [-Wclass-memaccess]
memcpy(&stuff, &ttl, sizeof(stuff));
```
I have:

Revert EDNS0Record to a trivial type

---

pdns/dnsdist-dynblocks.hh

Dynamic blocks were being created with the wrong duration the detection interval was being used.
Fixes the duration as set at the creation of dynamic blocks from rules.
I have:

Dynamic blocks were being created with the wrong duration

---

pdns/dnssecinfra.cc
pdns/lua-base4.cc
pdns/misc.cc
pdns/pdns_recursor.cc
pdns/rec_channel.cc
pdns/recursor_cache.cc

- Shadowed variables
- One warning about `strncpy()`, we always NULL-terminate the string anyway, but let's make the compiler happy.
I have:

rec: Fix some warnings reported by GCC

---

pdns/dnsdist-web.cc
pdns/dnsdistdist/docs/guides/webserver.rst

Default add the `Connection: close` header to dnsdist http responses to indicate that the connection will be closed after completion of the response.
Fix #6532 
I have:

dnsdist: default set "Connection: close" header for web requests

---

pdns/dnsdist-tcp.cc

The required memory has been reserve()'d, but we are not allowed to access it directly, and it breaks when compiled with the following flag, checking any access to containers as if .at() were used:
```
-D_GLIBCXX_ASSERTIONS
```
Fixes #6712.
I have:

dnsdist: Don't access the TCP buffer vector past its size

---

pdns/recursordist/docs/running.rst

Add missing word 'impact' to the documentation.
I have:

add missing word 'impact' to the documentation

---

pdns/pdns_recursor.cc
pdns/rec-snmp.cc
pdns/rec_channel_rec.cc
pdns/recursordist/RECURSOR-MIB.txt
pdns/recursordist/docs/metrics.rst
pdns/syncres.hh

Incoming queries larger than our buffer (1500 bytes) are truncated by the kernel, so let's not even try to parse them.
I have:

rec: Drop queries truncated because they were larger than our buffer

---

pdns/dnsdist-console.cc
pdns/dnsdist-console.hh
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdistdist/docs/guides/console.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dolog.hh
pdns/sodcrypto.cc
pdns/sodcrypto.hh
pdns/test-dnscrypt_cc.cc
pdns/test-dnsdist_cc.cc
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_Console.py

Fixes #6683 and explicitly prevents the situation from #6709, which was working in some cases because of a very brittle side-effect.
This PR should add a few words to the documentation to clarify that the use of encryption is also strongly recommended for local connections.
I have:

dnsdist: Refuse console connection without a proper key set

---

pdns/dnspacket.cc
pdns/dnspacket.hh

When we fill packets in the auth server, we check for duplicates.. in a very very slow way. With this PR, an unordered_set is used to speed up this process. 
This plot shows the time we take to fill a packet (in microseconds) with increasing number of records:
This PR appears to be a speedup at all packet sizes - except for a measurement error at the first ever query. 
I have:

Implement a smarter dedup for filling packets in auth

---

pdns/recursordist/docs/dnssec.rst

Add note about CD.
Slightly improve 'when?' table rendering for HTML (process-no-validate is now correctly "tt").
I have:

Tiny Recursor dnssec doc improvements

---

Makefile.am

In case `virtualenv` is not available, with this change, `pdns_server` will still have been built. It also looks slightly cleaner in `Makefile.am`.
I have:

auth: reorder SUBDIRS

---

pdns/lua-auth4.cc
pdns/stubresolver.cc

@goestreicher ran into crashes because AuthLua4 again tells us to parse resolv.conf (and add the results to a global vector). This PR fixes that.
I have:

only parse resolv.conf once - this avoids race conditions

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh

rec: Don't require authoritative answers for forward-recurse zones

---

pdns/Makefile.am
pdns/dnsdist-cache.cc
pdns/dnsdist-cache.hh
pdns/dnsdist-lua-bindings.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/test-dnsparser_cc.cc
pdns/dnsparser.cc
pdns/dnsparser.hh
pdns/dnswriter.cc
pdns/test-dnsdistpacketcache_cc.cc
pdns/test-dnsparser_cc.cc
regression-tests.dnsdist/test_Caching.py

So it's possible to cap the `TTL` of `NODATA` and `NXDOMAIN` answers.
Also fixes a bug in the `editTTLs()` feature, where the wrong section was passed to the callback.
Closes #6579.
I have:

 dnsdist: Add a negative TTL option to the packet cache

---

pdns/rec-lua-conf.cc
pdns/recursordist/docs/lua-config/rpz.rst
pdns/rpzloader.cc
pdns/rpzloader.hh
regression-tests.recursor-dnssec/test_RPZ.py

This PR implements the first part of #4996 and #6452, automatic fail over to another `RPZ` master. It does not provide a round-robin option to split the load across several masters. 
I have:

rec: Add support for multiple rpz masters as failover

---

pdns/recursordist/docs/manpages/rec_control.1.rst

Offer help for people who try to use `rec_control dump-cache /tmp/file` on systemd systems where `/tmp` is a private area not related to `/tmp`

Recursor: try to document how to handle systemd private tmp

---

pdns/dnsrecords.cc
pdns/ednsoptions.cc
pdns/ednsoptions.hh
pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/recursordist/docs/lua-scripting/dq.rst
pdns/recursordist/test-ednsoptions_cc.cc
regression-tests.recursor-dnssec/cookiesoption.py
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_Lua.py

This PR adds support for retrieving multiple values for the same `EDNS` option in the recursor, not breaking the existing API. The regular interface does not support more than one value, so it will keep returning only the first value for a given option, while two new methods make it possible to retrieve all the values:
- `EDNSOptionView:count()`
- `EDNSOptionView:getValues()`
The `FFI` interface already supported returning more than one value so support for multiple values has been transparently added to it.
This PR also adds several regression tests for the Lua interface.
Closes #6307.
I have:

rec: Support multiple values for the same EDNS option in gettag

---

pdns/dnsdist-cache.cc
pdns/dnsdist-cache.hh
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/test-dnsdistpacketcache_cc.cc

In the unlikely but quite real event two queries with the same qname, qtype and qclass but different EDNS options or flags end up with the same hash, the packet cache would return a answer that might
not be suitable for the query. Reduce the odds by checking the flags present in the dns header in addition to the qname, qtype and qclass.
For the same reason we might need to consider storing the ECS subnet if any.
I have:

dnsdist: Check the flags to detect collisions in the packet cache

---

docs/backends/bind.rst

Document that BIND backend hosted zones can't be altered from the API
I have:

Document that BIND backend hosted zones can't be altered from the API

---

pdns/dnsdist-dynblocks.hh
pdns/dnsdist-lua-inspection.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/guides/dynblocks.rst
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/test_DynBlocks.py

dnsdist: Add netmask-based {ex,in}clusions to DynBlockRulesGroup

---

pdns/dnsdist-lua-vars.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/guides/dynblocks.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/constants.rst
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_API.py
regression-tests.dnsdist/test_DynBlocks.py
regression-tests.dnsdist/test_HealthChecks.py
regression-tests.dnsdist/test_TCPLimits.py

Setting the dynamic block action to `NoOp` allows the dynamic rule to be inserted as usual and show up while looking at the rules, while not blocking any query and not stopping subsequent rules from
being evaluated. I pondered for a while not inserting any dynamic rule at all in that case, but we then log a lot of "inserting ..." lines as long as the condition is triggered, instead of just updating the existing dynamic rule.
Supersedes #6703 (thanks!).
CC @atosatto.
I have:

dnsdist: Add DNSAction.NoOp to debug Dynamic Blocks

---

pdns/dnsdist-lua-actions.cc
regression-tests.dnsdist/test_Advanced.py

The action has been documented at some point but never implemented, and it might be useful for testing purposes.
Closes #6758.
I have:

dnsdist: Implement NoneAction()

---

pdns/dnsdist-cache.cc
pdns/dnsdist-cache.hh
pdns/dnsdist-ecs.cc
pdns/dnsdist-ecs.hh
pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst
pdns/test-dnsdistpacketcache_cc.cc
regression-tests.dnsdist/test_Caching.py

We did not detect a collision involving two queries for the same qname, qtype, qclass and flags but with different `ECS` values hashing to the same key.
This commit adds an option to the packet cache to parse and keep the `ECS` value in order to detect this kind of collisions.
It's not enabled by default because parsing the `ECS` value has a cost and most deployment probably don't care.
This PR is based on the branch from #6747, so will need to be rebased after this one has been merged.
I have:

 dnsdist: Detect ECS collisions in the packet cache

---

pdns/dnsdist.cc
pdns/dnsdist.hh

I finally managed to reliably reproduce the "negative outstanding counter" issue by setting ` setMaxUDPOutstanding()` to a very low value and overloading the backend, causing `dnsdist` to do a lot of "active state reuses".
This PR tries harder to detect whether another thread has been reusing the state, making sure that we don't decrement the outstanding counter twice.
I have:

dnsdist: Fix an outstanding counter race when reusing states

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/rules-actions.rst
pdns/ednssubnet.cc
regression-tests.dnsdist/test_EdnsClientSubnet.py

dnsdist: Add SetECSAction to set an arbitrary outgoing ECS value

---

ext/luawrapper/include/LuaContext.hpp

`GCC` enables `-Wmaybe-uninitialized` by default with `-Wall`, and it reports what looks like false positives with `boost::optional` types.
See:
- https://svn.boost.org/trac10/ticket/12513
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78044
I'm not a huge fan of hiding warnings, but these are flooding my terminal causing me to miss other, legitimate, warnings, and they look like false positives to me. 
`clang` does not implement the warning and actually issue a warning if you try to hide a non-existent warning, so I had to exclude it.
I have:

LuaWrapper: Disable maybe uninitialized warnings with boost optional

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/tcpiohandler.cc
pdns/dnsdistdist/tcpiohandler.hh

This PR adds support for switching to a new set of DoT certificates and keys without restarting dnsdist. It also adds an option to completely disable TLS session resumption via tickets.
I have:

dnsdist: Add support for rotating certificates and keys

---

pdns/dnsparser.cc
pdns/test-dnsparser_cc.cc

Checking whether the SOA record is in the right section was broken because of a misplaced parenthesis, and the unit test checking that case turned out to be broken too (wrong class) :'(
The broken check was reported by cppcheck (thanks!):
```
Comparison of a boolean expression with an integer.
```
I have:

dnsdist: Fix detection of NoData / NXDomain answers in the cache

---

pdns/ws-auth.cc

While listing a zone via the API, if there are RRsets (i.e. a qname+qtype) with zero records and non-zero comments, merging the two datasets would derail, resulting in comments and records for subsequent RRsets being split into two JSON dicts instead of one.
I have:

avoid concurrent records/comments iteration from running out of sync

---

pdns/dnspacket.cc

It turns out we were not properly resetting the `TSIG` state between queries, leading the authoritative server to sign responses that did not need to be.
Fixes #6736.
I have:

auth: Reset the TSIG state between queries

---

pdns/ws-auth.cc

(cherry picked from commit 5481c77c8917ef3097d37e0da8a450a01b09f3de)
This backports #6780 to auth-4.1.x.
I have:

backport: avoid concurrent records/comments iteration from running out of sync

---

pdns/recursordist/Makefile.am
pdns/recursordist/configure.ac
pdns/recursordist/m4/pdns_enable_nod.m4

Newly Observed Domain support is configured via a configure option, however the compilation was still including the NOD source files and requiring boost filesystem.
I have:

Make NOD and Boost FS conditional for compilation based on configure flag

---

build-scripts/test-recursor

This disables the SNMP tests until we get around to updating the builder images to support this test.
I have:

skip recursor SNMP testing in buildbot

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

 auth: Make sure that we use strict weak records ordering in the API

---

modules/remotebackend/remotebackend.hh
pdns/communicator.hh
pdns/dbdnsseckeeper.cc
pdns/dnsdist-tcp.cc
pdns/dnsrecords.cc
pdns/ednssubnet.cc
pdns/iputils.cc
pdns/iputils.hh
pdns/misc.cc
pdns/nameserver.cc
pdns/pdns_recursor.cc
pdns/syncres.hh
pdns/test-iputils_hh.cc

Fix warnings reported by GCC 8.1.0:
- polymorphic exceptions caught by value
- ComboAddress objects manipulated via `memset()`
(cherry picked from commit d38e2ba97a78aa9dfc894fc4e13a6f3a410dd31a)
I have:

Backport rec-4.1.x: Fix warnings reported by GCC 8.1.0

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_Advanced.py

Allows matching based on the destination port of the question. This allows one to apply more powerful rules to ports bound for DoT for instance.
I have:

dnsdist: DSTPortRule 

---

pdns/dnsdist-lua-bindings.cc

So that we can do sketchy things with it from maintenance and luarule actions.
I have:

Make getOutstanding be usable from both lua and console

---

pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/rec_channel_rec.cc

On Linux/glibc, calling `set*id()` from a thread results in the other threads being sent the `SIGRT_1` signal so they are aware that they should switch credentials too, because `POSIX` requires that all threads use the same credentials but Linux actually handles it per thread. The reception of the signal interrupts the current `syscall` with `EINTR`, causing the loading of the `RPZ` zone to fail.
Fixes #6778.
I have:

rec: Delay the creation of RPZ threads until we have dropped privileges

---

pdns/lua-recursor4-ffi.hh
pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/recursordist/docs/lua-config/protobuf.rst
pdns/recursordist/docs/lua-scripting/dq.rst
regression-tests.recursor-dnssec/.gitignore
regression-tests.recursor-dnssec/requirements.txt
regression-tests.recursor-dnssec/runtests
regression-tests.recursor-dnssec/test_Protobuf.py

- Turn the protobuf options into a table because there are already too many of them
- Split the masks applied to the initiator to a separate `setProtobufMasks` directive
- Add the possibility to log only queries, or only responses
- Add the possibility to select queries (FFI only) and responses for export from the Lua hooks
- Add regression tests for the protobuf features
Closes #6361.
I have:

rec: Refactor Protobuf options, add query/response selection

---

pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst

This PR adds support for using more than one thread to distribute incoming queries to worker threads in the recursor.
Letting the recursor distribute queries based on a hash of the qname does wonder for the cache hit ratio, and very often results in much better DNS resolution performance than letting the kernel do the distribution via `reuseport`, or by having multiple threads listening on the same socket. However we have seen situation where having only one thread doing the distribution ends up being the bottleneck, mostly because one CPU core can't handle the load needed to keep many worker threads busy. Having more than one thread handling incoming queries, via `reuseport` if available, solves this issue while keeping the same cache hit ratio.
I have:

rec: Add support for several distributor threads

---

pdns/slavecommunicator.cc

When the final result of the slave-check get logged, always add the respective serials to the log line. This is very useful when debugging slave-check issues
I have:
- [partly] tested this code (only the cases without DNSSEC workarounds, but the code compiles)

Add the serials when logging the final result of a slave-check

---

build-scripts/test-recursor

Looks like mawk `match()` has a slightly different signature/behaviour than gawk. This replaces awk usage by perl.
I have:

recursor tests: replace awk command by perl

---

modules/tinydnsbackend/tinydnsbackend.cc
pdns/dnsdist-ecs.cc
pdns/dnsdist-ecs.hh
pdns/dnsdist.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsparser.cc
pdns/dnsparser.hh
pdns/lwres.cc
pdns/lwres.hh
pdns/pdns_recursor.cc
pdns/protobuf.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/test-dnsdist_cc.cc

This PR:
- Prevents an allocation and copy of the `DNS` query or response passed to `MOADNSParser`, and get rid of the weird `-12` dance (auth, rec) ;
- Makes `PacketReader` accepts a `string` instead of a `vector<uint18_t>` so we don't need to allocate a vector and copy our data to it (auth, rec, dnsdist) ;
- Removes a useless copy of the response in `arecvfrom()` (rec) ;
- Removes some string allocations and copies during `EDNS` processing (dnsdist) ;
- replaces a fixed 65k buffer allocated for every `TCP` connection by a dynamically allocated one (rec).
I have:

Get rid of some allocs/copies in DNS parsing

---

pdns/dnsdist-console.cc
pdns/dnsdist-ecs.cc
pdns/dnsdist-ecs.hh
pdns/dnsdist-lua-rules.cc
pdns/dnsdist-lua-vars.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsdistdist/docs/reference/constants.rst
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_Advanced.py

This adds `EDNSOptionRule`, used as follows (8 is edns-client-subnet):
```
warnlog(string.format("Script starting %s", "up!"))
newServer({address="8.8.8.8", pool="g1"})
newServer({address="8.8.4.4", pool="g2"})
addAction(EDNSOptionRule(8), PoolAction("g1"))
addAction(AllRule(), PoolAction("g2"))
getServer(0):setUp()
getServer(1):setUp()
```
Needs:
I have:

dnsdist: add EDNSOptionRule

---

pdns/dnsdist-lua.cc
pdns/dnsdist-web.cc

The default action for a dynamic block is `Action::None`, which doesn't mean that nothing will be done but that the global action will be applied instead. We failed to display that correctly in the console and via the `API`.
Reported by ph1 (thanks!).
I have:

dnsdist: Display DynBlocks' default action, None, as the global one

---

modules/gmysqlbackend/smysql.cc

Avoids build failure after #6842 on Debian (uses MariaDB) and SLES 12 (also MariaDB).
I have:

Workaround MariaDB pretending to be MySQL

---

pdns/pdnsutil.cc

As detailed in #6800, `pdnsutil check-zone` wrongly warns about RFC7505 null MX records. This PR remedies that.
I have:

check-zone: allow null MX, SRV

---

pdns/pdnsutil.cc

If you have duplicate zones, zone IDs or SOAs, check-all-zones will now produce errors like these:
duplicate SOA:
```
[Error] Another SOA for zone 'zeha1.example.org' (serial 2) has already been seen (serial 1).
[Error] Domain ID 99 of 'zeha1.example.org' in backend gsqlite3 has already been used by zone 'zeha1.example.org' in backend gsqlite3.
```
duplicate zone ID in different backends:
```
[Error] Another SOA for zone 'example.com' (serial 2847484148) has already been seen (serial 2847484148).
[Error] Domain ID 3 of 'example.com' in backend bind has already been used by zone 'example.com' in backend gsqlite3.
```
Fixes #6829 by means of adding checking in check-all-zones.
I have:

check-all-zones: find duplicate zones and SOAs

---

pdns/dnsdist-dynbpf.cc
pdns/dnsdist-dynbpf.hh
pdns/dnsdist-lua-bindings.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/ebpf.rst

Wanting to move from `DynBlockRulesGroup ` to `DynBPFFilter`, I found the `excludeRange` and `includeRange` methods missing, while the rest of the functionality between both ways of dynamically blocking was rather identical. So, I added them.
I have:

added :excludeRange and :includeRange methods to DynBPFFilter class

---

pdns/pdnsutil.cc

Before this PR, a double dot could make pdnsutil edit-zone abort completely with `Error: Found . in wrong position in DNSName myrecord.test..example.com`. With this PR, the normal 'please edit again' cycle is followed.
I have:

make edit-zone catch zoneparser exceptions as well

---

docs/settings.rst
pdns/common_startup.cc
pdns/mastercommunicator.cc

If there are multiple TSIG keys configured for a domain, PowerDNS will use the
first one retrieved from the backend, which may not be the correct one for the
respective slave. Hence, in setups with multiple slaves with different TSIG keys
it may be required to send NOTIFYs unsigned.
I have:

add option send-signed-notify to send NOTIFYs without TSIG signature

---

pdns/pdns_recursor.cc

rec: Disable only our own TCP listening socket when reuseport is enabled

---

regression-tests/tests/00dnssec-grabkeys/command

Because addzone.com is not in the regression testing named.conf, unbound does not know that it is a special name for which requests should be directed at PowerDNS.
I have:

do not leak requests for addzone.com to the Internet

---

pdns/pdns_recursor.cc

(cherry picked from commit adb6cd72c33eadaa60db7abdddea5ff1d29cf51b)
I have:

rec-4.1.x: Backport #6850: Disable only our own TCP listening socket when reuseport is enabled

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/guides/serverselection.rst
pdns/dnsdistdist/docs/reference/config.rst

This adds a new load balancing policy that is based on consistent hashing. Unlike the ``whashed`` policy, this distribution will keep consistent over time. Adding or removing servers will only remap a small part of the queries.
For the record, this also adds a`uuid` field to the `DownstreamState` class.
I have:

dnsdist: add consistent hash builtin policy

---

pdns/ixfrdist.cc
pdns/ixfrutils.cc
pdns/ixfrutils.hh
pdns/resolver.cc

* Avoid some copies during zone retrieval, reducing the memory usage
* Reserve memory in advance when possible to avoid reallocation
* Reduce lock contention and copy of zone information (records, diffs) when serving an actual query, by using shared pointers so we only need to hold the lock while retrieving or replacing a pointer, instead of having to hold it while copying the whole zone.   
I have:

ixfrdist: Reduce memory usage and lock contention

---

docs/changelog/4.1.rst

The "packet too short" log level change is present in both the 4.1.3 and 4.1.2 sections (around line 77). I confirmed it was in the 4.1.2 release via https://github.com/PowerDNS/pdns/commits/auth-4.1.2
I have:

changelog: fix dup of #6312 in 4.1.3, was in 4.1.2

---

docs/http-api/swagger/authoritative-api-swagger.yaml

I found some copy-paste oversight in the api docs, and corrected it based on the man page for "pdns_control retrieve" (which I assume does the same thing). I also used the axfr-retrieve api endpoint with pdns 4.1.3, it works as expected :)
I have:

API docs: fix zone axfr-retrieve description

---

pdns/dnsdist-ecs.cc

dnsdist: Fix a sign-comparison warning in isEDNSOptionInOpt()

---

pdns/dnsdistdist/docs/reference/dq.rst

Updates the documentation of `DNSQuestion.len` for accuracy. It was falsely reported to be the length of just the qname, which misled me as both a user and a developer.
I have:

dnsdist: Fix documentation of DNSQuestion.len

---

docs/settings.rst

It wasn't obvious to me, initially, that the loglevel values correspond to the libc syslog values (which you can often find in `/usr/include/sys/syslog.h`). Perhaps this was because I immediately disabled syslog output in favor of only stdout (which is captured by docker in my case).
Though, this is a subjective thing, and it does seem somewhat obvious to me now ...
I have:

docs: auth config settings: explain loglevel value

---

pdns/pdns_recursor.cc
pdns/rec_channel.hh
pdns/rec_channel_rec.cc
pdns/recursordist/docs/manpages/rec_control.1.rst
pdns/recursordist/html/index.html
pdns/recursordist/html/local.js
pdns/syncres.cc
pdns/syncres.hh
pdns/ws-recursor.cc

Keep track of what downstreams are causing the most timeouts. Useful for troubleshooting network connectivity issues rather than trolling servfails and manual testing.
I have:

Keep track of what destinations are causing the most timeouts

---

pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/guides/webserver.rst

My patch based on https://github.com/PowerDNS/pdns/pull/6343 prepared by @giganteous 
I made number of changes for it:
- Ported code to current master branch
- Introduced class which stores meta information about metrics (metric type, description). I do not like idea about mixing atomic counters and meta fields with big text blobs and I divided them
- Slightly changed code formatting
- Changed endpoint to /metrics as suggested by @dannyk81 
- Tested code and it works quite well for my case
I have:
- [*] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [*] compiled this code
- [*] tested this code
- [*] included documentation (including possible behaviour changes)
- [*] documented the code
- [] added or modified regression test(s)
- [] …

Added Prometheus stats support for dnsdist

---

pdns/rec-lua-conf.cc
pdns/recursordist/docs/lua-config/index.rst

As a distro maintainer, I'd like to ship a default Lua config file that also logs something, so users can know that they are not running the default empty configuration.
I intend to carry this as a 4.1 patch in Debian.
I have:

recursor: Add pdnslog to Lua configuration scripts

---

pdns/rec-lua-conf.cc

In Debian I want to ship a default Lua config file, which will modify the default behaviour (rgd. root keys). As such I want to clearly note this in the startup log. Therefore, add pdnslog.
Targets 4.1. master is in #6848.
I have:

recursor 4.1: Add pdnslog to Lua configuration scripts

---

regression-tests.nobackend/negcache-tests-dotted-cname/command
regression-tests.nobackend/negcache-tests-dotted-cname/pipe.py

This test failed on my Mac. I hope this PR makes the test work on more systems while not breaking it on a lot of systems.
I have:

 make negcache-tests-dotted-cname test portable between Python versions

---

docs/manpages/ixfrdist.yml.5.rst
pdns/ixfrdist.cc
pdns/ixfrdist.example.yml

* Don't override the original `TTL` in our `AXFR`/`IXFR` responses ;
* Group as many records as possible inside one `DNS` message, and send a message as soon as it is ready, so we can reduce the memory usage by not keeping all outgoing messages in memory, and send a lower number of messages ;
* Add an option to compress record while building the answer, off by default.
This PR could use a good review before merging.
I have:

ixfrdist: Fix TTL, optimize the construction of answers

---

pdns/opensslsigners.cc

The current code will only fail to release the allocated memory if called with an invalid algorithm, which won't happen, or if a memory allocation fails in which case this might not matter much.
Still, it's cleaner to release the memory properly and might avoid mistakes later if we look at this code while implementing a new crypto backend.
I have:

Release memory in case of error in the OpenSSL ECDSA constructor

---

pdns/rec_channel_rec.cc
pdns/syncres.cc
pdns/ws-recursor.cc

Convert a few uses to ```toLogString``` to print ```DNSName```'s that may be empty in a safer manner.
This helps with part of #6924 
I have:

rec: rec_control/ws toLogString

---

pdns/dnsdistdist/docs/guides/serverselection.rst

Small spelling mistakes
Fixed two small spelling mistakes in serverselection.rst guide
I have:

Fixed small spelling mistakes in serverselection.rst

---

docs/settings.rst
pdns/common_startup.cc
pdns/pdnsutil.cc

The documentation for the `direct-dnskey` setting currently only mentions additional DNSKEY records being fetched from the backend. However, the setting also affects `CDS` and `CDNSKEY` records.
I have:

document direct-dnskey setting also affects CDS and CDNSKEY records

---

pdns/opensslsigners.cc

LibreSSL 2.7.0 implemented some of the API calls introduced in the 1.1.0 version of OpenSSL.
Fixes #6943.
I have:

Fix compilation with LibreSSL 2.7.0+

---

pdns/mtasker_ucontext.cc

This avoids a crash on DEC Alpha systems. @ssb83 confirms that this fix works, as long as `stack-size` is a multiple of 8 (which it is by default).
I have:

realign ucontext stack after #6719

---

pdns/recursor_cache.hh

Otherwise the intermediary nodes will remain and consume memory until the tree is deleted from the index, which might never happen if we still have active entries for this specific qname and qtype.
This is not a huge issue for IPv4 entries because there is a limited number of entries in the index, but it is much more painful with IPv6 entries.
I have:

rec: Cleanup the netmask trees used for the ECS index on removals

---

pdns/dnsdist.cc

Reported by Yuni Kim, thanks a lot!
I have:

dnsdist: Fix compilation when SO_REUSEPORT is not defined

---

pdns/dnsproxy.cc
pdns/dnsproxy.hh
pdns/packethandler.cc

Before this patch, the scopebits on an ALIAS result from a backend would be thrown away. With this patch, we pass the scopebits down into the dnsproxy so it can apply it to the resulting A/AAAA records.
Related: #5469 
Should this be configurable?
I have:

[do not merge] apply ALIAS scopemask after chasing

---

pdns/lwres.cc
regression-tests.recursor-dnssec/test_ECS.py

 rec-4.1.x: Make sure that the ECS scope from the auth is < to the source

---

docs/settings.rst

Documentation update, added a note about correct configuration when master does not support either IPv4 or IPv6, but slave does.
Closes https://github.com/PowerDNS/pdns/issues/5899
I have:

If master doesnt support IPv4/IPv6, but slave does

---

pdns/dnsdist.cc

This changes how consistent hashing based query distribution is made to use `std::lower_bound` instead of iterating over hashes map.
Fix #6932 
I have:

dnsdist: do not iterate over hash map for chashed based query distribution

---

modules/gmysqlbackend/smysql.cc
modules/gpgsqlbackend/spgsql.cc
pdns/ssqlite3.cc

Add timing information when we run with query-logging. Turns one line into three. Lines are adorned with the value of 'this' so the three lines can be correlated even under load. Logs time spent for the 'execute' part and time spent until the last row is processed. This PR was inspired by a debugging session to find a performance problem with a customer, where this output would have been tremendously useful.
No timing calls are made unless query logging is enabled.
I have:

Enhance query-logging with timing for MySQL, PostgreSQL and SQLite

---

pdns/test-nameserver_cc.cc
pdns/testrunner.cc

move arg function to the testrunner

---

pdns/packethandler.cc
regression-tests/tests/ds-at-unsecure-delegation/expected_result
regression-tests/tests/ds-at-unsecure-delegation/expected_result.dnssec
regression-tests/tests/ds-at-unsecure-zone-cut/description
regression-tests/tests/ds-at-unsecure-zone-cut/expected_result
regression-tests/tests/ds-at-unsecure-zone-cut/expected_result.dnssec

When a DS query is received for a delegation in an unsigned zone, we responded with the delegation. This confuses various validators. With this PR, we authoritatively deny the presence of the DS.
I have:

respond correctly to DS query at delegation in unsigned zone

---

m4/pdns_enable_ixfrdist.m4
m4/pdns_with_lua.m4
m4/pdns_with_postgresql.m4

AS_HELP_STRING cares about whitespace preceding the call...
I have:

Fix ./configure --help alignment

---

pdns/dnsdemog.cc
pdns/dnsgram.cc
pdns/dnsreplay.cc
pdns/dnsscan.cc
pdns/dnsscope.cc
pdns/ixfrdist.cc
pdns/pdns_recursor.cc
pdns/slavecommunicator.cc

There were a number of styles for this exception object.
This enforces a single style (const, space before &).
I hope to write a wrapper for MOADNSException which includes the zone / record name...
It will be easier if this object is consistently named/typed...
I have:

Enforce style const MOADNSException &mde

---

pdns/test-dnsrecords_cc.cc

BOOST_CHECK_MESSAGE is designed to take a statement that describes a condition.
When `-l all` is used, it will print the statement, the condition, and
whether or not the condition passed.
With this change, output can appear like this:
test-dnsrecords_cc.cc:72: error: in "test_dnsrecords_cc/test_record_types": record types should be sorted such that 13 >= 21
Checking record type HINFO test #1
test-dnsrecords_cc.cc:72: info: check 'record types should be sorted such that 13 >= 13' has passed
I have:

Fix use of BOOST_CHECK_MESSAGE in test-dnsrecords_cc.cc

---

docs/modes-of-operation.rst
pdns/slavecommunicator.cc

If SOA-checks against a master with failing AXFR still succeed, we would
constantly try to AXFR the zone. To avoid this, we add the zone to the list
of failed slave-checks to suspend slave-checks (and subsequent AXFR) for
this zone for some time.
I have:

add incremental slave-check backoff also for failed AXFR 

---

regression-tests.api/runtests.py
regression-tests.api/test_RecursorConfig.py

Fixes the issue in the API regression tests reported in https://github.com/PowerDNS/pdns/pull/6962#issuecomment-420638541 
- Really make sure that the `ACL` is updated via the `API`
- Pass the initial `allow-from-file` value from the configuration instead of the command line so it can be overridden.
I have:

 rec: Fix the allow-from-file test in the API regression tests

---

pdns/dnsdist-cache.cc
pdns/dnsdist-ecs.cc
pdns/dnsdist-ecs.hh
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua-vars.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/dq.rst
pdns/test-dnsdist_cc.cc
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_EDNSOptions.py

Enabling access to the raw binary content of incoming `EDNS` options from `Lua` rules via `DNSQuestion::getEDNSOptions()`. This call returns a table with option code as keys and `EDNSOptionView`s as values. The size of the raw binary content can be retrieved via `EDNSOptionView::size` and the content with `EDNSOptionView::getContent()`, the later returning the binary content as a string.
I have:

dnsdist: Add DNSQuestion:getEDNSOptions() to access incoming EDNS options

---

pdns/dnsdist-web.cc

I added number of alive servers in pool for Prometheus. That's very useful for monitoring purposes.
I have:

dnsdist: export Prometheus metric about number of alive servers in pool

---

docs/settings.rst

fixing doc rst error by extending dashes

---

pdns/dnsdistdist/docs/statistics.rst

The documentation was technically correct, but everyone would expect the 'questions' and 'responses' metrics to match up. Since it was documented that this was not the case, I suggest not fixing the metric, but at least to document explicitly that 'responses' measures 'responses received from backend', and how to get the number you expect (by adding up cache-hits).
I have:

document explicitly that the dnsdist 'responses' metric is actually 'backend responses'

---

configure.ac
m4/pdns_check_libcrypto_eddsa.m4
pdns/opensslsigners.cc
pdns/recursordist/configure.ac
pdns/recursordist/m4/pdns_check_libcrypto_eddsa.m4
pdns/test-signers.cc

This implements algorithm 15 and 16 support in the OpenSSL signer. It will only be used if the (as of yet unreleased) OpenSSL 1.1.1 is used.
Please review carefully.
CC: @mind04 
I have:

Add support for OpenSSL 1.1.1's ed25519 and ed448 for signing and verifying

---

pdns/dnsrecords.hh
pdns/lwres.cc
pdns/lwres.hh
pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/rec-protobuf.cc
pdns/rec-protobuf.hh
pdns/recursordist/docs/lua-config/protobuf.rst
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/test_Protobuf.py

Several users have reported the need to export the content of of more record types found in responses. This pull request adds support for optionally exporting the content of `MX`, `NS`, `PTR`,  `SPF`, `SRV` and `TXT` record types, in addition to the existing `A`, `AAAA` and `CNAME`. The implementation is limited to those types because it special cases them.
An other option would be to implement all `xfr*()` methods to be able to get the "wire version" of all types.  If we decided to go that road, I think it might make sense to extract the `xfr*()`methods from `DNSPacketWriter` into a `DNSRecordWriter` implementing all `xfr*()` methods, that would be called by `DNSPacketWriter` but could also be used from the protobuf logger.
This PR is based on #6698 and will need a rebase after it has …

rec: Support exporting more record types via protobuf

---

pdns/dnsdistdist/docs/statistics.rst

The various statistics kept by dnsdist do add up to a coherent picture, this PR documents how.
The wording leaves a little bit of wiggle room that this is how it 'should' be. If we find that it isn't like this, the documentation should be leading.

Clarify meaning of dnsdist statistics

---

pdns/serialtweaker.cc

Setting the "SOA-EDIT" value for a zone to "NONE" causes an error:
'SOA-EDIT type 'NONE' for zone ZONENAME is unknown.'
The calculateEditSOA function could return the SOA as-is in such cases.

auth: Add support for "NONE" SOA-EDIT kind

---

builder-support/gen-version

Thanks to a comment by @atosatto (and the fact we have not published master packages yet) I managed to retain the 0.0.XXX versioning for master packages that don't break the package versioning and still allow upgrades from existing master packages.
I have:

pdnsbuilder: Make the version number even better

---

pdns/dnsdist-tcp.cc

Winfried and others noted that our TLS responses were super slow. This turned out to be caused by the Nagle
algorithm which we failed to disable. https://en.wikipedia.org/wiki/Nagle%27s_algorithm
I have:

dnsdist did not set TCP_NODELAY, causing needless latency

---

README.md

Yak: (auth at least) README has instructions for Debian 8.0, should not say '.0' and should be updated for 9
I have:

Update readme for debian 9

---

pdns/iputils.hh
pdns/test-iputils_hh.cc

The insertion is a bit slower as a result (~ +25%) but removal is much, much more faster for large sets as it was O(n) previously.
Walking all the entries might be a bit slower as well, but this change has no impact on the lookup speed, which is the critical point for the NMT.
I have:

Store NetmaskTree nodes in a set for faster removal

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

The records other than the `CNAME` for the initial target in `ANSWER` are not, nor are the `ADDITIONAL` ones, but `AUTHORITY` records are.
I have:

rec: Authority records in AA=1 CNAME answer are authoritative

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

The records other than the `CNAME` for the initial target in `ANSWER` are not, nor are the `ADDITIONAL` ones, but `AUTHORITY` records are.
(cherry picked from commit cdc5d0c09ac148c805e91411d863b04b144ebbf9)
Backport of #6979 to rel/rec-4.1.x.
I have:

rec-4.1.x: Authority records in AA=1 CNAME answer are authoritative

---

build-scripts/travis.sh

Yak: recursor and dnsdist rely on symlinks into the 'main' pdns source tree. Travis should check for dangling symlinks.
I have:

Travis dangling symlinks

---

pdns/rfc2136handler.cc

One of the PreReq error messages does not actually tell you the problem domain. Now it does.
I have:

slightly improve rfc2136 error message on failed prerequisite: what name

---

pdns/dnsscope.cc

Disable the histograms in dnsscope for boost versions below 1.48

auth: fix el6 build with default boost

---

pdns/dnsdistdist/tcpiohandler.cc

Otherwise we leak the memory allocated to handle the `TLS` connection if the handshake doesn't succeed correctly.
I have:

dnsdist: Release memory on DNS over TLS handshake failure

---

pdns/pdns_recursor.cc

This commit prevents a leak of DNSComboWriter in the catch-all exception
handler.

pdns-recursor: avoid a memory leak in catch-all exception handler

---

pdns/dnsdist-dynblocks.hh
pdns/dnsdist-lua-inspection.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-rings.hh
pdns/dnsdist-web.cc
pdns/dnsdist.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/docs/guides/dynblocks.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc
regression-tests.dnsdist/test_DynBlocks.py

After thinking a bit more about the needs described in #6907, I could not find a meaningful scenario where we want different actions for different rates except for the warning case. So for now I took the easy route of just adding a warning threshold, and we can improve on it later if we find that we need more than that.
Closes #6907.
I have:

dnsdist: Add warning rates to dynBlockRulesGroup rules

---

pdns/syncres.cc

directResolve function is used by lua-recursor4 in various callbacks. As
a result an exception thrown from this function is caught in generic
exception handlers at the end of startDoResolve (pdns_recursor).
Specifically, ImmediateServFailException is caught in the catch-all
exception handler, which obscures the origin of the error.
This commit adds handling of all exceptions inside directResolve and
converts them to error code (-1). This way, an exception in this
function is handled properly in startDoResolve and ServFail is sent
downstream.
To clarify, in case of exception the return DNSRecord vector is cleared
to make sure that old behavior is preserved, when in case of exception
the vector was not referenced in any way.

pdns-recursor: properly handle exceptions thrown from lua-recursor4

---

pdns/pdns_recursor.cc

This commit prevents a leak of DNSComboWriter in the catch-all exception
handler, which could be triggered by an `ImmediateServFailException` while invoking `followCNAMERecords`, `getFakeAAAARecords` or `getFakePTRRecords` from a `Lua` hook.
(cherry picked from commit cbb097d8581dbb27d81be3a3022a96b8ad08e295)
I have:

rec-4.1.x: avoid a memory leak in catch-all exception handler

---

pdns/dnsdist-web.cc

These were missing from the output. I've put them above the for loop. According to the Open Metrics standard, metrics don't have to be directly underneath the HELP or TYPE (and only one for each metric is allowed).
I have:

dnsdist: Add HELP and TYPE for dnsdist_server_ stats

---

pdns/opensslsigners.cc

The use of smart pointers makes memory management much easier, while preventing leaks. There is a small memory and CPU overhead to pay since we can't use `std::make_unique` to do only one allocation, but it was not noticeable in my very limited tests.
I have:

Use unique pointers in the OpenSSL signer

---

regression-tests.dnsdist/test_API.py

This ACL test was relying on a specific ordering since https://github.com/PowerDNS/pdns/pull/6962 which is not guaranteed to be true.
Thanks to @neilcook for reporting this!
I have:

dnsdist: Nodes in NMG are now ordered, fix the API regression tests

---

pdns/dnsdist-lua.cc

Hopefully fixes #7091, although I did not test against the development version of Boost.
I have:

dnsdist: Fix return-type detection with boost 1.69's tribool

---

README.md
docs/lua-records.rst

Documentation for Reverse DNS functions, using Lua with generic SQL, plus README improvements
Big thanks to @ahupowerdns for helping me out with the reverse DNS functions :)
**Documentation (`docs`) changes**
- Documented previously undocumented/uncommented Lua functions with in depth examples
- `createForward` 
- `createReverse`
- `createForward6`
- `createReverse6`
- Added a section for using Lua records with generic SQL backends, including an example set of SQL INSERT queries which work on both MySQL and PostgreSQL (and maybe others)
- Corrected `closest` to `pickclosest` in several areas, as it was incorrect
**README.md changes**
- Added packages required to build PowerDNS on Ubuntu 18.04
- Added build instructions for Sphinx docs (the `docs` folder), as PowerDNS sorely needs more …

Documentation for Reverse DNS functions, using Lua with generic SQL, plus README improvements

---

build-scripts/travis.sh

I have seen our `Lua` records regression tests fail from time to time on Travis, and I hope this change will help understanding why :)
I have:

auth: Print the content of pdns.log when the regression tests fail

---

builder-support/specs/dnsdist.spec
builder-support/specs/pdns-recursor.spec
builder-support/specs/pdns.spec

Specfile updates for rec, auth and dnsdist, to use lua instead of luajit on EL7/ARM64.
I have:

fixes for el7 on arm64

---

pdns/dnsdist-console.cc
pdns/dnsdist-console.hh
pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdistdist/docs/reference/config.rst

`setConsoleOutputMaxMsgSize` lets you tune the maximum size of a console message.
Fix #7084
For the record, I moved `{get,put}MsgLen32` in `dnsdist-console.cc` as both were not used anywhere else anymore.
I have:

dnsdist: add setConsoleOutputMaxMsgSize function

---

contrib/ProtobufLogger.py
pdns/dnsmessage.proto
pdns/nod.cc
pdns/nod.hh
pdns/pdns_recursor.cc
pdns/rec-protobuf.cc
pdns/rec-protobuf.hh
pdns/recursordist/docs/settings.rst
pdns/recursordist/test-nod_cc.cc

This PR extends the work on Newly Observed Domains by adding support for Unique DNS Responses; these are never-seen-before triplets of (qname, qtype, RR(rrname, rrtype, rrdata)). These are used by folks to detect potential evilness, such as fast-flux DNS.
Completely new to this PR is the ability to pass the NOD and UDR status via Protobuf. These are only set in the Response Protobuf packet. Protobuf responses from the packet cache have these flags cleared, as we only want to indicate this once. 
I have:

Unique DNS Responses

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdist-lua.hh
pdns/dnsdist-web.cc
pdns/dnsdist.hh
regression-tests.dnsdist/test_API.py

dnsdist: Add a 'creationOrder' field to rules

---

pdns/dnsname.hh

Boost 1.48 does not play nice with the storage used for dnsname.
I have:

Fix el6 builds

---

builder-support/specs/pdns-recursor.spec

Recent changes (around the NOD work) broke our compatibility with the old Protobuf version of EL6, so we're dropping support.
I have:

fix el6 recursor build by disabling protobuf support

---

builder-support/debian/authoritative/debian-jessie/pdns-backend-bind.postinst
builder-support/debian/authoritative/debian-stretch/pdns-backend-bind.postinst
builder-support/debian/authoritative/ubuntu-trusty/pdns-backend-bind.postinst

Tested on Xenial, upgrading from 4.0.0~alpha2, 4.0.5 and 4.1.4, with an edited simplebind.conf, bindbackend.conf and both edited.
Also tested upgrades on Bionic, Jessie and Stretch.
cc @zeha for a review 
Fixes #7065
I have:

Fix up the BIND config files on upgrade

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/validate.cc
pdns/validate.hh

There are some weird, maybe even broken, dnssec implementations out there. This pull is a workaround for the sign with inception is NOW problem. This is done by a loadbalancer vendor with a letter and a number in it's name. This is bad because only a very small time difference between signer and validator is enough for a domain to go bogus from time to time. 
This pull is adding an option to extent the signature validity by a number of seconds at inception and expire. This will increase the resilience of the validation process and avoid a number of hard to explain bogus results for high profile domains. The default is to add 60 seconds to the signature lifetime. If you think you need to increase this value check your clock. Ntp is your friend...
I have:

rec: extend the validity period of signatures by a number of seconds

---

pdns/dnsdist-lua-rules.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsdistdist/docs/rules-actions.rst

This adds the PoolAvailableRule. Can be used to apply different pools based on availability.
I have:

Add a PoolAvailableRule to easily add backup pools

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

This reverts commit 4caae205f06cb989c415a9c1e0f4c5ec667236a2.
It turns out that authority records in AA=1 CNAME answer may, or may not, be authoritative, and that in some cases considering them as authoritative causes DNSSEC validation failures.
I have:

rec-4.1.x: Revert "rec: Authority records in AA=1 CNAME answer are authoritative"

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

Backport of #7171 to rel/rec-4.1.x.
(cherry picked from commit 25e654f7f9725c474d96c7eca57cb34fe41c4669)
I have:

rec-4.1.x: Refuse queries for all meta-types

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

rec: Revert 'Keep the EDNS status of a server on FormErr with EDNS'

---

pdns/dnsdist.cc

This just fixes compiler warning that results in a build failure on OBS due to policy for openSUSE.
I have:

Fix compiler warning about returning garbage

---

pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/tcpiohandler.cc

dnsdist: Fix warnings, mostly unused parameters, reported by -Wextra

---

m4/pdns_check_lua_hpp.m4

Fix `lua.hpp` existence check to actually work
I have:

m4: Fix lua.hpp check to actually work

---

pdns/dnsparser.cc

Rename the `skipLabel` function to `skipDomainName`, since that's what it actually does. I found the parser code very confusing until I figured this out.
I have:

Rename skipLabel function to skipDomainName

---

pdns/lwres.cc
pdns/lwres.hh
pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/recursordist/docs/lua-config/protobuf.rst
pdns/recursordist/test-syncres_cc.cc
pdns/remote_logger.hh
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/test_Protobuf.py
regression-tests.recursor-dnssec/test_RPZ.py

So protobuf messages can be exported to several servers. At the moment we support only using the same exact options (timeouts, log queries, messages or both, ...) for all servers.
I have:

rec: Add support for more than one protobuf server

---

docs/settings.rst
pdns/auth-carbon.cc
pdns/common_startup.cc
pdns/dnsdist-carbon.cc
pdns/dnsdist-lua.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/guides/carbon.rst
pdns/rec-carbon.cc
pdns/rec_channel_rec.cc
pdns/recursordist/docs/settings.rst

This pull request adds two variables to carbon keys, namespace and instance. It is related to #6941 and #2362.
In environments with multiple pdns instances the predefined keys limit the way to distinguish between each of these instances. With namespace and instance made variable it is now possible to add the team, location, instance name or role into the metric name and therefore group them together for example with the database.
The documentation was updated for what is implemented at the moment. Everything is kept backwards compatible to avoid problems for current users upgrading.
But there are two parts where I do not know how to keep it backwards compatible.
1. In pdns/dnsdist-carbon.cc#143 the querycount metric is not per host and the instance is replaced with qname. Is it okay to …

add namespace and instance variable to carbon key

---

pdns/dnsrecords.cc
pdns/dnsrecords.hh
pdns/pdnsutil.cc
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

This is a copy of the check done in `pdnsutil check-zone` that will trigger an API error when trying to create or update an MX record with a non hostname content.
This fix #6636 
I have:

auth: api - Check DNSNames that should be hostnames

---

pdns/dnssecinfra.cc

And rewrite the message a bit.
Remove trailing `\n` from `pdns/dnssecinfra.cc:makeDSFromDNSKey`'s  `std::runtime_error()` message, and rewrite the error message itself a bit.
The `\n` made syslog a bit wacky:
pdns_server[3070]: Exception building answer packet for 779141.xyz/CDS (Asked to a DS of unknown digest type 3
pdns_server[3070]: ) sending out servfail
I didn't test this. :grimacing: 
I have:

Remove trailing \n from runtime_error message

---

docs/manpages/pdnsutil.1.rst
docs/settings.rst

In `pdnsutil.1`:
* Add Ed25519 and Ed448 to the list of DNSSEC algorithms
* Since ECC algorithms only support one valid key size, document what it is.
I have:

pdnsutil.1 & settings: Add Ed25519 and Ed448, document ECC keysizes, remove old algos

---

builder-support/debian/dnsdist/ubuntu-trusty/dnsdist.install

It seems that the debhelper version in trusty needs this to package the binary
I have:

Packages: add dnsdist.install for Ubuntu Trusty

---

pdns/syncres.cc

#5252 fixed part of the issue by ensuring we were talking to . and the SOA was for . (and fixed my CNAME example I was able to reproduce with).
#6112 still has issues because these conditions are still satisfied when using 8.8.8.8 under certain conditions.
By ensuring we have AA=1 this still works for cases like:
- Forwarding to a root server
- Hosting root zone ourselves in rec
and avoids all the nasty surprises you get otherwise.
I have:

rec: Avoid setting a root NX unless we have AA=1

---

build-scripts/travis.sh

The verisignlabs web server appears to be down; also, this other version has some important ECDSA fixes.
I have:

auth-4.0.x: switch to patched jdnssec from more reliable web server

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/guides/serverselection.rst
pdns/dnsdistdist/docs/reference/config.rst

This adds an optional UUID column to the `showServers()` output. This PR also tries to clarify what parameters the `chashed` distribution is based on.
I have:

dnsdist: add optional UUID column to showServers()

---

build-scripts/travis.sh

(cherry picked from commit 20445e6958184a6ca1e1eb7339434f6e77a8bb45)
Backport the jdnssec-tools upgrade.
I have:

upgrade to jdnssec-tools 0.14

---

pdns/resolver.cc

Without these patches, PowerDNS even parses NXDOMAIN responses and falsely uses
wrong SOA records, i.e. the SOA record of a parent zone in authority section
when answering with NXDOMAIN.
Patch 1: ignore NXDOMAIN responses
Patch 2: only use SOA RR if the name of the RR matches the qname
Fixes https://github.com/PowerDNS/pdns/issues/7058
It does not add all sanity checks, but it fixes issue 1 and 3. For issue 2 I do not found a solution as it seems all reponse sections (answer, authority, additional) are treated equally by the parser. Anyway, fixing issue 1+3 is sufficient.
I have:

SOA-check: reject nxdomain response and check label of RR against qname

---

pdns/dnsdist-lua-vars.cc
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/constants.rst

We can do NoRecurseAction() but not similar actions within a Lua rule nor as a dynamic block action.
This is potentially silly, please just close if it doesn't make sense to be doing - notably it's somewhat confusing because the query is put into the query ring before actions so it makes things like grepq look a bit weird.
I have:

dnsdist: Allow NoRecurse for use in dynamic blocks or lua rules

---

build-scripts/travis.sh
docs/manpages/ixfrdist.yml.5.rst
pdns/Makefile.am
pdns/ixfrdist-stats.cc
pdns/ixfrdist-stats.hh
pdns/ixfrdist-web.cc
pdns/ixfrdist-web.hh
pdns/ixfrdist.cc
pdns/ixfrdist.example.yml
pdns/webserver.cc
pdns/webserver.hh
pdns/ws-auth.cc
pdns/ws-recursor.cc
regression-tests.ixfrdist/requirements.txt
regression-tests.ixfrdist/test_Stats.py

This PR adds prometheus statistics to ixfrdist. It also refactors the `WebServer` class somewhat to make it more reusable (like for ixfrdist :smile:).
I've opened this PR early for comments on the code and to get some more ideas for statistics.
ToDo:
Future work:
- Make the webserver PW/API-key runtime-configable
- Add an API to ixfrdist
CC: @atosatto
I have:

Add metrics to ixfrdist

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-snmp.cc
pdns/dnsdist.hh
pdns/dnsdistdist/DNSDIST-MIB.txt
pdns/dnsdistdist/dnsdist-secpoll.cc
pdns/dnsdistdist/docs/statistics.rst
regression-tests.dnsdist/test_API.py

This PR adds the security status to the SNMP, carbon and prometheus statistics. It also adds a `showSecurityStatus` function.
Closes #7194
I have:

dnsdist: expose secpoll status

---

pdns/dnsdist.hh

dnsdist: Remove useless uint64_t* type from DNSDistStats::entry_t

---

pdns/recursordist/test-syncres_cc.cc

Otherwise we get random test failures when the `RRSIG` is generated after the number of seconds since epoch increased. Yes, there was still yet another place where we were calling `time()` in those tests..
I have:

rec: Use the SyncRes time when computing the RRSIG validity time

---

docs/domainmetadata.rst
docs/settings.rst
pdns/common_startup.cc
pdns/ws-auth.cc
regression-tests.api/test_Zones.py
regression-tests.api/test_helper.py

Previously, you had to set API-RECTIFY metadata on every zone you wanted to
have automatically rectified on changes through the API. With this change, the
default behaviour is to do a rectify, but this can globally be cahged with the
setting default-api-rectify, and overriden per zone.
It fixes #7231
I have:

Make api changes do a rectify by default, add an option to disable

---

pdns/ixfrdist.cc
pdns/ixfrutils.cc
pdns/ixfrutils.hh
regression-tests.ixfrdist/test_IXFR.py

`ixfrdist` was arbitrarily using a TTL of `3600` for `SOA` records.
I have:

ixfrdist: Preserve the correct TTL for SOA records

---

pdns/recursordist/README.md

recursor README was outdated in terms of Debian 9 build dependencies.
I have:

add some debian 9 recursor build deps

---

docs/conf.py

This fixes `LaTeX Error: Too deeply nested` while generating auth docs.
I have:

auth: docs - increase latex maximum list depth

---

docs/lua-records/functions.rst
pdns/lua-record.cc
regression-tests.auth-py/test_LuaRecords.py

Fixes -3 and -4 of #6892
This PR adds a `backupSelector` parameter to the `ifportup` and `ifurlup` methods. This is used to be able to customize the selector used when no candidate is declared as UP (instead of the default `random` one). This also adds the `all` selector that can be used to return all candidates.
I have:
What do you think ? ;-)

Improved Lua records - Added all selector, and backupSelector fallbacks

---

pdns/packethandler.cc
pdns/slavecommunicator.cc

Use a cache able soa record for the serial check caused by notify.
Ps. the cache is cleared after every axfr, so this is fine
I have:

Use a cache able soa record for the serial check caused by a notify

---

pdns/recursordist/docs/dns64.rst
pdns/recursordist/docs/lua-scripting/hooks.rst

A few typos in the documentation fixed.
* typo in ipv6 address explaining the example
* old 404 link back to the dns64 doc from the hooks doc
Please check my syntax. I've never have touched `rst` before. :-)
I have:

Fixed typos around DNS64 lua docs

---

pdns/rec_channel.cc
pdns/rec_channel.hh
pdns/rec_control.cc

Otherwise `rec_control` gets stuck when the queue is full. The recursor itself might also have encountered the same issue in `handleRCC()`.
Fixes #1898.
I have:

rec: Use the timeout passed to rec_control for sending too

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/tcpiohandler.cc
pdns/dnsdistdist/tcpiohandler.hh

Otherwise a thread can replace the shared pointer hold by the `GnuTLSIOCtx` while another thread is accessing it. The usage count is not incremented since no copy is made, so the content might get deleted while a thread is still accessing it, leading to use-after-free and possibly a crash.
Also fixes the type of `ticketsKeysRotationDelay` and `numberOfTicketsKeys`, apparently broken since the `localbind_t` type accepts an integer value.
I have:

dnsdist: Protect GnuTLS tickets key rotation with a read-write lock

---

docs/lua-records/index.rst
docs/settings.rst
pdns/common_startup.cc
pdns/packethandler.cc
regression-tests.auth-py/authtests.py

This PR standardize LUA records spelling to the plural form.
I have:

auth: make --enable-lua-records switch plural

---

m4/pdns_with_ebpf.m4

It turns out that RH decided to backport only the tracing subsystem part of eBPF as a "Technology Preview" in the RHEL / Centos 7.6 kernel, so most of the eBPF stuff is present but not what is needed
to use the networking parts.
With this change, eBPF support is disabled when `SO_ATTACH_BPF` is missing since we can't attach our filter to a socket without that anyway. Tested on CentOS 7.6 and Arch.
I have:

dnsdist: Check that SO_ATTACH_BPF is defined before enabling eBPF

---

docs/backends/generic-mysql.rst
docs/backends/generic-odbc.rst
docs/backends/generic-oracle.rst
docs/backends/generic-postgresql.rst
docs/backends/generic-sqlite3.rst

For 4.2, the `change_date` column was removed. This means that the schemas as currently shown in the docs break 4.1 installs. With this PR, we link to the 4.1 schemas for users who have not upgraded yet.
Closes #7254.
I have:

docs: link to 4.1 gsql schemas
