PowerDNS/pdns

pdns/ixfrutils.cc
Fix a regression introduced in #6885.
I have:
=> ixfrdist: Fix invalid buffer usage in getSerialFromMaster()

docs/manpages/ixfrdist.yml.5.rst
`workdir` does nothing; `work-dir` works.
I have:
=> ixfrdist: fix doc nit

pdns/reczones.cc
Per discussion on the mailing list removing forward-zones (or other data) would not purge the cache(s). This produces some surprises when you expect things to go back to normal. OTOH it would re-purge all existing data anyways, so just do both.
"Works for me" but might be doing something silly here.
I have:
=> Purge all auth/forward zone data including subtree.

docs/changelog/4.1.rst, docs/secpoll.zone
what it says in the title.
I have:
=> Changelog + secpoll for auth 4.1.4

docs/changelog/4.1.rst
pull-request #6648 is mysql transaction-isolation syntax change
pull-request #6848 is lua logging stuff
I have:
----
Do let me know if you find these more annoying than helpful :)
=> changelog: 4.1.4 back-ported #6648 not #6848

docs/http-api/swagger/authoritative-api-swagger.yaml, pdns/ws-auth.cc, regression-tests.api/test_Zones.py
Implements #5736.
Someone else please type in docs.
I have:
=> Auth API: add zone lookup by /zones?zone=example.org.

pdns/dnsdistdist/docs/reference/dq.rst, pdns/recursordist/docs/lua-scripting/dq.rst
=> docs: Fix minor grammar issues

build-scripts/test-recursor, configure.ac, m4/pdns_enable_backend_unit_tests.m4, m4/pdns_enable_unit_tests.m4, pdns/lua-recursor4.hh, pdns/lwres.cc, pdns/lwres.hh, pdns/pdns_recursor.cc, pdns/rec_control.cc, pdns/recursordist/docs/settings.rst, pdns/recursordist/test-syncres_cc.cc, pdns/reczones.cc, pdns/syncres.cc, pdns/syncres.hh
Backported:
- #6436 
- #6465 
- #6518 
- #6557 
- #6804 
- #6809 
- #6812 
- #6873
I have:
=> Recursor 4.1.4 backports

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.1.rst, pdns/recursordist/docs/settings.rst
=> Recursor 4.1.4 changelog and secpoll

pdns/rec_channel_rec.cc, pdns/recursordist/docs/manpages/rec_control.1.rst, pdns/syncres.cc, pdns/syncres.hh
Dumps the throttle map.
Probably not the cleanest method, open to suggestions and education on how to accomplish this better.
I have:
=> Dump the throttle map

pdns/rec-lua-conf.cc, regression-tests.recursor-dnssec/test_Protobuf.py
=> rec: fix outgoingProtobufServer config instantiation

docs/http-api/cache.rst, docs/http-api/index.rst, docs/http-api/swagger/authoritative-api-swagger.yaml
=> Document authoritative server cache endpoint

pdns/ws-recursor.cc
Make this a bit more readable
I have:
=> rec: Minor nit

pdns/ixfrdist.cc
Fixes a missing ) in an error message.
I have:
=> closing ) nit

pdns/recursor_cache.hh
=> rec-4.1.x: Cleanup the netmask trees used for the ECS index on removals

pdns/rec_channel_rec.cc
=> rec: clear all caches on (N)TA changes.

docs/requirements.txt, pdns/dnsdistdist/docs/requirements.txt, pdns/recursordist/docs/requirements.txt
See https://github.com/sphinx-doc/sphinx/issues/5417
I have:
=> Sphinx 1.8.0 seems broken, use any other version available instead

docs/requirements.txt, pdns/dnsdistdist/docs/requirements.txt, pdns/recursordist/docs/requirements.txt
(cherry picked from commit 424a5ee31cd82870da5e1df4b908735967e2912a)
I have:
=> auth-4.1.x: Sphinx 1.8.0 seems broken, use any other version available instead

docs/requirements.txt, pdns/dnsdistdist/docs/requirements.txt, pdns/recursordist/docs/requirements.txt
(cherry picked from commit 424a5ee31cd82870da5e1df4b908735967e2912a)
I have:
=> rec-4.1.x: Sphinx 1.8.0 seems broken, use any other version available instead

pdns/dnsproxy.cc, pdns/dnsproxy.hh, pdns/packethandler.cc
(cherry picked from commit 0abea1ca19249f9028e85dec3cf7535d0598fede)
I have:
=> apply ALIAS scopemask after chasing

modules/remotebackend/Gemfile.lock, modules/remotebackend/regression-tests/Gemfile.lock
=> Update the required version of ffi in the remote backend

pdns/mtasker.hh
This prevents crashes on some architectures and yields performance improvements on others.
I have:
=> align mthread stacks on 16-byte boundaries

pdns/pdns_recursor.cc, pdns/rec-snmp.cc, pdns/rec_channel_rec.cc, pdns/recursordist/RECURSOR-MIB.txt, pdns/recursordist/docs/metrics.rst, pdns/syncres.hh
Untested, should fix #6924.
I have:
=> rec: Drop incoming queries with a qdcount of 0

README.md, pdns/README-dnsdist.md, pdns/recursordist/README.md, regression-tests/README.md
=> Improve Readmes

pdns/dnsdistdist/docs/reference/config.rst
A documentation mistake
I have:
=> DNS over TLS is only possible via TCP/IP

pdns/ixfrdist.cc, regression-tests.ixfrdist/test_IXFR.py
Please see the individual commits.
I have:
=> various ixfrdist fixes/improvements

pdns/dnsdistdist/docs/guides/webserver.rst
=> Fix several sphinx warnings in the dnsdist docs.

pdns/recursordist/test-syncres_cc.cc
Introduced by a conflict between #6708 and #6979.
I have:
=> rec: Fix a compilation issue in the SyncRes unit tests

pdns/recursordist/docs/lua-config/rpz.rst
We did not make it clear how multiple RPZs are consulted. We now do.
=> document how multiple RPZs are consulted

build-scripts/travis.sh
(cherry picked from commit 280c2f89caaa1726fd02e6315e26f7b683ed6781)
I have:
=> rec-4.0.x: Backport tests: lower dnsbulktest threshold in travis

builder-support/dockerfiles/Dockerfile.rpmbuild, builder-support/dockerfiles/Dockerfile.target.centos-6, builder-support/specs/pdns.spec
=> make auth builder work on el6

pdns/recursordist/docs/settings.rst
=> rec: fix all warnings in the docs

pdns/rpzloader.cc
It's nice to know which zone is being worked on, as a large number of large zones provides a mix of messages with little context.
I have:
=> rec: RPZ - Include zone name in loading and indexed message

builder-support/debian/authoritative/debian-jessie/pdns-server.install, builder-support/debian/authoritative/debian-stretch/pdns-server.install, builder-support/dockerfiles/Dockerfile.dnsdist, builder-support/dockerfiles/Dockerfile.recursor, pdns/dnsdistdist/Makefile.am, pdns/recursordist/Makefile.am
This fixes an issue with the ixfrdist package and re-adds licenses to the dnsdist and recursor tarballs
I have:
=> Several Debian pkg fixes

builder-support/specs/pdns.spec
Reported by @phonedph1 on IRC.
I have:
=> Fix el6 post install issue with auth

builder-support/dockerfiles/Dockerfile.target.amazon-2
Our EL7 specs work without trouble on Amazon Linux 2.
I have:
=> add support for building Amazon Linux 2 packages

pdns/pdns_recursor.cc
This is a bit tricky because we need to release the pointer when we start a new `MThread`, but it makes memory leaks and use-after-free much less likely.
I have:
=> rec: Wrap our DNSComboWriter objects in smart pointers

pdns/dnsdist-cache.cc
=> Fix format string issue on 32bits arm

pdns/dnsdist-lua.cc, pdns/dnsdist.cc, pdns/dnsdistdist/docs/reference/config.rst, regression-tests.dnsdist/test_DynBlocks.py
=> dnsdist: Support the NXDomain action with dynamic blocks

builder-support/dockerfiles/Dockerfile.target.ubuntu-cosmic
So we have packages for the upcoming Ubuntu version.
I have:
=> Add Ubuntu Cosmic Cuttlefish build target

modules/geoipbackend/geoipbackend.cc
Catch and handle errors reading YAML config file.
I have:
=> geoipbackend: Handle read error for config file

pdns/dnsdistdist/docs/guides/webserver.rst
This documents with an example updating the ACLs via the API.
Fix #7099
I have:
=> dnsdist docs: update documentation on updating ACLs via the API

pdns/dnsdist-tcp.cc
=> dnsdist: Wrap TCP connection objects in smart pointers

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/configure.ac, pdns/dnsdistdist/dnsdist-secpoll.cc, pdns/dnsdistdist/dnsdist-secpoll.hh, pdns/dnsdistdist/docs/reference/config.rst, pdns/misc.cc, pdns/misc.hh, pdns/stubresolver.cc
Add the same security polling mechanism than the authoritative server and the recursor already have.
I have:
=> dnsdist: Add security polling

build-scripts/build-auth-rpm
Fixed on master by #7040
I have:
=> auth 4.1 build: Switch to devtoolset 7 for el6

build-scripts/build-auth-rpm
=> auth 4.0 el6: switch to devtoolset-7

build-scripts/build-recursor-rpm
=> rec 4.0 el6: switch to devtoolset-7

build-scripts/build-recursor-rpm
=> rec 4.1 el6: switch to devtoolset-7

pdns/pdns_recursor.cc, pdns/recursordist/docs/settings.rst, pdns/validate.cc, pdns/validate.hh
=> rec: allow the signture inception to be off by a number of seconds.

.travis.yml
=> Make travis use a modern python

pdns/recursordist/README.md
As submitted in the issue #7131 the link for current documentation is outdated, this commit will update this issue 
This will close #7131 
I have:
=> Line #84 old link to doc

pdns/README-dnsdist.md
=> added the s to http to avoid redirect line 10

contrib/ProtobufLogger.py, pdns/dnsmessage.proto, pdns/lwres.cc, pdns/mtasker_ucontext.cc, pdns/opensslsigners.cc, pdns/pdns_recursor.cc, pdns/protobuf.cc, pdns/protobuf.hh, pdns/rec_channel_rec.cc, pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc, pdns/syncres.hh, pdns/ws-recursor.cc
Backported:
- #6741
- #6917
- #6925
- #6945
- #6948
- #6951
- #7004
I have:
=> Recursor 4.1.5 backports

build-scripts/build-auth-rpm
=> package missing files

regression-tests.api/requirements.txt
This cleans up a GitHub security warning.
I have:
=> api tests: update requests to 2.20.0

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.1.rst
=> Add recursor 4.1.6 changelog and secpoll

docs/secpoll.zone, pdns/dnsdist-cache.cc, pdns/dnsdist-cache.hh, pdns/dnsdist-console.cc, pdns/dnsdist-ecs.cc, pdns/dnsdist-ecs.hh, pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist-xpf.cc, pdns/dnsdist-xpf.hh, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/dnsdist-xpf.cc, pdns/dnsdistdist/dnsdist-xpf.hh, pdns/dnsdistdist/docs/advanced/ecs.rst, pdns/dnsdistdist/docs/changelog.rst, pdns/dnsdistdist/docs/security-advisories/powerdns-advisory-for-dnsdist-2018-08.rst, pdns/dnsparser.cc, pdns/test-dnsdist_cc.cc, pdns/test-dnsdistpacketcache_cc.cc, pdns/test-dnsparser_cc.cc, regression-tests.dnsdist/test_Caching.py
=> dnsdist: Add 1.3.3 ChangeLog, update the secpoll zone

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.1.rst
=> recursor 4.1.7: changelog and secpoll

pdns/dnsdistdist/docs/reference/dq.rst
cc @rgacogne
Ref ef8640ddc0fcff7c84b955f2ec2110939140ca2e
=> Correct versionadded for getEDNSOptions and EDNSOptionView

pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc
=> rec: Refuse queries for all meta-types

pdns/dnsdistdist/docs/install.rst
=> Fix some links in the dnsdist install docs

pdns/recursordist/docs/lua-config/rpz.rst
Ass seen on irc guessing the right format of how to add multiply ip's to block I've added and example to reflect the right way...
I have:
=> Added a quick example of a ip block on rpzMaster

pdns/dnsdistdist/docs/guides/cache.rst
Has tried to make this section easier to read by incorporating it into a bulleted list
I have:
=> Improve the reading of the time value section

docs/migration.rst
Added a little note about the load-zone overwrites everything inclusive the soa.... (Coz I was in doubt myself as i tested it)
I have:
=> Changed .com.com to .com on line #134

modules/geoipbackend/geoipbackend.cc, modules/geoipbackend/regression-tests/ent-resolution/command, modules/geoipbackend/regression-tests/ent-resolution/description, modules/geoipbackend/regression-tests/ent-resolution/expected_result
=> geoipbackend: Allow empty content for ENT record

regression-tests.api/runtests.py, regression-tests.api/test_helper.py, regression-tests.auth-py/authtests.py, regression-tests.dnsdist/dnsdisttests.py, regression-tests.recursor-dnssec/printlogs.py, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_Protobuf.py, regression-tests.recursor-dnssec/test_basicNSEC3.py, regression-tests/bulktest-report.py, regression-tests/bulktest-to-json.py
Fix some Python 3 incompatibilities discovered in #7202
These changes should be compatible with both Python 2 and Python 3.
=> Modernize Python 2 code to get ready for Python 3

lgtm.yml, regression-tests.api/runtests.py, regression-tests.api/test_helper.py, regression-tests.auth-py/authtests.py, regression-tests.dnsdist/dnsdisttests.py, regression-tests.recursor-dnssec/printlogs.py, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_Protobuf.py, regression-tests.recursor-dnssec/test_basicNSEC3.py, regression-tests/bulktest-report.py, regression-tests/bulktest-to-json.py
Blocked by #7204
Force LGTM to test on Python 3 instead of Python 2
I have:
The _undefined names_ that I do not know how to fix are in #7204
=> Force LGTM to test on Python 3 instead of Python 2

build-scripts/travis.sh
This switches us back to official jdnssec-tools releases, now hosted on GitHub.
I have:
=> upgrade to jdnssec-tools 0.14

build-scripts/travis.sh
(cherry picked from commit 20445e6958184a6ca1e1eb7339434f6e77a8bb45)
I have:
=> auth 4.0.x: upgrade to jdnssec-tools 0.14

modules/geoipbackend/geoipinterface-dat.cc
This PR wraps libGeoIP return values in `unique_ptr` to make sure they are properly deleted.
This should fix #7184 
I have:
=> auth: geoip, properly delete libGeoIP return values

pdns/dnsdist-console.cc, pdns/dnsdist.hh
Only the console code uses them nowadays, so no need to export them.
I have:
=> dnsdist: Make getMsgLen32 and putMsgLen32 static

pdns/recursordist/test-syncres_cc.cc
Otherwise we get random test failures when the RRSIG is generated after the number of seconds since epoch increased.
Backport of #7235 for rel/rec-4.1.x. 
(cherry picked from commit 1e2e06f1fd4a29702eaa297456dca72714ac1fe0)
I have:
=> rec-4.1.x: Use the SyncRes time when computing the RRSIG validity time

modules/bindbackend/bindbackend2.cc, pdns/version.cc
Update features in auth/recursor --version output.
Also re-sort the list so that the outputted values are sorted alphabetically.
I have:
=> Update and re-sort feature list in --version output

README.md
=> README.md: fix typo in macOS instructions

pdns/pdns_recursor.cc
=> recursor: Fix typo in help text of signature-inception-skew option

pdns/version.cc
=> Add missing insertion operators for libcrypto's features

build-scripts/travis.sh
This fixes the auth builds in Travis.
I have:
=> Update rubygems in travis

regression-tests.recursor-dnssec/test_RootNXTrust.py
=> rec: Add some basic regression tests for the root-nx-trust feature

regression-tests.recursor-dnssec/test_Lua.py, regression-tests.recursor-dnssec/test_RPZ.py
=> rec: Add basic regression tests for most of the Lua hooks

pdns/pdns_recursor.cc, pdns/pubsuffix.hh, pdns/rec_channel.hh, pdns/rec_channel_rec.cc, pdns/recursordist/Makefile.am, pdns/recursordist/docs/settings.rst, pdns/recursordist/pubsuffixloader.cc
=> rec: Add support for loading the Public Suffix List from a file

pdns/pdns_recursor.cc, pdns/rec-snmp.cc, pdns/rec_channel_rec.cc, pdns/recursordist/RECURSOR-MIB.txt, pdns/recursordist/docs/metrics.rst, pdns/syncres.hh
=> rec: Add counters for incoming AD and CD queries

modules/opendbxbackend/odbxbackend.cc, pdns/dnsparser.cc, pdns/misc.cc, pdns/rcpgenerator.cc, pdns/sillyrecords.cc, pdns/zoneparser-tng.cc
=> Fix a few off-by-one errors

builder-support/post-build
Stolen from https://github.com/PowerDNS/pdns-builder/blob/master/helpers/build-rocks.sh#L44
Tested on macOS but not on any Linux.
I have:
=> try really hard to use gnu tar

regression-tests.dnsdist/dnscrypt.py, regression-tests.dnsdist/requirements.txt
Could use a review and some advice from a Python expert ;-)
I have:
=> dnsdist: Update DNSCrypt's regression tests for Python 3

build-scripts/travis.sh
Backport of #7312 to rel/auth-4.0.x.
(cherry picked from commit 2a5c0b379f0bc256cb92920e3be56139f5bcdc29)
I have:
=> auth-4.0.x: Update rubygems in travis (for bundler)

build-scripts/travis.sh
Backport of #7312 to rel/auth-4.1.x.
(cherry picked from commit 2a5c0b379f0bc256cb92920e3be56139f5bcdc29)
I have:
=> auth-4.1.x: Update rubygems in travis (for bundler)

pdns/recursordist/test-syncres_cc.cc
=> rec: Fix a possible timing issue w/ RRSIGs in the SyncRes unit tests

pdns/dnsdistdist/docs/reference/config.rst
Closes #7188.
Closes #7189.
I have:
=> dnsdist: Remove rmPool() from the doc and add showPools() to it

docs/guides/kskroll.rst
=> Tweaks to the rollover docs: make a few things explicit.

docs/manpages/pdns_notify.1.rst, pdns/notify.cc, regression-tests.nobackend/supermaster-signed/expected_result
=> pdns_notify: Support hostname for notification

README.md, docs/conf.py, pdns/dnsdistdist/docs/conf.py, pdns/minicurl.cc, pdns/minicurl.hh, pdns/recursordist/README.md, pdns/recursordist/docs/conf.py, pdns/version.cc, pdns/ws-auth.cc
Update copyright years :)
I have:
=> Hello 2019!

pdns/recursordist/docs/lua-config/rpz.rst
As I found my own "old" description of the multiply ip array in rpzMaster rather unfriendly and less descriptive I'm trying to make this easier to read and adding a more descriptive text.
Coal: make it more descriptive, understandable and avoid language misunderstanding.
Please comment and give suggestion for optimization 
/Spirillen
I have:
=> Optimizing and more descriptive rpzMaster ip array

regression-tests.recursor-dnssec/test_ECS.py
=> rec: Fix an invalid use if cls._PREFIX in the ECS regression tests

pdns/dnsdist-lua.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Add an optional 'checkTimeout' parameter to 'newServer()'

pdns/filterpo.cc
=> rec: Appease the Gods of spell checking

pdns/dnscrypt.hh, pdns/dnsdist.cc
=> dnsdist: Fix compilation without DNSCrypt support enabled

docs/settings.rst
This should hopefully fix the current master (and all PRs based on it) from being broken in Travis CI.
I have:
=> auth: Fix 'minumum' typo in the docs

builder-support/gen-version
=> Make version correct on shallow copies

pdns/dns_random.cc
`min` is the "minimum acceptable value for random number", used to improve uniformity, but it might be 0 for some values of the requested `upper_bound`, and in that case the current code always returns 0 with most `RNG`s.
I have:
=> Fix dns_random() always returning 0 when the minimum acceptable value is 0

pdns/sdig.cc
This avoids garbage output for non-IN class records in responses.
I have:
=> sdig: handle non-IN class records better

pdns/pdns_recursor.cc
When the recursor is configured to distribute incoming queries to its worker threads itself, and in the unlikely case that the pipe to the selected thread is full, randomly select another worker to handle the query. If this one fails too, we give up.
Same PR than #7383 but for rel/rec-4.1.x.
I have:
=> rec-4.1.x: Try another worker before failing if the first pipe was full

pdns/dnsdistdist/docs/reference/config.rst
Introduced in c1b8138133.
I have:
=> dnsdist: Fix 'collisons' typo in the docs

build-scripts/jsoref-spellchecker/whitelist.words, pdns/dnsdistdist/docs/reference/config.rst
Trivial spelling fix and spellcheck whitelist update.
I have:
=> Spellcheck fixes

pdns/pdns_recursor.cc, pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc, pdns/syncres.hh, regression-tests.recursor-dnssec/cookiesoption.py, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_Lua.py
=> rec-4.1.x: Load the Lua script in the distributor thread, check signature for AA=0 answers

build-scripts/jsoref-spellchecker/whitelist.words, docs/secpoll.zone, pdns/recursordist/docs/changelog/4.1.rst, pdns/recursordist/docs/security-advisories/powerdns-advisory-2019-01.rst, pdns/recursordist/docs/security-advisories/powerdns-advisory-2019-02.rst
=> rec: Add ChangeLog and secpoll update for the 4.1.9 release

build-scripts/jsoref-spellchecker/whitelist.words, pdns/bpf-filter.cc, pdns/dnsdist-ecs.cc, pdns/dnsdist-lua-bindings.cc, pdns/dnspacket.cc, pdns/dnspacket.hh, pdns/dnsrecords.cc, pdns/dnsscope.cc, pdns/dynlistener.cc, pdns/dynlistener.hh, pdns/notify.cc, pdns/ssqlite3.cc, pdns/ssqlite3.hh, pdns/ws-auth.cc, pdns/ws-auth.hh
=> Fix -Wextra warnings, mostly about members initialization order

docs/backends/generic-oracle.rst, docs/backends/oracle.rst
If you use Oracle, either become a customer or you are on your own.
=> note in docs that oracle gets no free support

build-scripts/jsoref-spellchecker/whitelist.words, pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc, pdns/syncres.hh
Stricter version of https://github.com/PowerDNS/pdns/pull/7258
I have:
=> rec: Sanitize records received before doing anything else

pdns/recursordist/test-syncres_cc.cc
On Debians mipsel builders this has caused test failures a number of
times in a row, so this is not just a possible issue.
Ref #7327
I have:
=> Backport #7327: rec: Fix a possible timing issue w/ RRSIGs in the SyncRes unit tests

pdns/Makefile.am, pdns/dnsdistdist/Makefile.am, pdns/recursordist/Makefile.am
Since the `-i` option of `sed` is not really portable.
I have:
=> Use perl instead of sed to conditionally remove lines from Makefiles

ext/yahttp/README.md, ext/yahttp/yahttp/exception.hpp, ext/yahttp/yahttp/reqresp.cpp, ext/yahttp/yahttp/router.hpp, ext/yahttp/yahttp/url.hpp, ext/yahttp/yahttp/utility.hpp
Import upstream fixes incl. (Set-)Cookie bugfix mentioned on mailing list, which got fixed by @rgacogne upstream.
I have:
=> Resync yahttp code to cmouse/yahttp@11be77a1fc4032

modules/ldapbackend/powerldap.cc, pdns/bindlexer.l, pdns/communicator.hh, pdns/misc.cc
Low hanging fruit of https://github.com/PowerDNS/pdns/issues/3006. The random() stuff is more involved and part of another PR. You might find that some bounds cannot really be hit.
But its a matter of principle to not allow unbounded writes.
I have:
=> sprintf, strcpy and const method case

modules/bindbackend/bindbackend2.cc, modules/bindbackend/bindbackend2.hh, modules/lmdbbackend/lmdbbackend.cc, modules/lmdbbackend/lmdbbackend.hh, modules/luabackend/luabackend.hh, modules/luabackend/slave.cc, modules/opendbxbackend/odbxbackend.cc, modules/opendbxbackend/odbxbackend.hh, modules/remotebackend/remotebackend.cc, modules/remotebackend/remotebackend.hh, pdns/backends/gsql/gsqlbackend.cc, pdns/backends/gsql/gsqlbackend.hh, pdns/dnsbackend.hh, pdns/slavecommunicator.cc
This commit was missing in #7453
I have:
=> auth: lmdb-backend avoid duplicate NSEC3 records in presigned zones

pdns/dnswriter.cc
=> Do not compress the root

modules/mydnsbackend/mydnsbackend.cc
A while loop with a constant condition is not a good idea in general.
Fixes https://github.com/PowerDNS/pdns/issues/7474
I have:
=> Avoid infinite loop in mydnsbackend.

pdns/dnsrecords.cc
fixes: #7429 
to be checked for the Pull Request to be accepted -->
I have:
=> auth: fix dot stripping in setContent()

pdns/json.cc, regression-tests.api/test_Zones.py
=> API: improve handling of out of range modified_at value

pdns/dnsdist.cc, pdns/dnssecinfra.cc, pdns/misc.cc, pdns/pdns_recursor.cc, pdns/rec_channel_rec.cc, pdns/recpacketcache.cc, pdns/recpacketcache.hh, pdns/recursor_cache.cc, pdns/reczones.cc, pdns/rpzloader.cc, pdns/syncres.cc, pdns/test-dnsdist_cc.cc, pdns/test-recpacketcache_cc.cc
=> Fix some warning reported by Clang's static analyzer

docs/lua-records/reference/misc.rst, pdns/lua-base4.cc, pdns/recursordist/docs/lua-scripting/functions.rst, regression-tests.recursor-dnssec/test_Lua.py
Fixes the usecase in #6853
I have:
=> Lua: expose `dns_random` as `pdnsrandom`

pdns/speedtest.cc
=> auth: Fix compilation of speedtest with GCC 8.0+

pdns/dnsdistdist/docs/rules-actions.rst
Minor capitalization cleanup in the documentation (`s/allRule/AllRule/`)
I have:
=> Minor capitalization cleanup

docs/backends/remote.rst, modules/remotebackend/remotebackend.cc, modules/remotebackend/remotebackend.hh, modules/remotebackend/test-remotebackend.cc, modules/remotebackend/unittest.rb
=> remotebackend: Implement getUpdatedMasters

pdns/backends/gsql/gsqlbackend.cc
**Added a bunch of reviewers so it can get into auth-4.2.0-beta1, but needs just one approval.**
Fixes #7493.
I have:
=> auth: Catch exception when parsing a zone's SOA in getUnfreshSlaveInfos()

pdns/dnstap.cc
=> Don't convert nsec to usec if we need nsec

pdns/recursordist/docs/settings.rst
=> aaaa-additional-processing does not exist anymore

pdns/dnsdistdist/docs/reference/config.rst
Non-content improvements to dnsdist docs.
I have:
=> dnsdist docs: fix formatting and one typo

pdns/backends/gsql/gsqlbackend.cc
=> gsqlbackend: Reset correct query in searchComments

pdns/dnsdist.hh
Fixes #7563 .Introduced in https://github.com/PowerDNS/pdns/pull/7406.
I have:
=> dnsdist: Properly initialize DNQuestion::ednsRCode

modules/remotebackend/httpconnector.cc, modules/remotebackend/remotebackend.hh
Backport of #7576 to rel/auth-4.0.x.
I have:
=> auth-4.0.x: remotebackend: http connector - Properly escape parameters

modules/remotebackend/httpconnector.cc, modules/remotebackend/remotebackend.hh
Backport of https://github.com/PowerDNS/pdns/pull/7576 to rel/auth-4.1.x.
I have:
=> auth-4.1.x: remotebackend: http connector - Properly escape parameters

pdns/dnsdist-lua-rules.cc, regression-tests.dnsdist/test_Advanced.py
=> dnsdist: Fix setRules()

build-scripts/build-auth-rpm
This was accidentally removed earlier
I have:
=> EL6: fix CXXFLAGS to build with compiler optimizations

pdns/backends/gsql/gsqlbackend.cc
This could help zooming into the source of the error.
I have:
=> GSQL: Log more data in error messages

.circleci/config.yml, build-scripts/circleci.sh
Comments welcome on making this cleaner so that future work on it is easier. We can make it more complete after merge. For now I'd like this to exist next to Travis, so we have MSSQL testing again, and so that we can gather some day-to-day experience with CircleCI.
I have:
=> set up circleCI testing for auth+godbc+mssql

pdns/distributor.hh
Hopefully fixes #7398.
I have:
=> auth: Ensure we increase the number of queued queries before decreasing it

pdns/ws-auth.cc
Alternative fix for #7407.
I have:
=> auth: Clear caches (meta-data, keys) on domain deletion

docs/backends/generic-mysql.rst, modules/gmysqlbackend/gmysqlbackend.cc, modules/gmysqlbackend/smysql.cc, modules/gmysqlbackend/smysql.hh
This is a forward-port of https://github.com/PowerDNS/pdns/pull/7509 to master.
Plus docs.
I have:
=> plug mysql_thread_init memory leak

.circleci/config.yml, build-scripts/circleci.sh
(cherry picked from commit fbd89850013536ecad8da2368d136f092d355388)
Backport CircleCi ODBC testing to auth 4.1.x.
I have:
=> auth-4.1.x: set up circleCI testing for auth+godbc+mssql

docs/backends/generic-postgresql.rst
=> typo in docs

pdns/pdns_recursor.cc, pdns/rec_channel_rec.cc, pdns/recursordist/docs/manpages/rec_control.1.rst, pdns/recursordist/docs/settings.rst, pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc, pdns/syncres.hh
To be able to artificially raise the TTLs of records in the ANSWER section of ECS-specific answers to be at least this long.
I have:
=> rec: Add a new ecs-minimum-ttl-override setting

pdns/README-dnsdist.md
Because we need libssl these days.
I have:
=> dnsdist README: update macOS instructions

pdns/dnsdistdist/html/local.js
=> dnsdist: Gracefully handle a null latency in the webserver's JS

pdns/recursordist/docs/settings.rst
=> Fix versionadded line

builder-support/dockerfiles/Dockerfile.rpmbuild
This unbreaks our el7 and amazon-linux:2 builds.
https://www.mail-archive.com/epel-devel@lists.fedoraproject.org/msg06502.html
dnsdist test build running at https://builder.powerdns.com/#/builders/98/builds/698
I have:
=> centos builds: ask for any python3

docs/dnssec/modes-of-operation.rst
=> dnssec clarifications

pdns/dnsdistdist/tcpiohandler.cc
=> dnsdist: Add missing overrides

pdns/dnsdistdist/Makefile.am
Needed for macOS compliation after #7481 
I have:
=> dnsdist: honor libcrypto include path

pdns/pdns_recursor.cc, pdns/rec_channel_rec.cc, pdns/recursordist/docs/metrics.rst, pdns/syncres.hh
#7647 but for master.
(cherry picked from commit 4ae78615a5a0fb0721ebe1a58a1235e75c47d400)
I have:
=> rec: This provides CPU usage statistics per thread (worker & distributor).

.circleci/config.yml, build-scripts/circleci.sh
(cherry picked from commit fbd89850013536ecad8da2368d136f092d355388)
Backport CircleCi ODBC testing to auth 4.0.x.
I have:
=> auth-4.0.x: set up circleCI testing for auth+godbc+mssql

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc, pdns/dnsdist.cc, pdns/dnsdistdist/docs/reference/config.rst, pdns/dolog.hh
=> dnsdist: Add 'setSyslogFacility()'

pdns/iputils.cc, pdns/pollmplexer.cc, pdns/tcpreceiver.cc, regression-tests.dnsdist/test_TCPLimits.py
With these three changes, dnsdist passes all tests on macOS again.
TODO: 
I have:
=> dnsdist: collected portability fixes

modules/lmdbbackend/lmdbbackend.cc, regression-tests/backends/lmdb-slave
Zones without records did not show up in the output of /api/v1/servers/localhost/zones api
Serial was not set for zones with records.
I have:
=> auth: lmdbbackend, fix getAllDomains()

pdns/dnsdist-lua-actions.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/iputils.hh, pdns/misc.cc, pdns/test-dnsdist_cc.cc, regression-tests.dnsdist/test_Protobuf.py
=> dnsdist: Fix small issues reported by cppcheck and clang's static analyzer

pdns/dnsdist-lua.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/docs/guides/serverselection.rst, regression-tests.dnsdist/test_Routing.py
=> dnsdist: Add 'setRoundRobinFailOnNoServer()'

regression-tests.dnsdist/runtests
Make sure we don't have old cert chain remains. Also cleanup configs dir before run.
Now without extra ballast.
I have:
- [X ] added or modified regression test(s)
=> Dnsdist runtests cleanup

pdns/recursordist/README.md
It's an old leftover from when Rec and Auth shared their makefiles.
I have:
=> remove --with-modules from recursor README

pdns/dnsdistdist/docs/guides/cache.rst
=> dnsdist: Update the syntax of newPacketCache() in the caching guide

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst, pdns/dnsdistdist/docs/upgrade_guide.rst
=> dnsdist: Prepare secpoll, changelog and upgrade guide for 1.4.0a1

docs/guides/basic-database.rst
Small typo in the basic DB guide.
I have:
=> Fix typo in basic-database guide

pdns/dnsdistdist/doh.cc
Reported by @paddg in https://github.com/PowerDNS/pdns/issues/6405#issuecomment-432163016 (thanks!).
I have:
=> dnsdist: Fix destination matching with DoH

pdns/dnsdistdist/docs/advanced/acl.rst, pdns/dnsdistdist/docs/reference/config.rst
Fixes https://github.com/PowerDNS/pdns/issues/7725.
I have:
=> dnsdist: Fix doc for checkInterval, setECSOverride and the ACL

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Prepare secpoll and ChangeLog updates for 1.4.0-alpha2

pdns/dnsdistdist/docs/reference/constants.rst, pdns/dnsdistdist/docs/reference/index.rst
=> dnsdist: Include dnsnameset.rst in the reference index

docs/guides/basic-database.rst
Make a somewhat useless answer a bit less useless.
I have:
=> Make guide more clear

docs/modes-of-operation.rst, docs/settings.rst, docs/upgrading.rst, pdns/common_startup.cc, pdns/packethandler.cc, regression-tests.nobackend/supermaster-signed/command, regression-tests.nobackend/supermaster-unsigned/command
The old name was very confusing. Fixes #7720.
I have:
=> rename supermaster to superslave, and mention in upgrade notes

pdns/recursordist/docs/http-api/endpoint-jsonstat.rst, pdns/recursordist/docs/http-api/index.rst
This was missing from recursor.
I have:
=> rec: start to document the jsonstat

docs/manpages/dumresp.1.rst, pdns/dumresp.cc
=> dumresp: Add TCP support

docs/manpages/pdnsutil.1.rst
=> Add export-zone-ds to pdnsutil man page

pdns/packethandler.cc
=> auth: always add DS for secure zones, broken since #7523

pdns/dnsdistdist/docs/quickstart.rst
=> dnsdist: Change addLocal example to IPv6 address in quickstart

pdns/dnsdistdist/docs/reference/carbon.rst
Adds missing parameter documentation for carbonServer()
=> [dnsdist] Doc fix of carbonServer

.circleci/config.yml
=> fix PR checkout in circle-ci testing

pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Document the SuffixMatchNode class, newSuffixMatchNode()

pdns/ws-auth.cc, regression-tests.api/test_Zones.py
=> auth: Fix ENTs removal when "replacing" new records via the API

regression-tests.dnsdist/test_DOH.py
Mostly to test POST queries which were not covered until now.
I have:
=> dnsdist: Add a few more DoH tests

pdns/pdnsutil.cc
=> show DS for second and further keys too; fixes #7667

pdns/dnsseckeeper.hh, pdns/packethandler.cc, pdns/packethandler.hh, pdns/serialtweaker.cc, pdns/tcpreceiver.cc, regression-tests.nobackend/soa-edit/command, regression-tests.nobackend/soa-edit/expected_result
=> Cleanup SOA editing

pdns/recursordist/docs/nod_udr.rst, pdns/recursordist/docs/security.rst
=> Documentation for the NOD and UDR features

pdns/dnsdist-console.cc, pdns/dnsdistdist/docs/rules-actions.rst, regression-tests.dnsdist/test_DOH.py
=> dnsdist: Add documentation, completion and tests for our DoH HTTP rules

docs/backends/generic-mysql.rst
We know MySQL views can cause problems for PowerDNS. Let's tell people about this & how we'll require reproduction w/o views for open source support.
I have:
=> add warning about MySQL views

pdns/rfc2136handler.cc, pdns/ws-auth.cc, regression-tests/tests/1dyndns-cname-and-other-data/command, regression-tests/tests/1dyndns-cname-and-other-data/expected_result
=>  auth: Allow updates to override existing ENT records

docs/settings.rst
Otherwise user can get confused
I have:
=> Mention that udp-truncation-threshold changed in 4.2.0

.circleci/config.yml
This only tests if it compiles.
@neilcook we might need to add some tests this :).
I have:
=> rec: Enable NOD in circle-ci

pdns/qtype.hh, pdns/syncres.cc
Makes the code much more readable.
I have:
=> Eliminate the loop in SyncRes::getAddrs()

pdns/backends/gsql/gsqlbackend.cc
Fixes #4450
Fixes #4475
I have:
=> auth gsql getAllDomains: ignore stou errors

regression-tests/README.md
=> auth: document how to get mysql or postgres from docker

pdns/syncres.cc
=> Backport 7841: recursor: log UDP TC bits during trace 

pdns/communicator.cc
https://github.com/PowerDNS/pdns/pull/7790
I have:
=> auth backport 7790 to 4.1.x: Minimal fix to avoid busy looping on lots of notifies.

modules/bindbackend/bindbackend2.cc, modules/bindbackend/bindbackend2.hh, modules/ldapbackend/native.cc, modules/lmdbbackend/lmdb-safe.hh, modules/lmdbbackend/lmdbbackend.cc, pdns/dns_random.cc, pdns/dnsbulktest.cc, pdns/dnspacket.hh, pdns/dnspcap.cc, pdns/dnstcpbench.cc, pdns/dumresp.cc, pdns/dynlistener.cc, pdns/ixfrutils.cc, pdns/nsec3dig.cc, pdns/nsecrecords.cc, pdns/pdnsutil.cc, pdns/saxfr.cc, pdns/sdig.cc, pdns/toysdig.cc
Nothing too serious, and some changes are even just there to make the code more readable. We might want to backport most of these changes to 4.2.x (auth and rec).
I have:
=> Fix warnings reported by Coverity

pdns/stubquery.cc
Currently: 
```
[otto@x1:3]$ stubquery www.google.com
Segmentation fault (core dumped) 
```
I have:
=> stubquery: Fix handling of optional type arg.

docs/dnssec/profile.rst
=> profile.rst: Remove GOST

configure.ac, m4/pdns_check_libcurl.m4, m4/pdns_enable_tools.m4, m4/pdns_with_lua_records.m4, pdns/Makefile.am, pdns/minicurl.cc, pdns/minicurl.hh, pdns/sdig.cc
This will need some autotooling help - I'm pretty sure building sdig without LUA records is now illegal, which is not exactly what we want.
This ignores the port number argument - should that argument be removed altogether in DoH mode?
I have:
=> add DoH support to sdig

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Prepare ChangeLog and secpoll for 1.4.0-beta1

m4/boost.m4
=> Update boost.m4 to the latest version

pdns/ueberbackend.cc
This pull should provide the evidence who is to blame for #6208 
I have:
=> auth: detect SOA cache pollution caused by broken backends

.circleci/config.yml
apparently 'Community Technology Preview' images expire, so
this switches us to a Generally Available version.
I have:
=> auth: switch circleci mssql image

pdns/dynhandler.cc, pdns/receiver.cc, pdns/statbag.cc, pdns/statbag.hh
Not configurable but that could easily be added if necessary in the future.
`DLShowHandler` was a bit strange imo, no braces? Fixed that as well.
I have:
=> Simple blacklist handler for StatBag

pdns/dnsdistdist/.gitignore
Git would be dirty after building dnsdist
I have:
=> Ignore generated files for ipcrypt

.circleci/config.yml
Context has already been created.
I have:
=> Use circle-ci context to get doc host FP

.circleci/config.yml
The other image, apparently, was temporary.
I have:
=> backport #7899: switch circleci mssql image

pdns/recursordist/docs/changelog/4.1.rst
=> Changlelog entry for rec-4.1.14

pdns/recursordist/test-syncres_cc9.cc
We used to set time returned by `sr->getNow()` via `gettimeofday()` and later the one used to compute the RRSIG validity via `time(nullptr)`. It turns out that the second call can return a value lesser than the first one, without the time going backward, making our tests fail.
After this commit we base our calculations on the same time value, so it should not fail randomly anymore.
Yes another occurrence of #6160 and #7235, but hopefully the last remaining one.
Supersedes #7883.
I have:
=> rec: Don't mix time() and gettimeofday() in our unit tests (again)

docs/changelog/4.2.rst, docs/secpoll.zone
Copy and fixes to #7907 (since I can't push to that branch and Peter isn't available at the moment).
=> Changelog and secpoll for auth-4.2.0-rc2 release.

pdns/dnsdistdist/docs/reference/config.rst
leastOustanding -> leastOutstanding
I have:
=> dnsdist doc typo fix

build-scripts/cherry-pick-pr.py
Typical name will be: backport-7905-to-rec-4.2.x
I have:
=> Append the basename of the target branch to the name of the created branch

docs/modes-of-operation.rst, docs/settings.rst, pdns/common_startup.cc, pdns/packethandler.cc, regression-tests.nobackend/supermaster-signed/command, regression-tests.nobackend/supermaster-unsigned/command
=> backport superslave setting to 4.1.x, but default to yes

pdns/pdns_recursor.cc, pdns/recursordist/docs/settings.rst, pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc.hh, pdns/recursordist/test-syncres_cc1.cc, pdns/recursordist/test-syncres_cc3.cc, pdns/syncres.cc, pdns/syncres.hh
Only tested in a local environment.
It implements a relaxed form of qname minimization, based on A queries with fallback to the full name if something goes wrong.
Enable with config option qname-minimization=yes (default no)
I have:
=> Rec experimental qname minimization

pdns/dnsname.hh, pdns/test-dnsname_cc.cc
=> rec backport  to rec 4.2.x: SuffixMatchRee fixes

pdns/dns_random.cc
Reported by Coverity (CID 1401626).
(cherry picked from commit 144c9852279ef0219c72fe549f72a40f3a255edc)
I have:
=> rec: backport to 4.2.x: Handle short reads from our random device

builder-support/debian/authoritative/debian-buster/pdns-backend-sqlite3.dirs, builder-support/debian/authoritative/debian-buster/pdns-server.dirs, builder-support/debian/authoritative/debian-buster/pdns-server.postinst, builder-support/debian/authoritative/debian-jessie/pdns-backend-sqlite3.dirs, builder-support/debian/authoritative/debian-jessie/pdns-server.dirs, builder-support/debian/authoritative/debian-jessie/pdns-server.postinst, builder-support/debian/authoritative/debian-stretch/pdns-backend-sqlite3.dirs, builder-support/debian/authoritative/debian-stretch/pdns-server.dirs, builder-support/debian/authoritative/debian-stretch/pdns-server.postinst, builder-support/debian/authoritative/ubuntu-trusty/pdns-backend-sqlite3.dirs, builder-support/debian/authoritative/ubuntu-trusty/pdns-server.dirs, builder-support/debian/authoritative/ubuntu-trusty/pdns-server.postinst
And ensure it owned by de pdns user.
Fixes #7888 for our own packages, tested on ubuntu bionic
cc: @zeha 
I have:
=> auth: move /var/lib/pdns to pdns-server debian package

configure.ac, pdns/version.cc
=> Show newer features in configure output and --version

pdns/dnsdistdist/tcpiohandler.cc
Log a bit more information in our error messages when a DoT issue occurs.
I have:
=> dnsdist: Improve error messages for DoT issues

docs/common/api/zone.rst, pdns/recursordist/docs/settings.rst
=> Fix a few markup issues in our documentation

pdns/lua-record.cc
=> removed unused variables in lua-record.cc

pdns/dnsdist-lua.cc
=> dnsdist: Skip non-DNSCrypt binds in `showDNSCryptBinds()`

.circleci/config.yml, .travis.yml
=> travis, circleci: only do recursor testing

pdns/dnsname.cc
Otherwise PRIu8 is undefined.
I have:
=> dnsname: unbreak el6 build by explicitly including <cinttypes>

pdns/dnsdist-lua.cc
=> dnsdist: Be a bit more explicit about what failed in testCrypto()

docs/secpoll.zone
This box is physical and can absorb attacks
I have:
=> Add tmpdns.powerdns.com to secpoll NSSet

pdns/recursordist/test-syncres_cc5.cc
Fix borrowed from #8008.
But this test also does `addRRSIG()` calls, these need adaptation as well.
See https://builder.powerdns.com/#/builders/114/builds/301
I have:
- [] added or modified regression test(s)
=> Another time sensistive test fixed with a fixedNow construct.

.circleci/config.yml
=> Add -Werror=format-security and -D_GLIBCXX_ASSERTIONS on CircleCI

docs/http-api/index.rst
Fixes typo in documentation of the api server for auth
I have:
=> Auth-documentation: Fix typo

.circleci/config.yml, regression-tests.ixfrdist/test_Stats.py
Manual backport of #8049 
I have:
=> auth 4.2.x: ixfrdist: test in CircleCI; remove useless error

pdns/distributor.hh, pdns/test-distributor_hh.cc
=> auth 4.2.x: Fix the accounting of servfail-queries in the distributor

pdns/Makefile.am, pdns/dnswriter.cc, pdns/dnswriter.hh, pdns/test-dnswriter_cc.cc
=> Backport 8028 to rec 4.2.x: limit compression pointers to 14 bits 

lgtm.yml
This should save a lot of time.
I have:
=> only LGTM auth on this branch

builder-support/dockerfiles/Dockerfile.target.raspbian-buster
Packages come out on my system!
I have:
=> builder: add raspbian-buster target

pdns/dnscrypt.cc, pdns/dnscrypt.hh, pdns/dnsdist-lua-bindings.cc, pdns/dnsdist-lua.cc, pdns/dnsdistdist/docs/reference/dnscrypt.rst
=> dnsdist: Accept more than one certificate in `addDNSCryptBind()`

docs/secpoll.zone, pdns/recursordist/docs/appendices/EOL.rst, pdns/recursordist/docs/changelog/4.2.rst
Plus a typo in the rc2 changelog.
I have:
=> Changelog and secpoll for upcoming rec-4.2.0 release

lgtm.yml
=> enable a bunch of extra features during LGTM builds

regression-tests.dnsdist/dnsdisttests.py
=> dnsdist: Fix local variable 'wire' referenced before assignment

pdns/pdnsutil.cc
(cherry picked from commit 85cc3e43d48ac08e23402c46938d3ee92cef3bca)
Backport of #8053 
I have:
=> pdnsutil: remove unused humanTime function

docs/conf.py, docs/manpages/nproxy.1.rst
=> add whatis description to nproxy man page

docs/lua-records/index.rst, docs/settings.rst
I enthousiastically merged #7869 without docs. This PR rectifies that situation.
I have:
=> LUA record documentation (version number, shared model)

pdns/dnsdist-lua-inspection.cc, pdns/dnsdistdist/doh.cc
Lintian found some spelling errors in current betas.
I have:
=> Fix some spelling errors found by lintian

pdns/dnsdistdist/doh.cc
In the quite unlikely case where sending a DoH query toward the backend over the UDP socket failed, we could have left a dangling pointer to the `DOHUnit` struct, possibly leading to a crash when the `IDState` was cleaned up later.
I have:
=> dnsdist: Prevent a dangling DOHUnit pointer when send() failed

README.md
OpenCSW appears dead, lets not suggest it's a good idea.
I have:
=> README: remove OpenCSW advice

docs/performance.rst, pdns/common_startup.cc, pdns/tcpreceiver.cc, pdns/tcpreceiver.hh, regression-tests.nobackend/counters/expected_result
A user spotted that this was missing, while it would be very useful to debug high load situations.
I have:
=> auth: add metric for open TCP connections

modules/bindbackend/bindbackend2.cc, modules/lmdbbackend/lmdbbackend.cc, pdns/communicator.cc, pdns/communicator.hh, pdns/dynhandler.cc, pdns/mastercommunicator.cc, pdns/pdnsutil.cc, pdns/rfc2136handler.cc, pdns/slavecommunicator.cc, pdns/ws-auth.cc
=> Auth: backport #8050

modules/gpgsqlbackend/4.1.0_to_4.2.0_schema.pgsql.sql, modules/gpgsqlbackend/schema.pgsql.sql, pdns/pdnsutil.cc
Backport of #8097, minus the doc commit.
I have:
=> auth 4.2: use BIGINT for notified_serial in pg schema

docs/backends/geoip.rst
it appears this is called, or at least a.k.a., the YAML backend, so let's say that.
Also fixes some typos and formatting I noticed This page could use a lot of extra comprehension love, IMO.
I have:
=> YAML backend

docs/performance.rst, pdns/common_startup.cc, pdns/tcpreceiver.cc, pdns/tcpreceiver.hh, regression-tests.nobackend/counters/expected_result
(cherry picked from commit d322f9312dda0603b0c3bddaa4e2e124990f524e)
Backport of #8125 
I have:
=> backport: auth: add metric for open TCP connections

ext/ipcrypt/Makefile.am
=> ext/ipcrypt: Ship LICENSE in tarballs

docs/security-advisories/powerdns-advisory-2019-06.rst
=> advisory 2019-06

modules/gpgsqlbackend/4.1.10_to_4.1.11.schema.pgsql.sql, modules/gpgsqlbackend/schema.pgsql.sql
Partial backport of #8097, adjusted for version numbers.
I have:
=> auth 4.1.x: adjust gpgsql schema for advisory 2019-06

docs/changelog/4.0.rst, docs/changelog/4.1.rst, docs/secpoll.zone
I've decided to keep the previous versions at `1 OK` because upgrading the software does not actually fix the problem.
I have:
=> auth: changelogs and secpoll for 4.0.9, 4.1.11

modules/gpgsqlbackend/4.0.8_to_4.0.9.schema.pgsql.sql, modules/gpgsqlbackend/schema.pgsql.sql
Partial backport of #8097, adjusted for version numbers.
I have:
=> auth 4.0.x: adjust gpgsql schema for advisory 2019-06

modules/pipebackend/coprocess.cc, modules/remotebackend/pipeconnector.cc
pipebackend and remotebackend use select() to wait on a single FD. In big setups, these FDs can be >1023, which crashes select().
I have:
=> auth: stop using select() in places where FDs can be >1023

pdns/dnsdist-lua.cc, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/doh.cc, pdns/doh.hh, regression-tests.dnsdist/test_DOH.py
This is a rebased and squashed version of #7957, plus a fix for the regression tests failure.
Closes #7900.
I have:
=> dnsdist: Add support for custom DoH headers

pdns/recursordist/docs/lua-scripting/hooks.rst, pdns/recursordist/docs/settings.rst
I suspect we planned to backport this, but we never did.
I have:
=> rec docs: fix versionadded for maintenance()

pdns/recursordist/docs/settings.rst
=> rec: Document that the special-memory-usage stat is excluded by default

modules/lmdbbackend/lmdbbackend.cc
Because of #8012, and no doubt other reasons that will pop up in the future, we need to be able to change the LMDB schema. Adding a version number now will make this a lot less painful.
I have:
=> auth lmdb: add schema versioning

modules/lmdbbackend/lmdbbackend.cc
(cherry picked from commit 370ae1cd4cd8869e2ba6d6525ac2dd6da5127b78)
Backport of #8129. 
I have:
=> auth 4.2.x lmdb: add schema versioning

ext/ipcrypt/Makefile.am
(cherry picked from commit ca80aa424b89b43cbc3ce11e6f5be5a901c3e2d7)
Backport #8135 
I have:
=> auth-4.2.x: ext/ipcrypt: Ship LICENSE in tarballs

modules/pipebackend/coprocess.cc, modules/remotebackend/pipeconnector.cc
=> auth 4.2.x: stop using select() in places where FDs can be >1023

pdns/pdnsutil.cc, regression-tests/tests/pdnsutil-increase-serial/command, regression-tests/tests/pdnsutil-increase-serial/description, regression-tests/tests/pdnsutil-increase-serial/expected_result, regression-tests/tests/pdnsutil-increase-serial/skip.nodyndns
We accidentally appended (prepended) the zone name.
Reported by @sndrsmnk, thanks!
I have:
=> pdnsutil increase-serial: set right ordername

pdns/pdnsutil.cc, regression-tests/tests/pdnsutil-increase-serial/command, regression-tests/tests/pdnsutil-increase-serial/description, regression-tests/tests/pdnsutil-increase-serial/expected_result, regression-tests/tests/pdnsutil-increase-serial/skip.nodyndns
(cherry picked from commit 970badd2b07b50e6103570f0ed91a834ac40cb15)
Backport of #8164. 
I have:
=> auth 4.2.x: pdnsutil increase-serial: set right ordername

modules/gpgsqlbackend/Makefile.am
=> gpgsqlbackend: add missing schema file to Makefile

pdns/Makefile.am, pdns/circular_buffer.hh, pdns/dnsdist-rings.hh, pdns/dnsdist.hh, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/circular_buffer.hh, pdns/dnsdistdist/tcpiohandler.cc, pdns/recursordist/Makefile.am, pdns/recursordist/circular_buffer.hh, pdns/remote_logger.hh, pdns/statbag.hh, pdns/syncres.hh, pdns/ws-api.cc
=> auth-4.2.x:  Make sure we always compile with BOOST_CB_ENABLE_DEBUG set to 0

m4/boost.m4, pdns/recursordist/configure.ac
=> auth-4.2.x: update boost.m4

build-scripts/build-auth-rpm, build-scripts/debian-authoritative/pdns-backend-mysql.docs, build-scripts/debian-authoritative/pdns-backend-pgsql.docs
After #8157 broke the el6 build because of an installed but unpackaged file, I noticed we were incomplete in more ways than one.
Test build at https://builder.powerdns.com/#/builders/8/builds/3189
I have:
=> 4.1.x packages: ship all mysql/postgres/sqlite schemas

docs/changelog/4.1.rst, docs/secpoll.zone
Build running at https://builder.powerdns.com/#/builders/8/builds/3191
I have:
=> auth 4.1.13: changelog and secpoll

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
Hopefully released on Monday!
I have:
=> dnsdist: Update the ChangeLog and secpoll for 1.4.0-rc1

builder-support/dockerfiles/Dockerfile.target.raspbian-buster
(cherry picked from commit cc1a371a2422cac77a90d6a0debbcfe6cadea84a)
I have:
=> backport to rec 4.2.x: builder: add raspbian-buster target

pdns/arguments.hh
Fixes misleading documentation for the `setSwitch`  function.
I have:
=> fixes misleading documentation

pdns/dnsdistdist/docs/guides/index.rst, pdns/dnsdistdist/docs/guides/ocsp-stapling.rst, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Add an OCSP stapling guide

builder-support/dockerfiles/Dockerfile.debbuild-prepare, builder-support/dockerfiles/Dockerfile.rpmbuild
=> Update h2o to 2.2.6, fixing CVE-2019-9512, CVE-2019-9514 and CVE-2019-9515

pdns/test-mplexer.cc
Many thanks to @stbuehler for the investigation, explanation and reproducer!
I have:
=> Gracefully handle the mplexer test pipe having only room for one

regression-tests.dnsdist/test_HealthChecks.py
=> dnsdist: Remove flaky healthcheck regression test

README.md
Add informations about pdns-builder so it can be more easily found
I have:
- [not relevant] compiled this code
- [not relevant] included documentation (including possible behaviour changes)
- [not relevant] documented the code
- [not relevant] added or modified regression test(s)
- [not relevant] added or modified unit test(s)
=> Add information about pdns-builder to README.md

pdns/dnsmessage.proto, pdns/lua-recursor4.cc, pdns/lua-recursor4.hh, pdns/pdns_recursor.cc, pdns/protobuf.cc, pdns/protobuf.hh, pdns/recursordist/docs/lua-scripting/dq.rst, pdns/recursordist/docs/lua-scripting/hooks.rst, regression-tests.recursor-dnssec/test_Protobuf.py
=> Backport 8001 to rec 4.2.x

pdns/recursordist/docs/lua-scripting/statistics.rst
=> Fix stray sentence in lua statistics docs.

pdns/rec-snmp.cc
SNMP handler registration is broken.
I have:
=> Fix inverse handler registration logic for SNMP.

pdns/rec-snmp.cc
(cherry picked from commit 3fc5b5122485c8a1aa34dd27fe0135950a26a90a)
I have:
=> rec: backport Fix inverse handler registration logic for SNMP.

modules/bindbackend/bindbackend2.cc
=> auth backport: bind getAllDomains: ignore per-zone exceptions

pdns/filterpo.cc
=> Add missing inc in rpz findClientPolicy loop.

pdns/filterpo.cc
(cherry picked from commit ae001b0e368e3a80f59d1c8ba64df15a42be00ef)
I have:
=> rec: backport 8236: Add missing inc in rpz findClientPolicy loop.

docs/upgrading.rst
=> correct table name

pdns/dnsdistdist/docs/guides/ocsp-stapling.rst
=> dnsdist: Fix some syntax errors in the OCSP stapling guide

docs/appendices/EOL.rst, docs/backends/lmdb.rst, docs/changelog/4.2.rst, docs/secpoll.zone
Todo: 
Builds at https://builder.powerdns.com/#/buildrequests/119670?redirect_to_build=true https://builder.powerdns.com/#/buildrequests/119669
I have:
=> auth 4.2.0: changelog, secpoll, doc updates

builder-support/dockerfiles/Dockerfile.authoritative, builder-support/dockerfiles/Dockerfile.dnsdist, builder-support/dockerfiles/Dockerfile.recursor, builder-support/dockerfiles/Dockerfile.target.sdist, m4/boost.m4, pdns/recursordist/configure.ac
This updates boost.m4 and configure.ac for boost::context detection
I have:
=> Backport #7951 to rec 4.2.x

m4/boost.m4, pdns/recursordist/configure.ac
This updates boost.m4 and configure.ac for boost::context detection
I have:
=> Backport #7951 to recursor 4.1.x

docs/secpoll.zone
=> remove tmpdns.powerdns.com from secpoll NSset

pdns/lua-base4.cc, pdns/lua-base4.hh, pdns/lua-recursor4.cc, pdns/lua-recursor4.hh, pdns/recursordist/docs/lua-scripting/features.rst, pdns/recursordist/docs/lua-scripting/index.rst, regression-tests.recursor-dnssec/test_Lua.py
Introduce a feature table to be able to check Lua features. 
#8205 
I have:
=> rec: Lua pdns_features table

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Update the ChangeLog and secpoll for 1.4.0-rc2

pdns/dnsdistconf.lua
Only tested the new syntax is accepted...
I have:
=> dnsdist: Do not use addLuaAction in example config

pdns/Makefile.am
This was accidently added in f441962aa3cdd9e1c2d6bab36d4274c6ac22dab7.
I have:
=> auth: Don't link lmdb needlessly

docs/backends/bind.rst, pdns/dnsdist-web.cc, pdns/recursordist/test-recursorcache_cc.cc
Fix spelling mistakes found by Debian's lintian.
I have:
=> Fix some spelling mistakes noticed by lintian

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.3.rst, pdns/recursordist/docs/changelog/index.rst
=> rec: changelog and secpoll update for rec-4.3.0-alpha1

.circleci/config.yml
This is the first of a few PRs that will change how we use CircleCI. I'm doing them one at a time so we can make sure each change does not break our day to day workflow.
I have:
=> circleci: centralise git checkout

pdns/dnsrecords.cc, pdns/qtype.hh
=> auth: register a few known types and remove an unknown one

.circleci/config.yml
=> circleci coverity: actually do git checkout

pdns/dnsdistdist/docs/install.rst
=> Fix typo/sentence

pdns/dnsdistdist/docs/reference/kvs.rst
Otherwise they look just like running text.
I have:
=> dnsdist kvs.rst: format code blocks correctly

pdns/dnsdist-web.cc
Reported by Andrew Hearn on the mailing-list (thanks!): 
https://mailman.powerdns.com/pipermail/dnsdist/2019-August/000667.html
I have:
=> dnsdist: Display the DoH and DoT binds in the web view

pdns/lua-record.cc
This PR avoids capturing variables in registered lua functions. This allows to register the function only once when used in "shared" mode.
See previous discussions in draft PR #8259
I have:
=> auth: register lua functions only once

builder-support/debian/authoritative/debian-buster/config/lua.conf, builder-support/debian/authoritative/debian-jessie/config/lua.conf, builder-support/debian/authoritative/debian-stretch/config/lua.conf, builder-support/debian/authoritative/ubuntu-trusty/config/lua.conf
Fix up outdated `lua-logging-query` examples
I have:
=> lua-logging-query -> lua-query-logging

pdns/recursordist/test-filterpo_cc.cc
~This test succeeds atm, while the description of #8231 suggests it fails currently.
Need to check older versions.~
I have:
=> Add unit test for #8231.

pdns/recursordist/test-syncres_cc4.cc
Made this test which mirrors the RPZ case. Currently fails... 
I have:
=> rec AuthDomain unit test for a wildcard in combinaton with an ent

pdns/dnsdistdist/dnsdist-secpoll.cc
=> dnsdist: Fix warning message on invalid secpoll answer

.circleci/Makefile, .gitignore
For quick turnaround times when debugging CircleCI processes.
I have:
=> makefile + one line doc for `circleci local execute`

pdns/dnsdist-lua-actions.cc, pdns/dnsdistdist/dnsdist-lua-bindings-protobuf.cc
=> dnsdist: Don't connect to remote logger in client/command mode

pdns/dns_random.cc
=> Retry getrandom() on EINTR

pdns/recursordist/docs/conf.py
No version number is better than a wrong one. 4.2 shipped with version set to 4.1....
I have:
=> Remove version number in man page footer

docs/conf.py
Blatantly stolen from #8332 
I have:
=> auth: remove version number from man page footers

SECURITY.md
Github displays the content of the `SECURITY.md` document at https://github.com/PowerDNS/pdns/security/policy nowadays.
I have:
=> Add a security policy in our repo, remove outdated statement about versions

configure.ac, ext/yahttp/yahttp/utility.hpp, modules/ldapbackend/exceptions.hh, modules/ldapbackend/ldapauthenticator.hh, modules/ldapbackend/ldapauthenticator_p.hh, modules/ldapbackend/ldapbackend.hh, modules/ldapbackend/ldaputils.hh, modules/ldapbackend/powerldap.hh, modules/ldapbackend/utils.hh, pdns/dnsdistdist/configure.ac, pdns/logger.cc, pdns/misc.cc, pdns/recursordist/configure.ac, pdns/syncres.cc, pdns/tsigutils.hh
=> Lgtm low hanging fruit

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst, pdns/dnsdistdist/docs/conf.py
=> dnsdist: ChangeLog and secpoll update for 1.4.0-rc3

pdns/dnsdist-lua.cc
=> dnsdist: Check the address supplied to 'webserver' in check-config

pdns/dnsdist-lua-bindings.cc, pdns/dnsdist-lua.cc, regression-tests.dnsdist/test_DOH.py
=> dnsdist: Lowercase custom DoH header names

builder-support/debian/recursor/debian-buster/rules, builder-support/debian/recursor/debian-jessie/rules, builder-support/debian/recursor/debian-stretch/rules
Note that jessie is different; it uses a tmp dir (see override_dh_auto_install target).
I have:
=> Fix chmod paths in rules files

pdns/dnsdist-web.cc
=> dnsdist: Fix a typo in the prometheus description of 'senderrors'

.circleci/config.yml, ext/yahttp/yahttp/cookie.hpp, pdns/dnsdist.hh, pdns/dnsdistdist/configure.ac, pdns/misc.cc, pdns/test-dnsdistpacketcache_cc.cc
=> dnsdist: Compile with -Wall -Wextra -Wshadow by default

regression-tests.dnsdist/clientsubnetoption.py, regression-tests.dnsdist/cookiesoption.py
This is very useful when comparing queries in dnsdist's regression tests.
I have:
=> Implement python's to_text() for Cookies and Client Subnet options

pdns/dnsdist-web.cc
=> dnsdist: Add a prometheus 'thread' label to distinguish identical frontends

pdns/dnsdistdist/doh.cc
Unfortunately we can't have all the metrics we have for plain TCP and DoT because libh2o is hiding quite a lot of them from us, but we can at least count these.
I have:
=> dnsdist: Count the number of concurrent connections for DoH as well

pdns/dnsdist-carbon.cc, pdns/dnsdist-lua-inspection.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist-web.cc, pdns/dnsdist.hh, pdns/dnsdistdist/doh.cc, pdns/dnsdistdist/tcpiohandler.cc, pdns/doh.hh, pdns/libssl.hh, pdns/tcpiohandler.hh
We used to have these for DoH only, this PR makes them available for DoT as well.
I have:
=> dnsdist: Add metrics about TLS versions with DNS over TLS

pdns/lua-record.cc
=> auth: A few shadowing cases.

pdns/dnsdist-web.cc
=> dnsdist: Add missing prometheus descriptions for cache-related metrics

pdns/capabilities.cc, pdns/capabilities.hh, pdns/dnsdist-lua.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdist.hh
=> dnsdist: Use SO_BINDTODEVICE when available for newServer's source itf

pdns/test-zoneparser_tng_cc.cc
Makes @pieterlexis sleep better
I have:
=> test-zoneparser_tng: more modern C++ idiom

pdns/misc.cc
Hopefully fixes #8412. Untested on macOS.
I have:
=> Work around CMSG_SPACE somehow not being a constexpr on macOS

Makefile.am
Otherwise the unit tests fail.
I have:
=> Add regression-tests/zones/unit2.test to EXTRA_DIST

pdns/dnsdist-lua.cc, pdns/dnsdistdist/doh.cc, pdns/dnsdistdist/libssl.cc, pdns/dnsdistdist/tcpiohandler.cc, pdns/doh.hh, pdns/libssl.hh, pdns/tcpiohandler.hh
=> dnsdist: Merge the setup of TLS contexts in Doh and DoT

builder-support/dockerfiles/Dockerfile.target.ubuntu-eoan
I have tested one query on the recursor, with and without dnsdist in front. I tested a few queries on auth+sqlite3.
Needs a buildbot config update!
I have:
=> add Ubuntu eoan builder target

builder-support/dockerfiles/Dockerfile.target.centos-8, builder-support/specs/dnsdist.spec, builder-support/specs/pdns-recursor.spec, builder-support/specs/pdns.spec
(cherry picked from commit 19293f266cf7bb719bd6975b3e06994f49e0e583)
I have:
=> Auth 42: Add CentOS 8 as builder target

builder-support/debian/authoritative/debian-buster/copyright, regression-tests/backends/common
=> pdns: oracle leftovers

pdns/zoneparser-tng.cc
In zone files, validate $GENERATE parameters before expanding.
I have:
=> Basic validation of $GENERATE parameters

pdns/dnsdist-carbon.cc, pdns/dnsdist-console.cc, pdns/dnsdist-lua-inspection.cc, pdns/dnsdist-web.cc, pdns/dnsdist.hh, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/doh.cc, pdns/dnsdistdist/libssl.cc, pdns/dnsdistdist/tcpiohandler.cc, pdns/doh.hh, pdns/libssl.hh, pdns/tcpiohandler.hh
So we can detect an abnormal rate of TLS connections failing because the cipher suite or the protocols supported are too restrictive, for example.
I have:
=> dnsdist: Add metrics about TLS handshake failures for DoH and DoT

regression-tests.recursor-dnssec/test_OOOTCP.py
aren't bothered with it and I can debug this in a private branch.
I have:
=> Disable one OOO test that mysteriously fails on CircleCI so others

ext/lmdb-safe/lmdb-safe.hh, pdns/dnsdist.cc, pdns/dnsdistdist/doh.cc, pdns/dnsdistdist/tcpiohandler.cc
=> dnsdist: Small changes suggested by cppcheck and clang's static analyzer

pdns/dnssecinfra.cc, pdns/opensslsigners.cc
Fixes first half of #8278.
I have:
=> openssl eddsa signers: report correct key size

build-scripts/changelog-from-pr.py
=> Small improvements to changelog-from-pr

pdns/zoneparser-tng.cc
(cherry picked from commit 775a673a1798d01e5e259a00cff7a757f5350f40)
I have:
=> rec: Backport 8451 to rec 4.2.x: Basic validation of $GENERATE parameters

pdns/dnsdist-web.cc
=> dnsdist: Rename the 'address' label to 'frontend' for DoH metrics

pdns/zoneparser-tng.cc
Illegal sounds if lawyers are involved, change to invalid.
I have:
=> Illegal -> Invalid

pdns/recursordist/docs/settings.rst
=> rec: Fix max-concurrent-requests-per-tcp-connection's underline

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.3.rst
alpha2 is tagged but will not be released due to a last-minute introduced bug :-(
So alpha3 it will be. 
Draft blog post in 
https://powerdnsblog.wordpress.com/?p=2905&preview=true
I have:
=> rec: 4.3.0 alpha3 prep

regression-tests.api/runtests, regression-tests.auth-py/runtests, regression-tests.dnsdist/runtests, regression-tests.ixfrdist/runtests, regression-tests.recursor-dnssec/runtests
which looks very ugly and just fills the logs in CircleCI and friends.
I have:
=> Pipe the output of pip to cat, so it produces no progress bar

.circleci/config.yml
=> circleci: use small resource class where possible

pdns/recursordist/Makefile.am
=> rec: Add generated dnstap.pb.{cc,h} to the 'clean' target

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Update secpoll zone and ChangeLog for 1.4.0-rc5

pdns/ws-auth.cc
Use a singe ueberbackend (db connection) per API call.
I have:
=> auth: api: avoid a large number of new database connections

pdns/recursordist/Makefile.am
(cherry picked from commit 74bdddef039219ef389eaae9731ae0f33b74b142)
I have:
=> rec: backport to 4.2.x: Add generated dnstap.pb.{cc,h} to the 'clean' target

builder-support/dockerfiles/Dockerfile.target.centos-8, builder-support/specs/dnsdist.spec, builder-support/specs/pdns-recursor.spec, builder-support/specs/pdns.spec
(cherry picked from commit 19293f266cf7bb719bd6975b3e06994f49e0e583)
I have:
=> Rec 4.2: Add CentOS 8 as builder target

docs/dnsupdate.rst, pdns/serialtweaker.cc, regression-tests/tests/pdnsutil-increase-serial-inception-epoch/command, regression-tests/tests/pdnsutil-increase-serial-inception-epoch/description, regression-tests/tests/pdnsutil-increase-serial-inception-epoch/expected_result, regression-tests/tests/pdnsutil-increase-serial-inception-epoch/skip.nodyndns, regression-tests/tests/pdnsutil-increase-serial/command
=>  pdnsutil increase-serial: under SOA-EDIT=INCEPTION-EPOCH, bump as if it is EPOCH

pdns/reczones.cc
=> rec: Avoid mthread race when using the set of rootNSZones.

pdns/pdns_recursor.cc, pdns/recursordist/docs/settings.rst, pdns/recursordist/test-syncres_cc.cc, pdns/syncres.cc, pdns/syncres.hh, regression-tests.recursor-dnssec/test_EDNSBufferSize.py, regression-tests.recursor-dnssec/test_Protobuf.py, regression-tests.recursor-dnssec/test_RootNXTrust.py, regression-tests.recursor/config.sh
Enablq qname minimization by default.
I have:
=> rec: enable qname minimization

modules/gmysqlbackend/smysql.cc, modules/opendbxbackend/odbxprivate.cc, modules/pipebackend/coprocess.cc, pdns/dnsdist.hh, pdns/iputils.hh, pdns/json.hh, pdns/nsecrecords.cc, pdns/opensslsigners.cc, pdns/rfc2136handler.cc, pdns/slavecommunicator.cc, pdns/speedtest.cc, pdns/webserver.hh
Fix lots of shadowing variables
I have:
=> Fix -WShadow warnings

pdns/pdnsutil.cc
This fixes the second half of #8278.
I have:
=> pdnsutil: correctly report ed* algo availability

pdns/pdns_recursor.cc, pdns/rec_channel.cc, pdns/rec_channel.hh, pdns/rec_channel_rec.cc, pdns/recursordist/docs/settings.rst
=> Revert "Rec 8020 docs fix"

pdns/recursordist/docs/settings.rst
=> rec: markup fix

pdns/pdns_recursor.cc, pdns/recursordist/test-syncres_cc.cc, pdns/reczones.cc, pdns/syncres.cc, pdns/syncres.hh
=> rec: Backport 8470 to rec 4.2.x:  prime NS records of root-servers.net parent (.net) 

pdns/rec_channel_rec.cc, pdns/syncres.cc, pdns/syncres.hh
(cherry picked from commit addde5c1785f040f803bc5154433b0574a197216)
I have:
=> rec: backport 7068 to 4.1.x: Do the edns dumping harder.

pdns/pdns_recursor.cc, pdns/recursordist/test-syncres_cc.cc, pdns/reczones.cc, pdns/syncres.cc, pdns/syncres.hh
=> rec: Backport 8470 to rec 4.1.x: prime NS records of root-servers.net parent (.net) 

docs/settings.rst, pdns/common_startup.cc, pdns/slavecommunicator.cc
(cherry picked from commit e3619f5766c37598579fd6d8d58d7160d31db34f)
backport of #8271 
I have:
=> auth 4.2.x: add configurable timeout for inbound AXFR

pdns/dnsdistdist/docs/guides/dns-over-https.rst
Supersedes #8354 by fixing a couple nits. Closes #8280.
I have:
=> dnsdist: Add a DoH guide to the documentation.

pdns/recursordist/docs/settings.rst
We have had very positive feedback. Earlier it was already switched to on by default.
I have:
=> QName Minimization is no longer experimental

pdns/pdns_recursor.cc
=> Avoid startup race by setting the state of a tread before starting it.

ext/lmdb-safe/lmdb-safe.cc, ext/lmdb-safe/lmdb-safe.hh, ext/lmdb-safe/lmdb-typed.cc, ext/lmdb-safe/lmdb-typed.hh, modules/lmdbbackend/lmdbbackend.cc, modules/lmdbbackend/lmdbbackend.hh, pdns/dnsdistdist/dnsdist-kvs.cc, pdns/dnsdistdist/test-dnsdistkvs_cc.cc, pdns/pdnsutil.cc, pdns/ws-auth.cc
Based on https://github.com/ahupowerdns/lmdb-safe/pull/6 from @horazont . Initial import by @pieterlexis.
Needs more testing.
I have:
=> Fix lmdb backend

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: ChangeLog and secpoll update for dnsdist 1.4.0

docs/dnsupdate.rst, pdns/serialtweaker.cc, regression-tests/tests/pdnsutil-increase-serial-inception-epoch/command, regression-tests/tests/pdnsutil-increase-serial-inception-epoch/description, regression-tests/tests/pdnsutil-increase-serial-inception-epoch/expected_result, regression-tests/tests/pdnsutil-increase-serial-inception-epoch/skip.nodyndns, regression-tests/tests/pdnsutil-increase-serial/command
=> auth-4.2.x: pdnsutil increase-serial: under SOA-EDIT=INCEPTION-EPOCH, bump as if it is EPOCH

modules/bindbackend/bindbackend2.cc
(cherry picked from commit 97ed14cd4efebd044ae824aac73fdc76aa6b9ed6)
Backport of #7989 
I have:
=> auth 4.2.x: bindbackend: use metadata for also-notifies as well

pdns/pdnsutil.cc, pdns/rfc2136handler.cc, regression-tests/tests/1dyndns-content-casemix/command, regression-tests/tests/1dyndns-content-casemix/description, regression-tests/tests/1dyndns-content-casemix/expected_result, regression-tests/tests/1dyndns-content-casemix/skip.nodyndns
=> auth-4.2.x: rfc2136, pdnsutil: somewhat improve duplicate record handling

docs/domainmetadata.rst, docs/settings.rst, pdns/slavecommunicator.cc, pdns/ws-auth.cc
=> auth 4.2.x: Add SLAVE-RENOTIFY zone metadata support

pdns/dnsrecords.cc, pdns/qtype.hh
(cherry picked from commit fa23972a8cadfd648ae75c0a47f7a514b30293c8)
Backport of #8095 
I have:
=> auth 4.2.x: register a few known types and remove an unknown one

pdns/packethandler.cc
If we don't drain `get()` after `lookup()`, the next DB lookup might fail.
I have:
=> auth: on luaSynth exception, drain db output. Fixes #8299

pdns/ws-auth.cc
=> Backport #8457 and #8497

pdns/dnsdist-dynblocks.hh, pdns/dnsdist-lua-inspection.cc, pdns/dnsdistdist/dnsdist-lua-inspection-ffi.cc, pdns/dnsdistdist/dnsdist-lua-inspection-ffi.hh, pdns/dnsscope.cc, pdns/statnode.cc, pdns/statnode.hh
=> dnsdist: Add the number of received bytes to StatNode entries

pdns/recursordist/docs/http-api/zone.rst
Fixes #5376, though the code could use some proper use checking as well.
I have:
=> rec: Explain the condition that must be true for the adding of auth zones and forwarding zones.

pdns/packethandler.cc
manual backport of #8301
I have:
=> auth-4.2.x: on luaSynth exception, drain db output

pdns/dnsdistdist/docs/reference/dnsnameset.rst
=> dnsdist: Fix typos in dnsnameset.rst' example code

.circleci/config.yml, pdns/recursordist/negcache.cc, pdns/recursordist/negcache.hh, pdns/recursordist/pubsuffixloader.cc, pdns/recursordist/rec_metrics.hh, pdns/recursordist/stable-bloom.hh, pdns/recursordist/test-ednsoptions_cc.cc, pdns/recursordist/test-filterpo_cc.cc, pdns/recursordist/test-mtasker.cc, pdns/recursordist/test-negcache_cc.cc, pdns/recursordist/test-nod_cc.cc, pdns/recursordist/test-recursorcache_cc.cc, pdns/recursordist/test-rpzloader_cc.cc, pdns/recursordist/test-secpoll_cc.cc, pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc.hh, pdns/recursordist/test-syncres_cc1.cc, pdns/recursordist/test-syncres_cc2.cc, pdns/recursordist/test-syncres_cc3.cc, pdns/recursordist/test-syncres_cc4.cc, pdns/recursordist/test-syncres_cc5.cc, pdns/recursordist/test-syncres_cc6.cc, pdns/recursordist/test-syncres_cc7.cc, pdns/recursordist/test-syncres_cc8.cc, pdns/recursordist/test-syncres_cc9.cc, pdns/recursordist/test-xpf_cc.cc, pdns/recursordist/testrunner.cc
Start of the great reformatting. This is only in recursordist
Done by:
```
./build-scripts/format-code pdns/recursordist/*.[ch][ch]
```
Tool is smart enough to only do regular files and not touch already reformatted files.
I have:
=> rec: Reformat code

pdns/pdns_recursor.cc, pdns/rec_channel_rec.cc, pdns/recursordist/docs/manpages/rec_control.rst, pdns/syncres.cc, pdns/syncres.hh
=> rec: Backport 8525 to rec 4.1.x: Purge map of failed auths periodically by keeping a last changed timestamp. 

pdns/pdns_recursor.cc, pdns/rec_channel_rec.cc, pdns/recursordist/docs/manpages/rec_control.1.rst, pdns/syncres.cc, pdns/syncres.hh
=> rec: Backport 8525 to rec 4.2.x: Purge map of failed auths periodically by keeping a last changed timestamp.

pdns/lua-record.cc
This turns a crash into a somewhat useful error.
I have:
=> LUA view: do not crash on empty IP list, fixes #8572

pdns/lua-record.cc
(cherry picked from commit 28beeb0f76f2ba0dcea0def88fe46dbce51d06eb)
Backport of #8575
I have:
=> auth-4.2.x: LUA view: do not crash on empty IP list, fixes #8572

build-scripts/format-code
=> format-code script: Do not show verbose messages if !tty or CIRCLECI

pdns/dnsdistdist/docs/install.rst, pdns/recursordist/docs/getting-started.rst, pdns/recursordist/docs/performance.rst
=> docs: s/RedHat/Red Hat/

build-scripts/git-to-changelog-merges, docs/changelog/4.2.rst, docs/secpoll.zone
=> secpoll and changelog for auth 4.2.1

docs/guides/recursion.rst, docs/settings.rst, pdns/common_startup.cc, pdns/nameserver.cc, pdns/nameserver.hh, pdns/tcpreceiver.cc, regression-tests.api/runtests.py, regression-tests.auth-py/authtests.py, regression-tests.nobackend/counters/command, regression-tests.nobackend/distributor/command, regression-tests.nobackend/supermaster-signed/command, regression-tests.nobackend/supermaster-unsigned/command, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor/config.sh
Treat listen address as equally as possible. This removes a bunch of
duplicate code.
I have:
=> Auth: Remove local-ipv6 setting

pdns/dnspcap.hh, pdns/dnsscope.cc
This improves the output in two situations that don't really happen a lot.
I have:
=> dnsscope: two nits

pdns/dnsdistdist/docs/reference/tuning.rst
=> dnsdist: Add missing newline in setMaxUDPOutstanding() documentation

pdns/dnsdistdist/dnsdist-kvs.cc
=> dnsdist: Add missing exception message in KVS error

pdns/dnsdist.cc, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Document that the 'zero-scope' feature requires 'parseECS'

modules/bindbackend/bindbackend2.cc, modules/bindbackend/bindbackend2.hh
(cherry picked from commit 7fff09acbd57c41b28d6dfba7a55e561167ace1a)
Backport of #8350
I have:
=> auth 4.2x: bind backend: pthread_mutex_t should be inited and destroyed and not be copied

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.1.rst
=> rec: Prep for rec-4.1.15

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.2.rst
=> Prepare for rec-4.2.1

build-scripts/git-to-changelog-merges, builder-support/specs/pdns.spec, docs/changelog/4.3.rst, docs/changelog/index.rst, docs/secpoll.zone, docs/settings.rst, docs/upgrading.rst
=> Auth 4.3.0 docs

build-scripts/docker/generate-repo-files.sh
I'm going to merge this at the end of the day if there are no objections, since this scripts doesn't affect anything else.
=> Add `auth-43` and `rec-43`.

pdns/dnsdistdist/docs/install.rst
=> dnsdist: Add missing underline in install documentation

pdns/pdnsutil.cc
Fix test syntax in 'pdnsutil --help'
I have:
=> Fix test syntax in 'pdnsutil --help'

pdns/recursordist/docs/settings.rst, pdns/recursordist/docs/upgrade.rst
=> Upgrade guide for rec-4.3

pdns/dnsdist-lua.cc
=> dnsdist: Display the correct DoT provider

pdns/dnsdistdist/docs/reference/comboaddress.rst, pdns/dnsdistdist/docs/reference/dnsnameset.rst, pdns/dnsdistdist/docs/reference/kvs.rst
=> dnsdist: Fix a few typos in the documentation

pdns/sdig.cc
Renamse a vasr so it does not clash.
I have:
=> sdig: Fix compilation on OpenBSD where stdin is a define

pdns/pdns_recursor.cc, pdns/recursordist/docs/settings.rst
=> rec: Backport 8647 to rec 4.3.x: increase default maxqperq

pdns/recursordist/test-syncres_cc1.cc, pdns/recursordist/test-syncres_cc4.cc, pdns/recursordist/test-syncres_cc6.cc, pdns/recursordist/test-syncres_cc7.cc, pdns/syncres.cc, pdns/validate.cc
=> rec: Backport 7928 to rec 4.2.x: Better detection of Bogus zone cuts for DNSSEC validation

contrib/ProtobufLogger.py, pdns/dnsdistdist/dnsdist-lua-bindings-protobuf.cc, pdns/dnsdistdist/docs/reference/protobuf.rst, pdns/dnsmessage.proto, pdns/pdns_recursor.cc, pdns/protobuf.cc, pdns/protobuf.hh
=> rec: Backport 8702 to 4.3.x: Add the source and destination ports to the protobuf msg

pdns/dnsdistdist/docs/rules-actions.rst
=> dnsdist: Fix a versionchanged in the docs

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.3.rst
=> rec: Prepare for recursor 4.3.0-beta2 release

pdns/pdns_recursor.cc
A POC following discsussion.
I have:
=> rec: Give an explcit messsage if something is wrong with socket-dir

builder-support/specs/pdns-recursor.spec
=> rec: EPEL 8 now has libfstrm-devel

builder-support/specs/dnsdist.spec
=> dnsdist: EPEL 8 now has libfstrm-devel

modules/lmdbbackend/lmdbbackend.cc, modules/lmdbbackend/lmdbbackend.hh
=> auth: lmdb-backend, remove duplicate code and some unused variables

pdns/pdns_recursor.cc
=> rec: Backport 8688 to rec 4.3.x: Give an explcit messsage if something is wrong with socket-dir. 

pdns/filterpo.cc, pdns/lua-recursor4.cc, pdns/pdns_recursor.cc, pdns/recursordist/test-filterpo_cc.cc, pdns/recursordist/test-syncres_cc3.cc, pdns/syncres.cc, pdns/syncres.hh, regression-tests.recursor-dnssec/test_RPZ.py
=> rec: Backport 8705 to rec 4.3.x: Fix the evaluation order for filtering policies (RPZ) 

builder-support/specs/pdns-recursor.spec
=> rec: Backport 8719 to rec 4.3.x: EPEL 8 now has libfstrm-devel

pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc.hh, pdns/recursordist/test-syncres_cc6.cc, pdns/validate.cc
=> rec: Backport 8723 to rec 4.3.x: add unit tests for the NSEC3 Opt-Out case

pdns/common_startup.cc, pdns/tcpreceiver.cc
=> auth: Fix auth logging if no packet cache; from Habbie

docs/dnssec/operational.rst
Because we get the occasional question about this.
I have:
=> auth dnssec docs: some notes on TTL usage

pdns/dnsseckeeper.hh, pdns/dynhandler.cc, pdns/tcpreceiver.cc, pdns/ws-auth.cc
=> auth: Make DNSSECKeeper::clear{All,}Caches() static

modules/bindbackend/bindbackend2.cc, modules/bindbackend/bindbackend2.hh
I had a bit of trouble understanding how the records are managed in the bind backend, especially when a zone is reloaded. I believe this PR will make it easier.
I have:
=> auth: Make it clearer that records are never altered, only replaced

docs/domainmetadata.rst, docs/settings.rst, pdns/common_startup.cc, pdns/dbdnsseckeeper.cc, pdns/dnsseckeeper.hh, pdns/packethandler.cc, regression-tests.nobackend/default-publish-cds/.gitignore, regression-tests.nobackend/default-publish-cds/command, regression-tests.nobackend/default-publish-cds/description, regression-tests.nobackend/default-publish-cds/expected_result, regression-tests.nobackend/default-publish-cds/named.conf, regression-tests.nobackend/default-publish-cds/pdns.conf
Fixes #6466. ~Needs docs.~ has docs
I have:
=> auth: add default-publish-{cds|cdnskey} options

pdns/pdnsutil.cc
It contains a (worhtless) private key and this triggers scanning tools.
I have:
=> pdnsutil: remove dead code

m4/boost.m4
This detects boost::context on boost version 1.61 through 1.65 correctly
(cherry picked from commit c54133a4abccd7228b6898af5cb7b684c6225e97)
I have:
=> rec: backport 8740 to rec 4.3.x: Update boost.m4

pdns/dnsseckeeper.hh
This is slightly faster, especially with a larger number of entries.
I have:
=> auth: Use a hashed index instead of an ordered one for the key cache

docs/backends/remote.rst, modules/remotebackend/httpconnector.cc, modules/remotebackend/remotebackend.cc, modules/remotebackend/remotebackend.hh
=> Remote: Implement getUnfreshSlaveInfos and setFresh

pdns/recursordist/docs/manpages/rec_control.1.rst
=> rec: Document the difference between rec_control quit and quit-nicely.

m4/boost.m4
This detects boost::context on boost version 1.61 through 1.65 correctly
(cherry picked from commit c54133a4abccd7228b6898af5cb7b684c6225e97)
I have:
=> rec: backport 8740 to rec 4.2.x: Update boost.m4

m4/boost.m4
This detects boost::context on boost version 1.61 through 1.65 correctly
(cherry picked from commit c54133a4abccd7228b6898af5cb7b684c6225e97)
I have:
=> rec: backport 8740 to rec 4.1.x: Update boost.m4

pdns/dbdnsseckeeper.cc, pdns/pdnsutil.cc
=> Remove the algo 5 -> 7 upgrade

docs/backends/lmdb.rst
I forgot to add documentation for the LMDB setting in #8177, so this fixes that oversight.
I have:
=> Add some documentation for the LMDB schema version setting

pdns/recursordist/docs/performance.rst
Fix typo in Recursor Performance Guide
=> Fix typo in Recursor Performance Guide

docs/changelog/4.3.rst, docs/secpoll.zone, docs/settings.rst, docs/upgrading.rst
=> changelog and secpoll for auth-4.3.0-beta1

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.3.rst
=> Prep rec-4.3.0-rc1

docs/common/security-policy.rst
=> Update security email addresses

docs/guides/basic-database.rst
Updated version number for shown Sql as the `published BOOL DEFAULT 1,` is for pdns-4.3.x
I have:
=> Updated version number

pdns/dnsdist-lua-bindings-dnsquestion.cc
`LuaWrapper` doesn't support inheritance, so even though `DNSResponse` inherits from the `DNSQuestion` object the bindings are not inherited.
I have:
=> dnsdist: Add getTag()/setTag() Lua bindings for a DNSResponse

pdns/dnsdist-web.cc
=> dnsdist: Add backend status to prometheus metrics

pdns/dnsdist-lua.cc, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/doh.cc, pdns/doh.hh, regression-tests.dnsdist/test_DOH.py
=> dnsdist: Implement Cache-Control headers in DoH

pdns/dnsdist-console.cc, pdns/dnsdist-lua-actions.cc, pdns/dnsdist-lua-bindings.cc, pdns/dnsdist-lua-vars.cc, pdns/dnsdist-lua.hh, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/docs/reference/constants.rst, pdns/dnsdistdist/docs/rules-actions.rst, regression-tests.dnsdist/test_Spoofing.py
Fixes https://github.com/PowerDNS/pdns/issues/7721
I have:
=> dnsdist: Add spoofRawAction() to craft answers from raw bytes

docs/tsig.rst
A small typo in documentation for TSIG.
I have:
=> Fix typo in tsig documentation

builder-support/debian/dnsdist/debian-buster/dnsdist.postinst, builder-support/debian/dnsdist/debian-buster/rules, builder-support/debian/dnsdist/debian-jessie/dnsdist.postinst, builder-support/debian/dnsdist/debian-jessie/rules, builder-support/debian/dnsdist/debian-stretch/dnsdist.postinst, builder-support/debian/dnsdist/debian-stretch/rules
Introduced in c98c0ef694de0c536e6d71af8c58a16f6635ea35
I have:
=> dnsdist: Fix configuration file installation / chmod

pdns/dnsdistdist/docs/upgrade_guide.rst, pdns/dnsdistdist/doh.cc, regression-tests.dnsdist/test_DOH.py
=> dnsdist: Don't accept sub-paths of configured DoH URLs

pdns/recursordist/docs/requirements.txt
Passing build at https://builder.powerdns.com/#/builders/9/builds/3062
I have:
=> rec-4.1.x: limit python deps to stuff that still works on py2

docs/Makefile.am
https://builder.powerdns.com/#/builders/8/builds/3213
I have:
=> auth-4.1.x: limit python deps to stuff that still works on py2

docs/http-api/swagger/authoritative-api-swagger.yaml, pdns/ws-api.cc
(cherry picked from commit c65b5e12832ac38259f215f084a33b214b117fa8)
I have:
=> auth 4.2.x api: add includerings option to statistics endpoint

builder-support/debian/authoritative/debian-buster/copyright, builder-support/debian/authoritative/debian-jessie/copyright, builder-support/debian/authoritative/debian-stretch/copyright, builder-support/debian/dnsdist/debian-buster/copyright, builder-support/debian/dnsdist/debian-jessie/control, builder-support/debian/dnsdist/debian-jessie/copyright, builder-support/debian/dnsdist/debian-stretch/control, builder-support/debian/dnsdist/debian-stretch/copyright, builder-support/debian/recursor/debian-buster/copyright, builder-support/debian/recursor/debian-jessie/copyright, builder-support/debian/recursor/debian-stretch/copyright, docs/changelog/4.0.rst, docs/changelog/4.1.rst, docs/changelog/4.2.rst, docs/changelog/pre-4.0.rst, docs/dnssec/index.rst, docs/security-advisories/powerdns-advisory-2015-03.rst, pdns/dnsdistdist/docs/changelog.rst, pdns/recursordist/docs/changelog/4.0.rst, pdns/recursordist/docs/changelog/4.1.rst, pdns/recursordist/docs/changelog/pre-4.0.rst
Updates my name in old changelogs, documentation, etc.
I guess not putting this MR into the changelogs would make sense ;)
=> Update my name in old changelogs

.circleci/config.yml, build-scripts/travis.sh
Hopefully fixes #8796.
I have:
=> auth CI: enable ODBC thread locking

pdns/nsecrecords.cc, pdns/test-dnsrecords_cc.cc
Fixes #8825 (thanks for the report!).
I have:
=> Refuse NSEC records with a bitmap length > 32

pdns/mastercommunicator.cc
=> auth: do not update identical notified serials

pdns/dnspacket.cc
Also improves the wording.
I have:
=> auth: log "No question section in packet" at Debug. Fixes #7970

.circleci/config.yml
=> auth-4.2.x: avoid 'git show -s' from starting a pager in CircleCI

pdns/filterpo.hh
=> rec: Init zone's d_priority field.

pdns/filterpo.cc, pdns/filterpo.hh, pdns/pdns_recursor.cc, pdns/recursordist/test-filterpo_cc.cc, pdns/syncres.cc, regression-tests.recursor-dnssec/test_Protobuf.py, regression-tests.recursor-dnssec/test_RPZ.py
=> rec: Backport 8823 to rec 4.3.x: do continue rpz processing if the current policy is passthru

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.3.rst
=> rec: Prep for rec-4.3.0-rc2

pdns/dnsdist-lua.cc, pdns/dnsdist-snmp.cc
=> dnsdist: Fix compile errors without snmp support

pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc, pdns/recursordist/test-syncres_cc6.cc, pdns/test-dnsdist_cc.cc, pdns/test-iputils_hh.cc
(which is more picky than others)
I have:
=> Fix unsigned vs signed warnings spotted by clang on OpenBSD

pdns/dnsdistdist/Makefile.am, pdns/recursordist/Makefile.am
This avoids the file sticking around when you no longer need it, in which case it might also be wrong compared to your systemwide version.
I have:
=> rec, dnsdist: always clean lua.hpp

.circleci/config.yml
Also:
- build the fuzzing targets ;
- <strike>build with Lua records enabled.</strike> (this was added to master in the meantime, see https://github.com/PowerDNS/pdns/pull/8744). 
I have:
=> auth: Build and run the unit tests in Circle CI

docs/changelog/4.3.rst, docs/secpoll.zone
~Changelog accurate as of~ tagged at 68d8625d3c8a8dee878cfc686358e068664a2cd6
* https://builder.powerdns.com/#/builders/99/builds/1182
* https://builder.powerdns.com/#/buildrequests/123757
I have:
=> changelog and secpoll for auth-4.3.0-beta2

.circleci/config.yml
(cherry picked from commit fed8314d910dbd61f3f3abfbf51f8a316b93001c)
Backport of #8833.
I have:
=> auth-4.2.x: Allow all connections to the PG server in Circle CI

.circleci/config.yml, build-scripts/format-code, pdns/test-bindparser_cc.cc
Fix a few issues which should bring us closer to being able to do format all.
I have:
=> Prepare for reformat-all

pdns/version.cc
=> Update copyright year

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc, pdns/dnsdistdist/docs/advanced/acl.rst, pdns/dnsdistdist/docs/reference/config.rst
Implement a function to remove a netmask from the ACL via the console.
I have:
=> Implement rmACL()

pdns/dnsdist-console.cc
=> dnsdist: Fix a typo in the help/completion for getDNSCryptBindCount

.circleci/config.yml
=> rec: backport 8833 to rec 4.3.x: Allow all connections to the PG server in Circle CI

pdns/version.cc
(cherry picked from commit 9fce9d6c21253da0fbeed5163d148be4a0bad1f6)
I have:
=> rec: backport 8857 to rec 4.3.x: update copyright year

docs/lua-records/functions.rst
The docs had warning NOTEs that were wrong.
I have:
=> auth LUA: explain supported createForward[6] formats

docs/backends/lmdb.rst
See https://github.com/PowerDNS/pdns/issues/8134#issuecomment-589634048
I have:
=> auth lmdb docs: update warning about known bugs

docs/settings.rst
=> auth: delay SOA autofilling removal to 4.4.0

docs/http-api/index.rst
Change wording
I'd use either "the use of a password" or "the use of password protection"
I have:
- [✔︎] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
=> auth docs: language nit

build-scripts/travis.sh
=> travis: skip odbc testing, we have it in circleci

pdns/dnsdist-lua.cc
=> dnsdist: Remove unused lambda capture reported by clang++

docs/secpoll.zone, pdns/recursordist/docs/appendices/EOL.rst, pdns/recursordist/docs/changelog/4.3.rst
=> rec: prep for rec-4.3.0

docs/manpages/sdig.1.rst, pdns/sdig.cc
Fixed synopsis and added usage examples in the sdig man page 
I have:
=> sdig man page: fix markup in synopsis, add usage hints, examples

build-scripts/travis.sh, pdns/version.cc
=> auth 4.3.x: two backports

pdns/recursordist/docs/manpages/rec_control.1.rst
=> In .rts a \ is \\.

pdns/recursordist/docs/manpages/rec_control.1.rst
I have:
Should fix #8885 correctly now.
=> rec: second attempt: use ``...`` for literals.

pdns/dnsdist-lua.cc
=> dnsdist: Fix 'unused lambda capture' warning without DoH or DoT

pdns/dnsdistdist/docs/rules-actions.rst
=> dnsdist: Fix documentation for functions removed in 1.3.0

pdns/recursordist/docs/changelog/4.3.rst
'rec dnstap' was not very descriptive
I have:
=> rec: note dnstap for auth communication in changelog

docs/performance.rst
=> auth docs: talk about glibc & MALLOC_ARENA_MAX

pdns/auth-packetcache.cc, pdns/auth-querycache.cc, pdns/cachecleaner.hh
=> auth: make sure we look at 10% of all cached items during cleanup

pdns/packethandler.cc
=> Fix it so NSEC and NSEC3 records if there are no published DNSKEY's

pdns/packethandler.cc
=> auth-4.3.x:  Fix it so NSEC and NSEC3 records if there are no published DNSKEYs

docs/changelog/4.3.rst, docs/secpoll.zone
=> auth: secpoll&changelog for 4.3.0-rc2

build-scripts/test-recursor-bulk
This should fix the buildbot recursor-test1 test.
I have:
=> rec: test now uses rec_control, so supply location of the executable

pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Document DynBlockRulesGroup:setSuffixMatchRule

pdns/dnsdistdist/docs/rules-actions.rst
=> dnsdist: Clarify how DelayResponseAction differs from DelayAction

builder-support/specs/dnsdist.spec, builder-support/specs/pdns-recursor.spec, builder-support/specs/pdns.spec
=> Reload systemctl service on updates

pdns/dnsdist.cc
=> dnsdist: Warn on startup about low weight values with chashed

pdns/dnsdistdist/docs/advanced/index.rst, pdns/dnsdistdist/docs/advanced/proxyprotocol.rst, pdns/dnsdistdist/docs/advanced/xpf.rst, pdns/dnsdistdist/docs/rules-actions.rst
=> dnsdist: Add more documentation about XPF and the Proxy Protocol

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst, pdns/dnsdistdist/docs/conf.py
=> dnsdist: Update ChangeLog and secpoll for 1.5.0-alpha1

ext/lmdb-safe/lmdb-safe.cc
This avoids a build issue on FreeBSD.
I have:
=> auth lmdb: avoid blanket std import; fixes #8872

ext/lmdb-safe/lmdb-safe.cc
Backport of #8916
(cherry picked from commit 6910a23b67f64bd71ffb26c1888fb9d8b99acfa6)
I have:
=> auth 4.3.x lmdb: avoid blanket std import; fixes #8872

pdns/dnsdist-lua-bindings.cc, pdns/dnsdistdist/docs/reference/config.rst
This allows for modifying an existing SMT.
I have:
=> dnsdist: expose SuffixMatchNode::remove in Lua

m4/boost.m4
Closes #8875
(cherry picked from commit 2bcb6ea0ddc99548d3d7d6d317c5d64d55aac6cc)
I have:
=> rec: backport 8876 to rec-4.2.x: Update boost.m4

m4/boost.m4
Closes #8875
(cherry picked from commit 2bcb6ea0ddc99548d3d7d6d317c5d64d55aac6cc)
I have:
=> rec: backport 8876 to rec-4.3.x: Update boost.m4

pdns/dnsdistdist/docs/guides/cache.rst
Fix layout in the dnsdist Caching Responses guide
=> Fix layout in the dnsdist Caching Responses guide

docs/installation.rst
=> auth docs: clarify absence/presence of pdns-backend-bind

pdns/packethandler.cc, regression-tests.nobackend/tinydns-data-check/expected_result, regression-tests/backends/bind-master, regression-tests/backends/gsql-common, regression-tests/backends/lmdb-master, regression-tests/named.conf, regression-tests/tests/cryptokeys/command, regression-tests/tests/cryptokeys/expected_result.narrow, regression-tests/tests/cryptokeys/expected_result.nsec3, regression-tests/tests/verify-dnssec-zone/command, regression-tests/zones/hiddencryptokeys.org
Properly fixes #8921, includes test cases.
I have:
=> Fix NSECx for unpublished DNSKEYs properly

pdns/dnsdistdist/docs/advanced/proxyprotocol.rst, pdns/recursordist/docs/settings.rst
=> rec/dnsdist: Document that we only support the version 2 of the Proxy Protocol

builder-support/dockerfiles/Dockerfile.debbuild-prepare, builder-support/dockerfiles/Dockerfile.target.ubuntu-focal
Builds auth, rec, dnsdist successfully. I did not test the resulting packages.
I have:
=> builder: add ubuntu focal target

pdns/packethandler.cc, regression-tests.nobackend/tinydns-data-check/expected_result, regression-tests/backends/bind-master, regression-tests/backends/gsql-common, regression-tests/backends/lmdb-master, regression-tests/named.conf, regression-tests/tests/cryptokeys/command, regression-tests/tests/cryptokeys/expected_result.narrow, regression-tests/tests/cryptokeys/expected_result.nsec3, regression-tests/tests/verify-dnssec-zone/command, regression-tests/zones/hiddencryptokeys.org
=> auth-4.3.x: Fix NSECx for unpublished DNSKEYs properly

regression-tests.auth-py/test_LuaRecords.py
This test was missing.
I have:
=> auth LUA: add test for resolve() function

builder-support/gen-version
=> Backport 7822 to rec-4.2.x: Update gen-version to use latest tag for version nunmbers

pdns/slavecommunicator.cc, regression-tests.auth-py/authtests.py, regression-tests.auth-py/requirements.txt, regression-tests.auth-py/test_IXFR.py
(cherry picked from commit fce7ba570569aa6e9d5a21e0c4525a50b73789ef)
Backport of #8977
I have:
=> auth-4.3.x: fix IXFR-in record duplication issue by avoiding the query cache

pdns/dnsdist.cc
=> dnsdist: Drop responses with the QR bit set to 0

.github/config.yml, docs/index.rst, pdns/recursordist/docs/index.rst
The plain `/new` link does not use any template.
I have:
=> docs: link to GitHub issue template chooser

pdns/dnssecinfra.cc, pdns/filterpo.hh, pdns/pdns_recursor.cc, pdns/recursor_cache.cc, pdns/reczones.cc, pdns/syncres.cc, pdns/validate.cc
Fix warnings with llvm10 and -Wrange-loop-construct
I have:
=> Fix warnings with llvm10 and -Wrange-loop-construct

pdns/slavecommunicator.cc, regression-tests.auth-py/authtests.py, regression-tests.auth-py/requirements.txt, regression-tests.auth-py/test_IXFR.py
=> auth 4.2: fix IXFR-in record duplication issue by avoiding the query cache

pdns/auth-packetcache.cc, pdns/auth-querycache.cc, pdns/cachecleaner.hh
=> auth-4.2: make sure we look at 10% of all cached items during cleanup

pdns/recursordist/test-recursorcache_cc.cc
Also, zap unneeded clear() calls, get() already does that.
Fixes #9006 
I have:
=> rec: test what's I believe was intended for test_RecursorCacheSimple

.circleci/config.yml
Hopefully this reduces the incidence of ALIAS failures breaking our CI.
I have:
=> circleci auth: use recursor on localhost for resolving ALIAS

pdns/ueberbackend.cc
=> auth 4.2: make sure get() is always returning the default value for d_place

modules/bindbackend/Makefile.am, pdns/Makefile.am
And, actually install them, like the gsqlbackends do.
I have:
=> Install bind SQL schema files as part of bindbackend

docs/appendices/EOL.rst
4.3 is out, so 4.0 is EOL.
I have:
=> auth docs: shift EOL generations

pdns/dnsdist-lua.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Add an option to control the size of the TCP listen queue

docs/changelog/4.2.rst, docs/secpoll.zone, docs/upgrading.rst
~Candidate builds: https://builder.powerdns.com/#/buildrequests/124796 and https://builder.powerdns.com/#/buildrequests/124794~
Todo:
I have:
=> changelog&secpoll for auth 4.2.2

pdns/recursordist/docs/appendices/internals.rst
=> rec: Tell a bit about qname minimization

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst, pdns/dnsdistdist/docs/guides/dns-over-https.rst, pdns/dnsdistdist/docs/guides/dns-over-tls.rst, pdns/dnsdistdist/docs/upgrade_guide.rst
=> dnsdist: Update ChangeLog and secpoll for 1.5.0-rc1

builder-support/specs/pdns.spec
This matches EPEL downstream.
Closes: #9026
I have:
=> EL8 pkgs: Build mysql backend against mariadb-connector-c-devel

pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Fix the year (2010 -> 2020) of the latest changelog entries

pdns/dnscrypt.cc, pdns/dnsdist-cache.cc, pdns/dnsdist-lua-bindings.cc, pdns/dnsdist-lua.cc
Reported by clang's `-Wrange-loop-construct` since version 10.
I have:
=> dnsdist: Avoid copies in for loops

pdns/lua-recursor4-ffi.hh, pdns/lua-recursor4.cc, pdns/lua-recursor4.hh, pdns/pdns_recursor.cc, pdns/recursor_cache.cc, pdns/recursor_cache.hh, pdns/recursordist/docs/lua-scripting/hooks.rst, pdns/recursordist/test-recursorcache_cc.cc, pdns/recursordist/test-syncres_cc3.cc, pdns/recursordist/test-syncres_cc8.cc, pdns/recursordist/test-syncres_cc9.cc, pdns/reczones.cc, pdns/syncres.cc, pdns/syncres.hh, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_RoutingTag.py
In Lua we can set a routing tag (final name to be decided upon). This tag is used as an extra key in the record cache.
I have:
=> Rec: routing tag

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.4.rst, pdns/recursordist/docs/changelog/index.rst
Builds:
https://builder.powerdns.com/#/builders/97/builds/1229
https://builder.powerdns.com/#/builders/114/builds/625
Draft blog: https://powerdnsblog.wordpress.com/?p=3065&preview=true
I have:
=> Prep rec-4.4.0-alpha1

pdns/dnsdistdist/docs/guides/webserver.rst, pdns/dnsdistdist/docs/reference/constants.rst, pdns/dnsdistdist/docs/reference/index.rst, pdns/dnsdistdist/docs/reference/logging.rst
A set of very small doc changes that would have helped me.
I have:
=> Small doc changes

pdns/dnsdist-console.cc, pdns/dnsdist-lua-vars.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/configure.ac, pdns/dnsdistdist/dnsdist-lua-inspection-ffi.hh, pdns/dnsdistdist/tcpiohandler.cc, pdns/dnslabeltext.rl, pdns/sodcrypto.cc
And fix a few missing or duplicated prototypes. Found a wrong Lua FFI function declaration in the process..
I have:
=> dnsdist: Build with -Wmissing-declarations -Wredundant-decls

pdns/devpollmplexer.cc
The less naked pointers remaining, the better I sleep at night ;)
I have:
=> Get rid of a naked pointer in the /dev/poll event multiplexer

modules/bindbackend/bindbackend2.cc
=> BIND-DOMAIN-EXTENDED-STATUS: don't look for a domain called BIND-DOMAIN-EXTENDED-STATUS

pdns/dnsdist-lua.cc
=> dnsdist: Fix duplicated HTTP/1 counter in 'showDOHFrontends()'

builder-support/dockerfiles/Dockerfile.debbuild-prepare, builder-support/dockerfiles/Dockerfile.target.ubuntu-focal
(cherry picked from commit b4f4b1ab4ba666fe16f0201b38778fe66dc8e7ae)
I have:
=> rec: backport to rec 4.3.x: builder: add ubuntu focal target

builder-support/dockerfiles/Dockerfile.debbuild-prepare, builder-support/dockerfiles/Dockerfile.target.ubuntu-focal
(cherry picked from commit b4f4b1ab4ba666fe16f0201b38778fe66dc8e7ae)
I have:
=> rec: backport to rec 4.2.x: builder: add ubuntu focal target

builder-support/dockerfiles/Dockerfile.debbuild-prepare, builder-support/dockerfiles/Dockerfile.target.ubuntu-focal
=> auth-4.3.x: add ubuntu focal target

modules/ldapbackend/ldapauthenticator.cc, modules/ldapbackend/ldapauthenticator_p.hh, pdns/dnsbackend.cc, pdns/filterpo.cc, pdns/pdnsutil.cc, pdns/receiver.cc, pdns/recursordist/test-syncres_cc.cc, pdns/slavecommunicator.cc, pdns/test-signers.cc, pdns/ws-auth.cc
And remove an unused variable at the same time.
I have:
=> Fix useless copies in loop reported by clang++ 10

ext/yahttp/yahttp/reqresp.cpp
=> auth-4.2.x: Fix build with gcc-10

modules/bindbackend/Makefile.am, pdns/Makefile.am
=> auth-4.3.x: Install bind SQL schema files as part of bindbackend

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
This should really be the last release candidate, with only a few minor fixes and cleanups. 
I have:
=> dnsdist: Update the ChangeLog and secpoll for 1.5.0-rc2

pdns/recursordist/docs/dnssec.rst
=> rec: don't suggest to add a TA for powerdns.com

docs/secpoll.zone
=> Mark auth 4.0.x as EOL, plus some even older versions.

docs/appendices/EOL.rst, pdns/recursordist/docs/appendices/EOL.rst
If this table format is OK, I'll add the auth one.
I have:
=> Tell about the release cycles.

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.1.rst, pdns/recursordist/docs/changelog/4.2.rst, pdns/recursordist/docs/changelog/4.3.rst, pdns/recursordist/docs/security-advisories/powerdns-advisory-2020-01.rst, pdns/recursordist/docs/security-advisories/powerdns-advisory-2020-02.rst, pdns/recursordist/docs/security-advisories/powerdns-advisory-2020-03.rst
=> rec: prep for May 2020 releases

pdns/auth-carbon.cc, pdns/dnsdist-carbon.cc, pdns/pdns_recursor.cc, pdns/rec-carbon.cc, pdns/recursordist/docs/settings.rst, pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc2.cc, pdns/recursordist/test-syncres_cc7.cc, pdns/rpzloader.cc, pdns/syncres.cc, pdns/syncres.hh, regression-tests.recursor-dnssec/test_RPZ.py
=> Recursor fixes May 2020

pdns/pdns_recursor.cc, pdns/rec-carbon.cc, pdns/recursordist/docs/settings.rst, pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc2.cc, pdns/recursordist/test-syncres_cc7.cc, pdns/rpzloader.cc, pdns/syncres.cc, pdns/syncres.hh, regression-tests.recursor-dnssec/test_RPZ.py
=> Recursor 4.3.x fixes May 2020

pdns/pdns_recursor.cc, pdns/rec-carbon.cc, pdns/recursordist/docs/settings.rst, pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc2.cc, pdns/recursordist/test-syncres_cc7.cc, pdns/rpzloader.cc, pdns/syncres.cc, pdns/syncres.hh, regression-tests.recursor-dnssec/test_RPZ.py
=> Recursor 4.2.x fixes May 2020

pdns/pdns_recursor.cc, pdns/rec-carbon.cc, pdns/recursordist/docs/settings.rst, pdns/recursordist/test-syncres_cc.cc, pdns/rpzloader.cc, pdns/syncres.cc, pdns/syncres.hh
=> Recursor 4.1.x fixes May 2020

pdns/recursordist/test-syncres_cc2.cc
=> fix formatting

.github/actions/spell-check/expect.txt, pdns/recursordist/docs/security-advisories/powerdns-advisory-2020-03.rst
Let's keep this open to fix all the spelling issues as well ;).
I have:
=> Fix LaTeX-pdns recursor docs

ext/yahttp/yahttp/reqresp.cpp
Backport of #8640 to be able to build with GCC 10.
(cherry picked from commit ffb885e)
I have:
=> rec-4.2.x: Fix build with gcc-10

pdns/recursordist/docs/security-advisories/powerdns-advisory-2020-02.rst
=> rec: powerdns-advisory-2020-002 -> powerdns-advisory-2020-02

docs/secpoll.zone
=> Prepare rec 4.1.16 secpoll update

pdns/dnspcap.cc
I sometimes capture traffic on lo(4) where my local test recursor is running. It would be nice to replay these captures. Currently link type LOOP is not supported.
I have:
=> Support LOOP link type in dnsreplay

docs/secpoll.zone
=> Secpoll cleanup, mark prereleases with vulnerabilities as such.

pdns/recursordist/docs/security-advisories/powerdns-advisory-2020-03.rst
=> rec: Typos and ref to rec instead of auth in security advisory

pdns/auth-carbon.cc, pdns/dnsdist-carbon.cc, pdns/misc.cc, pdns/misc.hh, pdns/rec-carbon.cc
=> rec-4.2.x: Fix compilation on systems that do not define HOST_NAME_MAX

pdns/recursordist/test-syncres_cc2.cc
(cherry picked from commit b963ef8b7568c55493f942d660d9a61103bfc04e)
I have:
=> rec-4.3.X: Fix formatting

build-scripts/travis.sh
(cherry picked from commit b5b83152b5a56b8095ab0d713a31c3ab5d1ec25b)
Backport of #9143.
I have:
=> rec-4.3.x: travis: install pdns package from direct download

.github/actions/spell-check/only.txt, build-scripts/travis.sh
Backport of #9130 and #9143.
I have:
=> rec-4.2.x: Unbreak travis and remove spell checking

.github/actions/spell-check/only.txt, build-scripts/travis.sh
Backport of #9130 and #9143.
I have:
=> rec-4.1.x: Unbreak travis and remove spell checking

.github/actions/spell-check/only.txt
(cherry picked from commit 16f3f8060ece690049dbf8059cf2f5a2bcc21bc2)
Backport of #9130.
I have:
=> auth-4.1.x: Suppress PR based spell check

.github/actions/spell-check/only.txt
Backport of #9130.
(cherry picked from commit 16f3f8060ece690049dbf8059cf2f5a2bcc21bc2)
I have:
=> auth-4.2.x: Suppress PR based spell check

.github/actions/spell-check/only.txt
(cherry picked from commit 16f3f8060ece690049dbf8059cf2f5a2bcc21bc2)
Backport of #9130.
I have:
=> auth-4.3.x: Suppress PR based spell check

pdns/recursordist/docs/settings.rst
=> Clarify docs

ext/yahttp/yahttp/reqresp.cpp, pdns/auth-carbon.cc, pdns/dnsdist-carbon.cc, pdns/misc.cc, pdns/misc.hh, pdns/rec-carbon.cc
Backport of #9127 + #8640.
I have:
=> rec-4.1.x: Fix compilation on systems that do not define HOST_NAME_MAX

pdns/rpzloader.cc, regression-tests.recursor-dnssec/test_RPZ.py
=> rec: Fix RPZ removals when an update has several deltas

pdns/pdns_recursor.cc
If the NOD lookup is slow, for example because the destination authoritative server is down, doing the NOD lookup before the response has been sent increases the latency a lot.
This commit moves the actual NOD lookup after the response has been sent, so we can still use the existing mthread (we might actually need to do a proper DNS resolution to find the target authoritative server) without keeping the client waiting.
Fixes #8836.
I have:
=> rec: Defer the NOD lookup until after the response has been sent

pdns/syncres.cc
Fixes the easy case of #9153. Longer chains with self-refs remain an issue.
I have:
=> rec: If a CNAME target is found in the cache, check if it's equal to qname and ServFail if so.

pdns/recursordist/test-syncres_cc6.cc, pdns/syncres.cc
=> rec: Fix the handling of DS queries for the root

modules/mydnsbackend/mydnsbackend.cc, modules/mydnsbackend/mydnsbackend.hh
Otherwise, the target database ends up with no SOA records for the migrated zones.
I have:
=> auth mydns: add SOA to list() output, fixes #9181

docs/changelog/4.2.rst
I somehow missed half of #8503 when writing the changelog.
I have:
=> auth: add #8497 to changelog

README.md
=> auth README: some fixes; remove manual doc build instructions

pdns/recursordist/docs/lua-scripting/hooks.rst
=> rec: Better document the gettag hook and its FFI counterpart

pdns/syncres.cc
Fixes #9193. Could use one unit test or two.
I have:
=> rec: Limit the TTL of RRSIG records as well

build-scripts/docker/generate-repo-files.sh
=> add master support to generate-repo-files.sh

pdns/ws-auth.cc, regression-tests.api/test_Zones.py
=> API: Allow rectifying Slave zones

pdns/Makefile.am, pdns/pdns.service.in
=> Set SyslogIdentifier for multiple instances

pdns/syncres.cc
=> rec: Don't copy the records when scanning for CNAME loops

pdns/recursordist/docs/index.rst, pdns/recursordist/docs/manpages/pdns_recursor.1.rst, pdns/recursordist/docs/metrics.rst, pdns/recursordist/docs/settings.rst, pdns/recursordist/docs/upgrade.rst
=> rec: fix doc generation warnings in recursor.

pdns/packethandler.cc
=>  auth-4.3.x: use real remote for supermaster createSlaveDomain()

.circleci/config.yml, docs/dnssec/pkcs11.rst, pdns/pdnsutil.cc, pdns/pkcs11signers.cc, regression-tests/start-test-stop
* ECDSA support
* tests upgraded to softhsm2
* tests enabled in CircleCI
TODO:
I have:
=> auth: PKCS11 improvements

docs/backends/bind.rst, docs/http-api/index.rst
=> auth doc nits

pdns/dnsdist-console.cc, pdns/dnsdistdist/dnsdist-kvs.cc, pdns/dnsdistdist/dnsdist-kvs.hh, pdns/dnsdistdist/dnsdist-lua-bindings-kvs.cc, pdns/dnsdistdist/docs/reference/kvs.rst, pdns/dnsdistdist/docs/rules-actions.rst, pdns/dnsdistdist/test-dnsdistkvs_cc.cc
=> dnsdist: Add optional masks to KeyValueLookupKeySourceIP

docs/dnsupdate.rst
Adding a link to dnsupdate page, section Update policy, to refer to the pdns wiki@github where I created a [dedicated page for Lua examples](https://github.com/PowerDNS/pdns/wiki/Lua-Examples-(Authoritative)), including an updatepolicy() example.
Addresses https://github.com/PowerDNS/pdns/issues/9234
I have:
=> auth: Link to pdns Wiki for updatescript examples

pdns/dnsdistdist/docs/guides/webserver.rst, pdns/dnsdistdist/docs/reference/config.rst
As suggested by @chbruyand during code review (thanks!).
I have:
=> dnsdist: Better examples for the webserver's ACL

pdns/recursordist/test-syncres_cc1.cc, pdns/syncres.cc
Backport #9194 #9202 #9216 
I have:
=> rec: backport 9194 and followup to rec 4.3.x: cname loop detection

pdns/pdnsutil.cc
`exit()` does not run destructors for all constructed objects, using `return` does allow that to happen.
I have:
=> pdnsutil: make sure we let all destructors run. Fixes #4973

pdns/rpzloader.cc, regression-tests.recursor-dnssec/test_RPZ.py
=> rec: backport 9172 to rec 4.3.x: Fix RPZ removals when an update has several deltas 

pdns/recursordist/test-syncres_cc6.cc, pdns/syncres.cc
=> rec: backport 9151 to rec 4.3.x: Fix the handling of DS queries for the root

pdns/portsmplexer.cc, pdns/test-dns_random_hh.cc
=> rec: backport 9031 to rec 4.3.x: Fix compilation of the ports event multiplexer

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Update the ChangeLog and the secpoll zone for 1.5.0-rc3

pdns/dnssecinfra.cc
=> Remove the thankfully not used anymore DEReater class

.github/ISSUE_TEMPLATE/config.yml
Maybe this will reduce the number of support tickets we get.
I have:
=> github issue chooser: add link to support page

.github/workflows/spelling.yml
Ideally this would enable the spell check action to report into pull requests (instead of just origin repositories on push).
I have:
---
This isn't tested. @Habbie and I are going to try it w/ pdns to see if it does something sane. If it doesn't, we'll go back to a drawing board.
=> spell-check: check pull requests

pdns/recursordist/docs/manpages/rec_control.1.rst
=> rec: zero means no timeout.

pdns/ws-recursor.cc, pdns/ws-recursor.hh, regression-tests.recursor-dnssec/test_API.py
=> rec: fix acl handling

pdns/sstuff.hh, pdns/webserver.cc, pdns/webserver.hh, pdns/ws-recursor.cc, pdns/ws-recursor.hh
=> rec: Backport of acl check to 4.1.x

pdns/ws-recursor.cc, pdns/ws-recursor.hh, regression-tests.recursor-dnssec/test_API.py
=> rec: acl backport to 4.2.x

pdns/ws-recursor.cc, pdns/ws-recursor.hh, regression-tests.recursor-dnssec/test_API.py
=> rec: Backport of acl fix to 4.3.x

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.1.rst, pdns/recursordist/docs/changelog/4.2.rst, pdns/recursordist/docs/changelog/4.3.rst, pdns/recursordist/docs/security-advisories/powerdns-advisory-2020-04.rst
=> rec: prep for 20200701 releases

pdns/pdns_recursor.cc
=> rec: common TCP write problems should only be logged if wanted.

pdns/recursordist/test-syncres_cc2.cc
=> rec: Kill an signed vs unsigned warning on OpenBSD

pdns/pdns_recursor.cc, pdns/syncres.cc
=> rec: use new operator to print states

pdns/pdns_recursor.cc
=> rec: backport of 9268 to 4.3.x: Better exception handling in houseKeeping / handlePolicyHit

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Update the ChangeLog and secpoll zone for 1.5.0-rc4

pdns/recursordist/test-syncres_cc9.cc, pdns/syncres.cc
<strike>Barely</strike> tested!
Needs <strike>unit tests,</strike> reviewer(s)..
I have:
=> rec: Refuse DS records received from child zones

pdns/backends/gsql/gsqlbackend.cc, pdns/packethandler.cc, pdns/ueberbackend.cc
There were some pointers reset using 0 instead of nullptr.
I have:
=> auth: 0 as nullptr cleanup

pdns/pdns_recursor.cc
=> rec: backport of 9268 to 4.2.x: Better exception handling in houseKeeping / handlePolicyHit

modules/bindbackend/bindbackend2.cc
The existing message was confusing me because it showed invalid/not
initialized data.
I have:
=> bindbackend: fix zoneId in log statement
