PowerDNS/pdns

pdns/dnsparser.cc

In some cases we could have called:
```
std::string::assign(InputIterator first, InputIterator last)
```
with last < first, which is UB:
> if the range specified by [first,last) is not valid, it causes undefined behavior
`libstdc++` handles that gracefully by throwing an out-of-range exception but `libc++` tries to allocate a negative value of bytes, which in turns triggers a request for a very large memory allocation, which fails.
This issue was triggered on `OSS-fuzz`.
I have:

Ensure a valid range to string::assign() in PacketReader::xfrBlob()

---

pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc

Use the exact same time everywhere so the tests don't fail if we switch to a different second since epoch in the middle of a test.
I have:

dnsdist: Remove a possible timing issue in the DynBlock unit tests

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

 auth: Prevent more than one CNAME/SOA record in the same RRset

---

regression-tests.api/test_cryptokeys.py

We used to request the creation of a 256-bit `RSA` key, which `OpenSSL` refuses from 1.1.1 onward. 1.1.0 used to accept everything larger than 16 bits (!) but in 1.1.1 512 (`RSA_MIN_MODULUS_BITS`) is the minimum.
We already changed this in master in https://github.com/PowerDNS/pdns/pull/6139, among other things.
I have:

auth-4.1.x: Use a realistic RSA key size for testing rsasha256 via the API

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

Backport of #7278 to rel/auth-4.1.x.
I have:

 auth-4.1.x: Prevent more than one CNAME/SOA record in the same RRset

---

docs/settings.rst

auth: Fix the default value of max-signature-cache-entries in the doc

---

pdns/pdns_recursor.cc

Reduce urgency of some log messages from `Error` to `Info` or `Warning`.
Fix  #2178 
I have:

rec: reduce log message urgency of non pertinent errors

---

docs/manpages/pdnsutil.1.rst
pdns/pdnsutil.cc

* generate-zone-key's default algorithm has changed to ECDSA256.
* Remove GOST from and add EdDSA to {add,generate}-zone-key usage messages.
* Remove an old comment.
I literally don't know C++, so writing this code was a bad idea, and not testing it was a worse one.
Adding the ifdefs introduces duplication but I don't know how to write it the right way.
I have:

pdnsutil documentation ECC algorithm updates

---

pdns/resolver.cc

In scalability tests I found the OS can run out of local ports making the call to bind() fail for the TCP socket we use to retrieve zones. If that happens we leak a filedescriptor.
I have:

prevent leak of file descriptor if running out of ports for incoming AXFR

---

builder-support/specs/pdns.spec

Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>
```
Distributor caught fatal exception: libmaxminddb support not compiled in
```

geoipbackend: Add libmaxminddb-devel dependency for CentOS

---

docs/backends/geoip.rst
modules/geoipbackend/geoipbackend.cc

In the case where the weight of all records is set to zero, former code was trying to compute probability by dividing by 0.
Another motivation to forbid the use of the "zero" weight is that the desired behavior was not clear.
This has been asked by @rgacogne in #7219 
I have:

auth: geoip - forbid 0 as weight value

---

build-scripts/travis.sh
pdns/recursordist/test-recursorcache_cc.cc
regression-tests.recursor/config.sh

Backport of #6458 to rel/-rec4.1.x.
(cherry picked from commit 97ab616efd0c8387978360a9eebb3a83f23fffe5)
I have:

rec-4.1.x: Enable the ghost tests again, add a corresponding unit test

---

configure.ac
pdns/Makefile.am

`dnsscope` requires Boost 1.48+ for its histogram feature, but the version check was relying on a automake variable that was not defined in `config.h` and thus the feature was never enabled.
I have:

dnsscope: Fix boost's version detection, build with histograms

---

docs/http-api/swagger/authoritative-api-swagger.yaml

Fix a number of simple syntactical errors in the Swagger spec.
I have:
While trying to use the Swagger definition file with the Python [bravado](https://github.com/Yelp/bravado) library I came across a number of simple-to-fix errors. This PR fixes them.

Fix a couple of Swagger / OpenAPI issues

---

pdns/nameserver.cc

This should aid in debugging when this happens. The error lies somewhere else in the code, knowing on which record this happen might help us find out where as we can use the record contents.
I have:

Improve error on sending non-TC response that should be TC

---

pdns/logger.cc
pdns/logger.hh

Use a template to log basic types

---

pdns/rec_channel.cc

Fixes #5745 without changing settings for all processes.
I have:

Rec: Set socket buf size for control socket.

---

build-scripts/UBSan.supp
build-scripts/travis.sh

We need a suppression because of a bug fixed in Boost 1.57.0, see:
https://github.com/boostorg/any/commit/c92ab03ab35775b6aab30f6cdc3d95b7dd8fc5c6
I have:

ixfrdist: Enable UndefinedBehaviorSanitizer in Travis CI

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst

This should prevent issues with networks that drop fragments, have
broken PMTU detection, etc.
This commit lowers both the udp-truncation-threshold (stub<->res) and
edns-outgoing-bufsize (rec<->auths).
I have:

rec: Lower default EDNS0 buffersizes to 1232 bytes

---

pdns/nameserver.cc

Previously we would only recognize 0.0.0.0 as 'any' and not 0.0.0.0:5300 or even 0.0.0.0:53.
I have:

Fix replying from ANY address for non-standard port

---

pdns/packethandler.cc

Under `--enable-verbose-logging`, this line would break on printing `QType::DS`. By simplifying the message, we avoid this problem.
I have:

simplify log message to avoid compile error

---

pdns/dnsrecords.hh
pdns/nsec3dig.cc
pdns/nsecrecords.cc
pdns/packethandler.cc
pdns/recursordist/test-syncres_cc.cc
pdns/slavecommunicator.cc
pdns/tcpreceiver.cc
pdns/test-dnsrecords_cc.cc
pdns/validate.cc

`NSEC` and `NSEC3` records content classes are currently storing the types they cover in a `std::set<uint16_t>`. While this is efficient for most cases because there are relatively few types covered, it uses a lot of memory for a very large number of types, up to ~3 MB.
This PR switches from a `std::set<uint16_t>` to a `std::bitset` once we reach 200 types, turning the memory usage to ~8k, which is roughly the size that the regular set uses for this number of elements.
I have:

Use a bitset for NSEC(3) records with lots of types

---

pdns/responsestats.cc

Although you might think otherwise, and I frequently do, atomic counters do not get zero-initialized.
With this PR, we do this by hand. This makes valgrind usable again on auth.
I have:

Zero out qtype response numbers in our statistics

---

configure.ac

While working on improving the configure code that handles mysql, we ran across this ghost
I have:

removing ghost

---

pdns/dnsdistdist/docs/quickstart.rst

added the +nocookie to the dig examples.
Reason, as you are setting up new software your mind is full, and who think of dig is sending DNS cookies? So for the quick copy/paste the cache test should also be possible with no errors.
I have:

add +nocookie to the dig examples

---

docs/manpages/pdnsutil.1.rst

Trying to remove some misunderstanding of how several masters are added by adding the "Master addressess is to be seperated by spaces" to avoid misunderstanding as noted in the IRC by me.
Reason
I understood that by this is MASTER OR [master in array]
Coz: Seen inconsistent to "@Habbie this is what unix commands are documented like
@Habbie  in every project
@Habbie over the last 30 years"
I have:

Remove some misunderstanding of adding several masters in slave zones

---

pdns/dnsdist-cache.hh
pdns/dnsdist-ecs.cc
pdns/dnsdist-ecs.hh
pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst
pdns/pdns_recursor.cc
pdns/rec-snmp.cc
pdns/rec_channel_rec.cc
pdns/recursordist/RECURSOR-MIB.txt
pdns/recursordist/docs/metrics.rst
pdns/syncres.hh
pdns/test-dnsdist_cc.cc
regression-tests.dnsdist/test_Caching.py

Rebase of #7035 + some additional fixes.
DO NOT MERGE - code works, but needs review
When recursor uses EDNS Client Subnet, a minority of domain names start getting variable answers depending on who is asking. The recursor cache is aware of how this works. However, when the recursor hides behind dnsdist, the dnsdist cache is not aware of which domains are variable or not.
With this PR, when the recursor is configured to 'use-incoming-edns-subnet', it will add a /0 ECS scope to responses that are not variable.
Meanwhile with this PR, dnsdist learns that /0 answers from backends are invariant, and uses these for anyone who asks, independent of source address. The details are described more fully in this gist: https://gist.github.com/ahupowerdns/cebbddb1cee967c4c6b31176c213dcb8
This code has …

Make recursor & dnsdist communicate (ECS) 'variable' status

---

pdns/logger.cc
pdns/logger.hh

This PR includes the commit from #6625, replaces #6639. I don't like the macro trick at all but I don't see any other way to make sure that the `Logger` object is correctly initialized before any use. 
I have:

logger: Use a function-level static var for the logger object

---

pdns/logger.cc
pdns/logger.hh

It might help with #6624, but feels cleaner to me anyhow.
I have:

logger: Use thread_local instead of pthread_getspecific()

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh

Related to #7234.
Only did a few quick tests, needs a lot more testing and regression tests.
We also need to investigate the:
```
!(wasForwardedOrAuthZone && ne->d_auth != authname)) { // Only the authname nameserver can neg cache entries
```
removal because as of now this code makes no sense to me.
I have:

rec: Fix DNSSEC validation with forward-zone-recurse

---

build-scripts/travis.sh

auth: Print the correct pdns.log when the py regression tests fail

---

pdns/filterpo.cc
pdns/filterpo.hh
pdns/lua-recursor4.cc
pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/recursordist/Makefile.am
pdns/recursordist/test-filterpo_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/rpzloader.cc
regression-tests.recursor-dnssec/test_RPZ.py

The RPZ specifications mandates that a zone can have more than one type present for local records, as a normal zone does, but before this pull request will only supported one.
Fixes #5657.
I have:

rec: Support several types for local RPZ records

---

regression-tests.auth-py/authtests.py
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_Advanced.py
regression-tests.dnsdist/test_Carbon.py
regression-tests.dnsdist/test_SelfAnsweredResponses.py
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_basicNSEC3.py

Improve test handling
I have:
* This makes the test output more consistent and thus makes it easier to figure out which test has a failure
* https://travis-ci.org/jsoref/pdns/jobs/476925140#L2811
```
ERROR
Dnstap: Send query packed in dnstap to a unix socket fstrmlogger server ... ok
Dnstap: Send query and responses packed in dnstap to a remotelogger server ... ok
DnstapExtra: Send query and responses packed in dnstap to a remotelogger server. Extra data is filled out. ... ok
Dyn Blocks (group) : Excluded from the dynamic block rules ... ok
...
XPF ... ok
======================================================================
ERROR: test suite for <class 'test_Dnstap.TestDnstapOverFrameStreamTcpLogger'>
----------------------------------------------------------------------
Traceback (most …
```

Tests output

---

pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc

Redo of https://github.com/PowerDNS/pdns/pull/6979.
These NS can't be authoritative since we have a CNAME answer for which only the record describing that alias is necessarily authoritative.
But if we allow the current auth, which might be serving the child zone, to raise the TTL of non-authoritative NS in the cache, they might be able to keep a "ghost" zone alive forever, even after the
delegation is gone from the parent.
So let's just do nothing with them, we can fetch them directly ifwe need them.
I have:

rec: Skip NS for the exact zone in CNAME answers

---

builder-support/dockerfiles/Dockerfile.authoritative
builder-support/dockerfiles/Dockerfile.dnsdist
builder-support/dockerfiles/Dockerfile.recursor
builder-support/dockerfiles/Dockerfile.target.amazon-2
builder-support/dockerfiles/Dockerfile.target.centos-6
builder-support/dockerfiles/Dockerfile.target.centos-7
builder-support/dockerfiles/Dockerfile.target.debian-jessie
builder-support/dockerfiles/Dockerfile.target.debian-stretch
builder-support/dockerfiles/Dockerfile.target.raspbian-jessie
builder-support/dockerfiles/Dockerfile.target.raspbian-stretch
builder-support/dockerfiles/Dockerfile.target.sdist
builder-support/dockerfiles/Dockerfile.target.ubuntu-bionic
builder-support/dockerfiles/Dockerfile.target.ubuntu-cosmic
builder-support/dockerfiles/Dockerfile.target.ubuntu-trusty
builder-support/dockerfiles/Dockerfile.target.ubuntu-xenial

Without this, `apt-get install` during builds might try to install packages that have been deleted from the archives, because the `apt-get update` layer was cached a month ago.
I have:

builder: add docker cache busting support

---

pdns/pdns_recursor.cc

When the recursor is configured to distribute incoming queries to its worker threads itself, and in the unlikely case that the pipe to the selected thread is full, randomly select another worker to
handle the query. If this one fails too, we give up.
I have:

rec: Try another worker before failing if the first pipe was full

---

docs/manpages/dnsscope.1.rst
pdns/dnsscope.cc

dnsscope miscounted its statistics, assigning '101 usec' to the <100 usec bin. Secondly, it neglected to process the last latency bin, causing it to spuriously report very late packets.
Add `-f,--filter-name` option to dnsscope to limit processing to queries within a certain domain
I have:

Dnsscope off-by-one + domain-filter

---

m4/pdns_with_mysql.m4

closes #5140
Detect `--without-mysql` and suggest `--with-modules="bind random" --with-dyn-modules="pipe"`
I have:
fwiw, this isn't my preference, I'd rather we just remove `gmysql` from `modules` when someone uses `--without-mysql`, but...
```sh
$ ./configure --without-mysql --with-libcrypto=/usr/local/opt/openssl 2>&1|tail -5
checking for arc4random... yes
checking whether to enable verbose logging... no
checking whether to enable PKCS11 support... no
checking whether to enable experimental GSS-TSIG support... no
configure: error: instead of --without-mysql try --with-modules="bind random" --with-dyn-modules="pipe"
```

Tell people to use --with-modules=... when they use --without-mysql

---

pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst

In some setups it might make sense to wait until 2 or 3 checks have succeeded before starting to use a backend, because we care about stability more than we want the backend to get back up fast.
This PR adds a new optional `rise` parameter to `newServer()`, specifying how many health checks must be successful before the backend is marked as up.
Closes #7237.
I have:

dnsdist: Add a 'rise' parameter to 'newServer()'

---

pdns/dnsdist-cache.cc
pdns/dnsdist-cache.hh
pdns/dnsdist-console.cc
pdns/dnsdist-lua-bindings.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/guides/cache.rst
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/test_Caching.py

This new option prevents expired entries from being expunged from the packet cache associated to a pool if all the backends in this pool are down, so we can keep serving stale data until at least one backend gets available again. 
Closes #7239.
I have:

dnsdist: Add a 'keepStaleData' option to the packet cache

---

pdns/common_startup.cc

This commit ensures `pdns_server` does not start when there is a
misconfiguration in default-[kz]sk-algorithm:
* Either is set to an unknown algorithm
* When using RSA, key size is unset
* zsk is set but ksk is not
* zsk is not set to the same as the ksk
I have:

auth: error on DNSSEC default misconfiguration

---

pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/docs/reference/dq.rst
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_Trailing.py

Expose data following a DNS message to Lua for both reading and writing.
Fixes #6846.
Incorporates #6897 ([diff from that base](https://github.com/gibson042/pdns/compare/2018-08-trailing-data-tests...2018-08-trailing-data)).
I have:

dnsdist: Expose trailing data

---

pdns/Makefile.am
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdist-protobuf.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/uuid-utils.cc
pdns/dnsdistdist/uuid-utils.hh
pdns/dnspcap2protobuf.cc
pdns/lwres.cc
pdns/pdns_recursor.cc
pdns/protobuf.hh
pdns/recursordist/Makefile.am
pdns/recursordist/uuid-utils.cc
pdns/recursordist/uuid-utils.hh
pdns/syncres.hh
pdns/uuid-utils.cc
pdns/uuid-utils.hh

Without this fix, compiling against boost 1.69.0 results in a lot of occurrences of the following warning:
```
In file included from /usr/include/boost/random/detail/integer_log2.hpp:19,
from /usr/include/boost/random/detail/large_arithmetic.hpp:19,
from /usr/include/boost/random/detail/const_mod.hpp:23,
from /usr/include/boost/random/detail/seed_impl.hpp:26,
from /usr/include/boost/random/mersenne_twister.hpp:30,
from /usr/include/boost/uuid/random_generator.hpp:17,
from /usr/include/boost/uuid/uuid_generators.hpp:17,
from protobuf.hh:34,
from protobuf.cc:4:
/usr/include/boost/pending/integer_log2.hpp:7:59: note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.
BOOST_HEADER_DEPRECATED("<boost/integer/integer_log2.hpp>");
```
A fix has been merged …

Move UUID generators to a common function, fix boost 1.69.0 warning

---

pdns/pdns_recursor.cc

6c4d0ab4cdb2fc73e73faba31fd8c3fe909e250a introduced a call to the Lua `ipfilter` hook that required access to the DNS header, but the corresponding variable was only declared when `protobuf` support had been enabled.
I have:

rec-4.1.x: Fix compilation in handleRunningTCPQuestion without protobuf support

---

pdns/rcpgenerator.cc

In ff7ac440afdae4370e12a1b9eb21d4b1389a861f we added trimming of whitespace,
so you could turn " 1.2.3.4 " into an A record 0x01020304. This commit made us more flexible
but also six times slower in some microbenchmarks.
This commit restores the old performance which shaves double digits percentages of time from many
benchmarks in 'speedtest', while making "make-a record" six times faster again.
I have:

Be smarter about trimming whitespace when creating records from ASCII

---

docs/changelog/4.0.rst

closes #7384
EPOCH was never supposed to be deprecated, and it is not going away. This PR removes that mention from the 4.0 changelog as it confused people.
I have:

fix 4.0 changelog that wrongly said SOA-EDIT=EPOCH was deprecated

---

pdns/dnsdist-lua-rules.cc

This makes `mvRule(0,x)` work where x is the highest rule number.
Maybe we want a test for this?
I have:

fix off-by-one in mvRule counting

---

pdns/lua-record.cc

Before:
```
Jan 25 12:53:43 Lua record reported: Exception thrown by a callback function called by Lua
```
After:
```
Jan 25 19:42:24 Lua record reported: Exception thrown by a callback function called by Lua: Unable to convert presentation address '10.0.0.0/8'
```
Ideally this would also return a backtrace, but this is a start.
I have:

LUA: report nested exception

---

pdns/namespaces.hh
pdns/rec-lua-conf.cc
pdns/remote_logger.cc
pdns/remote_logger.hh
regression-tests.recursor-dnssec/.gitignore
regression-tests.recursor-dnssec/requirements.txt
regression-tests.recursor-dnssec/runtests
regression-tests.recursor-dnssec/test_Protobuf.py

This is mostly a backport of #7428 to rel/rec-4.1.x, but it also backports some protobuf regression tests as well.
I have:

rec-4.1.x: Reduce systemcall usage in protobuf logging

---

pdns/dnsdist-lua-bindings.cc
pdns/namespaces.hh
pdns/pdns_recursor.cc
pdns/remote_logger.cc
pdns/remote_logger.hh

Since Spectre/Meltdown, system calls have become more expensive.  In
addition, relevant versions of glibc turn out to implement pthread_cond_wait
and pthread_cond_signal in such a way that they use multiple system calls always.
There is an optimization in glibc to improve this but it is disabled.
This new setup changes our protobuf logging so it amortizes system calls so we perform
far less than one call per message.
Note that our previous RemoteLogger was configured in terms of how many
*messages* it would buffer. Our new code is configured in terms of how many
*bytes*. I have multiplied the configured numbers by 100 elsewhere (recursor
config, dnsdist config) to sort of maintain parity.
In addition, the old RemoteLogger would buffer messages while there was no
connection available. We …

Reduce systemcall usage in protobuf logging

---

pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/recursordist/docs/lua-config/protobuf.rst
regression-tests.recursor-dnssec/test_Protobuf.py

rec-4.1.x: Add an option to export only responses over protobuf

---

pdns/dnsdistdist/docs/rules-actions.rst

dnsdist version 1.4.0 is not released yet
I have:

[dnsdist] Fix wrong version numbering of new features

---

build-scripts/travis.sh
regression-tests/backends/gsql-common
regression-tests/backends/ldap-master
regression-tests/start-test-stop

This introduces some local caching, and, I hope, a bit of retrying on ALIAS lookups, because we don't do that internally.
I considered hardcoding the google-public-dns-a.google.com./8.8.8.8 record we use for testing, but I'd like to see if just adding dnsmasq as a layer improves the situation without hardcoding anything. If it turns out we do need to add that static record, it will be just one extra item around line 336 of `build-scripts/travis.sh` at that time.
I have:

travis auth: install dnsmasq, configure it on 127.0.0.53

---

pdns/iputils.hh
pdns/nameserver.cc

Fix unaligned access, spotted on OpenBSD/sparc. Together with a compiler fix
make auth work on OpenBSD/sparc. See https://github.com/PowerDNS/pdns/issues/6742
I have:

Avoid unaligned access, it hurts on e.g. sparc64

---

docs/settings.rst

The default webserver port is 8081, not 8001. This is correct in other parts of the documentation but not on the settings page.
I have:

Fix default webserver port in documentation

---

build-scripts/changelog-from-pr.py

It's not very pretty but I'm not going to spend more time on it today.
`git blame ./build-scripts/changelog-from-pr.py` > reviewers
Possible improvements:
- merge `if access_token …` occurences back into one assignment
- `var.get(attribute, None)` → `var.get(attribute)` ?

Hack in support for GitHub access tokens.

---

pdns/dnsdistdist/docs/reference/config.rst

Updated the documentation of includeDirectory to reflect the fact that only .conf files will be loaded from the target directory.
I have:

Clarify documentation to reflect actual behavior of includeDirectory

---

pdns/pdnsutil.cc

Fixes the compiler warning mentioned in #7465 
I have:

pdnsutil: fix signed/unsigned comparison, closes #7465

---

pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/config.rst

Add option 'checkInterval' for newServer() to set the interval between
health checks.
I have:
- [yes] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [yes] compiled this code
- [yes] tested this code
- [yes] included documentation (including possible behaviour changes)
- [yes] documented the code
- [no] added or modified regression test(s)
- [no] added or modified unit test(s)
Hi,
this is a small patch to allow users to set the interval between health checks for each server.
Did a quick test on my setup which worked as expected.
I hope I did not forget any documentation?
Best regards

dnsdist: Add option to set interval between health checks

---

pdns/ws-auth.cc
regression-tests.api/requirements.txt
regression-tests.api/test_Zones.py

* Refuse to load RRset arrays that contain more than one of CNAME or DNAME.
* Expand refusal to load CNAMEs to pre-existing RRsets also to DNAMEs, and vice versa.
* Refuse to load zones given in BIND format for the same reasons.
* Apply hostname correctness check also to BIND format zones.
Also tidies up the zone tests a tiny bit.
I have:

Auth. API: improve RRset validation

---

regression-tests/backends/lmdb-master

After another ALIAS-related Travis failure, I discovered that LMDB testing still used 8.8.8.8.
I have:

also use dnsmasq during lmdb testing

---

builder-support/debian/authoritative/debian-jessie/control
builder-support/debian/authoritative/debian-stretch/control
builder-support/debian/dnsdist/debian-jessie/control
builder-support/debian/dnsdist/debian-stretch/control
builder-support/debian/recursor/debian-jessie/control
builder-support/debian/recursor/debian-stretch/control
builder-support/specs/dnsdist.spec
builder-support/specs/pdns.spec

Otherwise the detection of systemd's sandboxing features does not work properly, since it uses `systemctl` to determine the version of systemd.
A better option might be to use `pkg-config --modversion systemd` to retrieve the version but that's a fix for a later time.
I have:

Make sure that the systemd binaries are available during the build

---

pdns/pdnsutil.cc

pdnsutil add-record outputs TTL in wrong order when printing the new rrset. This moves TTL before IN like it should be.
Also there was unnecessary whitespace at the end of the line which was removed.
I have:

pdnsutil: Fix output order of pdnsutil add-record

---

pdns/dnsdistdist/configure.ac

This shaves a yak that @Habbie had. No longer check for OpenSSL or gnutls when DoT is disabled. This PR also does not show the detection of TLS libraries anymore when DoT is not enabled.
I have:

dnsdist: don't test or show unneeded TLS libs

---

pdns/ws-auth.cc

Fixes #6451. To be consistent with other places and documentation, separate multiple masters by comma and avoid the trailing space.
I have:

store masters with comma separated and without trailing space

---

pdns/recursordist/docs/lua-scripting/dq.rst

Document the more generic addRecord that addAnswer uses.
This lets you place data at different places, eg, additional section.
I have:

rec: Document addRecord

---

pdns/filterpo.cc
pdns/filterpo.hh
pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/recursordist/docs/lua-config/rpz.rst
pdns/rpzloader.cc
pdns/rpzloader.hh
regression-tests.recursor-dnssec/test_RPZ.py

Also be a bit more permissive when we do override them, because it might turn several `A` or `AAAA` records into several `CNAME`s which would trigger an error.
Fixes https://github.com/PowerDNS/pdns/issues/7452.
I have:

rec: Add an option to not override custom RPZ types with the default policy

---

pdns/pdns_recursor.cc
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/docs/settings.rst
pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/basicDNSSEC.py
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_Flags.py
regression-tests.recursor-dnssec/test_TTL.py

Since 4.1.0, the DNSSEC validation state of records is stored along with them so that we only need to validate once. This PR adds a new 'max-cache-bogus-ttl' option to cap the TTL of a record that has been validated as `Bogus` in the query cache, so we don't keep it around for days if the initial TTL is high.
Closes #7445.
This PR still needs a bit of testing, as well as regression tests.
I have:

rec: Add a new 'max-cache-bogus-ttl' option

---

pdns/ixfr.cc
pdns/test-ixfr_cc.cc
regression-tests.recursor-dnssec/requirements.txt
regression-tests.recursor-dnssec/test_RPZ.py

Backport of #7494 to rel/rec-4.1.x.
I have:

rec-4.1.x: Correctly interpret an empty AXFR response to an IXFR query

---

pdns/ixfr.cc
pdns/test-ixfr_cc.cc
regression-tests.recursor-dnssec/test_RPZ.py

If the remote server answered with an empty AXFR response to a RPZ IXFR query, the recursor incorrectly parsed this answer as an empty IXFR, instead of removing all records except the SOA from the zone.
It looks like the authoritative server is affected as well when slaving a, IXFR-enabled zone.
I have:

Correctly interpret an empty AXFR response to an IXFR query

---

docs/lua-records/functions.rst
pdns/lua-record.cc
pdns/minicurl.cc
pdns/minicurl.hh

This PR adds the "useragent" option to the `ifurlup` function for LUA records. By default, it sets the User-Agent to "PowerDNS Authoritative Server/$VERSION":
```
GET / HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: PowerDNS Authoritative Server/0.0.16019.0.LUArecorduseragent.g63dfa8dfc7.dirty
Accept: */*
```
Closes #7393 
I have:

LUA records: Add "useragent" option to `ifurlup` and set a default

---

docs/changelog/4.2.rst
docs/http-api/statistics.rst
docs/http-api/swagger/authoritative-api-swagger.yaml
pdns/responsestats-auth.cc
pdns/responsestats.cc
pdns/responsestats.hh
pdns/ws-api.cc
regression-tests.api/test_Servers.py

- Add new statistic variable about rcode responses
- Add metrics about RCode on statistics API entrypoint
- Rename queries-by-qtype as response-by-qtype on API stats because it's calculated on response side
Following Issue #7357, new statistic counter about rcode responses, published on the API on statistics entrypoint
Point to discuss : Name of variables.
On /statistics entrypoint, I've renamed queries-by-qtype as response-by-qtype, and named my new variable as response-by-rcode, because all of the work is made on responsestats.cc before sending the response. It's confusing to call the metrics as « queries » because it supposes that the metrics is measured when the querie cames and not before sending the response.
I have:

Add Rcode response statistics on API

---

pdns/common_startup.cc
pdns/dnsdist-snmp.cc
pdns/dnsdist-web.cc
pdns/dnsdist.hh
pdns/dnsdistdist/DNSDIST-MIB.txt
pdns/misc.cc
pdns/misc.hh
pdns/rec-snmp.cc
pdns/rec_channel_rec.cc
pdns/recursordist/RECURSOR-MIB.txt
regression-tests.nobackend/counters/command

Use a less expensive way to get memory stats for rel-memory-usage. You can ask for the old way by explicitly asking for special-memory-usage.
Also, implement a getrusage() based getRealMemUsage() for non-Linux systems.
I have:

Change the way getRealMemUsage() works on Linux (using statm)

---

docs/http-api/swagger/authoritative-api-swagger.yaml
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

This pull request adds a 'type' argument to the data-search api. Using this argument you can filter the api results on type, which can be 'all', 'zone', 'record' or 'comment'.
This PR fixes issue #5430 and is a rework of code provided by @mimianddaniel 
I have:

Add type filter to search-data api. Closes #5430

---

pdns/recursordist/docs/lua-config/protobuf.rst

The formatting of https://doc.powerdns.com/recursor/lua-config/protobuf.html is wrong for the `servers` parameter. This is an attempt to fix that.
I have:

If a type is complex, you need to specify a separate type: clause.

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsdistdist/docs/reference/dnsnameset.rst
pdns/dnsdistdist/docs/rules-actions.rst
pdns/dnsname.hh

Set of DNSName based on std::set.
Query rule for test if set contains qname.
I have:

DNSNameSet and QNameSetRule

---

pdns/dnssecinfra.cc

Before: `Error: Invalid DNS Private Key in file 'zsk-private_file.txt`
After: `Error: Invalid DNS Private Key in file 'zsk-private_file.txt' (n does not equal p q)`
I have:

report checkKey errors upwards in makeFromISCFile exception

---

docs/backends/geoip.rst
modules/geoipbackend/geoipbackend.cc
modules/geoipbackend/regression-tests/mixed-weight-resolution/command
modules/geoipbackend/regression-tests/mixed-weight-resolution/description
modules/geoipbackend/regression-tests/mixed-weight-resolution/expected_result
regression-tests/backends/geoip-master

Computes the record weight/probability per QType and adapt the code to avoid empty answer in a mixed-weighted-Qtype situation.
Closes #7051.
I have:

auth: geoip - Fix static lookup when using weighted records on multiple record types

---

pdns/misc.cc
pdns/misc.hh
pdns/pdns_recursor.cc

See https://sourceware.org/bugzilla/show_bug.cgi?id=24047
On Linux, by default only some icmp errors received are propagated upward.
By setting the right socket option, more icmp errors are reported as failed recv calls with the proper errno set. Specifcally host unreachable and net unreachable are interesting.
This has the effect that in the cases where such an icmp message is received, we actively abort the receive and continue with alternatives, instead of needing to wait for a timeout.
I have:

Set IP(V6)_RECVERR socket option to get notified of more than just port unreachable errors on Linux.

---

pdns/pdnsutil.cc

Fixes small typo in pdnsutil check-zone where one error was prepended by [error], while all others are prepended by [Error].
I have:

Make pdnsutil check-zone more consistent: An error is [Error]. Not [error].

---

docs/settings.rst

#6845 removed support for api-readonly, but only documented that for the recursor

Document the removal of api-readonly for the pdns-auth as well

---

pdns/recursordist/docs/lua-scripting/hooks.rst
pdns/recursordist/docs/metrics.rst

I was confused to see the MIB in the Lua docs, where, at best, one needs to know the trap OID.
I have:

move MIB from Lua docs to metrics docs

---

docs/http-api/swagger/authoritative-api-swagger.yaml

Fix a small discrepancy between the swagger spec and the actual code concerning the tsig zone properties
I have:

Use the correct property names for the tsig values in a zone object

---

docs/settings.rst
pdns/recursordist/docs/settings.rst

Currently the documentation does not mention that a user can specify multiple carbon-servers to send metrics to. This pull request adds information about this to the docs. 
I have:

Added documentation for configuring more than one carbon-server

---

pdns/dnsdistdist/docs/guides/dynblocks.rst

The correct syntax for setQueryRate is:
```
:setQueryRate(rate, seconds, reason, blockingTime[, action[, warningRate]])
```
The guide forgot to include the "action" parameter in the warningRate example. Note that because the actions are integers, this was valid LUA. It even worked, but the rule wouldn't show up in showDynBlocks()

Fix error in setQueryRate warning example

---

modules/remotebackend/httpconnector.cc
modules/remotebackend/pipeconnector.cc
modules/remotebackend/remotebackend.cc
modules/remotebackend/remotebackend.hh
modules/remotebackend/zmqconnector.cc

Fixes #7573 - caused by poorly escaped parameters.
I have:

remotebackend: http connector - Properly escape parameters

---

pdns/dnsscope.cc

Before:
```
CXX      dnsscope.o
dnsscope.cc:128:32: error: non-constant-expression cannot be narrowed from type 'uint32_t' (aka 'unsigned int') to '__darwin_suseconds_t' (aka 'int') in initializer list [-Wc++11-narrowing]
struct timeval a{lhs.tv_sec, lhs.tv_usec}, b{rhs.tv_sec, rhs.tv_usec};
^~~~~~~~~~~
dnsscope.cc:128:32: note: insert an explicit cast to silence this issue
struct timeval a{lhs.tv_sec, lhs.tv_usec}, b{rhs.tv_sec, rhs.tv_usec};
^~~~~~~~~~~
static_cast<__darwin_suseconds_t>( )
dnsscope.cc:128:60: error: non-constant-expression cannot be narrowed from type 'uint32_t' (aka 'unsigned int') to '__darwin_suseconds_t' (aka 'int') in initializer list [-Wc++11-narrowing]
struct timeval a{lhs.tv_sec, lhs.tv_usec}, b{rhs.tv_sec, rhs.tv_usec};
^~~~~~~~~~~
dnsscope.cc:128:60: note: …
```

cast usec, avoids a build failure on macOS/Darwin

---

build-scripts/travis.sh

We are hitting the Travis 50min limit often. This switches of a few tests while still keeping coverage.
I have:

Eliminate a few test because travis

---

pdns/lua-recursor4.cc

`getregisteredname` function was accidentically dropped in 4b9a4e966257eb08d4803633f5726b5a144a8e99 without adding it in a3e7b73528a96a3642adb42dc1e729ea2e8765f4
I have:

lua-recursor4: Add missing getregisteredname Lua function

---

pdns/dnsdistdist/tcpiohandler.cc

We didn't properly handle some cases where GnuTLS returns `GNUTLS_E_AGAIN`, dropping the connection instead.
I have:

dnsdist: Handle EAGAIN in the GnuTLS DNS over TLS provider

---

pdns/dnsdist-cache.cc
pdns/dnsdist-cache.hh
pdns/dnsdistdist/test-dnsdistrules_cc.cc
pdns/test-dnsdistpacketcache_cc.cc

If the host running the unit tests is very, very slow, some entries could previously have expired before the end of the tests and were not accounted for.
This PR tries to make sure that the entries last long enough, or at least account for expired entries if they don't.
Hopefully fixes #7590.
I have:

dnsdist: Prevent entries from expiring if the unit tests are slow

---

docs/common/api/endpoint-statistics.rst
docs/http-api/swagger/authoritative-api-swagger.yaml
pdns/pdns_recursor.cc
pdns/rec-carbon.cc
pdns/rec-snmp.cc
pdns/rec-snmp.hh
pdns/rec_channel.hh
pdns/rec_channel_rec.cc
pdns/recursordist/docs/metrics.rst
pdns/recursordist/docs/settings.rst
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/ws-api.cc
pdns/ws-api.hh
pdns/ws-auth.cc
pdns/ws-recursor.cc
regression-tests.api/test_Servers.py

This PR:
- adds statistics about ECS response sizes in the recursor, closing #7498 ;
- adds an API endpoint to request a specific statistic only, in the recursor and the auth, even if it is otherwise excluded from the list of all statistics ;
- disable the polling of expensive statistics (cache-bytes, packetcache-bytes) via SNMP by default ;
- make the list of metrics that are excluded from either the list of all statistics (API, rec-control) or completely (Carbon, SNMP) configurable per retrieval method.
I have:

Add rec statistics about ECS response sizes, API endpoint to get a specific stat

---

pdns/dnsdistdist/docs/advanced/tuning.rst

It was correct in the config reference, but not in the tuning guide. The lowercase version just gets ignored by dnsdist, possibly leading the admin to believe that reuseport does not work on their system.
I have:

properly capitalise reusePort

---

configure.ac
pdns/dnsdistdist/configure.ac
pdns/recursordist/configure.ac

We used to clobber C{,XX}FLAGS when those were set via the env, leading to the loss of e.g. `-O2` when set like this.
This PR ensures we append the C{,XX}FLAGS from the environment to our defaults
I have:

Don't clobber C{,XX}FLAGS when set in env

---

pdns/dbdnsseckeeper.cc

auth: Rectify for ent records in narrow zones was slightly wrong.

---

modules/gmysqlbackend/gmysqlbackend.cc
modules/gmysqlbackend/smysql.cc
modules/gmysqlbackend/smysql.hh

Whenever a thread uses MySQL, make sure to call `mysql_thread_end()` when the thread terminates.
~NOTE: not PRed to master yet.~ #7517 
I have:

plug mysql_thread_init memory leak, fixes #6231

---

modules/randombackend/randombackend.cc
pdns/Makefile.am
pdns/calidns.cc
pdns/common_startup.cc
pdns/ixfrdist.cc
pdns/lua-record.cc
pdns/notify.cc
pdns/pdns_recursor.cc
pdns/pdnsutil.cc
pdns/test-recpacketcache_cc.cc
pdns/unix_utility.cc
pdns/utility.hh

Eliminate rand() and srand() usage. These are really bad random generators and should not be used. Leaving usage of random() alone.
I have:

Utility::random() and srandom() is not used anymore.

---

pdns/test-packetcache_cc.cc

We used to do a retrieval from the cache to compute the hash, but that could have failed due to another thread already having the relevant lock ("deferred-lookup"), resulting the hash value not being updated.
I have:

auth: Avoid contention issues in the packet cache's unit tests

---

pdns/Makefile.am
pdns/common_startup.cc
pdns/packethandler.cc
pdns/responsestats-auth.cc
pdns/speedtest.cc
pdns/statbag.cc
pdns/statbag.hh
pdns/ws-auth.cc

When we previously summarised a ringbuffer we would do so case sensitively. In addition, packetcached delegations were put in the rings for queries for domains we are not auth for.
I have:

Auth ringbuffer simmaries were case sensitive & accounted delegations incorrectly

---

pdns/backends/gsql/gsqlbackend.cc

Backport of #7546.
(cherry picked from commit b7309408d65edc2365392bb4c24f7a39696a880b)

[backport to auth-4.1.x] gsqlbackend: Reset correct query in searchComments

---

pdns/resolver.cc

Backport of #7294.
(cherry picked from commit f852aff670c19b7dac9a0cef2c3912ebd8946201)

[backport to auth-4.1.x] prevent leak of file descriptor if running out of ports for incoming AXFR

---

pdns/backends/gsql/gsqlbackend.cc

Backport of #7496 to rel/auth-4.1.x.
(cherry picked from commit a6037f784da39d9cd784226fcc1a278383eb99a1)
I have:

[backport to auth-4.1.x] Catch exception when parsing a zone's SOA in getUnfreshSlaveInfos()

---

pdns/dnsrecords.cc

Backport of #7459.
(cherry picked from commit 0583946ff70d73b5da579db1d81c9c374adf2cc3)

[backport to auth-4.1.x] fix dot stripping in setContent()

---

pdns/dnswriter.cc

Backport of #7472.
(cherry picked from commit 2d6c4fcb18ec7ae1ef689656ce6d52b399cc26a9)

[backport to auth-4.1.x] Do not compress the root

---

pdns/dbdnsseckeeper.cc

Backport of #7580.
(Cherrypicked from:
- 666c721173d00d55953b86941099874867bae2c3
- 2885750af64e945ba475fd02f7f3cd5194052202 )

[backport to auth-4.1.x] Rectify for ent records in narrow zones was slightly wrong

---

pdns/nameserver.cc

Previously, we would not recognize 0.0.0.0:5300 or even 0.0.0.0:53 as the 'any' address, leading us to answer from the wrong address.
Backport of #7341.
(cherry picked from commit 36025a51ed16e31e5d186b2c126ef1178a39a569)

[backport to auth-4.1.x] Fix replying from ANY address for non-standard port

---

pdns/ixfr.cc
pdns/test-ixfr_cc.cc

Backport of #7494 to rel/auth-4.1.x
(cherry picked from commit 98b3317609b2783d1bfd5da99edc81af28f4e1d6)
I have:

[backport to auth-4.1.x] Correctly interpret an empty AXFR response to an IXFR query

---

docs/changelog/4.1.rst
docs/secpoll.zone

Most of these also appear in the 4.2.x changelogs.
I guess #7567 doesn't necessarily need to be in here, but it's a fun entry.

Update changelog and secpoll for auth-4.1.8

---

pdns/recursordist/README.md

Update PowerDNS Recursor `README.md` to note that Lua is required.
Trying to run `./configure` for the PowerDNS Recursor fails with a message saying that this is not possible. 
Indeed it is:
https://github.com/PowerDNS/pdns/blob/master/pdns/recursordist/configure.ac#L104
This updates the documentation to reflect this sad reality. 😉
I have:

Note that Lua is now required for the recursor

---

pdns/dnsdistdist/docs/reference/constants.rst

The C code uses `QClass`, but the Lua variable was added as `DNSClass` for whatever reason.
Documentation should use the Lua name, not the C name.
I have:

Lua QClass global does not exist

---

pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/docs/metrics.rst
pdns/syncres.hh

Adds a CPU millisecond use metric per thread that we have pipes to. 
I have:

This provides CPU usage statistics per thread (worker & distributor).

---

pdns/mtasker.cc
pdns/mtasker.hh
pdns/pdns_recursor.cc
pdns/rec-snmp.cc
pdns/rec_channel_rec.cc
pdns/recursordist/docs/metrics.rst
pdns/recursordist/docs/settings.rst
pdns/syncres.hh

Backport of https://github.com/PowerDNS/pdns/pull/7507 to rel/rec-4.1.x without exporting the new metric over SNMP, otherwise the OID would change between 4.1.x and master.
I have:

rec-4.1.x: Use a bounded load-balancing algo to distribute queries

---

pdns/mtasker.cc
pdns/mtasker.hh
pdns/pdns_recursor.cc
pdns/rec-snmp.cc
pdns/rec_channel_rec.cc
pdns/recursordist/RECURSOR-MIB.txt
pdns/recursordist/docs/metrics.rst
pdns/recursordist/docs/settings.rst
pdns/syncres.hh

If `pdns-distributes-queries` is set and this setting is set to another value than 0, the distributor thread will use a bounded load-balancing algorithm while distributing queries to worker threads, making sure that no thread is assigned more queries than distribution-load-factor times the average number of queries currently processed by all the workers.
For example, with a value of 1.25, no server should get more than 125 % of the average load. This helps making sure that all the workers have roughly the same share of queries, even if the incoming traffic is very skewed, with a majority of requests asking for the same qname.
I have:

rec: Use a bounded load-balancing algo to distribute queries

---

pdns/pdns_recursor.cc
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/docs/settings.rst
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh

This is further work based on https://github.com/PowerDNS/pdns/pull/7572
It introduces a new parameter to control caching of ECS specific answers: ecs-cache-limit-ttl
Ineffective by default. If set, an ECS specific answer must have a TTL >= the given limit to be cached.
I have:

Rec ecs cache limit with ttl

---

pdns/dnsdist-cache.cc
regression-tests.dnsdist/test_Caching.py

 dnsdist: Prevent 0-TTL cache hits

---

pdns/dnsdist-dynblocks.hh
pdns/dnsdist-lua-inspection.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/configure.ac
pdns/dnsdistdist/dnsdist-lua-inspection-ffi.cc
pdns/dnsdistdist/dnsdist-lua-inspection-ffi.hh
pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc
pdns/statnode.hh

This PR:
- adds the equivalent of `addDynBlockSMT()` to `dynBlockRulesGroup`, so we can unify all rules with the new syntax ;
- adds a `FFI` interface for the visitor function, which is roughly 5 times faster than the non-`FFI` one.
Fixes #7139.
I have:

dnsdist: Add addDynBlockSMT() support to dynBlockRulesGroup

---

pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/statistics.rst
regression-tests.dnsdist/test_API.py

Adds new global "frontend" stats for noerror, nxdomain and servfail answers sent to clients (like in the recursor).
If using cache in dnsdist you otherwise lose visibility of the types of answers sent from there.
Stat names are up for discussion, the term frontend seems to be used elsewhere as well. Perhaps servfail-responses and responses should be renamed to backend-* ?
I have:

dnsdist: add frontend response statistics

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdistdist/docs/reference/dq.rst
pdns/lua-recursor4.cc
regression-tests.dnsdist/test_EDNSOptions.py

Doc fix; Lua tables fix (may need upgrade notes?).
I have:

dnsdist, recursor: EDNSOptionView improvements

---

README.md

The information about the dnsdist README location was wrong. This fixes that, and also makes the information about that and the PowerDNS Recursor Markdown relative links, so they are nice and pretty when viewed on GitHub.
I have:

Correct dnsdist & recursor information in README

---

pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/docs/settings.rst

The switch is named disable-real-memory-usage
https://github.com/PowerDNS/pdns/issues/7661
I have:

Disable smap switch

---

pdns/recursordist/Makefile.am

uuid-utils was conditional on protobuf use, but we now use it for webserver logging, which means all builds need it.
This fixes our el6 build, which does not have protobuf.
I have:

always link in uuid-utils because webserver logging needs it now

---

docs/backends/generic-mysql.rst

https://github.com/PowerDNS/pdns/issues/7680
I have:

Fix 7680: gmysql-thread-cleanup option documented incorrectly

---

regression-tests.dnsdist/requirements.txt

This fixes dnsdist regress test framework on OpenBSD.
I have:

OpenBSD only has protoc 3.x; tell python to install the proper runtime.

---

pdns/dnsdist.cc
pdns/iputils.cc
pdns/kqueuemplexer.cc
regression-tests.dnsdist/dnsdisttests.py

- Fix a typo that prevented the kqueue multiplexer from compiling
- Fix an issue with self-answered queries and non-harvested source IPs
- Disable Nagle's algorithm (via `TCP_NODELAY`) in the regression tests
I have:

dnsdist: Fix compilation and tests on FreeBSD

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_CacheHitResponses.py
regression-tests.dnsdist/test_Caching.py
regression-tests.dnsdist/test_DNSCrypt.py
regression-tests.dnsdist/test_TCPKeepAlive.py

Get rid of the endless list of parameters, and use a table instead.
I have:

dnsdist: Switch to the new 'newPacketCache()' syntax for 1.4.0

---

modules/lmdbbackend/lmdbbackend.cc

lmdb setMaster defaulted to a master on port 0, which was not  helpful. Default is now 53.
I have:

LMDB defaulted to port 0 for master addresses unless explicitly set

---

pdns/backends/gsql/gsqlbackend.cc

As noted in #7705, gsql getAllDomainMetadata() did not return all domain
metadata.  This function would always filter DNSSEC related metadata, even
if a backend was configured to support DNSSEC.
I have:

No longer filter DNSSEC metadata when DNSSEC is enabled in gsql

---

pdns/dnsdist-lua-vars.cc
pdns/dnsdistdist/docs/advanced/axfr.rst
pdns/dnsdistdist/docs/guides/cache.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/constants.rst
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test-include-dir/test.conf
regression-tests.dnsdist/test_Advanced.py
regression-tests.dnsdist/test_Basics.py
regression-tests.dnsdist/test_Caching.py
regression-tests.dnsdist/test_CheckConfig.py
regression-tests.dnsdist/test_Dnstap.py
regression-tests.dnsdist/test_DynBlocks.py
regression-tests.dnsdist/test_EDNSSelfGenerated.py
regression-tests.dnsdist/test_HealthChecks.py
regression-tests.dnsdist/test_Protobuf.py
regression-tests.dnsdist/test_RecordsCount.py
regression-tests.dnsdist/test_Responses.py
regression-tests.dnsdist/test_TCPKeepAlive.py
regression-tests.dnsdist/test_TeeAction.py

Redo of #5669. Separate PR because the rebase involved some manual work (some code got removed, moved around, etc. since), and this way we can compare the two PRs to make sure I did not miss anything.
~TODO: add the deprecation warnings as discussed in #5669.~ Pushed.
I have:

dnsdist: Move constants to proper namespace

---

pdns/dnsdist-lua.cc
pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/tcpiohandler.hh

Store frontends as `ClientState`s right away instead of hard to read tuples, and share the same code for UDP, TCP, DNSCrypt and DNS over TLS binds.  
I have:

dnsdist: Unify the management of DNS/DNSCrypt/DoT frontends

---

pdns/dnsdistdist/tcpiohandler.cc

Before, we would log the fact that we could not set the ciphers for
gnutls but still start. When a connection came in, dnsdist would crash.
I have:

dnsdist: exit when setting ciphers fails (GNUTLS)

---

modules/lmdbbackend/lmdb-safe.hh
modules/lmdbbackend/lmdbbackend.cc

Use boost::string_view only from Boost 1.61 and later, fall back to string_ref otherwise. 
I have:

Boost string_view only appeared in Boost 1.61, not 1.54 as we were assuming

---

modules/lmdbbackend/lmdb-safe.cc
modules/lmdbbackend/lmdbbackend.cc

On 32 bit systems, there is almost no room for large mmaps. This PR changes the default for 32 bit systems. The lmdb map size should be configurable but it is very late in the 4.2 release time to do a good job there as we'd need to thread that all through lmdb-safe etc. 
I have:

Reduce mmap size for lmdb on 32 bits plus restrict number of shards

---

docs/requirements.txt
pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

Our custom Lua modules gives errors otherwise.
I have:

Require sphinx < 2.0

---

pdns/Makefile.am
pdns/iputils.hh
pdns/speedtest.cc

No tricks with the alignment of the union, just do a explicit memcpy.
https://github.com/PowerDNS/pdns/issues/7688
I have:

Alternative solution to the unaligned accesses. 

---

pdns/test-distributor_hh.cc

Also, explictly set arguments to avoid order dependencies and make it possible
to run single tests.
I have:

Use a smaller test size to not fill the pipe buffer on systems with small buffer

---

pdns/dnsdistdist/test-delaypipe_hh.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/testrunner.cc
pdns/test-distributor_hh.cc
pdns/test-dnsrecordcontent.cc
pdns/test-dnsrecords_cc.cc
pdns/test-packetcache_cc.cc
pdns/testrunner.cc

To make it possible to run individual unit test they should not depend on each other.
This makes sure all tests setup globals properly. Additionally, the testrunners of auth and rec call `reportAllTypes()` in init code since a lot of tests need that and a large set did not call it but depended silently on other tests to do it for them.
`./testrunner --random` now works all the time for all subprojects as well.
I have:

Fix unittest order deps

---

pdns/pdnsutil.cc

Previously, backends would mostly accept feedRecords() outside of the context of a transaction. No such luck for lmdb. Fixing this is a massive slowdown for b2b-migrate if your backend is actually doing transactions.  On the other hand, we just don't generally support this anymore. 
I have:

b2b-migrate did not open a transaction, breaking it for lmdb

---

pdns/pdns_recursor.cc

Before:
```
Apr 16 08:59:51 stats: 19 questions, 294 cache entries, 8 negative entries, 52% cache hits
Apr 16 08:59:51 stats: throttle map: 2, ns speeds: 111
Apr 16 08:59:51 stats: outpacket/query ratio 375%, 0% throttled, 0 no-delegation drops
Apr 16 08:59:51 stats: 2 outgoing tcp connections, 0 queries running, 2 outgoing timeouts
Apr 16 08:59:51 stats: 19 packet cache entries, 0% packet cache hits
Apr 16 08:59:51 Thread 0 has been distributed 7 queries
Apr 16 08:59:51 Thread 1 has been distributed 12 queries
Apr 16 08:59:51 stats: 0 qps (average over 12316 seconds)
```
After:
```
Apr 16 09:47:57 stats: 203 questions, 193 cache entries, 1 negative entries, 99% cache hits
Apr 16 09:47:57 stats: throttle map: 0, ns speeds: 86
Apr 16 09:47:57 stats: outpacket/query ratio 19%, 0% throttled, …
```

fix formatting for thread distribution stats message

---

builder-support/debian/dnsdist/debian-jessie/rules
builder-support/debian/dnsdist/debian-stretch/rules
builder-support/debian/dnsdist/ubuntu-trusty/rules
builder-support/specs/dnsdist.spec
builder-support/specs/pdns-recursor.spec
builder-support/specs/pdns.spec

~WIP while this passes through the builder, so we can clean up the inevitable failures resulting from this.~ done
* [auth](https://builder.powerdns.com/#/buildrequests/114646?redirect_to_build=true)
* [dnsdist](https://builder.powerdns.com/#/buildrequests/114647?redirect_to_build=true)
* [rec](https://builder.powerdns.com/#/buildrequests/114648?redirect_to_build=true)
Rebased after #7671:
* [auth](https://builder.powerdns.com/#/buildrequests/115095?redirect_to_build=true) - succes
* [dnsdist](https://builder.powerdns.com/#/buildrequests/115096?redirect_to_build=true) - success
* [rec](https://builder.powerdns.com/#/buildrequests/115097?redirect_to_build=true) - el6, el7: `configure: error: unrecognized options: --with-netsnmp` (fix pushed, [rebuilding] …

set --enable-option-checking=fatal on all package builds, enable SNMP in RPMs

---

pdns/pdns_recursor.cc

The `s_running` guard was only set to `false` for the handler thread and remained `true` after the first run for all the others.
I have:

rec: Fix the cache cleaning code being only run once for workers

---

modules/remotebackend/test-remotebackend.cc
modules/remotebackend/unittest.rb

Otherwise check-zone and NS-queries fail.
Noticed while verifying a remotebackend patch in Debian against 4.1.5. Not tested on master.
I have:

remotebackend: fix SOA in unittests

---

pdns/dnsdist.cc
pdns/iputils.cc
pdns/iputils.hh
pdns/nameserver.cc
pdns/pdns_recursor.cc

It might help prevent Path MTU poisoning attacks.
Untested, don't merge it yet!
I have:

Ignore Path MTU Discovery on UDP server socket

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst

Using `SO_TIMESTAMP` when available, so we can really compute the latency from the moment the datagram was actually received by the kernel instead of the moment we started processing it.
I have:

rec: Add 'protobuf-use-kernel-timestamp' for sharper latencies

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdistdist/docs/reference/config.rst

maxEntries is already a mandatory parameter for `newPacketCache`.
I have:

dnsdist: remove maxEntries from newPacketCache opts

---

regression-tests/.gitignore
regression-tests/tests/00dnssec-grabkeys/command

This generates two files that can then be used like `-lua-config-file=../../regression-tests/recursor.trustedkeys.lua --forward-zones-file=../../regression-tests/recursor.forward-zones-file` on the Recursor.
I have:

auth: export TAs and forward zones for rec testing with auth zones

---

pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/configure.ac

This fixes linking against a custom libcrypto, and building with no TLS and no HTTPS.
I have:

refactor tls/https lib handling to cover all option combinations

---

pdns/misc.cc
pdns/misc.hh
pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst

Allows setting the size in bytes of the internal buffer of the pipe used by the distributor to pass incoming queries to a worker thread.
Requires support for `F_SETPIPE_SZ` which is present in Linux since 2.6.35. The actual size might be rounded up to a multiple of a page size. 0 means that the OS default size is used.
A large buffer might allow the recursor to deal with very short-lived load spikes during which a worker thread gets overloaded, but it will be at the cost of an increased latency.
I have:

rec: Add a distribution-pipe-buffer-size setting

---

pdns/cachecleaner.hh
pdns/dbdnsseckeeper.cc
pdns/recursordist/negcache.cc
pdns/recursordist/test-negcache_cc.cc

Otherwise they might get expunged very quickly while they just have been inserted.
Similar to https://github.com/PowerDNS/pdns/pull/3451, which fixed this issue for the positive caches.
I have:

rec: Move replaced negcache entries to the back of the expunge queue

---

regression-tests.dnsdist/README
regression-tests.dnsdist/runtests

This makes `regression-tests.dnsdist/runtests` give forceful guidance about curl on macOS.
I have:

pycurl settings for darwin/brew

---

docs/guides/basic-database.rst
modules/gmysqlbackend/enable-foreign-keys.mysql.sql

The "easy install" guide includes the SQL schema for a MySQL backend, but fails to point out that that schema is for the 4.2/master releases. As the latest "stable" is 4.1.x, this confuses users.
I've also included the SQL for the constraints, as those are important enough to have new people load as a default. As they are following the getting-started guide, they are using InnoDB, and start with an empty DB, so there shouldn't be any problems adding the constraints.
I have:

Clarify the "easy setup guide": schema listed is for 4.2/master only

---

pdns/communicator.hh
pdns/mastercommunicator.cc
pdns/tcpreceiver.cc

Fix https://github.com/PowerDNS/pdns/issues/7646. 
It might not be the right place, though, but it prevents fatal exception on
unparseable A (or AAAA) addresss for nameserver addresses needed
to send notifies.
I have:

Do not exit on exception resolving addresses to notify

---

pdns/dnswasher.cc

Fixes this clang warning:
```
/usr/include/c++/v1/memory:2321:5: warning: delete called on 'IPObfuscator' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
delete __ptr;
^
/usr/include/c++/v1/memory:2634:7: note: in instantiation of member function 'std::__1::default_delete<IPObfuscator>::operator()' requested here
__ptr_.second()(__tmp);
^
/usr/include/c++/v1/memory:2588:19: note: in instantiation of member function 'std::__1::unique_ptr<IPObfuscator, std::__1::default_delete<IPObfuscator> >::reset' requested here
~unique_ptr() { reset(); }
^
dnswasher.cc:74:12: note: in instantiation of member function 'std::__1::unique_ptr<IPObfuscator, std::__1::default_delete<IPObfuscator> >::~unique_ptr' requested here
return std::unique_ptr<IPObfuscator>(new …
```

Fix a delete call on abstract class without virtual dt clang warning.

---

docs/backends/geoip.rst

closes https://github.com/PowerDNS/pdns/issues/7752
document pdns_control re-opens databases on reload
I have:

pdns_control reopens geoip databases on reload

---

docs/manpages/pdnsutil.1.rst

[[ Reopen of #7648 which got deleted because $reasons ]]
delete-rrset and replace-rrset was missing from the pdnsutil manpage / docs website
I have:

Add documentation for pdnsutil delete-rrset and replace-rrset

---

pdns/packethandler.cc
regression-tests.rootzone/tests/axfr/expected_result
regression-tests.rootzone/tests/axfr/expected_result.dnssec
regression-tests.rootzone/tests/axfr/expected_result.nsec3
regression-tests.rootzone/tests/axfr/expected_result.nsec3-optout
regression-tests.rootzone/tests/ds-at-ent-from-glue/command
regression-tests.rootzone/tests/ds-at-ent-from-glue/description
regression-tests.rootzone/tests/ds-at-ent-from-glue/expected_result
regression-tests.rootzone/tests/ds-at-ent-from-glue/expected_result.dnssec
regression-tests.rootzone/tests/ds-at-ent/command
regression-tests.rootzone/tests/ds-at-ent/description
regression-tests.rootzone/tests/ds-at-ent/expected_result
regression-tests.rootzone/tests/ds-at-ent/expected_result.dnssec
regression-tests.rootzone/tests/ds-at-glue/command
regression-tests.rootzone/tests/ds-at-glue/description
regression-tests.rootzone/tests/ds-at-glue/expected_result
regression-tests.rootzone/tests/ds-at-glue/expected_result.dnssec
regression-tests.rootzone/zones/ROOT

Glue and ents derived from glue did confuse the DS referral logic.
Fixes: #7625
I have:

auth: fix referral response for DS queries

---

pdns/backends/gsql/gsqlbackend.cc
pdns/pdnsutil.cc
pdns/ws-auth.cc

This improves the error reporting when running in `slave` mode, as well as via `pdnsutil` and the API.
Before, we should silently ignore slave zones with broken IPs in 'master'. Now we report on this:
```
Mar 12 16:25:55 Could not parse master address (foo) for zone 'example.com': Unable to convert presentation address 'foo'
Mar 12 16:25:55 No masters for slave zone 'example.com' found in the database
Mar 12 16:25:55 No new unfresh slave domains, 0 queued for AXFR already, 0 in progress
```
```
$ pdnsutil check-zone example.com
[Error] non-IP address for masters: Unable to convert presentation address 'foo'
[Error] No SOA record present, or active, in zone 'example.com'
Checked 0 records of 'example.com', 2 errors, 0 warnings.
```
I have:

Improve error reporting with garbage in the 'master' field of the database

---

pdns/packethandler.cc
pdns/packethandler.hh
regression-tests.rootzone/tests/direct-ds/command
regression-tests.rootzone/tests/direct-ds/description
regression-tests.rootzone/tests/direct-ds/expected_result
regression-tests.rootzone/tests/direct-ds/expected_result.dnssec
regression-tests.rootzone/tests/direct-ns/command
regression-tests.rootzone/tests/direct-ns/expected_result
regression-tests.rootzone/tests/direct-ns/expected_result.dnssec
regression-tests.rootzone/tests/ref-3ld/command
regression-tests.rootzone/tests/ref-3ld/expected_result
regression-tests.rootzone/tests/ref-3ld/expected_result.dnssec

PowerDNS auth was wasting a lot of resources doing dnssec preparations for non dnssec zones. 
I have:

disable dnssec pre-processing for non dnssec zones and avoid a lot of isSecuredZone() calls

---

builder-support/debian/recursor/ubuntu-trusty/control
builder-support/debian/recursor/ubuntu-trusty/rules

That package does not exist on Trusty
I have:

pkgs: don't depend on dns-root-data on Trusty

---

builder-support/dockerfiles/Dockerfile.rpmbuild

This change makes us ship *.src.rpm files as well. This will allow anyone to rebuild easily on RPM-based systems. A src RPM contains the exact specfile and tarball used to build the RPM packages.
I have:

ship SRPM files as well

---

pdns/dnsdistdist/doh.cc
regression-tests.dnsdist/test_DOH.py

Otherwise we might try to read an uninitialized value in the destructor if the parsing fails.
Hopefully fixes #7810.
I have:

dnsdist: Don't let 'self' dangling while parsing the request's qname

---

pdns/dnsrecords.cc

This RR type is missing a data field.
draft-reid-dnsext-rkey-00 defines the data as flags (0) / protocol (1) / algorithm / key, and for these last two is refering to RFC4034
https://tools.ietf.org/html/draft-reid-dnsext-rkey-00
https://tools.ietf.org/html/rfc4034#section-2.1
I have:

RKEY is missing algorithm field

---

docs/common/api/zone.rst
docs/http-api/swagger/authoritative-api-swagger.yaml
pdns/ws-auth.cc

In #4656 there was some agreement to drop set-ptr, this is the first step.
I have:

API: Mark set-ptr as deprecated

---

pdns/dnsparser.cc

This PR is quite similar to #7272.
In some cases we might have called:
```
string::string(InputIt first, InputIt last)
```
with last < first, which is invalid.
`libstdc++` handles that gracefully by throwing an out-of-range exception but `libc++` tries to allocate a negative value of bytes, which in turns triggers a request for a very large memory allocation, which fails.
This issue was triggered on `OSS-fuzz`.
I have:

Ensure a valid range to string() in PacketReader::getUnquotedText()

---

m4/pdns_with_net_snmp.m4

As discussed in https://github.com/PowerDNS/pdns/issues/7762, this seems to keep the environment cleaner.
I have:

SNMP: Use net-snmp-config --netsnmp-agent-libs instead of --agent-libs

---

m4/pdns_with_net_snmp.m4

We did not properly check whether `snmp_select_info2()` was available, resulting in this function not being used even when supported.
I have:

Fix the detection of snmp_select_info2()

---

modules/lmdbbackend/lmdbbackend.cc

Fix auth=1 bug and avoid the "Parsed and original record content are not equal:" warnings in pdnsutil check-zone
I have:

auth: lmdbbackend: auth was unset in get() (always true)

---

regression-tests.auth-py/authtests.py
regression-tests.auth-py/test_ALIAS.py
regression-tests.auth-py/test_LuaRecords.py

This will make it easier in the future to write tests needing different configurations.
I have:

Refactor auth-py tests so config templates can be used

---

pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/iputils.cc
pdns/iputils.hh
pdns/tcpiohandler.hh

Fix some minor issues reported by Coverity:
- one useless test due to the condition being always true ;
- uncaught exception if we ever try to get the handle of a non-established TCP connection which should never happen.
Also remove some code that has been unused since we moved to an event-based logic.
I have:

 dnsdist: Fix minor issues reported by Coverity

---

pdns/dnsdist-lua-vars.cc

The second incomplete copy was the one being used in practice, making `EDNSOptionCode.KEYTAG` invisible because it only existed in the first copy of the table.
I have:

remove second, incomplete copy of Lua EDNSOptionCode table

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/docs/rules-actions.rst
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/m4/pdns_check_libh2o_evloop.m4
pdns/dnsdistdist/tcpiohandler.cc
pdns/tcpiohandler.hh
regression-tests.dnsdist/configCA.conf
regression-tests.dnsdist/configServer.conf
regression-tests.dnsdist/runtests
regression-tests.dnsdist/test_TLS.py

Support for DoT should work with any version of OpenSSL or GnuTLS but for DoH it requires the addition of `h2o_socket_get_ssl_server_name()` in `libh2o` (PR in preparation). It's already possible to do HTTP Host header matching for DoH, though.
Closes #7210.
I have:

 dnsdist: Implement SNIRule for DoT and DoH

---

pdns/dnsdist-lua-actions.cc

I noticed that there were both `string` and `std::string` in the file that I am working on. This converts them all to `std::string`.
No issues, just some code hygiene improvement by making the style consistent. 
I have:

Change all occurrences of string to std::string

---

pdns/syncres.cc

Before:
```
May 22 15:48:06 [1] tipsport.cz: Trying IP 90.183.101.40:53, asking 'tipsport.cz|NS'
May 22 15:48:06 [1] tipsport.cz: using TCP with 90.183.101.40:53
```
leading to the question 'why is it using TCP?'
After:
```
May 22 15:48:06 [1] tipsport.cz: Trying IP 90.183.101.40:53, asking 'tipsport.cz|NS'
May 22 15:48:06 [1] tipsport.cz: truncated bit set, over UDP
May 22 15:48:06 [1] tipsport.cz: using TCP with 90.183.101.40:53
```
I have:

recursor: log UDP TC bits during trace

---

builder-support/dockerfiles/Dockerfile.target.sdist

Otherwise, passing something like `-m auth` will cause very confusing errors.
I have:

builder: error out when no valid modules are specified

---

modules/gmysqlbackend/gmysqlbackend.cc
modules/godbcbackend/godbcbackend.cc
modules/gpgsqlbackend/gpgsqlbackend.cc
modules/gsqlite3backend/gsqlite3backend.cc
pdns/backends/gsql/gsqlbackend.cc

The query is optimized for the existing schemas. If you join on records.domain_id = domains.id it is possible to speed-up things a little bit more, but this requires an index change. I'm not sure this is worth the trouble and the possible slowdown when this index is missing.
Test with 750K zones
Before:
```
Feb 07 09:27:03 getUpdatedMasters(): 87087980 usec to execute
Feb 07 09:27:03 750000 domains for which we are master need notifications
```
After:
```
Feb 07 09:30:43 getUpdatedMasters(): 7002059 usec to execute.
Feb 07 09:30:43 750000 domains for which we are master need notifications
```
I have:

auth: speedup getUpdatedMasters() for the gsql backends

---

pdns/dnsdistdist/docs/reference/config.rst

`mustResolve` requires a response's rcode to be different from `NXDomain`, `Refused` and `ServFail`, while the default is behavior accepts everything except `ServFail`.
Fixes #7848.
I have:

dnsdist: Fix the documentation of the 'mustResolve' parameter

---

m4/pdns_check_os.m4

Will fail otherwise with linking errors.
https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/dnsdist/compile.txt
Assuming it disappears:
```
CXXLD    dnsdist
libtool: warning: library '/var/lib/buildbot/slaves/weimar/arc_arc700/build/sdk/staging_dir/toolchain-arc_arc700_gcc-8.3.0_uClibc/lib/libstdc++.la' was moved.
libtool: warning: library '/var/lib/buildbot/slaves/weimar/arc_arc700/build/sdk/staging_dir/toolchain-arc_arc700_gcc-8.3.0_uClibc/lib/libstdc++.la' was moved.
/var/lib/buildbot/slaves/weimar/arc_arc700/build/sdk/staging_dir/toolchain-arc_arc700_gcc-8.3.0_uClibc/bin/../lib/gcc/arc-openwrt-linux-uclibc/8.3.0/../../../../arc-openwrt-linux-uclibc/bin/ld: dnsdist.o: undefined reference to symbol '__atomic_fetch_sub_8@@LIBATOMIC_1.0' …
```

Add latomic to ARC platform

---

pdns/dnsdistdist/tcpiohandler.cc

dnsdist: Add missing overrides for ::getServerNameIndication()

---

pdns/lwres.cc
pdns/pdns_recursor.cc
pdns/syncres.cc
pdns/syncres.hh

We are mostly focused on the performance of the 'fast' path, when the query can be served from the packet cache, and we had some low-hanging inefficiencies in the 'regular' path:
- `SyncRes::shuffleInSpeedOrder()` was very inefficient, doing several copies of `DNSName` objects including one in a map. The new version does only one copy, computes the needed speeds directly there and returns it ;
- We used `dns_random()` when shuffling `NS` records, and their corresponding `A` and `AAAA` entries. These operations really doesn't require a CSPRNG and `dns_random()` is much slower than the default randomness source used in C++11 ;
- The `UDPClientSocks` class was keeping every file descriptor it allocated in a set, checking that returned FDs belonged to that set before removing them from the FD …

rec: Small speedups in the recursion 'slow' path

---

pdns/recursordist/html/index.html
pdns/recursordist/html/local.js
pdns/webserver.cc
pdns/webserver.hh
pdns/ws-recursor.cc
regression-tests.api/runtests.py
regression-tests.api/test_Basics.py
regression-tests.api/test_Servers.py
regression-tests.api/test_helper.py
regression-tests.dnsdist/test_API.py

Removes need for API key on builtin webserver pages.
Fixes #5942.
I have:

Recursor: allow basic auth for some statistics APIs

---

.circleci/config.yml

We have not been running coverity for some time due to changes in the build infrastructure. This PR re-enables coverity by running it in circleci once per day, on the master branch.
Note that the PowerDNS organization in circleci needs to create 3 environments (dnsdist-coverity, auth-coverity and recursor-coverity) with 3 environment variables:
* `COVERITY_EMAIL`: the email address for build submission
* `COVERITY_TOKEN`: the token for the project
* `COVERITY_PROJECT`: The exact name of the project in coverity
I have:

Do coverity builds once a day via circleci

---

pdns/dnsdistdist/libssl.cc

Will not compile without deprecated APIs enabled.
Tested with released version of PowerDNS

Don't initialize and deinitialize with OpenSSL >= 1.1

---

pdns/dnsdistdist/docs/rules-actions.rst

I wasn't sure whether or not `PoolAvailableRule` was a rule or not and if it was how to use it. I've moved the rule to the rules section and added a example use case.
I have:

dnsdist: Move PoolAvailableRule to rules section

---

pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/statistics.rst
regression-tests.dnsdist/test_API.py

This PR adds support for Prometheus latency histograms as described in: https://prometheus.io/docs/concepts/metric_types/#histogram
It adds 3 metrics, `latency_sum`, `latency_count` and `latency_bucket`. The `latency_bucket` metrics have a `le` label which has the `lower and equal to` latency of the request in ms.
This resolves #6088 for dnsdist.
Example graph:
I have:

dnsdist: Support Prometheus latency histograms

---

pdns/minicurl.cc
pdns/minicurl.hh
pdns/receiver.cc

If `curl_global_init()` was not called prior to any call to `curl_easy_init()`, it will be automatically called.
The documentation states that:
> This may be lethal in multi-threaded cases, since
> curl_global_init is not thread-safe, and it may result in
> resource problems because there is no corresponding cleanup.
I have witnessed several crashes related to `libcurl` on Travis and I believe this might be the root cause of these failures.
I have:

auth: Initialize cURL before starting any thread

---

docs/settings.rst
pdns/common_startup.cc
pdns/common_startup.hh
pdns/receiver.cc

Also turns the TCPNameserver into a shared_ptr instead of a naked pointer.
I have:

auth: Remove disable-tcp option

---

m4/pdns_check_os.m4

ARM XScale, ARM 926EJ-S, and ARM FA526
Logs: https://downloads.openwrt.org/snapshots/faillogs/arm_arm926ej-s/packages/dnsdist/compile.txt
https://downloads.openwrt.org/snapshots/faillogs/arm_fa526/packages/dnsdist/compile.txt
https://downloads.openwrt.org/snapshots/faillogs/arm_xscale/packages/dnsdist/compile.txt

Check if -latomic is needed instead of hardcoding

---

.gitignore
docs/backends/bind.rst
docs/backends/generic-sqlite3.rst
docs/upgrading.rst
modules/bindbackend/bindbackend2.cc
modules/bindbackend/binddnssec.cc
modules/gsqlite3backend/gsqlite3backend.cc
pdns/pdnsutil.cc
pdns/ssqlite3.cc
pdns/ssqlite3.hh

WAL enables tremendous concurrency and avoids a lot of locking problems. It is a good default.
Fixes #7251 
I have:

sqlite3: make journal mode configurable; default to WAL

---

pdns/common_startup.cc
pdns/common_startup.hh
pdns/lua-record.cc

Nonscientific measurements:
* 60kqps from a plain A records
* 5kqps from `LUA A "'192.0.2.1'"`
* 35kqps from that same LUA with this patch and `enable-lua-records=shared`
Needs docs, maybe a test?
We could (presumably) win even more if we avoided doing 22 `writeFunction` calls for each LUA query still, but because of the captured variables, fixing that is not trivial. ~(After I just talked to @ahupowerdns  I'd like to try anyway)~ we'll try that for 4.3
I have:

auth LUA: optionally reuse Lua state

---

pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/recursordist/docs/lua-config/protobuf.rst

Currently code forces a string that can be converted to a ComboAddress: a IPv4 or IPv6 address:port. But we want unix domain sockets (a path) in the typical case. The farsight "collector" expects that.
I have:

Allow unix domains sockets for dnstap destinations

---

docs/backends/generic-mysql.rst
docs/backends/generic-sqlite3.rst
docs/backends/geoip.rst
docs/backends/index.rst
docs/backends/lmdb.rst
docs/manpages/sdig.1.rst
docs/modes-of-operation.rst
pdns/sdig.cc

* auth: sdig manpage: fix formatting; update with new features
* auth: sdig usage: sort options
* auth docs: fix link to supermaster/superslave setting
* auth docs: add lmdb backend to backends index
* auth docs: fix underline lengths
I have:

auth: some doc nits/updates

---

m4/pdns_enable_tools.m4
m4/pdns_with_lua_records.m4

The autotools changes in #7832 broke `build.sh sdist`, because it puts an `AM_CONDITIONAL` inside an `AS_IF` conditional.
I have:

auth: make configure call PDNS_CHECK_LIBCURL when needed 

---

builder-support/gen-version

As Debian broke our 0.0.0 with a 'Breaks' in libstdc++, we now use the
last released version number (when building a single product) so users
can keep installing packages built from master on Debian.
Closes #7781
Note that the build-infra might need some work too.
I have:

Use latest tag for version numbers for master builds

---

modules/lmdbbackend/lmdbbackend.cc

The LMDB backend has an option to pick the LMDB synchronisation mode. To pick lmdb synchronous mode (its default), you had to set `lmdb-syncmode=` which was weird. With this PR you can now do `lmdb-syncmode=sync` to achieve the same thing. 
I have:

Make explicit lmdbbackend synchronous option

---

pdns/lua-record.cc

See #7896 for the problem description.
I have:

auth LUA: explicitly unset ecswho if we are not setting it, fixes #7896

---

pdns/backends/gsql/gsqlbackend.cc
pdns/pdnsutil.cc
pdns/ssqlite3.cc
pdns/ws-auth.cc

We do deletes+inserts outside of transactions. This makes it possible to briefly observe NXDOMAIN while replacing RRsets. With this PR, most operations are correctly wrapped in transactions.
I have:

auth API, pdnsutil: improve backend transaction correctness 

---

pdns/communicator.hh
pdns/mastercommunicator.cc
pdns/tcpreceiver.cc

Backport of https://github.com/PowerDNS/pdns/pull/7662
I have:
- [X read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document

auth 4.1.x: backport 7662 Do not exit on exception resolving addresses to notify

---

pdns/pdns_recursor.cc
pdns/rec-snmp.cc
pdns/rec_channel_rec.cc
pdns/recursordist/RECURSOR-MIB.txt
pdns/recursordist/docs/metrics.rst
pdns/syncres.hh

(cherry picked from commit 88c33dca92f68d3c4a0a9dc8cb3c9838f034b94b)
Would it be an issue that the snmp objects IDs are no longer contiguous?
I have:
- [X  checked that this code was merged to master

rec backport to 4.1.x: Add counters for incoming AD and CD queries

---

pdns/syncres.cc

We don't care about the actual ordering, so let's do the cheapest comparisons first then the quite expensive `DNSName` comparison only if we really need to.
I have:

rec: Compare the CacheKey type and place first then the name

---

pdns/dnsdist-lua-bindings.cc

Prints out the already tracked number of records expunged by expungeByName. Helps to see if the expunge "hit" its intended target.
```
> getPool(""):getCache():expungeByName(newDNSName("powerdns.com"), DNSQType.ANY, true)
Expunged 5 records
> getPool(""):getCache():expungeByName(newDNSName("powerdns.com"), DNSQType.ANY, true)
Expunged 0 records
>
```
I have:

dnsdist: print stats from expungeByName

---

pdns/dnsdist-lua.cc

We used to log to the console but happily start, and running `--check` would report no error (because it simulates `client` mode, see https://github.com/PowerDNS/pdns/pull/7181).
I have:

dnsdist: Exit when requested DoT/DoH support is not compiled in

---

pdns/backends/gsql/gsqlbackend.cc

As noted in #7705, gsql getAllDomainMetadata() did not return all domain
metadata.  This function would always filter DNSSEC related metadata, even
if a backend was configured to support DNSSEC.
Backport of #7706 
(cherry picked from commit d97e1ae1430a1e66893e8156bdf1c7232d3d0331)
I have:

backport: No longer filter DNSSEC metadata when DNSSEC is enabled in gsql

---

pdns/lwres.cc
pdns/protobuf.cc
pdns/protobuf.hh

Allocating memory for the ProtoBuf objects an their fields is costly, as is converting the qname and potential UUID to strings, for example.
I have:

rec: Reuse the outgoing query protobuf for the incoming response

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/dnscrypt.rst

As not doing DNS over TCP is just dumb :). Docs say 1.4.0, but we could skip till 1.5.0.
I have:

dnsdist: disallow TCP disablement

---

pdns/filterpo.cc
pdns/filterpo.hh
pdns/recursordist/test-filterpo_cc.cc
pdns/recursordist/test-syncres_cc3.cc

The existing code was optimized for very larger filtering policies (RPZ) but was duplicating a lot of work when a large number of policies was in use. This PR makes sure we don't copy `DNSName` objects and iterate over their labels one time for each policy.
It also check whether a policy really has rules for the type of lookup (qname, source IP, NS name, etc) before doing any processing, so we can return right away if there is no matching rules.
I have:

 rec: Optimize for large number of filtering policies, empty sections

---

pdns/lwres.cc
pdns/rec-dnstap.hh
pdns/resolve-context.hh
pdns/syncres.cc
pdns/syncres.hh

This requires passing the auth zone name to asyncresolve(). I chose to do this via the context so that we do not have to add an extra parameter to a function already having too many of them.
This is not strictly needed (query-zone is an optional field in dnstap), but it can be handy for diagnosis and other purposes. 
I have:

rec: set the query-zone field in the dnstap messages. 

---

pdns/dnsname.cc
pdns/dnsname.hh

This PR speeds up the `DNSName::toString()` process by avoiding unnecessary memory copies.
I have:

all: DNSName, speeds up toString() conversion

---

pdns/dnsdistdist/docs/guides/downstreams.rst

This change only adds a single new line to fix the bullet points, otherwise it is displayed as a single line (which is likely unintended).
https://dnsdist.org/guides/downstreams.html#source-address-selection
I have:

dnsdist doc: add newline to fix bullet points

---

pdns/recursordist/test-syncres_cc9.cc

We used to set time returned by `sr->getNow()` via `gettimeofday()`
and later the one used to compute the RRSIG validity via
`time(nullptr)`. It turns out that the second call can return a
value lesser than the first one, without the time going backward,
making our tests fail.
After this commit we base our calculations on the same time value,
so it should not fail randomly anymore.
(cherry picked from commit d0add506df4075aa8a7e2eb7c66f58ea850ff6d4)
I have:

rec backport to 4.2.x: Don't mix time() and gettimeofday() in our unit tests (again)

---

pdns/dnsname.hh
pdns/test-dnsname_cc.cc

If we insert fr and www.domain.fr, domain.fr should not match www.domain.fr, the leaf node, and it should not match the intermediary domain.fr node, but it should match the fr end-node.
It should also be possible to remove the root from the tree.
I have:

 SuffixMatchTree: Fix root removal, partial match of non-leaf nodes

---

pdns/syncres.cc

We don't care about the actual ordering, so let's do the cheapest
comparisons first then the quite expensive DNSName comparison only
if we really need to.
(cherry picked from commit 186e99c98d195329af05129cd4d6512657edf4bc)
I have:

rec backport to 4.2.x: : Compare the CacheKey type and place first then the name

---

pdns/recursordist/test-syncres_cc1.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc6.cc
pdns/recursordist/test-syncres_cc7.cc
pdns/syncres.cc

`SyncRes::getDSRecords()` used to not set the `foundCut` flag as soon as the processing returned a `Bogus` state. In some situations, for example if the time was completely off and the `RRSIG` from the root zone were thus invalid, this wrong zone cut determination lead to validation issues.
I have:

rec: Better detection of Bogus zone cuts for DNSSEC validation

---

pdns/test-mplexer.cc

I can't reproduce the failure on Arch nor stretch, but I have now seen it occur two times on our CI tests, the most recent one in CircleCI, so I would like to understand what is happening.
I have:

Add debug informations to the MPlexer unit tests, tracking a failure

---

.circleci/config.yml

It seems that in the 2019-03 version of the coverity tools, the number
of leading dirs in the tarball changed.
I have:

coverity: Fix paths from extracted tarball

---

configure.ac
pdns/Makefile.am
pdns/calidns.cc

Implement receiving using `recvmsg(2)` and guard `sched_setscheduler(2)`.
Also, a non-null control msg of length 0 is illegal on OpenBSD.
I tried tried to avoid reformatting too much, formatting is a broken in a lot of places.
The error handling in the `poll` loop was broken afaiks, so I fixed that as well.
I have:

Adapt calidns for openbsd and other systems without rcvmmsg(2)

---

.circleci/config.yml
regression-tests.dnsdist/requirements.txt
regression-tests.dnsdist/test_Protobuf.py
regression-tests.dnsdist/test_SNMP.py

This adds circleci testing for dnsdist, running on debian buster, because it's easier than stretch-backports (for libh2o-evloop) and buster will be out soon anyway.
This fixes running dnsdist tests on python3 on my local systems (debian buster); it also does not appear to break testing on Travis, somehow. Specifically this removes the 2.x/3.x split in the python protobuf dependency.
I have:

dnsdist: test on circleci; support py3 in tests

---

m4/pdns_check_os.m4

This avoids having a huge list of platforms which can change over time.
(cherry picked from commit 1735eb98cd295c0aec2c2cd4cff436a786dbc70f)
I have:

rec backport to 4.2.x: Check if -latomic is needed instead of hardcoding

---

pdns/dnsdist-lua.cc

Only compile the loadTLSCertificateAndKeys fucntion when DoT and/or DoH
are enabled.
Takes care of one of the warnings in #7950
I have:

dnsdist: squelch unused function warning

---

pdns/syncres.cc

No functional changes.
* Log only once that we're attempting a DNAME lookup (instead of once per label)
* Return early when no cachehits are found so we can remove level of indentations
* Rename an iterator variable from `j` to `record` and use `auto const &`
I have:

rec: Clean ups in the SyncRes::doCNAMECacheLookup code

---

pdns/communicator.cc
pdns/mastercommunicator.cc

Backports of #7964 and #7829.
I have:

auth 4.0.x: two backports

---

pdns/communicator.hh
pdns/mastercommunicator.cc
pdns/tcpreceiver.cc

#7663 (backport of #7662) did not catch name parse errors. This PR moves the exception `catch` up so that we catch both name and IP parse errors. 
I have:

catch name & IP parse errors during outgoing notify preparations 

---

pdns/recursordist/test-syncres_cc8.cc

Fixes #7949
This silences the unused lambda warning by only defining it when it's used.
I have:

Silence unused lambda warning (retry)

---

pdns/dnsdistdist/docs/advanced/axfr.rst
pdns/dnsdistdist/docs/reference/constants.rst

This fixes some minor issues in the dnsdist docs:
DNSQType was introduced in 1.4.0, not 1.3.0
Typo in AXFR example (DNSQTypeIXFR)
I have:

Minor fixes to dnsdist docs

---

pdns/slavecommunicator.cc

If you neglected tos etup a zone as a slave, but received a notification, you'd get the following error:
```
Can't determine backend for domain 'example.com'
```
It personally took me a while to debug a problem because of this error (was something wrong with my backend?).
The new error mentions a zone not being a slave zone in this case.
I have:

Improve error when notification comes in for non-slave zone

---

docs/http-api/swagger/authoritative-api-swagger.yaml
pdns/ws-auth.cc
regression-tests.api/runtests.py
regression-tests.api/test_Zones.py

This gives API consumers the ability to see the edited SOA serial. The
API code used the same functions as the DNSSECKeeper, so this serial
will match the one send to clients in response to queries.
Closes #7961
I have:

auth: add edited_serial to Zone object

---

builder-support/specs/pdns.spec

This creates the pdns-backend-lmdb package for CentOS 7 builds
I have:

Add LMDB backend to centos-7

---

pdns/dnsdistdist/doh.cc

`h2o` doesn't allow us to override the HTTP `Server:` header in the usual way but we can override the default value in the `h2o_globalconf_t` object.
Fixes #7894.
I have:

dnsdist: Properly override the HTTP Server header for DoH

---

docs/manpages/pdnsutil.1.rst
pdns/pdnsutil.cc
regression-tests/tests/publishing-cds-cdnskey/expected_result

`pdnsutil set-publish-cds` defaults to enabling both SHA-1 and SHA-256. This changes it to use SHa-256 only.
(It's just a default, anyone can still enable SHA-1 if they want to.)
Reasons:
* ~~Burning hatred for all things SHA-1.~~
* Popular TLDs including .com use only SHA-256, so a resolver that only supports SHA-1 is terribly old and not very useful.
* `secure-zone` uses ECDSA by default. Are there even any resolvers that support ECDSA but don't support SHA-256?
* [BIND 9.15.0 did it.](https://ftp.isc.org/isc/bind9/9.15.0/RELEASE-NOTES-bind-9.15.0.html)
I've run part of the test suite, but not actually tried it.
I have:

Make pdnsutil set-publish-cds default to SHA-256 only

---

docs/settings.rst
pdns/auth-packetcache.cc
pdns/auth-packetcache.hh
pdns/common_startup.cc
pdns/packethandler.cc
pdns/tcpreceiver.cc

This was inspired by #7802 but is more in line with the current query cache behaviour
closes #7802
I have:

auth: completely disable the packet when cache-ttl=0

---

docs/http-api/index.rst
docs/settings.rst
pdns/common_startup.cc
pdns/recursordist/docs/settings.rst
pdns/webserver.cc
pdns/webserver.hh
pdns/ws-auth.cc

Because some people have big zones.
Bumping the buffer size from 1024 to 16000 changes the read time for a 4 megabyte request from 2 minutes to around 10 seconds.
I have:

auth web: make max request/response body size configurable

---

pdns/Makefile.am
pdns/dnsdistdist/dnsdist-secpoll.cc
pdns/recursordist/Makefile.am
pdns/recursordist/secpoll.cc
pdns/recursordist/secpoll.hh
pdns/recursordist/test-secpoll_cc.cc
pdns/secpoll-auth.cc
pdns/secpoll-recursor.cc
pdns/secpoll.cc
pdns/secpoll.hh
pdns/stubresolver.cc

* Fix log messages for non-releases (see #7895)
* Refactor auth and rec secpoll code to return early and catch an additional condition
* Set the security state to unknown in the auth on error (when state is OK)
I have:

Secpoll code: fixes and clean-ups

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsname.hh
regression-tests.dnsdist/test_CheckConfig.py

The SuffixMatchNode now also accepts a table of DNSNames, a table of
string, and singular strings.
Closes https://github.com/PowerDNS/pdns/issues/7390.
I have:

SuffixMatchNode:add: Accept more types

---

pdns/dnsdist-lua-rules.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsdistdist/docs/rules-actions.rst

This allows the user to hide the list of matched IPs in `showRules()`
I have:

dnsdist: Add `quiet` parameter to NetmaskGroupRule

---

pdns/dnsdist-tcp.cc

- The creation of the `Socket` object can throw if we run out of file descriptors ;
- Catch exceptions thrown from `setupTCPDownstream()` earlier, we don't care why it failed later, only that it did.
I have:

dnsdist: Fix handling of backend connection failing over TCP

---

pdns/dnsdist-tcp.cc
pdns/tcpiohandler.hh
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_TCPShort.py

`TCPIOHandler::tryRead()` and `TCPIOHandler::tryWrite()` are supposed to update the position and read/write the remaining number of bytes based on the initial total number minus the position, so that the caller can just pass the exact same parameters on short reads/writes until it succeeds or an exception is raised, without having to care about updating the position and number of bytes to read/write.
<strike>Untested yet.</strike>
Supersedes #7971.
I have:

dnsdist: Fix short IOs over TCP

---

pdns/calidns.cc
pdns/dnsdist.cc
pdns/dnsproxy.cc
pdns/iputils.cc
pdns/iputils.hh
pdns/misc.cc
pdns/misc.hh
pdns/nameserver.cc
pdns/pdns_recursor.cc

OpenBSDs man page http://man.openbsd.org/CMSG_DATA recommend explicit alignment of the buffer to hold cmsg data. 
This probably does not matter on non-strict alignment architectures, but is good practise.
(Disclaimer: I was one of the devs involved in this change to the man page, see http://cvsweb.openbsd.org/src/share/man/man3/CMSG_DATA.3).
Noticed while studying #7981
I have:

Explicitly align the buffer used for cmsgs

---

pdns/fstrm_logger.hh
pdns/lwres.cc
pdns/pdns_recursor.cc
pdns/remote_logger.hh
regression-tests.recursor-dnssec/test_Protobuf.py

The documentation states that you can log only outgoing queries or incoming responses, but this was not actually supported.
I have:

rec: Fix the export of only outgoing queries or incoming responses

---

pdns/misc.cc

Valgrind complains if we don't clear the padding. It is debatable if that is right...
Tested to fix #7981: without this PR valgrind complains if run with local address 0.0.0.0, with this the complaints are gone.
I have:

Clear CMSG_SPACE(sizeof(data)) in cmsghdr to appease valgrind.

---

docs/settings.rst
pdns/pdnsutil.cc

- default-soa-mail
- default-soa-name
- soa-refresh-default
- soa-retry-default
- soa-expire-default
- soa-minimum-ttl
Have reached their expiration date. They are incompatible with the API and the new lmdb backend.
I have:

auth: deprecate SOA autocomplete in pdnsutil check-zone

---

pdns/distributor.hh
pdns/test-distributor_hh.cc

This was broken since eb029b8efe0217b39c5cf34235b565b4c8d6e95e which introduced a specific type of DNSName,qtype ring.
It compiles but then fails on insertion with:
```
terminate called after throwing an instance of 'std::runtime_error'
what():  Attempting to account to non-existent ring 'servfail-queries'
Jun 28 14:24:19 Got a signal 6, attempting to print trace: 
Jun 28 14:24:19 pdns/pdns_server(+0x2f2486) [0x56222f0ea486]
Jun 28 14:24:19 /usr/lib/libc.so.6(+0x3a7e0) [0x7f3c2327a7e0]
Jun 28 14:24:19 /usr/lib/libc.so.6(gsignal+0x145) [0x7f3c2327a755]
Jun 28 14:24:19 /usr/lib/libc.so.6(abort+0x125) [0x7f3c23265851]
Jun 28 14:24:19 /usr/lib/libstdc++.so.6(+0x9581f) [0x7f3c2361981f]
Jun 28 14:24:19 /usr/lib/libstdc++.so.6(+0xa230a) [0x7f3c2362630a]
Jun 28 14:24:19 …
```

auth: Fix the accounting of servfail-queries in the distributor

---

build-scripts/cherry-pick-pr.py

#7940 changed the default naming for creating backport branches; this PR also uses that default naming when merging backports into a branch.
I have:

cherry-pick-pr: fix branch name in merge command

---

pdns/misc.cc

The current buffer size should be much more than required, but let's make sure it stays that way.
I have:

Add static assertions for the size of the src address control buffer

---

pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc.hh
pdns/recursordist/test-syncres_cc4.cc

On some very slow platforms where the test was taking too long, the signature's inception would have ended up _before_ the current SyncRes time used to do the validation, causing a validation issue.
I have:

rec: Don't go Bogus if the auth zone delegation test takes too long

---

pdns/receiver.cc

Make sure we're using glibc and not uclibc pretending to be glibc
I have:

auth: make sure we really are using glibc

---

pdns/distributor.hh
pdns/packethandler.cc

This only happens for issues that are not dependent on the content of the database or the incoming DNS query itself, but it could be an issue with a unreliable backend.
I have:

auth: Fix a leak on 'Backend reported permanent error which prevented looukp' error

---

pdns/misc.cc

(cherry picked from commit 20b22895546a3e7fb7760940599dfb1e29a00777)
I have:

rec backport to 4.2.x: Clear CMSG_SPACE(sizeof(data)) in cmsghdr to appease valgrind.

---

pdns/fstrm_logger.hh
pdns/lwres.cc
pdns/pdns_recursor.cc
pdns/remote_logger.hh
regression-tests.recursor-dnssec/test_Protobuf.py

Master re-uses the message but 4.2.x not. So this has to be reviewed with extra care,  it is not a straight merge.
I have:

rec backport to 4.2.x: Fix the export of only outgoing queries or incoming responses

---

pdns/dnsdist-tcp.cc

The current code could have tried to read a new query before coming back to the insertion, resetting the state in the process and leading to recording a wrong backend or worse, to a NULL-pointer dereference if the new query was dropped or self-answered (no backend then).
I have:

 dnsdist: Insert the response into the ringbuffer right after sending it

---

pdns/dnsmessage.proto
pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/protobuf.cc
pdns/protobuf.hh
pdns/recursordist/docs/lua-scripting/dq.rst
pdns/recursordist/docs/lua-scripting/hooks.rst
regression-tests.recursor-dnssec/test_Protobuf.py

This PR adds a new `deviceName` field to the protobuf messages. Like other fields such as `deviceId` or `requestorId`, this can be set dynamically in the `gettag()` LUA function. This also fixes the FFI corresponding API to actually set this field (and not the `deviceId`).
I have:

recursor: add deviceName field to protobuf messages

---

pdns/dnsname.cc
pdns/dnsname.hh

Shaves a nice 20%+ off `DNSName::toString()` for regular names, and cut in half the CPU time when we encounter a 'special' character (not `.` or `\` and lesser or equal to `0x20` or greater or equal to `0x7f`).
I have:

Don't create temporary strings to escape DNSName labels

---

pdns/dnsparser.cc
pdns/syncres.cc
pdns/syncres.hh

No major improvement but a couple minor ones:
- Don't copy the `GetBestNSAnswer` object on insertion ;
- Skip the lookups (and `chopOff()`s) in `SyncRes::getBestAuthZone` if we don't have any internal auth zones ;
- Use unordered maps for `DNSName`s based maps (`NsSet` object, `nsSpeeds`, internal auth zones) ;
- Compare the `qtype` before the `DNSName` in `GetBestNSAnswer` comparisons since we have types than just `A` and `AAAA` ;
- Compare the socket descriptor and ID before the `qname` when comparing `PacketID`s ;
- Insert the new DNSRecord last in MOADNSParser so we can move it.
I have:

rec: Small speed improvements in the SyncRes

---

pdns/dnsmessage.proto
pdns/lwres.cc
pdns/protobuf.cc
pdns/protobuf.hh
regression-tests.recursor-dnssec/test_Protobuf.py

The protobuf messages we send when we receive an incoming DNS response from an authoritative server have all the information found in the protobuf message for the corresponding outgoing DNS query, except that we don't generate a message for a timeout or a network error, so it still requires sending and keeping track of the outgoing query messages to detect these.
This PR amends the existing code to generate a special protobuf message for timeout or network errors, with a rcode set to the special `65536` value and a size of `0` bytes.
I have:

rec: Export a protobuf incoming response message for timeouts

---

pdns/receiver.cc

This commit fixes invalid syntax introduced in #7980 which caused build failures on some platforms
Failure from OpenWRT: (gcc-8.3.0 on arc uclibc)
```
receiver.cc:394:18: warning: extra tokens at end of #ifdef directive
#ifdef __GLIBC__ && !defined(__UCLIBC__)
^~
receiver.cc:395:10: fatal error: execinfo.h: No such file or directory
#include <execinfo.h>
^~~~~~~~~~~~
```
I have:

auth: correct syntax for GLIBC detection

---

pdns/dnsdistdist/doh.cc
pdns/doh.hh

We used to send a 500 status code when a query was dropped, regardless of the reason. This PR tries to return a more appropriate status code instead.
It also moves the ACL check right after the connection has been accepted, before the HTTP/2 and DNS parsing, to avoid wasting cycles on queries that we will end up dropping anyway. It's a bit more mean to HTTP clients that will get their TCP connection closed right away instead of a 403 status code, but I think it's worth it. Comments welcome :) 
I have:

dnsdist: Send better HTTP status codes, handle ACL drops earlier

---

pdns/dns.cc
pdns/dns.hh
pdns/dnsdist-lua-inspection.cc
pdns/dnsdist-tcp.cc

- We display the queries and responses received over UDP and DoH in verbose mode, but we were not displaying the ones received over TCP or DoT ;
- Display any non-zero opcode in `grepq()`.
I have:

 dnsdist: Display TCP/DoT queries and responses in verbose mode, opcode in grepq

---

pdns/communicator.hh
pdns/mastercommunicator.cc
pdns/tcpreceiver.cc

This brings master in line with  https://doc.powerdns.com/authoritative/security-advisories/powerdns-advisory-2019-04.html
I have:

forward-port #7964: catch name & IP parse errors during outgoing notify preparations

---

pdns/ssqlite3.cc

If an statement is passed, or there is something wrong with the database, we might have leaked the memory allocated by `sqlite3_exec`'s error message.
This doesn't really matter today because these conditions will abort the server, but it's cleaner that way. 
I have:

auth: Fix a memory leak when sqlite3_exec() fails

---

pdns/Makefile.am
pdns/dnswriter.cc
pdns/dnswriter.hh
pdns/test-dnswriter_cc.cc

In a very specific edge case, we would get compression pointers above the 0-0x3fff range, and truncate those to a very low number, causing clients to throw parse errors.
I have added a fix from @pieterlexis where DNSPacketWriter did not honour `compress=false` for the content of any type (like NS) that is permitted to compress by RFC.
I have:

limit compression pointers to 14 bits

---

.circleci/config.yml
regression-tests.ixfrdist/test_Stats.py

The error was caused by both `test_*.py` starting an `xfrserver` on the same port.
I have:

ixfrdist: test in CircleCI; remove useless error

---

pdns/ixfrdist.cc

When compressing, bigger chunks limit our compression ratio. When not compressing, smaller chunks don't make a huge difference in performance.
I have:

ixfrdist: limit XFR chunk size to 16k

---

pdns/ueberbackend.cc

According to the documentation on UeberBackend::getAuth(), a backend
returning an empty DNSName should signal that no matching parent zone
exists in this backend. However commit ae14c1f36a raises an exception if
isPartOf() is called on an empty DNSName so we need to switch the order
of the logic to prevent a SERVFAIL as a result.
I have:

Fix SERVFAIL when backend returns empty DNSName

---

pdns/devpollmplexer.cc

remove unused import to enable compile on illumos.
I have:

pdns/devpollmplexer: remove unused syncres.hh include

---

pdns/pdnsutil.cc

Discovered due to this new (to us) compiler warning:
```
pdnsutil.cc:59:32: warning: '%c' yields only last 2 digits of year in some locales [-Wformat-y2k]
```
I have:

pdnsutil: remove unused humanTime function

---

pdns/Makefile.am
pdns/circular_buffer.hh
pdns/dnsdist-rings.hh
pdns/dnsdist.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/circular_buffer.hh
pdns/dnsdistdist/tcpiohandler.cc
pdns/recursordist/Makefile.am
pdns/recursordist/circular_buffer.hh
pdns/remote_logger.hh
pdns/statbag.hh
pdns/syncres.hh
pdns/ws-api.cc

Even though the documentation states that:
> simultaneous read accesses to a shared circular_buffer are safe
`boost::circular_buffer` < 1.62 was built with a debugging facility *by default* that made it unsafe to access the same circular buffer from more than one thread at once, in addition to making iterator operations slower. 
- https://svn.boost.org/trac10/ticket/6277
- https://github.com/boostorg/circular_buffer/pull/9
It's only a real issue in dnsdist since our DNS over TLS code is the only place where we read from a circular buffer from several threads at once, but this change might provide a small performance boost in the auth and rec as well on platforms where boost is older than 1.62.
Note that I have compiled and tested this code only on Arch, we need to test it on other …

Make sure we always compile with BOOST_CB_ENABLE_DEBUG set to 0

---

pdns/Makefile.am
pdns/circular_buffer.hh
pdns/dnsdist-rings.hh
pdns/dnsdist.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/circular_buffer.hh
pdns/dnsdistdist/tcpiohandler.cc
pdns/recursordist/Makefile.am
pdns/recursordist/circular_buffer.hh
pdns/remote_logger.hh
pdns/statbag.hh
pdns/syncres.hh
pdns/ws-api.cc

Backport 8067 to rec 4.2.x: Make sure we always compile with BOOST_CB_ENABLE_DEBUG set to 0

---

pdns/dnsdist-tcp.cc
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_BrokenAnswer.py

We need to handle it gracefully if a function called from `handleResponse()` throws, most likely because the answer received from the backend was not valid.
I have:

dnsdist: Catch exceptions thrown when handling a TCP response

---

pdns/dnsdist-tcp.cc
regression-tests.dnsdist/test_TCPFastOpen.py

Using the same flag to indicate whether a connection was reused after being pulled from the pool AND to know if the `TFO` flag should be passed to `sendmsg()` led to an unlimited number of reconnection
attempts when `TFO` was enabled and the backend closed the connection right after a write (`sendmsg()` succeeds then `read()` returns 0 right away).
I have:

dnsdist: Fix unlimited retries when TCP Fast Open is enabled

---

docs/changelog/4.2.rst

#6220's title was "Add XPF support", but the only actual changes to Auth were to `sdig` and the test suite, and the changelog entry was misleading.
Reported by @spheron1.
This should be backported to 4.2.
I have:

Clarify XPF support in Auth changelog

---

builder-support/debian/recursor/debian-buster/rules
builder-support/debian/recursor/debian-jessie/rules
builder-support/debian/recursor/debian-stretch/rules
pdns/pdns_recursor.cc

As we'd now run as root in those instances. We also add a warning in the config-file about this. See https://github.com/PowerDNS/pdns/pull/7879#issuecomment-509033651 for the discussion
I have:

Ensure Debian SysV users get set{g,u}id

---

pdns/packethandler.cc

When verifying NOTIFY, compare TSIG key name using DNSName to validate it correctly. Fixes #8070 
I have:

packethandler: Compare TSIG key name using DNSName

---

pdns/test-mplexer.cc

This way we can at least check that the callbacks are called later.
Also, since it looks like the read pipe is always reported as ready, let's try to write first to see if it blocks.
I have:

Don't fail the test right away if we don't have the right number of FDs ready

---

pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/doh.cc
pdns/doh.hh

Timeouts, actively discovered or not, were not properly handled for DoH queries.
This PR is based on top of #7917 so we can send a proper HTTP status code, it will need to be rebased.
I have:

dnsdist: Proper HTTP response for timeouts over DoH

---

lgtm.yml

This reverts commit 8763cf1ca8ba2c7266521272fedc2b130af71f75.
LGTM keeps spending hours of CPU on our PRs to then eventually time out for some reason. I have the impression this started after #8077, so here we revert that to see if it helps.
I have:

Revert "enable a bunch of extra features during LGTM builds"

---

docs/requirements.txt
pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

docutils 0.15 breaks with python 2.7, so avoid it (falling back to 0.14) until 0.16 is out which I trust will fix this.
I have:

avoid docutils 0.15: https://sourceforge.net/p/docutils/bugs/365/

---

.circleci/config.yml
m4/systemd.m4

We use systemctl to determine the version as to find out what features
to enable in the unit file.
Thanks to @zeha for mentioning this
I have:

m4/systemd.m4: Fail when systemctl is not available

---

regression-tests.dnsdist/test_BrokenAnswer.py

The regression test added in #8078 introduced an issue when executed with Python 2:
```
Exception in thread TCP Responder:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "regression-tests.dnsdist/dnsdisttests.py", line 256, in TCPResponder
wire = callback(request)
File "regression-tests.dnsdist/test_BrokenAnswer.py", line 28, in responseCallback
altered = raw[:offset] + chr(255).encode('utf-8') + raw[offset+1:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
```
I have:

dnsdist: Fix a UnicodeDecodeError with py2 in the regression tests

---

pdns/dnsdist-tcp.cc

At least one user of 1.4.0-beta1 has reported that the outstanding counter is not always properly decremented, or is incremented twice. I have not been able to reproduce it so far but let's make sure we can only increment it once per TCP connection.
I have:

dnsdist: Double-check we only increment the outstanding counter once

---

docs/upgrading.rst
modules/gpgsqlbackend/4.1.0_to_4.2.0_schema.pgsql.sql
modules/gpgsqlbackend/schema.pgsql.sql
pdns/pdnsutil.cc

Fixes #6815.
Also adds the `change_date` and autoserial removal to the auth 4.2 upgrade docs.
I have:

auth: use BIGINT for notified_serial in pg schema

---

pdns/ueberbackend.cc

According to the documentation on UeberBackend::getAuth(), a backend
returning an empty DNSName should signal that no matching parent zone
exists in this backend. However commit ae14c1f36a raises an exception if
isPartOf() is called on an empty DNSName so we need to switch the order
of the logic to prevent a SERVFAIL as a result.
(cherry picked from commit 41147d678b30612d2431b59a898879368f1c4b06)
Backport of #8054 
I have:

auth 4.2: Fix SERVFAIL when backend returns empty DNSName

---

pdns/dnsdist-console.cc

cout may not be a tty, in which case it is block buffered by stdlib, so flush it after printing g_outputBuffer.
Fixes #8130
I have:

dnsdist-console: flush cout after printing g_outputBuffer

---

pdns/lua-base4.cc

c052aac71b2ff336ca59421a5bee30564ce9562a renamed it to `DNSName::wireLength()` while documenting the `DNSName` bindings in the auth, unfortunately breaking compatibility in the recursor.
Reported at https://mailman.powerdns.com/pipermail/pdns-dev/2019-July/001726.html
I have:

Restore the Lua binding for DNSName::wirelength()

---

pdns/dnsdist-ecs.cc
pdns/test-dnsdist_cc.cc

Interpreting the value as signed could result in a large value being considered negative. After the addition it would be stored into an unsigned value and thus become positive again, but the result of the addition would be wrong.
This means that we could fail to locate some EDNS options whose codes are too large and, while it's extremely unlikely to happen, we could get only a partial content for some very large options.
Reported by Brian Sullivan on the mailing-list [1].
[1]: https://mailman.powerdns.com/pipermail/dnsdist/2019-July/000596.html
I have:

dnsdist: Fix signedness issue in isEDNSOptionInOpt()

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua-actions.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_Advanced.py

As discussed on the mailing-list [1], this new action makes it possible to use an otherwise terminal action without stopping the rule processing. For example:
```
addAction(AllRule(), PoolAction("mypool"))
addAction(AllRule(), DisableValidationAction())
```
would route all incoming queries to the `mypool` pool, and since the `PoolAction()` terminates the processing the `DisableValidationAction()` one would never be applied.
With the new action, it is possible to do:
```
addAction(AllRule(), ContinueAction(PoolAction("mypool")))
addAction(AllRule(), DisableValidationAction())
```
This would result in all queries being routed to the `mypool` pool *with* the CD `flag` being set.
[1]: https://mailman.powerdns.com/pipermail/dnsdist/2019-July/000590.html
I have:

dnsdist: Implement ContinueAction()

---

pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/doh.cc

This change fixes a possible ABA issue and, coupled with stronger checks when updating the state, should reduce the likelihood of any issue when a state is reused from a different thread.
Needs a serious review.
I have:

dnsdist: Use a counter to mark IDState usage instead of the FD

---

pdns/dnsdist-carbon.cc
pdns/dnsdist-console.cc
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-web.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/docs/rules-actions.rst
pdns/dnsdistdist/doh.cc
pdns/doh.hh
regression-tests.dnsdist/test_DOH.py

This PR adds:
- `HTTPPathRegexRule` to be able to match the path of a DoH query with a regular expression ;
- `HTTPStatusAction` to be able to return a specific HTTP response to a DoH query ;
- Lua bindings (`DNQuestion:getHTTPHeaders()`, `DNSQuestion:getHTTPHost()`, `DNSQuestion:getHTTPPath()`, `DNSQuestion:getHTTPQueryString() and `DNSQuestion:getHTTPScheme()` to be able to inspect a DoH query from Lua ;
- `DNSQuestion:setHTTPResponse()` to be able to return a specific HTTP response from Lua as well.
Fixes #8133.
I have:

dnsdist: Add Lua bindings, rules and action for DoH

---

modules/pipebackend/coprocess.cc
modules/remotebackend/pipeconnector.cc

auth 4.1.x: stop using select() in places where FDs can be >1023

---

m4/systemd.m4

We use systemctl to determine the version as to find out what features
to enable in the unit file.
(cherry picked from commit 1f988403108ef7454006fcd995574d89f83aef7f)
Backport of #8081 (without the coverity bits).
I have:

auth-4.2.x: m4/systemd.m4: Fail when systemctl is not available

---

pdns/packethandler.cc

Fixes #8070
(cherry picked from commit 6da24c839a957f0f9866d8025a6bf35256b2e451)
Backport of #8071
I have:

auth 4.2.x: packethandler: Compare TSIG key name using DNSName

---

build-scripts/travis.sh
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/libssl.cc
pdns/dnsdistdist/libssl.hh
pdns/dnsdistdist/m4/dnsdist_with_libssl.m4
pdns/dnsdistdist/tcpiohandler.cc
pdns/doh.hh
pdns/tcpiohandler.hh
regression-tests.dnsdist/.gitignore
regression-tests.dnsdist/runtests
regression-tests.dnsdist/test_OCSP.py

The OCSP responses are loaded from files on startup, and reloaded when the `reloadAllCertificates()` command is issued.
Fixes #7812.
I have:

dnsdist: Add OCSP stapling (from files) for DoT and DoH

---

pdns/dnsdist.cc
pdns/dnsdistdist/docs/advanced/tuning.rst
pdns/dnsdistdist/docs/reference/tuning.rst

I don't see any good reason not to, unless perhaps in very specialized embedded setups.
I have:

dnsdist: Increase the default value of setMaxUDPOutstanding to 65535

---

pdns/dnsdist-tcp.cc
pdns/tcpiohandler.hh

When a non-blocking connect() has returned `EINPROGRESS`, it looks like BSD can return `ENOTCONN` on `read()` even after a `write()` succeeded.
We did not get a trace confirming that `read()` can indeed return `ENOTCONN` in that case yet, though.
Fixes #8021.
I have:

dnsdist: Handle ENOTCONN on read() over TCP

---

pdns/syncres.hh

Note that float saves mem, but on some machines it might even be
slower than double, since most FPUs are optimized for double.
Code does not seem to be able to make up its mind whether to use float or double ;-)
I have:

Some unneeded float<->double conversions.

---

pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc.hh
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc5.cc

In Debian I had to apply #8008 and #8047 on top of the Recursor 4.2.0 release to make `make check` pass on mipsel (which is super slow).
Please consider applying these to the release branch.
Disclaimer: While I've tested these in Debian, I have not tested this exact git hash.
I have:

Recursor 4.2: Backport #8008 #8047 test improvements

---

pdns/recursordist/configure.ac

On MIPS, there is no Boost Context. On OpenWRT, this is combined with a lack of `getcontext` in musl. This means we can never compile there. This PR makes configure do this, instead of waiting for the linker to error after compilation.
I have:

Bail out when no Context library is available

---

pdns/recursordist/configure.ac

Revert "Bail out when no Context library is available"

---

docs/backends/generic-sql.rst

Just fixing this incorrect query name in the docs.
`insert-empty-non-terminal-order-query` (`-query` instead of `--query`) is the correct name of the query, see:
https://github.com/PowerDNS/pdns/blob/rec-4.2.0/pdns/backends/gsql/gsqlbackend.cc#L82
and
https://github.com/PowerDNS/pdns/search?q=insert-empty-non-terminal-order-query&type=Code
I have:

Fix typo in SQL query name in documentation

---

builder-support/dockerfiles/Dockerfile.authoritative
builder-support/dockerfiles/Dockerfile.dnsdist
builder-support/dockerfiles/Dockerfile.recursor
builder-support/dockerfiles/Dockerfile.target.sdist

As discussed with @Habbie 
The problem is that on older Alpine there's no continuation.hpp, which will lead to a fatal error once the "no contex is fatal" PR will be committed.
I have:

Move to newer alpine for docker buildbot, needed for proper boost context detection

---

pdns/recursordist/configure.ac

Reverts the revert of #8122 since buildbot should now be able to handle this.

Revert "Revert "Bail out when no Context library is available""

---

pdns/lua-recursor4-ffi.hh
pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/syncres.hh

This will not skip the creation of a MThread since we will need it to follow CNAME records, if any, and we don't want to worry about a full parsing of the query and records creation in gettag, but it prevents the need of calling 'preresolve' which has no FFI equivalent, as well as the need to carry data around from one hook to another.
I have:

rec: Add bindings to craft answers from the FFI version of gettag

---

pdns/dnsdistdist/docs/advanced/qpslimits.rst
pdns/dnsdistdist/docs/rules-actions.rst

DelayAction() is only capable of delaying UDP queries. While it is noted in the reference for that command, DelayAction is used as an example in multiple places. Clarify in those examples that this will only delay UDP traffic.

dnsdist: clarify in the examples that DelayAction is UDP-only

---

modules/bindbackend/bindbackend2.cc

This fixes #7994. it also fixes `pdns_control list-zones` under the same error condition.
I have:

bind getAllDomains: ignore per-zone exceptions

---

pdns/filterpo.cc

Revert "rec: backport 8236: Add missing inc in rpz findClientPolicy loop."

---

pdns/dnsdistdist/dnsdist-kvs.cc

When neither the C++ 17 nor Boost >= 1.61 `string_view` are available, we fall back to `boost::string_ref`. Unfortunately it didn't have the `to_string()` method before 1.56.
Since we end up converting it to a string anyway, let's just skip the `string_view`/`string_ref` part.
I have:

dnsdist: Fix KVS compilation on Boost < 1.56

---

pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/libssl.cc
pdns/dnsdistdist/tcpiohandler.cc
pdns/libssl.hh

Make sure that the version of OpenSSL supports TLS 1.3. Fix a silent failure when setting the minimum TLS version.
I have:

dnsdist: TLS 1.3 requires OpenSSL 1.1.1.

---

pdns/syncres.cc

There is a typo in comment in "/pdns/syncres.cc:2883" :
> as described in section 5.3.4 of RFC 4035 and 5.3 of FRC 7129
The corrected comment should be:
"as described in section 5.3.4 of RFC 4035 and 5.3 of RFC 7129"

fix a typo in comment in syncres.cc: 'FRC 7129' to 'RFC 7129'

---

pdns/dnsdist-lua-inspection.cc
pdns/dnsdistdist/docs/reference/config.rst

Allowing to prevent the insertion of new dynamic block to be logged.
I have:

dnsdist: Add a Lua binding for `DynBlockRulesGroup:setQuiet(quiet)`

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/rules-actions.rst
pdns/dnsdistdist/doh.cc
pdns/doh.hh
regression-tests.dnsdist/test_DOH.py

The `HTTPPathRule` and `HTTPPathRegexRule`, and the `Lua` bindings to access the HTTP informations are only invoked for valid DNS over HTTP queries. This PR adds support for responding to HTTP queries _before_ the DNS payload has been parsed, thus allowing to respond to all HTTP queries.
I have:

dnsdist: Add support for early DoH HTTP responses

---

docs/http-api/swagger/authoritative-api-swagger.yaml

While implementing the Cryptokey JSON API, I was wondering why the API always returns a number instead of a string. If I understood correctly, according to [this](https://github.com/PowerDNS/pdns/blob/master/pdns/dbdnsseckeeper.cc#L134), this is valid behaviour.
I have:

Set type of Cryptokey ID to integer

---

docs/dnssec/modes-of-operation.rst

The example `pdnsutil` command in the DNSSEC Modes of Operation docs currently suggests putting the BIND DNSSEC database in `/var/db`.
Using a directory that pdns can't write to can be problematic, as discussed in #7888.
This PR changes it to `/var/lib/powerdns`, which the gsqlite3 backend `README.Debian` already suggests, and which is already owned by pdns as of #7889.
I have:

docs: suggest putting bind dnssec db in /var/lib/powerdns

---

pdns/dnsdistdist/docs/reference/dnsname.rst

This PR fixes a small typo in the reference documentation of dnsdist DNSName class.
I have:

fix typo in DNSName reference documentation

---

docs/domainmetadata.rst
docs/settings.rst
pdns/slavecommunicator.cc
pdns/ws-auth.cc

Adds support for new per-zone metadata SLAVE-RENOTIFY, which does the same thing as the global slave-renotify setting, but per-zone.
Needed for example when pdns is acting as a slave for a hidden master, but still needs to notify upstream slaves for specific zones.
I have:

Add SLAVE-RENOTIFY zone metadata support

---

modules/bindbackend/bindbackend2.cc

Makes bindbackend consult metadata, if available, for ALSO-NOTIFY entries. named.conf entries are  also still used too if set.
I have:

auth: bindbackend: use metadata for also-notifies as well

---

pdns/arguments.cc
pdns/pdns_recursor.cc

1. Uninitialized field in DNSComboWriter.
2. TOCTOU wrt stat() and then opendir(). opendir() already tells us if the path
is not a dir or not accesible, so no need to do a TOCTOU sensitive pre-check.
Use uniform error messages in log and exceptions while here.
** CID 1404735:  Uninitialized members  (UNINIT_CTOR)
** CID 1401970:  Security best practices violations  (TOCTOU)
With some whitespace fixes, since the indentation was completely wrong
I have:

rec: fix two coverity issues

---

docs/settings.rst
pdns/common_startup.cc
pdns/slavecommunicator.cc

Adds a configurable timeout for inbound AXFR. Default is 10 seconds which it was previously hardcoded to.
Needed when transferring large zones from slow masters which take a while before sending anything. Same timeout setting is also applied for subsequent `getChunk` calls.
Fun fact: bind has a default timeout of 2 hours for the whole AXFR, and 1 hour for stalls during transfer.
I have:

auth: add configurable timeout for inbound AXFR

---

build-scripts/docker/generate-repo-files.sh

This is mainly used for quickly testing new releases by starting up a Docker container for each of our repositories, this saves a lot of handwork.
Although this script is very blunt and already starting to get out of hand I still would like this in our repo to get more eyes on and as a reminder that we need something like this.
In time, we should replace it with better tools or port it to a real programming languages, but this has not happened in the last months as it will not happen in the foreseeable future.  For that time, this will come in handy.

Add script for generating repo files.

---

pdns/dnsdistconf.lua

Use DNSRCode & DNSQType when 1.4.0 is out... 
I have:

dnsdist: dnsdistconf.lua use non-deprecated versions for 1.4.0

---

pdns/dnsdistdist/docs/rules-actions.rst

Documentation fix - filename is a mandatory parameter to LogAction in dnsdist.
I have:

Documentation fix. filename is mandatory for LogAction() in 1.3.3.

---

pdns/dnsdistdist/docs/reference/config.rst

Reported by Brian Sullivan on the mailing-list [1] (thanks!).
[1]: https://mailman.powerdns.com/pipermail/dnsdist/2019-September/000671.html
I have:

dnsdist: Fix 'tls-1*' should be 'tls1.*' instead

---

pdns/webserver.cc

Without this, any exception that manages to bubble out of `serveConnection` will take down the whole pdns_server (or ixfrdist or recursor or ...) process with SIGABRT. Except on 'Linux', the user would also be left none the wiser as to the reason of the crash.
I have:

webserver: handle exceptions instead of SIGABRTing the world

---

pdns/pdnsutil.cc

First stab at #3814.
Simple implementation that does simple SOA change detection. Should work for most people
who just want to let increase-serial do the work.
Logic to increase serial is not centralized and it does not detect if the SERIAL has changed in the SOA. It just looks for a change of the SOA record in general.
I'm happy to also look at the rework of the increase-serial in general, but will need some guidance on that...
I have:

#3814 - Add question for to increase-soa after non SOA edit

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This should give users a nice chooser page instead of requiring them to extensively strip the template.
I have:

make separate bug/report templates

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/doh.cc
regression-tests.dnsdist/test_DOH.py

It allows using dnsdist behind a reverse-proxy or any other device offloading TLS.
Closes https://github.com/PowerDNS/pdns/issues/8263.
I have:

dnsdist: Allow accepting DoH queries over HTTP instead of HTTPS

---

pdns/pdns_recursor.cc
pdns/receiver.cc

Before:
```
pdns_server --launch=random --socket-dir=. foo
Fatal: non-option on the command line, perhaps a '--setting=123' statement missed the '='?
```
After:
```
pdns_server --launch=random --socket-dir=. bar
Sep 10 17:24:25 Unable to open /usr/local/etc/pdns.conf
Fatal: non-options (bar) on the command line, perhaps a '--setting=123' statement missed the '='?
pdns_server --launch=random --socket-dir=. bar foo
Sep 10 17:24:25 Unable to open /usr/local/etc/pdns.conf
Fatal: non-options (bar, foo) on the command line, perhaps a '--setting=123' statement missed the '='?
```
I have:

Improve commandline error reporting for non-opts

---

docs/dnsupdate.rst

The function name getZoneName() was misspelled in the reference.
If the wrong name is used as it was documented, that lead to nasty,
silent failure of the script as lua assumed default behavior of
non-existing functions and doesn't abort.
docs/dnsupdate.rst: Fix typo in getZoneName()
I have:

docs/dnsupdate.rst: Fix typo in getZoneName()

---

docs/backends/pipe.rst

By default, distributor-threads is a small number (currently 3). For
latency-bound applications this is too small, thus it would be a correct
place to have this description in pipe backend section as well.
Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>

docs: Add small description for pipe backend about distributor-threads

---

docs/lua-records/reference/misc.rst
pdns/calidns.cc
pdns/communicator.hh
pdns/dns_random.cc
pdns/dns_random.hh
pdns/dnspacket.cc
pdns/dnsproxy.cc
pdns/ixfr.cc
pdns/lwres.cc
pdns/notify.cc
pdns/recursordist/docs/lua-scripting/functions.rst
pdns/resolver.cc
pdns/rfc2136handler.cc
pdns/saxfr.cc
pdns/stubresolver.cc
pdns/test-dns_random_hh.cc
pdns/test-recpacketcache_cc.cc

Some of our `dns_random` usage looked like it expected the parameter to be an inclusive upper bound. This PR adds a test that ensures the upper bound is exclusive. The common `dns_random(0xffff)` pattern, which was off by one, is replaced by a single function with a clear name.
Reported by Matt Nordhoff, thanks!
I have:

dns_random: verify upper bound; fix boundary condition for QID generation

---

docs/manpages/pdns_control.1.rst

This patch adds some missing words for the "pdns_control
current-config" command in the pdns_control man page.
I have:

docs: Add missing words in pdns_control man page

---

pdns/dnssecinfra.cc
pdns/dnssecinfra.hh

`Testing algorithm 8: 'OpenSSL RSA' ->'OpenSSL RSA' -> 'OpenSSL RSA' Signature & verify ok, create 173usec, signature 75usec, verify 14usec` - the `create` part is new.
I have:

add key make time to pdnsutil test-all-algorithms, cleanup return type

---

regression-tests.dnsdist/test_HealthChecks.py

We have recurrent failures in CircleCI, likely caused by the fact that the next health check test has not completed yet, so be a bit more permissive about that.
I have:

dnsdist: Add more leeway in the health checks tests

---

modules/pipebackend/coprocess.cc
modules/pipebackend/coprocess.hh
modules/pipebackend/pipebackend.cc

By default the pipe backend enforces a timeout on the external process response time, via `poll()`. Since a buffered read would result in `poll()` considering that there is no unread data available even if there still is some in the buffer, the existing code disables any buffering on the pipe when the timeout is not disabled.
Unfortunately a non-buffered read is quite slower than a buffered one, so this PR implements an internal buffer in the pipe backend itself to speed things up, resulting in roughly 3 times more QPS with a very simple pipe backend script.    
I have:

auth: Emulate a buffered read in the pipe backend, ~3x faster

---

.circleci/config.yml

so ./builder-support is accessible.
Currently dnsdist and rec coverity targets fails because of wrong working dir.
I have:

circleci coverity target: fix cwd for dnsdist and rec when uploading tarballs 

---

pdns/dnsdistdist/dnsdist-kvs.hh

Fixes a funny looking message:
```
lookup key-value store based on 'suffix at least 2 labels)' and set the result in tag [...]
```
to:
```
lookup key-value store based on 'suffix with at least 2 label(s)' and set the result in tag [...]
```
I have:

dnsdist: Make KVS lookup text read better

---

modules/pipebackend/coprocess.cc

This closes a Coverity report 'Non-static class member "d_pid" is not initialized in this constructor nor in any functions that it calls.' and would also avoid us killing the wrong thing when we happen to `exit()` between instantiation and launch of a CoProcess.
I have:

pipebackend coprocess: initialise d_pid

---

pdns/recursordist/docs/conf.py

(cherry picked from commit 760d679c2a3566dac8001115db95762344cdcbd5)
Man pages/docs now contain 4.1.
I have:

backport to rec -4.2.x: Remove version number in man page footer

---

pdns/recursordist/Makefile.am
pdns/recursordist/test-rpzloader_cc.cc
pdns/rpzloader.cc
pdns/rpzloader.hh

While there, add unittest for translating rpz names into netmasks
Fixes issue #8338 
I have:

Fix #8338: Issue with "zz" abbreviation for IPv6 RPZ triggers

---

.clang-format

Run with `clang-format [-i] -style=file` in the tree.
`-i` does an in-place edit, without it result is written to stdout.
`-style=file` will look in cwd and up for a style file called .clang-format, which is added by this PR.
I have:

clang-format file proposal

---

modules/bindbackend/bindbackend2.cc
modules/bindbackend/bindbackend2.hh

To make our live easier, use a native C++ mutex.
Fixes #8161
I have:

bind backend: pthread_mutex_t should be inited and destroyed and not be copied

---

build-scripts/travis.sh
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/libssl.cc
pdns/dnsdistdist/tcpiohandler.cc
pdns/doh.hh
pdns/libssl.hh
regression-tests.dnsdist/test_TLSSessionResumption.py

<strike>Still needs regression tests (in progress).</strike>
I have:

dnsdist: Implement TLS Session Ticket Keys management for DoH

---

pdns/dnsdist-carbon.cc
pdns/dnsdist-lua-inspection.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/tcpiohandler.cc
pdns/tcpiohandler.hh

Also add stats about TLS session resumption.
Still needs some work, don't merge yet!
I have:

dnsdist: Better use of labels in our DoH prometheus export

---

pdns/dnsdist-lua-rules.cc

dnsdist: Fix the creation order of rules when inserted via SetRules()

---

pdns/dnsdist-web.cc

```
dnsdist_frontend_tlsnewsessions{frontend="127.0.0.1:9443",proto="TCP (DNS over HTTPS)"} 0
dnsdist_frontend_tlsresumptions{frontend="127.0.0.1:9443",proto="TCP (DNS over HTTPS)"} 0
dnsdist_frontend_http_connects{address="127.0.0.1:9443" } 0
dnsdist_frontend_doh_tls_queries{tls="tls10",address="127.0.0.1:9443" } 0
dnsdist_frontend_doh_tls_queries{tls="tls11",address="127.0.0.1:9443" } 0
dnsdist_frontend_doh_tls_queries{tls="tls12",address="127.0.0.1:9443" } 0
dnsdist_frontend_doh_tls_queries{tls="tls13",address="127.0.0.1:9443" } 0
dnsdist_frontend_doh_tls_queries{tls="unknown",address="127.0.0.1:9443" } 0
dnsdist_frontend_doh_http_method_queries{method="get",address="127.0.0.1:9443" } 0
dnsdist_frontend_doh_http_method_queries{method="post",address="127.0.0.1:9443" } 0 …
```

dnsdist: Refactor DoH prometheus metrics again

---

builder-support/debian/recursor/debian-buster/pdns-recursor.postinst
builder-support/debian/recursor/debian-buster/rules
builder-support/debian/recursor/debian-jessie/pdns-recursor.postinst
builder-support/debian/recursor/debian-jessie/rules
builder-support/debian/recursor/debian-stretch/pdns-recursor.postinst
builder-support/debian/recursor/debian-stretch/rules

When run as non-root. we need to make sure rec can read it's config file.
Same as #8352, but  for rec
I have:

rec: chmod/own recursor.conf for the systemd case

---

pdns/dnsname.hh
pdns/dnspacket.cc
pdns/dnspacket.hh
pdns/misc.cc
pdns/misc.hh
pdns/pdns_recursor.cc
pdns/resolve-context.hh
pdns/syncres.hh

A few issues spotted by lgtm and one by coverity (uninitialized field).
The lgtms ones are "rule-of-two" ones. Either define both a copy constructor and an assignment operator, or none.
I  have been explicit by choosing `= delete` or `= default` and in once case (SuffixMatchTree) adding a non-default assignment operator. I wonder though if the non-default copy ct and assignment operator are needed in tis case
I use ` = delete` if the methods are not used atm, and potentially wrong if used.
I have:

LGTM/coverity spotted issues: copy constructors and = operators

---

pdns/pdns_recursor.cc
pdns/recursordist/configure.ac
pdns/recursordist/m4/pdns_enable_nod.m4

Still disabled by default config.
I have:

rec: Build Newly Observerd Domain (NOD) support by default.

---

pdns/pdns_recursor.cc
pdns/rec_channel.hh
pdns/rec_channel_rec.cc

The Linux kernel handles signals for PID 1 processes differently. It
doesn't implement a default handler for some signals such as
SIGTERM/SIGINT.
When running pdns_recursor as a container, this causes a few annoyances.
You can work around those by running your containers with --init or by
installing `tini` inside the container. Or you can handle the signals in
the application itself.
This commit adds signal() handlers for SIGTERM and SIGINT for
pdns_recursor, if we are running as PID 1.
I have:

Add signal handling for SIGTERM and SIGINT in pdns_recursor, if we are PID1

---

pdns/dnsdist-carbon.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdist.hh

- Add per-frontend and per-server response counters
- Fix handling of latency-sum and latency-count in prometheus (found via `promtool check metrics`)
- Fix a typo in 'tcpdownstreamtimeouts' prometheus description (found via `promtool check metrics`)
- Add missing prometheus descriptions for  dnsdist_pool_servers and dnsdist_pool_active_servers (found via `promtool check metrics`)
- Deduplicate DoH frontend names in prometheus
I have:

dnsdist: More prometheus fixes

---

modules/luabackend/reload.cc

Allows building of lua backend on OpenBSD.
Or do we prefet a C++  style cast?
I have:

Printing a pthread_t on platforms having a non-int pthread_id requires a cast to uintptr_t.

---

modules/pipebackend/coprocess.cc

Fix `warning: unused variable ‘first’`
I have:

pipebackend: remove unused variable

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/tcpiohandler.cc
pdns/doh.hh
pdns/tcpiohandler.hh

It used to be that the servers had a much better configuration than the clients, but nowadays we better rely on the clients, as they know whether they have hardware support for a specific algorithm
which might save battery life or improve latency by a large margin.
I have:

dnsdist: Add a 'preferServerCiphers' option for DoH and DoT

---

pdns/statbag.cc
pdns/statbag.hh

During the debugging of #8161, we discovered more moving around of mutexes. This fixes the other place we did that.
I have:

auth statbag: move to std::mutex, avoid copies

---

contrib/assert-equal-DNSMessage/eqdnsmessage.py
regression-tests.auth-py/authtests.py
regression-tests.auth-py/eqdnsmessage.py
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/eqdnsmessage.py
regression-tests.ixfrdist/eqdnsmessage.py
regression-tests.ixfrdist/ixfrdisttests.py
regression-tests.recursor-dnssec/eqdnsmessage.py
regression-tests.recursor-dnssec/recursortests.py

before:
```
AssertionError: <DNS message, ID 38993> != <DNS message, ID 38993>
```
after:
```
AssertionError: <DNS message, ID 46818> != <DNS message, ID 46818>:
--- first
+++ second
@@ -1,10 +1,10 @@
id 46818
-opcode 6
-rcode NOTAUTH
-flags AD CD
+opcode QUERY
+rcode NOERROR
+flags RD
;QUESTION
xpf.tests.powerdns.com. IN A
;ANSWER
;AUTHORITY
;ADDITIONAL
-. 0 IN TYPE65422 \# 14 04117f0000017f000001f8bc14dc
+xpf.tests.powerdns.com. 60 IN TYPE65422 \# 14 04117f0000017f00000100000000
```
(I'm pretty sure the two different names and TTLs on the TYPE65422 line are some dnspython bug.)
Improve `assertEqual` output for differing DNS messages.
Draft until we are happy with the format; then I'll add the same support to our other dnspython-based test suites.
I have:

better assertEqual for dnspython

---

pdns/doh.hh

Otherwise it might remain in the 'set' state and we will never be able to rotate the key.
I have:

dnsdist: Clear the DoH Session Ticket Encryption Key in the ctor

---

pdns/dnsdistdist/docs/reference/config.rst

dnsdist: Add a missing line before SuffixMatchNode's 'versionadded'

---

pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/m4/dnsdist_with_libssl.m4
pdns/dnsdistdist/tcpiohandler.cc
regression-tests.dnsdist/test_TLSSessionResumption.py

This PR has all the non-debug parts of #8389: 
- really disable TLS tickets when asked, since OpenSSL either ignores the `SSL_OP_NO_TICKET` for TLS 1.3 or only disables stateless tickets but implements stateful ones (don't ask) ;
- In the regression tests, make sure that the `openssl s_client` command really wrote a new ticket to the output file when we expect one, and fail otherwise. Also rename the output file so that we can't try to reuse the session file left over by a previous test by mistake. 
I have:

dnsdist: Check that tickets have really been written in the tests, really disable tickets when asked

---

pdns/dnsdist-carbon.cc
pdns/dnsdist-lua-inspection.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist-web.cc
pdns/dnsdist.hh
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/tcpiohandler.cc
pdns/doh.hh
pdns/tcpiohandler.hh

Add metrics about DoH and DoT TLS Session Ticket Encryption Key usage:
- resumption attempts with an unknown key ;
- resumption from an inactive key, most likely after a rotation.
I have:

dnsdist: Add metrics about unknown/inactive TLS ticket keys

---

pdns/dnsdistdist/docs/guides/dynblocks.rst

Fix small typo in the dnsdist DynBlocks guide
I have:

Fix typo in setQueryRate docs

---

pdns/dnsdist-lua-inspection.cc

Also reflects that the number of TCP worker threads no longer represent the number of TCP clients.
I have:

dnsdist: Fix formatting in showTCPStats()

---

pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/doh.cc
regression-tests.dnsdist/test_Caching.py
regression-tests.dnsdist/test_DOH.py
regression-tests.dnsdist/test_TLS.py

It turns out that the packet cache suffered a regression since 1.3.0: the buffer allocated to incoming queries, and used to store the cached response if any, was not big enough to allow large (>1500 bytes for UDP, > 512 bytes for TCP/DoT/DoH) answers to be retrieved. We can now always retrieve entries up to 4096 bytes.
We also cached entries larger than what we could actually retrieve, we now no longer cache entries larger than 4096 bytes. 
I have:

dnsdist: Fix the caching of large entries

---

contrib/DNSDistLogActionReader.py
pdns/dnsdist-lua-actions.cc
pdns/dnsdistdist/docs/rules-actions.rst

* Adds an option to include timestamps ;
* and a second one to log to stdout in non-verbose mode ;
* and the binary format now includes an optional timestamp, the query ID, the qname, the qtype, the source address and port.
This PR also adds a small python snippet to the contrib/ directory to be able to read the binary logs.
Closes #8390.
I have:

dnsdist: Add more options to LogAction (non-verbose mode, timestamps)

---

pdns/dnsdist-lua.cc

`d_ticketsKeyRotationDelay` is now in the TLSConfig object, since #8383, but #8406 collided with that change.
I have:

dnsdist: Fix merge issue (d_ticketsKeyRotationDelay)

---

docs/http-api/swagger/authoritative-api-swagger.yaml
pdns/ws-auth.cc

`disabled` defaults to false.
I have:

auth API: make disabled optional for Record

---

builder-support/dockerfiles/Dockerfile.target.centos-8
builder-support/specs/dnsdist.spec
builder-support/specs/pdns-recursor.spec
builder-support/specs/pdns.spec

This produces packages for EL8 for all products.
```
builder/tmp/4.3.0-alpha1.288.centos8pkgs.g0c8b25175.dirty/centos-8/dist/x86_64/pdns-recursor-4.3.0-0.alpha1.centos8pkgs.288.g0c8b25175.dirty.1pdns.el8.x86_64.rpm
builder/tmp/4.3.0-alpha1.288.centos8pkgs.g0c8b25175.dirty/centos-8/dist/x86_64/pdns-recursor-debuginfo-4.3.0-0.alpha1.centos8pkgs.288.g0c8b25175.dirty.1pdns.el8.x86_64.rpm
builder/tmp/4.3.0-alpha1.288.centos8pkgs.g0c8b25175.dirty/centos-8/dist/x86_64/pdns-recursor-debugsource-4.3.0-0.alpha1.centos8pkgs.288.g0c8b25175.dirty.1pdns.el8.x86_64.rpm
builder/tmp/4.3.0-alpha1.288.centos8pkgs.g0c8b25175.dirty/centos-8/dist/pdns-recursor-4.3.0-0.alpha1.centos8pkgs.288.g0c8b25175.dirty.1pdns.el8.src.rpm
builder/tmp/1.4.0-rc3.68.centos8pkgs.g0c8b25175.dirty/centos-8/dist/x86_64/dnsdist-debu …
```

Add CentOS 8 as builder target

---

pdns/lua-recursor4.cc

Before:
```
;; QUESTION SECTION:
;4.2.a.7.6.5.3.6.f.f.7.7.b.1.2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa. IN PTR
;; ANSWER SECTION:
4.2.a.7.6.5.3.6.f.f.7.7.b.1.2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa. 82726	IN PTR server-99-86-122-36.dub2.r.cloudfront.net.
```
After:
```
;; QUESTION SECTION:
;4.2.a.7.6.5.3.6.f.f.7.7.b.1.2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa. IN PTR
;; ANSWER SECTION:
4.2.a.7.6.5.3.6.f.f.7.7.b.1.2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa. 0 IN CNAME 36.122.86.99.in-addr.arpa.
36.122.86.99.in-addr.arpa. 81396 IN	PTR	server-99-86-122-36.dub2.r.cloudfront.net.
```
requested by @tuxis-ie
I have:

dns64: stop hiding PTR indirection

---

pdns/dnsdistdist/docs/rules-actions.rst

This fixes the `versionadded` currently visible at https://dnsdist.org/rules-actions.html#HTTPStatusAction
I have:

dnsdist docs: fix versionadded formatting

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc2.cc
pdns/syncres.cc
pdns/syncres.hh

This commit implements the "NXDOMAIN: There Really Is Nothing Underneath".
When enabled (the default), the SyncRes will check the negative cache if
there exists a higher denied name and uses that data to send an NXDOMAIN
to the client. In essence, it is a more aggressive version of
root-nx-trust (which could be removed in the future).
There are several advantages:
* We potentially send fewer queries to the internet
* The record cache is not "polluted" with useless NXDOMAINs
I have:

Implement RFC 8020 "NXDOMAIN: There Really Is Nothing Underneath"

---

.circleci/config.yml
build-scripts/travis.sh
docs/manpages/sdig.1.rst
pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/sdig.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_OOOTCP.py
regression-tests.recursor-dnssec/test_SimpleTCP.py

Fixes #8358 
Answers are sent out the moment the become available, so not necessarily in the
same order as received. There's a limit on how many queries per TCP
induced connection we may have in flight.
Only very lightly tested!
Includes an sdig hack to read multiple queries from a file.
I have:

rec: Allow multiple simultaneous incoming TCP queries over a connection

---

pdns/dnsdistdist/doh.cc
pdns/doh.hh

It turns out that, at least when testing with `ASAN` enabled, we sometimes trigger use-after-free detection because we get the response from the backend, send it to the client then delete the
object before the `send()` call to the backend even returned.
I have:

dnsdist: Implement ref counting for the DOHUnit object

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/libssl.cc
pdns/dnsdistdist/m4/dnsdist_with_libssl.m4
pdns/doh.hh
pdns/libssl.hh

This PR:
- moves the `DoH` ticket keys logic into the `DOHAcceptContext` object, with the OCSP responses and SSL context objects ;
- adds support dumping TLS keys via the new `keyLogFile` directive.
The new `keyLogFile` feature is similar to what various programs do when the `SSLKEYLOGFILE` environment variable is set, and uses the format described in:
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format
I have:

dnsdist: Add support dumping TLS keys via keyLogFile

---

docs/manpages/sdig.1.rst
pdns/sdig.cc

```
$ ./sdig https://doh.powerdns.org/query 0 version.bind TXT class 3
Reply to question for qname='version.bind.', qtype=TXT
Rcode: 0 (No Error), RD: 0, QR: 1, TC: 0, AA: 0, opcode: 0
0	version.bind.	CHAOS	TXT	86400	"PowerDNS Recursor 4.1.14 (built Jun 13 2019 10:38:20 by root@9c4caadbc9e7)"
```
I have:

sdig: make query class selectable

---

builder-support/specs/pdns-recursor.init

Looks like everything was updated except this, and now the 4.3.0 master packages (pdns-recursor-4.3.0-0.alpha1.master.382.g479525a52.1pdns.el6.x86_64) don't run without making the directory first.
I have *not* checked what 4.2.0 is using. 
@pieterlexis  can you review?
I have:

rec: Update CentOS 6 init script

---

pdns/ixfrdist.cc
pdns/ixfrutils.cc
pdns/ixfrutils.hh
pdns/ixplore.cc

We noticed `ixfrdist` crashing while trying to read empty zonefiles from its storage. This PR avoids that crash, and causes a fresh fetch from the master in such cases. 
~This PR does not prevent the writing of empty files.~ now it does
~Should this PR remove empty/unparseable files when spotted?~ now it does
I have:

Ixfrdist: handle reading of empty files gracefully

---

pdns/dnsdist.cc
pdns/dnsdistdist/doh.cc
pdns/doh.hh

We need to increment the reference counter even before sending the
query to the backend, as soon as we copy a reference into the `IDState`.
Because:
- that makes sense anyway, we are storing a new copy ; 
- otherwise, in the unlikely event where we reuse the `IDState` before the query has been sent to the backend we might free the `DOHUnit` before the reference counter has been incremented and cause a double-free.
This is why we love smart pointers, too bad that we need to deal with raw C pointers a bit in that code..
I have:

dnsdist: Increment the DOHUnit ref count when it's set in the IDState

---

.circleci/config.yml
build-scripts/travis.sh
regression-tests.dnsdist/test_Prometheus.py

These tests are disabled on Travis because it doesn't have the prometheus package.
I have:

dnsdist: Add regression tests for our prometheus export

---

modules/geoipbackend/geoipbackend.cc
modules/geoipbackend/geoipbackend.hh

Consistently use Netmask instead of string and boolean in API. Fixes #8438 
I have:

geoipbackend: Use Netmask instead of string

---

regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_OOOTCP.py

CircleCI is running a recursor on 127.0.0.11 and redirects packets to it,
eating the packets that were targeted for the test auth on 127.0.0.11.
I have:

rec: Fix OOO tests on CircleCI and enable DNSSEC for them as well.

---

pdns/pdns_recursor.cc
pdns/recursordist/test-syncres_cc.cc
pdns/reczones.cc
pdns/syncres.cc
pdns/syncres.hh

Do not only put the root hints into the cache, but also make sure the NS records of the top level domains of the *names* of the root servers are in the cache. We need these to correctly determine the security status of that specific domain (normally `root-servers.net`). This is caused by the accident that the root servers are authoritative for `root-servers.net`, and some implementations reply not with a delegation on a `root-servers.net` `DS` query, but with a `NODATA` response (the domain is unsigned).
Discussed with @Habbie and @pieterlexis 
I have:

rec: prime NS records of root-servers.net parent (.net)

---

pdns/reczones.cc

This fixes an infinite recursion introduced by a test with a custom hints file. The wiping code was wiping . NS in that case.
I have:

rec: Do not wipe . NS records from cache

---

pdns/recursordist/test-mtasker.cc
pdns/recursordist/test-recursorcache_cc.cc
pdns/test-packetcache_cc.cc

This PR gets rid of a deprecation warning with Boost 1.71.0.
I have:

Remove deprecated floating_point_comparison.hpp header

---

builder-support/debian/recursor/debian-buster/lua-config/rootkeys.lua
builder-support/debian/recursor/debian-buster/pdns-recursor.dirs
builder-support/debian/recursor/debian-buster/recursor.lua
builder-support/debian/recursor/debian-buster/rules
builder-support/debian/recursor/debian-jessie/lua-config/rootkeys.lua
builder-support/debian/recursor/debian-jessie/pdns-recursor.dirs
builder-support/debian/recursor/debian-jessie/recursor.lua
builder-support/debian/recursor/debian-jessie/rules
builder-support/debian/recursor/debian-stretch/lua-config/rootkeys.lua
builder-support/debian/recursor/debian-stretch/pdns-recursor.dirs
builder-support/debian/recursor/debian-stretch/recursor.lua
builder-support/debian/recursor/debian-stretch/rules

This also automatically reloads them each 24 hours by default. A similar method was implemented by @zeha in Debian downstream for recursor 4.1.x.
@zeha you might want to port this to downstream (in 4.2.0+) as well.
I have:

Deb: Load DNSSEC Keys from disk by default

---

pdns/recursordist/Makefile.am
pdns/recursordist/test-rpzloader_cc.cc
pdns/rpzloader.cc
pdns/rpzloader.hh

While there, add unittest for translating rpz names into netmasks
(cherry picked from commit 301148e6d77e7cf8aed3b1b174bf6dbbeae7dc67)
I have:

Rec: backport to 4.2.x: Fix #8338: Issue with "zz" abbreviation for IPv6 RPZ triggers

---

docs/settings.rst
modules/bindbackend/bindbackend2.cc
pdns/comfun.cc
pdns/common_startup.cc
pdns/fuzz_zoneparsertng.cc
pdns/ixfrutils.cc
pdns/pdns_recursor.cc
pdns/pdnsutil.cc
pdns/recursordist/docs/settings.rst
pdns/reczones.cc
pdns/rpzloader.cc
pdns/validate-recursor.cc
pdns/ws-auth.cc
pdns/zone2json.cc
pdns/zone2ldap.cc
pdns/zone2sql.cc
pdns/zoneparser-tng.cc
pdns/zoneparser-tng.hh

A very large number of steps in one bind-style zone could trigger a lot of CPU and memory usage. This is not really a problem in most of the deployment scenarios but OSS-Fuzz has recently figured out how to trigger it.  
I have:

Add a parameter to limit the number of '$GENERATE' steps

---

pdns/pdnsutil.cc
pdns/rfc2136handler.cc
regression-tests/tests/1dyndns-content-casemix/command
regression-tests/tests/1dyndns-content-casemix/description
regression-tests/tests/1dyndns-content-casemix/expected_result
regression-tests/tests/1dyndns-content-casemix/skip.nodyndns

Improves #8217.
* pdnsutil: compare TXT records case sensitively when checking for duplicates
* rfc2136: compare PTR/MX/SRV case INsensitively when checking for duplicates
I have:

rfc2136, pdnsutil: somewhat improve duplicate record handling

---

pdns/dnsdist.cc
pdns/recursordist/docs/settings.rst

Fix a typo found by Debian's lintian.
I have:

Fix typo: settting to setting

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc2.cc
pdns/syncres.cc
pdns/syncres.hh

Only use DNSSEC validated entries for 8020 by default.
Note that the unit test diff looks weird, but I'm actually adding one new test and changing the constants of the others to unsigned. git diff makes it a weird maze.
We could add code trying to validate Indeterminate cached NXDs, but I left that as an exercise for the moment.
I have:

Rec: do RFC 8020 only if cache entry is dnssec validated

---

pdns/pdns_recursor.cc
pdns/rec_channel.cc
pdns/rec_channel.hh
pdns/rec_channel_rec.cc
pdns/recursordist/docs/settings.rst

Rec 8020 docs fix

---

pdns/pdns_recursor.cc
pdns/rec_channel.cc
pdns/rec_channel.hh
pdns/rec_channel_rec.cc

This is safer since the atexit handler is not ran while threads are
still active. Also, when using valgrind we get more clean leak reports.
I have:

Make threads run until asked to stop.

---

pdns/dnsdistdist/docs/reference/config.rst
pdns/libssl.hh

This setting should only be set when all ciphers offered by the server are considered secure, and our default suite still has a few options offered for compatibility reasons, which might not be as secure as other alternatives.
Apparently this also causes issue for some clients, even though it should not matter.
I have:

dnsdist: Prefer the cipher suite from the server by default (DoH, DoT)

---

pdns/dnsdist-dynblocks.hh
pdns/dnsdist-lua-inspection.cc

This PR adds bindings to access the `noerrors` and `drops` members of the `StatNode` object from `Lua`. It also fixes the accounting of actively discovered timeouts in that same object.
I have:

dnsdist: Add bindings for the noerrors and drops members of StatNode

---

pdns/pdns_recursor.cc
pdns/rec_channel.cc
pdns/rec_channel.hh
pdns/rec_channel_rec.cc

This is safer since the atexit handler is not ran while threads are
still active. Also, when using valgrind we get more clean leak reports.
Retry of the accidentally merged #8518 that was reverted.
I have:

rec: Make threads run until asked to stop.

---

pdns/dnsdist-console.cc

I'm not sure these descriptions are even used anywhere, but if they are show the new default.
I have:

dnsdist: Update dnsdist-console.cc

---

pdns/dnsdist-dynblocks.hh
pdns/dnsdist-lua.cc

This does not change the existing behavior since we are doing a case-insensitive comparison but it's nicer when generating metrics about the dynamic block rules.
I have:

dnsdist: Lowercase the name blocked by a SMT dynamic block

---

docs/http-api/swagger/authoritative-api-swagger.yaml
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

Stop backend creation in a tight loop when listing all domains over the API. Should improve performance considerably. Also notes in the docs that "list" is incomplete.
I have:

API: do not return dnssec info in domain list

---

pdns/recursordist/Makefile.am
pdns/recursordist/test-rpzloader_cc.cc
pdns/rpzloader.cc
pdns/rpzloader.hh

rec: Backport 8340 to rec 4.1.x: issue with "zz" abbreviation for IPv6 RPZ triggers

---

pdns/rec-snmp.cc
pdns/rec_channel_rec.cc
pdns/recursordist/RECURSOR-MIB.txt
pdns/recursordist/docs/metrics.rst
pdns/recursordist/rec_metrics.hh
pdns/syncres.cc
pdns/syncres.hh

Keep a counter of the number of outqueries that resort to 'use the full qname'
I have only tested rec_control gets for this so far.
Thoughts?
I have:

rec: qname-minimization metrics 

---

docs/http-api/swagger/authoritative-api-swagger.yaml
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

auth 4.2.x: API: do not return dnssec info in domain list

---

pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/docs/manpages/rec_control.1.rst
pdns/syncres.cc
pdns/syncres.hh

SyncRes thread local storage includes a map of failed auths which was
only cleaned if a specific IP was contacted again and that contact
succeeded. Persistent failing auths or auths that are never tried
again remained in the map.
While here add code to dump the failed servers map. Might (partially?)
solve #7771.
I have:

Rec: Purge map of failed auths periodically by keeping a last changed timestamp.

---

pdns/syncres.cc

Coverity noted the missing error check, but we also do not want to leak an fd if `fdopen` fails.
I have:

rec: check return value of dup() and avoid fd leak if if fdopen() fails

---

pdns/dnsdistdist/docs/guides/dns-over-https.rst

In #8263 DoH over unencrypted HTTP got implemented.
In #8540 the general usage got explained but this feature did not get mentioned.
I think it might be common that people will want to use a reverse proxy in front of dnsdist.
We use dnsdist in this form with the following config:
```
addDOHLocal("127.0.0.1:8053", nil, nil, "/", { reusePort=true })
```
I extended the guide accordingly.
PS: The formatting in the pdf looks weird atm. The only difference to the "correctly formatted" version seems to be the "::" at the end of the line ahead of the code block.
I added that as well.

[DOC dnsdist] Extend guide for DoH over HTTP

---

pdns/dnsdist-dynblocks.hh
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-rules.cc
pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/rec_channel_rec.cc
pdns/sholder.hh

This PR prevents unnecessary copies when adding/updating rules in dnsdist, and possibly for some configuration updates of the recursor as well. I only measured the dnsdist case, to be clear.
I have:

Use move semantics when updating the content of the StateHolder

---

build-scripts/travis.sh
regression-tests.dnsdist/test_Basics.py
regression-tests.dnsdist/test_CDB.py
regression-tests.dnsdist/test_DOH.py
regression-tests.dnsdist/test_LMDB.py
regression-tests.dnsdist/test_OCSP.py
regression-tests.dnsdist/test_Prometheus.py
regression-tests.dnsdist/test_TLSSessionResumption.py
regression-tests.dnsdist/test_Tags.py

It provides a better granularity, allowing the OCSP tests to be run for DoT even in the absence of DoH support.
I have:

dnsdist: Use env toggles to disable some regression tests in Travis

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/tcpiohandler.cc

The feedback from our users is that the OpenSSL provider is faster and more stable. We also provide better Session Ticket Keys rotation options with OpenSSL.
I have:

dnsdist: Switch the default DoT provider from GnuTLS to OpenSSL

---

modules/lmdbbackend/lmdb-safe.cc
modules/lmdbbackend/lmdb-safe.hh
modules/lmdbbackend/lmdb-typed.cc
modules/lmdbbackend/lmdb-typed.hh
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
pdns/pdnsutil.cc
pdns/ws-auth.cc

Replace the lmdb backend in 4.2.x with the current, a lot more functional, master version.
I have:

Backport lmdb backend from 780ae3f to 4.2.x

---

ext/yahttp/yahttp/reqresp.cpp

cc @cmouse 
YaHTTP did not accept a header like
```
Accept:application/json
```
Which should be allowed according to RFC 7230:
>    Each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.
I have:

YAHTTP: Accept headers without spaces

---

ext/yahttp/yahttp/reqresp.cpp

backport from #8562 
(cherry picked from commit 48180b07ee949a9ddda1063815ce1da403d63e8a)
I have:

auth 4.2.x: YAHTTP: Accept headers without spaces

---

Makefile.am
build-scripts/format-code

Leaving the file untouched if not changed and report if it was changed.
Callable as separate script or with `make format-code` in toplevel
to reformat .cc and .hh files in the modules and pdns dirs.
I have:

Add script to format code, 

---

pdns/auth-packetcache.cc
pdns/auth-packetcache.hh
pdns/auth-querycache.cc
pdns/auth-querycache.hh
pdns/cachecleaner.hh
pdns/dbdnsseckeeper.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsseckeeper.hh
pdns/recpacketcache.cc
pdns/recpacketcache.hh
pdns/recursor_cache.cc
pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh

Numbered indexes are hard to read and error prone. Specifying the tag in the call isn't a big burden and tells the reader which index is used. 
I have:

Avoid having to use numbered indexes by given all indexes a tag

---

pdns/auth-packetcache.cc
pdns/auth-packetcache.hh
pdns/auth-querycache.cc
pdns/auth-querycache.hh
pdns/dnscrypt.cc
pdns/dnscrypt.hh
pdns/dnsdist-cache.hh
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-kvs.cc
pdns/dnsdistdist/dnsdist-kvs.hh
pdns/dnsdistdist/dnsdist-rules.hh
pdns/test-lock_hh.cc

On some platforms, pthread_rwlock_init() not only inits mem, but also
acquires resources.
I have:

pthread_rwlock_init() should be matched by pthread_rwlock_destroy()

---

docs/backends/pipe.rst
docs/lua-records/reference/netmask.rst
docs/upgrading.rst
modules/geoipbackend/geoipbackend.cc
pdns/calidns.cc
pdns/dnspacket.cc
pdns/iputils.hh
pdns/lua-base4.cc
pdns/pdns_recursor.cc
pdns/recursordist/docs/lua-scripting/netmask.rst
pdns/recursordist/docs/upgrade.rst
pdns/syncres.cc
pdns/test-iputils_hh.cc

This changes the Netmask class to use isIPv6 instead of isIpv6.
I have:

global: Normalize isIpv4/6 to isIPv4/6

---

docs/manpages/pdnsutil.1.rst

Add increase-serial to pdnsutil doc, description is from `pdnsutil --help`
I have:

Add increase-serial to pdnsutil doc

---

regression-tests.dnsdist/test_TLSSessionResumption.py

In TLS 1.3 the server sends the TLS ticket after the handshake has been completed, but not necessarily right after that. Ideally we would like to wait for up to several seconds, but stop waiting as soon as we receive a ticket. Unfortunately we can't ask that from `openssl s_client`, and we are currently not always waiting long enough to get a ticket, leading to spurious failures.
Let's try waiting a bit longer to see if that helps.
I have:

dnsdist: Wait longer for the TLS ticket to arrive in our tests

---

builder-support/dockerfiles/Dockerfile.debbuild
builder-support/dockerfiles/Dockerfile.rpmbuild
builder-support/dockerfiles/Dockerfile.target.sdist

Without this, running something like `builder/build.sh centos-7` (without any `-m`) will spend a lot of time, and then fail confusingly.
Only lightly tested. PRed because @pieterlexis and I half-solved this problem 3 times before but it never landed.
I have:

builder: demand user chooses a module except when building docs

---

pdns/ws-auth.cc

While working with openapi-codegen generated code, it seems that the auth API might be a bit too strict when it comes to the createZone call.
This PR addresses 2 of these issues.
I have:

Auth API: be a bit more lenient

---

docs/manpages/sdig.1.rst
pdns/sdig.cc

~The stdin feature needs docs~. Manpage updated.
~The non-zero exit feature may need regression test adjustments.~ Tests pass!
I have:

sdig: decode DNS packets from stdin; exit non-zero on failure

---

pdns/auth-packetcache.cc
pdns/auth-packetcache.hh
pdns/auth-querycache.cc
pdns/auth-querycache.hh

Alternatively, we could introduce a copy constructor like dnsdist does; but we do not have dynamic resize in auth. So setup the cache size on construct.
I have:

Avoid copying of pthread_rwlock_t

---

pdns/dnssecinfra.cc
pdns/dnssecinfra.hh
pdns/dnssecsigner.cc
pdns/pdnsutil.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc.hh
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc5.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/syncres.cc
pdns/test-signers.cc
pdns/validate.cc
pdns/validate.hh

These duplicates should not exist but they do happen in the wild.
Since we need to sort the RRs anyway, let's be nice and remove duplicates as well.
We used to store the records in a vector and then sort the vector, we now store them directly into a sorted set. The overhead should be negligible since the number of records is very small. 
This fix is intended for the recursor where we validate records received from the outside, and should not have any visible impact for the authoritative server unless we somehow compute a signature for a RRSet containing duplicated records.
I have:

Remove duplicate RRs inside a RRSet when computing the signature

---

pdns/ws-auth.cc

Clear the caches for the entire zone after a patch operation (was apex only)
The default default-api-rectify setting was ignored in patchZone(). Rectify only took place when the API-RECTIFY metadata was set to "1".
I have:

Auth: api: cache and rectify fixes in patchZone()

---

pdns/dnsparser.cc

PowerDNS with lmdb, compiled by mock, is crashing regularly.
```
Dec  6 12:36:05 ns pdns_server[21249]: Dec 06 12:36:05 Got a signal 6, attempting to print trace:
Dec  6 12:36:05 ns pdns_server[21249]: Dec 06 12:36:05 /usr/sbin/pdns_server(+0x2d470a) [0x55c94ea2070a]
Dec  6 12:36:05 ns pdns_server[21249]: Dec 06 12:36:05 /lib64/libc.so.6(+0x379c0) [0x7fc0bf8b79c0]
Dec  6 12:36:05 ns pdns_server[21249]: Dec 06 12:36:05 /lib64/libc.so.6(gsignal+0x10f) [0x7fc0bf8b793f]
Dec  6 12:36:05 ns pdns_server[21249]: Dec 06 12:36:05 /lib64/libc.so.6(abort+0x127) [0x7fc0bf8a1c95]
Dec  6 12:36:05 ns pdns_server[21249]: Dec 06 12:36:05 /usr/sbin/pdns_server(+0x1591f8) [0x55c94e8a51f8]
Dec  6 12:36:05 ns pdns_server[21249]: Dec 06 12:36:05 /usr/sbin/pdns_server(_ZN16DNSRecordContent11unserializeERK7DNSName …
```

Backport fix out-of-bound access for zero length "serialized" string.

---

docs/lua-records/functions.rst
docs/settings.rst
pdns/common_startup.cc
pdns/common_startup.hh
pdns/lua-record.cc
pdns/minicurl.cc
pdns/minicurl.hh
regression-tests.auth-py/authtests.py

This PR puts TCP/IP and URL health checks in a single thread (instead of 1 thread per check).
This also removes checks that have been unused for a given period of time (currently 1 hour). This will prevent checks from modified or deleted records to keep being performed by the authoritative server (fix #7988).
I have:

auth: refactor health checks monitoring done from LUA records

---

build-scripts/docker/generate-repo-files.sh

Updated for the distros and versions that are generated for the auth-4.2.1+ packages.
Files for Centos 8 do not seem to be correct since they give this error:
```
$ docker build --no-cache --pull --file Dockerfile.auth-42.centos-8 .
Sending build context to Docker daemon  23.55kB
Step 1/5 : FROM centos:8
8: Pulling from library/centos
Digest: sha256:f94c1d992c193b3dc09e297ffd54d8a4f1dc946c37cbeceb26d35ce1647f88d9
Status: Image is up to date for centos:8
---> 0f3e07c0138f
Step 2/5 : RUN yum install -y epel-release yum-plugin-priorities
---> Running in 791b4b6b270f
CentOS-8 - AppStream                            3.2 MB/s | 6.3 MB     00:01    
CentOS-8 - Base                                 7.4 MB/s | 7.9 MB     00:01    
CentOS-8 - Extras                               7.3 kB/s | 2.1 kB …
```

Update docker repo script for auth-4.2.1.

---

pdns/pdns_recursor.cc
pdns/recursordist/test-syncres_cc2.cc
pdns/syncres.cc
pdns/syncres.hh

- Use `multi_index` for all time based data structures except `nsSpeeds`. That will come later.
- `nsSpeeds` *is* cleaned up up to be more memory-compact and to use `float` instead of `double` consistently.
- some cleanup of the time based cleanup condition in in housekeeping. Adding the thread id make no sense to me am at all. Not testing on a `time_t` only while spread out the cleanup in various threads to be not simultaneously.
- One condition in the throttle class in `syncres.hh` is marked ????, I copied it from the original code, but I have a hard time seeing this is the right condition.
I have:

Rec: better time based data structures

---

pdns/auth-packetcache.cc

This avoids:
```
In file included from auth-packetcache.cc:25:
auth-packetcache.hh: In constructor ‘AuthPacketCache::AuthPacketCache(size_t)’:
auth-packetcache.hh:136:10: warning: ‘AuthPacketCache::d_lastclean’ will be initialized after [-Wreorder]
time_t d_lastclean; // doesn't need to be atomic
^~~~~~~~~~~
auth-packetcache.hh:120:20: warning:   ‘std::vector<AuthPacketCache::MapCombo> AuthPacketCache::d_maps’ [-Wreorder]
vector<MapCombo> d_maps;
^~~~~~
auth-packetcache.cc:33:1: warning:   when initialized here [-Wreorder]
AuthPacketCache::AuthPacketCache(size_t mapsCount): d_lastclean(time(nullptr)), d_maps(mapsCount)
^~~~~~~~~~~~~~~
```
I have:

auth packetcache: sync init order with member order

---

regression-tests.dnsdist/requirements.txt

Otherwise we need libsodium >= 1.0.12 (required by this change: https://github.com/saltstack/libnacl/commit/8c8b2f8bc05a5b67f39acf9a6bc0bef6fa839166) and we don't have it in Trusty, which we still use in Travis.
I have:

dnsdist: Require Python libnacl < 1.7

---

pdns/syncres.cc

QName Minimization consults the cache first to see work needs tobe done. Via doCacheCheck() this can lead to a call to computeZoneCuts()
which might/does not work properly on only cached records, so always
make sure it can go out if needed. Should fix #8642.
I have:

rec: fix wrong zoneCuts caused by cache only lookup

---

pdns/dnsdistdist/docs/rules-actions.rst

Unless I'm mistaken you need to set this to `false` to have stdout logging in non-verbose mode.
I have:

dnsdist: Update rules-actions.rst

---

pdns/ws-auth.cc

Otherwise `GSQLBackend::getTSIGKey()` will try to match the algorithm in `keyAlgo` if it's set, which will prevent retrieving a key with a different algorithm that the previous one.
Untested, but will hopefully fix #8645.
I have:

auth: Clear the TSIG algo between iterations in the API

---

pdns/packethandler.cc

Explicitly set the port for outgoing queries to the SuperMaster when using trusted-notification-proxy and EDNS Client Subnet
Closes #8584
I have:

Fix trusted-notification-proxy port

---

pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc5.cc

While there, explicitly init qname-minimization in test-syncres to
false.  The current code gave the impression it was turned on by
default for unit tests.  We have a lot of test that count queries,
and that is highly depedent on qname minimization being on or off.
I have:

rec: Introduce test for PR 8648.

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/guides/serverselection.rst

This PR adds support for a bounded-load version of the consistent hashing policy, preventing one server from receiving much more queries than the others, even if the distribution of queries is not perfect.
This "consistent hashing with bounded loads" algorithm is enabled by setting `setConsistentHashingBalancingFactor()` to a value other than 0, which is the default. This value is the maximum number of outstanding queries that a given server can have at a given time, as a ratio of the average number of outstanding queries for all the active servers in the pool.
For example, setting `setConsistentHashingBalancingFactor(1.5)` means that no server will be allowed to have more outstanding queries than 1.5 times the average of all outstanding queries in the pool. The algorithm will try to …

dnsdist: Add bounded loads to the consistent hashing policy

---

regression-tests.dnsdist/requirements.txt

Otherwise we need libsodium >= 1.0.12 (required by this change:
https://github.com/saltstack/libnacl/commit/8c8b2f8bc05a5b67f39acf9a6bc0bef6fa839166
) and we don't have it in Trusty, which we still use in Travis.
(cherry picked from commit 1f474f69cc45af37646513618badd7bfa06741fd)
I have:

rec: backport to 4.3.x: dnsdist: Require Python libnacl < 1.7

---

ext/yahttp/yahttp/reqresp.cpp

From an e-mail from Jeff Law <law@redhat.com>:
Subject: Minor problem in pdns, dnsdist and pdns-recursor packages in Fedora
[ All three packages have embedded copies of the same problematic code
and the same patch fixes all three. ]
Red Hat's compiler team continues to try and be proactive in identifying
issues that will arise as a result of the introduction of a new GCC
release into Fedora each spring.
You're being contacted because a package you maintain in Fedora is going
to fail to build with gcc-10 in the spring.  Yes, I know that's a few
months away, but it's far easier to fix this stuff proactively now than
wait.
Fixing it now also means that your package will continue to be built
with testing versions of gcc-10 as we proceed through the development
process thus allowing additional …

Fix build with gcc-10

---

builder-support/debian/recursor/debian-buster/pdns-recursor.postinst
builder-support/debian/recursor/debian-jessie/pdns-recursor.postinst
builder-support/debian/recursor/debian-stretch/pdns-recursor.postinst

We manage the `pdns` user on our Debian systems manually, and we are having issues with the pdns-recursor postinst script failing because we use a non-system uid for it.
I simply copied the if statements [from the pdns-server postinst script](https://github.com/PowerDNS/pdns/blob/e963f425a360f6348102208308ffdcd24e8d5e09/builder-support/debian/authoritative/debian-buster/pdns-server.postinst) to the pdns-recursor ones so that the script doesn't try to create the user if it already exists.
I have:

rec: debian postinst / do not fail on user creation if it already exists

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst

This is enough for rev v6 queries with cold cache with validations and qname minimization enabled.  Fixes #8646.
These cases (with cold cache) might still take more than 5s though, so timeouts can still happen.
I have:

rec: Bump max-qperq default to 100 

---

pdns/pdns_recursor.cc

This is a fix for https://github.com/PowerDNS/pdns/issues/8676 where `dont-throttle-names` and `dont-throttle-netmasks` are not parsed as a comma separated list
I have:

parsing `dont-throttle-names` and `dont-throttle-netmasks` as comma separated lists

---

pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc5.cc
pdns/syncres.cc

Including unit test (which is PR #8667)
I have:

rec: backport 8648 to rec 4.3.x: fix wrong zoneCuts caused by cache only lookup

---

pdns/syncres.cc
pdns/validate.cc

So we should not set the `AD` bit for a `DS` `NODATA` or a `NXDOMAIN` answer proved by an `Opt-Out` `NSEC3` `RR`.
Hopefully fixes #8664.
Could use regression tests!
I have:

rec: An Opt-Out NSEC3 RR only proves that there is no secure delegation

---

pdns/syncres.hh

(cherry picked from commit 7b07a07cce7b9476ef602b9e9b35d30a239bdc96)
I have:

rec: backport 8694 to 4.3.x: Fix ./syncres.hh:228:20: warning: initialized lambda captures are a C++14 extension

---

pdns/syncres.cc
pdns/validate.cc

(cherry picked from commit 18c8faae6c67f734583c5c881d0d083d3253b49e)
I have:

rec: backport 8665 to 4.3.x: An Opt-Out NSEC3 RR only proves that there is no secure delegation

---

pdns/pdns_recursor.cc

(cherry picked from commit 5285831402f3f3a209c16cb3bd743eea640cf894)
I have:

rec: backport 8684 to 4.2.x: parsing `dont-throttle-names` and `dont-throttle-netmasks` as comma separated lists

---

pdns/pdns_recursor.cc

rec: backport 8684 to 4.3.x: parsing `dont-throttle-names` and `dont-throttle-netmasks` as comma separated lists

---

builder-support/debian/recursor/debian-buster/pdns-recursor.postinst
builder-support/debian/recursor/debian-jessie/pdns-recursor.postinst
builder-support/debian/recursor/debian-stretch/pdns-recursor.postinst

(cherry picked from commit fddad2718fb994d4fd016c03e1e05ef6c67aae14)
I have:

rec: backport 8639 to 4.2.x: debian postinst / do not fail on user creation if it already exists

---

builder-support/debian/recursor/debian-buster/pdns-recursor.postinst
builder-support/debian/recursor/debian-jessie/pdns-recursor.postinst
builder-support/debian/recursor/debian-stretch/pdns-recursor.postinst

(cherry picked from commit fddad2718fb994d4fd016c03e1e05ef6c67aae14)
I have:

rec: backport 8639 to 4.3.x: debian postinst / do not fail on user creation if it already exists

---

contrib/ProtobufLogger.py
pdns/dnsdistdist/dnsdist-lua-bindings-protobuf.cc
pdns/dnsdistdist/docs/reference/protobuf.rst
pdns/dnsmessage.proto
pdns/pdns_recursor.cc
pdns/protobuf.cc
pdns/protobuf.hh

- for all protobuf messages in dnsdist ;
- for incoming queries / outgoing responses in the recursor.
I have:

Add the source and destination ports to the protobuf msg

---

pdns/syncres.hh

Fix ./syncres.hh:228:20: warning: initialized lambda captures are a C++14 extension

---

pdns/dnsdist-dynblocks.hh
pdns/dnsdist-lua-inspection.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-dynblocks.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc
regression-tests.dnsdist/test_DynBlocks.py

Implements a dynamic blocking mechanism based on the ratio of a given rcode over all responses, as suggested in https://github.com/PowerDNS/pdns/issues/8045.
Could use a good review.
I have:

dnsdist: Implement dynamic blocking on ratio of rcode/total responses

---

pdns/dnsdist-lua.cc
pdns/dnsdist-lua.hh
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-lua-bindings-protobuf.cc
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_DOH.py
regression-tests.dnsdist/test_Routing.py

In client (and single command) mode we do not care too much about parsing the syntax of commands that do not relate to the console itself, and we do not want to create sockets and touch files on the local filesystem while parsing the configuration.
In check-config mode, however, we want to parse as much configuration directives as possible, and we to generate some files that might be required to validate the rest of the configuration (DNSCrypt certificates and keys, OCSP responses..).
This PR separates the two modes and tries to skip only the following parts when in check-config mode, compared to 'normal' configuration parsing:
- we still parse and create objects when processing 'add*Local()'   and 'set*Local()' directives, since the actual binding is delayed anyway ;
- we do not connect …

dnsdist: Separate the check-config and client modes

---

pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-healthchecks.cc
pdns/dnsdistdist/dnsdist-healthchecks.hh
pdns/mplexer.hh

We used to do health checking sequentially, which could take a long time with a huge list of backends, or simply if several of them were timing out.
This PR implements parallel health checks, we first loop through all the backends we have to check and send them a query, then use multiplexing on the sockets to get the responses, or handle the timeouts if any. This way a single round of checks should only take as long as the greatest timeout of the backends, instead of the total of all timeouts today.
I have:

dnsdist: Implement parallel health checks

---

pdns/filterpo.cc
pdns/lua-recursor4.cc
pdns/pdns_recursor.cc
pdns/recursordist/test-filterpo_cc.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/test_RPZ.py

- Since 272e9a0 we scanned all policies for an exact match before looking for wildcard matches. It brokes the promise that filtering policies are evaluated in the order they are defined ;
- After a "pass-thru" match, we should not process any other RPZ rule ;
- Export the filtering policy type to `Lua`.
I have:

rec: Fix precedence order for RPZ policies rules

---

docs/backends/remote.rst
modules/remotebackend/remotebackend.cc
modules/remotebackend/remotebackend.hh
modules/remotebackend/test-remotebackend.cc

The remote backend did not support 'also-notifies'. This PR implements this as a call to `getDomainMetadata` for `ALSO-NOTIFY`.
cc: @cmouse 
I have:

remote: Support ::alsoNotifies

---

pdns/iputils.hh
pdns/packethandler.cc
pdns/pdns_recursor.cc

Make `ComboAddress::setPort()` update the current object instead of creating a new one.
This fixes the source port not being set in protobuf messages in the recursor, as introduced in #8702.
I have:

Make ComboAddress::setPort() update the current object

---

pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc.hh
pdns/recursordist/test-syncres_cc6.cc
pdns/validate.cc

An `Opt-Out` `NSEC3` only proves that there is no delegation, so we should not consider a `DS NODATA` or a `NXDOMAIN` proved by that `RR` secure but insecure.
This was fixed in 18c8faae6c67f734583c5c881d0d083d3253b49e (https://github.com/PowerDNS/pdns/pull/8665) and this commit adds a few unit tests to cover the fix.
Closes #8693.
I have:

rec: Add unit tests for the NSEC3 Opt-Out case

---

pdns/iputils.hh
pdns/packethandler.cc
pdns/pdns_recursor.cc

Instead of creating a new one.
(cherry picked from commit 79816288afe7169c1f1bb28463f22512ca11c3b9)
I have:

rec: backport 8718 to rec 4.3.x: Make ComboAddress::setPort() update the current object

---

pdns/dnsdistdist/libssl.cc

This way dnsdist will load the default OpenSSL configuration, or a custom one specified via the `OPENSSL_CONF` environment variable.
It allows loading an engine or configuration various options supported by OpenSSL.
This requires OpenSSL >= 1.1.0.
I have:

dnsdist: Load an openssl configuration file, if any, during startup

---

pdns/auth-packetcache.cc
pdns/auth-packetcache.hh
pdns/auth-querycache.cc
pdns/auth-querycache.hh

Before this change, both the query and packet caches in the authoritative server can exceed their maximum size by a lot, until the next cleaning cycle.
This is particularly nasty since the current cleaning algorithm will never remove entries from the cache until they expire, as opposed to what we do in the recursor, for example, where we nuke the least-recently used entries, even if they are still valid, when the cache is full.
This commit changes that by removing the least recently inserted or updated entry from the cache after inserting a new one when the cache is full, thus enforcing the maximum size more strictly.
Note that this is really the least recently inserted/updated and not the least recently used one, as is done in the recursor. Having a proper `LRU` in the auth would require …

auth: Enforce a strict maximum size for the packet and records caches

---

modules/gpgsqlbackend/spgsql.cc
modules/gpgsqlbackend/spgsql.hh

Remove real prepared statements from the generic PostgreSQL backend. Instead use the parameterised libpq API, which was (as far as I remember) the original intent.
This should help users with transaction level pooling servers (like pgbouncer) where relying on cross-transaction session state is not possible (and prepared statement are such state).
I have:

gpgsqlbackend: Avoid actually prepared statements

---

pdns/ueberbackend.cc

Make sure get() is always returning the default value for d_place and not some, random, previously set value.
Fixes #8626
I have:

auth: make sure get() is always returning the default value for d_place

---

.circleci/config.yml
README.md
configure.ac
pdns/lua-auth4.cc
pdns/lua-base4.cc
pdns/lua-base4.hh

Recursor and dnsdist already treat Lua as mandatory; with the growing Lua-based feature set in the Auth, it would make sense to also treat Lua as mandatory. At times in the past we've discovered that nobody really tests building without Lua anymore.
Also see #8706.
I have:

Make Lua mandatory for Auth

---

docs/http-api/swagger/authoritative-api-swagger.yaml

Point out that the `rrsets` is only included at the zone detail endpoint
I have:

docs: clarify Zone object description, closes #8748

---

docs/settings.rst
docs/upgrading.rst
pdns/common_startup.cc
pdns/nameserver.cc
pdns/tcpreceiver.cc

Dropping options makes upgrades hard. Fixes #8624. 
I have:

allow local-ipv6 until 4.4.0

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

Permits DNAME with SOA and NS in zone apex. Closes #8641.
I have:

ws-auth: Allow DNAME in apex with SOA and NS records

---

pdns/dnsdistdist/tcpiohandler.cc

Otherwise we can end up with a DNS over TLS connection using a TLS Session Ticket Encryption Key, OCSP response or even `SSL_CTX` object after it was released following a reload of the TLS context (via `reloadAllCertificates()`, for example), triggering a use-after-free, possibly leading to a crash.
I have:

dnsdist: Use ref counting for the DoT TLS context

---

pdns/recursordist/docs/performance.rst

The Recursor performance guide discussed distributor threads, but did not mention the newish `distributor-threads` setting. This hastily written PR should remedy that. :D
I have:

Add distributor-threads setting to rec performance docs

---

pdns/dns.hh

Having a user-defined destructor prevents the compiler from generating implicit definition of the move constructor and the move assignment operator, which might have a serious performance impact.
I have:

Remove the empty user-defined destructor of DNSResourceRecord

---

docs/backends/bind.rst
docs/manpages/pdns_control.1.rst
modules/bindbackend/bindbackend2.cc
modules/bindbackend/bindbackend2.hh

I find very useful to be able to get much more information about the current status of the domain.
Sample output:
```
$ pdns_control BIND-DOMAIN-EXTENDED-STATUS
example.zone: 
Status: parsed into memory at 2020-01-08 17:38:12 +0100
Internal ID: 1
On-disk file: /etc/powerdns/example.zone (1578495472)
Kind: Slave
Masters: 
- 192.0.2.1:53
Also Notify: 
Number of records: 42
Loaded: 1
Check now: 0
Check interval: 0
Last check: 1578501492
Last notified: 0
```
I have:

auth: Add an extended status report in the bind backend

---

docs/backends/generic-mysql.rst
docs/backends/generic-odbc.rst
docs/backends/generic-postgresql.rst
docs/backends/generic-sqlite3.rst
docs/guides/basic-database.rst

The Auth SQL schema docs include links to the schemas for 4.1. This adds equivalent links for 4.2.
This is complementary to #8774. 
I have:

docs: Add 4.2 SQL schema links

---

docs/http-api/swagger/authoritative-api-swagger.yaml
pdns/ws-api.cc

The rings can easily grow to megabytes, and many statistics consumers are entirely uninterested in them.
~This uses `skiprings=true` (defaulting to false), as opposed to `dnssec=false` (defaulting to false) on the Zones endpoint. Should probably flip that around to work the same way (`includerings=false` with true as default)?~ Did this.
I have:

auth api: add includerings option to statistics endpoint

---

pdns/dnsdistdist/libssl.cc
pdns/dnsdistdist/tcpiohandler.cc

It turns out that the `keyLogFile` directive was ignored for DNS over TLS, while correctly working with DNS over HTTPS. I know I tested both when writing the code for #8442 but I guess the DoT part was lost in a refactoring at some point before opening the PR :-/
This PR also makes the feature more usable by flushing the key material to the file right away, so we don't have to wait for the buffer to get flushed.
I have:

dnsdist: Fix key logging for DNS over TLS

---

builder-support/debian/dnsdist/debian-buster/dnsdist.postinst
builder-support/debian/dnsdist/debian-buster/rules
builder-support/debian/dnsdist/debian-jessie/dnsdist.postinst
builder-support/debian/dnsdist/debian-jessie/rules
builder-support/debian/dnsdist/debian-stretch/dnsdist.postinst
builder-support/debian/dnsdist/debian-stretch/rules
m4/pdns_with_service_user.m4
pdns/dnsdist.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/configure.ac
pdns/dnsdistdist/dnsdist-systemd.cc
pdns/dnsdistdist/dnsdist-systemd.hh
pdns/dnsdistdist/dnsdist.service.in
pdns/dnsdistdist/m4/pdns_with_service_user.m4

With this PR, dnsdist is never started as root on Linux systems with systemd. This PR adds a `configure` option to set the username and group in the service file. It also removes the capabilities for dnsdist to do setuid and setgid.
Discussion:
* Should dnsdist log a warning when run inside systemd (`NOTIFY_SOCKET` defined) and `-u` or `-g` is set on the command line?
I have:

dnsdist: don't start as root within a systemd environment

---

pdns/dnsdist-console.cc
pdns/dnsdist-ecs.cc
pdns/dnsdist-ecs.hh
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/docs/rules-actions.rst
pdns/dnsname.hh
pdns/test-dnsdist_cc.cc
regression-tests.dnsdist/test_Advanced.py

Fixes #4747 by making it possible to add a `SOA` record in the additional section on a `NXDomain` or `NoData` answer.
I have:

dnsdist: Add SetNegativeAndSOAAction() and its Lua binding

---

pdns/recursordist/docs/lua-scripting/dq.rst

Two lua functions have double docs. Also group them a bit more naturally.
I have:

rec: Remove duplicate *PolicyTags docs

---

.circleci/config.yml

this
is
a
very
long
commit
message
to
trigger
the
problem
where
our
circleci
setup
tries
to
use
the
pager
to
show
long
commit
messages
just
like
this
one
although
there
are
others
quite
like
it
but
those
tend
to
be
way
easier
to
read
Long commit messages hang our Circle build. This PR fixes that.
I have:

avoid 'git show -s' from starting a pager in CircleCI

---

pdns/dnslabeltext.rl
pdns/dnsname.cc
pdns/dnsname.hh
pdns/dnswriter.hh

Saving a call to `strlen()` when we already know the size, i.e. when the `DNSName` is constructed from a string. This is often the case when we retrieved the name from a `SQL` backend, for example.
I have:

DNSName: Don't call strlen() when the length is already known

---

pdns/dnsdistdist/docs/reference/config.rst

dnsdist: Fix a typo 'apikey' -> 'apiKey' in setWebserverConfig() doc

---

pdns/dnsdistdist/docs/guides/downstreams.rst
pdns/dnsdistdist/docs/guides/dynblocks.rst
pdns/dnsdistdist/docs/rules-actions.rst

1.4.0 is out, it's time to get rid of references to the old `dnsdist.` stuff.
I have:

dnsdist docs: refer to new tables. Fixes #8798

---

pdns/dnsname.hh

Fix "error: 'strlen' was not declared in this scope" on CentOS 6

---

builder-support/dockerfiles/Dockerfile.rpmbuild
builder-support/dockerfiles/Dockerfile.target.amazon-2
builder-support/dockerfiles/Dockerfile.target.centos-6
builder-support/dockerfiles/Dockerfile.target.centos-7
builder-support/dockerfiles/Dockerfile.target.centos-8

references:
https://github.com/pombredanne/dnf-plugin-ovl
https://bugzilla.redhat.com/show_bug.cgi?id=1213602
This hopefully avoids the occasional RPMDB corruption we see in our builds.
I have:

builder: touch /var/lib/rpm/* in every docker layer that uses rpmdb

---

pdns/pdns_recursor.cc

(cherry picked from commit ef31b0902fa09fd9a03276b56a51d88d63e68c6f)
I have:

rec: backport 8559 to rec 4.2.x: Avoid startup race by setting the state of a tread before starting it.

---

pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/rpzloader.cc
pdns/rpzloader.hh

Without this, we would store the refresh value as zero, and ignore it on load (also making it zero), causing the Recursor to check the master in a tight loop.
Lightly tested. It looks like there is a conceptual disconnect between the stored SOA data and `d_refresh` in the Zone objects and I did not fully audit for any other disconnects of that kind.
I have:

rec RPZ dumpFile/seedFile: store/get SOA refresh on dump/load

---

pdns/dnsdist-lua.cc
pdns/dnsdist-web.cc
pdns/filterpo.cc
pdns/iputils.hh
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/sortlist.cc
pdns/test-iputils_hh.cc

The existing implementation of class NetmaskTree was inefficient because:
- it created a new tree node for each bit in the Netmask
- used a redundant std::set to provide iterator support.
These changes mend both these problems, yielding an overall decrease in CPU usage and memory requirements.
I have:

Rework NetmaskTree for better CPU and memory efficiency.

---

pdns/auth-packetcache.cc
pdns/auth-packetcache.hh
pdns/auth-querycache.cc
pdns/auth-querycache.hh
pdns/common_startup.cc
pdns/dbdnsseckeeper.cc
pdns/dnsseckeeper.hh

This PR allocates the buckets for hashed indexes in advance to prevent having to re-allocate and re-hash later when the caches grow.
I have:

auth: Prepare the caches' buckets in advance

---

docs/http-api/swagger/authoritative-api-swagger.yaml
docs/http-api/zone.rst

I've never implemented the '/servers/{server_id}/zones/{zone_id}/check' endpoint, and won't find time in the short term future.
Lets remove it to avoid potential confusion.
I have:

Remove not implemented zone check API from spec

---

pdns/tcpreceiver.cc

The RRSIG does not appear to hurt any clients, but sending to a DNSSEC-unaware client is useless.
I have:

IXFR: only sign SOA in empty response for +DO queries

---

ext/yahttp/yahttp/reqresp.hpp
ext/yahttp/yahttp/url.hpp

This ensures that urls like `http://[2001::db8::fff:22]/` and `http://[2001::db8::fff:22]:2500/`. It also now sends a `Host` header with bracketed IPv6 addresses when needed.
cc: @cmouse 
I have:

YaHTTP: Support bracketed IPv6 addresses

---

pdns/filterpo.cc
pdns/filterpo.hh
pdns/pdns_recursor.cc
pdns/recursordist/test-filterpo_cc.cc
pdns/syncres.cc
regression-tests.recursor-dnssec/test_Protobuf.py
regression-tests.recursor-dnssec/test_RPZ.py

Taking into account only higher priority zones.
While there avoid copying around the Policy objects too much by passing a reference that gets modified only if a match has been found.
I (actually *we*) have:

Rec: do continue rpz processing if the current policy is passthru

---

pdns/auth-packetcache.cc
pdns/auth-packetcache.hh
pdns/auth-querycache.cc
pdns/auth-querycache.hh
pdns/cachecleaner.hh
pdns/dbdnsseckeeper.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsseckeeper.hh
pdns/recpacketcache.cc
pdns/recpacketcache.hh
pdns/recursor_cache.cc

This backports #8713, and #8579 because it depends on it.
This PR is marked draft because we may not want this in 4.2.x, but having it here allows users to apply it to 4.2.x.
I have:

auth-4.2.x: Enforce a strict maximum size for the packet and records caches

---

builder-support/debian/authoritative/debian-buster/pdns-backend-bind.docs
builder-support/debian/authoritative/debian-buster/pdns-backend-mysql.docs
builder-support/debian/authoritative/debian-buster/pdns-backend-odbc.docs
builder-support/debian/authoritative/debian-buster/pdns-backend-pgsql.docs
builder-support/debian/authoritative/debian-buster/pdns-backend-sqlite3.docs
builder-support/debian/authoritative/debian-jessie/pdns-backend-bind.docs
builder-support/debian/authoritative/debian-jessie/pdns-backend-mysql.docs
builder-support/debian/authoritative/debian-jessie/pdns-backend-odbc.docs
builder-support/debian/authoritative/debian-jessie/pdns-backend-pgsql.docs
builder-support/debian/authoritative/debian-jessie/pdns-backend-sqlite3.docs
builder-support/debian/authoritative/debian-stretch/pdns-backend-bind.docs
builder-support/debian/authoritative/debian-stretch/pdns-backend-mysql.docs
builder-support/debian/authoritative/debian-stretch/pdns-backend-odbc.docs
builder-support/debian/authoritative/debian-stretch/pdns-backend-pgsql.docs
builder-support/debian/authoritative/debian-stretch/pdns-backend-sqlite3.docs
builder-support/specs/pdns.spec
modules/gmysqlbackend/Makefile.am
modules/godbcbackend/Makefile.am
modules/gpgsqlbackend/Makefile.am
modules/gsqlite3backend/Makefile.am
pdns/Makefile.am

* Add the 4.3.0 SQL schema upgrade files to tarballs. (I think.)
* Add the 3.4.0 through 4.3.0 files to the packages!
* Add the `bind` files to the `pdns` (rpm) and `pdns-backend-bind` (deb) packages.
* Add `enable-foreign-keys.mysql.sql` to the package and tarballs. (Don't know if it's useful, but it's not not useful.)
* Also reformat `godbc`'s `Makefile.am` similar to how the other backends were done. (And switch the order of a `.cc` file and a `.hh` file; I think it's an unordered list?)
The tarball issue was reported by HellSpawn the other day.
I've tested building CentOS 8, Debian Buster and Ubuntu Bionic with pdns-builder, and listed the contents of the debs and rpms and tarballs produced, but I haven't done any further testing (like actually installing things).
I duplicated SQL …

auth: Add more SQL schema files to packages and tarballs

---

pdns/nsecrecords.cc
pdns/test-dnsrecords_cc.cc

(cherry picked from commit 3d51568b456205c9bd60ceeedb4b43af4a33f019)
I have:

rec: Backport 8826 to rec 4.3.x: Refuse NSEC records with a bitmap length > 32

---

pdns/nsecrecords.cc
pdns/test-dnsrecords_cc.cc

(cherry picked from commit 3d51568b456205c9bd60ceeedb4b43af4a33f019)
I have:

rec: Backport 8825 to rec 4.2.x: Refuse NSEC records with a bitmap length > 32

---

.circleci/config.yml

Our PG tests on CircleCI are currently failing with:
```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD for the superuser. Use
"-e POSTGRES_PASSWORD=password" to set it in "docker run".
You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
without a password. This is *not* recommended. See PostgreSQL
documentation about "trust":
https://www.postgresql.org/docs/current/auth-trust.html
Exited with code 1
```
This seems related to this change [1], according to [2]. While the change seems a good idea, we don't really care whether our PG server allows all connections without a password. In fact that's what our current scripts expect.
[1]: https://github.com/docker-library/postgres/commit/42ce7437ee68150ee29f527242 …

Allow all connections to the PG server in Circle CI

---

pdns/dnsdistdist/test-dnsdistlbpolicies_cc.cc

dnsdist: Prevent referencing a Lua pol after the Lua ctx has been destroyed

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdist.hh

This is required by the new FFI interface. 
Reported by Coverity.
I have:

dnsdist: DownstreamState::getName() should return a ref, not a temp

---

pdns/recursordist/docs/http-api/endpoint-rpz-stats.rst

The table version got some unexplained `colspan=2` attributes. Changing the whole thing to a definition list fixes that and looks better in general.
I have:

rec docs: fix weird formatting of RPZ statistics list, thanks @horazont

---

pdns/pdns_recursor.cc

Hopefully fixes #8861.
I have:

rec: Only log qname parsing errors when 'log-common-errors' is set

---

pdns/pdns_recursor.cc

(cherry picked from commit 4b4566e8d28ff3b18152213e8c8666aa643f8eb9)
I have:

rec: backport 8864 to rec 4.1.x: Only log qname parsing errors when 'log-common-errors' is set

---

pdns/pdns_recursor.cc

(cherry picked from commit 4b4566e8d28ff3b18152213e8c8666aa643f8eb9)
I have:

rec: backport 8864 to rec 4.2.x: Only log qname parsing errors when 'log-common-errors' is set

---

pdns/pdns_recursor.cc

(cherry picked from commit 4b4566e8d28ff3b18152213e8c8666aa643f8eb9)
I have:

rec: backport 8864 to rec 4.3.x: Only log qname parsing errors when 'log-common-errors' is set

---

pdns/dnsdist.hh
pdns/fstrm_logger.cc
pdns/fstrm_logger.hh
pdns/remote_logger.cc
pdns/remote_logger.hh

Fixes #8629. 
Note that the metrics are accessible from the RemoteLogger object in dnsdist but not in the recursor. It's still an improvement to stop flooding the logs!
I have:

Add 'queue full' metrics for our remote logger, log at debug only

---

regression-tests.recursor/cache-recursorcache-forward/command

Sometimes just a bit more than 3s went by between the two queries, and that's fine. This PR is mostly because I have seen regular occurrences of spurious failure of this test in our continuous testing, and it was easy to fix :)
I have:

rec: Ignore off-by-one TTL in the cache-recursorcache-forward test

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/libssl.cc
pdns/libssl.hh

Adds a new `sessionTimeout` setting for TLS session lifetime. It is used both for sessions stored server-side and also to indicate to clients for how long their given TLS ticket is valid for. If unset or set to 0, will use OpenSSL's default (which for TLS protocols is 2 hours).
It makes sense to not tell the client to throw the ticket away if the ticket key hasn't yet been rotated.
I have:

dnsdist: add sessionTimeout setting for TLS session lifetime

---

.github/workflows/fuzz.yml

CI Fuzz allows for pull requests to be fuzzed in CI using fuzz targets enabled in OSS-Fuzz, as described here: https://google.github.io/oss-fuzz/getting-started/continuous-integration/
Completely untested, as it is hard to do so without getting this merged first :-)
I have:

Enable CI Fuzz: run our fuzz targets each time a pull request is submitted

---

pdns/dnsdistdist/docs/reference/index.rst
pdns/dnsdistdist/docs/reference/netmask.rst
pdns/dnsdistdist/docs/rules-actions.rst

Fixes invalid escaping in the `SpoofRawAction()` documentation and provides better examples of how to use it.
Also fixes a formatting issue in the `Netmask` documentation, and actually includes it in the documentation.
I have:

dnsdist: Fix the SpoofRawAction() example in the documentation

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst

Also add a warning if the option is enabled on a too old version of OpenSSL.
Fixes #8806.
I have:

dnsdist: Document that the 'keyLogFile' option requires OpenSSL >= 1.1.1

---

pdns/remote_logger.cc
pdns/remote_logger.hh

- Do not lock while trying to reconnect ;
- Try to reconnect right away if the disconnection was detected in the maintenance thread ;
- Keep queueing messages when the connection has been lost, until the buffer gets full.
I have:

Better handling of reconnections in Remote Logger (dnsdist, rec)

---

m4/pdns_check_libcrypto.m4
pdns/digests.hh
pdns/dnsdistdist/libssl.cc
pdns/dnsdistdist/m4/dnsdist_with_libssl.m4
pdns/dnssecinfra.cc
pdns/opensslsigners.cc

Instead of using version numbers, which is brittle, notably because LibreSSL faked the OpenSSL version numbers at some point without implementing all the newly introduced functions.
Fixes #8739.
I have:

Detect {Libre,Open}SSL functions availability during configure

---

pdns/dnsdist-console.cc
pdns/dnsdist-lbpolicies.hh
pdns/dnsdist-lua.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-lbpolicies.cc
pdns/dnsdistdist/docs/guides/serverselection.rst

Also make sure that the `chashed` implementation respects the weights, and properly handle backends that are not available during the bounds computation.
Closes https://github.com/PowerDNS/pdns/issues/7387.
I have:

dnsdist: Implement bounded loads for the whashed and wrandom policies

---

pdns/auth-packetcache.cc
pdns/auth-querycache.cc
pdns/cachecleaner.hh

Purging was very inefficient for large shards when the cached items are not equally distributed over all shards. We now look at 10% of the cached items in every shard. This was 10% of all items divided over all shards.
In some setups this will result in a dramatic decrease of cached items (up to 100x) with an identical cache hit rate.
I have:

auth: make sure we look at 10% of all cached items during cleanup

---

pdns/dnsdist-console.cc
pdns/dnsdistdist/dnsdist-lua-bindings-protobuf.cc
pdns/dnsdistdist/docs/reference/dnstap.rst
pdns/recursordist/docs/lua-config/protobuf.rst

This PR makes it possible to tune the Frame Stream library IO parameters in dnsdist.
I have:

dnsdist: Make FrameStream IO parameters configurable

---

.github/workflows/fuzz.yml

CIFuzz was in dry_run mode to make sure the PowerDNS build system was compatible. It CIFuzz is working correctly so dry_run mode should be turned off.

Turning dry_run off for CIFuzz

---

pdns/filterpo.cc
pdns/filterpo.hh
pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/rec-protobuf.cc
pdns/rec-protobuf.hh
pdns/recursordist/docs/lua-config/rpz.rst
pdns/recursordist/test-filterpo_cc.cc
pdns/rpzloader.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/ws-recursor.cc
regression-tests.recursor-dnssec/test_Protobuf.py

This commit adds the possibility to set custom tags to a RPZ zone, adding these tags to the policy ones (that can be set with Lua) when a policy matches.
It does so by creating a new `PolicyZoneData` object that is shared between the zone and all the policies that it holds, in order to:
- avoid duplicating the name, priority and tags for each policy ;
- prevent a circular dependency between shared pointers for the zone and its policies.
It also refactors the handling of RPZ policy hits in `startDoResolve()` to remove some code duplication.
CC @atosatto
I have:

rec: Add custom tags to RPZ hits

---

pdns/dnsdistdist/doh.cc

Before that change, we could have loaded DoH STEK from a file without properly setting the next rotation, causing a ticket rotation to happen during the first TLS session establishment.
This can be prevented by setting `ticketsKeysRotationDelay=0`.
I have:

dnsdist: Set the DoH ticket rotation delay before loading tickets

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/views.hh
pdns/doh.hh
regression-tests.dnsdist/test_DOH.py

This PR adds a `trustForwardedForHeader` option to `addDOHLocal()`. When that option is enabled, incoming `X-Forwarded-For` header are parsed and the last value of the last header replaces the source client IP address for ACL, rules and logging purposes.
Closes #8661.  
I have:

dnsdist: Add support for the processing of X-Forwarded-For headers

---

pdns/dnsdistdist/doh.cc

Early versions of `boost::string_ref` didn't have the ability to compare to string. Also the `.at()` operator of `boost::string_view` had a invalid use of the ternary operator.
I have:

dnsdist: Fix compilation issues with older boost::string_ref and string_view

---

docs/http-api/swagger/authoritative-api-swagger.yaml

Found when loading the spec into a validating parser :-)

Correct typo in Swagger specification

---

ext/lmdb-safe/lmdb-safe.hh
pdns/dnsdistdist/views.hh

On OpenBSD string_view is both in boost and std

---

ext/lmdb-safe/lmdb-safe.cc

Reported by `clang++`.
I have:

Remove a std::move() preventing Return-Value Optimization in lmdb-safe.cc

---

pdns/dnsdist.cc

`DNSCrypt` pads its queries for privacy purposes, and thus requires larger queries than plain DNS ones. Discarding fragmented datagrams doesn't make sense in that case, and actually leads to a very degraded service, as reported in https://github.com/PowerDNS/pdns/pull/7410#issuecomment-604318988.
At the moment I don't see any reason to accept fragmented datagrams for plain DNS queries, so this MR only applies to `DNSCrypt` binds for now.
I have:

dnsdist: Keep accepting fragmented UDP datagrams on DNSCrypt binds

---

pdns/dnsdist.cc

Follow-up from #8974, we need to be able to accept datagrams larger than 1500 bytes since the queries are padded, not dismissing reassembled datagrams is not enough.
I have:

dnsdist: Accept UDP datagrams larger than 1500 bytes for DNSCrypt

---

pdns/opensslsigners.cc
pdns/pkcs11signers.cc

This header is normally included with ssl.h.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

fix compilation without deprecated OpenSSL APIs

---

docs/http-api/swagger/authoritative-api-swagger.yaml

* createMetadata only accepts a single Metadata object, not an array
* getMetadata returns a single Metadata object, not an array
* add descriptions for metadata_kind parameters that were '???'
* note that modifyMetadata removes existing entries of the specified kind
Signed-off-by: Kevin P. Fleming <kevin@km6g.us>

Improve specification for metadata API endpoint

---

pdns/recursordist/test-syncres_cc2.cc
pdns/syncres.cc

test_referral_depth is actually hitting the limit in doCNAMECacheCheck() and not the generic depth limit. Use one less of referral to fix that.  Additionally, test and fix the non-limited case.
I have:

rec: fix referral unit test

---

pdns/slavecommunicator.cc
regression-tests.auth-py/authtests.py
regression-tests.auth-py/requirements.txt
regression-tests.auth-py/test_IXFR.py

When an incoming IXFR contained multiple deltas, we would end up with several SOA records. It turns out this is because the second delta is applied against data from the query cache, which was just invalidated by the application of the first delta. This PR fixes that by avoiding the query cache.
~Needs cleanup.~
I have:

auth: avoid IXFR-in record duplication

---

pdns/lua-recursor4.cc
pdns/misc.cc
pdns/misc.hh
pdns/pdns_recursor.cc
pdns/recursordist/docs/dns64.rst
pdns/recursordist/docs/settings.rst
pdns/syncres.hh
pdns/test-misc_hh.cc
regression-tests.recursor-dnssec/test_DNS64.py

Native support is much less flexible than `Lua` hooks but should satisfy most of the DNS64 setups. It is also much faster since it does not involve calling a `Lua` hook for all queries.
I have:

rec: Implement native DNS64 support, without Lua

---

docs/changelog/4.3.rst
docs/secpoll.zone
docs/upgrading.rst

In the hope that nobody finds a release breaking bug this week!
TODO:
~Candidate builds: https://builder.powerdns.com/#/buildrequests/124749 and https://builder.powerdns.com/#/buildrequests/124747~
Tag builds: https://builder.powerdns.com/#/buildrequests/124783?redirect_to_build=true and https://builder.powerdns.com/#/buildrequests/124784?redirect_to_build=true
I have:

auth 4.3.0 docs, upgrade notes, secpoll

---

docs/changelog/4.3.rst
docs/upgrading.rst

We fixed an IXFR-in corruption bug in 4.3.0, and our changelog and upgrade notes did not cover that in sufficient detail.
I have:

auth: document IXFR corruption and correction

---

pdns/pdns_recursor.cc

rec: fix typo (prefixe -> prefixes)

---

pdns/portsmplexer.cc
pdns/test-dns_random_hh.cc

I tested that this fixes the compilation and works on OpenIndiana.
Also fixes the compilation of our `dns_random` unit tests on systems that have both `getrandomm()` and `arc4random()`.
Fixes #9025.
Note that even though we do compile the `Solaris completion ports` code, we always also compile the `/dev/poll` one, and we do prefer that second one since it's loaded first and they have the same priority. I think we should just remove the `Solaris completion ports` code in later releases.
I have:

Fix compilation of the ports event multiplexer

---

modules/gmysqlbackend/smysql.cc

Before: `Can't connect to MySQL server on 'mariadb.mydomain.local' (101)`
Now: `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`
Sadly, the errno is still not expanded to a useful string, like `perror` could do if the `101` or `2` was offered by libmysqlclient as an integer, instead of something hidden in a string.
I have:

auth smysql: mimic error message format from mysql tooling

---

build-scripts/docker/generate-repo-files.sh

Tested using dnsdist-1.5.0-rc1 and most work but CentOS 8 gives the following error:
```
Step 4/5 : RUN yum install -y dnsdist
---> Running in 1cc64a74c4e1
PowerDNS repository for dnsdist - version 1.5.X  24 kB/s | 2.2 kB     00:00    
Extra Packages for Enterprise Linux Modular 8 - 126 kB/s | 116 kB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64  1.6 MB/s | 6.3 MB     00:03    
Error: 
Problem: cannot install the best candidate for the job
- nothing provides libcdb.so.1()(64bit) needed by dnsdist-1.5.0-0.rc1.1pdns.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
The command '/bin/sh -c yum install -y dnsdist' returned a non-zero code: 1
```

Add support for dnsdist-15 to repo script.

---

build-scripts/changelog-from-pr.py

See https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
I have:

Do not use github deprecated API for changelog script

---

pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/rpzloader.cc
pdns/rpzloader.hh

Backport of #8778
This avoids a tight loop in the RPZ downloader if a dumpfile is specified without refresh setting. 
I have:

rec: Backport 8778 to rec 4.3.x: RPZ dumpFile/seedFile: store/get SOA refresh on dump/load

---

modules/gmysqlbackend/smysql.cc
pdns/lua-record.cc
pdns/misc.cc
pdns/pkcs11signers.cc

- 'value is never actually read' warnings ;
- Prevent reading uninitialized memory in Lua's `getLatLon()` ;
- Make sure we don't divide by zero in Lua's `pickwhashed()`
I have:

auth: Fix warnings reported by clang++ 10

---

pdns/dnsdistdist/test-dnsdistkvs_cc.cc
pdns/dnsdistdist/test-dnsdistlbpolicies_cc.cc

dnsdist: a few warnings fixed, reported by clang on OpenBSD

---

pdns/dnsdistdist/dnsdist-backend.cc

When more than one socket per backend is used, we might not have added all the socket descriptors to the multiplexer and that's fine.
The error is harmless except for an error message and a leaked file descriptor (which is not an issue unless new servers are added in a loop and fail).
I have:

dnsdist: Gracefully handle a failure to remove FD on (re)-connection

---

pdns/test-lock_hh.cc

Avoid "pthread_rwlock_destroy on rwlock with waiters!" on OpenBSD

---

pdns/recursordist/docs/settings.rst

The default setting for `ecs-add-for` includes "::/0", not "::".

Correct doc for ecs-add-for default

---

pdns/iputils.hh

Found by Coverity (1419400), which concludes that if node could be
null, the following node->node.first.getBits() would deref a nullptr.
I have:

NetmaskTree: do not test node for null, the loop guarantees node is not null.

---

pdns/dnsdist-web.cc

It was noticed on IRC that the buckets for latency stats had no unit
I have:

dnsdist: add the unit to the help for latency buckets

---

pdns/ssqlite3.cc

Always free errmsg; use two diffferent string vars to avoid shadowing.
Coverity 1401969.
I have:

auth: better (actual) fix for mem leak in SSQLite3::execute()

---

pdns/logger.cc
pdns/logger.hh

Throwing an exception in the logger almost cetainly will cause
trouble. Coverity 1428667 shows this can happen in
LdapBackend::~LdapBackend().
I have:

Avoid throwing an exception in Logger::log().

---

pdns/ixfrdist-web.cc
pdns/webserver.cc
pdns/ws-auth.cc
pdns/ws-recursor.cc

Reported by @dwfreed on IRC (thanks!), based on a patch from Gentoo [1].
[1]: https://bugs.gentoo.org/719926
I have:

Boost 1.73 moved boost::bind placeholders to the placeholders namespace

---

pdns/dnsdistdist/dnsdist-secpoll.cc
pdns/recursordist/test-secpoll_cc.cc
pdns/secpoll-auth.cc
pdns/secpoll-recursor.cc
pdns/secpoll.cc

Less negatives in error messages improves readability.

---

builder-support/debian/authoritative/debian-buster/rules
builder-support/debian/authoritative/debian-jessie/rules
builder-support/debian/authoritative/debian-stretch/rules
builder-support/debian/recursor/debian-buster/rules
builder-support/debian/recursor/debian-jessie/rules
builder-support/debian/recursor/debian-stretch/rules
builder-support/specs/pdns.spec

- #8094 introduced --config=default, but the official packages did not get updated to use that.
- Also the pdns-recursor.conf on Debian changes with each update as it contains the version string. Even if there are no other changes, this causes a conffile prompt for each update, which is annoying when using the master repositories + automatic upgrades.
I have:

builder: improve shipped config files

---

pdns/Makefile.am
pdns/common_startup.cc
pdns/dnsdistdist/Makefile.am
pdns/pdns_recursor.cc
pdns/recursordist/Makefile.am

Systemd ensures the RuntimeDirectory is emptied when the service is started. This works fine until you start a second service (pdns@foo.service), which then removes the existing /run/pdns. This PR ensures the virtual services have their own runtime directories.
Note that we might need a code-change for virtual hosting to set the socket-dir automatically if pdns is virtually hosted and the socket-dir matches the socket-dir from `configure`.
I have:

Ensure runtime dirs for virtual services differ

---

ext/yahttp/yahttp/reqresp.cpp

Backport of #8640 to be able to build with GCC 10.
(cherry picked from commit ffb885e937c27bb1c62dee8f18c58ae0d5d52d39)
I have:

rec-4.3.x: Fix build with gcc-10

---

pdns/recursordist/docs/settings.rst

The `allow-from` setting's default value is `LOCAL_NETS`, but the copy of it in the documentation was incomplete.
https://github.com/PowerDNS/pdns/blob/d39c2ed05975d7dcf4fe396edb781beed3dde30e/pdns/pdns_recursor.cc#L260
https://github.com/PowerDNS/pdns/blob/d39c2ed05975d7dcf4fe396edb781beed3dde30e/pdns/pdns_recursor.cc#L3845
I have:

rec: docs: Update the allow-from setting default

---

pdns/syncres.cc

The missing ' will drive us crazy. We can't unsee it.
I have:

rec: Update syncres.cc

---

pdns/auth-carbon.cc
pdns/dnsdist-carbon.cc
pdns/misc.cc
pdns/misc.hh
pdns/rec-carbon.cc

On FreeBSD at least, HOST_NAME_MAX is not defined and we need to use sysconf() to get the value at runtime instead.
Based on a work done by @RvdE to make the recursor compile on FreeBSD (many thanks!).
(cherry picked from commit 4c990a1b82e091d887d873c7da5254de84aabebb)
Backport of #9127.
I have:

rec-4.3.x: Fix compilation on systems that do not define HOST_NAME_MAX

---

.github/actions/spell-check/only.txt

This should suppress the spell check scheduled task for PRs to this branch.
A technical explanation:
`schedule` tries to protect branches that may/may not have the spell checker enabled from PRs that start from before the spell checker was added, as well as from users who haven't opted into spell checking, from silently introducing spelling errors.
If a PR doesn't have a configured data set, it imports the one from the default branch (schedule only runs tasks defined on the default branch).
https://github.com/check-spelling/check-spelling/blob/5f7f35b25e6bce7b1e5a8f226369a86ab19a623e/check-pull-requests.sh#L161
I have:
This code is *not* to be merged to master. But it can be copied to other branches.
This code isn't actually tested, but I'm fairly confident it'll do the right thing.

Suppress PR based spell check for the rec-4.3.x branch

---

build-scripts/travis.sh

Because we removed the trusty repos, travis recursor testing fails to install pdns-server. This PR pulls pdns-server from a stable URL.
I have:

travis: install pdns package from direct download

---

pdns/recursordist/Makefile.am
pdns/recursordist/test-rpzloader_cc.cc

The real function moved to the pdns namespace anyway.
I have:

rec: Remove unused getQueryLocalAddress stub in the unit tests

---

pdns/opensslsigners.cc

openssl_pthreads_locking_callback and openssl_pthreads_id_callback are local functions, so they need static.
I have:

opensslsigners: Add missing 'static' keyword

---

build-scripts/docker/generate-repo-files.sh

Sometimes we need to install unsigned packages from our own ad-hoc repo,
installing `apt-transport-https` makes sure we can do this (at least on
Debian Stretch).

Make sure we can install unsigned packages.

---

pdns/auth-carbon.cc
pdns/dnsdist-carbon.cc
pdns/misc.cc
pdns/misc.hh
pdns/rec-carbon.cc

On FreeBSD at least, HOST_NAME_MAX is not defined and we need to use sysconf() to get the value at runtime instead.
Based on a work done by @RvdE to make the recursor compile on FreeBSD (many thanks!).
This PR generalizes the work done in #9125 to cover the authoritative server and dnsdist as well.
I have:

Fix compilation on systems that do not define HOST_NAME_MAX

---

pdns/recursordist/test-syncres_cc2.cc
pdns/syncres.cc

With the introduction of qname minimization, a function
doResolveNoQNameMinimization() was introduced. This function is
called by doResolve() with depth incremented. Due to the recursive
nature of the resursor algortihm (Nomen est Omen) we end up
incrementing the depth too much. This prompted a review of the other
places depth was incremented, and I believe it should only be done
when calling doResolve(). Especially the case "+ 2" in the getAddrs()
call looks strange to me, as the doResolve() calls in getAddrs()
already call doResolve() with depth + 1.
This fixes #9184 and likely other cases of deep recursion caused
by long CNAME chains.
I have:

rec: Correct depth increments.

---

docs/settings.rst
docs/tsig.rst

``allow-axfr-ips`` is ignored when a TSIG key is defined for outbound AXFRs for a zone. This fact is not documented.
I have:

Clarify allow-axfr-ips behaviour in combination with TSIG

---

docs/settings.rst
pdns/recursordist/docs/manpages/pdns_recursor.1.rst
pdns/recursordist/docs/settings.rst

The 'local-address' setting accepts both IPv4 and IPv6 addresses,
and also accepts port numbers. This patch documents all of those
behaviors.
Signed-off-by: Kevin P. Fleming <kevin@km6g.us>

Clarify local-address documentation

---

modules/remotebackend/httpconnector.cc
modules/remotebackend/remotebackend.cc
modules/remotebackend/remotebackend.hh

These functions are called inside a try block in e.g. the
slavecommunicator and them `throw`ing actually makes the reporting
better.
I have:

Remote Backend: Throw DBException in functions that allow it

---

pdns/tcpreceiver.cc

Fixes #7795.
Avoid making new backends when we are going to either deny the XFR, or
fall back to AXFR anyway.
This cuts down the number of new backends from four (three for IXFR
pre-checks plus one for AXFR) to one (just the AXFR one).
When replying in IXFR mode, we keep making _one_ new backend, which is
also better than before.
While we now hold the s_plock for a while longer, we only take it once
in doIXFR; before we took it twice -- for TSIG retrieval, which now
re-uses the IXFR backend.
I have:

Optimize IXFR-to-AXFR fallback path

---

docs/http-api/index.rst
pdns/auth-packetcache.cc
pdns/auth-querycache.cc
pdns/common_startup.cc
pdns/statbag.cc
pdns/statbag.hh
pdns/ws-auth.cc

This PR introduces a simple metrics-endpoint to `auth` in a similar fashion as was done in #6901 for `dnsdist` (and should fix #4947). The metrics reflected on the end-point are all of the `stats` and `funcstats` in the global `StatBag` instance (which should be the same as the "variables" listed in the webservers index page).
Due to a different metrics infrastructure in the `auth` compared to `dnsdist`, I took the liberty to extend the `StatBag` with a `StatType` map to configure the metric-type at the point where it is declared. This might not be what you want, please let me know if you'd prefer this configuration in a separate structure.
I have:

Implemented prometheus metrics-endpoint for auth

---

pdns/tcpreceiver.cc

Backport of #9163 to 4.3.x.
Avoid making new backends when we are going to either deny the XFR, or
fall back to AXFR anyway.
This cuts down the number of new backends from four (three for IXFR
pre-checks plus one for AXFR) to one (just the AXFR one).
When replying in IXFR mode, we keep making _one_ new backend, which is
also better than before.
While we now hold the s_plock for a while longer, we only take it once
in doIXFR; before we took it twice -- for TSIG retrieval, which now
re-uses the IXFR backend.
I have:

auth-4.3.x: Optimize IXFR-to-AXFR fallback path

---

ext/lmdb-safe/lmdb-safe.hh
pdns/dnsdistdist/views.hh

There's a standard C++ macro to check for its existence.
libstdc++ from GCC makes it available under C++17 and up. libcxx from
LLVM makes it available everywhere.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
I have:
- [x ] compiled this code

use std::string_view when available

---

pdns/recursordist/test-syncres_cc1.cc
pdns/syncres.cc

A more fundamental fix to CNAME loops. Fixes #9153. We scan the names in the answer section for CNAMEs we've already seen.
Also see  #9194,  the throw in the CNAME cache lookup is needed to actually abort things.
Needs tests.
I have:

rec: more sophisticated cname loop detection.

---

pdns/dnsdistdist/doh.cc

it causes ambiguity if both std::string_view and boost::string_view are in scope
As seen on OpenBSD (sorry to have missed that earlier):
```
doh.cc:658:85: error: reference to 'string_view' is ambiguous
static bool getHTTPHeaderValue(const h2o_req_t* req, const std::string& headerName, string_view& value)
^
./views.hh:31:14: note: candidate found by name lookup is 'string_view'
using boost::string_view;
^
/usr/include/c++/v1/string_view:771:37: note: candidate found by name lookup is 'std::__1::string_view'
typedef basic_string_view<char>     string_view;
^
doh.cc:662:3: error: reference to 'string_view' is ambiguous
```
I have:

Do not use `using namespace std;` 

---

modules/gpgsqlbackend/spgsql.cc

Addresses #5292 (for postgres only).
Example logs:
```
Jun 02 19:23:19 Query 140202644522992: Statement: SELECT content,ttl,prio,type,domain_id,disabled::int,name,auth::int FROM records WHERE disabled=false and type=$1 and name=$2
Jun 02 19:23:19 Query 140202644522992: Parameters: $1 = 'SOA', $2 = 'example.com'
```
I have:

gpgsqlbackend: add parameters to query logging

---

.github/actions/spell-check/expect.txt
docs/backends/generic-postgresql.rst
modules/gpgsqlbackend/gpgsqlbackend.cc
modules/gpgsqlbackend/spgsql.cc
modules/gpgsqlbackend/spgsql.hh

Fixes #9029.
Defaults to using prepared statements, but they can be turned off for pgBouncer (et al) users.
I have:

gpgsql: Reintroduce prepared statements

---

pdns/filterpo.hh
pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/recursordist/docs/lua-config/rpz.rst

If an RPZ is active, an answer set by `gettag_ffi` should not be used unless there is no RPZ match. There are some subtle points;
1. If no policy is matched or it is `NoAction`, use the result from `gettag_ffi` if available.
2. You still might want to prefer the exising behaviour: set `overridesGettag=false` for that case when loading the RPZ.
I have:

Rec: rpz policy should override gettag_ffi answer by default

---

pdns/packethandler.cc

Create super slave domains with the right master ip when a trusted notification proxy and ecs are used.
I have:
master

auth: use real remote for supermaster createSlaveDomain()

---

pdns/cachecleaner.hh
pdns/pdns_recursor.cc

- Only prime share cache once on startup
- Cache pruning could go into an infinite loop if not enough expired
entries could be pruned.
- Handler thread isn't run very often, but now the record cache
pruning is done by it, so increase frequency of the housekeeping
call for the handler thread.
I have:

rec: Fix three shared cache issues

---

builder-support/debian/authoritative/debian-buster/pdns-backend-sqlite3.docs
builder-support/debian/authoritative/debian-jessie/pdns-backend-sqlite3.docs
builder-support/debian/authoritative/debian-stretch/pdns-backend-sqlite3.docs
builder-support/specs/pdns.spec
modules/gsqlite3backend/4.3.0_to_4.3.1_schema.sqlite3.sql
modules/gsqlite3backend/Makefile.am
modules/gsqlite3backend/schema.sqlite3.sql

Sqlite3 backend was performing terrible in environments with many updates.
On a slaved root zone the performance increase was huge, 71ms -> 1ms per uncached query.
Since the lack of proper indexes is causing a lot of trouble in larger environments, I target this update at 4.3.1
I have:

auth: gsqlite3backend: add missing indexes

---

pdns/dnsdistconf.lua

The idea is to be able to provide a default configuration file, including the basic blocks to build a basic configuration of dnsdist. We should then be able to install it as a default dnsdist.conf.
Hopefully closes #8038.
I have:

dnsdist: Clean up dnsdistconf.lua as a default configuration file

---

pdns/dnsdist-lua.cc
pdns/dnsdist-web.cc
pdns/dnsdist.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-web.hh
pdns/dnsdistdist/docs/guides/webserver.rst
pdns/dnsdistdist/docs/reference/config.rst
regression-tests.dnsdist/test_API.py

Implement the same kind of ACL for the internal web server that we have in the auth and rec, and restricts to 127.0.0.1 and ::1 by default.
I have:

dnsdist: Implement an ACL in the internal web server

---

pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh
pdns/recursordist/test-negcache_cc.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/recursordist/test-syncres_cc9.cc
pdns/syncres.cc
pdns/syncres.hh

Otherwise, in the unlikely case that:
- we need to go to the network in order to validate, for example to get a DNSKEY ;
- the negative cache cleaning is run at that exact moment ;
- and the entry we have a pointer to gets wiped during that cleanup
we might trigger a heap-based use-after-free (read), possibly leading to a crash if the memory has been reused already.
This PR is composed of a first commit doing exactly that, and only that. IMHO this is what we will want to backport to 4.3.x and 4.2.x to keep the change small.
The second commit basically reverts the change introduced in 4.2 (28364e4b7f88ccabd976037154395b6220301100) to prevent a copy when retrieving entries from the negative cache. That seemed like a good idea at the time, but the resulting interface is too brittle. It …

rec: Copy the negative cache entry before validating it

---

pdns/syncres.cc

(cherry picked from commit fe091a7206f833e6927b82b813b5af0882d8c5d9)
Backport of #9205 
I have:

rec: backport 9205 to rec 4.3.x: Limit the TTL of RRSIG records as well

---

pdns/recursordist/test-syncres_cc2.cc
pdns/syncres.cc

Backport of #9192 
With the introduction of qname minimization, a function
doResolveNoQNameMinimization() was introduced. This function is
called by doResolve() with depth incremented. Due to the recursive
nature of the resursor algortihm (Nomen est Omen) we end up
incrementing the depth too much. This prompted a review of the other
places depth was incremented, and I believe it should only be done
when calling doResolve(). Especially the case "+ 2" in the getAddrs()
call looks strange to me, as the doResolve() calls in getAddrs()
already call doResolve() with depth + 1.
This fixes #9184 and likely other cases of deep recursion caused
by long CNAME chains.
(cherry picked from commit a06745426b4df4d3946c36cd3429a5c8db9a8cd0)
I have:

rec: backport 9192 to rec 4.3.x: Correct depth increments.

---

pdns/pdns_recursor.cc

Backport of #9142 
If the NOD lookup is slow, for example because the destination
authoritative server is down, doing the NOD lookup before the response
has been sent increases the latency a lot.
This commit moves the actual NOD lookup after the response has been
sent, so we can still use the existing mthread (we might actually need
to do a proper DNS resolution to find the target authoritative server)
without keeping the client waiting.
(cherry picked from commit 3bd27e4a01a3614aba3c0cf425e4ab9490318dd4)
I have:

rec: backport 9142 to 4.3.x: Defer the NOD lookup until after the response has been sent

---

pdns/cachecleaner.hh
pdns/recpacketcache.cc
pdns/recpacketcache.hh
pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh

- use size_t instead of unsigned int for sizes
- const correctness
- layout
- use return value of erase(), it points to the next value
I have:

Cleanup cache cleaner pruneCollection function

---

pdns/dnsdist-web.cc
pdns/ws-auth.cc
pdns/ws-recursor.cc

This PR adds a metric called `${SERVICE}_info` that is always `1`. But its labels are then used to ship the version number. This is similar to `node_exporter`'s `node_uname_info` metric.
I have:

Add version 'statistic' to prometheus

---

pdns/syncres.cc
pdns/syncres.hh

Backport of #9251 
Otherwise, in the unlikely case that:
- we need to go to the network in order to validate, for example to
get or a DNSKEY ;
- the negative cache cleaning is run at that exact moment ;
- and the entry we have a pointer to gets wiped during that cleanup
we might trigger a heap-based use-after-free (read), possibly leading
to a crash if the memory has been reused already.
I have:

rec: backport 9251 to re 4.2.x: Copy the negative cache entry before validating it

---

pdns/syncres.cc
pdns/syncres.hh

Backport of #9251 
Otherwise, in the unlikely case that:
- we need to go to the network in order to validate, for example to
get or a DNSKEY ;
- the negative cache cleaning is run at that exact moment ;
- and the entry we have a pointer to gets wiped during that cleanup
we might trigger a heap-based use-after-free (read), possibly leading
to a crash if the memory has been reused already.
I have:

rec: backport 9251 to rec 4.3.x: Copy the negative cache entry before validating it

---

pdns/pdns_recursor.cc
pdns/recursordist/test-syncres_cc.cc
pdns/reczones.cc
pdns/syncres.cc
pdns/syncres.hh

If you clear the cache for . in a tight loop, the priming code gets
called recursively in an unbounded fashion. This keeps track of the
stack depth and ServFails if needed.
I have:

rec: Control stack depth when priming.

---

docs/backends/generic-postgresql.rst

Adds documentation on how to run PowerDNS authoritative on CockroachDB. Based on testing in #5375 . Includes pointers on what schema and configuration changes to make, and a reference to the original content on Github for further details.
I have:

Add instructions for running PowerDNS on CockroachDB using generic pgsql

---

pdns/pdns_recursor.cc

- An uncaught exception being raised in `houseKeeping` could prevent it from being run again because `s_running` would stay true. That could for example happen when an `ImmediateServFailException` was raised during a call to `primeRootNSZones()` ;
- An `ImmediateServFailException` being raised during the call to `SyncRes::beginResolve()` from `handleRPZCustom()` could lead to the resolution process to stop without any response being sent:
```
Any other exception in a resolver context (www.example.net/A from 127.0.0.1:4242)
```
This commit turns into a ServFail answer instead.
I have:

rec: Better exception handling in houseKeeping / handlePolicyHit

---

regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_TCPLimits.py

This test keeps failing on Circle CI but never locally, so let's try to add some debug.
I have:

dnsdist: Debug failures in the TCP Limits regression test on Circle

---

builder-support/debian/authoritative/debian-buster/pdns-backend-sqlite3.docs
builder-support/debian/authoritative/debian-jessie/pdns-backend-sqlite3.docs
builder-support/debian/authoritative/debian-stretch/pdns-backend-sqlite3.docs
builder-support/specs/pdns.spec
modules/gsqlite3backend/4.3.0_to_4.3.1_schema.sqlite3.sql
modules/gsqlite3backend/Makefile.am
modules/gsqlite3backend/schema.sqlite3.sql

Sqlite3 backend was performing terrible in environments with many updates.
On a slaved root zone the performance increase was huge, 71ms -> 1ms.
Since the lack of proper indexes is causing a lot of trouble in larger environments, I target this update at 4.3.1
Backport of #9228
I have:

auth-4.3.x: gsqlite3backend: add missing indexes

---

pdns/recursordist/test-syncres_cc9.cc
pdns/syncres.cc
pdns/syncres.hh

The current code effectively disables lookup of cached CNAME results
for zone cut computations, which results in more queries than needed.
Should fix #9266 or at least give more insight.
Needs critical eyes badly!
I have:

rec: alternative way to do "skip cname check" for DS and DNSKEY records.

---

pdns/recursordist/docs/settings.rst

This question comes up every few weeks, and while there is no strong argument between our choice to not set the AA bit, it is good to at least note that we don't.
I have:

recursor: clarify that auth-zones are not served with an AA bit

---

pdns/recursordist/test-syncres_cc8.cc
pdns/validate.cc

A NSEC from a.powerdns.com. to a.b.powerdns.com. proves that b.powerdns.com. exists and is an empty non terminal, so it cannot be used to prove that b.powerdns.com. does not exist.
I have:

rec: Don't validate a NXD with a NSEC proving that the name is an ENT

---

pdns/dnsdistdist/doh.cc
pdns/doh.hh

This PR fixes a race between the different threads involved in DoH handling, leading to use-after-free and a crash in some cases. This is done by making sure that the h2o req object is only accessed from the main DoH thread, where it can't be altered by h2o in the meantime, and by preventing any access to it once the request has been canceled by h2o. It also makes sure that the pointer to our internal DOHUnit object is cleared from the h2o request pool before releasing that DOHUnit object.
This change involves a penalty cost because we now need to copy the HTTP headers, if any, because we need to access them from a different thread than the main DoH one and the internal memory handled by h2o could be gone then, or even be altered under our feet.
This issue was discovered by Tomas Krizek …

dnsdist: Prevent race between the DoH handling threads

---

pdns/recursordist/negcache.cc
pdns/recursordist/test-negcache_cc.cc

Dumping the authority records as well is useful for debugging, for example to understand the root of a DNSSEC validation failure.
I have:

rec: Dump the authority records of a negative cache entry as well

---

pdns/recursordist/test-syncres_cc5.cc

Fix wrong RRSIGs in a unit test, where the DS (or denial of) was signed by the child zone instead of the parent zone.
I have:

rec: Fix invalid signatures in a test (DS signed by the child zone)

---

pdns/validate.cc
pdns/validate.hh

This PR specifies a storage type for the validation state enumerations and defines the corresponding `<<` operators. This should save some space in memory and make it easier to read validation traces by printing a user-friendly name instead of an integer value in several cases.
I have:

rec: Specify a storage type for validation states

---

pdns/recursordist/test-syncres_cc5.cc
pdns/syncres.cc

Before that commit, failing to get the DS or DNSKEY records needed during validation because of a network issue would trigger a Bogus DNSSEC validation result because validation could not be performed, but that should just be a Server Failure instead.
This is especially an issue because the Bogus result would get inserted into the cache and could stay there for as long as
'max-cache-bogus-ttl' seconds.
I have:

rec: A ServFail while retrieving DS/DNSKEY records is just that

---

pdns/syncres.cc

There is no good reason to query that type, and we used to accept the query, even sending a query with TYPE0 to authoritative servers.
I have:

rec: Refuse QType 0 right away, based on rfc6895 section 3.1

---

pdns/rpzloader.cc

When no rpz cache is used and no refresh time is specified, use the refresh time read on the initial load of the zone.
Should fix #9299, though I need to test a few more cases.
I have:

rec: take initial refresh time  from loaded zone  

---

pdns/rpzloader.cc

When no rpz cache is used and no refresh time is specified, use the refresh time read on the initial load of the zone.
Should fix #9299.
(cherry picked from commit 3f4d728767f3924b4b96b22e6ae312ba8decdfe9)
Backport of #9301 
I have:

rec: backport 9301 to rec 4.3.x: take initial refresh time from loaded zone

---

pdns/syncres.cc

When the DNSKEYs are needed for validation, the initial RD flag should not prevent us from going to the network. This was fine in most cases because the DNSKEYs are usually retrieved during the computation of the zone cuts, where we already ignore the RD flag, but we might also need to retrieve the DNSKEYs during just-in-time validation later on.
I have:

rec: Ignore cache-only for DNSKEYs retrieval

---

pdns/recursordist/test-syncres_cc4.cc
pdns/syncres.cc

DNSKEYs might be cached in a non-validated state ("Indeterminate") when the DNSSEC mode is set to "Process" and the initial query did not ask for validation.
We would then validate the DNSKEY records against the RRSIGs, like for regular records, but not against the DSs.
As discussed during initial review, this change applies the same validation to cached records than we use when we validate new records directly, so I'm quite confident this would not introduce new issues, but we might have existing ones :)
The longer explanation is that `validateDNSKeysAgainstDS()`, called by `validateDNSKeys()`, will do a first pass where it will select DNSKEYs that are directly matched by a DS. If all keys have been selected in that way, ie we have only CSKs, all is good and we will stop there. Otherwise …

rec: Validate cached DNSKEYs against the DSs, not the RRSIGs only

---

configure.ac
pdns/dnsdistdist/configure.ac
pdns/recursordist/configure.ac

Been running this on my test OpenBSD/arm64 box for a while.
I have:

Use explicit flag for the specific version of c++ wer'e targeting.

---

pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh
pdns/recursordist/test-syncres_cc1.cc
pdns/recursordist/test-syncres_cc2.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc5.cc
pdns/recursordist/test-syncres_cc6.cc
pdns/recursordist/test-syncres_cc7.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/recursordist/test-syncres_cc9.cc
pdns/reczones.cc
pdns/secpoll-recursor.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/test-recpacketcache_cc.cc
pdns/toysdig.cc
pdns/validate.cc
pdns/validate.hh

Also rename the `NODATA` state to `NODENIAL`, as the existing name could easily be confused with `NXQTYPE`.
This has no functional impact, but makes the code cleaner.
I have:

rec: Stop cluttering the global namespace with validation states

---

modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
pdns/backends/gsql/gsqlbackend.cc
pdns/backends/gsql/gsqlbackend.hh
pdns/dnsbackend.hh
pdns/pdnsutil.cc
pdns/ueberbackend.cc
pdns/ueberbackend.hh
pdns/ws-auth.cc

Immediately fill out account, kind and masters when creating a zone (and if we have that info).
For backends supporting zone creation (gsql, lmdb).
Implements #9232 
I have:

auth: immediately fill account, kind, masters on zone create

---

pdns/recursordist/test-syncres_cc5.cc
pdns/syncres.cc

Before that commit, failing to get the DS or DNSKEY records needed
during validation because of a network issue would trigger a Bogus
DNSSEC validation result because validation could not be performed,
but that should just be a Server Failure instead.
This is especially an issue because the Bogus result would get
inserted into the cache and could stay there for as long as
'max-cache-bogus-ttl' seconds.
(cherry picked from commit e122af1cf073cab4bd0b1b346b6e166b49870d70)
#backport of #9292 
I have:

rec: backport 9292 to rec 4.3.x: A ServFail while retrieving DS/DNSKEY records is just that

---

pdns/syncres.cc

rec: Backport 9297 to rec 4.3.x: Ignore cache-only for DNSKEYs and DS retrieval 
