PowerDNS/pdns

pdns/recursordist/test-syncres_cc9.cc, pdns/syncres.cc
=> rec: Backport 9188 to rec 4.3.x: Refuse DS records received from child zones 

pdns/recursordist/test-syncres_cc9.cc, pdns/syncres.cc
=> rec: Backport 9188 to rec 4.2.x: Refuse DS records received from child zones 

pdns/recursordist/test-syncres_cc5.cc, pdns/syncres.cc
=> rec: Backport 9292 to rec 4.2.x: A ServFail while retrieving DS/DNSKEY records is just that

pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Update config.rst

pdns/backends/gsql/gsqlbackend.cc, pdns/pdns_recursor.cc, pdns/rfc2136handler.cc, pdns/rpzloader.cc, pdns/syncres.cc
Already handled by Logger.
I have:
=> Remove redundant toLogString() calls

pdns/recursordist/test-syncres_cc4.cc, pdns/validate.cc
As required by rfc4034 Section 5.2. That should not make any difference in practice.
I have:
=> rec: Check that DNSKEYs have the zone flag set

docs/http-api/index.rst
=> auth docs: note that /metrics is new in 4.4; closes #9325

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.2.rst, pdns/recursordist/docs/changelog/4.3.rst
=> rec: Prep for upcoming July 17th 2020 release.

.github/actions/spell-check/expect.txt, docs/secpoll.zone, pdns/recursordist/docs/changelog/4.4.rst
=> rec: prep for rec-4.4.0-alpha2

pdns/iputils.hh, pdns/lua-record.cc
Fixes #9279
Patch taken from issue.
I have:
=> Avoid name clashes on Solaris derived systems.

pdns/dnsdistdist/doh.cc
Reported by Stéphane Bortzmeyer (thanks!).
I have:
=> dnsdist: Fix compilation with h2o_socket_get_ssl_server_name

regression-tests/backends/gmysql-slave
Fix uppercase/lowercase mixup in variable name.
I have:
=> auth tests gmysql2: fix env var name typo

pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
Closes https://github.com/PowerDNS/pdns/issues/4470.
I have:
=> dnsdist: Handle calling PacketCache methods on a nil object

.github/actions/spell-check/expect.txt, docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Update ChangeLog and secpoll for the 1.5.0 release

pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Fix weird UTF-8 character in the ChangeLog

build-scripts/test-recursor-bulk, regression-tests/recursor-test
=> Rec: run test with more threads and skip the last (repeated) test

pdns/dnsdist-lua-bindings.cc, pdns/dnsdistdist/dnsdist-lua-ffi-interface.h, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsdistdist/docs/reference/config.rst
So custom load-balancing policies can use it.
I have:
=> dnsdist: Add Lua bindings to get a server's latency

modules/pipebackend/coprocess.cc, modules/pipebackend/coprocess.hh, pdns/dnsdist-cache.cc, pdns/dnspcap.cc, pdns/dnspcap.hh, pdns/dnspcap2protobuf.cc, pdns/dnstcpbench.cc, pdns/ixfrutils.cc, pdns/recursordist/test-negcache_cc.cc
=> Wrap more FILE objects in smart pointers

docs/upgrading.rst, pdns/dnsrecords.cc
=> Report IPSECKEY

pdns/recursordist/docs/settings.rst
=> Be explicit about IPs vs netmasks.

docs/appendices/backend-writers-guide.rst, docs/domainmetadata.rst, modules/bindbackend/bindbackend2.cc, modules/geoipbackend/geoipbackend.cc, modules/gmysqlbackend/gmysqlbackend.cc, modules/godbcbackend/godbcbackend.cc, modules/gpgsqlbackend/gpgsqlbackend.cc, modules/gsqlite3backend/gsqlite3backend.cc, modules/ldapbackend/ldapbackend.cc, modules/lmdbbackend/lmdbbackend.cc, modules/lua2backend/lua2backend.cc, modules/pipebackend/pipebackend.cc, modules/randombackend/randombackend.cc, modules/remotebackend/remotebackend.cc, modules/tinydnsbackend/tinydnsbackend.cc, pdns/Makefile.am, pdns/dnsbackend.cc, pdns/dnsbackend.hh, pdns/pdnsutil.cc, pdns/test-ueberbackend_cc.cc, pdns/ueberbackend.cc, pdns/ueberbackend.hh
This PR adds a few unit tests for the `UeberBackend` and tries to document a few corner case of multi-backend interactions.
Needs a thorough review by someone that understands how PowerDNS is supposed to work with multiple backends :-) 
I have:
=> auth: Add some UeberBackend unit tests, document multi-backend interactions

pdns/slavecommunicator.cc
Adds the used master address to all slave check "result" logs.
Should help with debugging issues when multiple masters are configured, and also clarify once and for all that the checked master is being used for the following AXFR.
I have:
=> auth: add used master address to slave check logs

docs/backends/generic-postgresql.rst, modules/gpgsqlbackend/gpgsqlbackend.cc, modules/gpgsqlbackend/spgsql.cc, modules/gpgsqlbackend/spgsql.hh
Backport of #9190, ignoring the larger cleanup in spgsql.cc done there.
I have:
=> auth 4.3.x: gpgsql: Reintroduce prepared statements

modules/geoipbackend/geoipbackend.cc
In the case of weighted round robin, we will give back only one
GeoIPDNSResourceRecord, so once we found it, there is no point to
keep looking except inducing a performance penalty.
This commit ensures we stop looking after we found our first weighted
match.
I have:
=> geoipbackend: stop looking after first weighted match

pdns/lua-auth4.cc
Otherwise we might fail to strip a trailing dot for some records.
Fixes #7429.
I have:
=> auth: Ensure qtype is set before calling setContent() in axfrfilter()

pdns/dnsdistdist/docs/upgrade_guide.rst
We forgot to mention this and it is leading to questions!
(This means people -do- read the upgrade notes, which is great news.)
I have:
=> dnsdist upgrade notes: note new webserver ACL

pdns/pdns_recursor.cc, pdns/recursordist/docs/settings.rst, regression-tests/recursor-test
=> rec: rename cache-shards to record-cache-shards and document it.

docs/http-api/zone.rst
=> Fix capitalization of Zone in documentation

.github/actions/spell-check/expect.txt
=> fix spelling dict after merge of 9264

pdns/lua-record.cc, regression-tests.auth-py/test_LuaRecords.py
* Allow the createForward record to lay deeper than directly underneath
the zone's apex.
* Add dashed IP address support to createForward
We might need to figure out where else we get the 'name not directly underneath the apex' wrong.
Also, lacks tests.
I have:
=> LUA records: two improvements to createForward

docs/http-api/tsigkey.rst
=> rst: Definition list ends without a blank line; unexpected unindent

pdns/pdns_recursor.cc, pdns/rec_channel_rec.cc, pdns/reczones.cc, pdns/webserver.cc, pdns/ws-recursor.cc
lambdas are standard C++. bind is also recommended against by LLVM.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
I have:
=> replace boost:bind() with lambdas

build-scripts/test-recursor
=> test-recursor: remove duplicate cd directive

pdns/Makefile.am, pdns/common_startup.cc, pdns/dnsdistdist/Makefile.am, pdns/pdns_recursor.cc, pdns/recursordist/Makefile.am
=> rec: Backport 9073 to rec 4.3.x: Ensure runtime dirs for virtual services differ

pdns/pdnsutil.cc
This avoids a missing-declaration compiler warning.
I have:
=> pdnsutil: file-local functions need to be static

docs/appendices/backend-writers-guide.rst
=> doc: Fix broken link to "per-zone-settings-domain-metadata"

pdns/rec-snmp.cc, pdns/rec_channel_rec.cc, pdns/recursordist/RECURSOR-MIB.txt, pdns/recursordist/docs/metrics.rst
=> rec: export record cache mutex stats via the various channels.

pdns/rec_channel_rec.cc
See e.g. coverity report 1431930
Exceptions seem to come from a "cannot happen" case in `allocator_version_traits.hpp`. Still it is a good thing to kill these, since they clutter the coverity reports.
I have:
=> rec: Clean some coverity reported cases of exceptions thrown but not caught.

pdns/backends/gsql/gsqlbackend.hh
=> auth: missing override

pdns/pdns_recursor.cc
Please double check this twice if it is ok for the capture to be done like this. data is thread local, is it safe to use a reference here?
I have:
=> rec: Fix warning: initialized lambda captures are a C++14 extension

.circleci/config.yml
=> dnsdist: Install 'patch' in Circle CI, required to install py-lmdb

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.4.rst
=> Prep for rec-4.4.0-beta1 release

modules/gmysqlbackend/smysql.cc
Yes another attempt at fixing #9421.
I have:
=> auth: Handle the extra single-row result set of MySQL stored procedures

.circleci/config.yml, regression-tests/backends/gmysql-master, regression-tests/start-test-stop
Add a test suite using (a) stored procedure for gmysql.
Needs to be merged after #9423. 
I have:
=> auth: add mysql stored procedure code test

docs/http-api/swagger/authoritative-api-swagger.yaml, docs/http-api/tsigkey.rst, docs/index.rst, docs/manpages/pdns_control.1.rst, docs/settings.rst
=> RST cleanup

builder-support/specs/pdns.spec
This matches EPEL downstream.
Backport of #9033
Needs an upgrade note!
I have:
=> auth-4.3.x: EL8 pkgs: Build mysql backend against mariadb-connector-c-devel

pdns/sdig.cc
As stated in section 6.2.1 of rfc7766:
>   "When sending multiple queries over a TCP connection, clients MUST NOT
reuse the DNS Message ID of an in-flight query on that connection in
order to avoid Message ID collisions.  This is especially important
if the server could be performing out-of-order processing"
I have:
=> sdig: Increment the DNS message IDs when pipelining

docs/upgrading.rst
=> auth 4.3.1 upgrade note for the mysql client lib

pdns/recursordist/docs/dns64.rst
=> rec docs: link to multi-prefix dns64 example on our wiki

builder-support/debian/authoritative/debian-buster/config/geoip.conf, builder-support/debian/authoritative/debian-jessie/config/geoip.conf, builder-support/debian/authoritative/debian-stretch/config/geoip.conf
- The documentation of the backend has moved to a new URL ;
- 'geoip-database-file' has been renamed to 'geoip-database-files' ;
- 'geoip-database-file6' does not exist anymore.
I have:
=> auth: Fix the sample 'geoip.conf' for Debian-based packages

codedocs/doxygen.conf
Exclude test-* files and avoid processing the same files multiple times (symlinks).
I have:
=> Update doxygen config

pdns/dnsdistdist/docs/rules-actions.rst
so document it as mandatory
I have:
=> dnsdist docs: TCPRule argument is not optional

pdns/recursordist/test-syncres_cc3.cc, pdns/syncres.cc
=> rec: When deciding if we are auth in the local auth or forwarding case, DS is special

.circleci/config.yml, modules/gmysqlbackend/smysql.cc, regression-tests/backends/gmysql-master, regression-tests/start-test-stop
Issue #9421, for 4.3.x.
- Partial backport of #9044, master commit a5d2c08.
- Backport of #9422, master commit ca32c9e.
- Backport of #9423, master commit f8289e5.
I have:
=> MySQL stored-procedure fix backport for 4.3.x

ext/yahttp/yahttp/reqresp.cpp
=> Fix building remote backend on GCC 10

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.3.rst
=> rec: Changelog and secpoll rec-4.3.4

pdns/pdns_recursor.cc
=> Parts is reused, so clear the names it might contain.

pdns/pdns_recursor.cc
(cherry picked from commit bc3d2b7386e058c39872a3aa74101283b6f1af45)
Backport of #9454 
I have:
=> rec: backport to 4.2.x: Parts is reused, so clear the names it might contain.

.circleci/config.yml, .travis.yml
=> rec-4.3.x: Remove non-recursor tests

.circleci/config.yml, .travis.yml
=> rec-4.4.x: Remove non-recursor tests

pdns/pdns_recursor.cc
(cherry picked from commit bc3d2b7386e058c39872a3aa74101283b6f1af45)
I have:
=> rec: backport to 4.4.x: Parts is reused, so clear the names it might contain.

pdns/pdns_recursor.cc
(cherry picked from commit bc3d2b7386e058c39872a3aa74101283b6f1af45)
Backport of #9454 
I have:
=> rec: Backport to rec-4.3.x: Parts is reused, so clear the names it might contain.

pdns/recursordist/examples/safesearch.lua
Add Safe Search for Youtube and DuckDuckGo to the example lua
I have:
=> Add youtube and duckduckgo

pdns/sdig.cc
=> auth-4.3.x: sdig: Increment the DNS message IDs when pipelining

pdns/dnsdist-lua-bindings.cc, pdns/dnsdistdist/docs/reference/dnsname.rst, pdns/dnsdistdist/docs/rules-actions.rst
Also added a note to the `SpoofRawAction` docs.
I have:
=> dnsdist dnsname: add toDNSString convenience function

docs/manpages/pdns_control.1.rst
=> Add pdnsutil to see also for pdns_control

pdns/syncres.cc, pdns/syncres.hh
=> rec: Backport 9448 to rec 4.4.x: We only want to do QName Minimization for the names in a forwarded  domain.

pdns/recursordist/docs/http-api/endpoint-failure.rst, pdns/recursordist/docs/metrics.rst, pdns/recursordist/docs/settings.rst
=> rec: Fix a few .rst warnings

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.4.rst
=> rec: prep for rec-4.4.0-rc1

pdns/pdns_recursor.cc
This can be handy to see what commands were issued to the recursor
when reviewing logs.
I have:
=> Log the line received fomr rec_control

pdns/dnsparser.cc, pdns/test-dnsrecords_cc.cc
=> auth-4.3.x: raise an exception on invalid content in unknown records

pdns/dnsparser.cc, pdns/test-dnsrecords_cc.cc
=> auth-4.2.x: raise an exception on invalid content in unknown records 

pdns/dnsparser.cc, pdns/test-dnsrecords_cc.cc
=>  auth-4.1.x: raise an exception on invalid content in unknown records #9499 

pdns/dnsparser.cc, pdns/recursordist/test-syncres_cc3.cc, pdns/test-dnsrecords_cc.cc
=> auth: raise an exception on invalid content in unknown records

pdns/rec-snmp.cc
=> rec: incomplete ifdef

pdns/rec_channel_rec.cc
=> rec: Check return value of dup(2) as noted by coverity.

docs/changelog/4.1.rst, docs/changelog/4.2.rst, docs/changelog/4.3.rst, docs/secpoll.zone, docs/security-advisories/powerdns-advisory-2020-05.rst, docs/security-advisories/powerdns-advisory-2020-06.rst, docs/upgrading.rst
=> auth 22 sept 2020: advisories, changelogs, docs

build-scripts/docker/generate-repo-files.sh
=> generate-repo-files: various updates

pdns/validate.cc
It has not been used for a long time, since we removed the code to generate DOT files.
I have:
=> rec: Remove unused vector of tags in validateDNSKeysAgainstDS()

pdns/dbdnsseckeeper.cc, pdns/dnsseckeeper.hh, pdns/packethandler.hh, pdns/rfc2136handler.cc
The number of yaks in the metadata cache was impressive. This pull will hopefully make them an extinct species :)
I have:
=> auth: improve metadata caching

pdns/dnsparser.cc, pdns/recursordist/test-syncres_cc3.cc, pdns/test-dnsrecords_cc.cc
=> rec: Backport 9497 to rec 4.4.x: raise an exception on invalid content in unknown record

pdns/dnsparser.cc
Minimal backport of #9497 
I have:
=> rec: Backport essential part of #9497 to rec-4.3.x: raise an exception on invalid content in unknown records 

pdns/dnsparser.cc
MInamal backport of #9497 
I have:
=> Rec: minimal backport of 9497 to rec 4.2.x: raise an exception on invalid content in unknown records

pdns/packethandler.cc
We should never reach this place, but just in case, let's get the DB in a clean state.
I have:
=> auth: avoid bad DB state in impossible situation; fix a typo

modules/lmdbbackend/lmdbbackend.cc
=> Fix a small coverity issue in lmdb backend and fix a compiler warning

.circleci/config.yml
Backport of #9426 to dnsdist-1.5.x.
(cherry picked from commit c17a2921a6096535bbaac837ed2d2db369091e58)
I have:
=> dnsdist-1.5.x: Install 'patch', required to install py-lmdb

.circleci/config.yml, .travis.yml
=> dnsdist-1.5.x: Disable non-dnsdist tests

pdns/rec_channel_rec.cc, pdns/recursor_cache.cc, pdns/reczones.cc, pdns/syncres.hh, pdns/ws-recursor.cc
=> rec: Backport #9515 to rec 4.4.x: actually fix wipe-cache-typed

pdns/pdns_recursor.cc, pdns/recursordist/docs/settings.rst
=> Recursor: Remove query-local-address6

pdns/recursordist/test-syncres_cc2.cc
We succeed (that is do not go into an endless loop) and we need to keep it that way.
I have:
=> rec: add unit test for potential NS loop.

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: ChangeLog and secpoll update for 1.5.1

builder-support/specs/pdns-recursor.spec, builder-support/specs/pdns.spec
Tested with build.sh. I did not check if the resulting binaries run and do the right thing in the affected bit of code.
I have:
=> el6: set __STDC_FORMAT_MACROS during package builds

.github/actions/spell-check/expect.txt, build-scripts/docker/generate-repo-files.sh, docs/changelog/4.4.rst, docs/changelog/index.rst, docs/secpoll.zone, docs/upgrading.rst
=> auth: changelog for 4.4.0-alpha1

pdns/recursordist/docs/http-api/endpoint-cache.rst, pdns/ws-recursor.cc
=> rec: Expose typed cache flush via Web API

pdns/recursordist/docs/http-api/endpoint-cache.rst, pdns/ws-recursor.cc
=> rec: Backport 9562 to rec 4.4.x: Expose typed cache flush via Web API 

pdns/recursordist/test-syncres_cc3.cc, pdns/syncres.cc
=> rec: Backport 9434 to rec 4.4.x: When deciding if we are auth in the local auth or forwarding case, DS is special

README.md
Especially for gpgsql, we do not need the full postgresql-server-dev package.
I have:
=> auth: update bionic packages in README

pdns/recursordist/docs/settings.rst, pdns/recursordist/docs/upgrade.rst
=> rec: News/changed settings for 4.4.x upgrade guide.

pdns/zone2sql.cc
=> auth: remove always true conditions in zone2sql

pdns/rec-protobuf.cc
=> rec: NULL check for return value of mutable_response() as noted by CodeQL

pdns/Makefile.am, pdns/ixfrutils.hh
=> Missing include guards as noted by CodeQL

.github/workflows/codeql-analysis.yml
and reduce make concurrency for dnsdist. This is my best guess for explaining the build failures.
I have:
=> codeql: separate build steps for auth/rec/dnsdist

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.4.rst
=> rec: Prep for rec-4.4.0-rc2

pdns/opensslsigners.cc
=> auth: Rewrite OpenSSLRSADNSCryptoKeyEngine::fromISCMap to be less tricky

pdns/recursor_cache.cc
=> rec: Backport of CVE-2020-25829 (any-cache-update) to 4.1.x

pdns/recursor_cache.cc, pdns/recursor_cache.hh, pdns/recursordist/test-syncres_cc8.cc, pdns/syncres.cc, pdns/validate.cc, pdns/validate.hh
=> Rec: Security 2020-07

pdns/syncres.cc
=> rec: Backport of CVE-2020-25829 (any-cache-update) to 4.2.x

pdns/recursor_cache.cc, pdns/recursor_cache.hh, pdns/recursordist/test-syncres_cc8.cc, pdns/syncres.cc, pdns/validate.cc, pdns/validate.hh
=> rec: Backport of CVE-2020-25829 (any-cache-update) to 4.3.x

pdns/recursor_cache.cc, pdns/recursor_cache.hh, pdns/recursordist/test-syncres_cc8.cc, pdns/syncres.cc, pdns/validate.cc, pdns/validate.hh
=> rec: Backport of CVE-2020-25829 (any-cache-update) to 4.4.x 

.github/actions/spell-check/expect.txt, docs/secpoll.zone, pdns/recursordist/docs/changelog/4.1.rst, pdns/recursordist/docs/changelog/4.2.rst, pdns/recursordist/docs/changelog/4.3.rst, pdns/recursordist/docs/security-advisories/powerdns-advisory-2020-07.rst
=> rec: Prep for rec Oct 13th 2020 security releases

pdns/dnsdistdist/docs/reference/dq.rst
=> dnsdist: Add the missing documentation for some dnsheader methods

.dockerignore, .gitignore, Dockerfile-auth, Dockerfile-dnsdist, Dockerfile-recursor, docker-compose.yml, dockerdata/dnsdist-resolver.lua, dockerdata/dnsdist-resolver.py, dockerdata/dnsdist.conf, dockerdata/pdns.conf, dockerdata/recursor.conf, dockerdata/startup.py, pdns/dnsdistdist/docs/reference/config.rst
Todo:
Reviews welcome though!
I have:
=> auth/rec/dnsdist: dockerise

pdns/dnsbackend.cc, pdns/dnsrecords.hh, pdns/nsec3dig.cc, pdns/nsecrecords.cc, pdns/rfc2136handler.cc
=> Fix some FIXME400s

docs/settings.rst, pdns/common_startup.cc, pdns/nameserver.cc, pdns/tcpreceiver.cc
=> auth: remove local-ipv6, query-local-address6

docs/secpoll.zone, pdns/recursordist/docs/appendices/EOL.rst, pdns/recursordist/docs/changelog/4.0.rst, pdns/recursordist/docs/changelog/4.1.rst, pdns/recursordist/docs/changelog/4.4.rst, pdns/recursordist/docs/changelog/pre-4.0.rst
Also updating EOL statements and adding notes to the old release notes to warn they are EOL.
I have:
=> Prep rec-4.4.0

.github/workflows/codeql-analysis.yml
This should avoid build failures after #9570
I have:
=> explicitly generate the protobuf parsers/generators

modules/bindbackend/bindbackend2.cc, pdns/dynloader.cc, pdns/notify.cc, pdns/nproxy.cc, pdns/sstuff.hh
Some places included namespaces.hh twice.
I have:
=> Including namespaces.hh once is enough

docs/settings.rst, modules/lmdbbackend/lmdbbackend.cc, pdns/dbdnsseckeeper.cc, pdns/packethandler.cc
=> auth: fix memory problems and an uninitalized variable

pdns/webserver.cc
Followup to the backport of #9070
I have:
=> rec: followup to backport of 9070 to 4.3.x: Previous placeholder fix was incomplete.

pdns/webserver.cc
Followup to backport of #9070.
I have:
=> rec: followup to backport of 9070 to 4.2.x: Previous placeholder fix was incomplete.

pdns/pdns_recursor.cc
Eistign code rouns down since `double` -> `uint64_t` conversion truncates
I have:
=> rec: Refactor the percentage computation and use rounding 

pdns/recursordist/docs/nod_udr.rst
Fix typo in Recursor NOD documentation
I have:
=> Fix typo in Recursor NOD documentation

pdns/dnsdistdist/docs/rules-actions.rst
=> dnsdist: fix doc warning "Unknown target name" in rules-actions.rst

docs/appendices/backend-writers-guide.rst, pdns/dnsbackend.hh, pdns/slavecommunicator.cc, pdns/tcpreceiver.cc, pdns/ueberbackend.cc, pdns/ueberbackend.hh
Makes reasoning about #9007 easier.
I have:
=> Remove UeberBackend::getSOA

pdns/rpzloader.cc
Small rewrite to make it more clear (I hope). Should also clear an initialized var warning from CodeQL.
I have:
=> rec: Cleanup of RPZ refresh handling

pdns/slavecommunicator.cc
This pull fixes the problems introduced by #9470 and some issues around 0 serials in slave zones.
Fixes #9646
Tested (and working) for slaves:
- 0 serials
- notifies
- serial roll-over
I have:
=> auth: partial revert of #9470

.dockerignore, Dockerfile-auth, Dockerfile-dnsdist, Dockerfile-recursor, Makefile.docker
See TODO list in #9618 
I have:
=> docker: phase 2

docs/index.rst, pdns/dnsdistdist/docs/index.rst, pdns/recursordist/docs/index.rst
=> docs: point sales requests toward OX

modules/lmdbbackend/lmdbbackend.cc
replaceRRSet was adding records without content.
I have:
=> auth: lmdb fix repaceRRSet()

.github/workflows/codeql-analysis.yml
=> codeql: run apt-get update before installing dependencies

pdns/pdns_recursor.cc, regression-tests.recursor-dnssec/test_Lua.py
=> rec: Backport 9679 to rec 4.4.x: Fix the processing of answers generated from gettag

modules/bindbackend/Makefile.am, modules/bindbackend/binddnssec.cc
I assume this was in there for historical reasons.
I have:
=> auth: remove duplicated Makefile target for bind dnssec schema

regression-tests/README.md
=> remove outdated regression docs, fixes #7925

.circleci/config.yml
=> circleci: authenticate to Docker Hub

modules/gpgsqlbackend/spgsql.cc
=> spgsql: fix a typo of mine in a comment

pdns/bindparser.yy, pdns/test-bindparser_cc.cc
Fixes: Parsing file: ./zones//sub.test.dyndns, domain: sub.test.dyndns
I have:
=> BIND: avoid double //

pdns/pdnsutil.cc, regression-tests/backends/bind-master, regression-tests/backends/gsql-common, regression-tests/backends/lmdb-master
* pdnsutil: show active flag in list-keys - fixes #4667 
* pdnsutil: validate key id when (de)activating - fixes #2212
* pdnsutil: extend Algorithm field size
* pdnsutil: check for domain existence in (de)activate-tsig-key - fixes #8758
I have:
=> pdnsutil zone key improvements

Docker-README.md, README.md
With a reference in our main README because that is the file the Docker Hub picks up.
I have:
=> docker: add README

pdns/recursordist/docs/metrics.rst, pdns/recursordist/rec_metrics.hh
=> rec: x-our-latency is a gauge

pdns/dnsdistdist/Makefile.am
That way it is rebuilt when the generation script is updated.
I have:
=> dnsdist: Add incfiles as a dependency to htmlfiles.h

pdns/dnsdist-tcp.cc
That makes debugging much easier.
I have:
=> dnsdist: Add the query payload size to the verbose log over TCP

Dockerfile-auth, Dockerfile-dnsdist, Dockerfile-recursor, Makefile.docker, dockerdata/dnsdist-resolver.lua, dockerdata/startup.py
This PR contains 3 improvements:
1. It copies less into the build environment, improving caching somewhat
2. It makes dnsdist-resolve not print each second
3. It adds templating to the startup script.
The last item needs docs, but I did not find a readme for the docker images.. so where will we do this?
I have:
=> Several docker image improvements

pdns/pdns_recursor.cc, regression-tests.recursor-dnssec/test_DNS64.py
When the requested qname is a CNAME to a second CNAME, the CNAME loop detection might get incorrectly triggered because the CNAMEs were already present in the vector of result records.
I have:
=> rec: Avoid a CNAME loop detection issue with DNS64 

pdns/lua-recursor4.cc
When the requested qname is a CNAME to a second CNAME, the CNAME loop detection might get incorrectly triggered because the CNAMEs were already present in the vector of result records.
Backport of #9696 to rel/rec-4.3.x.
I have:
=> rec-4.3.x: Avoid a CNAME loop detection issue with DNS64

pdns/recursordist/README.md
=> rec: add a few missing dependencies to README

pdns/webserver.hh
Reported by Coverity as CID 1436394 (auth and rec).
I have:
=> Fix initialization of WebServer::accept_yaml

regression-tests/README.md
=> auth regression docs: more mysql variants

.circleci/config.yml
=> rec-4.2.x: avoid paging in git

.circleci/config.yml
=> rec-4.3.x: avoid paging in git

.circleci/config.yml
=> auth-4.3.x: avoid paging in git

pdns/fstrm_logger.cc
It's long overdue since I was wanting to do it for more than a year. Nothing fancy,  but I was triggered by CodeQL saying: this function is too large and has too little comments.
I have:
=> Long overdue table driven option setting for libfstrm

pdns/Makefile.am, pdns/dnsdist-cache.cc, pdns/dnsdistdist/Makefile.am
=> dnsdist: Add the response code in the packet cache dump

pdns/pdnsutil.cc
* don't warn about occlusion of records with the same name as the DNAME record
* do warn about occlusion when the DNAME is at the apex
I have:
=> auth: pdnsutil check-zone: DNAME fixes

Dockerfile-auth, dockerdata/startup.py
This strips the auth modules as well, saving a few mb's in the image.
It also dumps the rendered templates to stdout, for easier debugging of startup issues.
I have:
=> Two new docker improvements

pdns/test-ueberbackend_cc.cc
=> auth: Kill warnings in test code on OpenBSD/clang

docs/changelog/4.4.rst, docs/secpoll.zone
=> auth: changelog&secpoll for auth-4.4.0-beta1

.github/workflows/codeql-analysis.yml, .github/workflows/fuzz.yml, .github/workflows/spelling.yml
https://github.com/actions/virtual-environments/issues/1816
I have:
=> github actions: pin ubuntu 20.04 instead of -latest

build-scripts/docker/generate-repo-files.sh
=> generate-repo-files: add raspbian support

pdns/dnsname.hh, pdns/packethandler.cc
=> auth-4.4.x: Fix the DNSName move assignment operator

pdns/dnsdistdist/docs/advanced/out-of-order.rst
=> dnsdist: Fix a typo (missing backquote) in the out-of-order docs

pdns/dnsrecords.cc
Tested on amd64 and s390x
I have:
=> APL records: fix endianness problem. Closes #9763

docs/settings.rst, docs/upgrading.rst
=> auth: document upgrade-unknown-types API interaction

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.3.rst, pdns/recursordist/docs/changelog/4.4.rst
=> rec: Prep for rec 4.3.6 and 4.4.1

pdns/dnsdist-tcp.cc, pdns/dnsdistdist/dnsdist-tcp-upstream.hh
=> dnsdist: Clean up unused fields in IncomingTCPConnectionState

pdns/dnsdistdist/dnsdist-tcp-downstream.hh
=> dnsdist: Initialize d_cleartextDH to make Coverity happy

pdns/pdnsutil.cc
=> pdnsutil add-record: notice when backend does not support replaceRRSet. Fixes #9730

pdns/dnsrecords.cc
=> auth-4.4.x: APL records: fix endianness problem.

pdns/test-rcpgenerator_cc.cc
This was not tested. This test ensures we don't accidentally break it in the future
I have:
=> Test IPv4-mapped-IPv6 in the RecordTextReader

pdns/dnsrecords.cc
=> rec-4.4.x: APL records: fix endianness problem.

pdns/packethandler.cc, pdns/slavecommunicator.cc, pdns/tcpreceiver.cc, pdns/tcpreceiver.hh
=> auth-4.4.x: add remote to default axfr logging

pdns/validate.cc
=> rec: Actually discard invalid RRSIGs with too high labels count

pdns/Makefile.am
=> auth api-swagger.json: do not depend on .venv target. Fixes #9792

modules/geoipbackend/geoipbackend.cc
=> auth geoipbackend: make local function static

modules/geoipbackend/geoipbackend.cc
=> auth-4.4.x: geoipbackend: make local function static

pdns/Makefile.am
=> auth 4.4.x api-swagger.json: do not depend on .venv target

.github/workflows/builder.yml
This includes running `make check`.
I have:
=> gh actions: build centos6 packages

modules/geoipbackend/geoipbackend.cc
=> auth-4.4.x: geoip: set netmask on all string formatting types

builder-support/dockerfiles/CentOS-SCLo-scl-rh.repo, builder-support/dockerfiles/Centos-Base-Vault.repo, builder-support/dockerfiles/Dockerfile.target.centos-6
This should tide us over until we need more (i.e. when EPEL mirrors also go away).
I have:
=> el6 builds: use vault.centos.org

docs/changelog/4.4.rst, docs/secpoll.zone
=> auth-4.4.0-rc1: docs and secpoll

.circleci/config.yml
With the goal of making Travis obsolete.
I have:
=> auth: extend CircleCI coverage

build-scripts/docker/generate-repo-files.sh, builder-support/dockerfiles/Dockerfile.target.centos-8
=> el8: PowerTools is now powertools

build-scripts/docker/generate-repo-files.sh, builder-support/dockerfiles/Dockerfile.target.centos-8
=> rec-4.4.x: el8: PowerTools is now powertools

build-scripts/docker/generate-repo-files.sh, builder-support/dockerfiles/Dockerfile.target.centos-8
=> auth-4.4.x: el8: PowerTools is now powertools

pdns/recursor_cache.cc, pdns/recursordist/test-recursorcache_cc.cc, pdns/recursordist/test-syncres_cc9.cc
=> rec: Backport 9817 to rec 4.4.x: Keep a cached, valid entry over a fresher Bogus one

pdns/Makefile.am, pdns/speedtest.cc, pdns/uuid-utils.cc, pdns/uuid-utils.hh
=> rec: Backport 9832 to rec 4.4.x: UUID: Use the non-cryptographic variant of the boost::uuid

pdns/lua-recursor4.cc, pdns/rec_channel_rec.cc, pdns/recursordist/docs/lua-scripting/dq.rst, pdns/recursordist/docs/metrics.rst, regression-tests.recursor-dnssec/test_Lua.py
Also add a regression test so we don't break the compatibility layer later.
I have:
=> rec: Add a compatibility layer for 'Bogus', document changes and the new metrics

pdns/dnsdist.cc
It used to be a cheap object to copy but it now hold two strings.
I have:
=> dnsdist: Don't copy the policy for every query

pdns/pdns_recursor.cc
=> More stack when asan is used

pdns/incfiles, pdns/ws-auth.cc
Backported from #9840 
I have:
=> auth: Backport 9840 to auth 4.4.x: Stop using incbin and use od & sed to generate constant string data.

modules/bindbackend/bindbackend2.cc
=> auth bind: call DynListener static functions correctly

pdns/dnsdist-web.cc, pdns/dnsdistdist/incfiles, pdns/incfiles, pdns/recursordist/incfiles, pdns/ws-auth.cc, pdns/ws-recursor.cc
=> Stop using incbin and use od & sed to generate constant string data

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.4.rst
I have:
https://builder.powerdns.com/#/builders/97/builds/1577
https://builder.powerdns.com/#/builders/114/builds/902 (arm)
https://blog.powerdns.com/?p=3268&preview=true
=> rec: Prep for rec 4.4.2 release

pdns/dnsdist-lua-bindings.cc, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Add a Lua binding for the number of queries dropped by a server

modules/bindbackend/bindbackend2.cc
=> auth-4.4.x bind: call DynListener static functions correctly

pdns/tcpreceiver.cc, regression-tests/backends/gsqlite3-master, regression-tests/backends/gsqlite3-slave
=> auth-4.4.x: fix direct-dnskey in AXFR-out

pdns/dnsdistdist/docs/advanced/acl.rst, pdns/dnsdistdist/docs/rules-actions.rst
=> dnsdist: Fix typos in the documentation

pdns/rec_channel_rec.cc, pdns/test-dnsname_cc.cc
=> rec: Get rid of warnings when compiling with Boost 1.74

m4/boost.m4
Fixes #9871 
Also upstreamed.
I have:
=> More toolsets in boost m4 code

Dockerfile-auth, dockerdata/startup.py
=> auth-4.4.x: two docker improvements

pdns/dnslabeltext.rl, pdns/dnswriter.cc, pdns/misc.hh, pdns/rcpgenerator.cc, pdns/rcpgenerator.hh, pdns/test-dnsrecords_cc.cc, pdns/test-rcpgenerator_cc.cc
=> auth-4.4: SVCB: Correctly parse and print unknown params

docs/upgrading.rst
=> auth docs: unconfuse upgrade text about unknown types

pdns/stubresolver.cc
Add a prefix to the log lines of the stub-resolver. Also add some extra info on _what_ was queried.
I have:
=> stub: improve logging

docs/appendices/EOL.rst, docs/changelog/4.4.rst, docs/secpoll.zone
=> changelog+secpoll for auth-4.4.0

.github/workflows/builder.yml, builder-support/dockerfiles/CentOS-SCLo-scl-rh.repo, builder-support/dockerfiles/Centos-Base-Vault.repo, builder-support/dockerfiles/Dockerfile.target.centos-6
Backport of #9815, #9881, #9779
I have:
=> auth-4.3.x: el6 build improvements

.github/workflows/builder.yml, builder-support/dockerfiles/CentOS-SCLo-scl-rh.repo, builder-support/dockerfiles/Centos-Base-Vault.repo, builder-support/dockerfiles/Dockerfile.rpmbuild, builder-support/dockerfiles/Dockerfile.target.amazon-2, builder-support/dockerfiles/Dockerfile.target.centos-6, builder-support/dockerfiles/Dockerfile.target.centos-7, builder-support/dockerfiles/Dockerfile.target.centos-8
Backport of #9815, #9881, #9779, #8807
I have:
=> rec-4.3.x: el6 build improvements

docs/settings.rst
Improve documentation for the max-signature-cache-entries configuration setting.
I have:
=> Document the behavior of the max-signature-cache-entries setting.

pdns/lua-record.cc
Fix missing #include for gcc-11
=> Fix missing #include for gcc-11

contrib/ProtobufLogger.py
=> ProtobufLogger: Better handling of short-reads, errors

pdns/Makefile.am
I've run an outdated testrunner too many times, so build i(if enabled) from the main target.
I have:
=> auth: If unit tests are enabled, build testrunner from the main target

pdns/pdnsutil.cc
Because otherwise your edits are gone!
I have:
=> pdnsutil edit-zone: do not exit on ZoneParser exception

docs/settings.rst
=> auth docs: correct local-address-nonexist-fail default

pdns/recursordist/test-syncres_cc4.cc
To avoid signature not yet valid issues on slow machines.
I have:
=> rec: Force the sig generation for test_dnssec_bogus_bad_sig to use the right time

pdns/backends/gsql/gsqlbackend.hh, pdns/dbdnsseckeeper.cc, pdns/dnsbackend.hh, pdns/dnsseckeeper.hh, pdns/ueberbackend.cc, pdns/ueberbackend.hh
Do not merge until the 4.4.x branch has been created.
I have:
=> auth: detect possible metadata cache pollution

pdns/pdnsutil.cc
=> auth-4.4.x: pdnsutil edit-zone: do not exit on ZoneParser exception

docs/conf.py, docs/guides/basic-database.rst, docs/installation.rst
This avoids one moving part, simplifying the setup.
I have:
=> auth: change installation example from MySQL to SQLite

docs/backends/generic-mysql.rst
Lead users who see errors about READ COMMITTED or READ UNCOMMITTED / BINLOG_FORMAT = STATEMENT
to this section of the docs.
I have:
=> Add SEO for BINLOG_FORMAT = STATEMENT error

pdns/dnsdist-lua-actions.cc, pdns/ssqlite3.cc
CodeQL is right AFAIKS.
I have:
=> CodeQL: two instances of expressions being always true

.github/workflows/codeql-analysis.yml
Before: 17+10+10 minutes building 3 products, plus 37 minutes analysis, is 74 minutes of wall clock time.
After: 17/10/10 plus 16/12/16 is 33/22/26 minutes, or less than half in wall clock time, at a cost of roughly 7 more cpu minutes.
I have:
=> codeQL: switch to merge commit analysis; split product builds

m4/boost.m4
Also upstreamed: https://github.com/tsuna/boost.m4/pull/122
I have:
=> Fix warnings generated by boost config test.

pdns/dnsrecords.cc
=> actually report IPSECKEY type - broken since #8638

.github/ISSUE_TEMPLATE/bug_report.md, docs/index.rst, pdns/recursordist/docs/index.rst
=> support policy applies to GitHub too

build-scripts/docker/generate-repo-files.sh, builder-support/dockerfiles/Dockerfile.target.centos-8
Backport of #9831, fixes broken build spotted in https://builder.powerdns.com/#/builders/98/builds/1608
I have:
=> dnsdist 1.5.x el8: PowerTools is now powertools

modules/gsqlite3backend/gsqlite3backend.cc
=> auth gsqlite3: handle escaping correctly for API search. Fixes #8791

builder-support/dockerfiles/Dockerfile.target.centos-8
=> auth-4.2.x el8: PowerTools is now powertools

builder-support/dockerfiles/Dockerfile.target.centos-8
=> auth-4.3.x el8: PowerTools is now powertools

modules/geoipbackend/geoipbackend.cc, modules/lmdbbackend/lmdbbackend.cc, modules/remotebackend/remotebackend.cc
=> auth-4.4.x: backport some asan/ubsan fixes

modules/lmdbbackend/lmdbbackend.cc
Related to, but possibly not fixing, #9903.
I have:
=> auth lmdb: serialise LMDBBackend construction

builder-support/dockerfiles/Dockerfile.target.centos-8
=> rec-4.2.x el8: PowerTools is now powertools

builder-support/dockerfiles/Dockerfile.target.centos-8
=> rec-4.3.x el8: PowerTools is now powertools

ext/lmdb-safe/lmdb-safe.cc
=> auth-4.4.x: Do a mdb_readers_check to clean up stale readers on database load

pdns/recursordist/docs/lua-config/rpz.rst, pdns/recursordist/docs/lua-scripting/dq.rst, pdns/recursordist/docs/lua-scripting/hooks.rst, pdns/recursordist/docs/upgrade.rst
Also make the 4.4.0 changes a bit more prominent in the docs and fix a few dead links.
Fixes #9916 
I have:
=> Add a note about RPZ changes in the upgrade guide.

modules/lmdbbackend/lmdbbackend.cc
=> auth-4.4.x lmdb: serialise LMDBBackend construction

ext/yahttp/yahttp/cookie.hpp, ext/yahttp/yahttp/reqresp.hpp, ext/yahttp/yahttp/utility.hpp
=> Reduce diff to upstream yahttp, fixing a few CodeQL reports

pdns/packethandler.cc, regression-tests/tests/direct-nsec3param/command, regression-tests/tests/direct-nsec3param/expected_result, regression-tests/tests/direct-nsec3param/expected_result.dnssec, regression-tests/tests/direct-nsec3param/expected_result.narrow, regression-tests/tests/direct-nsec3param/expected_result.nsec3
=> auth: Serve NSEC3PARAM when asked without DO

.github/workflows/spelling.yml
Because we've now made various Checks mandatory for PR merging.
I have:
=> spelling workflow: run always (but still only check docs)

pdns/dnsdist-console.cc, pdns/dnsdist-lua-actions.cc, pdns/dnsdistdist/docs/rules-actions.rst, regression-tests.dnsdist/test_Caching.py
=> dnsdist: Add SkipCacheResponseAction

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.5.rst, pdns/recursordist/docs/changelog/index.rst, pdns/recursordist/docs/upgrade.rst
To make the changelist a bit shorter, I skipped doc related stuff, build related stuff and PRs that do not cause an  change in behaviour visible for users.
https://blog.powerdns.com/?p=3285&preview=true
https://builder.powerdns.com/#/builders/97/builds/1623
https://builder.powerdns.com/#/builders/114/builds/934
tag target is f0abe7ad8e6695212168119eee9186c1fd27cdf7
I have:
=> rec: Prep for rec-4.5.0-alpha1

docs/backends/lmdb.rst, docs/upgrading.rst
Document the LMDB backend schema versions
I have:
=> Document LMDB backend schema versions

build-scripts/docker/generate-repo-files.sh
Tested with rec-4.5.0-alpha1 and works.
Do some older recs like `rec-41` and maybe `rec-42` need to be removed?
=> Add rec-45 to repo test script.

pdns/recursordist/docs/appendices/EOL.rst, pdns/recursordist/docs/index.rst, pdns/recursordist/docs/settings.rst
=> rec: Mention += in the docs plus an example

pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc
Check that we do not look at queries older than our sliding window, but also that we correctly trigger a block with a huge peak of queries not followed by any more queries.
I have:
=> dnsdist: More tests for the dynamic block's sliding window

docs/upgrading.rst
=> auth upgrade notes: IPSECKEY did not make it into 4.4

pdns/lua-record.cc
=> auth-4.4.x: Fix missing #include for gcc-11

modules/lmdbbackend/lmdbbackend.cc
Backport of second half of #9885.
I have:
=> auth-4.4.x lmdb: do not reuse backend that has seen corrupted data

regression-tests.dnsdist/dnsdisttests.py, regression-tests.dnsdist/test_OCSP.py, regression-tests.dnsdist/test_TLS.py
=> dnsdist: Add regression tests for certificates and OCSP reloading

pdns/dnsdist-lua.cc, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Handle syslog facility as string, document the numerical one

pdns/dnsdist-snmp.cc, pdns/dnsdist-web.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/DNSDIST-MIB.txt, pdns/dnsdistdist/docs/statistics.rst, regression-tests.dnsdist/test_API.py
=> dnsdist: Add a counter for queries truncated because of a rule

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-tcp.cc, pdns/dnsdist.cc, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/doh.cc, regression-tests.dnsdist/test_Advanced.py, regression-tests.dnsdist/test_Basics.py
=> dnsdist: Send a NotImp answer on empty (qdcount=0) queries

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-snmp.cc, pdns/dnsdist-snmp.hh, pdns/dnsdistdist/docs/advanced/axfr.rst, pdns/dnsdistdist/docs/changelog.rst, pdns/dnsdistdist/docs/reference/snmp.rst, pdns/snmp-agent.cc, pdns/snmp-agent.hh, regression-tests.dnsdist/snmpd.conf, regression-tests.dnsdist/test_DynBlocks.py
=> dnsdist: Replace offensive terms in our code and documentation

pdns/dnsdist.cc, regression-tests.dnsdist/test_Routing.py
=> dnsdist: Fix EDNS in ServFail generated when no server is available

pdns/recursordist/docs/dnssec.rst, pdns/recursordist/docs/settings.rst
and reformat two item lists.
I have:
=> rec: Document CD bit better, reference detailed DNSSEC docs from settings

.github/actions/spell-check/expect.txt, pdns/rec-snmp.cc, pdns/recursordist/RECURSOR-MIB.txt, pdns/recursordist/docs/metrics.rst
=> rec: Document taskqueue metrics and add them to SNMP MIB

pdns/test-luawrapper.cc
I forgot to push this before merge.
I have:
=> luawrapper test: improve comment

.github/actions/spell-check/expect.txt, docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst, pdns/dnsdistdist/docs/upgrade_guide.rst
TODO:
- <strike>merge https://github.com/PowerDNS/pdns/pull/9997</strike>
- <strike>cppcheck</strike>
- <strike>clang's static analyser</strike>
- <strike>Local build with clang++ and g++</strike>
- <strike>Local run of the unit and regression tests with ASAN and UBSAN enabled</strike>
- Blog post at https://powerdnsblog.wordpress.com/?p=3299&preview=true
- <strike>Edit the release date</strike>
I have:
=> dnsdist: ChangeLog and secpoll update for 1.6.0-alpha1

pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist docs: formatting + spelling in registerWebHandler explanation

build-scripts/docker/generate-repo-files.sh
Feel free to commit if approved.
=> Add dnsdist 1.6.x to repo script.

pdns/dnsdist-web.cc
=> dnsdist: Remove forgotten debug line in the web server

Dockerfile-auth
=> auth docker: find unixodbc on non-x86_64 platforms

Dockerfile-auth, Dockerfile-dnsdist, Dockerfile-recursor, dockerdata/startup.py
Ensures the version number for _RELEASES_ (`DOCKER_FAKE_RELEASE=YES`) is correct inside the image.
This also uses unbuffered output for python as discussed in https://github.com/PowerDNS/pdns/issues/9931#issuecomment-771204077
I have:
=> dockerfiles: Ensure version number is correct for releases

.github/workflows/builder.yml, builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
=> builder: support oraclelinux-8; verify build in GH Actions on push&PR

.github/workflows/docker.yml
To make sure a PR does not break our Docker images.
I have:
=> gh actions: build Docker images

pdns/responsestats-auth.cc, pdns/responsestats.hh, pdns/tcpreceiver.cc, pdns/tcpreceiver.hh
=> auth-4.4.x: fix tcp answer counters

pdns/dnspacket.cc, pdns/responsestats.cc, pdns/signingpipe.cc, pdns/stubresolver.cc, pdns/ws-auth.cc
=> rename a few `d_*` locals

pdns/pdnsutil.cc
This PR is the initial work for fixing #2214, initially returning errors in check-zone for the offending values.
I have:
=> Make check-zone also check whether there are duplicate key value pair metadatas for the zone

.github/actions/spell-check/expect.txt, docs/changelog/4.4.rst, docs/secpoll.zone
plus a typo fix in the auth 4.4.0 docs
I have:
=> changelog&secpoll for auth-4.4.1

pdns/pdns_recursor.cc, pdns/recursordist/docs/settings.rst, pdns/recursordist/docs/upgrade.rst
=> rec: Change spoof-nearmiss-max default to 1.

docs/lua-records/index.rst
=> docs: notes on LUA record splitting

docs/common/api/server.rst
=> docs: Avoid some confusion about server objects

pdns/Makefile.am, pdns/speedtest.cc
=> speedtest: add NSEC3 hashing test

pdns/pdnsutil.cc
Fixes #10085
This only warns, even though having this is an RFC violation. Moderns resolvers and clients should be able to handle this situation just fine.
I have:
=> pdnsutil: Warn on CNAME targets for NS, MX and SRV

pdns/recursordist/docs/settings.rst
=> rec: Document trace=fail better and warn against its shortcomings.

regression-tests/recursor-test
=> rec: Enable DNSSEC validation in bulk tests

pdns/dnsmessage.proto, pdns/pdns_recursor.cc, pdns/protozero.hh, pdns/recursordist/rec-protozero.hh, regression-tests.recursor-dnssec/test_Protobuf.py
Followup up #9654, git does not let me push to the original branch: https://github.com/threatstop/pdns master 
Fixes  #9653
Will also add regression test.
I have:
=> rec: followup to #9654: Add Policy Kind / RPZ action to Protobuf messages

pdns/dns.hh, pdns/lua-base4.cc, pdns/pdns_recursor.cc, pdns/recursordist/docs/lua-scripting/hooks.rst
Fixes #10080 (which contains a more detailed explanation)
Please review the docs changes extra carefully, I tried to make them more clear, but I don't know if I succeeded.
Maybe the removal of `PolicyDecision` and the corresponding Lua is a bit too radical and should be postponed.
I have:
=> rec: Handle policy (if needed) after postresolve and document the hooks better

pdns/syncres.cc
Only log when we found something
I have:
=> rec: Be less verbose telling we are looking up CNAMEs or DNAMEs

pdns/sdig.cc
=> sdig: write 2-byte header and request in one write call.

pdns/dnsdist-tcp.cc
We don't care about performance in that place but it prevents a warning.
I have:
=> dnsdist: Prevent a copy in DownstreamConnectionsManager::clear()

pdns/dnsdist-tcp.cc, pdns/dnsdistdist/dnsdist-tcp-downstream.cc
=> dnsdist: Do not update the TCP error counters on idle states

pdns/dnsdistdist/test-dnsdisttcp_cc.cc, pdns/recursordist/test-aggressive_nsec_cc.cc
=> Fix a few unused lambda captures and signed/unsigned warnings

docs/backends/lmdb.rst
=> docs: improve rendering of lmdb page

configure.ac, m4/ax_check_sign.m4, m4/ax_compile_check_sizeof.m4, m4/pdns_check_time_t.m4, pdns/dnsdistdist/configure.ac, pdns/dnsdistdist/m4/ax_check_sign.m4, pdns/dnsdistdist/m4/ax_compile_check_sizeof.m4, pdns/dnsdistdist/m4/pdns_check_time_t.m4, pdns/recursordist/configure.ac, pdns/recursordist/m4/ax_check_sign.m4, pdns/recursordist/m4/ax_compile_check_sizeof.m4, pdns/recursordist/m4/pdns_check_time_t.m4
We can do this once we get rid of the raspbian builds. Code suggested by @pieterlexis.
I have:
=> Check sizeof(time_t) to be at least 8

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Update the ChangeLog and secpoll zone for 1.6.0-alpha2

pdns/dnsmessage.proto
This imports a change from upstream (https://github.com/PowerDNS/dnsmessage), reducing the difference between the two to just the license text.
After this is approved&merged, I'll PR the license change upstream.
I have:
=> update dnsmessage.proto from upstream

.github/actions/spell-check/expect.txt, docs/backends/ldap.rst
Because that's what the code expects.
I have:
=> auth ldap docs: s/authmethod/bindmethod/

pdns/minicurl.cc, pdns/minicurl.hh, pdns/sdig.cc
While at it, honour timeout parameter as well for DoT.
I have:
=> sdig: implement TCP Fast Open for DoH

pdns/syncres.cc
While there, rename a var to be different from the method name.
I have:
=> rec: Only put a failing NS in the map if we actually went out and that produced no results

pdns/pdns_recursor.cc, pdns/recursordist/docs/settings.rst
=> docs: Fix formatting typo in Recursor settings

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.5.rst, pdns/recursordist/docs/upgrade.rst
Including a few upgrade notes.
https://builder.powerdns.com/#/builders/97/builds/1704
blog post:
https://blog.powerdns.com/?p=3317&preview=true
I have:
=> rec: Prep for rec-4.5.0-alpha3

docs/changelog/4.3.rst, docs/secpoll.zone, docs/upgrading.rst
=> auth 4.3.2: docs&secpoll

m4/systemd.m4
This issue was introduced in 7bbaae110abb53f43d0bf60c81efe3bb8630a925
I have:
=> Fix configure issue with systemd runtime dir detection

docs/settings.rst
=> Improve description of dname-processing

.github/workflows/secpoll.yml, pdns/pdnsutil.cc
=> check secpoll syntax

pdns/dnsrecords.hh
=> CSYNCRecordContent: init member variables

modules/lmdbbackend/lmdbbackend.cc, modules/lmdbbackend/lmdbbackend.hh, pdns/dnsparser.hh, regression-tests.api/test_Zones.py
Request to be accepted -->
I have:
=> auth: implement disabled in LMDB backend

pdns/recursordist/test-syncres_cc1.cc, pdns/reczones.cc, pdns/syncres.cc
=> rec: Don't pick up random root NS records from AUTHORITY sections

pdns/dnsdistdist/docs/advanced/tuning.rst, pdns/dnsdistdist/docs/guides/tls-sessions-management.rst, pdns/dnsdistdist/docs/reference/tuning.rst
=> dnsdist: Fix a few typos in the docs, document that setTCPUseSinglePipe should not be used anymore

pdns/dnsdist-lua-bindings.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-web.cc, pdns/dnsdist.cc, pdns/dnsdistdist/Makefile.am, pdns/dnsdistdist/dnsdist-backend.cc, pdns/dnsname.hh, regression-tests.dnsdist/test_Routing.py
This PR backports fixes from #9583 #9729 #9749 #9900 #10012 #10095
I have:
=> dnsdist-1.5.x: Backports fixes

.circleci/config.yml
=> circleci: use upstream docker images instead of the circleci forks

modules/lmdbbackend/lmdbbackend.cc
=> auth: fix coverity CID 1450843

pdns/recursordist/test-syncres_cc5.cc, pdns/syncres.cc, pdns/syncres.hh
=> rec: Backport 9970 to 4.4.x: test that we correctly cap the answer's TTL in expanded wildcard cases

docs/guides/basic-database.rst
The example for sqlite uses example.org instead of example.com
I have:
=> docs: Changed to correct zone in sqlite backend example

docs/upgrading.rst
=> auth upgrade docs: note removal of do-ipv6-additional-processing

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.3.rst, pdns/recursordist/docs/getting-started.rst
Plus a bonus dangling reference in docs fix.
https://builder.powerdns.com/#/builders/97/builds/1725
https://powerdnsblog.wordpress.com/?p=3360&preview=true
I have:
=> rec: changelog and secpoll for rec 4.3.7

.github/actions/spell-check/expect.txt, docs/manpages/pdnsutil.1.rst, docs/manpages/sdig.1.rst, pdns/dnsdistdist/docs/rules-actions.rst, pdns/misc.cc, pdns/misc.hh, pdns/pdnsutil.cc, pdns/sdig.cc
Compare the output below to the examples in https://dnsdist.org/rules-actions.html?highlight=spoofraw#SpoofRawAction
```
$ sdig 127.0.0.1 5300 d1.example.com TXT dumpluaraw
Reply to question for qname='d1.example.com.', qtype=TXT
Rcode: 0 (No Error), RD: 0, QR: 1, TC: 0, AA: 1, opcode: 0
0	d1.example.com.	IN	TXT	"\003aaa\004bbbb"
0	d1.example.com.	IN	TXT	"\003ccc"
$ sdig 127.0.0.1 5300 d2.example.com SRV dumpluaraw
Reply to question for qname='d2.example.com.', qtype=SRV
Rcode: 0 (No Error), RD: 0, QR: 1, TC: 0, AA: 1, opcode: 0
0	d2.example.com.	IN	SRV	"\000\000\000\000\255\255\003srv\008powerdns\003com\000"
$ sdig 127.0.0.1 5300 d3.example.com PTR dumpluaraw
Reply to question for qname='d3.example.com.', qtype=PTR
Rcode: 0 (No Error), RD: 0, QR: 1, TC: 0, AA: 1, opcode: 0
0 …
```
=> dig, pdnsutil: add dnsdist spoofAction string generators

pdns/recursordist/docs/metrics.rst, pdns/recursordist/docs/settings.rst
=> rec: A few updates and corrections of docs related to metrics and threads.

pdns/dnsdist-lua.cc, pdns/dnsdistdist/docs/reference/config.rst, pdns/libssl.cc, pdns/libssl.hh
=> dnsdist: Disable TLS renegotiation by default

.github/actions/spell-check/expect.txt, docs/secpoll.zone, pdns/recursordist/docs/appendices/EOL.rst, pdns/recursordist/docs/changelog/4.5.rst, pdns/recursordist/docs/upgrade.rst
https://builder.powerdns.com/#/builders/97/builds/1741
https://wordpress.com/post/blog.powerdns.com/3367
I have:
=> Rec: prep for 4.5.0 beta1

pdns/validate.cc
=> rec: Backport 9856 to rec 4.4.x: Use a short-lived NSEC3 hashes cache for denial validation

pdns/ws-auth.cc, regression-tests.api/test_Zones.py
Does what it says on the tin.
I have:
=> API: return RRType when finding a comment

pdns/recursor_cache.cc
=> rec: Clear d_from if we don't know where the update came from

pdns/recursor_cache.cc, pdns/recursor_cache.hh, pdns/recursordist/test-recursorcache_cc.cc, pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc2.cc, pdns/recursordist/test-syncres_cc7.cc, pdns/reczones.cc, pdns/syncres.cc, pdns/syncres.hh
Backport of #9883 
This is a largish backport, so some extra careful review appreciated!
I have:
=> rec: Backport 9883 to rec 4.4.x: Lookup DS entries before CNAME entries

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Add ChangeLog and secpoll update for 1.6.0-alpha3

Dockerfile-recursor, dockerdata/startup.py
=> Backport 10042 to rec 4.4.x: dockerfiles: Ensure version number is correct for releases

pdns/nod.cc, pdns/nod.hh, pdns/recursordist/stable-bloom.hh
=> rec: Backport 10238 to rec 4.4.x: More fail-safe handling of NOD files

pdns/nod.cc, pdns/nod.hh, pdns/recursordist/stable-bloom.hh
=> Backport 10238 to rec 4.5.x: More fail-safe handling of NOD files

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.4.rst
https://builder.powerdns.com/#/builders/97/builds/1755
https://wordpress.com/post/blog.powerdns.com/3389
I have:
=> rec: Prep for rec-4.4.3

pdns/recursordist/test-syncres_cc6.cc, pdns/syncres.cc
=> rec: Better handling of stranded DNSKeys

.clang-format, modules/bindbackend/bindbackend2.hh, modules/geoipbackend/geoipbackend.cc, modules/geoipbackend/geoipinterface-dat.cc, modules/geoipbackend/geoipinterface-mmdb.cc, modules/geoipbackend/geoipinterface.hh, modules/gmysqlbackend/gmysqlbackend.cc, modules/gmysqlbackend/smysql.cc, modules/gmysqlbackend/smysql.hh, modules/godbcbackend/sodbc.cc, modules/gpgsqlbackend/gpgsqlbackend.cc, modules/gpgsqlbackend/spgsql.cc, modules/gpgsqlbackend/spgsql.hh, modules/ldapbackend/ldapauthenticator.cc, modules/lmdbbackend/lmdbbackend.cc, modules/lmdbbackend/lmdbbackend.hh, pdns/recursordist/aggressive_nsec.hh, pdns/recursordist/negcache.hh, pdns/recursordist/taskqueue.hh, pdns/recursordist/test-filterpo_cc.cc, pdns/recursordist/test-mtasker.cc, pdns/recursordist/test-syncres_cc3.cc
=> AlignAfterOpenBracket: Align

docs/backends/generic-sql.rst, docs/dnsupdate.rst, docs/domainmetadata.rst, docs/modes-of-operation.rst
=> docs: Remove raw SQL statements where possible

docs/settings.rst, pdns/common_startup.cc, pdns/nameserver.cc, pdns/tcpreceiver.cc
=> auth: remove local-ipv6, query-local-address6 (redo of #9552). Closes #5368

builder-support/gen-version
=> Fix the package version _on_ prerelease tags

pdns/dbdnsseckeeper.cc
=> Include unordered_map

pdns/dnsdist.cc, pdns/iputils.cc, pdns/iputils.hh, pdns/nameserver.cc, pdns/pdns_recursor.cc
Treat v6 the same as v4 for PMTU discovery.
I have:
=> Also disable PMTU for v6

pdns/test-misc_hh.cc
=> auth: Fix a few warnings as seen on OpenBSD/clang

pdns/recursordist/docs/indexTOC.rst, pdns/recursordist/docs/lua-config/index.rst, pdns/recursordist/docs/lua-scripting/index.rst, pdns/recursordist/docs/running.rst
This is a better order IMO, also make it more clear what Lua config actually is used for in the TOC. For example, the reader scanning the TOC might not know that RPZ is configured via Lua, so if he's looking for RPZ config docs, he's lost.
I have:
=> rec: Reorder subjects and change titles, to make TOC more logical

pdns/recursordist/test-syncres_cc6.cc, pdns/syncres.cc
=> rec: Backport 10223 to rec 4.5.x: Better handling of stranded DNSKeys

pdns/dnsdist.cc, pdns/iputils.cc, pdns/iputils.hh, pdns/nameserver.cc, pdns/pdns_recursor.cc
(cherry picked from commit db63b4b63158d95399fa9109b9802b195df515f8)
Backport of #10264.
I have:
=> rec: backport 10264 to rec-4.5.x: Also disable PMTU for v6

pdns/lwres.cc, regression-tests.recursor-dnssec/test_RecDnstap.py
=> rec: Backport 10268 to rec-4.5.x: Log local IP in dnstap messages

pdns/qtype.cc, pdns/test-dnsrecords_cc.cc
=> qtypes: check type registration; add CSYNC

pdns/dnsdistdist/docs/guides/serverpools.rst, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist docs: remove addPool; clarify that getPool creates pools

modules/remotebackend/remotebackend.cc, pdns/dnsdistdist/dnsdist-secpoll.cc, pdns/pdns_recursor.cc, pdns/qtype.cc, pdns/qtype.hh, pdns/sdig.cc, pdns/syncres.cc, pdns/syncres.hh
And start using it in a few places.
Fixes #7389
I have:
=> Make QClass a class, including toString() method

builder-support/gen-version
Closes #9842
(cherry picked from commit 121a191d5ecd24818053a39013608e424a36142a)
Baxkport of #10252 
I have:
=> rec: backport 10252 to rex 4.5.x: Fix the package version _on_ prerelease tags

pdns/recursordist/test-syncres_cc2.cc, pdns/syncres.cc
This fixes #10263 here, but needs thorough reviewing and testing.
I have:
=> rec: First check the cache for NS name to address contents for both v4 and v6

pdns/arguments.cc, pdns/ixfr.cc, pdns/ixfr.hh, pdns/pdns_recursor.cc, pdns/rec-lua-conf.cc, pdns/rec-lua-conf.hh, pdns/rec-snmp.cc, pdns/rec-snmp.hh, pdns/rec_channel.hh, pdns/rec_channel_rec.cc, pdns/rpzloader.cc, pdns/rpzloader.hh, pdns/syncres.cc, pdns/syncres.hh, pdns/ws-recursor.cc
ATM table s used by both rec and auth, that seems a bit wrong, but otoh simplifies matters...
I have:
=> rec: Stop using potentially offensive names internally and warn about deprecated settings.

.github/workflows/builder.yml, builder-support/dockerfiles/Dockerfile.target.centos-8, builder-support/dockerfiles/Dockerfile.target.centos-8-stream
=> builder, gh actions: add centos-8-stream build

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.5.rst
https://builder.powerdns.com/#/builders/97/builds/1775
https://blog.powerdns.com/?p=3413&preview=true
I have:
=> rec: Prep for rec-4.5.0-beta2

docs/changelog/pre-4.0.rst, pdns/pdns_recursor.cc, pdns/rec_channel_rec.cc, pdns/recursordist/RECURSOR-MIB.txt, pdns/recursordist/docs/manpages/pdns_recursor.1.rst, pdns/recursordist/docs/metrics.rst, pdns/recursordist/docs/settings.rst, pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc3.cc, pdns/syncres.cc, pdns/syncres.hh, pdns/ws-recursor.cc, regression-tests.recursor/TODO
Remove `delegation-only` from the recursor. Fixes  #7544
I have:
=> rec: remove delegation only (issue #7544)

docs/changelog/pre-4.0.rst
=> Revert previous change to changelog, they should not be changed.

pdns/recursordist/docs/appendices/internals.rst, pdns/recursordist/docs/index.rst
=> Rec: recursor is actually a pretty complex piece of code

pdns/recursordist/docs/appendices/FAQ.rst
=> two more comments from Otto on recursor FAQ entry about bufsizes

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Add ChangeLog and secpoll for 1.6.0-rc1

pdns/validate.cc
=> rec: Backport 10298 to rec 4.5.x: print the covering NSEC

pdns/pdns_recursor.cc
(cherry picked from commit 327851e53faeeee67db857e2152e149edf72753e)
Backport of #10299 
I have:
=> rec: Backport 10299 to rec-4.5.x: update setting for aggressive-nsec-cache-size

pdns/recursordist/test-syncres_cc3.cc, pdns/syncres.cc, pdns/syncres.hh
Fixes #10189, and does not break existing unit tests.
Needs unit test.
I have:
=> rec: Do not put results of DS query for auth or forward domains in negcache.

pdns/recursordist/docs/lua-scripting/features.rst
=> Fix two typos in lua scripting docs

pdns/pdns_recursor.cc, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_ECS.py, regression-tests.recursor-dnssec/test_ProxyProtocol.py
=> rec: Backport 10303 to rec 4.5.x: Use the correct ECS address when proxy-protocol is enabled 

pdns/Makefile.am, pdns/dnsdistdist/Makefile.am, pdns/recursordist/Makefile.am
(cherry picked from commit 311f26839819062ced8697686372b6c6b2210bdf)
Backport of #10329 
I have:
=> rec: Backport of 10329 to rec-4.5.x: boost 1.76 containers: use standard exceptions

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.5.rst
https://builder.powerdns.com/#/builders/97/builds/1802
https://blog.powerdns.com/?p=3428&preview=true
I have:
=> rec: Prep for rec-4.5.0-rc1

pdns/dnsdistdist/test-delaypipe_hh.cc
Use the same type for `done`'s basic type, `n` and `i`.
I have:
=> dnsdist: fix test warnings

m4/boost.m4
=> auto.m4: clang 11.1 is a thing

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Add ChangeLog and secpoll for 1.6.0-rc2

pdns/dnsdistdist/docs/rules-actions.rst
=> dnsdist docs: correct bits for TCAction

docs/manpages/ixfrdist.yml.5.rst
=> docs: fix typo in ixfrdist docs

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Update ChangeLog and secpoll zone for 1.5.2

pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Fix a typo in the ChangeLog header for 1.5.2

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
https://powerdnsblog.wordpress.com/?p=3458&preview=true
I have:
=> dnsdist: Changelog and secpoll update for 1.6.0

builder-support/gen-version
Closes #9842
(cherry picked from commit 121a191d5ecd24818053a39013608e424a36142a)
Backport of #10252 
I have:
=> rec: Backport 10252 to rec-4.4.x: Fix the package version _on_ prerelease tags

pdns/pdns_recursor.cc, regression-tests.recursor-dnssec/test_ECS.py
=> Rec 4.4.x: zero ecs sizecheck

modules/gpgsqlbackend/gpgsqlbackend.cc, pdns/backends/gsql/gsqlbackend.cc, pdns/pdnsutil.cc
=> auth gpgsql: use SELECT .. RETURNING to get inserted row ID

pdns/pdns_recursor.cc, pdns/syncres.cc, pdns/syncres.hh
=> rec: For the NOD lookup case, we don't want QName Minimization.

pdns/pdns_recursor.cc, pdns/syncres.cc, pdns/syncres.hh
=> Rec: backport 10420 to 4.5.x: For the NOD lookup case, we don't want QName Minimization.

pdns/lua-recursor4.cc, pdns/lua-recursor4.hh, pdns/lwres.cc, pdns/lwres.hh, pdns/pdns_recursor.cc, pdns/rec-carbon.cc, pdns/rec_channel_rec.cc, pdns/recursordist/Makefile.am, pdns/recursordist/libssl.cc, pdns/recursordist/libssl.hh, pdns/recursordist/tcpiohandler.hh, pdns/syncres.cc, pdns/syncres.hh, pdns/ws-recursor.cc
This is needed to be able to act as a DoT client, but I first start with regular TCP53.
I have:
=> rec: move to tcpiohandler for outgoing TCP

docs/settings.rst, docs/upgrading.rst, pdns/common_startup.cc, pdns/dbdnsseckeeper.cc, pdns/pdnsutil.cc, pdns/receiver.cc
and some domain -> zone in the settings descriptions and settings.rst
I have:
=> auth: replace domain-metadata-cache-ttl by zone-metadata-cache-ttl

docs/appendices/FAQ.rst
=> auth faq: document a ProtectSystem=full implication

docs/conf.py, pdns/dnsdistdist/docs/conf.py, pdns/recursordist/docs/conf.py
Strictly speaking the year should be the year of the last major edit, but the build year is a good enough approximation.
I have:
=> docs: Determine copyright upper bound year by code

pdns/lock.hh
=> dnsdist-1.6.x: Backport a missing mutex header

pdns/syncres.cc
This makes them easier to read, and also makes it easier to spot which line of code dropped a record.
I have:
=> rec: distinguish the various 'Removing irrelevant record' log lines

pdns/dnsparser.cc, pdns/dnswriter.cc, pdns/rcpgenerator.cc, pdns/svc-records.cc, pdns/svc-records.hh, pdns/test-dnsrecords_cc.cc, pdns/test-dnswriter_cc.cc, pdns/test-rcpgenerator_cc.cc, pdns/test-svc_records_cc.cc, regression-tests.api/test_Zones.py
=> SVCB: rename echconfig to ech and add test vectors from draft

pdns/pdns_recursor.cc, pdns/recursordist/docs/settings.rst, pdns/recursordist/docs/upgrade.rst
Implement the recommended limit. Need to add ref to guideline once it is available in docs.
I have:
=> rec: Change nsec3-max-iterations default to 150

pdns/syncres.cc
Fixes #10415 (at least the most obvious cases).
I have:
=> rec: Remove checks in updateCacheFromRecords that are already done by sanitizeRecords.

pdns/recursordist/docs/lua-scripting/dq.rst, pdns/recursordist/docs/lua-scripting/policyevent.rst
Improving consistency: fixes errors that were fixed in the `qd` section but not here.
I have:
=> rec: Refer to the description in dq.appliedPolicy for PolicyEvent.appliedPolicy

pdns/dnsdistdist/docs/eol.rst, pdns/dnsdistdist/docs/index_TOC.rst
Proposal for a new EOL documentation page for your dnsdist product.
I have:
=>  dnsdist: docs new EOL page

.github/actions/spell-check/expect.txt, docs/changelog/4.5.rst, docs/changelog/index.rst, docs/guides/svcb.rst, docs/manpages/pdns_control.1.rst, docs/secpoll.zone, docs/upgrading.rst
=> changelog and secpoll for auth-4.5.0-alpha1

.circleci/config.yml, regression-tests.auth-py/test_LuaRecords.py, regression-tests.auth-py/test_SVCB.py
=> auth-py tests: unbreak, enable in CircleCI

pdns/ws-recursor.cc
=> rec: Fix a typo in the prometheus "edns-ping-mismatches" metric

docs/appendices/types.rst
Document unknown record type.
I have:
=> docs: Document unknown record type in supported types

docs/upgrading.rst
Documentation update.
There are a few settings that need replacing. This fixes #10465 .
=> Update documentation to reflect changes in default-soa-content.

docs/lua-records/functions.rst, docs/lua-records/reference/netmask.rst, pdns/lua-base4.cc, pdns/lua-record.cc, pdns/recursordist/docs/lua-scripting/netmask.rst, regression-tests.auth-py/authtests.py, regression-tests.auth-py/test_LuaRecords.py
Fixes #9701
Ready for review.
I have:
=> auth LUA: add filterForward function, to limit the scope of createForward[6]

pdns/dnsdist-lua-vars.cc, pdns/dnsdistdist/docs/reference/constants.rst
=> dnsdist: remove dnsdist.* lookup fallback

pdns/recursor_cache.cc, pdns/recursordist/Makefile.am, pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc.hh, pdns/recursordist/test-syncres_cc2.cc
=> rec: Backport of #10426 to rec-4.5.x: When refreshing, do not consider root almost expired

pdns/recursordist/test-syncres_cc9.cc, pdns/syncres.cc
=> rec: Backport 10460 to rec 4.5.x: Don't follow referral from the parent to the child for DS queries

m4/pdns_check_os.m4, pdns/Makefile.am, pdns/dnsdistdist/Makefile.am, pdns/kqueuemplexer.cc, pdns/recursordist/Makefile.am
<strike>Needs more than just compile testing</strike>. DId (basic) testing of auth, rec and dnsdist.
I have:
=> Switch OpenBSD to kqueue mplexer

.github/actions/spell-check/expect.txt, docs/changelog/4.5.rst, docs/secpoll.zone, docs/upgrading.rst
=> auth-4.5.0-beta1: docs+secpoll

.not-formatted, pdns/logger.cc, pdns/logger.hh, pdns/pdns_recursor.cc, pdns/recursor_cache.cc
Plus reformat logger.hh and .cc
Fixes #7389 fully at last...
I have:
=> Implement log methods for QType and QClass 

.github/workflows/secpoll.yml
=> in secpoll testing, do not start the auth

docs/appendices/FAQ.rst
User reported faq was confusing
I have:
=> Correct faq entry to talk about zones

Makefile.am
=> Set LANG=C explicitly, otherwise it may lead to suprises if the user isn't using LANG=C.

.github/actions/spell-check/expect.txt, docs/lua-records/reference/comboaddress.rst, pdns/lua-base4.cc, regression-tests.auth-py/test_LuaRecords.py
=> newCAFromRaw(): create ComboAddress from raw 4/16 byte strings

pdns/packethandler.cc, regression-tests.auth-py/test_SVCB.py
=> SVCB: Fix auto hints removing non-auto hints

pdns/pdnsutil.cc
=> pdnsutil edit-zone: correctly reask inc-serial question

pdns/dnslabeltext.rl, pdns/test-dnsrecords_cc.cc
=> SVCB: on parse error, throw instead of truncate

docs/manpages/pdnsutil.1.rst, pdns/pdnsutil.cc
=> auth pdnsutil add-zone-key: clarify zsk default

pdns/pdnsutil.cc
=> pdnsutil create-zone: better error if default-soa-content is broken

pdns/pdnsutil.cc
=> pdnsutil add-autoprimary: print error when exiting with 1

docs/changelog/4.5.rst, docs/secpoll.zone
=> auth-4.5.0-rc1: secpoll&docs

pdns/pdns_recursor.cc, pdns/recursordist/Makefile.am, pdns/recursordist/logging.cc, pdns/recursordist/logging.hh, pdns/recursordist/logr.hh, pdns/rpzloader.cc
This pull request is a WIP on how we could move current logging to structured logging. This Logr interface is based on a minimal logging API originally written for Go, see https://github.com/go-logr/logr
I'm not satisfied with the usage of intermediate value objects, but this gives for now the ability to accept various types, to unify their string conversion and to prevent conversion to happen if verbosity is too high.
Comments welcome!
I have:
=> rec: Structured logging

pdns/dnsdist.cc
=> dnsdist: Exit nicely to get coverage reports when COVERAGE is defined

builder-support/dockerfiles/Dockerfile.rpmbuild
(cherry picked from commit 912729cf22c5303fa4e0136a639132ca940a186f)
Backport of #10455 
I have:
=> rec: Backport 10455 to rec-4.5.x: builder rpmbuild: run yum upgrade first

docs/upgrading.rst
=> auth 4.2 upgrade docs: note default-api-rectify change

modules/bindbackend/bindbackend2.cc, modules/bindbackend/bindbackend2.hh, modules/bindbackend/binddnssec.cc, pdns/pdnsutil.cc
=> auth 4.5.x bindbackend: NSEC(3) setting consistency, reload improvements

pdns/ueberbackend.cc
=> auth-4.5.x: make UeberBackend::addCache pick the correct ttl

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.5.rst
Due to a build mishap it's going to be 4.5.4
https://builder.powerdns.com/#/builders/97/builds/1909
https://blog.powerdns.com/?p=3524&preview=true
I have:
=> rec: Prep rec-4.5.4

pdns/nsec3dig.cc, pdns/recursordist/aggressive_nsec.cc
=> rec, nsec3dig: NSEC(3) debugging improvements

builder-support/debian/recursor/debian-buster/rules, builder-support/specs/pdns-recursor.spec
Ensure we ship packages with DoT to auths enabled.
I have:
=> Rec: Enable DoT in packages

docs/changelog/4.5.rst, docs/secpoll.zone
=> auth-4.5.0-rc2: docs and secpoll

pdns/dnsdist-web.cc, pdns/dnsdistdist/docs/guides/webserver.rst, regression-tests.dnsdist/test_API.py
=> dnsdist: Implement a web endpoint to get metrics for only one pool

pdns/dnsdist-lua.cc, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Add the missing DOHFronted::loadNewCertificatesAndKeys()

pdns/dnsdist-lua-actions.cc, pdns/dnsdist-protobuf.cc, pdns/dnsdist.cc
=> dnsdist-1.6.x: Set the dnstap/protobuf transport to TCP for DoH queries

builder-support/dockerfiles/Dockerfile.rpmbuild
(cherry picked from commit 912729cf22c5303fa4e0136a639132ca940a186f)
backport of #10455
I have:
=> builder rpmbuild: run yum upgrade first

pdns/dnsdistdist/dnsdist.service.in, pdns/dnsdistdist/docs/advanced/ebpf.rst, pdns/dnsdistdist/docs/advanced/out-of-order.rst, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Documentation fixes (typo, eBPF capabilities)

docs/running.rst
A new user might be confused as to how to manipulate zone data in PowerDNS upon looking at the documentation about "Running and _Operating_". I added a section about ``pdnsutil`` to that page. 
I have:
- [ docs] compiled this code
- [ docs] tested this code
- [ docs] included documentation (including possible behaviour changes)
- [ docs] documented the code
- [ docs] added or modified regression test(s)
- [ docs] added or modified unit test(s)
=> Reference pdnsutil in "Running and Operating"

pdns/syncres.cc, pdns/ueberbackend.cc, pdns/validate.cc
=> Zap a few redundant toString() method call for logging qtype names

modules/bindbackend/binddnssec.cc
I broke this in #10549
reported by Ralf van der Enden
I have:
=> auth: allow building bindbackend without sqlite3

.circleci/config.yml
=> build docs using the texlive image

modules/bindbackend/binddnssec.cc
=> auth-4.5.x: allow building bindbackend without sqlite3

pdns/AUTH-MIB.txt, pdns/dnsdistdist/DNSDIST-MIB.txt, pdns/recursordist/RECURSOR-MIB.txt
This also includes a 'stub' auth MIB just for the purpose of this allocation.
I have:
=> SNMP: allocate local-use ranges for traps and trapObjects

docs/changelog/4.5.rst, docs/secpoll.zone
=> auth-4.5.0: secpoll and docs

.github/actions/spell-check/excludes.txt, .github/actions/spell-check/expect.txt, .github/actions/spell-check/patterns.txt, .github/actions/spell-check/reject.txt, .github/workflows/spelling2.yml
Upgrades to v0.0.19
https://github.com/check-spelling/check-spelling/security/advisories/GHSA-g86g-chm8-7r2p
I have:
=> Upgrade check-spelling to v0.0.19

pdns/pdns_recursor.cc
(cherry picked from commit b2b8ccea95ddde5cd170afef57ba8eeced3d1d0e)
Backport of #10515 
I have:
=> rec: Backport 10515 to rec-4.5.x: Clear the current proxy protocol values each iteration

pdns/lwres.cc, pdns/recursordist/test-mtasker.cc
=> rec: fix some compiler warnings

pdns/recursordist/test-syncres_cc3.cc, pdns/recursordist/test-syncres_cc4.cc, pdns/syncres.cc, pdns/syncres.hh
=> rec: backport #10555 to 4.4.x: Work around clueless servers sending AA=0 answers

pdns/responsestats.cc, pdns/responsestats.hh, regression-tests/tests/type65535-query/command, regression-tests/tests/type65535-query/description, regression-tests/tests/type65535-query/expected_result
(cherry picked from commit 9949e87aad7968d929cd110a8a9bcfa86b9a9d48)
I have:
=> auth-4.5.x: correct upper bounds on d_qtypecounters

docs/changelog/4.5.rst, docs/secpoll.zone, docs/security-advisories/powerdns-advisory-2021-01.rst
=> auth-4.5.1: advisory, changelog, secpoll

pdns/syncres.cc, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_Interop.py
=> rec: do not use DNSKEYs found below an apex for validation

pdns/recursordist/test-syncres_cc.cc, pdns/recursordist/test-syncres_cc10.cc, pdns/recursordist/test-syncres_cc6.cc, pdns/syncres.cc, pdns/syncres.hh
=> rec: Backport 10570 to rec 4.5.x: Make really sure we did not miss a cut on validation failure

builder-support/dockerfiles/Dockerfile.rpmbuild
(cherry picked from commit 912729cf22c5303fa4e0136a639132ca940a186f)
Backport of #10455 
I have:
=> rec: backport 10455 to rec-4.4.x: builder rpmbuild: run yum upgrade first

docs/appendices/EOL.rst
=> auth: EOL update after 4.5 release

.dockerignore
No need to upload this to the docker daemon.
I have:
=> docker: ignore compiled files

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.4.rst, pdns/recursordist/docs/changelog/4.5.rst
Including a few 2->3 upgrades for known vulnerability status for auth
https://builder.powerdns.com/#/builders/97/builds/1944 (4.4.5)
https://builder.powerdns.com/#/builders/97/builds/1949 (4.5.5)
https://blog.powerdns.com/?p=3549&preview=true
I have:
=> rec: Prep for rec-4.4.5 and rec-4.5.5

pdns/dnsdist-ecs.cc, pdns/test-dnsdist_cc.cc
Backport of #10419 to rel/dnsdist-1.6.x.
I have:
=> dnsdist-1.6.x: Properly handle ECS for queries with ancount or nscount > 0

pdns/rpzloader.cc
(cherry picked from commit 0c98e3de2cf1daae3f7034803668c1ac10fefe49)
Backport of #10627 
I have:
=> rec: backport 10627 to rec-4.4.x: Check in more places if the policy has been updated before using or modifying it.

pdns/recursordist/docs/performance.rst
=> rec: Google is working to fix their TFO issues on their DNS servers

pdns/opensslsigners.cc
=> checkKey: handle NULL error string from OpenSSL more gracefully

pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist docs: clarify grepq num parameter

pdns/pdns_recursor.cc, regression-tests.recursor-dnssec/test_RPZ.py
If preresolve returns `true` and indicates the packet should be dropped, do it. 
I have:
=> rec: Process policy and potential Drop action after Lua hooks

pdns/recursordist/test-syncres_cc6.cc, pdns/syncres.cc
Fixes #10621. Needs more testing, and at least one unit test.
I have:
=> rec: Detect a loop when the denial of the DS comes from the child zone

pdns/pdns_recursor.cc, pdns/syncres.cc, pdns/syncres.hh, regression-tests.recursor-dnssec/test_Lua.py
Fixes #10632.
Could use a regression test.
I have:
=> rec: Pass the Lua context to follow up queries (follow CNAME, dns64)

.circleci/config.yml, .github/workflows/build-and-test-all.yml, build-scripts/UBSan.supp, build-scripts/gh-actions-setup-inv, invoke.yaml, modules/remotebackend/Gemfile.lock, pdns/Makefile.am, tasks.py
and remove those from CircleCI.
I'd like to merge this to see if it's stable, and then we can move more things.
I have:
=> github actions: build auth+rec+dnsdist; test auth-api, dnsdist-regression, rec-api

.github/actions/spell-check/advice.md
Iterative improvements to advice offered by check-spelling
I have:
=> Try to improve advice

Dockerfile-auth, Dockerfile-dnsdist, Dockerfile-recursor
=> docker: apt does not have a stable cli

ext/lmdb-safe/lmdb-safe.cc
Discovered this while trying to reduce startup mapsize for dnsdist. For now we're stuck with the 16GB map. If anybody ever has a map bigger than that (and growing) we can add a mapsize option.
I have:
=> lmdb-safe: resizing while there might be open transactions is unsafe

.github/workflows/builder.yml
=> gh actions builder: upload built packages as artifacts

builder-support/debian/recursor/debian-buster/control, builder-support/dockerfiles/Dockerfile.target.debian-bullseye, builder-support/dockerfiles/Dockerfile.target.debian-bullseye-amd64, builder-support/dockerfiles/Dockerfile.target.debian-bullseye-arm64
=> dnsdist: Backport #10407; Debian Bullseye builder files

builder-support/debian/recursor/debian-buster/control, builder-support/dockerfiles/Dockerfile.target.debian-bullseye, builder-support/dockerfiles/Dockerfile.target.debian-bullseye-amd64, builder-support/dockerfiles/Dockerfile.target.debian-bullseye-arm64
=> rec: Backport #10407; Debian Bullseye builder files

pdns/dnsdist.cc, pdns/dnsdistdist/docs/rules-actions.rst, regression-tests.dnsdist/test_Advanced.py, regression-tests.dnsdist/test_Basics.py, regression-tests.dnsdist/test_EDNSSelfGenerated.py
=> dnsdist: Ignore TCAction over TCP

.dockerignore, pdns/dnsdist-lua.cc, pdns/dnsdist-web.cc, pdns/dnsdist.cc, pdns/dnsdist.hh, pdns/dnsdistdist/dnsdist-idstate.cc, pdns/dnsdistdist/docs/guides/webserver.rst, pdns/dnsdistdist/docs/reference/config.rst, pdns/dnsdistdist/tcpiohandler-mplexer.hh, regression-tests.dnsdist/test_API.py, regression-tests.dnsdist/test_Caching.py
This backports the following PRs to rel/dnsdist-1.6.x in preparation for 1.6.1:
- #10656
- #10560
- #10550
- #10389 
I will open a PR against master to correct the documentation for backported features (#10550, #10560).
I have:
=> dnsdist-1.6.x: Backport  #10656, #10560, #10550 and #10389 

.github/workflows/spelling.yml
=> gh actions: add dummy spelling workflow so we can prevent old versions from running

.github/workflows/build-and-test-all.yml, .github/workflows/builder.yml
At least one fork already ran out of the free (500MB) storage allowance.
I have:
=> gh actions: limit retention on uploaded artifacts

.github/workflows/build-and-test-all.yml
=> gh actions: make a single "collect" endpoint to simplify required checks for merges

pdns/recursordist/docs/lua-scripting/dq.rst
Remove duplicate in documentation.
I have:
=> DNSQuestion docs: Remove duplicate `qname`

pdns/syncres.cc
=> rec: Backport 10643 to rec 4.4.x: NS from the cache could be a forwarder

pdns/syncres.cc
=> rec: Backport 10643 to rec 4.5.x:  NS from the cache could be a forwarder 

pdns/dnscrypt.cc, pdns/dnsdist-lua-actions.cc, pdns/dnsdist-snmp.cc, pdns/dnsparser.hh, pdns/iputils.hh, pdns/misc.cc
Obtained with -Wcast-qual.
I have:
=> Clean up a bit of "cast from type [...] casts away qualifiers" warnings

pdns/dnsdistdist/docs/guides/webserver.rst, pdns/dnsdistdist/docs/reference/config.rst
These have been backported to 1.6.1:
- #10560
- #10550
Fixes #10691.
I have:
=> dnsdist: Use the correct version in the doc for backported features

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Prepare ChangeLog and secpoll for 1.6.1

pdns/dnsdist.cc, pdns/dnsdistdist/docs/reference/tuning.rst, pdns/dnsdistdist/docs/upgrade_guide.rst
And better document that change in the upgrade guide.
I have:
=> dnsdist: Stop raising the number of TCP workers to the number of TCP binds

pdns/dnsdistdist/tcpiohandler-mplexer.hh
Reported by Coverity (CID 372512).
I have:
=> dnsdist: Handle exception raised in IOStateGuard's destructor

pdns/dnsdistdist/docs/reference/dq.rst
=> dnsdist: Document DNSQuestion:getProtocol()

tasks.py
=> gh actions: auth make check: cat remotebackend test log

.github/actions/spell-check/expect.txt, pdns/dnsdistdist/docs/install.rst
=> dnsdist: Update the list of dependencies in the documentation

pdns/comfun.cc, pdns/dbdnsseckeeper.cc, pdns/distributor.hh, pdns/dnsdist.cc, pdns/nameserver.cc, pdns/rec_channel.cc, pdns/signingpipe.cc, pdns/stubresolver.cc, pdns/svc-records.cc, pdns/svc-records.hh, pdns/test-svc_records_cc.cc
=> Coverity fixes

regression-tests.api/requirements.txt, regression-tests.ixfrdist/requirements.txt
(cherry picked from commit 8e8be088de0634fc561f5c7f6e26d6ed03f401e8)
Backport of #10721 
I have:
=> rec: Backport 10721 to rec 4.4.x: require nose >= 1.3.7 everywhere

regression-tests.api/requirements.txt, regression-tests.ixfrdist/requirements.txt
(cherry picked from commit 8e8be088de0634fc561f5c7f6e26d6ed03f401e8)
Backport of #10721 
I have:
=> rec: Backport 10721 to rec 4.5.x: require nose >= 1.3.7 everywhere

pdns/recursordist/test-syncres_cc1.cc, pdns/syncres.cc
=> rec: Only the DNAME records are authoritative in DNAME answers

.github/workflows/builder.yml, .github/workflows/docker.yml
=> gh actions: build packages & docker images only once a day

pdns/credentials.cc, pdns/credentials.hh, pdns/dnspacket.hh, pdns/misc.hh
Most of them were introduced in #10157 but there was also a missing `<optional>` header in `dnspacket.hh` preventing compilation for me.
I have:
=> Fix issues reported by Coverity

.circleci/config.yml, pdns/rec_channel_rec.cc, regression-tests.recursor-dnssec/test_Prometheus.py
Fixes #10735 and adds a regress test to prevent this accident in the future.
I have:
=> Rec: fix Prometheus thread cpu usage

pdns/dnsdistdist/dnsdist-tcp-downstream.cc, pdns/dnsdistdist/test-dnsdisttcp_cc.cc
If the client has sent more than one concurrent query using the same query ID, we only send one response for all of these queries, and we should not mess up our outstanding queries counter.
That only happens when out-of-order queries are enabled in both the frontend and the backend.
I have:
=> dnsdist: Don't increase the outstanding counter on a duplicated ID over TCP

.circleci/config.yml, .github/workflows/build-and-test-all.yml, tasks.py
=> gh actions: test auth backends

.github/actions/spell-check/expect.txt, .github/actions/spell-check/patterns.txt, docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
=> dnsdist: Prepare ChangeLog and secpoll update for 1.7.0-alpha1

tasks.py
=> Move to clang12 for github actions, at least tsan seems to work better

pdns/rpzloader.cc
We used to only update these for RPZ loaded via XFR, which does not really makes sense.
I have:
=> rec: Update the stats (serial, number of records, timestamp) for RPZ files

pdns/lwres.cc
Spotted by @mind04, thanks!
I have:
=> rec: Fix compile for !HAVE_FSTRM

pdns/libssl.cc
As spotted by CodeQL. This file potentially holds confidential info, so be strict here.
I have:
=> Don't create file with wide permissions 

pdns/common_startup.cc
These exceptions should never bubble up to this point, but if it does it makes no sense to terminate the whole process because of it.
This commit logs a message at error level and moves on to the next query, like we do in the TCP path.
I have:
=> auth: Gracefully handle uncaught exceptions in the UDP path

modules/bindbackend/bindbackend2.cc
Reload of rejected zones was broken in bind backend. After this pull the backend tries to reload rejected zones once every "bind-check-interval" seconds or when it receives a reload request via pdns_control
fixes #7760
fixes #6232 
fixes #1107
I have:
=> auth: try to reload rejected zones in bind-backend

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.6.rst, pdns/recursordist/docs/changelog/index.rst, pdns/recursordist/docs/settings.rst, pdns/recursordist/docs/upgrade.rst
Prep for rec-4.6.0-alpha1, including a few reference fixes in docs.
https://builder.powerdns.com/#/builders/97/builds/2028 and associates test run succeeded
https://wordpress.com/post/blog.powerdns.com/3577
I have:
=> rec: Upgrade guide and changelog for rec-4.6.0-alpha1

docs/manpages/pdnsutil.1.rst
=> auth: fix copy+paste for decrypt

build-scripts/docker/repo-test/generate-repo-files.py
=> Add dnsdist-17 and rec-46 to repo test script.

pdns/dns.cc
=> Remove the unused BoundsCheckingPointer class

pdns/dnsdistdist/dnsdist-healthchecks.cc
=> dnsdist: Fix several typos in the health check code

docs/appendices/types.rst, docs/backends/bind.rst, docs/backends/generic-mysql.rst, docs/backends/generic-odbc.rst, docs/backends/generic-postgresql.rst, docs/backends/ldap.rst, docs/backends/lua2.rst, docs/backends/pipe.rst, docs/backends/random.rst, docs/backends/remote.rst, docs/backends/tinydns.rst
=> auth docs: remove some leftover mentions of autoserial

pdns/mastercommunicator.cc
=> auth NOTIFY: log names of NSes we could not resolve

.github/actions/spell-check/expect.txt, pdns/recursordist/docs/lua-config/ztc.rst, pdns/recursordist/docs/performance.rst, pdns/recursordist/rec-zonetocache.cc
=> rec: Followup on ZoneToCache and fix #10246: document local root config

docs/upgrading.rst, pdns/dns.cc, pdns/dns.hh, pdns/dnsbackend.cc, pdns/pdnsutil.cc
=> auth: remove attodot feature; fixes #10254

docs/lua-records/index.rst, docs/security.rst
=> Some things you should do when handling untrusted zone files.

.github/workflows/build-and-test-all.yml, regression-tests.dnsdist/test_Advanced.py
=> dnsdist: Disable 'IncludeDir' tests on GH actions

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.4.rst, pdns/recursordist/docs/changelog/4.5.rst
=> rec: Prep for rec-4.4.7 and rec-4.5.7

pdns/Makefile.am
Hopefully fixes #10801.
I have:
=> auth: pdns_control needs to be linked against libcrypto now

pdns/credentials.cc
=> Credentials: EVP_PKEY_CTX_set1_scrypt_salt() takes an `unsigned char*`

pdns/dnsdistdist/docs/index.rst
=> Fix quad9 example servers that had run together

pdns/dnsdistdist/docs/rules-actions.rst
=> If possible, use SuffixMatchNodeRule() instead of RegexRule()

modules/tinydnsbackend/tinydnsbackend.cc, pdns/backends/gsql/gsqlbackend.cc, pdns/dnsbackend.cc, pdns/pdnsutil.cc
=> auth: improve dnsname exception handling for SOA records

pdns/ws-api.cc, pdns/ws-api.hh, pdns/ws-auth.cc, pdns/ws-recursor.cc, regression-tests.api/test_Discovery.py
This avoids surprise 404s mid-path, and also matches what the Recursor docs already promise is there.
I have:
=> auth, rec: put some json on /api/v1

.github/workflows/build-and-test-all.yml, build-scripts/test-recursor, regression-tests.recursor-dnssec/runtests, regression-tests/recursor-test, tasks.py
After a small struggle this is starting to work. I drastically reduced to size of the bulk tests to circumvent the UDP traffic limitation of GH workers.
I also had to work around an issue that occurs on Ubuntu focal: libfstrm interacts in a bad way with libfaketime. Upgrading libfaketime did not work. So I added a mechanism to run a few tests without libfaketime.
I have:
=> rec: gh actions for recursor tests

pdns/rec_channel.cc
=> rec: Use a global timeout for the various recv's we're doing to get a control message

modules/tinydnsbackend/tinydnsbackend.cc, pdns/backends/gsql/gsqlbackend.cc, pdns/dnsbackend.cc, pdns/pdnsutil.cc
=> auth-4.5.x: improve dnsname exception handling for SOA records

pdns/ws-auth.cc, regression-tests.api/test_Zones.py
Partial backport of  #10959
I have:
=> auth-4.5.x: api, check SOA location

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.6.rst, pdns/recursordist/docs/settings.rst, pdns/recursordist/docs/upgrade.rst
https://builder.powerdns.com/#/builders/97/builds/2120
https://wordpress.com/post/blog.powerdns.com/3642
I have:
=> rec: Prep for rec-4.6.0-beta1

pdns/recursordist/docs/lua-scripting/netmask.rst
=> rec: Fix formatting for versionadded

modules/bindbackend/bindbackend2.cc
=> auth bindbackend: skip rejected zones during list and search

modules/bindbackend/bindbackend2.cc
(cherry picked from commit 3d9c1aabb30c95a621d9f5343398980a1b416d51)
backport of #10941
I have:
=> auth-4.x. bindbackend: skip rejected zones during list and search, fixes #10885

docs/changelog/4.5.rst, docs/secpoll.zone
=> auth-4.5.2: secpoll and changelog

docs/performance.rst, docs/security.rst, docs/settings.rst, pdns/recursordist/docs/settings.rst
=> rec, auth: some doc updates

CONTRIBUTING.md
=> some updates to CONTRIBUTING.md

.github/workflows/build-and-test-all.yml, pdns/recursordist/recursor-tsan.supp, regression-tests.api/runtests.py, tasks.py
I left out bulk tests with TSAN, as they become very slow and fail because of too many timeouts now and then.
I have:
=> rec: enable tsan for GH actions rec build and tests

pdns/dnsdist-ecs.cc, pdns/dnsdist-ecs.hh, pdns/dnsdist-lua-actions.cc, pdns/dnsdistdist/docs/rules-actions.rst, regression-tests.dnsdist/test_Advanced.py
=> dnsdist: Handle existing EDNS content for SetMacAddrAction/SetEDNSOptionAction

pdns/validate.cc, regression-tests.recursor-dnssec/test_Expired.py, regression-tests.recursor-dnssec/test_ExtendedErrors.py
Fixes #10936
Should grow a test.
I have:
=> rec: Return the proper ede on validation failure

pdns/rfc2136handler.cc, regression-tests/tests/1dyndns-update-add-delete-mx/expected_result, regression-tests/tests/1dyndns-update-delete-mx-prio/expected_result, regression-tests/tests/1dyndns-update-replace-mx/expected_result, regression-tests/tests/1dyndns-update-srv/expected_result
=> auth 2136: apply new TTL to whole RRset, not only to the added record

.github/workflows/secpoll.yml, docs/secpoll-check.sh
Hope I got the yaml invocation  and quoting right.
I have:
=> More strict secpoll.zone check

docs/secpoll.zone, pdns/recursordist/docs/changelog/4.6.rst, pdns/recursordist/docs/upgrade.rst
=> rec: Prep for rec-4.6.0-beta2

pdns/recursordist/docs/settings.rst
=> rec: Fix a typo in the documentation for 'allow-notify-from'

pdns/recursordist/rec-taskqueue.cc, pdns/recursordist/taskqueue.hh
Needed when using musl libc; fixes #11000
I have:
=> rec: Include sys/time.h in taskqueue.hh

pdns/pdns_recursor.cc, regression-tests.recursor-dnssec/test_Notify.py
<strike>It turns out a notify increments cache-hits, that feel a bit strange and should be looked into.</strike>
Pinging @kpfleming 
I have:
=> rec: Basic notify test

docs/conf.py, docs/requirements.txt, pdns/dnsdistdist/docs/conf.py, pdns/dnsdistdist/docs/requirements.txt, pdns/recursordist/docs/conf.py, pdns/recursordist/docs/requirements.txt
This removes one doc dependency from git.
I have:
=> docs: Use upstream changelog package

pdns/pdns_recursor.cc
See #10751, some extra scrutiny review is needed to make sure no other similar issue remains.
I have:
=> rec: Fix logic botch introduced by notify handling

pdns/pdns_recursor.cc, regression-tests.recursor-dnssec/test_Notify.py
=> rec: backport 10990 to rec 4.6.x: Basic notify test

pdns/rfc2136handler.cc, regression-tests/tests/1dyndns-update-add-delete-mx/expected_result, regression-tests/tests/1dyndns-update-delete-mx-prio/expected_result, regression-tests/tests/1dyndns-update-replace-mx/expected_result, regression-tests/tests/1dyndns-update-srv/expected_result
=> auth-4.4.x: apply new TTL to whole RRset, not only to the added record

pdns/pdns_recursor.cc
=> rec: Backport 11018 to rec 4.6.x: Fix logic botch introduced by notify handing 

pdns/recursordist/test-syncres_cc2.cc, pdns/syncres.cc
See https://datatracker.ietf.org/doc/html/rfc7871#section-7.4
Fixes #10994
I have:
=> rec: Do negcache negative results, even when wasVariable() is true

regression-tests.api/runtests.py, regression-tests.recursor-dnssec/test_AggressiveNSECCache.py, regression-tests.recursor-dnssec/test_ECS.py
There are likely more.
I have:
=> rec: Loosen timing checks that I have seen tripping in tsan enabled tests.

docs/dnssec/operational.rst, docs/domainmetadata.rst, docs/manpages/pdnsutil.1.rst, docs/upgrading.rst, pdns/pdnsutil.cc
=> auth: new default nsec3param settings

.github/workflows/formatting.yml
Should be marked as "required"
I have:
=> Check formatting on GH

pdns/bpf-filter.cc, pdns/dnsdistdist/dnsdist-tcp-downstream.cc, pdns/remote_logger.cc
=> dnsdist: Fix compiler/static analyzer warnings

pdns/dnsdist-console.cc, pdns/dnsdist-lua.cc, pdns/dnsdist-web.cc, pdns/dnsdistdist/connection-management.hh, pdns/dnsdistdist/dnsdist-web.hh, pdns/dnsdistdist/docs/reference/config.rst
=> dnsdist: Add 'showWebserverConfig'

docs/changelog/4.4.rst, docs/secpoll.zone
=> auth 4.4.2 secpoll&docs

pdns/recursordist/docs/lua-scripting/index.rst
=> rec: Warn about blocking calls from Lua

pdns/recursordist/docs/lua-scripting/index.rst
=> doc: grammar tweaks for recursordist lua-scripting

pdns/syncres.cc
=> rec: Compute step sizes for QM a la RFC 9156

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
https://powerdnsblog.wordpress.com/?p=3667&preview=true
I have:
=> dnsdist: Add ChangeLog and secpoll for 1.7.0-beta2

.circleci/config.yml
=> CircleCI: drop formatting check, superseded by GH workflows

pdns/pdns_recursor.cc
=> rec: Catch an exception in guard destructor as seen by coverity.

.circleci/config.yml, regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor/config.sh
=> rec: backport 11044 to rec 4.6.x: Fix v6 setup and start using a more modern auth on circleci 

pdns/lua-recursor4.cc, pdns/lua-recursor4.hh, pdns/pdns_recursor.cc
Shortcut on !function in the stub code.
I have:
=> rec: Do not generate eventtrace records if no Lua hook is defined

.github/workflows/formatting.yml
=> Wrong title of check

modules/bindbackend/bindbackend2.cc
=> auth: prevent bind-hybrid+zone-cache

regression-tests.recursor-dnssec/recursortests.py, regression-tests.recursor-dnssec/test_API.py
Trying to diagnose the recursor asan + ubsan failures, I spotted this.
I have:
=> rec: Regression tests: startup/cleanup fixes

docs/modes-of-operation.rst
Guided by app.grammarly.com
I have:
=> Minor fixes

docs/changelog/4.6.rst, docs/secpoll.zone
~Unfinished, alpha2 might grow a few more PRs.~ Now finished, and renamed to beta.1
=> auth-4.6.0-beta1: secpoll&docs

docs/settings.rst
- Add a hint including an SQL-Query on how to identify records with an unknown record type (as discussed on IRC).
I have:
=> docs: Add hint on how to find generic records in SQL backends

Docker-README.md, Dockerfile-auth, Dockerfile-dnsdist, Dockerfile-recursor
=> rec: Backport 11081 to rec 4.6.x: Remove capability requirements from Docker images

docs/upgrading.rst, pdns/dnsdistdist/docs/upgrade_guide.rst, pdns/recursordist/docs/upgrade.rst
@rgacogne do you want this in the dnsdist docs too? If so, where?
I have:
=> dnsdist, rec, auth: upgrade notes for 11081

pdns/dnsdist-idstate.hh, pdns/dnsdist.cc, pdns/dnsdistdist/doh.cc, pdns/doh.hh
Backport of #11075 to rel/dnsdist-1.7.x.
I have:
=> dnsdist-1.7.x: Fix a double-free when a DoH cross-protocol response is dropped

pdns/dnsdistdist/dnsdist-lua-ffi-interface.h, pdns/dnsdistdist/dnsdist-lua-ffi.cc
=> dnsdist: Add a Lua FFI helper to generate proxy protocol payloads

pdns/dnsdistdist/doh.cc
=> dnsdist: Fix compilation without incoming DoH support

pdns/dnsdistdist/doh.cc
Backport of #11079 to rel/dnsdist-1.7.x.
I have:
=> dnsdist-1.7.x: Check the size of the query when re-sending a DoH query

pdns/version.cc
=> version.c: Two more features to print

pdns/dnsdist-lua-actions.cc, pdns/dnsdistdist/dnsdist-lua-ffi-interface.h, pdns/dnsdistdist/dnsdist-lua-ffi.cc, pdns/dnsdistdist/docs/rules-actions.rst, pdns/dnsparser.cc, pdns/dnsparser.hh, pdns/test-dnsparser_cc.cc, regression-tests.dnsdist/test_Responses.py
This PR adds lua support to remove resource records from a response.
I have:
=> dnsdist: lua support to remove resource records from a response

pdns/iputils.cc
=> fix warning: firstTry is set but not used

.github/workflows/build-and-test-all.yml
=> rec: Fix the path to the recursor's UBSan suppression file in forks

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
https://powerdnsblog.wordpress.com/?p=3677&preview=true
I have:
=> dnsdist: Update the ChangeLog and the secpoll zone for 1.7.0-rc1

pdns/dnsdist-lua.cc, regression-tests.dnsdist/test_Lua.py, tasks.py
=> dnsdist: add newThread() function (experimental, subject to change)

regression-tests.dnsdist/.gitignore
=> dnsdist: Ignore the generated p12 file in the regression tests dir

modules/lmdbbackend/lmdbbackend.cc, pdns/tcpreceiver.cc
backport of:
-  #11115 
-  #11122 
I have:
=> Auth-4.5.x: backports

Docker-README.md, Dockerfile-auth, Dockerfile-dnsdist, Dockerfile-recursor
=> auth-4.6.x: docker images: Remove capability requirements

modules/lmdbbackend/lmdbbackend.cc, pdns/tcpreceiver.cc
backport of:
-  #11115 
-  #11122 
I have:
=> Auth-4.6.x: backports

docs/upgrading.rst, pdns/dnsdistdist/docs/upgrade_guide.rst, pdns/recursordist/docs/upgrade.rst
=> Use RST instead of Markdown for link

pdns/pdnsutil.cc
=> pdnsutil edit-zone: fix n and e behaviour on increase-serial prompt

builder-support/debian/authoritative/debian-buster/copyright, builder-support/debian/dnsdist/debian-buster/copyright, builder-support/debian/recursor/debian-buster/copyright, pdns/version.cc
=> Bump copyright year

tasks.py
=> auth: unixodbc-dev is dependency

m4/boost.m4
Though I'm wondering *why* this toolchain determination is needed.
Will send a PR to upstream as well.
I have:
=> boost.m4: OpenBSD arrived at clang-13

docs/appendices/backend-writers-guide.rst
=> auth docs: overview of DNS storage classes inside PowerDNS

docs/backends/bind.rst, docs/http-api/autoprimaries.rst, docs/http-api/index.rst, docs/http-api/swagger/authoritative-api-swagger.yaml, docs/manpages/pdnsutil.1.rst, modules/bindbackend/bindbackend2.cc, modules/bindbackend/bindbackend2.hh, modules/gmysqlbackend/gmysqlbackend.cc, modules/godbcbackend/godbcbackend.cc, modules/gpgsqlbackend/gpgsqlbackend.cc, modules/gsqlite3backend/gsqlite3backend.cc, pdns/backends/gsql/gsqlbackend.cc, pdns/backends/gsql/gsqlbackend.hh, pdns/dnsbackend.hh, pdns/pdnsutil.cc, pdns/ueberbackend.cc, pdns/ueberbackend.hh, pdns/ws-api.cc, pdns/ws-auth.cc, regression-tests.api/test_Servers.py
Massively cherrypicked from #10609, then expanded and fixed in various places.
~~Needs tests.~~ done
Todo:
I have:
=> auth: add autoprimary management in API & pdnsutil

pdns/dnssecinfra.cc
=> auth: Print algo mnemonic for speed test

modules/lmdbbackend/lmdbbackend.cc
=> auth-4.5.x: lmdb, check if the lookup name is part of the zone

docs/backends/bind.rst, docs/http-api/autoprimaries.rst, docs/http-api/index.rst, docs/http-api/swagger/authoritative-api-swagger.yaml, docs/manpages/pdnsutil.1.rst, modules/bindbackend/bindbackend2.cc, modules/bindbackend/bindbackend2.hh, modules/gmysqlbackend/gmysqlbackend.cc, modules/godbcbackend/godbcbackend.cc, modules/gpgsqlbackend/gpgsqlbackend.cc, modules/gsqlite3backend/gsqlite3backend.cc, pdns/backends/gsql/gsqlbackend.cc, pdns/backends/gsql/gsqlbackend.hh, pdns/dnsbackend.hh, pdns/pdnsutil.cc, pdns/ueberbackend.cc, pdns/ueberbackend.hh, pdns/ws-api.cc, pdns/ws-auth.cc, regression-tests.api/test_Servers.py
=> auth 4.6.x: add autoprimary management in API & pdnsutil #11102

modules/lmdbbackend/lmdbbackend.cc, modules/lmdbbackend/lmdbbackend.hh
=> auth-4.6.x: lmdb, check if the lookup name is part of the zone

pdns/dnsdist-lua-bindings.cc
and make the code a tiny bit more pretty.
Fixes #11113.
I have:
=> dnsdist: Work around a compiler bug seen on OpenBSD/amd64 using clang-13 

pdns/dnsdistdist/test-dnsdistkvs_cc.cc
=> dnsdist: Remove temporary files used in the KVS unit tests

docs/.gitignore, pdns/auth-zonecache.cc, pdns/auth-zonecache.hh, pdns/test-auth-zonecache_cc.cc, pdns/ws-auth.cc
=> auth-4.6.x: add zone removal to the zonecache

docs/appendices/backend-writers-guide.rst, docs/requirements.txt, docs/secpoll.zone, pdns/dnsdistdist/docs/requirements.txt, pdns/recursordist/docs/requirements.txt
=> remove a few lieter dependencies, plus a doc rendering fix

pdns/version.cc
(cherry picked from commit 030c37636cea0dd449acdc9d14f03b2e27ad0791)
Backport of #11109 
I have:
=> rec: Backport 11109 to rec-4.6.x: Two more features to print

pdns/threadname.cc
=> rec: Backport 11137 to rec 4.6.x: try shorted thread names

pdns/recursordist/configure.ac
Same as #11178, but now for rec.
I have:
=> rec: Build with -fvisibility=hidden by default

docs/changelog/4.6.rst, docs/secpoll.zone
=> auth-4.6.0-rc1: docs+secpoll

pdns/dnswasher.cc
=> dnswasher: Fix compilation with !HAVE_IPCIPHER

docs/secpoll.zone, pdns/dnsdistdist/docs/changelog.rst
Blog post draft: https://powerdnsblog.wordpress.com/?p=3695&preview=true
I have:
=> dnsdist: ChangeLog and secpoll update for 1.7.0

.github/workflows/build-and-test-all.yml, docs/http-api/swagger/authoritative-api-swagger.yaml, tasks.py
=> auth swagger: add a syntax test and fix a few things

builder-support/debian/authoritative/debian-buster/copyright, builder-support/debian/dnsdist/debian-buster/copyright, builder-support/debian/recursor/debian-buster/copyright, pdns/version.cc, pdns/ws-auth.cc
=> auth-4.6.x: bump copyright years to 2022

pdns/credentials.cc, pdns/libssl.cc
99% of that PR is based on Habbie's work, to be clear.
I have:
=> auth, dnsdist, rec: Fix build with OpenSSL 3.0.0

.github/workflows/build-and-test-all.yml
=> CI: add forgotten collect target

pdns/credentials.cc
Based on Habbie's pull request for master.
I have:
=> dnsdist-1.7.x: Fix compilation with OpenSSL 3.0.0

Makefile.am, pdns/sha.hh
This should fix the test zone unavailability and the build issue on CentOS7. Untested. Wil do so soon.
Test build: https://builder.powerdns.com/#/builders/97/builds/2223
I have:
=> Zonemd and sha.hh build issues

pdns/recursordist/rec-main.cc
=> rec: Fix #include "logging.hh", it should not be conditional

.github/workflows/builder.yml, builder-support/dockerfiles/Dockerfile.target.ubuntu-jammy
Sits on top of #11196. Second commit needs to be removed when done.
I have:
=> builder: add Ubuntu jammy target

pdns/ws-auth.cc
=> bump ws-auth.cc copyright year

README.md, builder-support/debian/authoritative/debian-buster/copyright, builder-support/debian/dnsdist/debian-buster/copyright, builder-support/debian/recursor/debian-buster/copyright, pdns/version.cc, pdns/ws-auth.cc
=> auth-4.5.x: update copyright years to 2022

Makefile.am
=> Add missing dir in the zonemd test file paths

pdns/recursordist/docs/lua-scripting/hooks.rst
=> rec: Fix a typo in the 'semantics' section of the hooks documentation

docs/changelog/4.5.rst, docs/secpoll.zone
=> auth-4.5.3: changelog and secpoll

.github/workflows/build-and-test-all.yml, docs/http-api/swagger/authoritative-api-swagger.yaml, tasks.py
=> auth 4.6.x swagger: add a syntax test and fix a few things

pdns/packethandler.cc
=> auth-4.6.x: show QType by name in log message

.github/workflows/build-and-test-all.yml, tasks.py
=> auth: install test deps during unit tests, so we get socat

pdns/credentials.cc
=> auth-4.6: Fix build with OpenSSL 3.0.0

Docker-README.md, Dockerfile-auth, Dockerfile-dnsdist, Dockerfile-recursor
=> dnsdist-1.7: Docker images: remove capability requirements

pdns/dnsdistdist/docs/upgrade_guide.rst
=> dnsdist upgrade guide: move docker note to 1.7.1

pdns/dnsdist-lua.cc
=> dnsdist: Fix 'inConfigCheck()'

regression-tests.recursor-dnssec/recursortests.py
=> rec: Fix the exit code when the recursor fails to start in our tests

docs/backends/remote.rst
=> Update remote docs based on experience

pdns/credentials.cc
Backport of https://github.com/PowerDNS/pdns/pull/11196 to rel/rec-4.6.x.
(cherry picked from commit 8535f66672ec9d1eebf5835d3e53238973a80478)
I have:
=> rec-4.6.x: Fix build with OpenSSL 3.0.0
