PowerDNS/pdns

pdns/recursordist/test-syncres_cc4.cc
pdns/syncres.cc

rec: Backport 9309 to rec 4.3.x: Validate cached DNSKEYs against the DSs, not the RRSIGs only

---

pdns/syncres.cc

rec: Backport 9297 to rec 4.2.x: Ignore cache-only for DNSKEYs/DS retrieval 

---

pdns/recursordist/test-syncres_cc4.cc
pdns/syncres.cc

DNSKEYs might be cached in a non-validated state ("Indeterminate")
when the DNSSEC mode is set to "Process" and the initial query did
not ask for validation.
We would then validate the DNSKEY records against the RRSIGs, like
for regular records, but not against the DSs.
(cherry picked from commit 453f37736a4d372e16755a903f5b5d5ac52b0c17)
Backport of #9309 
I have:

rec: Backport 9309 to rec 4.2.x: Validate cached DNSKEYs against the DSs, not the RRSIGs only

---

pdns/dnsdist-console.cc
pdns/dnsdist.cc

Due to some yet undiagnosed interaction of the standard and boost include
files, we hit a syntax error when compiling the boost uuid code on
OpenBSD.  This is fixed by using -std=gnu++11.  This only happens
when compiling dnsdist.cc.  In other places compiling uuid-utils.hh
with -std=c++11 does not trigger an error.
The erorr is:
```
In file included from dnsdist.cc:39:
In file included from ./uuid-utils.hh:24:
In file included from /usr/local/include/boost/uuid/uuid.hpp:203:
In file included from /usr/local/include/boost/uuid/detail/uuid_x86.ipp:22:
In file included from /usr/lib/clang/8.0.1/include/emmintrin.h:27:
In file included from /usr/lib/clang/8.0.1/include/xmmintrin.h:27:
/usr/lib/clang/8.0.1/include/mmintrin.h:81:40: error: cannot initialize a parameter of type …
```

dnsdist: Fix compilation on OpenBSD/amd64

---

pdns/misc.cc
pdns/test-misc_hh.cc

In 5c21b47fbc35ddcb8d939eb8541c6c3bad1080a8 we change how hostname is allocated. We allocate getMaxHostNameSize for string, then give the raw buffer for gethostname function, but forget to resize the string into actual result length, causing the carbon output to include trailing NUL bytes after hostname.
I have:

misc.cc: Resize hostname to final size in getCarbonHostname()

---

pdns/dnsdistdist/dnsdist-proxy-protocol.cc
pdns/proxy-protocol.cc

This PR makes the error message a bit more helpful when trying to send a too large value, instead of the size of cumulated values being too large.
I have:

dnsdist: Improve reporting of possible overflow via large Proxy Protocol values

---

pdns/dnsdist-lbpolicies.hh
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-lbpolicies.cc

It makes a noticeable difference as soon as the number of backends in a pool increases to more than 8 backends, and a huge difference when there is a large number of backends.
I have:

dnsdist: Prevent a copy of a pool's backends when selecting a server

---

pdns/dnsdistdist/docs/guides/dns-over-https.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/upgrade_guide.rst

Including the fact that in 1.5.0 the paths should be listed in the list of path passed to `addDOHLocal` to be able to match a response rule.
Many thanks to Stéphane Bortzmeyer for reporting this!
I have:

dnsdist: Better documentation for HTTP responses map

---

pdns/pdns_recursor.cc
pdns/recursordist/Makefile.am
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc10.cc
pdns/reczones.cc
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_ECS.py
regression-tests.recursor-dnssec/test_RoutingTag.py

The documentation actually mentions that not configuring a certain address family in `query-local-address` means no queries are sent out from that address family. This was only true for IPv4 though. This PR ensures this is true for v6 only installations as well.
I have:

rec: Disable outgoing v4 when QLA has no v4 addresses

---

pdns/dnsdist-carbon.cc
pdns/dnsdist-web.cc

dnsdist: Use toStringWithPort instead of manual addr/port concat

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-healthchecks.cc
pdns/dnsdistdist/docs/reference/config.rst

Force a reconnection when a downstream transitions to the UP state
Force the reconnection of a downstream when a server comes back up. 
I have:

dnsdist: Force a reconnection when a downstream transitions to the UP state

---

pdns/dnsname.hh
pdns/syncres.cc
pdns/syncres.hh

This changes the logic for finding NS records. If a regular (non-recursive) forward zone is hit, we *will* look in the cache to see if we have NS records available. Next we check if they are more specific as the forward domain, and use those instead of asking the forwarder.
This allows having a stub zone for the root. The whole thing does not work properly with qname minimization yet. If e.g. a root forward zone is specified, qname minimization will be switched off by the `isForwardOrAuth` check.
Just fixing this check to return false for non-recursive (stub) forward zones does not work since the Step0 cache check is fooled by the forwarding case in the first part of `doResolveNoQNameMinimization`: a forwarder is always consulted and if it answers with en empty ANSWER record set  (as …

rec: if we have an NS in cache, use it in the forwarder case

---

pdns/dnsdist-ecs.cc
pdns/dnsdistdist/docs/reference/config.rst

To match what we do in the auth and the rec.
I have:

dnsdist: Set the default EDNS buffer size on generated answers to 1232

---

modules/gmysqlbackend/gmysqlbackend.cc
modules/godbcbackend/godbcbackend.cc
modules/gpgsqlbackend/gpgsqlbackend.cc
modules/gsqlite3backend/gsqlite3backend.cc
pdns/backends/gsql/gsqlbackend.hh

Nothing uses this (yet?), but this untangles the constructor, setDB and allocateStatements order.
This way one can setup extra queries in one of the gsql backends -- without this, you'll end up unable to initialise either your query string or stmt. Also, without access to `d_query_stmt` you can't implement a custom list query.
I have:

gsqlbackend: allow backend-specific queries

---

pdns/dynhandler.cc

Log more actions triggered by `pdns_control`:
- `retrieve` (similar to `notify` but v.v.)
- `purge`
- `set`
Useful for debugging / analysing behaviour changes.
I have:

auth: log more pdns_control actions

---

pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-backend.cc

As reported in #9372, we used to keep the responder thread alive when a backend was removed, wasting resources.
I have:

dnsdist: Stop the related responder thread when a backend is removed

---

modules/bindbackend/bindbackend2.cc
modules/lmdbbackend/lmdbbackend.cc
pdns/lua-base4.cc
pdns/lua-recursor4.cc
pdns/pdnsutil.cc

Replace the use of '1' by QClass::IN to improve readability

---

pdns/ws-auth.cc
regression-tests.api/test_Zones.py

Before, it was possible to set nsec3params, but an API user was never
able to switch back to NSEC.
I have:

Auth API: Allow removal of NSEC3PARAM metadata

---

pdns/receiver.cc

Fixes help
I have:
```sh
current-config [diff|default]    retrieve the current configuration
[root@offsite pdns]# pdns_control current-config default
Syntax: current-config [diff]
```

receiver: fix help output for pdns current-config

---

pdns/ws-auth.cc
pdns/ws-auth.hh
regression-tests.api/test_Zones.py

This is an attempt to fix issue 8610, allowing for 'delete' and 'replace' rrsets to be combined in the same request, for the same record type. https://github.com/PowerDNS/pdns/issues/8610
I have:

Make a combination of delete and replace for rrset possible

---

modules/geoipbackend/geoipbackend.cc

618824cb73db384d52cf379c7d49744dbb5b8f6d (PR #7219) fixed computation
of weighted round robin computation per Qtype.
That commit also introduced a bug on the removal of the rounding gap.
Because it works on a copy of a GeoIPDNSResourceRecord, the updated
weight of the last record is not propagated to the domain object.
The bug is as follow:
1. The total weight is < 1000
2. The random probabability gives 1000
3. There is no resource to be given
This commit restores the original behavior of ensuring the gap is added
to the last resource so we always have 1000.
I have:

geoipbackend: propagate weighted rounding gap fix

---

builder-support/debian/authoritative/debian-buster/rules
builder-support/debian/authoritative/debian-jessie/rules
builder-support/debian/authoritative/debian-stretch/rules
builder-support/debian/recursor/debian-buster/rules
builder-support/debian/recursor/debian-jessie/rules
builder-support/debian/recursor/debian-stretch/rules
builder-support/specs/pdns.spec
docs/backends/generic-sql.rst
pdns/Makefile.am
pdns/recursordist/docs/getting-started.rst

During the configuration generation step in the build process for auth, the flag --no-config in 'pdns_server --no-config --config' is redundant as the --config flag already prevents auth from loading configurations as per https://github.com/PowerDNS/pdns/blob/master/pdns/receiver.cc#L418-L419
I have:

auth: remove redundant --no-config in makefile

---

pdns/recursordist/docs/lua-scripting/dnsname.rst

Since overloading Lua wrapper functions does not seem to be possible,
fix docs for DNSName:equal(). But note that == is defined for DNSNames.
Fixes #7510
Also zap a duplicated line in `lua-base4.cc`.
I have:

Fix docs for DNSName::equal()

---

docs/http-api/swagger/authoritative-api-swagger.yaml

The listZone operation supports the 'rrsets' parameter in the same
fashion as createZone does.

Document 'rrsets' parameter to API listZone operation

---

docs/dnssec/pkcs11.rst

Fixes a documentation mistake, and also documents how to use SoftHSM2 token remotely. This makes SoftHSM2 integration more secure by keeping the actual token out of PowerDNS process.
I have:

PKCS#11: Document SoftHSM2 remote usage

---

docs/manpages/pdns_control.1.rst
pdns/communicator.cc
pdns/communicator.hh
pdns/dynhandler.cc
pdns/receiver.cc
pdns/slavecommunicator.cc

This patch allows using `pdns_control retrieve domain ip` to force retrieve the domain. This overrides all slave checks.
I have:

Allow forced retrieval

---

pdns/Makefile.am
pdns/dnsdist.cc
pdns/dumresp.cc
pdns/iputils.cc
pdns/iputils.hh
pdns/nameserver.cc
pdns/nameserver.hh
pdns/pdns_recursor.cc

On FreeBSD, `SO_REUSEPORT` "permits multiple instances of a program to each receive UDP/IP multicast or broadcast datagrams destined for the bound port", while `SO_REUSEPORT_LB` distributes them "among the sharing processes based on a hash function of local port number, foreign IP address and port number".
I tested that `SO_REUSEPORT` is still correctly enabled on Linux after this change, but not that `SO_REUSEPORT_LB` is actually enabled on FreeBSD.
Closes #9156.
I have:

Add support for FreeBSD's SO_REUSEPORT_LB

---

pdns/filterpo.cc
pdns/filterpo.hh
pdns/recursordist/test-filterpo_cc.cc
pdns/rpzloader.cc

While there, refactor the name based code as well and fix a bug in the removal of Local data (aka Custom) records.
There are two XXX, wrt the return type of of the `Netmask::lookup()` function.
I have:

Rec: allow multipe local data records when doing RPZ IP matching

---

pdns/dnsdist-console.cc

There's a typo on line 529, where it says "true", but the double quotes cause a type cast error on LLVM11.
dnsdist-console.cc:529:32: error: type 'const char [5]' cannot be narrowed to 'bool' in initializer list [-Wc++11-narrowing]
{ "SetNegativeAndSOAAction", "true", "nxd, zone, ttl, mname, rname, serial, refresh, retry, expire, minimum [, options]", "Turn a query into a NXDomain or NoData answer and sets a SOA record in the additional section" },
^~~~~~
dnsdist-console.cc:529:32: note: insert an explicit cast to silence this issue
{ "SetNegativeAndSOAAction", "true", "nxd, zone, ttl, mname, rname, serial, refresh, retry, expire, minimum [, options]", "Turn a query into a NXDomain or NoData answer and sets a SOA record in the additional section" },
^~~~~~
static_cast<bool>( )
1 error …

Fix building with LLVM11

---

pdns/misc.cc
pdns/test-misc_hh.cc

Note that the test had to be adapted since older `getCarbonHostname()` always truncates at dot.
I have:

rec: Backport 9343 to rec 4.3.x: Resize hostname to final size in getCarbonHostname()

---

pdns/dnsdistdist/dnsdist-lbpolicies.cc
pdns/dnsdistdist/test-dnsdistlbpolicies_cc.cc

Working with indices instead of copying shared pointers results in a nice speed up, cutting the CPU time in half.
I have:

dnsdist: Speed up the round robin policy

---

pdns/delaypipe.cc
pdns/delaypipe.hh
pdns/dnsdistdist/test-delaypipe_hh.cc

Otherwise the `DelayPipe` thread might stop because the read() operation has been interrupted by a signal (like `SIGWINCH`, which is quite annoying).
Also remove the unused `read()` operation.
I have:

dnsdist: Handle EINTR in DelayPipe

---

pdns/dbdnsseckeeper.cc

auth: clear the key cache after addKey()

---

pdns/misc.cc
pdns/test-misc_hh.cc

Note that the test had to be adapated since older `getCarbonHostname()` truncates at dot.
I have:

rec: Backport 9343 to rec 4.2.x: Resize hostname to final size in getCarbonHostname()

---

pdns/receiver.cc
pdns/statbag.cc
pdns/statbag.hh
pdns/testrunner.cc

This avoids auth testrunner failures on 32 bit architectures. Possibly it also avoids silent memory corruption on 64 bit architectures.
I have:

statbag: handle key redeclarations better

---

pdns/recursordist/docs/settings.rst
pdns/syncres.cc

If we hit maxdepth, we still want to have some room to do the doResolveNoQNameMinimization call.
I have:

rec: Allow some more depth headroom for the no-qname-minimization fallback case

---

pdns/recursordist/test-syncres_cc10.cc

rec: FIx a few "warning: comparison of integers of different signs" on clang.OpenBSD

---

pdns/sdig.cc

During auth test runs, we occasionally see replies meant for unbound-host (ran just before sdig) end up on sdig's reply socket. This message should make that situation slightly less baffling.
I have:

sdig: report non-zero ID in response

---

pdns/dnsdist-console.cc
pdns/dnsdist-console.hh
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst

It removes the history items and delta() data from memory, which might be useful when a lot of commands are issued over time, to prevent a large memory usage.
I have:

dnsdist: Add the 'clearConsoleHistory' command

---

.github/actions/spell-check/expect.txt
pdns/dnsmessage.proto
pdns/filterpo.cc
pdns/filterpo.hh
pdns/lua-recursor4.cc
pdns/pdns_recursor.cc
pdns/rec-protobuf.cc
pdns/rec-protobuf.hh
pdns/recursordist/docs/lua-scripting/dq.rst
pdns/syncres.cc
regression-tests.recursor-dnssec/test_Protobuf.py

In RPZ speak, the trigger is the lefthand side of an RPZ rule. If a RPZ rule is hit, store the value of this trigger in the `appliedPolicy.policyTrigger` field so LUA can access it and also store it in the protobuf message.
Also add the value that caused the hit. 
While working on this, I noticed the docs mention `appliedPolicy.policyAction`, but the code does not set it afaiks. I'm assuming `appliedPolicy.policyType` was meant. Adapt the code and docs to agree with respect to this  and add `policytypes` listing the possible values for `policyType`.
Also added code to use the information in appliedPolicy to do logging in a consistent manner.
I have:

Rec: rpz store trigger in appliedPolicy and protobuf message

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdist.cc
pdns/dnsname.cc
pdns/dnsparser.cc
pdns/misc.hh

It should provide a small speed-up for KVS lookups, `SpoofAction`, `LogAction` and `fixup case` handling in dnsdist. It might save a few allocations for DNSSEC validation in the rec, and perhaps in some cases in the LMDB backend as well.
I have:

Avoid unnecessary allocations and copies with DNSName::toDNSString()

---

pdns/dnsdist-cache.cc
pdns/dnsdist-cache.hh
pdns/fuzz_dnsdistcache.cc

I stumbled upon unneeded memory allocations and copies while doing benchmarks to asses the impact of #8993.
Getting rid of them delivers a nice speed-up, up to ~40% in unrealistic micro-benchmarks, likely much less in practice.
I have:

dnsdist: Get rid of allocations in the packet cache's fast path

---

pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
pdns/dnsdistdist/docs/reference/config.rst

It saves one from typing `newDNSName()` :)
I have:

dnsdist: Accept string in DNSDistPacketCache:expungeByName

---

pdns/recursordist/docs/settings.rst
pdns/syncres.cc

rec: backport 9375 to rec 4.3.x: Allow some more depth headroom for the no-qname-minimization fallback case

---

pdns/dnsdist-lua-inspection.cc

We should not get an empty DNSName into the ring buffer, but let's
handle it gracefully if it does happen so we can investigate, instead
of getting:
> Caught exception: empty dnsnames aren't part of anything
I have:

dnsdist: Handle empty DNSNames in grepq()

---

pdns/packethandler.cc

The Auth already logs all NOTIFY cases except the successful one on `Notice` or higher, lets do the same on success.
I have:

auth slave: log successful NOTIFY

---

pdns/recursordist/docs/lua-scripting/netmask.rst

I have made this little rewrite to avoid other from pit falling into the same mistake I made myself, and read the existent code as a list of IP's inside `bad.ips`, and not a script returning pre-formatted IPs.
I have:

Small rewrite of `addMasks(dofile`

---

pdns/syncres.cc
pdns/syncres.hh

E.g. if foo.bar.com is forwarded and the qname is x.foo.bar.com,
start the QM process with ancestor foo.bar.com, so the query is
directed to the forwarder.  But if the qname is baz.bar.com, we do
regular QM, starting with the regular ancestor.
Should fix #9438 without breaking having forward for dot.
I have:

rec: We only want to do QName Minimization for the names in a forwarded domain.

---

pdns/dnsbulktest.cc

They are required to use `dns_random()`, which is used by our DNS packet generation code.
Reported by @franklouwers (thanks!).
I have:

dnsbulktest: Initialize the 'rng' and 'entropy-source' arguments

---

pdns/syncres.cc

A missing SOA in the authority section of negative (NXDOMAIN, NODATA) answers in a DNSSEC-secure zone currently leads to a Bogus result, because the needed NSEC/NSEC3 could not be validated.
Perhaps we could try to detect such a case and check for a valid denial of proof if a NSEC/NSEC3 record shows up in authority?
In the meantime this PR makes it clearer why the DNSSEC status was updated to Bogus in the trace.
I have:

rec: Log when going Bogus because of a missing SOA in authority

---

m4/pdns_check_dnstap.m4

Fail the configure when protobuf is disabled or not found but dnstap was
enabled.
Closes #9452
@omoerbeek @rgacogne Would it make sense to define a `HAVE_DNSTAP` that semi-replaces the `HAVE_FSTRM` for all dnstap related code?
I have:

dnsdist, rec: dnstap requires protobuf

---

pdns/cachecleaner.hh
pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursor_cache.hh
pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh
pdns/recursordist/test-negcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc2.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/recursordist/test-syncres_cc9.cc
pdns/reczones.cc
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor/config.sh

While the main record cache is shared between threads since some time, the negcache was not. This makes is so.
While there, simplify the `lruReplacingInsert()` result to just signal if an entry was inserted or replaced (this makes counting more easy) and generalize the invalidating of the per-shard cache used in the record cache so the code can be more easily be reused in the negcache.
This code keeps track of mutex acquired/contended counts. Don't know if this is going to stay, it is not exported in any way atm.
I have:

Rec: shared and sharded negcache

---

pdns/pdnsutil.cc

Frank Habicht emailed there was a small typo in pdnsutil where ipdecrypt was described as ipencrypt

Update pdnsutil.cc ipencrypt/ipdecrypt typo

---

docs/settings.rst
modules/lmdbbackend/lmdbbackend.cc
pdns/common_startup.cc
pdns/dnsname.cc
pdns/packethandler.cc
pdns/packethandler.hh
pdns/zone2sql.cc

- LMDB backend was not handling out of zone additionals well.
- doAdditionalProcessingAndDropAA() was wasting backend queries for out of zone records (this was triggering the lmdb bug)
- Remove the 'do-ipv6-additional-processing' setting, processing is now always on (hey, it is 2020 ;) )
- Some cleanup in zone2sql and doAdditionalProcessingAndDropAA()
I have:

Auth: remove a '// HACK FIXME400' and fix the bugs it was hiding

---

pdns/packethandler.cc

This is more efficient and some backends cannot deal with out of zone lookups. (lmdb)
Derived from #9478
I have:

auth: backport to 4.3.x: Do not send out of zone lookups to the backends

---

pdns/rec_channel_rec.cc

This was impelmented as part of the shared record cache code, but suffred a bug (likely a rebase error).
I have:

rec: Fix rec_control wipe-cache-typed

---

pdns/snmp-agent.hh

This avoids a case where the thread object and the RecursorSNMPAgent
object get destroyed in the wrong order.
```#0  thrkill () at /tmp/-:3
#1  0x000008fc7b1a55ee in _libc_abort () at /usr/src/lib/libc/stdlib/abort.c:51
#2  0x000008fc60181b3c in abort_message (format=<optimized out>) at /usr/src/lib/libcxxabi/src/abort_message.cpp:77
#3  0x000008fc60181f5f in demangling_terminate_handler () at /usr/src/lib/libcxxabi/src/cxa_default_handlers.cpp:76
#4  0x000008fc6016153f in std::__terminate (func=0x0) at /usr/src/lib/libcxxabi/src/cxa_handlers.cpp:60
#5  0x000008fc601614a9 in std::terminate () at /usr/src/lib/libcxxabi/src/cxa_handlers.cpp:91
#6  0x000008fc23cbc835 in std::__1::thread::~thread (this=0x0) at /usr/src/lib/libcxx/src/thread.cpp:44
#7  0x000008f9e1d8d0df in …
```

rec: Detach snmp thread to avoid trouble when trying to quit nicely.

---

ext/lmdb-safe/lmdb-safe.hh
pdns/dnsdist-cache.cc
pdns/dnsdistdist/doh.cc
pdns/packetcache.hh
pdns/views.hh

While we do not actually care about `string_view::at()` in lmdb-safe, we need to keep the two in sync so the type aliases do not collide.
Perhaps we should consider using `pdns_string_view` as an alias (outside of lmdb-safe) instead?
I have:

Sync string_view definition in lmdb-safe

---

pdns/dnsdistdist/docs/reference/dq.rst

The docs on `setProxyProtocolValues()` didn't mention the predefined entries in the Proxy Protocol specs. + Cleanup of silly quotes ('' got replaced by funky quotes in the rst to html process)
I have:

Point to reserved values for setProxyProtocolValues() + funky quotes replacements

---

.github/actions/spell-check/expect.txt
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/libssl.cc

The OpenSSL option SSL_OP_PRIORITIZE_CHACHA prioritizes ChaCha20-Poly1305 if the client does by temporarily re-prioritizing it to the top of the server cipher list. Since dnsdist already sets SSL_OP_CIPHER_SERVER_PREFERENCE by default (preferServerCiphers is set to true), setting this option enables clients that prefer ChaCha20 due to a lack of AES-NI (such as mobile devices) to override the server specified list. This option requires SSL_OP_CIPHER_SERVER_PREFERENCE to be set and was introduced in OpenSSL 1.1.1.
Note that this change neither affects clients that prefer AES or other ciphers, nor dnsdist's default options, unless the client explicitly prioritizes ChaCha20.
I have:
I have not added regression or unit tests as I was not sure if they are required for code that doesn't change …

dnsdist: prioritize ChaCha20-Poly1305 when client does

---

pdns/dnsdist-ecs.cc
pdns/test-dnsdist_cc.cc

Since 1.5.0, calling `getEDNSOptions()` from Lua would result in a `ServFail` for queries that had no records in additional but at least one record in either the answer or authority section, such as a `NOTIFY`, because of a bug in `parseEDNSOptions()`. That last function incorrectly called `slowParseEDNSOptions()` in that case, triggering an exception to be raised because `slowParseEDNSOptions()` does not expect to be called for a packet with no record in the additional
section.
`parseEDNSOptions()` now returns `false` for packets that have no record in the additional section.
I have:

dnsdist: Fix getEDNSOptions() for {AN,NS}COUNT != 0 and ARCOUNT = 0

---

pdns/lwres.hh
pdns/misc.cc
pdns/misc.hh
pdns/mtasker.cc
pdns/mtasker.hh
pdns/pdns_recursor.cc

This PR should have no functional impact, it just makes reviewing the code easier. It also saves a `gettimeofday()` call in `DTime::udiff()` which should not have any meaningful impact either.
I have:

rec: Better const-ness when dealing with timestamps

---

pdns/pdns_recursor.cc

It might be that there was no other incoming query on that connection and we timed out while the response had not been sent yet, but the client might want to re-use the connection after receiving the response.
We try to reset the TTD, but that might fail when the socket descriptor has already been removed.
I have:

rec: Watch the descriptor again after an out-of-order read timeout

---

ext/luawrapper/include/LuaContext.hpp

via https://github.com/ahupowerdns/luawrapper/pull/33
```
> pc = newPacketCache(5000000, {86400, 0, 60, 60, false, 40} )
[string "pc = newPacketCache(5000000, {86400, 0, 60, 6..."]:1: Caught exception: Expected key/value table, got array
stack traceback:
[C]: in function 'newPacketCache'
[string "pc = newPacketCache(5000000, {86400, 0, 60, 6..."]:1: in main chunk
```
(it's even more useful with files, of course)
I have:

lua: add backtraces to errors

---

docs/upgrading.rst
modules/gpgsqlbackend/spgsql.cc

This avoids weird parsing errors when your password contains spaces or single quotes.
I have:

auth: quote/escape PG connection parameters

---

pdns/ws-recursor.cc

Minimal backport of #9070
I have:

rec: backport to rec-4.3.x: Boost 1.73 moved boost::bind placeholders to the placeholders namespace 

---

pdns/ws-recursor.cc

Minimal backport of #9070 
I have:

rec: backport to rec-4.2.x: Boost 1.73 moved boost::bind placeholders to the placeholders namespace

---

modules/bindbackend/bindbackend2.cc

Makes `rediscover` detect changes to `masters` and/or `also-notify` in named.conf. Without this a restart is required for a new master to be used.
I have:

auth: bindbackend: 'rediscover' changes to master and also-notifies

---

pdns/dbdnsseckeeper.cc
pdns/dnsseckeeper.hh
pdns/rfc2136handler.cc
pdns/ws-auth.cc

And use rectify for full zone rectifies in the rfc2136 code
I have:

auth: make sure the metadata cache is not filled from within an api transaction

---

pdns/pdns_recursor.cc

rec: Backport 9495 to rec 4.3.x: Watch the descriptor again after an out-of-order read timeout

---

pdns/pdns_recursor.cc

rec: Backport 9495 to rec 4.4.x: Watch the descriptor again after an out-of-order read timeout 

---

pdns/syncres.cc

A missing SOA in the authority section of negative (NXDOMAIN, NODATA)
answers in a DNSSEC-secure zone currently leads to a Bogus result,
because the needed NSEC/NSEC3 could not be validated.
(cherry picked from commit 832f4fbdd7ef50d0e0ff5135ee6e270acc22df9d)
I have:

rec: Backport of 9471 to rec-4.3.x: Log when going Bogus because of a missing SOA in authority

---

pdns/syncres.cc

A missing SOA in the authority section of negative (NXDOMAIN, NODATA)
answers in a DNSSEC-secure zone currently leads to a Bogus result,
because the needed NSEC/NSEC3 could not be validated.
(cherry picked from commit 832f4fbdd7ef50d0e0ff5135ee6e270acc22df9d)
Backport of #9471 
I have:

rec: Backport 9471 to rec-4.4.x: Log when going Bogus because of a missing SOA in authority

---

pdns/svc-records.hh

Should fix 6 coverity warnings.
Warnings were all:
```
________________________________________________________________________________________________________
*** CID 362685:  Uninitialized members  (UNINIT_CTOR)
/svc-records.cc: 66 in SvcParam::SvcParam(const SvcParam::SvcParamKey &)()
60     
61     SvcParam::SvcParam(const SvcParamKey &key) {
62       d_key = key;
63       if (d_key != SvcParamKey::no_default_alpn) {
64         throw std::invalid_argument("can not create non-empty SvcParam for key '" + keyToString(key) + "'");
65       }
>>>     CID 362685:  Uninitialized members  (UNINIT_CTOR)
>>>     Non-static class member "d_port" is not initialized in this constructor nor in any functions that it calls.
66     }
67     
68     SvcParam::SvcParam(const SvcParamKey &key, const …
```

svb-records: Initialize d_port

---

pdns/dnsdist-console.cc

Backport of #9408 to dnsdist-1.5.x.
There's a typo on line 529, where it says "true", but the double quotes cause a type cast error on LLVM11.
```
dnsdist-console.cc:529:32: error: type 'const char [5]' cannot be narrowed to 'bool' in initializer list [-Wc++11-narrowing]
{ "SetNegativeAndSOAAction", "true", "nxd, zone, ttl, mname, rname, serial, refresh, retry, expire, minimum [, options]", "Turn a query into a NXDomain or NoData answer and sets a SOA record in the additional section" },
^~~~~~
dnsdist-console.cc:529:32: note: insert an explicit cast to silence this issue
{ "SetNegativeAndSOAAction", "true", "nxd, zone, ttl, mname, rname, serial, refresh, retry, expire, minimum [, options]", "Turn a query into a NXDomain or NoData answer and sets a SOA record in the additional section" }, …
```

dnsdist-1.5.x: Fix building with LLVM11

---

pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-backend.cc

Backport of #9378 to dnsdist-1.5.x.
(cherry picked from commit be55a20ce9bb7140071279d70bcb460f1f2b7b7d)
I have:

dnsdist-1.5.x: Stop the related responder thread when a backend is removed

---

pdns/dnsdist-console.cc
pdns/dnsdist-console.hh
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst

Backport of #9379 to dnsdist-1.5.x.
I have:

dnsdist-1.5.x: Add the 'clearConsoleHistory' command

---

pdns/dnsdist-ecs.cc
pdns/test-dnsdist_cc.cc

Backport of #9513 to dnsdist-1.5.x.
Since 1.5.0, calling `getEDNSOptions()` from Lua would result in a `ServFail` for queries that had no records in additional but at least one record in either the answer or authority section, such as a `NOTIFY`, because of a bug in `parseEDNSOptions()`. That last function incorrectly called `slowParseEDNSOptions()` in that case, triggering an exception to be raised because `slowParseEDNSOptions()` does not expect to be called for a packet with no record in the additional section.
`parseEDNSOptions()` now returns `false` for packets that have no record in the additional section.
(cherry picked from commit 38af359d79bccc500deaa598957a1b0d1ce11fd4)
I have:

dnsdist-1.5.x: Fix getEDNSOptions() for {AN,NS}COUNT != 0 and ARCOUNT = 0

---

ext/yahttp/yahttp/reqresp.cpp
pdns/misc.cc
pdns/rcpgenerator.cc
pdns/test-zoneparser_tng_cc.cc
pdns/zoneparser-tng.cc

These remaining cases are not in any way a security issue since the variables are initialized before the call. This mostly improves the reporting, and make sure we fail earlier.
I have:

Always check sscanf's return value

---

docs/manpages/pdns_control.1.rst
pdns/dynhandler.cc
pdns/statbag.cc
pdns/statbag.hh

Adds a variant of the "SHOW" command, listing only statistics with a given prefix.
Example:
```
$ ../pdns/pdns_control show 'domain-cache*'
domain-cache-hit=0,domain-cache-miss=0,domain-cache-size=7,
```
I have:

pdns_control: add show <prefix>

---

pdns/dnsdist.cc
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_Trailing.py

I can't reproduce that failure outside of Travis / Circle CI and even there if does happen randomly. I hope that adding some debug in verbose mode will help me track the root cause..
I have:

dnsdist: Debug trailing data failures

---

pdns/dnsdist-ecs.cc
pdns/test-dnsdist_cc.cc
regression-tests.dnsdist/clientsubnetoption.py
regression-tests.dnsdist/cookiesoption.py
regression-tests.dnsdist/test_Advanced.py
regression-tests.dnsdist/test_Basics.py
regression-tests.dnsdist/test_RecordsCount.py
regression-tests.dnsdist/test_XPF.py

This PR also includes fixes to make our regression tests work with dnspython 2.0.0, as without those fixes I can't test locally anymore :-)
I have:

dnsdist: Only add EDNS on negative answers if the query had EDNS

---

pdns/dnsdist-ecs.cc
pdns/test-dnsdist_cc.cc
regression-tests.dnsdist/clientsubnetoption.py
regression-tests.dnsdist/cookiesoption.py
regression-tests.dnsdist/test_Advanced.py
regression-tests.dnsdist/test_Basics.py
regression-tests.dnsdist/test_RecordsCount.py
regression-tests.dnsdist/test_XPF.py

Backport of #9553 to dnsdist-1.5.x.
I have:

dnsdist-1.5.x: Only add EDNS on negative answers if the query had EDNS

---

pdns/recursordist/docs/http-api/endpoint-servers-config.rst

Due to include structure we have a double "Configuration endpoint" header
I have:

rec: fix double "Configuration endpoint" in docs

---

pdns/pdns_recursor.cc

This ensures we don't log anything _apart_ from the version info.
Spotted in https://github.com/PowerDNS/pdns_recursor-ansible/issues/66
I have:

recursor: Don't parse any config with `--version`

---

pdns/pdns_recursor.cc

This ensures we don't log anything _apart_ from the version info.
Spotted in https://github.com/PowerDNS/pdns_recursor-ansible/issues/66
(cherry picked from commit 2733183fc0b35ed2b59c87aab5aaaa86688db778)
Backport of #9569 
I have:

rec: backport 9569 to rec 4.4.x: Don't parse any config with `--version`

---

pdns/dnsdistdist/Makefile.am

* make sure dnsdist-lua-ffi-interface.inc is built before dnsdist-lua-ffi.o
* cleaner output while building that .inc
by Pieter Lexis
I have:

dnsdist make: two fixes

---

pdns/iputils.cc
pdns/iputils.hh
pdns/reczones.cc
pdns/syncres.hh
pdns/test-iputils_hh.cc

Currently an IPv6 addres makes it use the explicit port case, interpreting the prefix as an IPv4 address.
Fix this by looking from the right for a colon. Also add unit tests. Fixes #7743
I'm moving this function to iputils as well (linking reczones with testrunner does no go smoothly).
There still remains an ambiguity I'm not really happy with: `string:port` can either be a full IPv6 address or a IPv6:port combo. If the string happens to parse as an IPv6 address the latter is returned. 
e.g.:
```
1::33:99 -> [1::33]:99
1:33::99 -> [1:33::99]
```
To avoid ambiguity always use square brackets for IPv6 addresss.
Since the original code allowed for naked IPv6 addresses we cannot just force that, alas. Or can we?
I have:

Rec: make parse ip:port a bit smarter

---

pdns/recursordist/test-syncres_cc2.cc

This avoids the non-deterministic behaviour.
It is still worthwhile  to investigate the non-deterministic case (when both address familiies are available).
See #9559 and #9565 
I have:

rec: Switch off IPv4 for test_glueless_referral_loop test to make sure there's only one IP per nameserver

---

pdns/notify.cc

Noticed this while looking at something related.
`getaddrinfo(3)` documents the return values as only zero meaning success. Indeed all other `getaddrinfo` call sites already check this correctly.
I have:

Fix error checking on one getaddrinfo call

---

pdns/axfr-retriever.hh

```
The uninitialized class member 'd_trc' is used to initialize the 'd_tsigVerifier' member.
```
According to the language standard, class members are initialized in the constructor in the same order as they are declared inside the class.
Your code contains a constructor where the initialization of one class member depends on another.
```cpp
AXFRRetriever::AXFRRetriever(const ComboAddress& remote,
const DNSName& domain,
const TSIGTriplet& tt, 
const ComboAddress* laddr,
size_t maxReceivedBytes,
uint16_t timeout)
: d_tsigVerifier(tt, remote, d_trc), d_receivedBytes(0), d_maxReceivedBytes(maxReceivedBytes)
```
At the same time, a variable used for initialization is not yet initialized itself.
To fix the bug, we need to put the declaration of the 'd_trc' class member before the declaration …

fix the initialization order in the class.

---

pdns/dnsparser.cc
pdns/dnsparser.hh
pdns/pdns_recursor.cc

We used to ignore questions that we consider invalid (unexpected opcode, qdcount != 1, QR=1, parse error, ...) but also those
received from source addresses blocked by ipfilter, still waiting for a new question to come up on the socket.
That might be fine for clients that will keep sending queries, even though they will still end up wondering what happened to the ignored queries, but some clients like dnsdist will wait until a response is sent, or a time out occurs.
Closing the TCP connection instead allows dnsdist to keep going, possibly retrying over a new connection but finally giving up,
instead of keeping the connection alive.
I have:

rec: Terminate TCP connections instead of 'ignoring' errors

---

.circleci/config.yml
build-scripts/test-sources-sorted.py
modules/geoipbackend/Makefile.am
modules/ldapbackend/Makefile.am
modules/lmdbbackend/Makefile.am
modules/lua2backend/Makefile.am
modules/remotebackend/Makefile.am
pdns/Makefile.am
pdns/dnsdistdist/Makefile.am
pdns/recursordist/Makefile.am

Closes #9521 
This adds a script to circle-ci that fails check-formatting if the lines in all `_SOURCES` entries are not sorted properly.
See a check with a wrongly sorted file [here](https://app.circleci.com/pipelines/github/pieterlexis/pdns/478/workflows/b62f38bf-ca85-4673-945f-1c964cd9271a/jobs/7602)
I have:

Sort *_SOURCES and add a checker

---

docs/lua-records/functions.rst
pdns/lua-record.cc

Fixes a potential uncaught exception and adds docs on all variables available to the LUA record.
I have:

Lua records fixes

---

docs/settings.rst
pdns/common_startup.cc
pdns/nameserver.cc
pdns/tcpreceiver.cc

It turns out the query-local-address6 settings merging was not released in 4.3.0.
We're now delaying both removals to keep everything simple for the users.
I have:

auth: delay local-ipv6 and query-local-address6 removal to 4.5.0 together

---

pdns/dbdnsseckeeper.cc
pdns/dnsseckeeper.hh
pdns/dnssecsigner.cc

There was an unnecessary soa lookup which resulted in a large number of extra backend queries.
I have:

auth: Speedup presigned signature lookups.

---

docs/settings.rst
pdns/common_startup.cc
pdns/pdnsutil.cc
regression-tests.api/test_Zones.py

This might reduce the number of lawyers emailing the powerdns security contacts in error.
I have:

auth: change "misconfigured" SOA MNAME to not mention powerdns and be RFC6761 compliant

---

pdns/lwres.cc
pdns/lwres.hh
pdns/pdns_recursor.cc
pdns/rec-carbon.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc.hh
pdns/recursordist/test-syncres_cc1.cc
pdns/recursordist/test-syncres_cc10.cc
pdns/recursordist/test-syncres_cc2.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc5.cc
pdns/recursordist/test-syncres_cc6.cc
pdns/recursordist/test-syncres_cc7.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/recursordist/test-syncres_cc9.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/ws-recursor.cc

Instead of throttling explicitly on ServFail and Refused, do it for all rcodes except `NoError` and `NXDomain`, with the exception of `FormError` which is handled earlier.
Also throttle servers sending data that we fail to parse.
This PR is huge because it adds a `LWResult::Result` type to stop dealing with numerical values all over the place, sorry about that.
Need more tests if the general idea is deemed correct.
I have:

rec: Throttle servers sending invalid data and rcodes

---

pdns/dnsdistdist/docs/reference/config.rst

Fix typo in dnsdist StatNode documentation
I have:

Fix typo in dnsdist StatNode documentation

---

pdns/recursordist/docs/nod_udr.rst

Fix typo in Recursor UDR documentation
I have:

Fix typo in Recursor UDR documentation

---

docs/lua-records/functions.rst

The example called the createReverse function on a PTR record for an
IPv6 address instead of the createReverse6 - which when mindlessly
copy and pasted resulted in a lengthy servfail error
I have:

docs: fix lua reverse example for IPv6 records

---

docs/settings.rst
modules/bindbackend/bindbackend2.cc
modules/bindbackend/bindbackend2.hh
pdns/backends/gsql/gsqlbackend.cc
pdns/backends/gsql/gsqlbackend.hh
pdns/common_startup.cc
pdns/dnsparser.cc
pdns/dnsparser.hh
pdns/pdnsutil.cc
pdns/test-zoneparser_tng_cc.cc
pdns/zoneparser-tng.cc
pdns/zoneparser-tng.hh

When upgrading to a release supporting new record types, all existing database entries using the TYPExxx format stop working. This prevents testing of a "master" release while preserving compatibility with a production database.
Makes TYPExxx work by always sending them through UnknownRecordContent and deserialising that using the specific QType handler.
I have:

gsql,bind: allow seamless serving of newly-supported TYPExxx records

---

modules/lmdbbackend/lmdbbackend.cc

Improves on #9646
(but does not fix the 'serial 0 means the domain is missing' problem in #9470)
I have:

auth lmdb: fill di.backend in getUnfreshSlaveInfos and getAllDomains

---

modules/bindbackend/bindbackend2.cc

Makes rediscover detect changes to the `type` property of zones in named.conf. 
Without this a restart is required for a change to the kind of a zone to apply (f.e. `native` -> `master`).
I have:

auth: bindbackend: 'rediscover' changes to 'type'

---

modules/bindbackend/bindbackend2.cc
modules/bindbackend/bindbackend2.hh

safeGetBBDomainInfo() was called for every record to get the, already known, zone name.
I have:

pdns: bind-backend speedup feedRecord()

---

pdns/misc.cc

Fixes compiler warning
misc.cc:1513:12: warning: comparison of integer expressions of different signedness:
size_t {aka long unsigned int} and int [-Wsign-compare]
I have:

pdns: setPipeBufferSize - Fix comparison sign mismatch

---

pdns/dbdnsseckeeper.cc
pdns/ueberbackend.cc

Should clean up:
```
>>>     CID 1435947:  Uninitialized members  (UNINIT_CTOR)
>>>     Non-static class member "d_qtype" is not initialized in this constructor nor in any functions that it calls.
>>>     CID 1030015:  Uninitialized members  (UNINIT_CTOR)
>>>     Non-static class member "zoneId" is not initialized in this constructor nor in any functions that it calls.
```
and:
```
dbdnsseckeeper.cc:621:13: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
rrsig = std::move(getRR<RRSIGRecordContent>(dzr.dr));
```
I have:

auth: cleanup warnings in ueberbackend, dbdnsseckeeper

---

pdns/lua-recursor4.cc
pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursor_cache.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc5.cc
pdns/recursordist/test-syncres_cc6.cc
pdns/recursordist/test-syncres_cc7.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/recursordist/test-syncres_cc9.cc
pdns/secpoll-recursor.cc
pdns/syncres.cc
pdns/validate.cc
pdns/validate.hh

This is especially useful after the fact, when the Bogus state is retrieved from a cache and we don't have any clue left as to how we ended up with that state.
Documentation is missing, and I wouldn't be surprised to see some regression tests fail.
I have:

rec: Move to several distinct Bogus states, for easier debugging

---

modules/lmdbbackend/lmdbbackend.cc

`pdnsutil delete-rrset` and other operations caused empty values to appear in LMDB databases (fixed in #9664).
Those empty values cause get() to (re)read freed memory.
This PR turns the valgrind warnings + a parse error into a vector out of range exception.
I have:

auth lmdb: avoid reading freed memory

---

pdns/pdns_recursor.cc
regression-tests.recursor-dnssec/test_Lua.py

The logic to let a RPZ match override the answers generated from Lua was broken, ignoring the generated values.
This PR needs regression tests so we don't break that again.
I have:

rec: Fix the processing of answers generated from gettag

---

pdns/syncres.cc

The is an optimization, avoiding hitting maxdepth followeed by no-QM fallback.
I have:

rec: If a.b.c CNAME x.a.b.c is encoutered, switch off QM for x.a.b.c resolve

---

pdns/lua-recursor4.cc
pdns/rec-carbon.cc
pdns/rec_channel.hh
pdns/rec_channel_rec.cc
pdns/recursordist/docs/lua-scripting/statistics.rst
pdns/ws-recursor.cc

This can be used to specify names that are structured using Prometheus
conventions. If no name Prometheus name is given, do a more thorough
conversion to a name Prometheus likes by replacing any non-alnum
char by an underscore.
I have:

rec: Allow to specify a name in getMetric() that is used for Prometheus export only.

---

pdns/common_startup.cc
pdns/communicator.hh
pdns/dynhandler.cc
pdns/dynhandler.hh
pdns/receiver.cc
pdns/slavecommunicator.cc
regression-tests.nobackend/counters/expected_result

This allows some insight into what the auth is doing
I have:

Auth: Add pdns_control command to the the list of XFR domains in queue

---

pdns/rec_channel_rec.cc
pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh
pdns/recursordist/test-negcache_cc.cc

I'm assuming the test always finishes within 1 second...
Fix tested by waiting in a loop until the second is *almost* over and then run the test.
While there zap a redundant test: it's legal to call `free(nullptr)`.
I have:

rec: the clock can tick while the negcache test is running.

---

modules/tinydnsbackend/tinydnsbackend.cc

This patch prevents tinydns from providing same domain twice when listing all domains. This can happen if there is same SOA record more than once.
Fixes #9173 
I have:

tinydnsbackend: Ignore duplicate SOA in getAllDomains()

---

docs/http-api/swagger/authoritative-api-swagger.yaml

Signed-off-by: Kevin P. Fleming <kevin@km6g.us>

TSIG Keys are also used for DNSUPDATE, so update API docs

---

pdns/backends/gsql/gsqlbackend.cc

It was impossible to edit/upgrade now supported TYPExxx records, since the old TYPExxx variant was never deleted in replaceRRSet(). This pull will slow down updates when upgrade-unknown-types is enabled. There is already a warning about the performance impact of this option in the documentation.
I have:

Auth: make it possible to replace now supported TYPExxx records

---

pdns/syncres.cc

rec: Backport 9680 to rec 4.3.x: If a.b.c CNAME x.a.b.c is encoutered, switch off QM

---

pdns/syncres.cc

rec: Backport 9680 to rec 4.4.x: If a.b.c CNAME x.a.b.c is encoutered, switch off QM

---

pdns/dnsdist-lua.cc
pdns/dnsdist-lua.hh
pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-lua-web.cc
pdns/dnsdistdist/dnsdist-web.hh
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/index.rst
pdns/dnsdistdist/docs/reference/web.rst
pdns/dnsdistdist/incfiles
pdns/sstuff.hh
regression-tests.dnsdist/test_API.py

dnsdist: Implement Lua custom web endpoints

---

docs/backends/geoip.rst
modules/geoipbackend/geoipbackend.cc
modules/geoipbackend/geoipbackend.hh
modules/geoipbackend/regression-tests/custom-mapping-txt-resolution/command
modules/geoipbackend/regression-tests/custom-mapping-txt-resolution/description
modules/geoipbackend/regression-tests/custom-mapping-txt-resolution/expected_result
regression-tests/backends/geoip-master

If for example you want a per country granularity, but still want to
group by custom regions: uk, fr, be -> eu-central, pt, es -> eu-south;
you need to to use %cc and create identical country records. It means
you zones file can become huge and powerdns does not like it too much.
For a user to have a custom mapping without the need to rewrite the
GeoIP database, with this commit, he/she can specify a custom mapping,
so if we get from the GeoIP database fr, we will look in the custom
mapping and find eu-central. So we only need to create the eu-central
record and it will be used by for uk, fr and be as per our first
example.
Definition of mapping_lookup_formats or custom_mapping at the domain
level has priority, but if not defined the global config will be used
as default.
The custom …

geoipbackend: accept custom lookup mapping

---

Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor
pdns/recursordist/configure.ac

This requires setting DOCKER_FAKE_RELEASE to YES as a build arg (on the docker hub). Combined with automatic builds based on tags (also on the docker hub) will lead to binaries with the correct version number
I have:

Allow setting a fake-ish version number when building release images

---

pdns/mastercommunicator.cc
pdns/slavecommunicator.cc
pdns/tcpreceiver.cc

Decrease the verbosity of AXFR and IXFR in the logs
Inspired by and successor of #9658 This pull will change the log levels for both, primary and secondary.
Closes #9658 #9514
Most XFR related events are now logged at notice level. And will not show up in the logs at the default log level.
This is the only (non error) message still logged at warning level on the primary:
```
Nov 09 13:33:31 AXFR of domain 'example.com' initiated by 127.0.0.2:36543
```
The secondary is only showing this at warning level:
```
Nov 09 13:33:31 AXFR done for 'example.com', zone committed with serial number 2005092501
```
You can argue about these two lines, but in my opinion it is important to not completely hide XFR at default log level.
I have:

Pdns AXFR, IXFR loglevels

---

pdns/mtasker.hh
pdns/pdns_recursor.cc
pdns/syncres.hh

The following scenario can occur. Multiple concurrent clients doing the same query A
are needed to trigger it:
1. Incoming request A, which has a need for request X
2. Add request X to chain because we already have an identical outstanding request
3. We receive the reply for X
4. We process the chain
5. In the meantime a new request for X that's identical is added to the chain
6. The added id in step 5 is not being processed anymore -> timeout
This can happen if request X has TTL 0, otherwise the record cache would have a hit.
Should fix timeouts seen for auth serving records with TTL 0. I suspect #9208 is a case of that as increasing the number of threads avoids the issue. Another workaound it to set `override-minimum-ttl`.
I have:

rec: Do not add request to a wait chain that's already processed or being processed

---

pdns/iputils.cc
pdns/iputils.hh
pdns/pdns_recursor.cc

Use OpenBSD's reliable local UDP port randomization instead of a home-grown mechanism and retry on sendmsg EAGAIN. The latter can and does happen on non-blocking UDP sockets on OpenBSD.
This makes running multiple recursor threads on OpenBSD much more reliable on heavy load. Previously
you would see quite some EAGAINs (leading to reply loss) on e.g. a dnsperf load test with threads > 1.
The arbitrary max loop count is a bit unsatisfactory....
There might be more systems that return EAGAIN once in a while on sendmsg(2) on a non-blocking UDP socket.
Apology for the white-space changes.
I have:

rec: two OpenBSD improvemenst wrt UDP sockets: port randomization and EGAIN errors

---

pdns/pdns_recursor.cc

Backport of #9697, minus metric.
I did not test this one (I did test the 4.4 backport).
I have:

rec-4.3: do not send overly long NOD lookups

---

pdns/pdns_recursor.cc

backport of #9697, minus metric
I have:

rec-4.4: do not send overly long NOD lookups

---

pdns/pdns_recursor.cc
regression-tests.recursor-dnssec/test_DNS64.py

When the requested qname is a CNAME to a second CNAME, the CNAME loop detection might get incorrectly triggered because the CNAMEs were already present in the vector of result records.
Backport of #9696 to rel/rec-4.4.x.
I have:

rec-4.4.x: Avoid a CNAME loop detection issue with DNS64

---

pdns/dnsdist-ecs.cc
pdns/dnsdist-ecs.hh
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-lua-bindings-dnscrypt.cc
pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
pdns/dnsdistdist/dnsdist-lua-bindings-protobuf.cc
regression-tests.dnsdist/test_Advanced.py

Since LuaWrapper enforces const-correctness, a const (shared) pointer
to an object can only read members and call const methods.
Therefore we have to take care to use the const qualifier during
registration of constant lambda Lua function bindings.
An example where the absence of the const qualifier was problematic is
LuaRule, which invokes its user provided match function with a constant
DNSQuestion object. Because the functions of DNSQuestion lacked
the const qualifier (e.g. getTag()), it was not possible to call them
from within the LuaRule match function.
I have:

dnsdist: Improve const-correctness of Lua bindings

---

pdns/dnsdistdist/docs/reference/dnsnameset.rst

The `newDNSNameSet()` function has no name argument.
I have:

dnsdist: Fix typo in DNSNameSet documentation

---

pdns/dnsdist-web.cc

fixes a typo in dnsdist prometheus metrics 
see #9728 
I have:

fix a typo in prometheus metrics dnsdist_frontend_tlshandshakefailures #9728

---

pdns/lua-recursor4.cc
pdns/rec-carbon.cc
pdns/rec_channel.hh
pdns/rec_channel_rec.cc
pdns/recursordist/docs/lua-scripting/statistics.rst
pdns/ws-recursor.cc

rec: Backport 9651 to rec 4.4.x: Allow to specify a name in getMetric() that is used for Prometheus export only.

---

pdns/mtasker.hh
pdns/pdns_recursor.cc
pdns/syncres.hh

The following scenario can occur. Multiple concurrent clients doing the same query A
are needed to trigger it:
1. Incoming request A, which has a need for request X
2. Add request X to chain because we already have an identical outstanding request
3. We receive the reply for X
4. We process the chain
5. In the meantime a new request for X that's identical is added to the chain
6. The added id in step 5 is not being processed anymore -> timeout
This can happen if request X has TTL 0, otherwise the record cache would have a hit.
(cherry picked from commit c647a254a0f863aabeaea9d33f673afa26c60457)
Backport of #9707 
I have:

rec: Backport to 4.3.x: Do not add request to a wait chain that's already processed or being processed.

---

pdns/mtasker.hh
pdns/pdns_recursor.cc
pdns/syncres.hh

The following scenario can occur. Multiple concurrent clients doing the same query A
are needed to trigger it:
1. Incoming request A, which has a need for request X
2. Add request X to chain because we already have an identical outstanding request
3. We receive the reply for X
4. We process the chain
5. In the meantime a new request for X that's identical is added to the chain
6. The added id in step 5 is not being processed anymore -> timeout
This can happen if request X has TTL 0, otherwise the record cache would have a hit.
(cherry picked from commit c647a254a0f863aabeaea9d33f673afa26c60457)
Backport of #9707 
I have:

rec: Backport to 4.4.x: Do not add request to a wait chain that's already processed or being processed.

---

regression-tests.auth-py/test_LuaRecords.py

While I cannot reproduce Travis' intermittent failures locally, I hope this might help.
I have:

auth LUA tests: give healthchecker more time

---

modules/lmdbbackend/lmdbbackend.cc
pdns/pdnsutil.cc

This changes the serial from `0` to the correct value in a domain-specific API call such as `/api/v1/servers/localhost/zones/example.com.`.
`/api/v1/servers/localhost/zones` yields the right serial without this patch, and I see that `void LMDBBackend::getAllDomains(vector<DomainInfo> *domains, bool include_disabled)` uses more 'direct' code to get the serial. PRing this as draft until I figure out which code is right.
I have:

lmdb: fill di.serial (code stolen straight from gsqlbackend)

---

pdns/resolver.cc

Because `Exiting because communicator thread died with STL error: Creating local resolver socket for ::: Protocol not supported` is too hard to read.
I have:

auth: put quotes around some IPs to make messages easier to read

---

pdns/packethandler.cc
pdns/packethandler.hh
pdns/ueberbackend.cc

This pull will increase uncached NXDOMAIN performance by roughly 10% in single backend setups. 
getSOAUncached() is used to figure out which backend is responsible for the before and after name. But in single backed setups this is obvious and does not require additional backend queries. 
Commit 1-3 are improvements, commit 4 is clean-up and is not changing functionality.
I have:

auth: nxdomain performance

---

pdns/dnsname.hh
pdns/packethandler.cc

A misplaced 'const' prevented it from being called, making every move of a DNSName into a full copy.
Introduced in d720eb8add5ebda11867e8b404125e0b68ed2911.
I have:

Fix the DNSName move assignment operator

---

pdns/recursordist/ednsextendederror.cc

`pdns_string_view` falls back to a regular string there, so there was an ambiguity on which overloaded function to call.
I have:

rec: Fix getEDNSExtendedErrorOptFromString() on CentOS 6

---

pdns/lwres.hh
pdns/pdns_recursor.cc
pdns/syncres.cc
pdns/syncres.hh

Instead of treating this like an unrecoverable network error and trying the next server, let's switch to TCP instead. This might
prevent a DoS by making us try every single servers and failing, and will make the spoofing attempt a bit much harder.
Could use a regression test.
I have:

rec: Switch to TCP in case of spoofing (near-miss) attempts

---

pdns/common_startup.cc
pdns/common_startup.hh

 auth-4.4.x: fix rounding inaccuracy in latency statistics

---

pdns/packethandler.cc
pdns/slavecommunicator.cc
pdns/tcpreceiver.cc
pdns/tcpreceiver.hh

After #9688 the axfr logs are a lot less extensive. This pull adds the remote address to the line pdns logs at default level.
I have:

auth: add remote to default axfr logging

---

pdns/syncres.cc
pdns/syncres.hh

Not chasing CNAMEs while we are only trying to determine where the next zone cut lies helps with some broken domains.
I have:

rec: Do not chase CNAME during qname minization step 4

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_Spoofing.py

This removes the second, useless argument to `SpoofAction`, fixing #9783. Additionally, I've added a test for `SpoofAction` setting the TTL.
I have:

dnsdist: Remove useless second argument for `SpoofAction`

---

m4/systemd.m4
pdns/Makefile.am
pdns/recursordist/Makefile.am

This is mostly a hack for systemd version <240 so using virtual hosting
on Ubuntu Bionic and EL7 does not lead to surprises.
This Commit explicitly adds the `--socket-dir` to the invocation of the
unit. Any users who want to use their own runtimedirs should use a
drop-in unit overriding ExecStart. I believe this does not validate the
principle of least surprise for those using the PowerDNS provided
packages and virtual hosting.
Fixes #9485
I have:

Ensure socket-dir matches runtimedir on old systemd

---

pdns/recursordist/test-syncres_cc5.cc
pdns/syncres.cc

If somehow the RRSIG indicating that the answer is expanded from a wildcard (label count smaller than the number of labels in the name) went _after_ the NSEC we need, we forgot to gather that NSEC.
It might have been an issue for downstream validation (we do gather them a second time later for our own validation) since the client would not have received them.
I have:

rec: Fix the gathering of denial proof for wildcard-expanded answers

---

docs/upgrading.rst
pdns/common_startup.cc
pdns/common_startup.hh

The latency statistics are off by a lot. This pull is changing the type of the avg_latency variable from int to double to avoid rounding issues in te calculation.
I have:

auth: fix rounding inaccuracy in latency statistics

---

m4/systemd.m4
pdns/Makefile.am
pdns/recursordist/Makefile.am

auth-4.4.x: Ensure socket-dir matches runtimedir on old systemd

---

pdns/pdns_recursor.cc

Better use the more detailed states now that we have them :)
I have:

rec: Log the exact Bogus state when 'dnssec-log-bogus' is enabled

---

pdns/bpf-filter.cc
pdns/dnsdist-console.cc
pdns/dnsdist-dynblocks.hh
pdns/dnsdist-dynbpf.cc
pdns/dnsdist-dynbpf.hh
pdns/dnsdist-lua.cc
pdns/dnsdist-web.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-dynblocks.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc
pdns/dnsname.hh
pdns/statnode.cc
pdns/statnode.hh
pdns/test-dnsname_cc.cc
regression-tests.dnsdist/test_DynBlocks.py

This PR is a work-in-progress, but the idea is to export the top 20 dynamic blocks for each `reason`, for SMT and NMG dynamic blocks. Since scanning every single entry might take a long time, these metrics are cached for 60s, which is currently hardcoded but could easily be made configurable.
The current metrics looks like this:
```
dnsdist_dynblocks_nmg_top_offenders{reason="Exceeded query rate",netmask="127.0.0.1/32"} 6
dnsdist_dynblocks_smt_top_offenders{reason="Pseudo-Random Subdomain Attack",suffix="prsd.powerdns.com."} 0
```
@SrX @wojas I'm pretty sure I'm holding the prometheus metrics wrong, feedback welcome :-)
We could also expose them to the API. It currently can request all dynamic block entries which is very slow, so exposing the top N would likely make sense there as well. …

dnsdist: Add prometheus metrics for top Dynamic Blocks entries

---

regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_Advanced.py
regression-tests.dnsdist/test_Trailing.py

Hopefully it might help with the transient failures of the trailing data regression test we are recurrently experiencing in CI.
I have:

dnsdist: Clean up the internal queues use for self-answered and trailing test responses

---

Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor

.. because otherwise at least two security scanners will dig up every CVE since PowerDNS 1.0 and claim the image is vulnerable to it
I have:

dockerfiles: do not claim equivs-dummy is sourced from pdns

---

modules/geoipbackend/geoipbackend.cc

(via Kees Monshouwer)
I noticed this failure while I was migrating geoip tests from Travis CI to Circle CI. We never noticed on Travis because the unbound-host there is too old to have qname minimisation, and thus it did not do the queries that ruin our cache.
I have:

auth geoip: set netmask on all string formatting types

---

pdns/syncres.cc
pdns/syncres.hh

(cherry picked from commit 7373cea835239f1b18a72000821bb17b516d954b)
Backport of #9790
I have:

rec: backport 9790 to rec-4.3.x: Do not chase CNAME during qname minization step 4

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst

TTL 0 causes a lot of extra needless work both for recursor and auth. 
I have:

Switch default TTL override to 1.

---

pdns/pdns_recursor.cc
pdns/ws-recursor.cc

At this point we already have several threads so calling `exit()` will cause problem by trying to destruct objects that are in use
by other threads, so call `_exit()` instead.
Also mention the web server in the error message so that the root cause is easier to identify.
Fixes #9808.
I have:

rec: Handle failure to start the web server more gracefully

---

pdns/recursor_cache.cc
pdns/recursordist/test-recursorcache_cc.cc
pdns/recursordist/test-syncres_cc9.cc

It turns out to be quite difficult to make us accept a record that we already have in cache, thanks to sanitization, but let's make
sure that we will not replace a valid entry with a Bogus one if that happens.
It might happen for SOA records, and for DS records when the TTL of the corresponding NS records is shorter than the TTL of the DS.
I have:

rec: Keep a cached, valid entry over a fresher Bogus one

---

pdns/syncres.cc
pdns/syncres.hh

(cherry picked from commit 7373cea835239f1b18a72000821bb17b516d954b)
Backport of #9790
I have:

rec: backport 9790 to rec-4.4.x: Do not chase CNAME during qname minization step 4

---

pdns/lua-recursor4.cc
pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursor_cache.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc5.cc
pdns/recursordist/test-syncres_cc6.cc
pdns/recursordist/test-syncres_cc7.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/recursordist/test-syncres_cc9.cc
pdns/secpoll-recursor.cc
pdns/syncres.cc
pdns/validate.cc
pdns/validate.hh

Backport of #9597 to rel/rec-4.4.x, with an additional commit to export the sum of all the new 'Bogus*' metrics as the existing 'Bogus' metric, to prevent messing up with existing dashboards.
At second thought, I think it would actually make sense to forward port that commit :-)
I have:

rec-4.4.x: Move to several distinct Bogus states, for easier debugging

---

pdns/syncres.cc
pdns/syncres.hh

(cherry picked from commit 6d1218188747bdeb9f8fddc52a0499a8d9490ff4)
Backport of #9807 
I have:

rec: Backport 9807 to rec 4.4.x: Untangle the validation/resolving qnames and qtypes

---

pdns/syncres.cc
pdns/syncres.hh

There was a confusion in `SyncRes::validateRecordsWithSigs` between the name and type we are currently resolving, and the name and type we are validating. It might have led to a spurious DNSSEC validation failure in some weird corner cases.
Could use some unit tests.
I have:

rec: Untangle the validation/resolving qnames and qtypes

---

m4/systemd.m4
pdns/Makefile.am
pdns/recursordist/Makefile.am

rec-4.4.x: Ensure socket-dir matches runtimedir on old systemd

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/advanced/acl.rst
pdns/dnsdistdist/docs/reference/config.rst

Adds the ability to set (and reload) the dnsdist ACL from a file. File is parsed in exactly the same way as in recursor, and also errors in the file leave the previous ACL untouched.
I have:

dnsdist: add ability to set ACL from a file

---

pdns/Makefile.am
pdns/speedtest.cc
pdns/uuid-utils.cc
pdns/uuid-utils.hh

Since Boost 1.67.0 the default UUID generator is cryptographically strong, which is neat but quite slower. Since we don't need that, just use the fastest version.
I have:

UUID: Use the non-cryptographic variant of the boost::uuid

---

pdns/packethandler.cc

A notify from trusted-notification-proxy was still producing log messages at Error level.
I have:

auth: don't log trusted-notification-proxy notify at error level

---

pdns/packethandler.cc

auth-4.4.x: don't log trusted-notification-proxy notify at error level

---

pdns/validate.cc

It turns out that computing those SHA1 hashes is far from cheap, and in almost all cases the salt and iterations are identical
so no need to compute them several times.
I have:

rec: Use a short-lived NSEC3 hashes cache for denial validation

---

pdns/dnsdistdist/doh.cc

This is done by implementing a per-thread table of DoH connections, keyed on the underlying file descriptor, since we don't have access to the `h2o_conn_t` object but only to the `h2o_socket_t` when the connection is first established (`h2o_socket_read_start()` callback) or terminated (`on_close` callback of the socket).
This also makes it possible to use a `std::shared_ptr` instead of our custom reference counting, since we keep an entry in the table for the duration of the connection and don't need to rely on h2o's raw pointer anymore to pass our data.
I have:

dnsdist: Add per connection queries count and duration stats for DoH

---

docs/http-api/swagger/authoritative-api-swagger.yaml

Rather than listing *some* of the ignored fields, and thus needing to keep that list up to date as fields are added to the zone
structure, instead list the fields that putZone actually uses to modify the zone.
Also remove the reference to metadata, since metadata is modified via other API operations.

Clarify description of putZone API operation.

---

modules/lmdbbackend/lmdbbackend.cc

Prevents errors of the following kind from occurring if LMDBBackend::get should throw an exception for some other reason:
```
Exception building answer packet for example.com/SOA (vector::_M_range_check: __n (which is 1410) >= this->size() (which is 1)) sending out servfail
```
I have:

auth-4.4.x: clear the LMDB set state when performing a new lookup or list to prevent corruption cases

---

pdns/pdns_recursor.cc
pdns/recursordist/Makefile.am
pdns/recursordist/test-syncres_cc.cc
pdns/sillyrecords.cc
regression-tests.recursor/runtests

This PR picks up the fixes of #8878, without actually enabling UBSAN on our CI for now.
Closes #8878.
I have:

rec: A few UBSAN-related fixes

---

builder-support/dockerfiles/Dockerfile.target.centos-6

This avoids yum breaking on machines without v6.
I have:

el6 docker builds: prefer v4 resolution

---

pdns/dnslabeltext.rl
pdns/dnswriter.cc
pdns/misc.hh
pdns/rcpgenerator.cc
pdns/rcpgenerator.hh
pdns/test-dnsrecords_cc.cc
pdns/test-rcpgenerator_cc.cc

There were multiple issues. With this commit, we *always* store the
bytes that are represented by the option. To do this, we needed to
properly parse RFC 1035 character-strings. This is now done with a
conversion of the ABNF from draft-ietf-dnsop-svcb-https-02 to ragel.
The resulting function could be used as a starting point for a better
TXT storage format.
Fixes #9829
I have:

SVCB: Correctly parse and print unknown params

---

docs/appendices/compiling.rst
docs/appendices/types.rst
docs/backends/generic-mysql.rst
docs/backends/geoip.rst
docs/common/api/endpoint-statistics.rst
docs/dnssec/operational.rst
docs/dnsupdate.rst
docs/http-api/cryptokey.rst
docs/http-api/index.rst
docs/modes-of-operation.rst
docs/performance.rst
docs/settings.rst

This removes settings that no longer exist since 4.2.0, and removes any
statements of settings and docs that were added or changed in 4.2.0 and below.
I have:

Remove all documentation irrelevant after 4.4.0

---

.dockerignore
Dockerfile-recursor
Makefile.docker
dockerdata/recursor.conf
dockerdata/startup.py

This will make dockerhub actually build 4.4 images once we tag the next version.
I have:

Port the dockerfiles from master to rec-4.4

---

pdns/dnsdistdist/docs/advanced/tuning.rst

dnsdist: Fix typo in tuning documentation
I have:

dnsdist: Fix typo in tuning documentation

---

pdns/dbdnsseckeeper.cc
pdns/decafsigners.cc
pdns/dnssecinfra.cc
pdns/dnssecinfra.hh
pdns/opensslsigners.cc
pdns/pdnsutil.cc
pdns/pkcs11signers.cc
pdns/pkcs11signers.hh
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/sodiumsigners.cc
pdns/test-signers.cc
pdns/validate.cc

We do not always need a shared pointer, and that saves memory barriers when we don't.
I have:

Return a unique_ptr instead of a shared one for DNSCryptoKeyEngine

---

pdns/dnsdist.cc
pdns/dnsdistdist/dnsdist-backend.cc

There was a lock starvation issue when removing a server with more than one socket in use (`sockets` greater than 1 on the corresponding `newServer` directive), because the mutex protecting the sockets array would never be released long enough by the responder thread to allow the thread stopping the server to acquire it.
This commit fixes that by marking the server as stopped right away, before acquiring the lock, and also making sure that the responder thread is woken up regularly (every second, even without any query to process) and that it checks whether the server has been stopped just after that.
The issue was introduced in be55a20ce9bb7140071279d70bcb460f1f2b7b7d, and backported to 1.5.1 in f0d48318cce0dd80ae73c529362bdb2921d8c5c9.
I have:

dnsdist: Fix a hang when removing a server with more than one socket

---

pdns/mtasker.hh
pdns/recursordist/configure.ac

Tests OK on Intel MacOS. Apple Silicon shows a few issues which I am investigating.
I have:

Enable address sanitizer on MacOS

---

pdns/slavecommunicator.cc

Correct the wording used in log entries created by zone xfr errors.
A sample of the current word is as follows:
```
unable to xfr zone (ResolverException): AXFR chunk error: Server Failure (This was the first time. Excluding zone from slave-checks until 166552654)
unable to xfr zone (ResolverException): AXFR chunk error: Server Failure (This was the 2th time. Excluding zone from slave-checks until 166552654)
unable to xfr zone (ResolverException): AXFR chunk error: Server Failure (This was the 3th time. Excluding zone from slave-checks until 166552654)
unable to xfr zone (ResolverException): AXFR chunk error: Server Failure (This was the 4th time. Excluding zone from slave-checks until 166552654)
unable to xfr zone (ResolverException): AXFR chunk error: Server Failure (This was the 5th …
```

Reword zone xfr log message to remove ordinal number naming errors.

---

pdns/recursordist/docs/settings.rst

Pending any further discussion on whether this is the -right- default, the docs should at least reflect what we shipped in 4.4 and below.
I have:

rec docs: correct local-address default

---

pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/test-recursorcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc2.cc
pdns/recursordist/test-syncres_cc7.cc
pdns/reczones.cc
pdns/syncres.cc
pdns/syncres.hh

When we are looking for a `DS`, we want to do the non-`CNAME` cache check first because we can actually have a `DS` (from the parent zone) AND a `CNAME` (from the child zone), and what we really want is the `DS`.
<strike>Note that this works because we do compute the zone cuts first, so we will have the `DS` (or denial of) in cache. We will need to be careful about that if we stop doing that, since the `DS` entry might expire while the `CNAME` one is still valid.</strike> I was mistaken, this PR makes the situation better when the `DS` entry (or denial of) is still there but doesn't work when it has expired and the `CNAME` hasn't.
<strike>Still need a unit test.</strike>
Fixes #9621.
I have:

rec: Lookup DS entries before CNAME entries

---

pdns/bpf-filter.cc
pdns/bpf-filter.hh
pdns/dnsdist-dynbpf.cc
pdns/dnsdist-dynbpf.hh
pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-dynblocks.cc
pdns/dnsdistdist/docs/advanced/ebpf.rst
pdns/dnsdistdist/docs/guides/dynblocks.rst
pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc

This PR will use the default `BPF` filter, if any, to apply dynamic block generated via a `DynBlockRulesGroup`.  `eBPF` blocks are applied in kernel space and are much more efficient than user space ones.
We still also insert a regular dynamic block so that any failure to get the `eBPF` working will fall back to user space blocking automatically. The metrics will also transparently sum the hits from the `eBPF` block and the regular one.
<strike>This PR is based on top of #9756 so only the last commit matters here, and the PR will need to get rebased once #9756 has been merged.</strike>
Closes #6763.
I have:

dnsdist: Use an eBPF filter for Dynamic blocks when available

---

pdns/dnsname.hh

Tested for all three products by building and running unittests.
I have:

MacOS (both Intel and arm64) and OpenBSD have no issues any more with boost::containter::string

---

m4/pdns_check_pthread_np.m4
pdns/recursordist/configure.ac

The previous version did not include `pthread.h` and thus could not find the symbols on some systems, including at least Debian Buster.
I have:

autoconf: correctly detect pthread symbols

---

pdns/protozero.hh

The existing Protocol Buffer code used to do that, so existing receivers might expect that field to be present.
And yes, this time I _did_ make sure to run every single Protocol Buffer and dnstap related tests :)
I have:

rec: Set the Protocol Buffer 'inBytes' field for zero-length messages

---

pdns/dnsdistdist/libssl.cc
regression-tests.dnsdist/test_TLS.py

Otherwise `SSL_get_servername()` only returns true when the session has been freshly established, and will return `nullptr` when it is resumed.
I have:

dnsdist: Fix SNI on resumed sessions by acknowledging the name sent by the client

---

pdns/tcpreceiver.cc
regression-tests/backends/gsqlite3-master
regression-tests/backends/gsqlite3-slave

direct-dnskey in AXFR-out was misbehaving like this:
| direct-dnskey | presigned | signed|
|-|-|-|
|  yes | remove all DNSKEY, CDNSKEY, CDS | remove all CDNSKEY, CDS / add backend DNSKEY|
| no | add bakend CDNSKEY, CDNSKEY, CDS | add backend DNSKEY, CDNSKEY, CDS  |
This pull fixes direct-dnskey behaviour and will make sure backend (C)DNSKEY and CDS records use the proper ttl in AXFR-out.
Fixes #9868  
I have:

auth: fix direct-dnskey in AXFR-out

---

pdns/test-dnscrypt_cc.cc

MacOS clang++ 12 with asan does not like to access a vector of bytes
outside it's begin()..end(), even thouh we assured there is capacity.
So make sure the size is set before groping inside the vector.
I have:

dnsdist: Appease clang++ 12 asan on MacOS

---

regression-tests/tests/00dnssec-grabkeys/command

unbound-host fires off the _ta query and does not wait for the answer.
This means that the response sometimes ends up with sdig, which was
not expecting it, breaking tests.
This PR MUST be CI checked.
I have:

auth testing: disable unbound's trust anchor signaling

---

pdns/dnsbulktest.cc
pdns/ws-auth.cc
pdns/ws-auth.hh
pdns/zone2sql.cc

The WebServer one might be controversial;, since it requires me to pull in ``webserver,hh`` in the `ws-auth.hh` file. THat is becausse `unique_ptr` woiuld otherwise complain:
```
/usr/include/c++/v1/memory:2335:19: error: invalid application of 'sizeof' to an incomplete type 'WebServer'
static_assert(sizeof(_Tp) > 0,
^~~~~~~~~~~
/usr/include/c++/v1/memory:2652:7: note: in instantiation of member function 'std::__1::default_delete<WebServer>::operator()' requested here
__ptr_.second()(__tmp);
^
/usr/include/c++/v1/memory:2606:19: note: in instantiation of member function 'std::__1::unique_ptr<WebServer, std::__1::default_delete<WebServer> >::reset' requested here
~unique_ptr() { reset(); }
^
./ws-auth.hh:74:7: note: in instantiation of member function 'std::__1::unique_ptr<WebServer, …
```

auth: Fix a few code ql warnings

---

pdns/dnsdistdist/libssl.cc
regression-tests.dnsdist/test_TLS.py

Otherwise `SSL_get_servername()` only returns true when the session has been freshly established, and will return `nullptr` when it is resumed.
(cherry picked from commit 767a9d3a727a4a3b4073f01fab4b2c1d7c55d73e)
Backport of #9921 on rel/dnsdist-1.5.x.
I have:

dnsdist-1.5.x: Fix SNI on resumed sessions by acknowledging the name sent by the client

---

pdns/calidns.cc
pdns/recursordist/test-syncres_cc7.cc
pdns/test-dnsdist_cc.cc

As seen with clang on both OpenBSD and MacOS. Only really interesting is the `msg_iovlen` one, which indeed Posix defines as an `int`.
I have:

Bunch of signed vs unsigned warnings

---

modules/lmdbbackend/lmdbbackend.cc

pdnsutil does not expose this code anywhere; this will become tested when we expand API testing to other backends than just SQLite3.
I have:

auth lmdb: fix typo from a testing attempt

---

configure.ac
m4/pdns_check_flex.m4
m4/pdns_check_lmdb.m4
m4/pdns_enable_remotebackend_zeromq.m4
m4/tm-gmtoff.m4
pdns/dnsdistdist/configure.ac
pdns/recursordist/configure.ac

This bumps the minimal autoconf requirement to 2.69 as well. This
version is on Ubuntu 16.04 (EOL due in 3 months) and CentOS 7.
Closes #9918
I have:

Fix warnings on autoconf 2.70

---

docs/Makefile.am
pdns/Makefile.am

When generated files (man pages, api-swagger files, etc.) are in the tree because they were part of a source distribution
but were not locally generated, 'make clean' should not remove them. Doing so results in a broken tree, as the Makefiles
expect the files to be present, and running 'configure' again will introduce the additional dependencies required to
generate them.
I have:

Avoid accidental removal of generated files

---

ext/lmdb-safe/lmdb-safe.cc

While a reader is kept open all write transactions lead to a increase in DB size due to the CoW mechanics. mdb_readers_check cleans up any readers left behind by crashed instances. We only do this when we open a DB in RW mode since we don't want to affect the DB when opening it in read only mode.
I have:

Do a mdb_reader_check to clean up stale readers on database load

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/doh.cc
pdns/doh.hh

We now use reference counting so that the response map is only destroyed after all readers are done with it. Previously updating the map meant that the underlying data was destroyed right away, while it might have been in use by DoH connection handler threads.
Fixes #9927 in my tests.
I have:

dnsdist: Fix a crash when a DoH responses map is updated at runtime

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/doh.cc
pdns/doh.hh

Backport of #9934 to rel/dnsdist-1.5.x.
(cherry picked from commit 312baf27f5357fae66582a8bbe937abff3c8d4fc)
I have:

dnsdist-1.5.x: Fix a crash when a DoH responses map is updated at runtime

---

pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recpacketcache.cc
pdns/recpacketcache.hh
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/Makefile.am
pdns/recursordist/docs/settings.rst
pdns/recursordist/rec-taskqueue.cc
pdns/recursordist/rec-taskqueue.hh
pdns/recursordist/taskqueue.cc
pdns/recursordist/taskqueue.hh
pdns/recursordist/test-recursorcache_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc7.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/recursordist/test-syncres_cc9.cc
pdns/syncres.cc
pdns/syncres.hh
regression-tests/recursor-test

This add two related mechanisms to the record cache:
1. When run normally, determining that an RC entry is "almost expired" and adding it to a queue of "to be refetched" entries (filtering duplicates).
2. Running a query done by SyncRes in a mode that considers "almost expired" entries as expired, triggering re-fetch of the RC "almost expired" entries used to resolve the query (including e.g. NS records that are used and almost expired).
The queue of almost expired entries is processed by the handler thread atm (this should change). It will refetch the names in "refetch almost expired" mode.
The whole mechanism is enabled by setting `refresh-on-ttl-perc`, e.g. to 10
If you want to play with this, _disable the packetcache_, since the entries in the PC and the RC mostly "dance to the same …

Rec: refresh almost expired

---

pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/test-recursorcache_cc.cc

In that case the loop exits without setting origTTL via handleHit().
I have:

rec: As found by coverity, origTTL can be left uninitialized if all the entries found are expired.

---

pdns/recursordist/test-syncres_cc5.cc
pdns/syncres.cc
pdns/syncres.hh

We need to take into account the TTL of NSEC(3) proofs in expanded wildcard answers, as well as the expiration time of their signatures.
Fixes #9967.
I have:

rec: Account for the NSEC(3) denial TTL in expanded wildcard answers

---

pdns/calidns.cc

So use the power of C++ to make the var the same type as msghdr.msg_iovlen.
I have:

Some platforms actually have an unsigned msghdr.msg_iovlen even though Posix says it should be an int.

---

pdns/dnsdistdist/configure.ac

Pre-Posix format has too low limit on path length that might
get hit on long branch names.
I have:

Move to ustar format for dist tarballs.

---

docs/settings.rst

`resolver=` was not documented, and references to it were shown as "setting-resolver" instead.
I have:

auth: Document resolver setting

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/doh.cc
pdns/doh.hh
regression-tests.dnsdist/test_DOH.py

That was the default before 1.5.0 and is very convenient in some setups.
I have:

dnsdist: Add an option to allow sub-paths for DoH

---

modules/lmdbbackend/lmdbbackend.cc

Prevents errors of the following kind from occurring if LMDBBackend::get should throw an exception for some other reason:
```
Exception building answer packet for example.com/SOA (vector::_M_range_check: __n (which is 1410) >= this->size() (which is 1)) sending out servfail
```
Port of #9884 to master.
I have:

Clear the LMDB set state when performing a new lookup or list to prevent corruption cases

---

pdns/dnsdist-rings.cc
pdns/dnsdist-rings.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc

Also add a debugging function to load the output of a `grepq()` command into the rings, in order to be able to reproduce a dynamic block issue.
I have:

dnsdist: Add a test for "Dynamic Block RCode rules messing up the queries count"

---

pdns/dnsdist-lua-inspection.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/advanced/tuning.rst
pdns/dnsdistdist/docs/reference/tuning.rst
regression-tests.dnsdist/test_Routing.py

Instead of starting only as many TCP worker threads on startup as the number of TCP listeners, then starting more at runtime, start all TCP worker threads on startup.
Change the default number of worker threads to at least 10, up to the number of TCP listener threads.
Document that change and improve the tuning page a bit.
I have:

dnsdist: Start all TCP worker threads on startup

---

pdns/dnsdist-dynblocks.hh
pdns/dnsdistdist/dnsdist-dynblocks.cc
regression-tests.dnsdist/test_DynBlocks.py

When a dynamic rcode rule was present, with a low traffic we could have been counting all the responses received by a client present in the in-memory ring-buffer, even very old ones, as queries. This could have triggered a query rate based dynamic block even though the client was not sending a lot of queries, in some none at all.
Also fixed a refreshing issue for SMT-based dynamic blocks. 
Already fixed in master by #9756.
This PR could use additional regression tests (master as well)!
I have:

dnsdist: Fix Dynamic Block RCode rules messing up the queries count

---

pdns/syncres.cc
regression-tests.recursor-dnssec/test_Simple.py
regression-tests.recursor-dnssec/test_SimpleTCP.py

This satisfies the SHOULD in RFC6761 section 6.3 point 4.
The RFC mentions in 6.3.
```
The domain "localhost." and any names falling within ".localhost."
are special in the following ways:
[.....]
4.  Caching DNS servers SHOULD recognize localhost names as special
and SHOULD NOT attempt to look up NS records for them, or
otherwise query authoritative DNS servers in an attempt to
resolve localhost names.  Instead, caching DNS servers SHOULD,
for all such address queries, generate an immediate positive
response giving the IP loopback address, and for all other query
types, generate an immediate negative response.  This is to avoid
unnecessary load on the root name servers and other name servers.
```
I have:

rec: treat the .localhost domain as special

---

pdns/common_startup.cc
pdns/pdns_recursor.cc

In the output of the help text, there's a line having "the the".
When running `pdns_recursor --help`, or `pdns_server --help`:
```
--carbon-instance=...
If set overwrites the the instance name default
```
I have:
Honestly, I don't know what the last box really means. I've created a separate branch for my changes, branched from the master branch. I'm unsure if the line should be deleted, or if the box should be checked...
Kind regards,
Bernd

Fix help text for carbon-instance

---

builder-support/specs/pdns-recursor.spec

This PR stops pulling in the protobuf development libraries (no longer required because we use protozero) and always pulls in libfstrm (this was conditional on EL version, but we no longer support 6, where it was unavailable)
I have:

Two spec-file fixes for the recursor

---

pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-lbpolicies.cc
pdns/dnsdistdist/test-dnsdistlbpolicies_cc.cc
regression-tests.dnsdist/test_Routing.py

dnsdist: Don't apply QPS to backend server on cache hits

---

pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/test-negcache_cc.cc
pdns/recursordist/test-recursorcache_cc.cc
pdns/test-recpacketcache_cc.cc

Recursor cache one was failing, a few functions return `int32_t` instead of `time_t`.
This is a demonstration of the type of issues #10000 talks about.
There are still issues caused by using `DNSRecord`'s `d_ttl` field (a 32-bit quantity since it corresponds to the phycial representation) for absolute time.
I have:

rec: fix recursor caches to handle timestamps > 2038

---

pdns/dnsdist.hh

destructor called on non-final 'QPSLimiter' that has virtual functions but non-virtual destructor
I have:

dnsdist: Silence clang 12 warning

---

pdns/dnsdist-tcp.cc

The warning emitted did not give guidance on how to fix the issue.
I have:

dnsdist: Improve error with a hint on how to fix it

---

pdns/dnsdist-console.cc
pdns/dnsdist-console.hh
pdns/dnsdist-lua.cc
pdns/dnsdist-web.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/connection-management.hh
pdns/dnsdistdist/dnsdist-web.hh
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/test-connectionmanagement_hh.cc
regression-tests.dnsdist/test_API.py
regression-tests.dnsdist/test_Console.py

Closes #4978.
This PR also cleans up a bit the console connection code, wrapping the socket to make sure it doesn't leak (existing code looked good but required some bookkeeping that the new one doesn't) and removing a couple unneeded allocations + copies.
I have:

dnsdist: Limit the number of concurrent console and web connections

---

pdns/Makefile.am
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/test-luawrapper.cc
pdns/recursordist/Makefile.am
pdns/recursordist/test-luawrapper.cc
pdns/test-luawrapper.cc

This catches the luajit/arm64 problem. Will add code comments explaining why this specific test is done.
I'm going through this product by product, breaking them one by one, to make sure CI catches these failures.
I have:

test luawrapper in make check

---

pdns/Makefile.am
pdns/dnsdistdist/Makefile.am
pdns/dnstap.cc
pdns/protozero.hh
pdns/recursordist/Makefile.am

On platforms with different byte orders (like s390x), protozero wants to include its own `byteswap.hpp`, but fails. This PR is one way to fix that.
Alternatively, also suitable for upstreaming:
```diff
diff --git a/ext/protozero/include/protozero/basic_pbf_writer.hpp b/ext/protozero/include/protozero/basic_pbf_writer.hpp
index f167c4d1d..b783293f1 100644
--- a/ext/protozero/include/protozero/basic_pbf_writer.hpp
+++ b/ext/protozero/include/protozero/basic_pbf_writer.hpp
@@ -23,7 +23,7 @@ documentation.
#include "varint.hpp"
#if PROTOZERO_BYTE_ORDER != PROTOZERO_LITTLE_ENDIAN
-# include <protozero/byteswap.hpp>
+# include "byteswap.hpp"
#endif
#include <cstddef>
diff --git a/ext/protozero/include/protozero/iterators.hpp b/ext/protozero/include/protozero/iterators.hpp
index …
```

protozero: make internal includes work

---

ext/luawrapper/include/LuaContext.hpp
ext/yahttp/yahttp/router.cpp
pdns/dnscrypt.hh
pdns/dnsdist-lua-inspection.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-rings.cc
pdns/dnsdist-xpf.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-lbpolicies.cc
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/tcpiohandler.cc
pdns/dnsparser.cc
pdns/doh.hh
pdns/ednsoptions.cc
pdns/iputils.cc
pdns/iputils.hh
pdns/pdnsexception.hh
pdns/protozero.cc
pdns/sodcrypto.hh
pdns/test-dnscrypt_cc.cc
pdns/test-dnsdist_cc.cc
pdns/xpf.cc

Mostly false positive that I'm tired of seeing, or performance tips in places we don't really care about performance.
But also a real bug in the code loading the ring buffers from a file (only used for debugging) and a few hardening measures (additional checks, initializations) that will not hurt and might prevent an issue later. 
I have:

dnsdist: Fix a few warnings reported by clang's static analyzer and cppcheck

---

pdns/dnssecinfra.cc
pdns/test-signers.cc

The salt does not change between iterations, and the hash size is constant, so we can just overwrite the hash instead.
I have:

Don't copy the same salt for all iterations in hashQNameWithSalt()

---

pdns/pdns_recursor.cc
pdns/recpacketcache.cc
pdns/recpacketcache.hh
pdns/test-recpacketcache_cc.cc
regression-tests.recursor-dnssec/test_PacketCache.py

Up until now the packetcache was not used for incoming queries over tcp.
Includes re-factoring of the cache-hit path to avoid code duplication.
Note that udp and tcp entries are separated, so we do not have to deal with deciding if a udp packet would fit a tcp query or vice versa.
I have:

Rec: packetcache for tcp queries

---

pdns/backends/gsql/gsqlbackend.cc
pdns/pdnsutil.cc
pdns/ws-auth.cc

deleteDomain() is running a few queries to delete domain data from different tables. If one of those queries is failing (for example due to locks) a partial deleted domain is left behind.
I have:

auth: run deleteDomain() inside a transaction

---

pdns/backends/gsql/gsqlbackend.cc
pdns/pdnsutil.cc
pdns/ws-auth.cc

auth-4.4.x: run deleteDomain() inside a transaction

---

pdns/iputils.hh

Coverity reported a leak in that code again after #10035, so I had to read it again and it still confused the heck out of me. I hope these changes will make it a bit more readable, but comments/ideas are welcome!
I have:

Make NetmaskTree::fork() a bit easier to understand

---

.github/actions/spell-check/excludes.txt
docs/http-api/swagger/authoritative-api-swagger.yaml
docs/requirements.txt

This patch documents the possible error response objects for all API
operations. When a spec-validating client is used, returning a
response code (and object) which are not included in the spec will
disallow access to the response object, and may cause an exception to
be thrown.
In order to do this without repeating the possible responses for each
API operation, the YAML anchor/alias mechanism is used so that the
list of response codes and their object schemas can be written in one
place. To make that possible, the patch adds a fictitious '/error' API
operation, which of course will actually return an error since it does
not exist.
The spec version has been bumped from 0.0.13 to 0.0.15 (0.0.14 should
have been used for the recent bug fixes to the spec file).
Note: If the spec file was …

Add error response objects to all API operations in spec file

---

pdns/dnsmessage.proto

Relicense `dnsmessage.proto` as CC0 Public Domain. GPLv2 makes no sense as this is an interface, not code.
CC0 was chosen because `dnstap.proto` also uses it and it seemed a good fit. 
I have:

dnsmessage.proto: make CC0 Public Domain

---

.clang-format

Setting these flags appears to fix one difference between clang-format8 and 10
I have:

fix a clang-format issue difference in opinion

---

builder-support/specs/pdns-recursor.spec

With this, identical packages as before the 'drop el6' backport come out.
I have:

rec-4.4.x el8: pull in libfstrm

---

pdns/mtasker.cc

We used to wait until the first invocation of a `MTask` to set the start of the stack, but that sometimes resulted in passing the `nullptr` address to `ASAN` when calling a task for the first time. It resulted in `ASAN` skipping the stack switch, logging something like:
```
WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x000000020000; bottom 0x7f18f174a000; size: 0xffff80e70e8d6000 (-139745106763776)
False positive error reports may follow
```
Then almost right away complaining about a stack-use-after-scope, or a stack-based overflow.
This changes sets the end of the memory allocation before the first invocation, so that we always notify a valid value. A closer
approximation is still set during the first invocation, as before.
I have:

rec: Set the start of the stack right away to avoid an ASAN issue

---

pdns/responsestats-auth.cc
pdns/responsestats.hh
pdns/tcpreceiver.cc
pdns/tcpreceiver.hh

AXFR was counting packets as answers and added one extra answer after the AXFR was finished.
Fixes #4146
I have:

auth: fix tcp answer counters

---

pdns/dnsdistdist/docs/guides/dns-over-https.rst

The response map example in https://dnsdist.org/guides/dns-over-https.html isn't formatted in a code block.
I _hope_ this PR fixes it. I did not actually test it.
I have:

dnsdist docs: Fix formatting of response map example

---

pdns/lua-recursor4.cc
pdns/pdns_recursor.cc
pdns/syncres.hh

Note that this is a change in behavior. While it is for the good and fixes #9547, it might be existing code depends on the old 0 value...
I have:

rec: Return current rcode instead of 0 if there are no CNAME records to follow

---

builder-support/dockerfiles/Dockerfile.target.centos-7
builder-support/dockerfiles/Dockerfile.target.centos-7-amd64
builder-support/dockerfiles/Dockerfile.target.centos-8
builder-support/dockerfiles/Dockerfile.target.centos-8-amd64
builder-support/dockerfiles/Dockerfile.target.centos-8-arm64
builder-support/dockerfiles/Dockerfile.target.debian-buster
builder-support/dockerfiles/Dockerfile.target.debian-buster-amd64
builder-support/dockerfiles/Dockerfile.target.debian-buster-arm64
builder-support/dockerfiles/Dockerfile.target.ubuntu-bionic
builder-support/dockerfiles/Dockerfile.target.ubuntu-bionic-amd64
builder-support/dockerfiles/Dockerfile.target.ubuntu-bionic-arm64
builder-support/dockerfiles/Dockerfile.target.ubuntu-focal
builder-support/dockerfiles/Dockerfile.target.ubuntu-focal-amd64
builder-support/dockerfiles/Dockerfile.target.ubuntu-focal-arm64

This allows us to be specific about what architecture to build for. The 'base' target remains, for anybody that just wants to build for their default arch. It might make sense to disable the base targets at some point.
I have:

builder: add arch-specific targets

---

builder-support/dockerfiles/Dockerfile.target.centos-8
builder-support/dockerfiles/Dockerfile.target.oraclelinux-8

The oraclelinux:8 image lost yum this week. The centos:8 image also prefers dnf.
I have:

docker builds: stop using yum on EL8 derivatives

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua.hh
pdns/dnsdist.cc
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_Spoofing.py

This adds the option to specify multiple responses with spoofRawAction
I have:

dnsdist: Add option to spoofRawAction to spoof multiple answers

---

pdns/dnsrecords.cc
pdns/dnsrecords.hh
pdns/pdns_recursor.cc
pdns/qtype.cc
pdns/qtype.hh
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/syncres.cc
pdns/syncres.hh

I converted syncres.* for starters to stop using uint16_t for qtype
and use QType everywhere.  Note that I also changed const QType&
in arg lists by QType, since it makes little sense to pass a 16 bit value
by const reference.
I have:

Improve the way QType behaves by defining proper conversion operators and a hash function.

---

pdns/recursordist/docs/lua-scripting/dnsname.rst

We really should be having one source for all common Lua docs.
Fixes #9608.
I have:

rec: Take the DNSName docs from auth, they are more complete

---

pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/test-dnsdistlbpolicies_cc.cc
regression-tests.dnsdist/test_Spoofing.py

This commits makes it possible to spoof multiple values from Lua:
```
function myfunc(dq)
local ret = { newCA("192.0.2.1"), newCA("192.0.2.2") }
dq:spoof(ret)
return DNSAction.HeaderModify
end
addAction(AllRule(), LuaAction(myfunc))
```
<strike>Barely tested, need tests and documentation.</strike>
Now with documentation and tests courtesy of tjikkun, thanks a lot!
I have:

dnsdist: Add 'spoof' and 'spoofRaw' Lua bindings

---

regression-tests.api/runtests
regression-tests.auth-py/runtests
regression-tests.dnsdist/runtests
regression-tests.ixfrdist/runtests

CI on CircleCI triggers spurious complaints about `bdist_wheel`
I have:
<details><summary>test-dnsdist-regression
</summary>
https://app.circleci.com/pipelines/github/PowerDNS/pdns/4091/workflows/eba4d9a3-ea2d-4f3f-bf14-a68e3047c992/jobs/74657
```
#!/bin/bash -eo pipefail
DNSDISTBIN="/opt/dnsdist/bin/dnsdist" \
./runtests
...
Collecting ply (from pysmi->pysnmp>=4.3.4->-r requirements.txt (line 6))
Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)
Building wheels for collected packages: future, pycurl, lmdb
Running setup.py bdist_wheel for future: started
Running setup.py bdist_wheel for future: finished with status 'error'
Complete output from command …
```

Add wheel to pip

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/docs/upgrade.rst
pdns/syncres.cc
pdns/syncres.hh

While there, add a few entries to the upgrade guide.
The current ways of makeing that deccisoi does not allow for the case: cache some v6 replies, but never cache v6 or vice versa.
I have:

rec: Introduce settings to never cache EDNS Client (v4/v6) Subnet carrying replies

---

pdns/arguments.cc
pdns/lua-base4.cc
pdns/lua-base4.hh
pdns/pdns_recursor.cc
pdns/rec_channel.cc
pdns/rec_channel.hh
pdns/rec_channel_rec.cc
pdns/rec_control.cc
pdns/recursordist/docs/manpages/rec_control.1.rst
pdns/syncres.hh
regression-tests.recursor-dnssec/test_RoutingTag.py

This makes `rec_control` open the file used by `dump-cache` and other dumping command and pass the file descriptor over the socket. This makes it more easy to export data if the recursor is running with restricted file access (e.g. chroot).
Also allows to dump the data to stdout (`rec_control dump-cache -`). 
I also added code to separate the error code from the string returned. This principle could also be extended to any command that could return an error.
Note that this causes an incompatibility between `rec_control` and `pdns_recursor`. I don't think we ever promised the API between the two would be stable or compatible between versions, but you know, people will stumble over this anyway. A note in the upgrade guide will be needed.
I have:

rec: Rec control pass fd

---

pdns/dnsdist.cc
pdns/dnsdist.hh

Otherwise we might crash when the first TCP query arrives because we are dividing by zero when trying to select a worker.
This PR also adds an explicit check to turn the crash into an exception if we ever manage to break that again.
I have:

dnsdist: Create TCP worker threads before acceptors ones

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua.cc

Since we return a `nullptr` object in client mode, we need to check that the object is valid in all methods and we forgot to do that in `addBPFFilterDynBlocks`, `excludeRange()` and `includeRange()`.
Fixes #10090.
I have:

dnsdist: Prevent a crash with DynBPF objects in client mode

---

pdns/pdnsutil.cc

Fixes the underlying issue from #7203.
```
$ cat broken-rr.example.zone
$ORIGIN broken-rr.example.
@ IN SOA foo bar 1 2 3 4 5
@ IN MX 10 . bla ;; This is broken
$ pdnsutil --config-dir=. load-zone broken-rr.example. broken-rr.example.zone
Creating 'broken-rr.example'
Bad record content in record for broken-rr.example|MX: When parsing MX trailing data was not parsed: ' bla'
```
I have:

pdnsutil load-zone: reject zones with broken rrs

---

docs/backends/ldap.rst

Examples for OpenLDAP index directives needs a space after keyword "index".
I have:

LDAP backend docs: Added missing spaces after OpenLDAP index directives

---

docs/backends/lmdb.rst
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh

Only lock until the first backend is ready.
I have:

auth: run lmdb init and upgrade code only once

---

.github/workflows/spelling.yml

#10066 switched from checking a potential merge to checking the PR head because I couldn't find a good way to check the merge. This code switches PRs to checking the merge.
I have:
If someone had a PR from before the 0.0.17-alpha upgrade, and made a PR before this merges, they'd get complaints about items that were fixed on master between their branch point and master.
With this change, those errors that have already been resolved in master will be treated as resolved.
Note: I have no idea what happens if there are merge conflicts. I half expect GitHub to scream in some fun way. But, technically this wasn't a new problem, it's close to before the upgrade.
You can experiment with the repository here: https://github.com/check-spelling/pdns/pull/1#issuecomment-780865943  -- note that at some …

check-spelling: Try checking out merge/head appropriately

---

pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/docs/metrics.rst
pdns/recursordist/docs/settings.rst
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/validate-recursor.cc
pdns/validate-recursor.hh
pdns/ws-recursor.cc

This implements the feature as requested in #10058.
Idea is that you can set `x-dnssec-names` to a suffixmatch list. DNSSEC counting actions will then be done for on `x-dnssec-result-bogus-...` counter instead of the regular one.
Missing: 
This PR is mainly to gauge if this approach is the way forward. I'm also open for a better name than `x-dnssec...`
I have:

rec: Count DNSSEC stats for some names in a different set of counters

---

pdns/histogram.hh
pdns/misc.hh
pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/Makefile.am
pdns/recursordist/histogram.hh
pdns/recursordist/test-histogram_hh.cc
pdns/syncres.cc
pdns/syncres.hh

This intended as code cleanup without changing externally observable behavior. It will make it easier to make the HIstogram configurable and add cumulative ones in the future.
Current latency computations are a mix of different types (float, double, uint64_t) and units (secs, millisecs, microsecs. Harmonize to always work in an integral number of microseconds, and only use doubles when needed to compute running averages.
Also make sure we use atomics for all data written to from different threads, specifically  `avgLatencyUsec` and `avgLatencyOursUsec`.
I have:

Rec: refactor latency and histogram calculations

---

pdns/dnsname.hh
pdns/dnsrecords.hh
pdns/lock.hh
pdns/pdns_recursor.cc
pdns/rec-snmp.cc
pdns/rec_channel_rec.cc
pdns/recursor_cache.cc
pdns/recursordist/Makefile.am
pdns/recursordist/RECURSOR-MIB.txt
pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/aggressive_nsec.hh
pdns/recursordist/docs/metrics.rst
pdns/recursordist/docs/settings.rst
pdns/recursordist/test-aggressive_nsec_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/syncres.cc
pdns/validate.cc
pdns/validate.hh
regression-tests.recursor-dnssec/test_AggressiveNSECCache.py

This is a work-in-progress PR, to see how it fares against our CI tests and get the feedback on the design choices.
Some of these are:
- using a separate cache instead of reusing/abusing the existing record cache: we don't store NSEC3 in the record cache, and the sharding makes it very hard to reuse it efficiently without writing some horrible hack, but more importantly I believe keeping the NSEC/NSEC3 ordered by zone reduce the amount of work doing the search by a nice margin.
- checking that new cache early means that we can be searching in the wrong zone, like in the root zone, even though we do have some information in our record cache about a more specific zone existing. This should not have any functional impact but likely has a performance impact. On the other hand doing the check …

rec: Implement rfc 8198 - Aggressive Use of DNSSEC-Validated Cache

---

docs/manpages/sdig.1.rst
pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.hh
pdns/dnsdistdist/dnsdist-tcp-upstream.hh
pdns/dnsdistdist/docs/advanced/tuning.rst
pdns/dnsdistdist/docs/reference/tuning.rst
pdns/dnsdistdist/tcpiohandler-mplexer.hh
pdns/dnsdistdist/test-dnsdisttcp_cc.cc
pdns/epollmplexer.cc
pdns/sdig.cc
pdns/sstuff.hh
pdns/tcpiohandler.cc
pdns/tcpiohandler.hh
pdns/test-dnscrypt_cc.cc

This PR fixes several issues in corner cases, introduced during the refactoring for out-of-order support. It also adds a lot of unit tests for that TCP code, which was planned for 1.7.0 but fast-forwarded because of issues reported with 1.6.0-alpha1.
It also adds a new configuration option, `setTCPInternalPipeBufferSize`, that can be used to set the size of the buffer of the internal pipe used to pass queries to TCP worker threads, thus allowing a smoother handling of incoming TCP connections peaks.
The diff seems huge but most of that (3200 out of 3900 additions) comes from the new unit tests, which actually amount to more lines of code than the TCP code itself and provides a very nice code coverage (which unfortunately does not prevent bugs from still hiding in a unexpected state.. …

dnsdist: Fix several bugs in the TCP code path, add unit tests

---

pdns/dnsdistdist/dnsdist-tcp-downstream.cc

This removes a warning introduced in #10108.
Before that PR we supported source interface selection over UDP and TCP when talking to our backends, via:
- the "generic" way, binding with the right source address, and passing the interface index down to the actual `sendmsg` call via `IP_PKTINFO` and `IPV6_PKTINFO` in case that was not enough ;
- `SO_BINDTODEVICE` on Linux, which was reported as the only working solution on Linux in https://github.com/PowerDNS/pdns/issues/8284.
After that PR we don't set the interface index anymore on the TCP path, and instead rely on:
- binding with the right source address being good enough on most OS ;
- setting `SO_BINDTODEVICE` on Linux.
As far as I can tell there is no other option, `IP_SENDIF` never made it to the BSD world, but from what I read …

dnsdist: Remove forgotten warning about source interface selection

---

pdns/dnsdist.cc
regression-tests.dnsdist/test_Trailing.py

The size check was missing since the `PacketBuffer` refactoring in 1.6, and the regression test was broken at roughly the same time because `dq.size` does not exist anymore.
I have:

dnsdist: Fix size check during trailing data addition, regression tests

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/dnssec.rst
pdns/recursordist/docs/settings.rst
pdns/recursordist/docs/upgrade.rst
regression-tests.recursor-dnssec/test_DNS64.py
regression-tests.recursor-dnssec/test_PacketCache.py
regression-tests.recursor-dnssec/test_Protobuf.py
regression-tests.recursor-dnssec/test_RPZ.py

This is a sane default nowadays. It will also greatly help if the aggressive NSEC cache (#10047) is enabled by default.
I have:

rec: Change dnssec default to `process`

---

pdns/dnsdist-cache.cc
pdns/dnsdist-cache.hh
pdns/dnsdist.cc
pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
pdns/test-dnsdistpacketcache_cc.cc

Otherwise we might remove enough entries from the first shards only and stop there, which means that the other shards might remain full.
This might be fine if we clean up often enough since the next cleaning run will start with the remaining shards, but that's sub-optimal when we are often nearly full because it will prevent new entries from being inserted in the shards that are full.
This should improve https://github.com/PowerDNS/pdns/issues/10128.
I have:

dnsdist: Clean up expired entries from all the packet cache's shards

---

pdns/common_startup.cc
pdns/common_startup.hh

auth-4.3.x: fix rounding inaccuracy in latency statistics

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc2.cc
pdns/syncres.cc
pdns/syncres.hh

In particular, we clear the entry if we see a succeeding resolve.
This means that we only a couple of failing resolves in a row will
cause a ban. Also change to default non-resolving-ns-max-fails from
1 to 5.
I have:

Make the non-resolving cache even less aggressive and add a unit test.

---

pdns/misc.cc

According to https://www.kernel.org/doc/html/latest/filesystems/proc.html "data" aka "drs" is broken. 
In practice most of the time it shows a number somewhere between RES and VIRT, but it seems to be completely off in multi-threaded processed once in a while.
So move to the same number top(1) displays as "RES". This number is not marked broken and top(1) and the metrics agreed all the time in my tests.
Should fix #7591
I have:

"data" size is unreliable, start using RES, as it seem reliable and relavant

---

Dockerfile-auth

`pdnsutil edit-zone` requires `EDITOR` to be set. Currently there's no editor installed at all. Adding vim, so that it can be used as default editor by `pdnsutil edit-zone`.
I have:

Install vim in docker-auth image

---

docs/lua-records/functions.rst

`ecswho` is documented to be a `ComboAddress`, but I'm 99.9% sure it's a `Netmask` instead.
```
lua.writeVariable("ecswho", dnsp.getRealRemote());
```
```
Netmask DNSPacket::getRealRemote() const
```
`bestwho` on the other hand is correctly documented as a `ComboAddress`:
```
s_lua_record_ctx->bestwho = dnsp.getRealRemote().getNetwork();
```
The second line of the diff is just for style.
I have:

docs: ecswho is a Netmask, not a ComboAddress

---

pdns/packethandler.cc
regression-tests/tests/alias-address/command
regression-tests/tests/alias-address/expected_result.dnssec

This ensures that NODATA responses from names with an ALIAS record don't
blank out A/AAAA on resolvers using aggressive NSEC caching.
This also removes the ALIAS type from the NSEC bitmap, as the ALIAS itself shouldn't be queried for anyway.
Closes #6667
I have:

ALIAS: Ensure A and AAAA are in the NSEC bitmap

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/libssl.cc
pdns/libssl.hh

It is enabled by default by nginx, haproxy, Dovecot, Tor...
I have:

dnsdist: Set OpenSSL to release buffers when idle, saves 35 kB per connection

---

pdns/dnsdist-cache.cc
pdns/dnsparser.hh
pdns/pdns_recursor.cc
pdns/test-dnsparser_cc.cc

Also add safety belt to the ageing code to not wrap TTLs.
I have:

rec: make sure we take the right minimum for the PC TTL data.

---

pdns/pdns_recursor.cc

Backport of #10185, without the dnsparser.hh change.
I have:

rec: Backport 10185 to 4.3.x: make sure we take the right minimum for the PC TTL data in the SERVFAIL case

---

pdns/pdns_recursor.cc

Backport of #10185 (without the dnsparser.hh change)
I have:

rec: Backport 10185 to 4.4.x: make sure we take the right minimum for the PC TTL data in the SERVFAIL case.

---

pdns/recursordist/test-syncres_cc5.cc
pdns/syncres.cc

If somehow the RRSIG indicating that the answer is expanded from a
wildcard (label count smaller than the number of labels in the name)
went _after_ the NSEC we need, we forgot to gather that NSEC.
It might have been an issue for downstream validation (we do gather
them a second time later for our own validation) since the client
would not have received them.
(cherry picked from commit 0626e855ad5f944f8b357d729dc42e001f57820a)
Backport of #9793 
I have:

rec: Backport 9793 to 4.4.x: Fix the gathering of denial proof for wildcard-expanded answers

---

pdns/dnsdist-web.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/statistics.rst
pdns/misc.cc
pdns/misc.hh
regression-tests.dnsdist/test_API.py

Making it easier to spot when the TCP / DoT or DoH acceptor threads are overloaded.
I have:

dnsdist: Add a metric for TCP listen queue full events

---

pdns/dnsname.hh

A misplaced 'const' prevented it from being called, making every
move of a DNSName into a full copy.
Introduced in d720eb8add5ebda11867e8b404125e0b68ed2911.
(cherry picked from commit 8d1bb300460d5cc97b4599ea8eddeb7b6d35decf)
I have:

rec: backport 9749 to 4.4.x: Fix the DNSName move assignement operator

---

modules/lmdbbackend/lmdbbackend.cc

Check in both commitTransaction and abortTransaction of the lmdbbackend whether a transaction is actually active
I have:

Check if transaction is active in LMDB

---

builder-support/dockerfiles/Dockerfile.target.amazon-2
builder-support/specs/pdns.spec

Just to match their docs more closely. This does not switch the build to an actually different EPEL repo.
Sidenote: the auth build for amazonlinux-2 is currently broken, but only because of something between ixfrdist and yaml-cpp. I've decided to not investigate that right now.
I have:

amazonlinux-2 packaging improvements

---

pdns/pdns_recursor.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc1.cc
pdns/reczones.cc
pdns/syncres.cc

Insert hints as non-auth into cache, so info received from the net is recorded in the cache.
Also make sure the root NS refresh happens more often if `max-cache-ttl` is low.
This is needed as the records no longer maintain the 1000 hours TTL.
In the existing setup, a reprime (with potential outdated info) was done at that
point in time since all root-server address records would expire at the same
time.
Lastly, fix a infinite (caught by depth check) recursion in getBestNSFromCache().
Fixes #10177.
As a bonus, reformat `reczones.cc` to make it easier on the eyes. (Ignore whitespace to make the diff easier).
I have:

rec: Insert hints as non-auth into cache

---

pdns/recursordist/test-aggressive_nsec_cc.cc
pdns/recursordist/test-syncres_cc1.cc
pdns/recursordist/test-syncres_cc2.cc
pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/recursordist/test-syncres_cc5.cc
pdns/recursordist/test-syncres_cc6.cc
pdns/recursordist/test-syncres_cc7.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/recursordist/test-syncres_cc9.cc
pdns/syncres.cc
pdns/syncres.hh
pdns/validate.cc
pdns/validate.hh
regression-tests.recursor-dnssec/test_AggressiveNSECCache.py
regression-tests.recursor-dnssec/test_Protobuf.py

This commits removes the early zone cut computation using DS queries.
It instead determines the status of a record when it is either received from an authoritative server or retrieved from a cache, detecting missed zone cuts when the expected signatures are not present.
This results in roughly 8% less outgoing queries in quick testing.
Needs a lot of testing, and there are several low-hanging optimizations that can be done to the new code.
I have:

rec: Get rid of early zone cut computation

---

pdns/pdns_recursor.cc
pdns/ws-recursor.cc

At this point we already have several threads so calling exit()
will cause problem by trying to destruct objects that are in use
by other threads, so call _exit() instead.
Also mention the web server in the error message so that the root
cause is easier to identify.
(cherry picked from commit ce715f38fcedf752220cd5056e1a3945330041fd)
Backport of #9812 
I have:

rec: Backport 9812 to 4.4.x: Handle failure to start the web server more gracefully

---

.circleci/config.yml
pdns/dnswriter.cc
pdns/dnswriter.hh
pdns/ednspadding.cc
pdns/ednspadding.hh
pdns/lua-recursor4-ffi.hh
pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/recursordist/Makefile.am
pdns/recursordist/docs/lua-scripting/dq.rst
pdns/recursordist/docs/settings.rst
pdns/recursordist/ednspadding.cc
pdns/recursordist/ednspadding.hh
regression-tests.recursor-dnssec/paddingoption.py
regression-tests.recursor-dnssec/test_EDNSPadding.py
regression-tests.recursor-dnssec/test_ExtendedErrors.py

The initial idea is to be able to add EDNS padding when answering to queries received over DoT or DoH. This PR allows adding this option based on the source (so you could use a different source when forwarding a query from dnsdist to the recursor, based on whether it was received over DoH or DoT), and optionally on whether the initial query had padding.
One of the challenge is that this duplicates the content of the packet cache to avoid mixing padded and non-padded responses.
I have:

rec: Implement EDNS0 padding (rfc7830) for outgoing responses

---

pdns/dnsdistdist/doh.cc
regression-tests.dnsdist/test_DOH.py

rfc8484 states that clients "SHOULD use a DNS ID of 0 in every DNS request", not MUST, and it does indeed happen.
The issue was introduced in 341d2553b74c579df9d9843959f3ca6f5c3dc954 (between 1.5.x and 1.6.0-alpha1) when we moved to a safer PacketBuffer.
I have:

dnsdist: Fix the handling of DoH queries with a non-zero ID

---

.circleci/config.yml

CicleCI docs indeed suggest the environment setting under docker do not apply
to the jobs steps.
So specify it explicitly for the test run itself.
I have:

rec: Setup env properly to skip v6 test.

---

.github/actions/spell-check/expect.txt
pdns/lwres.cc
pdns/pdns_recursor.cc
pdns/recursordist/docs/performance.rst
pdns/recursordist/docs/settings.rst
pdns/recursordist/docs/upgrade.rst
pdns/sdig.cc
pdns/sstuff.hh
pdns/syncres.cc
pdns/syncres.hh

Start supporting `TCP_FASTOPEN` for outgoing TCP connections.
We originally did this for `sdig` and the recursor, but the `sdig` case is now handler by tcpiohandler and no longer part  of this PR.
Don't forget to do `sysctl -w net.ipv4.tcp_fastopen=3` if you want to use this (or `1` if you only want it for outgoing and `2` for incoming only.
While testing this, I had a hard time finding auths that actually support FAST_OPEN.
8.8.8.8 and the google auths appear to do so, but trying to use it, the cookie is rejected and a new cookie is sent, causing the client to retransmit the request payload.
Fixes #7982
TODO
I have:

Rec and sdig: support tcp fastopen connect

---

pdns/dnsdist-lua.cc
pdns/dnsdist-rings.hh
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.hh
pdns/dnsdistdist/docs/advanced/tuning.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/tuning.rst
pdns/doh.hh
regression-tests.dnsdist/test_Caching.py
regression-tests.dnsdist/test_DNSCrypt.py

The sharding code has seen a lot of traffic by now and can safely be enabled by default, since it provides much better performance (less contention).
Determining the optimal size of pipe buffers on all systems is hard, but let's use a better default on Linux where we know it works well. Also increase the number of queued TCP/DoT connections now that the buffer is big enough.
I have:

dnsdist: Enable sharding by default, greater pipe buffer sizes

---

pdns/dnsdist-carbon.cc
pdns/dnsdist-lua-inspection.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist-web.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.hh
pdns/dnsdistdist/dnsdist-tcp-upstream.hh
pdns/dnsdistdist/test-dnsdisttcp_cc.cc

The TCP connect timeout was ignored since 1.4.0, and the write timeout used instead.
<strike>Needs more tests(done)</strike>
I have:

dnsdist: Fix the TCP connect timeout, add metrics

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-lua-bindings-dnscrypt.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/dnscrypt.rst

This PR unifies the way of reloading certificates over the different types of frontends (DNSCrypt, DoT and DoH). It also paves the way for the deprecation of the `TLSCtx` class by making every method available from the `TLSFrontend` class.
I have:

dnsdist: Unify certificate reloading syntaxes

---

pdns/dnsdist-carbon.cc
pdns/dnsdist-console.cc
pdns/dnsdist-lua-inspection.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist-web.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/dnscrypt.rst
pdns/dnsdistdist/docs/reference/tuning.rst
pdns/dnsdistdist/doh.cc
regression-tests.dnsdist/test_DOH.py
regression-tests.dnsdist/test_TCPLimits.py
regression-tests.dnsdist/test_TLS.py

This PR adds a configuration option for the number of inactive TCP connections kept in cache by TCP workers for future use.
It also adds new metrics for the maximum number of TCP connections reached per backend, and per frontend, and new configuration options to limit the number of concurrent incoming connections per frontend.
<strike>It lacks an option to configure the maximum number of incoming connections per front-end.</strike>
I have:

dnsdist: Add limits for cached TCP connections, metrics

---

pdns/rec_channel_rec.cc
pdns/test-dnsname_cc.cc

(cherry picked from commit b2dd79dc04e2939fb84e3a4ee3df9a191bebe529)
Backport of #9860 
I have:

rec: backport 9860 to 4.4.x: Get rid of warnings when compiling with Boost 1.74

---

pdns/lua-recursor4.cc
pdns/pdns_recursor.cc
pdns/syncres.hh

Note that this is a change in behaviour. While it is for the good, it might
be existing code depends on the old 0 value...
(cherry picked from commit 558d47eba7d2edd3fb5991af428d9d432fec1dfa)
Backport of #10064 
I have:

rec: Backport 10064 to 4.4.x: Return current rcode instead of 0 if there are no CNAME records to follow

---

pdns/nod.cc
pdns/nod.hh
pdns/recursordist/stable-bloom.hh

Current code does not take into account file operation failures in a safe way.
This PR makes sure we write to a temp file and rename only after a succesful write, plus we do not crash on corrupt files, we remove them.
I have:

rec: More fail-safe handling of NOD files

---

pdns/pdns_recursor.cc

(Partial) Backport of #10111 
I did not take the Lua changes, as there is a (slight) chance they are disruptive.
I have:

rec: Backport 10111 to rec 4.4.x: Handle policy (if needed) after postresolve

---

pdns/cachecleaner.hh
pdns/libssl.cc
pdns/libssl.hh
pdns/lock.hh
pdns/speedtest.cc
pdns/test-lock_hh.cc

Closes #10209.
The speed tests result looks good, except perhaps for a small regression in the "RW lock shared" case but since we are talking of 1 usec for 1000 operations, I believe we can live with that.
* master
```
'getlock-uncontended-test' 0.11 seconds: 112247847.3 runs/s, 0.01 usec/run
'RW lock shared' 0.11 seconds: 107827.9 runs/s, 9.27 usec/run
'RW lock exclusive' 0.11 seconds: 72534.4 runs/s, 13.79 usec/run
'RW lock try exclusive - non-contended' 0.11 seconds: 69176.3 runs/s, 14.46 usec/run
'RW lock try exclusive - contended' 0.11 seconds: 255326.8 runs/s, 3.92 usec/run
'RW lock try shared - non-contended' 0.11 seconds: 107123.5 runs/s, 9.34 usec/run
'RW lock try shared - contended' 0.11 seconds: 255821.4 runs/s, 3.91 usec/run
'getlock-uncontended-test' 0.11 seconds: 113262655.2 …
```

Replace pthread_rwlock with std::shared_mutex

---

docs/http-api/swagger/authoritative-api-swagger.yaml
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

When CDS publication for a zone is configured, also add a `"cds"` entry to the auth API cryptokeys object.
I have:

auth API cryptokeys: add cds array when configured to do so. Closes #10215

---

pdns/dnsdistdist/docs/rules-actions.rst

Fixes typo in dnsdist documentation for SuffixMatchNodeRule param name listing (smb vs smn).
I have:

Fix typo in dnsdist docs for SuffixMatchNodeRule

---

modules/gmysqlbackend/gmysqlbackend.cc
modules/godbcbackend/godbcbackend.cc
modules/gpgsqlbackend/gpgsqlbackend.cc
modules/gsqlite3backend/gsqlite3backend.cc
pdns/backends/gsql/gsqlbackend.cc
pdns/backends/gsql/gsqlbackend.hh
pdns/dbdnsseckeeper.cc
pdns/dns.hh
regression-tests/backends/godbc_sqlite3-master

inspired by and successor of #9064
closes #9064
Rectify must be able to correct the ordername under all circumstances. The previous pull was however making assumptions on the exiting rectify state. There is also an issue with empty vs NULL ordernames in the backends. For both values the backends do return an empty value. This is fine for the rest of pdns but is was confusing the smart rectify.
This pull is working around a these issues at the cost of slightly more update queries. Records with empty values are always updated. And the same applies to names with different ordername/auth values, mostly found in delegations.
Some numbers...
First rectify:
```
time ../pdns/pdnsutil --config-dir=. --config-name=gmysql rectify-all-zones example.com
Rectifying example.com: Adding NSEC ordering …
```

auth: rectify() do not update ordernames/auth when there is no need

---

docs/modes-of-operation.rst
pdns/Makefile.am
pdns/communicator.cc
pdns/communicator.hh
pdns/dnsbackend.hh
pdns/dynhandler.cc
pdns/packethandler.cc
pdns/slavecommunicator.cc
pdns/test-communicator_hh.cc
pdns/ws-auth.cc

This PR makes it possible to have AXFR requests of a different priority, where requests with the highest priority get handled first. closes #10190
I have:

auth: implement AXFR priority level queue code

---

pdns/dnsparser.cc
pdns/dnswriter.cc
pdns/dnswriter.hh
pdns/misc.hh
pdns/rcpgenerator.cc
pdns/test-rcpgenerator_cc.cc

The implementation in #10121 threw compiler warnings. After investigation, I found that that code only works by accident, because pointers are 64 bits on the systems we compile for.
In this PR, the first and third(!) commits are two alternative fixes for this problem. Please review and let me know what you like.
I have:

RFC6742 types: use correct size

---

pdns/lwres.cc
regression-tests.recursor-dnssec/test_RecDnstap.py

Fixes #10265.
Also fix two cases where we should not send a dnstap message:
1) if we're chaining on an existing query; 
2) if the sending failed
Needs tests, therefore draft.
I have:

rec: Log local IP in dnstap messages

---

pdns/rec_channel.cc
pdns/rec_channel.hh
pdns/rec_channel_rec.cc
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh

- The NegCache and MemRecursorCache destructors were not deadlock free
when running from testrunner. The purpose of the code in the dts
is also unclear, so delete them.
- quit-nicely uses a volatile sig_atomic_t, which is not thread-safe
according to tsan. Replace by atomic<bool>.
I have:
Errors reported:
```
FATAL: ThreadSanitizer CHECK failed: ../../../../src/libsanitizer/sanitizer_common/sanitizer_deadlock_detector.h:67 "((n_all_locks_)) < (((sizeof(all_locks_with_contexts_)/sizeof((all_locks_with_contexts_)[0]))))" (0x40, 0x40)
#0 __tsan::TsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) ../../../../src/libsanitizer/tsan/tsan_rtl_report.cpp:47 (libtsan.so.0+0x972d2)
#1 __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, …
```

rec: Fix a few cases discoverd by tsan:

---

pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/docs/reference/dq.rst
regression-tests.dnsdist/test_EDNSOptions.py

Also document that some methods and attributes are not present on the DNSResponse object.
Fixes #10262.
I have:

dnsdist: Add missing getEDNSOptions and getDO bindings for DNSResponse

---

pdns/recursor_cache.cc

(cherry picked from commit ef726696aa4411d49f7d5400abb275c000718034)
Backport of #10232
I have:

rec: Backport 10232 to 4.5.x: Clear d_from if we don't know where the update came from

---

ext/luawrapper/include/LuaContext.hpp

via https://github.com/ahupowerdns/luawrapper/pull/38
This avoids a dnsdist crash when code returns an array-shaped table (i.e. `return {1,2,3}`).
I have:

lua: don't destroy keys during table iteration

---

pdns/dnspcap.cc
pdns/dnspcap.hh
pdns/dnsreplay.cc

This avoids:
```
dnspcap.cc:146:98: runtime error: member access within misaligned address 0x7ffc47a138d2 for type 'struct ip', which requires 4 byte alignment
0x7ffc47a138d2: note: pointer points here
00 00  08 00 45 00 00 54 06 83  00 00 40 11 76 14 7f 00  00 01 7f 00 00 01 89 f3  14 b4 00 40 fe 53
^ 
#0 0x564956a3f534 in PcapPacketReader::getUDPPacket() /home/peter/projects/powerdns/pdns/pdns/dnspcap.cc:146
#1 0x564956c4ed99 in main /home/peter/projects/powerdns/pdns/pdns/dnsscope.cc:230
#2 0x7f2f7c6bb09a in __libc_start_main ../csu/libc-start.c:308
#3 0x5649569182d9 in _start (/home/peter/projects/powerdns/pdns/pdns/dnsscope+0xd3f2d9)
```
I have:

fix read alignment in dnspcap

---

pdns/rec-lua-conf.cc

Catch PDNSException and clear on failure.
Fixes #10290 (but not the root (zz handling) cause).
I have:

Exception loading the RPZ seedfile is not fatal.

---

pdns/pdns_recursor.cc

If `setSwitch` is used `--help` will offer you `yes` or `no` but these quickly produce an exception in `asNum(..)` so just use `set` instead?
Otherwise should it have a `--disable-XYZ` like the packet cache does?
I have:

rec: update setting for aggressive-nsec-cache-size

---

pdns/validate.cc

It would be nice to log not only that a name is covered, but what entry actually covers it. This is useful in debugging crazy setups.
"works for me" but not sure how correct this is or if it's the correct place to be logging. 
I have:

rec: print the covering NSEC

---

pdns/filterpo.cc
pdns/recursordist/test-filterpo_cc.cc

Includes extra tests from @rgacogne and @omoerbeek.
This may not be the best fix - perhaps 'are we at the beginning of the string' is a better one. Perhaps spending some more time with this whole function is appropriate.
I also suspect we get this bit wrong:
>  If there exists more than one sequence of zero-valued fields of identical length, then only the last such sequence is compressed. 
I have:

rpz dumper: stop generating double zz labels on networks that start with zeroes

---

pdns/pdns_recursor.cc
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_ECS.py
regression-tests.recursor-dnssec/test_ProxyProtocol.py

The recursor was using the address of the proxy instead of the one of the proxied client to generate the EDNS Client Subnet value to send to authoritative servers.
Reported on the mailing-list: https://mailman.powerdns.com/pipermail/pdns-users/2021-April/027168.html
I reproduced the issue locally and tested the fix, but this PR could use a regression test.
I have:

rec: Use the correct ECS address when proxy-protocol is enabled

---

pdns/filterpo.cc
pdns/recursordist/test-filterpo_cc.cc

rec: Backport 10286 to rec 4.5.x: rpz dumper: stop generating double zz labels on networks that start with zeroes

---

pdns/rec-lua-conf.cc

Catch PDNSException and clear on failure.
(cherry picked from commit a47cc75dfa7519bcf7b31cee511852ae954a50f8)
Backport of #10291 
I have:

rec: Backport 10291 to rec-4.5.x: Exception loading the RPZ seedfile is not fatal.

---

pdns/pdns_recursor.cc

There's a typo in the `edns-padding-tag` option help, "`toclients`", introduced in 3d324e0067dcbc158a280282a5772f3309a4ef81.
I have:

rec: Fix typo in edns-padding-tag help

---

pdns/rec-lua-conf.cc

Catch PDNSException and clear on failure.
(cherry picked from commit a47cc75dfa7519bcf7b31cee511852ae954a50f8)
Backport of #10291 
I have:

rec: backport 10291 to rec-4.4.x: Exception loading the RPZ seedfile is not fatal.

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/docs/upgrade.rst

Since queries incoming over TCP are now also using the packet
cache, there is now also one packet cache instance per distributor
thread. Each cache instance has a size of max-packetcache-entries
divided by (threads + distributor-threads).
I have:

rec: Improve packet cache sizing.

---

pdns/misc.hh

SimpleMatch is called with user-supplied strings in the API and the bind backend. We might get away with it in most cases because std::strings are null-terminated, but it's still undefined behaviour as there is no guarantee that end() will point to the terminator.
Reported by cppcheck 2.4.1:
```
misc.hh:501:16: warning: Either the condition 'mi==d_mask.end()' is redundant or there is possible dereference of an invalid iterator: mi. [derefInvalidIteratorRedundantCheck]
while(*mi == '*') ++mi;
^
misc.hh:502:16: note: Assuming that condition 'mi==d_mask.end()' is not redundant
if (mi == d_mask.end()) return true;
^
misc.hh:501:16: note: Dereference of an invalid iterator
while(*mi == '*') ++mi;
```
Only the first commit is relevant for backports.
I have:

auth: Prevent dereferencing std::string::end() in SimpleMatch

---

pdns/dnsdist.hh

So that there is no race when these vaues are read by the SNMP or web threads and updated by the health check thread at the same time.
Reported by Thread Sanitizer in CircleCI:
```
WARNING: ThreadSanitizer: data race (pid=11167)
Write of size 8 at 0x7b7400002558 by thread T18:
#0 healthChecksThread() /opt/project/pdns/dnsdistdist/dnsdist.cc:1712:22 (dnsdist+0xf2a4a2)
#1 void std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)()) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:60:14 (dnsdist+0xf40ea2)
#2 std::__invoke_result<void (*)()>::type std::__invoke<void (*)()>(void (*&&)()) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:95:14 (dnsdist+0xf40e0d)
#3 decltype(std::__invoke(_S_declval<0ul>())) …
```

dnsdist: Make the backend queryLoad and dropRate values atomic

---

pdns/Makefile.am
pdns/dnsdistdist/Makefile.am
pdns/recursordist/Makefile.am

https://www.boost.org/users/history/version_1_76_0.html
> Replaced default standard exception classes with Boost.Container own classes, reducing considerably the included files overhead. Example: in MSVC 19 boost/container/vector.hpp preprocessed file size reduces from 1,5MB to 930KB. If you still want to use standard exception classes, you can define BOOST_CONTAINER_USE_STD_EXCEPTIONS before using any Boost.Container class.
I have:

boost 1.76 containers: use standard exceptions

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/docs/upgrade.rst

Backport of #10312 
I have:
- [X compiled this code

rec: Backport 10312 to rec 4.5.x: improve packet cache sizeing now that TCP answers are also cached

---

pdns/pdns_recursor.cc

(cherry picked from commit 07e8ae03d1ec61f6d8f2577cf16a76889bbdd832)
Backport of #10318, taking the better wording.
I have:

rec: Backport 10318 to rec-4.5.x: Fix typo in edns-padding-tag help

---

.circleci/config.yml
modules/gpgsqlbackend/spgsql.cc
regression-tests/backends/gpgsql-master
regression-tests/start-test-stop

#2743 introduced support for 'multiple result sets' from Postgres (and MySQL). For Postgres, this needed the wrapping of even simple `SELECT` queries in transactions so that the 'refcursor' result sets would not get freed before we could get to them. That PR did not contain tests for the functionality.
(For reference, that would make the test in -this- PR work if the function looked more like:
```
CREATE FUNCTION basic_query(incoming_type varchar(10), incoming_name varchar(255))
RETURNS REFCURSOR AS $$
DECLARE
ref refcursor;
BEGIN
OPEN ref FOR SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=false and type=incoming_type and name=incoming_name;
RETURN ref;
END;
$$ LANGUAGE plpgsql;
```
)
Later, #3477 added an `#ifdef` because the code in #2743 relied on …

auth gpgsql: add stored procedure test, drop refcursor support

---

pdns/filterpo.cc
pdns/recursordist/test-filterpo_cc.cc

rec: Backport 10286 to rec 4.4.x: rpz dumper: stop generating double zz labels on networks that start with zeroes

---

pdns/recursordist/docs/lua-scripting/hooks.rst

Maybe this example did at one point, but right now... it doesn't actually do that. 
If we want it to actually do that... just close this and I'll try to PR the fix when I get a chance.
I have:

rec: Update hooks.rst

---

pdns/dnsdistdist/dnsdist-dynblocks.cc
pdns/dnsdistdist/docs/advanced/ebpf.rst
pdns/dnsdistdist/docs/guides/dynblocks.rst
pdns/dnsdistdist/docs/reference/config.rst

This PR updates the default cleanup interval for eBPF dynamic blocks from 300s to 60s. We are now using them by default when available and the default value was too long. It also adds a missing check so that only "drop" dynamic blocks are converted to eBPF. 
Fixes #10324.
I have:

dnsdist: Only use eBPF for "drop" actions, clean up more often

---

pdns/dnscrypt.cc
pdns/dnscrypt.hh

In theory these functions should already be protected by the Lua lock but better safe than sorry.
Found while working on the migration to LockGuarded.
I have:

dnsdist: Fix missing locks in DNSCrypt certificates management

---

pdns/dnsdist-lua-bindings-dnsquestion.cc
regression-tests.dnsdist/test_EDNSOptions.py

Backport of #10267 to rel/dnsdist-1.5.x.
(cherry picked from commit e292b91b89827450ca116a8fe7dbca146705ba3b)
I have:

dnsdist-1.5.x: Add missing getEDNSOptions and getDO bindings for DNSResponse

---

docs/upgrading.rst
pdns/lua-record.cc

Bumping default timeout  to 2s  for ifportup and ifurlup lua functions like described in the related documentation.
Fixes #10357.
I have:

auth: change default timeout to 2s for lua records

---

.not-formatted
pdns/Makefile.am
pdns/histogram.hh
pdns/mtasker.cc
pdns/mtasker.hh
pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/responsestats.cc
pdns/responsestats.hh
pdns/syncres.hh
pdns/tcpreceiver.cc
regression-tests.api/test_Servers.py

Start using new generic (atomic) histogram code and while there, fix a bug
concerning the rcode stats (which was not passed in by the caller by rec).
Note that this changes the histogram: instead of lumping all large counts into the last 2^16-1 bucket., there is an explicit bucket with bound MAX_UINT64
So the existing code has buckets
```
... 64800 65000 65535
``` 
with all values > 6500 end up in the last, we now have
```
... 64800 65000 MAX_UINT64
```
Draft since I have not tested auth yet.
I have:

rec: Fix TSAN complaints: max stacksize and response stats size counters

---

pdns/pdns_recursor.cc
regression-tests.recursor-dnssec/test_Lua.py

We do special case the `qname RPZ` processing after a `gettag_ffi` hit, leading to `dns64` to not be applied in that case. This commit adds `dns64` handling to the special case.
<strike>Needs regression tests.</strike>
I have:

rec: Apply dns64 on RPZ hits generated after a gettag_ffi hit

---

pdns/pdns_recursor.cc
regression-tests.recursor-dnssec/test_Lua.py

rec: Backport 10353 to rec 4.5.x: Apply dns64 on RPZ hits generated after a gettag_ffi hit 

---

pdns/dnssecinfra.cc

`DNSCryptoKeyEngine::makeFromISCFile()`, called by `pdnsutil import-zone-key` or the API, for example, would try to parse almost all values as a base64 string. Depending on the version of OpenSSL, it could have led to a weird `Error: BIO_read failed to read all data from memory buffer` error when the file contains a non-base64 value, like for example:
```
Flags: 257
```
Recent versions of OpenSSL seem to simply return that the value could not be parsed, but older ones (OpenSSL 1.0.2k from CentOS 7 for example) would report an incomplete read (`BIO_should_retry()` returning 1), triggering an exception that prevents the key from being loaded.
This commits keeps a longer list of known non-base64 values, but more importantly catch the base64 decoding exception and then store the initial value …

auth: Don't choke on non-base64 values when importing zone keys

---

pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/aggressive_nsec.hh

When a new NSEC3 record has a different salt than the one we know, we update the zone entry with the new salt. Unfortunately, that salt was read without holding the lock in `AggressiveNSECCache::getNSEC3Denial`, leading to a possible data race.
I have:

rec: Prevent a race in the aggressive NSEC cache

---

pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/aggressive_nsec.hh

When a new NSEC3 record has a different salt than the one we know, we
update the zone entry with the new salt. Unfortunately, that salt was
read without holding the lock in `AggressiveNSECCache::getNSEC3Denial`,
leading to a possible data race.
(cherry picked from commit 779f35b41c758bed9215d51df4fc3a69edbada9d)
Backport of #10375 
I have:

rec: Backport 10375 to rec-4.5.x: Prevent a race in the aggressive NSEC cache

---

.dockerignore

because we ignore **/*.1 to not drag built manpages into the docker
context - but this also prevents any tags ending in .1 (like rec-4.5.1)
from being built
I have:

.dockerignore: do not ignore .git

---

pdns/recursordist/docs/upgrade.rst

There were both "New Settings" and "New settings" sections in the Recursor 4.5 upgrade guide.
Also use more consistent capitalization and wording and remove a trailing space. :)
I have:

Combine duplicate sections in Recursor upgrade guide

---

pdns/recursordist/docs/settings.rst

Properly document that _refresh-on-ttl-perc_ was introduced in 4.5.0 - guess the colon went missing.
I have:

Fix docs: refresh-on-ttl-perc was added in 4.5.0

---

pdns/histogram.hh
pdns/lock.hh

Pdns did not compile on fedora 34
I have:

add missing includes (Fedora 34, gcc 11.1 / clang 12)

---

docs/settings.rst
docs/upgrading.rst
pdns/common_startup.cc

auth: change the consistent-backends default to 'yes'

---

pdns/dnsdist-rings.hh
pdns/dnsdist.hh
pdns/dnsdistdist/docs/advanced/tuning.rst
pdns/dnsdistdist/test-dnsdistrings_cc.cc

Reducing the space lost to padding and thus the memory usage. This change saves 1 MB of memory per downstream server in the default configuration, and around 8 bytes per entry in the ring buffer. It also adds a few words about memory consumption in the documentation.
I have:

dnsdist: Reorganize the IDState and Rings fields

---

docs/settings.rst
docs/upgrading.rst
pdns/common_startup.cc
pdns/dbdnsseckeeper.cc
regression-tests.api/test_Zones.py

A high number of iterations is a waste of resources and is not future proof .
I have:

auth: lower max-nsec3-iterations to 100

---

docs/manpages/pdnsutil.1.rst
pdns/pdnsutil.cc

Add an option to in/exclude disabled zones in the pdnsutil list-all-zone and list-keys output.
Use at() for command line options (second commit).
I have:

auth: add an option to in/exclude disabled zones in the pdnsutil list-all-zone and list-keys output.

---

pdns/common_startup.cc
pdns/test-dnsname_cc.cc

No real issue:
```
test-dnsname_cc.cc: In member function ‘void test_dnsname_cc::test_compare_canonical::test_method()’:
test-dnsname_cc.cc:684:26: warning: loop variable ‘b’ of type ‘const string&’ {aka ‘const std::__cxx11::basic_string<char>&’} binds to a temporary constructed from type ‘const char* const’ [-Wrange-loop-construct]
684 |   for(const std::string& b : {"bert.com.", "alpha.nl.", "articles.xxx.",
|                          ^
test-dnsname_cc.cc:684:26: note: use non-reference type ‘const string’ {aka ‘const std::__cxx11::basic_string<char>’} to make the copy explicit or ‘const char* const&’ to prevent copying
```
and 
```
common_startup.cc: In function ‘void mainthread()’:
common_startup.cc:617:24: warning: loop variable ‘algotype’ of type ‘const string&’ {aka ‘const …
```

Fix 'temporary used in loop' warnings reported by g++ 11.1.0

---

modules/bindbackend/bindbackend2.cc
modules/bindbackend/bindbackend2.hh
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
modules/remotebackend/httpconnector.cc
modules/remotebackend/remotebackend.cc
modules/remotebackend/remotebackend.hh
pdns/backends/gsql/gsqlbackend.cc
pdns/backends/gsql/gsqlbackend.hh
pdns/dnsbackend.hh
pdns/slavecommunicator.cc

A failed SOA lookup triggered by a notify was not retried. The log message told that a recheck was scheduled, but this was a lie.
This pull will improve the reliability of notifies, especially on servers with a large number of zones.
I have:

auth: make sure we recheck failed SOA lookups for notifies

---

docs/manpages/pdns_control.1.rst
docs/manpages/pdnsutil.1.rst
pdns/dnsbackend.hh
pdns/dynhandler.cc
pdns/pdnsutil.cc
pdns/receiver.cc

The old versions of the commands are still available for compatibility reasons. The tests are not modified and still use the old version of the commands, to make sure they still work as expected. We should change this at a later date.
Both tools now consistently use 'zone'. Before this  pull it was a mix of 'domain' and 'zone'.
I have:

auth: use primary and secondary for pdnsutil and pdns_control commands 

---

modules/bindbackend/bindbackend2.cc
modules/bindbackend/bindbackend2.hh
modules/remotebackend/remotebackend.cc
modules/remotebackend/remotebackend.hh
pdns/auth-zonecache.cc
pdns/backends/gsql/gsqlbackend.cc
pdns/backends/gsql/gsqlbackend.hh
pdns/dnsbackend.hh
pdns/packethandler.cc
regression-tests.nobackend/supermaster-unsigned/command

- New auto-secondary zones were not added to the zone-cache
- Delete and recreate a zone within one refresh cycle could result in the cache returning the old zoneid for this zone
I have:

auth: zone-cache improvements

---

pdns/dnsdist-snmp.cc
pdns/dnsdist.cc

Unless I'm mistaken, the report (below) is a false positive since `std::atomic<T>::operator T` is equivalent to `load()` and
`std::atomic<T>::operator=` to `store()`, but perhaps I'm missing something.
Note that I could not reproduce the issue using clang++ 11.1.0's TSAN, only with the one from g++ 11.1.0.
```
==================
WARNING: ThreadSanitizer: data race (pid=11157)
Atomic read of size 8 at 0x7b7400002580 by thread T2:
#0 __tsan_atomic64_load <null> (dnsdist+0x7a6eb0)
#1 std::atomic<double>::load(std::memory_order) const /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/atomic:250:2 (dnsdist+0x83c4da)
#2 pdns::stat_t_trait<double>::operator double() const /opt/project/pdns/dnsdistdist/./stat_t.hh:67:60 (dnsdist+0xd05b2e)
#3 …
```

dnsdist: Fix a data race reported by TSAN in SNMP metrics

---

pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/tsan.supp

We might indeed be off by a few connections in the "maximum connections seen" counter, but we don't care that much.
TSAN report was:
```
WARNING: ThreadSanitizer: data race (pid=10555)
Atomic write of size 8 at 0x7b74000023c0 by thread T5:
#0 __tsan_atomic64_fetch_sub <null> (dnsdist+0x7a9ea9)
#1 std::__atomic_base<unsigned long>::operator--() /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/atomic_base.h:304:16 (dnsdist+0x82537f)
#2 pdns::stat_t_trait<unsigned long>::operator--() /opt/project/pdns/dnsdistdist/./stat_t.hh:52:14 (dnsdist+0xed91a5)
#3 TCPConnectionToBackend::~TCPConnectionToBackend() /opt/project/pdns/dnsdistdist/./dnsdist-tcp-downstream.hh:58:7 (dnsdist+0xeed22c)
#4 void __gnu_cxx::new_allocator<TCPConnectionToBackend>::destroy<TCPConnectionToBackend>(T …
```

dnsdist: Add a suppression for a race in TCP stats reported by TSAN

---

pdns/pdns_recursor.cc
pdns/syncres.cc

It started with just adjusting loglevels, but then I saw that the code to set the loglevel did not take into account `g_quiet` properly.
Should fix #10395
I have:

Take into account g_quiet when determing loglevel and change a few loglevels

---

docs/backends/generic-postgresql.rst
docs/settings.rst
docs/upgrading.rst

Fixes the version of removal of `local-ipv6` and fixes several sphinx warnings as well.
I have:

Fix the upgrade guide for local-ipv6 + other doc fixes

---

builder-support/dockerfiles/Dockerfile.rpmbuild

This unbreaks the oraclelinux-8 build and prevents future problems. It also means our deps and headers are newer.
I have:

builder rpmbuild: run yum upgrade first

---

builder-support/debian/recursor/debian-buster/control
builder-support/dockerfiles/Dockerfile.target.debian-bullseye
builder-support/dockerfiles/Dockerfile.target.debian-bullseye-amd64
builder-support/dockerfiles/Dockerfile.target.debian-bullseye-arm64

Add Debian bullseye Dockerfiles.
Related to #10406.
I have:

builder-support: add Debian bullseye dockerfiles

---

pdns/dnsdist-ecs.cc
pdns/test-dnsdist_cc.cc

Some queries (some NOTIFY, for example) have non-empty answer section. Our code handling the addition of EDNS Client Subnet was not properly handling that case when there was no existing EDNS in the query, or more precisely when the additional section was empty.
Closes #10409.
Supersedes #10410.
I have:

dnsdist: Properly handle ECS for queries with ancount or nscount > 0

---

pdns/recursordist/test-syncres_cc9.cc
pdns/syncres.cc

It happens if the server does not know about the DS special case.
Treat the delegation as a unsigned NODATA answer in that case.
For example for sthc.nordlo.cloud we go from the existing:
```
[1]   sthc.nordlo.cloud: Resolved 'nordlo.cloud' NS ns2.zetup.se to: 159.253.27.75
[1]   sthc.nordlo.cloud: Trying IP 159.253.27.75:53, asking 'sthc.nordlo.cloud|DS'
[1]   sthc.nordlo.cloud: Got 3 answers from ns2.zetup.se (159.253.27.75), rcode=0 (No Error), aa=0, in 35ms
[1]   sthc.nordlo.cloud: accept answer 'sthc.nordlo.cloud|NS|ns2.loopia.se.' from 'nordlo.cloud' nameservers? ttl=3600, place=2 YES!
[1]   sthc.nordlo.cloud: accept answer 'sthc.nordlo.cloud|NS|ns1.loopia.se.' from 'nordlo.cloud' nameservers? ttl=3600, place=2 YES!
[1]   sthc.nordlo.cloud: OPT answer '.' from 'nordlo.cloud' …
```

rec: Don't follow referral from the parent to the child for DS queries

---

modules/bindbackend/bindbackend2.cc
modules/bindbackend/bindbackend2.hh
modules/gpgsqlbackend/gpgsqlbackend.cc
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
modules/remotebackend/remotebackend.cc
modules/remotebackend/remotebackend.hh
pdns/backends/gsql/gsqlbackend.cc
pdns/backends/gsql/gsqlbackend.hh
pdns/dnsbackend.hh
pdns/packethandler.cc
pdns/ueberbackend.cc
pdns/ws-auth.cc

Remove the zone id code from create(Slave)Domain(). This code was adding a lot of complexity to the backends and was also slightly wrong in the gsql backends.
- A zone is now added to the zone-cache after the create transaction is committed (api). 
- The auto secondary code is now verifying the creation of the zone before it is added to the zone-cache.
Closes: #10453
I have:

auth: simplify createDomain()

---

m4/ax_check_sign.m4

When running autoreconf with ax_check_sign.m4, autoconf 2.71 complains
about the use of `AX_TRY_COMPILE`:
```
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:29: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:29: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
m4/ax_check_sign.m4:41: AX_CHECK_SIGN is expanded from...
m4/pdns_check_time_t.m4:1: PDNS_CHECK_TIME_T is expanded from...
configure.ac:29: the top level
```
This updates the macro to use `AC_COMPILE_IFELSE`, which has been …

Update AX_CHECK_SIGN for autoconf 2.71

---

pdns/recursor_cache.cc
pdns/recursordist/Makefile.am
pdns/recursordist/taskqueue.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc.hh
pdns/recursordist/test-syncres_cc2.cc
pdns/syncres.cc

When SyncREs is running in refresh-almost-expired mode, we should
not consider NS and their A/AAAA records to be almost expired, that
can cause refetch propagation all the way up to the root and marking
of nameservers as non-resolving.
Issue reported on IRC by ph1.
I have:

rec: When refreshing, do not consider root almost expired 

---

pdns/recursordist/test-syncres_cc5.cc
pdns/syncres.cc

For wildcard-expanded answers we need to collect the proof that the
exact name does not exist and add them to the response. We also
collect that proof for negative answers.
When the answer is a wildcard-expanded NODATA, we only need to collect
them once, not twice.
(cherry picked from commit d89f023d1bd6ae7d0eb6d72e7b2771363f5e4f79)
Backport of #10350
I have:

rec: Backport of 10350 to rex-4.5.x: Only add the NSEC and RRSIG records once in wildcard NODATA answers

---

pdns/pdns_recursor.cc
pdns/syncres.cc

(cherry picked from commit cf02f990a7fb9398aa4b13373c7ae35f7d2d47e3)
Backport of #10396 
I have:

rec: Backport 10396 to rec-4.5.x: Take into account q_quiet when determing loglevel and change a few loglevels.

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/docs/upgrade.rst

Backport of #10440 
Don't forget to forward port the docs changes!
I have:

Backport 10440 to rec 4.5.x: Change nsec3-max-iterations default to 150 

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/4.4.rst
pdns/recursordist/docs/changelog/4.5.rst
pdns/recursordist/docs/settings.rst
pdns/recursordist/docs/upgrade.rst

https://builder.powerdns.com/#/builders/97/builds/1876
https://builder.powerdns.com/#/builders/97/builds/1877
https://blog.powerdns.com/?p=3507&preview=true
Secpoll update is intentionally missing, since it wikl conflict with the 4.4.4 release anyway.
I have:

Rec: Prep for 4.4.4 and 4.5.2

---

pdns/dnsdist-lua.cc
pdns/dnsdist-lua.hh
pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc

dnsdist does not use most of the configuration in client mode, mostly caring about the settings needed to access the console, but we still need to parse all directives and create objects due to the way our Lua parsing works. We don't, however, need to allocate the whole storage needed for packet caches, for backend states or for the in-memory ring buffers.
This reduces the memory consumption of a console client to roughly 1 MB from hundreds of them in some cases.
I have:

dnsdist: Skip some memory allocations in client mode

---

pdns/speedtest.cc

speedtest: Fix QType::getName() renamed to QType::toString()

---

dockerdata/dnsdist-resolver.lua

Supports multiple IP addresses for the dnsdist-resolver lua script.
It does this by creating server names with the ip adresses embedded. `server#ip`
I have:

Support multiple ip addresses for dnsdist-resolver lua script

---

docs/backends/remote.rst

* Somewhere between PowerDNS 4.2 and 4.4, `GetAllDomainMetadata` became mandatory: a backend returning 404 (+ html error page) will result in PowerDNS responding with `SERVFAIL`:
```
Mar 25 21:57:32 ip-10-80-68-222 pdns_server[2795931]: Cannot parse JSON reply: expected value, got '<' (60)
Mar 25 21:57:32 ip-10-80-68-222 pdns_server[2795931]: Backend reported condition which prevented lookup (Exception caught when receiving: Unknown error while receiving data) sending out servfail
````
* `GetDomainMetadata` and `GetAllDomainMetadata` state `false` can be returned, but doing this results in an error (sorry, I did not capture the exact log message)
I have:
-

Fix documentation around get*DomainMetadata

---

pdns/pdns_recursor.cc

When processing multiple UDP packets in `handleNewUDPQuestion`, we should start with an empty vector.
I tried to create a regression test for this, but the current framework does not allow for triggering the "process multiple UDP packets" case in an easy way.
Found by reading code.
I have:

rec: Clear the current proxy protocol values each iteration

---

pdns/packethandler.cc
pdns/rfc2136handler.cc

Fixes #10321.
Fixes #10516.
I have:

auth 2136: allow placing DNSKEY/CDS/CDNSKEY regardless of direct-dnskey setting

---

pdns/recursordist/test-syncres_cc7.cc
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/basicDNSSEC.py

*Preliminary* backport of 10518; wil be updated once test(s) has been added.
I have:

rec: Backport of 10518 to 4.5.x: Make sure that we pass the SOA along the NSEC(3) proof for DS queries

---

pdns/recursordist/test-syncres_cc7.cc
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/basicDNSSEC.py

If the client is requesting a DS that does not exist, we need to provide the SOA (+RRSIGs) along with the NSEC(3) proof (+RRSIGs) and we might not have it if we picked up the proof from a delegation, in which case we need to keep on to do the actual DS query.
It used to work before 4.5.0 because the zone cuts determination code was requesting the DS records before doing any resolution, so we would get the denial and the SOA at the very beginning and not replace it on a delegation because we knew the zone was Insecure at that point.
Note that we still want to use the "no SOA denial" for internal zone cuts computation since we don't care about the SOA at that point, and that saves quite some outgoing queries.
Still needs some tests (unit and perhaps regression ones).
I have:

rec: Make sure that we pass the SOA along the NSEC(3) proof for DS queries

---

pdns/ueberbackend.cc

Looks like there is a missing rename of QType.getName() to QType.toString().
I have:

auth: fix compilation issue

---

pdns/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.hh
pdns/dnsdistdist/dnsdist-tcp-upstream.hh
pdns/dnsdistdist/test-dnsdisttcp_cc.cc
pdns/dnsparser.hh
regression-tests.dnsdist/test_AXFR.py

Added logic to parse SOA records for XFR transfers and figure out if the XFR transfer is finished.
Resolves #10436
I have:

dnsdist: Make DNSDist XFR aware when transfer is finished

---

regression-tests.dnsdist/test_Caching.py

The value of the TTL for negative answers was capped to 1s, which means that the answer will only be present in the cache for the current second. If the test starts at the end of a second in unix time, there is a real risk that the entry is no longer usable when we try to fetch it from the cache.
Increase the TTL to 2s instead to reduce that risk.
I have:

dnsdist: Increase the TTL of test answers to prevent spurious failures

---

pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/docs/advanced/tls-sessions-management.rst
pdns/dnsdistdist/docs/guides/dns-over-https.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/reference/constants.rst
pdns/dnsdistdist/docs/rules-actions.rst
pdns/dnsdistdist/docs/upgrade_guide.rst
regression-tests.dnsdist/test_Spoofing.py

This is the FFI equivalent to `DNSQuestion:spoof()` [1]
I believe this closes #10456.
[1]: https://dnsdist.org/reference/dq.html#DNSQuestion:spoof
I have:

dnsdist: Add FFI functions to spoof multiple raw values 

---

pdns/histogram.hh
pdns/pdns_recursor.cc
pdns/rec_channel.hh
pdns/rec_channel_rec.cc
pdns/recursordist/docs/metrics.rst
pdns/recursordist/docs/settings.rst
pdns/recursordist/rec_metrics.hh
pdns/recursordist/test-histogram_hh.cc
pdns/responsestats.hh
pdns/syncres.cc
pdns/syncres.hh
pdns/ws-recursor.cc

An aproach at #9077
Main things to consider:
1. All stats are new (to not disturb people using the old ones) and cumulative as this is the standard way for Prometheus
2. for cumulAnswers I also record packet cache hits (existing histograms do do not)
3. I use a 1-2-5 steps in microseconds. e.g:
```
pdns_recursor_cumul_answers_seconds_bucket{le="1e-05"} 0
pdns_recursor_cumul_answers_seconds_bucket{le="2e-05"} 0
pdns_recursor_cumul_answers_seconds_bucket{le="5e-05"} 1
pdns_recursor_cumul_answers_seconds_bucket{le="0.0001"} 1
pdns_recursor_cumul_answers_seconds_bucket{le="0.0002"} 2
pdns_recursor_cumul_answers_seconds_bucket{le="0.0005"} 2
pdns_recursor_cumul_answers_seconds_bucket{le="0.001"} 2
pdns_recursor_cumul_answers_seconds_bucket{le="0.002"} 2 …
```

Rec: cumulative and Prometheus friendly histograms

---

regression-tests.dnsdist/test_Caching.py

With the previous 1s TTL, the entry was only valid for the current second, but we might have been very near the end of that second already when inserting. With a 2s TTL (which was apparently intended anyway) we have a full second before the entry expires.
I have:

dnsdist: Use a 2s TTL in testCacheNoStale to prevent failures

---

regression-tests.dnsdist/test_Carbon.py

It seems to fail quite frequently these days, and that gives us two whole more seconds before timing out, which hopefully should be enough in most cases.
I have:

dnsdist: Add some leeway for the carbon data to reach the test receiver

---

docs/upgrading.rst

Upgrade Notes should say farewell to query-local-address6 as well.
I have:

docs: query-local-address6 has been removed in #10251 as well

---

pdns/ueberbackend.cc

This fixes that UeberBackend::addCache always uses d_cache_ttl, rather than the last TTL lower than d_cache_ttl. The old behavior leads to potentially undesirable results in case of ANY lookups.
I have:

auth: make UeberBackend::addCache pick the correct ttl

---

modules/bindbackend/bindbackend2.cc
modules/bindbackend/bindbackend2.hh
modules/bindbackend/binddnssec.cc
pdns/pdnsutil.cc

* keep, inside the bindbackend, the nsec(3) settings consistent with the 'rectification' applied on zone load. This avoids crashes when nsec3 is enabled or disabled without reloading the zone in the bindbackend.
* purge auth caches on bindbackend zone reload
I have:

auth bindbackend: NSEC(3) setting consistency, reload improvements

---

pdns/pdns_recursor.cc
pdns/recursordist/docs/settings.rst

a05df8bd4
remove DNS_OVER_TLS guard around applying the dot-to-port-853 setting
before this commit: pointing a forward at port 853, without DoT support,
causes Recursor to attempt to do UDP over port 853 to the upstream. This
rarely works.
after this commit: much swifter failure with an error log message saying
`45.55.10.200:853 requested but not available`
b42f9eb31
emit error when dot-to-auth-names is set without DoT support
3f2abbbe0
toTimestampStringMilli is only called from inside this file, make it static
e1cab5663153c17eca8f40574e6029be7bfb7dc9
rec docs: fix warnings
I have:

rec: assorted improvements

---

pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/syncres.cc
pdns/syncres.hh

Instead of accepting answer records in AA=0 responses, which might have lowered the sanity checks applied to these records, this PR fixes the AA bit on responses containing one or more answer records received from an authoritative server that is allowed to send them. Basically, we detect that the server is broken and doesn't know shit about DNS, and we set the AA bit to 1, as the server should have done.
With great sadness, this PR is acknowledging that it is easier to make the code of well-maintained software more complicated than it is to get some well-known vendors to fix their "products". Fixes #8150.
I have:

rec: Work around clueless servers sending AA=0 answers 

---

pdns/dnsdist-cache.cc
pdns/dnsdist-cache.hh
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdist-protobuf.cc
pdns/dnsdist-snmp.cc
pdns/dnsdist-tcp.cc
pdns/dnsdist-xpf.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-idstate.cc
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-proxy-protocol.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/test-dnsdistkvs_cc.cc
pdns/dnsdistdist/test-dnsdistlbpolicies_cc.cc
pdns/dnsdistdist/test-dnsdistrules_cc.cc
pdns/dnsdistdist/test-dnsdisttcp_cc.cc
pdns/dnstap.cc
pdns/dnstap.hh
pdns/dnstap.proto
pdns/lwres.cc
pdns/test-dnsdist_cc.cc
pdns/test-dnsdistpacketcache_cc.cc
regression-tests.dnsdist/test_Advanced.py
regression-tests.dnsdist/test_DNSCrypt.py
regression-tests.dnsdist/test_DOH.py
regression-tests.dnsdist/test_TLS.py

This turned out to be more difficult than I expected. Part of the work already existed in #10338 but was not enough to be able to pass the right protocol to dnstap, which I wanted to do since it now supports DoT and DoH (updated dnstap.proto is included in this PR).
Fixes https://github.com/PowerDNS/pdns/issues/10497.
I added the "backport to dnsdist-1.6.x" label because I think we need to fix the dnstap issue on that branch as well, but we clearly should not backport this PR. Perhaps a simple test on whether the request was received over DoH (dq.du is not `nullptr` would be enough for 1.6.x?
I have:

dnsdist: Carry the exact incoming protocol (Do53, DNSCrypt, DoT, DoH) in DQ

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/rules-actions.rst

dnsdist: Implement 'reload()' to rotate Log(Response)Action's log file

---

pdns/dnsdistdist/docs/quickstart.rst

This PR fixes two small typos in the dnsdist docs. Very minor but figured I'd correct them nonetheless.
I have:

fix: dnsdist docs quickstart typo

---

pdns/recursordist/test-syncres_cc3.cc
pdns/recursordist/test-syncres_cc4.cc
pdns/syncres.cc
pdns/syncres.hh

Backport 10555 to rec 4.5.x: Work around clueless servers sending AA=0 answers

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-lua-ffi.hh
pdns/dnsdistdist/dnsdist-rules.cc
pdns/dnsdistdist/dnsdist-rules.hh
pdns/dnsdistdist/docs/advanced/tuning.rst
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_Advanced.py

This allows Lua FFI rules and actions that don't need access to the global, shared Lua state to be lock-less, avoiding lock contention.
I have:

dnsdist: Add support for Lua per-thread FFI rules and actions

---

pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc10.cc
pdns/recursordist/test-syncres_cc6.cc
pdns/syncres.cc
pdns/syncres.hh

Since 4.5.0 we do not pre-compute the zone cuts at the start of the resolution process, which saves a lot of queries but also works around broken DNS implementations that do not handle DS queries correctly. Unfortunately before this PR we were sometimes misled by signed, broken but insecure zones (no DS at the parent) and could return an erroneous Bogus status.
This PR keeps the global logic introduced in 4.5, following the hint provided by the signer field in signatures, since that works fine for 99% of the cases, but double-checks whether we missed a zone cut if the answer does not validate properly.
I have:

rec: Make really sure we did not miss a cut on validation failure

---

pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/test-aggressive_nsec_cc.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/validate.cc

Before that commit, the aggressive NSEC(3) cache could have mistakenly used NSEC3s from the parent zone to prove that a given name in the child zone did not exist, which is incorrect.
It happened because we did not properly detect that the NSEC3 for the closest encloser was an ancestor NSEC3 indicating a delegation, and then in the unlikely but possible case that we found a NSEC3 from the parent zone whose hashes covered the next closer we wrongly concluded that the name did not exist, returning a NXDomain with an invalid proof of denial.
This PR needs to be backported to rel/rec-4.5.x where the aggressive NSEC(3) cache was introduced.
It also explicitly sets the number of NSEC3 iterations in the unit tests that clearly depend on that (although I might have missed some) to prevent a …

rec: Ancestor NSEC3s can only deny the existence of a DS

---

pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/test-aggressive_nsec_cc.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/validate.cc

Backport of #10587 to rel/rec-4.5.x.
I have:

rec: Backport 10587 to rec-4.5.x: Ancestor NSEC3s can only deny the existence of a DS

---

docs/settings.rst
docs/upgrading.rst

A comment on https://blog.powerdns.com/2021/07/13/powerdns-authoritative-server-4-5-0/ rightfully said that the upgrade notes lack these words.
I have:

auth 4.5 upgrade notes and settings: more words on the zone cache

---

docs/changelog/4.5.rst
pdns/responsestats.cc
pdns/responsestats.hh
regression-tests/tests/type65535-query/command
regression-tests/tests/type65535-query/description
regression-tests/tests/type65535-query/expected_result

This fixes security advisory 2021-01.
I have:

auth: correct upper bounds on d_qtypecounters

---

pdns/dnsdistdist/docs/reference/dq.rst
pdns/dnsdistdist/docs/rules-actions.rst

It surprised me that setTagAction and setTagResponseAction didn't overwrite existing tag values. This adds a line to the docs so that future users aren't surprised by this.
I have:

Document setTag(Response)Action behaviour

---

pdns/mtasker.cc
pdns/mtasker.hh
pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/test-syncres_cc10.cc
pdns/syncres.hh

This PR moves to shared objects for the `PacketID` keys to the events index.
The TCP code already uses `shared_ptr<PacketID>`'s, but then passed the `*` object to the event code. Since the event code copies the keys (of type `PacketId`), updates to the state where not reflected after `waitEvent` returned. In the case of TCP timeouts than could lead to inconsistent state and FD actions.
This also moves everything (including the UDP code) to `shared_ptr<PacketID>` and fixes a bug where the regular `operator<` and the birthday compare functions did not agree.
Issues found while working on a "Keep TCP connections open" branch.
I have:

Rec: make all PacketIDs shared_ptr

---

pdns/dnsdistdist/docs/reference/config.rst

Document that using setECSOverride in front of Auth servers responding with ECS info can lead to downstream SERVFAIL responses when scopes no longer match and confuse clients (nameservers).
I have:

dnsdist: Document that setECSOverride has its drawbacks

---

m4/pdns_check_os.m4
pdns/kqueuemplexer.cc
pdns/lwres.cc
pdns/pdns_recursor.cc
pdns/rec-carbon.cc
pdns/recursordist/Makefile.am
pdns/ws-recursor.cc

Prep for testing the mplexer chnages in #10631 on MacOS, first make sure we're using kqueue. Plus some  general fixes.
I have:

Move MacOS to kqueue and assorted compile fixes

---

pdns/rpzloader.cc

Fixes #10625 in local testing.
There are still race conditions in this code, but this PR  should reduce them to microsecond opportunities instead of seconds/minutes. We should ponder a more fundemental approach to these "remove RPZ" cases.
I have:

rec: Check in more places if the policy has been updated before using or modifying it.

---

pdns/rpzloader.cc

(cherry picked from commit 0c98e3de2cf1daae3f7034803668c1ac10fefe49)
Backport of #10627 
I have:

rec: backport 10627 to rec 4.5.x: Check in more places if the policy has been updated before  using or modifying it.

---

pdns/decafsigners.cc

```
decafsigners.cc: In member function ‘virtual bool DecafED25519DNSCryptoKeyEngine::verify(const string&, const string&) const’:
decafsigners.cc:140:11: warning: catching polymorphic type ‘class decaf::CryptoException’ by value [-Wcatch-value=]
140 |   } catch(CryptoException) {
|           ^~~~~~~~~~~~~~~
decafsigners.cc: In member function ‘virtual bool DecafED448DNSCryptoKeyEngine::verify(const string&, const string&) const’:
decafsigners.cc:276:11: warning: catching polymorphic type ‘class decaf::CryptoException’ by value [-Wcatch-value=]
276 |   } catch(CryptoException) {
|           ^~~~~~~~~~~~~~~
```
On the other hand, I wonder if we should not drop the decaf code altogether since:
- 15 is provided by `libsodium` and recent versions of `OpenSSL`
- 16 is provided by recent …

Fix a warning about catching a polymorphic exception type by value

---

pdns/dnsdist.cc
regression-tests.dnsdist/test_Caching.py

We used to restore the RD and CD flags from the initial query before inserting the response into the cache. That would cause an issue if the flags had been altered, for example via `SetNoRecurseAction`, as the cache lookup is done _after_ the actions have been applied and thus after the flags altered.
If the initial query had the RD bit set, and thus was cleared by the rule, the response would have been inserted with the RD bit restored, and no lookup would then succeed because it would be done with the bit cleared.
This commit fixes the insertion to use the RD and CD bits as set in the response before restoring them, and restores the RD and CD bits after a cache hit as well, to ensure that:
- cache lookups are done after the rules are applied
- cache insertions are done before the flags …

dnsdist: Fix the wrong RD and CD flags being cached, causing misses

---

.not-formatted
pdns/devpollmplexer.cc
pdns/dnsdistdist/test-dnsdisttcp_cc.cc
pdns/epollmplexer.cc
pdns/kqueuemplexer.cc
pdns/mplexer.hh
pdns/pollmplexer.cc
pdns/portsmplexer.cc
pdns/test-mplexer.cc

This commit refactors our multiplexers to be able to wait for a descriptor to become readable OR writable at the same time.
I kept the two separate maps for an easier handling of the separate TTD and to limit the amount of changes, but we might want to mergethem into a single map in the future.
The accounting is moved into the parent class instead of being dealt with by the multiplexers themselves.
I noticed that the poll multiplexer allocates and fills a vector of pollfd for every call to run(), which seems wasteful, but I did not
want to touch that in this commit.
I did not compile or test the kqueue, ports and /dev/poll multiplexers yet, so don't merge this without testing them first.
I have:

Handle waiting for a descriptor to become readable OR writable

---

pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/docs/lua-config/rpz.rst
pdns/recursordist/docs/metrics.rst
pdns/recursordist/rec_metrics.hh
pdns/syncres.cc
pdns/syncres.hh
pdns/ws-recursor.cc

By default only exported via Prometheus.
This is not finished yet, after #10554 is merged the Prometheus help info should be added
to this branch. The current Prometheus HELP code does not handle multicounter stuff and that PR adds is.
I have:

rec: Keep a count of per rpz (or filter) hits

---

pdns/pdns_recursor.cc

rec: Fix wrong default value call for dot-to-port-853 setting

---

regression-tests/recursor-test

We see the occasional bulk test failures on buildbot (but not locally or on CirlceCI). So improve the script a bit to help diagnosis:
- Exit if rec did not start up
- Status requesting commands (rec_control and kill -USR1) failures are non-fatal
except for the last 'ping' so the dump of the recursor log is reached.
- Increase timeout of rec_control command (to help investigating issues on buildbot)
The script is run with -e, so failure will lead to exit without killing
the running recursor atm.
I have:

rec: Improve the rec bulk test script

---

pdns/cachecleaner.hh
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/negcache.cc
pdns/recursordist/negcache.hh

Since the migration to LockGuarded, the code keeping track of the contention of record and negative cache shard locks was bypassed and the lock directly acquired. This does not cause any other issue than the `record-cache-acquired` and `record-cache-contended` metrics not being updated.
This PR fixes that, and make the content private so we no longer can bypass that code in the future.
Note that it looks like we don't do anything about these metrics for the negative cache, even though we dutifully record them.
I have:

rec: Fix the acquired/contended cache counters not being updated

---

pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-idstate.cc
regression-tests.dnsdist/test_Caching.py

The fix in dbadb4d272a3317407e6bc934f55c2d41a87c0ac (#10650) actually introduced an issue, because the backend might not perfectly echo the RD and CD flags as they were in the query.
We can't use the "original" (before applying rules) flags either, so we need to store the flags as they were sent to the backend to be able to correctly store them in the cache.
I have:

dnsdist: Cache based on the DNS flags of the query after applying the rules

---

.circleci/config.yml
.github/workflows/secpoll.yml
build-scripts/docker/repo-test/templates/Dockerfile-debian.jinja2

Replace `apt-key` with `curl -o`
(Also merge some `apt-get update` / `apt-get install` docker stages as it's dangerous to have them split)
I have:

Replace apt-key with curl -o

---

pdns/dnsdistdist/dnsdist-tcp-downstream.hh
pdns/dnsdistdist/test-dnsdisttcp_cc.cc

When the client closes the TCP connection while we are still waiting for the backend to send at least one response, and the backend connection then terminates abnormally, we could have not properly reset the outstanding
counter of that backend.
Backport of #10705 to rel/dnsdist-1.6.x.
I have:

dnsdist-1.6.x: Fix outstanding counter issue

---

pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/test-dnsdisttcp_cc.cc

When the client closes the TCP connection while we are still waiting for the backend to send at least one response, and the backend connection then terminates abnormally, we could have not properly reset the outstanding
counter of that backend.
I have:

dnsdist: Fix outstanding counter issue when a TCP connection dies

---

pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/test-aggressive_nsec_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc.hh

No need to include the same record twice when it provides, at the same time, a proof that the closest encloser exists and that the next closer does not, and/or that the wildcard does not exist either.
This happens right away in a zone with a single record, like reported by Matt Nordhoff, but it might happen in other cases as well.
Fixes #10699.
I have:

rec: Fix the aggressive cache returning duplicated NSEC3 records

---

pdns/test-ueberbackend_cc.cc

Due to an oversight the QueryCache wasn't actually enabled for the UeberBackend unit tests cases where it should.
I have:

auth: actually use the QueryCache for the UeberBackend unit tests

---

pdns/recursordist/aggressive_nsec.cc
pdns/recursordist/test-aggressive_nsec_cc.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc.hh

No need to include the same record twice when it provides, at the same
time, a proof that the closest encloser exists and that the next closer
does not, and/or that the wildcard does not exist either.
This happens right away in a zone with a single record, like reported
by Matt Nordhoff, but it might happen in other cases as well.
(cherry picked from commit eca47c4dd85d2711ebc26767dfa78bdbce2c7f16)
Backport of #10701 
I have:

rec: Backport 10701 to rec-4.5.x: Fix the aggressive cache returning duplicated NSEC3 records

---

.github/actions/spell-check/expect.txt
pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/docs/metrics.rst
pdns/recursordist/test-histogram_hh.cc
pdns/syncres.hh
pdns/ws-recursor.cc

Process feedback from @johnhtodd and @wojas : better names and HELP and use a tag to distinguish
ipv4 and ipv6 for the new Prometheus-friendly histograms.
Followup to #10122 
I have:
Example output:
```
pdns_recursor_cumul_authanswers_seconds_count 5
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.001"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.001"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.002"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.002"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.005"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.005"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.01"} 1 …
```

rec: followup to Prometheus-friendly histograms (#10122)

---

regression-tests.api/requirements.txt
regression-tests.ixfrdist/requirements.txt

Breakage noticed on a rel/rec-4.4.x build. I am unsure why our master builds are not suffering.
I have:

require nose >= 1.3.7 everywhere

---

pdns/recursordist/test-syncres_cc6.cc
pdns/recursordist/test-syncres_cc8.cc
pdns/validate.cc

The existing code would not have accepted that proof anyway since the NSEC(3) are signed by a DNSKEY that would require fetching the corresponding DS, which causes a loop that would be detected, but it is cleaner to actually check this.
I don't think we need to backport this.
I have:

rec: Be more strict when validating DS wrt parent/child NSEC(3)s

---

.github/actions/spell-check/expect.txt
docs/manpages/sdig.1.rst
docs/settings.rst
modules/lua2backend/lua2api2.hh
modules/pipebackend/pipebackend.cc
modules/remotebackend/Makefile.am
modules/remotebackend/remotebackend.cc
pdns/Makefile.am
pdns/common_startup.cc
pdns/common_startup.hh
pdns/dnspacket.cc
pdns/dnspacket.hh
pdns/lua-auth4.cc
pdns/lua-record.cc
pdns/nameserver.cc
pdns/packethandler.cc
pdns/proxy-protocol.hh
pdns/responsestats-auth.cc
pdns/rfc2136handler.cc
pdns/sdig.cc
pdns/tcpreceiver.cc
pdns/tcpreceiver.hh
pdns/test-nameserver_cc.cc
regression-tests.auth-py/proxyprotocol.py
regression-tests.auth-py/test_ProxyProtocol.py

incoming PROXY support for:
* AXFR ACLs
* NOTIFY sources
* getting the remote address in LUA records
* 2136 ACLs
* query/response accounting
* log output
* the remote used by backends to take geo-style decisions
Fixes #8403.
Needs:
Check that backends use the right IP:
I have:

auth: incoming PROXY support

---

.github/actions/spell-check/expect.txt
pdns/dnsdist-lua-bindings.cc
pdns/dnsdistdist/dnsdist-svc.cc
pdns/dnsdistdist/dnsdist-svc.hh
pdns/dnsdistdist/docs/reference/svc.rst
regression-tests.dnsdist/test_SVCB.py

As every SVC parameter is technically optional, the syntax to create them should reflect this.
Fixes #10732.
I have:

dnsdist: accept a table to SVCParams for newSVCRecordParameters

---

pdns/rcpgenerator.cc
pdns/svc-records.cc
pdns/svc-records.hh
pdns/test-rcpgenerator_cc.cc

This allows PowerDNS to accept SVC Params like `key4=\192\000\002\222` or `key4=abcd`. I've included tests, but am not truly happy with the implementation and would like some comments.
I have:

SVCB: Accept known SVCParams in generic format

---

m4/ax_check_sign.m4

Backport of #10450 to rel/dnsdist-1.6.x.
When running autoreconf with ax_check_sign.m4, autoconf 2.71 complains
about the use of `AX_TRY_COMPILE`:
```
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:29: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:29: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
m4/ax_check_sign.m4:41: AX_CHECK_SIGN is expanded from...
m4/pdns_check_time_t.m4:1: PDNS_CHECK_TIME_T is expanded from...
configure.ac:29: the top level
```
This updates the macro to …

dnsdist-1.6.x: Update AX_CHECK_SIGN for autoconf 2.71

---

pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/test-dnsdisttcp_cc.cc

If the client has sent more than one concurrent query using the same query ID, we only send one response for all of these queries, and we should not mess up our outstanding queries counter.
That only happens when out-of-order queries are enabled in both the frontend and the backend.
I have:

dnsdist-1.6.x: Don't increase the outstanding counter on a duplicated ID over TCP

---

docs/secpoll.zone

It should be '1', not '3' as there is currently nothing to update to.
Currently dnsdist complains with:
```
PowerDNS DNSDist Security Update Mandatory: Unsupported pre-release
```
I have:

dnsdist: Fix secpoll for 1.7.0-alpha1

---

pdns/Makefile.am
pdns/speedtest.cc

Fixes #6492 (or at least gives us some data).
I have:
On old bullseye laptop:
```
'Random test sodium' 0.38 seconds: 1847879.0 runs/s, 0.54 usec/run
'Random test openssl' 0.12 seconds: 580113.7 runs/s, 1.72 usec/run
'Random test getrandom' 0.34 seconds: 1883117.4 runs/s, 0.53 usec/run
'Random test urandom' 0.51 seconds: 1649074.8 runs/s, 0.61 usec/run
```
Random buster VM:
```
'Random test sodium' 0.48 seconds: 1252499.3 runs/s, 0.80 usec/run
'Random test openssl' 0.12 seconds: 332932.7 runs/s, 3.00 usec/run
'Random test getrandom' 0.54 seconds: 1280666.6 runs/s, 0.78 usec/run
'Random test urandom' 0.45 seconds: 1115434.9 runs/s, 0.90 usec/run
```
on OpenBSD (pretty beefy AMD):
```
'Random test sodium' 0.10 seconds: 35829910.5 runs/s, 0.03 usec/run
'Random test openssl' 0.10 seconds: …
```

Add our various random implementations to speedtest

---

pdns/dnsrecords.hh
pdns/lwres.cc
pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/Makefile.am
pdns/recursordist/docs/settings.rst
pdns/recursordist/rec-tcpout.cc
pdns/recursordist/rec-tcpout.hh
pdns/ws-recursor.cc

This maintains open TCP/DoT connections to auth or forwarders.  If a new connection is needed to a specific IP, one from the idle set is used if available. Connections are put in the idle set after a query is done with some basic success. If a connection comes from the idle set, it might be closed by the peer, so the code has to be prepared that it may not work and a new one has to be requested from the set (and if not available, created).
There might be some overlap with (upcoming) dnsdist code, we should look into merging at some point.
But for now I want to publish this so people can review and test.
ATM this mechanism is enabled with `tcp-out-max-idle-ms=10000`, `tcp-out-max-idle-per-auth=10`, `tcp-out-max-queries=0` (no maximum) and `"tcp-out-max-idle-per-thread=100`. See the docs …

Rec: tcp/dot connection pooling

---

pdns/pdns_recursor.cc

pdns_recursor.cc:5069:67: error: non-constant-expression cannot be narrowed from type 'long long' to '__darwin_suseconds_t' (aka 'int') in initializer list [-Wc++11-narrowing]
TCPOutConnectionManager::s_maxIdleTime = timeval{millis / 1000, (millis % 1000) * 1000 };
I have:

rec: work around clang on MacOS being pedantic

---

pdns/speedtest.cc

Our tests are designed to run for 100 ms of CPU time, but this is currently measured with `ITIMER_VIRTUAL` which means only when the process is executing in userspace. Switching to `ITIMER_PROF` would also account for the time spent
when the system is running on behalf of the process, which seems closer to what we want.
It fixes the reported time often exceeding 100ms in the numbers reported for `sodium`, `getrandom` and `urandom` in #10753, as they spend most of their time in kernel space.
I have:

speedtest: Count the system time as well as the user time

---

pdns/dnsdistdist/docs/reference/netmaskgroup.rst

Current wording suggests the integer values do matter, while they are ignored.
I have:

dnsdist: Improve NetmaskGroup:addMasks docs

---

pdns/rpzloader.cc

This commit fixes two issues:
- if the existing zone name is not empty we should use it, instead of the zone domain
- if the zone domain has to be used, it should not include a final dot
I have:

rec: Use the correct RPZ policy name when loading via XFR

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/dnsdist-nghttp2.cc
pdns/dnsdistdist/dnsdist-nghttp2.hh

This commit raises the number of DoH workers to be at least 1, always, unless told otherwise via `setOutgoingDoHWorkerThreads(0)`.
In that last case it raises an exception if the console is used to declare a new DoH backend later on.
Fixes #10771.
I have:

dnsdist: Better handling of outgoing DoH workers

---

pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdistdist/doh.cc
regression-tests.dnsdist/test_OutgoingDOH.py

We used to tell the cache that the queries was received over TCP when inserting the response into the packet cache, which is obviously not true.
Reported by Denis Machard on the mailing-list [1].
[1]: https://mailman.powerdns.com/pipermail/dnsdist/2021-October/001122.html
I have:

dnsdist: Properly cache UDP queries passed to a TCP/DoT/DoH backend

---

pdns/recursordist/test-rec-zonetocache.cc

Fixes #10799
```
test-rec-zonetocache.cc: In member function 'void rec_zonetocache::test_zonetocache::test_method()':
test-rec-zonetocache.cc:77:27: sorry, unimplemented: non-trivial designated initializers not supported
.d_refreshPeriod = 0};
^
test-rec-zonetocache.cc:77:27: warning: missing initializer for member 'RecZoneToCache::Config::d_tt' [-Wmissing-field-initializers]
```
I have:

rec: Fix compile error on Ubuntu 18

---

pdns/rpzloader.cc

This commit fixes two issues:
- if the existing zone name is not empty we should use it, instead of
the zone domain
- if the zone domain has to be used, it should not include a final dot
(cherry picked from commit 3e86a970828dda814a140c9613311a8507c3c458)
Backport of #10768 
I have:

rec: Backport 10768 to rec 4.4.x: Use the correct RPZ policy name when loading via XFR

---

dockerdata/dnsdist-resolver.py

Remove debug log line printing a statement into stdout all the time.
I have:

Remove debug print line flooding logs

---

.github/workflows/build-and-test-all.yml
docs/settings.rst
modules/bindbackend/bindbackend2.cc
pdns/common_startup.cc
pdns/fuzz_zoneparsertng.cc
pdns/pdns_recursor.cc
pdns/pdnsutil.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/rec-zonetocache.cc
pdns/reczones.cc
pdns/rpzloader.cc
pdns/test-zoneparser_tng_cc.cc
pdns/ws-auth.cc
pdns/zone2json.cc
pdns/zone2ldap.cc
pdns/zone2sql.cc
pdns/zoneparser-tng.cc
pdns/zoneparser-tng.hh

- Stricter parsing of `$GENERATE` parameters
- Limit the number of nested `$INCLUDE` directives
I have:

ZoneParserTNG: Stricter checks when loading a zone file

---

pdns/pdns_recursor.cc
pdns/rec_channel.cc
pdns/rec_channel.hh
pdns/rec_control.cc

Nice consequences:
- No more need to set buffer sizes or have a large read buffer. 
- No more need to create a temporary socket for replies, a session concept is built into SOCK_STREAM sockets and we can just write the reply into the stream.
Survived basic testing here.
I have:

rec: Move to a stream based socket for the control channel

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst

This allows retaining the ability to create and use eBPF programs and maps at runtime, even if `kernel.unprivileged_bpf_disabled` is set, by keeping the `CAP_BPF` capability. It can be useful to prevent unprivileged programs on the system from loading eBPF while still allowing dnsdist to do so.
I have:

dnsdist: Add the ability to retain select capabilities at runtime

---

pdns/dnsdistdist/docs/reference/svc.rst

This is likely not an actual issue since most clients are not going to do any caching but let's document how to do the right thing and return NODATA for non-SVC types, instead of passing the query to the backend and likely getting a NXDOMAIN answer. 
I have:

dnsdist: Reply with NODATA for non-SVC types in the SVC documentation

---

pdns/dnsdist.cc

`addLocal("0.0.0.0:9999")` gives `Warning: IPV6_RECVPKTINFO setsockopt failed: Protocol not available` otherwise.
No idea how correct this is other than "works for me"
I have:

dnsdist: dont try to set IPV6_RECVPKTINFO on an ipv4 any bind?

---

modules/gmysqlbackend/gmysqlbackend.cc
modules/godbcbackend/godbcbackend.cc
modules/gpgsqlbackend/gpgsqlbackend.cc
modules/gsqlite3backend/gsqlite3backend.cc
pdns/ws-auth.cc
regression-tests.api/test_Zones.py

Some types only live apex and some are not allowed (or useful) there.
The info-all-master-query was also modified to make sure it will ignore non apex SOA records.
I have:

auth: api, check qtype location

---

pdns/dnsdistdist/test-dnsdisttcp_cc.cc
pdns/tcpiohandler.cc
pdns/tcpiohandler.hh

They are not needed and cause (at least on OpenBSD) firewall state table
clashes: they remain in a embryotic state because no actual activity
occurs on them due to the rest of the tests using mockup code.
tcpiohandler.cc is not linked into the tests, so define it locally in
test-dnsdisttcp_cc.cc as well.
Followup on the diagnosis made in #10976.
I have:

dnsdist: Disable the actual connect() in the test_dnsdisttcp_cc_c unit tests.

---

pdns/recursordist/docs/settings.rst

All (?) of the `forward-zones` options apply to `forward-zones-recurse` as well. Make sure we mention this in the docs
I have:

Clarify recursor docs for forward-zones-recurse

---

pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dnsdist-nghttp2.cc
pdns/dnsdistdist/dnsdist-nghttp2.hh
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.hh
pdns/dnsdistdist/docs/reference/tuning.rst
pdns/dnsdistdist/test-dnsdist-connections-cache.cc
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/test_AXFR.py

Reported by Coverity (CID 373724).
It also immediately removes a HTTP/2 connection from the list if it is no longer usable (TCP socket is dead).
I have:

dnsdist: Remove unreachable code in HTTP/2 connections cleanup

---

build-scripts/docker/repo-test/generate-repo-files.py

Add `rec-45` for Debian Bullseye to repo test script.

---

pdns/dnsdist-lua.cc

Broken in 4f69984102318ab9f2e9a7e97ceb6f8b377fcd93 (so affects beta1 only) by using a hard-coded value as upper bound instead of the value passed in parameter.
I have:

dnsdist: Fix Lua parameters bound checks

---

pdns/recursordist/docs/settings.rst

Provide a cross-reference so users will know that `forward-zones-file` can be used to specify NOTIFY-allowed zones.

rec: Add xref between allow-notify-for-file and forward-zones-file

---

.github/actions/spell-check/expect.txt
pdns/calidns.cc
pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/docs/reference/tuning.rst
pdns/dnsreplay.cc
pdns/iputils.cc
pdns/iputils.hh
pdns/pdns_recursor.cc

And raise them to 16777216 by default. Although perhaps we should only do that on Linux?
This PR also refactors the functions duplicated in the recursor, calidns and dnsreplay and therefore impacts the auth and the rec.
Closes #10898.
I have:

dnsdist: Add a function to set the UDP recv/snd buffer sizes

---

pdns/recursordist/rec-taskqueue.cc
pdns/recursordist/taskqueue.hh

(cherry picked from commit 671ca0dee0cb529856af414e5b00db1b8b1e4d95)
Backport of #11005 
I have:

rec: bacport 11005 to rec 4.6.x: Include sys/time.h; needed on musl

---

pdns/rfc2136handler.cc
regression-tests/tests/1dyndns-update-add-delete-mx/expected_result
regression-tests/tests/1dyndns-update-delete-mx-prio/expected_result
regression-tests/tests/1dyndns-update-replace-mx/expected_result
regression-tests/tests/1dyndns-update-srv/expected_result

auth-4.5.x: apply new TTL to whole RRset, not only to the added record

---

regression-tests.recursor-dnssec/runtests
tasks.py

- Use the MT variant for libfaketime, we are MT after all
- It is only needed for auth and LD_PRELOAD is set by the tests where it matters
- It interacts badly with libfstrm and tsan in the recursor
- No more separate run of the dnstap test is needed
I have:

rec: Rec regr vs libfaketime

---

pdns/recursordist/test-syncres_cc2.cc
pdns/syncres.cc

See https://datatracker.ietf.org/doc/html/rfc7871#section-7.4
Fixes #10994
(cherry picked from commit 2bcec14adbffbf4b28d698cb607877fb96054e87)
Backport of #11010 
I have:

rec: backport 11010 to rec-4.4.x: Do cache negcache results, even when wasVariable() is true

---

pdns/recursordist/test-syncres_cc2.cc
pdns/syncres.cc

See https://datatracker.ietf.org/doc/html/rfc7871#section-7.4
Fixes #10994
(cherry picked from commit 2bcec14adbffbf4b28d698cb607877fb96054e87)
Backport of #11010
I have:

rec: backport 10110 to rec-4.5.x: Do cache negcache results, even when wasVariable() is true

---

pdns/tcpiohandler.cc

We were not properly freeing the memory of TLS session tickets reused for outgoing TLS (DoT / DoH) connections.
Reported by Stéphane Bortzmeyer (many thanks!)
I have:

dnsdist: Fix a memory leak when reusing TLS tickets for outgoing connections

---

pdns/tcpiohandler.cc

In some configurations that we can't detect (PKCS11 support enabled, with a default PKCS11 trust store), GnuTLS from 3.7.0 to at least 3.7.2 leaks memory when validating a server certificate. The issue has been reported to GnuTLS and acknowledged, but there is no available fix yet.
I have:

dnsdist: Warn that GnuTLS 3.7.x leaks memory when validating certs

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist-nghttp2.cc
pdns/dnsdistdist/dnsdist-session-cache.cc
pdns/dnsdistdist/dnsdist-session-cache.hh
pdns/dnsdistdist/docs/reference/config.rst

Also dump the number of cached (active and idle) outgoing connections when a TCP or DoH state dump is requested.
I have:

dnsdist: Add a function to know how many TLS sessions are currently cached

---

pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc

Making it unusable from Lua FFI when dnsdist is compiled with `-fvisibility=hidden`.
Also fixes a g++/LTO warning about uninitialized dnsheaders in the unit tests.
I have:

dnsdist: Add missing visibility attribute on `dnsdist_ffi_dnsquestion_get_qname_hash`

---

.github/workflows/build-and-test-all.yml

There is a failure mode that if it hits makes almost all remaining test fail.  Symptom
is that the auths do not start up properly.
I have:

rec: Disable tsan regression runs for rec for now,

---

pdns/pdns_recursor.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/test_KeepOpenTCP.py

Use guard objects to do the TCP connection bookkeeping and cleanup if needed.
If a policy drop is to be handled for a TCP connection, do not answer that query, but do handle already in-flight queries and then close.
Fixes #11021 
I have:

Rec incoming tcp bookkeeping

---

pdns/dnsdistdist/dnsdist-healthchecks.cc
regression-tests.dnsdist/test_OutgoingTLS.py

This reduces the cost of the healthchecks themselves while saving the TLS session reduces the cost of opening of a DoT connection for actual queries later on.
In the future a refactoring of the TCP/DoT healthcheck code to be more like the "black box" approach used for DoH would be nice to have.
I have:

dnsdist: Reuse and save the TLS session tickets in DoT healthchecks

---

regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_RPZ.py
regression-tests.recursor-dnssec/test_RootNXTrust.py

Instead of having a fixed 1 or 2s delay, poll the TCP port to see
if rec or auth has started up in a semi-tight loop: a loop with a
small sleep.  For teardown we poll the wait status using poll() in
a similar loop.
I have:

rec: Regression tests: smarter and faster startup and teardown of auth and rec

---

builder-support/specs/pdns-recursor.spec
builder-support/specs/pdns.spec
m4/systemd.m4
pdns/Makefile.am
pdns/recursordist/Makefile.am

Should fix #10958 though I wonder if build time checks are proper for these systemd feature tests. Shouldn't these be install time checks in a perfect world?
I have:

Condition to HAVE_SYSTEMD_WITH_RUNTIME_DIR_ENV is reversed

---

builder-support/specs/pdns-recursor.spec
builder-support/specs/pdns.spec
m4/systemd.m4
pdns/Makefile.am
pdns/recursordist/Makefile.am

(cherry picked from commit fc1f6fb803e3ab7346f327b6113fc79eaa40abf2)
Backport of #10982 
I have:

rec: backport 10982 to rec-4.x.6: Condition to HAVE_SYSTEMD_WITH_RUNTIME_DIR_ENV is reversed

---

.github/workflows/build-and-test-all.yml

There is a failure mode that if it hits makes almost all remaining test fail.  Symptom
is that the auths do not start up properly.
(cherry picked from commit 2ef0d14bf39fafa45d39d5a0b5e8e5f263357d17)
Backport of #11038 
I have:

rec: backport 11038 to rec-4.6.x: Disable tsan regression runs for rec for now

---

pdns/dnsdistdist/docs/reference/config.rst

`setWebserverConfig()` accepts a 'customHeaders' key, and not a 'custom_headers' one. Also update the documentation for `webserver()` where it does not really matter so they are in sync.
I have:

dnsdist: Fix 'custom_headers' -> 'customHeaders' in the webserver doc

---

docs/secpoll.zone
pdns/recursordist/docs/changelog/4.6.rst

Prep for rec-4.6.0-rc1.
I wish we could say in the secpoll: superseded release, i.e. a status between 1 and 2: 
`X: recommended to upgrade` (but no security issue).
Or should we redefine status 2 to be: "Recommended upgrade for security or other reasons?
I have:

rec: Prep for rec-4.6.0-rc1

---

docs/common/secpoll.rst
docs/secpoll.zone

A proposal:
Slight change in the secpoll policy: status 2 is also issued for non-security related upgrade recommendations, but for pre-releases only. This is to nudge people into not running a pre-release version if a newer one is available.
Also add the policy to `secpoll.zone` itself.
If this is deemed a good thing, I'll update the secpoll records of pre-releases as well.
I have:

secpoll: for pre-releases, use status 2 when supserseded.

---

pdns/ws-auth.cc

Some people want to add domains to the zonecache as soon as possible. This is currently automatic when the zone is created using the API or autoprimary. For database-based provisioning systems this allows the provisioning system to add the zone by calling the /cache/flush endpoint.
This is #10617 without any cleanup, and adding the zone works only on the HTTP APIs cache flush endpoint. Nothing happens on the command line, etc.
I have:

Auth: add zone to zonecache on flush API endpoint

---

docs/upgrading.rst
pdns/pdnsutil.cc

Includes an upgrade note, but no manpage update, because nobody should be using SHA1 DSes.
I have:

pdnsutil: skip SHA1 DSes except in verbose mode, fixes #11045

---

pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
regression-tests.dnsdist/test_Spoofing.py

This prevent an allocation and a copy since we can now directly pass a Lua string.
Many thanks to @wojas for the suggestion!
I have:

dnsdist: Fix const-correctness of dnsdist_ffi_raw_value_t's value

---

Docker-README.md
Dockerfile-auth
Dockerfile-dnsdist
Dockerfile-recursor

The current Docker images are built with a dependency on the NET_BIND_SERVICE capability which used to be required for binding to a privileged port. This capability included in the image causes problems when trying to deploy the image on a Kubernetes platform with restrictive security policies in place (which is becoming the norm).
This pull request removes those dependencies and adds instructions to:
- Avoid these privileged ports (by binding to non-privileged ports)
- Add the NET_BIND_SERVICE capability to containers
I have:

Docker images: Remove capability requirements

---

pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc

(cherry picked from commit 6a948130b2406d0e3b295ec68f56b3b8ed302960)
I have:

rec: Backport 11069 to rec-4.6.x: Do not generate eventtrace records if no Lua hook is defined

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua.hh
pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-lua-ffi.hh
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_Responses.py

This adds `LimitTTLResponseAction()`, `SetMinTTLResponseAction()` and `SetMaxTTLResponseAction()` to limit returned TTL values to given boundaries.
I have:

dnsdist: add lua support to limit TTL values of responses

---

pdns/dnsdist-idstate.hh
pdns/dnsdist.cc
pdns/dnsdistdist/doh.cc
pdns/doh.hh

Introduced in 1.7.0, and only when a cross-protocol response to a DoH query is dropped by a rule.
I have:

dnsdist: Fix a double-free when a DoH cross-protocol response is dropped

---

pdns/nameserver.cc

Likely the `close(2)` will succeed and not change `errno`, but the idoim of not saving `errno` is wrong anyway.
I have:

auth: save errno value as close(2) might clobber it

---

.github/actions/spell-check/expect.txt
m4/pdns_check_network_libs.m4
pdns/dnsdist-console.cc
pdns/dnsdist-lua-bindings.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/iputils.cc
pdns/iputils.hh

This PR adds Lua bindings to retrieve the list of network interfaces and associated addresses, provided that `getifaddrs` is supported.
I tested this code on Linux, the documentation suggests that it should work on FreeBSD and OpenBSD as well but I did not test that.
I have:

dnsdist: Add Lua bindings to get the list of network interfaces, addresses

---

pdns/dnsdistdist/doh.cc

Backport of #11105 to rel/dnsdist-1.7.x.
(cherry picked from commit d0ae90801838ed9104051fa11fa577f3a96a9289)
I have:

dnsdist-1.7.x: Fix compilation without incoming DoH support

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-vars.cc
pdns/dnsdist-lua.hh
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/docs/reference/constants.rst
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_Spoofing.py

This adds the ability to set a completely self-generated raw answer from Lua
I have:

 dnsdist: add support to spoof a full self-generated response from lua

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/libssl.cc
pdns/libssl.hh
pdns/tcpiohandler.cc
regression-tests.dnsdist/dnsdisttests.py
regression-tests.dnsdist/runtests
regression-tests.dnsdist/test_DOH.py
regression-tests.dnsdist/test_TLS.py

This adds support for password protected PCKS12 files. `addDOHLocal` and `addTLSLocal` now accept either a single `cert` parameter (without any `key`) and thus try to open it as a PCKS12 file or directly a `TLSCertificate` object initialized via `newTLSCertificate`.
I have:

dnsdist: add support for password protected PCKS12 files for TLS configuration

---

pdns/dnsdistdist/doh.cc

When the UDP response to a DoH query was truncated, we re-send the query via TCP, passing it to a TCP worker. We need to edit the ID to its original value before that, and while there is no reason that the query is smaller than a dnsheader, we need to check its size, not the size of the response.
I have:

dnsdist: Check the size of the query when re-sending a DoH query

---

pdns/dnsmessage.proto
pdns/lua-recursor4-ffi.hh
pdns/lua-recursor4.cc
pdns/lua-recursor4.hh
pdns/pdns_recursor.cc
pdns/recursor_cache.cc
pdns/recursor_cache.hh
pdns/recursordist/rec-eventtrace.cc
pdns/recursordist/rec-eventtrace.hh
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_Lua.py

Initial stab at providing an ffi interface for postresolve.
Although I think this is already useful, this PR is mainly to solicit feedback.
The API likely need some extra tweaks and methods.
Many simple cases can be handled by `pdns_postresolve_ffi_handle_set_appliedpolicy_kind()` (custom is not available for that case, since it is really RPZ oriented)
It is also possible to modify existing records (content only), remove all records and add records.
Current methods:
```
typedef struct pdns_postresolve_ffi_handle pdns_postresolve_ffi_handle_t;
const char* pdns_postresolve_ffi_handle_get_qname(pdns_postresolve_ffi_handle_t* ref) __attribute__((visibility("default")));
void pdns_postresolve_ffi_handle_get_qname_raw(pdns_postresolve_ffi_handle_t* ref, const char** qname, size_t* qnameSize) …
```

rec: postresolve ffi

---

m4/pdns_with_libssl.m4
pdns/libssl.cc

Fix `missing SSL_CTX_use_cert_and_key` function on openssl version < 1.1.1 by disabling pkcs12 support
Introduced in https://github.com/PowerDNS/pdns/pull/11027
```
libssl.cc: In function 'std::unique_ptr<ssl_ctx_st, void (*)(ssl_ctx_st*)> libssl_init_server_context(const TLSConfig&, std::map<int, std::basic_string<char> >&)':
libssl.cc:809:82: error: 'sk_X509_free' was not declared in this scope
auto ca = std::unique_ptr<STACK_OF(X509), void(*)(STACK_OF(X509)*)>(captr, sk_X509_free);
^~~~~~~~~~~~
libssl.cc:811:11: error: 'SSL_CTX_use_cert_and_key' was not declared in this scope
if (SSL_CTX_use_cert_and_key(ctx.get(), cert.get(), key.get(), ca.get(), 1) != 1) {
^~~~~~~~~~~~~~~~~~~~~~~~
libssl.cc:811:11: note: suggested alternative: 'SSL_CTX_use_certificate'
if …
```

libssl: fix compilation issues on older openssl versions

---

build-scripts/gh-actions-setup-inv

After a long search documented in #11080 it turns out that the periodic (failing) starting of `pdns_server` by `systemd` interferes with starting the authoritative servers used in the recursor regression tests.
If you need a service running in a test, start it explicitly. At the moment only the SNMP daemon is needed, which was already (re)started in the test scripts.
Tested many times in my own repo without seeing any failure to start auths in the recursor regression tests. The failure was quite common without this.
I have:

github actions: Set policy to not start/enable services by default

---

m4/pdns_enable_ipcipher.m4
pdns/dnsdistdist/configure.ac

`ipcipher` support now defaults to `auto` instead of `yes`, so that we can build (or just run `make dist`) even if `libcrypto` is not available.
I have:

Properly handle ipcipher support when libcrypto is not available

---

pdns/packethandler.cc

"Should not get here" log message previously showed the QType as the numeric code, instead of the more common name (ex: instead of A, it showed 1).
I have:

auth: show QType by name in log message

---

pdns/dnsdist-dynblocks.hh

`d_warningRate` in this function will always be 0, as that's how it's initialized and it's never updated, so we need to check `d_warningRatio` instead to see if warnings are enabled.
This also adds some more tests of `d_enabled` as the correct short-circuit for when these are initialized with their zero-argument constructor.
Fixes #11131
I have:

Test correct member in DynBlockRatioRule::warningRatioExceeded

---

modules/bindbackend/bindbackend2.cc
modules/bindbackend/binddnssec.cc
modules/godbcbackend/sodbc.cc
pdns/backends/gsql/gsqlbackend.cc
pdns/resolver.cc

Removes never reachable `return <something>;` statements.
I have:

auth: remove dead return statements

---

.github/workflows/build-and-test-all.yml
pdns/pdns_recursor.cc
pdns/recursordist/recursor-tsan.supp
pdns/syncres.cc
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_ECS.py
regression-tests.recursor-dnssec/test_ExtendedErrors.py
regression-tests.recursor-dnssec/test_Lua.py
regression-tests.recursor-dnssec/test_Prometheus.py
regression-tests.recursor-dnssec/test_RoutingTag.py

Some modifications were needed to make tsan work for rec regression test:
- Update `numberOfDistributedQueries` only from the thread itself
- Do not `use boost::format` (it calls into locale handling code that does not seem to be thread-safe)
- Stop printing periodic stats (they are racey, but we do not care)
Survived a couple of test runs here.
I have:

rec: enable recursor regression tests using tsan

---

pdns/threadname.cc

https://man7.org/linux/man-pages/man3/pthread_setname_np.3.html
... The thread name is a
meaningful C language string, whose length is restricted to 16
characters, including the terminating null byte ('\0').
User reports:
> Could not set thread name pdns-r/ztc/rpz.urlhaus.abuse.ch. for thread: Numerical result out of range
the `pdns-r/ztc` is a really expensive prefix for a 15 char threadname, I'd personally suggest using `ztc:` instead, that'd give 6 chars to the thread name that are currently wasted.
I have:

Try shorter thread names

---

modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh

Duplicate domain-id's in the zone cache could trick imdb backend into serving records from the wrong zone.
I have:

auth: lmdb, check if the lookup name is part of the zone

---

pdns/axfr-retriever.cc
pdns/axfr-retriever.hh
pdns/epollmplexer.cc
pdns/kqueuemplexer.cc
pdns/mplexer.hh
pdns/pdns_recursor.cc
pdns/portsmplexer.cc

It was deprecated in 1.65.0: `This facility is deprecated because a shared_ptr to T[] or T[N] is now available, and is superior in every regard`.
As far as I can tell we never actually used the reference counting 'shared' feature anyway.
I have only partially tested this change, in particular I did not test the `ports` and `kqueue` multiplexers.
I have:

Stop using the deprecated boost::shared_array

---

regression-tests.recursor-dnssec/test_ExtendedErrors.py

This was prompted by a change in one of the external tests we do.
servfail.nl/AAAA should maybe return edns error code 9 (DNSKEY Missing), but it is not clear 1) if that is correct and 2) how to do that in the current code
I have:

rec: servfail.nl changed setup

---

pdns/dnsdist-dynblocks.hh

Backport of #11132 to rel/dnsdist-1.7.x.
I have:

dnsdist-1.7.x: Test correct member in DynBlockRatioRule::warningRatioExceeded

---

pdns/recursordist/docs/settings.rst

This wasn't around as of 4.0 - it landed in this file in 223bb49ef87feee34af9d1076b55bee81a38b8bc
but the removal notice was already included at that time.
I have:

doc: remove auth-can-lower-ttl

---

pdns/dnsdistdist/docs/guides/webserver.rst
pdns/dnsdistdist/docs/reference/config.rst
pdns/dnsdistdist/docs/rules-actions.rst

Several deprecated actions have been removed in e22209274a48fde28ab7cb256939ee65e5283bfa, along with the deprecated additional parameters to the `webserver` directive.
Closes #11149.
I have:

dnsdist: Document webserver and actions removals in 1.7.0

---

docs/.gitignore
pdns/auth-zonecache.cc
pdns/auth-zonecache.hh
pdns/test-auth-zonecache_cc.cc
pdns/test-ueberbackend_cc.cc
pdns/ws-auth.cc

This pull fixes:
- Removal of a zone via the api did not remove the zone from the zonecache.
- New zones did not show up in the stats until the next full refresh.
The ueberBackand zonecache tests are broken (never worked). The test itself is fixed but cannot function without getAllDomans() in SimpleBackend. Commented out the test for now.
I have:

Auth: add zone removal to the zone cache

---

ext/protozero/CHANGELOG.md
ext/protozero/include/protozero/buffer_string.hpp
ext/protozero/include/protozero/buffer_vector.hpp
ext/protozero/include/protozero/byteswap.hpp
ext/protozero/include/protozero/version.hpp

Changes:
- Fixes undefined behaviour in `float` and `double` byteswap.
- Add missing includes of "config.hpp".
- Avoid narrowing conversion by doing an explicit `static_cast`.
As far as I can tell these changes do not need to be backported.
I have:

Update protozero to 1.7.1

---

pdns/dnsdistdist/configure.ac

Not marking our symbols visible by default allows the compiler to do better optimizations, especially with Link-Time Optimizations that several distributions are now enabling by default.
The most obvious optimization comes from dead code removal because the compiler now knows that it cannot be used by an external shared object, but better inlining might also occur.
Even without LTO, it reduces the final size of stripped binaries and might improve loading times a bit.
Note that we already mark the symbols that we want to export with the 'default' visibilty, for example for Lua FFI.
I have:

dnsdist: Build with `-fvisibility=hidden` by default

---

pdns/dnsdist-rings.hh
pdns/dnsdistdist/test-dnsdistrings_cc.cc
pdns/misc.cc
pdns/misc.hh

This PR adds support for storing mac address of the requestor in query rings (only when compiled with `-DDNSDIST_RINGS_WITH_MACADDRESS`).
I have:

dnsdist: add support to store mac address in query rings

---

pdns/libssl.cc

OPENSSL_init_crypto(), added in 1.1.0, loads all available ciphers and digests by default. Since we only need the TLS-related ones, that only increases the startup time and the memory usage.
Before:
```
OPENSSL_INIT: ossl_init_base: Setting up stop handlers
OPENSSL_INIT: ossl_init_register_atexit()
OPENSSL_INIT: ossl_init_load_crypto_nodelete()
OPENSSL_INIT: openssl_config_int((null), (null), 50)
OPENSSL_INIT: ossl_init_engine_rdrand: engine_load_rdrand_int()
OPENSSL_INIT: ossl_init_thread_start: marking thread for err_state
OPENSSL_INIT: ossl_init_load_crypto_strings: err_load_crypto_strings_int()
OPENSSL_INIT: ossl_init_engine_dynamic: engine_load_dynamic_int()
OPENSSL_INIT: ossl_init_add_all_ciphers: openssl_add_all_ciphers_int()
OPENSSL_INIT: ossl_init_add_all_digests: …
```

libssl: Load only the ciphers and digests needed for TLS, not all of them

---

.github/actions/spell-check/expect.txt
docs/manpages/pdnsutil.1.rst
pdns/Makefile.am
pdns/dnsrecords.cc
pdns/dnsrecords.hh
pdns/dnssecinfra.cc
pdns/dnssecinfra.hh
pdns/pdnsutil.cc
pdns/qtype.cc
pdns/qtype.hh
pdns/sha.hh
pdns/test-dnsrecords_cc.cc
pdns/test-zonemd_cc.cc
pdns/zonemd.cc
pdns/zonemd.hh
regression-tests/zones/zonemd-allunsup.zone
regression-tests/zones/zonemd-duplicate.zone
regression-tests/zones/zonemd-invalid.zone
regression-tests/zones/zonemd-nozonemd.zone
regression-tests/zones/zonemd-serialmismatch.zone
regression-tests/zones/zonemd-sha512.zone
regression-tests/zones/zonemd-syntax.zone
regression-tests/zones/zonemd1.zone
regression-tests/zones/zonemd2.zone
regression-tests/zones/zonemd3.zone
regression-tests/zones/zonemd4.zone
regression-tests/zones/zonemd5.zone

1) Define record type
2) Verification according to RFC, including many failure cases and RSIG handling. Support sha384 and sha512
3) Unit tests, including all examples from RFC and a few failure cases.
4) Command line for pdnsutil: zonemd-verify-file
Based on POC from @Habbie, with many changes.
Things to be done I can think of (details to be decided):
For the Recursor: 
- validation of incoming zones (potentially Zone to Cache, RPZ, Auth-Zones). Those cases need to consider DNSSEC validation of ZONEMD records as well per RFC. Also config of zone should indicate if ZONEMD verification is required. For Zone to Cache and RPZ we can do that from Lua, for Auth Zones it is not immediately clear how.
For the Authoritative Server:
- verify/insert/update/remove ZONEMD in DB 
- send ZONEMD out on …

First part of ZONEMD support

---

pdns/dnsdist-rings.cc
pdns/dnsdist-rings.hh
pdns/dnsdist.cc
pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc
pdns/dnsdistdist/test-dnsdistrings_cc.cc

It is a bit cumbersome to have to call `Rings::init()` when we are ready, but it prevents allocating the default number of entries, 10k, which is quite a lot for small setups. Of course the memory was released once the configuration had been parsed, but it might be too late in some cases, and we would end up with a bigger reported memory usage than our actual one since heap shrinkage seldom happens.
I have:

dnsdist: Defer the actual allocation of the ring buffer entries

---

regression-tests.auth-py/requirements.txt
regression-tests.ixfrdist/requirements.txt

CI: dnspython 2.2.0 breaks auth and ixfrdist testing, pin to 2.1.0

---

regression-tests.auth-py/requirements.txt
regression-tests.ixfrdist/requirements.txt

auth-4.6.x: CI: dnspython 2.2.0 breaks auth and ixfrdist testing, pin to 2.1.0

---

regression-tests.auth-py/requirements.txt
regression-tests.ixfrdist/requirements.txt

auth-4.5.x: CI: dnspython 2.2.0 breaks auth and ixfrdist testing, pin to 2.1.0

---

pdns/dnsname.hh
pdns/dnssecinfra.hh
pdns/iputils.hh
pdns/misc.hh
pdns/zonemd.cc

It is no longer needed since the types can now be automatically deduced, has been deprecated in C++11 and removed in C++17.
Reported by @tjikkun after seeing the warnings on Fedora (thanks!).
I have:

Stop using the now deprecated and useless std::binary_function

---

pdns/dnsname.hh
pdns/dnssecinfra.hh
pdns/iputils.hh
pdns/misc.hh

It is no longer needed since the types can now be automatically
deduced, has been deprecated in C++11 and removed in C++17.
backport of #11197
I have:

auth-4.6.x: Stop using the now deprecated and useless std::binary_function

---

modules/lmdbbackend/lmdbbackend.cc
pdns/Makefile.am

This allows external software to detect when a database has been fully replaced.
I have:

auth lmdb: add a UUID to newly created databases

---

pdns/dnsdistdist/dnsdist-tcp-downstream.hh

The health-check timeout is in milliseconds, contrary to the other ones that are in seconds.
Fixes #11250.
I have:

dnsdist: Fix the health-check timeout for outgoing DoH connections

---

pdns/recursordist/test-syncres_cc6.cc
pdns/syncres.cc

For a /broken/ domain that returns a CNAME for a DS query, make sure we abort DS retrieval instead of going into a potential recursion that produces a ServFail.
Maybe the test can be simplified...
I have:

rec: a CNAME answer on DS query should abort DS retrieval

---

pdns/recursordist/test-syncres_cc8.cc
pdns/validate.cc

Ancestor NSEC(3)s have the SOA bit clear (delegation), and the remaining non-apex ones should not have the NS set.
I have:

rec: Reject non-apex NSEC(3)s that have both the NS and SOA bits set

---

.github/workflows/builder.yml
builder-support/dockerfiles/Dockerfile.target.centos-7
builder-support/dockerfiles/Dockerfile.target.centos-8
builder-support/dockerfiles/Dockerfile.target.el-7
builder-support/dockerfiles/Dockerfile.target.el-7-amd64
builder-support/dockerfiles/Dockerfile.target.el-8
builder-support/dockerfiles/Dockerfile.target.el-8-amd64
builder-support/dockerfiles/Dockerfile.target.el-8-arm64
builder-support/dockerfiles/Dockerfile.target.oraclelinux-8
builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-amd64
builder-support/dockerfiles/Dockerfile.target.oraclelinux-8-arm64

builder: migrate EL8 builds to oraclelinux, rename centos8 to el8 where possible

---

pdns/lwres.cc

Initialize isNew before calling a (potentially) exception throwing function. Reformat block in separate commit first.
Spotted by @rgacogne 
I have:

Rec: fix lwres isnew

---

pdns/recursordist/test-rec-zonetocache.cc

rec: Fix zone-to-cache test by properly initing trust anchors and dnssec mode

---

regression-tests.auth-py/requirements.txt
regression-tests.ixfrdist/requirements.txt

(cherry picked from commit 46a40ed033d64f58aa30013d7e68daa5b5e8d615)
I have:

rec: backport to rec-4.4.x: CI: dnspython 2.2.0 breaks auth and ixfrdist testing, pin to 2.1.0

---

regression-tests.auth-py/requirements.txt
regression-tests.ixfrdist/requirements.txt

(cherry picked from commit 46a40ed033d64f58aa30013d7e68daa5b5e8d615)
I have:

rec: backport to rec-4.5.x: CI: dnspython 2.2.0 breaks auth and ixfrdist testing, pin to 2.1.0

---

regression-tests.auth-py/requirements.txt
regression-tests.ixfrdist/requirements.txt

(cherry picked from commit 46a40ed033d64f58aa30013d7e68daa5b5e8d615)
I have:

rec: backport to rec-4.6.x: CI: dnspython 2.2.0 breaks auth and ixfrdist testing, pin to 2.1.0

---

regression-tests.recursor-dnssec/test_ExtendedErrors.py

I think in an ideal world we should return 9 (DNSSEC key missing) but I don't see a
easy way to do that at the moment.
(cherry picked from commit 2cd34ba5c565ee6bad368f577e34fa6d9519ab7d)
Backport of #11168
I have:

rec: backport 11168 to rec-4.6.x: servfail.nl changed their setup.

---

docs/lua-records/functions.rst

I could not figure out the behaviour from reading the existing text,
so it needed a rewrite.
I think the main issue with the original text is that it uses synonyms all over the place: `set` and `group`; `available`, `up` and `viable candidate`; `select` and `use`. This attempts to use only one term for one concept.
I have:

Rewrite the section defining the behaviour of urlup.

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdist.cc
pdns/dnsdistdist/docs/rules-actions.rst
regression-tests.dnsdist/test_Routing.py
regression-tests.dnsdist/test_RulesActions.py

It seems silly not being able to apply other rules after that one.
Could use a regression test.
I have:

dnsdist: Add a parameter to PoolAction to keep processing rules

---

regression-tests.auth-py/requirements.txt
regression-tests.ixfrdist/requirements.txt

auth-4.4.x: CI: dnspython 2.2.0 breaks auth and ixfrdist testing, pin to 2.1.0

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst

New Lua threads will no longer get started in 'client' and 'config check' modes, where they make little sense.
I have:

dnsdist: Do not execute 'newThread' in client or config check modes

---

pdns/recursordist/docs/settings.rst
pdns/recursordist/docs/upgrade.rst
pdns/recursordist/rec-main.cc
pdns/recursordist/test-syncres_cc.cc
pdns/reczones.cc
pdns/syncres.cc
pdns/syncres.hh

Disabling can be useful in special setups, e.g. if the root servers cannot be reached and you're forwarding all queries to another recursor. This PR then allows you to not have  to setup a fake root by setting `hint-file=no`.
This also make sure we use the right dnssec mode for processing hints
and changes a few log levels to Debug to be less verbose.
I do worry that people will disable root-hints processing when they should not and then come complaining that their recursor is broken... hence the draft status
I have:

rec: Allow disabling of processing the root hints

---

pdns/lua-base4.cc
pdns/lua-recursor4.cc
pdns/recursordist/contrib/powerdns-example-script.lua
pdns/recursordist/docs/lua-scripting/dq.rst
pdns/recursordist/docs/lua-scripting/hooks.rst
pdns/recursordist/docs/upgrade.rst

Address documentation issues with the old `pdns.DROP` method and warn if `rcode` is set to it in Lua hooks.
Also fix a few other cases of inconsistent style (and errors) in the example script.
Fixes #11287
I have:

Rec: document changes to policy.DROP better and warn on using the now unsupported way

---

pdns/lua-recursor4.cc
pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recursordist/docs/settings.rst
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/rec-taskqueue.cc
pdns/recursordist/rec-taskqueue.hh
pdns/recursordist/rec-tcp.cc
pdns/recursordist/taskqueue.cc
pdns/recursordist/taskqueue.hh
pdns/recursordist/test-syncres_cc.cc
pdns/syncres.hh
pdns/ws-recursor.cc

1. Refactor recursor thread code, `RecThreadInfo` becomes a proper class with methods.
2. Introduce a new thread: `taskThead`. This is a `recursorThread` that can be used for async task execution. Currently one, but in theory there could be more.
3. Use the new `taskThread` to execute the `Zone to Cache`code and the `taskQueue`. The `taskQueue` now has become shared data instead of a thread local one.
The `broadcastAccFucntion` does call the distributor, worker and the new `taskThread`, but skips the handler. This needs to be revisited. One of the questions is; should all the `recursorThreads` be included in stats gathering? ATM, handler is skipped, but it is not clear to me why, as the handler thread also does resolving work, e.g. to prime the root info so constributes to stat counts. I …

Rec: thread refactoring

---

docs/settings.rst
pdns/recursordist/docs/settings.rst

Fix some reStructuredText syntax, seems it is picky about the space in `.. foobar::`, so it's just rendered as "..foobar::" in some places in the docs.
I have:

docs: fix rst syntax

---

pdns/dnsdist-console.cc

I tested:
* `./configure --without-libedit CXXFLAGS='-DDISABLE_COMPLETION'`
* `./configure --without-libedit`
* `./configure`
all 3 built, and the third one had working completions.
I have:

dnsdist: fix building without libedit

---

pdns/pdns_recursor.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/rec-tcp.cc
pdns/syncres.hh

After the Lua context is recreated by a reload script, in-flight queries should still use the old one and not the new.
Fixes #11289
The Lua context used by the followCNAMERecords(), getFakeAAAARecords() and
getFakePTRRecords() functions should be validated. I have marked the spots
with XXX in this commit
I have:

rec: Use the Lua context stored in SyncRes when calling hooks.

---

pdns/rec-lua-conf.cc
pdns/recursordist/docs/lua-config/protobuf.rst

This allows symbolic names for e.g. QTypes. Use that in protobufServer() and
outgoingProtobufServer(). Will also be used for the upcoming additional records code.
I have:

Read the base Lua definitions into the Lua context for reading the Lua config

---

pdns/decafsigners.cc
pdns/pdnsutil.cc
pdns/sodiumsigners.cc

And do not implement non-implemented features with an empty body.
At least avoids the crash of #11325
I have:

Check return value of DNSCryptoKeyEngine::makeFromPEMString()

---

docs/backends/lmdb.rst

`lmdb-map-size` is accidentally called `lmdb-random-ids` in the header.
I have:

docs: Fix lmdb-map-size copy and paste mistake

---

pdns/dns_random.cc
pdns/dns_random.hh
pdns/dnsdist-idstate.hh
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/Makefile.am
pdns/dnsdistdist/dns_random.hh
pdns/dnsdistdist/dnsdist-backend.cc
pdns/dnsdistdist/dnsdist-healthchecks.cc
pdns/dnsdistdist/dnsdist-random.cc
pdns/dnsdistdist/dnsdist-random.hh
pdns/dnsdistdist/dnsdist-secpoll.cc
pdns/dnsdistdist/docs/guides/downstreams.rst
pdns/dnsdistdist/docs/quickstart.rst
pdns/dnsdistdist/docs/reference/tuning.rst
pdns/dnsdistdist/doh.cc
pdns/dnsdistdist/test-dnsdistlbpolicies_cc.cc

This PRs add two options that can be used to reduce the risk of UDP exchanges when the path between dnsdist and its backend is not trusted:
- `setRandomizedIdsOverUDP()` allows picking up a random ID
- `setRandomizedOutgoingSockets()` allows selecting a random outgoing socket if several are available, effectively improving the entropy of the source port.
I have:

dnsdist: Allow randomly selecting a backend UDP socket and query ID

---

pdns/dnsrecords.hh
pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/recursordist/docs/lua-config/additionals.rst
pdns/recursordist/docs/lua-config/index.rst
pdns/shuffle.cc
pdns/shuffle.hh
pdns/syncres.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/recursortests.py
regression-tests.recursor-dnssec/test_Additionals.py

This PR is a PoC of adding additional records to a result if wanted and relevant.
TODO
Currently we consume some Additional record types (name dependent on the corresponding Answer record) from auths and store them as non-auth in the record cache, but we never send any Additional record to the client.
With this PR, we can add Additionals for MX, NS, SRV, NAPTR, SVCB and HTTPS records. We have code per record type to determined the target name.
Additionally, there is a table that defines which qtypes to add for which answer records. The table also defines how to resolve the additional records.
The options are
- `Ignore` (do not add)
- `CacheOnly` look into the record cache add add if availabe
- `CacheOnlyRequireAuth` look into the record cache add add if availabe and authoritative
- …

Rec: add Additonal records to query results if appropriate

---

pdns/recursordist/stable-bloom.hh

Detected by `-fsanitize=undefined -fsanitize-minimal-runtime` on OpenBSD; no idea why the regular ubsan run we do on CI does not catch this.
I have:

rec: fix unaligned access is murmur hash code used by NOD

---

pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/test-dnsdisttcp_cc.cc

If an I/O error occurs while we are processing a XFR response whose first message has already been processed, and the proxy protocol is used between dnsdist and the backend, there is a use-after-free in the loop looking at the queries pending for that connection because the frontend might decide to terminate the connection to the backend, clearing the queries container, while we are the middle of loop.
```
==22972== Thread 3 dnsdist/tcpClie:
==22972== Invalid read of size 8
==22972==    at 0x6A725A: _M_next (hashtable_policy.h:282)
==22972==    by 0x6A725A: _M_incr (hashtable_policy.h:299)
==22972==    by 0x6A725A: operator++ (hashtable_policy.h:351)
==22972==    by 0x6A725A: TCPConnectionToBackend::handleIO(std::shared_ptr<TCPConnectionToBackend>&, timeval const&) …
```

dnsdist: Fix a use-after-free in case of a network error in the middle of a XFR query

---

pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/test-dnsdisttcp_cc.cc

Backport of #11334 to rel/dnsdist-1.7.x.
I have:

dnsdist-1.7.x: Fix a use-after-free in case of a network error in the middle of a XFR query

---

.clang-tidy.bugs
.clang-tidy.full
.gitignore

- Add some clangd/clang-tidy and compilation database files to `.gitignore`.
- Add different configuration files for `clang-tidy` (more information in the commit message).
Documentation about how to generate the compilation database and use `clangd` and
`clang-tidy` will come at a later point.
I have:

Clang-tidy config files

---

ext/lmdb-safe/lmdb-typed.cc
regression-tests/backends/lmdb-master

regression testing now happens with random IDs, except for HTTP API testing
I have:

auth lmdb random-ids: stop generating negative numbers

---

pdns/dns.hh
pdns/packetcache.hh
pdns/pdns_recursor.cc
pdns/recursordist/rec-tcp.cc

As the string holding the packet may be potentially unaligned wrt to int access.
I'm using a copy of the header, but the copy is only made if the passed in pointer is pointing to unaligned data.
Some day we should switch to `PacketBuffer` instead of `std::string` for packet data. The first is naturally aligned (it allocates using `new()` instead of the more complex way a `std::string` works) and has the nice feature of not initializing its buffer when (re)sizing.
I am not doing that now as it has tentacles all over the place including the packet cache code that is shared with auth. Also `PacketBuffer` is missing a few methods that the current code uses (e.g. `compare()`. This is all solvable, but now for now.
This was caught by using `-fsanitize=undefined -fsanitize-minimal-runtime` that …

rec: Introduce dnsheader_aligned: a helper class to access dnsheader data

---

pdns/recursordist/test-syncres_cc8.cc
pdns/validate.cc

rec: Backport 11225 to rec 4.6.x: Reject non-apex NSEC(3)s that have both the NS and SOA bits set 

---

pdns/recursordist/test-syncres_cc6.cc
pdns/syncres.cc

rec: Backport 11245 to rec 4.6.x: a CNAME answer on DS query should abort DS retrieval 

---

pdns/lua-base4.cc
pdns/lua-recursor4.cc

Backport of #11288
Once this is is, we have to adapt the docs in the main branch (settings and upgarde guide) to refer to the right version.
I have:

rec: Backport 11288 to rec 4.6.x: Log an error if pdns.DROP is used as rcode in Lua callbacks 

---

pdns/pdns_recursor.cc
regression-tests.recursor-dnssec/test_Lua.py

rec: Backport 11327 to rec 4.6.x: If we get NODATA on an AAAA in followCNAMERecords, try dns64

---

pdns/recursor_cache.cc
pdns/recursordist/rec-taskqueue.cc

Minimal backport of #11338 
I have:

rec: Backport of 11338 to rec-4.6.x: QType ADDR is supposed to be used internally only

---

pdns/dnsdistdist/docs/reference/svc.rst

fixes documentation of SVCParams alpn description.
"doh" is not a valid alpn value. it's likely a typo and meant to say "dot"
I have:

fix doc of SVCParams alpn description

---

pdns/recursordist/taskqueue.cc
pdns/syncres.cc

Otherwise we get bad interaction with QM, as newly discovered
delegation points are stored in the cache, but not seen the QM
algorithm. Might/should fix #11371.
I have:

rec: Be more careful using refresh mode only for the record asked.

---

pdns/syncres.cc

Git history shows this was converted wrongly when hardcoded values were replaced by enum values
I have:

rec: Distinguish between unreachable and timeout for throttling

---

pdns/dnsdist-lua-actions.cc
pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdist-lua-bindings.cc
pdns/dnsdist-lua-inspection.cc
pdns/dnsdist-lua-rules.cc
pdns/dnsdist-lua-vars.cc
pdns/dnsdist-lua.cc
pdns/dnsdist-lua.hh
pdns/dnsdistdist/dnsdist-lua-bindings-dnscrypt.cc
pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc
pdns/dnsdistdist/dnsdist-lua-bindings-protobuf.cc
pdns/dnsdistdist/dnsdist-lua-web.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.hh
pdns/dnsdistdist/doh.cc
pdns/doh.hh

That PR defines types for the mapping of Lua arrays and associative arrays to C++, improving readability and consistency:
```c++
template <class T> using LuaArray = std::vector<std::pair<int, T>>;
template <class T> using LuaAssociativeTable = std::unordered_map<std::string, T>;
template <class T> using LuaTypeOrArrayOf = boost::variant<T, LuaArray<T>>;
```
I have:

dnsdist: Define types for Lua arrays and associative arrays

---

pdns/misc.cc

Otherwise g++ 11.2.0 complains here:
```
misc.cc: In function ‘int makeIPv6sockaddr(const string&, sockaddr_in6*)’:
misc.cc:711:8: error: ‘optional’ is not a member of ‘std’
711 |   std::optional<uint16_t> port = std::nullopt;
|        ^~~~~~~~
misc.cc:61:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
```
I have:

dnsdist: Fix compilation by adding a missing <optional> include in misc.cc

---

.github/actions/spell-check/expect.txt
pdns/pdns_recursor.cc
pdns/rec-lua-conf.cc
pdns/rec-lua-conf.hh
pdns/rec_channel_rec.cc
pdns/recursordist/docs/lua-config/index.rst
pdns/recursordist/docs/lua-config/protobuf.rst
pdns/recursordist/docs/lua-config/proxymapping.rst
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/recursordist/rec-tcp.cc
pdns/syncres.hh
regression-tests.recursor-dnssec/test_Protobuf.py
regression-tests.recursor-dnssec/test_ProxyByTable.py

A way to internally used a mapped adres as the source address for a query.
I have:

Rec: proxy by table

---

pdns/rec_channel_rec.cc
pdns/rec_control.cc
pdns/recursordist/docs/appendices/internals.rst
pdns/recursordist/docs/manpages/rec_control.1.rst
pdns/recursordist/docs/settings.rst
pdns/recursordist/docs/upgrade.rst
pdns/recursordist/rec-main.cc
pdns/recursordist/test-syncres_cc.cc
pdns/recursordist/test-syncres_cc1.cc
pdns/syncres.cc
pdns/syncres.hh

When a non-auth NS set is replaced by an auth one, remember the non-auth one if it contains NS not in the auth set.
Use that NS set later as a fallback if resolving fails.
TODO:
Should fix #10594
I have:

rec: Remember parent NS set, to be able to fallback to it if needed

---

pdns/misc.hh

We can avoid extraneous checks when the min or max values of different int types are equal.
I have:

Checked int conversions: Avoid checks when boundary values are equal

---

docs/requirements.txt
pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

Jinja2 3.1.0 removed deprecated code that is still used by sphinx 1.8.x, and it looks like our custom sphinx extensions are not working with more recent versions of sphinx..
See:
and
```
```
I have:

docs: Pin jinja2 to < 3.1.0

---

pdns/misc.hh

Fix `checked_stoi` to not leave the `idx`/`pos` value uninitialized when the input string is empty.
I have:

`checked_stoi` fix: Don't leave `idx`/`pos` uninitialized when the input string is empty

---

docs/requirements.txt
pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

auth 4.4.x docs: Pin jinja2 to < 3.1.0

---

docs/requirements.txt
pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

auth-4.5.x docs: Pin jinja2 to < 3.1.0

---

docs/requirements.txt
pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

rec-4.4.x docs: Pin jinja2 to < 3.1.0

---

docs/requirements.txt
pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

rec-4.5.x docs: Pin jinja2 to < 3.1.0

---

docs/requirements.txt
pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

rec-4.6.x docs: Pin jinja2 to < 3.1.0

---

.gitattributes

On the right-hand side of:
https://github.com/powerdns/pdns/
you can see a chart like this:
This can be tuned with:
https://github.com/github/linguist/blob/master/docs/overrides.md#using-gitattributes
With this change, the matching files will be treated as `DNS Zone`, by default the are not [detectable](https://github.com/github/linguist/blob/master/docs/overrides.md#detectable) and thus will fall out of the Languages chart:
This change is currently live on https://github.com/jsoref/pdns:
I have:

Add linguist-language tag for dns zones

---

pdns/dnsdist.cc

When health-checking is disabled, or when a check delay longer than one second is used, there is no need to allocate a new multiplexer object every second.
The CPU gain here is not huge, but it might matter for low-end devices, as mentioned in #11422. Since most of the CPU usage here seems to be caused by our handling of UDP timeouts, where we scan `setMaxUDPOutstanding` [1] buckets every second, a much better improvement for these low-end devices can be reached on master by setting `setRandomizedIdsOverUDP(true)` [2], allowing us to only scan the buckets that are actually in use.
[1]: https://dnsdist.org/reference/tuning.html#setMaxUDPOutstanding
[2]: https://dnsdist.org/reference/tuning.html#setRandomizedIdsOverUDP
I have:

dnsdist: Only allocate the health-check mplexer when needed

---

docs/backends/lmdb.rst
ext/lmdb-safe/lmdb-safe.cc
ext/lmdb-safe/lmdb-safe.hh
ext/lmdb-safe/lmdb-typed.cc
ext/lmdb-safe/lmdb-typed.hh
modules/lmdbbackend/lmdbbackend.cc
modules/lmdbbackend/lmdbbackend.hh
pdns/Makefile.am
pdns/dnsdistdist/dnsdist-kvs.hh
pdns/dnsdistdist/test-dnsdistkvs_cc.cc
regression-tests.nobackend/lmdb-id-generation/command
regression-tests.nobackend/lmdb-id-generation/description
regression-tests.nobackend/lmdb-id-generation/expected_result
regression-tests/backends/lmdb-master

* UUID for LMDB database: #11241
* LMDB random ids: #11309, #11354
* configurable LMDB map size: #11328
* auth lmdb: default values for KeyDataDB members, thanks ubsan #11306 
I have:

auth-4.6.x: LMDB backports

---

regression-tests.recursor-dnssec/test_RPZIncomplete.py

Plus counts are different due to rpz loading changes in master.
I have:

rec: rec-4.4.x has no waitForTCPSocket in test code

---

pdns/mtasker.hh
pdns/mtasker_context.hh
pdns/mtasker_fcontext.cc
pdns/mtasker_ucontext.cc
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/statbag.hh
pdns/syncres.hh
pdns/webserver.hh
pdns/ws-auth.hh
pdns/ws-recursor.hh
pdns/zone2ldap.cc

One more step in the general rule: if a facility is available in `std`, stop using the `boost` equivalent.
The only remaining ref to `boost::function` is now in `yahttp`, but that is conditional on C++11, so we're clean.
As a side effect this fixes a memory leak reported by scanbuild when using a function object in `rec-main.cc`.
The memory leak itself seems to be deep inside the boost code.
This touches `mtasker`, so it is a bit scary. I did not test the `ucontext` case (and I wonder if we should keep on supporting it).
I have:

Switch from boost::function to std::function everywhere

---

.not-formatted
pdns/cachecleaner.hh
pdns/lwres.cc
pdns/pdns_recursor.cc
pdns/rec_channel_rec.cc
pdns/recpacketcache.cc
pdns/recpacketcache.hh
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-main.hh
pdns/syncres.cc
pdns/syncres.hh
pdns/test-recpacketcache_cc.cc

This PR changes the eviction policy for the packet cache. It requires less operations in the LRU list and spreads the cost of pruning the full cache by removing an item when an item is added to a full cache.
This makes the order of the PC cache now strictly LRU, with the reasoning that if a cache item is found to be expired, we are going to update it very soon as we only look for entry we are looking up for a client. If it is expired, a resolve will follow immediately. (no recursion desired is really an exception). So the existing method of moving it to the front will be followed by an move to the back very soon. We do keep moving it to the back of it is not expired.
So what this PR does is:
- Tell the PC its size, so that it can evict an item when an item is added to a full cache
- If we …

Rec: packet cache improvements

---

pdns/recursordist/rec-main.cc

parseACL() returns a nullptr when both options are set empty.
I have:

Prevent segfault with empty allow-from-file and allow-from options

---

pdns/ixfr.cc
regression-tests.auth-py/runtests
regression-tests.auth-py/test_XFRIncomplete.py
regression-tests.recursor-dnssec/test_RPZIncomplete.py

As we might break from the loop early, we need to check if the end SOA was seen after the loop.
Also make sure we detect end conditions for both AXFR and IXFR style properly, to avoid processing
data after the end marker.
This is PowerDNS Security Advisory 2022-01
I have:

ixfr: Fix a case where an incomplete read caused by network error might result in a truncated zone

---

pdns/rec_channel_rec.cc
pdns/recursordist/rec-main.cc
pdns/syncres.cc
pdns/syncres.hh

This moves the nsspeeds table to use a multi-index and become shared between threads. The multi-index is used to be able to purge without needing a full scan. Shared has the big advantage that all threads can use and update the speed info, which should make the mechanism more effective and avoid a lot of duplicate information.
But: this is a draft request, it needs tests with many thread to
- check if lock contention is an issue
- check if heap fragmentation with multiple threads doing allocations and de-allocations is an issue
The two points above might outweigh the benefits. If they do, we still can keep the multi-index part (and cheap pruning) and not use the shared part.
This also changes the format of the dump-nsspeeds command: the 2nd column now has the timestamp and the columns are …

rec: Use boost::mult-index for nsspeed table and make it shared.

---

.github/workflows/codeql-analysis.yml

rel/auth-4.4x uses a different config setup (without prod name) which seems to confuse CodeQL
This one is a backport of the master branch setup.
I have:

auth-4.4.x: Unify CodeQL config between branches

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdist.cc
pdns/dnsdistdist/docs/reference/config.rst

Partially implemented #9994
I have:

dnsdist: Add setTCPFastOpenKey()

---

docs/changelog/4.5.rst
docs/guides/svcb.rst
docs/settings.rst

I stumbled upon the [`svc-autohints` guide](https://doc.powerdns.com/authoritative/guides/svcb.html#svc-autohints) (probably via IRC) and went to test it out, but instead I got some error.
As it turns out, this isn't included in my version (4.4.1 from Debian 11) but is 4.5.0 as part of #10074, for which the changelog entry didn't mention this.
(Thanks Habbie for pointing out the version and PR before I could finish digging through the `git blame`)
I have:

Document which version adds svc-autohints

---

pdns/recursordist/docs/lua-config/additionals.rst
pdns/syncres.cc
pdns/syncres.hh

This was left unimplemented in the initial PR.
If a task is pushed, I mark the triggering question as variable, so the result is not inserted into the packet cache. Once the additional records are retrieved (or absence is determined) no tasks are pushed and answer will be inserted into the PC. 
This mechanism has to be evaluated critically, as a additional records with low TTLs now often prevent caching the main answer in the PC as those low TTL record cause new tasks to be pushed often. So I'm actually not sure if this mechanism is effective, especially given the trend of lower and lower TTLs (e.g. check microsoft.com or any domain that hosts their mail with MS)
I have:

Rec: add deferred mode for additional records

---

pdns/devpollmplexer.cc
pdns/epollmplexer.cc
pdns/kqueuemplexer.cc
pdns/mplexer.hh
pdns/pollmplexer.cc
pdns/portsmplexer.cc
pdns/recursordist/rec-main.cc
pdns/test-mplexer.cc

This allows indicating the maximum number of events we want to process in a single run, which is usually bounded by the number of file descriptors we are planning on watching.
The default is still 1024 events, but this change makes it possible to allocate a smaller vector of events to reduce the memory usage when we know we are going to need to process so many events in a single run.
As usual for code that touches to our multiplexer, I unfortunately do not have the platforms needed to test /dev/poll, kqueue and ports at hand, so I would appreciate any feedback, as well as a good review :)
I have:

Multiplexer: Take the maximum number of events as a hint

---

pdns/dnsdist-lua-bindings.cc
pdns/dnsdistdist/docs/advanced/ebpf.rst
pdns/dnsdistdist/docs/reference/ebpf.rst

Allowing the use of `BPFFilter::attachToAllBinds()` at configuration time will result in ambiguous semantics.
In fact, using `BPFFilter::attachToAllBinds()` at configuration may not take effect.
Reject the use of `BPFFilter::attachToAllBinds()` at configuration time will prevent misuse.
I have:

Reject BPFFilter::attachToAllBinds() at configuration time

---

pdns/rec_channel_rec.cc
pdns/rec_control.cc
pdns/recursordist/docs/manpages/rec_control.1.rst
pdns/recursordist/docs/settings.rst
pdns/recursordist/rec-main.cc
pdns/recursordist/rec-taskqueue.cc
pdns/recursordist/rec-taskqueue.hh
pdns/recursordist/taskqueue.cc
pdns/recursordist/taskqueue.hh
pdns/syncres.cc
pdns/syncres.hh

Creating this PR so other can play wit this. I don't think this is production ready!
This implements an experimental approach to probe nameservers for DoT support and start using DoT to those if it works. Probing is done by a separate task. Until that task comes with a conclusion, the IP will be contacted in the regular way.
Enable by setting `max-busy-dot-probes` to a value > 0. Default is 0.
The `max-busy-dot-probes` number says how many async tasks can be scheduled doing DoT probes concurrently.
The tasks have to compete with other tasks to be done, so it may take a while for it to be executed. Until then the map entry is in state `Busy`. If the task sees it supports DoT, the entry becomes `Good`, otherwise `Bad`.
If there are too may Busy tasks, no new task will be scheduled. This is …

Rec: probe auth for DoT support

---

pdns/dnsdist-rings.hh
pdns/dnsdist-tcp.cc
pdns/dnsdist.cc
pdns/dnsdist.hh
pdns/dnsdistdist/configure.ac
pdns/dnsdistdist/dnsdist-lua-ffi-interface.h
pdns/dnsdistdist/dnsdist-lua-ffi.cc
pdns/dnsdistdist/dnsdist-lua-ffi.hh
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/test-connectionmanagement_hh.cc
pdns/test-credentials_cc.cc

This PR contains a bunch of small cleanups for dnsdist, most of these straightforward ones.
The only controversial one being the decision to revert the `time_t` check for dnsdist, which I believe makes sense because:
- dnsdist does not deal with signatures, and therefore is less sensitive to time issues than the auth or the rec
- it is more and more often deployed on embedded devices were this will still be an issue for some time, until a 64-bit `time_t` becomes available, and it seems silly to just prevent using dnsdist there. In fact we are seeing downstream maintainers removing that check, which is probably a good indication that it is more a hindrance than anything else. 
I have:

dnsdist: Bunch of small cleanups

---

pdns/pdns_recursor.cc
pdns/recursordist/rec-main.cc

Writing a pointer though a pipe and freeing it in the pipe reader is not something that Coverity understands.
Writing a model seems much more work, so lets see if these annotation reduce the false positives wrt these leaks.
But even if they don't work as expected, they provide valuable information to a reader of the code IMO.
I have:

rec: Add coverity annotations for a leak false positives

---

pdns/dolog.hh
pdns/proxy-protocol.cc

- Avoid a reallocation if the initial allocation of the proxy header is too small to host the remaining content
- When syslog logging is enabled, we do not need to allocate two strings with the same content to log to syslog and stdout
I have:

dnsdist: Prevent allocations in two corner cases 

---

pdns/recursordist/docs/appendices/FAQ.rst
pdns/recursordist/docs/settings.rst
pdns/recursordist/rec-main.cc

and shortening he interval on failure.
The original  code has a fixed 2 hours interval. That was changed to be `max-cache-ttl/12`. But now that we have an easy way to do an adaptive interval that is much preferable.
I have:

rec: Adaptive root refresh interval, normally at 80% of max-cache-ttl

---

docs/requirements.txt
pdns/dnsdistdist/docs/requirements.txt
pdns/recursordist/docs/requirements.txt

Backport of #11449 to rel/dnsdist-1.7.x
See:
and
```
```
I have:

dnsdist-1.7.x: Pin jinja2 to < 3.1.0

---

pdns/bpf-filter.cc
pdns/bpf-filter.hh
pdns/dnsdist-lua-bindings.cc
pdns/dnsdistdist/docs/advanced/ebpf.rst
pdns/dnsdistdist/docs/reference/ebpf.rst

As discussed in #11526.
It is necessary to combine the parameters in `newBPFFilter` into a table.
I have:

Merge multiple parameters in newBPFFilter

---

pdns/syncres.cc

Without this, probed DoT actually becomes regular TCP.
I have:

Fix DoT port, as noted by ph1 on IRC

---

.circleci/config.yml

This should unbreak docs building in CircleCI.
I have:

circleci: revert docs build to specific debian image, instead of the debian:testing underlying the texlive image

---

pdns/dnsdist-tcp.cc
pdns/dnsdistdist/doh.cc

dnsdist: Use the correct outgoing protocol in our ring buffers

---

pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst

dnsdist: Add a 'getAddressAndPort()' method to DOHFrontend and TLSFrontend objects

---

pdns/dnsdist.cc
pdns/dnsdistdist/dnsdist-dynblocks.cc
pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc

When the DynBlock rule does not set a specific action we use the default one, set with `setDynBlocksAction()`, so we should follow the same logic when determining whether to insert an eBPF block.
Fixes #11504.
I have:

dnsdist: Properly use eBPF when the DynBlock is not set

---

pdns/bpf-filter.cc

dnsdist: Fix wrong eBPF values (qtype, counter) being inserted for qnames

---

pdns/dnsdist.cc
pdns/dnsdistdist/dnsdist-dynblocks.cc
pdns/dnsdistdist/test-dnsdistdynblocks_hh.cc

When the DynBlock rule does not set a specific action we use the default one, set with `setDynBlocksAction()`, so we should follow the same logic when determining whether to insert an eBPF block.
(cherry picked from commit 8742251acdcce8cd27d859595e5e30cecfa4e4ab)
Backport of #11544 to rel/dnsdist-1.7.x.
I have:

dnsdist-1.7.x: Properly use eBPF when the DynBlock is not set

---

m4/pdns_with_libdecaf.m4
pdns/Makefile.am
pdns/dnsdistdist/Makefile.am
pdns/recursordist/Makefile.am
tasks.py

This adds a few things:
- Passing a user-defined header location through LIBDECAF_CFLAGS=-I...
- Otherwise, check the following directories for decaf.hxx:
- /usr/include
- /usr/include/decaf
- Add whichever one is picked to LIBDECAF_CFLAGS
- Then AC_CHECK_HEADER decaf.hxx using CXXFLAGS with LIBDECAF_CFLAGS
The reason for this change is that some package systems have decaf.hxx under /usr/include and others have it under /usr/include/decaf.
I have:

Try harder to find libdecaf headers

---

pdns/Makefile.am
pdns/decafsigners.cc
pdns/dnssecinfra.cc
pdns/opensslsigners.cc
pdns/sodiumsigners.cc
pdns/test-signers.cc

Support PEM import and export of EdDSA keys. There are two implementations:
- OpenSSL, which supports both Ed25519 and Ed448.
- Sodium, which only supports Ed25519 and depends on OpenSSL for PEM de/serialization.
- Libdecaf, which supports both Ed25519 and Ed448 and depends on OpenSSL for PEM de/serialization.
I have:

Support PEM import and export of EdDSA keys

---

pdns/dnsdist-console.cc

Otherwise one cannot know whether the server has closed the connection or sent a too large message.
Also wrap the console's socket descriptors in FDWrapper objects to make sure we do not forget to close them in the future, doing that manually is always brittle.
Closes #11488 
I have:

dnsdist: Log when a console message exceeds the maximum size

---

pdns/dnsdistdist/docs/reference/ebpf.rst

dnsdist: fix wrong parameter type in document
I have:

dnsdist: fix wrong parameter type in document

---

pdns/decafsigners.cc
pdns/dnssecinfra.cc
pdns/opensslsigners.cc
pdns/sodiumsigners.cc
pdns/test-signers.cc

This cleans up and refactors signers tests (`test-signers.cc`):
- Uses the boost test fixtures, and avoids a bit of duplication with `#ifdef`s.
- Adds some logging (using `--log_level=message`) to print which algorithms and their implementations are available.
- Integrates the testing of `ed448` into the generic signer testing mechanism.
- Adds the PEM import/export tests for `ed448`.
I have:

Refactor signers tests

---

pdns/dnsdistdist/dnsdist-backend.cc

As suggested by @hhoffstaette in #11576, this should significantly reduce the load on dnsdist setups that are mostly idle.
I have:

dnsdist: Scan the UDP buckets only when we have outstanding queries

---

pdns/signingpipe.cc

The spot where the warning happens changed, plus appease clang-tidy.
I have:

auth: Tweak for Coverity 1488422

---

pdns/rec_channel_rec.cc
pdns/recursordist/docs/upgrade.rst
pdns/recursordist/rec-main.cc
pdns/syncres.cc
pdns/syncres.hh

Move throttle map from a thread local to shared. This map is only consulted when going auth on the net. Information collected by a thread is useful to other threads to avoid double work finding out an auth needs to be throttled.
I have:

Rec: shared throttle map

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst

And also from the configuration, without having to edit the arguments passed to the program.
I have:

dnsdist: Add setVerbose() to switch the verbose mode at runtime

---

pdns/dnsdist-tcp.cc
pdns/dnsdistdist/dnsdist-tcp-downstream.cc
pdns/dnsdistdist/dnsdist-tcp.hh
pdns/dnsdistdist/doh.cc
regression-tests.dnsdist/dnsdistdohtests.py
regression-tests.dnsdist/test_DOH.py
regression-tests.dnsdist/test_ProxyProtocol.py

dnsdist forwards incoming DoH queries to its backend over UDP, and retry over TCP if the response is truncated (TC=1).
When the proxy protocol is used between dnsdist and its backend, the second query, over TCP, needs to take into account that the proxy protocol payload has already been handled. This was not properly done in that exact case because the proxy protocol payload length was not propagated to the code handling the TCP communication, leading to the query ID being edited at the wrong offset in the packet and thus to an invalid proxy protocol payload.
I have:

dnsdist: Fix invalid proxy protocol payload on a DoH TC to TCP retry

---

pdns/dnsdistdist/doh.cc
regression-tests.dnsdist/test_ProxyProtocol.py

Passing an IPv6 address in the X-Forwarded-For header of an DoH frontend listening on a IPv4 address, with a proxy-protocol-enabled backend, results in dnsdist trying to mix IPv4 and IPv6 in the same proxy protocol payload which is not possible. The resulting exception was not properly handled and left a dangling UDP state, whose DOHUnit pointer was no longer valid, causing a use-after-free when dnsdist processed the dangling UDP state while checking for timeouts.
<strike>This PR is based on #11604 as it reused the same mechanism for the regression test, so it will have to be rebased after the base PR has been merged.</strike>
I have:

dnsdist: Fix a crash on a invalid protocol in DoH forwarded-for header

---

pdns/zonemd.hh

Zap binary function, not needed and deprecated in c++11, removed in c++17

---

pdns/recursordist/docs/settings.rst
pdns/ws-recursor.cc
regression-tests.api/test_RecursorConfig.py

Current API code to set/retrieve this does not handle the empty case correctly.
I have:

Rec: api allow empty allow-from

---

pdns/dnsdist-lua-bindings-dnsquestion.cc
pdns/dnsdistdist/docs/reference/dq.rst
regression-tests.dnsdist/test_RulesActions.py

dnsdist: Add Lua bindings to access the DNS payload as a string

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua.cc
pdns/dnsdistdist/docs/reference/config.rst

This allows Lua code to entirely skip verbose log calls if verbose logging is disabled.
I have:

dnsdist: add getVerbose() function

---

.github/workflows/codeql-analysis.yml

This might fix the occasional build issues with the CodeQL GH Action.
(cherry picked from commit d6b94fbd9664a7acac00f5dd8ebbacc4119ed045)
Backport of #11570 
I have:

rec: Backport 11570 Reduce make -j parameter from 8 to 4, as dnsdist does.

---

pdns/recursordist/docs/settings.rst
pdns/ws-recursor.cc
regression-tests.api/test_RecursorConfig.py

rec: Backport 11609 to rec 4.7.x: Fix API issue when asking config values for allow-from or allow-notiy-from

---

pdns/dnsdist-console.cc
pdns/dnsdist-lua-bindings.cc
pdns/dnsdistdist/docs/reference/config.rst
pdns/misc.cc

The existing implementation used /proc/net/arp which only contains MAC addresses for IPv4 addresses. Switching to netlink provides support for IPv6 addresses as well, and roughly the same performance (it seems a tiny bit faster but the difference is in the error margin).
<strike>This is just a draft as the code could be prettier, don't merge this just yet!</strike>
I have:

dnsdist: Support link-level address retrieval for IPv6 as well

---

pdns/misc.cc

It is perfectly valid to pass a buffer larger than a link-level address, and we should not fail when that happens.
I have:

dnsdist: Accept large buffers in getMACAddress()

---

pdns/arguments.cc

(cherry picked from commit 7e32a0b96df460abd8fb98fbb63f4d336b9c3d03)
Backport of #11644
I have:

rec: Backport 11644 to rec-4.7.x: Deprecation warning for XPF settings.

---

pdns/dnsdist-cache.cc
pdns/dnsdist-cache.hh
pdns/dnsdist-carbon.cc
pdns/dnsdist-web.cc
pdns/dnsdistdist/dnsdist-lua-bindings-packetcache.cc

This adds a cache cleanup counter for dnsdist.
I have:

dnsdist: add a counter for the number of cache cleanups

---

pdns/recursordist/rec-main.cc

"time**s**outs" typo. Introduced in #11654.
I have:

rec: Fix typo in stats log message
